/**
 * Grade 3 · Module 2 — Place value through metric measurement.
 * Written to docs/new-flow/AUTHORING.md. Not yet founder-reviewed.
 */
import type { Lesson, Picture } from '../script'

/** A number line of clock times: one tick every 5 minutes, a time label every 10. `from`/`to` are minutes after `h`:00. */
const timeline = (h: number, from: number, to: number, extra: Partial<Extract<Picture, { kind: 'numline' }>> = {}): Picture => ({
  kind: 'numline', min: from, max: to, ticks: (to - from) / 5,
  labels: Array.from({ length: (to - from) / 5 + 1 }, (_, i) => {
    const m = from + i * 5
    return m % 10 ? null : `${((h - 1 + Math.floor(m / 60)) % 12) + 1}:${String(m % 60).padStart(2, '0')}`
  }),
  ...extra,
})

const gramScale = (value: number | null, max = 1000, step = 100, labelEvery = 200): Picture =>
  ({ kind: 'measure', tool: 'scale', max, step, labelEvery, value, unit: 'grams' })
const kgScale = (value: number | null, max: number, step: number, labelEvery: number): Picture =>
  ({ kind: 'measure', tool: 'scale', max, step, labelEvery, value, unit: 'kilograms' })
const mlJug = (value: number | null, max = 1000, step = 100, labelEvery = 200): Picture =>
  ({ kind: 'measure', tool: 'jug', max, step, labelEvery, value, unit: 'milliliters' })
const literJug = (value: number | null, max: number, step: number, labelEvery: number): Picture =>
  ({ kind: 'measure', tool: 'jug', max, step, labelEvery, value, unit: 'liters' })

const between = (min: number, max: number, at: number): Picture =>
  ({ kind: 'numline', min, max, ticks: 10, labels: 'none', points: [{ at, label: String(at) }] })
const add = (a: string, b: string): Picture => ({ kind: 'columns', rows: [a, b], op: '+', places: ['H', 'T', 'O'], answer: null })
const sub = (a: string, b: string): Picture => ({ kind: 'columns', rows: [a, b], op: '−', places: ['H', 'T', 'O'], answer: null })

export const G3M2: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m2-t1', title: 'Read the clock to 5 minutes', skill: 'Tell time to the nearest 5 minutes',
    bigIdea: 'The long hand counts by 5s. Each number on the clock is 5 more minutes.',
    screens: [
      { title: 'When does the show start?', text: 'Your show starts at the time on this clock. What time is it?',
        pictures: [{ kind: 'clock', h: 4, m: 15 }] },
      { title: 'The numbers are not the minutes', text: 'Look where the long hand is pointing. Right at the 3. Now, careful here. That does not mean 3 minutes. Those big numbers count the hours. They never count the minutes.',
        beats: [
          { say: 'Look where the long hand is pointing. Right at the 3.', pic: 0 },
          { say: 'Now, careful here. That does not mean 3 minutes.', write: 'not 3 minutes' },
          { say: 'Those big numbers count the hours. They never count the minutes.' },
        ],
        pictures: [{ kind: 'clock', h: 4, m: 15 }] },
      { title: 'The big idea', text: 'The long hand counts by 5s. Each number on the clock is 5 more minutes.',
        pictures: [{ kind: 'clock', h: 4, m: 15, fives: true }] },
      { title: 'Read the short hand first', text: "Let's start with the short hand. It is just past the 4, and it has not reached the 5 yet. So the hour is 4. I'll write that down.",
        beats: [
          { say: "Let's start with the short hand.", pic: 0 },
          { say: 'It is just past the 4, and it has not reached the 5 yet.' },
          { say: "So the hour is 4. I'll write that down.", write: 'Hour: 4' },
        ],
        pictures: [{ kind: 'clock', h: 4, m: 15 }] },
      { title: 'Count by 5s', text: 'Now the long hand. Start at the top and count by 5s. Five, ten, fifteen. Stop at the long hand. That is 15 minutes.',
        beats: [
          { say: 'Now the long hand. Start at the top and count by 5s.', pic: 0 },
          { say: 'Five, ten, fifteen. Stop at the long hand.', pic: 1 },
          { say: 'That is 15 minutes.', write: 'Minutes: 15' },
        ],
        pictures: [{ kind: 'clock', h: 4, m: 15, fives: true }, { kind: 'table', head: ['Long hand on', 'Minutes'], rows: [['1', '5'], ['2', '10'], ['3', '15']], motion: true }] },
      { title: 'Put it together', text: 'So we have hour 4, and 15 minutes. We write the hour first, then two dots, then the minutes. Say it out loud with me: four fifteen.',
        beats: [
          { say: 'So we have hour 4, and 15 minutes.' },
          { say: 'We write the hour first, then two dots, then the minutes.', pic: 0 },
          { say: 'Say it out loud with me: four fifteen.' },
        ],
        pictures: [{ kind: 'eq', text: '4:15' }] },
      { title: 'One thing not to do', text: "Here is the mix-up almost everybody makes. Do not write down the number the long hand is pointing at. The long hand on the 3 means 15 minutes, not 3.",
        beats: [
          { say: 'Here is the mix-up almost everybody makes.' },
          { say: 'Do not write down the number the long hand is pointing at.', pic: 0 },
          { say: 'The long hand on the 3 means 15 minutes, not 3.' },
        ],
        pictures: [{ kind: 'cards', wrong: '4:03', right: '4:15' }] },
    ],
    turn: {
      text: 'What time does this clock show?', picture: { kind: 'clock', h: 2, m: 25 },
      answer: { time: [2, 25] }, steps: ['The short hand is just past the 2, so the hour is 2.', 'The long hand is on the 5. Count by 5s: 5, 10, 15, 20, 25.', 'It is 2:25.'],
      prompt: 'Read the short hand for the hour. Count by 5s for the minutes.',
      hint1: 'Which number is the short hand just past?',
      hint2: 'The long hand is on the 5. Count by 5s five times.',
      twin: { text: 'What time does this clock show?', picture: { kind: 'clock', h: 9, m: 40 },
        answer: { time: [9, 40] }, steps: ['The short hand is past the 9, so the hour is 9.', 'The long hand is on the 8. Count by 5s eight times: 40.', 'It is 9:40.'],
        hint1: 'Which number is the short hand just past?', hint2: 'The long hand is on the 8. Count by 5s eight times.' },
    },
    won: { text: 'You found the hour, then counted by 5s.', sticker: 'The long hand is the minute hand. It counts by 5s.' },
    twinWon: { text: 'You found the hour, then counted by 5s to 40.', sticker: 'The long hand is the minute hand. It counts by 5s.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What time is it?', picture: { kind: 'clock', h: 6, m: 10 }, answer: { time: [6, 10] },
        steps: ['The short hand is just past the 6, so the hour is 6.', 'The long hand is on the 2. Count by 5s: 5, 10.', 'It is 6:10.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What time is it?', picture: { kind: 'clock', h: 3, m: 35 }, answer: { time: [3, 35] },
        steps: ['The short hand is past the 3, so the hour is 3.', 'The long hand is on the 7. Count by 5s seven times: 35.', 'It is 3:35.'] } },
      { why: 'Still "count by 5s"', problem: { text: 'What time is it?', picture: { kind: 'clock', h: 11, m: 50 }, answer: { time: [11, 50] },
        steps: ['The short hand is past the 11, so the hour is 11.', 'The long hand is on the 10. Count by 5s ten times: 50.', 'It is 11:50.'] } },
      { why: 'A little harder', problem: { text: 'What time is it? Look closely at the short hand.', picture: { kind: 'clock', h: 4, m: 55 }, answer: { time: [4, 55] },
        steps: ['The short hand is almost on the 5. It has not reached it, so the hour is still 4.', 'The long hand is on the 11. Count by 5s eleven times: 55.', 'It is 4:55.'] } },
      { why: 'Same math in a story', problem: { text: 'Mia starts reading when the clock shows this. What time does she start?', picture: { kind: 'clock', h: 7, m: 20 }, answer: { time: [7, 20] },
        steps: ['The short hand is just past the 7, so the hour is 7.', 'The long hand is on the 4. Count by 5s: 5, 10, 15, 20.', 'She starts at 7:20.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m2-t2', title: 'Read the clock to 1 minute', skill: 'Tell time to the nearest minute',
    bigIdea: 'Count by 5s to the last number the long hand passed. Then count on by 1s for the little marks.',
    screens: [
      { title: 'When does the bus come?', text: 'The bus comes when the clock looks like this. What time is it?',
        pictures: [{ kind: 'clock', h: 3, m: 27 }] },
      { title: 'The long hand is between numbers', text: 'The long hand is not on a number. It is between the 5 and the 6. Counting by 5s alone will not get there.',
        pictures: [{ kind: 'clock', h: 3, m: 27 }] },
      { title: 'The big idea', text: 'Count by 5s to the last number the long hand passed. Then count on by 1s for the little marks.',
        pictures: [{ kind: 'clock', h: 3, m: 27, fives: true }] },
      { title: 'Hour first, then 5s', text: 'The short hand is just past the 3, so the hour is 3. The long hand has passed the 5. Count by 5s to the 5: 5, 10, 15, 20, 25.',
        pictures: [{ kind: 'clock', h: 3, m: 27, fives: true }] },
      { title: 'Count on by 1s', text: 'Each little mark is 1 more minute. From 25, count the little marks: 26, 27.',
        pictures: [{ kind: 'clock', h: 3, m: 27, fives: true }, { kind: 'table', head: ['Count', 'Minutes'], rows: [['by 5s to the 5', '25'], ['1 more mark', '26'], ['1 more mark', '27']], motion: true }] },
      { title: 'Put it together', text: 'Hour 3, 27 minutes. We write 3:27.',
        pictures: [{ kind: 'eq', text: '3:27' }] },
      { title: 'One thing not to do', text: "Don't stop at the number before the long hand. Stopping at 25 leaves out the 2 little marks.",
        pictures: [{ kind: 'cards', wrong: '3:25', right: '3:27' }] },
    ],
    turn: {
      text: 'What time does this clock show?', picture: { kind: 'clock', h: 8, m: 17 },
      answer: { time: [8, 17] }, steps: ['The short hand is just past the 8, so the hour is 8.', 'The long hand has passed the 3. Count by 5s to the 3: 5, 10, 15.', 'Count on 2 little marks: 16, 17.', 'It is 8:17.'],
      prompt: 'Find the hour. Count by 5s, then count on by 1s.',
      hint1: 'Which number has the long hand just passed?',
      hint2: 'Count by 5s to the 3. Then count the little marks one at a time.',
      twin: { text: 'What time does this clock show?', picture: { kind: 'clock', h: 5, m: 38 },
        answer: { time: [5, 38] }, steps: ['The short hand is past the 5, so the hour is 5.', 'The long hand has passed the 7. Count by 5s to the 7: 35.', 'Count on 3 little marks: 36, 37, 38.', 'It is 5:38.'],
        hint1: 'Which number has the long hand just passed?', hint2: 'Count by 5s to the 7. Then count the little marks one at a time.' },
    },
    won: { text: 'You counted by 5s, then by 1s, to the exact minute.', sticker: 'Each little mark on the clock is 1 minute.' },
    twinWon: { text: 'You counted by 5s, then by 1s, to read 5:38.', sticker: 'Each little mark on the clock is 1 minute.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What time is it?', picture: { kind: 'clock', h: 2, m: 22 }, answer: { time: [2, 22] },
        steps: ['The short hand is just past the 2, so the hour is 2.', 'The long hand has passed the 4. Count by 5s to the 4: 20.', 'Count on 2 little marks: 21, 22.', 'It is 2:22.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What time is it?', picture: { kind: 'clock', h: 6, m: 48 }, answer: { time: [6, 48] },
        steps: ['The short hand is past the 6, so the hour is 6.', 'The long hand has passed the 9. Count by 5s to the 9: 45.', 'Count on 3 little marks: 46, 47, 48.', 'It is 6:48.'] } },
      { why: 'Still "5s, then 1s"', problem: { text: 'What time is it?', picture: { kind: 'clock', h: 10, m: 21 }, answer: { time: [10, 21] },
        steps: ['The short hand is just past the 10, so the hour is 10.', 'The long hand has passed the 4. Count by 5s to the 4: 20.', 'Count on 1 little mark: 21.', 'It is 10:21.'] } },
      { why: 'A little harder', problem: { text: 'What time is it? Look closely at the short hand.', picture: { kind: 'clock', h: 9, m: 57 }, answer: { time: [9, 57] },
        steps: ['The short hand is almost on the 10. It has not reached it, so the hour is still 9.', 'The long hand has passed the 11. Count by 5s to the 11: 55.', 'Count on 2 little marks: 56, 57.', 'It is 9:57.'] } },
      { why: 'Same math in a story', problem: { text: 'Leo gets out of bed when the clock shows this. What time does he get up?', picture: { kind: 'clock', h: 7, m: 6 }, answer: { time: [7, 6] },
        steps: ['The short hand is just past the 7, so the hour is 7.', 'The long hand has passed the 1. Count by 5s to the 1: 5.', 'Count on 1 little mark: 6.', 'He gets up at 7:06.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m2-t3', title: 'How long did it take?', skill: 'Find elapsed time in minutes',
    bigIdea: 'Start at the start time. Jump to the end time and add up the jumps.',
    screens: [
      { title: 'How long is the game?', text: 'The game starts at 3:10. It ends at 3:45. How many minutes long is it?',
        pictures: [timeline(3, 0, 60, { points: [{ at: 10, label: 'start' }, { at: 45, label: 'end' }] })] },
      { title: 'A clock does not show how long', text: 'A clock tells you what time it is. It does not tell you how long something took. We have to count the minutes in between.',
        pictures: [timeline(3, 0, 60, { points: [{ at: 10, label: 'start' }, { at: 45, label: 'end' }] })] },
      { title: 'The big idea', text: 'Start at the start time. Jump to the end time and add up the jumps.',
        pictures: [timeline(3, 0, 60, { points: [{ at: 10, label: 'start' }, { at: 45, label: 'end' }] })] },
      { title: 'Jump by 10s', text: 'From 3:10, jump 10 minutes at a time: 3:20, 3:30, 3:40. That is 3 jumps of 10, so 30 minutes.',
        pictures: [timeline(3, 0, 60, { points: [{ at: 10, label: 'start' }, { at: 45, label: 'end' }],
          jumps: [{ from: 10, to: 20, label: '10' }, { from: 20, to: 30, label: '10' }, { from: 30, to: 40, label: '10' }], motion: true })] },
      { title: 'Jump the rest', text: 'From 3:40 to 3:45 is 5 more minutes.',
        pictures: [timeline(3, 0, 60, { points: [{ at: 10, label: 'start' }, { at: 45, label: 'end' }],
          jumps: [{ from: 10, to: 20, label: '10' }, { from: 20, to: 30, label: '10' }, { from: 30, to: 40, label: '10' }, { from: 40, to: 45, label: '5' }], motion: true })] },
      { title: 'Add up the jumps', text: '30 minutes and 5 minutes make 35 minutes. The game is 35 minutes long.',
        pictures: [timeline(3, 0, 60, { points: [{ at: 10, label: 'start' }, { at: 45, label: 'end' }],
          jumps: [{ from: 10, to: 20, label: '10' }, { from: 20, to: 30, label: '10' }, { from: 30, to: 40, label: '10' }, { from: 40, to: 45, label: '5' }] }),
          { kind: 'eq', text: '10 + 10 + 10 + 5 = 35' }] },
      { title: 'One thing not to do', text: "Don't answer with the end time. The question asks how many minutes, not what time it ends.",
        pictures: [{ kind: 'cards', wrong: '3:45', right: '35 minutes' }] },
    ],
    turn: {
      text: 'Art class starts at 1:15. It ends at 1:40. How many minutes long is it?',
      picture: timeline(1, 0, 60, { points: [{ at: 15, label: 'start' }] }),
      answer: 25, steps: ['Start at 1:15. Jump 5 minutes to 1:20.', 'Jump by 10s: 1:30, 1:40. That is 20 more minutes.', 'Add up the jumps: 5 + 20 = 25.', 'It is 25 minutes long.'],
      prompt: 'Start at the start time. Jump to the end time, then add up the jumps.',
      hint1: 'Start at 1:15. Jump to the next 10 first.',
      hint2: 'From 1:20, jump by 10s to 1:40. Then add all your jumps.',
      twin: { text: 'Lunch starts at 12:05. It ends at 12:50. How many minutes long is it?',
        picture: timeline(12, 0, 60, { points: [{ at: 5, label: 'start' }] }),
        answer: 45, steps: ['Start at 12:05. Jump 5 minutes to 12:10.', 'Jump by 10s to 12:50. That is 4 jumps, so 40 minutes.', 'Add up the jumps: 5 + 40 = 45.', 'It is 45 minutes long.'],
        hint1: 'Start at 12:05. Jump 5 minutes to the next 10.', hint2: 'From 12:10, jump by 10s to 12:50. Then add all your jumps.' },
    },
    won: { text: 'You jumped from the start to the end and added up the jumps.', sticker: 'The time from start to end is called elapsed time.' },
    twinWon: { text: 'You jumped from 12:05 to 12:50 and added up 45 minutes.', sticker: 'The time from start to end is called elapsed time.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Music starts at 2:10. It ends at 2:35. How many minutes long is it?',
        picture: timeline(2, 0, 60, { points: [{ at: 10, label: 'start' }] }), answer: 25,
        steps: ['From 2:10, jump by 10s: 2:20, 2:30. That is 20 minutes.', 'From 2:30 to 2:35 is 5 more minutes.', '20 + 5 = 25. It is 25 minutes long.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Recess starts at 10:20. It ends at 10:35. How many minutes long is it?',
        picture: timeline(10, 0, 60, { points: [{ at: 20, label: 'start' }] }), answer: 15,
        steps: ['From 10:20 to 10:30 is 10 minutes.', 'From 10:30 to 10:35 is 5 more minutes.', '10 + 5 = 15. Recess is 15 minutes long.'] } },
      { why: 'Still "add up the jumps"', problem: { text: 'A bath starts at 6:05. It ends at 6:40. How many minutes long is it?',
        picture: timeline(6, 0, 60, { points: [{ at: 5, label: 'start' }] }), answer: 35,
        steps: ['From 6:05 to 6:10 is 5 minutes.', 'From 6:10 to 6:40 is 3 jumps of 10, so 30 minutes.', '5 + 30 = 35. The bath is 35 minutes long.'] } },
      { why: 'A little harder', problem: { text: 'A movie starts at 4:40. It ends at 5:25. How many minutes long is it?',
        picture: timeline(4, 30, 90, { points: [{ at: 40, label: 'start' }] }), answer: 45,
        steps: ['From 4:40 to 5:00 is 2 jumps of 10, so 20 minutes.', 'From 5:00 to 5:25 is 25 more minutes.', '20 + 25 = 45. The movie is 45 minutes long.'] } },
      { why: 'Same math in a story', problem: { text: 'Ava starts her homework at 7:15. She finishes at 7:50. How many minutes does she work?',
        picture: timeline(7, 0, 60, { points: [{ at: 15, label: 'start' }] }), answer: 35,
        steps: ['From 7:15 to 7:20 is 5 minutes.', 'From 7:20 to 7:50 is 3 jumps of 10, so 30 minutes.', '5 + 30 = 35. She works for 35 minutes.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m2-t4', title: 'Heavy or light (grams, kilograms)', skill: 'Read a scale in grams and kilograms',
    bigIdea: 'Find how much each little mark is worth. Then count the marks to the needle.',
    screens: [
      { title: 'How heavy are the apples?', text: 'A bag of apples sits on the scale. How heavy is it?',
        pictures: [gramScale(700)] },
      { title: 'Not every mark has a number', text: 'The needle stops between 600 and 800. There is no number right where it points.',
        pictures: [gramScale(700)] },
      { title: 'The big idea', text: 'Find how much each little mark is worth. Then count the marks to the needle.',
        pictures: [gramScale(700)] },
      { title: 'What is one mark worth?', text: 'From 0 to 200 there are 2 jumps. So each little mark is 100 grams.',
        pictures: [gramScale(700), { kind: 'table', head: ['Marks from 0', 'Grams'], rows: [['1', '100'], ['2', '200']], motion: true }] },
      { title: 'Count to the needle', text: 'Start at 600. One more mark is 700. The apples weigh 700 grams.',
        pictures: [gramScale(700), { kind: 'table', head: ['Count', 'Grams'], rows: [['at the number', '600'], ['1 more mark', '700']], motion: true }] },
      { title: 'Grams or kilograms?', text: 'Light things, like apples, are weighed in grams. Heavy things, like a dog, are weighed in kilograms. 1 kilogram is 1,000 grams.',
        pictures: [kgScale(12, 20, 1, 5)] },
      { title: 'One thing not to do', text: "Don't count each mark as 1. On this scale each mark is 100 grams.",
        pictures: [{ kind: 'cards', wrong: '600 and 1 more = 601 grams', right: '600 and 100 more = 700 grams' }] },
    ],
    turn: {
      text: 'How heavy is the bag of rice?', picture: gramScale(300),
      answer: 300, steps: ['From 0 to 200 there are 2 jumps, so each mark is 100 grams.', 'The needle is 1 mark past 200.', 'So the rice weighs 300 grams.'],
      prompt: 'Find what one mark is worth. Then count to the needle.',
      hint1: 'How much is each little mark worth?',
      hint2: 'Each mark is 100 grams. Find the number just before the needle and count on.',
      twin: { text: 'How heavy is the puppy?', picture: kgScale(7, 10, 1, 2),
        answer: 7, steps: ['From 0 to 2 there are 2 jumps, so each mark is 1 kilogram.', 'The needle is 1 mark past 6.', 'So the puppy weighs 7 kilograms.'],
        hint1: 'How much is each little mark worth?', hint2: 'Each mark is 1 kilogram. Find the number just before the needle and count on.' },
    },
    won: { text: 'You found what one mark is worth and counted to the needle.', sticker: 'How heavy something is is called its mass.' },
    twinWon: { text: 'You counted the marks and found the puppy weighs 7 kilograms.', sticker: 'How heavy something is is called its mass.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'How heavy is the bag of flour?', picture: gramScale(500), answer: 500,
        steps: ['Each mark is 100 grams.', 'The needle is 1 mark past 400.', 'So the flour weighs 500 grams.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'How heavy is the box?', picture: kgScale(35, 50, 5, 10), answer: 35,
        steps: ['From 0 to 10 there are 2 jumps, so each mark is 5 kilograms.', 'The needle is 1 mark past 30.', 'So the box weighs 35 kilograms.'] } },
      { why: 'Still "count to the needle"', problem: { text: 'How heavy is the suitcase?', picture: kgScale(13, 20, 1, 5), answer: 13,
        steps: ['From 0 to 5 there are 5 jumps, so each mark is 1 kilogram.', 'Start at 10 and count 3 marks: 11, 12, 13.', 'So the suitcase weighs 13 kilograms.'] } },
      { why: 'A little harder', problem: { text: 'How heavy is the book?', picture: gramScale(350, 500, 50, 100), answer: 350,
        steps: ['From 0 to 100 there are 2 jumps, so each mark is 50 grams.', 'The needle is 1 mark past 300.', 'So the book weighs 350 grams.'] } },
      { why: 'Same math in a story', problem: { text: 'Sam puts a bag of pasta on the scale. It weighs 400 grams. Then he adds a jar of sauce that weighs 350 grams. How many grams are on the scale now?',
        picture: gramScale(400, 1000, 50, 200), answer: 750,
        steps: ['The pasta weighs 400 grams.', 'Add the sauce: 400 + 350.', 'So there are 750 grams on the scale.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m2-t5', title: 'How much water? (liters, milliliters)', skill: 'Read a jug in milliliters and liters',
    bigIdea: 'Find how much each little mark is worth. Then count the marks up to the top of the water.',
    screens: [
      { title: 'How much juice?', text: 'Juice is poured into a jug. How much juice is in the jug?',
        pictures: [mlJug(500)] },
      { title: 'The top is between numbers', text: 'The top of the juice is between 400 and 600. There is no number right there.',
        pictures: [mlJug(500)] },
      { title: 'The big idea', text: 'Find how much each little mark is worth. Then count the marks up to the top of the water.',
        pictures: [mlJug(500)] },
      { title: 'What is one mark worth?', text: 'From 0 to 200 there are 2 jumps. So each little mark is 100 milliliters.',
        pictures: [mlJug(500), { kind: 'table', head: ['Marks from 0', 'Milliliters'], rows: [['1', '100'], ['2', '200']], motion: true }] },
      { title: 'Count up to the top', text: 'Start at 400. Count up one mark: 500. There are 500 milliliters of juice.',
        pictures: [mlJug(500), { kind: 'table', head: ['Count', 'Milliliters'], rows: [['at the number', '400'], ['1 more mark', '500']], motion: true }] },
      { title: 'Milliliters or liters?', text: 'A little water, like a cup, is measured in milliliters. A lot of water, like a bucket, is measured in liters. 1 liter is 1,000 milliliters.',
        pictures: [literJug(7, 10, 1, 2)] },
      { title: 'One thing not to do', text: "Don't stop at the number below the water. Count the marks all the way up to the top.",
        pictures: [{ kind: 'cards', wrong: '400 milliliters', right: '500 milliliters' }] },
    ],
    turn: {
      text: 'How much water is in the jug?', picture: mlJug(700),
      answer: 700, steps: ['From 0 to 200 there are 2 jumps, so each mark is 100 milliliters.', 'The water is 1 mark above 600.', 'So there are 700 milliliters.'],
      prompt: 'Find what one mark is worth. Then count up to the top of the water.',
      hint1: 'How much is each little mark worth?',
      hint2: 'Each mark is 100 milliliters. Find the number just below the water and count up.',
      twin: { text: 'How many liters of water are in the fish tank?', picture: literJug(3, 10, 1, 2),
        answer: 3, steps: ['From 0 to 2 there are 2 jumps, so each mark is 1 liter.', 'The water is 1 mark above 2.', 'So there are 3 liters.'],
        hint1: 'How much is each little mark worth?', hint2: 'Each mark is 1 liter. Find the number just below the water and count up.' },
    },
    won: { text: 'You found what one mark is worth and counted up to the top.', sticker: 'How much liquid a container holds is called its liquid volume.' },
    twinWon: { text: 'You counted up the marks and found 3 liters.', sticker: 'How much liquid a container holds is called its liquid volume.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'How much milk is in the jug?', picture: mlJug(300), answer: 300,
        steps: ['Each mark is 100 milliliters.', 'The milk is 1 mark above 200.', 'So there are 300 milliliters.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'How many liters of water are in the bucket?', picture: literJug(8, 20, 1, 5), answer: 8,
        steps: ['From 0 to 5 there are 5 jumps, so each mark is 1 liter.', 'The water is 3 marks above 5: 6, 7, 8.', 'So there are 8 liters.'] } },
      { why: 'Still "count up the marks"', problem: { text: 'How many liters of soup are in the pot?', picture: literJug(9, 10, 1, 2), answer: 9,
        steps: ['From 0 to 2 there are 2 jumps, so each mark is 1 liter.', 'The soup is 1 mark above 8.', 'So there are 9 liters.'] } },
      { why: 'A little harder', problem: { text: 'How much water is in the glass?', picture: mlJug(150, 500, 50, 100), answer: 150,
        steps: ['From 0 to 100 there are 2 jumps, so each mark is 50 milliliters.', 'The water is 1 mark above 100.', 'So there are 150 milliliters.'] } },
      { why: 'Same math in a story', problem: { text: 'A jug has 900 milliliters of lemonade. Mia pours out 250 milliliters. How many milliliters are left?',
        picture: mlJug(900, 1000, 50, 200), answer: 650,
        steps: ['The jug starts with 900 milliliters.', 'Take away what Mia pours out: 900 − 250.', 'So 650 milliliters are left.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m2-t6', title: 'Round to the nearest 10', skill: 'Round a number to the nearest ten',
    bigIdea: 'A number rounds to the ten it is closer to. If it is right in the middle, it goes up.',
    screens: [
      { title: 'About how many marbles?', text: 'A jar has 37 marbles. Is that closer to 30 marbles or 40 marbles?',
        pictures: [{ kind: 'numline', min: 30, max: 40, ticks: 10, points: [{ at: 37, label: '37' }] }] },
      { title: 'The first number can fool you', text: '37 starts with a 3, so you might say 30. But that does not tell you which ten is closer.',
        pictures: [{ kind: 'numline', min: 30, max: 40, ticks: 10, points: [{ at: 37, label: '37' }] }] },
      { title: 'The big idea', text: 'A number rounds to the ten it is closer to. If it is right in the middle, it goes up.',
        pictures: [{ kind: 'numline', min: 30, max: 40, ticks: 10, points: [{ at: 37, label: '37' }] }] },
      { title: 'Find the two tens', text: '37 is more than 30 and less than 40. Those are the two tens on each side.',
        pictures: [{ kind: 'numline', min: 30, max: 40, ticks: 10, labels: 'ends', points: [{ at: 37, label: '37' }] }] },
      { title: 'Which ten is closer?', text: 'From 37, it takes 3 jumps up to 40. It takes 7 jumps back to 30. 40 is closer, so 37 rounds to 40.',
        pictures: [{ kind: 'numline', min: 30, max: 40, ticks: 10, labels: 'ends', points: [{ at: 37, label: '37' }],
          jumps: [{ from: 37, to: 38 }, { from: 38, to: 39 }, { from: 39, to: 40 }], motion: true }] },
      { title: 'Right in the middle', text: '35 is exactly in the middle of 30 and 40. It is 5 jumps from each. When it is in the middle, it goes up. 35 rounds to 40.',
        pictures: [{ kind: 'numline', min: 30, max: 40, ticks: 10, labels: 'ends', points: [{ at: 35, label: '35' }] }, { kind: 'eq', text: '35 → 40' }] },
      { title: 'One thing not to do', text: "Don't just drop the ones. 37 is not closer to 30. It is closer to 40.",
        pictures: [{ kind: 'cards', wrong: '37 → 30', right: '37 → 40' }] },
    ],
    turn: {
      text: 'Round 62 to the nearest ten.', picture: between(60, 70, 62),
      answer: 60, steps: ['62 is between 60 and 70.', '62 is 2 jumps from 60 and 8 jumps from 70.', 'So 62 rounds to 60.'],
      prompt: 'Find the two tens on each side. Which one is closer?',
      hint1: 'Which two tens is 62 between?',
      hint2: '62 is 2 jumps from one ten and 8 jumps from the other. Which is closer?',
      twin: { text: 'Round 78 to the nearest ten.', picture: between(70, 80, 78),
        answer: 80, steps: ['78 is between 70 and 80.', '78 is 8 jumps from 70 and 2 jumps from 80.', 'So 78 rounds to 80.'],
        hint1: 'Which two tens is 78 between?', hint2: '78 is 8 jumps from one ten and 2 jumps from the other. Which is closer?' },
    },
    won: { text: 'You found the two tens and picked the closer one.', sticker: 'The middle between two tens is called the halfway point. It rounds up.' },
    twinWon: { text: 'You found that 78 is closer to 80.', sticker: 'The middle between two tens is called the halfway point. It rounds up.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Round 34 to the nearest ten.', picture: between(30, 40, 34), answer: 30,
        steps: ['34 is between 30 and 40.', '34 is 4 jumps from 30 and 6 jumps from 40.', 'So 34 rounds to 30.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Round 56 to the nearest ten.', picture: between(50, 60, 56), answer: 60,
        steps: ['56 is between 50 and 60.', '56 is 6 jumps from 50 and 4 jumps from 60.', 'So 56 rounds to 60.'] } },
      { why: 'Still "go to the closer ten"', problem: { text: 'Round 85 to the nearest ten.', picture: between(80, 90, 85), answer: 90,
        steps: ['85 is between 80 and 90.', '85 is right in the middle: 5 jumps each way.', 'In the middle, it goes up. So 85 rounds to 90.'] } },
      { why: 'A little harder', problem: { text: 'Round 143 to the nearest ten.', picture: between(140, 150, 143), answer: 140,
        steps: ['143 is between 140 and 150.', '143 is 3 jumps from 140 and 7 jumps from 150.', 'So 143 rounds to 140.'] } },
      { why: 'Same math in a story', problem: { text: 'A class read 67 books. About how many books is that, to the nearest ten?', picture: between(60, 70, 67), answer: 70,
        steps: ['67 is between 60 and 70.', '67 is 7 jumps from 60 and 3 jumps from 70.', 'So 67 rounds to 70.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m2-t7', title: 'Round to the nearest 100', skill: 'Round a number to the nearest hundred',
    bigIdea: 'A number rounds to the hundred it is closer to. If it is right in the middle, it goes up.',
    screens: [
      { title: 'About how many people?', text: '270 people came to the fair. Is that closer to 200 people or 300 people?',
        pictures: [{ kind: 'numline', min: 200, max: 300, ticks: 10, points: [{ at: 270, label: '270' }] }] },
      { title: 'The hundreds are far apart', text: 'From 200 to 300 is a long way. Counting one at a time would take too long. We jump by 10s instead.',
        pictures: [{ kind: 'numline', min: 200, max: 300, ticks: 10, points: [{ at: 270, label: '270' }] }] },
      { title: 'The big idea', text: 'A number rounds to the hundred it is closer to. If it is right in the middle, it goes up.',
        pictures: [{ kind: 'numline', min: 200, max: 300, ticks: 10, points: [{ at: 270, label: '270' }] }] },
      { title: 'Find the two hundreds', text: '270 is more than 200 and less than 300. Those are the two hundreds on each side.',
        pictures: [{ kind: 'numline', min: 200, max: 300, ticks: 10, labels: 'ends', points: [{ at: 270, label: '270' }] }] },
      { title: 'Which hundred is closer?', text: 'From 270, it takes 3 jumps of 10 up to 300. It takes 7 jumps of 10 back to 200. 300 is closer, so 270 rounds to 300.',
        pictures: [{ kind: 'numline', min: 200, max: 300, ticks: 10, labels: 'ends', points: [{ at: 270, label: '270' }],
          jumps: [{ from: 270, to: 280 }, { from: 280, to: 290 }, { from: 290, to: 300 }], motion: true }] },
      { title: 'Right in the middle', text: '250 is exactly in the middle of 200 and 300. When it is in the middle, it goes up. 250 rounds to 300.',
        pictures: [{ kind: 'numline', min: 200, max: 300, ticks: 10, labels: 'ends', points: [{ at: 250, label: '250' }] }, { kind: 'eq', text: '250 → 300' }] },
      { title: 'One thing not to do', text: "Don't let the ones fool you. 329 ends in 9, but it is only 29 more than 300. It rounds to 300.",
        pictures: [{ kind: 'cards', wrong: '329 → 400', right: '329 → 300' }] },
    ],
    turn: {
      text: 'Round 420 to the nearest hundred.', picture: between(400, 500, 420),
      answer: 400, steps: ['420 is between 400 and 500.', '420 is 2 jumps of 10 from 400 and 8 jumps of 10 from 500.', 'So 420 rounds to 400.'],
      prompt: 'Find the two hundreds on each side. Which one is closer?',
      hint1: 'Which two hundreds is 420 between?',
      hint2: '420 is 2 jumps of 10 from one hundred and 8 jumps from the other. Which is closer?',
      twin: { text: 'Round 680 to the nearest hundred.', picture: between(600, 700, 680),
        answer: 700, steps: ['680 is between 600 and 700.', '680 is 8 jumps of 10 from 600 and 2 jumps of 10 from 700.', 'So 680 rounds to 700.'],
        hint1: 'Which two hundreds is 680 between?', hint2: '680 is 8 jumps of 10 from one hundred and 2 jumps from the other. Which is closer?' },
    },
    won: { text: 'You found the two hundreds and picked the closer one.', sticker: 'A rounded number is an estimate: close to the real number, and easy to use.' },
    twinWon: { text: 'You found that 680 is closer to 700.', sticker: 'A rounded number is an estimate: close to the real number, and easy to use.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Round 310 to the nearest hundred.', picture: between(300, 400, 310), answer: 300,
        steps: ['310 is between 300 and 400.', '310 is 1 jump of 10 from 300 and 9 jumps of 10 from 400.', 'So 310 rounds to 300.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Round 590 to the nearest hundred.', picture: between(500, 600, 590), answer: 600,
        steps: ['590 is between 500 and 600.', '590 is 9 jumps of 10 from 500 and 1 jump of 10 from 600.', 'So 590 rounds to 600.'] } },
      { why: 'Still "go to the closer hundred"', problem: { text: 'Round 750 to the nearest hundred.', picture: between(700, 800, 750), answer: 800,
        steps: ['750 is between 700 and 800.', '750 is right in the middle: 5 jumps of 10 each way.', 'In the middle, it goes up. So 750 rounds to 800.'] } },
      { why: 'A little harder', problem: { text: 'Round 364 to the nearest hundred.', picture: between(300, 400, 364), answer: 400,
        steps: ['364 is between 300 and 400.', '364 is 64 more than 300, and 36 less than 400.', '400 is closer, so 364 rounds to 400.'] } },
      { why: 'Same math in a story', problem: { text: 'A school has 238 students. About how many students is that, to the nearest hundred?', picture: between(200, 300, 238), answer: 200,
        steps: ['238 is between 200 and 300.', '238 is 38 more than 200, and 62 less than 300.', 'So 238 rounds to 200.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m2-t8', title: 'Add big numbers (trade 10 ones for a ten)', skill: 'Add three-digit numbers with regrouping',
    bigIdea: 'Add the ones first. If there are 10 or more, trade 10 ones for 1 ten.',
    screens: [
      { title: 'Books on two shelves', text: 'One shelf has 146 books. The other has 128 books. How many books are there in all?',
        pictures: [{ kind: 'blocks', hundreds: 1, tens: 4, ones: 6 }, { kind: 'blocks', hundreds: 1, tens: 2, ones: 8 }] },
      { title: 'Too many ones', text: 'Put the ones together: 6 and 8 make 14 ones. One place can only hold up to 9, so we cannot just write 14.',
        pictures: [{ kind: 'blocks', hundreds: 2, tens: 6, ones: 14 }] },
      { title: 'The big idea', text: 'Add the ones first. If there are 10 or more, trade 10 ones for 1 ten.',
        pictures: [{ kind: 'blocks', hundreds: 2, tens: 6, ones: 14 }] },
      { title: 'Add the ones first', text: '6 ones and 8 ones make 14 ones. That is 10 or more, so we trade.',
        pictures: [{ kind: 'blocks', hundreds: 2, tens: 6, ones: 14, motion: true }] },
      { title: 'Trade 10 ones for a ten', text: 'Ring 10 ones. Swap them for 1 ten. Now there are 7 tens and 4 ones.',
        pictures: [{ kind: 'blocks', hundreds: 2, tens: 6, ones: 14, trade: 'ones' }, { kind: 'blocks', hundreds: 2, tens: 7, ones: 4, motion: true }] },
      { title: 'Add the tens and hundreds', text: '2 hundreds, 7 tens and 4 ones make 274. So 146 + 128 = 274.',
        pictures: [{ kind: 'blocks', hundreds: 2, tens: 7, ones: 4 }, { kind: 'eq', text: '146 + 128 = 274' }] },
      { title: 'One thing not to do', text: "Don't forget the ten you traded. Add it in with the other tens.",
        pictures: [{ kind: 'cards', wrong: '146 + 128 = 264', right: '146 + 128 = 274' }, { kind: 'columns', rows: ['146', '128'], op: '+', carry: '1 ', places: ['H', 'T', 'O'], answer: '274' }] },
    ],
    turn: {
      text: 'A farm has 235 hens and 147 ducks. How many birds are there?', picture: add('235', '147'),
      answer: 382, steps: ['Ones: 5 + 7 = 12. Trade 10 ones for 1 ten, and write 2 ones.', 'Tens: 1 + 3 + 4 = 8 tens.', 'Hundreds: 2 + 1 = 3 hundreds.', 'So 235 + 147 = 382.'],
      prompt: 'Add the ones first. Trade 10 ones for a ten if you need to.',
      hint1: 'Add the ones first. Is it 10 or more?',
      hint2: '5 + 7 = 12. Write the 2 and trade 10 ones for 1 ten.',
      twin: { text: 'A shop sells 316 red pens and 259 blue pens. How many pens is that?', picture: add('316', '259'),
        answer: 575, steps: ['Ones: 6 + 9 = 15. Trade 10 ones for 1 ten, and write 5 ones.', 'Tens: 1 + 1 + 5 = 7 tens.', 'Hundreds: 3 + 2 = 5 hundreds.', 'So 316 + 259 = 575.'],
        hint1: 'Add the ones first. Is it 10 or more?', hint2: '6 + 9 = 15. Write the 5 and trade 10 ones for 1 ten.' },
    },
    won: { text: 'You added the ones first and traded 10 ones for a ten.', sticker: 'Trading 10 ones for 1 ten is called regrouping.' },
    twinWon: { text: 'You traded 10 ones for 1 ten and found 316 + 259 = 575.', sticker: 'Trading 10 ones for 1 ten is called regrouping.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '128 + 134 = ?', picture: add('128', '134'), answer: 262,
        steps: ['Ones: 8 + 4 = 12. Trade 10 ones for 1 ten, and write 2 ones.', 'Tens: 1 + 2 + 3 = 6 tens. Hundreds: 1 + 1 = 2.', 'So 128 + 134 = 262.'] } },
      { why: 'Same idea, new numbers', problem: { text: '407 + 285 = ?', picture: add('407', '285'), answer: 692,
        steps: ['Ones: 7 + 5 = 12. Trade 10 ones for 1 ten, and write 2 ones.', 'Tens: 1 + 0 + 8 = 9 tens. Hundreds: 4 + 2 = 6.', 'So 407 + 285 = 692.'] } },
      { why: 'Still "trade 10 ones"', problem: { text: '356 + 229 = ?', picture: add('356', '229'), answer: 585,
        steps: ['Ones: 6 + 9 = 15. Trade 10 ones for 1 ten, and write 5 ones.', 'Tens: 1 + 5 + 2 = 8 tens. Hundreds: 3 + 2 = 5.', 'So 356 + 229 = 585.'] } },
      { why: 'A little harder', problem: { text: '478 + 256 = ?', picture: add('478', '256'), answer: 734,
        steps: ['Ones: 8 + 6 = 14. Trade 10 ones for 1 ten, and write 4 ones.', 'Tens: 1 + 7 + 5 = 13 tens. Trade 10 tens for 1 hundred, and write 3 tens.', 'Hundreds: 1 + 4 + 2 = 7.', 'So 478 + 256 = 734.'] } },
      { why: 'Same math in a story', problem: { text: 'Jon has 365 stamps. His sister gives him 187 more. How many stamps does he have now?', picture: add('365', '187'), answer: 552,
        steps: ['Ones: 5 + 7 = 12. Trade 10 ones for 1 ten, and write 2 ones.', 'Tens: 1 + 6 + 8 = 15 tens. Trade 10 tens for 1 hundred, and write 5 tens.', 'Hundreds: 1 + 3 + 1 = 5.', 'So Jon has 552 stamps.'] } },
    ],
  },

  // ── Topic 9 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m2-t9', title: 'Take away big numbers (break a ten)', skill: 'Subtract three-digit numbers with regrouping',
    bigIdea: 'Take away the ones first. If there are not enough ones, break 1 ten into 10 ones.',
    screens: [
      { title: 'Giving stickers away', text: 'Nia has 352 stickers. She gives away 127. How many stickers are left?',
        pictures: [{ kind: 'blocks', hundreds: 3, tens: 5, ones: 2 }] },
      { title: 'Not enough ones', text: 'We need to take away 7 ones. But there are only 2 ones. We cannot take 7 from 2.',
        pictures: [{ kind: 'blocks', hundreds: 3, tens: 5, ones: 2 }] },
      { title: 'The big idea', text: 'Take away the ones first. If there are not enough ones, break 1 ten into 10 ones.',
        pictures: [{ kind: 'blocks', hundreds: 3, tens: 5, ones: 2 }] },
      { title: 'Break a ten', text: 'Break 1 ten into 10 ones. Now there are 4 tens and 12 ones. It is still 352.',
        pictures: [{ kind: 'blocks', hundreds: 3, tens: 4, ones: 12, trade: 'ones', motion: true }] },
      { title: 'Take away the ones', text: '12 ones take away 7 ones leaves 5 ones.',
        pictures: [{ kind: 'blocks', hundreds: 3, tens: 4, ones: 5, motion: true }] },
      { title: 'Take away the tens and hundreds', text: '4 tens take away 2 tens leaves 2 tens. 3 hundreds take away 1 hundred leaves 2 hundreds. So 352 − 127 = 225.',
        pictures: [{ kind: 'blocks', hundreds: 2, tens: 2, ones: 5 }, { kind: 'eq', text: '352 − 127 = 225' }] },
      { title: 'One thing not to do', text: "Don't flip the ones around. 2 − 7 is not 7 − 2. Break a ten instead.",
        pictures: [{ kind: 'cards', wrong: '352 − 127 = 235', right: '352 − 127 = 225' }, { kind: 'columns', rows: ['352', '127'], op: '−', places: ['H', 'T', 'O'], answer: '225' }] },
    ],
    turn: {
      text: 'A library has 463 books. 218 are borrowed. How many books are left?', picture: sub('463', '218'),
      answer: 245, steps: ['Ones: 3 is less than 8. Break 1 ten into 10 ones, so there are 13 ones.', 'Ones: 13 − 8 = 5. Tens: 5 − 1 = 4.', 'Hundreds: 4 − 2 = 2.', 'So 463 − 218 = 245.'],
      prompt: 'Take away the ones first. Break a ten if you need more ones.',
      hint1: 'Look at the ones. Can you take 8 from 3?',
      hint2: 'Break 1 ten into 10 ones. Now there are 13 ones and 5 tens.',
      twin: { text: 'A baker made 572 rolls and sold 336. How many rolls are left?', picture: sub('572', '336'),
        answer: 236, steps: ['Ones: 2 is less than 6. Break 1 ten into 10 ones, so there are 12 ones.', 'Ones: 12 − 6 = 6. Tens: 6 − 3 = 3.', 'Hundreds: 5 − 3 = 2.', 'So 572 − 336 = 236.'],
        hint1: 'Look at the ones. Can you take 6 from 2?', hint2: 'Break 1 ten into 10 ones. Now there are 12 ones and 6 tens.' },
    },
    won: { text: 'You broke a ten when there were not enough ones.', sticker: 'Breaking 1 ten into 10 ones is also called regrouping.' },
    twinWon: { text: 'You broke a ten and found 572 − 336 = 236.', sticker: 'Breaking 1 ten into 10 ones is also called regrouping.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '245 − 128 = ?', picture: sub('245', '128'), answer: 117,
        steps: ['Ones: break 1 ten, so 15 − 8 = 7.', 'Tens: 3 − 2 = 1. Hundreds: 2 − 1 = 1.', 'So 245 − 128 = 117.'] } },
      { why: 'Same idea, new numbers', problem: { text: '634 − 219 = ?', picture: sub('634', '219'), answer: 415,
        steps: ['Ones: break 1 ten, so 14 − 9 = 5.', 'Tens: 2 − 1 = 1. Hundreds: 6 − 2 = 4.', 'So 634 − 219 = 415.'] } },
      { why: 'Still "break a ten"', problem: { text: '781 − 356 = ?', picture: sub('781', '356'), answer: 425,
        steps: ['Ones: break 1 ten, so 11 − 6 = 5.', 'Tens: 7 − 5 = 2. Hundreds: 7 − 3 = 4.', 'So 781 − 356 = 425.'] } },
      { why: 'A little harder', problem: { text: '523 − 187 = ?', picture: sub('523', '187'), answer: 336,
        steps: ['Ones: break 1 ten, so 13 − 7 = 6. Now there is 1 ten.', 'Tens: 1 is less than 8. Break 1 hundred into 10 tens, so 11 − 8 = 3.', 'Hundreds: 4 − 1 = 3.', 'So 523 − 187 = 336.'] } },
      { why: 'Same math in a story', problem: { text: 'A school has 640 chairs. 275 are in the hall. How many chairs are not in the hall?', picture: sub('640', '275'), answer: 365,
        steps: ['Ones: break 1 ten, so 10 − 5 = 5. Now there are 3 tens.', 'Tens: 3 is less than 7. Break 1 hundred into 10 tens, so 13 − 7 = 6.', 'Hundreds: 5 − 2 = 3.', 'So 365 chairs are not in the hall.'] } },
    ],
  },
]
