/**
 * Grade 3 · Module 4 — Multiplication and area.
 * Written to docs/new-flow/AUTHORING.md. Every teaching picture is the `grid` of square tiles.
 */
import type { Lesson } from '../script'
import { attachChalk } from '../chalk'
import { G3M4_CHALK } from './chalk/g3m4'

export const G3M4: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m4-t1', title: 'Cover the floor with tiles', skill: 'Area is the number of square tiles that cover a shape',
    bigIdea: "To find how much floor there is, count the square tiles that cover it, with no gaps and no overlaps.",
    screens: [
      { title: 'A new floor', text: 'A playroom floor is covered with square tiles. How much floor is there?',
        pictures: [{ kind: 'grid', rows: 3, cols: 4 }] },
      { title: "A ruler is not enough", text: "A ruler tells you how long one side is. But the floor is the whole inside. So how do we measure the inside? We cover it with tiles.",
        beats: [
          { say: "A ruler tells you how long one side is.", pic: 0 },
          { say: "But the floor is the whole inside." },
          { say: "So how do we measure the inside? We cover it with tiles." },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 4, top: '4 ft' }] },
      { title: "The big idea", text: "To find how much floor there is, count the square tiles that cover it, with no gaps and no overlaps.",
        beats: [
          { say: "To find how much floor there is, count the square tiles that cover it, with no gaps and no overlaps.", pic: 0 },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 4 }] },
      { title: "Every tile is the same", text: "Look at one tile. It is a square, 1 foot on every side. Every tile is the same, and they fit side by side.",
        beats: [
          { say: "Look at one tile.", pic: 0 },
          { say: "It is a square, 1 foot on every side." },
          { say: "Every tile is the same, and they fit side by side." },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 4, shade: [{ r: 0, c: 0, h: 1, w: 1 }] }] },
      { title: "Count the tiles", text: "Now count every tile, just once. Go one row at a time. 4, 8, 12. That's 12 tiles.",
        beats: [
          { say: "Now count every tile, just once.", pic: 0 },
          { say: "Go one row at a time. 4, 8, 12." },
          { say: "That's 12 tiles.", pic: 1 },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 4, motion: true,
          shade: [{ r: 0, c: 0, h: 1, w: 4 }, { r: 1, c: 0, h: 1, w: 4 }, { r: 2, c: 0, h: 1, w: 4 }] },
          { kind: 'eq', text: '12 tiles' }] },
      { title: "Say how big", text: "So how do we say how big that is? Each tile is 1 foot on every side, so we call it 1 square foot. 12 tiles cover 12 square feet.",
        beats: [
          { say: "So how do we say how big that is?", pic: 0 },
          { say: "Each tile is 1 foot on every side, so we call it 1 square foot." },
          { say: "12 tiles cover 12 square feet.", pic: 1 },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 4, shade: [{ r: 0, c: 0, h: 3, w: 4 }] }, { kind: 'eq', text: '12 square feet' }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't leave a GAP, and don't let tiles overlap. A gap misses floor, and an overlap counts it twice. Cover it all, just once. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't leave a GAP, and don't let tiles overlap.", pic: 0 },
          { say: "A gap misses floor, and an overlap counts it twice. Cover it all, just once.", pic: 1 },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 4, hide: [{ r: 1, c: 2, h: 1, w: 1 }] }, { kind: 'cards', wrong: 'a gap: 11 tiles', right: 'no gaps: 12 tiles' }] },
    ],
    turn: {
      text: 'Each tile is 1 square foot. How many square feet of floor do these tiles cover?',
      picture: { kind: 'grid', rows: 3, cols: 5 },
      answer: 15, steps: ['Each tile is 1 square foot.', 'Count the tiles one row at a time: 5, then 10, then 15.', 'So the tiles cover 15 square feet.'],
      prompt: 'Count every tile once. Each tile is 1 square foot.',
      hint1: 'Count each tile once. Try going across one row at a time.',
      hint2: 'The top row has 5 tiles. Keep counting along every row.',
      twin: { text: 'Each tile is 1 square foot. How many square feet of floor do these tiles cover?',
        picture: { kind: 'grid', rows: 2, cols: 6 },
        answer: 12, steps: ['Each tile is 1 square foot.', 'Count the top row: 6 tiles. Keep counting the bottom row: 7, 8, 9, 10, 11, 12.', 'So the tiles cover 12 square feet.'],
        hint1: 'Count every tile once. Do not skip any.', hint2: 'Count the top row. Then keep counting along the bottom row.' },
    },
    won: { text: 'You counted every tile once, with no gaps and no overlaps.', sticker: 'The space a shape covers is its area. Each tile is a square unit.' },
    twinWon: { text: 'You counted every tile once and found 12 square feet.', sticker: 'The space a shape covers is its area. Each tile is a square unit.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Each tile is 1 square foot. How many square feet do these tiles cover?',
        picture: { kind: 'grid', rows: 3, cols: 3 }, answer: 9,
        steps: ['Each tile is 1 square foot.', 'Count every tile once: 3, 6, 9.', 'So the tiles cover 9 square feet.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Each square is 1 square unit. How many square units cover this shape?',
        picture: { kind: 'grid', rows: 4, cols: 5 }, answer: 20,
        steps: ['Each square is 1 square unit.', 'Count one row at a time: 5, 10, 15, 20.', 'So 20 square units cover it.'] } },
      { why: 'Still "count the tiles"', problem: { text: 'Each tile is 1 square foot. How many square feet do these tiles cover?',
        picture: { kind: 'grid', rows: 2, cols: 7 }, answer: 14,
        steps: ['Each tile is 1 square foot.', 'The top row has 7 tiles. The bottom row has 7 more: 8, 9, 10, 11, 12, 13, 14.', 'So the tiles cover 14 square feet.'] } },
      { why: 'A little harder', problem: { text: 'Each square is 1 square unit. How many square units cover this shape?',
        picture: { kind: 'grid', rows: 4, cols: 6 }, answer: 24,
        steps: ['Each square is 1 square unit.', 'Count one row at a time: 6, 12, 18, 24.', 'So 24 square units cover it.'] } },
      { why: 'Same math in a story', problem: { text: 'Leo covers a box lid with square stickers. Each sticker is 1 square inch. How many square inches does he cover?',
        picture: { kind: 'grid', rows: 3, cols: 6 }, answer: 18,
        steps: ['Each sticker is 1 square inch.', 'Count one row at a time: 6, 12, 18.', 'So Leo covers 18 square inches.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m4-t2', title: 'Count the rows instead', skill: 'Area of a rectangle: rows × tiles in a row',
    bigIdea: "For a rectangle, the area is the number of rows times the tiles in one row.",
    screens: [
      { title: 'A garden of tiles', text: 'A garden is 5 tiles long and 3 tiles wide. How many tiles cover it?',
        pictures: [{ kind: 'grid', rows: 3, cols: 5, top: '5 tiles', left: '3 tiles' }] },
      { title: "One by one is slow", text: "You could count every tile, one at a time. That works. But in a big garden, it takes a long time. Is there a faster way? Yes. Look at the rows.",
        beats: [
          { say: "You could count every tile, one at a time.", pic: 0 },
          { say: "That works. But in a big garden, it takes a long time." },
          { say: "Is there a faster way? Yes. Look at the rows." },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 5 }] },
      { title: "The big idea", text: "For a rectangle, the area is the number of rows times the tiles in one row.",
        beats: [
          { say: "For a rectangle, the area is the number of rows times the tiles in one row.", pic: 0 },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 5 }] },
      { title: "Count the rows", text: "Look. Rows go across, like lines of writing. How many rows are there? Count with me. 1, 2, 3. That's 3 rows.",
        beats: [
          { say: "Look. Rows go across, like lines of writing.", pic: 0 },
          { say: "How many rows are there? Count with me. 1, 2, 3." },
          { say: "That's 3 rows." },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 5, left: '3 rows', motion: true,
          shade: [{ r: 0, c: 0, h: 1, w: 5, tone: 1 }, { r: 1, c: 0, h: 1, w: 5, tone: 2 }, { r: 2, c: 0, h: 1, w: 5, tone: 1 }] }] },
      { title: "Count one row", text: "Every row is the same, so count just one. 1, 2, 3, 4, 5. One row has 5 tiles.",
        beats: [
          { say: "Every row is the same, so count just one.", pic: 0 },
          { say: "1, 2, 3, 4, 5." },
          { say: "One row has 5 tiles." },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 5, top: '5 in a row', shade: [{ r: 0, c: 0, h: 1, w: 5 }] }] },
      { title: "3 rows of 5", text: "Now count by whole rows. 5, 10, 15. 3 rows of 5 is 15, so 3 \u00d7 5 = 15. The area is 15 square units.",
        beats: [
          { say: "Now count by whole rows. 5, 10, 15.", pic: 0 },
          { say: "3 rows of 5 is 15, so 3 \u00d7 5 = 15.", pic: 1 },
          { say: "The area is 15 square units." },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 5, motion: true,
          shade: [{ r: 0, c: 0, h: 1, w: 5 }, { r: 1, c: 0, h: 1, w: 5 }, { r: 2, c: 0, h: 1, w: 5 }] },
          { kind: 'eq', text: '3 × 5 = 15' }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't ADD 5 and 3. That gives 8, but the tiles are 3 rows of 5. So multiply, 3 \u00d7 5 = 15. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't ADD 5 and 3.", pic: 0 },
          { say: "That gives 8, but the tiles are 3 rows of 5. So multiply, 3 \u00d7 5 = 15." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '5 + 3 = 8', right: '3 × 5 = 15' }] },
    ],
    turn: {
      text: 'A rug is 6 tiles long and 4 tiles wide. What is its area in square units?',
      picture: { kind: 'grid', rows: 4, cols: 6, top: '6', left: '4' },
      answer: 24, steps: ['There are 4 rows, and each row has 6 tiles.', 'Count by rows: 6, 12, 18, 24.', 'So 4 × 6 = 24. The area is 24 square units.'],
      prompt: 'Count the rows. Count one row. Then multiply.',
      hint1: 'How many rows are there? How many tiles are in one row?',
      hint2: 'There are 4 rows of 6. Count by 6s, one row at a time: 6, 12 …',
      twin: { text: 'A mat is 5 tiles long and 2 tiles wide. What is its area in square units?',
        picture: { kind: 'grid', rows: 2, cols: 5, top: '5', left: '2' },
        answer: 10, steps: ['There are 2 rows, and each row has 5 tiles.', 'Count by rows: 5, 10.', 'So 2 × 5 = 10. The area is 10 square units.'],
        hint1: 'How many rows are there? How many tiles are in one row?', hint2: 'There are 2 rows of 5. Count by 5s, one row at a time.' },
    },
    won: { text: 'You multiplied the rows by the tiles in a row. That is the area.', sticker: 'For a rectangle, area = length × width.' },
    twinWon: { text: 'You multiplied 2 rows by 5 tiles in a row to find the area.', sticker: 'For a rectangle, area = length × width.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A mat is 4 tiles long and 3 tiles wide. What is its area in square units?',
        picture: { kind: 'grid', rows: 3, cols: 4, top: '4', left: '3' }, answer: 12,
        steps: ['There are 3 rows of 4 tiles.', 'Count by rows: 4, 8, 12.', 'So 3 × 4 = 12 square units.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A patio is 4 tiles long and 5 tiles wide. What is its area in square units?',
        picture: { kind: 'grid', rows: 5, cols: 4, top: '4', left: '5' }, answer: 20,
        steps: ['There are 5 rows of 4 tiles.', 'Count by rows: 4, 8, 12, 16, 20.', 'So 5 × 4 = 20 square units.'] } },
      { why: 'Still "rows times a row"', problem: { text: 'A wall has 6 rows of tiles, with 3 tiles in each row. What is its area in square units?',
        picture: { kind: 'grid', rows: 6, cols: 3 }, answer: 18,
        steps: ['There are 6 rows of 3 tiles.', 'Count by rows: 3, 6, 9, 12, 15, 18.', 'So 6 × 3 = 18 square units.'] } },
      { why: 'A little harder', problem: { text: 'A floor is 7 tiles long and 6 tiles wide. What is its area in square units?',
        picture: { kind: 'grid', rows: 6, cols: 7, top: '7', left: '6' }, answer: 42,
        steps: ['There are 6 rows of 7 tiles.', 'Count by 7s: 7, 14, 21, 28, 35, 42.', 'So 6 × 7 = 42 square units.'] } },
      { why: 'Same math in a story', problem: { text: 'A bathroom floor has 8 rows of tiles, with 5 tiles in each row. Each tile is 1 square foot. How many square feet is the floor?',
        picture: { kind: 'grid', rows: 8, cols: 5 }, answer: 40,
        steps: ['There are 8 rows of 5 tiles, and each tile is 1 square foot.', 'Count by 5s: 5, 10, 15, 20, 25, 30, 35, 40.', 'So 8 × 5 = 40 square feet.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m4-t3', title: 'Break the rug into two pieces', skill: 'Split a rectangle into two parts and add the areas',
    bigIdea: "Cut a big rectangle into two smaller ones, find each area, then add them.",
    screens: [
      { title: 'A long rug', text: 'A rug is 7 tiles long and 3 tiles wide. How much space does it cover?',
        pictures: [{ kind: 'grid', rows: 3, cols: 7, top: '7', left: '3' }] },
      { title: "A fact you may not know", text: "The area is 3 \u00d7 7. Do you know that fact yet? That's okay if not. But you know 3 \u00d7 5, and 3 \u00d7 2.",
        beats: [
          { say: "The area is 3 \u00d7 7.", pic: 0 },
          { say: "Do you know that fact yet? That's okay if not." },
          { say: "But you know 3 \u00d7 5, and 3 \u00d7 2." },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 7, top: '7', left: '3' }] },
      { title: "The big idea", text: "Cut a big rectangle into two smaller ones, find each area, then add them.",
        beats: [
          { say: "Cut a big rectangle into two smaller ones, find each area, then add them.", pic: 0 },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 7, split: { col: 5 }, shade: [{ r: 0, c: 0, h: 3, w: 5, tone: 1 }, { r: 0, c: 5, h: 3, w: 2, tone: 2 }] }] },
      { title: "Cut the rug", text: "So let's cut it, right after 5 tiles. Now there are two smaller rugs. One is 3 by 5, and one is 3 by 2.",
        beats: [
          { say: "So let's cut it, right after 5 tiles.", pic: 0 },
          { say: "Now there are two smaller rugs." },
          { say: "One is 3 by 5, and one is 3 by 2." },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 7, split: { col: 5 }, motion: true,
          shade: [{ r: 0, c: 0, h: 3, w: 5, tone: 1 }, { r: 0, c: 5, h: 3, w: 2, tone: 2 }] }] },
      { title: "Find each piece", text: "Now find each one. The first is 3 rows of 5. That's 15. The second is 3 rows of 2. That's 6.",
        beats: [
          { say: "Now find each one.", pic: 0 },
          { say: "The first is 3 rows of 5. That's 15.", pic: 1 },
          { say: "The second is 3 rows of 2. That's 6." },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 7, split: { col: 5 }, shade: [{ r: 0, c: 0, h: 3, w: 5, tone: 1 }, { r: 0, c: 5, h: 3, w: 2, tone: 2 }] },
          { kind: 'eq', text: '3 × 5 = 15', lines: ['3 × 2 = 6'] }] },
      { title: "Add the pieces", text: "Now put the pieces back together. 15 + 6 = 21. So 3 \u00d7 7 = 21. The rug covers 21 square units.",
        beats: [
          { say: "Now put the pieces back together." },
          { say: "15 + 6 = 21. So 3 \u00d7 7 = 21.", pic: 0 },
          { say: "The rug covers 21 square units." },
        ],
        pictures: [{ kind: 'eq', text: '3 × 7 = 3 × 5 + 3 × 2', lines: ['= 15 + 6', '= 21'] }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't STOP after one piece. 3 \u00d7 5 = 15 is only part of the rug. Add the other piece, and 15 + 6 = 21. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't STOP after one piece.", pic: 0 },
          { say: "3 \u00d7 5 = 15 is only part of the rug. Add the other piece, and 15 + 6 = 21." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '3 × 7 = 15', right: '3 × 7 = 15 + 6 = 21' }] },
    ],
    turn: {
      text: 'A rug is 8 tiles long and 3 tiles wide. Cut it after 5 tiles. What is its area?',
      picture: { kind: 'grid', rows: 3, cols: 8, top: '8', left: '3', split: { col: 5 }, shade: [{ r: 0, c: 0, h: 3, w: 5, tone: 1 }, { r: 0, c: 5, h: 3, w: 3, tone: 2 }] },
      answer: 24, steps: ['Cut after 5 tiles. The pieces are 3 by 5 and 3 by 3.', '3 × 5 = 15 and 3 × 3 = 9.', '15 + 9 = 24, so the area is 24 square units.'],
      prompt: 'Find the area of each piece. Then add the two pieces.',
      hint1: 'What is the area of each piece? Then add them.',
      hint2: 'The pieces are 3 × 5 and 3 × 3. Find each one, then add.',
      twin: { text: 'A rug is 7 tiles long and 4 tiles wide. Cut it after 5 tiles. What is its area?',
        picture: { kind: 'grid', rows: 4, cols: 7, top: '7', left: '4', split: { col: 5 }, shade: [{ r: 0, c: 0, h: 4, w: 5, tone: 1 }, { r: 0, c: 5, h: 4, w: 2, tone: 2 }] },
        answer: 28, steps: ['Cut after 5 tiles. The pieces are 4 by 5 and 4 by 2.', '4 × 5 = 20 and 4 × 2 = 8.', '20 + 8 = 28, so the area is 28 square units.'],
        hint1: 'Find the area of each piece. Then add the two areas.', hint2: 'The pieces are 4 × 5 and 4 × 2. Find each one, then add.' },
    },
    won: { text: 'You broke a hard fact into two easy pieces and added them.', sticker: 'Breaking a times fact into two easier facts is called the distributive property.' },
    twinWon: { text: 'You cut the rug after 5 tiles and added the two pieces to get 28.', sticker: 'Breaking a times fact into two easier facts is called the distributive property.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A rug is 6 tiles long and 3 tiles wide. Cut it after 5 tiles. What is its area?',
        picture: { kind: 'grid', rows: 3, cols: 6, top: '6', left: '3', split: { col: 5 }, shade: [{ r: 0, c: 0, h: 3, w: 5, tone: 1 }, { r: 0, c: 5, h: 3, w: 1, tone: 2 }] }, answer: 18,
        steps: ['The pieces are 3 by 5 and 3 by 1.', '3 × 5 = 15 and 3 × 1 = 3.', '15 + 3 = 18 square units.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A rug is 8 tiles long and 4 tiles wide. Cut it after 5 tiles. What is its area?',
        picture: { kind: 'grid', rows: 4, cols: 8, top: '8', left: '4', split: { col: 5 }, shade: [{ r: 0, c: 0, h: 4, w: 5, tone: 1 }, { r: 0, c: 5, h: 4, w: 3, tone: 2 }] }, answer: 32,
        steps: ['The pieces are 4 by 5 and 4 by 3.', '4 × 5 = 20 and 4 × 3 = 12.', '20 + 12 = 32 square units.'] } },
      { why: 'Still "two pieces, then add"', problem: { text: 'A rug is 7 tiles long and 6 tiles wide. Cut it after 5 tiles. What is its area?',
        picture: { kind: 'grid', rows: 6, cols: 7, top: '7', left: '6', split: { col: 5 }, shade: [{ r: 0, c: 0, h: 6, w: 5, tone: 1 }, { r: 0, c: 5, h: 6, w: 2, tone: 2 }] }, answer: 42,
        steps: ['The pieces are 6 by 5 and 6 by 2.', '6 × 5 = 30 and 6 × 2 = 12.', '30 + 12 = 42 square units.'] } },
      { why: 'A little harder', problem: { text: 'A rug is 8 tiles long and 7 tiles wide. Cut it after 5 tiles. What is its area?',
        picture: { kind: 'grid', rows: 7, cols: 8, top: '8', left: '7', split: { col: 5 }, shade: [{ r: 0, c: 0, h: 7, w: 5, tone: 1 }, { r: 0, c: 5, h: 7, w: 3, tone: 2 }] }, answer: 56,
        steps: ['The pieces are 7 by 5 and 7 by 3.', '7 × 5 = 35 and 7 × 3 = 21.', '35 + 21 = 56 square units.'] } },
      { why: 'Same math in a story', problem: { text: 'Nina tiles a patio 9 tiles long and 4 tiles wide. The first 5 tiles of each row are gray and the rest are white. How many tiles does she use in all?',
        picture: { kind: 'grid', rows: 4, cols: 9, split: { col: 5 }, shade: [{ r: 0, c: 0, h: 4, w: 5, tone: 3 }, { r: 0, c: 5, h: 4, w: 4, tone: 2 }] }, answer: 36,
        steps: ['The gray part is 4 by 5 and the white part is 4 by 4.', '4 × 5 = 20 gray tiles and 4 × 4 = 16 white tiles.', '20 + 16 = 36, so Nina uses 36 tiles.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m4-t4', title: 'An L-shaped room', skill: 'Area of a shape made of two rectangles',
    bigIdea: "Cut the L into two rectangles, find the area of each, then add.",
    screens: [
      { title: 'A room shaped like an L', text: 'This room is shaped like the letter L. Each tile is 1 square foot. How many square feet of carpet cover the floor?',
        pictures: [{ kind: 'grid', rows: 5, cols: 6, top: '6 ft', left: '5 ft', hide: [{ r: 0, c: 3, h: 2, w: 3 }] }] },
      { title: "It is not one rectangle", text: "Can you just multiply the rows by one row? Not here. Look at the rows. The top 2 rows have 3 tiles. The bottom 3 have 6.",
        beats: [
          { say: "Can you just multiply the rows by one row? Not here.", pic: 0 },
          { say: "Look at the rows." },
          { say: "The top 2 rows have 3 tiles. The bottom 3 have 6." },
        ],
        pictures: [{ kind: 'grid', rows: 5, cols: 6, hide: [{ r: 0, c: 3, h: 2, w: 3 }] }] },
      { title: "The big idea", text: "Cut the L into two rectangles, find the area of each, then add.",
        beats: [
          { say: "Cut the L into two rectangles, find the area of each, then add.", pic: 0 },
        ],
        pictures: [{ kind: 'grid', rows: 5, cols: 6, hide: [{ r: 0, c: 3, h: 2, w: 3 }], split: { col: 3 },
          shade: [{ r: 0, c: 0, h: 5, w: 3, tone: 1 }, { r: 2, c: 3, h: 3, w: 3, tone: 2 }] }] },
      { title: "Cut it into two rectangles", text: "So draw a line down, after 3 tiles. Now there are two rectangles. A tall one on the left, and a short one.",
        beats: [
          { say: "So draw a line down, after 3 tiles.", pic: 0 },
          { say: "Now there are two rectangles." },
          { say: "A tall one on the left, and a short one." },
        ],
        pictures: [{ kind: 'grid', rows: 5, cols: 6, hide: [{ r: 0, c: 3, h: 2, w: 3 }], split: { col: 3 }, motion: true,
          shade: [{ r: 0, c: 0, h: 5, w: 3, tone: 1 }, { r: 2, c: 3, h: 3, w: 3, tone: 2 }] }] },
      { title: "Find each area", text: "Now take them one at a time. The tall one is 5 rows of 3. That's 15. The short one is 3 rows of 3. That's 9.",
        beats: [
          { say: "Now take them one at a time.", pic: 0 },
          { say: "The tall one is 5 rows of 3. That's 15.", pic: 1 },
          { say: "The short one is 3 rows of 3. That's 9." },
        ],
        pictures: [{ kind: 'grid', rows: 5, cols: 6, hide: [{ r: 0, c: 3, h: 2, w: 3 }], split: { col: 3 },
          shade: [{ r: 0, c: 0, h: 5, w: 3, tone: 1 }, { r: 2, c: 3, h: 3, w: 3, tone: 2 }] },
          { kind: 'eq', text: '5 × 3 = 15', lines: ['3 × 3 = 9'] }] },
      { title: "Add the two parts", text: "Now put the two parts together. 15 + 9 = 24. So the room needs 24 square feet of carpet.",
        beats: [
          { say: "Now put the two parts together." },
          { say: "15 + 9 = 24.", pic: 0 },
          { say: "So the room needs 24 square feet of carpet." },
        ],
        pictures: [{ kind: 'eq', text: '15 + 9 = 24', lines: ['24 square feet'] }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't multiply the two LONGEST sides. 5 \u00d7 6 = 30 counts the missing corner too, where there is no floor. Find each part and add them. 15 + 9 = 24. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't multiply the two LONGEST sides. 5 \u00d7 6 = 30 counts the missing corner too, where there is no floor.", pic: 0 },
          { say: "Find each part and add them. 15 + 9 = 24.", pic: 1 },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'grid', rows: 5, cols: 6, top: '6 ft', left: '5 ft', hide: [{ r: 0, c: 3, h: 2, w: 3 }] },
          { kind: 'cards', wrong: '5 × 6 = 30', right: '15 + 9 = 24' }] },
    ],
    turn: {
      text: 'Each tile is 1 square foot. How many square feet is this L-shaped room?',
      picture: { kind: 'grid', rows: 4, cols: 6, hide: [{ r: 0, c: 3, h: 2, w: 3 }], split: { col: 3 } },
      answer: 18, steps: ['Cut the room along the dashed line into two rectangles.', 'The tall part is 4 × 3 = 12. The short part is 2 × 3 = 6.', '12 + 6 = 18, so the room is 18 square feet.'],
      prompt: 'Cut the room into two rectangles. Find each area, then add.',
      hint1: 'Cut the room into two rectangles. Find the area of each one.',
      hint2: 'The tall part is 4 rows of 3. The short part is 2 rows of 3. Add their areas.',
      twin: { text: 'Each tile is 1 square foot. How many square feet is this L-shaped room?',
        picture: { kind: 'grid', rows: 5, cols: 5, hide: [{ r: 0, c: 2, h: 3, w: 3 }], split: { col: 2 } },
        answer: 16, steps: ['Cut the room along the dashed line into two rectangles.', 'The tall part is 5 × 2 = 10. The short part is 2 × 3 = 6.', '10 + 6 = 16, so the room is 16 square feet.'],
        hint1: 'Cut the room into two rectangles. Find the area of each one.', hint2: 'The tall part is 5 rows of 2. The short part is 2 rows of 3. Add their areas.' },
    },
    won: { text: 'You cut the L into two rectangles, found each area, and added.', sticker: 'A shape made of smaller shapes is a composite shape. Its area is the parts added together.' },
    twinWon: { text: 'You cut the room into two rectangles and added them to get 16 square feet.', sticker: 'A shape made of smaller shapes is a composite shape. Its area is the parts added together.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Each tile is 1 square foot. How many square feet is this L-shaped room?',
        picture: { kind: 'grid', rows: 4, cols: 5, hide: [{ r: 0, c: 2, h: 2, w: 3 }], split: { col: 2 } }, answer: 14,
        steps: ['Cut along the dashed line into two rectangles.', 'The tall part is 4 × 2 = 8. The short part is 2 × 3 = 6.', '8 + 6 = 14 square feet.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Each tile is 1 square foot. How many square feet is this L-shaped room?',
        picture: { kind: 'grid', rows: 6, cols: 5, hide: [{ r: 0, c: 3, h: 3, w: 2 }], split: { col: 3 } }, answer: 24,
        steps: ['Cut along the dashed line into two rectangles.', 'The tall part is 6 × 3 = 18. The short part is 3 × 2 = 6.', '18 + 6 = 24 square feet.'] } },
      { why: 'Still "two rectangles, then add"', problem: { text: 'Each tile is 1 square unit. What is the area of this L-shape in square units?',
        picture: { kind: 'grid', rows: 5, cols: 7, hide: [{ r: 3, c: 4, h: 2, w: 3 }], split: { col: 4 } }, answer: 29,
        steps: ['Cut along the dashed line into two rectangles.', 'The tall part is 5 × 4 = 20. The short part is 3 × 3 = 9.', '20 + 9 = 29 square units.'] } },
      { why: 'A little harder', problem: { text: 'Each tile is 1 square foot. How many square feet is this L-shaped room?',
        picture: { kind: 'grid', rows: 8, cols: 9, hide: [{ r: 0, c: 5, h: 4, w: 4 }], split: { col: 5 } }, answer: 56,
        steps: ['Cut along the dashed line into two rectangles.', 'The tall part is 8 × 5 = 40. The short part is 4 × 4 = 16.', '40 + 16 = 56 square feet.'] } },
      { why: 'Same math in a story', problem: { text: "Mia's bedroom is shaped like an L. Each tile is 1 square foot. How many square feet of carpet does she need?",
        picture: { kind: 'grid', rows: 6, cols: 8, hide: [{ r: 0, c: 4, h: 2, w: 4 }], split: { col: 4 } }, answer: 40,
        steps: ['Cut the room along the dashed line into two rectangles.', 'The tall part is 6 × 4 = 24. The short part is 4 × 4 = 16.', '24 + 16 = 40, so Mia needs 40 square feet.'] } },
    ],
  },
]

attachChalk(G3M4, G3M4_CHALK)
