/** Grade 3 · Module 5 — Fractions as numbers. Written to docs/new-flow/AUTHORING.md. */
import type { Lesson } from '../script'

const YES_NO = ['yes', 'no']

export const G3M5: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t1', title: 'Cut the sandwich fairly', skill: 'Equal parts of a whole',
    bigIdea: 'Fair pieces are all the same size. Count the pieces only when they are equal.',
    screens: [
      { title: 'Sharing a sandwich', text: 'You and a friend share one sandwich. It is cut into 2 pieces. Is that fair?',
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }] }] }] },
      { title: 'Two pieces is not enough to know', text: 'So it is cut into 2 pieces. But knowing it is 2 pieces is not enough. Look at this one. One piece is big and one is small. Whoever gets that little piece is not going to be happy.',
        beats: [
          { say: 'So it is cut into 2 pieces. But knowing it is 2 pieces is not enough.' },
          { say: 'Look at this one. One piece is big and one is small.', pic: 0, effect: 'draw' },
          { say: 'Whoever gets that little piece is not going to be happy.', write: 'counting the pieces is not enough' },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 3, shade: true }, { w: 1 }] }] }] },
      { title: 'The big idea', text: 'Fair pieces are all the same size. Count the pieces only when they are equal.',
        beats: [
          { say: 'Fair pieces are all the same size.', pic: 0, effect: 'draw' },
          { say: 'Count the pieces only when they are equal.' },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }] }] }] },
      { title: 'Cut down the middle', text: "Now watch. I'll cut the sandwich right down the middle. Both pieces are the same size, so they match. That is 2 fair pieces, one for each of you.",
        beats: [
          { say: "Now watch. I'll cut the sandwich right down the middle.", pic: 0, effect: 'draw' },
          { say: 'Both pieces are the same size, so they match.' },
          { say: 'That is 2 fair pieces, one for each of you.', write: 'fair = every piece matches' },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 1, shade: true }, { w: 1 }] }], motion: true }] },
      { title: 'More friends, more cuts', text: 'What if 4 friends want some? Then we cut 4 pieces, and they all have to be the same size. Each friend gets 1 of the 4 equal pieces.',
        beats: [
          { say: 'What if 4 friends want some?' },
          { say: 'Then we cut 4 pieces, and they all have to be the same size.', pic: 0, effect: 'draw' },
          { say: 'Each friend gets 1 of the 4 equal pieces.', write: 'more friends → more equal pieces' },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 1, shade: true }, { w: 1 }, { w: 1 }, { w: 1 }] }], motion: true }] },
      { title: 'Check with your eyes', text: 'Here is how you check, and you can do it with just your eyes. Put the pieces side by side and look down the row. If every piece matches, the cut is fair. If even one is bigger, it is not.',
        beats: [
          { say: 'Here is how you check, and you can do it with just your eyes.' },
          { say: 'Put the pieces side by side and look down the row.', pic: 0, effect: 'draw' },
          { say: 'If every piece matches, the cut is fair. If even one is bigger, it is not.' },
        ],
        pictures: [{ kind: 'tape', rows: [
          { label: 'Fair', cells: [{ w: 1 }, { w: 1 }, { w: 1 }] },
          { label: 'Not fair', cells: [{ w: 1.6 }, { w: 0.7 }, { w: 0.7 }] },
        ] }] },
      { title: 'One thing not to do', text: "Here is the trap almost everybody falls into. Don't just count the pieces and call it fair. 4 pieces are not fair if some of them are bigger than the others.",
        beats: [
          { say: 'Here is the trap almost everybody falls into.' },
          { say: "Don't just count the pieces and call it fair.", pic: 0 },
          { say: '4 pieces are not fair if some of them are bigger than the others.' },
        ],
        pictures: [{ kind: 'cards', wrong: '4 pieces of any size', right: '4 pieces, all the same size' }] },
    ],
    turn: {
      text: 'This sandwich is cut into 3 pieces. Are the pieces fair?',
      picture: { kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 2 }, { w: 1 }] }] },
      answer: { choices: YES_NO, correct: 1 },
      steps: ['Look at the size of each piece.', 'The middle piece is bigger than the two end pieces.', 'The pieces are not the same size, so the answer is no.'],
      prompt: 'Look at every piece. Fair pieces are all the same size.',
      hint1: 'Are all the pieces the same size?',
      hint2: 'Compare the middle piece with the pieces at the ends.',
      twin: { text: 'This bar is cut into 6 pieces. Are the pieces fair?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }] }] },
        answer: { choices: YES_NO, correct: 0 },
        steps: ['Look at the size of each piece.', 'Every piece is just as wide as the one next to it.', 'The pieces all match, so the answer is yes.'],
        hint1: 'Look at each piece. Do they all match?',
        hint2: 'Put your finger on each piece and compare it with the next one.' },
    },
    won: { text: 'You checked the size of every piece before you said fair.', sticker: 'Pieces that are all the same size are called equal parts.' },
    twinWon: { text: 'You checked that all 6 pieces were the same size.', sticker: 'Pieces that are all the same size are called equal parts.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A sandwich is cut into 2 pieces. Are the pieces fair?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }] }] }, answer: { choices: YES_NO, correct: 0 },
        steps: ['Look at the two pieces.', 'They are the same size.', 'Both pieces match, so the answer is yes.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A granola bar is cut into 4 pieces. Are the pieces fair?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }, { w: 2 }, { w: 1 }] }] }, answer: { choices: YES_NO, correct: 1 },
        steps: ['Look at the size of each piece.', 'One piece is twice as wide as the others.', 'The pieces are not the same size, so the answer is no.'] } },
      { why: 'Still "same-size pieces"', problem: { text: 'This bar is cut into equal pieces. How many equal pieces are there?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }] }] }, answer: 8,
        steps: ['Every piece is the same size, so we can count them.', 'Count them: 1, 2, 3, 4, 5, 6, 7, 8.', 'There are 8 equal pieces.'] } },
      { why: 'A little harder', problem: { text: 'A pan of cornbread is cut into 6 pieces. Are the pieces fair?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }, { w: 1.5 }, { w: 0.5 }] }] }, answer: { choices: YES_NO, correct: 1 },
        steps: ['Look at the size of each piece, all the way to the end.', 'The last two pieces are not the same size as the others.', 'The pieces do not all match, so the answer is no.'] } },
      { why: 'Same math in a story', problem: { text: 'Ben cuts a long sub sandwich for 4 friends. The picture shows his cuts. Are the pieces fair?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }] }] }, answer: { choices: YES_NO, correct: 0 },
        steps: ['Look at the size of each piece.', 'All 4 pieces are the same size.', 'Every friend gets the same amount, so the answer is yes.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t2', title: 'One piece: 1/4', skill: 'One equal piece of a whole',
    bigIdea: 'The bottom number tells how many equal pieces make the whole. One piece of 4 is 1/4.',
    screens: [
      { title: 'Lunch time', text: 'A sandwich is cut into 4 equal pieces. You eat 1 piece. How much of the sandwich did you eat?',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 1 }] }] },
      { title: 'It is not just "1"', text: 'You ate 1 piece. But careful, that is not 1 whole sandwich. So we need a way to say 1 piece out of 4 equal pieces.',
        beats: [
          { say: 'You ate 1 piece.', pic: 0, effect: 'draw' },
          { say: 'But careful, that is not 1 whole sandwich.', write: '1 piece is not 1 whole' },
          { say: 'So we need a way to say 1 piece out of 4 equal pieces.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 1 }] }] },
      { title: 'The big idea', text: 'The bottom number tells how many equal pieces make the whole. One piece of 4 is 1/4.',
        beats: [
          { say: 'The bottom number tells how many equal pieces make the whole.', pic: 0, effect: 'draw' },
          { say: 'One piece of 4 is 1/4.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 1 }] }] },
      { title: 'Count the equal pieces', text: 'Start with the whole sandwich. It is cut into 4 equal pieces, so count them: 1, 2, 3, 4. That 4 goes on the bottom.',
        beats: [
          { say: 'Start with the whole sandwich.', pic: 0, effect: 'draw' },
          { say: 'It is cut into 4 equal pieces, so count them: 1, 2, 3, 4.' },
          { say: 'That 4 goes on the bottom.', write: 'bottom = all the equal pieces' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 1, shaded: 0, split: 4 }], motion: true }] },
      { title: 'Count the piece you ate', text: 'Now the piece you ate. That is just 1 piece, the shaded one. So the 1 goes on top.',
        beats: [
          { say: 'Now the piece you ate.', pic: 0, effect: 'draw' },
          { say: 'That is just 1 piece, the shaded one.' },
          { say: 'So the 1 goes on top.', write: 'top = the pieces you have' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 1 }], motion: true }] },
      { title: 'Write it', text: 'So we put the two numbers together. We write 1/4, and we say "one fourth". It means 1 of 4 equal pieces.',
        beats: [
          { say: 'So we put the two numbers together.', pic: 0, effect: 'draw' },
          { say: 'We write 1/4, and we say "one fourth".', pic: 1 },
          { say: 'It means 1 of 4 equal pieces.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 1, label: '1/4' }] }, { kind: 'eq', text: '1/4' }] },
      { title: 'One thing not to do', text: "Here is the one that trips people up. Don't put the pieces that are left over on the bottom. 3 pieces are left, but the sandwich was cut into 4. So it is 1/4, not 1/3.",
        beats: [
          { say: 'Here is the one that trips people up.' },
          { say: "Don't put the pieces that are left over on the bottom.", pic: 0 },
          { say: '3 pieces are left, but the sandwich was cut into 4. So it is 1/4, not 1/3.' },
        ],
        pictures: [{ kind: 'cards', wrong: '1/3', right: '1/4' }] },
    ],
    turn: {
      text: 'A bar is cut into 6 equal pieces. 1 piece is shaded. How much of the bar is shaded?',
      picture: { kind: 'bars', bars: [{ parts: 6, shaded: 1 }] },
      answer: { frac: [1, 6] },
      steps: ['The bar is cut into 6 equal pieces, so 6 goes on the bottom.', '1 piece is shaded, so 1 goes on the top.', 'So the answer is 1/6.'],
      prompt: 'Count all the equal pieces for the bottom. Count the shaded piece for the top.',
      hint1: 'How many equal pieces is the whole bar cut into?',
      hint2: 'The shaded piece is 1 of those pieces. Put the 1 on top.',
      twin: { text: 'A pizza strip is cut into 3 equal pieces. You eat 1 piece. How much of the strip did you eat?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 1 }] },
        answer: { frac: [1, 3] },
        steps: ['The strip is cut into 3 equal pieces, so 3 goes on the bottom.', 'You ate 1 piece, so 1 goes on the top.', 'So the answer is 1/3.'],
        hint1: 'How many equal pieces is the strip cut into?',
        hint2: 'You ate 1 piece. That number goes on top.' },
    },
    won: { text: 'You counted the equal pieces for the bottom and the shaded piece for the top.', sticker: 'One equal piece, like 1/6, is called a unit fraction.' },
    twinWon: { text: 'You found 1 piece out of 3 equal pieces.', sticker: 'One equal piece, like 1/3, is called a unit fraction.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A sandwich is cut into 2 equal pieces. You eat 1 piece. How much did you eat?',
        picture: { kind: 'bars', bars: [{ parts: 2, shaded: 1 }] }, answer: { frac: [1, 2] },
        steps: ['The sandwich is cut into 2 equal pieces, so 2 goes on the bottom.', 'You ate 1 piece, so 1 goes on the top.', 'So the answer is 1/2.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A bar is cut into 8 equal pieces. 1 piece is shaded. How much of the bar is shaded?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 1 }] }, answer: { frac: [1, 8] },
        steps: ['The bar is cut into 8 equal pieces, so 8 goes on the bottom.', '1 piece is shaded, so 1 goes on the top.', 'So the answer is 1/8.'] } },
      { why: 'Still "one equal piece"', problem: { text: 'A cracker is cut into 4 equal pieces. 1 piece is shaded. How much of the cracker is shaded?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 1 }] }, answer: { frac: [1, 4] },
        steps: ['The cracker is cut into 4 equal pieces, so 4 goes on the bottom.', '1 piece is shaded, so 1 goes on the top.', 'So the answer is 1/4.'] } },
      { why: 'A little harder', problem: { text: 'A granola bar is cut into equal pieces. Each piece is 1/6 of the bar. How many pieces are there?',
        picture: { kind: 'bars', bars: [{ parts: 1, shaded: 0 }] }, answer: 6,
        steps: ['1/6 means 1 of 6 equal pieces.', 'The bottom number tells how many equal pieces make the whole bar.', 'So there are 6 pieces.'] } },
      { why: 'Same math in a story', problem: { text: 'Mia cuts a ribbon into 3 equal pieces. She gives 1 piece to Jo. How much of the ribbon does Jo get?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 1 }] }, answer: { frac: [1, 3] },
        steps: ['The ribbon is cut into 3 equal pieces, so 3 goes on the bottom.', 'Jo gets 1 piece, so 1 goes on the top.', 'So Jo gets 1/3 of the ribbon.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t3', title: 'Three pieces: 3/4', skill: 'More than one equal piece',
    bigIdea: 'The bottom number tells how many equal pieces make the whole. The top number tells how many pieces you have.',
    screens: [
      { title: 'A hungry lunch', text: 'A sandwich is cut into 4 equal pieces. You eat 3 pieces. How much of the sandwich did you eat?',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 3 }] }] },
      { title: 'More than one piece', text: 'You already know this part. 1 piece out of 4 is 1/4. But this time you ate more than 1 piece. So how do we write 3 of them?',
        beats: [
          { say: 'You already know this part. 1 piece out of 4 is 1/4.', pic: 0, effect: 'draw' },
          { say: 'But this time you ate more than 1 piece.' },
          { say: 'So how do we write 3 of them?' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 1, label: '1/4' }, { parts: 4, shaded: 3 }] }] },
      { title: 'The big idea', text: 'The bottom number tells how many equal pieces make the whole. The top number tells how many pieces you have.',
        beats: [
          { say: 'The bottom number tells how many equal pieces make the whole.', pic: 0, effect: 'draw' },
          { say: 'The top number tells how many pieces you have.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 3 }] }] },
      { title: 'The bottom is still 4', text: 'Nothing happened to the sandwich itself. It is still cut into the same 4 equal pieces. So the bottom number is still 4.',
        beats: [
          { say: 'Nothing happened to the sandwich itself.', pic: 0, effect: 'draw' },
          { say: 'It is still cut into the same 4 equal pieces.' },
          { say: 'So the bottom number is still 4.', write: 'taking more pieces does not change the bottom' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 1, shaded: 0, split: 4 }], motion: true }] },
      { title: 'Count the pieces you have', text: 'Now count the shaded pieces with me. 1, 2, 3. You have 3 pieces, so the top number is 3.',
        beats: [
          { say: 'Now count the shaded pieces with me.', pic: 0, effect: 'draw' },
          { say: '1, 2, 3.' },
          { say: 'You have 3 pieces, so the top number is 3.', write: 'top = how many you took' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 3 }], motion: true }] },
      { title: 'Write it', text: 'Now put the two numbers together. We write 3/4, and we say "three fourths". It means 3 of 4 equal pieces.',
        beats: [
          { say: 'Now put the two numbers together.', pic: 0, effect: 'draw' },
          { say: 'We write 3/4, and we say "three fourths".', pic: 1 },
          { say: 'It means 3 of 4 equal pieces.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 3, label: '3/4' }] }, { kind: 'eq', text: '3/4', lines: ['3 pieces you have', '4 equal pieces in the whole'] }] },
      { title: 'One thing not to do', text: "Watch out for this one. Don't put the piece that is left over on the bottom. 1 piece is left, but the whole thing was cut into 4. The bottom always counts all the pieces.",
        beats: [
          { say: 'Watch out for this one.' },
          { say: "Don't put the piece that is left over on the bottom.", pic: 0 },
          { say: '1 piece is left, but the whole thing was cut into 4. The bottom always counts all the pieces.' },
        ],
        pictures: [{ kind: 'cards', wrong: '3/1', right: '3/4' }] },
    ],
    turn: {
      text: 'A bar is cut into 6 equal pieces. 5 pieces are shaded. How much of the bar is shaded?',
      picture: { kind: 'bars', bars: [{ parts: 6, shaded: 5 }] },
      answer: { frac: [5, 6] },
      steps: ['The bar is cut into 6 equal pieces, so 6 goes on the bottom.', 'Count the shaded pieces: 1, 2, 3, 4, 5. So 5 goes on the top.', 'So the answer is 5/6.'],
      prompt: 'Count all the equal pieces for the bottom. Count the shaded pieces for the top.',
      hint1: 'How many equal pieces make the whole bar? That is the bottom.',
      hint2: 'Now count only the shaded pieces. That is the top.',
      twin: { text: 'A pan of brownies is cut into 8 equal pieces. 3 pieces are eaten. How much of the pan was eaten?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 3 }] },
        answer: { frac: [3, 8] },
        steps: ['The pan is cut into 8 equal pieces, so 8 goes on the bottom.', '3 pieces were eaten, so 3 goes on the top.', 'So the answer is 3/8.'],
        hint1: 'How many equal pieces is the whole pan cut into?',
        hint2: 'Count only the shaded pieces. That number goes on top.' },
    },
    won: { text: 'You counted all the pieces for the bottom and your pieces for the top.', sticker: 'The top number is called the numerator. It counts the pieces you have.' },
    twinWon: { text: 'You found 3 pieces out of 8 equal pieces.', sticker: 'The top number is called the numerator. It counts the pieces you have.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A sandwich is cut into 4 equal pieces. You eat 2 pieces. How much did you eat?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 2 }] }, answer: { frac: [2, 4] },
        steps: ['The sandwich is cut into 4 equal pieces, so 4 goes on the bottom.', 'You ate 2 pieces, so 2 goes on the top.', 'So the answer is 2/4.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A bar is cut into 3 equal pieces. 2 pieces are shaded. How much of the bar is shaded?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 2 }] }, answer: { frac: [2, 3] },
        steps: ['The bar is cut into 3 equal pieces, so 3 goes on the bottom.', '2 pieces are shaded, so 2 goes on the top.', 'So the answer is 2/3.'] } },
      { why: 'Still "count the pieces you have"', problem: { text: 'A bar is cut into 8 equal pieces. 5 pieces are shaded. How much of the bar is shaded?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 5 }] }, answer: { frac: [5, 8] },
        steps: ['The bar is cut into 8 equal pieces, so 8 goes on the bottom.', 'Count the shaded pieces: 1, 2, 3, 4, 5. So 5 goes on the top.', 'So the answer is 5/8.'] } },
      { why: 'A little harder', problem: { text: 'A bar is cut into 6 equal pieces. 2 pieces are white. How much of the bar is shaded?',
        picture: { kind: 'bars', bars: [{ parts: 6, shaded: 4 }] }, answer: { frac: [4, 6] },
        steps: ['The bar is cut into 6 equal pieces, so 6 goes on the bottom.', '2 of the 6 pieces are white, so 6 − 2 = 4 pieces are shaded.', 'So the answer is 4/6.'] } },
      { why: 'Same math in a story', problem: { text: 'Nia cuts a pizza into 8 equal slices. Her family eats 7 slices. How much of the pizza did they eat?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 7 }] }, answer: { frac: [7, 8] },
        steps: ['The pizza is cut into 8 equal slices, so 8 goes on the bottom.', 'They ate 7 slices, so 7 goes on the top.', 'So they ate 7/8 of the pizza.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t4', title: 'Fractions on a number line', skill: 'A fraction is a point on the number line',
    bigIdea: 'The line from 0 to 1 is one whole. Cut it into equal jumps, then count the jumps from 0.',
    screens: [
      { title: 'A walk to the park', text: 'The path from home to the park is cut into 4 equal parts. Home is 0 and the park is 1. You walk 3 parts. Where are you?',
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 4, labels: 'ends' }] },
      { title: 'No pieces to hold', text: 'This one is different. On a line there are no sandwich pieces to pick up and count. So how do we find 3 of the 4 parts?',
        beats: [
          { say: 'This one is different.' },
          { say: 'On a line there are no sandwich pieces to pick up and count.', pic: 0, effect: 'draw' },
          { say: 'So how do we find 3 of the 4 parts?' },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 4, labels: 'ends' }] },
      { title: 'The big idea', text: 'The line from 0 to 1 is one whole. Cut it into equal jumps, then count the jumps from 0.',
        beats: [
          { say: 'The line from 0 to 1 is one whole.', pic: 0, effect: 'draw' },
          { say: 'Cut it into equal jumps, then count the jumps from 0.' },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 4, labels: 'ends' }] },
      { title: 'Cut the whole into 4 jumps', text: 'The space from 0 all the way to 1 is one whole. So we cut it into 4 equal jumps. Every jump is exactly the same size, and each one is 1/4.',
        beats: [
          { say: 'The space from 0 all the way to 1 is one whole.', write: '0 to 1 is the whole' },
          { say: 'So we cut it into 4 equal jumps.', pic: 0, effect: 'draw' },
          { say: 'Every jump is exactly the same size, and each one is 1/4.' },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 4, labels: 'ends', motion: true,
          jumps: [{ from: 0, to: 0.25, label: '1/4' }, { from: 0.25, to: 0.5, label: '1/4' }, { from: 0.5, to: 0.75, label: '1/4' }, { from: 0.75, to: 1, label: '1/4' }] }] },
      { title: 'Take 3 jumps', text: 'Now put your finger on 0 and jump with me. 1/4, 2/4, 3/4. And you land right there, on 3/4.',
        beats: [
          { say: 'Now put your finger on 0 and jump with me.', pic: 0, effect: 'draw' },
          { say: '1/4, 2/4, 3/4.' },
          { say: 'And you land right there, on 3/4.' },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 4, labels: ['0', '1/4', '2/4', '3/4', '1'], motion: true,
          jumps: [{ from: 0, to: 0.25 }, { from: 0.25, to: 0.5 }, { from: 0.5, to: 0.75 }], points: [{ at: 0.75 }] }] },
      { title: 'Every mark has a name', text: 'Every mark on this line has a name. The mark after 3 jumps is called 3/4. And it is a real number, just like 0 and 1 are.',
        beats: [
          { say: 'Every mark on this line has a name.', pic: 0, effect: 'draw' },
          { say: 'The mark after 3 jumps is called 3/4.' },
          { say: 'And it is a real number, just like 0 and 1 are.', write: 'a fraction is a number' },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 4, labels: ['0', '1/4', '2/4', '3/4', '1'], points: [{ at: 0.75, label: '3/4' }] }] },
      { title: 'One thing not to do', text: "Here is the thing to be careful about. The jumps have to be the same size, every single one. Jumps of different sizes don't count as fourths at all.",
        beats: [
          { say: 'Here is the thing to be careful about.' },
          { say: 'The jumps have to be the same size, every single one.', pic: 0 },
          { say: "Jumps of different sizes don't count as fourths at all." },
        ],
        pictures: [{ kind: 'cards', wrong: 'Jumps of different sizes', right: 'Jumps all the same size' }] },
    ],
    turn: {
      text: 'This line from 0 to 1 is cut into 6 equal jumps. Which fraction is at the dot?',
      picture: { kind: 'numline', min: 0, max: 1, ticks: 6, labels: 'ends', points: [{ at: 5 / 6 }] },
      answer: { frac: [5, 6] },
      steps: ['The line is cut into 6 equal jumps, so the bottom number is 6.', 'Count the jumps from 0 to the dot: 1, 2, 3, 4, 5.', 'So the dot is at 5/6.'],
      prompt: 'Count the equal jumps from 0 to 1 for the bottom. Count the jumps to the dot for the top.',
      hint1: 'How many equal jumps go from 0 to 1?',
      hint2: 'Start at 0 and count the jumps until you reach the dot.',
      twin: { text: 'This line from 0 to 1 is cut into 3 equal jumps. Which fraction is at the dot?',
        picture: { kind: 'numline', min: 0, max: 1, ticks: 3, labels: 'ends', points: [{ at: 2 / 3 }] },
        answer: { frac: [2, 3] },
        steps: ['The line is cut into 3 equal jumps, so the bottom number is 3.', 'Count the jumps from 0 to the dot: 1, 2.', 'So the dot is at 2/3.'],
        hint1: 'How many equal jumps go from 0 to 1?',
        hint2: 'Start at 0. Count the jumps to the dot. The 0 is where you start, not a jump.' },
    },
    won: { text: 'You counted the equal jumps in the whole, then the jumps to the dot.', sticker: 'A fraction is a number. It has its own place on the number line.' },
    twinWon: { text: 'You counted 3 equal jumps in the whole, then the jumps to the dot.', sticker: 'A fraction is a number. It has its own place on the number line.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'This line from 0 to 1 is cut into 4 equal jumps. Which fraction is at the dot?',
        picture: { kind: 'numline', min: 0, max: 1, ticks: 4, labels: 'ends', points: [{ at: 0.5 }] }, answer: { frac: [2, 4] },
        steps: ['The line is cut into 4 equal jumps, so the bottom number is 4.', 'Count the jumps from 0 to the dot: 1, 2.', 'So the dot is at 2/4.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'This line from 0 to 1 is cut into 8 equal jumps. Which fraction is at the dot?',
        picture: { kind: 'numline', min: 0, max: 1, ticks: 8, labels: 'ends', points: [{ at: 5 / 8 }] }, answer: { frac: [5, 8] },
        steps: ['The line is cut into 8 equal jumps, so the bottom number is 8.', 'Count the jumps from 0 to the dot: 1, 2, 3, 4, 5.', 'So the dot is at 5/8.'] } },
      { why: 'Still "count equal jumps"', problem: { text: 'This line from 0 to 1 is cut into 2 equal jumps. Which fraction is at the dot?',
        picture: { kind: 'numline', min: 0, max: 1, ticks: 2, labels: 'ends', points: [{ at: 0.5 }] }, answer: { frac: [1, 2] },
        steps: ['The line is cut into 2 equal jumps, so the bottom number is 2.', 'The dot is 1 jump from 0.', 'So the dot is at 1/2.'] } },
      { why: 'A little harder', problem: { text: 'This line from 0 to 1 is cut into 8 equal jumps. The dot is 1 jump before 1. Which fraction is at the dot?',
        picture: { kind: 'numline', min: 0, max: 1, ticks: 8, labels: 'ends', points: [{ at: 7 / 8 }] }, answer: { frac: [7, 8] },
        steps: ['The line is cut into 8 equal jumps, so the bottom number is 8.', 'Getting to 1 takes 8 jumps. The dot is 1 jump before that, so 8 − 1 = 7 jumps.', 'So the dot is at 7/8.'] } },
      { why: 'Same math in a story', problem: { text: 'The path from the house to the gate is cut into 3 equal parts. The house is 0 and the gate is 1. Ava walks 1 part. The dot shows Ava. What fraction of the way has she walked?',
        picture: { kind: 'numline', min: 0, max: 1, ticks: 3, labels: 'ends', points: [{ at: 1 / 3 }] }, answer: { frac: [1, 3] },
        steps: ['The path is cut into 3 equal parts, so the bottom number is 3.', 'Ava walked 1 part from 0.', 'So she has walked 1/3 of the way.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t5', title: 'Same amount, different pieces', skill: 'Equal fractions cover the same amount',
    bigIdea: 'You can cut the same amount into smaller pieces. The amount stays the same.',
    screens: [
      { title: 'Two candy bars', text: 'These two candy bars are the same size. One is cut into 2 pieces, one into 4. Who has more chocolate?',
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1 }, { parts: 4, shaded: 2 }] }] },
      { title: 'The numbers look different', text: 'Look at the two names. 1/2 and 2/4. Every number in them is different. So it really looks like they should be different amounts.',
        beats: [
          { say: 'Look at the two names.', pic: 0, effect: 'draw' },
          { say: '1/2 and 2/4. Every number in them is different.' },
          { say: 'So it really looks like they should be different amounts.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1, label: '1/2' }, { parts: 4, shaded: 2, label: '2/4' }] }] },
      { title: 'The big idea', text: 'You can cut the same amount into smaller pieces. The amount stays the same.',
        beats: [
          { say: 'You can cut the same amount into smaller pieces.', pic: 0, effect: 'draw' },
          { say: 'The amount stays the same.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1 }, { parts: 4, shaded: 2 }] }] },
      { title: 'Half a bar', text: "Let's start with just one bar. I'll shade 1 of the 2 equal pieces. That much is 1/2 of the bar.",
        beats: [
          { say: "Let's start with just one bar.", pic: 0, effect: 'draw' },
          { say: "I'll shade 1 of the 2 equal pieces." },
          { say: 'That much is 1/2 of the bar.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1, label: '1/2' }], motion: true }] },
      { title: 'Cut each piece again', text: 'Now watch what I do to it. I cut each piece in 2, so the shaded part is now 2 pieces out of 4. But look, nothing was added and nothing was eaten.',
        beats: [
          { say: 'Now watch what I do to it.', pic: 0, effect: 'draw' },
          { say: 'I cut each piece in 2, so the shaded part is now 2 pieces out of 4.' },
          { say: 'But look, nothing was added and nothing was eaten.', write: 'cutting does not change the amount' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1, split: 2 }], motion: true }] },
      { title: 'They match', text: 'Now stack the two bars, one right above the other. See where the shading stops. Both of them stop at exactly the same place. So 1/2 and 2/4 are the same amount.',
        beats: [
          { say: 'Now stack the two bars, one right above the other.', pic: 0, effect: 'draw' },
          { say: 'See where the shading stops. Both of them stop at exactly the same place.' },
          { say: 'So 1/2 and 2/4 are the same amount.', pic: 1 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1, label: '1/2' }, { parts: 4, shaded: 2, label: '2/4' }] }, { kind: 'eq', text: '1/2 = 2/4' }] },
      { title: 'One thing not to do', text: "Here is the mistake to watch for. Don't change only one of the numbers. 1/2 is not 1/4. When the pieces get smaller, you need more of them to cover the same amount.",
        beats: [
          { say: 'Here is the mistake to watch for.' },
          { say: "Don't change only one of the numbers. 1/2 is not 1/4.", pic: 0 },
          { say: 'When the pieces get smaller, you need more of them to cover the same amount.' },
        ],
        pictures: [{ kind: 'cards', wrong: '1/2 = 1/4', right: '1/2 = 2/4' }] },
    ],
    turn: {
      text: 'Do 2/3 and 4/6 cover the same amount?',
      picture: { kind: 'bars', bars: [{ parts: 3, shaded: 2, label: '2/3' }, { parts: 6, shaded: 4, label: '4/6' }] },
      answer: { choices: YES_NO, correct: 0 },
      steps: ['Both bars are the same size.', 'Each piece of the top bar is cut into 2 smaller pieces on the bottom bar.', 'The shading stops at the same place, so the answer is yes.'],
      prompt: 'The bars are the same size. Check if the shaded parts match.',
      hint1: 'Look at where the shading stops on each bar.',
      hint2: 'Each piece on the top bar was cut into 2 smaller pieces. Did the shaded amount change?',
      twin: { text: 'The top bar shows 1/4. The bottom bar is cut into 8 equal pieces. How many pieces do you shade to cover the same amount?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 1, label: '1/4' }, { parts: 8, shaded: 0 }] },
        answer: 2,
        steps: ['Each piece of the top bar sits over small pieces of the bottom bar.', 'Under the 1 shaded piece there are 2 small pieces.', 'So you shade 2 pieces.'],
        hint1: 'Each piece on the top bar sits over how many small pieces below?',
        hint2: 'Look under the shaded piece on top. Count the small pieces under it.' },
    },
    won: { text: 'You saw that 2/3 and 4/6 cover the same amount.', sticker: 'Fractions that cover the same amount are called equivalent fractions.' },
    twinWon: { text: 'You saw that 1/4 and 2/8 cover the same amount.', sticker: 'Fractions that cover the same amount are called equivalent fractions.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Do 1/3 and 2/6 cover the same amount?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 1, label: '1/3' }, { parts: 6, shaded: 2, label: '2/6' }] }, answer: { choices: YES_NO, correct: 0 },
        steps: ['Both bars are the same size.', 'The 1 shaded piece on top is cut into 2 smaller shaded pieces below.', 'The shading stops at the same place, so the answer is yes.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Do 1/2 and 3/8 cover the same amount?',
        picture: { kind: 'bars', bars: [{ parts: 2, shaded: 1, label: '1/2' }, { parts: 8, shaded: 3, label: '3/8' }] }, answer: { choices: YES_NO, correct: 1 },
        steps: ['1/2 stops in the middle of the bar.', '3/8 stops before the middle. It would take 4 of the 8 pieces to reach the middle.', 'They do not match, so the answer is no.'] } },
      { why: 'Still "same amount, smaller pieces"', problem: { text: 'The top bar shows 1/2. The bottom bar is cut into 6 equal pieces. How many pieces do you shade to cover the same amount?',
        picture: { kind: 'bars', bars: [{ parts: 2, shaded: 1, label: '1/2' }, { parts: 6, shaded: 0 }] }, answer: 3,
        steps: ['Half of the bar is the first half, up to the middle.', 'Count the small pieces up to the middle: 1, 2, 3.', 'So you shade 3 pieces.'] } },
      { why: 'A little harder', problem: { text: 'The top bar shows 3/4. The bottom bar is cut into 8 equal pieces. How many pieces do you shade to cover the same amount?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 3, label: '3/4' }, { parts: 8, shaded: 0 }] }, answer: 6,
        steps: ['Each piece of the top bar sits over 2 small pieces.', 'There are 3 shaded pieces on top, so 3 × 2 small pieces.', 'So you shade 6 pieces.'] } },
      { why: 'Same math in a story', problem: { text: 'Jay eats 2/4 of a pan of cornbread. Kim has a same-size pan cut into 8 equal pieces. How many pieces must Kim eat to eat the same amount?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 2, label: '2/4' }, { parts: 8, shaded: 0 }] }, answer: 4,
        steps: ["Each piece of Jay's pan is the size of 2 pieces of Kim's pan.", 'Jay ate 2 pieces, so Kim needs 2 × 2 pieces.', 'So Kim must eat 4 pieces.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t6', title: 'A whole pizza: 4/4 = 1', skill: 'All the pieces make 1 whole',
    bigIdea: 'When the top and bottom numbers are the same, you have all the pieces. That is 1 whole.',
    screens: [
      { title: 'Pizza night', text: 'A pizza is cut into 4 equal slices. Your family eats all 4 slices. How much of the pizza is gone?',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }] }] },
      { title: 'It is not 4 pizzas', text: 'So 4 slices were eaten. But careful, that is not 4 pizzas. It was one pizza the whole time, just cut into slices.',
        beats: [
          { say: 'So 4 slices were eaten.', pic: 0, effect: 'draw' },
          { say: 'But careful, that is not 4 pizzas.', write: '4 slices is not 4 pizzas' },
          { say: 'It was one pizza the whole time, just cut into slices.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }] }] },
      { title: 'The big idea', text: 'When the top and bottom numbers are the same, you have all the pieces. That is 1 whole.',
        beats: [
          { say: 'When the top and bottom numbers are the same, you have all the pieces.', pic: 0, effect: 'draw' },
          { say: 'That is 1 whole.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }] }] },
      { title: 'Count every slice', text: 'Count the slices along with me. 1/4, 2/4, 3/4, 4/4. And that is all 4 of the 4 pieces, every one of them.',
        beats: [
          { say: 'Count the slices along with me.', pic: 0, effect: 'draw' },
          { say: '1/4, 2/4, 3/4, 4/4.' },
          { say: 'And that is all 4 of the 4 pieces, every one of them.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }], motion: true }] },
      { title: 'All the pieces make one whole', text: 'Now look at the bar. Every bit of it is shaded, and nothing is left over. So 4/4 is exactly the same as 1 whole bar.',
        beats: [
          { say: 'Now look at the bar.', pic: 0, effect: 'draw' },
          { say: 'Every bit of it is shaded, and nothing is left over.' },
          { say: 'So 4/4 is exactly the same as 1 whole bar.', write: 'all the pieces → 1 whole' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4, label: '4/4' }, { parts: 1, shaded: 1, label: '1' }], motion: true }] },
      { title: 'Any whole works', text: 'And this works no matter how you cut it. Cut a bar into 6 equal pieces, and all 6 of them is 6/6. Cut it into 2, and both pieces is 2/2. Every one of those is 1 whole.',
        beats: [
          { say: 'And this works no matter how you cut it.' },
          { say: 'Cut a bar into 6 equal pieces, and all 6 of them is 6/6. Cut it into 2, and both pieces is 2/2.', pic: 0, effect: 'draw' },
          { say: 'Every one of those is 1 whole.', pic: 1 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 6, shaded: 6, label: '6/6' }, { parts: 2, shaded: 2, label: '2/2' }] }, { kind: 'eq', text: '6/6 = 2/2 = 1' }] },
      { title: 'One thing not to do', text: "Here is where the numbers fool you. Don't think the bigger numbers mean more. 8/8 is not more than 4/4. They are both exactly 1 whole.",
        beats: [
          { say: 'Here is where the numbers fool you.' },
          { say: "Don't think the bigger numbers mean more.", pic: 0 },
          { say: '8/8 is not more than 4/4. They are both exactly 1 whole.' },
        ],
        pictures: [{ kind: 'cards', wrong: '8/8 is more than 4/4', right: '8/8 = 4/4 = 1' }] },
    ],
    turn: {
      text: 'A bar is cut into 6 equal pieces. All the pieces are shaded. How much of the bar is shaded? Write it with a top and bottom number.',
      picture: { kind: 'bars', bars: [{ parts: 6, shaded: 6 }] },
      answer: { frac: [6, 6] },
      steps: ['The bar is cut into 6 equal pieces, so 6 goes on the bottom.', 'All 6 pieces are shaded, so 6 goes on the top.', 'So the answer is 6/6. That is 1 whole.'],
      prompt: 'Count all the pieces for the bottom. Count the shaded pieces for the top.',
      hint1: 'How many equal pieces are in the whole bar?',
      hint2: 'Count the shaded pieces. Are any pieces white?',
      twin: { text: 'A sandwich is cut into 3 equal pieces. How many pieces do you eat to eat the whole sandwich?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 0 }] },
        answer: 3,
        steps: ['The whole sandwich means every piece.', 'The sandwich is cut into equal pieces. Count them: 1, 2, 3.', 'So you eat 3 pieces.'],
        hint1: 'How many equal pieces is the sandwich cut into?',
        hint2: 'The whole sandwich means every piece. Count them all.' },
    },
    won: { text: 'You saw that all 6 of the 6 pieces make 1 whole.', sticker: 'A fraction with the same top and bottom number is equal to 1 whole.' },
    twinWon: { text: 'You saw that all 3 pieces make 1 whole sandwich.', sticker: 'A fraction like 3/3, with the same top and bottom number, is equal to 1 whole.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A sandwich is cut into 2 equal pieces. You eat both pieces. How much of the sandwich did you eat?',
        picture: { kind: 'bars', bars: [{ parts: 2, shaded: 2 }] }, answer: { frac: [2, 2] },
        steps: ['The sandwich is cut into 2 equal pieces, so 2 goes on the bottom.', 'You ate both pieces, so 2 goes on the top.', 'So the answer is 2/2. That is 1 whole.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A bar is cut into 3 equal pieces. All the pieces are shaded. How much of the bar is shaded?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 3 }] }, answer: { frac: [3, 3] },
        steps: ['The bar is cut into 3 equal pieces, so 3 goes on the bottom.', 'All 3 pieces are shaded, so 3 goes on the top.', 'So the answer is 3/3. That is 1 whole.'] } },
      { why: 'Still "all the pieces make 1"', problem: { text: 'This bar is cut into 4 equal pieces. How many fourths make 1 whole?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 0 }] }, answer: 4,
        steps: ['1 whole means every piece of the bar.', 'The bar is cut into equal pieces. Count them: 1, 2, 3, 4.', 'So 4 fourths make 1 whole.'] } },
      { why: 'A little harder', problem: { text: '6/? = 1. What number goes on the bottom?',
        picture: { kind: 'bars', bars: [{ parts: 1, shaded: 1 }] }, answer: 6,
        steps: ['1 whole means you have all the pieces.', 'So the top and bottom numbers are the same.', 'The bottom number is 6.'] } },
      { why: 'Same math in a story', problem: { text: 'Ms. Lee cuts a pan of cornbread into 8 equal pieces. The class eats all of them. How much of the pan did they eat?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 8 }] }, answer: { frac: [8, 8] },
        steps: ['The pan is cut into 8 equal pieces, so 8 goes on the bottom.', 'The class ate all 8 pieces, so 8 goes on the top.', 'So they ate 8/8 of the pan. That is 1 whole pan.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t7', title: 'Which is bigger? Same pieces cut', skill: 'Compare fractions with the same bottom number',
    bigIdea: 'When the pieces are the same size, more pieces is more. Just compare the top numbers.',
    screens: [
      { title: 'Two pizzas', text: 'Two same-size pizzas are each cut into 8 equal slices. Ana eats 3 slices. Ben eats 5 slices. Who ate more?',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 3, label: 'Ana' }, { parts: 8, shaded: 5, label: 'Ben' }] }] },
      { title: 'Both end in 8', text: 'Ana ate 3/8, and Ben ate 5/8. Notice that both bottom numbers are the same, an 8 and an 8. So what is left to tell us which one is bigger?',
        beats: [
          { say: 'Ana ate 3/8, and Ben ate 5/8.', pic: 0, effect: 'draw' },
          { say: 'Notice that both bottom numbers are the same, an 8 and an 8.' },
          { say: 'So what is left to tell us which one is bigger?' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 3, label: '3/8' }, { parts: 8, shaded: 5, label: '5/8' }] }] },
      { title: 'The big idea', text: 'When the pieces are the same size, more pieces is more. Just compare the top numbers.',
        beats: [
          { say: 'When the pieces are the same size, more pieces is more.', pic: 0, effect: 'draw' },
          { say: 'Just compare the top numbers.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 3, label: '3/8' }, { parts: 8, shaded: 5, label: '5/8' }] }] },
      { title: 'Same-size pieces', text: 'Look at the two pizzas first. Both of them are cut into 8 equal pieces. So every single piece is the same size, on both pizzas.',
        beats: [
          { say: 'Look at the two pizzas first.', pic: 0, effect: 'draw' },
          { say: 'Both of them are cut into 8 equal pieces.' },
          { say: 'So every single piece is the same size, on both pizzas.', write: 'same bottom → same size pieces' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 1, shaded: 0, split: 8 }, { parts: 1, shaded: 0, split: 8 }], motion: true }] },
      { title: 'Count the pieces', text: 'Now we just count. Ana has 3 pieces and Ben has 5 pieces. And 5 pieces of the same size is more than 3 of them.',
        beats: [
          { say: 'Now we just count.', pic: 0, effect: 'draw' },
          { say: 'Ana has 3 pieces and Ben has 5 pieces.' },
          { say: 'And 5 pieces of the same size is more than 3 of them.', write: 'same size pieces → more pieces wins' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 3, label: '3/8' }, { parts: 8, shaded: 5, label: '5/8' }], motion: true }] },
      { title: 'Write it', text: 'So 5/8 is bigger than 3/8. We write it like this, with the pointy sign in the middle. The open side of that sign always faces the bigger number.',
        beats: [
          { say: 'So 5/8 is bigger than 3/8.', pic: 0, effect: 'draw' },
          { say: 'We write it like this, with the pointy sign in the middle.', pic: 1 },
          { say: 'The open side of that sign always faces the bigger number.', write: 'open side faces the bigger number' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 5, label: '5/8' }, { parts: 8, shaded: 3, label: '3/8' }] }, { kind: 'eq', text: '5/8 > 3/8' }] },
      { title: 'One thing not to do', text: "One last warning. Don't look at the pieces that are left on the plate. Look only at the pieces each person actually has.",
        beats: [
          { say: 'One last warning.' },
          { say: "Don't look at the pieces that are left on the plate.", pic: 0 },
          { say: 'Look only at the pieces each person actually has.' },
        ],
        pictures: [{ kind: 'cards', wrong: '3/8 > 5/8', right: '5/8 > 3/8' }] },
    ],
    turn: {
      text: 'Which is bigger: 2/6 or 5/6?',
      picture: { kind: 'bars', bars: [{ parts: 6, shaded: 0, label: '2/6' }, { parts: 6, shaded: 0, label: '5/6' }] },
      answer: { choices: ['2/6', '5/6'], correct: 1 },
      steps: ['Both are cut into 6 equal pieces, so the pieces are the same size.', '5 pieces is more than 2 pieces.', 'So the bigger one is 5/6.'],
      prompt: 'The pieces are the same size. Compare how many pieces each one has.',
      hint1: 'Are the bottom numbers the same?',
      hint2: 'Shade 2 pieces on one bar and 5 on the other in your head. Which covers more?',
      twin: { text: 'Which is bigger: 3/4 or 1/4?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 0, label: '3/4' }, { parts: 4, shaded: 0, label: '1/4' }] },
        answer: { choices: ['3/4', '1/4'], correct: 0 },
        steps: ['Both are cut into 4 equal pieces, so the pieces are the same size.', '3 pieces is more than 1 piece.', 'So the bigger one is 3/4.'],
        hint1: 'Are the pieces the same size?',
        hint2: 'Compare the top numbers. Which one has more pieces?' },
    },
    won: { text: 'You compared the top numbers because the pieces were the same size.', sticker: '> means "is greater than". 5/6 > 2/6.' },
    twinWon: { text: 'You compared 3 pieces and 1 piece of the same size.', sticker: 'When the bottom numbers match, the bigger top number is the bigger fraction.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which is bigger: 3/8 or 6/8?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 0, label: '3/8' }, { parts: 8, shaded: 0, label: '6/8' }] }, answer: { choices: ['3/8', '6/8'], correct: 1 },
        steps: ['Both are cut into 8 equal pieces, so the pieces are the same size.', '6 pieces is more than 3 pieces.', 'So the bigger one is 6/8.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Which is bigger: 2/3 or 1/3?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 0, label: '2/3' }, { parts: 3, shaded: 0, label: '1/3' }] }, answer: { choices: ['2/3', '1/3'], correct: 0 },
        steps: ['Both are cut into 3 equal pieces, so the pieces are the same size.', '2 pieces is more than 1 piece.', 'So the bigger one is 2/3.'] } },
      { why: 'Still "same-size pieces"', problem: { text: 'Which sign goes in the middle? 4/6 ? 3/6',
        picture: { kind: 'bars', bars: [{ parts: 6, shaded: 0, label: '4/6' }, { parts: 6, shaded: 0, label: '3/6' }] }, answer: { choices: ['<', '>', '='], correct: 1 },
        steps: ['Both are cut into 6 equal pieces.', '4 pieces is more than 3 pieces, so 4/6 is bigger.', 'So 4/6 > 3/6.'] } },
      { why: 'A little harder', problem: { text: 'Which sign goes in the middle? 5/8 ? 7/8',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 0, label: '5/8' }, { parts: 8, shaded: 0, label: '7/8' }] }, answer: { choices: ['<', '>', '='], correct: 0 },
        steps: ['Both are cut into 8 equal pieces.', '5 pieces is fewer than 7 pieces, so 5/8 is smaller.', 'The open side faces the bigger number, so 5/8 < 7/8.'] } },
      { why: 'Same math in a story', problem: { text: 'Mia ran 3/4 of a mile. Leo ran 2/4 of a mile. Who ran farther?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 0, label: '3/4' }, { parts: 4, shaded: 0, label: '2/4' }] }, answer: { choices: ['Mia', 'Leo'], correct: 0 },
        steps: ['Both miles are cut into 4 equal parts.', 'Mia ran 3 parts and Leo ran 2 parts.', 'So Mia ran farther.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t8', title: 'Which is bigger? Same pieces taken', skill: 'Compare fractions with the same top number',
    bigIdea: 'When you take the same number of pieces, bigger pieces make more. Fewer cuts make bigger pieces.',
    screens: [
      { title: 'Two sandwiches', text: 'Two same-size sandwiches. One is cut into 3 equal pieces. One is cut into 8. You get 1 piece. Which piece is bigger: 1/3 or 1/8?',
        pictures: [{ kind: 'bars', bars: [{ parts: 3, shaded: 1, label: '1/3' }, { parts: 8, shaded: 1, label: '1/8' }] }] },
      { title: 'Bigger number, smaller piece', text: 'Now, 8 is a bigger number than 3. But here is the surprise. 1/8 is not bigger than 1/3. So this time we cannot just pick the bigger number.',
        beats: [
          { say: 'Now, 8 is a bigger number than 3.', pic: 0, effect: 'draw' },
          { say: 'But here is the surprise. 1/8 is not bigger than 1/3.' },
          { say: 'So this time we cannot just pick the bigger number.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 3, shaded: 1, label: '1/3' }, { parts: 8, shaded: 1, label: '1/8' }] }] },
      { title: 'The big idea', text: 'When you take the same number of pieces, bigger pieces make more. Fewer cuts make bigger pieces.',
        beats: [
          { say: 'When you take the same number of pieces, bigger pieces make more.', pic: 0, effect: 'draw' },
          { say: 'Fewer cuts make bigger pieces.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 3, shaded: 1, label: '1/3' }, { parts: 8, shaded: 1, label: '1/8' }] }] },
      { title: 'Cut into 3', text: "Let's cut a bar into just 3 equal pieces. Only two cuts, so each piece comes out nice and big.",
        beats: [
          { say: "Let's cut a bar into just 3 equal pieces.", pic: 0, effect: 'draw' },
          { say: 'Only two cuts, so each piece comes out nice and big.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 1, shaded: 0, split: 3 }], motion: true }] },
      { title: 'Cut into 8', text: 'Now here is the same bar again, cut into 8 equal pieces. Each piece is much smaller now. More cuts, smaller pieces. Remember that one.',
        beats: [
          { say: 'Now here is the same bar again, cut into 8 equal pieces.', pic: 0, effect: 'draw' },
          { say: 'Each piece is much smaller now.' },
          { say: 'More cuts, smaller pieces. Remember that one.', write: 'more cuts → smaller pieces' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 3, shaded: 1, label: '1/3' }, { parts: 8, shaded: 1, label: '1/8' }], motion: true }] },
      { title: 'Take 2 of each', text: 'Now take 2 pieces from each bar, so 2/3 and 2/8. The same number of pieces both times, but the pieces of 3 are bigger. So 2/3 is bigger, and we write it like this.',
        beats: [
          { say: 'Now take 2 pieces from each bar, so 2/3 and 2/8.', pic: 0, effect: 'draw' },
          { say: 'The same number of pieces both times, but the pieces of 3 are bigger.' },
          { say: 'So 2/3 is bigger, and we write it like this.', pic: 1 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 3, shaded: 2, label: '2/3' }, { parts: 8, shaded: 2, label: '2/8' }] }, { kind: 'eq', text: '2/3 > 2/8' }] },
      { title: 'One thing not to do', text: "Here is the trap, and it catches almost everyone. Don't just pick the bigger bottom number. A bigger bottom number means more cuts, so each piece is smaller.",
        beats: [
          { say: 'Here is the trap, and it catches almost everyone.' },
          { say: "Don't just pick the bigger bottom number.", pic: 0 },
          { say: 'A bigger bottom number means more cuts, so each piece is smaller.' },
        ],
        pictures: [{ kind: 'cards', wrong: '1/8 > 1/3', right: '1/3 > 1/8' }] },
    ],
    turn: {
      text: 'Which is bigger: 1/4 or 1/6?',
      picture: { kind: 'bars', bars: [{ parts: 4, shaded: 0, label: '1/4' }, { parts: 6, shaded: 0, label: '1/6' }] },
      answer: { choices: ['1/4', '1/6'], correct: 0 },
      steps: ['Both take 1 piece.', 'A bar cut into 4 has bigger pieces than a bar cut into 6.', 'So the bigger one is 1/4.'],
      prompt: 'Both take the same number of pieces. Find the bar with the bigger pieces.',
      hint1: 'Both take the same number of pieces. Which bar has bigger pieces?',
      hint2: 'Fewer cuts make bigger pieces. Which bar has fewer cuts?',
      twin: { text: 'Which is bigger: 3/8 or 3/4?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 0, label: '3/8' }, { parts: 4, shaded: 0, label: '3/4' }] },
        answer: { choices: ['3/8', '3/4'], correct: 1 },
        steps: ['Both take 3 pieces.', 'A bar cut into 4 has bigger pieces than a bar cut into 8.', 'So the bigger one is 3/4.'],
        hint1: 'Both take 3 pieces. Which bar has bigger pieces?',
        hint2: 'Compare the bottom numbers. Fewer cuts make bigger pieces.' },
    },
    won: { text: 'You took the same number of pieces and picked the bigger pieces.', sticker: 'Same top number: the smaller bottom number is the bigger fraction.' },
    twinWon: { text: 'You took 3 pieces from each and picked the bigger pieces.', sticker: 'Same top number: the smaller bottom number is the bigger fraction.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which is bigger: 1/2 or 1/3?',
        picture: { kind: 'bars', bars: [{ parts: 2, shaded: 0, label: '1/2' }, { parts: 3, shaded: 0, label: '1/3' }] }, answer: { choices: ['1/2', '1/3'], correct: 0 },
        steps: ['Both take 1 piece.', 'A bar cut into 2 has bigger pieces than a bar cut into 3.', 'So the bigger one is 1/2.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Which is bigger: 2/8 or 2/6?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 0, label: '2/8' }, { parts: 6, shaded: 0, label: '2/6' }] }, answer: { choices: ['2/8', '2/6'], correct: 1 },
        steps: ['Both take 2 pieces.', 'A bar cut into 6 has bigger pieces than a bar cut into 8.', 'So the bigger one is 2/6.'] } },
      { why: 'Still "bigger pieces make more"', problem: { text: 'Which sign goes in the middle? 1/3 ? 1/6',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 0, label: '1/3' }, { parts: 6, shaded: 0, label: '1/6' }] }, answer: { choices: ['<', '>', '='], correct: 1 },
        steps: ['Both take 1 piece.', 'Pieces of 3 are bigger than pieces of 6, so 1/3 is bigger.', 'So 1/3 > 1/6.'] } },
      { why: 'A little harder', problem: { text: 'Which sign goes in the middle? 5/8 ? 5/6',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 0, label: '5/8' }, { parts: 6, shaded: 0, label: '5/6' }] }, answer: { choices: ['<', '>', '='], correct: 0 },
        steps: ['Both take 5 pieces.', 'Pieces of 8 are smaller than pieces of 6, so 5/8 is smaller.', 'The open side faces the bigger number, so 5/8 < 5/6.'] } },
      { why: 'Same math in a story', problem: { text: 'Ava eats 2/3 of a small pizza. Jon eats 2/4 of a pizza the same size. Who eats more?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 0, label: '2/3' }, { parts: 4, shaded: 0, label: '2/4' }] }, answer: { choices: ['Ava', 'Jon'], correct: 0 },
        steps: ['Both eat 2 pieces.', "A pizza cut into 3 has bigger slices than a pizza cut into 4, so Ava's slices are bigger.", 'So Ava eats more.'] } },
    ],
  },
]
