/** Grade 3 · Module 5 — Fractions as numbers. Written to docs/new-flow/AUTHORING.md. */
import type { Lesson } from '../script'
import { attachChalk } from '../chalk'
import { G3M5_CHALK } from './chalk/g3m5'

const YES_NO = ['yes', 'no']

export const G3M5: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t1', title: 'Cut the sandwich fairly', skill: 'Equal parts of a whole',
    bigIdea: "A cut is fair only when every piece is the same size.",
    screens: [
      { title: 'Sharing a sandwich', text: 'You and a friend share one sandwich. It is cut into 2 pieces. Is that fair?',
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }] }] }] },
      { title: 'Two pieces is not enough to know', text: "2 pieces, one for each of you. That sounds fair. But look. This sandwich has 2 pieces too, one big and one small. So is counting the pieces enough? No.",
        beats: [
          { say: "2 pieces, one for each of you. That sounds fair." },
          { say: "But look. This sandwich has 2 pieces too, one big and one small.", pic: 0 },
          { say: "So is counting the pieces enough? No." },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 3, shade: true }, { w: 1 }] }] }] },
      { title: 'The big idea', text: "A cut is fair only when every piece is the same size.",
        beats: [
          { say: "A cut is fair only when every piece is the same size.", pic: 0 },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }] }] }] },
      { title: 'Cut down the middle', text: "Look. I'll cut the sandwich right down the middle. Now check. Are both pieces the same size? Yes, they match. That's 2 fair pieces, one for you and one for your friend.",
        beats: [
          { say: "Look. I'll cut the sandwich right down the middle.", pic: 0 },
          { say: "Now check. Are both pieces the same size? Yes, they match." },
          { say: "That's 2 fair pieces, one for you and one for your friend." },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 1, shade: true }, { w: 1 }] }], motion: true }] },
      { title: 'More friends, more cuts', text: "What if 4 friends share the sandwich? Then we cut 4 pieces, and every piece is the same size. Each friend gets 1 of the 4 equal pieces.",
        beats: [
          { say: "What if 4 friends share the sandwich?" },
          { say: "Then we cut 4 pieces, and every piece is the same size.", pic: 0 },
          { say: "Each friend gets 1 of the 4 equal pieces." },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 1, shade: true }, { w: 1 }, { w: 1 }, { w: 1 }] }], motion: true }] },
      { title: 'Check with your eyes', text: "How can you check a cut? Just look at the pieces. If every piece matches, the cut is fair. If even one piece is bigger, it is not fair.",
        beats: [
          { say: "How can you check a cut? Just look at the pieces." },
          { say: "If every piece matches, the cut is fair.", pic: 0 },
          { say: "If even one piece is bigger, it is not fair." },
        ],
        pictures: [{ kind: 'tape', rows: [
          { label: 'Fair', cells: [{ w: 1 }, { w: 1 }, { w: 1 }] },
          { label: 'Not fair', cells: [{ w: 1.6 }, { w: 0.7 }, { w: 0.7 }] },
        ] }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't just COUNT the pieces and call it fair. 4 pieces are not fair if one is bigger. Every piece has to be the same size. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't just COUNT the pieces and call it fair.", pic: 0 },
          { say: "4 pieces are not fair if one is bigger. Every piece has to be the same size." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '4 pieces of any size', right: '4 pieces, all the same size' }] },
    ],
    turn: {
      text: 'This sandwich is cut into 3 pieces. Are the pieces fair?',
      picture: { kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 2 }, { w: 1 }] }] },
      answer: { choices: YES_NO, correct: 1 },
      steps: ['Look at the size of each piece.', 'The middle piece is bigger than the two end pieces.', 'The pieces are not the same size, so the answer is no.'],
      prompt: 'Look at every piece. Fair pieces are all the same size.',
      hint1: 'Are all the pieces the same size?',
      hint2: 'Compare the middle piece with the pieces at the ends.',
      twin: { text: 'This bar is cut into 6 pieces. Are the pieces fair?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }] }] },
        answer: { choices: YES_NO, correct: 0 },
        steps: ['Look at the size of each piece.', 'Every piece is just as wide as the one next to it.', 'The pieces all match, so the answer is yes.'],
        hint1: 'Look at each piece. Do they all match?',
        hint2: 'Put your finger on each piece and compare it with the next one.' },
    },
    won: { text: 'You checked the size of every piece before you said fair.', sticker: 'Pieces that are all the same size are called equal parts.' },
    twinWon: { text: 'You checked that all 6 pieces were the same size.', sticker: 'Pieces that are all the same size are called equal parts.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A sandwich is cut into 2 pieces. Are the pieces fair?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }] }] }, answer: { choices: YES_NO, correct: 0 },
        steps: ['Look at the two pieces.', 'They are the same size.', 'Both pieces match, so the answer is yes.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A granola bar is cut into 4 pieces. Are the pieces fair?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }, { w: 2 }, { w: 1 }] }] }, answer: { choices: YES_NO, correct: 1 },
        steps: ['Look at the size of each piece.', 'One piece is twice as wide as the others.', 'The pieces are not the same size, so the answer is no.'] } },
      { why: 'Still "same-size pieces"', problem: { text: 'This bar is cut into equal pieces. How many equal pieces are there?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }] }] }, answer: 8,
        steps: ['Every piece is the same size, so we can count them.', 'Count them: 1, 2, 3, 4, 5, 6, 7, 8.', 'There are 8 equal pieces.'] } },
      { why: 'A little harder', problem: { text: 'A pan of cornbread is cut into 6 pieces. Are the pieces fair?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }, { w: 1.5 }, { w: 0.5 }] }] }, answer: { choices: YES_NO, correct: 1 },
        steps: ['Look at the size of each piece, all the way to the end.', 'The last two pieces are not the same size as the others.', 'The pieces do not all match, so the answer is no.'] } },
      { why: 'Same math in a story', problem: { text: 'Ben cuts a long sub sandwich for 4 friends. The picture shows his cuts. Are the pieces fair?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1 }, { w: 1 }, { w: 1 }, { w: 1 }] }] }, answer: { choices: YES_NO, correct: 0 },
        steps: ['Look at the size of each piece.', 'All 4 pieces are the same size.', 'Every friend gets the same amount, so the answer is yes.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t2', title: 'One piece: 1/4', skill: 'One equal piece of a whole',
    bigIdea: "1 of 4 equal pieces is 1/4, and the bottom number counts all the equal pieces.",
    screens: [
      { title: 'Lunch time', text: 'A sandwich is cut into 4 equal pieces. You eat 1 piece. How much of the sandwich did you eat?',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 1 }] }] },
      { title: 'It is not just "1"', text: "You ate 1 piece. But that is not 1 whole sandwich. So how do we write 1 piece out of 4?",
        beats: [
          { say: "You ate 1 piece.", pic: 0 },
          { say: "But that is not 1 whole sandwich." },
          { say: "So how do we write 1 piece out of 4?" },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 1 }] }] },
      { title: 'The big idea', text: "1 of 4 equal pieces is 1/4, and the bottom number counts all the equal pieces.",
        beats: [
          { say: "1 of 4 equal pieces is 1/4, and the bottom number counts all the equal pieces.", pic: 0 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 1 }] }] },
      { title: 'Count the equal pieces', text: "Start with the whole sandwich. It is cut into equal pieces. Count them. 1, 2, 3, 4. 4 pieces make the whole. So the 4 goes on the bottom.",
        beats: [
          { say: "Start with the whole sandwich.", pic: 0 },
          { say: "It is cut into equal pieces. Count them. 1, 2, 3, 4." },
          { say: "4 pieces make the whole. So the 4 goes on the bottom." },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 1, shaded: 0, split: 4 }], motion: true }] },
      { title: 'Count the piece you ate', text: "The 4 is on the bottom. Now the piece you ate. Just 1 piece, the shaded one. So the 1 goes on top.",
        beats: [
          { say: "The 4 is on the bottom.", pic: 0 },
          { say: "Now the piece you ate. Just 1 piece, the shaded one." },
          { say: "So the 1 goes on top." },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 1 }], motion: true }] },
      { title: 'Write it', text: "Put the two numbers together. That's 1/4. We say it out loud as one fourth. It means 1 of 4 equal pieces, the part you ate.",
        beats: [
          { say: "Put the two numbers together. That's 1/4.", pic: 1 },
          { say: "We say it out loud as one fourth." },
          { say: "It means 1 of 4 equal pieces, the part you ate.", pic: 0 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 1, label: '1/4' }] }, { kind: 'eq', text: '1/4' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't put the LEFTOVER pieces on the bottom. 3 pieces are left, but the sandwich was cut into 4. So it is 1/4, not 1/3. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't put the LEFTOVER pieces on the bottom.", pic: 0 },
          { say: "3 pieces are left, but the sandwich was cut into 4. So it is 1/4, not 1/3." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '1/3', right: '1/4' }] },
    ],
    turn: {
      text: 'A bar is cut into 6 equal pieces. 1 piece is shaded. How much of the bar is shaded?',
      picture: { kind: 'bars', bars: [{ parts: 6, shaded: 1 }] },
      answer: { frac: [1, 6] },
      steps: ['The bar is cut into 6 equal pieces, so 6 goes on the bottom.', '1 piece is shaded, so 1 goes on the top.', 'So the answer is 1/6.'],
      prompt: 'Count all the equal pieces for the bottom. Count the shaded piece for the top.',
      hint1: 'How many equal pieces is the whole bar cut into?',
      hint2: 'The shaded piece is 1 of those pieces. Put the 1 on top.',
      twin: { text: 'A pizza strip is cut into 3 equal pieces. You eat 1 piece. How much of the strip did you eat?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 1 }] },
        answer: { frac: [1, 3] },
        steps: ['The strip is cut into 3 equal pieces, so 3 goes on the bottom.', 'You ate 1 piece, so 1 goes on the top.', 'So the answer is 1/3.'],
        hint1: 'How many equal pieces is the strip cut into?',
        hint2: 'You ate 1 piece. That number goes on top.' },
    },
    won: { text: 'You counted the equal pieces for the bottom and the shaded piece for the top.', sticker: 'One equal piece, like 1/6, is called a unit fraction.' },
    twinWon: { text: 'You found 1 piece out of 3 equal pieces.', sticker: 'One equal piece, like 1/3, is called a unit fraction.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A sandwich is cut into 2 equal pieces. You eat 1 piece. How much did you eat?',
        picture: { kind: 'bars', bars: [{ parts: 2, shaded: 1 }] }, answer: { frac: [1, 2] },
        steps: ['The sandwich is cut into 2 equal pieces, so 2 goes on the bottom.', 'You ate 1 piece, so 1 goes on the top.', 'So the answer is 1/2.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A bar is cut into 8 equal pieces. 1 piece is shaded. How much of the bar is shaded?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 1 }] }, answer: { frac: [1, 8] },
        steps: ['The bar is cut into 8 equal pieces, so 8 goes on the bottom.', '1 piece is shaded, so 1 goes on the top.', 'So the answer is 1/8.'] } },
      { why: 'Still "one equal piece"', problem: { text: 'A cracker is cut into 4 equal pieces. 1 piece is shaded. How much of the cracker is shaded?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 1 }] }, answer: { frac: [1, 4] },
        steps: ['The cracker is cut into 4 equal pieces, so 4 goes on the bottom.', '1 piece is shaded, so 1 goes on the top.', 'So the answer is 1/4.'] } },
      { why: 'A little harder', problem: { text: 'A granola bar is cut into equal pieces. Each piece is 1/6 of the bar. How many pieces are there?',
        picture: { kind: 'bars', bars: [{ parts: 1, shaded: 0 }] }, answer: 6,
        steps: ['1/6 means 1 of 6 equal pieces.', 'The bottom number tells how many equal pieces make the whole bar.', 'So there are 6 pieces.'] } },
      { why: 'Same math in a story', problem: { text: 'Mia cuts a ribbon into 3 equal pieces. She gives 1 piece to Jo. How much of the ribbon does Jo get?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 1 }] }, answer: { frac: [1, 3] },
        steps: ['The ribbon is cut into 3 equal pieces, so 3 goes on the bottom.', 'Jo gets 1 piece, so 1 goes on the top.', 'So Jo gets 1/3 of the ribbon.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t3', title: 'Three pieces: 3/4', skill: 'More than one equal piece',
    bigIdea: "The bottom number counts all the equal pieces, and the top number counts the pieces you have.",
    screens: [
      { title: 'A hungry lunch', text: 'A sandwich is cut into 4 equal pieces. You eat 3 pieces. How much of the sandwich did you eat?',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 3 }] }] },
      { title: 'More than one piece', text: "You know this part. 1 piece out of 4 is 1/4. But this time you ate 3 pieces. So how do we write 3 of them?",
        beats: [
          { say: "You know this part. 1 piece out of 4 is 1/4.", pic: 0 },
          { say: "But this time you ate 3 pieces." },
          { say: "So how do we write 3 of them?" },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 1, label: '1/4' }, { parts: 4, shaded: 3 }] }] },
      { title: 'The big idea', text: "The bottom number counts all the equal pieces, and the top number counts the pieces you have.",
        beats: [
          { say: "The bottom number counts all the equal pieces, and the top number counts the pieces you have.", pic: 0 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 3 }] }] },
      { title: 'The bottom is still 4', text: "Look at the whole sandwich. It is still cut into 4 equal pieces. Did eating change that? No. So the bottom number is still 4.",
        beats: [
          { say: "Look at the whole sandwich.", pic: 0 },
          { say: "It is still cut into 4 equal pieces. Did eating change that? No." },
          { say: "So the bottom number is still 4." },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 1, shaded: 0, split: 4 }], motion: true }] },
      { title: 'Count the pieces you have', text: "The 4 is on the bottom. Now count the shaded pieces with me. 1, 2, 3. You have 3 pieces, so the top number is 3.",
        beats: [
          { say: "The 4 is on the bottom. Now count the shaded pieces with me.", pic: 0 },
          { say: "1, 2, 3." },
          { say: "You have 3 pieces, so the top number is 3." },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 3 }], motion: true }] },
      { title: 'Write it', text: "Put the two numbers together. That's 3/4. We say it out loud as three fourths. It means 3 of 4 equal pieces, the part you ate.",
        beats: [
          { say: "Put the two numbers together. That's 3/4.", pic: 1 },
          { say: "We say it out loud as three fourths." },
          { say: "It means 3 of 4 equal pieces, the part you ate.", pic: 0 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 3, label: '3/4' }] }, { kind: 'eq', text: '3/4', lines: ['3 pieces you have', '4 equal pieces in the whole'] }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't put the piece that is LEFT on the bottom. 1 piece is left, but the sandwich was cut into 4. The bottom counts all the pieces, so it is 3/4. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't put the piece that is LEFT on the bottom.", pic: 0 },
          { say: "1 piece is left, but the sandwich was cut into 4. The bottom counts all the pieces, so it is 3/4." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '3/1', right: '3/4' }] },
    ],
    turn: {
      text: 'A bar is cut into 6 equal pieces. 5 pieces are shaded. How much of the bar is shaded?',
      picture: { kind: 'bars', bars: [{ parts: 6, shaded: 5 }] },
      answer: { frac: [5, 6] },
      steps: ['The bar is cut into 6 equal pieces, so 6 goes on the bottom.', 'Count the shaded pieces: 1, 2, 3, 4, 5. So 5 goes on the top.', 'So the answer is 5/6.'],
      prompt: 'Count all the equal pieces for the bottom. Count the shaded pieces for the top.',
      hint1: 'How many equal pieces make the whole bar? That is the bottom.',
      hint2: 'Now count only the shaded pieces. That is the top.',
      twin: { text: 'A pan of brownies is cut into 8 equal pieces. 3 pieces are eaten. How much of the pan was eaten?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 3 }] },
        answer: { frac: [3, 8] },
        steps: ['The pan is cut into 8 equal pieces, so 8 goes on the bottom.', '3 pieces were eaten, so 3 goes on the top.', 'So the answer is 3/8.'],
        hint1: 'How many equal pieces is the whole pan cut into?',
        hint2: 'Count only the shaded pieces. That number goes on top.' },
    },
    won: { text: 'You counted all the pieces for the bottom and your pieces for the top.', sticker: 'The top number is called the numerator. It counts the pieces you have.' },
    twinWon: { text: 'You found 3 pieces out of 8 equal pieces.', sticker: 'The top number is called the numerator. It counts the pieces you have.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A sandwich is cut into 4 equal pieces. You eat 2 pieces. How much did you eat?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 2 }] }, answer: { frac: [2, 4] },
        steps: ['The sandwich is cut into 4 equal pieces, so 4 goes on the bottom.', 'You ate 2 pieces, so 2 goes on the top.', 'So the answer is 2/4.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A bar is cut into 3 equal pieces. 2 pieces are shaded. How much of the bar is shaded?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 2 }] }, answer: { frac: [2, 3] },
        steps: ['The bar is cut into 3 equal pieces, so 3 goes on the bottom.', '2 pieces are shaded, so 2 goes on the top.', 'So the answer is 2/3.'] } },
      { why: 'Still "count the pieces you have"', problem: { text: 'A bar is cut into 8 equal pieces. 5 pieces are shaded. How much of the bar is shaded?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 5 }] }, answer: { frac: [5, 8] },
        steps: ['The bar is cut into 8 equal pieces, so 8 goes on the bottom.', 'Count the shaded pieces: 1, 2, 3, 4, 5. So 5 goes on the top.', 'So the answer is 5/8.'] } },
      { why: 'A little harder', problem: { text: 'A bar is cut into 6 equal pieces. 2 pieces are white. How much of the bar is shaded?',
        picture: { kind: 'bars', bars: [{ parts: 6, shaded: 4 }] }, answer: { frac: [4, 6] },
        steps: ['The bar is cut into 6 equal pieces, so 6 goes on the bottom.', '2 of the 6 pieces are white, so 6 − 2 = 4 pieces are shaded.', 'So the answer is 4/6.'] } },
      { why: 'Same math in a story', problem: { text: 'Nia cuts a pizza into 8 equal slices. Her family eats 7 slices. How much of the pizza did they eat?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 7 }] }, answer: { frac: [7, 8] },
        steps: ['The pizza is cut into 8 equal slices, so 8 goes on the bottom.', 'They ate 7 slices, so 7 goes on the top.', 'So they ate 7/8 of the pizza.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t4', title: 'Fractions on a number line', skill: 'A fraction is a point on the number line',
    bigIdea: "The space from 0 to 1 is one whole, so cut it into equal jumps and count the jumps from 0.",
    screens: [
      { title: 'A walk to the park', text: 'The path from home to the park is cut into 4 equal parts. Home is 0 and the park is 1. You walk 3 parts. Where are you?',
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 4, labels: 'ends' }] },
      { title: 'No pieces to hold', text: "This one is different. There's no sandwich, just a path from home to the park. There are no pieces to pick up and count. So how do we find 3 of the 4 parts?",
        beats: [
          { say: "This one is different. There's no sandwich, just a path from home to the park.", pic: 0 },
          { say: "There are no pieces to pick up and count." },
          { say: "So how do we find 3 of the 4 parts?" },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 4, labels: 'ends' }] },
      { title: 'The big idea', text: "The space from 0 to 1 is one whole, so cut it into equal jumps and count the jumps from 0.",
        beats: [
          { say: "The space from 0 to 1 is one whole, so cut it into equal jumps and count the jumps from 0.", pic: 0 },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 4, labels: 'ends' }] },
      { title: 'Cut the whole into 4 jumps', text: "The path from 0 all the way to 1 is one whole. Cut it into 4 equal jumps. Every jump is the same size, so each one is 1/4.",
        beats: [
          { say: "The path from 0 all the way to 1 is one whole." },
          { say: "Cut it into 4 equal jumps.", pic: 0 },
          { say: "Every jump is the same size, so each one is 1/4." },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 4, labels: 'ends', motion: true,
          jumps: [{ from: 0, to: 0.25, label: '1/4' }, { from: 0.25, to: 0.5, label: '1/4' }, { from: 0.5, to: 0.75, label: '1/4' }, { from: 0.75, to: 1, label: '1/4' }] }] },
      { title: 'Take 3 jumps', text: "Put your finger on 0. Now jump with me. 1/4, 2/4, 3/4. That's 3 jumps. You land on 3/4.",
        beats: [
          { say: "Put your finger on 0.", pic: 0 },
          { say: "Now jump with me. 1/4, 2/4, 3/4." },
          { say: "That's 3 jumps. You land on 3/4." },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 4, labels: ['0', '1/4', '2/4', '3/4', '1'], motion: true,
          jumps: [{ from: 0, to: 0.25 }, { from: 0.25, to: 0.5 }, { from: 0.5, to: 0.75 }], points: [{ at: 0.75 }] }] },
      { title: 'Every mark has a name', text: "Every mark on this line has a name. The mark after 3 jumps is 3/4. Is 3/4 a real number? Yes, just like 0 and 1 are.",
        beats: [
          { say: "Every mark on this line has a name.", pic: 0 },
          { say: "The mark after 3 jumps is 3/4." },
          { say: "Is 3/4 a real number? Yes, just like 0 and 1 are." },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 4, labels: ['0', '1/4', '2/4', '3/4', '1'], points: [{ at: 0.75, label: '3/4' }] }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Jumps of DIFFERENT sizes are not fourths. Every jump from 0 to 1 must be the same size. Only then do 3 jumps land on 3/4. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Jumps of DIFFERENT sizes are not fourths.", pic: 0 },
          { say: "Every jump from 0 to 1 must be the same size. Only then do 3 jumps land on 3/4." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: 'Jumps of different sizes', right: 'Jumps all the same size' }] },
    ],
    turn: {
      text: 'This line from 0 to 1 is cut into 6 equal jumps. Which fraction is at the dot?',
      picture: { kind: 'numline', min: 0, max: 1, ticks: 6, labels: 'ends', points: [{ at: 5 / 6 }] },
      answer: { frac: [5, 6] },
      steps: ['The line is cut into 6 equal jumps, so the bottom number is 6.', 'Count the jumps from 0 to the dot: 1, 2, 3, 4, 5.', 'So the dot is at 5/6.'],
      prompt: 'Count the equal jumps from 0 to 1 for the bottom. Count the jumps to the dot for the top.',
      hint1: 'How many equal jumps go from 0 to 1?',
      hint2: 'Start at 0 and count the jumps until you reach the dot.',
      twin: { text: 'This line from 0 to 1 is cut into 3 equal jumps. Which fraction is at the dot?',
        picture: { kind: 'numline', min: 0, max: 1, ticks: 3, labels: 'ends', points: [{ at: 2 / 3 }] },
        answer: { frac: [2, 3] },
        steps: ['The line is cut into 3 equal jumps, so the bottom number is 3.', 'Count the jumps from 0 to the dot: 1, 2.', 'So the dot is at 2/3.'],
        hint1: 'How many equal jumps go from 0 to 1?',
        hint2: 'Start at 0. Count the jumps to the dot. The 0 is where you start, not a jump.' },
    },
    won: { text: 'You counted the equal jumps in the whole, then the jumps to the dot.', sticker: 'A fraction is a number. It has its own place on the number line.' },
    twinWon: { text: 'You counted 3 equal jumps in the whole, then the jumps to the dot.', sticker: 'A fraction is a number. It has its own place on the number line.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'This line from 0 to 1 is cut into 4 equal jumps. Which fraction is at the dot?',
        picture: { kind: 'numline', min: 0, max: 1, ticks: 4, labels: 'ends', points: [{ at: 0.5 }] }, answer: { frac: [2, 4] },
        steps: ['The line is cut into 4 equal jumps, so the bottom number is 4.', 'Count the jumps from 0 to the dot: 1, 2.', 'So the dot is at 2/4.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'This line from 0 to 1 is cut into 8 equal jumps. Which fraction is at the dot?',
        picture: { kind: 'numline', min: 0, max: 1, ticks: 8, labels: 'ends', points: [{ at: 5 / 8 }] }, answer: { frac: [5, 8] },
        steps: ['The line is cut into 8 equal jumps, so the bottom number is 8.', 'Count the jumps from 0 to the dot: 1, 2, 3, 4, 5.', 'So the dot is at 5/8.'] } },
      { why: 'Still "count equal jumps"', problem: { text: 'This line from 0 to 1 is cut into 2 equal jumps. Which fraction is at the dot?',
        picture: { kind: 'numline', min: 0, max: 1, ticks: 2, labels: 'ends', points: [{ at: 0.5 }] }, answer: { frac: [1, 2] },
        steps: ['The line is cut into 2 equal jumps, so the bottom number is 2.', 'The dot is 1 jump from 0.', 'So the dot is at 1/2.'] } },
      { why: 'A little harder', problem: { text: 'This line from 0 to 1 is cut into 8 equal jumps. The dot is 1 jump before 1. Which fraction is at the dot?',
        picture: { kind: 'numline', min: 0, max: 1, ticks: 8, labels: 'ends', points: [{ at: 7 / 8 }] }, answer: { frac: [7, 8] },
        steps: ['The line is cut into 8 equal jumps, so the bottom number is 8.', 'Getting to 1 takes 8 jumps. The dot is 1 jump before that, so 8 − 1 = 7 jumps.', 'So the dot is at 7/8.'] } },
      { why: 'Same math in a story', problem: { text: 'The path from the house to the gate is cut into 3 equal parts. The house is 0 and the gate is 1. Ava walks 1 part. The dot shows Ava. What fraction of the way has she walked?',
        picture: { kind: 'numline', min: 0, max: 1, ticks: 3, labels: 'ends', points: [{ at: 1 / 3 }] }, answer: { frac: [1, 3] },
        steps: ['The path is cut into 3 equal parts, so the bottom number is 3.', 'Ava walked 1 part from 0.', 'So she has walked 1/3 of the way.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t5', title: 'Same amount, different pieces', skill: 'Equal fractions cover the same amount',
    bigIdea: 'You can cut the same amount into smaller pieces, and the amount stays the same.',
    screens: [
      { title: 'Two candy bars', text: 'These two candy bars are the same size. One is cut into 2 pieces, one into 4. Who has more chocolate?',
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1 }, { parts: 4, shaded: 2 }] }] },
      { title: 'The names look different', text: 'One bar shows 1/2, the other 2/4. Every number is different. So does one bar have more chocolate? Look at the bars, not the numbers.',
        beats: [
          { say: 'One bar shows 1/2, the other 2/4.', pic: 0 },
          { say: 'Every number is different. So does one bar have more chocolate?' },
          { say: 'Look at the bars, not the numbers.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1, label: '1/2' }, { parts: 4, shaded: 2, label: '2/4' }] }] },
      { title: 'The big idea', text: 'You can cut the same amount into smaller pieces, and the amount stays the same.',
        beats: [
          { say: 'You can cut the same amount into smaller pieces, and the amount stays the same.', pic: 0 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1 }, { parts: 4, shaded: 2 }] }] },
      { title: 'Half a bar', text: "Start with one bar, cut into 2 equal pieces. Shade 1 of the 2. That's 1/2.",
        beats: [
          { say: 'Start with one bar, cut into 2 equal pieces.', pic: 0 },
          { say: "Shade 1 of the 2. That's 1/2." },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1, label: '1/2' }], motion: true }] },
      { title: 'Cut each piece again', text: "Now cut each piece in 2. There are 4 pieces now, and 2 are shaded. That's 2/4. Did we add chocolate? No, and none was eaten.",
        beats: [
          { say: 'Now cut each piece in 2.', pic: 0 },
          { say: "There are 4 pieces now, and 2 are shaded. That's 2/4." },
          { say: 'Did we add chocolate? No, and none was eaten.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1, split: 2 }], motion: true }] },
      { title: 'They match', text: 'Put the two bars one above the other. Look where the shading stops. Both stop at the same place. So 1/2 and 2/4 are the same amount. Nobody has more.',
        beats: [
          { say: 'Put the two bars one above the other.', pic: 0 },
          { say: 'Look where the shading stops. Both stop at the same place.' },
          { say: 'So 1/2 and 2/4 are the same amount. Nobody has more.', pic: 1 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1, label: '1/2' }, { parts: 4, shaded: 2, label: '2/4' }] }, { kind: 'eq', text: '1/2 = 2/4' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't change just ONE number. 1/2 is not 1/4. Smaller pieces means you need more of them. So 1/2 = 2/4. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't change just ONE number. 1/2 is not 1/4.", pic: 0 },
          { say: 'Smaller pieces means you need more of them. So 1/2 = 2/4.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '1/2 = 1/4', right: '1/2 = 2/4' }] },
    ],
    turn: {
      text: 'Do 2/3 and 4/6 cover the same amount?',
      picture: { kind: 'bars', bars: [{ parts: 3, shaded: 2, label: '2/3' }, { parts: 6, shaded: 4, label: '4/6' }] },
      answer: { choices: YES_NO, correct: 0 },
      steps: ['Both bars are the same size.', 'Each piece of the top bar is cut into 2 smaller pieces on the bottom bar.', 'The shading stops at the same place, so the answer is yes.'],
      prompt: 'The bars are the same size. Check if the shaded parts match.',
      hint1: 'Look at where the shading stops on each bar.',
      hint2: 'Each piece on the top bar was cut into 2 smaller pieces. Did the shaded amount change?',
      twin: { text: 'The top bar shows 1/4. The bottom bar is cut into 8 equal pieces. How many pieces do you shade to cover the same amount?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 1, label: '1/4' }, { parts: 8, shaded: 0 }] },
        answer: 2,
        steps: ['Each piece of the top bar sits over small pieces of the bottom bar.', 'Under the 1 shaded piece there are 2 small pieces.', 'So you shade 2 pieces.'],
        hint1: 'Each piece on the top bar sits over how many small pieces below?',
        hint2: 'Look under the shaded piece on top. Count the small pieces under it.' },
    },
    won: { text: 'You saw that 2/3 and 4/6 cover the same amount.', sticker: 'Fractions that cover the same amount are called equivalent fractions.' },
    twinWon: { text: 'You saw that 1/4 and 2/8 cover the same amount.', sticker: 'Fractions that cover the same amount are called equivalent fractions.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Do 1/3 and 2/6 cover the same amount?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 1, label: '1/3' }, { parts: 6, shaded: 2, label: '2/6' }] }, answer: { choices: YES_NO, correct: 0 },
        steps: ['Both bars are the same size.', 'The 1 shaded piece on top is cut into 2 smaller shaded pieces below.', 'The shading stops at the same place, so the answer is yes.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Do 1/2 and 3/8 cover the same amount?',
        picture: { kind: 'bars', bars: [{ parts: 2, shaded: 1, label: '1/2' }, { parts: 8, shaded: 3, label: '3/8' }] }, answer: { choices: YES_NO, correct: 1 },
        steps: ['1/2 stops in the middle of the bar.', '3/8 stops before the middle. It would take 4 of the 8 pieces to reach the middle.', 'They do not match, so the answer is no.'] } },
      { why: 'Still "same amount, smaller pieces"', problem: { text: 'The top bar shows 1/2. The bottom bar is cut into 6 equal pieces. How many pieces do you shade to cover the same amount?',
        picture: { kind: 'bars', bars: [{ parts: 2, shaded: 1, label: '1/2' }, { parts: 6, shaded: 0 }] }, answer: 3,
        steps: ['Half of the bar is the first half, up to the middle.', 'Count the small pieces up to the middle: 1, 2, 3.', 'So you shade 3 pieces.'] } },
      { why: 'A little harder', problem: { text: 'The top bar shows 3/4. The bottom bar is cut into 8 equal pieces. How many pieces do you shade to cover the same amount?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 3, label: '3/4' }, { parts: 8, shaded: 0 }] }, answer: 6,
        steps: ['Each piece of the top bar sits over 2 small pieces.', 'There are 3 shaded pieces on top, so 3 × 2 small pieces.', 'So you shade 6 pieces.'] } },
      { why: 'Same math in a story', problem: { text: 'Jay eats 2/4 of a pan of cornbread. Kim has a same-size pan cut into 8 equal pieces. How many pieces must Kim eat to eat the same amount?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 2, label: '2/4' }, { parts: 8, shaded: 0 }] }, answer: 4,
        steps: ["Each piece of Jay's pan is the size of 2 pieces of Kim's pan.", 'Jay ate 2 pieces, so Kim needs 2 × 2 pieces.', 'So Kim must eat 4 pieces.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t6', title: 'A whole pizza: 4/4 = 1', skill: 'All the pieces make 1 whole',
    bigIdea: 'When the top and bottom numbers are the same, you have all the pieces, and that is 1 whole.',
    screens: [
      { title: 'Pizza night', text: 'A pizza is cut into 4 equal slices. Your family eats all 4 slices. How much of the pizza is gone?',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }] }] },
      { title: 'It is not 4 pizzas', text: '4 slices were eaten. So is that 4 pizzas? No. It was one pizza the whole time, cut into 4 slices.',
        beats: [
          { say: '4 slices were eaten.', pic: 0 },
          { say: 'So is that 4 pizzas? No.' },
          { say: 'It was one pizza the whole time, cut into 4 slices.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }] }] },
      { title: 'The big idea', text: 'When the top and bottom numbers are the same, you have all the pieces, and that is 1 whole.',
        beats: [
          { say: 'When the top and bottom numbers are the same, you have all the pieces, and that is 1 whole.', pic: 0 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }] }] },
      { title: 'Count every slice', text: "Count the slices with me. 1/4, 2/4, 3/4, 4/4. That's all 4 of the 4 slices.",
        beats: [
          { say: 'Count the slices with me.', pic: 0 },
          { say: '1/4, 2/4, 3/4, 4/4.' },
          { say: "That's all 4 of the 4 slices." },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }], motion: true }] },
      { title: 'All the slices make 1 whole', text: 'Look at the pizza now. Every slice is gone, and nothing is left over. So 4/4 is 1 whole pizza.',
        beats: [
          { say: 'Look at the pizza now.', pic: 0 },
          { say: 'Every slice is gone, and nothing is left over.' },
          { say: 'So 4/4 is 1 whole pizza.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4, label: '4/4' }, { parts: 1, shaded: 1, label: '1' }], motion: true }] },
      { title: 'Any whole works', text: 'It works however you cut it. Cut a bar into 6 equal pieces, and all 6 make 6/6. Cut one into 2, and both pieces make 2/2. Each one is 1 whole.',
        beats: [
          { say: 'It works however you cut it.' },
          { say: 'Cut a bar into 6 equal pieces, and all 6 make 6/6.', pic: 0 },
          { say: 'Cut one into 2, and both pieces make 2/2.' },
          { say: 'Each one is 1 whole.', pic: 1 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 6, shaded: 6, label: '6/6' }, { parts: 2, shaded: 2, label: '2/2' }] }, { kind: 'eq', text: '6/6 = 2/2 = 1' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Bigger numbers do not mean MORE here. 8/8 is not more than 4/4. Both are all the pieces, so both are 1 whole. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: 'Bigger numbers do not mean MORE here. 8/8 is not more than 4/4.', pic: 0 },
          { say: 'Both are all the pieces, so both are 1 whole.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '8/8 is more than 4/4', right: '8/8 = 4/4 = 1' }] },
    ],
    turn: {
      text: 'A bar is cut into 6 equal pieces. All the pieces are shaded. How much of the bar is shaded? Write it with a top and bottom number.',
      picture: { kind: 'bars', bars: [{ parts: 6, shaded: 6 }] },
      answer: { frac: [6, 6] },
      steps: ['The bar is cut into 6 equal pieces, so 6 goes on the bottom.', 'All 6 pieces are shaded, so 6 goes on the top.', 'So the answer is 6/6. That is 1 whole.'],
      prompt: 'Count all the pieces for the bottom. Count the shaded pieces for the top.',
      hint1: 'How many equal pieces are in the whole bar?',
      hint2: 'Count the shaded pieces. Are any pieces white?',
      twin: { text: 'A sandwich is cut into 3 equal pieces. How many pieces do you eat to eat the whole sandwich?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 0 }] },
        answer: 3,
        steps: ['The whole sandwich means every piece.', 'The sandwich is cut into equal pieces. Count them: 1, 2, 3.', 'So you eat 3 pieces.'],
        hint1: 'How many equal pieces is the sandwich cut into?',
        hint2: 'The whole sandwich means every piece. Count them all.' },
    },
    won: { text: 'You saw that all 6 of the 6 pieces make 1 whole.', sticker: 'A fraction with the same top and bottom number is equal to 1 whole.' },
    twinWon: { text: 'You saw that all 3 pieces make 1 whole sandwich.', sticker: 'A fraction like 3/3, with the same top and bottom number, is equal to 1 whole.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A sandwich is cut into 2 equal pieces. You eat both pieces. How much of the sandwich did you eat?',
        picture: { kind: 'bars', bars: [{ parts: 2, shaded: 2 }] }, answer: { frac: [2, 2] },
        steps: ['The sandwich is cut into 2 equal pieces, so 2 goes on the bottom.', 'You ate both pieces, so 2 goes on the top.', 'So the answer is 2/2. That is 1 whole.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A bar is cut into 3 equal pieces. All the pieces are shaded. How much of the bar is shaded?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 3 }] }, answer: { frac: [3, 3] },
        steps: ['The bar is cut into 3 equal pieces, so 3 goes on the bottom.', 'All 3 pieces are shaded, so 3 goes on the top.', 'So the answer is 3/3. That is 1 whole.'] } },
      { why: 'Still "all the pieces make 1"', problem: { text: 'This bar is cut into 4 equal pieces. How many fourths make 1 whole?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 0 }] }, answer: 4,
        steps: ['1 whole means every piece of the bar.', 'The bar is cut into equal pieces. Count them: 1, 2, 3, 4.', 'So 4 fourths make 1 whole.'] } },
      { why: 'A little harder', problem: { text: '6/? = 1. What number goes on the bottom?',
        picture: { kind: 'bars', bars: [{ parts: 1, shaded: 1 }] }, answer: 6,
        steps: ['1 whole means you have all the pieces.', 'So the top and bottom numbers are the same.', 'The bottom number is 6.'] } },
      { why: 'Same math in a story', problem: { text: 'Ms. Lee cuts a pan of cornbread into 8 equal pieces. The class eats all of them. How much of the pan did they eat?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 8 }] }, answer: { frac: [8, 8] },
        steps: ['The pan is cut into 8 equal pieces, so 8 goes on the bottom.', 'The class ate all 8 pieces, so 8 goes on the top.', 'So they ate 8/8 of the pan. That is 1 whole pan.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t7', title: 'Which is bigger? Same pieces cut', skill: 'Compare fractions with the same bottom number',
    bigIdea: 'When the pieces are the same size, more pieces is more, so just compare the top numbers.',
    screens: [
      { title: 'Two pizzas', text: 'Two same-size pizzas are each cut into 8 equal slices. Ana eats 3 slices. Ben eats 5 slices. Who ate more?',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 3, label: 'Ana' }, { parts: 8, shaded: 5, label: 'Ben' }] }] },
      { title: 'Both end in 8', text: 'Ana ate 3/8. Ben ate 5/8. Both bottom numbers are 8. So how can we tell who ate more?',
        beats: [
          { say: 'Ana ate 3/8. Ben ate 5/8.', pic: 0 },
          { say: 'Both bottom numbers are 8. So how can we tell who ate more?' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 3, label: '3/8' }, { parts: 8, shaded: 5, label: '5/8' }] }] },
      { title: 'The big idea', text: 'When the pieces are the same size, more pieces is more, so just compare the top numbers.',
        beats: [
          { say: 'When the pieces are the same size, more pieces is more, so just compare the top numbers.', pic: 0 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 3, label: '3/8' }, { parts: 8, shaded: 5, label: '5/8' }] }] },
      { title: 'Same-size slices', text: 'Look at the two pizzas. Both are cut into 8 equal slices. So every slice is the same size, on both pizzas.',
        beats: [
          { say: 'Look at the two pizzas.', pic: 0 },
          { say: 'Both are cut into 8 equal slices.' },
          { say: 'So every slice is the same size, on both pizzas.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 1, shaded: 0, split: 8 }, { parts: 1, shaded: 0, split: 8 }], motion: true }] },
      { title: 'Count the slices', text: 'Now just count. Ana has 3 slices. Ben has 5 slices. 5 same-size slices are more than 3. So Ben ate more.',
        beats: [
          { say: 'Now just count.', pic: 0 },
          { say: 'Ana has 3 slices. Ben has 5 slices.' },
          { say: '5 same-size slices are more than 3. So Ben ate more.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 3, label: '3/8' }, { parts: 8, shaded: 5, label: '5/8' }], motion: true }] },
      { title: 'Write it', text: 'Now write it with a sign. 5/8 > 3/8. The open side of the sign faces the bigger number.',
        beats: [
          { say: 'Now write it with a sign. 5/8 > 3/8.', pic: 1 },
          { say: 'The open side of the sign faces the bigger number.', pic: 0 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 5, label: '5/8' }, { parts: 8, shaded: 3, label: '3/8' }] }, { kind: 'eq', text: '5/8 > 3/8' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't count the slices LEFT on the plate. Ana left 5 slices, but she ate only 3. Count the slices each one ate. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't count the slices LEFT on the plate.", pic: 0 },
          { say: 'Ana left 5 slices, but she ate only 3. Count the slices each one ate.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '3/8 > 5/8', right: '5/8 > 3/8' }] },
    ],
    turn: {
      text: 'Which is bigger: 2/6 or 5/6?',
      picture: { kind: 'bars', bars: [{ parts: 6, shaded: 0, label: '2/6' }, { parts: 6, shaded: 0, label: '5/6' }] },
      answer: { choices: ['2/6', '5/6'], correct: 1 },
      steps: ['Both are cut into 6 equal pieces, so the pieces are the same size.', '5 pieces is more than 2 pieces.', 'So the bigger one is 5/6.'],
      prompt: 'The pieces are the same size. Compare how many pieces each one has.',
      hint1: 'Are the bottom numbers the same?',
      hint2: 'Shade 2 pieces on one bar and 5 on the other in your head. Which covers more?',
      twin: { text: 'Which is bigger: 3/4 or 1/4?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 0, label: '3/4' }, { parts: 4, shaded: 0, label: '1/4' }] },
        answer: { choices: ['3/4', '1/4'], correct: 0 },
        steps: ['Both are cut into 4 equal pieces, so the pieces are the same size.', '3 pieces is more than 1 piece.', 'So the bigger one is 3/4.'],
        hint1: 'Are the pieces the same size?',
        hint2: 'Compare the top numbers. Which one has more pieces?' },
    },
    won: { text: 'You compared the top numbers because the pieces were the same size.', sticker: '> means "is greater than". 5/6 > 2/6.' },
    twinWon: { text: 'You compared 3 pieces and 1 piece of the same size.', sticker: 'When the bottom numbers match, the bigger top number is the bigger fraction.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which is bigger: 3/8 or 6/8?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 0, label: '3/8' }, { parts: 8, shaded: 0, label: '6/8' }] }, answer: { choices: ['3/8', '6/8'], correct: 1 },
        steps: ['Both are cut into 8 equal pieces, so the pieces are the same size.', '6 pieces is more than 3 pieces.', 'So the bigger one is 6/8.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Which is bigger: 2/3 or 1/3?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 0, label: '2/3' }, { parts: 3, shaded: 0, label: '1/3' }] }, answer: { choices: ['2/3', '1/3'], correct: 0 },
        steps: ['Both are cut into 3 equal pieces, so the pieces are the same size.', '2 pieces is more than 1 piece.', 'So the bigger one is 2/3.'] } },
      { why: 'Still "same-size pieces"', problem: { text: 'Which sign goes in the middle? 4/6 ? 3/6',
        picture: { kind: 'bars', bars: [{ parts: 6, shaded: 0, label: '4/6' }, { parts: 6, shaded: 0, label: '3/6' }] }, answer: { choices: ['<', '>', '='], correct: 1 },
        steps: ['Both are cut into 6 equal pieces.', '4 pieces is more than 3 pieces, so 4/6 is bigger.', 'So 4/6 > 3/6.'] } },
      { why: 'A little harder', problem: { text: 'Which sign goes in the middle? 5/8 ? 7/8',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 0, label: '5/8' }, { parts: 8, shaded: 0, label: '7/8' }] }, answer: { choices: ['<', '>', '='], correct: 0 },
        steps: ['Both are cut into 8 equal pieces.', '5 pieces is fewer than 7 pieces, so 5/8 is smaller.', 'The open side faces the bigger number, so 5/8 < 7/8.'] } },
      { why: 'Same math in a story', problem: { text: 'Mia ran 3/4 of a mile. Leo ran 2/4 of a mile. Who ran farther?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 0, label: '3/4' }, { parts: 4, shaded: 0, label: '2/4' }] }, answer: { choices: ['Mia', 'Leo'], correct: 0 },
        steps: ['Both miles are cut into 4 equal parts.', 'Mia ran 3 parts and Leo ran 2 parts.', 'So Mia ran farther.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m5-t8', title: 'Which is bigger? Same pieces taken', skill: 'Compare fractions with the same top number',
    bigIdea: 'When you take the same number of pieces, the one cut into fewer pieces is more, because its pieces are bigger.',
    screens: [
      { title: 'Two sandwiches', text: 'Two same-size sandwiches. One is cut into 3 equal pieces. One is cut into 8. You get 1 piece. Which piece is bigger: 1/3 or 1/8?',
        pictures: [{ kind: 'bars', bars: [{ parts: 3, shaded: 1, label: '1/3' }, { parts: 8, shaded: 1, label: '1/8' }] }] },
      { title: 'Bigger number, smaller piece', text: '8 is a bigger number than 3. So is 1/8 bigger than 1/3? No. This time, the bigger number gives the smaller piece.',
        beats: [
          { say: '8 is a bigger number than 3.' },
          { say: 'So is 1/8 bigger than 1/3? No.' },
          { say: 'This time, the bigger number gives the smaller piece.', pic: 0 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 3, shaded: 1, label: '1/3' }, { parts: 8, shaded: 1, label: '1/8' }] }] },
      { title: 'The big idea', text: 'When you take the same number of pieces, the one cut into fewer pieces is more, because its pieces are bigger.',
        beats: [
          { say: 'When you take the same number of pieces, the one cut into fewer pieces is more, because its pieces are bigger.', pic: 0 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 3, shaded: 1, label: '1/3' }, { parts: 8, shaded: 1, label: '1/8' }] }] },
      { title: 'Cut into 3', text: 'Take a bar and cut it into 3 equal pieces. Only 3 pieces, so each one is big.',
        beats: [
          { say: 'Take a bar and cut it into 3 equal pieces.', pic: 0 },
          { say: 'Only 3 pieces, so each one is big.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 1, shaded: 0, split: 3 }], motion: true }] },
      { title: 'Cut into 8', text: 'Now cut a bar the same size into 8 equal pieces. Each piece is much smaller. More cuts, smaller pieces.',
        beats: [
          { say: 'Now cut a bar the same size into 8 equal pieces.', pic: 0 },
          { say: 'Each piece is much smaller.' },
          { say: 'More cuts, smaller pieces.' },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 3, shaded: 1, label: '1/3' }, { parts: 8, shaded: 1, label: '1/8' }], motion: true }] },
      { title: 'Take 2 of each', text: "Take 2 pieces from each. That's 2/3 and 2/8. Same number of pieces, but the pieces of 3 are bigger. So 2/3 > 2/8.",
        beats: [
          { say: "Take 2 pieces from each. That's 2/3 and 2/8.", pic: 0 },
          { say: 'Same number of pieces, but the pieces of 3 are bigger.' },
          { say: 'So 2/3 > 2/8.', pic: 1 },
        ],
        pictures: [{ kind: 'bars', bars: [{ parts: 3, shaded: 2, label: '2/3' }, { parts: 8, shaded: 2, label: '2/8' }] }, { kind: 'eq', text: '2/3 > 2/8' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't pick the BIGGER bottom number. A bigger bottom number means more cuts, so smaller pieces. So 1/3 > 1/8. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't pick the BIGGER bottom number.", pic: 0 },
          { say: 'A bigger bottom number means more cuts, so smaller pieces. So 1/3 > 1/8.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '1/8 > 1/3', right: '1/3 > 1/8' }] },
    ],
    turn: {
      text: 'Which is bigger: 1/4 or 1/6?',
      picture: { kind: 'bars', bars: [{ parts: 4, shaded: 0, label: '1/4' }, { parts: 6, shaded: 0, label: '1/6' }] },
      answer: { choices: ['1/4', '1/6'], correct: 0 },
      steps: ['Both take 1 piece.', 'A bar cut into 4 has bigger pieces than a bar cut into 6.', 'So the bigger one is 1/4.'],
      prompt: 'Both take the same number of pieces. Find the bar with the bigger pieces.',
      hint1: 'Both take the same number of pieces. Which bar has bigger pieces?',
      hint2: 'Fewer cuts make bigger pieces. Which bar has fewer cuts?',
      twin: { text: 'Which is bigger: 3/8 or 3/4?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 0, label: '3/8' }, { parts: 4, shaded: 0, label: '3/4' }] },
        answer: { choices: ['3/8', '3/4'], correct: 1 },
        steps: ['Both take 3 pieces.', 'A bar cut into 4 has bigger pieces than a bar cut into 8.', 'So the bigger one is 3/4.'],
        hint1: 'Both take 3 pieces. Which bar has bigger pieces?',
        hint2: 'Compare the bottom numbers. Fewer cuts make bigger pieces.' },
    },
    won: { text: 'You took the same number of pieces and picked the bigger pieces.', sticker: 'Same top number: the smaller bottom number is the bigger fraction.' },
    twinWon: { text: 'You took 3 pieces from each and picked the bigger pieces.', sticker: 'Same top number: the smaller bottom number is the bigger fraction.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which is bigger: 1/2 or 1/3?',
        picture: { kind: 'bars', bars: [{ parts: 2, shaded: 0, label: '1/2' }, { parts: 3, shaded: 0, label: '1/3' }] }, answer: { choices: ['1/2', '1/3'], correct: 0 },
        steps: ['Both take 1 piece.', 'A bar cut into 2 has bigger pieces than a bar cut into 3.', 'So the bigger one is 1/2.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Which is bigger: 2/8 or 2/6?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 0, label: '2/8' }, { parts: 6, shaded: 0, label: '2/6' }] }, answer: { choices: ['2/8', '2/6'], correct: 1 },
        steps: ['Both take 2 pieces.', 'A bar cut into 6 has bigger pieces than a bar cut into 8.', 'So the bigger one is 2/6.'] } },
      { why: 'Still "bigger pieces make more"', problem: { text: 'Which sign goes in the middle? 1/3 ? 1/6',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 0, label: '1/3' }, { parts: 6, shaded: 0, label: '1/6' }] }, answer: { choices: ['<', '>', '='], correct: 1 },
        steps: ['Both take 1 piece.', 'Pieces of 3 are bigger than pieces of 6, so 1/3 is bigger.', 'So 1/3 > 1/6.'] } },
      { why: 'A little harder', problem: { text: 'Which sign goes in the middle? 5/8 ? 5/6',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 0, label: '5/8' }, { parts: 6, shaded: 0, label: '5/6' }] }, answer: { choices: ['<', '>', '='], correct: 0 },
        steps: ['Both take 5 pieces.', 'Pieces of 8 are smaller than pieces of 6, so 5/8 is smaller.', 'The open side faces the bigger number, so 5/8 < 5/6.'] } },
      { why: 'Same math in a story', problem: { text: 'Ava eats 2/3 of a small pizza. Jon eats 2/4 of a pizza the same size. Who eats more?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 0, label: '2/3' }, { parts: 4, shaded: 0, label: '2/4' }] }, answer: { choices: ['Ava', 'Jon'], correct: 0 },
        steps: ['Both eat 2 pieces.', "A pizza cut into 3 has bigger slices than a pizza cut into 4, so Ava's slices are bigger.", 'So Ava eats more.'] } },
    ],
  },
]

attachChalk(G3M5, G3M5_CHALK)
