/**
 * Grade 4 · Module 1 — Place value for addition and subtraction.
 * Written to docs/new-flow/AUTHORING.md.
 * Teaching pictures: t1 place chart (table) · t2 blocks · t3 place chart · t4 numline · t5/t6 columns ·
 * t7 table of rounded numbers · t8 tape.
 */
import type { Lesson, Picture } from '../script'
import { attachChalk } from '../chalk'
import { G4M1_CHALK } from './chalk/g4m1'

const PLACES = ['hundred thousands', 'ten thousands', 'thousands', 'hundreds', 'tens', 'ones']

/** A place-value chart: each number's digits under their places, right-aligned. Commas in `nums` are ignored. */
function chart(nums: string[], o: { labels?: string[]; mark?: [number, number][]; motion?: boolean } = {}): Picture {
  const digits = nums.map(n => n.replace(/,/g, '').split(''))
  const n = Math.max(...digits.map(d => d.length))
  const rows = digits.map((d, i) => [...(o.labels ? [o.labels[i]] : []), ...Array(n - d.length).fill(''), ...d])
  return { kind: 'table', head: [...(o.labels ? [''] : []), ...PLACES.slice(6 - n)], rows, rowHead: !!o.labels, mark: o.mark, motion: o.motion }
}

const LT = ['<', '>', '=']

export const G4M1: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t1', title: 'Read big numbers (to a million)', skill: 'Read and write numbers to 1,000,000',
    bigIdea: 'Read the part before the comma, say "thousand" at the comma, then read the last three digits.',
    screens: [
      { title: 'How many people?', text: 'A sign says 305,420 people live in a city. How do you read that big number?',
        pictures: [{ kind: 'eq', text: '305,420 people' }] },
      { title: 'Too many digits at once', text: "Six digits in a row. You could read them one by one. Three, zero, five, four, two, zero. But how many people is that? It doesn't say. Look at the comma.",
        beats: [
          { say: "Six digits in a row.", pic: 0 },
          { say: "You could read them one by one. Three, zero, five, four, two, zero." },
          { say: "But how many people is that? It doesn't say." },
          { say: "Look at the comma." },
        ],
        pictures: [chart(['305420'])] },
      { title: 'The big idea', text: 'Read the part before the comma, say "thousand" at the comma, then read the last three digits.',
        beats: [
          { say: 'Read the part before the comma, say "thousand" at the comma, then read the last three digits.', pic: 0 },
        ],
        pictures: [{ kind: 'eq', text: '305 , 420', lines: ['thousand , the rest'] }] },
      { title: 'Read the part before the comma', text: "Cover up everything after the comma. What's left is 305. Read it like a normal number. Three hundred five. Then say thousand. Three hundred five thousand.",
        beats: [
          { say: "Cover up everything after the comma. What's left is 305.", pic: 0 },
          { say: "Read it like a normal number. Three hundred five." },
          { say: "Then say thousand. Three hundred five thousand.", pic: 1 },
        ],
        pictures: [chart(['305420'], { mark: [[0, 0], [0, 1], [0, 2]], motion: true }), { kind: 'eq', text: '305 thousand' }] },
      { title: 'Read the last three digits', text: "Now the part after the comma. 420. Read it just as it is. Four hundred twenty. No extra word goes after it.",
        beats: [
          { say: "Now the part after the comma. 420.", pic: 0 },
          { say: "Read it just as it is. Four hundred twenty." },
          { say: "No extra word goes after it." },
        ],
        pictures: [chart(['305420'], { mark: [[0, 3], [0, 4], [0, 5]] })] },
      { title: 'Put the two parts together', text: "Put the two parts together. Three hundred five thousand, four hundred twenty. That's how many people live in the city.",
        beats: [
          { say: "Put the two parts together.", pic: 0 },
          { say: "Three hundred five thousand, four hundred twenty." },
          { say: "That's how many people live in the city." },
        ],
        pictures: [{ kind: 'eq', text: '305,420', lines: ['three hundred five thousand,', 'four hundred twenty'] }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't DROP the zero in three hundred five. 35 is not 305. The zero holds the tens place open. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't DROP the zero in three hundred five.", pic: 0 },
          { say: "35 is not 305. The zero holds the tens place open." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '35,420', right: '305,420' }] },
    ],
    turn: {
      text: 'Write this number with digits: two hundred forty-six thousand, one hundred eight.',
      picture: chart(['??????']),
      answer: 246108,
      steps: ['Before the comma: two hundred forty-six is 246.', 'After the comma: one hundred eight needs three digits, 108.', 'So the number is 246,108.'],
      prompt: 'Write the thousands group first. Then write three digits after the comma.',
      hint1: 'Write the group before "thousand" first: two hundred forty-six.',
      hint2: 'After the comma you always need three digits. One hundred eight has a zero in the tens.',
      twin: { text: 'Write this number with digits: seven hundred thirty thousand, fifty-two.',
        picture: chart(['??????']),
        answer: 730052,
        steps: ['Before the comma: seven hundred thirty is 730.', 'After the comma: fifty-two needs three digits, so write 052.', 'So the number is 730,052.'],
        hint1: 'Write the group before "thousand" first: seven hundred thirty.',
        hint2: 'After the comma you need three digits. Fifty-two has no hundreds, so start with a zero.' },
    },
    won: { text: 'You wrote the thousands group, then three digits after the comma.', sticker: 'What a digit is worth depends on its place. That is called place value.' },
    twinWon: { text: 'You wrote 730,052, with a zero holding the hundreds place open.', sticker: 'What a digit is worth depends on its place. That is called place value.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Write this number with digits: four hundred twelve thousand, three hundred fifty.',
        picture: chart(['??????']), answer: 412350,
        steps: ['Before the comma: four hundred twelve is 412.', 'After the comma: three hundred fifty is 350.', 'So the number is 412,350.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Write this number with digits: eighty-five thousand, six hundred seven.',
        picture: chart(['?????']), answer: 85607,
        steps: ['Before the comma: eighty-five is 85.', 'After the comma: six hundred seven needs a zero in the tens, 607.', 'So the number is 85,607.'] } },
      { why: 'Still "every digit has a place"', problem: { text: 'In 562,194, what is the 6 worth?',
        picture: chart(['562194']), answer: 60000,
        steps: ['The 6 is in the ten thousands place.', 'One ten thousand is 10,000, so 6 ten thousands is 60,000.', 'So the 6 is worth 60,000.'] } },
      { why: 'A little harder', problem: { text: 'Write this number with digits: nine hundred six thousand, forty.',
        picture: chart(['??????']), answer: 906040,
        steps: ['Before the comma: nine hundred six is 906.', 'After the comma: forty needs three digits, so write 040.', 'So the number is 906,040.'] } },
      { why: 'Same math in a story', problem: { text: 'A stadium sold four hundred eighty thousand, two hundred fifteen tickets this year. Write that number with digits.',
        picture: chart(['??????']), answer: 480215,
        steps: ['Before the comma: four hundred eighty is 480.', 'After the comma: two hundred fifteen is 215.', 'So the stadium sold 480,215 tickets.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t2', title: 'Each place is 10 times the next', skill: 'A digit in one place is worth 10 times what it is worth in the place to its right',
    bigIdea: 'Ten of one place make one of the next place to the left, so each place is worth 10 times the place to its right.',
    screens: [
      { title: 'Snap the cubes together', text: 'Here are 10 little cubes. Snap them into a row and they make one long stick. What if you keep going?',
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 0, ones: 10 }] },
      { title: 'The digits look the same', text: "Look at 440. Both first digits are 4. Are they worth the same? No. But how much more is one?",
        beats: [
          { say: "Look at 440. Both first digits are 4.", pic: 0 },
          { say: "Are they worth the same? No." },
          { say: "But how much more is one?" },
        ],
        pictures: [{ kind: 'eq', text: '440' }] },
      { title: 'The big idea', text: 'Ten of one place make one of the next place to the left, so each place is worth 10 times the place to its right.',
        beats: [
          { say: 'Ten of one place make one of the next place to the left, so each place is worth 10 times the place to its right.', pic: 0 },
        ],
        pictures: [{ kind: 'blocks', hundreds: 1, tens: 1, ones: 1 }] },
      { title: 'Ten ones make a ten', text: 'Take 10 little cubes and snap them together. They make 1 ten. So 1 ten is worth 10 ones.',
        beats: [
          { say: 'Take 10 little cubes and snap them together.', pic: 0 },
          { say: 'They make 1 ten. So 1 ten is worth 10 ones.' },
        ],
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 0, ones: 10, trade: 'ones', motion: true }] },
      { title: 'Ten tens make a hundred', text: 'Now snap 10 tens together. They make 1 hundred. See? 10 of one place make 1 of the next.',
        beats: [
          { say: 'Now snap 10 tens together.', pic: 0 },
          { say: 'They make 1 hundred.' },
          { say: 'See? 10 of one place make 1 of the next.' },
        ],
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 10, ones: 0, trade: 'tens', motion: true }] },
      { title: 'Back to 440', text: "Back to 440. The second 4 is worth 40. The first 4 is one place to the left, so it's worth 400. That's 10 times as much.",
        beats: [
          { say: "Back to 440. The second 4 is worth 40.", pic: 0 },
          { say: "The first 4 is one place to the left, so it's worth 400." },
          { say: "That's 10 times as much.", pic: 1 },
        ],
        pictures: [{ kind: 'table', head: ['hundreds', 'tens', 'ones'], rows: [['4', '4', '0']] },
          { kind: 'eq', text: '40 × 10 = 400' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't TAKE AWAY to find how many times. That gives 360. Count the 40s. 400 is 10 groups of 40. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't TAKE AWAY to find how many times.", pic: 0 },
          { say: "That gives 360. Count the 40s. 400 is 10 groups of 40." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '400 − 40 = 360', right: '400 = 10 × 40' }] },
    ],
    turn: {
      text: 'In 770, the first 7 is worth 700 and the second 7 is worth 70. How many times greater is the first 7?',
      picture: chart(['770']),
      answer: 10,
      steps: ['The first 7 is one place to the left of the second 7.', 'One place to the left is worth 10 times as much: 70 × 10 = 700.', 'So the first 7 is 10 times greater.'],
      prompt: 'Look at how far apart the two 7s are. Each step to the left is worth more.',
      hint1: 'How many 70s make 700?',
      hint2: 'Count by 70s until you reach 700. How many 70s did you count?',
      twin: { text: 'In 3,300, the first 3 is worth 3,000 and the second 3 is worth 300. How many times greater is the first 3?',
        picture: chart(['3300']),
        answer: 10,
        steps: ['The first 3 is one place to the left of the second 3.', 'One place to the left is worth 10 times as much: 300 × 10 = 3,000.', 'So the first 3 is 10 times greater.'],
        hint1: 'Is the first 3 one place or two places to the left of the second 3?',
        hint2: 'How many 300s make 3,000?' },
    },
    won: { text: 'You saw that one step to the left is worth 10 times as much.', sticker: 'Each place is worth 10 times the place to its right. That is how place value works.' },
    twinWon: { text: 'You saw that 3,000 is 10 times 300.', sticker: 'Each place is worth 10 times the place to its right. That is how place value works.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'In 550, the first 5 is worth 500 and the second 5 is worth 50. How many times greater is the first 5?',
        picture: chart(['550']), answer: 10,
        steps: ['The first 5 is one place to the left of the second 5.', '50 × 10 = 500.', 'So the first 5 is 10 times greater.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What number is 10 times 400?',
        picture: { kind: 'blocks', hundreds: 4, tens: 0, ones: 0 }, answer: 4000,
        steps: ['10 hundreds make 1 thousand.', 'So 10 times 4 hundreds is 4 thousands.', 'So 10 times 400 is 4,000.'] } },
      { why: 'Still "10 of one place make the next"', problem: { text: 'How many hundreds make 2,000?',
        picture: chart(['2000']), answer: 20,
        steps: ['1 thousand is 10 hundreds.', '2 thousands is 10 hundreds and 10 more hundreds.', 'So 20 hundreds make 2,000.'] } },
      { why: 'A little harder', problem: { text: 'What number is 10 times 7,000?',
        picture: chart(['7000']), answer: 70000,
        steps: ['10 thousands make 1 ten thousand.', 'So 10 times 7 thousands is 7 ten thousands.', 'So 10 times 7,000 is 70,000.'] } },
      { why: 'Same math in a story', problem: { text: 'A factory puts 100 buttons in a bag. A box holds 10 bags. How many buttons are in a box?',
        picture: { kind: 'table', head: ['bags', 'buttons'], rows: [['1', '100'], ['10', '?']] }, answer: 1000,
        steps: ['A box has 10 bags of 100 buttons.', '10 times 100 moves one place to the left: 1,000.', 'So a box holds 1,000 buttons.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t3', title: 'Compare big numbers', skill: 'Compare multi-digit numbers with <, > and =',
    bigIdea: 'Line the numbers up by place, and the first place from the left where the digits differ decides which is bigger.',
    screens: [
      { title: 'Two cities', text: 'City A has 48,250 people. City B has 46,980 people. Which city has more?',
        pictures: [chart(['48250', '46980'], { labels: ['A', 'B'] })] },
      { title: 'Big digits can trick you', text: "City B has a 9 and an 8. Big digits. So does City B have more? Not so fast. Big digits in small places can trick you.",
        beats: [
          { say: "City B has a 9 and an 8. Big digits.", pic: 0 },
          { say: "So does City B have more? Not so fast." },
          { say: "Big digits in small places can trick you." },
        ],
        pictures: [chart(['48250', '46980'], { labels: ['A', 'B'], mark: [[1, 3], [1, 4]] })] },
      { title: 'The big idea', text: 'Line the numbers up by place, and the first place from the left where the digits differ decides which is bigger.',
        beats: [
          { say: 'Line the numbers up by place, and the first place from the left where the digits differ decides which is bigger.', pic: 0 },
        ],
        pictures: [chart(['48250', '46980'], { labels: ['A', 'B'] })] },
      { title: 'Line up the places', text: "So put both numbers in a chart. Every digit goes under its own place. Now we can compare straight down.",
        beats: [
          { say: "So put both numbers in a chart.", pic: 0 },
          { say: "Every digit goes under its own place." },
          { say: "Now we can compare straight down." },
        ],
        pictures: [chart(['48250', '46980'], { labels: ['A', 'B'], motion: true })] },
      { title: 'Start at the left', text: "Start at the left, the biggest place. Ten thousands: 4 and 4. The same, so keep going. Thousands: 8 and 6. They're different. This place decides.",
        beats: [
          { say: "Start at the left, the biggest place.", pic: 0 },
          { say: "Ten thousands: 4 and 4. The same, so keep going." },
          { say: "Thousands: 8 and 6. They're different. This place decides." },
        ],
        pictures: [chart(['48250', '46980'], { labels: ['A', 'B'], mark: [[0, 2], [1, 2]] })] },
      { title: 'The first difference decides', text: "8 thousands is more than 6 thousands. So City A has more. 48,250 is greater than 46,980. The digits after that don't matter at all.",
        beats: [
          { say: "8 thousands is more than 6 thousands." },
          { say: "So City A has more. 48,250 is greater than 46,980.", pic: 0 },
          { say: "The digits after that don't matter at all." },
        ],
        pictures: [{ kind: 'eq', text: '48,250 > 46,980' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't just compare the FIRST digits. 9,870 starts with 9, but it has no ten thousands. 10,200 does, so it's bigger. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't just compare the FIRST digits.", pic: 1 },
          { say: "9,870 starts with 9, but it has no ten thousands.", pic: 0 },
          { say: "10,200 does, so it's bigger." },
          { say: "Okay. Your turn." },
        ],
        pictures: [chart(['9870', '10200']), { kind: 'cards', wrong: '9,870 > 10,200', right: '9,870 < 10,200' }] },
    ],
    turn: {
      text: 'Pick the sign that makes it true: 57,340 __ 57,290',
      picture: chart(['57340', '57290']),
      answer: { choices: LT, correct: 1 },
      steps: ['Ten thousands and thousands are the same: 5 and 7.', 'Hundreds: 3 is more than 2.', 'So 57,340 > 57,290.'],
      prompt: 'Line up the places. Find the first place where the digits are different.',
      hint1: 'Start at the biggest place. Move right until two digits are different.',
      hint2: 'The ten thousands and the thousands match. Look at the hundreds.',
      twin: { text: 'Pick the sign that makes it true: 63,105 __ 63,150',
        picture: chart(['63105', '63150']),
        answer: { choices: LT, correct: 0 },
        steps: ['Ten thousands, thousands and hundreds are the same: 6, 3 and 1.', 'Tens: 0 is less than 5.', 'So 63,105 < 63,150.'],
        hint1: 'Line up the places. Which place is the first to be different?',
        hint2: 'The ten thousands, thousands and hundreds match. Look at the tens.' },
    },
    won: { text: 'You lined up the places and let the first different digit decide.', sticker: '> means greater than. < means less than.' },
    twinWon: { text: 'You found the first different place and saw that 63,105 < 63,150.', sticker: '> means greater than. < means less than.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Pick the sign that makes it true: 82,460 __ 84,120',
        picture: chart(['82460', '84120']), answer: { choices: LT, correct: 0 },
        steps: ['Ten thousands are the same: 8.', 'Thousands: 2 is less than 4.', 'So 82,460 < 84,120.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Pick the sign that makes it true: 291,054 __ 219,504',
        picture: chart(['291054', '219504']), answer: { choices: LT, correct: 1 },
        steps: ['Hundred thousands are the same: 2.', 'Ten thousands: 9 is more than 1.', 'So 291,054 > 219,504.'] } },
      { why: 'Still "line up the places"', problem: { text: 'Pick the sign that makes it true: 6,999 __ 10,001',
        picture: chart(['6999', '10001']), answer: { choices: LT, correct: 0 },
        steps: ['Line up the places. 10,001 has a ten thousand. 6,999 has none.', 'The first different place is the ten thousands: 0 is less than 1.', 'So 6,999 < 10,001.'] } },
      { why: 'A little harder', problem: { text: 'Pick the sign that makes it true: 740,915 __ 740,195',
        picture: chart(['740915', '740195']), answer: { choices: LT, correct: 1 },
        steps: ['Hundred thousands, ten thousands and thousands are the same: 7, 4 and 0.', 'Hundreds: 9 is more than 1.', 'So 740,915 > 740,195.'] } },
      { why: 'Same math in a story', problem: { text: 'A zoo had 125,640 visitors in June and 125,604 in July. Pick the sign: June __ July',
        picture: chart(['125640', '125604'], { labels: ['June', 'July'] }), answer: { choices: LT, correct: 1 },
        steps: ['The hundred thousands, ten thousands, thousands and hundreds all match.', 'Tens: 4 is more than 0.', 'So 125,640 > 125,604. June had more.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t4', title: 'Round big numbers', skill: 'Round multi-digit numbers to any place',
    bigIdea: 'A number rounds to the closer of the two round numbers it sits between, and the exact middle rounds up.',
    screens: [
      { title: 'About how many fans?', text: 'A game had 36,420 fans. The news wants to say it with a round number of thousands. What should it say?',
        pictures: [{ kind: 'numline', min: 36000, max: 37000, ticks: 10, labels: 'none', points: [{ at: 36420, label: '36,420' }] }] },
      { title: 'Crossing out is not enough', text: "You could cross out the last three digits. 36,420 becomes 36,000. But try 36,720. It becomes 36,000 too. Is that right? No. It's closer to 37,000.",
        beats: [
          { say: "You could cross out the last three digits." },
          { say: "36,420 becomes 36,000." },
          { say: "But try 36,720. It becomes 36,000 too." },
          { say: "Is that right? No. It's closer to 37,000.", pic: 0 },
        ],
        pictures: [{ kind: 'numline', min: 36000, max: 37000, ticks: 10, labels: 'ends', points: [{ at: 36720, label: '36,720' }] }] },
      { title: 'The big idea', text: 'A number rounds to the closer of the two round numbers it sits between, and the exact middle rounds up.',
        beats: [
          { say: 'A number rounds to the closer of the two round numbers it sits between, and the exact middle rounds up.', pic: 0 },
        ],
        pictures: [{ kind: 'numline', min: 36000, max: 37000, ticks: 10, labels: 'ends' }] },
      { title: 'Find the two round thousands', text: "Look at 36,420. It's more than 36,000 and less than 37,000. So those are the two ends of the line.",
        beats: [
          { say: "Look at 36,420." },
          { say: "It's more than 36,000 and less than 37,000." },
          { say: "So those are the two ends of the line.", pic: 0 },
        ],
        pictures: [{ kind: 'numline', min: 36000, max: 37000, ticks: 10, labels: 'ends', points: [{ at: 36420, label: '36,420' }] }] },
      { title: 'Find the middle', text: "Now find the middle. Halfway from 36,000 to 37,000 is 36,500. Has 36,420 reached it? Not yet. It's still closer to 36,000.",
        beats: [
          { say: "Now find the middle. Halfway from 36,000 to 37,000 is 36,500.", pic: 0 },
          { say: "Has 36,420 reached it? Not yet." },
          { say: "It's still closer to 36,000." },
        ],
        pictures: [{ kind: 'numline', min: 36000, max: 37000, ticks: 10, motion: true,
          labels: ['36,000', null, null, null, null, '36,500', null, null, null, null, '37,000'],
          points: [{ at: 36420, label: '36,420' }], jumps: [{ from: 36420, to: 36000 }] }] },
      { title: 'Round to the closer end', text: "So 36,420 rounds to 36,000. The news says about 36,000 fans. Quick check. The digit after the thousands is 4, and less than 5 rounds down.",
        beats: [
          { say: "So 36,420 rounds to 36,000. The news says about 36,000 fans.", pic: 0 },
          { say: "Quick check. The digit after the thousands is 4, and less than 5 rounds down." },
        ],
        pictures: [{ kind: 'eq', text: '36,420 → 36,000' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Exactly in the middle, don't round DOWN. 36,500 is halfway, and halfway goes up, to 37,000. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Exactly in the middle, don't round DOWN.", pic: 0 },
          { say: "36,500 is halfway, and halfway goes up, to 37,000." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '36,500 → 36,000', right: '36,500 → 37,000' }] },
    ],
    turn: {
      text: 'Round 52,780 to the nearest thousand.',
      picture: { kind: 'numline', min: 52000, max: 53000, ticks: 10, labels: 'none', points: [{ at: 52780, label: '52,780' }] },
      answer: 53000,
      steps: ['52,780 is between 52,000 and 53,000.', 'Halfway is 52,500, and 52,780 is past halfway.', 'So 52,780 rounds to 53,000.'],
      prompt: 'Find the two round thousands it is between. Which one is closer?',
      hint1: 'Which two round thousands is 52,780 between?',
      hint2: 'Look at the hundreds digit. Is it 5 or more?',
      twin: { text: 'Round 71,490 to the nearest thousand.',
        picture: { kind: 'numline', min: 71000, max: 72000, ticks: 10, labels: 'none', points: [{ at: 71490, label: '71,490' }] },
        answer: 71000,
        steps: ['71,490 is between 71,000 and 72,000.', 'Halfway is 71,500, and 71,490 has not reached it.', 'So 71,490 rounds to 71,000.'],
        hint1: 'Which two round thousands is 71,490 between?',
        hint2: 'Find the middle between them. Is 71,490 before it or past it?' },
    },
    won: { text: 'You found the two round numbers and picked the closer one.', sticker: 'Rounding means going to the closer round number. The digit to the right decides.' },
    twinWon: { text: 'You saw 71,490 is just before halfway, so it rounds to 71,000.', sticker: 'Rounding means going to the closer round number. The digit to the right decides.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Round 24,630 to the nearest thousand.',
        picture: { kind: 'numline', min: 24000, max: 25000, ticks: 10, labels: 'none', points: [{ at: 24630, label: '24,630' }] }, answer: 25000,
        steps: ['24,630 is between 24,000 and 25,000.', 'The hundreds digit is 6, which is 5 or more.', 'So 24,630 rounds to 25,000.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Round 8,350 to the nearest hundred.',
        picture: { kind: 'numline', min: 8300, max: 8400, ticks: 10, labels: 'none', points: [{ at: 8350, label: '8,350' }] }, answer: 8400,
        steps: ['8,350 is between 8,300 and 8,400.', '8,350 is exactly halfway, and halfway rounds up.', 'So 8,350 rounds to 8,400.'] } },
      { why: 'Still "go to the closer one"', problem: { text: 'Round 147,200 to the nearest ten thousand.',
        picture: { kind: 'numline', min: 140000, max: 150000, ticks: 10, labels: 'none', points: [{ at: 147200, label: '147,200' }] }, answer: 150000,
        steps: ['147,200 is between 140,000 and 150,000.', 'The thousands digit is 7, which is 5 or more.', 'So 147,200 rounds to 150,000.'] } },
      { why: 'A little harder', problem: { text: 'Round 603,950 to the nearest thousand.',
        picture: { kind: 'numline', min: 603000, max: 604000, ticks: 10, labels: 'none', points: [{ at: 603950, label: '603,950' }] }, answer: 604000,
        steps: ['603,950 is between 603,000 and 604,000.', 'The hundreds digit is 9, which is 5 or more.', 'So 603,950 rounds to 604,000.'] } },
      { why: 'Same math in a story', problem: { text: 'A school library has 12,480 books. Round the number of books to the nearest hundred.',
        picture: { kind: 'numline', min: 12400, max: 12500, ticks: 10, labels: 'none', points: [{ at: 12480, label: '12,480' }] }, answer: 12500,
        steps: ['12,480 is between 12,400 and 12,500.', 'The tens digit is 8, which is 5 or more.', 'So about 12,500 books.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t5', title: 'Add big numbers', skill: 'Add multi-digit numbers with the standard algorithm',
    bigIdea: 'Line up the places and add from the ones. When a place makes 10 or more, carry 1 to the next place left.',
    screens: [
      { title: 'Two days of visitors', text: 'A museum had 2,456 visitors on Saturday and 1,378 on Sunday. How many visitors came in all?',
        pictures: [{ kind: 'columns', rows: ['2456', '1378'], op: '+' }] },
      { title: 'Too big to count on', text: 'Could you count up from 2,456 one at a time? You could, but you would be there all day. And holding all those digits in your head at once is hard too.',
        beats: [
          { say: 'Could you count up from 2,456 one at a time?', pic: 0 },
          { say: 'You could, but you would be there all day.' },
          { say: 'And holding all those digits in your head at once is hard too.' },
        ],
        pictures: [{ kind: 'columns', rows: ['2456', '1378'], op: '+' }] },
      { title: 'The big idea', text: 'Line up the places and add from the ones. When a place makes 10 or more, carry 1 to the next place left.',
        beats: [
          { say: 'Line up the places and add from the ones.', pic: 0 },
          { say: 'When a place makes 10 or more, carry 1 to the next place left.' },
        ],
        pictures: [{ kind: 'columns', rows: ['2456', '1378'], op: '+', places: ['Th', 'H', 'T', 'O'] }] },
      { title: 'Start with the ones', text: 'Always start on the right, with the ones. 6 plus 8 is 14, and 14 is too big to fit in one place. It is 1 ten and 4 ones, so the 4 stays here and the 1 goes up to the tens.',
        beats: [
          { say: 'Always start on the right, with the ones.' },
          { say: '6 plus 8 is 14, and 14 is too big to fit in one place.' },
          { say: 'It is 1 ten and 4 ones, so the 4 stays here and the 1 goes up to the tens.', pic: 0, write: '10 or more → carry 1 to the left' },
        ],
        pictures: [{ kind: 'columns', rows: ['2456', '1378'], op: '+', places: ['Th', 'H', 'T', 'O'], carry: '1 ', answer: '4', motion: true }] },
      { title: 'Now the tens and hundreds', text: "Tens now, and don't forget that carried 1. 5 plus 7 plus 1 is 13, so write the 3 and carry another 1. Hundreds: 4 plus 3 plus 1 is 8. That one fits, so there is nothing to carry.",
        beats: [
          { say: "Tens now, and don't forget that carried 1." },
          { say: '5 plus 7 plus 1 is 13, so write the 3 and carry another 1.', pic: 0 },
          { say: 'Hundreds: 4 plus 3 plus 1 is 8. That one fits, so there is nothing to carry.' },
        ],
        pictures: [{ kind: 'columns', rows: ['2456', '1378'], op: '+', places: ['Th', 'H', 'T', 'O'], carry: '11 ', answer: '834', motion: true }] },
      { title: 'Finish with the thousands', text: 'Last place, the thousands. 2 plus 1 is 3, and nothing to carry. So 3,834 visitors came in all.',
        beats: [
          { say: 'Last place, the thousands.' },
          { say: '2 plus 1 is 3, and nothing to carry.', pic: 0 },
          { say: 'So 3,834 visitors came in all.' },
        ],
        pictures: [{ kind: 'columns', rows: ['2456', '1378'], op: '+', places: ['Th', 'H', 'T', 'O'], carry: '11 ', answer: '3834' }] },
      { title: 'One thing not to do', text: "Here is where most mistakes happen. Don't forget to add the 1 you carried. Leave it out and you get 3,724 instead of 3,834.",
        beats: [
          { say: 'Here is where most mistakes happen.' },
          { say: "Don't forget to add the 1 you carried.", pic: 0 },
          { say: 'Leave it out and you get 3,724 instead of 3,834.' },
        ],
        pictures: [{ kind: 'cards', wrong: '2,456 + 1,378 = 3,724', right: '2,456 + 1,378 = 3,834' }] },
    ],
    turn: {
      text: 'Add: 3,467 + 2,385',
      picture: { kind: 'columns', rows: ['3467', '2385'], op: '+', answer: null },
      answer: 5852,
      steps: ['Ones: 7 + 5 = 12. Write 2, carry 1.', 'Tens: 6 + 8 + 1 = 15. Write 5, carry 1. Hundreds: 4 + 3 + 1 = 8.', 'Thousands: 3 + 2 = 5. So the total is 5,852.'],
      prompt: 'Start with the ones. Carry when a place makes 10 or more.',
      hint1: 'Start with the ones. If you get 10 or more, carry 1 to the tens.',
      hint2: 'Ones: 7 + 5 = 12. Write 2 and carry 1. Keep going to the left.',
      twin: { text: 'Add: 4,578 + 1,264',
        picture: { kind: 'columns', rows: ['4578', '1264'], op: '+', answer: null },
        answer: 5842,
        steps: ['Ones: 8 + 4 = 12. Write 2, carry 1.', 'Tens: 7 + 6 + 1 = 14. Write 4, carry 1. Hundreds: 5 + 2 + 1 = 8.', 'Thousands: 4 + 1 = 5. So the total is 5,842.'],
        hint1: 'Add the ones first. Carry when you make 10 or more.',
        hint2: 'Ones: 8 + 4 = 12. Write 2 and carry 1 to the tens.' },
    },
    won: { text: 'You added one place at a time and carried when you had to.', sticker: 'Carrying to the next place is called regrouping. This way of adding is the standard algorithm.' },
    twinWon: { text: 'You carried 1 twice and found 4,578 + 1,264 = 5,842.', sticker: 'Carrying to the next place is called regrouping. This way of adding is the standard algorithm.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Add: 2,345 + 1,487',
        picture: { kind: 'columns', rows: ['2345', '1487'], op: '+', answer: null }, answer: 3832,
        steps: ['Ones: 5 + 7 = 12. Write 2, carry 1.', 'Tens: 4 + 8 + 1 = 13. Write 3, carry 1. Hundreds: 3 + 4 + 1 = 8.', 'Thousands: 2 + 1 = 3. So the total is 3,832.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Add: 6,209 + 2,856',
        picture: { kind: 'columns', rows: ['6209', '2856'], op: '+', answer: null }, answer: 9065,
        steps: ['Ones: 9 + 6 = 15. Write 5, carry 1. Tens: 0 + 5 + 1 = 6.', 'Hundreds: 2 + 8 = 10. Write 0, carry 1.', 'Thousands: 6 + 2 + 1 = 9. So the total is 9,065.'] } },
      { why: 'Still "carry to the next place"', problem: { text: 'Add: 45,378 + 27,946',
        picture: { kind: 'columns', rows: ['45378', '27946'], op: '+', answer: null }, answer: 73324,
        steps: ['Ones: 8 + 6 = 14. Write 4, carry 1. Tens: 7 + 4 + 1 = 12. Write 2, carry 1.', 'Hundreds: 3 + 9 + 1 = 13. Write 3, carry 1. Thousands: 5 + 7 + 1 = 13. Write 3, carry 1.', 'Ten thousands: 4 + 2 + 1 = 7. So the total is 73,324.'] } },
      { why: 'A little harder', problem: { text: 'Add: 386,547 + 248,695',
        picture: { kind: 'columns', rows: ['386547', '248695'], op: '+', answer: null }, answer: 635242,
        steps: ['Ones: 7 + 5 = 12, write 2. Tens: 4 + 9 + 1 = 14, write 4. Hundreds: 5 + 6 + 1 = 12, write 2.', 'Thousands: 6 + 8 + 1 = 15, write 5. Ten thousands: 8 + 4 + 1 = 13, write 3. Carry 1 each time.', 'Hundred thousands: 3 + 2 + 1 = 6. So the total is 635,242.'] } },
      { why: 'Same math in a story', problem: { text: 'A farm picked 18,736 apples in September and 24,588 in October. How many apples did it pick in all?',
        picture: { kind: 'columns', rows: ['18736', '24588'], op: '+', answer: null }, answer: 43324,
        steps: ['Ones: 6 + 8 = 14, write 4. Tens: 3 + 8 + 1 = 12, write 2. Carry 1 each time.', 'Hundreds: 7 + 5 + 1 = 13, write 3. Thousands: 8 + 4 + 1 = 13, write 3. Carry 1 each time.', 'Ten thousands: 1 + 2 + 1 = 4. So the farm picked 43,324 apples.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t6', title: 'Subtract big numbers (across zeros)', skill: 'Subtract multi-digit numbers when the top number has zeros',
    bigIdea: 'If a place is too small and the places next to it are zeros, go left to the first digit that is not zero. Break one of those, and each zero on the way becomes 9.',
    screens: [
      { title: 'Money for books', text: 'A school raised $3,005. It spent $1,247 on books. How much money is left?',
        pictures: [{ kind: 'columns', rows: ['3005', '1247'], op: '−' }] },
      { title: 'Nothing next door', text: 'Start at the ones, like always. You cannot take 7 from 5, so you go next door for a ten. But look. There are 0 tens, and 0 hundreds too. There is nothing next door to borrow.',
        beats: [
          { say: 'Start at the ones, like always. You cannot take 7 from 5, so you go next door for a ten.', pic: 0 },
          { say: 'But look. There are 0 tens, and 0 hundreds too.' },
          { say: 'There is nothing next door to borrow.' },
        ],
        pictures: [{ kind: 'columns', rows: ['3005', '1247'], op: '−', places: ['Th', 'H', 'T', 'O'] }] },
      { title: 'The big idea', text: 'If a place is too small and the places next to it are zeros, go left to the first digit that is not zero. Break one of those, and each zero on the way becomes 9.',
        beats: [
          { say: 'If a place is too small and the places next to it are zeros, go left to the first digit that is not zero.', pic: 0 },
          { say: 'Break one of those, and each zero on the way becomes 9.' },
        ],
        pictures: [{ kind: 'columns', rows: ['3005', '1247'], op: '−', places: ['Th', 'H', 'T', 'O'] }] },
      { title: 'Go to the first digit that is not zero', text: 'So keep walking left until you find a digit that is not zero. Here that is the 3 in the thousands. Break 1 thousand open into 10 hundreds, and 2 thousands are left behind.',
        beats: [
          { say: 'So keep walking left until you find a digit that is not zero.', write: 'walk left to the first digit that is not 0' },
          { say: 'Here that is the 3 in the thousands.' },
          { say: 'Break 1 thousand open into 10 hundreds, and 2 thousands are left behind.', pic: 0 },
        ],
        pictures: [{ kind: 'columns', rows: ['3005', '1247'], op: '−', places: ['Th', 'H', 'T', 'O'], carry: '2   ', motion: true }] },
      { title: 'Keep breaking', text: 'Now keep breaking, one place at a time. Break 1 of those hundreds into 10 tens, and 9 hundreds are left. Break 1 of those tens into 10 ones, and 9 tens are left with 15 ones at the end.',
        beats: [
          { say: 'Now keep breaking, one place at a time.' },
          { say: 'Break 1 of those hundreds into 10 tens, and 9 hundreds are left.', pic: 0 },
          { say: 'Break 1 of those tens into 10 ones, and 9 tens are left with 15 ones at the end.', pic: 1 },
        ],
        pictures: [{ kind: 'columns', rows: ['3005', '1247'], op: '−', places: ['Th', 'H', 'T', 'O'], carry: '299 ', motion: true },
          { kind: 'eq', text: '2 thousands, 9 hundreds, 9 tens, 15 ones' }] },
      { title: 'Now take away', text: 'Now every place has enough, so we can take away. 15 minus 7 is 8. 9 minus 4 is 5. 9 minus 2 is 7. And 2 minus 1 is 1. So the school has $1,758 left.',
        beats: [
          { say: 'Now every place has enough, so we can take away.' },
          { say: '15 minus 7 is 8. 9 minus 4 is 5. 9 minus 2 is 7. And 2 minus 1 is 1.', pic: 0 },
          { say: 'So the school has $1,758 left.' },
        ],
        pictures: [{ kind: 'columns', rows: ['3005', '1247'], op: '−', places: ['Th', 'H', 'T', 'O'], carry: '299 ', answer: '1758' }] },
      { title: 'One thing not to do', text: "Here is the shortcut that looks tempting and is wrong. Don't flip the digits around and take 5 from 7 because it is easier. Always take the bottom digit from the top one, and break a bigger place when the top is too small.",
        beats: [
          { say: 'Here is the shortcut that looks tempting and is wrong.' },
          { say: "Don't flip the digits around and take 5 from 7 because it is easier.", pic: 0 },
          { say: 'Always take the bottom digit from the top one, and break a bigger place when the top is too small.' },
        ],
        pictures: [{ kind: 'cards', wrong: '3,005 − 1,247 = 2,242', right: '3,005 − 1,247 = 1,758' }] },
    ],
    turn: {
      text: 'Subtract: 5,004 − 2,318',
      picture: { kind: 'columns', rows: ['5004', '2318'], op: '−', answer: null },
      answer: 2686,
      steps: ['4 ones is not enough, and the tens and hundreds are 0. Break 1 of the 5 thousands.', 'Now there are 4 thousands, 9 hundreds, 9 tens and 14 ones.', '14 − 8 = 6, 9 − 1 = 8, 9 − 3 = 6, 4 − 2 = 2. So the answer is 2,686.'],
      prompt: 'Go left to the first digit that is not zero. Break it, then take away place by place.',
      hint1: 'You cannot take 8 from 4. Which is the first place to the left that is not 0?',
      hint2: 'Break 1 thousand. The hundreds and tens both become 9, and the ones become 14.',
      twin: { text: 'Subtract: 7,002 − 3,465',
        picture: { kind: 'columns', rows: ['7002', '3465'], op: '−', answer: null },
        answer: 3537,
        steps: ['2 ones is not enough, and the tens and hundreds are 0. Break 1 of the 7 thousands.', 'Now there are 6 thousands, 9 hundreds, 9 tens and 12 ones.', '12 − 5 = 7, 9 − 6 = 3, 9 − 4 = 5, 6 − 3 = 3. So the answer is 3,537.'],
        hint1: 'You cannot take 5 from 2. Look left for the first place that is not 0.',
        hint2: 'Break 1 of the 7 thousands. The zeros become 9s, and the ones become 12.' },
    },
    won: { text: 'You went past the zeros, broke a thousand, and took away place by place.', sticker: 'Breaking a bigger place into smaller ones is called regrouping.' },
    twinWon: { text: 'You broke a thousand to get past the zeros: 7,002 − 3,465 = 3,537.', sticker: 'Breaking a bigger place into smaller ones is called regrouping.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Subtract: 6,003 − 2,475',
        picture: { kind: 'columns', rows: ['6003', '2475'], op: '−', answer: null }, answer: 3528,
        steps: ['Break 1 of the 6 thousands. Now there are 5 thousands, 9 hundreds, 9 tens and 13 ones.', '13 − 5 = 8, 9 − 7 = 2, 9 − 4 = 5, 5 − 2 = 3.', 'So the answer is 3,528.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Subtract: 8,000 − 3,642',
        picture: { kind: 'columns', rows: ['8000', '3642'], op: '−', answer: null }, answer: 4358,
        steps: ['Break 1 of the 8 thousands. Now there are 7 thousands, 9 hundreds, 9 tens and 10 ones.', '10 − 2 = 8, 9 − 4 = 5, 9 − 6 = 3, 7 − 3 = 4.', 'So the answer is 4,358.'] } },
      { why: 'Still "each zero becomes 9"', problem: { text: 'Subtract: 7,000 − 2,381',
        picture: { kind: 'columns', rows: ['7000', '2381'], op: '−', answer: null }, answer: 4619,
        steps: ['Break 1 of the 7 thousands. Now there are 6 thousands, 9 hundreds, 9 tens and 10 ones.', '10 − 1 = 9, 9 − 8 = 1, 9 − 3 = 6, 6 − 2 = 4.', 'So the answer is 4,619.'] } },
      { why: 'A little harder', problem: { text: 'Subtract: 20,005 − 7,318',
        picture: { kind: 'columns', rows: ['20005', '7318'], op: '−', answer: null }, answer: 12687,
        steps: ['The first digit that is not zero is the 2 ten thousands. Break 1 of them.', 'Now there is 1 ten thousand, 9 thousands, 9 hundreds, 9 tens and 15 ones.', '15 − 8 = 7, 9 − 1 = 8, 9 − 3 = 6, 9 − 7 = 2, 1 − 0 = 1. So the answer is 12,687.'] } },
      { why: 'Same math in a story', problem: { text: 'A bakery made 5,000 cookies for a fair. It sold 3,764. How many cookies are left?',
        picture: { kind: 'columns', rows: ['5000', '3764'], op: '−', answer: null }, answer: 1236,
        steps: ['Break 1 of the 5 thousands. Now there are 4 thousands, 9 hundreds, 9 tens and 10 ones.', '10 − 4 = 6, 9 − 6 = 3, 9 − 7 = 2, 4 − 3 = 1.', 'So 1,236 cookies are left.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t7', title: 'Is my answer about right?', skill: 'Estimate a sum or difference by rounding, and check if an answer is reasonable',
    bigIdea: 'Round each number to an easy one and do the math with those. If your answer is far from that, check your work.',
    screens: [
      { title: 'Did Maya add right?', text: 'Maya added 4,875 + 2,960 and got 6,835. How can she tell if that is about right, without doing it all again?',
        pictures: [{ kind: 'eq', text: '4,875 + 2,960 = 6,835' }] },
      { title: 'Doing it again is slow', text: 'She could add the whole thing again. But that takes time, and here is the catch. If she made a slip the first time, she might make the very same slip again.',
        beats: [
          { say: 'She could add the whole thing again.' },
          { say: 'But that takes time, and here is the catch. If she made a slip the first time, she might make the very same slip again.', pic: 0 },
        ],
        pictures: [{ kind: 'table', head: ['number', 'nearest thousand'], rows: [['4,875', '?'], ['2,960', '?']] }] },
      { title: 'The big idea', text: 'Round each number to an easy one and do the math with those. If your answer is far from that, check your work.',
        beats: [
          { say: 'Round each number to an easy one and do the math with those.', pic: 0 },
          { say: 'If your answer is far from that, check your work.' },
        ],
        pictures: [{ kind: 'table', head: ['number', 'nearest thousand'], rows: [['4,875', '?'], ['2,960', '?']] }] },
      { title: 'Round each number', text: 'So round first. Nearest thousand for both of them. 4,875 rounds up to 5,000, and 2,960 rounds up to 3,000.',
        beats: [
          { say: 'So round first. Nearest thousand for both of them.', write: 'round first, then do the easy math' },
          { say: '4,875 rounds up to 5,000, and 2,960 rounds up to 3,000.', pic: 0 },
        ],
        pictures: [{ kind: 'table', head: ['number', 'nearest thousand'], rows: [['4,875', '5,000'], ['2,960', '3,000']], motion: true }] },
      { title: 'Add the round numbers', text: 'Now add the round numbers instead of the messy ones. 5,000 plus 3,000 is 8,000, and you can do that in your head without writing a thing.',
        beats: [
          { say: 'Now add the round numbers instead of the messy ones.', pic: 0 },
          { say: '5,000 plus 3,000 is 8,000, and you can do that in your head without writing a thing.', pic: 1 },
        ],
        pictures: [{ kind: 'table', head: ['number', 'nearest thousand'], rows: [['4,875', '5,000'], ['2,960', '3,000']], mark: [[0, 1], [1, 1]] },
          { kind: 'eq', text: '5,000 + 3,000 = 8,000' }] },
      { title: 'Compare', text: "Now compare. Maya's answer was 6,835, and that is a long way from 8,000. That gap is telling her to go back and check. When she adds again she gets 7,835, and that sits right next to 8,000.",
        beats: [
          { say: 'Now compare.' },
          { say: "Maya's answer was 6,835, and that is a long way from 8,000.", pic: 0 },
          { say: 'That gap is telling her to go back and check. When she adds again she gets 7,835, and that sits right next to 8,000.' },
        ],
        pictures: [{ kind: 'eq', text: '6,835 is far from 8,000', lines: ['7,835 is close to 8,000'] }] },
      { title: 'One thing not to do', text: "One last thing. Don't hand in the round answer as if it were the real one. 8,000 only tells you about where the real answer should land.",
        beats: [
          { say: 'One last thing.' },
          { say: "Don't hand in the round answer as if it were the real one.", pic: 0 },
          { say: '8,000 only tells you about where the real answer should land.' },
        ],
        pictures: [{ kind: 'cards', wrong: '4,875 + 2,960 = 8,000', right: '4,875 + 2,960 is about 8,000' }] },
    ],
    turn: {
      text: 'Round each number to the nearest thousand, then add. About how much is 3,812 + 5,190?',
      picture: { kind: 'table', head: ['number', 'nearest thousand'], rows: [['3,812', '?'], ['5,190', '?']] },
      answer: 9000,
      steps: ['3,812 rounds to 4,000. 5,190 rounds to 5,000.', '4,000 + 5,000 = 9,000.', 'So 3,812 + 5,190 is about 9,000.'],
      prompt: 'Round each number to the nearest thousand. Then add the round numbers.',
      hint1: 'Round each number to the nearest thousand first.',
      hint2: 'Look at the hundreds digit of each number. 5 or more rounds up.',
      twin: { text: 'Round each number to the nearest thousand, then add. About how much is 6,420 + 1,745?',
        picture: { kind: 'table', head: ['number', 'nearest thousand'], rows: [['6,420', '?'], ['1,745', '?']] },
        answer: 8000,
        steps: ['6,420 rounds to 6,000. 1,745 rounds to 2,000.', '6,000 + 2,000 = 8,000.', 'So 6,420 + 1,745 is about 8,000.'],
        hint1: 'Round 6,420 to the nearest thousand. Then round 1,745.',
        hint2: 'Is each hundreds digit 5 or more? Then add the two round numbers.' },
    },
    won: { text: 'You rounded first, so the math was easy to do in your head.', sticker: 'An answer that is about right is called an estimate.' },
    twinWon: { text: 'You rounded 6,420 and 1,745 and found about 8,000.', sticker: 'An answer that is about right is called an estimate.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Round each number to the nearest thousand, then add. About how much is 2,780 + 4,105?',
        picture: { kind: 'table', head: ['number', 'nearest thousand'], rows: [['2,780', '?'], ['4,105', '?']] }, answer: 7000,
        steps: ['2,780 rounds to 3,000. 4,105 rounds to 4,000.', '3,000 + 4,000 = 7,000.', 'So 2,780 + 4,105 is about 7,000.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Round each number to the nearest hundred, then add. About how much is 3,648 + 1,271?',
        picture: { kind: 'table', head: ['number', 'nearest hundred'], rows: [['3,648', '?'], ['1,271', '?']] }, answer: 4900,
        steps: ['3,648 rounds to 3,600. 1,271 rounds to 1,300.', '3,600 + 1,300 = 4,900.', 'So 3,648 + 1,271 is about 4,900.'] } },
      { why: 'Still "round, then compare"', problem: { text: 'Leo says 7,120 − 2,890 = 4,230. Round each number to the nearest thousand to check. Is his answer about right?',
        picture: { kind: 'eq', text: '7,120 − 2,890 = 4,230' }, answer: { choices: ['yes', 'no'], correct: 0 },
        steps: ['7,120 rounds to 7,000. 2,890 rounds to 3,000.', '7,000 − 3,000 = 4,000.', '4,230 is close to 4,000, so yes.'] } },
      { why: 'A little harder', problem: { text: 'Round each number to the nearest ten thousand, then subtract. About how much is 83,410 − 26,950?',
        picture: { kind: 'table', head: ['number', 'nearest ten thousand'], rows: [['83,410', '?'], ['26,950', '?']] }, answer: 50000,
        steps: ['83,410 rounds to 80,000. 26,950 rounds to 30,000.', '80,000 − 30,000 = 50,000.', 'So 83,410 − 26,950 is about 50,000.'] } },
      { why: 'Same math in a story', problem: { text: 'A theater sold 4,630 tickets on Friday and 3,390 on Saturday. Round each to the nearest thousand. About how many tickets did it sell in all?',
        picture: { kind: 'table', head: ['day', 'tickets', 'nearest thousand'], rows: [['Friday', '4,630', '?'], ['Saturday', '3,390', '?']], rowHead: true }, answer: 8000,
        steps: ['4,630 rounds to 5,000. 3,390 rounds to 3,000.', '5,000 + 3,000 = 8,000.', 'So the theater sold about 8,000 tickets.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t8', title: 'Two-step add and subtract stories', skill: 'Solve two-step word problems with addition and subtraction',
    bigIdea: 'Some stories need two steps. Draw a bar for the story, work out the first step, then use it to answer.',
    screens: [
      { title: 'Books at the library', text: 'A library had 2,450 books. It got 1,300 new books. Then it gave away 820. How many books does it have now?',
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 2450, text: '2,450' }] }] }] },
      { title: 'One step is not enough', text: 'Read it again and count what happens. Books come in, and then books go out. That is two different things, so one step will not get you to the end.',
        beats: [
          { say: 'Read it again and count what happens.' },
          { say: 'Books come in, and then books go out.', pic: 0 },
          { say: 'That is two different things, so one step will not get you to the end.' },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 2450, text: '2,450' }, { w: 1300, text: '+ 1,300', shade: true }] }] }] },
      { title: 'The big idea', text: 'Some stories need two steps. Draw a bar for the story, work out the first step, then use it to answer.',
        beats: [
          { say: 'Some stories need two steps.', pic: 0 },
          { say: 'Draw a bar for the story, work out the first step, then use it to answer.' },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 2450, text: '2,450' }, { w: 1300, text: '1,300', shade: true }] },
          { cells: [{ w: 2930, text: '?' }, { w: 820, text: '820', shade: true }] }] }] },
      { title: 'Step 1: books come in', text: 'Step one, the books coming in. Add them on to what the library already had: 2,450 plus 1,300. That makes the bar longer, and the longer bar is what we work with next.',
        beats: [
          { say: 'Step one, the books coming in.' },
          { say: 'Add them on to what the library already had: 2,450 plus 1,300.', pic: 0 },
          { say: 'That makes the bar longer, and the longer bar is what we work with next.', write: 'step 1 answer → step 2 starting number' },
        ],
        pictures: [{ kind: 'tape', motion: true, rows: [{ cells: [{ w: 2450, text: '2,450' }, { w: 1300, text: '1,300', shade: true }], brace: '3,750' }] }] },
      { title: 'Step 2: books go out', text: 'Step two, the books going out. Same bar, but now 820 of them are given away. The piece that is left over is the part we are asked for.',
        beats: [
          { say: 'Step two, the books going out.' },
          { say: 'Same bar, but now 820 of them are given away.', pic: 0 },
          { say: 'The piece that is left over is the part we are asked for.' },
        ],
        pictures: [{ kind: 'tape', motion: true, rows: [{ cells: [{ w: 3750, text: '3,750' }] },
          { cells: [{ w: 2930, text: '?' }, { w: 820, text: '820 given away', shade: true }] }] }] },
      { title: 'Find the answer', text: 'So take the 820 away. 3,750 minus 820 leaves 2,930. The library has 2,930 books on its shelves now.',
        beats: [
          { say: 'So take the 820 away.' },
          { say: '3,750 minus 820 leaves 2,930.', pic: 0 },
          { say: 'The library has 2,930 books on its shelves now.', pic: 1 },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 3750, text: '3,750' }] },
          { cells: [{ w: 2930, text: '2,930' }, { w: 820, text: '820', shade: true }] }] },
          { kind: 'eq', text: '3,750 − 820 = 2,930' }] },
      { title: 'One thing not to do', text: "Here is the trap in every two-step story. Don't stop when you finish step one. 3,750 was the count before a single book was given away.",
        beats: [
          { say: 'Here is the trap in every two-step story.' },
          { say: "Don't stop when you finish step one.", pic: 0 },
          { say: '3,750 was the count before a single book was given away.' },
        ],
        pictures: [{ kind: 'cards', wrong: 'The library has 3,750 books', right: 'The library has 2,930 books' }] },
    ],
    turn: {
      text: 'A school had 1,640 pencils. It bought 1,200 more. Then it handed out 750. How many pencils are left?',
      picture: { kind: 'tape', rows: [{ cells: [{ w: 1640, text: '1,640' }, { w: 1200, text: '1,200', shade: true }] },
        { cells: [{ w: 2090, text: '?' }, { w: 750, text: '750', shade: true }] }] },
      answer: 2090,
      steps: ['Step 1: 1,640 + 1,200 = 2,840 pencils.', 'Step 2: 2,840 − 750 = 2,090.', 'So 2,090 pencils are left.'],
      prompt: 'Do the first thing that happened. Then use that number for the second step.',
      hint1: 'What happened first? Add the pencils the school bought.',
      hint2: 'After step 1, take away the 750 pencils that were handed out.',
      twin: { text: 'A shop had 2,380 stickers. It got 1,500 more. Then it sold 960. How many stickers are left?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 2380, text: '2,380' }, { w: 1500, text: '1,500', shade: true }] },
          { cells: [{ w: 2920, text: '?' }, { w: 960, text: '960', shade: true }] }] },
        answer: 2920,
        steps: ['Step 1: 2,380 + 1,500 = 3,880 stickers.', 'Step 2: 3,880 − 960 = 2,920.', 'So 2,920 stickers are left.'],
        hint1: 'What happened first? Add the stickers the shop got.',
        hint2: 'After step 1, take away the 960 stickers it sold.' },
    },
    won: { text: 'You did the first step, then used it to finish the story.', sticker: 'A story that needs two steps is a two-step problem. The bar drawing is a tape diagram.' },
    twinWon: { text: 'You added the 1,500 new stickers, then took away 960 to get 2,920.', sticker: 'A story that needs two steps is a two-step problem. The bar drawing is a tape diagram.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A bakery had 1,850 rolls. It baked 1,100 more. Then it sold 930. How many rolls are left?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1850, text: '1,850' }, { w: 1100, text: '1,100', shade: true }] },
          { cells: [{ w: 2020, text: '?' }, { w: 930, text: '930', shade: true }] }] }, answer: 2020,
        steps: ['Step 1: 1,850 + 1,100 = 2,950 rolls.', 'Step 2: 2,950 − 930 = 2,020.', 'So 2,020 rolls are left.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A class read 2,300 pages in March and 1,450 pages in April. Their goal is 5,000 pages. How many more pages do they need to read?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 2300, text: '2,300' }, { w: 1450, text: '1,450' }, { w: 1250, text: '?', shade: true }], brace: '5,000 pages' }] }, answer: 1250,
        steps: ['Step 1: 2,300 + 1,450 = 3,750 pages read.', 'Step 2: 5,000 − 3,750 = 1,250.', 'So they need 1,250 more pages.'] } },
      { why: 'Still "one step at a time"', problem: { text: 'A truck carried 4,200 pounds of sand. It dropped off 1,350 pounds. Then it picked up 900 pounds. How many pounds is it carrying now?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 2850 }, { w: 1350, text: '1,350', shade: true }], brace: '4,200 pounds' },
          { cells: [{ w: 2850 }, { w: 900, text: '900', shade: true }], brace: '?' }] }, answer: 3750,
        steps: ['Step 1: 4,200 − 1,350 = 2,850 pounds.', 'Step 2: 2,850 + 900 = 3,750.', 'So the truck is carrying 3,750 pounds.'] } },
      { why: 'A little harder', problem: { text: 'A town had 12,480 people. Then 2,350 people moved in and 1,875 people moved away. How many people live there now?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 12480, text: '12,480' }, { w: 2350, text: '2,350', shade: true }] },
          { cells: [{ w: 12955, text: '?' }, { w: 1875, text: '1,875', shade: true }] }] }, answer: 12955,
        steps: ['Step 1: 12,480 + 2,350 = 14,830 people.', 'Step 2: 14,830 − 1,875 = 12,955.', 'So 12,955 people live there now.'] } },
      { why: 'Same math in a story', problem: { text: 'Ana wants to save $2,500. She saved $1,275 last year and $860 this year. How much more does she need to save?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1275, text: '$1,275' }, { w: 860, text: '$860' }, { w: 365, text: '?', shade: true }], brace: '$2,500' }] }, answer: 365,
        steps: ['Step 1: $1,275 + $860 = $2,135 saved.', 'Step 2: $2,500 − $2,135 = $365.', 'So Ana needs $365 more.'] } },
    ],
  },
]

attachChalk(G4M1, G4M1_CHALK)
