/**
 * Grade 4 · Module 1 — Place value for addition and subtraction.
 * Written to docs/new-flow/AUTHORING.md.
 * Teaching pictures: t1 place chart (table) · t2 blocks · t3 place chart · t4 numline · t5/t6 columns ·
 * t7 table of rounded numbers · t8 tape.
 */
import type { Lesson, Picture } from '../script'
import { attachChalk } from '../chalk'
import { G4M1_CHALK } from './chalk/g4m1'

const PLACES = ['hundred thousands', 'ten thousands', 'thousands', 'hundreds', 'tens', 'ones']

/** A place-value chart: each number's digits under their places, right-aligned. Commas in `nums` are ignored. */
function chart(nums: string[], o: { labels?: string[]; mark?: [number, number][]; motion?: boolean } = {}): Picture {
  const digits = nums.map(n => n.replace(/,/g, '').split(''))
  const n = Math.max(...digits.map(d => d.length))
  const rows = digits.map((d, i) => [...(o.labels ? [o.labels[i]] : []), ...Array(n - d.length).fill(''), ...d])
  return { kind: 'table', head: [...(o.labels ? [''] : []), ...PLACES.slice(6 - n)], rows, rowHead: !!o.labels, mark: o.mark, motion: o.motion }
}

const LT = ['<', '>', '=']

export const G4M1: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t1', title: 'Read big numbers (to a million)', skill: 'Read and write numbers to 1,000,000',
    bigIdea: 'The comma splits a big number into groups of three. Read the group before the comma and say "thousand", then read the rest.',
    screens: [
      { title: 'How many people?', text: 'A sign says 305,420 people live in a city. How do you read that big number?',
        pictures: [{ kind: 'eq', text: '305,420 people' }] },
      { title: 'Too many digits at once', text: "Six digits in a row. That's a lot to take in at once. If you just read the digits out loud, three, zero, five, four, two, zero, you still have no idea how many people that is.",
        beats: [
          { say: "Six digits in a row. That's a lot to take in at once.", pic: 0 },
          { say: 'If you just read the digits out loud, three, zero, five, four, two, zero, you still have no idea how many people that is.' },
        ],
        pictures: [chart(['305420'])] },
      { title: 'The big idea', text: 'The comma splits a big number into groups of three. Read the group before the comma and say "thousand", then read the rest.',
        beats: [
          { say: 'The comma splits a big number into groups of three.', pic: 0 },
          { say: 'Read the group before the comma and say "thousand", then read the rest.' },
        ],
        pictures: [{ kind: 'eq', text: '305 , 420', lines: ['thousand , the rest'] }] },
      { title: 'Every digit has a place', text: "Let's put every digit under its own place. Now look at the 3. It's sitting in the hundred thousands place. So that 3 is worth 300,000.",
        beats: [
          { say: "Let's put every digit under its own place.", pic: 0 },
          { say: "Now look at the 3. It's sitting in the hundred thousands place." },
          { say: 'So that 3 is worth 300,000.', write: 'the place tells you what a digit is worth' },
        ],
        pictures: [chart(['305420'], { motion: true, mark: [[0, 0]] })] },
      { title: 'Read the group before the comma', text: "Cover up everything after the comma. What's left is 305. Say that part like a normal number, then add the word thousand. Three hundred five thousand.",
        beats: [
          { say: "Cover up everything after the comma. What's left is 305.", pic: 0 },
          { say: 'Say that part like a normal number, then add the word thousand.', write: 'first group + "thousand"' },
          { say: 'Three hundred five thousand.', pic: 1 },
        ],
        pictures: [chart(['305420'], { mark: [[0, 0], [0, 1], [0, 2]] }), { kind: 'eq', text: '305 thousand' }] },
      { title: 'Read the rest', text: 'Now the other side of the comma: 420. You read that part just as it is, with no extra word after it. So the whole number is three hundred five thousand, four hundred twenty.',
        beats: [
          { say: 'Now the other side of the comma: 420.', pic: 0 },
          { say: 'You read that part just as it is, with no extra word after it.' },
          { say: 'So the whole number is three hundred five thousand, four hundred twenty.', pic: 1 },
        ],
        pictures: [chart(['305420'], { mark: [[0, 3], [0, 4], [0, 5]] }), { kind: 'eq', text: '305,420', lines: ['three hundred five thousand,', 'four hundred twenty'] }] },
      { title: 'One thing not to do', text: "Here's the slip to watch for. Don't skip a zero when you write the number down. A zero holds a place open. Without it, the 3 slides over into the wrong place.",
        beats: [
          { say: "Here's the slip to watch for." },
          { say: "Don't skip a zero when you write the number down.", pic: 0 },
          { say: 'A zero holds a place open. Without it, the 3 slides over into the wrong place.' },
        ],
        pictures: [{ kind: 'cards', wrong: '35,420', right: '305,420' }] },
    ],
    turn: {
      text: 'Write this number with digits: two hundred forty-six thousand, one hundred eight.',
      picture: chart(['??????']),
      answer: 246108,
      steps: ['Before the comma: two hundred forty-six is 246.', 'After the comma: one hundred eight needs three digits, 108.', 'So the number is 246,108.'],
      prompt: 'Write the thousands group first. Then write three digits after the comma.',
      hint1: 'Write the group before "thousand" first: two hundred forty-six.',
      hint2: 'After the comma you always need three digits. One hundred eight has a zero in the tens.',
      twin: { text: 'Write this number with digits: seven hundred thirty thousand, fifty-two.',
        picture: chart(['??????']),
        answer: 730052,
        steps: ['Before the comma: seven hundred thirty is 730.', 'After the comma: fifty-two needs three digits, so write 052.', 'So the number is 730,052.'],
        hint1: 'Write the group before "thousand" first: seven hundred thirty.',
        hint2: 'After the comma you need three digits. Fifty-two has no hundreds, so start with a zero.' },
    },
    won: { text: 'You wrote the thousands group, then three digits after the comma.', sticker: 'What a digit is worth depends on its place. That is called place value.' },
    twinWon: { text: 'You wrote 730,052, with a zero holding the hundreds place open.', sticker: 'What a digit is worth depends on its place. That is called place value.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Write this number with digits: four hundred twelve thousand, three hundred fifty.',
        picture: chart(['??????']), answer: 412350,
        steps: ['Before the comma: four hundred twelve is 412.', 'After the comma: three hundred fifty is 350.', 'So the number is 412,350.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Write this number with digits: eighty-five thousand, six hundred seven.',
        picture: chart(['?????']), answer: 85607,
        steps: ['Before the comma: eighty-five is 85.', 'After the comma: six hundred seven needs a zero in the tens, 607.', 'So the number is 85,607.'] } },
      { why: 'Still "every digit has a place"', problem: { text: 'In 562,194, what is the 6 worth?',
        picture: chart(['562194']), answer: 60000,
        steps: ['The 6 is in the ten thousands place.', 'One ten thousand is 10,000, so 6 ten thousands is 60,000.', 'So the 6 is worth 60,000.'] } },
      { why: 'A little harder', problem: { text: 'Write this number with digits: nine hundred six thousand, forty.',
        picture: chart(['??????']), answer: 906040,
        steps: ['Before the comma: nine hundred six is 906.', 'After the comma: forty needs three digits, so write 040.', 'So the number is 906,040.'] } },
      { why: 'Same math in a story', problem: { text: 'A stadium sold four hundred eighty thousand, two hundred fifteen tickets this year. Write that number with digits.',
        picture: chart(['??????']), answer: 480215,
        steps: ['Before the comma: four hundred eighty is 480.', 'After the comma: two hundred fifteen is 215.', 'So the stadium sold 480,215 tickets.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t2', title: 'Each place is 10 times the next', skill: 'A digit in one place is worth 10 times what it is worth in the place to its right',
    bigIdea: 'Ten of one place make one of the next place to the left. So each place is worth 10 times the place to its right.',
    screens: [
      { title: 'Snap the cubes together', text: 'Here are 10 little cubes. Snap them into a row and they make one long stick. What if you keep going?',
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 0, ones: 10 }] },
      { title: 'The digits look the same', text: 'Take a look at 440. Those first two digits are both 4, and they look exactly the same. But they are not worth the same thing at all, and staring at them will not tell you how much bigger one is.',
        beats: [
          { say: 'Take a look at 440. Those first two digits are both 4, and they look exactly the same.', pic: 0 },
          { say: 'But they are not worth the same thing at all, and staring at them will not tell you how much bigger one is.' },
        ],
        pictures: [{ kind: 'eq', text: '440' }] },
      { title: 'The big idea', text: 'Ten of one place make one of the next place to the left. So each place is worth 10 times the place to its right.',
        beats: [
          { say: 'Ten of one place make one of the next place to the left.', pic: 0 },
          { say: 'So each place is worth 10 times the place to its right.' },
        ],
        pictures: [{ kind: 'blocks', hundreds: 1, tens: 1, ones: 1 }] },
      { title: 'Ten ones make a ten', text: 'Watch what happens when I ring 10 of these little ones. Snapped together, they make one ten. So a ten is worth 10 times a one.',
        beats: [
          { say: 'Watch what happens when I ring 10 of these little ones.', pic: 0 },
          { say: 'Snapped together, they make one ten.' },
          { say: 'So a ten is worth 10 times a one.', write: '10 ones → 1 ten' },
        ],
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 0, ones: 10, trade: 'ones', motion: true }] },
      { title: 'Ten tens make a hundred', text: 'Now the same move, one place up. Ring 10 tens and they make one hundred. Every time, 10 of one thing makes 1 of the next thing.',
        beats: [
          { say: 'Now the same move, one place up.', pic: 0 },
          { say: 'Ring 10 tens and they make one hundred.' },
          { say: 'Every time, 10 of one thing makes 1 of the next thing.', write: '10 tens → 1 hundred' },
        ],
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 10, ones: 0, trade: 'tens', motion: true }] },
      { title: 'It keeps going', text: 'And it does not stop there. 10 hundreds make 1 thousand, and every step to the left is worth 10 times as much. So back in 440, the first 4 is worth 400 and the second one is worth 40. That is 10 times bigger.',
        beats: [
          { say: 'And it does not stop there.' },
          { say: '10 hundreds make 1 thousand, and every step to the left is worth 10 times as much.', pic: 0 },
          { say: 'So back in 440, the first 4 is worth 400 and the second one is worth 40. That is 10 times bigger.', pic: 1 },
        ],
        pictures: [{ kind: 'table', head: ['thousands', 'hundreds', 'tens', 'ones'], rows: [['1,000', '100', '10', '1']] },
          { kind: 'eq', text: '40 × 10 = 400' }] },
      { title: 'One thing not to do', text: "Here's the one that trips people up. Don't think a place to the left is just a little bit more. It is 10 times as much, every single time.",
        beats: [
          { say: "Here's the one that trips people up." },
          { say: "Don't think a place to the left is just a little bit more.", pic: 0 },
          { say: 'It is 10 times as much, every single time.' },
        ],
        pictures: [{ kind: 'cards', wrong: '400 is a bit more than 40', right: '400 is 10 times 40' }] },
    ],
    turn: {
      text: 'In 770, the first 7 is worth 700 and the second 7 is worth 70. How many times greater is the first 7?',
      picture: chart(['770']),
      answer: 10,
      steps: ['The first 7 is one place to the left of the second 7.', 'One place to the left is worth 10 times as much: 70 × 10 = 700.', 'So the first 7 is 10 times greater.'],
      prompt: 'Look at how far apart the two 7s are. Each step to the left is worth more.',
      hint1: 'How many 70s make 700?',
      hint2: 'Count by 70s until you reach 700. How many 70s did you count?',
      twin: { text: 'In 3,300, the first 3 is worth 3,000 and the second 3 is worth 300. How many times greater is the first 3?',
        picture: chart(['3300']),
        answer: 10,
        steps: ['The first 3 is one place to the left of the second 3.', 'One place to the left is worth 10 times as much: 300 × 10 = 3,000.', 'So the first 3 is 10 times greater.'],
        hint1: 'Is the first 3 one place or two places to the left of the second 3?',
        hint2: 'How many 300s make 3,000?' },
    },
    won: { text: 'You saw that one step to the left is worth 10 times as much.', sticker: 'Each place is worth 10 times the place to its right. That is how place value works.' },
    twinWon: { text: 'You saw that 3,000 is 10 times 300.', sticker: 'Each place is worth 10 times the place to its right. That is how place value works.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'In 550, the first 5 is worth 500 and the second 5 is worth 50. How many times greater is the first 5?',
        picture: chart(['550']), answer: 10,
        steps: ['The first 5 is one place to the left of the second 5.', '50 × 10 = 500.', 'So the first 5 is 10 times greater.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What number is 10 times 400?',
        picture: { kind: 'blocks', hundreds: 4, tens: 0, ones: 0 }, answer: 4000,
        steps: ['10 hundreds make 1 thousand.', 'So 10 times 4 hundreds is 4 thousands.', 'So 10 times 400 is 4,000.'] } },
      { why: 'Still "10 of one place make the next"', problem: { text: 'How many hundreds make 2,000?',
        picture: chart(['2000']), answer: 20,
        steps: ['1 thousand is 10 hundreds.', '2 thousands is 10 hundreds and 10 more hundreds.', 'So 20 hundreds make 2,000.'] } },
      { why: 'A little harder', problem: { text: 'What number is 10 times 7,000?',
        picture: chart(['7000']), answer: 70000,
        steps: ['10 thousands make 1 ten thousand.', 'So 10 times 7 thousands is 7 ten thousands.', 'So 10 times 7,000 is 70,000.'] } },
      { why: 'Same math in a story', problem: { text: 'A factory puts 100 buttons in a bag. A box holds 10 bags. How many buttons are in a box?',
        picture: { kind: 'table', head: ['bags', 'buttons'], rows: [['1', '100'], ['10', '?']] }, answer: 1000,
        steps: ['A box has 10 bags of 100 buttons.', '10 times 100 moves one place to the left: 1,000.', 'So a box holds 1,000 buttons.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t3', title: 'Compare big numbers', skill: 'Compare multi-digit numbers with <, > and =',
    bigIdea: 'Line the numbers up by place. Start at the biggest place and find the first digits that are different.',
    screens: [
      { title: 'Two cities', text: 'City A has 48,250 people. City B has 46,980 people. Which city has more?',
        pictures: [chart(['48250', '46980'], { labels: ['A', 'B'] })] },
      { title: 'Big digits can trick you', text: 'Careful here. City B has 9 hundreds and 8 tens, and City A only has 2 hundreds and 5 tens. Those are big digits, and if you look at them first you will pick the wrong city.',
        beats: [
          { say: 'Careful here.' },
          { say: 'City B has 9 hundreds and 8 tens, and City A only has 2 hundreds and 5 tens.', pic: 0 },
          { say: 'Those are big digits, and if you look at them first you will pick the wrong city.' },
        ],
        pictures: [chart(['48250', '46980'], { labels: ['A', 'B'], mark: [[1, 3], [1, 4]] })] },
      { title: 'The big idea', text: 'Line the numbers up by place. Start at the biggest place and find the first digits that are different.',
        beats: [
          { say: 'Line the numbers up by place.', pic: 0 },
          { say: 'Start at the biggest place and find the first digits that are different.' },
        ],
        pictures: [chart(['48250', '46980'], { labels: ['A', 'B'] })] },
      { title: 'Line up the places', text: "So let's do it properly. Both numbers go in the chart, every digit under its own place. Now they are lined up, and we can compare them straight down.",
        beats: [
          { say: "So let's do it properly." },
          { say: 'Both numbers go in the chart, every digit under its own place.', pic: 0 },
          { say: 'Now they are lined up, and we can compare them straight down.' },
        ],
        pictures: [chart(['48250', '46980'], { labels: ['A', 'B'], motion: true })] },
      { title: 'Start at the left', text: 'Start all the way at the left, at the biggest place. Ten thousands: both have a 4, so that tells us nothing. Move one place right. Thousands: 8 and 6. There it is, the first place where they are different.',
        beats: [
          { say: 'Start all the way at the left, at the biggest place.', pic: 0 },
          { say: 'Ten thousands: both have a 4, so that tells us nothing. Move one place right.', write: 'same digit → keep going right' },
          { say: 'Thousands: 8 and 6. There it is, the first place where they are different.' },
        ],
        pictures: [chart(['48250', '46980'], { labels: ['A', 'B'], mark: [[0, 2], [1, 2]] })] },
      { title: 'The first difference decides', text: '8 thousands beats 6 thousands, so City A has more. 48,250 is greater than 46,980. And here is the nice part. Every digit after that first difference does not matter at all.',
        beats: [
          { say: '8 thousands beats 6 thousands, so City A has more.' },
          { say: '48,250 is greater than 46,980.', pic: 0 },
          { say: 'And here is the nice part. Every digit after that first difference does not matter at all.' },
        ],
        pictures: [{ kind: 'eq', text: '48,250 > 46,980' }] },
      { title: 'One thing not to do', text: "Don't just grab the first digit you see. Line the places up first. 9,870 has no ten thousands at all, so it is less than 10,200, even though it starts with a 9.",
        beats: [
          { say: "Don't just grab the first digit you see. Line the places up first.", pic: 0 },
          { say: '9,870 has no ten thousands at all, so it is less than 10,200, even though it starts with a 9.', pic: 1 },
        ],
        pictures: [chart(['9870', '10200']), { kind: 'cards', wrong: '9,870 > 10,200', right: '9,870 < 10,200' }] },
    ],
    turn: {
      text: 'Pick the sign that makes it true: 57,340 __ 57,290',
      picture: chart(['57340', '57290']),
      answer: { choices: LT, correct: 1 },
      steps: ['Ten thousands and thousands are the same: 5 and 7.', 'Hundreds: 3 is more than 2.', 'So 57,340 > 57,290.'],
      prompt: 'Line up the places. Find the first place where the digits are different.',
      hint1: 'Start at the biggest place. Move right until two digits are different.',
      hint2: 'The ten thousands and the thousands match. Look at the hundreds.',
      twin: { text: 'Pick the sign that makes it true: 63,105 __ 63,150',
        picture: chart(['63105', '63150']),
        answer: { choices: LT, correct: 0 },
        steps: ['Ten thousands, thousands and hundreds are the same: 6, 3 and 1.', 'Tens: 0 is less than 5.', 'So 63,105 < 63,150.'],
        hint1: 'Line up the places. Which place is the first to be different?',
        hint2: 'The ten thousands, thousands and hundreds match. Look at the tens.' },
    },
    won: { text: 'You lined up the places and let the first different digit decide.', sticker: '> means greater than. < means less than.' },
    twinWon: { text: 'You found the first different place and saw that 63,105 < 63,150.', sticker: '> means greater than. < means less than.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Pick the sign that makes it true: 82,460 __ 84,120',
        picture: chart(['82460', '84120']), answer: { choices: LT, correct: 0 },
        steps: ['Ten thousands are the same: 8.', 'Thousands: 2 is less than 4.', 'So 82,460 < 84,120.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Pick the sign that makes it true: 291,054 __ 219,504',
        picture: chart(['291054', '219504']), answer: { choices: LT, correct: 1 },
        steps: ['Hundred thousands are the same: 2.', 'Ten thousands: 9 is more than 1.', 'So 291,054 > 219,504.'] } },
      { why: 'Still "line up the places"', problem: { text: 'Pick the sign that makes it true: 6,999 __ 10,001',
        picture: chart(['6999', '10001']), answer: { choices: LT, correct: 0 },
        steps: ['Line up the places. 10,001 has a ten thousand. 6,999 has none.', 'The first different place is the ten thousands: 0 is less than 1.', 'So 6,999 < 10,001.'] } },
      { why: 'A little harder', problem: { text: 'Pick the sign that makes it true: 740,915 __ 740,195',
        picture: chart(['740915', '740195']), answer: { choices: LT, correct: 1 },
        steps: ['Hundred thousands, ten thousands and thousands are the same: 7, 4 and 0.', 'Hundreds: 9 is more than 1.', 'So 740,915 > 740,195.'] } },
      { why: 'Same math in a story', problem: { text: 'A zoo had 125,640 visitors in June and 125,604 in July. Pick the sign: June __ July',
        picture: chart(['125640', '125604'], { labels: ['June', 'July'] }), answer: { choices: LT, correct: 1 },
        steps: ['The hundred thousands, ten thousands, thousands and hundreds all match.', 'Tens: 4 is more than 0.', 'So 125,640 > 125,604. June had more.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t4', title: 'Round big numbers', skill: 'Round multi-digit numbers to any place',
    bigIdea: 'Find the two round numbers it sits between. It rounds to the closer one, and exactly halfway rounds up.',
    screens: [
      { title: 'About how many fans?', text: 'A game had 36,420 fans. The news wants to say it with a round number of thousands. What should it say?',
        pictures: [{ kind: 'numline', min: 36000, max: 37000, ticks: 10, labels: 'none', points: [{ at: 36420, label: '36,420' }] }] },
      { title: 'Crossing out digits is not enough', text: 'One idea is to cross out the last digits and call it done. But watch. That would turn 36,720 into 36,000, and 36,720 is much closer to 37,000. So crossing out is not enough.',
        beats: [
          { say: 'One idea is to cross out the last digits and call it done.' },
          { say: 'But watch. That would turn 36,720 into 36,000, and 36,720 is much closer to 37,000.', pic: 0 },
          { say: 'So crossing out is not enough.' },
        ],
        pictures: [{ kind: 'numline', min: 36000, max: 37000, ticks: 10, labels: 'ends', points: [{ at: 36720, label: '36,720' }] }] },
      { title: 'The big idea', text: 'Find the two round numbers it sits between. It rounds to the closer one, and exactly halfway rounds up.',
        beats: [
          { say: 'Find the two round numbers it sits between.', pic: 0 },
          { say: 'It rounds to the closer one, and exactly halfway rounds up.' },
        ],
        pictures: [{ kind: 'numline', min: 36000, max: 37000, ticks: 10, labels: 'ends' }] },
      { title: 'Find the two round thousands', text: 'We want round thousands, so ask which two 36,420 sits between. It is after 36,000 and before 37,000. Put those at the two ends of the line, and drop 36,420 in where it belongs.',
        beats: [
          { say: 'We want round thousands, so ask which two 36,420 sits between.' },
          { say: 'It is after 36,000 and before 37,000.' },
          { say: 'Put those at the two ends of the line, and drop 36,420 in where it belongs.', pic: 0 },
        ],
        pictures: [{ kind: 'numline', min: 36000, max: 37000, ticks: 10, labels: 'ends', points: [{ at: 36420, label: '36,420' }] }] },
      { title: 'Find the middle', text: 'Now find the middle of those two. 36,420 has not reached the middle yet, so it is still closer to the bottom end. That means it goes down.',
        beats: [
          { say: 'Now find the middle of those two.', pic: 0 },
          { say: '36,420 has not reached the middle yet, so it is still closer to the bottom end.', write: 'before the middle → round down' },
          { say: 'That means it goes down.' },
        ],
        pictures: [{ kind: 'numline', min: 36000, max: 37000, ticks: 10, motion: true,
          labels: ['36,000', null, null, null, null, '36,500', null, null, null, null, '37,000'],
          points: [{ at: 36420, label: '36,420' }], jumps: [{ from: 36420, to: 36000 }] }] },
      { title: 'Round to the closer end', text: 'So 36,420 rounds to 36,000. And here is a quick way to check yourself. Look at the digit just right of the thousands. It is a 4, and anything less than 5 rounds down.',
        beats: [
          { say: 'So 36,420 rounds to 36,000.', pic: 0 },
          { say: 'And here is a quick way to check yourself. Look at the digit just right of the thousands.' },
          { say: 'It is a 4, and anything less than 5 rounds down.', write: 'less than 5 → down · 5 or more → up' },
        ],
        pictures: [{ kind: 'eq', text: '36,420 → 36,000' }] },
      { title: 'One thing not to do', text: "Watch out for the exact middle. When a number lands right in the middle, don't round it down. 36,500 is dead center, and the middle always goes up.",
        beats: [
          { say: 'Watch out for the exact middle.' },
          { say: "When a number lands right in the middle, don't round it down.", pic: 0 },
          { say: '36,500 is dead center, and the middle always goes up.' },
        ],
        pictures: [{ kind: 'cards', wrong: '36,500 → 36,000', right: '36,500 → 37,000' }] },
    ],
    turn: {
      text: 'Round 52,780 to the nearest thousand.',
      picture: { kind: 'numline', min: 52000, max: 53000, ticks: 10, labels: 'none', points: [{ at: 52780, label: '52,780' }] },
      answer: 53000,
      steps: ['52,780 is between 52,000 and 53,000.', 'Halfway is 52,500, and 52,780 is past halfway.', 'So 52,780 rounds to 53,000.'],
      prompt: 'Find the two round thousands it is between. Which one is closer?',
      hint1: 'Which two round thousands is 52,780 between?',
      hint2: 'Look at the hundreds digit. Is it 5 or more?',
      twin: { text: 'Round 71,490 to the nearest thousand.',
        picture: { kind: 'numline', min: 71000, max: 72000, ticks: 10, labels: 'none', points: [{ at: 71490, label: '71,490' }] },
        answer: 71000,
        steps: ['71,490 is between 71,000 and 72,000.', 'Halfway is 71,500, and 71,490 has not reached it.', 'So 71,490 rounds to 71,000.'],
        hint1: 'Which two round thousands is 71,490 between?',
        hint2: 'Find the middle between them. Is 71,490 before it or past it?' },
    },
    won: { text: 'You found the two round numbers and picked the closer one.', sticker: 'Rounding means going to the closer round number. The digit to the right decides.' },
    twinWon: { text: 'You saw 71,490 is just before halfway, so it rounds to 71,000.', sticker: 'Rounding means going to the closer round number. The digit to the right decides.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Round 24,630 to the nearest thousand.',
        picture: { kind: 'numline', min: 24000, max: 25000, ticks: 10, labels: 'none', points: [{ at: 24630, label: '24,630' }] }, answer: 25000,
        steps: ['24,630 is between 24,000 and 25,000.', 'The hundreds digit is 6, which is 5 or more.', 'So 24,630 rounds to 25,000.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Round 8,350 to the nearest hundred.',
        picture: { kind: 'numline', min: 8300, max: 8400, ticks: 10, labels: 'none', points: [{ at: 8350, label: '8,350' }] }, answer: 8400,
        steps: ['8,350 is between 8,300 and 8,400.', '8,350 is exactly halfway, and halfway rounds up.', 'So 8,350 rounds to 8,400.'] } },
      { why: 'Still "go to the closer one"', problem: { text: 'Round 147,200 to the nearest ten thousand.',
        picture: { kind: 'numline', min: 140000, max: 150000, ticks: 10, labels: 'none', points: [{ at: 147200, label: '147,200' }] }, answer: 150000,
        steps: ['147,200 is between 140,000 and 150,000.', 'The thousands digit is 7, which is 5 or more.', 'So 147,200 rounds to 150,000.'] } },
      { why: 'A little harder', problem: { text: 'Round 603,950 to the nearest thousand.',
        picture: { kind: 'numline', min: 603000, max: 604000, ticks: 10, labels: 'none', points: [{ at: 603950, label: '603,950' }] }, answer: 604000,
        steps: ['603,950 is between 603,000 and 604,000.', 'The hundreds digit is 9, which is 5 or more.', 'So 603,950 rounds to 604,000.'] } },
      { why: 'Same math in a story', problem: { text: 'A school library has 12,480 books. Round the number of books to the nearest hundred.',
        picture: { kind: 'numline', min: 12400, max: 12500, ticks: 10, labels: 'none', points: [{ at: 12480, label: '12,480' }] }, answer: 12500,
        steps: ['12,480 is between 12,400 and 12,500.', 'The tens digit is 8, which is 5 or more.', 'So about 12,500 books.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t5', title: 'Add big numbers', skill: 'Add multi-digit numbers with the standard algorithm',
    bigIdea: 'Add one place at a time, starting with the ones, and when a place makes 10 or more, carry 1 to the next place left.',
    screens: [
      { title: 'Two days of visitors', text: 'A museum had 2,456 visitors on Saturday and 1,378 on Sunday. How many visitors came in all?',
        pictures: [{ kind: 'columns', rows: ['2456', '1378'], op: '+' }] },
      { title: 'Too big to count on', text: "Could you count up from 2,456, one at a time? You could. But that's 1,378 counts. Is there a faster way? Yes.",
        beats: [
          { say: 'Could you count up from 2,456, one at a time?', pic: 0 },
          { say: "You could. But that's 1,378 counts." },
          { say: 'Is there a faster way? Yes.' },
        ],
        pictures: [{ kind: 'columns', rows: ['2456', '1378'], op: '+' }] },
      { title: 'The big idea', text: 'Add one place at a time, starting with the ones, and when a place makes 10 or more, carry 1 to the next place left.',
        beats: [
          { say: 'Add one place at a time, starting with the ones, and when a place makes 10 or more, carry 1 to the next place left.', pic: 0 },
        ],
        pictures: [{ kind: 'columns', rows: ['2456', '1378'], op: '+', places: ['Th', 'H', 'T', 'O'] }] },
      { title: 'Start with the ones', text: 'Look. Stack 2,456 on 1,378, ones under ones. Start on the right. 6 + 8 = 14. Can 14 fit in one place? No. Write the 4, and carry the 1 to the tens.',
        beats: [
          { say: 'Look. Stack 2,456 on 1,378, ones under ones.' },
          { say: 'Start on the right. 6 + 8 = 14.' },
          { say: 'Can 14 fit in one place? No. Write the 4, and carry the 1 to the tens.', pic: 0 },
        ],
        pictures: [{ kind: 'columns', rows: ['2456', '1378'], op: '+', places: ['Th', 'H', 'T', 'O'], carry: '1 ', answer: '4', motion: true }] },
      { title: 'Now the tens and hundreds', text: 'Now the tens. 1 + 5 + 7 = 13. Write the 3, and carry another 1. Then the hundreds. 1 + 4 + 3 = 8. That fits.',
        beats: [
          { say: 'Now the tens. 1 + 5 + 7 = 13.' },
          { say: 'Write the 3, and carry another 1.', pic: 0 },
          { say: 'Then the hundreds. 1 + 4 + 3 = 8. That fits.' },
        ],
        pictures: [{ kind: 'columns', rows: ['2456', '1378'], op: '+', places: ['Th', 'H', 'T', 'O'], carry: '11 ', answer: '834', motion: true }] },
      { title: 'Finish with the thousands', text: 'Last, the thousands. 2 + 1 = 3. So 2,456 + 1,378 = 3,834 visitors.',
        beats: [
          { say: 'Last, the thousands. 2 + 1 = 3.', pic: 0 },
          { say: 'So 2,456 + 1,378 = 3,834 visitors.' },
        ],
        pictures: [{ kind: 'columns', rows: ['2456', '1378'], op: '+', places: ['Th', 'H', 'T', 'O'], carry: '11 ', answer: '3834' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't FORGET to add what you carried. Leave it out, and you get 3,724. Add it in, and it's 3,834. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't FORGET to add what you carried.", pic: 0 },
          { say: "Leave it out, and you get 3,724. Add it in, and it's 3,834." },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '2,456 + 1,378 = 3,724', right: '2,456 + 1,378 = 3,834' }] },
    ],
    turn: {
      text: 'Add: 3,467 + 2,385',
      picture: { kind: 'columns', rows: ['3467', '2385'], op: '+', answer: null },
      answer: 5852,
      steps: ['Ones: 7 + 5 = 12. Write 2, carry 1.', 'Tens: 6 + 8 + 1 = 15. Write 5, carry 1. Hundreds: 4 + 3 + 1 = 8.', 'Thousands: 3 + 2 = 5. So the total is 5,852.'],
      prompt: 'Start with the ones. Carry when a place makes 10 or more.',
      hint1: 'Start with the ones. If you get 10 or more, carry 1 to the tens.',
      hint2: 'Ones: 7 + 5 = 12. Write 2 and carry 1. Keep going to the left.',
      twin: { text: 'Add: 4,578 + 1,264',
        picture: { kind: 'columns', rows: ['4578', '1264'], op: '+', answer: null },
        answer: 5842,
        steps: ['Ones: 8 + 4 = 12. Write 2, carry 1.', 'Tens: 7 + 6 + 1 = 14. Write 4, carry 1. Hundreds: 5 + 2 + 1 = 8.', 'Thousands: 4 + 1 = 5. So the total is 5,842.'],
        hint1: 'Add the ones first. Carry when you make 10 or more.',
        hint2: 'Ones: 8 + 4 = 12. Write 2 and carry 1 to the tens.' },
    },
    won: { text: 'You added one place at a time and carried when you had to.', sticker: 'Carrying to the next place is called regrouping. This way of adding is the standard algorithm.' },
    twinWon: { text: 'You carried 1 twice and found 4,578 + 1,264 = 5,842.', sticker: 'Carrying to the next place is called regrouping. This way of adding is the standard algorithm.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Add: 2,345 + 1,487',
        picture: { kind: 'columns', rows: ['2345', '1487'], op: '+', answer: null }, answer: 3832,
        steps: ['Ones: 5 + 7 = 12. Write 2, carry 1.', 'Tens: 4 + 8 + 1 = 13. Write 3, carry 1. Hundreds: 3 + 4 + 1 = 8.', 'Thousands: 2 + 1 = 3. So the total is 3,832.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Add: 6,209 + 2,856',
        picture: { kind: 'columns', rows: ['6209', '2856'], op: '+', answer: null }, answer: 9065,
        steps: ['Ones: 9 + 6 = 15. Write 5, carry 1. Tens: 0 + 5 + 1 = 6.', 'Hundreds: 2 + 8 = 10. Write 0, carry 1.', 'Thousands: 6 + 2 + 1 = 9. So the total is 9,065.'] } },
      { why: 'Still "carry to the next place"', problem: { text: 'Add: 45,378 + 27,946',
        picture: { kind: 'columns', rows: ['45378', '27946'], op: '+', answer: null }, answer: 73324,
        steps: ['Ones: 8 + 6 = 14. Write 4, carry 1. Tens: 7 + 4 + 1 = 12. Write 2, carry 1.', 'Hundreds: 3 + 9 + 1 = 13. Write 3, carry 1. Thousands: 5 + 7 + 1 = 13. Write 3, carry 1.', 'Ten thousands: 4 + 2 + 1 = 7. So the total is 73,324.'] } },
      { why: 'A little harder', problem: { text: 'Add: 386,547 + 248,695',
        picture: { kind: 'columns', rows: ['386547', '248695'], op: '+', answer: null }, answer: 635242,
        steps: ['Ones: 7 + 5 = 12, write 2. Tens: 4 + 9 + 1 = 14, write 4. Hundreds: 5 + 6 + 1 = 12, write 2.', 'Thousands: 6 + 8 + 1 = 15, write 5. Ten thousands: 8 + 4 + 1 = 13, write 3. Carry 1 each time.', 'Hundred thousands: 3 + 2 + 1 = 6. So the total is 635,242.'] } },
      { why: 'Same math in a story', problem: { text: 'A farm picked 18,736 apples in September and 24,588 in October. How many apples did it pick in all?',
        picture: { kind: 'columns', rows: ['18736', '24588'], op: '+', answer: null }, answer: 43324,
        steps: ['Ones: 6 + 8 = 14, write 4. Tens: 3 + 8 + 1 = 12, write 2. Carry 1 each time.', 'Hundreds: 7 + 5 + 1 = 13, write 3. Thousands: 8 + 4 + 1 = 13, write 3. Carry 1 each time.', 'Ten thousands: 1 + 2 + 1 = 4. So the farm picked 43,324 apples.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t6', title: 'Subtract big numbers (across zeros)', skill: 'Subtract multi-digit numbers when the top number has zeros',
    bigIdea: 'If the next place is a zero, keep going left to a digit that is not zero, break 1 from there, and each zero on the way becomes 9.',
    screens: [
      { title: 'Money for books', text: 'A school raised $3,005. It spent $1,247 on books. How much money is left?',
        pictures: [{ kind: 'columns', rows: ['3005', '1247'], op: '−' }] },
      { title: 'Nothing next door', text: 'Start with the ones. Can you take 7 from 5? No. So you look next door for a ten. But the tens place is 0, and so is the hundreds.',
        beats: [
          { say: 'Start with the ones. Can you take 7 from 5? No.', pic: 0 },
          { say: 'So you look next door for a ten.' },
          { say: 'But the tens place is 0, and so is the hundreds.' },
        ],
        pictures: [{ kind: 'columns', rows: ['3005', '1247'], op: '−', places: ['Th', 'H', 'T', 'O'] }] },
      { title: 'The big idea', text: 'If the next place is a zero, keep going left to a digit that is not zero, break 1 from there, and each zero on the way becomes 9.',
        beats: [
          { say: 'If the next place is a zero, keep going left to a digit that is not zero, break 1 from there, and each zero on the way becomes 9.', pic: 0 },
        ],
        pictures: [{ kind: 'columns', rows: ['3005', '1247'], op: '−', places: ['Th', 'H', 'T', 'O'] }] },
      { title: 'Go to the first digit that is not zero', text: 'Walk left, past both zeros, to the 3. Break 1 thousand into 10 hundreds. That leaves 2 thousands.',
        beats: [
          { say: 'Walk left, past both zeros, to the 3.' },
          { say: 'Break 1 thousand into 10 hundreds.', pic: 0 },
          { say: 'That leaves 2 thousands.' },
        ],
        pictures: [{ kind: 'columns', rows: ['3005', '1247'], op: '−', places: ['Th', 'H', 'T', 'O'], carry: '2   ', motion: true }] },
      { title: 'Keep breaking', text: 'Now break 1 hundred into 10 tens. 9 hundreds are left. Break 1 ten into 10 ones. 9 tens are left, and the ones are 15.',
        beats: [
          { say: 'Now break 1 hundred into 10 tens.' },
          { say: '9 hundreds are left.', pic: 0 },
          { say: 'Break 1 ten into 10 ones.' },
          { say: '9 tens are left, and the ones are 15.', pic: 1 },
        ],
        pictures: [{ kind: 'columns', rows: ['3005', '1247'], op: '−', places: ['Th', 'H', 'T', 'O'], carry: '299 ', motion: true },
          { kind: 'eq', text: '2 thousands, 9 hundreds, 9 tens, 15 ones' }] },
      { title: 'Now take away', text: 'Now take away. 15 − 7 = 8. 9 − 4 = 5. 9 − 2 = 7. 2 − 1 = 1. So the school has $1,758 left.',
        beats: [
          { say: 'Now take away. 15 − 7 = 8. 9 − 4 = 5.', pic: 0 },
          { say: '9 − 2 = 7. 2 − 1 = 1.' },
          { say: 'So the school has $1,758 left.' },
        ],
        pictures: [{ kind: 'columns', rows: ['3005', '1247'], op: '−', places: ['Th', 'H', 'T', 'O'], carry: '299 ', answer: '1758' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't FLIP it to 7 − 5. That gives 2,242. The 7 is what you take away, so break a bigger place first. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't FLIP it to 7 − 5. That gives 2,242.", pic: 0 },
          { say: 'The 7 is what you take away, so break a bigger place first.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '3,005 − 1,247 = 2,242', right: '3,005 − 1,247 = 1,758' }] },
    ],
    turn: {
      text: 'Subtract: 5,004 − 2,318',
      picture: { kind: 'columns', rows: ['5004', '2318'], op: '−', answer: null },
      answer: 2686,
      steps: ['4 ones is not enough, and the tens and hundreds are 0. Break 1 of the 5 thousands.', 'Now there are 4 thousands, 9 hundreds, 9 tens and 14 ones.', '14 − 8 = 6, 9 − 1 = 8, 9 − 3 = 6, 4 − 2 = 2. So the answer is 2,686.'],
      prompt: 'Go left to the first digit that is not zero. Break it, then take away place by place.',
      hint1: 'You cannot take 8 from 4. Which is the first place to the left that is not 0?',
      hint2: 'Break 1 thousand. The hundreds and tens both become 9, and the ones become 14.',
      twin: { text: 'Subtract: 7,002 − 3,465',
        picture: { kind: 'columns', rows: ['7002', '3465'], op: '−', answer: null },
        answer: 3537,
        steps: ['2 ones is not enough, and the tens and hundreds are 0. Break 1 of the 7 thousands.', 'Now there are 6 thousands, 9 hundreds, 9 tens and 12 ones.', '12 − 5 = 7, 9 − 6 = 3, 9 − 4 = 5, 6 − 3 = 3. So the answer is 3,537.'],
        hint1: 'You cannot take 5 from 2. Look left for the first place that is not 0.',
        hint2: 'Break 1 of the 7 thousands. The zeros become 9s, and the ones become 12.' },
    },
    won: { text: 'You went past the zeros, broke a thousand, and took away place by place.', sticker: 'Breaking a bigger place into smaller ones is called regrouping.' },
    twinWon: { text: 'You broke a thousand to get past the zeros: 7,002 − 3,465 = 3,537.', sticker: 'Breaking a bigger place into smaller ones is called regrouping.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Subtract: 6,003 − 2,475',
        picture: { kind: 'columns', rows: ['6003', '2475'], op: '−', answer: null }, answer: 3528,
        steps: ['Break 1 of the 6 thousands. Now there are 5 thousands, 9 hundreds, 9 tens and 13 ones.', '13 − 5 = 8, 9 − 7 = 2, 9 − 4 = 5, 5 − 2 = 3.', 'So the answer is 3,528.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Subtract: 8,000 − 3,642',
        picture: { kind: 'columns', rows: ['8000', '3642'], op: '−', answer: null }, answer: 4358,
        steps: ['Break 1 of the 8 thousands. Now there are 7 thousands, 9 hundreds, 9 tens and 10 ones.', '10 − 2 = 8, 9 − 4 = 5, 9 − 6 = 3, 7 − 3 = 4.', 'So the answer is 4,358.'] } },
      { why: 'Still "each zero becomes 9"', problem: { text: 'Subtract: 7,000 − 2,381',
        picture: { kind: 'columns', rows: ['7000', '2381'], op: '−', answer: null }, answer: 4619,
        steps: ['Break 1 of the 7 thousands. Now there are 6 thousands, 9 hundreds, 9 tens and 10 ones.', '10 − 1 = 9, 9 − 8 = 1, 9 − 3 = 6, 6 − 2 = 4.', 'So the answer is 4,619.'] } },
      { why: 'A little harder', problem: { text: 'Subtract: 20,005 − 7,318',
        picture: { kind: 'columns', rows: ['20005', '7318'], op: '−', answer: null }, answer: 12687,
        steps: ['The first digit that is not zero is the 2 ten thousands. Break 1 of them.', 'Now there is 1 ten thousand, 9 thousands, 9 hundreds, 9 tens and 15 ones.', '15 − 8 = 7, 9 − 1 = 8, 9 − 3 = 6, 9 − 7 = 2, 1 − 0 = 1. So the answer is 12,687.'] } },
      { why: 'Same math in a story', problem: { text: 'A bakery made 5,000 cookies for a fair. It sold 3,764. How many cookies are left?',
        picture: { kind: 'columns', rows: ['5000', '3764'], op: '−', answer: null }, answer: 1236,
        steps: ['Break 1 of the 5 thousands. Now there are 4 thousands, 9 hundreds, 9 tens and 10 ones.', '10 − 4 = 6, 9 − 6 = 3, 9 − 7 = 2, 4 − 3 = 1.', 'So 1,236 cookies are left.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t7', title: 'Is my answer about right?', skill: 'Estimate a sum or difference by rounding, and check if an answer is reasonable',
    bigIdea: 'Round each number, do the math with the round numbers, and if your answer is far from that, check your work.',
    screens: [
      { title: 'Did Maya add right?', text: 'Maya added 4,875 + 2,960 and got 6,835. How can she tell if that is about right, without doing it all again?',
        pictures: [{ kind: 'eq', text: '4,875 + 2,960 = 6,835' }] },
      { title: 'Doing it again is slow', text: 'She could add it all again. But if she slipped once, she could slip the same way twice. Is there a quicker check? Yes.',
        beats: [
          { say: 'She could add it all again.' },
          { say: 'But if she slipped once, she could slip the same way twice.', pic: 0 },
          { say: 'Is there a quicker check? Yes.' },
        ],
        pictures: [{ kind: 'table', head: ['number', 'nearest thousand'], rows: [['4,875', '?'], ['2,960', '?']] }] },
      { title: 'The big idea', text: 'Round each number, do the math with the round numbers, and if your answer is far from that, check your work.',
        beats: [
          { say: 'Round each number, do the math with the round numbers, and if your answer is far from that, check your work.', pic: 0 },
        ],
        pictures: [{ kind: 'table', head: ['number', 'nearest thousand'], rows: [['4,875', '?'], ['2,960', '?']] }] },
      { title: 'Round each number', text: 'Round each number to the nearest thousand. 4,875 is closer to 5,000. 2,960 is closer to 3,000.',
        beats: [
          { say: 'Round each number to the nearest thousand.' },
          { say: '4,875 is closer to 5,000.', pic: 0 },
          { say: '2,960 is closer to 3,000.' },
        ],
        pictures: [{ kind: 'table', head: ['number', 'nearest thousand'], rows: [['4,875', '5,000'], ['2,960', '3,000']], motion: true }] },
      { title: 'Add the round numbers', text: 'Now add the round numbers. 5,000 + 3,000 = 8,000. You can do that in your head.',
        beats: [
          { say: 'Now add the round numbers.', pic: 0 },
          { say: '5,000 + 3,000 = 8,000. You can do that in your head.', pic: 1 },
        ],
        pictures: [{ kind: 'table', head: ['number', 'nearest thousand'], rows: [['4,875', '5,000'], ['2,960', '3,000']], mark: [[0, 1], [1, 1]] },
          { kind: 'eq', text: '5,000 + 3,000 = 8,000' }] },
      { title: 'Compare', text: "Now compare. Is 6,835 close to 8,000? No. It's more than 1,000 away. So Maya checks her work, and gets 7,835. That is close.",
        beats: [
          { say: 'Now compare. Is 6,835 close to 8,000? No.', pic: 0 },
          { say: "It's more than 1,000 away." },
          { say: 'So Maya checks her work, and gets 7,835. That is close.' },
        ],
        pictures: [{ kind: 'eq', text: '6,835 is far from 8,000', lines: ['7,835 is close to 8,000'] }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't just CHOP 4,875 down to 4,000. It's closer to 5,000. Chop both, and you get 6,000, so Maya's 6,835 looks fine. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't just CHOP 4,875 down to 4,000. It's closer to 5,000.", pic: 0 },
          { say: "Chop both, and you get 6,000, so Maya's 6,835 looks fine." },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '4,875 is about 4,000', right: '4,875 is about 5,000' }] },
    ],
    turn: {
      text: 'Round each number to the nearest thousand, then add. About how much is 3,812 + 5,190?',
      picture: { kind: 'table', head: ['number', 'nearest thousand'], rows: [['3,812', '?'], ['5,190', '?']] },
      answer: 9000,
      steps: ['3,812 rounds to 4,000. 5,190 rounds to 5,000.', '4,000 + 5,000 = 9,000.', 'So 3,812 + 5,190 is about 9,000.'],
      prompt: 'Round each number to the nearest thousand. Then add the round numbers.',
      hint1: 'Round each number to the nearest thousand first.',
      hint2: 'Look at the hundreds digit of each number. 5 or more rounds up.',
      twin: { text: 'Round each number to the nearest thousand, then add. About how much is 6,420 + 1,745?',
        picture: { kind: 'table', head: ['number', 'nearest thousand'], rows: [['6,420', '?'], ['1,745', '?']] },
        answer: 8000,
        steps: ['6,420 rounds to 6,000. 1,745 rounds to 2,000.', '6,000 + 2,000 = 8,000.', 'So 6,420 + 1,745 is about 8,000.'],
        hint1: 'Round 6,420 to the nearest thousand. Then round 1,745.',
        hint2: 'Is each hundreds digit 5 or more? Then add the two round numbers.' },
    },
    won: { text: 'You rounded first, so the math was easy to do in your head.', sticker: 'An answer that is about right is called an estimate.' },
    twinWon: { text: 'You rounded 6,420 and 1,745 and found about 8,000.', sticker: 'An answer that is about right is called an estimate.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Round each number to the nearest thousand, then add. About how much is 2,780 + 4,105?',
        picture: { kind: 'table', head: ['number', 'nearest thousand'], rows: [['2,780', '?'], ['4,105', '?']] }, answer: 7000,
        steps: ['2,780 rounds to 3,000. 4,105 rounds to 4,000.', '3,000 + 4,000 = 7,000.', 'So 2,780 + 4,105 is about 7,000.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Round each number to the nearest hundred, then add. About how much is 3,648 + 1,271?',
        picture: { kind: 'table', head: ['number', 'nearest hundred'], rows: [['3,648', '?'], ['1,271', '?']] }, answer: 4900,
        steps: ['3,648 rounds to 3,600. 1,271 rounds to 1,300.', '3,600 + 1,300 = 4,900.', 'So 3,648 + 1,271 is about 4,900.'] } },
      { why: 'Still "round, then compare"', problem: { text: 'Leo says 7,120 − 2,890 = 4,230. Round each number to the nearest thousand to check. Is his answer about right?',
        picture: { kind: 'eq', text: '7,120 − 2,890 = 4,230' }, answer: { choices: ['yes', 'no'], correct: 0 },
        steps: ['7,120 rounds to 7,000. 2,890 rounds to 3,000.', '7,000 − 3,000 = 4,000.', '4,230 is close to 4,000, so yes.'] } },
      { why: 'A little harder', problem: { text: 'Round each number to the nearest ten thousand, then subtract. About how much is 83,410 − 26,950?',
        picture: { kind: 'table', head: ['number', 'nearest ten thousand'], rows: [['83,410', '?'], ['26,950', '?']] }, answer: 50000,
        steps: ['83,410 rounds to 80,000. 26,950 rounds to 30,000.', '80,000 − 30,000 = 50,000.', 'So 83,410 − 26,950 is about 50,000.'] } },
      { why: 'Same math in a story', problem: { text: 'A theater sold 4,630 tickets on Friday and 3,390 on Saturday. Round each to the nearest thousand. About how many tickets did it sell in all?',
        picture: { kind: 'table', head: ['day', 'tickets', 'nearest thousand'], rows: [['Friday', '4,630', '?'], ['Saturday', '3,390', '?']], rowHead: true }, answer: 8000,
        steps: ['4,630 rounds to 5,000. 3,390 rounds to 3,000.', '5,000 + 3,000 = 8,000.', 'So the theater sold about 8,000 tickets.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m1-t8', title: 'Two-step add and subtract stories', skill: 'Solve two-step word problems with addition and subtraction',
    bigIdea: 'When a story has two steps, do the first step, then use its answer to start the second.',
    screens: [
      { title: 'Books at the library', text: 'A library had 2,450 books. It got 1,300 new books. Then it gave away 820. How many books does it have now?',
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 2450, text: '2,450' }] }] }] },
      { title: 'One step is not enough', text: "Read it again. What happens to the books? Some come in. Then some go out. That's two things, so one step won't get you there.",
        beats: [
          { say: 'Read it again. What happens to the books?' },
          { say: 'Some come in. Then some go out.', pic: 0 },
          { say: "That's two things, so one step won't get you there." },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 2450, text: '2,450' }, { w: 1300, text: '+ 1,300', shade: true }] }] }] },
      { title: 'The big idea', text: 'When a story has two steps, do the first step, then use its answer to start the second.',
        beats: [
          { say: 'When a story has two steps, do the first step, then use its answer to start the second.', pic: 0 },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 2450, text: '2,450' }, { w: 1300, text: '1,300', shade: true }] },
          { cells: [{ w: 2930, text: '?' }, { w: 820, text: '820', shade: true }] }] }] },
      { title: 'Step 1: books come in', text: 'Step 1. The new books come in. 2,450 + 1,300 = 3,750. Now the library has 3,750 books.',
        beats: [
          { say: 'Step 1. The new books come in.' },
          { say: '2,450 + 1,300 = 3,750.', pic: 0 },
          { say: 'Now the library has 3,750 books.' },
        ],
        pictures: [{ kind: 'tape', motion: true, rows: [{ cells: [{ w: 2450, text: '2,450' }, { w: 1300, text: '1,300', shade: true }], brace: '3,750' }] }] },
      { title: 'Step 2: books go out', text: 'Step 2 starts from 3,750, not from 2,450. Then 820 books go out.',
        beats: [
          { say: 'Step 2 starts from 3,750, not from 2,450.' },
          { say: 'Then 820 books go out.', pic: 0 },
        ],
        pictures: [{ kind: 'tape', motion: true, rows: [{ cells: [{ w: 3750, text: '3,750' }] },
          { cells: [{ w: 2930, text: '?' }, { w: 820, text: '820 given away', shade: true }] }] }] },
      { title: 'Find the answer', text: 'So take away 820. 3,750 − 820 = 2,930. The library has 2,930 books now.',
        beats: [
          { say: 'So take away 820.' },
          { say: '3,750 − 820 = 2,930.', pic: 1 },
          { say: 'The library has 2,930 books now.', pic: 0 },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 3750, text: '3,750' }] },
          { cells: [{ w: 2930, text: '2,930' }, { w: 820, text: '820', shade: true }] }] },
          { kind: 'eq', text: '3,750 − 820 = 2,930' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't STOP after step 1. 3,750 is the count before any books go out. Keep going, to 2,930. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't STOP after step 1.", pic: 0 },
          { say: '3,750 is the count before any books go out. Keep going, to 2,930.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: 'The library has 3,750 books', right: 'The library has 2,930 books' }] },
    ],
    turn: {
      text: 'A school had 1,640 pencils. It bought 1,200 more. Then it handed out 750. How many pencils are left?',
      picture: { kind: 'tape', rows: [{ cells: [{ w: 1640, text: '1,640' }, { w: 1200, text: '1,200', shade: true }] },
        { cells: [{ w: 2090, text: '?' }, { w: 750, text: '750', shade: true }] }] },
      answer: 2090,
      steps: ['Step 1: 1,640 + 1,200 = 2,840 pencils.', 'Step 2: 2,840 − 750 = 2,090.', 'So 2,090 pencils are left.'],
      prompt: 'Do the first thing that happened. Then use that number for the second step.',
      hint1: 'What happened first? Add the pencils the school bought.',
      hint2: 'After step 1, take away the 750 pencils that were handed out.',
      twin: { text: 'A shop had 2,380 stickers. It got 1,500 more. Then it sold 960. How many stickers are left?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 2380, text: '2,380' }, { w: 1500, text: '1,500', shade: true }] },
          { cells: [{ w: 2920, text: '?' }, { w: 960, text: '960', shade: true }] }] },
        answer: 2920,
        steps: ['Step 1: 2,380 + 1,500 = 3,880 stickers.', 'Step 2: 3,880 − 960 = 2,920.', 'So 2,920 stickers are left.'],
        hint1: 'What happened first? Add the stickers the shop got.',
        hint2: 'After step 1, take away the 960 stickers it sold.' },
    },
    won: { text: 'You did the first step, then used it to finish the story.', sticker: 'A story that needs two steps is a two-step problem. The bar drawing is a tape diagram.' },
    twinWon: { text: 'You added the 1,500 new stickers, then took away 960 to get 2,920.', sticker: 'A story that needs two steps is a two-step problem. The bar drawing is a tape diagram.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A bakery had 1,850 rolls. It baked 1,100 more. Then it sold 930. How many rolls are left?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1850, text: '1,850' }, { w: 1100, text: '1,100', shade: true }] },
          { cells: [{ w: 2020, text: '?' }, { w: 930, text: '930', shade: true }] }] }, answer: 2020,
        steps: ['Step 1: 1,850 + 1,100 = 2,950 rolls.', 'Step 2: 2,950 − 930 = 2,020.', 'So 2,020 rolls are left.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A class read 2,300 pages in March and 1,450 pages in April. Their goal is 5,000 pages. How many more pages do they need to read?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 2300, text: '2,300' }, { w: 1450, text: '1,450' }, { w: 1250, text: '?', shade: true }], brace: '5,000 pages' }] }, answer: 1250,
        steps: ['Step 1: 2,300 + 1,450 = 3,750 pages read.', 'Step 2: 5,000 − 3,750 = 1,250.', 'So they need 1,250 more pages.'] } },
      { why: 'Still "one step at a time"', problem: { text: 'A truck carried 4,200 pounds of sand. It dropped off 1,350 pounds. Then it picked up 900 pounds. How many pounds is it carrying now?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 2850 }, { w: 1350, text: '1,350', shade: true }], brace: '4,200 pounds' },
          { cells: [{ w: 2850 }, { w: 900, text: '900', shade: true }], brace: '?' }] }, answer: 3750,
        steps: ['Step 1: 4,200 − 1,350 = 2,850 pounds.', 'Step 2: 2,850 + 900 = 3,750.', 'So the truck is carrying 3,750 pounds.'] } },
      { why: 'A little harder', problem: { text: 'A town had 12,480 people. Then 2,350 people moved in and 1,875 people moved away. How many people live there now?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 12480, text: '12,480' }, { w: 2350, text: '2,350', shade: true }] },
          { cells: [{ w: 12955, text: '?' }, { w: 1875, text: '1,875', shade: true }] }] }, answer: 12955,
        steps: ['Step 1: 12,480 + 2,350 = 14,830 people.', 'Step 2: 14,830 − 1,875 = 12,955.', 'So 12,955 people live there now.'] } },
      { why: 'Same math in a story', problem: { text: 'Ana wants to save $2,500. She saved $1,275 last year and $860 this year. How much more does she need to save?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1275, text: '$1,275' }, { w: 860, text: '$860' }, { w: 365, text: '?', shade: true }], brace: '$2,500' }] }, answer: 365,
        steps: ['Step 1: $1,275 + $860 = $2,135 saved.', 'Step 2: $2,500 − $2,135 = $365.', 'So Ana needs $365 more.'] } },
    ],
  },
]

attachChalk(G4M1, G4M1_CHALK)
