/**
 * Grade 4 · Module 2 — Place value for multiplication and division.
 * Written to docs/new-flow/AUTHORING.md.
 */
import type { Lesson, Picture } from '../script'

// ── small picture builders (data only) ─────────────────────────────────────────────────────────
/** "Name has n", then "Other has k copies of n" with a '?' brace. */
const copies = (a: string, n: number, b: string, k: number): Picture => ({
  kind: 'tape',
  rows: [
    { label: a, cells: [{ w: n, text: String(n), shade: true }] },
    { label: b, cells: Array.from({ length: k }, () => ({ w: n, text: String(n) })), brace: '?' },
  ],
})
/** A frog line: 12 equal jumps long, only the ends labelled, the first jump drawn. */
const frog = (step: number): Picture => ({ kind: 'numline', min: 0, max: step * 12, ticks: 12, labels: 'ends', jumps: [{ from: 0, to: step, label: `+${step}` }] })
const HEAD = ['ten thousands', 'thousands', 'hundreds', 'tens', 'ones']
/** A place-value chart with the starting number and an empty row for the answer. */
const chart = (n: number): Picture => {
  const d = String(n).padStart(5, ' ').split('').map(c => c === ' ' ? '' : c)
  return { kind: 'table', head: HEAD, rows: [d, ['', '', '', '', '']] }
}
const PRIME = ['prime', 'composite']

export const G4M2: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m2-t1', title: 'Times as many', skill: 'Solve "times as many" comparisons by multiplying',
    bigIdea: 'Times as many means copies. 4 times as many as 3 is 4 copies of 3, so multiply.',
    screens: [
      { title: 'Who has more?', text: 'Ann has 3 stickers. Sam has 4 times as many as Ann. How many stickers does Sam have?',
        pictures: [{ kind: 'tape', rows: [{ label: 'Ann', cells: [{ w: 3, text: '3', shade: true }] }, { label: 'Sam', cells: [{ w: 12, text: '?' }] }] }] },
      { title: 'Adding does not work', text: "Your first thought might be to add: 3 + 4 = 7. But look again at that 4. It doesn't mean 4 more stickers. It means Sam has 4 copies of what Ann has.",
        beats: [
          { say: 'Your first thought might be to add: 3 + 4 = 7.', pic: 0 },
          { say: "But look again at that 4. It doesn't mean 4 more stickers.", write: 'not 4 more' },
          { say: 'It means Sam has 4 copies of what Ann has.' },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Ann', cells: [{ w: 3, text: '3', shade: true }] }, { label: 'Sam', cells: [{ w: 12, text: '?' }] }] }] },
      { title: 'The big idea', text: 'Times as many means copies. 4 times as many as 3 is 4 copies of 3, so multiply.',
        beats: [
          { say: 'Times as many means copies.', pic: 0 },
          { say: '4 times as many as 3 is 4 copies of 3, so multiply.' },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Ann', cells: [{ w: 3, text: '3', shade: true }] },
          { label: 'Sam', cells: [{ w: 3, text: '3' }, { w: 3, text: '3' }, { w: 3, text: '3' }, { w: 3, text: '3' }] }] }] },
      { title: "Draw Ann's bar", text: "Let's build it. Ann has 3 stickers, so here is one bar for her 3. That one bar is the size we are going to copy.",
        beats: [
          { say: "Let's build it. Ann has 3 stickers, so here is one bar for her 3.", pic: 0 },
          { say: 'That one bar is the size we are going to copy.' },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Ann', cells: [{ w: 3, text: '3', shade: true }] }], motion: true }] },
      { title: 'Make 4 copies', text: "Now Sam. Sam's bar is Ann's bar, 4 times over. So I lay down one copy, two, three, four. 4 copies of 3.",
        beats: [
          { say: "Now Sam. Sam's bar is Ann's bar, 4 times over.", pic: 0 },
          { say: 'So I lay down one copy, two, three, four.' },
          { say: '4 copies of 3.', write: 'times as many → copies' },
        ],
        pictures: [{ kind: 'tape', motion: true, rows: [{ label: 'Ann', cells: [{ w: 3, text: '3', shade: true }] },
          { label: 'Sam', cells: [{ w: 3, text: '3', shade: true }, { w: 3, text: '3', shade: true }, { w: 3, text: '3', shade: true }, { w: 3, text: '3', shade: true }], brace: '4 copies of 3' }] }] },
      { title: 'Multiply', text: 'Now count them up. 4 copies of 3 is exactly what 4 × 3 means. So 4 × 3 = 12. Sam has 12 stickers.',
        beats: [
          { say: 'Now count them up.', pic: 0 },
          { say: '4 copies of 3 is exactly what 4 × 3 means.', write: 'copies → ×' },
          { say: 'So 4 × 3 = 12. Sam has 12 stickers.', pic: 1 },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Ann', cells: [{ w: 3, text: '3', shade: true }] },
          { label: 'Sam', cells: [{ w: 3, text: '3' }, { w: 3, text: '3' }, { w: 3, text: '3' }, { w: 3, text: '3' }], brace: '12' }] },
          { kind: 'eq', text: '4 × 3 = 12' }] },
      { title: 'One thing not to do', text: "Here is the trap almost everybody falls into. Don't add the two numbers. Times as many means make copies, and copies are multiplying.",
        beats: [
          { say: 'Here is the trap almost everybody falls into.' },
          { say: "Don't add the two numbers.", pic: 0 },
          { say: 'Times as many means make copies, and copies are multiplying.' },
        ],
        pictures: [{ kind: 'cards', wrong: '3 + 4 = 7', right: '4 × 3 = 12' }] },
    ],
    turn: {
      text: 'Mia has 5 shells. Leo has 3 times as many shells as Mia. How many shells does Leo have?',
      picture: copies('Mia', 5, 'Leo', 3),
      answer: 15, steps: ["Leo has 3 copies of Mia's 5 shells.", 'Copies means multiply: 3 × 5.', 'So Leo has 15 shells.'],
      prompt: 'Make copies of the smaller amount. Then multiply.',
      hint1: "How many copies of Mia's shells does Leo have?",
      hint2: 'Leo has 3 copies of 5. Count by 5s three times.',
      twin: { text: 'A red ribbon is 2 feet long. A blue ribbon is 6 times as long as the red one. How long is the blue ribbon, in feet?',
        picture: copies('Red', 2, 'Blue', 6),
        answer: 12, steps: ['The blue ribbon is 6 copies of 2 feet.', 'Copies means multiply: 6 × 2.', 'So the blue ribbon is 12 feet long.'],
        hint1: 'How many copies of the red ribbon make the blue one?', hint2: 'The blue ribbon is 6 copies of 2 feet. Count by 2s six times.' },
    },
    won: { text: 'You made copies of the smaller amount, then multiplied.', sticker: 'Times as many is a multiplying comparison. You multiply, you do not add.' },
    twinWon: { text: 'You made 6 copies of 2 feet and found 12 feet.', sticker: 'Times as many is a multiplying comparison. You multiply, you do not add.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Ben has 2 toy cars. Zoe has 4 times as many toy cars as Ben. How many toy cars does Zoe have?',
        picture: copies('Ben', 2, 'Zoe', 4), answer: 8,
        steps: ["Zoe has 4 copies of Ben's 2.", 'Multiply: 4 × 2.', 'So Zoe has 8 toy cars.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A small box holds 6 crayons. A big box holds 3 times as many. How many crayons does the big box hold?',
        picture: copies('Small', 6, 'Big', 3), answer: 18,
        steps: ['The big box holds 3 copies of 6.', 'Multiply: 3 × 6.', 'So the big box holds 18 crayons.'] } },
      { why: 'Still "copies, not adding"', problem: { text: 'Tom read 7 pages. Kim read 5 times as many pages as Tom. How many pages did Kim read?',
        picture: copies('Tom', 7, 'Kim', 5), answer: 35,
        steps: ["Kim read 5 copies of Tom's 7 pages.", 'Multiply: 5 × 7.', 'So Kim read 35 pages.'] } },
      { why: 'A little harder', problem: { text: 'A puppy weighs 9 pounds. A big dog weighs 8 times as much as the puppy. How many pounds does the big dog weigh?',
        picture: copies('Puppy', 9, 'Big dog', 8), answer: 72,
        steps: ["The big dog's weight is 8 copies of 9 pounds.", 'Multiply: 8 × 9.', 'So the big dog weighs 72 pounds.'] } },
      { why: 'Same math in a story', problem: { text: 'Lily picked 6 apples. Her dad picked 7 times as many apples as Lily. How many apples did her dad pick?',
        picture: copies('Lily', 6, 'Dad', 7), answer: 42,
        steps: ["Her dad picked 7 copies of Lily's 6 apples.", 'Multiply: 7 × 6.', 'So her dad picked 42 apples.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m2-t2', title: 'Factor pairs', skill: 'Find every pair of numbers that multiply to make a number',
    bigIdea: 'Two numbers that multiply to make a number are a pair. Each rectangle of tiles shows one pair.',
    screens: [
      { title: 'A pile of tiles', text: 'You have 12 square tiles. How many different rectangles can you make with all of them?',
        pictures: [{ kind: 'grid', rows: 3, cols: 4 }] },
      { title: 'One rectangle is not all of them', text: 'Here is one way. 3 rows of 4, and it uses every single tile. But that is not the only way. The same 12 tiles can be pushed around into other rectangles too.',
        beats: [
          { say: 'Here is one way. 3 rows of 4, and it uses every single tile.', pic: 0 },
          { say: 'But that is not the only way.' },
          { say: 'The same 12 tiles can be pushed around into other rectangles too.' },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 4, top: '4', left: '3' }] },
      { title: 'The big idea', text: 'Two numbers that multiply to make a number are a pair. Each rectangle of tiles shows one pair.',
        beats: [
          { say: 'Two numbers that multiply to make a number are a pair.', pic: 0 },
          { say: 'Each rectangle of tiles shows one pair.' },
        ],
        pictures: [{ kind: 'grid', rows: 2, cols: 6, top: '6', left: '2' }] },
      { title: '1 row, then 2 rows', text: "Let's go through them in order. Start with one long row: that is 1 × 12. Now push them into two rows. Two rows of 6, which is 2 × 6. Both of those use all 12 tiles.",
        beats: [
          { say: "Let's go through them in order. Start with one long row: that is 1 × 12.", pic: 0 },
          { say: 'Now push them into two rows. Two rows of 6, which is 2 × 6.', pic: 1 },
          { say: 'Both of those use all 12 tiles.', write: 'uses every tile = a pair' },
        ],
        pictures: [{ kind: 'grid', rows: 1, cols: 12, top: '12', left: '1' }, { kind: 'grid', rows: 2, cols: 6, top: '6', left: '2', motion: true }] },
      { title: '3 rows', text: 'Now try three rows. Three rows of 4, and again every tile is used. That is 3 × 4 = 12. What about four rows of 3? That is the same rectangle turned on its side, so we do not count it twice.',
        beats: [
          { say: 'Now try three rows. Three rows of 4, and again every tile is used.', pic: 0 },
          { say: 'That is 3 × 4 = 12.', pic: 1 },
          { say: 'What about four rows of 3? That is the same rectangle turned on its side, so we do not count it twice.', write: 'turned = not a new one' },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 4, top: '4', left: '3', motion: true,
          shade: [{ r: 0, c: 0, h: 1, w: 4, tone: 1 }, { r: 1, c: 0, h: 1, w: 4, tone: 2 }, { r: 2, c: 0, h: 1, w: 4, tone: 1 }] },
          { kind: 'eq', text: '3 × 4 = 12' }] },
      { title: '5 rows does not work', text: 'Now rows of 5. Look what happens: the last row comes up short. So 5 is not in a pair for 12. That leaves us 3 pairs: 1 and 12, 2 and 6, 3 and 4.',
        beats: [
          { say: 'Now rows of 5. Look what happens: the last row comes up short.', pic: 0 },
          { say: 'So 5 is not in a pair for 12.', write: 'short row → not a pair' },
          { say: 'That leaves us 3 pairs: 1 and 12, 2 and 6, 3 and 4.', pic: 1 },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 5, hide: [{ r: 2, c: 2, h: 1, w: 3 }], motion: true }, { kind: 'eq', text: '1 × 12', lines: ['2 × 6', '3 × 4'] }] },
      { title: 'One thing not to do', text: "One pair gets forgotten more than any other. Don't leave out the single long row. 1 and the number itself are always a pair.",
        beats: [
          { say: 'One pair gets forgotten more than any other.' },
          { say: "Don't leave out the single long row.", pic: 0 },
          { say: '1 and the number itself are always a pair.' },
        ],
        pictures: [{ kind: 'cards', wrong: '12: 2 × 6, 3 × 4', right: '12: 1 × 12, 2 × 6, 3 × 4' }] },
    ],
    turn: {
      text: 'How many different rectangles can you make with all 10 tiles? A rectangle turned around is not a new one.',
      picture: { kind: 'grid', rows: 1, cols: 10 },
      answer: 2, steps: ['1 row of 10 works: 1 × 10.', '2 rows of 5 works: 2 × 5. Rows of 3 or 4 leave a short row.', 'So there are 2 rectangles.'],
      prompt: 'Start with 1 long row. Then try 2 rows, 3 rows, and more.',
      hint1: 'Start with 1 long row. Then try 2 rows, 3 rows, 4 rows.',
      hint2: 'Only keep the rows that use all 10 tiles with no short row.',
      twin: { text: 'How many different rectangles can you make with all 18 tiles? A rectangle turned around is not a new one.',
        picture: { kind: 'grid', rows: 1, cols: 18 },
        answer: 3, steps: ['1 row of 18 works, and 2 rows of 9 works.', '3 rows of 6 works. Rows of 4 or 5 leave a short row, and 6 rows is 3 rows turned.', 'So there are 3 rectangles.'],
        hint1: 'Try 1 row, then 2 rows, then 3 rows. Does each one use all 18 tiles?', hint2: 'Count by 2s, then by 3s, then by 4s. Which ones land exactly on 18?' },
    },
    won: { text: 'You found every rectangle, starting from one long row.', sticker: 'Numbers that multiply to make a number are its factors. Each rectangle shows a factor pair.' },
    twinWon: { text: 'You found all 3 rectangles you can make with 18 tiles.', sticker: 'Numbers that multiply to make a number are its factors. Each rectangle shows a factor pair.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'How many different rectangles can you make with all 6 tiles? A rectangle turned around is not a new one.',
        picture: { kind: 'grid', rows: 1, cols: 6 }, answer: 2,
        steps: ['1 row of 6 works: 1 × 6.', '2 rows of 3 works: 2 × 3. 3 rows of 2 is the same one turned.', 'So there are 2 rectangles.'] } },
      { why: 'Same idea, new numbers', problem: { text: '20 tiles make a rectangle with 4 rows. How many tiles are in each row?',
        picture: { kind: 'eq', text: '4 × ? = 20' }, answer: 5,
        steps: ['4 rows use all 20 tiles, so think: 4 × what makes 20?', 'Count by 4s: 4, 8, 12, 16, 20. That is 5 jumps.', 'So each row has 5 tiles.'] } },
      { why: 'Still "rectangles make pairs"', problem: { text: 'How many different rectangles can you make with all 16 tiles? A rectangle turned around is not a new one.',
        picture: { kind: 'grid', rows: 1, cols: 16 }, answer: 3,
        steps: ['1 × 16 works, and 2 × 8 works.', '4 × 4 works too, a square. Rows of 3, 5, 6 and 7 leave a short row.', 'So there are 3 rectangles.'] } },
      { why: 'A little harder', problem: { text: 'How many different rectangles can you make with all 24 tiles? A rectangle turned around is not a new one.',
        picture: { kind: 'grid', rows: 2, cols: 12 }, answer: 4,
        steps: ['1 × 24 and 2 × 12 both work.', '3 × 8 and 4 × 6 both work. Rows of 5 leave a short row, and 6 rows is 4 rows turned.', 'So there are 4 rectangles.'] } },
      { why: 'Same math in a story', problem: { text: 'A baker puts 28 muffins on a tray in 4 equal rows. How many muffins are in each row?',
        picture: { kind: 'eq', text: '4 × ? = 28' }, answer: 7,
        steps: ['4 rows hold all 28 muffins, so think: 4 × what makes 28?', 'Count by 4s: 4, 8, 12, 16, 20, 24, 28. That is 7 jumps.', 'So each row has 7 muffins.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m2-t3', title: 'Prime or composite?', skill: 'Tell whether a number has only one rectangle or more',
    bigIdea: 'Some numbers make only one rectangle: one long row. Other numbers make more than one.',
    screens: [
      { title: 'Plant pots', text: 'A gardener has 7 plant pots to set out in a rectangle. How many ways can she do it?',
        pictures: [{ kind: 'grid', rows: 1, cols: 7 }] },
      { title: 'Some numbers will not fit', text: 'She tries two rows. See that gap at the end? One spot is empty, so two rows does not work. Some numbers just will not make a second rectangle, no matter how you push them around.',
        beats: [
          { say: 'She tries two rows. See that gap at the end?', pic: 0 },
          { say: 'One spot is empty, so two rows does not work.' },
          { say: 'Some numbers just will not make a second rectangle, no matter how you push them around.' },
        ],
        pictures: [{ kind: 'grid', rows: 2, cols: 4, hide: [{ r: 1, c: 3, h: 1, w: 1 }] }] },
      { title: 'The big idea', text: 'Some numbers make only one rectangle: one long row. Other numbers make more than one.',
        beats: [
          { say: 'Some numbers make only one rectangle: one long row.', pic: 0 },
          { say: 'Other numbers make more than one.' },
        ],
        pictures: [{ kind: 'grid', rows: 1, cols: 7 }] },
      { title: 'Try 7', text: "Let's test 7 properly. Two rows leaves a short row. Three rows leaves a short row too. So with 7 pots, only the one long row works.",
        beats: [
          { say: "Let's test 7 properly. Two rows leaves a short row.", pic: 0 },
          { say: 'Three rows leaves a short row too.', pic: 1 },
          { say: 'So with 7 pots, only the one long row works.', write: '7 → one rectangle' },
        ],
        pictures: [{ kind: 'grid', rows: 2, cols: 4, hide: [{ r: 1, c: 3, h: 1, w: 1 }], motion: true },
          { kind: 'grid', rows: 3, cols: 3, hide: [{ r: 2, c: 1, h: 1, w: 2 }], motion: true }] },
      { title: 'Try 6', text: "Now let's try 6 instead. 6 pots make one long row of 6. But they also make two rows of 3, with nothing missing. That is more than one rectangle.",
        beats: [
          { say: "Now let's try 6 instead. 6 pots make one long row of 6.", pic: 0 },
          { say: 'But they also make two rows of 3, with nothing missing.', pic: 1 },
          { say: 'That is more than one rectangle.', write: '6 → more than one' },
        ],
        pictures: [{ kind: 'grid', rows: 1, cols: 6 }, { kind: 'grid', rows: 2, cols: 3, motion: true }] },
      { title: 'Two kinds of numbers', text: 'So look at what we found. 7 makes only one rectangle. 6 makes more than one. And every number bigger than 1 is one kind or the other. There is nothing in between.',
        beats: [
          { say: 'So look at what we found. 7 makes only one rectangle.', pic: 0 },
          { say: '6 makes more than one.', pic: 1 },
          { say: 'And every number bigger than 1 is one kind or the other. There is nothing in between.', write: 'one rectangle, or more' },
        ],
        pictures: [{ kind: 'grid', rows: 1, cols: 7, shade: [{ r: 0, c: 0, h: 1, w: 7, tone: 1 }] }, { kind: 'grid', rows: 2, cols: 3, shade: [{ r: 0, c: 0, h: 2, w: 3, tone: 2 }] }] },
      { title: 'One thing not to do', text: "Here is the one that catches people. Don't think every odd number makes only one rectangle. 9 is odd. But look at this: 9 makes three rows of 3. So being odd is not what decides it.",
        beats: [
          { say: "Here is the one that catches people. Don't think every odd number makes only one rectangle." },
          { say: '9 is odd. But look at this: 9 makes three rows of 3.', pic: 0 },
          { say: 'So being odd is not what decides it.', pic: 1 },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 3 }, { kind: 'cards', wrong: '9 is odd, so only one rectangle', right: '9 = 3 × 3, so more than one' }] },
    ],
    turn: {
      text: 'A number that makes only one rectangle is prime. A number that makes more than one is composite. Is 15 prime or composite?',
      picture: { kind: 'grid', rows: 1, cols: 15 },
      answer: { choices: PRIME, correct: 1 },
      steps: ['1 row of 15 works.', '3 rows of 5 also works, because 3 × 5 = 15.', 'More than one rectangle, so 15 is composite.'],
      prompt: 'Try 2 rows, 3 rows and more. Is there a second rectangle?',
      hint1: 'Try 3 rows. Does it use all the tiles, with no short row?',
      hint2: 'Count by 3s: 3, 6, 9 … Do you land exactly on 15?',
      twin: { text: 'A number that makes only one rectangle is prime. A number that makes more than one is composite. Is 11 prime or composite?',
        picture: { kind: 'grid', rows: 1, cols: 11 },
        answer: { choices: PRIME, correct: 0 },
        steps: ['1 row of 11 works.', '2, 3, 4 and 5 rows each leave a short row.', 'Only one rectangle, so 11 is prime.'],
        hint1: 'Try 2 rows, 3 rows, 4 rows. Is there always a short row?', hint2: 'Count by 2s and by 3s. Do you ever land exactly on 11?' },
    },
    won: { text: 'You tried rows until you found a second rectangle.', sticker: 'A number whose only factors are one and itself is prime. A number with more factors is composite.' },
    twinWon: { text: 'You tried the rows and found 11 makes only one rectangle.', sticker: 'A number whose only factors are one and itself is prime. A number with more factors is composite.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Is 5 prime or composite?',
        picture: { kind: 'grid', rows: 1, cols: 5 }, answer: { choices: PRIME, correct: 0 },
        steps: ['1 row of 5 works.', '2, 3 and 4 rows each leave a short row.', 'Only one rectangle, so 5 is prime.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Is 8 prime or composite?',
        picture: { kind: 'grid', rows: 1, cols: 8 }, answer: { choices: PRIME, correct: 1 },
        steps: ['1 row of 8 works.', '2 rows of 4 also works, because 2 × 4 = 8.', 'More than one rectangle, so 8 is composite.'] } },
      { why: 'Still "only one rectangle?"', problem: { text: 'Is 13 prime or composite?',
        picture: { kind: 'grid', rows: 1, cols: 13 }, answer: { choices: PRIME, correct: 0 },
        steps: ['1 row of 13 works.', 'Rows of 2, 3, 4, 5 and 6 each leave a short row.', 'Only one rectangle, so 13 is prime.'] } },
      { why: 'A little harder', problem: { text: 'Is 21 prime or composite?',
        picture: { kind: 'grid', rows: 2, cols: 11, hide: [{ r: 1, c: 10, h: 1, w: 1 }] }, answer: { choices: PRIME, correct: 1 },
        steps: ['2 rows leave a short row, but keep trying.', '3 rows of 7 works, because 3 × 7 = 21.', 'More than one rectangle, so 21 is composite.'] } },
      { why: 'Same math in a story', problem: { text: 'A class sets out 17 chairs. Can they make more than one rectangle, or only one long row? Is 17 prime or composite?',
        picture: { kind: 'grid', rows: 1, cols: 17 }, answer: { choices: PRIME, correct: 0 },
        steps: ['1 long row of 17 works.', 'Rows of 2 up to 8 each leave a short row.', 'Only one rectangle, so 17 is prime.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m2-t4', title: 'Multiples', skill: 'Count by a number and find the numbers it lands on',
    bigIdea: 'Count by a number to jump along the line. Each place you land is that number times 1, 2, 3, and so on.',
    screens: [
      { title: 'A jumping frog', text: 'A frog starts at 0 and jumps 4 spaces each time. Where does it land?',
        pictures: [{ kind: 'numline', min: 0, max: 24, ticks: 6, points: [{ at: 0, label: 'start' }] }] },
      { title: 'Counting by 1s is slow', text: 'You could count every single space: 1, 2, 3, 4, and then start over. That takes forever, and it is easy to lose your place. The frog skips straight over the numbers in between.',
        beats: [
          { say: 'You could count every single space: 1, 2, 3, 4, and then start over.', pic: 0 },
          { say: 'That takes forever, and it is easy to lose your place.' },
          { say: 'The frog skips straight over the numbers in between.' },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 24, ticks: 24, labels: 'ends' }] },
      { title: 'The big idea', text: 'Count by a number to jump along the line. Each place you land is that number times 1, 2, 3, and so on.',
        beats: [
          { say: 'Count by a number to jump along the line.', pic: 0 },
          { say: 'Each place you land is that number times 1, 2, 3, and so on.' },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 24, ticks: 6, jumps: [{ from: 0, to: 4 }, { from: 4, to: 8 }, { from: 8, to: 12 }, { from: 12, to: 16 }, { from: 16, to: 20 }, { from: 20, to: 24 }] }] },
      { title: 'Jump by 4', text: 'Watch the frog. Start at 0 and jump 4. Jump 4 again. And again. It lands on 4, then 8, then 12.',
        beats: [
          { say: 'Watch the frog. Start at 0 and jump 4.', pic: 0 },
          { say: 'Jump 4 again. And again.' },
          { say: 'It lands on 4, then 8, then 12.', write: 'counting by 4 = jumping by 4' },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 24, ticks: 6, motion: true, jumps: [{ from: 0, to: 4, label: '+4' }, { from: 4, to: 8, label: '+4' }, { from: 8, to: 12, label: '+4' }] }] },
      { title: 'Each landing is a times fact', text: 'Now here is the part worth noticing. The 1st landing is 1 × 4. The 2nd landing is 2 × 4. The 3rd is 3 × 4. The landing number is the number you multiply by.',
        beats: [
          { say: 'Now here is the part worth noticing.', pic: 0 },
          { say: 'The 1st landing is 1 × 4. The 2nd landing is 2 × 4. The 3rd is 3 × 4.', pic: 1 },
          { say: 'The landing number is the number you multiply by.', write: 'landing number → × the jump' },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 24, ticks: 6, points: [{ at: 4, label: '1st' }, { at: 8, label: '2nd' }, { at: 12, label: '3rd' }] },
          { kind: 'eq', text: '1 × 4 = 4', lines: ['2 × 4 = 8', '3 × 4 = 12'] }] },
      { title: 'Skip to the 6th', text: 'So to find the 6th landing, you do not have to count every jump. You can go straight to the times fact. 6 × 4 = 24. The frog lands on 24.',
        beats: [
          { say: 'So to find the 6th landing, you do not have to count every jump.', pic: 0 },
          { say: 'You can go straight to the times fact.', write: 'skip the counting, use the fact' },
          { say: '6 × 4 = 24. The frog lands on 24.', pic: 1 },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 24, ticks: 6, motion: true, jumps: [{ from: 0, to: 4 }, { from: 4, to: 8 }, { from: 8, to: 12 }, { from: 12, to: 16 }, { from: 16, to: 20 }, { from: 20, to: 24 }] },
          { kind: 'eq', text: '6 × 4 = 24' }] },
      { title: 'One thing not to do', text: "One thing to watch for. Don't count 0 as a landing. 0 is where the frog starts, before it jumps at all. The 1st landing is 4.",
        beats: [
          { say: 'One thing to watch for.' },
          { say: "Don't count 0 as a landing.", pic: 0 },
          { say: '0 is where the frog starts, before it jumps at all. The 1st landing is 4.' },
        ],
        pictures: [{ kind: 'cards', wrong: '1st: 0 · 2nd: 4 · 3rd: 8', right: '1st: 4 · 2nd: 8 · 3rd: 12' }] },
    ],
    turn: {
      text: 'A frog starts at 0 and jumps 3 spaces each time. Where is its 5th landing?',
      picture: frog(3),
      answer: 15, steps: ['Count by 3s, one landing at a time: 3, 6, 9, 12, 15.', 'That matches the times fact 5 × 3.', 'So the 5th landing is 15.'],
      prompt: 'Count by 3s from 0. Stop at the 5th landing.',
      hint1: 'Count by 3s. Keep track of how many landings you have made.',
      hint2: 'The 5th landing is 5 × 3. Count by 3s: 3, 6, 9 …',
      twin: { text: 'A frog starts at 0 and jumps 6 spaces each time. Where is its 4th landing?',
        picture: frog(6),
        answer: 24, steps: ['Count by 6s, one landing at a time: 6, 12, 18, 24.', 'That matches the times fact 4 × 6.', 'So the 4th landing is 24.'],
        hint1: 'Count by 6s. Stop at the 4th landing.', hint2: 'The 4th landing is 4 × 6. Count by 6s: 6, 12 …' },
    },
    won: { text: 'You counted by 3s and stopped at the 5th landing.', sticker: 'The numbers you land on when you count by 3 are the multiples of 3.' },
    twinWon: { text: 'You counted by 6s and found the 4th landing, 24.', sticker: 'The numbers you land on when you count by 6 are the multiples of 6.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A frog starts at 0 and jumps 5 spaces each time. Where is its 4th landing?',
        picture: frog(5), answer: 20,
        steps: ['Count by 5s: 5, 10, 15, 20.', 'That is 4 × 5.', 'So the 4th landing is 20.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Count by 7s, starting at 0. What is the 6th number you land on?',
        picture: frog(7), answer: 42,
        steps: ['Count by 7s: 7, 14, 21, 28, 35, 42.', 'That is 6 × 7.', 'So the 6th number is 42.'] } },
      { why: 'Still "count by the number"', problem: { text: 'Count by 4s from 0: 4, 8, 12 … Do you land on 36?',
        picture: frog(4), answer: { choices: ['yes', 'no'], correct: 0 },
        steps: ['36 is a landing if some number times 4 makes 36.', '9 × 4 = 36, so the 9th landing is 36.', 'So the answer is yes.'] } },
      { why: 'A little harder', problem: { text: 'Count by 9s, starting at 0. What is the 8th number you land on?',
        picture: frog(9), answer: 72,
        steps: ['The 8th landing is 8 × 9.', 'Count by 9s: 9, 18, 27, 36, 45, 54, 63, 72.', 'So the 8th number is 72.'] } },
      { why: 'Same math in a story', problem: { text: 'A bus comes to the stop every 8 minutes. The first bus comes 8 minutes after the stop opens. How many minutes after opening does the 7th bus come?',
        picture: frog(8), answer: 56,
        steps: ['Each bus comes 8 minutes after the last one, so count by 8s.', 'The 7th bus is 7 × 8: 8, 16, 24, 32, 40, 48, 56.', 'So the 7th bus comes 56 minutes after opening.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m2-t5', title: 'Multiply by 10, 100, 1,000', skill: 'Multiply a whole number by 10, 100 or 1,000 by moving digits',
    bigIdea: 'When you multiply by 10, every digit moves one place to the left. A 0 fills the empty ones place.',
    screens: [
      { title: 'Boxes of pencils', text: 'A store has 34 boxes. Each box holds 10 pencils. How many pencils is that?',
        pictures: [{ kind: 'table', head: HEAD, rows: [['', '', '', '3', '4']] }] },
      { title: 'Counting by 10s takes a while', text: 'You could count by 10s, 34 times over. That is a lot of counting, and it is easy to lose your place. There is a much faster way, and it is all about where the digits sit.',
        beats: [
          { say: 'You could count by 10s, 34 times over.', pic: 0 },
          { say: 'That is a lot of counting, and it is easy to lose your place.' },
          { say: 'There is a much faster way, and it is all about where the digits sit.' },
        ],
        pictures: [{ kind: 'table', head: HEAD, rows: [['', '', '', '3', '4']] }] },
      { title: 'The big idea', text: 'When you multiply by 10, every digit moves one place to the left. A 0 fills the empty ones place.',
        beats: [
          { say: 'When you multiply by 10, every digit moves one place to the left.', pic: 0 },
          { say: 'A 0 fills the empty ones place.' },
        ],
        pictures: [{ kind: 'table', head: HEAD, rows: [['', '', '', '3', '4'], ['', '', '3', '4', '0']] }] },
      { title: 'Times 10', text: 'Watch each digit move one place to the left. The 3 tens become 3 hundreds, and the 4 ones become 4 tens. Now nothing is left in the ones place, so a 0 goes there to hold it.',
        beats: [
          { say: 'Watch each digit move one place to the left.', pic: 0 },
          { say: 'The 3 tens become 3 hundreds, and the 4 ones become 4 tens.', write: 'every digit slides one place left' },
          { say: 'Now nothing is left in the ones place, so a 0 goes there to hold it.', pic: 1 },
        ],
        pictures: [{ kind: 'table', head: HEAD, motion: true, rows: [['', '', '', '3', '4'], ['', '', '3', '4', '0']], mark: [[1, 2], [1, 3]] },
          { kind: 'eq', text: '34 × 10 = 340' }] },
      { title: 'Times 100', text: 'Times 100 is just times 10, and then times 10 again. Two moves instead of one, so every digit slides two places to the left. And two 0s hold the empty places behind it.',
        beats: [
          { say: 'Times 100 is just times 10, and then times 10 again.' },
          { say: 'Two moves instead of one, so every digit slides two places to the left.', pic: 0 },
          { say: 'And two 0s hold the empty places behind it.', pic: 1 },
        ],
        pictures: [{ kind: 'table', head: HEAD, motion: true, rows: [['', '', '', '3', '4'], ['', '3', '4', '0', '0']], mark: [[1, 1], [1, 2]] },
          { kind: 'eq', text: '34 × 100 = 3,400' }] },
      { title: 'Times 1,000', text: 'And times 1,000? Three moves. Every digit slides three places to the left, and three 0s hold the empty places behind it.',
        beats: [
          { say: 'And times 1,000? Three moves.', write: 'one move for each 0' },
          { say: 'Every digit slides three places to the left,', pic: 0 },
          { say: 'and three 0s hold the empty places behind it.', pic: 1 },
        ],
        pictures: [{ kind: 'table', head: HEAD, rows: [['', '', '', '3', '4'], ['3', '4', '0', '0', '0']], mark: [[1, 0], [1, 1]] },
          { kind: 'eq', text: '34 × 1,000 = 34,000' }] },
      { title: 'One thing not to do', text: "Here is the slip to avoid. Don't just stick one 0 on the end every time. Times 100 moves two places, so it needs two 0s.",
        beats: [
          { say: 'Here is the slip to avoid.' },
          { say: "Don't just stick one 0 on the end every time.", pic: 0 },
          { say: 'Times 100 moves two places, so it needs two 0s.' },
        ],
        pictures: [{ kind: 'cards', wrong: '34 × 100 = 340', right: '34 × 100 = 3,400' }] },
    ],
    turn: {
      text: 'What is 52 × 100?',
      picture: chart(52),
      answer: 5200, steps: ['Times 100 moves every digit two places to the left.', '5 tens become 5 thousands, and 2 ones become 2 hundreds. 0s fill the tens and ones.', 'So 52 × 100 = 5,200.'],
      prompt: 'How many places does each digit move? Fill the empty places with 0.',
      hint1: 'How many places does times 100 move each digit?',
      hint2: 'Move the 5 and the 2 two places to the left. Fill the empty places with 0.',
      twin: { text: 'What is 7 × 1,000?',
        picture: chart(7),
        answer: 7000, steps: ['Times 1,000 moves the digit three places to the left.', '7 ones become 7 thousands. 0s fill the hundreds, tens and ones.', 'So 7 × 1,000 = 7,000.'],
        hint1: 'How many places does times 1,000 move the digit?', hint2: 'Move the 7 three places to the left. Fill the empty places with 0.' },
    },
    won: { text: 'You moved each digit two places to the left.', sticker: 'Each place is 10 times the place to its right. That is why the digits move left.' },
    twinWon: { text: 'You moved the 7 three places to the left and got 7,000.', sticker: 'Each place is 10 times the place to its right. That is why the digits move left.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What is 46 × 10?',
        picture: chart(46), answer: 460,
        steps: ['Times 10 moves every digit one place to the left.', '4 tens become 4 hundreds, 6 ones become 6 tens, and a 0 fills the ones.', 'So 46 × 10 = 460.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is 18 × 100?',
        picture: chart(18), answer: 1800,
        steps: ['Times 100 moves every digit two places to the left.', '1 ten becomes 1 thousand, 8 ones become 8 hundreds, and 0s fill the tens and ones.', 'So 18 × 100 = 1,800.'] } },
      { why: 'Still "digits move left"', problem: { text: 'What is 9 × 1,000?',
        picture: chart(9), answer: 9000,
        steps: ['Times 1,000 moves the digit three places to the left.', '9 ones become 9 thousands, and 0s fill the other three places.', 'So 9 × 1,000 = 9,000.'] } },
      { why: 'A little harder', problem: { text: 'What is 250 × 100?',
        picture: chart(250), answer: 25000,
        steps: ['Times 100 moves every digit two places to the left.', '2 hundreds become 2 ten thousands, 5 tens become 5 thousands, 0 ones become 0 hundreds, and 0s fill the tens and ones.', 'So 250 × 100 = 25,000.'] } },
      { why: 'Same math in a story', problem: { text: 'A farm packs 63 crates. Each crate holds 1,000 seeds. How many seeds is that?',
        picture: chart(63), answer: 63000,
        steps: ['63 crates of 1,000 is 63 × 1,000.', 'Each digit moves three places to the left, and 0s fill the hundreds, tens and ones.', 'So that is 63,000 seeds.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m2-t6', title: 'Multiply tens by ones (4 × 30)', skill: 'Multiply a multiple of ten by a one-digit number',
    bigIdea: '30 is 3 tens. So 4 × 30 is 4 × 3 tens, which is 12 tens, or 120.',
    screens: [
      { title: 'Packs of cards', text: 'A game has 4 packs. Each pack has 30 cards. How many cards are there in all?',
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 3, ones: 0 }] },
      { title: '4 × 3 is not enough', text: 'You already know that 4 × 3 = 12. But careful. Each pack has 30 cards, not 3. So the answer has to be much bigger than 12.',
        beats: [
          { say: 'You already know that 4 × 3 = 12.', pic: 0 },
          { say: 'But careful. Each pack has 30 cards, not 3.', write: '30, not 3' },
          { say: 'So the answer has to be much bigger than 12.' },
        ],
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 3, ones: 0 }] },
      { title: 'The big idea', text: '30 is 3 tens. So 4 × 30 is 4 × 3 tens, which is 12 tens, or 120.',
        beats: [
          { say: '30 is 3 tens.', pic: 0 },
          { say: 'So 4 × 30 is 4 × 3 tens, which is 12 tens, or 120.' },
        ],
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 12, ones: 0 }] },
      { title: 'See the tens', text: "Let's count in tens instead. One pack of 30 is 3 ten rods. So 4 packs is 4 groups of 3 tens.",
        beats: [
          { say: "Let's count in tens instead.", pic: 0 },
          { say: 'One pack of 30 is 3 ten rods.', pic: 1 },
          { say: 'So 4 packs is 4 groups of 3 tens.', write: 'count the tens, not the ones' },
        ],
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 3, ones: 0, motion: true }, { kind: 'eq', text: '30 = 3 tens' }] },
      { title: 'Put the groups together', text: 'Now push all 4 groups together. 4 groups of 3 tens make 12 tens. It is the same 4 × 3 you already know, only we are counting tens.',
        beats: [
          { say: 'Now push all 4 groups together.', pic: 0 },
          { say: '4 groups of 3 tens make 12 tens.', pic: 1 },
          { say: 'It is the same 4 × 3 you already know, only we are counting tens.' },
        ],
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 12, ones: 0, motion: true }, { kind: 'eq', text: '4 × 3 tens = 12 tens' }] },
      { title: 'Trade ten tens', text: 'Now, 10 tens make 1 hundred, so we can trade. 12 tens becomes 1 hundred and 2 tens. Write that as a number and it is 120.',
        beats: [
          { say: 'Now, 10 tens make 1 hundred, so we can trade.', pic: 0 },
          { say: '12 tens becomes 1 hundred and 2 tens.', pic: 1 },
          { say: 'Write that as a number and it is 120.', pic: 2 },
        ],
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 12, ones: 0, trade: 'tens' }, { kind: 'blocks', hundreds: 1, tens: 2, ones: 0, motion: true },
          { kind: 'eq', text: '4 × 30 = 120' }] },
      { title: 'One thing not to do', text: "Here is the mistake to watch for. Don't drop the tens along the way. 4 × 3 is 12, but 4 × 30 is 12 tens, and that is 120.",
        beats: [
          { say: 'Here is the mistake to watch for.' },
          { say: "Don't drop the tens along the way.", pic: 0 },
          { say: '4 × 3 is 12, but 4 × 30 is 12 tens, and that is 120.' },
        ],
        pictures: [{ kind: 'cards', wrong: '4 × 30 = 12', right: '4 × 30 = 120' }] },
    ],
    turn: {
      text: 'A game has 5 packs. Each pack has 30 cards. How many cards are there in all?',
      picture: { kind: 'blocks', hundreds: 0, tens: 3, ones: 0 },
      answer: 150, steps: ['Each pack of 30 is 3 tens.', '5 × 3 tens = 15 tens.', '15 tens is 1 hundred and 5 tens, so 5 × 30 = 150.'],
      prompt: 'Think of 30 as tens. Multiply the tens.',
      hint1: 'How many tens are in 30?',
      hint2: 'Find 5 × 3 tens. How many tens is that?',
      twin: { text: 'What is 6 × 40?',
        picture: { kind: 'blocks', hundreds: 0, tens: 4, ones: 0 },
        answer: 240, steps: ['40 is 4 tens.', '6 × 4 tens = 24 tens.', '24 tens is 2 hundreds and 4 tens, so 6 × 40 = 240.'],
        hint1: 'How many tens are in 40?', hint2: 'Find 6 × 4 tens. Then write that many tens as a number.' },
    },
    won: { text: 'You multiplied the tens, then wrote them as a number.', sticker: 'Numbers like 30 and 40 are multiples of 10. Multiply the tens, then say how many tens.' },
    twinWon: { text: 'You turned 40 into 4 tens and found 240.', sticker: 'Think in tens: 40 is 4 tens, so multiply the 4, then write the tens.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A game has 2 packs. Each pack has 40 cards. How many cards are there in all?',
        picture: { kind: 'blocks', hundreds: 0, tens: 4, ones: 0 }, answer: 80,
        steps: ['Each pack of 40 is 4 tens.', '2 × 4 tens = 8 tens.', '8 tens is 80, so there are 80 cards.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is 3 × 50?',
        picture: { kind: 'blocks', hundreds: 0, tens: 5, ones: 0 }, answer: 150,
        steps: ['50 is 5 tens.', '3 × 5 tens = 15 tens.', '15 tens is 150, so 3 × 50 = 150.'] } },
      { why: 'Still "count the tens"', problem: { text: 'What is 7 × 20?',
        picture: { kind: 'blocks', hundreds: 0, tens: 2, ones: 0 }, answer: 140,
        steps: ['20 is 2 tens.', '7 × 2 tens = 14 tens.', '14 tens is 140, so 7 × 20 = 140.'] } },
      { why: 'A little harder', problem: { text: 'What is 8 × 60?',
        picture: { kind: 'blocks', hundreds: 0, tens: 6, ones: 0 }, answer: 480,
        steps: ['60 is 6 tens.', '8 × 6 tens = 48 tens.', '48 tens is 4 hundreds and 8 tens, so 8 × 60 = 480.'] } },
      { why: 'Same math in a story', problem: { text: 'A school orders 6 boxes of pencils. Each box holds 70 pencils. How many pencils does the school get?',
        picture: { kind: 'blocks', hundreds: 0, tens: 7, ones: 0 }, answer: 420,
        steps: ['Each box of 70 is 7 tens.', '6 × 7 tens = 42 tens.', '42 tens is 420, so the school gets 420 pencils.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m2-t7', title: 'Divide tens (80 ÷ 4)', skill: 'Divide a multiple of ten by a one-digit number by sharing tens',
    bigIdea: '80 is 8 tens. Share the tens: 8 tens ÷ 4 = 2 tens, which is 20.',
    screens: [
      { title: 'Sheets of stickers', text: '80 stickers come on sheets of 10. Share them fairly among 4 friends. How many stickers does each friend get?',
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 8, ones: 0 }] },
      { title: 'One at a time is slow', text: 'You could hand them out one sticker at a time, but you would be there all day. And look, they already come in tens. That is going to make this much easier.',
        beats: [
          { say: 'You could hand them out one sticker at a time, but you would be there all day.', pic: 0 },
          { say: 'And look, they already come in tens.' },
          { say: 'That is going to make this much easier.' },
        ],
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 8, ones: 0 }] },
      { title: 'The big idea', text: '80 is 8 tens. Share the tens: 8 tens ÷ 4 = 2 tens, which is 20.',
        beats: [
          { say: '80 is 8 tens.', pic: 0 },
          { say: 'Share the tens: 8 tens ÷ 4 = 2 tens, which is 20.' },
        ],
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 8, ones: 0 }] },
      { title: 'Count the tens', text: 'First, count the sheets. 80 stickers is 8 sheets of 10, so that is 8 tens. From here on we are sharing sheets, not single stickers.',
        beats: [
          { say: 'First, count the sheets.', pic: 0 },
          { say: '80 stickers is 8 sheets of 10, so that is 8 tens.', pic: 1 },
          { say: 'From here on we are sharing sheets, not single stickers.', write: 'share the tens' },
        ],
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 8, ones: 0, motion: true }, { kind: 'eq', text: '80 = 8 tens' }] },
      { title: 'Share the tens', text: 'Give one sheet to each friend. Then go around again. Every friend ends up with 2 sheets, and 2 sheets is 2 tens.',
        beats: [
          { say: 'Give one sheet to each friend. Then go around again.', pic: 0 },
          { say: 'Every friend ends up with 2 sheets,' },
          { say: 'and 2 sheets is 2 tens.', pic: 1 },
        ],
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 2, ones: 0, motion: true }, { kind: 'eq', text: '8 tens ÷ 4 = 2 tens' }] },
      { title: 'Write the tens', text: 'Last step. Turn the tens back into a plain number. 2 tens is 20. So 80 ÷ 4 = 20, and each friend gets 20 stickers.',
        beats: [
          { say: 'Last step. Turn the tens back into a plain number.', pic: 0 },
          { say: '2 tens is 20.', write: 'tens → a number at the end' },
          { say: 'So 80 ÷ 4 = 20, and each friend gets 20 stickers.', pic: 1 },
        ],
        pictures: [{ kind: 'blocks', hundreds: 0, tens: 2, ones: 0 }, { kind: 'eq', text: '80 ÷ 4 = 20' }] },
      { title: 'One thing not to do', text: "And the slip to avoid. Don't drop the tens at the end. 8 ÷ 4 is 2, but 8 tens ÷ 4 is 2 tens, and that is 20.",
        beats: [
          { say: 'And the slip to avoid.' },
          { say: "Don't drop the tens at the end.", pic: 0 },
          { say: '8 ÷ 4 is 2, but 8 tens ÷ 4 is 2 tens, and that is 20.' },
        ],
        pictures: [{ kind: 'cards', wrong: '80 ÷ 4 = 2', right: '80 ÷ 4 = 20' }] },
    ],
    turn: {
      text: '90 stickers come on sheets of 10. Share them fairly among 3 friends. How many stickers does each friend get?',
      picture: { kind: 'blocks', hundreds: 0, tens: 9, ones: 0 },
      answer: 30, steps: ['90 is 9 tens.', '9 tens ÷ 3 = 3 tens.', '3 tens is 30, so each friend gets 30 stickers.'],
      prompt: 'Count the tens. Share the tens.',
      hint1: 'How many tens are in 90?',
      hint2: 'Share 9 tens among 3 friends. How many tens does each friend get?',
      twin: { text: 'What is 160 ÷ 4?',
        picture: { kind: 'blocks', hundreds: 0, tens: 16, ones: 0 },
        answer: 40, steps: ['160 is 16 tens.', '16 tens ÷ 4 = 4 tens.', '4 tens is 40, so 160 ÷ 4 = 40.'],
        hint1: 'How many tens are in 160?', hint2: 'Share 16 tens into 4 equal groups. How many tens are in each group?' },
    },
    won: { text: 'You shared the tens, then wrote the tens as a number.', sticker: 'The answer to a division is called the quotient.' },
    twinWon: { text: 'You thought of 160 as tens, shared them, and got 40.', sticker: 'The answer to a division is called the quotient.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '60 stickers come on sheets of 10. Share them fairly between 2 friends. How many stickers does each friend get?',
        picture: { kind: 'blocks', hundreds: 0, tens: 6, ones: 0 }, answer: 30,
        steps: ['60 is 6 tens.', '6 tens ÷ 2 = 3 tens.', '3 tens is 30, so each friend gets 30 stickers.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is 50 ÷ 5?',
        picture: { kind: 'blocks', hundreds: 0, tens: 5, ones: 0 }, answer: 10,
        steps: ['50 is 5 tens.', '5 tens ÷ 5 = 1 ten.', '1 ten is 10, so 50 ÷ 5 = 10.'] } },
      { why: 'Still "share the tens"', problem: { text: 'What is 120 ÷ 3?',
        picture: { kind: 'blocks', hundreds: 0, tens: 12, ones: 0 }, answer: 40,
        steps: ['120 is 12 tens.', '12 tens ÷ 3 = 4 tens.', '4 tens is 40, so 120 ÷ 3 = 40.'] } },
      { why: 'A little harder', problem: { text: 'What is 200 ÷ 5?',
        picture: { kind: 'blocks', hundreds: 0, tens: 20, ones: 0 }, answer: 40,
        steps: ['200 is 20 tens.', '20 tens ÷ 5 = 4 tens.', '4 tens is 40, so 200 ÷ 5 = 40.'] } },
      { why: 'Same math in a story', problem: { text: 'A baker has 150 cookies. She packs them equally into 5 boxes. How many cookies go in each box?',
        picture: { kind: 'blocks', hundreds: 0, tens: 15, ones: 0 }, answer: 30,
        steps: ['150 is 15 tens.', '15 tens ÷ 5 = 3 tens.', '3 tens is 30, so each box gets 30 cookies.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m2-t8', title: 'Division with a remainder', skill: 'Divide into full groups and find how many are left over',
    bigIdea: 'When things do not share out evenly, make as many full groups as you can. What is left is too few for another group.',
    screens: [
      { title: 'Stickers on pages', text: 'You have 14 stickers. Each page of your book holds 4. How many pages can you fill all the way?',
        pictures: [{ kind: 'grid', rows: 1, cols: 14 }] },
      { title: 'It does not come out even', text: "Let's count by 4s and see: 4, 8, 12, 16. Did you catch that? The count jumped straight past 14. So these pages are not going to come out even.",
        beats: [
          { say: "Let's count by 4s and see: 4, 8, 12, 16.", pic: 0 },
          { say: 'Did you catch that? The count jumped straight past 14.' },
          { say: 'So these pages are not going to come out even.' },
        ],
        pictures: [{ kind: 'grid', rows: 1, cols: 14 }] },
      { title: 'The big idea', text: 'When things do not share out evenly, make as many full groups as you can. What is left is too few for another group.',
        beats: [
          { say: 'When things do not share out evenly, make as many full groups as you can.', pic: 0 },
          { say: 'What is left is too few for another group.' },
        ],
        pictures: [{ kind: 'grid', rows: 1, cols: 14, shade: [{ r: 0, c: 0, h: 1, w: 4, tone: 1 }, { r: 0, c: 4, h: 1, w: 4, tone: 2 }, { r: 0, c: 8, h: 1, w: 4, tone: 1 }] }] },
      { title: 'Fill one page', text: "So let's fill what we can. Put 4 stickers on the first page. That page is full.",
        beats: [
          { say: "So let's fill what we can.", pic: 0 },
          { say: 'Put 4 stickers on the first page. That page is full.' },
        ],
        pictures: [{ kind: 'grid', rows: 1, cols: 14, motion: true, shade: [{ r: 0, c: 0, h: 1, w: 4, tone: 1 }] }] },
      { title: 'Keep filling pages', text: 'Now keep going until you cannot fill another one. 4, then 8, then 12. That is 3 full pages.',
        beats: [
          { say: 'Now keep going until you cannot fill another one.', pic: 0 },
          { say: '4, then 8, then 12.' },
          { say: 'That is 3 full pages.', write: 'full groups only' },
        ],
        pictures: [{ kind: 'grid', rows: 1, cols: 14, motion: true, shade: [{ r: 0, c: 0, h: 1, w: 4, tone: 1 }, { r: 0, c: 4, h: 1, w: 4, tone: 2 }, { r: 0, c: 8, h: 1, w: 4, tone: 1 }] }] },
      { title: 'What is left', text: 'Those 3 pages used 12 stickers, so 2 are still in your hand. And 2 is too few to fill another page, so they stay left over. That is what 14 ÷ 4 gives us: 3 full groups, with 2 left over.',
        beats: [
          { say: 'Those 3 pages used 12 stickers, so 2 are still in your hand.', pic: 0 },
          { say: 'And 2 is too few to fill another page, so they stay left over.', write: 'left over = too few for a group' },
          { say: 'That is what 14 ÷ 4 gives us: 3 full groups, with 2 left over.', pic: 1 },
        ],
        pictures: [{ kind: 'grid', rows: 1, cols: 14, shade: [{ r: 0, c: 0, h: 1, w: 4, tone: 1 }, { r: 0, c: 4, h: 1, w: 4, tone: 2 }, { r: 0, c: 8, h: 1, w: 4, tone: 1 }] },
          { kind: 'eq', text: '14 ÷ 4 = 3 groups, 2 left over' }] },
      { title: 'One thing not to do', text: "One last thing. Don't stop too soon. If 4 or more are still left, you can fill another page.",
        beats: [
          { say: 'One last thing.' },
          { say: "Don't stop too soon.", pic: 0 },
          { say: 'If 4 or more are still left, you can fill another page.' },
        ],
        pictures: [{ kind: 'cards', wrong: '14 ÷ 4 = 2 groups, 6 left over', right: '14 ÷ 4 = 3 groups, 2 left over' }] },
    ],
    turn: {
      text: 'You have 23 stickers. Each page holds 4. How many pages can you fill all the way?',
      picture: { kind: 'rings', total: 23, size: 4, obj: 'sticker', state: 'start' },
      answer: 5, steps: ['Count by 4s: 4, 8, 12, 16, 20. 24 would be too many.', '20 stickers fill the pages, and 3 are left over.', 'So you can fill 5 full pages.'],
      prompt: 'Make groups of 4 until you cannot make another.',
      hint1: 'Count by 4s. Stop before you go past 23.',
      hint2: 'Which number in the 4s count is closest to 23 without going over? How many 4s is that?',
      twin: { text: 'You have 17 stickers. Each page holds 5. After you fill every page you can, how many stickers are left over?',
        picture: { kind: 'rings', total: 17, size: 5, obj: 'sticker', state: 'start' },
        answer: 2, steps: ['Count by 5s: 5, 10, 15. 20 would be too many.', 'So the full pages use 15 stickers.', '17 − 15 = 2, so 2 stickers are left over.'],
        hint1: 'Count by 5s. Stop before you go past 17.', hint2: 'How many stickers do the full pages use? Take that away from 17.' },
    },
    won: { text: 'You made full groups of 4 and stopped before going over.', sticker: 'What is left over is called the remainder. The number of full groups is the quotient.' },
    twinWon: { text: 'You filled the pages with 17 stickers and found 2 left over.', sticker: 'What is left over is called the remainder. The number of full groups is the quotient.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'You have 13 stickers. Each page holds 3. How many pages can you fill all the way?',
        picture: { kind: 'rings', total: 13, size: 3, obj: 'sticker', state: 'start' }, answer: 4,
        steps: ['Count by 3s: 3, 6, 9, 12. 15 would be too many.', '12 stickers fill the pages, and 1 is left over.', 'So you can fill 4 full pages.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'You put 19 marbles into groups of 4. How many marbles are left over?',
        picture: { kind: 'rings', total: 19, size: 4, obj: 'dot', state: 'start' }, answer: 3,
        steps: ['Count by 4s: 4, 8, 12, 16. 20 would be too many.', 'The full groups use 16 marbles.', '19 − 16 = 3, so 3 marbles are left over.'] } },
      { why: 'Still "full groups, then what is left"', problem: { text: '26 apples go into bags of 5. How many bags are full?',
        picture: { kind: 'rings', total: 26, size: 5, obj: 'apple', state: 'start' }, answer: 5,
        steps: ['Count by 5s: 5, 10, 15, 20, 25. 30 would be too many.', '25 apples fill the bags, and 1 is left over.', 'So 5 bags are full.'] } },
      { why: 'A little harder', problem: { text: '47 crayons go into boxes of 6. After you fill every box you can, how many crayons are left over?',
        picture: { kind: 'rings', total: 47, size: 6, obj: 'crayon', state: 'start' }, answer: 5,
        steps: ['Count by 6s: 6, 12, 18, 24, 30, 36, 42. 48 would be too many.', 'The full boxes use 42 crayons.', '47 − 42 = 5, so 5 crayons are left over.'] } },
      { why: 'Same math in a story', problem: { text: 'A van has 8 seats. 30 kids go on a trip. How many vans are filled all the way?',
        picture: { kind: 'rings', total: 30, size: 8, obj: 'chair', state: 'start' }, answer: 3,
        steps: ['Count by 8s: 8, 16, 24. 32 would be too many.', '24 kids fill the vans, and 6 kids are left.', 'So 3 vans are filled all the way.'] } },
    ],
  },
]
