/**
 * Grade 4 · Module 3 — Multiplication and division of multi-digit numbers.
 * Written to docs/new-flow/AUTHORING.md. Topic 1 follows the founder's own Grade 4 example (16 × 3).
 * Teaching pictures: `area` (t1, t2, t4, t5), `columns` (t3), `longdiv` (t6), `tape` (t7, t8).
 */
import type { Lesson, Picture } from '../script'

// ⚠️ Long division work lines are drawn in the dividend's columns, and a leading `−` takes a column of its own.
// So on the teaching screens the dividend carries one leading space: the first `−` sits in that empty column.
const ld = (quotient: string | undefined, work: string[]): Picture => ({ kind: 'longdiv', divisor: '3', dividend: '372', quotient, work })

// A remainder question: one group's size, then the unknown rest. It shows the question, never how many groups.
const leftQ = (per: string, total: string): Picture => ({ kind: 'tape', rows: [{ cells: [{ w: 2, text: per, shade: true }, { w: 4, text: '?' }], brace: total }] })

const vans: Picture = { kind: 'tape', rows: [{ cells: [...Array.from({ length: 6 }, () => ({ w: 4, text: '4' })), { w: 2, text: '2', shade: true }], brace: '26 children' }] }

const boxes = (n: number, each: string) => Array.from({ length: n }, () => ({ w: 1, text: each }))

export const G4M3: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m3-t1', title: 'Break a number apart to multiply (16 × 3)', skill: 'Multiply a two-digit number by one digit by breaking it into tens and ones',
    bigIdea: 'Break the big number into tens and ones. Multiply each part, then add the parts.',
    screens: [
      { title: 'A long floor', text: 'A hallway floor is 16 feet long and 3 feet wide. How many square feet of floor is that?',
        pictures: [{ kind: 'area', cols: ['16'], rows: ['3'] }] },
      { title: '16 is awkward', text: "Here's the trouble. 16 × 3 is not a fact you know by heart. 16 is an awkward number to multiply all in one go.",
        beats: [
          { say: "Here's the trouble. 16 × 3 is not a fact you know by heart.", pic: 0, effect: 'draw' },
          { say: '16 is an awkward number to multiply all in one go.', write: 'too big to do in one go' },
        ],
        pictures: [{ kind: 'area', cols: ['16'], rows: ['3'] }] },
      { title: 'The big idea', text: 'Break the big number into tens and ones. Multiply each part, then add the parts.',
        beats: [
          { say: 'Break the big number into tens and ones.', pic: 0, effect: 'draw' },
          { say: 'Multiply each part, then add the parts.' },
        ],
        pictures: [{ kind: 'area', cols: ['10', '6'], rows: ['3'], widths: [10, 6] }] },
      { title: 'Break 16 apart', text: "So let's cut 16 into 10 and 6. I'll cut the floor right after 10 feet. Look at that. Two smaller pieces now, 10 by 3 and 6 by 3.",
        beats: [
          { say: "So let's cut 16 into 10 and 6.", pic: 0, effect: 'draw' },
          { say: "I'll cut the floor right after 10 feet.", write: 'break at the ten' },
          { say: 'Look at that. Two smaller pieces now, 10 by 3 and 6 by 3.' },
        ],
        pictures: [{ kind: 'area', cols: ['10', '6'], rows: ['3'], widths: [10, 6] }] },
      { title: 'Multiply each part', text: 'Now each piece is an easy one. The first piece is 10 × 3, and that is 30. The second piece is 6 × 3, and that is 18.',
        beats: [
          { say: 'Now each piece is an easy one.', pic: 0, effect: 'draw' },
          { say: 'The first piece is 10 × 3, and that is 30.' },
          { say: 'The second piece is 6 × 3, and that is 18.', pic: 1 },
        ],
        pictures: [{ kind: 'area', cols: ['10', '6'], rows: ['3'], widths: [10, 6], cells: [['30', '18']], motion: true },
          { kind: 'eq', text: '10 × 3 = 30', lines: ['6 × 3 = 18'] }] },
      { title: 'Add the parts', text: 'Now put the two pieces back together. 30 + 18 = 48. So 16 × 3 = 48, and the floor is 48 square feet.',
        beats: [
          { say: 'Now put the two pieces back together.', write: 'every part, then add' },
          { say: '30 + 18 = 48.', pic: 0 },
          { say: 'So 16 × 3 = 48, and the floor is 48 square feet.' },
        ],
        pictures: [{ kind: 'eq', text: '16 × 3 = 10 × 3 + 6 × 3', lines: ['= 30 + 18', '= 48'] }] },
      { title: 'One thing not to do', text: "Here is the slip almost everybody makes. Don't stop at 30. That 10 × 3 is only part of the floor. Once you have multiplied the parts, you have to add them.",
        beats: [
          { say: 'Here is the slip almost everybody makes.' },
          { say: "Don't stop at 30. That 10 × 3 is only part of the floor.", pic: 0 },
          { say: 'Once you have multiplied the parts, you have to add them.' },
        ],
        pictures: [{ kind: 'cards', wrong: '16 × 3 = 30', right: '16 × 3 = 30 + 18 = 48' }] },
    ],
    turn: {
      text: 'A floor is 23 feet long and 4 feet wide. Break 23 into 20 and 3. How many square feet is the floor?',
      picture: { kind: 'area', cols: ['20', '3'], rows: ['4'], widths: [20, 3] },
      answer: 92, steps: ['Break 23 into 20 and 3.', '20 × 4 = 80 and 3 × 4 = 12.', '80 + 12 = 92, so the floor is 92 square feet.'],
      prompt: 'Multiply each part by 4. Then add the parts.',
      hint1: 'Multiply 20 by 4 and 3 by 4. Then add the two parts.',
      hint2: '20 × 4 = 80. Now find 3 × 4 and add it on.',
      twin: { text: 'A floor is 14 feet long and 5 feet wide. Break 14 into 10 and 4. How many square feet is the floor?',
        picture: { kind: 'area', cols: ['10', '4'], rows: ['5'], widths: [10, 4] },
        answer: 70, steps: ['Break 14 into 10 and 4.', '10 × 5 = 50 and 4 × 5 = 20.', '50 + 20 = 70, so the floor is 70 square feet.'],
        hint1: 'Multiply 10 by 5 and 4 by 5. Then add the two parts.', hint2: '10 × 5 = 50. Now find 4 × 5 and add it on.' },
    },
    won: { text: 'You broke the big number into tens and ones, multiplied each part, and added.', sticker: 'Breaking a number apart to multiply is called the distributive property.' },
    twinWon: { text: 'You broke 14 into 10 and 4, multiplied each part, and added to get 70.', sticker: 'Breaking a number apart to multiply is called the distributive property.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A floor is 13 feet long and 3 feet wide. Break 13 into 10 and 3. How many square feet is the floor?',
        picture: { kind: 'area', cols: ['10', '3'], rows: ['3'], widths: [10, 3] }, answer: 39,
        steps: ['Break 13 into 10 and 3.', '10 × 3 = 30 and 3 × 3 = 9.', '30 + 9 = 39, so the floor is 39 square feet.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A patio is 18 feet long and 4 feet wide. How many square feet is the patio?',
        picture: { kind: 'area', cols: ['10', '8'], rows: ['4'], widths: [10, 8] }, answer: 72,
        steps: ['Break 18 into 10 and 8.', '10 × 4 = 40 and 8 × 4 = 32.', '40 + 32 = 72, so the patio is 72 square feet.'] } },
      { why: 'Still "break it, then add"', problem: { text: 'Find 27 × 3.',
        picture: { kind: 'area', cols: ['20', '7'], rows: ['3'], widths: [20, 7] }, answer: 81,
        steps: ['Break 27 into 20 and 7.', '20 × 3 = 60 and 7 × 3 = 21.', '60 + 21 = 81, so 27 × 3 = 81.'] } },
      { why: 'A little harder', problem: { text: 'Find 46 × 7.',
        picture: { kind: 'area', cols: ['40', '6'], rows: ['7'], widths: [40, 6] }, answer: 322,
        steps: ['Break 46 into 40 and 6.', '40 × 7 = 280 and 6 × 7 = 42.', '280 + 42 = 322, so 46 × 7 = 322.'] } },
      { why: 'Same math in a story', problem: { text: 'A school buys 6 boxes of pencils. Each box holds 34 pencils. How many pencils does the school buy?',
        picture: { kind: 'area', cols: ['30', '4'], rows: ['6'], widths: [30, 4] }, answer: 204,
        steps: ['Break 34 into 30 and 4.', '30 × 6 = 180 and 4 × 6 = 24.', '180 + 24 = 204, so the school buys 204 pencils.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m3-t2', title: 'Multiply a big number by one digit', skill: 'Multiply a three- or four-digit number by one digit, place by place',
    bigIdea: 'Break the number into hundreds, tens and ones. Multiply each part, then add all the parts.',
    screens: [
      { title: 'Seats on a train', text: 'A train has 6 cars. Each car has 342 seats. How many seats are on the train?',
        pictures: [{ kind: 'area', cols: ['342'], rows: ['6'] }] },
      { title: 'Too big to count', text: '342 × 6 is nowhere in your times tables. And counting out 6 groups of 342 one by one would take you all day.',
        beats: [
          { say: '342 × 6 is nowhere in your times tables.', pic: 0, effect: 'draw' },
          { say: 'And counting out 6 groups of 342 one by one would take you all day.', write: 'counting is too slow' },
        ],
        pictures: [{ kind: 'area', cols: ['342'], rows: ['6'] }] },
      { title: 'The big idea', text: 'Break the number into hundreds, tens and ones. Multiply each part, then add all the parts.',
        beats: [
          { say: 'Break the number into hundreds, tens and ones.', pic: 0, effect: 'draw' },
          { say: 'Multiply each part, then add all the parts.' },
        ],
        pictures: [{ kind: 'area', cols: ['300', '40', '2'], rows: ['6'], widths: [5, 3, 2] }] },
      { title: 'Break 342 apart', text: "342 is 300 and 40 and 2. So I'll cut it into three parts, one for each place.",
        beats: [
          { say: '342 is 300 and 40 and 2.', pic: 0, effect: 'draw' },
          { say: "So I'll cut it into three parts, one for each place.", write: 'one part for each place' },
        ],
        pictures: [{ kind: 'area', cols: ['300', '40', '2'], rows: ['6'], widths: [5, 3, 2] }] },
      { title: 'Multiply each part', text: 'Start with the biggest part. 3 hundreds times 6 is 18 hundreds, so 300 × 6 = 1,800. Then 40 × 6 = 240, and 2 × 6 = 12.',
        beats: [
          { say: 'Start with the biggest part.', pic: 0, effect: 'draw' },
          { say: '3 hundreds times 6 is 18 hundreds, so 300 × 6 = 1,800.' },
          { say: 'Then 40 × 6 = 240, and 2 × 6 = 12.', pic: 1 },
        ],
        pictures: [{ kind: 'area', cols: ['300', '40', '2'], rows: ['6'], widths: [5, 3, 2], cells: [['1,800', '240', '12']], motion: true },
          { kind: 'eq', text: '300 × 6 = 1,800', lines: ['40 × 6 = 240', '2 × 6 = 12'] }] },
      { title: 'Add all the parts', text: 'Now add every part. 1,800 + 240 + 12 = 2,052. So 342 × 6 = 2,052, and there are 2,052 seats on the train.',
        beats: [
          { say: 'Now add every part.', write: 'no part gets left out' },
          { say: '1,800 + 240 + 12 = 2,052.', pic: 0 },
          { say: 'So 342 × 6 = 2,052, and there are 2,052 seats on the train.' },
        ],
        pictures: [{ kind: 'eq', text: '342 × 6 = 1,800 + 240 + 12', lines: ['= 2,052'] }] },
      { title: 'One thing not to do', text: "Watch out for this one. Don't leave a part out. Those 2 ones get multiplied too. Every part gets multiplied, and every part gets added.",
        beats: [
          { say: 'Watch out for this one.' },
          { say: "Don't leave a part out. Those 2 ones get multiplied too.", pic: 0 },
          { say: 'Every part gets multiplied, and every part gets added.' },
        ],
        pictures: [{ kind: 'cards', wrong: '1,800 + 240 = 2,040', right: '1,800 + 240 + 12 = 2,052' }] },
    ],
    turn: {
      text: 'A train has 4 cars. Each car has 253 seats. How many seats are on the train?',
      picture: { kind: 'area', cols: ['200', '50', '3'], rows: ['4'], widths: [5, 3, 2] },
      answer: 1012, steps: ['Break 253 into 200, 50 and 3.', '200 × 4 = 800, 50 × 4 = 200 and 3 × 4 = 12.', '800 + 200 + 12 = 1,012, so there are 1,012 seats.'],
      prompt: 'Multiply each part by 4. Then add all three parts.',
      hint1: 'Multiply 200, 50 and 3 by 4. Then add all three parts.',
      hint2: 'Start with 200 × 4 = 800. Now find 50 × 4 and 3 × 4.',
      twin: { text: 'A train has 3 cars. Each car has 132 seats. How many seats are on the train?',
        picture: { kind: 'area', cols: ['100', '30', '2'], rows: ['3'], widths: [5, 3, 2] },
        answer: 396, steps: ['Break 132 into 100, 30 and 2.', '100 × 3 = 300, 30 × 3 = 90 and 2 × 3 = 6.', '300 + 90 + 6 = 396, so there are 396 seats.'],
        hint1: 'Multiply 100, 30 and 2 by 3. Then add all three parts.', hint2: 'Start with 100 × 3 = 300. Now find 30 × 3 and 2 × 3.' },
    },
    won: { text: 'You multiplied every place and added all the parts.', sticker: 'Each part you multiply and add is called a partial product.' },
    twinWon: { text: 'You broke 132 into three parts, multiplied each by 3, and added to get 396.', sticker: 'Each part you multiply and add is called a partial product.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Find 213 × 4.',
        picture: { kind: 'area', cols: ['200', '10', '3'], rows: ['4'], widths: [5, 3, 2] }, answer: 852,
        steps: ['Break 213 into 200, 10 and 3.', '200 × 4 = 800, 10 × 4 = 40 and 3 × 4 = 12.', '800 + 40 + 12 = 852, so 213 × 4 = 852.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Find 324 × 5.',
        picture: { kind: 'area', cols: ['300', '20', '4'], rows: ['5'], widths: [5, 3, 2] }, answer: 1620,
        steps: ['Break 324 into 300, 20 and 4.', '300 × 5 = 1,500, 20 × 5 = 100 and 4 × 5 = 20.', '1,500 + 100 + 20 = 1,620, so 324 × 5 = 1,620.'] } },
      { why: 'Still "every part, then add"', problem: { text: 'Find 1,203 × 3.',
        picture: { kind: 'area', cols: ['1,000', '200', '3'], rows: ['3'], widths: [5, 3, 2] }, answer: 3609,
        steps: ['Break 1,203 into 1,000, 200 and 3. There are no tens.', '1,000 × 3 = 3,000, 200 × 3 = 600 and 3 × 3 = 9.', '3,000 + 600 + 9 = 3,609, so 1,203 × 3 = 3,609.'] } },
      { why: 'A little harder', problem: { text: 'Find 2,416 × 4.',
        picture: { kind: 'area', cols: ['2,000', '400', '10', '6'], rows: ['4'], widths: [4, 3, 2, 2] }, answer: 9664,
        steps: ['Break 2,416 into 2,000, 400, 10 and 6.', '2,000 × 4 = 8,000, 400 × 4 = 1,600, 10 × 4 = 40 and 6 × 4 = 24.', '8,000 + 1,600 + 40 + 24 = 9,664, so 2,416 × 4 = 9,664.'] } },
      { why: 'Same math in a story', problem: { text: 'A farm packs 7 crates of apples. Each crate holds 135 apples. How many apples does the farm pack?',
        picture: { kind: 'area', cols: ['100', '30', '5'], rows: ['7'], widths: [5, 3, 2] }, answer: 945,
        steps: ['Break 135 into 100, 30 and 5.', '100 × 7 = 700, 30 × 7 = 210 and 5 × 7 = 35.', '700 + 210 + 35 = 945, so the farm packs 945 apples.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m3-t3', title: 'The standard way to multiply', skill: 'Multiply by one digit in columns, carrying to the next place',
    bigIdea: 'Start at the ones and move left. When a place makes 10 or more, write the ones and carry the tens to the next place.',
    screens: [
      { title: 'Boxes of crayons', text: 'A store has 3 boxes. Each box holds 164 crayons. How many crayons are there?',
        pictures: [{ kind: 'columns', rows: ['164', '3'], op: '×' }] },
      { title: 'A shorter way to write it', text: 'You could break 164 into 100, 60 and 4 and add the three parts. That works every time, but it is a lot of writing. Let me show you a shorter way.',
        beats: [
          { say: 'You could break 164 into 100, 60 and 4 and add the three parts.', pic: 0, effect: 'draw' },
          { say: 'That works every time, but it is a lot of writing.' },
          { say: 'Let me show you a shorter way.', write: 'same math, less writing' },
        ],
        pictures: [{ kind: 'columns', rows: ['164', '3'], op: '×' }] },
      { title: 'The big idea', text: 'Start at the ones and move left. When a place makes 10 or more, write the ones and carry the tens to the next place.',
        beats: [
          { say: 'Start at the ones and move left.', pic: 0, effect: 'draw' },
          { say: 'When a place makes 10 or more, write the ones and carry the tens to the next place.' },
        ],
        pictures: [{ kind: 'columns', rows: ['164', '3'], op: '×', places: ['H', 'T', 'O'] }] },
      { title: 'The ones', text: 'Ones first. 4 × 3 = 12. That is 1 ten and 2 ones, so the 2 goes under the ones. The 1 ten does not fit here, so it rides up to the top of the tens.',
        beats: [
          { say: 'Ones first. 4 × 3 = 12.', pic: 0, effect: 'draw' },
          { say: 'That is 1 ten and 2 ones, so the 2 goes under the ones.' },
          { say: 'The 1 ten does not fit here, so it rides up to the top of the tens.', write: 'a ten never stays in the ones' },
        ],
        pictures: [{ kind: 'columns', rows: ['164', '3'], op: '×', places: ['H', 'T', 'O'], carry: '1 ', answer: '2', motion: true }] },
      { title: 'The tens', text: 'Now the tens. 6 × 3 = 18, and then add the 1 you carried. That makes 19. Write the 9 under the tens and carry the 1 up to the hundreds.',
        beats: [
          { say: 'Now the tens. 6 × 3 = 18, and then add the 1 you carried.', pic: 0, effect: 'draw' },
          { say: 'That makes 19.', write: 'multiply first, then add the carry' },
          { say: 'Write the 9 under the tens and carry the 1 up to the hundreds.' },
        ],
        pictures: [{ kind: 'columns', rows: ['164', '3'], op: '×', places: ['H', 'T', 'O'], carry: '11 ', answer: '92', motion: true }] },
      { title: 'The hundreds', text: 'Last one. 1 × 3 = 3, plus the 1 you carried makes 4. Write the 4 down and you are done. So 164 × 3 = 492 crayons.',
        beats: [
          { say: 'Last one. 1 × 3 = 3, plus the 1 you carried makes 4.', pic: 0, effect: 'draw' },
          { say: 'Write the 4 down and you are done.' },
          { say: 'So 164 × 3 = 492 crayons.' },
        ],
        pictures: [{ kind: 'columns', rows: ['164', '3'], op: '×', places: ['H', 'T', 'O'], carry: '11 ', answer: '492' }] },
      { title: 'One thing not to do', text: "Here is where it goes wrong. Don't forget the number you carried. Multiply first, then add the carry, and then write.",
        beats: [
          { say: 'Here is where it goes wrong.' },
          { say: "Don't forget the number you carried.", pic: 0 },
          { say: 'Multiply first, then add the carry, and then write.' },
        ],
        pictures: [{ kind: 'cards', wrong: '164 × 3 = 382', right: '164 × 3 = 492' }] },
    ],
    turn: {
      text: 'A store has 4 boxes. Each box holds 127 crayons. Multiply the standard way. How many crayons are there?',
      picture: { kind: 'columns', rows: ['127', '4'], op: '×', answer: null },
      answer: 508, steps: ['Ones: 7 × 4 = 28. Write 8, carry 2.', 'Tens: 2 × 4 = 8, plus the 2 carried is 10. Write 0, carry 1.', 'Hundreds: 1 × 4 = 4, plus 1 is 5. So there are 508 crayons.'],
      prompt: 'Start with the ones. Multiply, then add any carry.',
      hint1: 'Start with the ones: 7 × 4. Write the ones and carry the tens.',
      hint2: '7 × 4 = 28, so write 8 and carry 2. Add that 2 after you multiply the tens.',
      twin: { text: 'Multiply the standard way: 238 × 3.',
        picture: { kind: 'columns', rows: ['238', '3'], op: '×', answer: null },
        answer: 714, steps: ['Ones: 8 × 3 = 24. Write 4, carry 2.', 'Tens: 3 × 3 = 9, plus the 2 carried is 11. Write 1, carry 1.', 'Hundreds: 2 × 3 = 6, plus 1 is 7. So 238 × 3 = 714.'],
        hint1: 'Start with the ones: 8 × 3. Write the ones and carry the tens.', hint2: '8 × 3 = 24, so write 4 and carry 2. Add the carry after each multiply.' },
    },
    won: { text: 'You went place by place from the ones, and you added every carry.', sticker: 'This step-by-step way to multiply in columns is called the standard algorithm.' },
    twinWon: { text: 'You multiplied 238 × 3 place by place, carried, and got 714.', sticker: 'This step-by-step way to multiply in columns is called the standard algorithm.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Multiply the standard way: 153 × 2.',
        picture: { kind: 'columns', rows: ['153', '2'], op: '×', answer: null }, answer: 306,
        steps: ['Ones: 3 × 2 = 6. Write 6.', 'Tens: 5 × 2 = 10. Write 0, carry 1.', 'Hundreds: 1 × 2 = 2, plus the 1 carried is 3. So 153 × 2 = 306.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Multiply the standard way: 246 × 3.',
        picture: { kind: 'columns', rows: ['246', '3'], op: '×', answer: null }, answer: 738,
        steps: ['Ones: 6 × 3 = 18. Write 8, carry 1.', 'Tens: 4 × 3 = 12, plus 1 is 13. Write 3, carry 1.', 'Hundreds: 2 × 3 = 6, plus 1 is 7. So 246 × 3 = 738.'] } },
      { why: 'Still "carry to the next place"', problem: { text: 'Multiply the standard way: 409 × 5.',
        picture: { kind: 'columns', rows: ['409', '5'], op: '×', answer: null }, answer: 2045,
        steps: ['Ones: 9 × 5 = 45. Write 5, carry 4.', 'Tens: 0 × 5 = 0, plus the 4 carried is 4. Write 4.', 'Hundreds: 4 × 5 = 20. Write 20. So 409 × 5 = 2,045.'] } },
      { why: 'A little harder', problem: { text: 'Multiply the standard way: 1,354 × 3.',
        picture: { kind: 'columns', rows: ['1354', '3'], op: '×', answer: null }, answer: 4062,
        steps: ['Ones: 4 × 3 = 12. Write 2, carry 1. Tens: 5 × 3 = 15, plus 1 is 16. Write 6, carry 1.', 'Hundreds: 3 × 3 = 9, plus 1 is 10. Write 0, carry 1.', 'Thousands: 1 × 3 = 3, plus 1 is 4. So 1,354 × 3 = 4,062.'] } },
      { why: 'Same math in a story', problem: { text: 'A theater has 6 sections. Each section has 275 seats. How many seats are in the theater?',
        picture: { kind: 'columns', rows: ['275', '6'], op: '×', answer: null }, answer: 1650,
        steps: ['Ones: 5 × 6 = 30. Write 0, carry 3.', 'Tens: 7 × 6 = 42, plus 3 is 45. Write 5, carry 4.', 'Hundreds: 2 × 6 = 12, plus 4 is 16. So there are 1,650 seats.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m3-t4', title: 'Two-digit times two-digit', skill: 'Multiply two two-digit numbers by breaking both apart',
    bigIdea: 'Break both numbers into tens and ones. Multiply every part by every part, then add all four pieces.',
    screens: [
      { title: 'A garden', text: 'A garden is 23 feet long and 14 feet wide. How many square feet is the garden?',
        pictures: [{ kind: 'area', cols: ['23'], rows: ['14'] }] },
      { title: 'Both numbers are big', text: 'Last time only one number was big. This time both of them are. And if you break only the 23 apart, you are still stuck with 20 × 14, which is no easier.',
        beats: [
          { say: 'Last time only one number was big. This time both of them are.', pic: 0, effect: 'draw' },
          { say: 'And if you break only the 23 apart, you are still stuck with 20 × 14, which is no easier.', write: 'breaking one is not enough' },
        ],
        pictures: [{ kind: 'area', cols: ['23'], rows: ['14'] }] },
      { title: 'The big idea', text: 'Break both numbers into tens and ones. Multiply every part by every part, then add all four pieces.',
        beats: [
          { say: 'Break both numbers into tens and ones.', pic: 0, effect: 'draw' },
          { say: 'Multiply every part by every part, then add all four pieces.' },
        ],
        pictures: [{ kind: 'area', cols: ['20', '3'], rows: ['10', '4'], widths: [3, 1], heights: [2, 1] }] },
      { title: 'Break both apart', text: '23 is 20 and 3. 14 is 10 and 4. So I cut the garden both ways, across and down. And now look. Four smaller pieces.',
        beats: [
          { say: '23 is 20 and 3. 14 is 10 and 4.', pic: 0, effect: 'draw' },
          { say: 'So I cut the garden both ways, across and down.', write: 'cut across and down' },
          { say: 'And now look. Four smaller pieces.' },
        ],
        pictures: [{ kind: 'area', cols: ['20', '3'], rows: ['10', '4'], widths: [3, 1], heights: [2, 1] }] },
      { title: 'Multiply every piece', text: 'Now take them one at a time. 20 × 10 = 200. 3 × 10 = 30. 20 × 4 = 80. And the little corner, 3 × 4 = 12.',
        beats: [
          { say: 'Now take them one at a time.', pic: 0, effect: 'draw' },
          { say: '20 × 10 = 200. 3 × 10 = 30.' },
          { say: '20 × 4 = 80. And the little corner, 3 × 4 = 12.' },
        ],
        pictures: [{ kind: 'area', cols: ['20', '3'], rows: ['10', '4'], widths: [3, 1], heights: [2, 1], cells: [['200', '30'], ['80', '12']], motion: true }] },
      { title: 'Add all four pieces', text: 'Every piece is part of the garden, so add all four. 200 + 30 + 80 + 12 = 322. So 23 × 14 = 322, and the garden is 322 square feet.',
        beats: [
          { say: 'Every piece is part of the garden, so add all four.', write: 'all four, every time' },
          { say: '200 + 30 + 80 + 12 = 322.', pic: 0 },
          { say: 'So 23 × 14 = 322, and the garden is 322 square feet.' },
        ],
        pictures: [{ kind: 'eq', text: '23 × 14 = 200 + 30 + 80 + 12', lines: ['= 322'] }] },
      { title: 'One thing not to do', text: "This is the one to watch. Don't just multiply tens by tens and ones by ones. 20 × 10 and 3 × 4 leave two whole pieces of the garden out.",
        beats: [
          { say: 'This is the one to watch.' },
          { say: "Don't just multiply tens by tens and ones by ones.", pic: 0 },
          { say: '20 × 10 and 3 × 4 leave two whole pieces of the garden out.' },
        ],
        pictures: [{ kind: 'cards', wrong: '23 × 14 = 200 + 12 = 212', right: '200 + 30 + 80 + 12 = 322' }] },
    ],
    turn: {
      text: 'A garden is 23 feet long and 15 feet wide. How many square feet is the garden?',
      picture: { kind: 'area', cols: ['20', '3'], rows: ['10', '5'], widths: [3, 1], heights: [2, 1] },
      answer: 345, steps: ['Break 23 into 20 and 3, and 15 into 10 and 5.', 'The four pieces are 20 × 10 = 200, 3 × 10 = 30, 20 × 5 = 100 and 3 × 5 = 15.', '200 + 30 + 100 + 15 = 345, so the garden is 345 square feet.'],
      prompt: 'Find all four pieces. Then add them.',
      hint1: 'Multiply each top number by each side number. There are four pieces.',
      hint2: 'The four pieces are 20 × 10, 3 × 10, 20 × 5 and 3 × 5. Add them all.',
      twin: { text: 'A garden is 32 feet long and 12 feet wide. How many square feet is the garden?',
        picture: { kind: 'area', cols: ['30', '2'], rows: ['10', '2'], widths: [3, 1], heights: [2, 1] },
        answer: 384, steps: ['Break 32 into 30 and 2, and 12 into 10 and 2.', 'The four pieces are 30 × 10 = 300, 2 × 10 = 20, 30 × 2 = 60 and 2 × 2 = 4.', '300 + 20 + 60 + 4 = 384, so the garden is 384 square feet.'],
        hint1: 'Multiply each top number by each side number. There are four pieces.', hint2: 'The four pieces are 30 × 10, 2 × 10, 30 × 2 and 2 × 2. Add them all.' },
    },
    won: { text: 'You broke both numbers apart, found all four pieces, and added them.', sticker: 'Each of the four pieces is a partial product. This drawing is called an area model.' },
    twinWon: { text: 'You found all four pieces of 32 × 12 and added them to get 384.', sticker: 'Each of the four pieces is a partial product. This drawing is called an area model.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Find 24 × 13.',
        picture: { kind: 'area', cols: ['20', '4'], rows: ['10', '3'], widths: [3, 1], heights: [2, 1] }, answer: 312,
        steps: ['Break 24 into 20 and 4, and 13 into 10 and 3.', '20 × 10 = 200, 4 × 10 = 40, 20 × 3 = 60 and 4 × 3 = 12.', '200 + 40 + 60 + 12 = 312, so 24 × 13 = 312.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Find 31 × 22.',
        picture: { kind: 'area', cols: ['30', '1'], rows: ['20', '2'], widths: [3, 1], heights: [2, 1] }, answer: 682,
        steps: ['Break 31 into 30 and 1, and 22 into 20 and 2.', '30 × 20 = 600, 1 × 20 = 20, 30 × 2 = 60 and 1 × 2 = 2.', '600 + 20 + 60 + 2 = 682, so 31 × 22 = 682.'] } },
      { why: 'Still "four pieces, then add"', problem: { text: 'Find 45 × 12.',
        picture: { kind: 'area', cols: ['40', '5'], rows: ['10', '2'], widths: [3, 1], heights: [2, 1] }, answer: 540,
        steps: ['Break 45 into 40 and 5, and 12 into 10 and 2.', '40 × 10 = 400, 5 × 10 = 50, 40 × 2 = 80 and 5 × 2 = 10.', '400 + 50 + 80 + 10 = 540, so 45 × 12 = 540.'] } },
      { why: 'A little harder', problem: { text: 'Find 67 × 38.',
        picture: { kind: 'area', cols: ['60', '7'], rows: ['30', '8'], widths: [3, 1], heights: [2, 1] }, answer: 2546,
        steps: ['Break 67 into 60 and 7, and 38 into 30 and 8.', '60 × 30 = 1,800, 7 × 30 = 210, 60 × 8 = 480 and 7 × 8 = 56.', '1,800 + 210 + 480 + 56 = 2,546, so 67 × 38 = 2,546.'] } },
      { why: 'Same math in a story', problem: { text: 'A school hall has 26 rows of chairs. Each row has 18 chairs. How many chairs are in the hall?',
        picture: { kind: 'area', cols: ['20', '6'], rows: ['10', '8'], widths: [3, 1], heights: [2, 1] }, answer: 468,
        steps: ['Break 26 into 20 and 6, and 18 into 10 and 8.', '20 × 10 = 200, 6 × 10 = 60, 20 × 8 = 160 and 6 × 8 = 48.', '200 + 60 + 160 + 48 = 468, so there are 468 chairs.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m3-t5', title: 'Break a number apart to divide', skill: 'Divide by breaking the number into parts that share evenly',
    bigIdea: 'Break the number into parts that are easy to share. Divide each part, then add the answers.',
    screens: [
      { title: 'A long rug', text: 'A rug covers 84 square feet. It is 4 feet wide. How long is the rug?',
        pictures: [{ kind: 'area', cols: ['?'], rows: ['4'], cells: [['84']] }] },
      { title: 'Not a fact you know', text: '84 ÷ 4 is not in your times tables either. And 84 is too big to share out by 4 in your head all in one go.',
        beats: [
          { say: '84 ÷ 4 is not in your times tables either.', pic: 0, effect: 'draw' },
          { say: 'And 84 is too big to share out by 4 in your head all in one go.', write: 'too big to share all at once' },
        ],
        pictures: [{ kind: 'area', cols: ['?'], rows: ['4'], cells: [['84']] }] },
      { title: 'The big idea', text: 'Break the number into parts that are easy to share. Divide each part, then add the answers.',
        beats: [
          { say: 'Break the number into parts that are easy to share.', pic: 0, effect: 'draw' },
          { say: 'Divide each part, then add the answers.' },
        ],
        pictures: [{ kind: 'area', cols: ['?', '?'], rows: ['4'], widths: [4, 1], cells: [['80', '4']] }] },
      { title: 'Break 84 apart', text: '84 is 80 and 4. Now, I picked those two on purpose, because both of them share by 4 easily. So cut the rug into an 80 piece and a 4 piece.',
        beats: [
          { say: '84 is 80 and 4.', pic: 0, effect: 'draw' },
          { say: 'Now, I picked those two on purpose, because both of them share by 4 easily.', write: 'pick parts that share easily' },
          { say: 'So cut the rug into an 80 piece and a 4 piece.' },
        ],
        pictures: [{ kind: 'area', cols: ['?', '?'], rows: ['4'], widths: [4, 1], cells: [['80', '4']], motion: true }] },
      { title: 'Divide each part', text: 'Share each piece on its own. 80 ÷ 4 = 20, because 4 × 20 = 80. And 4 ÷ 4 = 1. Those two numbers are the lengths of the two pieces.',
        beats: [
          { say: 'Share each piece on its own.', pic: 0, effect: 'draw' },
          { say: '80 ÷ 4 = 20, because 4 × 20 = 80. And 4 ÷ 4 = 1.', pic: 1 },
          { say: 'Those two numbers are the lengths of the two pieces.' },
        ],
        pictures: [{ kind: 'area', cols: ['20', '1'], rows: ['4'], widths: [4, 1], cells: [['80', '4']] },
          { kind: 'eq', text: '80 ÷ 4 = 20', lines: ['4 ÷ 4 = 1'] }] },
      { title: 'Add the lengths', text: 'Push the pieces back together and the lengths add up. 20 + 1 = 21. So 84 ÷ 4 = 21, and the rug is 21 feet long.',
        beats: [
          { say: 'Push the pieces back together and the lengths add up.', write: 'share each part, then add' },
          { say: '20 + 1 = 21.', pic: 0 },
          { say: 'So 84 ÷ 4 = 21, and the rug is 21 feet long.' },
        ],
        pictures: [{ kind: 'eq', text: '84 ÷ 4 = 80 ÷ 4 + 4 ÷ 4', lines: ['= 20 + 1', '= 21'] }] },
      { title: 'One thing not to do', text: "Here is the trap. Don't forget to divide every part. That little 4 gets shared by 4 as well, not just the 80.",
        beats: [
          { say: 'Here is the trap.' },
          { say: "Don't forget to divide every part.", pic: 0 },
          { say: 'That little 4 gets shared by 4 as well, not just the 80.' },
        ],
        pictures: [{ kind: 'cards', wrong: '84 ÷ 4 = 20 + 4 = 24', right: '84 ÷ 4 = 20 + 1 = 21' }] },
    ],
    turn: {
      text: 'A rug covers 96 square feet. It is 3 feet wide. Break 96 into 90 and 6. How long is the rug?',
      picture: { kind: 'area', cols: ['?', '?'], rows: ['3'], widths: [4, 1], cells: [['90', '6']] },
      answer: 32, steps: ['Break 96 into 90 and 6.', '90 ÷ 3 = 30 and 6 ÷ 3 = 2.', '30 + 2 = 32, so the rug is 32 feet long.'],
      prompt: 'Share each part by 3. Then add the answers.',
      hint1: 'Divide 90 by 3 and 6 by 3. Then add the two answers.',
      hint2: '90 ÷ 3 = 30, because 3 × 30 = 90. Now find 6 ÷ 3 and add it on.',
      twin: { text: 'A rug covers 68 square feet. It is 2 feet wide. Break 68 into 60 and 8. How long is the rug?',
        picture: { kind: 'area', cols: ['?', '?'], rows: ['2'], widths: [4, 1], cells: [['60', '8']] },
        answer: 34, steps: ['Break 68 into 60 and 8.', '60 ÷ 2 = 30 and 8 ÷ 2 = 4.', '30 + 4 = 34, so the rug is 34 feet long.'],
        hint1: 'Divide 60 by 2 and 8 by 2. Then add the two answers.', hint2: '60 ÷ 2 = 30, because 2 × 30 = 60. Now find 8 ÷ 2 and add it on.' },
    },
    won: { text: 'You broke the number into easy parts, shared each one, and added.', sticker: 'In 96 ÷ 3 = 32, 96 is the dividend, 3 is the divisor and 32 is the quotient.' },
    twinWon: { text: 'You broke 68 into 60 and 8, shared each part by 2, and got 34.', sticker: 'In 68 ÷ 2 = 34, 68 is the dividend, 2 is the divisor and 34 is the quotient.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A rug covers 88 square feet. It is 4 feet wide. Break 88 into 80 and 8. How long is the rug?',
        picture: { kind: 'area', cols: ['?', '?'], rows: ['4'], widths: [4, 1], cells: [['80', '8']] }, answer: 22,
        steps: ['Break 88 into 80 and 8.', '80 ÷ 4 = 20 and 8 ÷ 4 = 2.', '20 + 2 = 22, so the rug is 22 feet long.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Find 75 ÷ 5. Break 75 into 50 and 25.',
        picture: { kind: 'area', cols: ['?', '?'], rows: ['5'], widths: [2, 1], cells: [['50', '25']] }, answer: 15,
        steps: ['Break 75 into 50 and 25.', '50 ÷ 5 = 10 and 25 ÷ 5 = 5.', '10 + 5 = 15, so 75 ÷ 5 = 15.'] } },
      { why: 'Still "share each part"', problem: { text: 'Find 624 ÷ 6. Break 624 into 600 and 24.',
        picture: { kind: 'area', cols: ['?', '?'], rows: ['6'], widths: [4, 1], cells: [['600', '24']] }, answer: 104,
        steps: ['Break 624 into 600 and 24.', '600 ÷ 6 = 100 and 24 ÷ 6 = 4.', '100 + 4 = 104, so 624 ÷ 6 = 104.'] } },
      { why: 'A little harder', problem: { text: 'Find 856 ÷ 4. Break 856 into 800, 40 and 16.',
        picture: { kind: 'area', cols: ['?', '?', '?'], rows: ['4'], widths: [5, 2, 2], cells: [['800', '40', '16']] }, answer: 214,
        steps: ['Break 856 into 800, 40 and 16.', '800 ÷ 4 = 200, 40 ÷ 4 = 10 and 16 ÷ 4 = 4.', '200 + 10 + 4 = 214, so 856 ÷ 4 = 214.'] } },
      { why: 'Same math in a story', problem: { text: 'A baker shares 72 muffins equally onto 3 trays. Break 72 into 60 and 12. How many muffins go on each tray?',
        picture: { kind: 'area', cols: ['?', '?'], rows: ['3'], widths: [3, 1], cells: [['60', '12']] }, answer: 24,
        steps: ['Break 72 into 60 and 12.', '60 ÷ 3 = 20 and 12 ÷ 3 = 4.', '20 + 4 = 24, so each tray gets 24 muffins.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m3-t6', title: 'Divide a big number by one digit', skill: 'Long division by a one-digit number, one place at a time',
    bigIdea: 'Share one place at a time, starting with the biggest place. Divide, multiply, take away, then bring down the next digit.',
    screens: [
      { title: 'Sharing stickers', text: '3 friends share 372 stickers equally. How many stickers does each friend get?',
        pictures: [ld(undefined, [])] },
      { title: 'Too big to break in your head', text: 'Breaking it apart still works, but picking good parts gets hard once the numbers are this big. So let me show you a way that works for any number at all, one digit at a time.',
        beats: [
          { say: 'Breaking it apart still works, but picking good parts gets hard once the numbers are this big.', pic: 0, effect: 'draw' },
          { say: 'So let me show you a way that works for any number at all, one digit at a time.', write: 'one digit at a time' },
        ],
        pictures: [ld(undefined, [])] },
      { title: 'The big idea', text: 'Share one place at a time, starting with the biggest place. Divide, multiply, take away, then bring down the next digit.',
        beats: [
          { say: 'Share one place at a time, starting with the biggest place.', pic: 0, effect: 'draw' },
          { say: 'Divide, multiply, take away, then bring down the next digit.' },
        ],
        pictures: [ld(undefined, [])] },
      { title: 'The hundreds', text: 'Start big. 3 hundreds shared by 3 friends is 1 hundred each, so the 1 goes on top. Now 1 × 3 = 3, and 3 − 3 = 0, so nothing is left in the hundreds. Bring the 7 down.',
        beats: [
          { say: 'Start big. 3 hundreds shared by 3 friends is 1 hundred each, so the 1 goes on top.', pic: 0, effect: 'draw' },
          { say: 'Now 1 × 3 = 3, and 3 − 3 = 0, so nothing is left in the hundreds.' },
          { say: 'Bring the 7 down.', pic: 1 },
        ],
        pictures: [ld('1', ['−3  ', ' 7 ']),
          { kind: 'table', head: ['Divide', 'Multiply', 'Take away', 'Bring down'], rows: [['3 ÷ 3 = 1', '1 × 3 = 3', '3 − 3 = 0', 'the 7']], motion: true }] },
      { title: 'The tens', text: 'Now the tens. 7 tens shared by 3 is 2 tens each, with 1 ten left over. The 2 goes on top. 2 × 3 = 6, and 7 − 6 = 1. Bring the 2 down beside that 1, and you have 12.',
        beats: [
          { say: 'Now the tens. 7 tens shared by 3 is 2 tens each, with 1 ten left over.', pic: 0, effect: 'draw' },
          { say: 'The 2 goes on top. 2 × 3 = 6, and 7 − 6 = 1.' },
          { say: 'Bring the 2 down beside that 1, and you have 12.', write: 'the leftover joins the next digit' },
        ],
        pictures: [ld('12', ['−3  ', ' 7 ', ' −6 ', ' 12'])] },
      { title: 'The ones', text: 'Last place. 12 shared by 3 is 4, so the 4 goes on top. 4 × 3 = 12, and 12 − 12 = 0. Nothing left over. So 372 ÷ 3 = 124, and each friend gets 124 stickers.',
        beats: [
          { say: 'Last place. 12 shared by 3 is 4, so the 4 goes on top.', pic: 0, effect: 'draw' },
          { say: '4 × 3 = 12, and 12 − 12 = 0. Nothing left over.' },
          { say: 'So 372 ÷ 3 = 124, and each friend gets 124 stickers.' },
        ],
        pictures: [ld('124', ['−3  ', ' 7 ', ' −6 ', ' 12', ' −12', '  0'])] },
      { title: 'One thing not to do', text: "Here is the one that catches people. Don't skip a place. Every digit gets its turn and its own number on top, starting all the way back at the hundreds.",
        beats: [
          { say: 'Here is the one that catches people.' },
          { say: "Don't skip a place.", pic: 0 },
          { say: 'Every digit gets its turn and its own number on top, starting all the way back at the hundreds.' },
        ],
        pictures: [{ kind: 'cards', wrong: '372 ÷ 3 = 24', right: '372 ÷ 3 = 124' }] },
    ],
    turn: {
      text: 'Find 384 ÷ 3.',
      picture: { kind: 'longdiv', divisor: '3', dividend: '384' },
      answer: 128, steps: ['Hundreds: 3 ÷ 3 = 1, and 3 − 3 = 0. Bring down the 8.', 'Tens: 3 goes into 8 two times, and 8 − 6 = 2. Bring down the 4 to make 24.', 'Ones: 24 ÷ 3 = 8. So 384 ÷ 3 = 128.'],
      prompt: 'Start with the hundreds. Divide, multiply, take away, bring down.',
      hint1: 'Start with the hundreds: how many 3s are in 3?',
      hint2: 'Next, 3 goes into 8 two times with 2 left. Bring down the 4 beside the 2.',
      twin: { text: 'Find 552 ÷ 4.',
        picture: { kind: 'longdiv', divisor: '4', dividend: '552' },
        answer: 138, steps: ['Hundreds: 4 goes into 5 once, and 5 − 4 = 1. Bring down the 5 to make 15.', 'Tens: 4 goes into 15 three times, and 15 − 12 = 3. Bring down the 2 to make 32.', 'Ones: 32 ÷ 4 = 8. So 552 ÷ 4 = 138.'],
        hint1: 'Start with the hundreds: how many 4s are in 5?', hint2: 'After the hundreds, 1 is left. Bring down the 5 beside it and share that by 4.' },
    },
    won: { text: 'You shared one place at a time: divide, multiply, take away, bring down.', sticker: 'Dividing one place at a time like this is called long division.' },
    twinWon: { text: 'You shared 552 by 4 one place at a time and got 138.', sticker: 'Dividing one place at a time like this is called long division.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Find 486 ÷ 2.',
        picture: { kind: 'longdiv', divisor: '2', dividend: '486' }, answer: 243,
        steps: ['Hundreds: 4 ÷ 2 = 2. Nothing is left. Bring down the 8.', 'Tens: 8 ÷ 2 = 4. Nothing is left. Bring down the 6.', 'Ones: 6 ÷ 2 = 3. So 486 ÷ 2 = 243.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Find 736 ÷ 4.',
        picture: { kind: 'longdiv', divisor: '4', dividend: '736' }, answer: 184,
        steps: ['Hundreds: 4 goes into 7 once, and 7 − 4 = 3. Bring down the 3 to make 33.', 'Tens: 4 goes into 33 eight times, and 33 − 32 = 1. Bring down the 6 to make 16.', 'Ones: 16 ÷ 4 = 4. So 736 ÷ 4 = 184.'] } },
      { why: 'Still "one place at a time"', problem: { text: 'Find 945 ÷ 5.',
        picture: { kind: 'longdiv', divisor: '5', dividend: '945' }, answer: 189,
        steps: ['Hundreds: 5 goes into 9 once, and 9 − 5 = 4. Bring down the 4 to make 44.', 'Tens: 5 goes into 44 eight times, and 44 − 40 = 4. Bring down the 5 to make 45.', 'Ones: 45 ÷ 5 = 9. So 945 ÷ 5 = 189.'] } },
      { why: 'A little harder', problem: { text: 'Find 2,184 ÷ 6.',
        picture: { kind: 'longdiv', divisor: '6', dividend: '2184' }, answer: 364,
        steps: ['6 does not go into 2, so start with 21. 6 goes into 21 three times, and 21 − 18 = 3.', 'Bring down the 8 to make 38. 6 goes into 38 six times, and 38 − 36 = 2.', 'Bring down the 4 to make 24. 24 ÷ 6 = 4. So 2,184 ÷ 6 = 364.'] } },
      { why: 'Same math in a story', problem: { text: 'A farmer packs 1,176 eggs equally into 8 crates. How many eggs go in each crate?',
        picture: { kind: 'longdiv', divisor: '8', dividend: '1176' }, answer: 147,
        steps: ['8 does not go into 1, so start with 11. 8 goes into 11 once, and 11 − 8 = 3.', 'Bring down the 7 to make 37. 8 goes into 37 four times, and 37 − 32 = 5.', 'Bring down the 6 to make 56. 56 ÷ 8 = 7. So each crate gets 147 eggs.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m3-t7', title: 'What to do with the remainder', skill: 'Decide what a remainder means in a story: round up, drop it, or answer with it',
    bigIdea: 'Divide first. Then read the question to decide: add one more group, drop the leftover, or give the leftover as the answer.',
    screens: [
      { title: 'A trip to the zoo', text: '26 children are going to the zoo. Each van holds 4 children. How many vans do they need?',
        pictures: [leftQ('4 per van', '26 children')] },
      { title: 'It does not come out even', text: "Let's try it. 26 ÷ 4 is 6, with 2 left over. But 6 with 2 left over is not a number of vans. You have to decide what that 2 means.",
        beats: [
          { say: "Let's try it. 26 ÷ 4 is 6, with 2 left over.", pic: 0, effect: 'draw' },
          { say: 'But 6 with 2 left over is not a number of vans.' },
          { say: 'You have to decide what that 2 means.', write: 'the leftover needs a decision' },
        ],
        pictures: [vans] },
      { title: 'The big idea', text: 'Divide first. Then read the question to decide: add one more group, drop the leftover, or give the leftover as the answer.',
        beats: [
          { say: 'Divide first.', pic: 0, effect: 'draw' },
          { say: 'Then read the question to decide: add one more group, drop the leftover, or give the leftover as the answer.' },
        ],
        pictures: [vans] },
      { title: 'Fill the vans', text: "Let's actually fill them, 4 children at a time. 6 full vans carry 24 children. And there are our 2 left over.",
        beats: [
          { say: "Let's actually fill them, 4 children at a time.", pic: 0, effect: 'draw' },
          { say: '6 full vans carry 24 children.' },
          { say: 'And there are our 2 left over.' },
        ],
        pictures: [{ ...vans, motion: true }] },
      { title: 'Read the question', text: 'Now go back and read the question. It asks how many vans they need. Those 2 children still need a ride, so they need one more van. That is 7 vans.',
        beats: [
          { say: 'Now go back and read the question. It asks how many vans they need.', pic: 0, effect: 'draw' },
          { say: 'Those 2 children still need a ride, so they need one more van.', write: 'everyone rides → one more group' },
          { say: 'That is 7 vans.' },
        ],
        pictures: [vans] },
      { title: 'Three kinds of questions', text: 'Here is what I really want you to see. The same 26 ÷ 4 can give three different answers. It all depends on what the question asked for.',
        beats: [
          { say: 'Here is what I really want you to see.', pic: 0, effect: 'draw' },
          { say: 'The same 26 ÷ 4 can give three different answers.', pic: 1 },
          { say: 'It all depends on what the question asked for.' },
        ],
        pictures: [vans, { kind: 'table', head: ['The question asks', 'Answer'], rows: [['How many vans are needed?', '7'], ['How many vans are full?', '6'], ['How many children are left over?', '2']], motion: true }] },
      { title: 'One thing not to do', text: "So here is the mistake. Don't just copy down what the division says. 6 vans would leave 2 children behind. Read the question, then decide.",
        beats: [
          { say: 'So here is the mistake.' },
          { say: "Don't just copy down what the division says.", pic: 0 },
          { say: '6 vans would leave 2 children behind. Read the question, then decide.' },
        ],
        pictures: [{ kind: 'cards', wrong: '6 vans (2 children stay home)', right: '7 vans (everyone rides)' }] },
    ],
    turn: {
      text: '30 children are going to the zoo. Each van holds 4 children. How many vans do they need?',
      picture: leftQ('4 per van', '30 children'),
      answer: 8, steps: ['30 ÷ 4 is 7 with 2 left over.', 'The question asks how many vans are needed. The 2 children left over still need a ride, so add one more van.', 'They need 8 vans.'],
      prompt: 'Divide. Then read the question to decide what the leftover means.',
      hint1: 'Divide 30 by 4. Is anything left over?',
      hint2: 'The children left over still need a ride. Do you need one more van?',
      twin: { text: '43 people are going to a game. Each car holds 5 people. How many cars do they need?',
        picture: leftQ('5 per car', '43 people'),
        answer: 9, steps: ['43 ÷ 5 is 8 with 3 left over.', 'The 3 people left over still need a seat, so add one more car.', 'They need 9 cars.'],
        hint1: 'Divide 43 by 5. Is anything left over?', hint2: 'The people left over still need a seat. Do you need one more car?' },
    },
    won: { text: 'You divided, then read the question to decide what the leftover meant.', sticker: 'What is left over after you divide is called the remainder.' },
    twinWon: { text: 'You divided 43 by 5 and added one more car, so everyone rides in 9 cars.', sticker: 'What is left over after you divide is called the remainder.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '22 children are going swimming. Each van holds 4 children. How many vans do they need?',
        picture: leftQ('4 per van', '22 children'), answer: 6,
        steps: ['22 ÷ 4 is 5 with 2 left over.', 'The 2 children left over still need a ride, so add one more van.', 'They need 6 vans.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A baker has 45 cookies. Each box holds 6 cookies. How many boxes can she fill?',
        picture: leftQ('6 per box', '45 cookies'), answer: 7,
        steps: ['45 ÷ 6 is 7 with 3 left over.', 'The question asks for full boxes. 3 cookies cannot fill a box, so leave them out.', 'She can fill 7 boxes.'] } },
      { why: 'Still "what does the leftover mean?"', problem: { text: 'Sam shares 50 stickers equally among 8 friends, giving each friend as many as he can. How many stickers are left over?',
        picture: { kind: 'tape', rows: [{ cells: [...Array.from({ length: 8 }, () => ({ w: 1, text: '?' })), { w: 1, text: '?', shade: true }], brace: '50 stickers' }] }, answer: 2,
        steps: ['50 ÷ 8 is 6 with some left over, because 8 × 6 = 48.', 'The question asks what is left over, not how many each friend gets: 50 − 48.', 'So 2 stickers are left over.'] } },
      { why: 'A little harder', problem: { text: '316 people wait for a ferry. The ferry carries 8 people on each trip. How many trips does it need to carry everyone?',
        picture: leftQ('8 per trip', '316 people'), answer: 40,
        steps: ['316 ÷ 8 is 39 with 4 left over, because 8 × 39 = 312.', 'The 4 people left over still need a ride, so add one more trip.', 'The ferry needs 40 trips.'] } },
      { why: 'Same math in a story', problem: { text: 'A farmer has 200 eggs. Each carton holds 6 eggs. How many cartons can the farmer fill?',
        picture: leftQ('6 per carton', '200 eggs'), answer: 33,
        steps: ['200 ÷ 6 is 33 with 2 left over, because 6 × 33 = 198.', 'The question asks for full cartons. 2 eggs cannot fill a carton, so leave them out.', 'The farmer can fill 33 cartons.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m3-t8', title: 'Multi-step stories', skill: 'Solve a story that needs two steps: find the hidden number first',
    bigIdea: 'Find the hidden number first. Then use it to answer the question.',
    screens: [
      { title: 'Pencils at a shop', text: 'A shop has 4 boxes of pencils. Each box holds 25 pencils. The shop sells 38 pencils. How many pencils are left?',
        pictures: [{ kind: 'tape', rows: [{ label: 'Boxes', cells: boxes(4, '25') }, { label: 'Pencils', cells: [{ w: 1.52, text: '38 sold', shade: true }, { w: 2.48, text: '? left' }] }] }] },
      { title: 'Two questions in one', text: 'You cannot take 38 away yet, because we do not know what to take it away from. The story never tells you how many pencils the shop had to start with. That number is hiding.',
        beats: [
          { say: 'You cannot take 38 away yet, because we do not know what to take it away from.', pic: 0, effect: 'draw' },
          { say: 'The story never tells you how many pencils the shop had to start with.' },
          { say: 'That number is hiding.', write: 'no starting number yet' },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Boxes', cells: boxes(4, '25') }, { label: 'Pencils', cells: [{ w: 1.52, text: '38 sold', shade: true }, { w: 2.48, text: '? left' }] }] }] },
      { title: 'The big idea', text: 'Find the hidden number first. Then use it to answer the question.',
        beats: [
          { say: 'Find the hidden number first.', pic: 0, effect: 'draw' },
          { say: 'Then use it to answer the question.' },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Boxes', cells: boxes(4, '25') }, { label: 'Pencils', cells: [{ w: 1.52, text: '38 sold', shade: true }, { w: 2.48, text: '? left' }] }] }] },
      { title: 'Step 1: the hidden number', text: 'So, step one. The shop had 4 boxes, and each box holds 25 pencils. 4 × 25 = 100. There it is. The shop started with 100 pencils.',
        beats: [
          { say: 'So, step one. The shop had 4 boxes, and each box holds 25 pencils.', pic: 0, effect: 'draw' },
          { say: '4 × 25 = 100.' },
          { say: 'There it is. The shop started with 100 pencils.' },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Boxes', cells: boxes(4, '25'), brace: '100 pencils' }], motion: true }] },
      { title: 'Step 2: answer the question', text: 'Step two. Now that we have the 100, we can take away the 38 that sold. 100 − 38 = 62.',
        beats: [
          { say: 'Step two. Now that we have the 100, we can take away the 38 that sold.', pic: 0, effect: 'draw' },
          { say: '100 − 38 = 62.', write: 'step 1 feeds step 2' },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Boxes', cells: boxes(4, '25') }, { label: 'Pencils', cells: [{ w: 1.52, text: '38 sold', shade: true }, { w: 2.48, text: '62 left' }], brace: '100 pencils' }], motion: true }] },
      { title: 'Check it makes sense', text: 'Now check it. 62 left and 38 sold put back together make 100, and that is all 4 boxes. It fits. So 62 pencils are left.',
        beats: [
          { say: 'Now check it.', pic: 0 },
          { say: '62 left and 38 sold put back together make 100, and that is all 4 boxes.' },
          { say: 'It fits. So 62 pencils are left.', write: 'put it back together to check' },
        ],
        pictures: [{ kind: 'eq', text: '4 × 25 = 100', lines: ['100 − 38 = 62', '62 + 38 = 100'] }] },
      { title: 'One thing not to do', text: "And here is the big one. Don't stop after the first step. 100 is how many pencils there were, not how many are left. Always finish on the question.",
        beats: [
          { say: 'And here is the big one.' },
          { say: "Don't stop after the first step.", pic: 0 },
          { say: '100 is how many pencils there were, not how many are left. Always finish on the question.' },
        ],
        pictures: [{ kind: 'cards', wrong: '100 pencils left', right: '100 − 38 = 62 pencils left' }] },
    ],
    turn: {
      text: 'A shop has 4 boxes of pencils. Each box holds 25 pencils. The shop sells 47 pencils. How many pencils are left?',
      picture: { kind: 'tape', rows: [{ label: 'Boxes', cells: boxes(4, '25') }, { label: 'Pencils', cells: [{ w: 1.88, text: '47 sold', shade: true }, { w: 2.12, text: '? left' }] }] },
      answer: 53, steps: ['First find all the pencils: 4 × 25 = 100.', 'Then take away the pencils sold: 100 − 47 = 53.', 'So 53 pencils are left.'],
      prompt: 'Find the hidden number first. Then answer the question.',
      hint1: 'How many pencils were there before any were sold?',
      hint2: 'First find 4 × 25. Then take away 47.',
      twin: { text: 'A farmer fills 6 baskets. Each basket holds 32 apples. He sells 75 apples. How many apples are left?',
        picture: { kind: 'tape', rows: [{ label: 'Baskets', cells: boxes(6, '32') }, { label: 'Apples', cells: [{ w: 2.34, text: '75 sold', shade: true }, { w: 3.66, text: '? left' }] }] },
        answer: 117, steps: ['First find all the apples: 6 × 32 = 192.', 'Then take away the apples sold: 192 − 75 = 117.', 'So 117 apples are left.'],
        hint1: 'How many apples were there before any were sold?', hint2: 'First find 6 × 32. Then take away 75.' },
    },
    won: { text: 'You found the hidden number first, then used it to answer the question.', sticker: 'A story that needs more than one step is a multi-step problem.' },
    twinWon: { text: 'You found all the apples first, then took away 75 to get 117.', sticker: 'A story that needs more than one step is a multi-step problem.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A shop has 3 boxes of markers. Each box holds 25 markers. The shop sells 29 markers. How many markers are left?',
        picture: { kind: 'tape', rows: [{ label: 'Boxes', cells: boxes(3, '25') }, { label: 'Markers', cells: [{ w: 1.16, text: '29 sold', shade: true }, { w: 1.84, text: '? left' }] }] }, answer: 46,
        steps: ['First find all the markers: 3 × 25 = 75.', 'Then take away the markers sold: 75 − 29 = 46.', 'So 46 markers are left.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A class buys 5 packs of juice boxes. Each pack has 12 juice boxes. The children drink 18. How many juice boxes are left?',
        picture: { kind: 'tape', rows: [{ label: 'Packs', cells: boxes(5, '12') }, { label: 'Juice', cells: [{ w: 1.5, text: '18 drunk', shade: true }, { w: 3.5, text: '? left' }] }] }, answer: 42,
        steps: ['First find all the juice boxes: 5 × 12 = 60.', 'Then take away the ones the children drink: 60 − 18 = 42.', 'So 42 juice boxes are left.'] } },
      { why: 'Still "hidden number first"', problem: { text: 'A baker packs 84 muffins equally onto 4 trays. Then she adds 7 more muffins to one tray. How many muffins are on that tray now?',
        picture: { kind: 'tape', rows: [{ label: 'All', cells: [{ w: 4, text: '84 muffins' }] }, { label: 'Trays', cells: boxes(4, '?') }, { label: 'That tray', cells: [{ w: 1, text: '?' }, { w: 0.5, text: '+7', shade: true }] }] }, answer: 28,
        steps: ['First find how many go on each tray: 84 ÷ 4 = 21.', 'Then add the 7 extra muffins: 21 + 7 = 28.', 'So that tray has 28 muffins.'] } },
      { why: 'A little harder', problem: { text: 'A school orders 8 boxes of crayons. Each box holds 144 crayons. It gives 375 crayons to the art room. How many crayons are left?',
        picture: { kind: 'tape', rows: [{ label: 'Boxes', cells: boxes(8, '144') }, { label: 'Crayons', cells: [{ w: 2.6, text: '375 given', shade: true }, { w: 5.4, text: '? left' }] }] }, answer: 777,
        steps: ['First find all the crayons: 8 × 144 = 1,152.', 'Then take away the crayons given away: 1,152 − 375 = 777.', 'So 777 crayons are left.'] } },
      { why: 'Same math in a story', problem: { text: 'Movie tickets cost $6 each. A group buys 23 tickets and pays with $200. How many dollars do they get back?',
        picture: { kind: 'tape', rows: [{ label: 'Tickets', cells: [{ w: 1, text: '$6' }, { w: 1, text: '$6' }, { w: 2, text: '… 23 tickets' }] }, { label: 'Paid $200', cells: [{ w: 4, text: 'cost', shade: true }, { w: 1.8, text: '? back' }] }] }, answer: 62,
        steps: ['First find what the tickets cost: 23 × 6 = 138 dollars.', 'Then take the cost away from what they paid: 200 − 138 = 62.', 'So they get $62 back.'] } },
    ],
  },
]
