/**
 * Grade 4 · Module 4 — Foundations for fraction operations.
 * Written to docs/new-flow/AUTHORING.md. Every teaching picture is the `bars` fraction bar.
 */
import type { Lesson, Picture } from '../script'

const SIGNS = ['<', '>', '=']
const LT = { choices: SIGNS, correct: 0 }
const GT = { choices: SIGNS, correct: 1 }
const EQ = { choices: SIGNS, correct: 2 }

/** Two labelled, unshaded bars: the question for a compare problem, never the answer. */
const pair = (a: [number, string], b: [number, string]): Picture =>
  ({ kind: 'bars', bars: [{ parts: a[0], shaded: 0, label: a[1] }, { parts: b[0], shaded: 0, label: b[1] }] })

/** n copies of one shaded piece out of `parts`. */
const copies = (n: number, parts: number, shaded = 1): Picture =>
  ({ kind: 'bars', bars: Array.from({ length: n }, () => ({ parts, shaded })) })

export const G4M4: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m4-t1', title: 'Same amount, smaller pieces', skill: 'Make an equal fraction by cutting every piece into smaller pieces',
    bigIdea: 'Cut every piece into the same number of smaller pieces. Multiply the top and the bottom by that number.',
    screens: [
      { title: 'Half a chocolate bar', text: 'You eat 1/2 of a chocolate bar. Your friend cuts the same bar into 4 pieces and eats 2. Who ate more?',
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1, label: '1/2' }, { parts: 4, shaded: 2, label: '2/4' }] }] },
      { title: 'The numbers look different', text: '1/2 and 2/4 use different numbers. But look at the shaded parts. They are the same size.',
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1, label: '1/2' }, { parts: 4, shaded: 2, label: '2/4' }] }] },
      { title: 'The big idea', text: 'Cut every piece into the same number of smaller pieces. Multiply the top and the bottom by that number.',
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1, split: 2 }] }] },
      { title: 'Cut every piece', text: 'Start with 1/2. Cut each piece into 2 smaller pieces.',
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1, split: 2 }], motion: true }] },
      { title: 'Count the new pieces', text: 'Now the bar has 4 pieces, and 2 of them are shaded. The shaded part did not grow or shrink.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 2, label: '2/4' }], motion: true }] },
      { title: 'Top and bottom both change', text: 'You cut every piece into 2. So the top and the bottom are both multiplied by 2. 1/2 = 2/4.',
        pictures: [{ kind: 'bars', bars: [{ parts: 2, shaded: 1, label: '1/2' }, { parts: 4, shaded: 2, label: '2/4' }] },
          { kind: 'eq', text: '1/2 = 2/4', lines: ['top: 1 × 2 = 2', 'bottom: 2 × 2 = 4'] }] },
      { title: 'One thing not to do', text: "Don't change only the bottom. 1/4 is less than 1/2. Multiply the top by the same number too.",
        pictures: [{ kind: 'cards', wrong: '1/2 = 1/4', right: '1/2 = 2/4' }] },
    ],
    turn: {
      text: 'Cut every piece of 1/2 into smaller pieces so there are 6 in all. 1/2 = ?/6. What is the missing top number?',
      picture: { kind: 'bars', bars: [{ parts: 2, shaded: 1, label: '1/2' }, { parts: 6, shaded: 0, label: '?/6' }] },
      answer: 3, steps: ['To go from 2 pieces to 6 pieces, cut each piece into 3.', 'Multiply the top by 3 too: 1 × 3.', 'So 1/2 = 3/6. The missing number is 3.'],
      prompt: 'Find what the bottom was multiplied by. Multiply the top by the same number.',
      hint1: 'How many small pieces must each half be cut into to make 6 in all?',
      hint2: 'The bottom went from 2 to 6. What did you multiply by? Do the same to the top.',
      twin: { text: 'Cut every piece of 1/3 into smaller pieces so there are 6 in all. 1/3 = ?/6. What is the missing top number?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 1, label: '1/3' }, { parts: 6, shaded: 0, label: '?/6' }] },
        answer: 2, steps: ['To go from 3 pieces to 6 pieces, cut each piece into 2.', 'Multiply the top by 2 too: 1 × 2.', 'So 1/3 = 2/6. The missing number is 2.'],
        hint1: 'How many small pieces must each third be cut into to make 6 in all?',
        hint2: 'The bottom went from 3 to 6. What did you multiply by? Do the same to the top.' },
    },
    won: { text: 'You cut every piece the same way and multiplied the top and the bottom.', sticker: 'Fractions that name the same amount are called equivalent fractions.' },
    twinWon: { text: 'You found that 1/3 is the same amount as 2/6.', sticker: 'Fractions that name the same amount are called equivalent fractions.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '1/2 = ?/8. What is the missing top number?',
        picture: { kind: 'bars', bars: [{ parts: 2, shaded: 1, label: '1/2' }, { parts: 8, shaded: 0, label: '?/8' }] }, answer: 4,
        steps: ['2 pieces become 8 when you cut each piece into 4.', 'Multiply the top by 4 too: 1 × 4.', 'So 1/2 = 4/8. The missing number is 4.'] } },
      { why: 'Same idea, new numbers', problem: { text: '2/3 = ?/12. What is the missing top number?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 2, label: '2/3' }, { parts: 12, shaded: 0, label: '?/12' }] }, answer: 8,
        steps: ['3 pieces become 12 when you cut each piece into 4.', 'Multiply the top by 4 too: 2 × 4.', 'So 2/3 = 8/12. The missing number is 8.'] } },
      { why: 'Still "cut every piece"', problem: { text: '3/4 = ?/8. What is the missing top number?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 3, label: '3/4' }, { parts: 8, shaded: 0, label: '?/8' }] }, answer: 6,
        steps: ['4 pieces become 8 when you cut each piece into 2.', 'Multiply the top by 2 too: 3 × 2.', 'So 3/4 = 6/8. The missing number is 6.'] } },
      { why: 'A little harder', problem: { text: '7/10 = ?/100. What is the missing top number?',
        picture: { kind: 'bars', bars: [{ parts: 10, shaded: 7, label: '7/10' }] }, answer: 70,
        steps: ['10 pieces become 100 when you cut each piece into 10.', 'Multiply the top by 10 too: 7 × 10.', 'So 7/10 = 70/100. The missing number is 70.'] } },
      { why: 'Same math in a story', problem: { text: 'Sam eats 2/4 of a pizza. Kim eats the same amount of the same size pizza, but hers is cut into 8 equal slices. How many slices does Kim eat?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 2, label: '2/4' }, { parts: 8, shaded: 0, label: '?/8' }] }, answer: 4,
        steps: ['8 slices is every fourth cut into 2.', 'Multiply the top by 2 too: 2 × 2.', 'So 2/4 = 4/8. Kim eats 4 slices.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m4-t2', title: 'Compare with one half', skill: 'Compare two fractions by checking each one against 1/2',
    bigIdea: 'Find half of the bottom number. If one fraction is below half and the other is above half, the one above half is bigger.',
    screens: [
      { title: 'Two pies', text: 'You eat 3/8 of a pie. Your friend eats 4/6 of the same size pie. Who ate more?',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 3, label: '3/8' }, { parts: 6, shaded: 4, label: '4/6' }] }] },
      { title: 'The pieces are different', text: 'Eighths and sixths are different sizes. So you cannot just compare the 3 and the 4.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 3, label: '3/8' }, { parts: 6, shaded: 4, label: '4/6' }] }] },
      { title: 'The big idea', text: 'Find half of the bottom number. If one fraction is below half and the other is above half, the one above half is bigger.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 3, label: '3/8' }, { parts: 2, shaded: 1, label: '1/2' }, { parts: 6, shaded: 4, label: '4/6' }] }] },
      { title: 'Is 3/8 more than half?', text: 'Half of 8 pieces is 4 pieces. 3 is less than 4. So 3/8 is less than 1/2.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 3, label: '3/8' }, { parts: 8, shaded: 4, label: '1/2' }], motion: true }] },
      { title: 'Is 4/6 more than half?', text: 'Half of 6 pieces is 3 pieces. 4 is more than 3. So 4/6 is more than 1/2.',
        pictures: [{ kind: 'bars', bars: [{ parts: 6, shaded: 3, label: '1/2' }, { parts: 6, shaded: 4, label: '4/6' }], motion: true }] },
      { title: 'Put it together', text: '3/8 is below half. 4/6 is above half. So 3/8 < 4/6. Your friend ate more.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 3, label: '3/8' }, { parts: 2, shaded: 1, label: '1/2' }, { parts: 6, shaded: 4, label: '4/6' }] },
          { kind: 'eq', text: '3/8 < 1/2 < 4/6', lines: ['3/8 < 4/6'] }] },
      { title: 'One thing not to do', text: "Don't say 3/8 is bigger because 8 is bigger than 6. More pieces means smaller pieces. Check each one against half.",
        pictures: [{ kind: 'cards', wrong: '3/8 > 4/6', right: '3/8 < 4/6' }] },
    ],
    turn: {
      text: 'Compare 5/8 and 2/6. Which sign goes in the middle? 5/8 ? 2/6',
      picture: pair([8, '5/8'], [6, '2/6']),
      answer: GT, steps: ['Half of 8 is 4. 5 is more than 4, so 5/8 is more than 1/2.', 'Half of 6 is 3. 2 is less than 3, so 2/6 is less than 1/2.', 'So 5/8 > 2/6. The answer is >.'],
      prompt: 'Check each fraction against half. Is it above half or below half?',
      hint1: 'Is 5/8 more or less than half? Is 2/6 more or less than half?',
      hint2: 'Half of 8 pieces is 4 pieces. Half of 6 pieces is 3 pieces. Compare each top to its half.',
      twin: { text: 'Compare 2/10 and 3/4. Which sign goes in the middle? 2/10 ? 3/4',
        picture: pair([10, '2/10'], [4, '3/4']),
        answer: LT, steps: ['Half of 10 is 5. 2 is less than 5, so 2/10 is less than 1/2.', 'Half of 4 is 2. 3 is more than 2, so 3/4 is more than 1/2.', 'So 2/10 < 3/4. The answer is <.'],
        hint1: 'Is 2/10 more or less than half? Is 3/4 more or less than half?',
        hint2: 'Half of 10 pieces is 5 pieces. Half of 4 pieces is 2 pieces. Compare each top to its half.' },
    },
    won: { text: 'You checked each fraction against half, then compared.', sticker: 'A number you compare against, like one half, is called a benchmark.' },
    twinWon: { text: 'You saw that 2/10 is below half and 3/4 is above half.', sticker: 'A number you compare against, like one half, is called a benchmark.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which sign goes in the middle? 2/8 ? 4/6',
        picture: pair([8, '2/8'], [6, '4/6']), answer: LT,
        steps: ['Half of 8 is 4. 2 is less than 4, so 2/8 is less than 1/2.', 'Half of 6 is 3. 4 is more than 3, so 4/6 is more than 1/2.', 'So 2/8 < 4/6. The answer is <.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Which sign goes in the middle? 7/10 ? 3/8',
        picture: pair([10, '7/10'], [8, '3/8']), answer: GT,
        steps: ['Half of 10 is 5. 7 is more than 5, so 7/10 is more than 1/2.', 'Half of 8 is 4. 3 is less than 4, so 3/8 is less than 1/2.', 'So 7/10 > 3/8. The answer is >.'] } },
      { why: 'Still "check against half"', problem: { text: 'Which sign goes in the middle? 4/8 ? 3/6',
        picture: pair([8, '4/8'], [6, '3/6']), answer: EQ,
        steps: ['Half of 8 is 4, so 4/8 is exactly 1/2.', 'Half of 6 is 3, so 3/6 is exactly 1/2.', 'Both are 1/2, so 4/8 = 3/6. The answer is =.'] } },
      { why: 'A little harder', problem: { text: 'Which sign goes in the middle? 5/12 ? 4/5',
        picture: pair([12, '5/12'], [5, '4/5']), answer: LT,
        steps: ['Half of 12 is 6. 5 is less than 6, so 5/12 is less than 1/2.', 'Half of 5 is 2 and a half. 4 is more than that, so 4/5 is more than 1/2.', 'So 5/12 < 4/5. The answer is <.'] } },
      { why: 'Same math in a story', problem: { text: 'Ava runs 3/10 of a mile. Ben runs 5/8 of a mile. Which sign goes in the middle? 3/10 ? 5/8',
        picture: pair([10, '3/10'], [8, '5/8']), answer: LT,
        steps: ['Half of 10 is 5. 3 is less than 5, so Ava runs less than 1/2 a mile.', 'Half of 8 is 4. 5 is more than 4, so Ben runs more than 1/2 a mile.', 'So 3/10 < 5/8. Ben runs farther. The answer is <.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m4-t3', title: 'Compare by making pieces match', skill: 'Compare two fractions by cutting them into the same size pieces',
    bigIdea: 'To compare, cut the pieces so both fractions use the same size pieces. Then compare the tops.',
    screens: [
      { title: 'Two ribbons', text: 'Mia has 3/4 of a ribbon. Leo has 5/8 of the same size ribbon. Who has more?',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 3, label: '3/4' }, { parts: 8, shaded: 5, label: '5/8' }] }] },
      { title: 'Big pieces and small pieces', text: 'Fourths are bigger than eighths. 3 big pieces and 5 small pieces are hard to compare.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 3, label: '3/4' }, { parts: 8, shaded: 5, label: '5/8' }] }] },
      { title: 'The big idea', text: 'To compare, cut the pieces so both fractions use the same size pieces. Then compare the tops.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 3, split: 2, label: '3/4' }, { parts: 8, shaded: 5, label: '5/8' }] }] },
      { title: 'Cut the fourths', text: 'Cut each fourth into 2 pieces. Now both bars are cut into eighths.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 3, split: 2, label: '3/4' }, { parts: 8, shaded: 5, label: '5/8' }], motion: true }] },
      { title: 'Count the eighths', text: 'Each fourth is now 2 eighths. 3 fourths is 6 eighths. So 3/4 = 6/8.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 6, label: '6/8' }, { parts: 8, shaded: 5, label: '5/8' }], motion: true }] },
      { title: 'Compare the tops', text: 'Now the pieces match. 6 eighths is more than 5 eighths. So 3/4 > 5/8. Mia has more.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 6, label: '6/8' }, { parts: 8, shaded: 5, label: '5/8' }] },
          { kind: 'eq', text: '6/8 > 5/8', lines: ['3/4 > 5/8'] }] },
      { title: 'One thing not to do', text: "Don't compare the tops before the pieces match. 5 is more than 3, but 5/8 is less than 3/4.",
        pictures: [{ kind: 'cards', wrong: '3/4 < 5/8', right: '3/4 > 5/8' }] },
    ],
    turn: {
      text: 'Compare 3/4 and 7/8. Which sign goes in the middle? 3/4 ? 7/8',
      picture: pair([4, '3/4'], [8, '7/8']),
      answer: LT, steps: ['Cut each fourth into 2 pieces: 3/4 = 6/8.', 'Now both are eighths: 6/8 is less than 7/8.', 'So 3/4 < 7/8. The answer is <.'],
      prompt: 'Make the pieces the same size first. Then compare the tops.',
      hint1: 'Can you cut the fourths so they become eighths?',
      hint2: 'Each fourth is 2 eighths. How many eighths is 3/4?',
      twin: { text: 'Compare 2/3 and 4/6. Which sign goes in the middle? 2/3 ? 4/6',
        picture: pair([3, '2/3'], [6, '4/6']),
        answer: EQ, steps: ['Cut each third into 2 pieces: 2/3 = 4/6.', 'Now both are sixths: 4/6 and 4/6 are the same.', 'So 2/3 = 4/6. The answer is =.'],
        hint1: 'Can you cut the thirds so they become sixths?',
        hint2: 'Each third is 2 sixths. How many sixths is 2/3?' },
    },
    won: { text: 'You made the pieces match, then compared the tops.', sticker: 'Making the bottom numbers match is finding a common denominator.' },
    twinWon: { text: 'You cut the thirds into sixths and saw that 2/3 and 4/6 are the same.', sticker: 'Making the bottom numbers match is finding a common denominator.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which sign goes in the middle? 1/4 ? 3/8',
        picture: pair([4, '1/4'], [8, '3/8']), answer: LT,
        steps: ['Cut each fourth into 2 pieces: 1/4 = 2/8.', 'Now both are eighths: 2/8 is less than 3/8.', 'So 1/4 < 3/8. The answer is <.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Which sign goes in the middle? 5/6 ? 2/3',
        picture: pair([6, '5/6'], [3, '2/3']), answer: GT,
        steps: ['Cut each third into 2 pieces: 2/3 = 4/6.', 'Now both are sixths: 5/6 is more than 4/6.', 'So 5/6 > 2/3. The answer is >.'] } },
      { why: 'Still "make the pieces match"', problem: { text: 'Which sign goes in the middle? 3/5 ? 7/10',
        picture: pair([5, '3/5'], [10, '7/10']), answer: LT,
        steps: ['Cut each fifth into 2 pieces: 3/5 = 6/10.', 'Now both are tenths: 6/10 is less than 7/10.', 'So 3/5 < 7/10. The answer is <.'] } },
      { why: 'A little harder', problem: { text: 'Which sign goes in the middle? 3/4 ? 7/12',
        picture: pair([4, '3/4'], [12, '7/12']), answer: GT,
        steps: ['Cut each fourth into 3 pieces: 3/4 = 9/12.', 'Now both are twelfths: 9/12 is more than 7/12.', 'So 3/4 > 7/12. The answer is >.'] } },
      { why: 'Same math in a story', problem: { text: 'Jay drinks 1/2 of a bottle of water. Kate drinks 4/10 of the same size bottle. Which sign goes in the middle? 1/2 ? 4/10',
        picture: pair([2, '1/2'], [10, '4/10']), answer: GT,
        steps: ['Cut each half into 5 pieces: 1/2 = 5/10.', 'Now both are tenths: 5/10 is more than 4/10.', 'So 1/2 > 4/10. Jay drinks more. The answer is >.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m4-t4', title: 'Break a fraction apart', skill: 'Write a fraction as a sum of fractions with the same bottom number',
    bigIdea: 'A fraction is a group of same-size pieces. Split the pieces into smaller groups, and the groups add back to the fraction.',
    screens: [
      { title: 'Two plates', text: 'A pan of cornbread is cut into 8 equal pieces. 5 pieces are left. You put some on one plate and the rest on another. How could you share them?',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 5 }] }] },
      { title: 'One number, many pieces', text: '5/8 looks like one number. But it is really 5 separate pieces, and pieces can be moved into groups.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 5 }] }] },
      { title: 'The big idea', text: 'A fraction is a group of same-size pieces. Split the pieces into smaller groups, and the groups add back to the fraction.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 2, shade2: 3 }] }] },
      { title: 'Count the pieces', text: '5/8 means 5 pieces. Each piece is 1/8.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 5 }], motion: true },
          { kind: 'eq', text: '1/8 + 1/8 + 1/8 + 1/8 + 1/8' }] },
      { title: 'Make two groups', text: 'Put 2 pieces on one plate and 3 pieces on the other.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 2, shade2: 3 }], motion: true }] },
      { title: 'Write it as adding', text: '2 eighths and 3 eighths make 5 eighths. So 5/8 = 2/8 + 3/8.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 2, shade2: 3 }] }, { kind: 'eq', text: '5/8 = 2/8 + 3/8' }] },
      { title: 'One thing not to do', text: "Don't split the bottom number. Every piece is still an eighth, on both plates.",
        pictures: [{ kind: 'cards', wrong: '5/8 = 2/4 + 3/4', right: '5/8 = 2/8 + 3/8' }] },
    ],
    turn: {
      text: 'Break 5/8 apart. 5/8 = 1/8 + ? What fraction is missing?',
      picture: { kind: 'bars', bars: [{ parts: 8, shaded: 5, label: '5/8' }, { parts: 8, shaded: 1, label: '1/8' }] },
      answer: { frac: [4, 8] }, steps: ['5/8 is 5 eighths. 1/8 is 1 of them.', '5 pieces take away 1 piece leaves 4 pieces. They are still eighths.', 'So 5/8 = 1/8 + 4/8. The missing fraction is 4/8.'],
      prompt: 'Count the pieces in the whole fraction. Find how many pieces are still missing.',
      hint1: 'How many eighths are in 5/8? How many are used already?',
      hint2: '1/8 is 1 piece. How many more pieces make 5 pieces? Keep them as eighths.',
      twin: { text: 'Break 7/10 apart. 7/10 = 3/10 + ? What fraction is missing?',
        picture: { kind: 'bars', bars: [{ parts: 10, shaded: 7, label: '7/10' }, { parts: 10, shaded: 3, label: '3/10' }] },
        answer: { frac: [4, 10] }, steps: ['7/10 is 7 tenths. 3/10 is 3 of them.', '7 pieces take away 3 pieces leaves 4 pieces. They are still tenths.', 'So 7/10 = 3/10 + 4/10. The missing fraction is 4/10.'],
        hint1: 'How many tenths are in 7/10? How many are used already?',
        hint2: '3/10 is 3 pieces. How many more pieces make 7 pieces? Keep them as tenths.' },
    },
    won: { text: 'You split a fraction into groups of same-size pieces.', sticker: 'Breaking a number into parts that add back up is called decomposing.' },
    twinWon: { text: 'You broke 7/10 into 3/10 and 4/10.', sticker: 'Breaking a number into parts that add back up is called decomposing.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '5/6 = 2/6 + ? What fraction is missing?',
        picture: { kind: 'bars', bars: [{ parts: 6, shaded: 5, label: '5/6' }, { parts: 6, shaded: 2, label: '2/6' }] }, answer: { frac: [3, 6] },
        steps: ['5/6 is 5 sixths. 2/6 is 2 of them.', '5 pieces take away 2 pieces leaves 3 pieces.', 'So 5/6 = 2/6 + 3/6. The missing fraction is 3/6.'] } },
      { why: 'Same idea, new numbers', problem: { text: '4/5 = 1/5 + ? What fraction is missing?',
        picture: { kind: 'bars', bars: [{ parts: 5, shaded: 4, label: '4/5' }, { parts: 5, shaded: 1, label: '1/5' }] }, answer: { frac: [3, 5] },
        steps: ['4/5 is 4 fifths. 1/5 is 1 of them.', '4 pieces take away 1 piece leaves 3 pieces.', 'So 4/5 = 1/5 + 3/5. The missing fraction is 3/5.'] } },
      { why: 'Still "split the pieces"', problem: { text: '7/8 = ? + 3/8. What fraction is missing?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 7, label: '7/8' }, { parts: 8, shaded: 3, label: '3/8' }] }, answer: { frac: [4, 8] },
        steps: ['7/8 is 7 eighths. 3/8 is 3 of them.', '7 pieces take away 3 pieces leaves 4 pieces.', 'So 7/8 = 4/8 + 3/8. The missing fraction is 4/8.'] } },
      { why: 'A little harder', problem: { text: '9/12 = 2/12 + 3/12 + ? What fraction is missing?',
        picture: { kind: 'bars', bars: [{ parts: 12, shaded: 9, label: '9/12' }, { parts: 12, shaded: 2, shade2: 3 }] }, answer: { frac: [4, 12] },
        steps: ['9/12 is 9 twelfths. 2/12 and 3/12 are 5 of them.', '9 pieces take away 5 pieces leaves 4 pieces.', 'So 9/12 = 2/12 + 3/12 + 4/12. The missing fraction is 4/12.'] } },
      { why: 'Same math in a story', problem: { text: 'Nora has 9/10 of a pound of grapes. She puts 4/10 of a pound in her lunch bag and the rest in a bowl. How much goes in the bowl?',
        picture: { kind: 'bars', bars: [{ parts: 10, shaded: 9, label: '9/10' }, { parts: 10, shaded: 4, label: '4/10' }] }, answer: { frac: [5, 10] },
        steps: ['9/10 is 9 tenths. The lunch bag gets 4 of them.', '9 pieces take away 4 pieces leaves 5 pieces.', 'So 9/10 = 4/10 + 5/10. The bowl gets 5/10 of a pound.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m4-t5', title: 'Add fractions with the same bottom number', skill: 'Add fractions with the same bottom number',
    bigIdea: 'Same-size pieces? Add the number of pieces. Leave the piece size alone.',
    screens: [
      { title: 'A pan of brownies', text: 'A pan of brownies is cut into 8 equal pieces. You eat 2/8 of the pan, then 3/8 more. How much did you eat?',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 2 }] }] },
      { title: 'Not every number is a count', text: 'It is tempting to add every number you see. But the 8 does not count what you ate. It tells the size of each piece.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 2, label: '2/8' }, { parts: 8, shaded: 3, label: '3/8' }] }] },
      { title: 'The big idea', text: 'Same-size pieces? Add the number of pieces. Leave the piece size alone.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 2, shade2: 3 }] }] },
      { title: 'First, 2 pieces', text: 'The pan is cut into 8. Shade 2 pieces for the first 2/8.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 2 }], motion: true }] },
      { title: 'Then 3 more', text: 'Shade 3 more pieces for the next 3/8. They are the same size as the first pieces.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 2, shade2: 3 }], motion: true }] },
      { title: 'Count the pieces', text: '2 pieces and 3 pieces make 5 pieces. Each one is still an eighth. So 2/8 + 3/8 = 5/8.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 2, shade2: 3, label: '5/8' }] }, { kind: 'eq', text: '2/8 + 3/8 = 5/8' }] },
      { title: 'One thing not to do', text: "Don't add the bottom numbers. 16 would mean smaller pieces, and you never had those.",
        pictures: [{ kind: 'cards', wrong: '2/8 + 3/8 = 5/16', right: '2/8 + 3/8 = 5/8' }] },
    ],
    turn: {
      text: 'What is 1/6 + 4/6?',
      picture: { kind: 'bars', bars: [{ parts: 6, shaded: 1, label: '1/6' }, { parts: 6, shaded: 4, label: '4/6' }] },
      answer: { frac: [5, 6] }, steps: ['Both fractions are sixths, so the pieces are the same size.', 'Add the pieces: 1 + 4 = 5. Keep the bottom number 6.', 'So 1/6 + 4/6 = 5/6.'],
      prompt: 'The pieces are the same size. Add the pieces and keep the bottom number.',
      hint1: 'Are the pieces the same size? Then count how many pieces there are in all.',
      hint2: 'Add the top numbers, 1 and 4. The pieces are still sixths.',
      twin: { text: 'What is 3/10 + 4/10?',
        picture: { kind: 'bars', bars: [{ parts: 10, shaded: 3, label: '3/10' }, { parts: 10, shaded: 4, label: '4/10' }] },
        answer: { frac: [7, 10] }, steps: ['Both fractions are tenths, so the pieces are the same size.', 'Add the pieces: 3 + 4 = 7. Keep the bottom number 10.', 'So 3/10 + 4/10 = 7/10.'],
        hint1: 'Are the pieces the same size? Then count how many pieces there are in all.',
        hint2: 'Add the top numbers, 3 and 4. The pieces are still tenths.' },
    },
    won: { text: 'You added the pieces and kept the piece size.', sticker: 'The bottom number is called the denominator. It stays the same when you add same-size pieces.' },
    twinWon: { text: 'You added 3 tenths and 4 tenths to get 7/10.', sticker: 'The bottom number is called the denominator. It stays the same when you add same-size pieces.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What is 2/5 + 1/5?',
        picture: { kind: 'bars', bars: [{ parts: 5, shaded: 2, label: '2/5' }, { parts: 5, shaded: 1, label: '1/5' }] }, answer: { frac: [3, 5] },
        steps: ['Both are fifths, so the pieces are the same size.', 'Add the pieces: 2 + 1 = 3. Keep the bottom number 5.', 'So 2/5 + 1/5 = 3/5.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is 3/8 + 4/8?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 3, label: '3/8' }, { parts: 8, shaded: 4, label: '4/8' }] }, answer: { frac: [7, 8] },
        steps: ['Both are eighths, so the pieces are the same size.', 'Add the pieces: 3 + 4 = 7. Keep the bottom number 8.', 'So 3/8 + 4/8 = 7/8.'] } },
      { why: 'Still "add the pieces"', problem: { text: 'What is 5/12 + 6/12?',
        picture: { kind: 'bars', bars: [{ parts: 12, shaded: 5, label: '5/12' }, { parts: 12, shaded: 6, label: '6/12' }] }, answer: { frac: [11, 12] },
        steps: ['Both are twelfths, so the pieces are the same size.', 'Add the pieces: 5 + 6 = 11. Keep the bottom number 12.', 'So 5/12 + 6/12 = 11/12.'] } },
      { why: 'A little harder', problem: { text: 'What is 45/100 + 32/100?',
        picture: { kind: 'eq', text: '45/100 + 32/100 = ?' }, answer: { frac: [77, 100] },
        steps: ['Both are hundredths, so the pieces are the same size.', 'Add the pieces: 45 + 32 = 77. Keep the bottom number 100.', 'So 45/100 + 32/100 = 77/100.'] } },
      { why: 'Same math in a story', problem: { text: 'Ella paints 3/10 of a fence in the morning and 6/10 of it in the afternoon. How much of the fence does she paint?',
        picture: { kind: 'bars', bars: [{ parts: 10, shaded: 3, label: '3/10' }, { parts: 10, shaded: 6, label: '6/10' }] }, answer: { frac: [9, 10] },
        steps: ['Both are tenths of the same fence, so the pieces are the same size.', 'Add the pieces: 3 + 6 = 9. Keep the bottom number 10.', 'So 3/10 + 6/10 = 9/10 of the fence.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m4-t6', title: 'Take away fractions with the same bottom number', skill: 'Subtract fractions with the same bottom number',
    bigIdea: 'Same-size pieces? Take away the number of pieces. Leave the piece size alone.',
    screens: [
      { title: 'Pizza left over', text: 'There is 7/8 of a pizza left. You eat 3/8 of the pizza. How much is left now?',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 7 }] }] },
      { title: 'The pizza did not vanish', text: 'If you take away both numbers, the bottom becomes 8 − 8 = 0. But there is still pizza. The 8 tells the size of each slice.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 7 }] }] },
      { title: 'The big idea', text: 'Same-size pieces? Take away the number of pieces. Leave the piece size alone.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 7 }, { parts: 8, shaded: 4 }] }] },
      { title: 'Start with 7 slices', text: '7/8 means 7 slices. Each slice is 1/8.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 7 }], motion: true }] },
      { title: 'Take 3 away', text: 'You eat 3 slices. Now only 4 slices are shaded.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 7 }, { parts: 8, shaded: 4 }], motion: true }] },
      { title: 'Count what is left', text: '7 slices take away 3 slices is 4 slices. They are still eighths. So 7/8 − 3/8 = 4/8.',
        pictures: [{ kind: 'bars', bars: [{ parts: 8, shaded: 4, label: '4/8' }] }, { kind: 'eq', text: '7/8 − 3/8 = 4/8' }] },
      { title: 'One thing not to do', text: "Don't take away the bottom numbers. The slices are still eighths after you eat some.",
        pictures: [{ kind: 'cards', wrong: '7/8 − 3/8 = 4/0', right: '7/8 − 3/8 = 4/8' }] },
    ],
    turn: {
      text: 'What is 7/8 − 2/8?',
      picture: { kind: 'bars', bars: [{ parts: 8, shaded: 7, label: '7/8' }] },
      answer: { frac: [5, 8] }, steps: ['Both are eighths, so the pieces are the same size.', 'Take away the pieces: 7 − 2 = 5. Keep the bottom number 8.', 'So 7/8 − 2/8 = 5/8.'],
      prompt: 'The pieces are the same size. Take away pieces and keep the bottom number.',
      hint1: 'Are the pieces the same size? How many pieces do you take away?',
      hint2: 'Start with 7 pieces and take away 2. The pieces are still eighths.',
      twin: { text: 'What is 5/6 − 4/6?',
        picture: { kind: 'bars', bars: [{ parts: 6, shaded: 5, label: '5/6' }] },
        answer: { frac: [1, 6] }, steps: ['Both are sixths, so the pieces are the same size.', 'Take away the pieces: 5 − 4 = 1. Keep the bottom number 6.', 'So 5/6 − 4/6 = 1/6.'],
        hint1: 'Are the pieces the same size? How many pieces do you take away?',
        hint2: 'Start with 5 pieces and take away 4. The pieces are still sixths.' },
    },
    won: { text: 'You took away pieces and kept the piece size.', sticker: 'When the denominators match, you only take away the top numbers.' },
    twinWon: { text: 'You took 4 sixths away from 5/6 and got 1/6.', sticker: 'When the denominators match, you only take away the top numbers.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What is 4/5 − 1/5?',
        picture: { kind: 'bars', bars: [{ parts: 5, shaded: 4, label: '4/5' }] }, answer: { frac: [3, 5] },
        steps: ['Both are fifths, so the pieces are the same size.', 'Take away the pieces: 4 − 1 = 3. Keep the bottom number 5.', 'So 4/5 − 1/5 = 3/5.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is 9/10 − 6/10?',
        picture: { kind: 'bars', bars: [{ parts: 10, shaded: 9, label: '9/10' }] }, answer: { frac: [3, 10] },
        steps: ['Both are tenths, so the pieces are the same size.', 'Take away the pieces: 9 − 6 = 3. Keep the bottom number 10.', 'So 9/10 − 6/10 = 3/10.'] } },
      { why: 'Still "take away the pieces"', problem: { text: 'What is 11/12 − 4/12?',
        picture: { kind: 'bars', bars: [{ parts: 12, shaded: 11, label: '11/12' }] }, answer: { frac: [7, 12] },
        steps: ['Both are twelfths, so the pieces are the same size.', 'Take away the pieces: 11 − 4 = 7. Keep the bottom number 12.', 'So 11/12 − 4/12 = 7/12.'] } },
      { why: 'A little harder', problem: { text: 'What is 1 − 3/8?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 8, label: '1' }] }, answer: { frac: [5, 8] },
        steps: ['1 whole cut into eighths is 8/8.', 'Take away the pieces: 8 − 3 = 5. Keep the bottom number 8.', 'So 1 − 3/8 = 5/8.'] } },
      { why: 'Same math in a story', problem: { text: 'A jug holds 6/8 of a gallon of juice. Sam pours out 3/8 of a gallon. How much juice is left in the jug?',
        picture: { kind: 'bars', bars: [{ parts: 8, shaded: 6, label: '6/8' }] }, answer: { frac: [3, 8] },
        steps: ['Both are eighths of a gallon, so the pieces are the same size.', 'Take away the pieces: 6 − 3 = 3. Keep the bottom number 8.', 'So 6/8 − 3/8 = 3/8 of a gallon.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m4-t7', title: 'Mixed numbers and fractions', skill: 'Change between wholes-and-a-fraction and a fraction bigger than 1',
    bigIdea: 'Every whole is made of pieces. Count the pieces in the wholes, then add the extra pieces.',
    screens: [
      { title: 'Pizzas on the table', text: 'There are 2 whole pizzas and 3/4 of another pizza. Each pizza is cut into 4 slices. How many slices is that?',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }, { parts: 4, shaded: 4 }, { parts: 4, shaded: 3 }] }] },
      { title: 'Two ways to say it', text: 'You can say "2 pizzas and 3/4". Or you can count every slice. Both are the same food, but the numbers look different.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }, { parts: 4, shaded: 4 }, { parts: 4, shaded: 3 }] }] },
      { title: 'The big idea', text: 'Every whole is made of pieces. Count the pieces in the wholes, then add the extra pieces.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }, { parts: 4, shaded: 4 }, { parts: 4, shaded: 3 }] }] },
      { title: 'Count the whole pizzas', text: 'Each whole pizza is 4 slices, or 4/4. 2 whole pizzas is 4 + 4 = 8 slices.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }, { parts: 4, shaded: 4 }, { parts: 4, shaded: 0 }], motion: true }] },
      { title: 'Add the extra slices', text: 'There are 3 more slices. 8 + 3 = 11 slices.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }, { parts: 4, shaded: 4 }, { parts: 4, shaded: 3 }], motion: true }] },
      { title: 'Write it both ways', text: 'Each slice is 1/4, so 11 slices is 11/4. 2 3/4 and 11/4 are the same amount.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }, { parts: 4, shaded: 4 }, { parts: 4, shaded: 3 }] },
          { kind: 'eq', text: '2 3/4 = 11/4', lines: ['4 + 4 + 3 = 11 fourths'] }] },
      { title: 'One thing not to do', text: "Don't just add the 2 and the 3. The 2 counts whole pizzas, and every whole pizza has 4 slices.",
        pictures: [{ kind: 'cards', wrong: '2 3/4 = 5/4', right: '2 3/4 = 11/4' }] },
    ],
    turn: {
      text: 'Write 2 1/4 as fourths. 2 1/4 = ?/4. What is the missing top number?',
      picture: { kind: 'bars', bars: [{ parts: 4, shaded: 4 }, { parts: 4, shaded: 4 }, { parts: 4, shaded: 1 }] },
      answer: 9, steps: ['Each whole is 4/4. 2 wholes is 4 + 4 = 8 fourths.', 'Add the extra 1 fourth: 8 + 1.', 'So 2 1/4 = 9/4. The missing number is 9.'],
      prompt: 'Count the fourths in the wholes. Then add the extra fourth.',
      hint1: 'How many fourths are in 1 whole? How many in 2 wholes?',
      hint2: 'Each whole is 4 fourths. Count the fourths in 2 wholes, then add the 1 extra fourth.',
      twin: { text: 'Write 1 2/3 as thirds. 1 2/3 = ?/3. What is the missing top number?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 3 }, { parts: 3, shaded: 2 }] },
        answer: 5, steps: ['1 whole is 3/3, which is 3 thirds.', 'Add the extra 2 thirds: 3 + 2.', 'So 1 2/3 = 5/3. The missing number is 5.'],
        hint1: 'How many thirds are in 1 whole?',
        hint2: 'Count the thirds in the whole, then add the extra thirds.' },
    },
    won: { text: 'You counted the pieces in the wholes and added the extra pieces.', sticker: 'Wholes with a fraction is a mixed number. A fraction with a top bigger than its bottom is an improper fraction.' },
    twinWon: { text: 'You counted the thirds in 1 2/3 and found 5/3.', sticker: 'Wholes with a fraction is a mixed number. A fraction with a top bigger than its bottom is an improper fraction.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '1 3/4 = ?/4. What is the missing top number?',
        picture: { kind: 'bars', bars: [{ parts: 4, shaded: 4 }, { parts: 4, shaded: 3 }] }, answer: 7,
        steps: ['1 whole is 4 fourths.', 'Add the extra 3 fourths: 4 + 3.', 'So 1 3/4 = 7/4. The missing number is 7.'] } },
      { why: 'Same idea, new numbers', problem: { text: '2 2/3 = ?/3. What is the missing top number?',
        picture: { kind: 'bars', bars: [{ parts: 3, shaded: 3 }, { parts: 3, shaded: 3 }, { parts: 3, shaded: 2 }] }, answer: 8,
        steps: ['Each whole is 3 thirds. 2 wholes is 3 + 3 = 6 thirds.', 'Add the extra 2 thirds: 6 + 2.', 'So 2 2/3 = 8/3. The missing number is 8.'] } },
      { why: 'Still "count the pieces"', problem: { text: '7/3 = ? 1/3. How many wholes are in 7/3?',
        picture: { kind: 'eq', text: '7/3 = ? 1/3' }, answer: 2,
        steps: ['Each whole is 3 thirds.', '7 thirds is 3 + 3 + 1: two wholes, with 1 third left over.', 'So 7/3 = 2 1/3. There are 2 wholes.'] } },
      { why: 'A little harder', problem: { text: '4 3/5 = ?/5. What is the missing top number?',
        picture: { kind: 'eq', text: '4 3/5 = ?/5' }, answer: 23,
        steps: ['Each whole is 5 fifths. 4 wholes is 4 × 5 = 20 fifths.', 'Add the extra 3 fifths: 20 + 3.', 'So 4 3/5 = 23/5. The missing number is 23.'] } },
      { why: 'Same math in a story', problem: { text: 'A baker has 2 whole pies and 5/6 of another pie. Each pie is cut into 6 slices. How many slices does she have?',
        picture: { kind: 'eq', text: '2 5/6 = ?/6' }, answer: 17,
        steps: ['Each pie is 6 slices. 2 pies is 6 + 6 = 12 slices.', 'Add the 5 extra slices: 12 + 5.', 'So 2 5/6 = 17/6. She has 17 slices.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m4-t8', title: 'Add mixed numbers', skill: 'Add wholes-and-fractions with the same bottom number',
    bigIdea: 'Add the wholes. Add the pieces. Then put them together.',
    screens: [
      { title: 'Flour for baking', text: 'You use 1 1/4 cups of flour for bread and 1 2/4 cups for pancakes. How much flour do you use in all?',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }, { parts: 4, shaded: 1 }, { parts: 4, shaded: 0, shade2: 4 }, { parts: 4, shaded: 0, shade2: 2 }] }] },
      { title: 'So many numbers', text: 'Each amount has wholes and pieces. If you mix them all up, it gets confusing fast.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }, { parts: 4, shaded: 1 }, { parts: 4, shaded: 0, shade2: 4 }, { parts: 4, shaded: 0, shade2: 2 }] }] },
      { title: 'The big idea', text: 'Add the wholes. Add the pieces. Then put them together.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }, { parts: 4, shaded: 0, shade2: 4 }, { parts: 4, shaded: 1, shade2: 2 }] }] },
      { title: 'Add the wholes', text: '1 whole cup and 1 whole cup make 2 whole cups.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }, { parts: 4, shaded: 0, shade2: 4 }], motion: true }] },
      { title: 'Add the pieces', text: '1/4 and 2/4 are the same size pieces. 1 piece and 2 pieces make 3/4.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 1, shade2: 2 }], motion: true }] },
      { title: 'Put them together', text: '2 wholes and 3/4 is 2 3/4. So 1 1/4 + 1 2/4 = 2 3/4 cups.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 4 }, { parts: 4, shaded: 0, shade2: 4 }, { parts: 4, shaded: 1, shade2: 2 }] },
          { kind: 'eq', text: '1 1/4 + 1 2/4 = 2 3/4', lines: ['wholes: 1 + 1 = 2', 'pieces: 1/4 + 2/4 = 3/4'] }] },
      { title: 'One thing not to do', text: "Don't add the bottom numbers of the pieces. They are still fourths, just like before.",
        pictures: [{ kind: 'cards', wrong: '1 1/4 + 1 2/4 = 2 3/8', right: '1 1/4 + 1 2/4 = 2 3/4' }] },
    ],
    turn: {
      text: 'What is 2 1/4 + 1 2/4?',
      picture: { kind: 'eq', text: '2 1/4 + 1 2/4 = ?' },
      answer: { frac: [3, 4], whole: 3 }, steps: ['Add the wholes: 2 + 1 = 3.', 'Add the pieces: 1/4 + 2/4 = 3/4.', 'So 2 1/4 + 1 2/4 = 3 3/4.'],
      prompt: 'Add the wholes. Add the pieces. Then put them together.',
      hint1: 'Add the wholes first. Then add the pieces.',
      hint2: 'The wholes are 2 and 1. The pieces are 1/4 and 2/4. Keep the pieces as fourths.',
      twin: { text: 'What is 1 2/6 + 2 3/6?',
        picture: { kind: 'eq', text: '1 2/6 + 2 3/6 = ?' },
        answer: { frac: [5, 6], whole: 3 }, steps: ['Add the wholes: 1 + 2 = 3.', 'Add the pieces: 2/6 + 3/6 = 5/6.', 'So 1 2/6 + 2 3/6 = 3 5/6.'],
        hint1: 'Add the wholes first. Then add the pieces.',
        hint2: 'The wholes are 1 and 2. The pieces are 2/6 and 3/6. Keep the pieces as sixths.' },
    },
    won: { text: 'You added the wholes, added the pieces, and put them together.', sticker: 'A whole number with a fraction is a mixed number. Add the wholes and the fractions.' },
    twinWon: { text: 'You added the wholes and the sixths to get 3 5/6.', sticker: 'A whole number with a fraction is a mixed number. Add the wholes and the fractions.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What is 1 1/5 + 2 3/5?',
        picture: { kind: 'eq', text: '1 1/5 + 2 3/5 = ?' }, answer: { frac: [4, 5], whole: 3 },
        steps: ['Add the wholes: 1 + 2 = 3.', 'Add the pieces: 1/5 + 3/5 = 4/5.', 'So 1 1/5 + 2 3/5 = 3 4/5.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is 3 2/8 + 1 5/8?',
        picture: { kind: 'eq', text: '3 2/8 + 1 5/8 = ?' }, answer: { frac: [7, 8], whole: 4 },
        steps: ['Add the wholes: 3 + 1 = 4.', 'Add the pieces: 2/8 + 5/8 = 7/8.', 'So 3 2/8 + 1 5/8 = 4 7/8.'] } },
      { why: 'Still "wholes, then pieces"', problem: { text: 'What is 2 3/10 + 4 4/10?',
        picture: { kind: 'eq', text: '2 3/10 + 4 4/10 = ?' }, answer: { frac: [7, 10], whole: 6 },
        steps: ['Add the wholes: 2 + 4 = 6.', 'Add the pieces: 3/10 + 4/10 = 7/10.', 'So 2 3/10 + 4 4/10 = 6 7/10.'] } },
      { why: 'A little harder', problem: { text: 'What is 1 3/4 + 2 2/4?',
        picture: { kind: 'eq', text: '1 3/4 + 2 2/4 = ?' }, answer: { frac: [1, 4], whole: 4 },
        steps: ['Add the wholes: 1 + 2 = 3.', 'Add the pieces: 3/4 + 2/4 = 5/4. That is 4/4, which is 1 whole, and 1/4 more.', 'Trade 4/4 for 1 whole: 3 + 1 = 4, with 1/4 left. So the answer is 4 1/4.'] } },
      { why: 'Same math in a story', problem: { text: 'Jo walks 1 2/8 miles to the park. Then Jo walks 2 3/8 miles home a longer way. How far does Jo walk in all?',
        picture: { kind: 'eq', text: '1 2/8 + 2 3/8 = ?' }, answer: { frac: [5, 8], whole: 3 },
        steps: ['Add the wholes: 1 + 2 = 3.', 'Add the pieces: 2/8 + 3/8 = 5/8.', 'So Jo walks 3 5/8 miles.'] } },
    ],
  },

  // ── Topic 9 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m4-t9', title: 'A whole number times a fraction', skill: 'Multiply a whole number by a fraction as copies of the same piece',
    bigIdea: 'A whole number times a fraction means that many copies of the same piece. Count the pieces, and keep the piece size.',
    screens: [
      { title: 'Sandwiches for friends', text: 'Each friend gets 1/4 of a sandwich. There are 3 friends. How much sandwich is that in all?',
        pictures: [copies(3, 4)] },
      { title: 'Not 3 × 4', text: 'The 3 counts friends. The 1/4 is the size of each piece. 3 × 4 = 12 would be way more sandwich than you have.',
        pictures: [copies(3, 4)] },
      { title: 'The big idea', text: 'A whole number times a fraction means that many copies of the same piece. Count the pieces, and keep the piece size.',
        pictures: [copies(3, 4)] },
      { title: 'One copy for each friend', text: 'Each friend gets 1 piece. Each piece is 1/4. That is 3 copies of 1/4.',
        pictures: [{ ...copies(3, 4), motion: true } as Picture] },
      { title: 'Push the pieces together', text: 'Put the 3 pieces into one sandwich. They fill 3 of the 4 parts.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 3 }], motion: true }] },
      { title: 'Write it', text: '3 copies of 1/4 is 3/4. So 3 × 1/4 = 3/4.',
        pictures: [{ kind: 'bars', bars: [{ parts: 4, shaded: 3, label: '3/4' }] },
          { kind: 'eq', text: '3 × 1/4 = 3/4', lines: ['1/4 + 1/4 + 1/4 = 3/4'] }] },
      { title: 'One thing not to do', text: "Don't change the bottom to 12. The pieces are still fourths. Only the number of pieces grows.",
        pictures: [{ kind: 'cards', wrong: '3 × 1/4 = 3/12', right: '3 × 1/4 = 3/4' }] },
    ],
    turn: {
      text: 'What is 4 × 1/5?',
      picture: copies(4, 5),
      answer: { frac: [4, 5] }, steps: ['4 × 1/5 means 4 copies of 1/5.', 'Count the pieces: 4 pieces, and each one is a fifth.', 'So 4 × 1/5 = 4/5.'],
      prompt: 'Count the copies of the piece. Keep the piece size.',
      hint1: 'How many copies are there? What size is each piece?',
      hint2: 'Each piece is a fifth. Count the pieces, and keep the bottom number 5.',
      twin: { text: 'What is 3 × 1/6?',
        picture: copies(3, 6),
        answer: { frac: [3, 6] }, steps: ['3 × 1/6 means 3 copies of 1/6.', 'Count the pieces: 3 pieces, and each one is a sixth.', 'So 3 × 1/6 = 3/6.'],
        hint1: 'How many copies are there? What size is each piece?',
        hint2: 'Each piece is a sixth. Count the pieces, and keep the bottom number 6.' },
    },
    won: { text: 'You counted copies of the same piece and kept the piece size.', sticker: 'A fraction with a top of one is a unit fraction. Times a whole number counts copies of it.' },
    twinWon: { text: 'You counted 3 copies of 1/6 and got 3/6.', sticker: 'A fraction with a top of one is a unit fraction. Times a whole number counts copies of it.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What is 2 × 1/3?',
        picture: copies(2, 3), answer: { frac: [2, 3] },
        steps: ['2 × 1/3 means 2 copies of 1/3.', 'Count the pieces: 2 pieces, each a third.', 'So 2 × 1/3 = 2/3.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is 5 × 1/8?',
        picture: { kind: 'eq', text: '5 × 1/8 = ?' }, answer: { frac: [5, 8] },
        steps: ['5 × 1/8 means 5 copies of 1/8.', 'Count the pieces: 5 pieces, each an eighth.', 'So 5 × 1/8 = 5/8.'] } },
      { why: 'Still "copies of a piece"', problem: { text: 'What is 6 × 1/10?',
        picture: { kind: 'eq', text: '6 × 1/10 = ?' }, answer: { frac: [6, 10] },
        steps: ['6 × 1/10 means 6 copies of 1/10.', 'Count the pieces: 6 pieces, each a tenth.', 'So 6 × 1/10 = 6/10.'] } },
      { why: 'A little harder', problem: { text: 'What is 3 × 2/5?',
        picture: copies(3, 5, 2), answer: { frac: [6, 5] },
        steps: ['3 × 2/5 means 3 copies of 2/5.', 'Each copy is 2 fifths. Count the pieces: 2 + 2 + 2 = 6 fifths.', 'So 3 × 2/5 = 6/5.'] } },
      { why: 'Same math in a story', problem: { text: 'A recipe uses 2/3 of a cup of milk. You make the recipe 2 times. How much milk do you use?',
        picture: copies(2, 3, 2), answer: { frac: [4, 3] },
        steps: ['2 times 2/3 means 2 copies of 2/3.', 'Each copy is 2 thirds. Count the pieces: 2 + 2 = 4 thirds.', 'So 2 × 2/3 = 4/3 cups of milk.'] } },
    ],
  },
]
