/**
 * Grade 4 · Module 5 — Angle measurements and plane figures.
 * Written to docs/new-flow/AUTHORING.md. Topics 1 and 5–8 draw with `poly`; topics 2–4 with `angle`.
 */
import type { Lesson, Picture } from '../script'
import { attachChalk } from '../chalk'
import { G4M5_CHALK } from './chalk/g4m5'

type Pt = [number, number]

/** A triangle on a base of length L with angle a at the left corner and b at the right (so the third is 180 − a − b). */
const tri = (a: number, b: number, L = 6, dx = 0): Pt[] => {
  const ta = Math.tan((a * Math.PI) / 180), tb = Math.tan((b * Math.PI) / 180), x = (L * tb) / (ta + tb)
  const r = (v: number) => Math.round(v * 100) / 100
  return [[dx, 0], [dx + L, 0], [r(dx + x), r(x * ta)]]
}

/** A ray: a dot where it starts, an arrow where it goes on. */
const ray = (a: Pt, b: Pt, label?: string) => [{ a, b: a, dots: true }, { a, b, arrow: 'end' as const, label }]
/** A line: arrows at both ends. */
const line = (a: Pt, b: Pt, label?: string) => ({ a, b, arrow: 'both' as const, label })
/** A square-corner mark where two lines cross at v (a and b sit a little way along each line). */
const square = (a: Pt, v: Pt, b: Pt) => ({ pts: [a, v, b], open: true, right: [1] })

const ENDS = ['line', 'ray', 'line segment']
const OPEN = ['acute', 'right', 'obtuse']
const PAIR = ['parallel', 'perpendicular', 'neither']
const TRI = ['acute triangle', 'right triangle', 'obtuse triangle']
const QUAD = ['rectangle', 'rhombus', 'parallelogram', 'trapezoid']
const YES_NO = ['yes', 'no']
const ALL4 = [0, 1, 2, 3]

const house: Pt[] = [[0, 0], [4, 0], [4, 3], [2, 5], [0, 3]]
const fold = (a: Pt, b: Pt) => ({ a, b, dashed: true, tone: 2 as const })
const onProtractor = (deg: number): Picture => ({ kind: 'angle', deg, protractor: true })

export const G4M5: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m5-t1', title: 'Points, lines and rays', skill: 'Tell a line, a ray and a line segment apart by their ends',
    bigIdea: 'Look at the ends. A dot means it stops there. An arrow means it keeps going forever.',
    screens: [
      { title: 'Straight paths', text: 'A piece of string stops at both ends. A flashlight beam starts at the flashlight and shines on and on. How do we draw each one?',
        pictures: [{ kind: 'poly', shapes: [], segs: [{ a: [0, 2], b: [5, 2], dots: true, label: 'string' }, ...ray([0, 0], [6, 0], 'flashlight beam')] }] },
      { title: 'The middle looks the same', text: 'Both of those paths are straight. If you cover up the ends with your thumb, the middles look exactly the same. So the difference is not in the middle. It is at the ends.',
        beats: [
          { say: 'Both of those paths are straight.', pic: 0 },
          { say: 'If you cover up the ends with your thumb, the middles look exactly the same.' },
          { say: 'So the difference is not in the middle. It is at the ends.', write: 'the ends tell you the name' },
        ],
        pictures: [{ kind: 'poly', shapes: [], segs: [{ a: [0, 2], b: [5, 2] }, { a: [0, 0], b: [6, 0] }] }] },
      { title: 'The big idea', text: 'Look at the ends. A dot means it stops there. An arrow means it keeps going forever.',
        beats: [
          { say: 'Look at the ends.', pic: 0 },
          { say: 'A dot means it stops there.' },
          { say: 'An arrow means it keeps going forever.' },
        ],
        pictures: [{ kind: 'poly', shapes: [], segs: [{ a: [0, 4], b: [5, 4], dots: true }, ...ray([0, 2], [5, 2]), line([0, 0], [5, 0])] }] },
      { title: 'A dot means stop', text: 'A dot marks one exact spot, and we call that a point. Now watch what happens when I put a dot on both ends of a straight path. It stops right there, at both ends. That one has a name: a line segment.',
        beats: [
          { say: 'A dot marks one exact spot, and we call that a point.', pic: 0 },
          { say: 'Now watch what happens when I put a dot on both ends of a straight path.' },
          { say: 'It stops right there, at both ends. That one has a name: a line segment.', write: 'dot + dot = line segment' },
        ],
        pictures: [{ kind: 'poly', motion: true, shapes: [], segs: [{ a: [0, 0], b: [5, 0] }, { a: [0, 0], b: [5, 0], dots: true }] }] },
      { title: 'An arrow means keep going', text: 'An arrow is different. An arrow means the path never stops, it just keeps on going. So here is a dot at one end and an arrow at the other. It starts at the dot and runs on forever. We call that one a ray.',
        beats: [
          { say: 'An arrow is different. An arrow means the path never stops, it just keeps on going.', pic: 0 },
          { say: 'So here is a dot at one end and an arrow at the other.' },
          { say: 'It starts at the dot and runs on forever. We call that one a ray.', write: 'dot + arrow = ray' },
        ],
        pictures: [{ kind: 'poly', motion: true, shapes: [], segs: ray([0, 0], [5, 0]) }] },
      { title: 'Arrows at both ends', text: 'Now put an arrow at both ends. Nothing stops it either way, so it goes on forever in both directions. That is a line. Here are all three together.',
        beats: [
          { say: 'Now put an arrow at both ends.', pic: 0 },
          { say: 'Nothing stops it either way, so it goes on forever in both directions. That is a line.' },
          { say: 'Here are all three together.', pic: 1 },
        ],
        pictures: [{ kind: 'poly', shapes: [], segs: [line([0, 0], [5, 0])] },
          { kind: 'table', head: ['the ends', 'the name'], rows: [['dot and dot', 'line segment'], ['dot and arrow', 'ray'], ['arrow and arrow', 'line']] }] },
      { title: 'One thing not to do', text: "Here is the trap. Don't go by how long the path looks. A short path with arrows at both ends still goes on forever. And a long path with dots on the ends still stops.",
        beats: [
          { say: "Here is the trap. Don't go by how long the path looks." },
          { say: 'A short path with arrows at both ends still goes on forever.', pic: 0 },
          { say: 'And a long path with dots on the ends still stops.', pic: 1 },
        ],
        pictures: [{ kind: 'poly', shapes: [], segs: [line([0, 2], [2, 2]), { a: [0, 0], b: [7, 0], dots: true }] },
          { kind: 'cards', wrong: 'long means line', right: 'arrows at both ends mean line' }] },
    ],
    turn: {
      text: 'Look at the ends. What is this?',
      picture: { kind: 'poly', shapes: [], segs: ray([0, 0], [6, 0]) },
      answer: { choices: ENDS, correct: 1 },
      steps: ['One end has a dot, so it starts there.', 'The other end has an arrow, so it keeps going forever.', 'So it is a ray.'],
      prompt: 'Look at both ends. A dot stops. An arrow keeps going.',
      hint1: 'What is at the left end? What is at the other end?',
      hint2: 'One end stops at a dot. Does the other end stop too?',
      twin: { text: 'Look at the ends. What is this?',
        picture: { kind: 'poly', shapes: [], segs: [line([0, 0], [5, 3])] },
        answer: { choices: ENDS, correct: 0 },
        steps: ['Both ends have arrows.', 'It goes on forever both ways.', 'So it is a line.'],
        hint1: 'Look at both ends. Is there a dot anywhere?', hint2: 'An arrow means it keeps going. How many ends keep going?' },
    },
    won: { text: 'You looked at the ends to name it.', sticker: 'A path that starts at a point and goes on forever one way is a ray.' },
    twinWon: { text: 'You saw arrows at both ends, so it goes on forever both ways.', sticker: 'A line goes on forever both ways. A ray goes on forever one way.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Look at the ends. What is this?',
        picture: { kind: 'poly', shapes: [], segs: [{ a: [0, 0], b: [6, 0], dots: true }] }, answer: { choices: ENDS, correct: 2 },
        steps: ['Both ends have a dot.', 'So it stops at both ends.', 'So it is a line segment.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Look at the ends. What is this?',
        picture: { kind: 'poly', shapes: [], segs: ray([0, 0], [0, 5]) }, answer: { choices: ENDS, correct: 1 },
        steps: ['The bottom end has a dot, so it starts there.', 'The top end has an arrow, so it keeps going up forever.', 'So it is a ray.'] } },
      { why: 'Still "look at the ends"', problem: { text: 'Look at the ends. What is this?',
        picture: { kind: 'poly', shapes: [], segs: ray([5, 3], [0, 0]) }, answer: { choices: ENDS, correct: 1 },
        steps: ['The dot is on the right, so it starts there.', 'The arrow is on the left, so it keeps going that way forever.', 'So it is a ray.'] } },
      { why: 'A little harder', problem: { text: 'Each path starts at the middle dot. How many rays start at this dot?',
        picture: { kind: 'poly', shapes: [], segs: [...ray([0, 0], [4, 0]), { a: [0, 0], b: [2, 3], arrow: 'end' }, { a: [0, 0], b: [-3, 2], arrow: 'end' }] },
        answer: 3,
        steps: ['Every path starts at the same dot.', 'Every path ends in an arrow, so each one is a ray.', 'Count the arrows: 3.'] } },
      { why: 'Same math in a story', problem: { text: 'A toy train track starts at one station and stops at the other. Its drawing is below. What is it?',
        picture: { kind: 'poly', shapes: [], segs: [{ a: [0, 0], b: [6, 0], dots: true }], labels: [{ at: [0, 1], text: 'Station A' }, { at: [6, 1], text: 'Station B' }] },
        answer: { choices: ENDS, correct: 2 },
        steps: ['The track starts at a dot at Station A.', 'It stops at a dot at Station B, so it stops at both ends.', 'So it is a line segment.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m5-t2', title: 'Right, acute or obtuse?', skill: 'Sort an angle by comparing it with a right angle',
    bigIdea: 'Compare the angle with a square corner: narrower (acute), the same (right) or wider (obtuse).',
    screens: [
      { title: 'Open the door', text: 'Two rays that start at the same point make an angle, like a door and its wall. A door can open a little or a lot. How can we sort angles?',
        pictures: [{ kind: 'angle', deg: 40 }] },
      { title: 'Long rays do not matter', text: 'Careful with this one. Long rays do not make a big angle. Two rays can run a long way and still barely open at all. What counts is how far apart the two rays open.',
        beats: [
          { say: 'Careful with this one. Long rays do not make a big angle.', pic: 0 },
          { say: 'Two rays can run a long way and still barely open at all.' },
          { say: 'What counts is how far apart the two rays open.', write: 'the opening, not the length' },
        ],
        pictures: [{ kind: 'angle', deg: 40 }] },
      { title: 'The big idea', text: 'Compare the angle with a square corner: narrower (acute), the same (right) or wider (obtuse).',
        beats: [
          { say: 'Compare the angle with a square corner: narrower (acute), the same (right) or wider (obtuse).', pic: 0 },
        ],
        pictures: [{ kind: 'angle', deg: 90 }] },
      { title: 'A square corner', text: 'Start with the one you already know. The corner of a book, the corner of a door, the corner of this page: they are all the same square corner. In math we call it a right angle. That little square in the corner is how we mark it.',
        beats: [
          { say: 'Start with the one you already know.', pic: 0 },
          { say: 'The corner of a book, the corner of a door, the corner of this page: they are all the same square corner.' },
          { say: 'In math we call it a right angle. That little square in the corner is how we mark it.', write: 'square corner = right angle' },
        ],
        pictures: [{ kind: 'angle', deg: 90, motion: true }] },
      { title: 'Narrower', text: 'Now this one. Put a square corner next to it in your head. These rays open less than that, so the angle is narrow and sharp. A narrow angle like that is called acute.',
        beats: [
          { say: 'Now this one. Put a square corner next to it in your head.', pic: 0 },
          { say: 'These rays open less than that, so the angle is narrow and sharp.' },
          { say: 'A narrow angle like that is called acute.', write: 'narrower than square → acute' },
        ],
        pictures: [{ kind: 'angle', deg: 50 }] },
      { title: 'Wider', text: 'And this one goes the other way. The rays open more than a square corner. Look, there is a whole square corner in there, and then some extra on top. A wide angle like that is called obtuse.',
        beats: [
          { say: 'And this one goes the other way. The rays open more than a square corner.', pic: 0 },
          { say: 'Look, there is a whole square corner in there, and then some extra on top.' },
          { say: 'A wide angle like that is called obtuse.', write: 'wider than square → obtuse' },
        ],
        pictures: [{ kind: 'angle', deg: 130, parts: [90, 40], partLabels: [null, null], motion: true }] },
      { title: 'One thing not to do', text: "Here is the mix-up to watch for. Don't call an angle wide just because its rays are long. Look at the opening, never the length of the rays.",
        beats: [
          { say: 'Here is the mix-up to watch for.' },
          { say: "Don't call an angle wide just because its rays are long.", pic: 0 },
          { say: 'Look at the opening, never the length of the rays.' },
        ],
        pictures: [{ kind: 'cards', wrong: 'long rays, so obtuse', right: 'wide opening, so obtuse' }] },
    ],
    turn: {
      text: 'Is this angle acute, right or obtuse?',
      picture: { kind: 'angle', deg: 120 },
      answer: { choices: OPEN, correct: 2 },
      steps: ['Picture a square corner at the point.', 'The rays open wider than a square corner.', 'So the angle is obtuse.'],
      prompt: 'Picture a square corner at the point. Is the angle narrower, the same or wider?',
      hint1: 'Picture the corner of a book at the point. Does the angle open more or less?',
      hint2: 'Is the opening narrower than a square corner, or wider?',
      twin: { text: 'Is this angle acute, right or obtuse?',
        picture: { kind: 'angle', deg: 35 },
        answer: { choices: OPEN, correct: 0 },
        steps: ['Picture a square corner at the point.', 'The rays open less than a square corner.', 'So the angle is acute.'],
        hint1: 'Compare it with the corner of a book.', hint2: 'Does the angle open less than a square corner, or more?' },
    },
    won: { text: 'You compared the angle with a square corner.', sticker: 'An angle less than a right angle is acute. An angle more than a right angle is obtuse.' },
    twinWon: { text: 'You saw the rays open less than a square corner.', sticker: 'An angle less than a right angle is acute. An angle more than a right angle is obtuse.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Is this angle acute, right or obtuse?',
        picture: { kind: 'angle', deg: 150 }, answer: { choices: OPEN, correct: 2 },
        steps: ['Picture a square corner at the point.', 'The rays open much wider than a square corner.', 'So the angle is obtuse.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Is this angle acute, right or obtuse?',
        picture: { kind: 'angle', deg: 60 }, answer: { choices: OPEN, correct: 0 },
        steps: ['Picture a square corner at the point.', 'The rays open less than a square corner.', 'So the angle is acute.'] } },
      { why: 'Still "compare with a square corner"', problem: { text: 'Is this angle acute, right or obtuse?',
        picture: { kind: 'angle', deg: 90 }, answer: { choices: OPEN, correct: 1 },
        steps: ['The little square in the corner shows a square corner.', 'The angle is exactly the same as a square corner.', 'So the angle is right.'] } },
      { why: 'A little harder', problem: { text: 'This one is close. Is this angle acute, right or obtuse?',
        picture: { kind: 'angle', deg: 80 }, answer: { choices: OPEN, correct: 0 },
        steps: ['There is no little square, so it is not a square corner.', 'The rays open a little less than a square corner.', 'So the angle is acute.'] } },
      { why: 'Same math in a story', problem: { text: 'Mia opens her laptop this far. Is the angle between the screen and the keyboard acute, right or obtuse?',
        picture: { kind: 'angle', deg: 110 }, answer: { choices: OPEN, correct: 2 },
        steps: ['Picture a square corner where the screen meets the keyboard.', 'The screen leans back past a square corner.', 'So the angle is obtuse.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m5-t3', title: 'Measure an angle in degrees', skill: 'Read an angle on a protractor to the nearest 10 degrees',
    bigIdea: 'Put the middle of the protractor on the point and 0 on one ray. Count up to the other ray.',
    screens: [
      { title: 'How far does it open?', text: 'A ramp for a toy car tilts up from the floor. It is narrower than a square corner. But exactly how far open is it?',
        pictures: [{ kind: 'angle', deg: 40 }] },
      { title: 'Narrow is not exact', text: "Saying narrow doesn't tell us exactly how far it opens. Look at this one. And now this one. Both are narrow, and they are nowhere near the same. So we need a number, not a word.",
        beats: [
          { say: "Saying narrow doesn't tell us exactly how far it opens. Look at this one.", pic: 0 },
          { say: 'And now this one.', pic: 1 },
          { say: 'Both are narrow, and they are nowhere near the same. So we need a number, not a word.', write: 'a number, not a word' },
        ],
        pictures: [{ kind: 'angle', deg: 20 }, { kind: 'angle', deg: 70 }] },
      { title: 'The big idea', text: 'Put the middle of the protractor on the point and 0 on one ray. Count up to the other ray.',
        beats: [
          { say: 'Put the middle of the protractor on the point and 0 on one ray.', pic: 0 },
          { say: 'Count up to the other ray.' },
        ],
        pictures: [onProtractor(40)] },
      { title: 'Line up the protractor', text: 'This tool is a protractor. It is a half circle, and its edge is marked in small equal steps called degrees. Put the middle of it right on the point where the rays meet. Then turn it until the bottom ray lies along the 0.',
        beats: [
          { say: 'This tool is a protractor. It is a half circle, and its edge is marked in small equal steps called degrees.', pic: 0 },
          { say: 'Put the middle of it right on the point where the rays meet.' },
          { say: 'Then turn it until the bottom ray lies along the 0.', write: 'middle on the point, 0 on a ray' },
        ],
        pictures: [onProtractor(40)] },
      { title: 'Count up from 0', text: 'Now we count. Each small mark on the edge is 10 more. Start at 0 and count up to the big number 30. Then one more small mark past it, and that lands us on 40.',
        beats: [
          { say: 'Now we count. Each small mark on the edge is 10 more.', pic: 0 },
          { say: 'Start at 0 and count up to the big number 30.' },
          { say: 'Then one more small mark past it, and that lands us on 40.' },
        ],
        pictures: [{ kind: 'angle', deg: 40, protractor: true, parts: [30, 10], partLabels: ['30', '+10'], motion: true }] },
      { title: 'Say how big', text: 'So where does the other ray land? Right on 40. That means the angle measures 40 degrees, and we write it with a little circle up high.',
        beats: [
          { say: 'So where does the other ray land? Right on 40.', pic: 0 },
          { say: 'That means the angle measures 40 degrees, and we write it with a little circle up high.', pic: 1 },
        ],
        pictures: [onProtractor(40), { kind: 'eq', text: '40°' }] },
      { title: 'One thing not to do', text: "Here is where people slip. Don't count from the far end of the protractor. There are two sets of numbers on it, and it is easy to grab the wrong one. Always start at the 0 that sits on your bottom ray and count up from there.",
        beats: [
          { say: 'Here is where people slip.' },
          { say: "Don't count from the far end of the protractor. There are two sets of numbers on it, and it is easy to grab the wrong one.", pic: 0 },
          { say: 'Always start at the 0 that sits on your bottom ray and count up from there.', write: 'start at the 0 on your ray' },
        ],
        pictures: [{ kind: 'cards', wrong: '140°', right: '40°' }] },
    ],
    turn: {
      text: 'The angle is drawn on a protractor. How many degrees is it?',
      picture: onProtractor(70),
      answer: 70, steps: ['The bottom ray sits on 0.', 'The other ray is one small mark past the 60.', '60 + 10 = 70, so the angle is 70°.'],
      prompt: 'Start at the 0 on the bottom ray. Count up to the other ray.',
      hint1: 'Start at the 0 on the bottom ray. Which big number is the other ray closest to?',
      hint2: 'Each small mark is 10 more. Count on from 60.',
      twin: { text: 'The angle is drawn on a protractor. How many degrees is it?',
        picture: onProtractor(110),
        answer: 110, steps: ['The bottom ray sits on 0.', 'The other ray is two small marks past the 90.', '90 + 20 = 110, so the angle is 110°.'],
        hint1: 'Start at the 0 on the bottom ray and count up.', hint2: 'Find the 90. Each small mark after it is 10 more.' },
    },
    won: { text: 'You started at 0 and counted up to the other ray.', sticker: 'Angles are measured in degrees (°). A right angle is 90°.' },
    twinWon: { text: 'You started at 0 and read 110° on the protractor.', sticker: 'Angles are measured in degrees (°).' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'The angle is drawn on a protractor. How many degrees is it?',
        picture: onProtractor(40), answer: 40,
        steps: ['The bottom ray sits on 0.', 'The other ray is one small mark past the 30.', '30 + 10 = 40, so the angle is 40°.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'The angle is drawn on a protractor. How many degrees is it?',
        picture: onProtractor(140), answer: 140,
        steps: ['The bottom ray sits on 0.', 'The other ray is two small marks past the 120.', '120 + 20 = 140, so the angle is 140°.'] } },
      { why: 'Still "start at 0 and count up"', problem: { text: 'The angle is drawn on a protractor. How many degrees is it?',
        picture: onProtractor(20), answer: 20,
        steps: ['Start at the 0 on the bottom ray.', 'Count the small marks up to the other ray: 10, 20.', 'So the angle is 20°.'] } },
      { why: 'A little harder', problem: { text: 'The angle is drawn on a protractor. How many degrees is it?',
        picture: onProtractor(160), answer: 160,
        steps: ['Start at the 0 on the bottom ray, not at the far end.', 'The other ray is one small mark past the 150.', '150 + 10 = 160, so the angle is 160°.'] } },
      { why: 'Same math in a story', problem: { text: 'A drawbridge opens this far. How many degrees is it open?',
        picture: onProtractor(50), answer: 50,
        steps: ['The road sits on 0.', 'The bridge is two small marks past the 30.', '30 + 20 = 50, so the bridge is open 50°.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m5-t4', title: 'Angles add up', skill: 'Find a missing angle when the parts add up to the whole',
    bigIdea: 'When an angle is split into parts, the parts add up to the whole angle.',
    screens: [
      { title: 'Two slices', text: 'A slice of pie is cut into two smaller slices. The two small slices together make the whole slice. Angles work the same way.',
        pictures: [{ kind: 'angle', deg: 90, parts: [40, 50], partLabels: [null, null] }] },
      { title: 'No need to measure again', text: 'You could go get the protractor and measure every single part. But hold on. If you already know the whole angle, and you know one of the parts, you do not need to measure anything. You can work the missing part out instead.',
        beats: [
          { say: 'You could go get the protractor and measure every single part.', pic: 0 },
          { say: 'But hold on. If you already know the whole angle, and you know one of the parts, you do not need to measure anything.' },
          { say: 'You can work the missing part out instead.', write: 'know the whole and one part → work it out' },
        ],
        pictures: [{ kind: 'angle', deg: 90, parts: [40, 50], partLabels: ['40°', '?'] }] },
      { title: 'The big idea', text: 'When an angle is split into parts, the parts add up to the whole angle.',
        beats: [
          { say: 'When an angle is split into parts, the parts add up to the whole angle.', pic: 0 },
        ],
        pictures: [{ kind: 'angle', deg: 90, parts: [40, 50] }] },
      { title: 'Parts side by side', text: 'Watch the two parts go together. The 40 degree part, then the 50 degree part right next to it. They fill the whole square corner, with no gap left over and nothing sticking out.',
        beats: [
          { say: 'Watch the two parts go together.', pic: 0 },
          { say: 'The 40 degree part, then the 50 degree part right next to it.' },
          { say: 'They fill the whole square corner, with no gap left over and nothing sticking out.' },
        ],
        pictures: [{ kind: 'angle', deg: 90, parts: [40, 50], motion: true }] },
      { title: 'Add the parts', text: 'So to find the whole, we add the parts. 40 and 50 together make 90. And 90 degrees is a right angle, which is exactly what we can see.',
        beats: [
          { say: 'So to find the whole, we add the parts.', pic: 0, write: 'parts added → the whole' },
          { say: '40 and 50 together make 90.', pic: 1 },
          { say: 'And 90 degrees is a right angle, which is exactly what we can see.' },
        ],
        pictures: [{ kind: 'angle', deg: 90, parts: [40, 50] }, { kind: 'eq', text: '40° + 50° = 90°' }] },
      { title: 'Find a missing part', text: 'Now turn it around. This time we know the whole is 90 degrees and one part is 40, and the other part is a question mark. The part is inside the whole, so we take it away. 90 take away 40 leaves 50, so the missing part is 50 degrees.',
        beats: [
          { say: 'Now turn it around.', pic: 0 },
          { say: 'This time we know the whole is 90 degrees and one part is 40, and the other part is a question mark.' },
          { say: 'The part is inside the whole, so we take it away.', write: 'missing part → take it off the whole' },
          { say: '90 take away 40 leaves 50, so the missing part is 50 degrees.', pic: 1 },
        ],
        pictures: [{ kind: 'angle', deg: 90, parts: [40, 50], partLabels: ['40°', '?'] }, { kind: 'eq', text: '90 − 40 = 50' }] },
      { title: 'One thing not to do', text: "Here is the one that trips people. Don't add the part onto the whole. The part is already sitting inside the whole, so adding makes the answer bigger than the whole angle. Take it away instead.",
        beats: [
          { say: 'Here is the one that trips people.' },
          { say: "Don't add the part onto the whole.", pic: 0 },
          { say: 'The part is already sitting inside the whole, so adding makes the answer bigger than the whole angle. Take it away instead.' },
        ],
        pictures: [{ kind: 'cards', wrong: '90 + 40 = 130', right: '90 − 40 = 50' }] },
    ],
    turn: {
      text: 'The whole angle is a right angle, 90°. One part is 30°. How many degrees is the other part?',
      picture: { kind: 'angle', deg: 90, parts: [30, 60], partLabels: ['30°', '?'] },
      answer: 60, steps: ['The two parts add up to the whole, 90°.', 'Take away the part you know: 90 − 30.', 'So the other part is 60°.'],
      prompt: 'The parts add up to the whole. Take away the part you know.',
      hint1: 'The parts add up to the whole. How big is the whole?',
      hint2: 'Start at 90 and take away 30.',
      twin: { text: 'The two parts make a straight line, 180°. One part is 110°. How many degrees is the other part?',
        picture: { kind: 'angle', deg: 180, parts: [110, 70], partLabels: ['110°', '?'] },
        answer: 70, steps: ['A straight line is 180°, and the two parts add up to it.', 'Take away the part you know: 180 − 110.', 'So the other part is 70°.'],
        hint1: 'What do the two parts add up to on a straight line?', hint2: 'Start at 180 and take away 110.' },
    },
    won: { text: 'You took the part you know away from the whole.', sticker: 'Angle measures are additive: the parts add up to the whole angle.' },
    twinWon: { text: 'You took 110° away from 180° to find the missing part.', sticker: 'Angle measures are additive. A straight angle is 180°.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'The whole angle is 90°. One part is 20°. How many degrees is the other part?',
        picture: { kind: 'angle', deg: 90, parts: [20, 70], partLabels: ['20°', '?'] }, answer: 70,
        steps: ['The two parts add up to 90°.', 'Take away the part you know: 90 − 20.', 'So the other part is 70°.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'The whole angle is 90°. One part is 55°. How many degrees is the other part?',
        picture: { kind: 'angle', deg: 90, parts: [55, 35], partLabels: ['55°', '?'] }, answer: 35,
        steps: ['The two parts add up to 90°.', 'Take away the part you know: 90 − 55.', 'So the other part is 35°.'] } },
      { why: 'Still "the parts add up"', problem: { text: 'Two angles sit side by side: 45° and 60°. How many degrees is the whole angle?',
        picture: { kind: 'angle', deg: 105, parts: [45, 60] }, answer: 105,
        steps: ['The parts add up to the whole.', 'Add them: 45 + 60.', 'So the whole angle is 105°.'] } },
      { why: 'A little harder', problem: { text: 'The two parts make a straight line, 180°. One part is 35°. How many degrees is the other part?',
        picture: { kind: 'angle', deg: 180, parts: [35, 145], partLabels: ['35°', '?'] }, answer: 145,
        steps: ['A straight line is 180°, and the two parts add up to it.', 'Take away the part you know: 180 − 35.', 'So the other part is 145°.'] } },
      { why: 'Same math in a story', problem: { text: 'A corner shelf fits in a 90° corner. A board splits it, and one part is 25°. How many degrees is the other part?',
        picture: { kind: 'angle', deg: 90, parts: [25, 65], partLabels: ['25°', '?'] }, answer: 65,
        steps: ['The two parts add up to the whole corner, 90°.', 'Take away the part you know: 90 − 25.', 'So the other part is 65°.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m5-t5', title: 'Parallel and perpendicular lines', skill: 'Tell parallel and perpendicular lines apart',
    bigIdea: "Lines with the same gap all the way are parallel, and lines that cross at a square corner are perpendicular.",
    screens: [
      { title: 'Rails and a plus sign', text: 'The two rails of a train track run side by side. The two lines of a plus sign cross. How are these pairs of lines different?',
        pictures: [{ kind: 'poly', shapes: [], segs: [line([0, 0], [5, 0]), line([0, 1.5], [5, 1.5]), line([7, 0.75], [10, 0.75]), line([8.5, -0.75], [8.5, 2.25])] }] },
      { title: "Cross or not", text: "The rails never cross. The plus sign does. So how do we name each pair? We check the gap, and the corner.",
        beats: [
          { say: "The rails never cross. The plus sign does.", pic: 0 },
          { say: "So how do we name each pair?" },
          { say: "We check the gap, and the corner." },
        ],
        pictures: [{ kind: 'poly', shapes: [], segs: [line([0, 0], [4, 2]), line([0, 2], [4, 0]), line([6, 1], [9, 1]), line([7.5, -0.5], [7.5, 2.5])] }] },
      { title: "The big idea", text: "Lines with the same gap all the way are parallel, and lines that cross at a square corner are perpendicular.",
        beats: [
          { say: "Lines with the same gap all the way are parallel, and lines that cross at a square corner are perpendicular.", pic: 0 },
        ],
        pictures: [{ kind: 'poly', shapes: [square([9.1, 0.75], [8.5, 0.75], [8.5, 1.35])],
          segs: [line([0, 0], [5, 0]), line([0, 1.5], [5, 1.5]), line([7, 0.75], [10, 0.75]), line([8.5, -0.75], [8.5, 2.25])] }] },
      { title: "The same gap all the way", text: "Start with the rails. The gap here, here and here is the same. So they never meet. They are parallel.",
        beats: [
          { say: "Start with the rails.", pic: 0 },
          { say: "The gap here, here and here is the same." },
          { say: "So they never meet." },
          { say: "They are parallel." },
        ],
        pictures: [{ kind: 'poly', motion: true, shapes: [], segs: [line([0, 0], [5, 2]), line([0, 1.5], [5, 3.5])] }] },
      { title: "Cross at a square corner", text: "Now the plus sign. The lines cross, and all 4 corners are square corners. We mark one with a small square. They are perpendicular.",
        beats: [
          { say: "Now the plus sign.", pic: 0 },
          { say: "The lines cross, and all 4 corners are square corners." },
          { say: "We mark one with a small square." },
          { say: "They are perpendicular." },
        ],
        pictures: [{ kind: 'poly', motion: true, shapes: [square([2.6, 2], [2, 2], [2, 2.6])], segs: [line([0, 2], [4, 2]), line([2, 0], [2, 4])] }] },
      { title: "Neither", text: "What about open scissors? They cross, so they are not parallel. The corners are not square, so they are not perpendicular. They are neither.",
        beats: [
          { say: "What about open scissors?", pic: 0 },
          { say: "They cross, so they are not parallel." },
          { say: "The corners are not square, so they are not perpendicular." },
          { say: "They are neither.", pic: 1 },
        ],
        pictures: [{ kind: 'poly', shapes: [], segs: [line([0, 0], [4, 2]), line([0, 2], [4, 0])] },
          { kind: 'table', head: ['the lines', 'the name'], rows: [['never meet', 'parallel'], ['cross at a square corner', 'perpendicular'], ['cross, not square', 'neither']] }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Not touching does NOT mean parallel. This gap gets smaller, so they meet farther on. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Not touching does NOT mean parallel.", pic: 0 },
          { say: "This gap gets smaller, so they meet farther on.", pic: 1 },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'poly', shapes: [], segs: [line([0, 0], [6, 1]), line([0, 3], [6, 2])] },
          { kind: 'cards', wrong: 'not touching, so parallel', right: 'same gap all the way, so parallel' }] },
    ],
    turn: {
      text: 'Are these lines parallel, perpendicular or neither?',
      picture: { kind: 'poly', shapes: [square([1.5, 1.5], [2, 2], [2.5, 1.5])], segs: [line([0, 0], [4, 4]), line([0, 4], [4, 0])] },
      answer: { choices: PAIR, correct: 1 },
      steps: ['The lines cross.', 'The little square shows they cross at a square corner.', 'So the lines are perpendicular.'],
      prompt: 'Do the lines meet? If they cross, is it at a square corner?',
      hint1: 'Do the lines ever meet?',
      hint2: 'Look where they cross. Do you see a little square?',
      twin: { text: 'Are these lines parallel, perpendicular or neither?',
        picture: { kind: 'poly', shapes: [], segs: [line([0, 0], [5, 2]), line([0, 2], [5, 4])] },
        answer: { choices: PAIR, correct: 0 },
        steps: ['The lines do not cross.', 'The gap between them is the same the whole way.', 'So the lines are parallel.'],
        hint1: 'Do the lines cross, or do they stay apart?', hint2: 'Check the gap at each end. Is it the same?' },
    },
    won: { text: 'You checked if the lines meet, and how they meet.', sticker: 'Lines that cross at a right angle are perpendicular.' },
    twinWon: { text: 'You saw the gap between the lines stays the same.', sticker: 'Lines that never meet and stay the same distance apart are parallel.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Are these lines parallel, perpendicular or neither?',
        picture: { kind: 'poly', shapes: [square([3.6, 2], [3, 2], [3, 2.6])], segs: [line([0, 2], [6, 2]), line([3, 0], [3, 4])] },
        answer: { choices: PAIR, correct: 1 },
        steps: ['The lines cross.', 'The little square shows a square corner.', 'So the lines are perpendicular.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Are these lines parallel, perpendicular or neither?',
        picture: { kind: 'poly', shapes: [], segs: [line([0, 0], [0, 5]), line([2, 0], [2, 5])] },
        answer: { choices: PAIR, correct: 0 },
        steps: ['The lines do not cross.', 'They stay the same distance apart from top to bottom.', 'So the lines are parallel.'] } },
      { why: 'Still "never meet, or a square corner"', problem: { text: 'Are these lines parallel, perpendicular or neither?',
        picture: { kind: 'poly', shapes: [], segs: [line([0, 0], [5, 2]), line([0, 2], [5, 0])] },
        answer: { choices: PAIR, correct: 2 },
        steps: ['The lines cross, so they are not parallel.', 'They cross like open scissors, not at a square corner.', 'So the answer is neither.'] } },
      { why: 'A little harder', problem: { text: 'These lines do not touch in the picture. Are they parallel, perpendicular or neither?',
        picture: { kind: 'poly', shapes: [], segs: [line([0, 0], [6, 1]), line([0, 3], [6, 2])] },
        answer: { choices: PAIR, correct: 2 },
        steps: ['The gap is wide on the left and smaller on the right, so they will meet farther along.', 'They would not meet at a square corner.', 'So the answer is neither.'] } },
      { why: 'Same math in a story', problem: { text: 'Two streets on a map cross like this. Are the streets parallel, perpendicular or neither?',
        picture: { kind: 'poly', shapes: [square([2.55, 2.3], [2, 2], [1.7, 2.55])], segs: [line([0, 0.9], [4, 3.1]), line([3.1, 0], [0.9, 4])] },
        answer: { choices: PAIR, correct: 1 },
        steps: ['The streets cross.', 'The little square shows they cross at a square corner.', 'So the streets are perpendicular.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m5-t6', title: 'Sort triangles', skill: 'Sort a triangle as acute, right or obtuse by its biggest angle',
    bigIdea: "Find the biggest angle: a square corner makes a right triangle, wider makes an obtuse triangle, and narrower makes an acute triangle.",
    screens: [
      { title: 'Triangles everywhere', text: 'A slice of pizza, a ramp and a tent are all triangles. Can we sort them into groups?',
        pictures: [{ kind: 'poly', shapes: [{ pts: tri(60, 55, 4, 0), tone: 1 }, { pts: tri(90, 50, 4, 5), tone: 2 }, { pts: tri(25, 35, 5, 10), tone: 3 }] }] },
      { title: "Counting won't sort them", text: "Count the sides. Every one has 3. Count the corners. 3 again. So what makes them different? The size of their angles.",
        beats: [
          { say: "Count the sides. Every one has 3.", pic: 0 },
          { say: "Count the corners. 3 again." },
          { say: "So what makes them different? The size of their angles." },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: tri(60, 55, 4, 0), tone: 1 }, { pts: tri(90, 50, 4, 5), tone: 2 }, { pts: tri(25, 35, 5, 10), tone: 3 }] }] },
      { title: "The big idea", text: "Find the biggest angle: a square corner makes a right triangle, wider makes an obtuse triangle, and narrower makes an acute triangle.",
        beats: [
          { say: "Find the biggest angle: a square corner makes a right triangle, wider makes an obtuse triangle, and narrower makes an acute triangle.", pic: 0 },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: tri(60, 55, 4, 0), tone: 1 }, { pts: tri(90, 50, 4, 5), tone: 2, right: [0] }, { pts: tri(25, 35, 5, 10), tone: 3, angles: [null, null, '120°'] }] }] },
      { title: "A square corner", text: "Find the biggest angle first. Here it's this corner, with a small square. That's a right angle, 90°. So this is a right triangle.",
        beats: [
          { say: "Find the biggest angle first.", pic: 0 },
          { say: "Here it's this corner, with a small square." },
          { say: "That's a right angle, 90°." },
          { say: "So this is a right triangle." },
        ],
        pictures: [{ kind: 'poly', motion: true, shapes: [{ pts: tri(90, 35), tone: 2, right: [0], angles: [null, '35°', '55°'] }] }] },
      { title: "Wider than a square corner", text: "Next one. Its angles are 25°, 35° and 120°. The biggest is 120°. Is that wider than 90°? Yes. So this is an obtuse triangle.",
        beats: [
          { say: "Next one. Its angles are 25°, 35° and 120°.", pic: 0 },
          { say: "The biggest is 120°." },
          { say: "Is that wider than 90°? Yes." },
          { say: "So this is an obtuse triangle." },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: tri(25, 35), tone: 3, angles: ['25°', '35°', '120°'] }] }] },
      { title: "All narrow", text: "Last one. Its angles are 70°, 70° and 40°. Even the biggest, 70°, is narrower than 90°. So this is an acute triangle.",
        beats: [
          { say: "Last one. Its angles are 70°, 70° and 40°.", pic: 0 },
          { say: "Even the biggest, 70°, is narrower than 90°." },
          { say: "So this is an acute triangle." },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: tri(70, 70, 4), tone: 1, angles: ['70°', '70°', '40°'], ticks: [1, 2] }] }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't name a triangle by a SMALL angle. Every triangle has small ones. Only the biggest angle names it. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't name a triangle by a SMALL angle. Every triangle has small ones.", pic: 0 },
          { say: "Only the biggest angle names it.", pic: 1 },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: tri(25, 35), tone: 3, angles: ['25°', '35°', '120°'] }] },
          { kind: 'cards', wrong: '25° is narrow, so acute', right: '120° is the biggest, so obtuse' }] },
    ],
    turn: {
      text: 'Look at the angles. Is this an acute triangle, a right triangle or an obtuse triangle?',
      picture: { kind: 'poly', shapes: [{ pts: tri(30, 40), tone: 1, angles: ['30°', '40°', '110°'] }] },
      answer: { choices: TRI, correct: 2 },
      steps: ['The angles are 30°, 40° and 110°.', 'The biggest is 110°, which is wider than a right angle.', 'So it is an obtuse triangle.'],
      prompt: 'Find the biggest angle. Compare it with a right angle.',
      hint1: 'Which angle is the biggest?',
      hint2: 'Compare the biggest angle with a right angle, 90°.',
      twin: { text: 'Look at the angles. Is this an acute triangle, a right triangle or an obtuse triangle?',
        picture: { kind: 'poly', shapes: [{ pts: tri(50, 60), tone: 2, angles: ['50°', '60°', '70°'] }] },
        answer: { choices: TRI, correct: 0 },
        steps: ['The angles are 50°, 60° and 70°.', 'The biggest is 70°, which is narrower than a right angle.', 'So it is an acute triangle.'],
        hint1: 'Find the biggest angle.', hint2: 'Is the biggest angle less than 90°, or 90°, or more?' },
    },
    won: { text: 'You sorted the triangle by its biggest angle.', sticker: 'Triangles are sorted by angles: acute, right or obtuse. A triangle with 2 sides the same length is isosceles.' },
    twinWon: { text: 'You found the biggest angle and saw it was narrower than a right angle.', sticker: 'A triangle with all its angles narrower than a right angle is acute. A triangle with two sides the same length is isosceles.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Is this an acute triangle, a right triangle or an obtuse triangle?',
        picture: { kind: 'poly', shapes: [{ pts: tri(20, 35), tone: 1, angles: ['20°', '35°', '125°'] }] }, answer: { choices: TRI, correct: 2 },
        steps: ['The angles are 20°, 35° and 125°.', 'The biggest is 125°, which is wider than a right angle.', 'So it is an obtuse triangle.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Is this an acute triangle, a right triangle or an obtuse triangle?',
        picture: { kind: 'poly', shapes: [{ pts: tri(90, 40), tone: 2, right: [0], angles: [null, '40°', '50°'] }] }, answer: { choices: TRI, correct: 1 },
        steps: ['The little square shows a right angle.', 'The other two angles, 40° and 50°, are smaller, so the right angle is the biggest.', 'So it is a right triangle.'] } },
      { why: 'Still "look at the biggest angle"', problem: { text: 'Is this an acute triangle, a right triangle or an obtuse triangle?',
        picture: { kind: 'poly', shapes: [{ pts: tri(80, 45), tone: 3, angles: ['80°', '45°', '55°'] }] }, answer: { choices: TRI, correct: 0 },
        steps: ['The angles are 80°, 45° and 55°.', 'The biggest is 80°, which is narrower than a right angle.', 'So it is an acute triangle.'] } },
      { why: 'A little harder', problem: { text: 'Look closely. Is this an acute triangle, a right triangle or an obtuse triangle?',
        picture: { kind: 'poly', shapes: [{ pts: tri(45, 40), tone: 4, angles: ['45°', '40°', '95°'] }] }, answer: { choices: TRI, correct: 2 },
        steps: ['The angles are 45°, 40° and 95°.', 'The biggest is 95°. That is a little wider than a right angle, 90°.', 'So it is an obtuse triangle.'] } },
      { why: 'Same math in a story', problem: { text: 'A yield sign is a triangle with these angles. Is it an acute triangle, a right triangle or an obtuse triangle?',
        picture: { kind: 'poly', shapes: [{ pts: tri(60, 60), tone: 2, angles: ['60°', '60°', '60°'], ticks: [0, 1, 2] }] }, answer: { choices: TRI, correct: 0 },
        steps: ['All three angles are 60°.', 'Even the biggest angle is narrower than a right angle.', 'So it is an acute triangle.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m5-t7', title: 'Sort four-sided shapes', skill: 'Name a four-sided shape by its parallel sides, equal sides and square corners',
    bigIdea: "Count the pairs of parallel sides first, then check the sides and corners to find the best name.",
    screens: [
      { title: 'Four sides each', text: 'A table top, a leaning shelf and the side of a lampshade all have 4 sides. What is the best name for each one?',
        pictures: [{ kind: 'poly', shapes: [{ pts: [[0, 0], [4, 0], [4, 2.5], [0, 2.5]], tone: 1 }, { pts: [[5, 0], [9, 0], [10, 2.5], [6, 2.5]], tone: 2 }, { pts: [[11.5, 0], [16.5, 0], [15.5, 2.5], [12.5, 2.5]], tone: 3 }] }] },
      { title: "Four sides is not a name", text: "All 3 have 4 sides. So is 4 sides a name? No. Look at which sides are parallel.",
        beats: [
          { say: "All 3 have 4 sides.", pic: 0 },
          { say: "So is 4 sides a name? No." },
          { say: "Look at which sides are parallel." },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: [[0, 0], [4, 0], [4, 2.5], [0, 2.5]], tone: 1 }, { pts: [[5, 0], [9, 0], [10, 2.5], [6, 2.5]], tone: 2 }, { pts: [[11.5, 0], [16.5, 0], [15.5, 2.5], [12.5, 2.5]], tone: 3 }] }] },
      { title: "The big idea", text: "Count the pairs of parallel sides first, then check the sides and corners to find the best name.",
        beats: [
          { say: "Count the pairs of parallel sides first, then check the sides and corners to find the best name.", pic: 0 },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: [[0, 0], [4, 0], [4, 2.5], [0, 2.5]], tone: 1, right: ALL4 }, { pts: [[5, 0], [9, 0], [10, 2.5], [6, 2.5]], tone: 2 }, { pts: [[11.5, 0], [16.5, 0], [15.5, 2.5], [12.5, 2.5]], tone: 3 }] }] },
      { title: "Two pairs", text: "Take the leaning shelf. Top and bottom are parallel. That's 1 pair. Left and right are parallel too. 2 pairs. So it's a parallelogram.",
        beats: [
          { say: "Take the leaning shelf.", pic: 0 },
          { say: "Top and bottom are parallel. That's 1 pair." },
          { say: "Left and right are parallel too. 2 pairs." },
          { say: "So it's a parallelogram." },
        ],
        pictures: [{ kind: 'poly', motion: true, shapes: [{ pts: [[0, 0], [5, 0], [6.5, 2.5], [1.5, 2.5]], tone: 2 }] }] },
      { title: "Only one pair", text: "Now the lampshade side. Top and bottom are parallel again. But the other 2 sides lean in, so they would meet. Just 1 pair. It's a trapezoid.",
        beats: [
          { say: "Now the lampshade side.", pic: 0 },
          { say: "Top and bottom are parallel again." },
          { say: "But the other 2 sides lean in, so they would meet." },
          { say: "Just 1 pair. It's a trapezoid." },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: [[0, 0], [6, 0], [4.5, 2.5], [1.5, 2.5]], tone: 3 }] }] },
      { title: "Then check the corners", text: "What about the table top? 2 pairs, and 4 square corners. So it's a rectangle. With 4 equal sides too, it would be a square.",
        beats: [
          { say: "What about the table top?", pic: 0 },
          { say: "2 pairs, and 4 square corners." },
          { say: "So it's a rectangle." },
          { say: "With 4 equal sides too, it would be a square." },
        ],
        pictures: [{ kind: 'table', motion: true, head: ['shape', 'parallel pairs', 'square corners?', '4 equal sides?'],
          rows: [['square', '2', 'yes', 'yes'], ['rectangle', '2', 'yes', 'no'], ['rhombus', '2', 'no', 'yes'], ['parallelogram', '2', 'no', 'no'], ['trapezoid', '1', 'no', 'no']] }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Not every leaning shape is a rhombus. It needs 4 EQUAL sides. The shelf leans, but its sides don't match. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Not every leaning shape is a rhombus.", pic: 0 },
          { say: "It needs 4 EQUAL sides. The shelf leans, but its sides don't match.", pic: 1 },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: [[0, 0], [5, 0], [6.5, 2.5], [1.5, 2.5]], tone: 2 }] },
          { kind: 'cards', wrong: 'it leans, so rhombus', right: 'it leans and has 4 equal sides, so rhombus' }] },
    ],
    turn: {
      text: 'Which name fits this shape best?',
      picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [5, 0], [6.5, 2.5], [1.5, 2.5]], tone: 2 }] },
      answer: { choices: QUAD, correct: 2 },
      steps: ['The top and bottom are parallel, and the left and right sides are parallel too. That is two pairs.', 'There are no square corners, and the sides are not all the same length.', 'So the best name is parallelogram.'],
      prompt: 'Count the pairs of parallel sides. Then check the corners and the sides.',
      hint1: 'How many pairs of sides run side by side and never meet?',
      hint2: 'There are no square corners. Are all 4 sides the same length?',
      twin: { text: 'Which name fits this shape best?',
        picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [6, 0], [4.5, 2.5], [1.5, 2.5]], tone: 3 }] },
        answer: { choices: QUAD, correct: 3 },
        steps: ['The top and bottom are parallel.', 'The left and right sides lean in toward each other, so they are not parallel.', 'Only one pair is parallel, so the best name is trapezoid.'],
        hint1: 'Look at the top and bottom. Then look at the left and right sides.', hint2: 'Do the left and right sides lean in toward each other?' },
    },
    won: { text: 'You counted the pairs of parallel sides, then checked the rest.', sticker: 'A four-sided shape with two pairs of parallel sides is a parallelogram. With only one pair, it is a trapezoid.' },
    twinWon: { text: 'You found only one pair of parallel sides.', sticker: 'A four-sided shape with only one pair of parallel sides is a trapezoid.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which name fits this shape best?',
        picture: { kind: 'poly', shapes: [{ pts: [[1.5, 0], [6.5, 0], [5, 2.5], [0, 2.5]], tone: 1 }] }, answer: { choices: QUAD, correct: 2 },
        steps: ['The top and bottom are parallel, and so are the left and right sides: two pairs.', 'No square corners, and the sides are not all the same length.', 'So the best name is parallelogram.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'The little marks show equal sides. Which name fits this shape best?',
        picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [3, 0], [4.5, 2.6], [1.5, 2.6]], tone: 3, ticks: ALL4 }] }, answer: { choices: QUAD, correct: 1 },
        steps: ['It has two pairs of parallel sides.', 'The marks show all 4 sides are the same length, but there are no square corners.', 'So the best name is rhombus.'] } },
      { why: 'Still "count the parallel pairs"', problem: { text: 'Does this shape have a pair of parallel sides?',
        picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [5, 0], [3, 3], [0, 3]], tone: 4, right: [0, 3] }] }, answer: { choices: YES_NO, correct: 0 },
        steps: ['Look at the top and the bottom.', 'They run side by side and never meet, so they are a pair of parallel sides.', 'So the answer is yes.'] } },
      { why: 'A little harder', problem: { text: 'Does this shape have a pair of parallel sides?',
        picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [5, 0], [4, 3], [1, 2]], tone: 2 }] }, answer: { choices: YES_NO, correct: 1 },
        steps: ['The top and bottom get closer on the left, so they would meet.', 'The left and right sides lean in toward each other, so they would meet too.', 'No pair of sides is parallel, so the answer is no.'] } },
      { why: 'Same math in a story', problem: { text: 'A door has this shape. Which name fits it best?',
        picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [3, 0], [3, 7], [0, 7]], tone: 1, right: ALL4, sides: ['3 ft', '7 ft', '3 ft', '7 ft'] }] },
        answer: { choices: ['square', 'rectangle', 'rhombus', 'trapezoid'], correct: 1 },
        steps: ['It has two pairs of parallel sides and 4 square corners.', 'The sides are 3 feet and 7 feet, so they are not all the same length.', 'So the best name is rectangle.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m5-t8', title: 'Lines of symmetry', skill: 'Tell whether a line folds a shape into matching halves, and count those lines',
    bigIdea: "A fold line counts only if the two halves land exactly on top of each other.",
    screens: [
      { title: 'Fold a paper house', text: 'You cut a house out of paper and fold it along the dashed line. Do the two halves land exactly on top of each other?',
        pictures: [{ kind: 'poly', shapes: [{ pts: house, tone: 1 }], segs: [fold([2, -0.5], [2, 5.5])] }] },
      { title: "Looking is not enough", text: "How can you tell if a fold works? Picture the fold, and check where every part lands.",
        beats: [
          { say: "How can you tell if a fold works?", pic: 0 },
          { say: "Picture the fold, and check where every part lands." },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: [[0, 0], [6, 0], [6, 3], [0, 3]], tone: 2 }], segs: [fold([0, 0], [6, 3])] }] },
      { title: "The big idea", text: "A fold line counts only if the two halves land exactly on top of each other.",
        beats: [
          { say: "A fold line counts only if the two halves land exactly on top of each other.", pic: 0 },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: house, tone: 1 }], segs: [fold([2, -0.5], [2, 5.5])] }] },
      { title: "Fold it", text: "Fold the house down the dashed line. Wall lands on wall, roof on roof. Nothing sticks out, so this line works.",
        beats: [
          { say: "Fold the house down the dashed line.", pic: 0 },
          { say: "Wall lands on wall, roof on roof." },
          { say: "Nothing sticks out, so this line works." },
        ],
        pictures: [{ kind: 'poly', motion: true, shapes: [{ pts: [[0, 0], [2, 0], [2, 5], [0, 3]], tone: 1 }, { pts: [[2, 0], [4, 0], [4, 3], [2, 5]], tone: 2 }], segs: [fold([2, -0.5], [2, 5.5])] }] },
      { title: "Across the middle", text: "Now try a line across the middle. Fold the top down. The top has a point, and the bottom has square corners. They don't match, so this line does not work.",
        beats: [
          { say: "Now try a line across the middle.", pic: 0 },
          { say: "Fold the top down." },
          { say: "The top has a point, and the bottom has square corners." },
          { say: "They don't match, so this line does not work." },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: house, tone: 1 }], segs: [fold([-0.5, 2.5], [4.5, 2.5])] }] },
      { title: "Count every fold line", text: "Can a shape have more than one? This rectangle can. Down the middle works, and across the middle works. So it has 2 fold lines.",
        beats: [
          { say: "Can a shape have more than one?" },
          { say: "This rectangle can.", pic: 0 },
          { say: "Down the middle works, and across the middle works." },
          { say: "So it has 2 fold lines.", pic: 1 },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: [[0, 0], [6, 0], [6, 3], [0, 3]], tone: 2 }], segs: [fold([3, -0.5], [3, 3.5]), fold([-0.5, 1.5], [6.5, 1.5])] },
          { kind: 'eq', text: '2 fold lines' }] },
      { title: "One thing not to do", text: "Here's the part people mix up. On a long rectangle, corner to corner does NOT work. Fold it, and the corners stick out. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "On a long rectangle, corner to corner does NOT work.", pic: 1 },
          { say: "Fold it, and the corners stick out.", pic: 0 },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: [[0, 0], [6, 0], [6, 3], [0, 3]], tone: 2 }], segs: [fold([0, 0], [6, 3])] },
          { kind: 'cards', wrong: 'rectangle: 4 fold lines', right: 'rectangle: 2 fold lines' }] },
    ],
    turn: {
      text: 'Fold along the dashed line. Do the two halves match exactly?',
      picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [4, 0], [2, 4]], tone: 1 }], segs: [fold([2, -0.5], [2, 4.5])] },
      answer: { choices: YES_NO, correct: 0 },
      steps: ['Fold the triangle along the dashed line.', 'The left corner lands on the right corner, and the two slanted sides land on each other.', 'The halves match, so the answer is yes.'],
      prompt: 'Picture folding along the dashed line. Does every part land on a matching part?',
      hint1: 'Picture folding along the dashed line. Where does each corner land?',
      hint2: 'When you fold, does the left half sit exactly on the right half, with nothing sticking out?',
      twin: { text: 'Fold along the dashed line. Do the two halves match exactly?',
        picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [6, 0], [6, 3], [0, 3]], tone: 2 }], segs: [fold([0, 0], [6, 3])] },
        answer: { choices: YES_NO, correct: 1 },
        steps: ['Fold the rectangle along the dashed line.', 'The corners do not land on each other, so parts stick out.', 'The halves do not match, so the answer is no.'],
        hint1: 'Picture the fold. Does every corner land on another corner?', hint2: 'Same size is not enough. Would the halves sit exactly on top of each other?' },
    },
    won: { text: 'You folded the shape in your head and checked that the halves match.', sticker: 'A fold line where both halves match exactly is a line of symmetry.' },
    twinWon: { text: 'You saw that the halves would not match on that fold.', sticker: 'A fold line where both halves match exactly is a line of symmetry.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Fold along the dashed line. Do the two halves match exactly?',
        picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [4, 0], [4, 4], [0, 4]], tone: 3 }], segs: [fold([2, -0.5], [2, 4.5])] }, answer: { choices: YES_NO, correct: 0 },
        steps: ['Fold the square down the dashed line.', 'The left half lands exactly on the right half.', 'The halves match, so the answer is yes.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Fold along the dashed line. Do the two halves match exactly?',
        picture: { kind: 'poly', shapes: [{ pts: house, tone: 1 }], segs: [fold([1.2, -0.5], [1.2, 5.5])] }, answer: { choices: YES_NO, correct: 1 },
        steps: ['The dashed line is not in the middle of the house.', 'One part is thin and the other is wide, and the roof point is all on one side.', 'The halves do not match, so the answer is no.'] } },
      { why: 'Still "fold and match"', problem: { text: 'How many matching fold lines does this rectangle have?',
        picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [5, 0], [5, 2], [0, 2]], tone: 2 }] }, answer: 2,
        steps: ['Down the middle matches, and across the middle matches.', 'Corner to corner does not match on a long rectangle.', 'So it has 2.'] } },
      { why: 'A little harder', problem: { text: 'All 4 sides are the same length and all corners are square. How many matching fold lines does this square have?',
        picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [4, 0], [4, 4], [0, 4]], tone: 3, ticks: ALL4, right: ALL4 }] }, answer: 4,
        steps: ['Down the middle and across the middle both match.', 'Because all the sides are the same length, corner to corner matches too, both ways.', 'That is 2 + 2, so the square has 4.'] } },
      { why: 'Same math in a story', problem: { text: 'Ava makes a kite in this shape. How many matching fold lines does her kite have?',
        picture: { kind: 'poly', shapes: [{ pts: [[2, 0], [4, 3], [2, 5], [0, 3]], tone: 4 }] }, answer: 1,
        steps: ['Fold it from the top point to the bottom point: the left and right halves match.', 'Fold it across: the top part is shorter than the bottom part, so it does not match.', 'So the kite has 1.'] } },
    ],
  },
]

attachChalk(G4M5, G4M5_CHALK)
