/**
 * Grade 4 · Module 6 — Place value for decimal fractions.
 * Written to docs/new-flow/AUTHORING.md. Topic 1 is the founder's own Grade 4 example (tenths as decimals).
 */
import type { Lesson, Picture } from '../script'

/** A 10 × 10 hundredths grid with `n` squares shaded: full columns first (tone 1), then the rest of the next column (tone 2). */
const hund = (n: number, motion = false): Picture => {
  const cols = Math.floor(n / 10), extra = n % 10
  const shade: { r: number; c: number; h: number; w: number; tone?: 1 | 2 }[] = []
  if (cols) shade.push({ r: 0, c: 0, h: 10, w: cols, tone: 1 })
  if (extra) shade.push({ r: 0, c: cols, h: extra, w: 1, tone: 2 })
  return { kind: 'grid', rows: 10, cols: 10, shade, motion }
}
const blank: Picture = { kind: 'grid', rows: 10, cols: 10 }
const bar = (shaded: number, label?: string, motion = false): Picture => ({ kind: 'bars', bars: [{ parts: 10, shaded, label }], motion })
const line = (min: number, max: number, at?: number): Picture =>
  ({ kind: 'numline', min, max, ticks: 10, labels: 'ends', points: at === undefined ? [] : [{ at }] })
const coins = (d: string, dimes: string, p: string, mark?: [number, number][]): Picture =>
  ({ kind: 'table', head: ['Dollars', 'Dimes', 'Pennies'], rows: [[d, dimes, p]], mark, motion: !!mark })
const SIGNS = ['<', '>', '=']

export const G4M6: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m6-t1', title: 'Tenths as decimals', skill: 'Write tenths as a fraction and as a decimal',
    bigIdea: 'The first number after the point means tenths. So 3/10 is 0.3.',
    screens: [
      { title: 'A bar of chocolate', text: 'A chocolate bar is cut into 10 equal strips. You have 3 strips. How much of the bar is that?',
        pictures: [bar(3)] },
      { title: 'Signs use a point', text: 'You already know this one. 3 strips out of 10 is 3/10. But go and look at a price tag, or the scale at the doctor. You will not see a fraction there. You will see a number with a point in it.',
        beats: [
          { say: 'You already know this one. 3 strips out of 10 is 3/10.', pic: 0 },
          { say: 'But go and look at a price tag, or the scale at the doctor.' },
          { say: 'You will not see a fraction there. You will see a number with a point in it.' },
        ],
        pictures: [bar(3, '3/10')] },
      { title: 'The big idea', text: 'The first number after the point means tenths. So 3/10 is 0.3.',
        beats: [
          { say: 'The first number after the point means tenths.', pic: 0 },
          { say: 'So 3/10 is 0.3.' },
        ],
        pictures: [bar(3)] },
      { title: 'One strip is one tenth', text: "Let's look at just one strip. The bar is cut into 10 equal strips, so one strip is one tenth of the whole bar. And here is how we write one tenth. As a fraction, or with a point.",
        beats: [
          { say: "Let's look at just one strip.", pic: 0 },
          { say: 'The bar is cut into 10 equal strips, so one strip is one tenth of the whole bar.', write: '10 equal parts → tenths' },
          { say: 'And here is how we write one tenth. As a fraction, or with a point.', pic: 1 },
        ],
        pictures: [bar(1, '1/10', true), { kind: 'eq', text: '1/10 = 0.1' }] },
      { title: 'Count the strips', text: 'Now back to the shaded strips. Count them with me. One, two, three. 3 strips, and every strip is a tenth. So that is 3 tenths.',
        beats: [
          { say: 'Now back to the shaded strips. Count them with me.', pic: 0 },
          { say: 'One, two, three.' },
          { say: '3 strips, and every strip is a tenth. So that is 3 tenths.', pic: 1 },
        ],
        pictures: [bar(3, undefined, true), { kind: 'eq', text: '3 tenths' }] },
      { title: 'Write it with a point', text: 'So 3 tenths is 3/10. Written with a point, that same amount is 0.3. Same chocolate, same 3 strips. Two ways to write it.',
        beats: [
          { say: 'So 3 tenths is 3/10.' },
          { say: 'Written with a point, that same amount is 0.3.', pic: 0, write: 'tenths → first place after the point' },
          { say: 'Same chocolate, same 3 strips. Two ways to write it.', pic: 1 },
        ],
        pictures: [bar(3, '0.3'), { kind: 'eq', text: '3/10 = 0.3' }] },
      { title: 'One thing not to do', text: "Here is the slip almost everybody makes. Don't write 0.03 for 3 strips. That 3 has slid one place too far, and 0.03 is a tiny sliver of the bar. Tenths sit right after the point.",
        beats: [
          { say: 'Here is the slip almost everybody makes.' },
          { say: "Don't write 0.03 for 3 strips.", pic: 0 },
          { say: 'That 3 has slid one place too far, and 0.03 is a tiny sliver of the bar. Tenths sit right after the point.' },
        ],
        pictures: [{ kind: 'cards', wrong: '3/10 = 0.03', right: '3/10 = 0.3' }] },
    ],
    turn: {
      text: 'A bar is cut into 10 equal strips. You have 0.4 of the bar. Write it as a fraction.',
      picture: bar(0),
      answer: { frac: [4, 10] }, steps: ['The first number after the point means tenths.', '0.4 is 4 tenths, that is 4 strips out of 10.', 'So 0.4 is 4/10.'],
      prompt: 'The number after the point tells how many strips. The bar has 10 strips.',
      hint1: 'The first number after the point tells how many tenths.',
      hint2: 'Each strip is 1/10. How many strips is 0.4?',
      twin: { text: 'A bar is cut into 10 equal strips. 7 strips are shaded. Write the shaded part as a decimal.',
        picture: bar(7),
        answer: 0.7, steps: ['The bar has 10 equal strips, so each strip is one tenth.', '7 strips are 7 tenths, which is 7/10.', 'So the shaded part is 0.7.'],
        hint1: 'How many equal strips is the bar cut into? How many are shaded?',
        hint2: 'Each shaded strip is one tenth. The number of tenths goes right after the point.' },
    },
    won: { text: 'You read the tenths and wrote them as a fraction.', sticker: 'A number with a point in it is a decimal. The first place after the point is the tenths place.' },
    twinWon: { text: 'You counted 7 tenths and wrote 0.7.', sticker: 'A number with a point in it is a decimal. The first place after the point is the tenths place.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A bar is cut into 10 equal strips. 6 strips are shaded. Write the shaded part as a decimal.',
        picture: bar(6), answer: 0.6,
        steps: ['Each strip is one tenth.', '6 strips are 6 tenths, or 6/10.', 'So the shaded part is 0.6.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Write 9/10 as a decimal.',
        picture: bar(0, '9/10'), answer: 0.9,
        steps: ['9/10 is 9 tenths.', 'Tenths go right after the point.', 'So 9/10 is 0.9.'] } },
      { why: 'Still "tenths go after the point"', problem: { text: 'Write 0.2 as a fraction with 10 on the bottom.',
        picture: bar(0), answer: { frac: [2, 10] },
        steps: ['The 2 is right after the point, so it means 2 tenths.', '2 tenths is 2 strips out of 10.', 'So 0.2 is 2/10.'] } },
      { why: 'A little harder', problem: { text: 'A bar has 10 equal strips. The shaded strips are eaten. What part of the bar is left, as a decimal?',
        picture: bar(4), answer: 0.6,
        steps: ['4 of the 10 strips are eaten.', '10 − 4 = 6 strips are left. That is 6 tenths.', 'So 0.6 of the bar is left.'] } },
      { why: 'Same math in a story', problem: { text: 'A ribbon is cut into 10 equal pieces. Lily uses 5 pieces for a bow. What part of the ribbon does she use, as a decimal?',
        picture: bar(0), answer: 0.5,
        steps: ['Each piece is one tenth of the ribbon.', '5 pieces are 5 tenths, or 5/10.', 'So Lily uses 0.5 of the ribbon.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m6-t2', title: 'Hundredths as decimals', skill: 'Write hundredths as a fraction and as a decimal',
    bigIdea: 'The second number after the point means hundredths. So 25/100 is 0.25.',
    screens: [
      { title: 'A sheet of stickers', text: 'A sheet has 100 small square stickers, in 10 rows of 10. 25 of them are used. How much of the sheet is used?',
        pictures: [hund(25)] },
      { title: 'Tenths are too big', text: 'Remember, one full column is one tenth. But look at the shaded part. 25 squares is more than 2 columns and less than 3. Tenths on their own cannot name it.',
        beats: [
          { say: 'Remember, one full column is one tenth.', pic: 0, write: '1 column = 1 tenth' },
          { say: 'But look at the shaded part. 25 squares is more than 2 columns and less than 3.' },
          { say: 'Tenths on their own cannot name it.' },
        ],
        pictures: [hund(25)] },
      { title: 'The big idea', text: 'The second number after the point means hundredths. So 25/100 is 0.25.',
        beats: [
          { say: 'The second number after the point means hundredths.', pic: 0 },
          { say: 'So 25/100 is 0.25.' },
        ],
        pictures: [hund(25)] },
      { title: 'One square is one hundredth', text: "Let's go smaller. Here is just one little square. The sheet has 100 equal squares, so one of them is one hundredth of the sheet. And this is how we write one hundredth.",
        beats: [
          { say: "Let's go smaller. Here is just one little square.", pic: 0 },
          { say: 'The sheet has 100 equal squares, so one of them is one hundredth of the sheet.', write: '100 equal parts → hundredths' },
          { say: 'And this is how we write one hundredth.', pic: 1 },
        ],
        pictures: [{ kind: 'grid', rows: 10, cols: 10, shade: [{ r: 0, c: 0, h: 1, w: 1, tone: 2 }], motion: true }, { kind: 'eq', text: '1/100 = 0.01' }] },
      { title: 'Count the squares', text: 'Now count the shaded part. Take the full columns by 10s first. Ten, twenty. Then 5 more squares, and we are at 25. So 25 hundredths are shaded.',
        beats: [
          { say: 'Now count the shaded part. Take the full columns by 10s first.', pic: 0 },
          { say: 'Ten, twenty. Then 5 more squares, and we are at 25.' },
          { say: 'So 25 hundredths are shaded.', pic: 1 },
        ],
        pictures: [hund(25, true), { kind: 'eq', text: '25 hundredths' }] },
      { title: 'Write it with a point', text: 'So 25 hundredths is 25/100. With a point, we write it 0.25. And each digit is doing a job here. The 2 counts the full columns, and the 5 counts the extra squares.',
        beats: [
          { say: 'So 25 hundredths is 25/100.', pic: 0 },
          { say: 'With a point, we write it 0.25.', pic: 1 },
          { say: 'And each digit is doing a job here. The 2 counts the full columns, and the 5 counts the extra squares.', write: 'first place → columns, second place → squares' },
        ],
        pictures: [hund(25), { kind: 'eq', text: '25/100 = 0.25' }] },
      { title: 'One thing not to do', text: "Here is the one to watch for. Don't write 2.5. That is more than 2 whole sheets, and we only shaded part of one. Hundredths need two places after the point.",
        beats: [
          { say: 'Here is the one to watch for.' },
          { say: "Don't write 2.5.", pic: 0 },
          { say: 'That is more than 2 whole sheets, and we only shaded part of one. Hundredths need two places after the point.' },
        ],
        pictures: [{ kind: 'cards', wrong: '25/100 = 2.5', right: '25/100 = 0.25' }] },
    ],
    turn: {
      text: 'This grid has 100 equal squares. What part is shaded, as a decimal?',
      picture: hund(37),
      answer: 0.37, steps: ['The grid has 100 equal squares, so each square is one hundredth.', 'Count full columns: 10, 20, 30. Then 7 more makes 37.', '37 hundredths is 37/100, so the shaded part is 0.37.'],
      prompt: 'Count the shaded squares. Then write the hundredths after the point.',
      hint1: 'How many squares are shaded? Count full columns by 10s first.',
      hint2: 'Each full column is 10 squares. Count the columns, then add the extra squares.',
      twin: { text: 'This grid has 100 equal squares. What part is shaded, as a decimal?',
        picture: hund(62),
        answer: 0.62, steps: ['Each square is one hundredth.', 'Count full columns: 10, 20, 30, 40, 50, 60. Then 2 more makes 62.', '62 hundredths is 62/100, so the shaded part is 0.62.'],
        hint1: 'Count the full columns by 10s first.',
        hint2: 'After the full columns, add the squares in the column that is not full.' },
    },
    won: { text: 'You counted hundredths and wrote them with two places after the point.', sticker: 'The second place after the point is the hundredths place.' },
    twinWon: { text: 'You counted the shaded squares out of 100 and wrote 0.62.', sticker: 'The second place after the point is the hundredths place.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'This grid has 100 equal squares. What part is shaded, as a decimal?',
        picture: hund(48), answer: 0.48,
        steps: ['Each square is one hundredth.', '4 full columns is 40. Then 8 more makes 48.', 'So the shaded part is 0.48.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Write 71/100 as a decimal.',
        picture: blank, answer: 0.71,
        steps: ['71/100 is 71 hundredths.', 'That is 7 tenths and 1 hundredth.', 'So 71/100 is 0.71.'] } },
      { why: 'Still "two places for hundredths"', problem: { text: 'Write 9/100 as a decimal.',
        picture: blank, answer: 0.09,
        steps: ['9/100 is 9 hundredths and no tenths.', 'Put 0 in the first place after the point and 9 in the second.', 'So 9/100 is 0.09.'] } },
      { why: 'A little harder', problem: { text: 'Write 0.56 as a fraction with 100 on the bottom.',
        picture: blank, answer: { frac: [56, 100] },
        steps: ['0.56 has two places after the point, so it counts hundredths.', 'It is 56 hundredths.', 'So 0.56 is 56/100.'] } },
      { why: 'Same math in a story', problem: { text: 'A box holds 100 crayons. 83 of them are blue. What part of the box is blue, as a decimal?',
        picture: blank, answer: 0.83,
        steps: ['Each crayon is one hundredth of the box.', '83 crayons are 83 hundredths, or 83/100.', 'So 0.83 of the box is blue.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m6-t3', title: '0.5 is the same as 0.50', skill: 'A zero at the end of a decimal does not change its value',
    bigIdea: 'A 0 at the end does not change the amount. 5 tenths and 50 hundredths cover the same space.',
    screens: [
      { title: 'A tray of brownies', text: 'A tray of brownies is cut into 100 small squares. Ana eats the shaded part. Ben says she ate 0.5 of the tray. Ana says 0.50. Who is right?',
        pictures: [hund(50)] },
      { title: 'They look different', text: "Look at the two numbers on their own. 0.50 has more digits than 0.5. And 50 is a lot more than 5, so your eyes tell you 0.50 must be the bigger one. Let's go and check that.",
        beats: [
          { say: 'Look at the two numbers on their own.', pic: 0 },
          { say: '0.50 has more digits than 0.5.' },
          { say: 'And 50 is a lot more than 5, so your eyes tell you 0.50 must be the bigger one.' },
          { say: "Let's go and check that." },
        ],
        pictures: [{ kind: 'eq', text: '0.5 and 0.50' }] },
      { title: 'The big idea', text: 'A 0 at the end does not change the amount. 5 tenths and 50 hundredths cover the same space.',
        beats: [
          { say: 'A 0 at the end does not change the amount.', pic: 0 },
          { say: '5 tenths and 50 hundredths cover the same space.' },
        ],
        pictures: [hund(50)] },
      { title: 'Count the columns', text: 'Count the shaded part by columns first. Each column is one tenth, and 5 of them are shaded. That gives us 5 tenths, which we write 0.5.',
        beats: [
          { say: 'Count the shaded part by columns first.', pic: 0 },
          { say: 'Each column is one tenth, and 5 of them are shaded.', write: 'column → tenth' },
          { say: 'That gives us 5 tenths, which we write 0.5.', pic: 1 },
        ],
        pictures: [hund(50, true), { kind: 'eq', text: '5 tenths = 0.5' }] },
      { title: 'Count the squares', text: 'Now count the very same shading, but by little squares. 5 columns of 10 squares is 50 squares. That is 50 hundredths, and we write it 0.50.',
        beats: [
          { say: 'Now count the very same shading, but by little squares.', pic: 0 },
          { say: '5 columns of 10 squares is 50 squares.', write: 'square → hundredth' },
          { say: 'That is 50 hundredths, and we write it 0.50.', pic: 1 },
        ],
        pictures: [hund(50), { kind: 'eq', text: '50 hundredths = 0.50' }] },
      { title: 'Same space, two names', text: 'Nothing moved between those two counts. The same squares were shaded both times, so 0.5 and 0.50 are the same amount. Ana and Ben were both right. That 0 on the end is only telling us there are no extra squares.',
        beats: [
          { say: 'Nothing moved between those two counts.', pic: 0 },
          { say: 'The same squares were shaded both times, so 0.5 and 0.50 are the same amount.', pic: 1 },
          { say: 'Ana and Ben were both right. That 0 on the end is only telling us there are no extra squares.', write: '0 at the end → no extra squares' },
        ],
        pictures: [hund(50), { kind: 'eq', text: '0.5 = 0.50' }] },
      { title: 'One thing not to do', text: "Here is the trap. Don't decide 0.50 is bigger just because 50 is more than 5. Go back to the tray. They cover the very same squares.",
        beats: [
          { say: 'Here is the trap.' },
          { say: "Don't decide 0.50 is bigger just because 50 is more than 5.", pic: 0 },
          { say: 'Go back to the tray. They cover the very same squares.' },
        ],
        pictures: [{ kind: 'cards', wrong: '0.50 > 0.5', right: '0.50 = 0.5' }] },
    ],
    turn: {
      text: 'You shade 0.7 of a 100-square grid. How many small squares do you shade?',
      picture: blank,
      answer: 70, steps: ['0.7 is 7 tenths, and each tenth is a column of 10 squares.', '7 columns of 10 squares is 70 squares.', 'So 0.7 is 70 squares, or 0.70.'],
      prompt: 'Each tenth is one full column. Count the squares in those columns.',
      hint1: 'How many columns is 0.7? Each column is one tenth.',
      hint2: 'Each column has 10 squares. Count by 10s, once for each column.',
      twin: { text: 'You shade 0.3 of a 100-square grid. How many small squares do you shade?',
        picture: blank,
        answer: 30, steps: ['0.3 is 3 tenths, which is 3 columns.', 'Each column has 10 squares, so 3 columns is 10, 20, 30 squares.', 'So 0.3 is 30 squares, or 0.30.'],
        hint1: 'How many full columns is 0.3?',
        hint2: 'Each column has 10 squares. Count by 10s for each column.' },
    },
    won: { text: 'You saw that tenths and hundredths can name the same amount.', sticker: 'Decimals that name the same amount, like 0.5 and 0.50, are equivalent decimals.' },
    twinWon: { text: 'You saw that 0.3 is 30 small squares.', sticker: 'Decimals that name the same amount are called equivalent decimals.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'You shade 0.6 of a 100-square grid. How many small squares do you shade?',
        picture: blank, answer: 60,
        steps: ['0.6 is 6 tenths, which is 6 columns.', '6 columns of 10 squares is 60 squares.', 'So 0.6 is 60 squares.'] } },
      { why: 'Same idea, new numbers', problem: { text: '0.40 of a 100-square grid is shaded. How many full columns of 10 is that?',
        picture: blank, answer: 4,
        steps: ['0.40 is 40 hundredths, which is 40 squares.', 'Each column has 10 squares, so 40 squares fill 4 columns.', 'So 0.40 is 4 columns, the same as 0.4.'] } },
      { why: 'Still "a 0 at the end changes nothing"', problem: { text: 'Which sign goes between them? 0.9 ? 0.90',
        picture: { kind: 'eq', text: '0.9 ? 0.90' }, answer: { choices: SIGNS, correct: 2 },
        steps: ['0.9 is 9 tenths, which is 9 full columns.', '0.90 is 90 hundredths, which is the same 9 columns.', 'They are the same amount, so the sign is =.'] } },
      { why: 'A little harder', problem: { text: 'The shaded part of this 100-square grid is 20 hundredths. Write it as a decimal with just one place after the point.',
        picture: hund(20), answer: 0.2,
        steps: ['20 hundredths is 0.20.', 'The 0 at the end changes nothing.', 'So it is 0.2.'] } },
      { why: 'Same math in a story', problem: { text: 'A garden has 100 equal beds. 0.8 of the garden has beans. How many beds have beans?',
        picture: blank, answer: 80,
        steps: ['0.8 is 8 tenths, the same as 80 hundredths.', 'Each hundredth is 1 bed out of 100.', 'So 80 beds have beans.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m6-t4', title: 'Decimals on a number line', skill: 'Name a point on a number line in tenths or hundredths',
    bigIdea: 'Cut the space from 0 to 1 into 10 equal jumps. Each jump is 0.1.',
    screens: [
      { title: 'A walk to the park', text: 'The park is 1 mile away. You stop at the dot. How far have you walked?',
        pictures: [line(0, 1, 0.6)] },
      { title: 'Only two numbers', text: 'The line only gives us two numbers, 0 and 1. And the dot is sitting between them, so it is not a whole number at all. Those little marks in between need names of their own.',
        beats: [
          { say: 'The line only gives us two numbers, 0 and 1.', pic: 0 },
          { say: 'And the dot is sitting between them, so it is not a whole number at all.' },
          { say: 'Those little marks in between need names of their own.' },
        ],
        pictures: [line(0, 1, 0.6)] },
      { title: 'The big idea', text: 'Cut the space from 0 to 1 into 10 equal jumps. Each jump is 0.1.',
        beats: [
          { say: 'Cut the space from 0 to 1 into 10 equal jumps.', pic: 0 },
          { say: 'Each jump is 0.1.' },
        ],
        pictures: [line(0, 1)] },
      { title: 'Count the jumps', text: 'Count the jumps from 0 all the way along to 1. There are 10 of them, and every one is the same size. So one jump is one tenth of a mile.',
        beats: [
          { say: 'Count the jumps from 0 all the way along to 1.', pic: 0 },
          { say: 'There are 10 of them, and every one is the same size.' },
          { say: 'So one jump is one tenth of a mile.', write: '10 equal jumps → each one is a tenth' },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 10, labels: 'ends', jumps: [{ from: 0, to: 0.1, label: '0.1' }], motion: true }] },
      { title: 'Jump to the dot', text: 'Now we hop. Start at 0 and go one tenth at a time. 0.1, 0.2, 0.3, 0.4, 0.5, 0.6. And we land right on the dot. That took 6 jumps.',
        beats: [
          { say: 'Now we hop. Start at 0 and go one tenth at a time.', pic: 0 },
          { say: '0.1, 0.2, 0.3, 0.4, 0.5, 0.6. And we land right on the dot.' },
          { say: 'That took 6 jumps.', write: 'Jumps: 6' },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 10, points: [{ at: 0.6 }], motion: true,
          jumps: [0, 1, 2, 3, 4, 5].map(k => ({ from: k / 10, to: (k + 1) / 10 })) }] },
      { title: 'Name the dot', text: '6 jumps, and each one is worth 0.1. That makes 0.6. So you have walked 0.6 of a mile to get to that dot.',
        beats: [
          { say: '6 jumps, and each one is worth 0.1. That makes 0.6.', pic: 0 },
          { say: 'So you have walked 0.6 of a mile to get to that dot.' },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 10, labels: 'ends', points: [{ at: 0.6, label: '0.6' }] }] },
      { title: 'One thing not to do', text: "Here is where this one goes wrong. Don't count the marks. Count the jumps. That mark at 0 is where you started. It is not a jump.",
        beats: [
          { say: 'Here is where this one goes wrong.' },
          { say: "Don't count the marks. Count the jumps.", pic: 0 },
          { say: 'That mark at 0 is where you started. It is not a jump.' },
        ],
        pictures: [{ kind: 'cards', wrong: '7 marks, so 0.7', right: '6 jumps, so 0.6' }] },
    ],
    turn: {
      text: 'What number is at the dot?',
      picture: line(0, 1, 0.4),
      answer: 0.4, steps: ['There are 10 equal jumps from 0 to 1, so each jump is 0.1.', 'Count the jumps from 0 to the dot: 4 jumps.', 'So the dot is at 0.4.'],
      prompt: 'Find what one jump is worth. Then count the jumps from 0.',
      hint1: 'How many equal jumps are there from 0 to 1? What is each one worth?',
      hint2: 'Each jump is 0.1. Count the jumps from 0 to the dot.',
      twin: { text: 'This line goes from 1 to 2. What number is at the dot?',
        picture: line(1, 2, 1.3),
        answer: 1.3, steps: ['There are 10 equal jumps from 1 to 2, so each jump is 0.1.', 'Start at 1 and count 3 jumps to the dot.', 'So the dot is at 1.3.'],
        hint1: 'This line starts at 1, not 0. What is each jump worth?',
        hint2: 'Start at 1. Count the jumps to the dot, adding one tenth each time.' },
    },
    won: { text: 'You found what one jump is worth, then counted the jumps.', sticker: 'The marks between two whole numbers name decimals. Each of the 10 equal jumps is one tenth.' },
    twinWon: { text: 'You started at 1 and counted jumps of 0.1 to 1.3.', sticker: 'The marks between two whole numbers name decimals. Each equal jump is one tenth.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What number is at the dot?',
        picture: line(0, 1, 0.8), answer: 0.8,
        steps: ['Each of the 10 jumps is 0.1.', 'Count from 0 to the dot: 8 jumps.', 'So the dot is at 0.8.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What number is at the dot?',
        picture: line(0, 1, 0.2), answer: 0.2,
        steps: ['Each of the 10 jumps is 0.1.', 'Count from 0 to the dot: 2 jumps.', 'So the dot is at 0.2.'] } },
      { why: 'Still "count the jumps"', problem: { text: 'This line goes from 1 to 2. What number is at the dot?',
        picture: line(1, 2, 1.7), answer: 1.7,
        steps: ['There are 10 equal jumps from 1 to 2, so each jump is 0.1.', 'Start at 1 and count 7 jumps to the dot.', 'So the dot is at 1.7.'] } },
      { why: 'A little harder', problem: { text: 'This line goes from 0.2 to 0.3. What number is at the dot?',
        picture: line(0.2, 0.3, 0.26), answer: 0.26,
        steps: ['There are 10 equal jumps from 0.2 to 0.3, so each jump is one hundredth, 0.01.', 'Start at 0.2 and count 6 jumps: 0.21, 0.22, 0.23, 0.24, 0.25 and one more.', 'So the dot is at 0.26.'] } },
      { why: 'Same math in a story', problem: { text: 'This part of a bike trail goes from mile 1 to mile 2. Ava stops at the dot. How many miles along the trail is she?',
        picture: line(1, 2, 1.4), answer: 1.4,
        steps: ['There are 10 equal jumps from 1 to 2, so each jump is 0.1 of a mile.', 'Start at 1 and count 4 jumps to the dot.', 'So Ava is 1.4 miles along the trail.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m6-t5', title: 'Compare decimals', skill: 'Compare two decimals to hundredths with <, > or =',
    bigIdea: 'Compare the tenths first. The number with more tenths is bigger, no matter how many digits come after.',
    screens: [
      { title: 'Who drank more?', text: 'Two bottles of juice are the same size. Kim drinks 0.5 of hers. Raj drinks 0.45 of his. Who drinks more?',
        pictures: [hund(50), hund(45)] },
      { title: 'Longer is not bigger', text: 'Put the two numbers side by side. 0.45 is longer, and 45 is more than 5, so it looks like the bigger drink. But the digits after the point are not whole numbers. They are pieces of one bottle.',
        beats: [
          { say: 'Put the two numbers side by side.', pic: 0 },
          { say: '0.45 is longer, and 45 is more than 5, so it looks like the bigger drink.' },
          { say: 'But the digits after the point are not whole numbers. They are pieces of one bottle.' },
        ],
        pictures: [{ kind: 'eq', text: '0.5 ? 0.45' }] },
      { title: 'The big idea', text: 'Compare the tenths first. The number with more tenths is bigger, no matter how many digits come after.',
        beats: [
          { say: 'Compare the tenths first.', pic: 0 },
          { say: 'The number with more tenths is bigger, no matter how many digits come after.', pic: 1 },
        ],
        pictures: [hund(50), hund(45)] },
      { title: 'Tenths first', text: "So look only at the tenths, which are the full columns. Kim's 0.5 has 5 tenths, 5 whole columns. Raj's 0.45 has only 4 tenths. He gets 4 whole columns and a handful of loose squares.",
        beats: [
          { say: 'So look only at the tenths, which are the full columns.', write: 'tenths = the full columns' },
          { say: "Kim's 0.5 has 5 tenths, 5 whole columns.", pic: 0 },
          { say: "Raj's 0.45 has only 4 tenths. He gets 4 whole columns and a handful of loose squares.", pic: 1 },
        ],
        pictures: [hund(50, true), hund(45, true)] },
      { title: 'Line them up', text: 'There is another way to see it. Both bottles, counted in little squares. Write 0.5 as 0.50, so both numbers have two places. Now it is 50 hundredths against 45 hundredths.',
        beats: [
          { say: 'There is another way to see it.', pic: 0 },
          { say: 'Both bottles, counted in little squares.', pic: 1 },
          { say: 'Write 0.5 as 0.50, so both numbers have two places.', write: 'add a 0 → same number of places' },
          { say: 'Now it is 50 hundredths against 45 hundredths.', pic: 2 },
        ],
        pictures: [hund(50), hund(45), { kind: 'eq', text: '0.50 and 0.45', lines: ['50 hundredths and 45 hundredths'] }] },
      { title: 'Say it with a sign', text: 'Count them up. Kim has 50 squares. Raj has 45. So Kim has more, and now we say that with a sign. The open end always points at the bigger number. Kim drinks more.',
        beats: [
          { say: 'Count them up. Kim has 50 squares.', pic: 0 },
          { say: 'Raj has 45.', pic: 1 },
          { say: 'So Kim has more, and now we say that with a sign.', pic: 2 },
          { say: 'The open end always points at the bigger number. Kim drinks more.', write: 'open end → the bigger number' },
        ],
        pictures: [hund(50), hund(45), { kind: 'eq', text: '0.5 > 0.45' }] },
      { title: 'One thing not to do', text: "Here is the mix-up. Don't just grab the number with more digits. Count the tenths first, every single time.",
        beats: [
          { say: 'Here is the mix-up.' },
          { say: "Don't just grab the number with more digits.", pic: 0 },
          { say: 'Count the tenths first, every single time.', write: 'tenths first, not the digit count' },
        ],
        pictures: [{ kind: 'cards', wrong: '0.45 > 0.5', right: '0.5 > 0.45' }] },
    ],
    turn: {
      text: 'Which sign goes between them? 0.6 ? 0.58',
      picture: { kind: 'eq', text: '0.6 ? 0.58' },
      answer: { choices: SIGNS, correct: 1 }, steps: ['0.6 has 6 tenths. 0.58 has 5 tenths.', '6 tenths is more than 5 tenths, so 0.6 is bigger.', 'So 0.6 > 0.58, and the sign is >.'],
      prompt: 'Look at the tenths first.',
      hint1: 'Look at the first number after the point in each one.',
      hint2: 'Write 0.6 as 0.60. Now compare 60 hundredths and 58 hundredths.',
      twin: { text: 'Which sign goes between them? 0.3 ? 0.35',
        picture: { kind: 'eq', text: '0.3 ? 0.35' },
        answer: { choices: SIGNS, correct: 0 }, steps: ['Both have 3 tenths, so look at the hundredths.', 'Write 0.3 as 0.30. 30 hundredths is less than 35 hundredths.', 'So 0.3 < 0.35, and the sign is <.'],
        hint1: 'Both have the same tenths. What do you check next?',
        hint2: 'Put a 0 at the end of 0.3 so both have two places. Then compare.' },
    },
    won: { text: 'You compared the tenths first, not the number of digits.', sticker: 'The tenths place is worth more than the hundredths place, so compare it first.' },
    twinWon: { text: 'You saw that 0.3 < 0.35 by looking at the hundredths.', sticker: 'The tenths place is worth more than the hundredths place, so compare it first.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which sign goes between them? 0.7 ? 0.69',
        picture: { kind: 'eq', text: '0.7 ? 0.69' }, answer: { choices: SIGNS, correct: 1 },
        steps: ['0.7 has 7 tenths. 0.69 has 6 tenths.', '7 tenths is more.', 'So 0.7 > 0.69, and the sign is >.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Which sign goes between them? 0.24 ? 0.42',
        picture: { kind: 'eq', text: '0.24 ? 0.42' }, answer: { choices: SIGNS, correct: 0 },
        steps: ['0.24 has 2 tenths. 0.42 has 4 tenths.', '2 tenths is less than 4 tenths.', 'So 0.24 < 0.42, and the sign is <.'] } },
      { why: 'Still "tenths first"', problem: { text: 'Which sign goes between them? 0.8 ? 0.80',
        picture: { kind: 'eq', text: '0.8 ? 0.80' }, answer: { choices: SIGNS, correct: 2 },
        steps: ['Both have 8 tenths.', '0.8 is 0.80, so both have 0 hundredths too.', 'They are the same, so the sign is =.'] } },
      { why: 'A little harder', problem: { text: 'Which sign goes between them? 1.09 ? 1.1',
        picture: { kind: 'eq', text: '1.09 ? 1.1' }, answer: { choices: SIGNS, correct: 0 },
        steps: ['Both have 1 whole.', '1.09 has 0 tenths. 1.1 has 1 tenth.', 'So 1.09 < 1.1, and the sign is <.'] } },
      { why: 'Same math in a story', problem: { text: 'Leo jumps 1.4 meters. Ana jumps 1.35 meters. Who jumps farther?',
        picture: { kind: 'eq', text: '1.4 ? 1.35' }, answer: { choices: ['Leo', 'Ana', 'They tie'], correct: 0 },
        steps: ['Both jump 1 whole meter.', '1.4 has 4 tenths. 1.35 has 3 tenths. 4 tenths is more.', 'So 1.4 > 1.35, and Leo jumps farther.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m6-t6', title: 'Add tenths and hundredths', skill: 'Add a number of tenths and a number of hundredths',
    bigIdea: 'Change the tenths into hundredths first. Then add the hundredths.',
    screens: [
      { title: 'Painting a wall', text: 'A wall is split into 100 equal squares. Dad paints 3/10 of it. You paint 4/100 of it. How much of the wall is painted?',
        pictures: [hund(34)] },
      { title: 'Different sizes', text: 'Careful here. We cannot just add the 3 and the 4. A tenth is a whole column of this wall. A hundredth is one tiny square. Those two pieces are not the same size.',
        beats: [
          { say: 'Careful here. We cannot just add the 3 and the 4.', pic: 0 },
          { say: 'A tenth is a whole column of this wall. A hundredth is one tiny square.' },
          { say: 'Those two pieces are not the same size.', write: 'same size pieces → then add' },
        ],
        pictures: [hund(34)] },
      { title: 'The big idea', text: 'Change the tenths into hundredths first. Then add the hundredths.',
        beats: [
          { say: 'Change the tenths into hundredths first.', pic: 0 },
          { say: 'Then add the hundredths.' },
        ],
        pictures: [hund(34)] },
      { title: 'Tenths into hundredths', text: "Take one single column. It is 1/10 of the wall, and it holds 10 little squares. So one tenth is the very same thing as 10 hundredths. Dad painted 3 of those columns, so his 3 tenths are 30 squares. Same paint, counted a different way.",
        beats: [
          { say: 'Take one single column. It is 1/10 of the wall, and it holds 10 little squares.' },
          { say: 'So one tenth is the very same thing as 10 hundredths.', write: '1 tenth → 10 hundredths' },
          { say: 'Dad painted 3 of those columns, so his 3 tenths are 30 squares.', pic: 0 },
          { say: 'Same paint, counted a different way.', pic: 1 },
        ],
        pictures: [hund(30, true), { kind: 'eq', text: '3/10 = 30/100' }] },
      { title: 'Now add', text: "Now both parts are measured in the same little squares. Dad's 30, and your 4 more. Put them together and we have 34 squares out of 100.",
        beats: [
          { say: 'Now both parts are measured in the same little squares.', pic: 0 },
          { say: "Dad's 30, and your 4 more." },
          { say: 'Put them together and we have 34 squares out of 100.', pic: 1 },
        ],
        pictures: [hund(34, true), { kind: 'eq', text: '30/100 + 4/100 = 34/100' }] },
      { title: 'Write it with a point', text: "And 34 hundredths with a point is 0.34. Read those digits back to the wall. The 3 is Dad's 3 full columns, and the 4 is your 4 extra squares.",
        beats: [
          { say: 'And 34 hundredths with a point is 0.34.', pic: 0 },
          { say: 'Read those digits back to the wall.', pic: 1 },
          { say: "The 3 is Dad's 3 full columns, and the 4 is your 4 extra squares." },
        ],
        pictures: [hund(34), { kind: 'eq', text: '3/10 + 4/100 = 34/100 = 0.34' }] },
      { title: 'One thing not to do', text: "Here is the one to avoid. Don't add the top numbers and the bottom numbers. 10 and 100 are the sizes of the pieces, not amounts to add up. Change the tenths into hundredths first.",
        beats: [
          { say: 'Here is the one to avoid.' },
          { say: "Don't add the top numbers and the bottom numbers.", pic: 0 },
          { say: '10 and 100 are the sizes of the pieces, not amounts to add up. Change the tenths into hundredths first.' },
        ],
        pictures: [{ kind: 'cards', wrong: '3/10 + 4/100 = 7/110', right: '3/10 + 4/100 = 34/100' }] },
    ],
    turn: {
      text: 'Add. 2/10 + 5/100 = ?',
      picture: { kind: 'eq', text: '2/10 + 5/100 = ?' },
      answer: { frac: [25, 100] }, steps: ['2/10 is 2 columns of 10 squares, so 2/10 = 20/100.', 'Now add the hundredths: 20 and 5 more.', 'So 2/10 + 5/100 = 25/100, or 0.25.'],
      prompt: 'Change the tenths into hundredths. Then add.',
      hint1: 'Change 2/10 into hundredths first.',
      hint2: 'One tenth is 10 hundredths. So 2/10 is 20/100. Now add the 5.',
      twin: { text: 'Add. 6/10 + 7/100 = ?',
        picture: { kind: 'eq', text: '6/10 + 7/100 = ?' },
        answer: { frac: [67, 100] }, steps: ['6/10 is 6 columns of 10 squares, so 6/10 = 60/100.', 'Now add the hundredths: 60 and 7 more.', 'So 6/10 + 7/100 = 67/100, or 0.67.'],
        hint1: 'Change 6/10 into hundredths first.',
        hint2: 'Each tenth is 10 hundredths. How many hundredths is 6/10? Then add the 7.' },
    },
    won: { text: 'You changed the tenths into hundredths, then added.', sticker: 'The top number is the numerator and the bottom is the denominator. Add numerators only when the denominators match.' },
    twinWon: { text: 'You changed 6/10 into hundredths and found 67/100.', sticker: 'The top number is the numerator and the bottom is the denominator. Add numerators only when the denominators match.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Add. 4/10 + 3/100 = ?',
        picture: { kind: 'eq', text: '4/10 + 3/100 = ?' }, answer: { frac: [43, 100] },
        steps: ['4/10 = 40/100.', '40/100 + 3/100 = 43/100.', 'So the answer is 43/100.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Add, and write the answer as a decimal. 5/10 + 8/100 = ?',
        picture: { kind: 'eq', text: '5/10 + 8/100 = ?' }, answer: 0.58,
        steps: ['5/10 = 50/100.', '50/100 + 8/100 = 58/100.', 'So the sum is 0.58.'] } },
      { why: 'Still "tenths into hundredths"', problem: { text: 'Add. 9/100 + 7/10 = ?',
        picture: { kind: 'eq', text: '9/100 + 7/10 = ?' }, answer: { frac: [79, 100] },
        steps: ['The tenths can come second. Change them anyway: 7/10 = 70/100.', '9/100 + 70/100 = 79/100.', 'So the answer is 79/100.'] } },
      { why: 'A little harder', problem: { text: 'Add. 3/10 + 45/100 = ?',
        picture: { kind: 'eq', text: '3/10 + 45/100 = ?' }, answer: { frac: [75, 100] },
        steps: ['3/10 = 30/100.', '30/100 + 45/100 = 75/100.', 'So the answer is 75/100.'] } },
      { why: 'Same math in a story', problem: { text: 'Nia fills 4/10 of a jar with red beads and 25/100 of it with blue beads. How much of the jar is full? Write it as a decimal.',
        picture: blank, answer: 0.65,
        steps: ['4/10 = 40/100.', '40/100 + 25/100 = 65/100.', 'So 0.65 of the jar is full.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m6-t7', title: 'Money as decimals', skill: 'Write dollars and cents with a decimal point',
    bigIdea: 'A dollar is 100 cents, so cents are hundredths of a dollar. 2 dollars and 35 cents is $2.35.',
    screens: [
      { title: 'At the shop', text: 'You have 2 dollar bills, 3 dimes and 5 pennies. A toy costs $2.35. Do you have just enough?',
        pictures: [coins('2', '3', '5')] },
      { title: 'What does the tag mean?', text: 'Here is what you are holding. And here is the price tag. It does not say dollars anywhere, and it does not say cents. It just uses a point. So to read it, you have to know what each digit is counting.',
        beats: [
          { say: 'Here is what you are holding.', pic: 0 },
          { say: 'And here is the price tag.', pic: 1 },
          { say: 'It does not say dollars anywhere, and it does not say cents. It just uses a point.' },
          { say: 'So to read it, you have to know what each digit is counting.' },
        ],
        pictures: [coins('2', '3', '5'), { kind: 'eq', text: '$2.35' }] },
      { title: 'The big idea', text: 'A dollar is 100 cents, so cents are hundredths of a dollar. 2 dollars and 35 cents is $2.35.',
        beats: [
          { say: 'A dollar is 100 cents, so cents are hundredths of a dollar.', pic: 0 },
          { say: '2 dollars and 35 cents is $2.35.' },
        ],
        pictures: [coins('2', '3', '5')] },
      { title: 'A dime is one tenth', text: 'Start with the dimes. It takes 10 dimes to make 1 dollar, so a single dime is one tenth of a dollar. And a tenth goes right after the point.',
        beats: [
          { say: 'Start with the dimes.', pic: 0 },
          { say: 'It takes 10 dimes to make 1 dollar, so a single dime is one tenth of a dollar.', pic: 1 },
          { say: 'And a tenth goes right after the point.', write: 'dimes → first place after the point' },
        ],
        pictures: [coins('2', '3', '5', [[0, 1]]), { kind: 'eq', text: '1 dime = $0.10' }] },
      { title: 'A penny is one hundredth', text: 'Now the pennies. It takes 100 pennies to make 1 dollar, so one penny is one hundredth of a dollar. Hundredths live in the second place.',
        beats: [
          { say: 'Now the pennies.', pic: 0 },
          { say: 'It takes 100 pennies to make 1 dollar, so one penny is one hundredth of a dollar.', pic: 1 },
          { say: 'Hundredths live in the second place.', write: 'pennies → second place after the point' },
        ],
        pictures: [coins('2', '3', '5', [[0, 2]]), { kind: 'eq', text: '1 penny = $0.01' }] },
      { title: 'Read the price', text: 'So write your money in that order. The dollars, then the point, then the dimes, then the pennies. That comes out as $2.35, which is exactly what the tag says. You have just enough.',
        beats: [
          { say: 'So write your money in that order.', pic: 0 },
          { say: 'The dollars, then the point, then the dimes, then the pennies.' },
          { say: 'That comes out as $2.35, which is exactly what the tag says.', pic: 1 },
          { say: 'You have just enough.' },
        ],
        pictures: [coins('2', '3', '5'), { kind: 'eq', text: '2 dollars, 3 dimes, 5 pennies', lines: ['$2.35'] }] },
      { title: 'One thing not to do', text: "Here is the slip that costs you money. Don't write 5 cents as $0.5. That first place belongs to the dimes, so $0.5 is 5 dimes, which is 50 cents. 5 cents is $0.05.",
        beats: [
          { say: 'Here is the slip that costs you money.' },
          { say: "Don't write 5 cents as $0.5.", pic: 0 },
          { say: 'That first place belongs to the dimes, so $0.5 is 5 dimes, which is 50 cents. 5 cents is $0.05.' },
        ],
        pictures: [{ kind: 'cards', wrong: '5 cents = $0.5', right: '5 cents = $0.05' }] },
    ],
    turn: {
      text: 'You have 4 dollars, 1 dime and 7 pennies. How much money is that?',
      picture: coins('4', '1', '7'),
      answer: 4.17, steps: ['The 4 dollars go before the point.', '1 dime is 1 tenth of a dollar. 7 pennies are 7 hundredths.', 'So it is $4.17.'],
      prompt: 'Dollars, then the point, then dimes, then pennies.',
      hint1: 'What goes before the point? What goes right after it?',
      hint2: 'Dimes go in the first place after the point. Pennies go in the second.',
      twin: { text: 'You have 3 dollars, 6 dimes and 2 pennies. How much money is that?',
        picture: coins('3', '6', '2'),
        answer: 3.62, steps: ['The 3 dollars go before the point.', '6 dimes are 6 tenths of a dollar. 2 pennies are 2 hundredths.', 'So it is $3.62.'],
        hint1: 'Start with the dollars. Where do they go?',
        hint2: 'After the point, write the dimes first, then the pennies.' },
    },
    won: { text: 'You put the dollars, dimes and pennies in their places.', sticker: 'The point between dollars and cents is the decimal point. Cents are hundredths of a dollar.' },
    twinWon: { text: 'You put the dimes and pennies in their places and wrote $3.62.', sticker: 'The point between dollars and cents is the decimal point. Cents are hundredths of a dollar.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'You have 1 dollar, 4 dimes and 8 pennies. How much money is that?',
        picture: coins('1', '4', '8'), answer: 1.48,
        steps: ['The 1 dollar goes before the point.', '4 dimes are 4 tenths. 8 pennies are 8 hundredths.', 'So it is $1.48.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Write 5 dollars and 26 cents with a point, like $2.35.',
        picture: { kind: 'table', head: ['Dollars', 'Cents'], rows: [['5', '26']] }, answer: 5.26,
        steps: ['The 5 dollars go before the point.', '26 cents are 26 hundredths of a dollar, so they take the two places after the point.', 'So it is $5.26.'] } },
      { why: 'Still "cents are hundredths"', problem: { text: 'Write 6 dollars and 3 cents with a point.',
        picture: { kind: 'table', head: ['Dollars', 'Cents'], rows: [['6', '3']] }, answer: 6.03,
        steps: ['3 cents is 3 hundredths of a dollar.', 'There are no dimes, so a 0 goes right after the point.', 'So it is $6.03.'] } },
      { why: 'A little harder', problem: { text: 'How many cents is $3.45?',
        picture: { kind: 'eq', text: '$3.45 = ? cents' }, answer: 345,
        steps: ['Each dollar is 100 cents, so 3 dollars is 300 cents.', 'The .45 is 45 cents.', 'So $3.45 is 345 cents.'] } },
      { why: 'Same math in a story', problem: { text: 'A book costs 8 dollars and 15 cents. What does its price tag say?',
        picture: { kind: 'table', head: ['Dollars', 'Cents'], rows: [['8', '15']] }, answer: 8.15,
        steps: ['The 8 dollars go before the point.', '15 cents take the two places after the point.', 'So the tag says $8.15.'] } },
    ],
  },
]
