/**
 * Grade 4 · Module 6 — Place value for decimal fractions.
 * Written to docs/new-flow/AUTHORING.md. Topic 1 is the founder's own Grade 4 example (tenths as decimals).
 */
import type { Lesson, Picture } from '../script'

/** A 10 × 10 hundredths grid with `n` squares shaded: full columns first (tone 1), then the rest of the next column (tone 2). */
const hund = (n: number, motion = false): Picture => {
  const cols = Math.floor(n / 10), extra = n % 10
  const shade: { r: number; c: number; h: number; w: number; tone?: 1 | 2 }[] = []
  if (cols) shade.push({ r: 0, c: 0, h: 10, w: cols, tone: 1 })
  if (extra) shade.push({ r: 0, c: cols, h: extra, w: 1, tone: 2 })
  return { kind: 'grid', rows: 10, cols: 10, shade, motion }
}
const blank: Picture = { kind: 'grid', rows: 10, cols: 10 }
const bar = (shaded: number, label?: string, motion = false): Picture => ({ kind: 'bars', bars: [{ parts: 10, shaded, label }], motion })
const line = (min: number, max: number, at?: number): Picture =>
  ({ kind: 'numline', min, max, ticks: 10, labels: 'ends', points: at === undefined ? [] : [{ at }] })
const coins = (d: string, dimes: string, p: string, mark?: [number, number][]): Picture =>
  ({ kind: 'table', head: ['Dollars', 'Dimes', 'Pennies'], rows: [[d, dimes, p]], mark, motion: !!mark })
const SIGNS = ['<', '>', '=']

export const G4M6: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m6-t1', title: 'Tenths as decimals', skill: 'Write tenths as a fraction and as a decimal',
    bigIdea: 'The first number after the point means tenths. So 3/10 is 0.3.',
    screens: [
      { title: 'A bar of chocolate', text: 'A chocolate bar is cut into 10 equal strips. You have 3 strips. How much of the bar is that?',
        pictures: [bar(3)] },
      { title: 'Signs use a point', text: 'You know 3 out of 10 is 3/10. But a price tag or a scale does not show a fraction. It shows a number with a point in it.',
        pictures: [bar(3, '3/10')] },
      { title: 'The big idea', text: 'The first number after the point means tenths. So 3/10 is 0.3.',
        pictures: [bar(3)] },
      { title: 'One strip is one tenth', text: 'The bar is cut into 10 equal strips. One strip is one tenth of the bar. We write it 1/10, or 0.1.',
        pictures: [bar(1, '1/10', true), { kind: 'eq', text: '1/10 = 0.1' }] },
      { title: 'Count the strips', text: 'Count the shaded strips: 1, 2, 3. That is 3 tenths.',
        pictures: [bar(3, undefined, true), { kind: 'eq', text: '3 tenths' }] },
      { title: 'Write it with a point', text: '3 tenths is 3/10. With a point it is 0.3. Same amount, two ways to write it.',
        pictures: [bar(3, '0.3'), { kind: 'eq', text: '3/10 = 0.3' }] },
      { title: 'One thing not to do', text: "Don't write 0.03 for 3 strips. 0.03 is much smaller. Tenths go right after the point.",
        pictures: [{ kind: 'cards', wrong: '3/10 = 0.03', right: '3/10 = 0.3' }] },
    ],
    turn: {
      text: 'A bar is cut into 10 equal strips. You have 0.4 of the bar. Write it as a fraction.',
      picture: bar(0),
      answer: { frac: [4, 10] }, steps: ['The first number after the point means tenths.', '0.4 is 4 tenths, that is 4 strips out of 10.', 'So 0.4 is 4/10.'],
      prompt: 'The number after the point tells how many strips. The bar has 10 strips.',
      hint1: 'The first number after the point tells how many tenths.',
      hint2: 'Each strip is 1/10. How many strips is 0.4?',
      twin: { text: 'A bar is cut into 10 equal strips. 7 strips are shaded. Write the shaded part as a decimal.',
        picture: bar(7),
        answer: 0.7, steps: ['The bar has 10 equal strips, so each strip is one tenth.', '7 strips are 7 tenths, which is 7/10.', 'So the shaded part is 0.7.'],
        hint1: 'How many equal strips is the bar cut into? How many are shaded?',
        hint2: 'Each shaded strip is one tenth. The number of tenths goes right after the point.' },
    },
    won: { text: 'You read the tenths and wrote them as a fraction.', sticker: 'A number with a point in it is a decimal. The first place after the point is the tenths place.' },
    twinWon: { text: 'You counted 7 tenths and wrote 0.7.', sticker: 'A number with a point in it is a decimal. The first place after the point is the tenths place.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A bar is cut into 10 equal strips. 6 strips are shaded. Write the shaded part as a decimal.',
        picture: bar(6), answer: 0.6,
        steps: ['Each strip is one tenth.', '6 strips are 6 tenths, or 6/10.', 'So the shaded part is 0.6.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Write 9/10 as a decimal.',
        picture: bar(0, '9/10'), answer: 0.9,
        steps: ['9/10 is 9 tenths.', 'Tenths go right after the point.', 'So 9/10 is 0.9.'] } },
      { why: 'Still "tenths go after the point"', problem: { text: 'Write 0.2 as a fraction with 10 on the bottom.',
        picture: bar(0), answer: { frac: [2, 10] },
        steps: ['The 2 is right after the point, so it means 2 tenths.', '2 tenths is 2 strips out of 10.', 'So 0.2 is 2/10.'] } },
      { why: 'A little harder', problem: { text: 'A bar has 10 equal strips. The shaded strips are eaten. What part of the bar is left, as a decimal?',
        picture: bar(4), answer: 0.6,
        steps: ['4 of the 10 strips are eaten.', '10 − 4 = 6 strips are left. That is 6 tenths.', 'So 0.6 of the bar is left.'] } },
      { why: 'Same math in a story', problem: { text: 'A ribbon is cut into 10 equal pieces. Lily uses 5 pieces for a bow. What part of the ribbon does she use, as a decimal?',
        picture: bar(0), answer: 0.5,
        steps: ['Each piece is one tenth of the ribbon.', '5 pieces are 5 tenths, or 5/10.', 'So Lily uses 0.5 of the ribbon.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m6-t2', title: 'Hundredths as decimals', skill: 'Write hundredths as a fraction and as a decimal',
    bigIdea: 'The second number after the point means hundredths. So 25/100 is 0.25.',
    screens: [
      { title: 'A sheet of stickers', text: 'A sheet has 100 small square stickers, in 10 rows of 10. 25 of them are used. How much of the sheet is used?',
        pictures: [hund(25)] },
      { title: 'Tenths are too big', text: 'One full column is one tenth. But 25 squares is more than 2 columns and less than 3. Tenths alone cannot say it.',
        pictures: [hund(25)] },
      { title: 'The big idea', text: 'The second number after the point means hundredths. So 25/100 is 0.25.',
        pictures: [hund(25)] },
      { title: 'One square is one hundredth', text: 'The sheet has 100 equal squares. One square is one hundredth of the sheet. We write it 1/100, or 0.01.',
        pictures: [{ kind: 'grid', rows: 10, cols: 10, shade: [{ r: 0, c: 0, h: 1, w: 1, tone: 2 }], motion: true }, { kind: 'eq', text: '1/100 = 0.01' }] },
      { title: 'Count the squares', text: 'Count full columns by 10s: 10, 20. Then 5 more squares: 25. That is 25 hundredths.',
        pictures: [hund(25, true), { kind: 'eq', text: '25 hundredths' }] },
      { title: 'Write it with a point', text: '25 hundredths is 25/100. With a point it is 0.25. The 2 counts the full columns. The 5 counts the extra squares.',
        pictures: [hund(25), { kind: 'eq', text: '25/100 = 0.25' }] },
      { title: 'One thing not to do', text: "Don't write 2.5. That is more than 2 whole sheets. Hundredths need two places after the point.",
        pictures: [{ kind: 'cards', wrong: '25/100 = 2.5', right: '25/100 = 0.25' }] },
    ],
    turn: {
      text: 'This grid has 100 equal squares. What part is shaded, as a decimal?',
      picture: hund(37),
      answer: 0.37, steps: ['The grid has 100 equal squares, so each square is one hundredth.', 'Count full columns: 10, 20, 30. Then 7 more makes 37.', '37 hundredths is 37/100, so the shaded part is 0.37.'],
      prompt: 'Count the shaded squares. Then write the hundredths after the point.',
      hint1: 'How many squares are shaded? Count full columns by 10s first.',
      hint2: 'Each full column is 10 squares. Count the columns, then add the extra squares.',
      twin: { text: 'This grid has 100 equal squares. What part is shaded, as a decimal?',
        picture: hund(62),
        answer: 0.62, steps: ['Each square is one hundredth.', 'Count full columns: 10, 20, 30, 40, 50, 60. Then 2 more makes 62.', '62 hundredths is 62/100, so the shaded part is 0.62.'],
        hint1: 'Count the full columns by 10s first.',
        hint2: 'After the full columns, add the squares in the column that is not full.' },
    },
    won: { text: 'You counted hundredths and wrote them with two places after the point.', sticker: 'The second place after the point is the hundredths place.' },
    twinWon: { text: 'You counted the shaded squares out of 100 and wrote 0.62.', sticker: 'The second place after the point is the hundredths place.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'This grid has 100 equal squares. What part is shaded, as a decimal?',
        picture: hund(48), answer: 0.48,
        steps: ['Each square is one hundredth.', '4 full columns is 40. Then 8 more makes 48.', 'So the shaded part is 0.48.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Write 71/100 as a decimal.',
        picture: blank, answer: 0.71,
        steps: ['71/100 is 71 hundredths.', 'That is 7 tenths and 1 hundredth.', 'So 71/100 is 0.71.'] } },
      { why: 'Still "two places for hundredths"', problem: { text: 'Write 9/100 as a decimal.',
        picture: blank, answer: 0.09,
        steps: ['9/100 is 9 hundredths and no tenths.', 'Put 0 in the first place after the point and 9 in the second.', 'So 9/100 is 0.09.'] } },
      { why: 'A little harder', problem: { text: 'Write 0.56 as a fraction with 100 on the bottom.',
        picture: blank, answer: { frac: [56, 100] },
        steps: ['0.56 has two places after the point, so it counts hundredths.', 'It is 56 hundredths.', 'So 0.56 is 56/100.'] } },
      { why: 'Same math in a story', problem: { text: 'A box holds 100 crayons. 83 of them are blue. What part of the box is blue, as a decimal?',
        picture: blank, answer: 0.83,
        steps: ['Each crayon is one hundredth of the box.', '83 crayons are 83 hundredths, or 83/100.', 'So 0.83 of the box is blue.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m6-t3', title: '0.5 is the same as 0.50', skill: 'A zero at the end of a decimal does not change its value',
    bigIdea: 'A 0 at the end does not change the amount. 5 tenths and 50 hundredths cover the same space.',
    screens: [
      { title: 'A tray of brownies', text: 'A tray of brownies is cut into 100 small squares. Ana eats the shaded part. Ben says she ate 0.5 of the tray. Ana says 0.50. Who is right?',
        pictures: [hund(50)] },
      { title: 'They look different', text: '0.50 has more digits than 0.5, and 50 is much more than 5. So it is easy to think 0.50 is more.',
        pictures: [{ kind: 'eq', text: '0.5 and 0.50' }] },
      { title: 'The big idea', text: 'A 0 at the end does not change the amount. 5 tenths and 50 hundredths cover the same space.',
        pictures: [hund(50)] },
      { title: 'Count the columns', text: 'Each column is one tenth. 5 columns are shaded. That is 5 tenths, or 0.5.',
        pictures: [hund(50, true), { kind: 'eq', text: '5 tenths = 0.5' }] },
      { title: 'Count the squares', text: 'Now count the small squares. 5 columns of 10 is 50 squares. That is 50 hundredths, or 0.50.',
        pictures: [hund(50), { kind: 'eq', text: '50 hundredths = 0.50' }] },
      { title: 'Same space, two names', text: 'It is the same shading both times. So 0.5 = 0.50. Both are right. The 0 at the end just says there are no extra squares.',
        pictures: [hund(50), { kind: 'eq', text: '0.5 = 0.50' }] },
      { title: 'One thing not to do', text: "Don't think 0.50 is bigger because 50 is more than 5. They cover the very same squares.",
        pictures: [{ kind: 'cards', wrong: '0.50 > 0.5', right: '0.50 = 0.5' }] },
    ],
    turn: {
      text: 'You shade 0.7 of a 100-square grid. How many small squares do you shade?',
      picture: blank,
      answer: 70, steps: ['0.7 is 7 tenths, and each tenth is a column of 10 squares.', '7 columns of 10 squares is 70 squares.', 'So 0.7 is 70 squares, or 0.70.'],
      prompt: 'Each tenth is one full column. Count the squares in those columns.',
      hint1: 'How many columns is 0.7? Each column is one tenth.',
      hint2: 'Each column has 10 squares. Count by 10s, once for each column.',
      twin: { text: 'You shade 0.3 of a 100-square grid. How many small squares do you shade?',
        picture: blank,
        answer: 30, steps: ['0.3 is 3 tenths, which is 3 columns.', 'Each column has 10 squares, so 3 columns is 10, 20, 30 squares.', 'So 0.3 is 30 squares, or 0.30.'],
        hint1: 'How many full columns is 0.3?',
        hint2: 'Each column has 10 squares. Count by 10s for each column.' },
    },
    won: { text: 'You saw that tenths and hundredths can name the same amount.', sticker: 'Decimals that name the same amount, like 0.5 and 0.50, are equivalent decimals.' },
    twinWon: { text: 'You saw that 0.3 is 30 small squares.', sticker: 'Decimals that name the same amount are called equivalent decimals.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'You shade 0.6 of a 100-square grid. How many small squares do you shade?',
        picture: blank, answer: 60,
        steps: ['0.6 is 6 tenths, which is 6 columns.', '6 columns of 10 squares is 60 squares.', 'So 0.6 is 60 squares.'] } },
      { why: 'Same idea, new numbers', problem: { text: '0.40 of a 100-square grid is shaded. How many full columns of 10 is that?',
        picture: blank, answer: 4,
        steps: ['0.40 is 40 hundredths, which is 40 squares.', 'Each column has 10 squares, so 40 squares fill 4 columns.', 'So 0.40 is 4 columns, the same as 0.4.'] } },
      { why: 'Still "a 0 at the end changes nothing"', problem: { text: 'Which sign goes between them? 0.9 ? 0.90',
        picture: { kind: 'eq', text: '0.9 ? 0.90' }, answer: { choices: SIGNS, correct: 2 },
        steps: ['0.9 is 9 tenths, which is 9 full columns.', '0.90 is 90 hundredths, which is the same 9 columns.', 'They are the same amount, so the sign is =.'] } },
      { why: 'A little harder', problem: { text: 'The shaded part of this 100-square grid is 20 hundredths. Write it as a decimal with just one place after the point.',
        picture: hund(20), answer: 0.2,
        steps: ['20 hundredths is 0.20.', 'The 0 at the end changes nothing.', 'So it is 0.2.'] } },
      { why: 'Same math in a story', problem: { text: 'A garden has 100 equal beds. 0.8 of the garden has beans. How many beds have beans?',
        picture: blank, answer: 80,
        steps: ['0.8 is 8 tenths, the same as 80 hundredths.', 'Each hundredth is 1 bed out of 100.', 'So 80 beds have beans.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m6-t4', title: 'Decimals on a number line', skill: 'Name a point on a number line in tenths or hundredths',
    bigIdea: 'Cut the space from 0 to 1 into 10 equal jumps. Each jump is 0.1.',
    screens: [
      { title: 'A walk to the park', text: 'The park is 1 mile away. You stop at the dot. How far have you walked?',
        pictures: [line(0, 1, 0.6)] },
      { title: 'Only two numbers', text: 'The line only shows 0 and 1. The dot is between them, so it is not a whole number. The marks in between need names.',
        pictures: [line(0, 1, 0.6)] },
      { title: 'The big idea', text: 'Cut the space from 0 to 1 into 10 equal jumps. Each jump is 0.1.',
        pictures: [line(0, 1)] },
      { title: 'Count the jumps', text: 'There are 10 equal jumps from 0 to 1. So each jump is one tenth of a mile, or 0.1.',
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 10, labels: 'ends', jumps: [{ from: 0, to: 0.1, label: '0.1' }], motion: true }] },
      { title: 'Jump to the dot', text: 'Start at 0. Jump 0.1 at a time: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6. That is 6 jumps.',
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 10, points: [{ at: 0.6 }], motion: true,
          jumps: [0, 1, 2, 3, 4, 5].map(k => ({ from: k / 10, to: (k + 1) / 10 })) }] },
      { title: 'Name the dot', text: '6 jumps of 0.1 is 0.6. You have walked 0.6 of a mile.',
        pictures: [{ kind: 'numline', min: 0, max: 1, ticks: 10, labels: 'ends', points: [{ at: 0.6, label: '0.6' }] }] },
      { title: 'One thing not to do', text: "Don't count the marks. Count the jumps. The mark at 0 is where you start, not a jump.",
        pictures: [{ kind: 'cards', wrong: '7 marks, so 0.7', right: '6 jumps, so 0.6' }] },
    ],
    turn: {
      text: 'What number is at the dot?',
      picture: line(0, 1, 0.4),
      answer: 0.4, steps: ['There are 10 equal jumps from 0 to 1, so each jump is 0.1.', 'Count the jumps from 0 to the dot: 4 jumps.', 'So the dot is at 0.4.'],
      prompt: 'Find what one jump is worth. Then count the jumps from 0.',
      hint1: 'How many equal jumps are there from 0 to 1? What is each one worth?',
      hint2: 'Each jump is 0.1. Count the jumps from 0 to the dot.',
      twin: { text: 'This line goes from 1 to 2. What number is at the dot?',
        picture: line(1, 2, 1.3),
        answer: 1.3, steps: ['There are 10 equal jumps from 1 to 2, so each jump is 0.1.', 'Start at 1 and count 3 jumps to the dot.', 'So the dot is at 1.3.'],
        hint1: 'This line starts at 1, not 0. What is each jump worth?',
        hint2: 'Start at 1. Count the jumps to the dot, adding one tenth each time.' },
    },
    won: { text: 'You found what one jump is worth, then counted the jumps.', sticker: 'The marks between two whole numbers name decimals. Each of the 10 equal jumps is one tenth.' },
    twinWon: { text: 'You started at 1 and counted jumps of 0.1 to 1.3.', sticker: 'The marks between two whole numbers name decimals. Each equal jump is one tenth.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What number is at the dot?',
        picture: line(0, 1, 0.8), answer: 0.8,
        steps: ['Each of the 10 jumps is 0.1.', 'Count from 0 to the dot: 8 jumps.', 'So the dot is at 0.8.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What number is at the dot?',
        picture: line(0, 1, 0.2), answer: 0.2,
        steps: ['Each of the 10 jumps is 0.1.', 'Count from 0 to the dot: 2 jumps.', 'So the dot is at 0.2.'] } },
      { why: 'Still "count the jumps"', problem: { text: 'This line goes from 1 to 2. What number is at the dot?',
        picture: line(1, 2, 1.7), answer: 1.7,
        steps: ['There are 10 equal jumps from 1 to 2, so each jump is 0.1.', 'Start at 1 and count 7 jumps to the dot.', 'So the dot is at 1.7.'] } },
      { why: 'A little harder', problem: { text: 'This line goes from 0.2 to 0.3. What number is at the dot?',
        picture: line(0.2, 0.3, 0.26), answer: 0.26,
        steps: ['There are 10 equal jumps from 0.2 to 0.3, so each jump is one hundredth, 0.01.', 'Start at 0.2 and count 6 jumps: 0.21, 0.22, 0.23, 0.24, 0.25 and one more.', 'So the dot is at 0.26.'] } },
      { why: 'Same math in a story', problem: { text: 'This part of a bike trail goes from mile 1 to mile 2. Ava stops at the dot. How many miles along the trail is she?',
        picture: line(1, 2, 1.4), answer: 1.4,
        steps: ['There are 10 equal jumps from 1 to 2, so each jump is 0.1 of a mile.', 'Start at 1 and count 4 jumps to the dot.', 'So Ava is 1.4 miles along the trail.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m6-t5', title: 'Compare decimals', skill: 'Compare two decimals to hundredths with <, > or =',
    bigIdea: 'Compare the tenths first. The number with more tenths is bigger, no matter how many digits come after.',
    screens: [
      { title: 'Who drank more?', text: 'Two bottles of juice are the same size. Kim drinks 0.5 of hers. Raj drinks 0.45 of his. Who drinks more?',
        pictures: [hund(50), hund(45)] },
      { title: 'Longer is not bigger', text: '0.45 has more digits, and 45 is more than 5. So it looks bigger. But the digits after the point are not whole numbers.',
        pictures: [{ kind: 'eq', text: '0.5 ? 0.45' }] },
      { title: 'The big idea', text: 'Compare the tenths first. The number with more tenths is bigger, no matter how many digits come after.',
        pictures: [hund(50), hund(45)] },
      { title: 'Tenths first', text: '0.5 has 5 tenths: 5 full columns. 0.45 has only 4 tenths: 4 full columns and a few extra squares.',
        pictures: [hund(50, true), hund(45, true)] },
      { title: 'Line them up', text: 'Write 0.5 as 0.50, so both have two places. Now it is 50 hundredths against 45 hundredths.',
        pictures: [hund(50), hund(45), { kind: 'eq', text: '0.50 and 0.45', lines: ['50 hundredths and 45 hundredths'] }] },
      { title: 'Say it with a sign', text: '50 is more than 45, so 0.5 is more. We write 0.5 > 0.45. Kim drinks more.',
        pictures: [hund(50), hund(45), { kind: 'eq', text: '0.5 > 0.45' }] },
      { title: 'One thing not to do', text: "Don't pick the number with more digits. Compare the tenths first.",
        pictures: [{ kind: 'cards', wrong: '0.45 > 0.5', right: '0.5 > 0.45' }] },
    ],
    turn: {
      text: 'Which sign goes between them? 0.6 ? 0.58',
      picture: { kind: 'eq', text: '0.6 ? 0.58' },
      answer: { choices: SIGNS, correct: 1 }, steps: ['0.6 has 6 tenths. 0.58 has 5 tenths.', '6 tenths is more than 5 tenths, so 0.6 is bigger.', 'So 0.6 > 0.58, and the sign is >.'],
      prompt: 'Look at the tenths first.',
      hint1: 'Look at the first number after the point in each one.',
      hint2: 'Write 0.6 as 0.60. Now compare 60 hundredths and 58 hundredths.',
      twin: { text: 'Which sign goes between them? 0.3 ? 0.35',
        picture: { kind: 'eq', text: '0.3 ? 0.35' },
        answer: { choices: SIGNS, correct: 0 }, steps: ['Both have 3 tenths, so look at the hundredths.', 'Write 0.3 as 0.30. 30 hundredths is less than 35 hundredths.', 'So 0.3 < 0.35, and the sign is <.'],
        hint1: 'Both have the same tenths. What do you check next?',
        hint2: 'Put a 0 at the end of 0.3 so both have two places. Then compare.' },
    },
    won: { text: 'You compared the tenths first, not the number of digits.', sticker: 'The tenths place is worth more than the hundredths place, so compare it first.' },
    twinWon: { text: 'You saw that 0.3 < 0.35 by looking at the hundredths.', sticker: 'The tenths place is worth more than the hundredths place, so compare it first.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which sign goes between them? 0.7 ? 0.69',
        picture: { kind: 'eq', text: '0.7 ? 0.69' }, answer: { choices: SIGNS, correct: 1 },
        steps: ['0.7 has 7 tenths. 0.69 has 6 tenths.', '7 tenths is more.', 'So 0.7 > 0.69, and the sign is >.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Which sign goes between them? 0.24 ? 0.42',
        picture: { kind: 'eq', text: '0.24 ? 0.42' }, answer: { choices: SIGNS, correct: 0 },
        steps: ['0.24 has 2 tenths. 0.42 has 4 tenths.', '2 tenths is less than 4 tenths.', 'So 0.24 < 0.42, and the sign is <.'] } },
      { why: 'Still "tenths first"', problem: { text: 'Which sign goes between them? 0.8 ? 0.80',
        picture: { kind: 'eq', text: '0.8 ? 0.80' }, answer: { choices: SIGNS, correct: 2 },
        steps: ['Both have 8 tenths.', '0.8 is 0.80, so both have 0 hundredths too.', 'They are the same, so the sign is =.'] } },
      { why: 'A little harder', problem: { text: 'Which sign goes between them? 1.09 ? 1.1',
        picture: { kind: 'eq', text: '1.09 ? 1.1' }, answer: { choices: SIGNS, correct: 0 },
        steps: ['Both have 1 whole.', '1.09 has 0 tenths. 1.1 has 1 tenth.', 'So 1.09 < 1.1, and the sign is <.'] } },
      { why: 'Same math in a story', problem: { text: 'Leo jumps 1.4 meters. Ana jumps 1.35 meters. Who jumps farther?',
        picture: { kind: 'eq', text: '1.4 ? 1.35' }, answer: { choices: ['Leo', 'Ana', 'They tie'], correct: 0 },
        steps: ['Both jump 1 whole meter.', '1.4 has 4 tenths. 1.35 has 3 tenths. 4 tenths is more.', 'So 1.4 > 1.35, and Leo jumps farther.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m6-t6', title: 'Add tenths and hundredths', skill: 'Add a number of tenths and a number of hundredths',
    bigIdea: 'Change the tenths into hundredths first. Then add the hundredths.',
    screens: [
      { title: 'Painting a wall', text: 'A wall is split into 100 equal squares. Dad paints 3/10 of it. You paint 4/100 of it. How much of the wall is painted?',
        pictures: [hund(34)] },
      { title: 'Different sizes', text: 'You cannot just add 3 and 4. A tenth is a whole column. A hundredth is one tiny square. They are not the same size.',
        pictures: [hund(34)] },
      { title: 'The big idea', text: 'Change the tenths into hundredths first. Then add the hundredths.',
        pictures: [hund(34)] },
      { title: 'Tenths into hundredths', text: 'One column is 1/10, and it has 10 small squares. So 1/10 = 10/100. Dad’s 3 columns are 30 squares: 3/10 = 30/100.',
        pictures: [hund(30, true), { kind: 'eq', text: '3/10 = 30/100' }] },
      { title: 'Now add', text: 'Now both parts are hundredths. 30 squares and 4 more squares make 34 squares.',
        pictures: [hund(34, true), { kind: 'eq', text: '30/100 + 4/100 = 34/100' }] },
      { title: 'Write it with a point', text: '34/100 is 0.34. The 3 is Dad’s 3 columns. The 4 is your 4 extra squares.',
        pictures: [hund(34), { kind: 'eq', text: '3/10 + 4/100 = 34/100 = 0.34' }] },
      { title: 'One thing not to do', text: "Don't add the top numbers and the bottom numbers. Change the tenths into hundredths first.",
        pictures: [{ kind: 'cards', wrong: '3/10 + 4/100 = 7/110', right: '3/10 + 4/100 = 34/100' }] },
    ],
    turn: {
      text: 'Add. 2/10 + 5/100 = ?',
      picture: { kind: 'eq', text: '2/10 + 5/100 = ?' },
      answer: { frac: [25, 100] }, steps: ['2/10 is 2 columns of 10 squares, so 2/10 = 20/100.', 'Now add the hundredths: 20 and 5 more.', 'So 2/10 + 5/100 = 25/100, or 0.25.'],
      prompt: 'Change the tenths into hundredths. Then add.',
      hint1: 'Change 2/10 into hundredths first.',
      hint2: 'One tenth is 10 hundredths. So 2/10 is 20/100. Now add the 5.',
      twin: { text: 'Add. 6/10 + 7/100 = ?',
        picture: { kind: 'eq', text: '6/10 + 7/100 = ?' },
        answer: { frac: [67, 100] }, steps: ['6/10 is 6 columns of 10 squares, so 6/10 = 60/100.', 'Now add the hundredths: 60 and 7 more.', 'So 6/10 + 7/100 = 67/100, or 0.67.'],
        hint1: 'Change 6/10 into hundredths first.',
        hint2: 'Each tenth is 10 hundredths. How many hundredths is 6/10? Then add the 7.' },
    },
    won: { text: 'You changed the tenths into hundredths, then added.', sticker: 'The top number is the numerator and the bottom is the denominator. Add numerators only when the denominators match.' },
    twinWon: { text: 'You changed 6/10 into hundredths and found 67/100.', sticker: 'The top number is the numerator and the bottom is the denominator. Add numerators only when the denominators match.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Add. 4/10 + 3/100 = ?',
        picture: { kind: 'eq', text: '4/10 + 3/100 = ?' }, answer: { frac: [43, 100] },
        steps: ['4/10 = 40/100.', '40/100 + 3/100 = 43/100.', 'So the answer is 43/100.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Add, and write the answer as a decimal. 5/10 + 8/100 = ?',
        picture: { kind: 'eq', text: '5/10 + 8/100 = ?' }, answer: 0.58,
        steps: ['5/10 = 50/100.', '50/100 + 8/100 = 58/100.', 'So the sum is 0.58.'] } },
      { why: 'Still "tenths into hundredths"', problem: { text: 'Add. 9/100 + 7/10 = ?',
        picture: { kind: 'eq', text: '9/100 + 7/10 = ?' }, answer: { frac: [79, 100] },
        steps: ['The tenths can come second. Change them anyway: 7/10 = 70/100.', '9/100 + 70/100 = 79/100.', 'So the answer is 79/100.'] } },
      { why: 'A little harder', problem: { text: 'Add. 3/10 + 45/100 = ?',
        picture: { kind: 'eq', text: '3/10 + 45/100 = ?' }, answer: { frac: [75, 100] },
        steps: ['3/10 = 30/100.', '30/100 + 45/100 = 75/100.', 'So the answer is 75/100.'] } },
      { why: 'Same math in a story', problem: { text: 'Nia fills 4/10 of a jar with red beads and 25/100 of it with blue beads. How much of the jar is full? Write it as a decimal.',
        picture: blank, answer: 0.65,
        steps: ['4/10 = 40/100.', '40/100 + 25/100 = 65/100.', 'So 0.65 of the jar is full.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g4m6-t7', title: 'Money as decimals', skill: 'Write dollars and cents with a decimal point',
    bigIdea: 'A dollar is 100 cents, so cents are hundredths of a dollar. 2 dollars and 35 cents is $2.35.',
    screens: [
      { title: 'At the shop', text: 'You have 2 dollar bills, 3 dimes and 5 pennies. A toy costs $2.35. Do you have just enough?',
        pictures: [coins('2', '3', '5')] },
      { title: 'What does the tag mean?', text: 'The price tag does not say "dollars" or "cents". It uses a point. To read it, you need to know what each digit means.',
        pictures: [coins('2', '3', '5'), { kind: 'eq', text: '$2.35' }] },
      { title: 'The big idea', text: 'A dollar is 100 cents, so cents are hundredths of a dollar. 2 dollars and 35 cents is $2.35.',
        pictures: [coins('2', '3', '5')] },
      { title: 'A dime is one tenth', text: '10 dimes make 1 dollar. So one dime is one tenth of a dollar: $0.10. Dimes go right after the point.',
        pictures: [coins('2', '3', '5', [[0, 1]]), { kind: 'eq', text: '1 dime = $0.10' }] },
      { title: 'A penny is one hundredth', text: '100 pennies make 1 dollar. So one penny is one hundredth of a dollar: $0.01. Pennies go in the second place.',
        pictures: [coins('2', '3', '5', [[0, 2]]), { kind: 'eq', text: '1 penny = $0.01' }] },
      { title: 'Read the price', text: 'Write the dollars, then the point, then the dimes, then the pennies: $2.35. You have just enough.',
        pictures: [coins('2', '3', '5'), { kind: 'eq', text: '2 dollars, 3 dimes, 5 pennies', lines: ['$2.35'] }] },
      { title: 'One thing not to do', text: "Don't write 5 cents as $0.5. That is 5 dimes, which is 50 cents. 5 cents is $0.05.",
        pictures: [{ kind: 'cards', wrong: '5 cents = $0.5', right: '5 cents = $0.05' }] },
    ],
    turn: {
      text: 'You have 4 dollars, 1 dime and 7 pennies. How much money is that?',
      picture: coins('4', '1', '7'),
      answer: 4.17, steps: ['The 4 dollars go before the point.', '1 dime is 1 tenth of a dollar. 7 pennies are 7 hundredths.', 'So it is $4.17.'],
      prompt: 'Dollars, then the point, then dimes, then pennies.',
      hint1: 'What goes before the point? What goes right after it?',
      hint2: 'Dimes go in the first place after the point. Pennies go in the second.',
      twin: { text: 'You have 3 dollars, 6 dimes and 2 pennies. How much money is that?',
        picture: coins('3', '6', '2'),
        answer: 3.62, steps: ['The 3 dollars go before the point.', '6 dimes are 6 tenths of a dollar. 2 pennies are 2 hundredths.', 'So it is $3.62.'],
        hint1: 'Start with the dollars. Where do they go?',
        hint2: 'After the point, write the dimes first, then the pennies.' },
    },
    won: { text: 'You put the dollars, dimes and pennies in their places.', sticker: 'The point between dollars and cents is the decimal point. Cents are hundredths of a dollar.' },
    twinWon: { text: 'You put the dimes and pennies in their places and wrote $3.62.', sticker: 'The point between dollars and cents is the decimal point. Cents are hundredths of a dollar.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'You have 1 dollar, 4 dimes and 8 pennies. How much money is that?',
        picture: coins('1', '4', '8'), answer: 1.48,
        steps: ['The 1 dollar goes before the point.', '4 dimes are 4 tenths. 8 pennies are 8 hundredths.', 'So it is $1.48.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Write 5 dollars and 26 cents with a point, like $2.35.',
        picture: { kind: 'table', head: ['Dollars', 'Cents'], rows: [['5', '26']] }, answer: 5.26,
        steps: ['The 5 dollars go before the point.', '26 cents are 26 hundredths of a dollar, so they take the two places after the point.', 'So it is $5.26.'] } },
      { why: 'Still "cents are hundredths"', problem: { text: 'Write 6 dollars and 3 cents with a point.',
        picture: { kind: 'table', head: ['Dollars', 'Cents'], rows: [['6', '3']] }, answer: 6.03,
        steps: ['3 cents is 3 hundredths of a dollar.', 'There are no dimes, so a 0 goes right after the point.', 'So it is $6.03.'] } },
      { why: 'A little harder', problem: { text: 'How many cents is $3.45?',
        picture: { kind: 'eq', text: '$3.45 = ? cents' }, answer: 345,
        steps: ['Each dollar is 100 cents, so 3 dollars is 300 cents.', 'The .45 is 45 cents.', 'So $3.45 is 345 cents.'] } },
      { why: 'Same math in a story', problem: { text: 'A book costs 8 dollars and 15 cents. What does its price tag say?',
        picture: { kind: 'table', head: ['Dollars', 'Cents'], rows: [['8', '15']] }, answer: 8.15,
        steps: ['The 8 dollars go before the point.', '15 cents take the two places after the point.', 'So the tag says $8.15.'] } },
    ],
  },
]
