/**
 * Grade 5 · Module 2 — Addition and subtraction with fractions.
 * Written to docs/new-flow/AUTHORING.md. Topic 1 follows the founder's own "Step By Step Script" (1/2 + 1/4).
 */
import type { Lesson, Picture } from '../script'
import { attachChalk } from '../chalk'
import { G5M2_CHALK } from './chalk/g5m2'

type Bar = { parts: number; shaded: number; shade2?: number; split?: number; label?: string }
/** One fraction bar. */
const b = (parts: number, shaded: number, label?: string, more: Partial<Bar> = {}): Bar => ({ parts, shaded, label, ...more })
const bars = (list: Bar[], motion = false): Picture => ({ kind: 'bars', bars: list, motion })
/** Two fractions side by side, each labelled — the question, never the sum. */
const two = (p1: number, s1: number, p2: number, s2: number): Picture => bars([b(p1, s1, `${s1}/${p1}`), b(p2, s2, `${s2}/${p2}`)])
const eq = (text: string, lines?: string[]): Picture => ({ kind: 'eq', text, lines })
const dot = (labels: string[], values: number[], xLabel: string, motion = false): Picture =>
  ({ kind: 'chart', type: 'dot', labels, values, xLabel, motion })
const HALF = ['more than 1', 'less than 1']

export const G5M2: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m2-t1', title: 'Different-size pieces', skill: 'Add two fractions whose pieces are different sizes',
    bigIdea: 'Make the pieces the same size first. Then add how many pieces you have.',
    screens: [
      { scene: 'g5m2-t1', title: 'Adding different-size pieces', text: 'You run 1/2 mile. Then you run 1/4 mile. How far did you run in all?',
        pictures: [two(2, 1, 4, 1)] },
      { title: "The pieces don't match", text: "Look at these two bars. The pieces are not the same size at all. A half is a big piece. A fourth is a much smaller one. So we can't add them yet. Adding 1 piece to 1 piece would not tell us anything.",
        beats: [
          { say: 'Look at these two bars. The pieces are not the same size at all.', pic: 0 },
          { say: 'A half is a big piece. A fourth is a much smaller one.' },
          { say: "So we can't add them yet. Adding 1 piece to 1 piece would not tell us anything.", write: 'different sizes → cannot add yet' },
        ],
        pictures: [two(2, 1, 4, 1)] },
      { title: 'The big idea', text: 'Make the pieces the same size first. Then add how many pieces you have.',
        beats: [
          { say: 'Make the pieces the same size first.', pic: 0 },
          { say: 'Then add how many pieces you have.' },
        ],
        pictures: [two(2, 1, 4, 1)] },
      { title: 'Make the pieces match', text: 'Watch what happens when I cut the half straight down the middle. Now it is 2 pieces, and each one is exactly a fourth. Same amount of bar, just cut into smaller pieces. So 1/2 and 2/4 are two names for the same thing.',
        beats: [
          { say: 'Watch what happens when I cut the half straight down the middle.', pic: 0 },
          { say: 'Now it is 2 pieces, and each one is exactly a fourth.', write: 'cut in 2 → twice as many pieces' },
          { say: 'Same amount of bar, just cut into smaller pieces. So 1/2 and 2/4 are two names for the same thing.', pic: 1 },
        ],
        pictures: [bars([b(2, 1, '1/2', { split: 2 })], true), eq('1/2 = 2/4')] },
      { title: 'Same-size pieces', text: 'Now look at them again. Both bars are in fourths, and every piece is the same size. That is what we were waiting for. Now we can add.',
        beats: [
          { say: 'Now look at them again. Both bars are in fourths, and every piece is the same size.', pic: 0 },
          { say: 'That is what we were waiting for. Now we can add.', write: 'same size pieces → ready to add' },
        ],
        pictures: [bars([b(4, 2, '2/4'), b(4, 1, '1/4')], true)] },
      { title: 'Add how many pieces', text: 'Here comes the easy part. 2 fourths and 1 more fourth. That is 3 fourths. And notice the 4 on the bottom does not change. We are counting pieces, not resizing them. So 1/2 + 1/4 = 3/4.',
        beats: [
          { say: 'Here comes the easy part. 2 fourths and 1 more fourth.' },
          { say: 'That is 3 fourths.', pic: 0 },
          { say: 'And notice the 4 on the bottom does not change. We are counting pieces, not resizing them.', write: 'add the top, keep the bottom' },
          { say: 'So 1/2 + 1/4 = 3/4.', pic: 1 },
        ],
        pictures: [bars([b(4, 2, '3/4', { shade2: 1 })], true), eq('2/4 + 1/4 = 3/4')] },
      { title: 'One thing not to do', text: "Here is the mistake almost everybody makes once. Don't add the bottom numbers too. 1/2 + 1/4 is not 2/6. The bottom number tells you the piece size, and the pieces don't get smaller just because you added some.",
        beats: [
          { say: 'Here is the mistake almost everybody makes once.' },
          { say: "Don't add the bottom numbers too. 1/2 + 1/4 is not 2/6.", pic: 0 },
          { say: "The bottom number tells you the piece size, and the pieces don't get smaller just because you added some.", write: 'bottom number = piece size' },
        ],
        pictures: [{ kind: 'cards', wrong: '1/2 + 1/4 = 2/6', right: '1/2 + 1/4 = 3/4' }] },
    ],
    turn: {
      text: 'Add. 1/3 + 1/6 = ?',
      picture: two(3, 1, 6, 1),
      answer: { frac: [3, 6] },
      steps: ['Thirds and sixths are not the same size, so make them match.', 'Cut each third into 2 pieces. Now 1/3 is 2/6.', '2 sixths + 1 sixth = 3 sixths. So 1/3 + 1/6 = 3/6.'],
      prompt: 'Make the pieces the same size first. Then add.',
      hint1: 'Can you turn the thirds into sixths?',
      hint2: '1/3 is the same as 2/6. Now add 2/6 + 1/6.',
      twin: { text: 'Add. 1/2 + 1/3 = ?',
        picture: two(2, 1, 3, 1),
        answer: { frac: [5, 6] },
        steps: ['Halves and thirds do not match, but both can be cut into sixths.', 'Cut each half into 3 pieces: 1/2 is 3/6. Cut each third into 2 pieces: 1/3 is 2/6.', 'Add the pieces: 3/6 + 2/6 = 5/6.'],
        hint1: 'Halves and thirds are different sizes. What smaller piece can both be cut into?',
        hint2: 'Cut each half into 3 pieces and each third into 2 pieces. How many sixths is each one?' },
    },
    won: { text: 'You made the pieces match, then added. That is the whole trick.', sticker: 'When the bottom numbers match, the fractions have a common denominator.' },
    twinWon: { text: 'You turned halves and thirds into sixths and added to get 5/6.', sticker: 'When the bottom numbers match, the fractions have a common denominator.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Add. 1/2 + 1/8 = ?', picture: two(2, 1, 8, 1), answer: { frac: [5, 8] },
        steps: ['Cut each half into 4 pieces. So 1/2 is 4/8.', 'Now add the eighths: 4/8 + 1/8.', 'So 1/2 + 1/8 = 5/8.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Add. 1/3 + 1/9 = ?', picture: two(3, 1, 9, 1), answer: { frac: [4, 9] },
        steps: ['Cut each third into 3 pieces. So 1/3 is 3/9.', 'Now add the ninths: 3/9 + 1/9.', 'So 1/3 + 1/9 = 4/9.'] } },
      { why: 'Still "make the pieces match"', problem: { text: 'Add. 2/5 + 1/10 = ?', picture: two(5, 2, 10, 1), answer: { frac: [5, 10] },
        steps: ['Cut each fifth into 2 pieces. So 2/5 is 4/10.', 'Now add the tenths: 4/10 + 1/10.', 'So 2/5 + 1/10 = 5/10.'] } },
      { why: 'A little harder', problem: { text: 'Add. 1/4 + 1/6 = ?', picture: two(4, 1, 6, 1), answer: { frac: [5, 12] },
        steps: ['Fourths do not turn into sixths, but both can be cut into twelfths.', '1/4 is 3/12, and 1/6 is 2/12.', 'So 1/4 + 1/6 = 5/12.'] } },
      { why: 'Same math in a story', problem: { text: 'Sam walks 1/2 mile, then 1/3 mile. How far does he walk in all?', picture: two(2, 1, 3, 1), answer: { frac: [5, 6] },
        steps: ['Halves and thirds can both be cut into sixths.', '1/2 mile is 3/6 mile. 1/3 mile is 2/6 mile.', '3/6 + 2/6 = 5/6, so Sam walks 5/6 mile.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m2-t2', title: 'Make the pieces match', skill: 'Find a common denominator for two fractions',
    bigIdea: 'Count by each bottom number. The first number in both lists is a piece size both fractions can use.',
    screens: [
      { scene: 'g5m2-t2', title: 'Two pans of cornbread', text: 'You have 2/3 of one pan of cornbread and 1/4 of another pan. You want all the pieces the same size. What size works?',
        pictures: [two(3, 2, 4, 1)] },
      { title: 'Thirds and fourths do not fit', text: 'Try cutting a third in half. You get sixths. Sixths are fine, but fourths will never turn into sixths. What we need is one piece size that thirds can make and fourths can make too.',
        beats: [
          { say: 'Try cutting a third in half. You get sixths.', pic: 0 },
          { say: 'Sixths are fine, but fourths will never turn into sixths.' },
          { say: 'What we need is one piece size that thirds can make and fourths can make too.', write: 'need a size BOTH can make' },
        ],
        pictures: [two(3, 2, 4, 1)] },
      { title: 'The big idea', text: 'Count by each bottom number. The first number in both lists is a piece size both fractions can use.',
        beats: [
          { say: 'Count by each bottom number.', pic: 0 },
          { say: 'The first number in both lists is a piece size both fractions can use.' },
        ],
        pictures: [two(3, 2, 4, 1)] },
      { title: 'Count by both', text: "Let's count by 3s together. 3, 6, 9, 12. Now by 4s. 4, 8, 12. Do you see it? 12 turns up in both lists, and it is the first one that does. So twelfths is our piece size.",
        beats: [
          { say: "Let's count by 3s together. 3, 6, 9, 12. Now by 4s. 4, 8, 12.", pic: 1 },
          { say: 'Do you see it? 12 turns up in both lists, and it is the first one that does.' },
          { say: 'So twelfths is our piece size.', write: 'first number in both lists → the piece size' },
        ],
        pictures: [two(3, 2, 4, 1), eq('3, 6, 9, 12', ['4, 8, 12'])] },
      { title: 'Cut into twelfths', text: 'Now we cut. Each third splits into 4 little pieces, so 2 thirds become 8 twelfths. And each fourth splits into 3, so 1 fourth becomes 3 twelfths.',
        beats: [
          { say: 'Now we cut. Each third splits into 4 little pieces, so 2 thirds become 8 twelfths.', pic: 0 },
          { say: 'And each fourth splits into 3, so 1 fourth becomes 3 twelfths.', write: 'more pieces → more shaded pieces too' },
        ],
        pictures: [bars([b(3, 2, '2/3', { split: 4 }), b(4, 1, '1/4', { split: 3 })], true)] },
      { title: 'Now they match', text: 'Look at them now. Both bars are in twelfths, and the pieces line up perfectly. Nothing got bigger or smaller. I only gave them new names. And now that the pieces match, adding or taking away is easy.',
        beats: [
          { say: 'Look at them now. Both bars are in twelfths, and the pieces line up perfectly.', pic: 0 },
          { say: 'Nothing got bigger or smaller. I only gave them new names.', pic: 1 },
          { say: 'And now that the pieces match, adding or taking away is easy.', write: 'same bottom number → ready to add' },
        ],
        pictures: [bars([b(12, 8, '8/12'), b(12, 3, '3/12')], true), eq('2/3 = 8/12', ['1/4 = 3/12'])] },
      { title: 'One thing not to do', text: "One warning before you go. Don't just change the bottom number and leave the top alone. When every piece gets cut into 4, the shaded pieces get cut into 4 as well, so 2/3 becomes 8/12, not 2/12.",
        beats: [
          { say: 'One warning before you go.' },
          { say: "Don't just change the bottom number and leave the top alone.", pic: 0 },
          { say: 'When every piece gets cut into 4, the shaded pieces get cut into 4 as well, so 2/3 becomes 8/12, not 2/12.', write: 'cut the bottom → cut the top the same way' },
        ],
        pictures: [{ kind: 'cards', wrong: '2/3 = 2/12', right: '2/3 = 8/12' }] },
    ],
    turn: {
      text: 'What is the smallest piece size that 1/2 and 1/5 can both be cut into? Type the new bottom number.',
      picture: two(2, 1, 5, 1),
      answer: 10,
      steps: ['Count by 2s: 2, 4, 6, 8, 10.', 'Count by 5s: 5, 10.', 'The first number in both lists is 10, so use tenths.'],
      prompt: 'Count by each bottom number. Find the first number in both lists.',
      hint1: 'Count by 2s and count by 5s. Where do the lists meet?',
      hint2: 'Count by 5s: 5, and then what? Is that number in the 2s list too?',
      twin: { text: 'What is the smallest piece size that 1/3 and 1/4 can both be cut into? Type the new bottom number.',
        picture: two(3, 1, 4, 1),
        answer: 12,
        steps: ['Count by 3s: 3, 6, 9, 12.', 'Count by 4s: 4, 8, 12.', 'The first number in both lists is 12, so use twelfths.'],
        hint1: 'Count by 3s and count by 4s. Where do the lists meet?',
        hint2: 'Keep counting by 4s: 4, 8, and then? Is that number in the 3s list?' },
    },
    won: { text: 'You counted by both bottom numbers and found where the lists meet.', sticker: 'A bottom number two fractions can share is called a common denominator.' },
    twinWon: { text: 'You counted by 3s and 4s and met at 12.', sticker: 'A bottom number two fractions can share is called a common denominator.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What is the smallest piece size that 1/2 and 1/3 can both be cut into? Type the new bottom number.',
        picture: two(2, 1, 3, 1), answer: 6,
        steps: ['Count by 2s: 2, 4, 6.', 'Count by 3s: 3, 6.', 'The first number in both lists is 6.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is the smallest piece size that 1/3 and 1/5 can both be cut into? Type the new bottom number.',
        picture: two(3, 1, 5, 1), answer: 15,
        steps: ['Count by 3s: 3, 6, 9, 12, 15.', 'Count by 5s: 5, 10, 15.', 'The first number in both lists is 15.'] } },
      { why: 'Still "cut both the same way"', problem: { text: 'Write 3/5 with 10 on the bottom.',
        picture: bars([b(5, 3, '3/5'), b(10, 0)]), answer: { frac: [6, 10], exact: true },
        steps: ['Tenths are fifths cut into 2 pieces each.', 'So the 3 shaded pieces become 3 × 2 = 6 pieces.', 'So 3/5 = 6/10.'] } },
      { why: 'A little harder', problem: { text: 'What is the smallest piece size that 3/8 and 5/6 can both be cut into? Type the new bottom number.',
        picture: two(8, 3, 6, 5), answer: 24,
        steps: ['Count by 8s: 8, 16, 24.', 'Count by 6s: 6, 12, 18, 24.', 'The first number in both lists is 24.'] } },
      { why: 'Same math in a story', problem: { text: 'Mia cuts one pie into fourths and a same-size pie into sixths. She wants all the pieces to match. How many pieces should each pie be cut into?',
        picture: bars([b(4, 0), b(6, 0)]), answer: 12,
        steps: ['Count by 4s: 4, 8, 12.', 'Count by 6s: 6, 12.', 'The first number in both lists is 12, so each pie is cut into 12 pieces.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m2-t3', title: 'Take away different-size pieces', skill: 'Subtract fractions with unlike denominators',
    bigIdea: 'Make the pieces the same size first. Then take away pieces.',
    screens: [
      { scene: 'g5m2-t3', title: 'Pizza left over', text: 'You have 3/4 of a pizza. You eat 1/2 of a pizza. How much pizza is left?',
        pictures: [two(4, 3, 2, 1)] },
      { title: "The pieces don't match", text: "Same problem as before, but this time we are taking away. Fourths and halves are different sizes. So 3 pieces take away 1 piece tells us nothing at all. Those pieces aren't the same thing.",
        beats: [
          { say: 'Same problem as before, but this time we are taking away.', pic: 0 },
          { say: 'Fourths and halves are different sizes.' },
          { say: "So 3 pieces take away 1 piece tells us nothing at all. Those pieces aren't the same thing.", write: 'different sizes → cannot take away yet' },
        ],
        pictures: [two(4, 3, 2, 1)] },
      { title: 'The big idea', text: 'Make the pieces the same size first. Then take away pieces.',
        beats: [
          { say: 'Make the pieces the same size first.', pic: 0 },
          { say: 'Then take away pieces.' },
        ],
        pictures: [two(4, 3, 2, 1)] },
      { title: 'Make the pieces match', text: 'You have done this before. Cut the half right down the middle. Each new piece is a fourth. So the half you ate is really 2 fourths.',
        beats: [
          { say: 'You have done this before. Cut the half right down the middle.', pic: 0 },
          { say: 'Each new piece is a fourth.' },
          { say: 'So the half you ate is really 2 fourths.', pic: 1 },
        ],
        pictures: [bars([b(2, 1, '1/2', { split: 2 })], true), eq('1/2 = 2/4')] },
      { title: 'Same-size pieces', text: 'Now both bars are in fourths. 3 fourths on the plate, 2 fourths eaten. Every piece is the same size, so now we can take away.',
        beats: [
          { say: 'Now both bars are in fourths. 3 fourths on the plate, 2 fourths eaten.', pic: 0 },
          { say: 'Every piece is the same size, so now we can take away.', write: 'same size pieces → ready to take away' },
        ],
        pictures: [bars([b(4, 3, '3/4'), b(4, 2, '2/4')], true)] },
      { title: 'Take away pieces', text: 'Watch the yellow pieces go. Those are the 2 fourths you ate. 3 fourths take away 2 fourths, and 1 fourth is still sitting there. So 3/4 − 1/2 = 1/4.',
        beats: [
          { say: 'Watch the yellow pieces go. Those are the 2 fourths you ate.', pic: 0 },
          { say: '3 fourths take away 2 fourths, and 1 fourth is still sitting there.', write: 'take away the top, keep the bottom' },
          { say: 'So 3/4 − 1/2 = 1/4.', pic: 1 },
        ],
        pictures: [bars([b(4, 1, '1/4', { shade2: 2 })], true), eq('3/4 − 2/4 = 1/4')] },
      { title: 'One thing not to do', text: "Here is the trap. Don't take the bottom numbers away from each other. 3/4 − 1/2 is not 2/2. That would say you still have a whole pizza after eating half of one, and that cannot be right.",
        beats: [
          { say: 'Here is the trap.' },
          { say: "Don't take the bottom numbers away from each other. 3/4 − 1/2 is not 2/2.", pic: 0 },
          { say: 'That would say you still have a whole pizza after eating half of one, and that cannot be right.', write: 'bottom number = piece size, it stays' },
        ],
        pictures: [{ kind: 'cards', wrong: '3/4 − 1/2 = 2/2', right: '3/4 − 1/2 = 1/4' }] },
    ],
    turn: {
      text: 'Take away. 5/6 − 1/3 = ?',
      picture: two(6, 5, 3, 1),
      answer: { frac: [3, 6] },
      steps: ['Thirds are bigger than sixths, so make the pieces match.', 'Cut each third into 2 pieces. So 1/3 is 2/6.', '5/6 − 2/6 = 3/6.'],
      prompt: 'Make the pieces the same size first. Then take away.',
      hint1: 'Can you turn the thirds into sixths?',
      hint2: '1/3 is the same as 2/6. Now take 2/6 away from 5/6.',
      twin: { text: 'Take away. 1/2 − 1/5 = ?',
        picture: two(2, 1, 5, 1),
        answer: { frac: [3, 10] },
        steps: ['Halves and fifths can both be cut into tenths.', '1/2 is 5/10, and 1/5 is 2/10.', '5/10 − 2/10 = 3/10.'],
        hint1: 'Halves and fifths are different sizes. What smaller piece can both be cut into?',
        hint2: 'Count by 2s and by 5s to find where they meet. Then change both fractions.' },
    },
    won: { text: 'You made the pieces match, then took away.', sticker: 'Take away only when the fractions have a common denominator.' },
    twinWon: { text: 'You turned halves and fifths into tenths and found 3/10.', sticker: 'Take away only when the fractions have a common denominator.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Take away. 7/8 − 1/2 = ?', picture: two(8, 7, 2, 1), answer: { frac: [3, 8] },
        steps: ['Cut each half into 4 pieces. So 1/2 is 4/8.', 'Take away the eighths: 7/8 − 4/8.', 'So 7/8 − 1/2 = 3/8.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Take away. 2/3 − 1/6 = ?', picture: two(3, 2, 6, 1), answer: { frac: [3, 6] },
        steps: ['Cut each third into 2 pieces. So 2/3 is 4/6.', 'Take away the sixths: 4/6 − 1/6.', 'So 2/3 − 1/6 = 3/6.'] } },
      { why: 'Still "match, then take away"', problem: { text: 'Take away. 9/10 − 2/5 = ?', picture: two(10, 9, 5, 2), answer: { frac: [5, 10] },
        steps: ['Cut each fifth into 2 pieces. So 2/5 is 4/10.', 'Take away the tenths: 9/10 − 4/10.', 'So 9/10 − 2/5 = 5/10.'] } },
      { why: 'A little harder', problem: { text: 'Take away. 3/4 − 1/3 = ?', picture: two(4, 3, 3, 1), answer: { frac: [5, 12] },
        steps: ['Fourths and thirds can both be cut into twelfths.', '3/4 is 9/12, and 1/3 is 4/12.', '9/12 − 4/12 = 5/12. So 3/4 − 1/3 = 5/12.'] } },
      { why: 'Same math in a story', problem: { text: 'A jug has 2/3 gallon of juice. Kim pours out 1/2 gallon. How much juice is left?', picture: two(3, 2, 2, 1), answer: { frac: [1, 6] },
        steps: ['Thirds and halves can both be cut into sixths.', '2/3 is 4/6, and 1/2 is 3/6.', '4/6 − 3/6 = 1/6, so 1/6 gallon is left.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m2-t4', title: 'Add mixed numbers', skill: 'Add mixed numbers, trading pieces for a whole when needed',
    bigIdea: 'Add the wholes, then add the pieces. If the pieces make a whole, trade them for 1 more whole.',
    screens: [
      { scene: 'g5m2-t4', title: 'Two hikes', text: 'You hike 1 1/2 miles in the morning. You hike 1 3/4 miles after lunch. How far did you hike in all?',
        pictures: [bars([b(1, 1, '1'), b(2, 1, '1/2'), b(1, 1, '1'), b(4, 3, '3/4')])] },
      { title: 'Wholes and pieces', text: 'Look at what we have here. There are 2 whole miles, and then 2 leftover bits, and those bits are different sizes. Doing all of that in one go is how people get tangled up. So we are going to split the job in two.',
        beats: [
          { say: 'Look at what we have here. There are 2 whole miles, and then 2 leftover bits, and those bits are different sizes.', pic: 0 },
          { say: 'Doing all of that in one go is how people get tangled up.' },
          { say: 'So we are going to split the job in two.', write: 'wholes first, pieces after' },
        ],
        pictures: [bars([b(1, 1, '1'), b(2, 1, '1/2'), b(1, 1, '1'), b(4, 3, '3/4')])] },
      { title: 'The big idea', text: 'Add the wholes, then add the pieces. If the pieces make a whole, trade them for 1 more whole.',
        beats: [
          { say: 'Add the wholes, then add the pieces.', pic: 0 },
          { say: 'If the pieces make a whole, trade them for 1 more whole.' },
        ],
        pictures: [bars([b(1, 1, '1'), b(2, 1, '1/2'), b(1, 1, '1'), b(4, 3, '3/4')])] },
      { title: 'Add the wholes', text: 'Wholes first, because they are the easy part. 1 whole and 1 whole make 2 wholes. Park that 2 somewhere safe and leave the pieces alone for a minute.',
        beats: [
          { say: 'Wholes first, because they are the easy part.', pic: 0 },
          { say: '1 whole and 1 whole make 2 wholes.', pic: 1 },
          { say: 'Park that 2 somewhere safe and leave the pieces alone for a minute.' },
        ],
        pictures: [bars([b(1, 1, '1'), b(1, 1, '1')], true), eq('1 + 1 = 2')] },
      { title: 'Add the pieces', text: "Now the pieces. They don't match yet, so cut the half into 2 and it becomes 2/4. Now add: 2 fourths and 3 fourths is 5 fourths. And look at that. 5 fourths is more than one whole bar.",
        beats: [
          { say: "Now the pieces. They don't match yet, so cut the half into 2 and it becomes 2/4.", pic: 0 },
          { say: 'Now add: 2 fourths and 3 fourths is 5 fourths.', pic: 1 },
          { say: 'And look at that. 5 fourths is more than one whole bar.', write: 'top bigger than bottom → more than 1 whole' },
        ],
        pictures: [bars([b(4, 2, undefined, { shade2: 2 }), b(4, 0, undefined, { shade2: 1 })], true), eq('2/4 + 3/4 = 5/4')] },
      { title: 'Trade for a whole', text: 'So we trade. 4 of those fourths fill a whole bar exactly, and 1 fourth is left over. That means 5/4 is 1 1/4. Put it with the 2 wholes we parked, and the hike is 3 1/4 miles.',
        beats: [
          { say: 'So we trade. 4 of those fourths fill a whole bar exactly, and 1 fourth is left over.', pic: 0 },
          { say: 'That means 5/4 is 1 1/4.', write: 'enough pieces to fill a whole → trade' },
          { say: 'Put it with the 2 wholes we parked, and the hike is 3 1/4 miles.', pic: 1 },
        ],
        pictures: [bars([b(4, 4, '1'), b(4, 1, '1/4')], true), eq('2 + 1 1/4 = 3 1/4')] },
      { title: 'One thing not to do', text: "One last warning. Don't add the bottom numbers when you add the pieces. 1/2 + 3/4 is not 4/6. Make the pieces match first, every single time.",
        beats: [
          { say: 'One last warning.' },
          { say: "Don't add the bottom numbers when you add the pieces. 1/2 + 3/4 is not 4/6.", pic: 0 },
          { say: 'Make the pieces match first, every single time.', write: 'match the pieces before you add' },
        ],
        pictures: [{ kind: 'cards', wrong: '1 1/2 + 1 3/4 = 2 4/6', right: '1 1/2 + 1 3/4 = 3 1/4' }] },
    ],
    turn: {
      text: 'Add. 1 1/2 + 2 3/4 = ?',
      picture: eq('1 1/2 + 2 3/4 = ?'),
      answer: { frac: [1, 4], whole: 4 },
      steps: ['Add the wholes: 1 + 2 = 3.', 'Make the pieces match: 2/4 + 3/4 = 5/4, which is 1 1/4.', '3 + 1 1/4 = 4 1/4.'],
      prompt: 'Add the wholes. Then make the pieces match and add them.',
      hint1: 'First add the wholes. Then turn the half into fourths.',
      hint2: '1/2 is 2/4, so the pieces are 2/4 + 3/4. Is that more than a whole?',
      twin: { text: 'Add. 2 1/3 + 1 1/6 = ?',
        picture: eq('2 1/3 + 1 1/6 = ?'),
        answer: { frac: [3, 6], whole: 3 },
        steps: ['Add the wholes: 2 + 1 = 3.', 'Make the pieces match: 1/3 is 2/6, so 2/6 + 1/6 = 3/6.', '3 + 3/6 = 3 3/6.'],
        hint1: 'Add the wholes first. Then look at the pieces.',
        hint2: 'Turn the third into sixths. Then add the sixths.' },
    },
    won: { text: 'You added the wholes, added the pieces, and traded 4 fourths for a whole.', sticker: 'A whole number and a fraction together make a mixed number.' },
    twinWon: { text: 'You added the wholes, then the sixths, and got 3 3/6.', sticker: 'A whole number and a fraction together make a mixed number.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Add. 2 3/4 + 2 1/2 = ?', picture: eq('2 3/4 + 2 1/2 = ?'), answer: { frac: [1, 4], whole: 5 },
        steps: ['Add the wholes: 2 + 2 = 4.', '1/2 is 2/4, so 3/4 + 2/4 = 5/4, which is 1 1/4.', '4 + 1 1/4 = 5 1/4.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Add. 1 2/3 + 1 1/2 = ?', picture: eq('1 2/3 + 1 1/2 = ?'), answer: { frac: [1, 6], whole: 3 },
        steps: ['Add the wholes: 1 + 1 = 2.', 'Use sixths: 4/6 + 3/6 = 7/6, which is 1 1/6.', '2 + 1 1/6 = 3 1/6.'] } },
      { why: 'Still "wholes, then pieces"', problem: { text: 'Add. 3 1/5 + 2 1/10 = ?', picture: eq('3 1/5 + 2 1/10 = ?'), answer: { frac: [3, 10], whole: 5 },
        steps: ['Add the wholes: 3 + 2 = 5.', '1/5 is 2/10, so 2/10 + 1/10 = 3/10.', '5 + 3/10 = 5 3/10.'] } },
      { why: 'A little harder', problem: { text: 'Add. 2 5/6 + 1 3/4 = ?', picture: eq('2 5/6 + 1 3/4 = ?'), answer: { frac: [7, 12], whole: 4 },
        steps: ['Add the wholes: 2 + 1 = 3.', 'Use twelfths: 10/12 + 9/12 = 19/12, which is 1 7/12.', '3 + 1 7/12 = 4 7/12.'] } },
      { why: 'Same math in a story', problem: { text: 'A plant is 2 3/8 inches tall. It grows 1 3/4 inches more. How tall is it now?', picture: eq('2 3/8 + 1 3/4 = ?'), answer: { frac: [1, 8], whole: 4 },
        steps: ['Add the wholes: 2 + 1 = 3.', '3/4 is 6/8, so 3/8 + 6/8 = 9/8, which is 1 1/8.', '3 + 1 1/8 = 4 1/8, so the plant is 4 1/8 inches tall.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m2-t5', title: 'Take away mixed numbers (break a whole)', skill: 'Subtract mixed numbers by breaking a whole into pieces',
    bigIdea: "If there are not enough pieces to take away, break 1 whole into pieces first.",
    screens: [
      { scene: 'g5m2-t5', title: 'Cutting ribbon', text: 'You have 3 1/4 feet of ribbon. You cut off 1 3/4 feet. How much ribbon is left?',
        pictures: [bars([b(1, 1, '1'), b(1, 1, '1'), b(1, 1, '1'), b(4, 1, '1/4')])] },
      { title: "Not enough fourths", text: "Look at the fourths first. You need to cut off 3 fourths. How many fourths do you have? Just 1. You can't take 3 pieces from 1 piece. So where do more pieces come from?",
        beats: [
          { say: "Look at the fourths first. You need to cut off 3 fourths.", pic: 0 },
          { say: "How many fourths do you have? Just 1." },
          { say: "You can't take 3 pieces from 1 piece. So where do more pieces come from?" },
        ],
        pictures: [bars([b(4, 1, '1/4')])] },
      { title: "The big idea", text: "If there are not enough pieces to take away, break 1 whole into pieces first.",
        beats: [
          { say: "If there are not enough pieces to take away, break 1 whole into pieces first.", pic: 0 },
        ],
        pictures: [bars([b(1, 1, '1'), b(1, 1, '1'), b(1, 1, '1'), b(4, 1, '1/4')])] },
      { title: "Break a whole", text: "So take 1 of the 3 whole feet and cut it into 4 fourths. Now you have 2 wholes, and 5 fourths instead of 1. It's the same ribbon, just cut up more. 3 1/4 is the same as 2 5/4.",
        beats: [
          { say: "So take 1 of the 3 whole feet and cut it into 4 fourths.", pic: 0 },
          { say: "Now you have 2 wholes, and 5 fourths instead of 1." },
          { say: "It's the same ribbon, just cut up more. 3 1/4 is the same as 2 5/4.", pic: 1 },
        ],
        pictures: [bars([b(1, 1, '1'), b(1, 1, '1'), b(1, 1, '4/4', { split: 4 }), b(4, 1, '1/4')], true), eq('3 1/4 = 2 5/4')] },
      { title: "Take away the pieces", text: "Now there are enough pieces. Take 3 fourths away from 5 fourths. Count what's left. 2 fourths.",
        beats: [
          { say: "Now there are enough pieces. Take 3 fourths away from 5 fourths.", pic: 0 },
          { say: "Count what's left. 2 fourths.", pic: 1 },
        ],
        pictures: [bars([b(4, 2, undefined, { shade2: 2 }), b(4, 0, undefined, { shade2: 1 })], true), eq('5/4 − 3/4 = 2/4')] },
      { title: "Take away the wholes", text: "Then the wholes. 2 wholes take away 1 whole leaves 1 whole. Put it all back together. 1 2/4 feet of ribbon is left.",
        beats: [
          { say: "Then the wholes. 2 wholes take away 1 whole leaves 1 whole.", pic: 0 },
          { say: "Put it all back together. 1 2/4 feet of ribbon is left.", pic: 1 },
        ],
        pictures: [bars([b(1, 1, '1'), b(4, 2, '2/4')], true), eq('2 − 1 = 1', ['3 1/4 − 1 3/4 = 1 2/4'])] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't FLIP it and take 1 fourth from 3 fourths. That gives 2 2/4. You are cutting off 3 fourths, not 1. Break a whole first. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't FLIP it and take 1 fourth from 3 fourths. That gives 2 2/4.", pic: 0 },
          { say: "You are cutting off 3 fourths, not 1. Break a whole first." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '3 1/4 − 1 3/4 = 2 2/4', right: '3 1/4 − 1 3/4 = 1 2/4' }] },
    ],
    turn: {
      text: 'Take away. 4 1/3 − 1 2/3 = ?',
      picture: eq('4 1/3 − 1 2/3 = ?'),
      answer: { frac: [2, 3], whole: 2 },
      steps: ['You cannot take 2 thirds from 1 third, so break a whole.', '4 1/3 is the same as 3 4/3.', '3 4/3 − 1 2/3 = 2 2/3.'],
      prompt: 'Not enough pieces? Break 1 whole first.',
      hint1: 'Do you have enough thirds to take away 2 thirds?',
      hint2: 'Break 1 whole into 3 thirds. So 4 1/3 is the same as 3 4/3.',
      twin: { text: 'Take away. 3 1/5 − 1 3/5 = ?',
        picture: eq('3 1/5 − 1 3/5 = ?'),
        answer: { frac: [3, 5], whole: 1 },
        steps: ['You cannot take 3 fifths from 1 fifth, so break a whole.', '3 1/5 is the same as 2 6/5.', '2 6/5 − 1 3/5 = 1 3/5.'],
        hint1: 'Do you have enough fifths to take away?',
        hint2: 'Break 1 whole into 5 fifths and put them with the fifth you have.' },
    },
    won: { text: 'You broke a whole into pieces, then took away.', sticker: 'Breaking a whole into smaller pieces is called regrouping.' },
    twinWon: { text: 'You broke a whole into fifths and found 1 3/5.', sticker: 'Breaking a whole into smaller pieces is called regrouping.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Take away. 5 1/4 − 2 3/4 = ?', picture: eq('5 1/4 − 2 3/4 = ?'), answer: { frac: [2, 4], whole: 2 },
        steps: ['You cannot take 3 fourths from 1 fourth, so break a whole.', '5 1/4 is the same as 4 5/4.', '4 5/4 − 2 3/4 = 2 2/4.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Take away. 6 2/5 − 3 4/5 = ?', picture: eq('6 2/5 − 3 4/5 = ?'), answer: { frac: [3, 5], whole: 2 },
        steps: ['You cannot take 4 fifths from 2 fifths, so break a whole.', '6 2/5 is the same as 5 7/5.', '5 7/5 − 3 4/5 = 2 3/5.'] } },
      { why: 'Still "break a whole"', problem: { text: 'Take away. 3 − 1 3/8 = ?', picture: eq('3 − 1 3/8 = ?'), answer: { frac: [5, 8], whole: 1 },
        steps: ['There are no eighths to take from, so break a whole.', '3 is the same as 2 8/8.', '2 8/8 − 1 3/8 = 1 5/8.'] } },
      { why: 'A little harder', problem: { text: 'Take away. 4 1/6 − 1 1/2 = ?', picture: eq('4 1/6 − 1 1/2 = ?'), answer: { frac: [4, 6], whole: 2 },
        steps: ['Make the pieces match: 1 1/2 is 1 3/6.', 'You cannot take 3 sixths from 1 sixth, so break a whole: 4 1/6 is 3 7/6.', '3 7/6 − 1 3/6 = 2 4/6.'] } },
      { why: 'Same math in a story', problem: { text: 'A board is 5 3/8 feet long. Leo cuts off 2 7/8 feet. How long is the board now?', picture: eq('5 3/8 − 2 7/8 = ?'), answer: { frac: [4, 8], whole: 2 },
        steps: ['You cannot take 7 eighths from 3 eighths, so break a whole.', '5 3/8 is the same as 4 11/8.', '4 11/8 − 2 7/8 = 2 4/8, so the board is 2 4/8 feet long.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m2-t6', title: 'Is it more or less than 1?', skill: 'Estimate a sum of fractions by comparing each to 1/2',
    bigIdea: "Compare each part to 1/2: two parts over 1/2 make more than 1, and two parts under 1/2 make less than 1.",
    screens: [
      { scene: 'g5m2-t6', title: 'Enough paint?', text: 'You need 1 can of paint. You have 3/5 of a can and 4/7 of a can. Do you have more than 1 can?',
        pictures: [two(5, 3, 7, 4)] },
      { title: "Hard to add", text: "You could match fifths and sevenths. But that takes a lot of tiny pieces. Read the question again. Does it ask how much? No. It only asks if you have more than 1 can.",
        beats: [
          { say: "You could match fifths and sevenths. But that takes a lot of tiny pieces.", pic: 0 },
          { say: "Read the question again. Does it ask how much? No." },
          { say: "It only asks if you have more than 1 can." },
        ],
        pictures: [two(5, 3, 7, 4)] },
      { title: "The big idea", text: "Compare each part to 1/2: two parts over 1/2 make more than 1, and two parts under 1/2 make less than 1.",
        beats: [
          { say: "Compare each part to 1/2: two parts over 1/2 make more than 1, and two parts under 1/2 make less than 1.", pic: 0 },
        ],
        pictures: [bars([b(2, 1, '1/2'), b(5, 3, '3/5'), b(7, 4, '4/7')])] },
      { title: "Check the first can", text: "Take 3/5. Half of 5 pieces is 2 and a half pieces. Is 3 more than 2 and a half? Yes. So 3/5 is more than half.",
        beats: [
          { say: "Take 3/5. Half of 5 pieces is 2 and a half pieces.", pic: 0 },
          { say: "Is 3 more than 2 and a half? Yes." },
          { say: "So 3/5 is more than half." },
        ],
        pictures: [bars([b(2, 1, '1/2'), b(5, 3, '3/5')], true)] },
      { title: "Check the other can", text: "Now 4/7. Half of 7 pieces is 3 and a half. You have 4 pieces, which is more again. So 4/7 is more than half too.",
        beats: [
          { say: "Now 4/7. Half of 7 pieces is 3 and a half.", pic: 0 },
          { say: "You have 4 pieces, which is more again." },
          { say: "So 4/7 is more than half too." },
        ],
        pictures: [bars([b(2, 1, '1/2'), b(7, 4, '4/7')], true)] },
      { title: "Put them together", text: "Half a can and half a can make exactly 1 can. Both of your cans are more than half. So together you have more than 1 can, and you never had to add.",
        beats: [
          { say: "Half a can and half a can make exactly 1 can.", pic: 0 },
          { say: "Both of your cans are more than half." },
          { say: "So together you have more than 1 can, and you never had to add.", pic: 1 },
        ],
        pictures: [bars([b(2, 1, '1/2', { shade2: 1 }), b(5, 3, '3/5'), b(7, 4, '4/7')], true), eq('3/5 + 4/7 is more than 1')] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't ADD the tops and add the bottoms. That gives 7/12, and that is less than 1. But each part was more than half, so together they are more than 1. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't ADD the tops and add the bottoms. That gives 7/12, and that is less than 1.", pic: 0 },
          { say: "But each part was more than half, so together they are more than 1." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '3/5 + 4/7 = 7/12, less than 1', right: '3/5 + 4/7 is more than 1' }] },
    ],
    turn: {
      text: 'Is 5/8 + 2/3 more or less than 1?',
      picture: two(8, 5, 3, 2),
      answer: { choices: HALF, correct: 0 },
      steps: ['Half of 8 is 4. 5 is more, so 5/8 is more than 1/2.', 'Half of 3 is 1 and a half. 2 is more, so 2/3 is more than 1/2.', 'Both are more than 1/2, so the sum is more than 1.'],
      prompt: 'Compare each fraction to one half.',
      hint1: 'Is 5/8 more or less than half?',
      hint2: 'Half of 8 pieces is 4 pieces. Half of 3 pieces is 1 and a half. Compare each one.',
      twin: { text: 'Is 2/5 + 3/7 more or less than 1?',
        picture: two(5, 2, 7, 3),
        answer: { choices: HALF, correct: 1 },
        steps: ['Half of 5 is 2 and a half. 2 is less, so 2/5 is less than 1/2.', 'Half of 7 is 3 and a half. 3 is less, so 3/7 is less than 1/2.', 'Both are less than 1/2, so the sum is less than 1.'],
        hint1: 'Is 2/5 more or less than half?',
        hint2: 'Half of 5 pieces is 2 and a half. Half of 7 pieces is 3 and a half. Compare each one.' },
    },
    won: { text: 'You checked each fraction against one half, without adding.', sticker: 'A friendly number you compare to, like one half, is called a benchmark.' },
    twinWon: { text: 'You saw that 2/5 and 3/7 are each less than half, so the sum is less than 1.', sticker: 'A friendly number you compare to, like one half, is called a benchmark.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Is 4/6 + 5/9 more or less than 1?', picture: two(6, 4, 9, 5), answer: { choices: HALF, correct: 0 },
        steps: ['Half of 6 is 3. 4 is more, so 4/6 is more than 1/2.', 'Half of 9 is 4 and a half. 5 is more, so 5/9 is more than 1/2.', 'Both are more than 1/2, so the sum is more than 1.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Is 1/4 + 2/5 more or less than 1?', picture: two(4, 1, 5, 2), answer: { choices: HALF, correct: 1 },
        steps: ['Half of 4 is 2. 1 is less, so 1/4 is less than 1/2.', 'Half of 5 is 2 and a half. 2 is less, so 2/5 is less than 1/2.', 'Both are less than 1/2, so the sum is less than 1.'] } },
      { why: 'Still "compare to one half"', problem: { text: 'Is 3/8 + 1/3 more or less than 1?', picture: two(8, 3, 3, 1), answer: { choices: HALF, correct: 1 },
        steps: ['Half of 8 is 4. 3 is less, so 3/8 is less than 1/2.', 'Half of 3 is 1 and a half. 1 is less, so 1/3 is less than 1/2.', 'Both are less than 1/2, so the sum is less than 1.'] } },
      { why: 'A little harder', problem: { text: 'Is 6/10 + 1/2 more or less than 1?', picture: two(10, 6, 2, 1), answer: { choices: HALF, correct: 0 },
        steps: ['Half of 10 is 5. 6 is more, so 6/10 is more than 1/2.', '1/2 + 1/2 is exactly 1, and 6/10 is a bit more than 1/2.', 'So 6/10 + 1/2 is more than 1.'] } },
      { why: 'Same math in a story', problem: { text: 'Ana walks 3/8 mile to school, then 2/5 mile to the park. Did she walk more or less than 1 mile?', picture: two(8, 3, 5, 2), answer: { choices: HALF, correct: 1 },
        steps: ['Half of 8 is 4. 3 is less, so 3/8 is less than 1/2.', 'Half of 5 is 2 and a half. 2 is less, so 2/5 is less than 1/2.', 'Both parts are less than 1/2, so she walked less than 1 mile.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m2-t7', title: 'Fraction stories', skill: 'Solve word problems that add or subtract fractions',
    bigIdea: "Draw the story as bars, then decide: put the parts together, or find the gap.",
    screens: [
      { scene: 'g5m2-t7', title: 'Who ran farther?', text: 'Max runs 3/4 mile. Lee runs 1/2 mile. How much farther does Max run?',
        pictures: [{ kind: 'tape', rows: [{ label: 'Max', cells: [{ w: 3, text: '3/4', shade: true }] }, { label: 'Lee', cells: [{ w: 2, text: '1/2', shade: true }] }] }] },
      { title: "Add or take away?", text: "There are two numbers, and nothing says what to do with them. Add them? No. That would tell how far they ran together. The question asks how much farther.",
        beats: [
          { say: "There are two numbers, and nothing says what to do with them.", pic: 0 },
          { say: "Add them? No. That would tell how far they ran together." },
          { say: "The question asks how much farther." },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Max', cells: [{ w: 3, text: '3/4', shade: true }] }, { label: 'Lee', cells: [{ w: 2, text: '1/2', shade: true }] }] }] },
      { title: "The big idea", text: "Draw the story as bars, then decide: put the parts together, or find the gap.",
        beats: [
          { say: "Draw the story as bars, then decide: put the parts together, or find the gap.", pic: 0 },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Max', cells: [{ w: 3, text: '3/4', shade: true }] }, { label: 'Lee', cells: [{ w: 2, text: '1/2', shade: true }] }] }] },
      { title: "Draw it", text: "So before any math, we draw. Max's bar is 3/4 of a mile. Lee's bar goes right under it, 1/2 of a mile. Both bars start at the same place.",
        beats: [
          { say: "So before any math, we draw.", pic: 0 },
          { say: "Max's bar is 3/4 of a mile. Lee's bar goes right under it, 1/2 of a mile." },
          { say: "Both bars start at the same place." },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Max', cells: [{ w: 3, text: '3/4', shade: true }] }, { label: 'Lee', cells: [{ w: 2, text: '1/2', shade: true }] }], motion: true }] },
      { title: "Find the gap", text: "Now look. Max's bar sticks out past Lee's. That part is how much farther Max ran. Finding a gap means taking away: 3/4 − 1/2.",
        beats: [
          { say: "Now look. Max's bar sticks out past Lee's.", pic: 0 },
          { say: "That part is how much farther Max ran." },
          { say: "Finding a gap means taking away: 3/4 − 1/2." },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Max', cells: [{ w: 3, text: '3/4', shade: true }] }, { label: 'Lee', cells: [{ w: 2, text: '1/2', shade: true }, { w: 1, text: '?' }] }], motion: true }] },
      { title: "Work it out", text: "Make the pieces match first. 1/2 is the same as 2/4. 3 fourths take away 2 fourths leaves 1 fourth. So Max runs 1/4 mile farther.",
        beats: [
          { say: "Make the pieces match first. 1/2 is the same as 2/4.", pic: 0 },
          { say: "3 fourths take away 2 fourths leaves 1 fourth.", pic: 1 },
          { say: "So Max runs 1/4 mile farther." },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Max', cells: [{ w: 3, text: '3/4', shade: true }] }, { label: 'Lee', cells: [{ w: 2, text: '2/4', shade: true }, { w: 1, text: '1/4' }] }] }, eq('3/4 − 2/4 = 1/4')] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't ADD just because you see two numbers. Adding tells how far they ran together. How much farther means the gap, and a gap means take away. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't ADD just because you see two numbers. Adding tells how far they ran together.", pic: 0 },
          { say: "How much farther means the gap, and a gap means take away." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '3/4 + 1/2 = 1 1/4 mile farther', right: '3/4 − 1/2 = 1/4 mile farther' }] },
    ],
    turn: {
      text: 'Kim reads for 2/3 hour. Tom reads for 1/6 hour. How much longer does Kim read?',
      picture: { kind: 'tape', rows: [{ label: 'Kim', cells: [{ w: 4, text: '2/3', shade: true }] }, { label: 'Tom', cells: [{ w: 1, text: '1/6', shade: true }] }] },
      answer: { frac: [3, 6] },
      steps: ['"How much longer" means find the gap, so take away: 2/3 − 1/6.', '2/3 is 4/6.', '4/6 − 1/6 = 3/6, so Kim reads 3/6 hour longer.'],
      prompt: 'Draw it. Then decide: put together, or find the gap.',
      hint1: 'Does "how much longer" mean put the parts together or find the gap?',
      hint2: 'Take 1/6 away from 2/3. Turn the thirds into sixths first.',
      twin: { text: 'Ben paints 1/4 of a fence in the morning and 3/8 of it after lunch. How much of the fence has he painted?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 2, text: '1/4', shade: true }, { w: 3, text: '3/8', shade: true }], brace: '?' }] },
        answer: { frac: [5, 8] },
        steps: ['Both parts of the fence go together, so add: 1/4 + 3/8.', '1/4 is 2/8.', '2/8 + 3/8 = 5/8, so he has painted 5/8 of the fence.'],
        hint1: 'Is this putting parts together or finding a gap?',
        hint2: 'Add the two parts. Turn the fourths into eighths first.' },
    },
    won: { text: 'You drew the story, saw it was a gap, and took away.', sticker: 'Putting parts together gives a sum. The gap between two amounts is a difference.' },
    twinWon: { text: 'You put 1/4 and 3/8 together and found 5/8 of the fence.', sticker: 'Putting parts together gives a sum. The gap between two amounts is a difference.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Ada has 5/6 yard of ribbon. Joe has 1/2 yard. How much more ribbon does Ada have?',
        picture: { kind: 'tape', rows: [{ label: 'Ada', cells: [{ w: 5, text: '5/6', shade: true }] }, { label: 'Joe', cells: [{ w: 3, text: '1/2', shade: true }] }] },
        answer: { frac: [2, 6] },
        steps: ['"How much more" means find the gap, so take away: 5/6 − 1/2.', '1/2 is 3/6.', '5/6 − 3/6 = 2/6, so Ada has 2/6 yard more.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Sue walks 1/3 mile to the store and then 1/2 mile to the park. How far does she walk in all?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 2, text: '1/3', shade: true }, { w: 3, text: '1/2', shade: true }], brace: '?' }] },
        answer: { frac: [5, 6] },
        steps: ['"In all" means put the parts together, so add: 1/3 + 1/2.', '1/3 is 2/6, and 1/2 is 3/6.', '2/6 + 3/6 = 5/6, so she walks 5/6 mile.'] } },
      { why: 'Still "draw it, then decide"', problem: { text: 'A jug has 7/8 quart of milk. You pour out 1/4 quart. How much milk is left?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 7, text: '7/8', shade: true }, { w: 1 }] }] },
        answer: { frac: [5, 8] },
        steps: ['Some milk is poured out, so take away: 7/8 − 1/4.', '1/4 is 2/8.', '7/8 − 2/8 = 5/8, so 5/8 quart is left.'] } },
      { why: 'A little harder', problem: { text: 'A bag has 3/4 pound of nuts. Ali eats 1/3 pound and Rae eats 1/6 pound. How much is left?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 9, text: '3/4', shade: true }] }] },
        answer: { frac: [3, 12] },
        steps: ['Both amounts are eaten, so take both away: 3/4 − 1/3 − 1/6.', 'Use twelfths: 3/4 is 9/12, 1/3 is 4/12, and 1/6 is 2/12.', '9/12 − 4/12 − 2/12 = 3/12, so 3/12 pound is left.'] } },
      { why: 'Same math in a story', problem: { text: 'A plant grows 3/10 inch one week and 1/2 inch the next week. How much does it grow in the two weeks?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 3, text: '3/10', shade: true }, { w: 5, text: '1/2', shade: true }], brace: '?' }] },
        answer: { frac: [8, 10] },
        steps: ['Both weeks go together, so add: 3/10 + 1/2.', '1/2 is 5/10.', '3/10 + 5/10 = 8/10, so it grows 8/10 inch.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m2-t8', title: 'Line plot with fractions', skill: 'Read fraction measurements on a line plot and add or subtract them',
    bigIdea: "Each ✕ is one thing, and the number under it tells how much that thing measured.",
    screens: [
      { scene: 'g5m2-t8', title: 'Bean plants', text: 'Your class measured how much 6 bean plants grew in one week. How much more did the plant that grew the most grow than one that grew the least?',
        pictures: [dot(['1/4', '2/4', '3/4'], [2, 3, 1], 'inches grown')] },
      { title: "Just marks", text: "This chart has no list of numbers, just ✕ marks above a line. So how do we take anything away? First, work out what one ✕ means.",
        beats: [
          { say: "This chart has no list of numbers, just ✕ marks above a line.", pic: 0 },
          { say: "So how do we take anything away? First, work out what one ✕ means." },
        ],
        pictures: [dot(['1/4', '2/4', '3/4'], [2, 3, 1], 'inches grown')] },
      { title: "The big idea", text: "Each ✕ is one thing, and the number under it tells how much that thing measured.",
        beats: [
          { say: "Each ✕ is one thing, and the number under it tells how much that thing measured.", pic: 0 },
        ],
        pictures: [dot(['1/4', '2/4', '3/4'], [2, 3, 1], 'inches grown')] },
      { title: "Each ✕ is one plant", text: "Here, one ✕ is one plant. 2 ✕ marks sit above 1/4, so 2 plants grew 1/4 inch. 3 plants grew 2/4 inch, and 1 plant grew 3/4 inch.",
        beats: [
          { say: "Here, one ✕ is one plant.", pic: 0 },
          { say: "2 ✕ marks sit above 1/4, so 2 plants grew 1/4 inch." },
          { say: "3 plants grew 2/4 inch, and 1 plant grew 3/4 inch." },
        ],
        pictures: [dot(['1/4', '2/4', '3/4'], [2, 3, 1], 'inches grown', true)] },
      { title: "Most and least", text: "Which plant grew the most? Look all the way to the right. That ✕ sits above 3/4. The least is all the way to the left, above 1/4.",
        beats: [
          { say: "Which plant grew the most? Look all the way to the right.", pic: 0 },
          { say: "That ✕ sits above 3/4." },
          { say: "The least is all the way to the left, above 1/4." },
        ],
        pictures: [dot(['1/4', '2/4', '3/4'], [2, 3, 1], 'inches grown', true)] },
      { title: "Take away", text: "The question wants the gap between them, so we take away. 3/4 − 1/4 = 2/4. The plant that grew the most grew 2/4 inch more.",
        beats: [
          { say: "The question wants the gap between them, so we take away.", pic: 0 },
          { say: "3/4 − 1/4 = 2/4.", pic: 1 },
          { say: "The plant that grew the most grew 2/4 inch more." },
        ],
        pictures: [dot(['1/4', '2/4', '3/4'], [2, 3, 1], 'inches grown'), eq('3/4 − 1/4 = 2/4')] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't COUNT the ✕ marks and take those away. The count tells how many plants. The number under them tells how much each one grew. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't COUNT the ✕ marks and take those away.", pic: 0 },
          { say: "The count tells how many plants. The number under them tells how much each one grew." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '3 ✕ − 1 ✕ = 2 inches', right: '3/4 − 1/4 = 2/4 inch' }] },
    ],
    turn: {
      text: 'The chart shows how far 7 snails crawled, in feet. How much farther did the snail that went farthest crawl than the one that went shortest?',
      picture: dot(['1/8', '3/8', '5/8', '7/8'], [1, 3, 2, 1], 'feet crawled'),
      answer: { frac: [6, 8] },
      steps: ['Each ✕ is one snail. The ✕ farthest right is above 7/8, and the ✕ farthest left is above 1/8.', 'Take away: 7/8 − 1/8.', '7/8 − 1/8 = 6/8, so it crawled 6/8 foot farther.'],
      prompt: 'Read the numbers under the ✕ marks. Then take away.',
      hint1: 'Which ✕ is farthest right? Which is farthest left? Read the numbers under them.',
      hint2: 'Take the number under the leftmost ✕ away from the number under the rightmost ✕.',
      twin: { text: 'The chart shows how far 6 frogs jumped, in yards. How much farther was the longest jump than the shortest jump?',
        picture: dot(['1/6', '3/6', '5/6'], [2, 3, 1], 'yards jumped'),
        answer: { frac: [4, 6] },
        steps: ['Each ✕ is one frog. The longest jump is above 5/6, and the shortest is above 1/6.', 'Take away: 5/6 − 1/6.', '5/6 − 1/6 = 4/6, so the longest jump was 4/6 yard farther.'],
        hint1: 'Read the number under the ✕ farthest right and under the ✕ farthest left.',
        hint2: 'Take the shorter jump away from the longer jump.' },
    },
    won: { text: 'You read the numbers under the ✕ marks, then took away.', sticker: 'A chart that shows each measurement as an ✕ above a number line is a line plot.' },
    twinWon: { text: 'You read the ✕ at each end and found a gap of 4/6 yard.', sticker: 'A chart that shows each measurement as an ✕ above a number line is a line plot.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'The chart shows how long 7 worms are, in inches. How much longer is the longest worm than the shortest worm?',
        picture: dot(['1/10', '3/10', '5/10', '7/10'], [2, 1, 3, 1], 'inches long'), answer: { frac: [6, 10] },
        steps: ['The ✕ farthest right is above 7/10. The ✕ farthest left is above 1/10.', 'Take away: 7/10 − 1/10.', '7/10 − 1/10 = 6/10, so it is 6/10 inch longer.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'The chart shows how long 8 pencil stubs are, in inches. How much longer is the longest stub than the shortest stub?',
        picture: dot(['1', '1 1/4', '1 1/2', '1 3/4'], [1, 3, 2, 2], 'inches long'), answer: { frac: [3, 4] },
        steps: ['The ✕ farthest right is above 1 3/4. The ✕ farthest left is above 1.', 'Take away: 1 3/4 − 1.', '1 3/4 − 1 = 3/4, so it is 3/4 inch longer.'] } },
      { why: 'Still "read the numbers"', problem: { text: 'The chart shows how much juice 8 kids drank, in cups. How much did the kids who drank 3/4 cup drink in all?',
        picture: dot(['1/4', '1/2', '3/4', '1'], [2, 3, 2, 1], 'cups of juice'), answer: { frac: [2, 4], whole: 1 },
        steps: ['There are 2 ✕ above 3/4, so 2 kids drank 3/4 cup each.', 'Add: 3/4 + 3/4 = 6/4.', '6/4 is 1 whole and 2/4, so they drank 1 2/4 cups.'] } },
      { why: 'A little harder', problem: { text: 'The chart shows the weights of 4 apples, in pounds. How much do all 4 apples weigh together?',
        picture: dot(['1/4', '1/2', '3/4'], [2, 1, 1], 'pounds'), answer: { frac: [3, 4], whole: 1 },
        steps: ['Each ✕ is one apple: 1/4, 1/4, 1/2 and 3/4.', 'Use fourths: 1/4 + 1/4 + 2/4 + 3/4 = 7/4.', '7/4 is 1 3/4, so the apples weigh 1 3/4 pounds.'] } },
      { why: 'Same math in a story', problem: { text: 'Sam measured the rain on 6 days, in inches. How much more rain fell on the wettest day than on the driest day?',
        picture: dot(['4/8', '5/8', '6/8', '7/8'], [1, 2, 2, 1], 'inches of rain'), answer: { frac: [3, 8] },
        steps: ['The wettest day is the ✕ above 7/8. The driest day is the ✕ above 4/8.', 'Take away: 7/8 − 4/8.', '7/8 − 4/8 = 3/8, so 3/8 inch more rain fell.'] } },
    ],
  },
]

attachChalk(G5M2, G5M2_CHALK)
