/**
 * Grade 5 · Module 3 — Multiplication and division with fractions.
 * Written to docs/new-flow/AUTHORING.md. Topics 3 and 6 are the founder's own Grade 5 examples
 * (a fraction of a fraction: 1/3 × 1/2; how many small pieces fit: 2 ÷ 1/4).
 */
import type { Lesson, Picture } from '../script'
import { attachChalk } from '../chalk'
import { G5M3_CHALK } from './chalk/g5m3'

/** `n` whole bars (pizzas, yards, cups), each optionally cut into `split` pieces or shaded as `parts`/`shaded`. */
const wholes = (n: number, bar: { parts?: number; shaded?: number; split?: number } = {}, motion = false): Picture =>
  ({ kind: 'bars', bars: Array.from({ length: n }, () => ({ parts: bar.parts ?? 1, shaded: bar.shaded ?? 0, split: bar.split })), motion })
/** One bar cut into `parts`, `shaded` of them shaded (a piece of a pie). */
const piece = (parts: number, shaded: number, split?: number, label?: string, motion = false): Picture =>
  ({ kind: 'bars', bars: [{ parts, shaded, split, label }], motion })
/** A tape in `n` equal cells, the first `shade` shaded, under a brace. */
const tape = (n: number, brace?: string, shade = 0, text?: string, motion = false): Picture =>
  ({ kind: 'tape', rows: [{ cells: Array.from({ length: n }, (_, i) => ({ w: 1, shade: i < shade, text })), brace }], motion })
/** A pan as a grid: the top `rows` rows are the part you have (teal); the first `take` columns of that part are yellow. */
const pan = (rows: number, cols: number, have: number, take = 0, motion = false): Picture => ({
  kind: 'grid', rows, cols, motion,
  shade: [...(take ? [{ r: 0, c: 0, h: have, w: take, tone: 2 as const }] : []), { r: 0, c: 0, h: have, w: cols, tone: 1 as const }],
})
/** One square meter cut into `rows` × `cols`; `covR` × `covC` pieces covered. */
const meter = (rows: number, cols: number, covR = 0, covC = 0, motion = false): Picture => ({
  kind: 'grid', rows, cols, top: '1 m', left: '1 m', motion,
  shade: covR ? [{ r: 0, c: 0, h: covR, w: covC, tone: 1 }] : undefined,
})
const cmp = (n: number) => [`bigger than ${n}`, `smaller than ${n}`, `equal to ${n}`]

export const G5M3: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m3-t1', title: 'A fraction is a division', skill: 'Write a division as a fraction (3 ÷ 4 = 3/4)',
    bigIdea: 'A fraction is a share. 3 ÷ 4 is the same as 3/4.',
    screens: [
      { scene: 'g5m3-t1', title: 'Pizza for four', text: '3 pizzas are shared equally by 4 friends. How much pizza does each friend get?',
        pictures: [wholes(3)] },
      { title: 'Not even one each', text: "Count the pizzas with me. 3 pizzas, and 4 friends. There are fewer pizzas than friends, so nobody is getting a whole pizza to themselves. That means our answer is not going to be a whole number.",
        beats: [
          { say: 'Count the pizzas with me. 3 pizzas, and 4 friends.', pic: 0 },
          { say: 'There are fewer pizzas than friends, so nobody is getting a whole pizza to themselves.', write: 'fewer pizzas than friends' },
          { say: 'That means our answer is not going to be a whole number.' },
        ],
        pictures: [wholes(3)] },
      { title: 'The big idea', text: 'A fraction is a share. 3 ÷ 4 is the same as 3/4.',
        beats: [
          { say: 'A fraction is a share.', pic: 0 },
          { say: '3 ÷ 4 is the same as 3/4.', pic: 1 },
        ],
        pictures: [wholes(3), { kind: 'eq', text: '3 ÷ 4 = 3/4' }] },
      { title: 'Cut every pizza', text: "Watch what I do. I'll cut each pizza into 4 equal slices, one slice for every friend. Why 4? Because there are 4 friends, and every pizza gets the same cut.",
        beats: [
          { say: "Watch what I do. I'll cut each pizza into 4 equal slices, one slice for every friend.", pic: 0 },
          { say: 'Why 4? Because there are 4 friends, and every pizza gets the same cut.', write: '4 friends → 4 slices' },
        ],
        pictures: [wholes(3, { split: 4 }, true)] },
      { title: 'One slice from each pizza', text: "Now each friend walks past and takes 1 slice from every pizza. Follow one friend: a slice here, a slice here, a slice here. That's 3 slices, and every one of them is 1/4 of a pizza.",
        beats: [
          { say: 'Now each friend walks past and takes 1 slice from every pizza.', pic: 0 },
          { say: 'Follow one friend: a slice here, a slice here, a slice here.' },
          { say: "That's 3 slices, and every one of them is 1/4 of a pizza.", write: '3 slices of 1/4' },
        ],
        pictures: [wholes(3, { parts: 4, shaded: 1 }, true)] },
      { title: 'Put the slices together', text: "Push those 3 slices together and look what you have. 3 slices of 1/4 make 3/4 of a pizza. So each friend gets 3/4, and there is our answer: 3 ÷ 4 = 3/4.",
        beats: [
          { say: 'Push those 3 slices together and look what you have.', pic: 0 },
          { say: '3 slices of 1/4 make 3/4 of a pizza.' },
          { say: 'So each friend gets 3/4, and there is our answer: 3 ÷ 4 = 3/4.', pic: 1 },
        ],
        pictures: [piece(4, 3, undefined, '3/4'), { kind: 'eq', text: '3 ÷ 4 = 3/4' }] },
      { title: 'One thing not to do', text: "Here is the slip to watch for. Don't flip the two numbers over. The number being shared goes on top, and the number of friends goes underneath.",
        beats: [
          { say: 'Here is the slip to watch for.' },
          { say: "Don't flip the two numbers over.", pic: 0 },
          { say: 'The number being shared goes on top, and the number of friends goes underneath.', write: 'shared on top' },
        ],
        pictures: [{ kind: 'cards', wrong: '3 ÷ 4 = 4/3', right: '3 ÷ 4 = 3/4' }] },
    ],
    turn: {
      text: '2 pizzas are shared equally by 3 friends. How much pizza does each friend get?',
      picture: wholes(2),
      answer: { frac: [2, 3] },
      steps: ['Cut each pizza into 3 equal slices, one for each friend.', 'Each friend gets 1 slice from each of the 2 pizzas. That is 2 slices of 1/3.', 'So 2 ÷ 3 = 2/3.'],
      prompt: 'Cut every pizza so each friend gets a slice. Then count one friend’s slices.',
      hint1: 'How many pizzas are shared? How many friends share them?',
      hint2: 'Cut each pizza into 3 slices. Each friend gets one slice from every pizza. What size is that?',
      twin: { text: '4 pies are shared equally by 5 kids. How much pie does each kid get?',
        picture: wholes(4),
        answer: { frac: [4, 5] },
        steps: ['Cut each pie into 5 equal slices, one for each kid.', 'Each kid gets 1 slice from each of the 4 pies. That is 4 slices of 1/5.', 'So 4 ÷ 5 = 4/5.'],
        hint1: 'How many pies are shared? How many kids share them?',
        hint2: 'Cut each pie into 5 slices. Each kid gets one slice from every pie. Count those slices.' },
    },
    won: { text: 'You turned a sharing problem into a fraction.', sticker: 'The top number (the numerator) is divided by the bottom number (the denominator).' },
    twinWon: { text: 'You shared 4 pies among 5 kids and wrote 4/5.', sticker: 'The top number (the numerator) is divided by the bottom number (the denominator).' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '3 pizzas are shared equally by 5 friends. How much pizza does each friend get?',
        picture: wholes(3), answer: { frac: [3, 5] },
        steps: ['Cut each pizza into 5 equal slices.', 'Each friend gets 1 slice from each of the 3 pizzas: 3 slices of 1/5.', 'So 3 ÷ 5 = 3/5.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Write 5 ÷ 8 as a fraction.',
        picture: { kind: 'eq', text: '5 ÷ 8 = ?' }, answer: { frac: [5, 8] },
        steps: ['A fraction is a share.', 'The number being shared, 5, goes on top. The 8 goes on the bottom.', 'So 5 ÷ 8 = 5/8.'] } },
      { why: 'Still "a fraction is a share"', problem: { text: '7 cups of juice are shared equally by 10 kids. How much juice does each kid get?',
        picture: wholes(7), answer: { frac: [7, 10] },
        steps: ['Cut each cup into 10 equal parts.', 'Each kid gets 1 part from each of the 7 cups: 7 parts of 1/10.', 'So each kid gets 7/10 of a cup.'] } },
      { why: 'A little harder', problem: { text: 'What is 7 ÷ 4? Write it as a mixed number.',
        picture: { kind: 'eq', text: '7 ÷ 4 = ?' }, answer: { frac: [3, 4], whole: 1 },
        steps: ['7 ÷ 4 is 7/4.', '4/4 make 1 whole, and 3/4 are left over.', 'So 7 ÷ 4 = 1 3/4.'] } },
      { why: 'Same math in a story', problem: { text: '5 yards of ribbon are cut into 2 equal pieces. How many yards long is each piece?',
        picture: wholes(5), answer: { frac: [1, 2], whole: 2 },
        steps: ['5 ÷ 2 is 5/2.', '4/2 make 2 wholes, and 1/2 is left over.', 'So each piece is 2 1/2 yards.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m3-t2', title: 'A fraction of a whole number', skill: 'Find a fraction of a whole number (2/3 of 12)',
    bigIdea: 'To find 2/3 of 12, cut 12 into 3 equal parts and take 2 of them.',
    screens: [
      { scene: 'g5m3-t2', title: 'Sharing stickers', text: 'You have 12 stickers. You give 2/3 of them to your sister. How many stickers is that?',
        pictures: [tape(1, '12 stickers')] },
      { title: 'Not 2, and not 3', text: "Careful here. 2/3 is not a number of stickers, so you can't just hand over 2 of them, or 3 of them. First we need to know how big one third of 12 is.",
        beats: [
          { say: "Careful here. 2/3 is not a number of stickers, so you can't just hand over 2 of them, or 3 of them.", pic: 0 },
          { say: 'First we need to know how big one third of 12 is.', write: 'find one part first' },
        ],
        pictures: [tape(1, '12 stickers')] },
      { title: 'The big idea', text: 'To find 2/3 of 12, cut 12 into 3 equal parts and take 2 of them.',
        beats: [
          { say: 'To find 2/3 of 12, cut 12 into 3 equal parts and take 2 of them.', pic: 0 },
        ],
        pictures: [tape(3, '12 stickers')] },
      { title: 'Cut into 3 equal parts', text: "Look at the bottom number, the 3. That one tells us how many equal parts to make, so I'll cut the 12 stickers into 3. 12 ÷ 3 = 4, so there are 4 stickers sitting in each part.",
        beats: [
          { say: 'Look at the bottom number, the 3.', write: 'bottom number → how many parts' },
          { say: "That one tells us how many equal parts to make, so I'll cut the 12 stickers into 3.", pic: 0 },
          { say: '12 ÷ 3 = 4, so there are 4 stickers sitting in each part.', pic: 1 },
        ],
        pictures: [tape(3, '12 stickers', 0, '4', true), { kind: 'eq', text: '12 ÷ 3 = 4' }] },
      { title: 'Take 2 parts', text: "Now the top number, the 2. That one tells us how many parts to take, so I'll shade 2 of them. 4 stickers, and 4 more stickers, is 8.",
        beats: [
          { say: 'Now the top number, the 2.', write: 'top number → how many parts to take' },
          { say: "That one tells us how many parts to take, so I'll shade 2 of them.", pic: 0 },
          { say: '4 stickers, and 4 more stickers, is 8.', pic: 1 },
        ],
        pictures: [tape(3, '12 stickers', 2, '4', true), { kind: 'eq', text: '2 × 4 = 8' }] },
      { title: 'Put it together', text: 'So your sister walks away with 8 stickers. 2/3 of 12 is 8. And notice it came from two small steps, and it will be those same two steps every single time.',
        beats: [
          { say: 'So your sister walks away with 8 stickers.', pic: 0 },
          { say: '2/3 of 12 is 8.', pic: 1 },
          { say: 'And notice it came from two small steps, and it will be those same two steps every single time.', write: 'divide by the bottom, times by the top' },
        ],
        pictures: [tape(3, '12 stickers', 2, '4'), { kind: 'eq', text: '2/3 of 12 = 8', lines: ['12 ÷ 3 = 4', '2 × 4 = 8'] }] },
      { title: 'One thing not to do', text: "Here is where people stop too soon. Don't hand over just one part. 4 is only 1/3 of 12, and we want 2 of those parts.",
        beats: [
          { say: 'Here is where people stop too soon.' },
          { say: "Don't hand over just one part.", pic: 0 },
          { say: '4 is only 1/3 of 12, and we want 2 of those parts.' },
        ],
        pictures: [{ kind: 'cards', wrong: '2/3 of 12 = 4', right: '2/3 of 12 = 8' }] },
    ],
    turn: {
      text: 'What is 3/4 of 20?',
      picture: tape(4, '20'),
      answer: 15,
      steps: ['Cut 20 into 4 equal parts: 20 ÷ 4 = 5.', 'Take 3 of the parts: 3 × 5.', 'So 3/4 of 20 is 15.'],
      prompt: 'Cut into equal parts first. Then take the parts the top number asks for.',
      hint1: 'How many equal parts do you cut 20 into?',
      hint2: 'Find one part first: 20 ÷ 4. Then take 3 of those parts.',
      twin: { text: 'What is 2/5 of 30?',
        picture: tape(5, '30'),
        answer: 12,
        steps: ['Cut 30 into 5 equal parts: 30 ÷ 5 = 6.', 'Take 2 of the parts: 2 × 6.', 'So 2/5 of 30 is 12.'],
        hint1: 'How many equal parts does the bottom number tell you to make?',
        hint2: 'Find one part first: 30 ÷ 5. Then take 2 of those parts.' },
    },
    won: { text: 'You found one part, then took 3 of them.', sticker: '"3/4 of 20" means 3/4 × 20. In math, "of" means times.' },
    twinWon: { text: 'You cut 30 into 5 equal parts and took 2 of them.', sticker: '"2/5 of 30" means 2/5 × 30. In math, "of" means times.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What is 2/3 of 15?',
        picture: tape(3, '15'), answer: 10,
        steps: ['15 ÷ 3 = 5, so each part is 5.', 'Take 2 parts: 2 × 5.', 'So 2/3 of 15 is 10.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is 3/5 of 25?',
        picture: tape(5, '25'), answer: 15,
        steps: ['25 ÷ 5 = 5, so each part is 5.', 'Take 3 parts: 3 × 5.', 'So 3/5 of 25 is 15.'] } },
      { why: 'Still "one part, then take some"', problem: { text: 'What is 5/6 of 18?',
        picture: tape(6, '18'), answer: 15,
        steps: ['18 ÷ 6 = 3, so each part is 3.', 'Take 5 parts: 5 × 3.', 'So 5/6 of 18 is 15.'] } },
      { why: 'A little harder', problem: { text: 'What is 5/8 of 48?',
        picture: tape(8, '48'), answer: 30,
        steps: ['48 ÷ 8 = 6, so each part is 6.', 'Take 5 parts: 5 × 6.', 'So 5/8 of 48 is 30.'] } },
      { why: 'Same math in a story', problem: { text: 'A class has 28 students. 3/4 of them walk to school. How many students walk to school?',
        picture: tape(4, '28 students'), answer: 21,
        steps: ['Cut 28 into 4 equal parts: 28 ÷ 4 = 7.', 'Take 3 parts: 3 × 7.', 'So 21 students walk to school.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m3-t3', title: 'A fraction of a fraction', skill: 'Multiply a fraction by a fraction with an area picture',
    bigIdea: 'You are taking a piece of a piece. The answer is a smaller piece of the whole pan.',
    screens: [
      { scene: 'g5m3-t3', title: 'Half a pan', text: 'You have half a pan of brownies. You eat 1/3 of that half. How much of the whole pan did you eat?',
        pictures: [pan(2, 3, 1)] },
      { title: 'A third of what?', text: 'Here is the tricky part, and it is worth slowing down for. That 1/3 is a third of the half, not a third of the whole pan. So we have to go and find your piece on the whole pan.',
        beats: [
          { say: 'Here is the tricky part, and it is worth slowing down for.', pic: 0 },
          { say: 'That 1/3 is a third of the half, not a third of the whole pan.', write: 'a third of the HALF' },
          { say: 'So we have to go and find your piece on the whole pan.' },
        ],
        pictures: [pan(2, 3, 1)] },
      { title: 'The big idea', text: 'You are taking a piece of a piece. The answer is a smaller piece of the whole pan.',
        beats: [
          { say: 'You are taking a piece of a piece.', pic: 0 },
          { say: 'The answer is a smaller piece of the whole pan.' },
        ],
        pictures: [pan(2, 3, 1, 1)] },
      { title: 'Shade the half', text: "Let's draw the pan. It is cut into 2 equal rows, and the top row is the part you have. So that top row is 1/2 of the pan.",
        beats: [
          { say: "Let's draw the pan. It is cut into 2 equal rows, and the top row is the part you have.", pic: 0 },
          { say: 'So that top row is 1/2 of the pan.', write: 'top row = 1/2' },
        ],
        pictures: [pan(2, 3, 1, 0, true)] },
      { title: 'Take 1/3 of the half', text: 'Now cut the other way. The pan is also in 3 equal columns, so your half is sitting in 3 pieces. You eat 1 of those 3.',
        beats: [
          { say: 'Now cut the other way.', pic: 0 },
          { say: 'The pan is also in 3 equal columns, so your half is sitting in 3 pieces.' },
          { say: 'You eat 1 of those 3.', write: '1 of the 3 pieces in your half' },
        ],
        pictures: [pan(2, 3, 1, 1, true)] },
      { title: 'Count on the whole pan', text: 'Now step back and look at the whole pan. 2 rows across 3 columns makes 6 equal pieces, and you ate 1 of them. So 1/3 × 1/2 = 1/6.',
        beats: [
          { say: 'Now step back and look at the whole pan.', pic: 0 },
          { say: '2 rows across 3 columns makes 6 equal pieces, and you ate 1 of them.', write: 'rows × columns = pieces in the pan' },
          { say: 'So 1/3 × 1/2 = 1/6.', pic: 1 },
        ],
        pictures: [pan(2, 3, 1, 1), { kind: 'eq', text: '1/3 × 1/2 = 1/6', lines: ['1 × 1 = 1 piece eaten', '3 × 2 = 6 pieces in the pan'] }] },
      { title: 'One thing not to do', text: "One last thing, and it surprises people every time. Don't expect a bigger number here. You ate a piece of a piece, so 1/6 is smaller than the half you started with.",
        beats: [
          { say: 'One last thing, and it surprises people every time.' },
          { say: "Don't expect a bigger number here.", pic: 0 },
          { say: 'You ate a piece of a piece, so 1/6 is smaller than the half you started with.' },
        ],
        pictures: [{ kind: 'cards', wrong: '1/3 × 1/2 is more than 1/2', right: '1/3 × 1/2 = 1/6, less than 1/2' }] },
    ],
    turn: {
      text: 'You have half a pan. You eat 1/4 of that half. How much of the whole pan is that? Find 1/4 × 1/2.',
      picture: pan(2, 4, 1),
      answer: { frac: [1, 8] },
      steps: ['The half is the top row. The pan is cut into 4 columns, so the half has 4 pieces.', 'You eat 1 of those 4 pieces. The whole pan has 2 × 4 = 8 pieces.', 'So 1/4 × 1/2 = 1/8.'],
      prompt: 'Take the piece of the half. Then count how many pieces like it fill the whole pan.',
      hint1: 'The top row is the half. How many pieces is it cut into?',
      hint2: 'Take 1 piece of the top row. How many pieces like that make the whole pan?',
      twin: { text: 'You have 1/4 of a pan. You eat 1/3 of that part. How much of the whole pan is that? Find 1/3 × 1/4.',
        picture: pan(4, 3, 1),
        answer: { frac: [1, 12] },
        steps: ['Your part is the top row. The pan is cut into 3 columns, so your part has 3 pieces.', 'You eat 1 of those 3 pieces. The whole pan has 4 × 3 pieces.', 'So 1/3 × 1/4 = 1/12.'],
        hint1: 'The shaded row is your part. How many pieces is it cut into?',
        hint2: 'Take 1 piece of the shaded row. Count how many pieces like it fill the whole pan.' },
    },
    won: { text: 'You took a piece of a piece and found it on the whole pan.', sticker: 'The answer when you multiply is called the product.' },
    twinWon: { text: 'You found 1/3 of 1/4 of the pan: 1/12.', sticker: 'The answer when you multiply is called the product.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'You have 1/4 of a pan. You eat 1/2 of that part. Find 1/2 × 1/4.',
        picture: pan(4, 2, 1), answer: { frac: [1, 8] },
        steps: ['Your part is the top row, cut into 2 pieces.', 'You eat 1 of the 2 pieces. The whole pan has 4 × 2 = 8 pieces.', 'So 1/2 × 1/4 = 1/8.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Find 1/2 × 1/5. The shaded row is 1/5 of the pan.',
        picture: pan(5, 2, 1), answer: { frac: [1, 10] },
        steps: ['The shaded row is 1/5 of the pan, cut into 2 pieces.', 'Take 1 of the 2 pieces. The whole pan has 5 × 2 = 10 pieces.', 'So 1/2 × 1/5 = 1/10.'] } },
      { why: 'Still "a piece of a piece"', problem: { text: 'Find 2/3 × 1/2. The shaded row is 1/2 of the pan.',
        picture: pan(2, 3, 1), answer: { frac: [2, 6] },
        steps: ['The shaded row is 1/2 of the pan, cut into 3 pieces.', 'Take 2 of the 3 pieces. The whole pan has 2 × 3 = 6 pieces.', 'So 2/3 × 1/2 = 2/6, which is the same as 1/3.'] } },
      { why: 'A little harder', problem: { text: 'Find 3/4 × 2/3. The shaded rows are 2/3 of the pan.',
        picture: pan(3, 4, 2), answer: { frac: [6, 12] },
        steps: ['The 2 shaded rows are 2/3 of the pan. Each row is cut into 4 pieces.', 'Take 3/4 of each shaded row: 3 pieces in each of 2 rows is 6 pieces. The pan has 3 × 4 = 12 pieces.', 'So 3/4 × 2/3 = 6/12, which is the same as 1/2.'] } },
      { why: 'Same math in a story', problem: { text: 'Half of a garden has flowers. 3/5 of the flower part has red flowers. What part of the whole garden has red flowers?',
        picture: pan(2, 5, 1), answer: { frac: [3, 10] },
        steps: ['The flower half is the top row, cut into 5 pieces.', 'Take 3 of those 5 pieces. The whole garden has 2 × 5 = 10 pieces.', 'So 3/10 of the garden has red flowers.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m3-t4', title: 'Area with fraction sides', skill: 'Find the area of a rectangle with fraction side lengths',
    bigIdea: 'Put the rectangle on one square meter. Count the pieces it covers out of all the pieces.',
    screens: [
      { scene: 'g5m3-t4', title: 'A small rug', text: 'A rug is 1/2 meter wide and 3/4 meter long. How much floor does it cover?',
        pictures: [meter(2, 4, 1, 3)] },
      { title: 'No whole squares to count', text: 'With whole-number sides you would just count square meters. But look at this rug. It is smaller than one square meter, so there is not even one whole square to count.',
        beats: [
          { say: 'With whole-number sides you would just count square meters.', pic: 0 },
          { say: 'But look at this rug.' },
          { say: 'It is smaller than one square meter, so there is not even one whole square to count.' },
        ],
        pictures: [meter(2, 4, 1, 3)] },
      { title: 'The big idea', text: 'Put the rectangle on one square meter. Count the pieces it covers out of all the pieces.',
        beats: [
          { say: 'Put the rectangle on one square meter.', pic: 0 },
          { say: 'Count the pieces it covers out of all the pieces.' },
        ],
        pictures: [meter(2, 4, 1, 3)] },
      { title: 'Cut one square meter', text: "Start with a square that is 1 meter on every side. The rug is 1/2 by 3/4, so I'll cut that square into 2 equal rows and 4 equal columns. Count them up: 8 equal pieces.",
        beats: [
          { say: 'Start with a square that is 1 meter on every side.', pic: 0 },
          { say: "The rug is 1/2 by 3/4, so I'll cut that square into 2 equal rows and 4 equal columns.", write: 'bottom numbers → rows and columns' },
          { say: 'Count them up: 8 equal pieces.' },
        ],
        pictures: [meter(2, 4)] },
      { title: 'Lay the rug on it', text: 'Now lay the rug down on that square. 1/2 meter is 1 of the 2 rows, and 3/4 meter is 3 of the 4 columns. So the rug covers one row, 3 pieces across.',
        beats: [
          { say: 'Now lay the rug down on that square.', pic: 0 },
          { say: '1/2 meter is 1 of the 2 rows, and 3/4 meter is 3 of the 4 columns.' },
          { say: 'So the rug covers one row, 3 pieces across.' },
        ],
        pictures: [meter(2, 4, 1, 3, true)] },
      { title: 'Count the pieces', text: 'Count what is underneath the rug: 3 pieces out of the 8. So the rug covers 3/8 of a square meter. And look, 1/2 × 3/4 = 3/8. Side times side, just like always.',
        beats: [
          { say: 'Count what is underneath the rug: 3 pieces out of the 8.', pic: 0 },
          { say: 'So the rug covers 3/8 of a square meter.' },
          { say: 'And look, 1/2 × 3/4 = 3/8. Side times side, just like always.', pic: 1, write: 'side × side = area' },
        ],
        pictures: [meter(2, 4, 1, 3), { kind: 'eq', text: '1/2 × 3/4 = 3/8' }] },
      { title: 'One thing not to do', text: "Here is the one to watch. Don't add the two sides together. Adding tells you how far it is along two edges, not how much floor is covered.",
        beats: [
          { say: 'Here is the one to watch.' },
          { say: "Don't add the two sides together.", pic: 0 },
          { say: 'Adding tells you how far it is along two edges, not how much floor is covered.' },
        ],
        pictures: [{ kind: 'cards', wrong: '1/2 + 3/4 square meter', right: '1/2 × 3/4 = 3/8 square meter' }] },
    ],
    turn: {
      text: 'A mat is 1/2 meter wide and 2/3 meter long. What is its area, in square meters?',
      picture: meter(2, 3),
      answer: { frac: [2, 6] },
      steps: ['Cut 1 square meter into 2 rows and 3 columns: 6 equal pieces.', 'The mat covers 1 row and 2 columns, so 2 of the 6 pieces.', 'So the area is 2/6 square meter, the same as 1/3.'],
      prompt: 'Cut one square meter to match the sides. Count the pieces the mat covers.',
      hint1: 'Cut the square into 2 rows and 3 columns. How many pieces is that?',
      hint2: 'Which rows and columns does the mat cover? Count those pieces out of all the pieces.',
      twin: { text: 'A shelf board is 1/3 meter wide and 3/4 meter long. What is its area, in square meters?',
        picture: meter(3, 4),
        answer: { frac: [3, 12] },
        steps: ['Cut 1 square meter into 3 rows and 4 columns: 3 × 4 equal pieces.', 'The board covers 1 row and 3 columns, so 3 pieces.', 'So the area is 3/12 square meter, the same as 1/4.'],
        hint1: 'Cut the square into 3 rows and 4 columns. How many pieces is that?',
        hint2: 'How many rows and how many columns does the board cover? Count those pieces.' },
    },
    won: { text: 'You put the mat on one square meter and counted its pieces.', sticker: 'Area is length × width, even when the sides are fractions.' },
    twinWon: { text: 'You found that a 1/3 by 3/4 board covers 3/12 of a square meter.', sticker: 'Area is length × width, even when the sides are fractions.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A napkin is 1/2 meter wide and 3/5 meter long. What is its area, in square meters?',
        picture: meter(2, 5), answer: { frac: [3, 10] },
        steps: ['2 rows and 5 columns make 10 equal pieces.', 'The napkin covers 1 row and 3 columns: 3 pieces.', 'So the area is 3/10 square meter.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A picture is 1/4 meter wide and 2/3 meter tall. What is its area, in square meters?',
        picture: meter(4, 3), answer: { frac: [2, 12] },
        steps: ['4 rows and 3 columns make 12 equal pieces.', 'The picture covers 1 row and 2 columns: 2 pieces.', 'So the area is 2/12 square meter, the same as 1/6.'] } },
      { why: 'Still "count the pieces it covers"', problem: { text: 'A tray is 2/3 meter wide and 3/4 meter long. What is its area, in square meters?',
        picture: meter(3, 4), answer: { frac: [6, 12] },
        steps: ['3 rows and 4 columns make 12 equal pieces.', 'The tray covers 2 rows and 3 columns: 2 × 3 = 6 pieces.', 'So the area is 6/12 square meter, the same as 1/2.'] } },
      { why: 'A little harder', problem: { text: 'A garden patch is 3/4 meter wide and 4/5 meter long. What is its area, in square meters?',
        picture: meter(4, 5), answer: { frac: [12, 20] },
        steps: ['4 rows and 5 columns make 20 equal pieces.', 'The patch covers 3 rows and 4 columns: 3 × 4 = 12 pieces.', 'So the area is 12/20 square meter, the same as 3/5.'] } },
      { why: 'Same math in a story', problem: { text: 'Mia paints a window pane that is 2/5 meter wide and 3/4 meter tall. How many square meters does she paint?',
        picture: meter(4, 5), answer: { frac: [6, 20] },
        steps: ['Cut 1 square meter into 4 rows and 5 columns: 20 equal pieces.', 'The pane covers 3 rows and 2 columns: 3 × 2 = 6 pieces.', 'So Mia paints 6/20 square meter, the same as 3/10.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m3-t5', title: 'Times less than 1 makes it smaller', skill: 'Tell if a product is bigger or smaller than a number without working it out',
    bigIdea: 'Multiply by less than 1 and you get part of the amount, multiply by more than 1 and you get more than all of it.',
    screens: [
      { scene: 'g5m3-t5', title: 'Part of a recipe', text: 'A recipe uses 8 cups of flour. You make 3/4 of the recipe. Will you use more than 8 cups, or less?',
        pictures: [{ kind: 'tape', rows: [{ label: 'Recipe', cells: [{ w: 8, text: '8 cups' }] }] }] },
      { title: 'Times used to mean more', text: "Up to now, times made numbers bigger. 3 × 8 = 24. But look at the 3. It's more than 1. 3/4 is less than 1. So what happens?",
        beats: [
          { say: 'Up to now, times made numbers bigger.', pic: 0 },
          { say: "3 × 8 = 24. But look at the 3. It's more than 1." },
          { say: '3/4 is less than 1. So what happens?' },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Recipe', cells: [{ w: 8, text: '8 cups' }] }] }] },
      { title: 'The big idea', text: 'Multiply by less than 1 and you get part of the amount, multiply by more than 1 and you get more than all of it.',
        beats: [
          { say: 'Multiply by less than 1 and you get part of the amount, multiply by more than 1 and you get more than all of it.', pic: 0 },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Recipe', cells: [{ w: 8, text: '8' }] }, { label: '3/4 ×', cells: [{ w: 6, text: '6', shade: true }, { w: 2 }] }] }] },
      { title: 'Times 1 keeps it the same', text: "Start with 1 × 8. That's one whole recipe. It uses the same 8 cups. Nothing changes.",
        beats: [
          { say: "Start with 1 × 8. That's one whole recipe.", pic: 0 },
          { say: 'It uses the same 8 cups. Nothing changes.' },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Recipe', cells: [{ w: 8, text: '8' }] }, { label: '1 ×', cells: [{ w: 8, text: '8', shade: true }] }], motion: true }] },
      { title: 'Times less than 1', text: "Now 3/4 × 8. Is 3/4 more than 1? No, less. So cut the 8 cups into 4 equal parts, and take 3. That's 6 cups, less than 8.",
        beats: [
          { say: 'Now 3/4 × 8. Is 3/4 more than 1? No, less.', pic: 0 },
          { say: 'So cut the 8 cups into 4 equal parts, and take 3.' },
          { say: "That's 6 cups, less than 8." },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Recipe', cells: [{ w: 8, text: '8' }] }, { label: '3/4 ×', cells: [{ w: 6, text: '6', shade: true }, { w: 2 }] }], motion: true }] },
      { title: 'Times more than 1', text: "Now 1 1/2 × 8. That's more than 1 whole. So you get all 8 cups, and half of 8 again. 8 + 4 = 12 cups, more than you started with.",
        beats: [
          { say: "Now 1 1/2 × 8. That's more than 1 whole.", pic: 0 },
          { say: 'So you get all 8 cups, and half of 8 again.' },
          { say: '8 + 4 = 12 cups, more than you started with.' },
        ],
        pictures: [{ kind: 'tape', rows: [{ label: 'Recipe', cells: [{ w: 8, text: '8' }] }, { label: '1 1/2 ×', cells: [{ w: 8, text: '8', shade: true }, { w: 4, text: '4', shade: true }] }], motion: true }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't think times ALWAYS makes it bigger. Look at what you multiply by first. 3/4 is less than 1, so 3/4 × 8 comes out smaller. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't think times ALWAYS makes it bigger.", pic: 0 },
          { say: 'Look at what you multiply by first. 3/4 is less than 1, so 3/4 × 8 comes out smaller.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '3/4 × 8 is bigger than 8', right: '3/4 × 8 is smaller than 8' }] },
    ],
    turn: {
      text: 'Without working it out: is 2/3 × 9 bigger than 9, smaller than 9, or equal to 9?',
      picture: tape(1, '9'),
      answer: { choices: cmp(9), correct: 1 },
      steps: ['Look at the number you multiply by: 2/3.', '2/3 is less than 1, so you get only part of 9.', 'So 2/3 × 9 is smaller than 9.'],
      prompt: 'Is the fraction more than 1, less than 1, or exactly 1?',
      hint1: 'Is 2/3 more than 1 or less than 1?',
      hint2: 'If you take 2/3 of 9 things, do you get all of them, more than all, or only some?',
      twin: { text: 'Without working it out: is 5/4 × 6 bigger than 6, smaller than 6, or equal to 6?',
        picture: tape(1, '6'),
        answer: { choices: cmp(6), correct: 0 },
        steps: ['Look at the number you multiply by: 5/4.', '4/4 is 1 whole, so 5/4 is more than 1. You get all of 6 and a bit more.', 'So 5/4 × 6 is bigger than 6.'],
        hint1: 'Is 5/4 more than 4/4 or less?',
        hint2: 'Four fourths make 1 whole. Is the number you multiply by more than that, or less?' },
    },
    won: { text: 'You looked at the fraction first and knew the answer would be smaller.', sticker: 'Making a number bigger or smaller by multiplying is called scaling.' },
    twinWon: { text: 'You saw that 5/4 is more than 1, so 5/4 × 6 is bigger than 6.', sticker: 'Making a number bigger or smaller by multiplying is called scaling.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Is 3/4 × 12 bigger than 12, smaller than 12, or equal to 12?',
        picture: tape(1, '12'), answer: { choices: cmp(12), correct: 1 },
        steps: ['You multiply by 3/4.', '3/4 is less than 1, so you get only part of 12.', 'So 3/4 × 12 is smaller than 12.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Is 4/4 × 7 bigger than 7, smaller than 7, or equal to 7?',
        picture: tape(1, '7'), answer: { choices: cmp(7), correct: 2 },
        steps: ['4/4 is exactly 1 whole.', '1 times a number is that same number.', 'So 4/4 × 7 is equal to 7.'] } },
      { why: 'Still "less than 1 makes it smaller"', problem: { text: 'Is 7/3 × 5 bigger than 5, smaller than 5, or equal to 5?',
        picture: tape(1, '5'), answer: { choices: cmp(5), correct: 0 },
        steps: ['3/3 is 1 whole, so 7/3 is more than 1.', 'You get all of 5 and more.', 'So 7/3 × 5 is bigger than 5.'] } },
      { why: 'A little harder', problem: { text: 'Work it out: what is 3/5 × 10? Check that it is smaller than 10.',
        picture: tape(1, '10'), answer: 6,
        steps: ['10 ÷ 5 = 2, so 1/5 of 10 is 2.', '3/5 is 3 of those parts: 3 × 2.', 'So 3/5 × 10 = 6, which is smaller than 10.'] } },
      { why: 'Same math in a story', problem: { text: 'A puppy weighs 10 pounds. A kitten weighs 1/2 as much as the puppy. Does the kitten weigh more than 10 pounds, less than 10 pounds, or exactly 10 pounds?',
        picture: tape(1, '10 pounds'), answer: { choices: ['more than 10 pounds', 'less than 10 pounds', 'exactly 10 pounds'], correct: 1 },
        steps: ['The kitten weighs 1/2 × 10 pounds.', '1/2 is less than 1, so it is only part of 10.', 'So the kitten weighs less than 10 pounds.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m3-t6', title: 'How many small pieces fit?', skill: 'Divide a whole number by a unit fraction',
    bigIdea: 'Dividing by a small piece asks how many of those pieces fit.',
    screens: [
      { scene: 'g5m3-t6', title: 'Making bows', text: 'You have 2 yards of ribbon. Each bow uses 1/4 yard. How many bows can you make?',
        pictures: [wholes(2)] },
      { title: 'Sharing does not fit', text: 'Usually, dividing means sharing. But can you share 2 yards among 1/4 of a friend? No. So dividing by 1/4 must ask something else.',
        beats: [
          { say: 'Usually, dividing means sharing.', pic: 0 },
          { say: 'But can you share 2 yards among 1/4 of a friend? No.' },
          { say: 'So dividing by 1/4 must ask something else.' },
        ],
        pictures: [wholes(2)] },
      { title: 'The big idea', text: 'Dividing by a small piece asks how many of those pieces fit.',
        beats: [
          { say: 'Dividing by a small piece asks how many of those pieces fit.', pic: 0 },
        ],
        pictures: [wholes(2, { split: 4 })] },
      { title: 'Cut each yard into fourths', text: 'Each bow takes 1/4 of a yard. So cut every yard into 4 equal pieces, one piece for each bow.',
        beats: [
          { say: 'Each bow takes 1/4 of a yard.' },
          { say: 'So cut every yard into 4 equal pieces, one piece for each bow.', pic: 0 },
        ],
        pictures: [wholes(2, { split: 4 }, true)] },
      { title: 'Count the pieces', text: "Now count the pieces with me. The first yard gives 4. The second yard gives 4 more. Four, eight. That's 8 pieces, so 8 bows.",
        beats: [
          { say: 'Now count the pieces with me.', pic: 0 },
          { say: 'The first yard gives 4. The second yard gives 4 more.' },
          { say: "Four, eight. That's 8 pieces, so 8 bows." },
        ],
        pictures: [wholes(2, { parts: 4, shaded: 4 }, true)] },
      { title: 'Put it together', text: "So 8 fourths fit in 2 yards. That's what 2 ÷ 1/4 asks. 2 ÷ 1/4 = 8. Each yard holds 4, so 2 yards hold 2 × 4 = 8.",
        beats: [
          { say: 'So 8 fourths fit in 2 yards.', pic: 0 },
          { say: "That's what 2 ÷ 1/4 asks. 2 ÷ 1/4 = 8.", pic: 1 },
          { say: 'Each yard holds 4, so 2 yards hold 2 × 4 = 8.' },
        ],
        pictures: [wholes(2, { parts: 4, shaded: 4 }), { kind: 'eq', text: '2 ÷ 1/4 = 8', lines: ['4 pieces in each yard', '2 × 4 = 8'] }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't answer 1/2. That's 2 ÷ 4, NOT 2 ÷ 1/4. Small pieces fit many times, so the answer is bigger than 2. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't answer 1/2. That's 2 ÷ 4, NOT 2 ÷ 1/4.", pic: 0 },
          { say: 'Small pieces fit many times, so the answer is bigger than 2.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '2 ÷ 1/4 = 1/2', right: '2 ÷ 1/4 = 8' }] },
    ],
    turn: {
      text: 'You have 3 yards of ribbon. Each bow uses 1/2 yard. How many bows can you make? Find 3 ÷ 1/2.',
      picture: wholes(3),
      answer: 6,
      steps: ['Cut each yard into halves. Each yard holds 2 halves.', '3 yards with 2 halves each is 3 × 2 halves.', 'So 3 ÷ 1/2 = 6.'],
      prompt: 'Cut every yard into pieces the size of one bow. Count all the pieces.',
      hint1: 'How many halves fit in 1 yard?',
      hint2: 'Each yard holds the same number of halves. Count them for all 3 yards.',
      twin: { text: 'You have 4 cups of rice. Each bowl gets 1/3 cup. How many bowls can you fill? Find 4 ÷ 1/3.',
        picture: wholes(4),
        answer: 12,
        steps: ['Cut each cup into thirds. Each cup holds 3 thirds.', '4 cups with 3 thirds each is 4 × 3 thirds.', 'So 4 ÷ 1/3 = 12.'],
        hint1: 'How many thirds fit in 1 cup?',
        hint2: 'Count the thirds in one cup. Every cup holds the same number, so do it for all 4 cups.' },
    },
    won: { text: 'You counted how many little pieces fit.', sticker: 'A fraction with 1 on top, like 1/2, is called a unit fraction.' },
    twinWon: { text: 'You counted how many 1/3 cups fit in 4 cups: 12 bowls.', sticker: 'A fraction with 1 on top, like 1/3, is called a unit fraction.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'You have 2 yards of ribbon. Each bow uses 1/3 yard. How many bows? Find 2 ÷ 1/3.',
        picture: wholes(2), answer: 6,
        steps: ['Each yard holds 3 thirds.', '2 yards with 3 thirds each is 2 × 3 thirds.', 'So 2 ÷ 1/3 = 6.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Find 5 ÷ 1/2.',
        picture: wholes(5), answer: 10,
        steps: ['Each whole holds 2 halves.', '5 wholes with 2 halves each is 5 × 2 halves.', 'So 5 ÷ 1/2 = 10.'] } },
      { why: 'Still "how many pieces fit"', problem: { text: 'Find 3 ÷ 1/4.',
        picture: wholes(3), answer: 12,
        steps: ['Each whole holds 4 fourths.', '3 wholes with 4 fourths each is 3 × 4 fourths.', 'So 3 ÷ 1/4 = 12.'] } },
      { why: 'A little harder', problem: { text: 'Find 6 ÷ 1/5.',
        picture: wholes(6), answer: 30,
        steps: ['Each whole holds 5 fifths.', '6 wholes with 5 fifths each is 6 × 5 fifths.', 'So 6 ÷ 1/5 = 30.'] } },
      { why: 'Same math in a story', problem: { text: 'A pizza shop has 4 pizzas. Each slice is 1/6 of a pizza. How many slices are there?',
        picture: wholes(4), answer: 24,
        steps: ['Each pizza holds 6 slices of 1/6.', '4 pizzas with 6 slices each is 4 × 6 slices.', 'So there are 24 slices.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m3-t7', title: 'Share a small piece', skill: 'Divide a unit fraction by a whole number',
    bigIdea: 'To share a piece, cut it up, then see how big one share is in the whole.',
    screens: [
      { scene: 'g5m3-t7', title: 'Leftover pie', text: 'Half of a pie is left. 3 friends share it equally. How much of the whole pie does each friend get?',
        pictures: [piece(2, 1)] },
      { title: 'A third of what?', text: 'Each friend gets 1 of 3 pieces of the half. But is that 1/3 of the pie? No. The question asks about the whole pie, not the half.',
        beats: [
          { say: 'Each friend gets 1 of 3 pieces of the half.', pic: 0 },
          { say: 'But is that 1/3 of the pie? No.' },
          { say: 'The question asks about the whole pie, not the half.' },
        ],
        pictures: [piece(2, 1)] },
      { title: 'The big idea', text: 'To share a piece, cut it up, then see how big one share is in the whole.',
        beats: [
          { say: 'To share a piece, cut it up, then see how big one share is in the whole.', pic: 0 },
        ],
        pictures: [piece(2, 1, 3)] },
      { title: 'Look at the whole pie', text: "Draw the whole pie first. It's 2 halves. The shaded half is what's left.",
        beats: [
          { say: 'Draw the whole pie first.', pic: 0 },
          { say: "It's 2 halves. The shaded half is what's left." },
        ],
        pictures: [piece(2, 1, undefined, undefined, true)] },
      { title: 'Cut the half into 3', text: "Now cut that half into 3 equal pieces, one for each friend. Here's the move that matters. Give the other half the same cuts. Now the whole pie has 6 equal pieces.",
        beats: [
          { say: 'Now cut that half into 3 equal pieces, one for each friend.', pic: 0 },
          { say: "Here's the move that matters. Give the other half the same cuts." },
          { say: 'Now the whole pie has 6 equal pieces.' },
        ],
        pictures: [piece(2, 1, 3, undefined, true)] },
      { title: 'One share of the whole', text: "Each friend gets 1 of those 6 pieces. That's 1/6 of the whole pie. So 1/2 ÷ 3 = 1/6.",
        beats: [
          { say: 'Each friend gets 1 of those 6 pieces.', pic: 0 },
          { say: "That's 1/6 of the whole pie." },
          { say: 'So 1/2 ÷ 3 = 1/6.', pic: 1 },
        ],
        pictures: [piece(6, 1, undefined, '1/6'), { kind: 'eq', text: '1/2 ÷ 3 = 1/6' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Sharing does not make a piece BIGGER. 1/2 ÷ 3 is not 3/2. Each share is smaller than the half. It's 1/6. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: 'Sharing does not make a piece BIGGER. 1/2 ÷ 3 is not 3/2.', pic: 0 },
          { say: "Each share is smaller than the half. It's 1/6." },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '1/2 ÷ 3 = 3/2', right: '1/2 ÷ 3 = 1/6' }] },
    ],
    turn: {
      text: '1/4 of a pie is left. 2 friends share it equally. How much of the whole pie does each friend get? Find 1/4 ÷ 2.',
      picture: piece(4, 1),
      answer: { frac: [1, 8] },
      steps: ['Cut the 1/4 into 2 equal pieces, one for each friend.', 'Give every fourth the same cut. The whole pie has 4 × 2 = 8 pieces.', 'So 1/4 ÷ 2 = 1/8.'],
      prompt: 'Cut the shaded piece for the friends. Then count pieces that size in the whole pie.',
      hint1: 'Cut the shaded part into 2 equal pieces.',
      hint2: 'If every part of the pie got the same cut, how many pieces would the whole pie have?',
      twin: { text: '1/3 of a pan of cornbread is left. 4 kids share it equally. How much of the whole pan does each kid get? Find 1/3 ÷ 4.',
        picture: piece(3, 1),
        answer: { frac: [1, 12] },
        steps: ['Cut the 1/3 into 4 equal pieces, one for each kid.', 'Give every third the same cuts. The whole pan has 3 × 4 pieces.', 'So 1/3 ÷ 4 = 1/12.'],
        hint1: 'Cut the shaded part into 4 equal pieces.',
        hint2: 'Give every third the same cuts. How many pieces are in the whole pan?' },
    },
    won: { text: 'You shared the piece, then saw how big one share is in the whole pie.', sticker: 'The answer to a division is called the quotient.' },
    twinWon: { text: 'You shared 1/3 among 4 kids and got 1/12 each.', sticker: 'The answer to a division is called the quotient.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Half of a pie is left. 2 friends share it equally. Find 1/2 ÷ 2.',
        picture: piece(2, 1), answer: { frac: [1, 4] },
        steps: ['Cut the half into 2 equal pieces.', 'Give the other half the same cut. The whole pie has 2 × 2 = 4 pieces.', 'So 1/2 ÷ 2 = 1/4.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Find 1/5 ÷ 2.',
        picture: piece(5, 1), answer: { frac: [1, 10] },
        steps: ['Cut the 1/5 into 2 equal pieces.', 'Give every fifth the same cut. The whole has 5 × 2 = 10 pieces.', 'So 1/5 ÷ 2 = 1/10.'] } },
      { why: 'Still "share the small piece"', problem: { text: 'Find 1/4 ÷ 3.',
        picture: piece(4, 1), answer: { frac: [1, 12] },
        steps: ['Cut the 1/4 into 3 equal pieces.', 'Give every fourth the same cuts. The whole has 4 × 3 = 12 pieces.', 'So 1/4 ÷ 3 = 1/12.'] } },
      { why: 'A little harder', problem: { text: 'Find 1/6 ÷ 3.',
        picture: piece(6, 1), answer: { frac: [1, 18] },
        steps: ['Cut the 1/6 into 3 equal pieces.', 'Give every sixth the same cuts. The whole has 6 × 3 = 18 pieces.', 'So 1/6 ÷ 3 = 1/18.'] } },
      { why: 'Same math in a story', problem: { text: '1/2 gallon of juice is poured equally into 5 cups. What part of a gallon is in each cup?',
        picture: piece(2, 1), answer: { frac: [1, 10] },
        steps: ['Cut the 1/2 gallon into 5 equal parts, one for each cup.', 'Give the other half the same cuts. The whole gallon has 2 × 5 = 10 parts.', 'So each cup has 1/10 of a gallon.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m3-t8', title: 'Fraction times-and-share stories', skill: 'Choose fraction multiplication or division to solve a story',
    bigIdea: 'Draw the story, then ask: are you taking part of an amount, or counting how many pieces fit?',
    screens: [
      { scene: 'g5m3-t8', title: 'A walk on the trail', text: 'A trail is 4 miles long. You walk 3/4 of it before lunch. How far do you walk before lunch?',
        pictures: [tape(4, '4 miles', 0, '1 mile')] },
      { title: 'Same numbers, two questions', text: 'Two stories can use the same 4 miles. One takes part of it. One counts pieces along it. So times or divide? The words tell you.',
        beats: [
          { say: 'Two stories can use the same 4 miles.', pic: 0 },
          { say: 'One takes part of it. One counts pieces along it.' },
          { say: 'So times or divide? The words tell you.' },
        ],
        pictures: [tape(4, '4 miles', 0, '1 mile')] },
      { title: 'The big idea', text: 'Draw the story, then ask: are you taking part of an amount, or counting how many pieces fit?',
        beats: [
          { say: 'Draw the story, then ask: are you taking part of an amount, or counting how many pieces fit?', pic: 0 },
        ],
        pictures: [tape(4, '4 miles')] },
      { title: 'Part of an amount', text: "Our story says 3/4 of the trail. That's part of it, so multiply. Cut 4 miles into 4 equal parts, and take 3. 3/4 × 4 = 3 miles.",
        beats: [
          { say: "Our story says 3/4 of the trail. That's part of it, so multiply." },
          { say: 'Cut 4 miles into 4 equal parts, and take 3.', pic: 0 },
          { say: '3/4 × 4 = 3 miles.', pic: 1 },
        ],
        pictures: [tape(4, '4 miles', 3, '1', true), { kind: 'eq', text: '3/4 × 4 = 3' }] },
      { title: 'How many pieces fit', text: "Now a new story: a water stop every 1/2 mile. How many halves fit in 4 miles? Each mile holds 2, so 8. That's 4 ÷ 1/2 = 8 water stops.",
        beats: [
          { say: 'Now a new story: a water stop every 1/2 mile.' },
          { say: 'How many halves fit in 4 miles? Each mile holds 2, so 8.', pic: 0 },
          { say: "That's 4 ÷ 1/2 = 8 water stops.", pic: 1 },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: Array.from({ length: 8 }, (_, i) => ({ w: 0.5, text: '1/2', shade: i % 2 === 0 })), brace: '4 miles' }], motion: true },
          { kind: 'eq', text: '4 ÷ 1/2 = 8' }] },
      { title: 'Check the size', text: 'Check the size. Part of 4 miles must be less than 4, and 3 is. Counting half miles gives more than 4, and 8 is.',
        beats: [
          { say: 'Check the size.', pic: 0 },
          { say: 'Part of 4 miles must be less than 4, and 3 is.' },
          { say: 'Counting half miles gives more than 4, and 8 is.' },
        ],
        pictures: [{ kind: 'tape', rows: [
          { label: 'Walked', cells: [{ w: 3, text: '3', shade: true }, { w: 1 }] },
          { label: 'Stops', cells: Array.from({ length: 8 }, (_, i) => ({ w: 0.5, shade: i % 2 === 0 })) },
        ] }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't pick times or divide from the NUMBERS. A stop every 1/2 mile is not 1/2 × 4. It's 4 ÷ 1/2 = 8. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't pick times or divide from the NUMBERS.", pic: 0 },
          { say: "A stop every 1/2 mile is not 1/2 × 4. It's 4 ÷ 1/2 = 8." },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: 'a stop every 1/2 mile in 4 miles: 1/2 × 4 = 2', right: 'a stop every 1/2 mile in 4 miles: 4 ÷ 1/2 = 8' }] },
    ],
    turn: {
      text: 'A rope is 6 feet long. You cut it into pieces that are each 1/3 foot long. How many pieces do you get?',
      picture: tape(6, '6 feet'),
      answer: 18,
      steps: ['The story counts how many 1/3-foot pieces fit, so divide: 6 ÷ 1/3.', 'Each foot holds 3 thirds, so 6 feet hold 6 × 3.', 'So you get 18 pieces.'],
      prompt: 'Read what the story asks. Part of the rope, or how many pieces fit?',
      hint1: 'Is the story taking part of the rope, or counting pieces that fit?',
      hint2: 'How many 1/3-foot pieces fit in 1 foot? Now do that for every foot.',
      twin: { text: 'A rope is 6 feet long. You use 2/3 of it to tie up a tent. How many feet of rope do you use?',
        picture: tape(3, '6 feet'),
        answer: 4,
        steps: ['The story takes part of the rope, so find 2/3 of 6.', 'Cut 6 into 3 equal parts: 6 ÷ 3 = 2. Take 2 parts: 2 × 2.', 'So you use 4 feet of rope.'],
        hint1: 'Is the story taking part of the rope, or counting pieces that fit?',
        hint2: 'Cut the 6 feet into 3 equal parts. How many parts do you take?' },
    },
    won: { text: 'You saw the story was counting pieces, so you divided.', sticker: 'Multiplication and division are inverse operations: each one undoes the other.' },
    twinWon: { text: 'You saw the story took 2/3 of 6 feet, and found 4 feet.', sticker: '"Of" in a story means multiply. "How many fit" means divide.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A board is 5 feet long. You cut it into pieces that are each 1/2 foot long. How many pieces do you get?',
        picture: tape(5, '5 feet'), answer: 10,
        steps: ['The story counts pieces that fit, so divide: 5 ÷ 1/2.', 'Each foot holds 2 halves, so 5 feet hold 5 × 2.', 'So you get 10 pieces.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A class has 24 students. 3/8 of them bring lunch from home. How many students bring lunch?',
        picture: tape(8, '24 students'), answer: 9,
        steps: ['The story takes part of 24, so find 3/8 of 24.', '24 ÷ 8 = 3, so each part is 3. Take 3 parts: 3 × 3.', 'So 9 students bring lunch.'] } },
      { why: 'Still "read what the story asks"', problem: { text: '1/2 pound of cheese is shared equally by 4 kids. How many pounds does each kid get?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1, text: '1/2 lb', shade: true }, { w: 1 }], brace: '1 pound' }] }, answer: { frac: [1, 8] },
        steps: ['The story shares a piece, so divide: 1/2 ÷ 4.', 'Cut the half into 4 pieces and give the other half the same cuts: 2 × 4 = 8 pieces in the pound.', 'So each kid gets 1/8 pound.'] } },
      { why: 'A little harder', problem: { text: 'A bag has 12 cups of flour. You use 3/4 of it. You scoop the rest into 1/3-cup scoops. How many scoops do you get?',
        picture: tape(4, '12 cups'), answer: 9,
        steps: ['3/4 of 12: 12 ÷ 4 = 3, and 3 × 3 = 9 cups are used.', 'That leaves 12 − 9 = 3 cups.', 'Each cup holds 3 scoops of 1/3 cup, so 3 cups hold 3 × 3 scoops.', 'So you get 9 scoops.'] } },
      { why: 'Same math in a story', problem: { text: 'A farmer has 1/3 acre of land. She splits it into 2 equal gardens. What part of an acre is each garden?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 1, text: '1/3', shade: true }, { w: 1 }, { w: 1 }], brace: '1 acre' }] }, answer: { frac: [1, 6] },
        steps: ['The story shares a piece, so divide: 1/3 ÷ 2.', 'Cut the 1/3 into 2 pieces and give every third the same cut: 3 × 2 = 6 pieces in the acre.', 'So each garden is 1/6 acre.'] } },
    ],
  },
]

attachChalk(G5M3, G5M3_CHALK)
