/**
 * Grade 5 · Module 4 — Place value for decimal operations.
 * Written to docs/new-flow/AUTHORING.md. Continues Grade 4 · Module 6 (tenths and hundredths).
 * Teaching pictures: `table` (t1, t2, t7, t9), `numline` (t3), `columns` (t4, t5), `area` (t6), `tape` (t8).
 */
import type { Lesson, Picture } from '../script'

const SIGNS = ['<', '>', '=']

/** Place-value chart, ones to thousandths. */
const PV4 = ['Ones', 'Tenths', 'Hundredths', 'Thousandths']
const pv = (rows: string[][], mark?: [number, number][], motion = false): Picture => ({ kind: 'table', head: PV4, rows, mark, motion })
const pvBlank = pv([['?', '?', '?', '?']])

/** Two numbers lined up in the chart, each row headed by the number itself. */
const cmp = (rows: string[][], mark?: [number, number][], motion = false): Picture =>
  ({ kind: 'table', head: ['', ...PV4], rows, rowHead: true, mark, motion })

/** A question number line between two neighbours, with no labels (the ends would name the answer). */
const rline = (min: number, max: number, at: number): Picture => ({ kind: 'numline', min, max, ticks: 10, labels: 'none', points: [{ at }] })

const add = (rows: string[]): Picture => ({ kind: 'columns', rows, op: '+', answer: null })
const sub = (rows: string[]): Picture => ({ kind: 'columns', rows, op: '−', answer: null })

/** Area model: one whole-number row times the parts of a decimal, cells empty. */
const parts = (by: string, cols: string[]): Picture => ({ kind: 'area', cols, rows: [by], cells: [cols.map(() => null)] })

/** Place chart, hundreds to hundredths. */
const PV5 = ['Hundreds', 'Tens', 'Ones', 'Tenths', 'Hundredths']
const shift = (rows: string[][], mark?: [number, number][], motion = false): Picture => ({ kind: 'table', head: PV5, rows, mark, motion })

/** A tape cut into `n` equal unknown pieces, with the total over it. */
const share = (n: number, total: string, text = '?', motion = false): Picture =>
  ({ kind: 'tape', rows: [{ cells: Array.from({ length: n }, () => ({ w: 1, text })), brace: total }], motion })

const units = (a: string, b: string, rows: string[][], mark?: [number, number][], motion = false): Picture =>
  ({ kind: 'table', head: [a, b], rows, mark, motion })

export const G5M4: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m4-t1', title: 'Thousandths', skill: 'Read and write thousandths, and name the value of a digit',
    bigIdea: 'The third place after the point is thousandths. So 47 thousandths is 0.047.',
    screens: [
      { scene: 'g5m4-t1', title: 'A tiny seed', text: 'A seed is so light it weighs 47 thousandths of a gram. How do you write that with a point?',
        pictures: [{ kind: 'eq', text: '47 thousandths of a gram' }] },
      { title: 'Hundredths are too big', text: 'You already know tenths and hundredths. But look at this seed. Even one hundredth of a gram is too heavy for it. We need to cut the pieces smaller still.',
        beats: [
          { say: 'You already know tenths and hundredths.', pic: 0 },
          { say: 'But look at this seed. Even one hundredth of a gram is too heavy for it.' },
          { say: 'We need to cut the pieces smaller still.', write: 'we need a smaller place' },
        ],
        pictures: [{ kind: 'table', head: ['Ones', 'Tenths', 'Hundredths'], rows: [['0', '?', '?']] }] },
      { title: 'The big idea', text: 'The third place after the point is thousandths. So 47 thousandths is 0.047.',
        beats: [
          { say: 'The third place after the point is thousandths.', pic: 0 },
          { say: 'So 47 thousandths is 0.047.' },
        ],
        pictures: [pv([['0', '0', '4', '7']])] },
      { title: 'Cut it smaller', text: 'Take one hundredth and cut it into 10 equal pieces. Each little piece is one thousandth, and we write it 0.001. It takes 1,000 of those to make one whole.',
        beats: [
          { say: 'Take one hundredth and cut it into 10 equal pieces.', pic: 0, write: 'cut a place into 10 → the next place' },
          { say: 'Each little piece is one thousandth, and we write it 0.001.', pic: 1 },
          { say: 'It takes 1,000 of those to make one whole.' },
        ],
        pictures: [pv([['0', '0', '0', '1']], [[0, 3]], true), { kind: 'eq', text: '1 thousandth = 0.001' }] },
      { title: 'Fill the places', text: "Now let's build 47 thousandths. That is 4 hundredths and 7 thousandths. There are no ones and no tenths, so we put a 0 in each of those places.",
        beats: [
          { say: "Now let's build 47 thousandths. That is 4 hundredths and 7 thousandths.", pic: 0 },
          { say: 'There are no ones and no tenths, so we put a 0 in each of those places.', write: 'empty place → write 0' },
        ],
        pictures: [pv([['0', '0', '4', '7']], [[0, 2], [0, 3]], true)] },
      { title: 'Write it with a point', text: 'Now read the chart straight across, left to right. It says 0, point, 0, 4, 7. So the seed weighs 0.047 grams.',
        beats: [
          { say: 'Now read the chart straight across, left to right.', pic: 0 },
          { say: 'It says 0, point, 0, 4, 7.' },
          { say: 'So the seed weighs 0.047 grams.', pic: 1 },
        ],
        pictures: [pv([['0', '0', '4', '7']]), { kind: 'eq', text: '47 thousandths = 0.047' }] },
      { title: 'One thing not to do', text: "Here is the slip to watch for. Don't write 0.47. That is 47 hundredths, and it is ten times heavier. Thousandths need three places after the point.",
        beats: [
          { say: 'Here is the slip to watch for.' },
          { say: "Don't write 0.47. That is 47 hundredths, and it is ten times heavier.", pic: 0 },
          { say: 'Thousandths need three places after the point.', write: 'thousandths → 3 places' },
        ],
        pictures: [{ kind: 'cards', wrong: '47 thousandths = 0.47', right: '47 thousandths = 0.047' }] },
    ],
    turn: {
      text: 'Write 36 thousandths with a point.',
      picture: pvBlank,
      answer: 0.036, steps: ['36 thousandths is 3 hundredths and 6 thousandths.', 'There are no ones and no tenths, so those places are 0.', 'So 36 thousandths is 0.036.'],
      prompt: 'Thousandths go in the third place after the point.',
      hint1: 'How many places after the point do thousandths need?',
      hint2: 'Thousandths take three places after the point. Put a 0 in any empty place.',
      twin: { text: 'Write 52 thousandths with a point.',
        picture: pvBlank,
        answer: 0.052, steps: ['52 thousandths is 5 hundredths and 2 thousandths.', 'There are no ones and no tenths, so those places are 0.', 'So 52 thousandths is 0.052.'],
        hint1: 'Which place after the point is the thousandths place?',
        hint2: 'Use three places after the point. Fill the tenths place with a 0.' },
    },
    won: { text: 'You put thousandths in the third place after the point.', sticker: 'The third place after the point is the thousandths place.' },
    twinWon: { text: 'You wrote 52 thousandths as 0.052.', sticker: 'The third place after the point is the thousandths place.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Write 29 thousandths with a point.',
        picture: pvBlank, answer: 0.029,
        steps: ['29 thousandths is 2 hundredths and 9 thousandths.', 'The ones and tenths are 0.', 'So 29 thousandths is 0.029.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Write 3 and 145 thousandths with a point.',
        picture: pvBlank, answer: 3.145,
        steps: ['The 3 wholes go before the point.', '145 thousandths is 1 tenth, 4 hundredths and 5 thousandths.', 'So it is 3.145.'] } },
      { why: 'Still "three places for thousandths"', problem: { text: 'Write 8 thousandths with a point.',
        picture: pvBlank, answer: 0.008,
        steps: ['8 thousandths has no tenths and no hundredths.', 'Put 0 in the first two places after the point and 8 in the third.', 'So 8 thousandths is 0.008.'] } },
      { why: 'A little harder', problem: { text: 'In 4.629, what is the value of the 9?',
        picture: pv([['4', '6', '2', '9']]), answer: 0.009,
        steps: ['The 9 is in the third place after the point.', 'The third place is thousandths, so the 9 means 9 thousandths.', 'So the 9 is worth 0.009.'] } },
      { why: 'Same math in a story', problem: { text: 'A raindrop weighs 64 thousandths of a gram. Write its weight with a point.',
        picture: { kind: 'eq', text: '64 thousandths of a gram' }, answer: 0.064,
        steps: ['64 thousandths is 6 hundredths and 4 thousandths.', 'The ones and tenths are 0.', 'So the raindrop weighs 0.064 grams.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m4-t2', title: 'Compare decimals to thousandths', skill: 'Compare two decimals to thousandths with <, > or =',
    bigIdea: 'Line up the places and compare from the left. The first place that is different decides.',
    screens: [
      { scene: 'g5m4-t2', title: 'A snail race', text: 'Two snails race. One crawls 0.4 meters. The other crawls 0.389 meters. Which one crawls farther?',
        pictures: [cmp([['0.4', '0', '4', '', ''], ['0.389', '0', '3', '8', '9']])] },
      { title: 'Longer is not bigger', text: 'Look at 0.389. It has more digits, and 389 is way more than 4. So it looks like the bigger one. But careful: the digits after the point are not whole numbers.',
        beats: [
          { say: 'Look at 0.389. It has more digits, and 389 is way more than 4.', pic: 0 },
          { say: 'So it looks like the bigger one.' },
          { say: 'But careful: the digits after the point are not whole numbers.', write: 'more digits ≠ bigger' },
        ],
        pictures: [{ kind: 'eq', text: '0.4 ? 0.389' }] },
      { title: 'The big idea', text: 'Line up the places and compare from the left. The first place that is different decides.',
        beats: [
          { say: 'Line up the places and compare from the left.', pic: 0 },
          { say: 'The first place that is different decides.' },
        ],
        pictures: [cmp([['0.4', '0', '4', '0', '0'], ['0.389', '0', '3', '8', '9']])] },
      { title: 'Line up the places', text: 'Put both numbers into the chart, one place right under the other. 0.4 has nothing in the hundredths or thousandths, so fill those with zeros. Written that way, 0.4 is 0.400.',
        beats: [
          { say: 'Put both numbers into the chart, one place right under the other.', pic: 0 },
          { say: '0.4 has nothing in the hundredths or thousandths, so fill those with zeros.', write: 'empty place → write 0' },
          { say: 'Written that way, 0.4 is 0.400.' },
        ],
        pictures: [cmp([['0.4', '0', '4', '0', '0'], ['0.389', '0', '3', '8', '9']], [[0, 3], [0, 4]], true)] },
      { title: 'Go from the left', text: 'Now start at the left and walk across. The ones match: 0 and 0. Keep going. The tenths are 4 and 3, and those are different. That is the place that decides.',
        beats: [
          { say: 'Now start at the left and walk across.', pic: 0 },
          { say: 'The ones match: 0 and 0. Keep going.' },
          { say: 'The tenths are 4 and 3, and those are different. That is the place that decides.', write: 'first different place wins' },
        ],
        pictures: [cmp([['0.4', '0', '4', '0', '0'], ['0.389', '0', '3', '8', '9']], [[0, 2], [1, 2]], true)] },
      { title: 'Say it with a sign', text: '4 tenths is more than 3 tenths. So 0.4 is the bigger number, and we write 0.4 > 0.389. The first snail crawls farther.',
        beats: [
          { say: '4 tenths is more than 3 tenths.' },
          { say: 'So 0.4 is the bigger number, and we write 0.4 > 0.389.', pic: 0 },
          { say: 'The first snail crawls farther.' },
        ],
        pictures: [{ kind: 'eq', text: '0.4 > 0.389' }] },
      { title: 'One thing not to do', text: "Here is the trap. Don't pick the number just because it has more digits. Line up the places, and look at the tenths first.",
        beats: [
          { say: 'Here is the trap.' },
          { say: "Don't pick the number just because it has more digits.", pic: 0 },
          { say: 'Line up the places, and look at the tenths first.', write: 'compare place by place' },
        ],
        pictures: [{ kind: 'cards', wrong: '0.389 > 0.4', right: '0.4 > 0.389' }] },
    ],
    turn: {
      text: 'Which sign goes between them? 0.7 ? 0.698',
      picture: { kind: 'eq', text: '0.7 ? 0.698' },
      answer: { choices: SIGNS, correct: 1 }, steps: ['Line them up: 0.700 and 0.698.', 'The ones match. The tenths are 7 and 6, and 7 is more.', 'So 0.7 > 0.698, and the sign is >.'],
      prompt: 'Line up the places. Find the first place that is different.',
      hint1: 'Write 0.7 with three places after the point.',
      hint2: 'The ones are the same. Now compare the tenths.',
      twin: { text: 'Which sign goes between them? 0.352 ? 0.36',
        picture: { kind: 'eq', text: '0.352 ? 0.36' },
        answer: { choices: SIGNS, correct: 0 }, steps: ['Line them up: 0.352 and 0.360.', 'The ones and tenths match. The hundredths are 5 and 6, and 5 is less.', 'So 0.352 < 0.36, and the sign is <.'],
        hint1: 'Put a 0 at the end of 0.36 so both have three places.',
        hint2: 'The tenths are the same. Check the hundredths next.' },
    },
    won: { text: 'You lined up the places and found the first one that is different.', sticker: 'The places after the point are decimal places. Compare them from the left.' },
    twinWon: { text: 'You saw that 0.352 < 0.36 by checking the hundredths.', sticker: 'The places after the point are decimal places. Compare them from the left.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which sign goes between them? 0.5 ? 0.487',
        picture: { kind: 'eq', text: '0.5 ? 0.487' }, answer: { choices: SIGNS, correct: 1 },
        steps: ['Line them up: 0.500 and 0.487.', 'The tenths are 5 and 4, and 5 is more.', 'So 0.5 > 0.487, and the sign is >.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Which sign goes between them? 0.214 ? 0.241',
        picture: { kind: 'eq', text: '0.214 ? 0.241' }, answer: { choices: SIGNS, correct: 0 },
        steps: ['The tenths are both 2.', 'The hundredths are 1 and 4, and 1 is less.', 'So 0.214 < 0.241, and the sign is <.'] } },
      { why: 'Still "the first different place decides"', problem: { text: 'Which sign goes between them? 0.60 ? 0.600',
        picture: { kind: 'eq', text: '0.60 ? 0.600' }, answer: { choices: SIGNS, correct: 2 },
        steps: ['Line them up: 0.600 and 0.600.', 'Every place is the same, so no place decides.', 'They are equal, so the sign is =.'] } },
      { why: 'A little harder', problem: { text: 'Which sign goes between them? 2.089 ? 2.1',
        picture: { kind: 'eq', text: '2.089 ? 2.1' }, answer: { choices: SIGNS, correct: 0 },
        steps: ['Line them up: 2.089 and 2.100. The ones are both 2.', 'The tenths are 0 and 1, and 0 is less.', 'So 2.089 < 2.1, and the sign is <.'] } },
      { why: 'Same math in a story', problem: { text: "Mia's pencil is 0.145 meters long. Leo's pencil is 0.15 meters long. Whose pencil is longer?",
        picture: { kind: 'eq', text: '0.145 ? 0.15' }, answer: { choices: ['Mia', 'Leo', 'Same length'], correct: 1 },
        steps: ['Line them up: 0.145 and 0.150.', 'The tenths match. The hundredths are 4 and 5, and 5 is more.', "So 0.15 > 0.145, and Leo's pencil is longer."] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m4-t3', title: 'Round decimals', skill: 'Round a decimal to the nearest whole, tenth or hundredth',
    bigIdea: 'Find the two numbers it sits between, then pick the closer one. Halfway or past it rounds up.',
    screens: [
      { scene: 'g5m4-t3', title: 'How long is the ribbon?', text: 'A ribbon is 3.27 meters long. The shop only writes tenths of a meter on the tag. What should the tag say?',
        pictures: [{ kind: 'numline', min: 3.2, max: 3.3, ticks: 10, labels: 'ends', points: [{ at: 3.27 }] }] },
      { title: 'Too many places', text: 'A tenth is one place after the point. But 3.27 has two places, so it does not fit on the tag. We need a number with just one place. Is it 3.2, or is it 3.3?',
        beats: [
          { say: 'A tenth is one place after the point.', pic: 0, effect: 'draw' },
          { say: 'But 3.27 has two places, so it does not fit on the tag.', write: 'tenths → 1 place after the point' },
          { say: 'We need a number with just one place. Is it 3.2, or is it 3.3?' },
        ],
        pictures: [{ kind: 'numline', min: 3.2, max: 3.3, ticks: 10, labels: 'ends', points: [{ at: 3.27 }] }] },
      { title: 'The big idea', text: 'Find the two numbers it sits between, then pick the closer one. Halfway or past it rounds up.',
        beats: [
          { say: 'Find the two numbers it sits between, then pick the closer one.', pic: 0, effect: 'draw' },
          { say: 'Halfway or past it rounds up.' },
        ],
        pictures: [{ kind: 'numline', min: 3.2, max: 3.3, ticks: 10, labels: 'ends', points: [{ at: 3.27 }] }] },
      { title: 'Find halfway', text: '3.27 sits somewhere between 3.2 and 3.3. Let me mark the middle. Halfway between them is 3.25.',
        beats: [
          { say: '3.27 sits somewhere between 3.2 and 3.3.', pic: 0, effect: 'draw' },
          { say: 'Let me mark the middle.', write: 'halfway decides' },
          { say: 'Halfway between them is 3.25.' },
        ],
        pictures: [{ kind: 'numline', min: 3.2, max: 3.3, ticks: 10, labels: ['3.2', null, null, null, null, '3.25', null, null, null, null, '3.3'],
          points: [{ at: 3.25, label: 'halfway' }, { at: 3.27 }], motion: true }] },
      { title: 'Which is closer?', text: 'Now look where 3.27 landed. It is past halfway. From 3.27 up to 3.3 is only 3 hundredths, but back down to 3.2 is 7 hundredths.',
        beats: [
          { say: 'Now look where 3.27 landed. It is past halfway.', pic: 0, effect: 'draw' },
          { say: 'From 3.27 up to 3.3 is only 3 hundredths, but back down to 3.2 is 7 hundredths.', write: 'past halfway → round up' },
        ],
        pictures: [{ kind: 'numline', min: 3.2, max: 3.3, ticks: 10, labels: 'ends', points: [{ at: 3.27 }],
          jumps: [{ from: 3.27, to: 3.3, label: '0.03' }], motion: true }] },
      { title: 'Round it', text: '3.3 is the closer one, so 3.27 rounds up to 3.3. The tag says 3.3 meters.',
        beats: [
          { say: '3.3 is the closer one, so 3.27 rounds up to 3.3.', pic: 0, effect: 'draw' },
          { say: 'The tag says 3.3 meters.', pic: 1 },
        ],
        pictures: [{ kind: 'numline', min: 3.2, max: 3.3, ticks: 10, labels: 'ends', points: [{ at: 3.27, label: '3.27' }] }, { kind: 'eq', text: '3.27 → 3.3' }] },
      { title: 'One thing not to do', text: "Here is what I don't want you to do. Don't just chop off the last digit. 3.27 is closer to 3.3, not 3.2.",
        beats: [
          { say: "Here is what I don't want you to do." },
          { say: "Don't just chop off the last digit.", pic: 0 },
          { say: '3.27 is closer to 3.3, not 3.2.', write: 'check halfway, then pick' },
        ],
        pictures: [{ kind: 'cards', wrong: '3.27 → 3.2', right: '3.27 → 3.3' }] },
    ],
    turn: {
      text: 'Round 5.64 to the nearest tenth.',
      picture: rline(5.6, 5.7, 5.64),
      answer: 5.6, steps: ['5.64 sits between 5.6 and 5.7. Halfway is 5.65.', '5.64 is just before halfway, so it is closer to the lower one.', 'So 5.64 rounds to 5.6.'],
      prompt: 'Find the two tenths it sits between. Pick the closer one.',
      hint1: 'Which two tenths does 5.64 sit between?',
      hint2: 'Halfway between them is 5.65. Is 5.64 before or past halfway?',
      twin: { text: 'Round 2.386 to the nearest hundredth.',
        picture: rline(2.38, 2.39, 2.386),
        answer: 2.39, steps: ['2.386 sits between 2.38 and 2.39. Halfway is 2.385.', '2.386 is past halfway, so it rounds up.', 'So 2.386 rounds to 2.39.'],
        hint1: 'Nearest hundredth means two places after the point. Which two hundredths is it between?',
        hint2: 'Find halfway between the two hundredths. Is 2.386 before or past it?' },
    },
    won: { text: 'You found the two tenths and picked the closer one.', sticker: 'Rounding finds the closest simpler number. Halfway or past it rounds up.' },
    twinWon: { text: 'You rounded 2.386 up to 2.39.', sticker: 'Rounding finds the closest simpler number. Halfway or past it rounds up.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Round 4.82 to the nearest tenth.',
        picture: rline(4.8, 4.9, 4.82), answer: 4.8,
        steps: ['4.82 sits between 4.8 and 4.9. Halfway is 4.85.', '4.82 is before halfway, so it rounds down.', 'So 4.82 rounds to 4.8.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Round 7.36 to the nearest tenth.',
        picture: rline(7.3, 7.4, 7.36), answer: 7.4,
        steps: ['7.36 sits between 7.3 and 7.4. Halfway is 7.35.', '7.36 is past halfway, so it rounds up.', 'So 7.36 rounds to 7.4.'] } },
      { why: 'Still "halfway rounds up"', problem: { text: 'Round 1.45 to the nearest tenth.',
        picture: rline(1.4, 1.5, 1.45), answer: 1.5,
        steps: ['1.45 sits between 1.4 and 1.5. Halfway is 1.45.', '1.45 is exactly halfway, and halfway rounds up.', 'So 1.45 rounds to 1.5.'] } },
      { why: 'A little harder', problem: { text: 'Round 6.718 to the nearest whole number.',
        picture: rline(6, 7, 6.718), answer: 7,
        steps: ['6.718 sits between 6 and 7. Halfway is 6.5.', '6.718 is past halfway, so it rounds up.', 'So 6.718 rounds to 7.'] } },
      { why: 'Same math in a story', problem: { text: 'A puppy weighs 3.462 kilograms. What is its weight to the nearest hundredth of a kilogram?',
        picture: rline(3.46, 3.47, 3.462), answer: 3.46,
        steps: ['3.462 sits between 3.46 and 3.47. Halfway is 3.465.', '3.462 is before halfway, so it rounds down.', 'So the puppy weighs about 3.46 kilograms.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m4-t4', title: 'Add decimals (line up the point)', skill: 'Add decimals to hundredths and thousandths by lining up the points',
    bigIdea: 'Line up the points, so each place sits under the same place. Then add like whole numbers and bring the point straight down.',
    screens: [
      { scene: 'g5m4-t4', title: 'Two bags of apples', text: 'One bag of apples weighs 12.45 pounds. Another bag weighs 3.7 pounds. How much do they weigh together?',
        pictures: [{ kind: 'eq', text: '12.45 + 3.7' }] },
      { title: 'The last digits trick you', text: 'Watch what happens if you line up the last digits. The 7 tenths ends up sitting under the 5 hundredths. Now two different places are being added together, and the answer will be way off.',
        beats: [
          { say: 'Watch what happens if you line up the last digits.', pic: 0, effect: 'draw' },
          { say: 'The 7 tenths ends up sitting under the 5 hundredths.' },
          { say: 'Now two different places are being added together, and the answer will be way off.', write: 'tenths must sit over tenths' },
        ],
        pictures: [{ kind: 'columns', rows: ['12.45', '3.7'], op: '+' }] },
      { title: 'The big idea', text: 'Line up the points, so each place sits under the same place. Then add like whole numbers and bring the point straight down.',
        beats: [
          { say: 'Line up the points, so each place sits under the same place.', pic: 0, effect: 'draw' },
          { say: 'Then add like whole numbers and bring the point straight down.' },
        ],
        pictures: [{ kind: 'columns', rows: ['12.45', ' 3.70'], op: '+' }] },
      { title: 'Line up the points', text: "So let's put the points one straight under the other. 3.7 has nothing in the hundredths place, so write it as 3.70. Now both numbers have the same places.",
        beats: [
          { say: "So let's put the points one straight under the other.", pic: 0, effect: 'draw' },
          { say: '3.7 has nothing in the hundredths place, so write it as 3.70.', write: 'empty place → write 0' },
          { say: 'Now both numbers have the same places.' },
        ],
        pictures: [{ kind: 'columns', rows: ['12.45', ' 3.70'], op: '+', motion: true }] },
      { title: 'Add from the right', text: 'Now add, starting from the right. Hundredths: 5 + 0 = 5. Tenths: 4 + 7 = 11, so write the 1 and carry the other 1. Ones: 2 + 3 and the carried 1 makes 6. And the tens: 1.',
        beats: [
          { say: 'Now add, starting from the right.', pic: 0, effect: 'draw', write: 'add from the right' },
          { say: 'Hundredths: 5 + 0 = 5. Tenths: 4 + 7 = 11, so write the 1 and carry the other 1.' },
          { say: 'Ones: 2 + 3 and the carried 1 makes 6. And the tens: 1.' },
        ],
        pictures: [{ kind: 'columns', rows: ['12.45', ' 3.70'], op: '+', carry: '1   ', answer: '16.15', motion: true }] },
      { title: 'Bring the point down', text: 'One last thing, and it is the one people forget. The point in the answer goes straight down under the other points. So the two bags weigh 16.15 pounds.',
        beats: [
          { say: 'One last thing, and it is the one people forget.' },
          { say: 'The point in the answer goes straight down under the other points.', pic: 0, effect: 'draw', write: 'point straight down' },
          { say: 'So the two bags weigh 16.15 pounds.', pic: 1 },
        ],
        pictures: [{ kind: 'columns', rows: ['12.45', ' 3.70'], op: '+', carry: '1   ', answer: '16.15' }, { kind: 'eq', text: '12.45 + 3.7 = 16.15' }] },
      { title: 'One thing not to do', text: "Here is the mistake to watch for. Don't line up the last digits. Line up the points, every time.",
        beats: [
          { say: 'Here is the mistake to watch for.' },
          { say: "Don't line up the last digits.", pic: 0 },
          { say: 'Line up the points, every time.', write: 'points over points' },
        ],
        pictures: [{ kind: 'cards', wrong: '12.45 + 3.7 = 12.82', right: '12.45 + 3.7 = 16.15' }] },
    ],
    turn: {
      text: 'Add. 23.56 + 4.8 = ?',
      picture: add(['23.56', ' 4.80']),
      answer: 28.36, steps: ['Line up the points: write 4.8 as 4.80.', 'Add from the right: 6 + 0 = 6. 5 + 8 = 13, so write 3 and carry 1. 3 + 4 + 1 = 8. Then the 2.', 'So 23.56 + 4.8 = 28.36.'],
      prompt: 'Line up the points. Add from the right. Bring the point down.',
      hint1: 'Is the point of 4.8 right under the other point?',
      hint2: 'Write 4.8 as 4.80. Start with the hundredths: 6 + 0.',
      twin: { text: 'Add. 15.3 + 2.64 = ?',
        picture: add(['15.30', ' 2.64']),
        answer: 17.94, steps: ['Write 15.3 as 15.30 so the points line up.', 'Add from the right: 0 + 4 = 4. 3 + 6 = 9. 5 + 2 = 7. Then the 1.', 'So 15.3 + 2.64 = 17.94.'],
        hint1: 'Which number needs a 0 at the end so both have two places after the point?',
        hint2: 'Start with the hundredths: 0 + 4. Then do the tenths.' },
    },
    won: { text: 'You lined up the points, added, and brought the point down.', sticker: 'Lining up the decimal points puts each place value under the same place value.' },
    twinWon: { text: 'You lined up the points and found 17.94.', sticker: 'Lining up the decimal points puts each place value under the same place value.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Add. 34.27 + 5.6 = ?',
        picture: add(['34.27', ' 5.60']), answer: 39.87,
        steps: ['Write 5.6 as 5.60 so the points line up.', '7 + 0 = 7. 2 + 6 = 8. 4 + 5 = 9. Then the 3.', 'So 34.27 + 5.6 = 39.87.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Add. 8.35 + 6.42 = ?',
        picture: add(['8.35', '6.42']), answer: 14.77,
        steps: ['The points already line up.', 'Hundredths: 5 + 2 = 7. Tenths: 3 + 4 = 7. Ones: 8 + 6 = 14.', 'So 8.35 + 6.42 = 14.77.'] } },
      { why: 'Still "line up the points"', problem: { text: 'Add. 7.9 + 2.456 = ?',
        picture: add(['7.900', '2.456']), answer: 10.356,
        steps: ['Write 7.9 as 7.900 so both have three places after the point.', '0 + 6 = 6. 0 + 5 = 5. 9 + 4 = 13, so write 3 and carry 1. 7 + 2 + 1 = 10.', 'So 7.9 + 2.456 = 10.356.'] } },
      { why: 'A little harder', problem: { text: 'Add. 45.68 + 7.57 = ?',
        picture: add(['45.68', ' 7.57']), answer: 53.25,
        steps: ['The points line up.', '8 + 7 = 15, write 5 carry 1. 6 + 5 + 1 = 12, write 2 carry 1. 5 + 7 + 1 = 13, write 3 carry 1. 4 + 1 = 5.', 'So 45.68 + 7.57 = 53.25.'] } },
      { why: 'Same math in a story', problem: { text: 'Sam runs 3.75 kilometers on Monday and 4.6 kilometers on Tuesday. How far does he run in all?',
        picture: add(['3.75', '4.60']), answer: 8.35,
        steps: ['Write 4.6 as 4.60 so the points line up.', '5 + 0 = 5. 7 + 6 = 13, so write 3 and carry 1. 3 + 4 + 1 = 8.', 'So Sam runs 8.35 kilometers.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m4-t5', title: 'Take away decimals', skill: 'Subtract decimals to hundredths by lining up the points',
    bigIdea: 'Line up the points and fill any empty place with a 0. Then take away like whole numbers.',
    screens: [
      { scene: 'g5m4-t5', title: 'Juice left over', text: 'A jug holds 5.2 liters of juice. You pour out 1.35 liters. How much juice is left?',
        pictures: [{ kind: 'eq', text: '5.2 − 1.35' }] },
      { title: 'A place is empty', text: 'Line them up and look at the hundredths. 5.2 has nothing there, but 1.35 has 5 hundredths. It looks like there is nothing to take the 5 away from.',
        beats: [
          { say: 'Line them up and look at the hundredths.', pic: 0, effect: 'draw' },
          { say: '5.2 has nothing there, but 1.35 has 5 hundredths.' },
          { say: 'It looks like there is nothing to take the 5 away from.' },
        ],
        pictures: [{ kind: 'columns', rows: ['5.2 ', '1.35'], op: '−' }] },
      { title: 'The big idea', text: 'Line up the points and fill any empty place with a 0. Then take away like whole numbers.',
        beats: [
          { say: 'Line up the points and fill any empty place with a 0.', pic: 0, effect: 'draw' },
          { say: 'Then take away like whole numbers.' },
        ],
        pictures: [{ kind: 'columns', rows: ['5.20', '1.35'], op: '−' }] },
      { title: 'Fill it with a 0', text: 'Here is the fix. 5.2 is the same amount as 5.20, so write the 0 in. Now every place has a digit in it, and the points still line up.',
        beats: [
          { say: 'Here is the fix.' },
          { say: '5.2 is the same amount as 5.20, so write the 0 in.', pic: 0, effect: 'draw', write: 'empty place → write 0' },
          { say: 'Now every place has a digit in it, and the points still line up.' },
        ],
        pictures: [{ kind: 'columns', rows: ['5.20', '1.35'], op: '−', motion: true }] },
      { title: 'Take away from the right', text: 'Now take away from the right. Hundredths: 0 − 5 will not go, so trade one tenth over and do 10 − 5 = 5. Tenths: now it is 1 − 3, so trade again: 11 − 3 = 8. Ones: 4 − 1 = 3.',
        beats: [
          { say: 'Now take away from the right.', pic: 0, effect: 'draw', write: 'not enough → trade from the left' },
          { say: 'Hundredths: 0 − 5 will not go, so trade one tenth over and do 10 − 5 = 5.' },
          { say: 'Tenths: now it is 1 − 3, so trade again: 11 − 3 = 8. Ones: 4 − 1 = 3.' },
        ],
        pictures: [{ kind: 'columns', rows: ['5.20', '1.35'], op: '−', answer: '3.85', motion: true }] },
      { title: 'Bring the point down', text: 'And the point comes straight down, just like in adding. So there are 3.85 liters of juice left in the jug.',
        beats: [
          { say: 'And the point comes straight down, just like in adding.', pic: 0, effect: 'draw', write: 'point straight down' },
          { say: 'So there are 3.85 liters of juice left in the jug.', pic: 1 },
        ],
        pictures: [{ kind: 'columns', rows: ['5.20', '1.35'], op: '−', answer: '3.85' }, { kind: 'eq', text: '5.2 − 1.35 = 3.85' }] },
      { title: 'One thing not to do', text: "Watch out for this one. When the top place is empty, don't just bring the bottom digit down. Write a 0 up there and trade.",
        beats: [
          { say: 'Watch out for this one.' },
          { say: "When the top place is empty, don't just bring the bottom digit down.", pic: 0 },
          { say: 'Write a 0 up there and trade.', write: 'fill with 0, then trade' },
        ],
        pictures: [{ kind: 'cards', wrong: '5.2 − 1.35 = 3.95', right: '5.2 − 1.35 = 3.85' }] },
    ],
    turn: {
      text: 'Take away. 6.4 − 2.75 = ?',
      picture: sub(['6.4 ', '2.75']),
      answer: 3.65, steps: ['Write 6.4 as 6.40 so every place has a digit.', 'Hundredths: trade, so 10 − 5 = 5. Tenths: 3 − 7 needs a trade, so 13 − 7 = 6. Ones: 5 − 2 = 3.', 'So 6.4 − 2.75 = 3.65.'],
      prompt: 'Put a 0 in the empty place. Then take away from the right.',
      hint1: 'What goes in the empty hundredths place of 6.4?',
      hint2: 'Write 6.40. Now 0 − 5 needs a trade from the tenths.',
      twin: { text: 'Take away. 9.3 − 4.68 = ?',
        picture: sub(['9.3 ', '4.68']),
        answer: 4.62, steps: ['Write 9.3 as 9.30 so every place has a digit.', 'Hundredths: trade, so 10 − 8 = 2. Tenths: 2 − 6 needs a trade, so 12 − 6 = 6. Ones: 8 − 4 = 4.', 'So 9.3 − 4.68 = 4.62.'],
        hint1: 'Fill the empty place in 9.3 with a 0 first.',
        hint2: 'Start with the hundredths: 0 − 8 needs a trade from the tenths.' },
    },
    won: { text: 'You filled the empty place with a 0, traded, and took away.', sticker: 'Taking away is subtraction. Line up the decimal points before you subtract.' },
    twinWon: { text: 'You filled in a 0 and found 4.62.', sticker: 'Taking away is subtraction. Line up the decimal points before you subtract.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Take away. 7.5 − 3.26 = ?',
        picture: sub(['7.5 ', '3.26']), answer: 4.24,
        steps: ['Write 7.5 as 7.50.', 'Hundredths: trade, so 10 − 6 = 4. Tenths: 4 − 2 = 2. Ones: 7 − 3 = 4.', 'So 7.5 − 3.26 = 4.24.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Take away. 8.64 − 5.31 = ?',
        picture: sub(['8.64', '5.31']), answer: 3.33,
        steps: ['The points line up and no place is empty.', 'Hundredths: 4 − 1 = 3. Tenths: 6 − 3 = 3. Ones: 8 − 5 = 3.', 'So 8.64 − 5.31 = 3.33.'] } },
      { why: 'Still "fill the empty place with 0"', problem: { text: 'Take away. 4 − 1.72 = ?',
        picture: sub(['4   ', '1.72']), answer: 2.28,
        steps: ['4 is the same as 4.00.', 'Hundredths: trade, so 10 − 2 = 8. Tenths: 9 − 7 = 2. Ones: 3 − 1 = 2.', 'So 4 − 1.72 = 2.28.'] } },
      { why: 'A little harder', problem: { text: 'Take away. 15.2 − 7.86 = ?',
        picture: sub(['15.2 ', ' 7.86']), answer: 7.34,
        steps: ['Write 15.2 as 15.20.', 'Hundredths: 10 − 6 = 4. Tenths: 11 − 8 = 3. Ones: 14 − 7 = 7. Each step needed a trade.', 'So 15.2 − 7.86 = 7.34.'] } },
      { why: 'Same math in a story', problem: { text: 'A board is 3.5 meters long. Kai cuts off 1.28 meters. How long is the piece that is left?',
        picture: sub(['3.5 ', '1.28']), answer: 2.22,
        steps: ['Write 3.5 as 3.50.', 'Hundredths: trade, so 10 − 8 = 2. Tenths: 4 − 2 = 2. Ones: 3 − 1 = 2.', 'So the piece left is 2.22 meters.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m4-t6', title: 'Multiply a decimal by a whole number', skill: 'Multiply a decimal to hundredths by a one-digit whole number',
    bigIdea: 'Break the decimal into wholes, tenths and hundredths. Multiply each part, then add.',
    screens: [
      { scene: 'g5m4-t6', title: 'Three smoothies', text: 'One smoothie costs $1.25. You buy 3 smoothies. How much do you pay?',
        pictures: [{ kind: 'eq', text: '3 × $1.25' }] },
      { title: 'Adding again is slow', text: 'You could just add. 1.25 + 1.25 + 1.25. That works fine for 3 smoothies. But for 8 or 9 of them, you would be adding all day.',
        beats: [
          { say: 'You could just add. 1.25 + 1.25 + 1.25.', pic: 0 },
          { say: 'That works fine for 3 smoothies.' },
          { say: 'But for 8 or 9 of them, you would be adding all day.' },
        ],
        pictures: [{ kind: 'eq', text: '1.25 + 1.25 + 1.25' }] },
      { title: 'The big idea', text: 'Break the decimal into wholes, tenths and hundredths. Multiply each part, then add.',
        beats: [
          { say: 'Break the decimal into wholes, tenths and hundredths.', pic: 0, effect: 'draw' },
          { say: 'Multiply each part, then add.' },
        ],
        pictures: [{ kind: 'area', cols: ['1', '0.2', '0.05'], rows: ['3'], widths: [10, 4, 2] }] },
      { title: 'Break 1.25 apart', text: "So let's break 1.25 apart. It is 1 whole, 2 tenths and 5 hundredths. Written out, 1.25 = 1 + 0.2 + 0.05.",
        beats: [
          { say: "So let's break 1.25 apart.", pic: 0, effect: 'draw' },
          { say: 'It is 1 whole, 2 tenths and 5 hundredths.' },
          { say: 'Written out, 1.25 = 1 + 0.2 + 0.05.', pic: 1 },
        ],
        pictures: [{ kind: 'area', cols: ['1', '0.2', '0.05'], rows: ['3'], widths: [10, 4, 2], motion: true }, { kind: 'eq', text: '1.25 = 1 + 0.2 + 0.05' }] },
      { title: 'Multiply each part', text: 'Now take each part and multiply it by 3. 3 × 1 = 3. 3 × 2 tenths is 6 tenths, which is 0.6. And 3 × 5 hundredths is 15 hundredths, which is 0.15.',
        beats: [
          { say: 'Now take each part and multiply it by 3.', pic: 0, effect: 'draw', write: 'multiply every part' },
          { say: '3 × 1 = 3. 3 × 2 tenths is 6 tenths, which is 0.6.' },
          { say: 'And 3 × 5 hundredths is 15 hundredths, which is 0.15.' },
        ],
        pictures: [{ kind: 'area', cols: ['1', '0.2', '0.05'], rows: ['3'], widths: [10, 4, 2], cells: [['3', '0.6', '0.15']], motion: true }] },
      { title: 'Add the parts', text: 'Last step: put the pieces back together. 3 + 0.6 + 0.15 = 3.75. So 3 smoothies cost $3.75.',
        beats: [
          { say: 'Last step: put the pieces back together.', pic: 0, effect: 'draw' },
          { say: '3 + 0.6 + 0.15 = 3.75.', pic: 1 },
          { say: 'So 3 smoothies cost $3.75.' },
        ],
        pictures: [{ kind: 'area', cols: ['1', '0.2', '0.05'], rows: ['3'], widths: [10, 4, 2], cells: [['3', '0.6', '0.15']] },
          { kind: 'eq', text: '3 + 0.6 + 0.15 = 3.75' }] },
      { title: 'One thing not to do', text: 'Here is where the point gets lost. 3 × 125 is 375, and that part is true. But 3 smoothies at about a dollar each cost about $3, not $375. So the answer is 3.75.',
        beats: [
          { say: 'Here is where the point gets lost.' },
          { say: '3 × 125 is 375, and that part is true.', pic: 0 },
          { say: 'But 3 smoothies at about a dollar each cost about $3, not $375. So the answer is 3.75.', write: 'check: is the size sensible?' },
        ],
        pictures: [{ kind: 'cards', wrong: '3 × 1.25 = 375', right: '3 × 1.25 = 3.75' }] },
    ],
    turn: {
      text: 'Multiply. 4 × 1.32 = ?',
      picture: parts('4', ['1', '0.3', '0.02']),
      answer: 5.28, steps: ['1.32 is 1 + 0.3 + 0.02.', '4 × 1 = 4, 4 × 0.3 = 1.2, and 4 × 0.02 = 0.08.', '4 + 1.2 + 0.08 = 5.28, so 4 × 1.32 = 5.28.'],
      prompt: 'Break the decimal into parts. Multiply each part. Then add.',
      hint1: 'Break 1.32 into wholes, tenths and hundredths.',
      hint2: 'Find 4 × 1, 4 × 0.3 and 4 × 0.02. Then add them.',
      twin: { text: 'Multiply. 3 × 2.14 = ?',
        picture: parts('3', ['2', '0.1', '0.04']),
        answer: 6.42, steps: ['2.14 is 2 + 0.1 + 0.04.', '3 × 2 = 6, 3 × 0.1 = 0.3, and 3 × 0.04 = 0.12.', '6 + 0.3 + 0.12 = 6.42, so 3 × 2.14 = 6.42.'],
        hint1: 'Break 2.14 into wholes, tenths and hundredths.',
        hint2: 'Multiply 3 by each part. Then add the three answers.' },
    },
    won: { text: 'You multiplied each part of the decimal, then added.', sticker: 'Multiplying each part and adding is called the distributive property.' },
    twinWon: { text: 'You multiplied each part of 2.14 by 3 and got 6.42.', sticker: 'Multiplying each part and adding is called the distributive property.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Multiply. 2 × 1.34 = ?',
        picture: parts('2', ['1', '0.3', '0.04']), answer: 2.68,
        steps: ['1.34 is 1 + 0.3 + 0.04.', '2 × 1 = 2, 2 × 0.3 = 0.6, and 2 × 0.04 = 0.08.', '2 + 0.6 + 0.08 = 2.68, so 2 × 1.34 = 2.68.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Multiply. 3 × 2.13 = ?',
        picture: parts('3', ['2', '0.1', '0.03']), answer: 6.39,
        steps: ['2.13 is 2 + 0.1 + 0.03.', '3 × 2 = 6, 3 × 0.1 = 0.3, and 3 × 0.03 = 0.09.', '6 + 0.3 + 0.09 = 6.39, so 3 × 2.13 = 6.39.'] } },
      { why: 'Still "multiply each part"', problem: { text: 'Multiply. 5 × 0.17 = ?',
        picture: parts('5', ['0.1', '0.07']), answer: 0.85,
        steps: ['0.17 is 0.1 + 0.07.', '5 × 0.1 = 0.5 and 5 × 0.07 = 0.35.', '0.5 + 0.35 = 0.85, so 5 × 0.17 = 0.85.'] } },
      { why: 'A little harder', problem: { text: 'Multiply. 6 × 3.47 = ?',
        picture: parts('6', ['3', '0.4', '0.07']), answer: 20.82,
        steps: ['3.47 is 3 + 0.4 + 0.07.', '6 × 3 = 18, 6 × 0.4 = 2.4, and 6 × 0.07 = 0.42.', '18 + 2.4 + 0.42 = 20.82, so 6 × 3.47 = 20.82.'] } },
      { why: 'Same math in a story', problem: { text: 'A notebook costs $2.35. How much do 3 notebooks cost?',
        picture: parts('3', ['2', '0.3', '0.05']), answer: 7.05,
        steps: ['2.35 is 2 + 0.3 + 0.05.', '3 × 2 = 6, 3 × 0.3 = 0.9, and 3 × 0.05 = 0.15.', '6 + 0.9 + 0.15 = 7.05, so 3 notebooks cost $7.05.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m4-t7', title: 'Multiply and divide by 10, 100, 1,000', skill: 'Multiply and divide decimals by 10, 100 and 1,000 by moving the digits',
    bigIdea: 'Multiply by 10 and every digit moves one place left. Divide by 10 and every digit moves one place right; 100 is two places and 1,000 is three.',
    screens: [
      { scene: 'g5m4-t7', title: 'A store full of rice', text: 'One bag of rice weighs 2.36 kilograms. A store has 100 bags. How many kilograms is that?',
        pictures: [shift([['', '', '2', '3', '6']])] },
      { title: 'Adding zeros does not work', text: 'With whole numbers, times 100 just puts two zeros on the end. Try that here and you get 2.3600. But 2.3600 is still only 2.36. Zeros after the point change nothing at all.',
        beats: [
          { say: 'With whole numbers, times 100 just puts two zeros on the end.' },
          { say: 'Try that here and you get 2.3600. But 2.3600 is still only 2.36.', pic: 0 },
          { say: 'Zeros after the point change nothing at all.', write: 'zeros on the end → no change' },
        ],
        pictures: [{ kind: 'eq', text: '2.3600 = 2.36' }] },
      { title: 'The big idea', text: 'Multiply by 10 and every digit moves one place left. Divide by 10 and every digit moves one place right; 100 is two places and 1,000 is three.',
        beats: [
          { say: 'Multiply by 10 and every digit moves one place left.', pic: 0 },
          { say: 'Divide by 10 and every digit moves one place right; 100 is two places and 1,000 is three.' },
        ],
        pictures: [shift([['', '', '2', '3', '6']])] },
      { title: 'One place left', text: 'Look at the chart. Every place is worth 10 times the place to its right. So when we multiply by 10, every digit slides one place to the left. That turns 2.36 into 23.6.',
        beats: [
          { say: 'Look at the chart. Every place is worth 10 times the place to its right.', pic: 0 },
          { say: 'So when we multiply by 10, every digit slides one place to the left.', write: '× 10 → one place left' },
          { say: 'That turns 2.36 into 23.6.' },
        ],
        pictures: [shift([['', '', '2', '3', '6'], ['', '2', '3', '6', '']], [[1, 1], [1, 2], [1, 3]], true)] },
      { title: 'Two places left', text: 'Times 100 is just times 10, and then times 10 again. So every digit slides two places left this time. Watch the 2: it goes from the ones all the way to the hundreds.',
        beats: [
          { say: 'Times 100 is just times 10, and then times 10 again.' },
          { say: 'So every digit slides two places left this time.', pic: 0, write: 'count the zeros → count the places' },
          { say: 'Watch the 2: it goes from the ones all the way to the hundreds.' },
        ],
        pictures: [shift([['', '', '2', '3', '6'], ['2', '3', '6', '', '']], [[1, 0], [1, 1], [1, 2]], true)] },
      { title: 'Read the new number', text: 'Now read off the new number. The 2 is in the hundreds, the 3 in the tens and the 6 in the ones. So 2.36 × 100 = 236. And dividing takes you right back: 236 ÷ 100 = 2.36.',
        beats: [
          { say: 'Now read off the new number.' },
          { say: 'The 2 is in the hundreds, the 3 in the tens and the 6 in the ones. So 2.36 × 100 = 236.', pic: 0 },
          { say: 'And dividing takes you right back: 236 ÷ 100 = 2.36.' },
        ],
        pictures: [{ kind: 'eq', text: '2.36 × 100 = 236', lines: ['236 ÷ 100 = 2.36'] }] },
      { title: 'One thing not to do', text: "So here is the one to avoid. Don't just stick zeros on the end. Move every single digit instead.",
        beats: [
          { say: 'So here is the one to avoid.' },
          { say: "Don't just stick zeros on the end.", pic: 0 },
          { say: 'Move every single digit instead.', write: 'move the digits, not the zeros' },
        ],
        pictures: [{ kind: 'cards', wrong: '2.36 × 100 = 2.3600', right: '2.36 × 100 = 236' }] },
    ],
    turn: {
      text: 'Multiply. 4.57 × 100 = ?',
      picture: shift([['', '', '4', '5', '7'], ['?', '?', '?', '', '']]),
      answer: 457, steps: ['Times 100 moves every digit two places to the left.', 'The 4 moves from the ones to the hundreds, the 5 to the tens, and the 7 to the ones.', 'So 4.57 × 100 = 457.'],
      prompt: 'Count the zeros in 100. Move every digit that many places.',
      hint1: 'How many zeros does 100 have? That is how many places to move.',
      hint2: 'Multiplying moves the digits left. Where does the 4 land after two places?',
      twin: { text: 'Divide. 38.2 ÷ 10 = ?',
        picture: shift([['', '3', '8', '2', '']]),
        answer: 3.82, steps: ['Divide by 10 moves every digit one place to the right.', 'The 3 moves from the tens to the ones, the 8 to the tenths, and the 2 to the hundredths.', 'So 38.2 ÷ 10 = 3.82.'],
        hint1: 'When you divide, which way do the digits move?',
        hint2: 'Move every digit one place to the right. Where does the 3 land?' },
    },
    won: { text: 'You moved every digit two places left.', sticker: '10, 100 and 1,000 are powers of ten. Each one moves the digits one more place.' },
    twinWon: { text: 'You moved every digit of 38.2 one place right, to 3.82.', sticker: '10, 100 and 1,000 are powers of ten. Each one moves the digits one more place.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Multiply. 6.14 × 100 = ?',
        picture: shift([['', '', '6', '1', '4']]), answer: 614,
        steps: ['Times 100 moves every digit two places left.', 'The 6 goes to the hundreds, the 1 to the tens, and the 4 to the ones.', 'So 6.14 × 100 = 614.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Multiply. 0.9 × 10 = ?',
        picture: shift([['', '', '0', '9', '']]), answer: 9,
        steps: ['Times 10 moves every digit one place left.', 'The 9 moves from the tenths to the ones.', 'So 0.9 × 10 = 9.'] } },
      { why: 'Still "count the zeros, move the digits"', problem: { text: 'Divide. 52 ÷ 100 = ?',
        picture: shift([['', '5', '2', '', '']]), answer: 0.52,
        steps: ['Divide by 100 moves every digit two places right.', 'The 5 moves from the tens to the tenths, and the 2 from the ones to the hundredths.', 'So 52 ÷ 100 = 0.52.'] } },
      { why: 'A little harder', problem: { text: 'Multiply. 3.7 × 1,000 = ?',
        picture: { kind: 'table', head: ['Thousands', 'Hundreds', 'Tens', 'Ones', 'Tenths'], rows: [['', '', '', '3', '7']] }, answer: 3700,
        steps: ['Times 1,000 moves every digit three places left.', 'The 3 moves from the ones to the thousands, and the 7 from the tenths to the hundreds. The tens and ones get a 0.', 'So 3.7 × 1,000 = 3,700.'] } },
      { why: 'Same math in a story', problem: { text: 'A roll of 10 stickers costs $4.50. Each sticker costs the same. How much does one sticker cost?',
        picture: shift([['', '', '4', '5', '0']]), answer: 0.45,
        steps: ['Find 4.50 ÷ 10. Dividing by 10 moves every digit one place right.', 'The 4 moves from the ones to the tenths, and the 5 to the hundredths.', 'So one sticker costs $0.45.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m4-t8', title: 'Divide a decimal by a whole number', skill: 'Divide a decimal to hundredths by a one-digit whole number',
    bigIdea: 'Count the decimal in tenths. Share the tenths equally, then write the answer with a point again.',
    screens: [
      { scene: 'g5m4-t8', title: 'Share a ribbon', text: 'A ribbon is 7.2 meters long. You cut it into 3 equal pieces. How long is each piece?',
        pictures: [share(3, '7.2 m')] },
      { title: 'It does not share evenly', text: 'Try sharing the 7 whole meters first. 3 pieces of 2 meters is 6, and that leaves 1 meter over. And we still have the 0.2 to deal with.',
        beats: [
          { say: 'Try sharing the 7 whole meters first.', pic: 0, effect: 'draw' },
          { say: '3 pieces of 2 meters is 6, and that leaves 1 meter over.' },
          { say: 'And we still have the 0.2 to deal with.' },
        ],
        pictures: [share(3, '7.2 m')] },
      { title: 'The big idea', text: 'Count the decimal in tenths. Share the tenths equally, then write the answer with a point again.',
        beats: [
          { say: 'Count the decimal in tenths.', pic: 0, effect: 'draw' },
          { say: 'Share the tenths equally, then write the answer with a point again.' },
        ],
        pictures: [share(3, '7.2 m')] },
      { title: 'Count in tenths', text: 'Here is the trick. Every meter is 10 tenths, so 7 meters is 70 tenths. Add the 2 tenths we already had, and the whole ribbon is 72 tenths.',
        beats: [
          { say: 'Here is the trick. Every meter is 10 tenths, so 7 meters is 70 tenths.', pic: 0, effect: 'draw' },
          { say: 'Add the 2 tenths we already had, and the whole ribbon is 72 tenths.', pic: 1, write: 'count in tenths, not wholes' },
        ],
        pictures: [share(3, '72 tenths', '?', true), { kind: 'eq', text: '7.2 = 72 tenths' }] },
      { title: 'Share the tenths', text: 'Now 72 shares into 3 just fine. 72 ÷ 3 = 24, so every piece gets 24 tenths.',
        beats: [
          { say: 'Now 72 shares into 3 just fine.', pic: 0, effect: 'draw' },
          { say: '72 ÷ 3 = 24, so every piece gets 24 tenths.', pic: 1 },
        ],
        pictures: [share(3, '72 tenths', '24 tenths', true), { kind: 'eq', text: '72 ÷ 3 = 24' }] },
      { title: 'Write it with a point', text: 'Do not stop there, though. 24 tenths is 2 wholes and 4 tenths, and that is 2.4. So each piece of ribbon is 2.4 meters long.',
        beats: [
          { say: 'Do not stop there, though.' },
          { say: '24 tenths is 2 wholes and 4 tenths, and that is 2.4.', pic: 0, effect: 'draw', write: 'tenths → put the point back' },
          { say: 'So each piece of ribbon is 2.4 meters long.', pic: 1 },
        ],
        pictures: [share(3, '7.2 m', '2.4 m'), { kind: 'eq', text: '7.2 ÷ 3 = 2.4' }] },
      { title: 'One thing not to do', text: "And that is exactly the slip to watch. Don't stop at 24, because 24 is the count of tenths. Put the point back in and write 2.4.",
        beats: [
          { say: 'And that is exactly the slip to watch.' },
          { say: "Don't stop at 24, because 24 is the count of tenths.", pic: 0 },
          { say: 'Put the point back in and write 2.4.' },
        ],
        pictures: [{ kind: 'cards', wrong: '7.2 ÷ 3 = 24', right: '7.2 ÷ 3 = 2.4' }] },
    ],
    turn: {
      text: 'Divide. 7.5 ÷ 3 = ?',
      picture: share(3, '7.5'),
      answer: 2.5, steps: ['7.5 is 75 tenths.', '75 ÷ 3 = 25, so each part is 25 tenths.', '25 tenths is 2.5, so 7.5 ÷ 3 = 2.5.'],
      prompt: 'Count the decimal in tenths. Share them. Then write it with a point.',
      hint1: 'How many tenths is 7.5?',
      hint2: 'Share 75 tenths into 3 equal parts. Then write the tenths with a point.',
      twin: { text: 'Divide. 9.2 ÷ 4 = ?',
        picture: share(4, '9.2'),
        answer: 2.3, steps: ['9.2 is 92 tenths.', '92 ÷ 4 = 23, so each part is 23 tenths.', '23 tenths is 2.3, so 9.2 ÷ 4 = 2.3.'],
        hint1: 'Count 9.2 in tenths first.',
        hint2: 'Share 92 tenths into 4 equal parts. Then write the tenths with a point.' },
    },
    won: { text: 'You counted in tenths, shared them, and put the point back.', sticker: 'The answer to a division is the quotient. Its point sits right above the point in the number you share.' },
    twinWon: { text: 'You shared 9.2 into 4 equal parts and got 2.3.', sticker: 'The answer to a division is the quotient. Its point sits right above the point in the number you share.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Divide. 8.4 ÷ 3 = ?',
        picture: share(3, '8.4'), answer: 2.8,
        steps: ['8.4 is 84 tenths.', '84 ÷ 3 = 28, so each part is 28 tenths.', '28 tenths is 2.8, so 8.4 ÷ 3 = 2.8.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Divide. 6.5 ÷ 5 = ?',
        picture: share(5, '6.5'), answer: 1.3,
        steps: ['6.5 is 65 tenths.', '65 ÷ 5 = 13, so each part is 13 tenths.', '13 tenths is 1.3, so 6.5 ÷ 5 = 1.3.'] } },
      { why: 'Still "share the tenths"', problem: { text: 'Divide. 3.6 ÷ 4 = ?',
        picture: share(4, '3.6'), answer: 0.9,
        steps: ['3.6 is 36 tenths.', '36 ÷ 4 = 9, so each part is 9 tenths.', '9 tenths is 0.9, so 3.6 ÷ 4 = 0.9.'] } },
      { why: 'A little harder', problem: { text: 'Divide. 8.46 ÷ 3 = ?',
        picture: share(3, '8.46'), answer: 2.82,
        steps: ['8.46 has two places after the point, so count it in hundredths: 846 hundredths.', '846 ÷ 3 = 282, so each part is 282 hundredths.', '282 hundredths is 2.82, so 8.46 ÷ 3 = 2.82.'] } },
      { why: 'Same math in a story', problem: { text: 'Four friends share a 5.2-kilogram bag of oranges equally. How many kilograms does each friend get?',
        picture: share(4, '5.2 kg'), answer: 1.3,
        steps: ['5.2 is 52 tenths.', '52 ÷ 4 = 13, so each friend gets 13 tenths.', '13 tenths is 1.3, so each friend gets 1.3 kilograms.'] } },
    ],
  },

  // ── Topic 9 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m4-t9', title: 'Change metric units', skill: 'Convert km/m, m/cm, kg/g and L/mL by multiplying or dividing by 10, 100 or 1,000',
    bigIdea: 'To change to a smaller unit, multiply, because you need more of them. To change to a bigger unit, divide, because you need fewer.',
    screens: [
      { scene: 'g5m4-t9', title: 'A long trail', text: 'A trail is 2.5 kilometers long. The sign at the start counts in meters. How many meters long is the trail?',
        pictures: [units('Kilometers', 'Meters', [['2.5', '?']])] },
      { title: 'Two sizes of unit', text: 'Think about how different these two units are. A kilometer is much longer than a meter. In fact it takes 1,000 meters to make 1 kilometer. So the same trail is a small number of kilometers, but a big number of meters.',
        beats: [
          { say: 'Think about how different these two units are. A kilometer is much longer than a meter.' },
          { say: 'In fact it takes 1,000 meters to make 1 kilometer.', pic: 0 },
          { say: 'So the same trail is a small number of kilometers, but a big number of meters.', write: 'smaller unit → more of them' },
        ],
        pictures: [{ kind: 'eq', text: '1 kilometer = 1,000 meters' }] },
      { title: 'The big idea', text: 'To change to a smaller unit, multiply, because you need more of them. To change to a bigger unit, divide, because you need fewer.',
        beats: [
          { say: 'To change to a smaller unit, multiply, because you need more of them.', pic: 0 },
          { say: 'To change to a bigger unit, divide, because you need fewer.' },
        ],
        pictures: [{ kind: 'table', head: ['1 of this', 'is the same as'],
          rows: [['1 kilometer', '1,000 meters'], ['1 meter', '100 centimeters'], ['1 kilogram', '1,000 grams'], ['1 liter', '1,000 milliliters']] }] },
      { title: 'Smaller unit, more of them', text: 'We are going from kilometers to meters, and meters are the smaller unit. So there will be more of them, which means we multiply. And 1 kilometer is 1,000 meters, so we multiply by 1,000.',
        beats: [
          { say: 'We are going from kilometers to meters, and meters are the smaller unit.', pic: 0 },
          { say: 'So there will be more of them, which means we multiply.', write: 'smaller unit → multiply' },
          { say: 'And 1 kilometer is 1,000 meters, so we multiply by 1,000.' },
        ],
        pictures: [units('Kilometers', 'Meters', [['1', '1,000'], ['2', '2,000'], ['2.5', '?']], [[2, 0]], true)] },
      { title: 'Move the digits', text: 'You already know how to multiply by 1,000: every digit moves three places left. So 2.5 becomes 2,500.',
        beats: [
          { say: 'You already know how to multiply by 1,000: every digit moves three places left.', pic: 0 },
          { say: 'So 2.5 becomes 2,500.', pic: 1 },
        ],
        pictures: [units('Kilometers', 'Meters', [['1', '1,000'], ['2', '2,000'], ['2.5', '2,500']], [[2, 1]], true), { kind: 'eq', text: '2.5 × 1,000 = 2,500' }] },
      { title: 'Check it makes sense', text: "Before we finish, let's check that the answer is sensible. The trail is 2.5 kilometers, or 2,500 meters. The smaller unit ended up with the bigger number, and that is exactly what we expected.",
        beats: [
          { say: "Before we finish, let's check that the answer is sensible." },
          { say: 'The trail is 2.5 kilometers, or 2,500 meters.', pic: 0 },
          { say: 'The smaller unit ended up with the bigger number, and that is exactly what we expected.', write: 'does the size make sense?' },
        ],
        pictures: [{ kind: 'eq', text: '2.5 km = 2,500 m' }] },
      { title: 'One thing not to do', text: "Here is the one that catches people. Don't divide when you are going to the smaller unit. You would end up with fewer meters than kilometers, and that cannot be right.",
        beats: [
          { say: 'Here is the one that catches people.' },
          { say: "Don't divide when you are going to the smaller unit.", pic: 0 },
          { say: 'You would end up with fewer meters than kilometers, and that cannot be right.' },
        ],
        pictures: [{ kind: 'cards', wrong: '2.5 km = 0.0025 m', right: '2.5 km = 2,500 m' }] },
    ],
    turn: {
      text: 'How many meters is 4.2 kilometers?',
      picture: units('Kilometers', 'Meters', [['1', '1,000'], ['4.2', '?']]),
      answer: 4200, steps: ['Meters are smaller, so there will be more of them. Multiply.', '1 kilometer is 1,000 meters, so find 4.2 × 1,000. Every digit moves three places left.', 'So 4.2 kilometers is 4,200 meters.'],
      prompt: 'Smaller unit: multiply. Bigger unit: divide.',
      hint1: 'Is a meter smaller or bigger than a kilometer? So do you multiply or divide?',
      hint2: '1 kilometer is 1,000 meters. Multiply 4.2 by 1,000.',
      twin: { text: 'How many kilograms is 3,400 grams?',
        picture: units('Grams', 'Kilograms', [['1,000', '1'], ['3,400', '?']]),
        answer: 3.4, steps: ['Kilograms are bigger, so there will be fewer of them. Divide.', '1,000 grams is 1 kilogram, so find 3,400 ÷ 1,000. Every digit moves three places right.', 'So 3,400 grams is 3.4 kilograms.'],
        hint1: 'Is a kilogram bigger or smaller than a gram? So do you multiply or divide?',
        hint2: '1,000 grams make 1 kilogram. Divide 3,400 by 1,000.' },
    },
    won: { text: 'You chose to multiply because meters are smaller than kilometers.', sticker: 'Kilo means a thousand. Changing between units like these is a metric conversion.' },
    twinWon: { text: 'You changed 3,400 grams into 3.4 kilograms.', sticker: 'Kilo means a thousand. Changing between units like these is a metric conversion.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'How many meters is 6.8 kilometers?',
        picture: units('Kilometers', 'Meters', [['1', '1,000'], ['6.8', '?']]), answer: 6800,
        steps: ['Meters are smaller, so multiply.', '1 kilometer is 1,000 meters, so find 6.8 × 1,000.', 'So 6.8 kilometers is 6,800 meters.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'How many centimeters is 3.25 meters?',
        picture: units('Meters', 'Centimeters', [['1', '100'], ['3.25', '?']]), answer: 325,
        steps: ['Centimeters are smaller, so multiply.', '1 meter is 100 centimeters, so find 3.25 × 100. Every digit moves two places left.', 'So 3.25 meters is 325 centimeters.'] } },
      { why: 'Still "smaller unit, multiply"', problem: { text: 'How many milliliters is 1.75 liters?',
        picture: units('Liters', 'Milliliters', [['1', '1,000'], ['1.75', '?']]), answer: 1750,
        steps: ['Milliliters are smaller, so multiply.', '1 liter is 1,000 milliliters, so find 1.75 × 1,000.', 'So 1.75 liters is 1,750 milliliters.'] } },
      { why: 'A little harder', problem: { text: 'How many meters is 485 centimeters?',
        picture: units('Centimeters', 'Meters', [['100', '1'], ['485', '?']]), answer: 4.85,
        steps: ['Meters are bigger, so there will be fewer of them. Divide.', '100 centimeters is 1 meter, so find 485 ÷ 100. Every digit moves two places right.', 'So 485 centimeters is 4.85 meters.'] } },
      { why: 'Same math in a story', problem: { text: 'A water bottle holds 750 milliliters. How many liters is that?',
        picture: units('Milliliters', 'Liters', [['1,000', '1'], ['750', '?']]), answer: 0.75,
        steps: ['Liters are bigger, so divide.', '1,000 milliliters is 1 liter, so find 750 ÷ 1,000. Every digit moves three places right.', 'So the bottle holds 0.75 liters.'] } },
    ],
  },
]
