/**
 * Grade 5 · Module 5 — Addition and multiplication with area and volume.
 * Written to docs/new-flow/AUTHORING.md. Not yet reviewed by the founder.
 * Topic 2 follows the founder's own Grade 5 example (a box 4 long, 3 wide, 2 layers high).
 */
import type { Lesson, Picture } from '../script'
import { attachChalk } from '../chalk'
import { G5M5_CHALK } from './chalk/g5m5'

// ── shared pictures ─────────────────────────────────────────────────────────────────────────────
const ALL4 = [0, 1, 2, 3]
const sq: [number, number][] = [[0, 4], [3, 4], [3, 7], [0, 7]]
const rect: [number, number][] = [[5, 4], [10, 4], [10, 7], [5, 7]]
const rhom: [number, number][] = [[0, 0], [3, 0], [4.5, 2.6], [1.5, 2.6]]
const lean: [number, number][] = [[6, 0], [10, 0], [11, 2.5], [7, 2.5]]
const FAMILY: Picture = { kind: 'poly', shapes: [{ pts: sq, tone: 1 }, { pts: rect, tone: 2 }, { pts: rhom, tone: 3 }, { pts: lean, tone: 4 }] }
const YES_NO = ['yes', 'no']

const boxes = (a: string[], b: string[], names = ['Box A', 'Box B']): Picture =>
  ({ kind: 'table', head: ['', 'length', 'width', 'height'], rows: [[names[0], ...a], [names[1], ...b]], rowHead: true })

export const G5M5: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m5-t1', title: 'Volume is counting cubes', skill: 'The space inside a box is the number of unit cubes that fill it',
    bigIdea: "To find how much space is inside a box, count the small cubes that fill it, with no gaps.",
    screens: [
      { scene: 'g5m5-t1', title: 'A box of blocks', text: 'A toy box is packed with small blocks, all the same size. How much space is inside the box?',
        pictures: [{ kind: 'cubes', l: 3, w: 2, h: 2 }] },
      { title: "Flat tiles are not enough", text: "Tiles cover a flat floor. But this box goes up, too. Can flat tiles fill it? No. The space above them stays empty.",
        beats: [
          { say: "Tiles cover a flat floor.", pic: 0 },
          { say: "But this box goes up, too. Can flat tiles fill it?" },
          { say: "No. The space above them stays empty." },
        ],
        pictures: [{ kind: 'cubes', l: 3, w: 2, h: 2, layers: 1 }] },
      { title: "The big idea", text: "To find how much space is inside a box, count the small cubes that fill it, with no gaps.",
        beats: [
          { say: "To find how much space is inside a box, count the small cubes that fill it, with no gaps.", pic: 0 },
        ],
        pictures: [{ kind: 'cubes', l: 3, w: 2, h: 2 }] },
      { title: "Every cube is the same", text: "Look at one little cube. It's 1 unit long, 1 unit wide and 1 unit tall. They're all the same, so they fit with no gaps.",
        beats: [
          { say: "Look at one little cube.", pic: 0 },
          { say: "It's 1 unit long, 1 unit wide and 1 unit tall." },
          { say: "They're all the same, so they fit with no gaps.", pic: 1 },
        ],
        pictures: [{ kind: 'cubes', l: 1, w: 1, h: 1 }, { kind: 'cubes', l: 3, w: 2, h: 2 }] },
      { title: "Count the cubes", text: "Let's count. The bottom layer is 2 rows of 3. That's 6. The top layer is the same, 6 more. 6 + 6 = 12.",
        beats: [
          { say: "Let's count. The bottom layer is 2 rows of 3. That's 6.", pic: 0 },
          { say: "The top layer is the same, 6 more." },
          { say: "6 + 6 = 12.", pic: 1 },
        ],
        pictures: [{ kind: 'cubes', l: 3, w: 2, h: 2, motion: true }, { kind: 'eq', text: '6 + 6 = 12' }] },
      { title: "That is the space inside", text: "So 12 cubes fill the box. That number is how much space is inside.",
        beats: [
          { say: "So 12 cubes fill the box.", pic: 0 },
          { say: "That number is how much space is inside.", pic: 1 },
        ],
        pictures: [{ kind: 'cubes', l: 3, w: 2, h: 2 }, { kind: 'eq', text: '12 cubes' }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't count only the cubes you SEE. You see 10. 2 more hide in back, under the top layer. That makes 12. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't count only the cubes you SEE.", pic: 0 },
          { say: "You see 10. 2 more hide in back, under the top layer. That makes 12.", pic: 1 },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cubes', l: 3, w: 2, h: 2 }, { kind: 'cards', wrong: 'only the cubes you see: 10', right: 'every cube, even hidden ones: 12' }] },
    ],
    turn: {
      text: 'Each small cube is the same size. How many cubes fill this box?',
      picture: { kind: 'cubes', l: 4, w: 2, h: 2 },
      answer: 16, steps: ['The top layer has 2 rows of 4: 4 + 4 = 8 cubes.', 'The layer underneath is the same: 8 more, even the ones you cannot see.', 'So 16 cubes fill the box.'],
      prompt: 'Count every cube once, even the hidden ones.',
      hint1: 'Count the cubes on top first. Then think about the cubes underneath.',
      hint2: 'The top layer has 8 cubes. Is the layer under it the same?',
      twin: { text: 'Each small cube is the same size. How many cubes fill this box?',
        picture: { kind: 'cubes', l: 3, w: 3, h: 2 },
        answer: 18, steps: ['The top layer has 3 rows of 3: 3 + 3 + 3 = 9 cubes.', 'The layer underneath has 9 more, even the ones you cannot see.', 'So 18 cubes fill the box.'],
        hint1: 'Count the cubes on top first. Then count the layer under them.', hint2: 'The top has 3 rows of 3 cubes. The layer below is just the same.' },
    },
    won: { text: 'You counted every cube, even the ones hiding at the back and underneath.', sticker: 'The number of unit cubes that fill a box is its volume.' },
    twinWon: { text: 'You counted every cube, even the hidden ones, and found 18.', sticker: 'The number of unit cubes that fill a box is its volume.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Each small cube is the same size. How many cubes fill this box?',
        picture: { kind: 'cubes', l: 3, w: 2, h: 1 }, answer: 6,
        steps: ['The box has just one layer, so nothing hides underneath.', 'Count each cube: 3 + 3 = 6.', 'So 6 cubes fill the box.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Each small cube is the same size. How many cubes fill this box?',
        picture: { kind: 'cubes', l: 5, w: 2, h: 2 }, answer: 20,
        steps: ['The top layer has 5 + 5 = 10 cubes.', 'The layer underneath has 10 more.', 'So 20 cubes fill the box.'] } },
      { why: 'Still "count every cube"', problem: { text: 'Each small cube is the same size. How many cubes fill this box?',
        picture: { kind: 'cubes', l: 2, w: 2, h: 3 }, answer: 12,
        steps: ['Each layer has 2 + 2 = 4 cubes.', 'There are 3 layers: 4, 8, 12.', 'So 12 cubes fill the box.'] } },
      { why: 'A little harder', problem: { text: 'Each small cube is the same size. How many cubes fill this box?',
        picture: { kind: 'cubes', l: 3, w: 3, h: 3 }, answer: 27,
        steps: ['Each layer has 3 + 3 + 3 = 9 cubes.', 'There are 3 layers: 9, 18, 27.', 'So 27 cubes fill the box.'] } },
      { why: 'Same math in a story', problem: { text: 'Ben packs sugar cubes into a small box, with no gaps. How many sugar cubes fit in the box?',
        picture: { kind: 'cubes', l: 5, w: 3, h: 2 }, answer: 30,
        steps: ['The top layer has 3 rows of 5: 5 + 5 + 5 = 15 cubes.', 'The layer underneath has 15 more.', 'So 30 sugar cubes fit.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m5-t2', title: 'One layer times how many layers', skill: 'Volume of a box: cubes in one layer × number of layers',
    bigIdea: "Count the cubes in one layer, then multiply by how many layers.",
    screens: [
      { scene: 'g5m5-t2', title: 'A box to pack', text: 'A box is packed with little cubes. It is 4 cubes long, 3 cubes wide and 2 layers high. How many cubes are inside?',
        pictures: [{ kind: 'cubes', l: 4, w: 3, h: 2 }] },
      { title: "Too many to count", text: "Could you count them one by one? You could. But some hide at the back, and a whole layer hides underneath. You'd lose your place. Is there a faster way? Yes.",
        beats: [
          { say: "Could you count them one by one?", pic: 0 },
          { say: "You could. But some hide at the back, and a whole layer hides underneath." },
          { say: "You'd lose your place. Is there a faster way? Yes." },
        ],
        pictures: [{ kind: 'cubes', l: 4, w: 3, h: 2 }] },
      { title: "The big idea", text: "Count the cubes in one layer, then multiply by how many layers.",
        beats: [
          { say: "Count the cubes in one layer, then multiply by how many layers.", pic: 0 },
        ],
        pictures: [{ kind: 'cubes', l: 4, w: 3, h: 2 }] },
      { title: "Find the bottom layer", text: "Start with the bottom layer. It's 4 cubes long and 3 cubes wide. So 4 × 3 = 12 cubes.",
        beats: [
          { say: "Start with the bottom layer.", pic: 0 },
          { say: "It's 4 cubes long and 3 cubes wide." },
          { say: "So 4 × 3 = 12 cubes.", pic: 1 },
        ],
        pictures: [{ kind: 'cubes', l: 4, w: 3, h: 2, layers: 1 }, { kind: 'eq', text: '4 × 3 = 12' }] },
      { title: "Stack the next layer", text: "Now put the next layer on top. It's just like the bottom one. Another 12 cubes.",
        beats: [
          { say: "Now put the next layer on top.", pic: 0 },
          { say: "It's just like the bottom one. Another 12 cubes." },
        ],
        pictures: [{ kind: 'cubes', l: 4, w: 3, h: 2, motion: true }] },
      { title: "Multiply by the layers", text: "So that's 2 layers of 12. 12 × 2 = 24. The box holds 24 cubes.",
        beats: [
          { say: "So that's 2 layers of 12.", pic: 0 },
          { say: "12 × 2 = 24. The box holds 24 cubes.", pic: 1 },
        ],
        pictures: [{ kind: 'cubes', l: 4, w: 3, h: 2 }, { kind: 'eq', text: '12 × 2 = 24', lines: ['24 cubes'] }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't STOP after one layer. 12 is only the bottom of the box. Multiply by the 2 layers to get 24. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't STOP after one layer.", pic: 0 },
          { say: "12 is only the bottom of the box. Multiply by the 2 layers to get 24.", pic: 1 },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cubes', l: 4, w: 3, h: 2, layers: 1 }, { kind: 'cards', wrong: '4 × 3 = 12', right: '4 × 3 = 12, then 12 × 2 = 24' }] },
    ],
    turn: {
      text: 'A box is 5 cubes long, 2 cubes wide and 3 layers high. How many cubes fill it?',
      picture: { kind: 'cubes', l: 5, w: 2, h: 3, layers: 1 },
      answer: 30, steps: ['One layer is 5 × 2 = 10 cubes.', 'There are 3 layers, so multiply 10 × 3.', 'So 30 cubes fill the box.'],
      prompt: 'Find one layer. Then multiply by the number of layers.',
      hint1: 'How many cubes are in the bottom layer?',
      hint2: 'One layer is 5 × 2. How many layers are there?',
      twin: { text: 'A box is 3 cubes long, 3 cubes wide and 4 layers high. How many cubes fill it?',
        picture: { kind: 'cubes', l: 3, w: 3, h: 4, layers: 1 },
        answer: 36, steps: ['One layer is 3 × 3 = 9 cubes.', 'There are 4 layers, so multiply 9 × 4.', 'So 36 cubes fill the box.'],
        hint1: 'How many cubes are in the bottom layer?', hint2: 'One layer is 3 × 3. Now multiply by the number of layers.' },
    },
    won: { text: 'You found one layer, then multiplied by the layers.', sticker: 'Volume = cubes in one layer × number of layers. Each cube is a cubic unit.' },
    twinWon: { text: 'You found one layer of 3 × 3, then multiplied by 4 layers to get 36.', sticker: 'Volume = cubes in one layer × number of layers. Each cube is a cubic unit.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A box is 4 cubes long, 2 cubes wide and 2 layers high. How many cubes fill it?',
        picture: { kind: 'cubes', l: 4, w: 2, h: 2, layers: 1 }, answer: 16,
        steps: ['One layer is 4 × 2 = 8 cubes.', 'There are 2 layers: 8 × 2.', 'So 16 cubes fill the box.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A box is 3 cubes long, 2 cubes wide and 5 layers high. How many cubes fill it?',
        picture: { kind: 'cubes', l: 3, w: 2, h: 5, layers: 1 }, answer: 30,
        steps: ['One layer is 3 × 2 = 6 cubes.', 'There are 5 layers: 6 × 5.', 'So 30 cubes fill the box.'] } },
      { why: 'Still "one layer times layers"', problem: { text: 'A box is 6 cubes long, 2 cubes wide and 4 layers high. How many cubes fill it?',
        picture: { kind: 'cubes', l: 6, w: 2, h: 4, layers: 1 }, answer: 48,
        steps: ['One layer is 6 × 2 = 12 cubes.', 'There are 4 layers: 12 × 4.', 'So 48 cubes fill the box.'] } },
      { why: 'A little harder', problem: { text: 'A box is 5 cubes long, 4 cubes wide and 3 layers high. How many cubes fill it?',
        picture: { kind: 'cubes', l: 5, w: 4, h: 3, layers: 1 }, answer: 60,
        steps: ['One layer is 5 × 4 = 20 cubes.', 'There are 3 layers: 20 × 3.', 'So 60 cubes fill the box.'] } },
      { why: 'Same math in a story', problem: { text: 'A crate is packed with juice boxes in layers. Each layer is 6 juice boxes long and 3 wide. The crate has 4 layers. How many juice boxes are in the crate?',
        picture: { kind: 'cubes', l: 6, w: 3, h: 4, layers: 1 }, answer: 72,
        steps: ['One layer is 6 × 3 = 18 juice boxes.', 'There are 4 layers: 18 × 4.', 'So there are 72 juice boxes in the crate.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m5-t3', title: 'Length × width × height', skill: 'Volume of a box = length × width × height',
    bigIdea: "Multiply the length, the width and the height to find the volume of a box.",
    screens: [
      { scene: 'g5m5-t3', title: 'A fish tank', text: 'A fish tank is 5 feet long, 2 feet wide and 3 feet tall. How much water can fit inside?',
        pictures: [{ kind: 'solid', shape: 'prism', labels: { l: '5 ft', w: '2 ft', h: '3 ft' } }] },
      { title: "No cubes to count", text: "This time there are no cubes to count. But you know every edge: 5 feet, 2 feet and 3 feet. Can the edges tell you how much fits? Yes.",
        beats: [
          { say: "This time there are no cubes to count.", pic: 0 },
          { say: "But you know every edge: 5 feet, 2 feet and 3 feet." },
          { say: "Can the edges tell you how much fits? Yes." },
        ],
        pictures: [{ kind: 'solid', shape: 'prism', labels: { l: '5 ft', w: '2 ft', h: '3 ft' } }] },
      { title: "The big idea", text: "Multiply the length, the width and the height to find the volume of a box.",
        beats: [
          { say: "Multiply the length, the width and the height to find the volume of a box.", pic: 0 },
        ],
        pictures: [{ kind: 'solid', shape: 'prism', labels: { l: 'length', w: 'width', h: 'height' } }] },
      { title: "The bottom is one layer", text: "Start with the bottom. It's 5 feet by 2 feet. Cubes 1 foot on each side cover it: 5 × 2 = 10. That's one layer.",
        beats: [
          { say: "Start with the bottom. It's 5 feet by 2 feet.", pic: 0 },
          { say: "Cubes 1 foot on each side cover it: 5 × 2 = 10.", pic: 1 },
          { say: "That's one layer." },
        ],
        pictures: [{ kind: 'solid', shape: 'prism', labels: { l: '5 ft', w: '2 ft' } }, { kind: 'eq', text: '5 × 2 = 10' }] },
      { title: "The height is the layers", text: "The tank is 3 feet tall, so 3 layers stack up. Ten, twenty, thirty.",
        beats: [
          { say: "The tank is 3 feet tall, so 3 layers stack up.", pic: 0 },
          { say: "Ten, twenty, thirty.", pic: 1 },
        ],
        pictures: [{ kind: 'solid', shape: 'prism', labels: { l: '5 ft', w: '2 ft', h: '3 ft' } },
          { kind: 'table', head: ['layers', 'cubes'], rows: [['1', '10'], ['2', '20'], ['3', '30']], motion: true }] },
      { title: "Put it together", text: "So multiply all three. 5 × 2 × 3 = 30. The tank holds 30 cubic feet of water.",
        beats: [
          { say: "So multiply all three." },
          { say: "5 × 2 × 3 = 30. The tank holds 30 cubic feet of water.", pic: 0 },
        ],
        pictures: [{ kind: 'eq', text: '5 × 2 × 3 = 30', lines: ['30 cubic feet'] }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't ADD the edges. 5 + 2 + 3 = 10 only walks along three edges. Multiply to fill the inside. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't ADD the edges.", pic: 0 },
          { say: "5 + 2 + 3 = 10 only walks along three edges. Multiply to fill the inside." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '5 + 2 + 3 = 10', right: '5 × 2 × 3 = 30' }] },
    ],
    turn: {
      text: 'A box is 4 cm long, 3 cm wide and 5 cm tall. What is its volume in cubic centimeters?',
      picture: { kind: 'solid', shape: 'prism', labels: { l: '4 cm', w: '3 cm', h: '5 cm' } },
      answer: 60, steps: ['The bottom layer is 4 × 3 = 12 cubes.', 'The box is 5 cm tall, so there are 5 layers: 12 × 5.', 'So the volume is 60 cubic centimeters.'],
      prompt: 'Multiply the length by the width. Then multiply by the height.',
      hint1: 'Multiply the length by the width first. That is one layer.',
      hint2: 'The bottom is 4 × 3. Now multiply by the height, 5.',
      twin: { text: 'A box is 6 in long, 2 in wide and 4 in tall. What is its volume in cubic inches?',
        picture: { kind: 'solid', shape: 'prism', labels: { l: '6 in', w: '2 in', h: '4 in' } },
        answer: 48, steps: ['The bottom layer is 6 × 2 = 12 cubes.', 'The box is 4 inches tall, so there are 4 layers: 12 × 4.', 'So the volume is 48 cubic inches.'],
        hint1: 'Multiply the length by the width first. That is one layer.', hint2: 'The bottom is 6 × 2. Now multiply by the height.' },
    },
    won: { text: 'You multiplied the length, the width and the height to fill the box.', sticker: 'A box shape is called a rectangular prism. Its volume = length × width × height.' },
    twinWon: { text: 'You multiplied 6 × 2 × 4 to get 48 cubic inches.', sticker: 'A box shape is called a rectangular prism. Its volume = length × width × height.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A box is 3 ft long, 2 ft wide and 4 ft tall. What is its volume in cubic feet?',
        picture: { kind: 'solid', shape: 'prism', labels: { l: '3 ft', w: '2 ft', h: '4 ft' } }, answer: 24,
        steps: ['The bottom layer is 3 × 2 = 6.', 'There are 4 layers: 6 × 4.', 'So the volume is 24 cubic feet.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A box is 5 cm long, 4 cm wide and 2 cm tall. What is its volume in cubic centimeters?',
        picture: { kind: 'solid', shape: 'prism', labels: { l: '5 cm', w: '4 cm', h: '2 cm' } }, answer: 40,
        steps: ['The bottom layer is 5 × 4 = 20.', 'There are 2 layers: 20 × 2.', 'So the volume is 40 cubic centimeters.'] } },
      { why: 'Still "length × width × height"', problem: { text: 'A box is 7 in long, 3 in wide and 2 in tall. What is its volume in cubic inches?',
        picture: { kind: 'solid', shape: 'prism', labels: { l: '7 in', w: '3 in', h: '2 in' } }, answer: 42,
        steps: ['The bottom layer is 7 × 3 = 21.', 'There are 2 layers: 21 × 2.', 'So the volume is 42 cubic inches.'] } },
      { why: 'A little harder', problem: { text: 'A box is 8 cm long, 5 cm wide and 6 cm tall. What is its volume in cubic centimeters?',
        picture: { kind: 'solid', shape: 'prism', labels: { l: '8 cm', w: '5 cm', h: '6 cm' } }, answer: 240,
        steps: ['The bottom layer is 8 × 5 = 40.', 'There are 6 layers: 40 × 6.', 'So the volume is 240 cubic centimeters.'] } },
      { why: 'Same math in a story', problem: { text: 'A sandbox is 7 feet long, 4 feet wide and 2 feet deep. How many cubic feet of sand fill it?',
        picture: { kind: 'solid', shape: 'prism', labels: { l: '7 ft', w: '4 ft', h: '2 ft' } }, answer: 56,
        steps: ['The bottom layer is 7 × 4 = 28.', 'The sand is 2 feet deep, so 2 layers: 28 × 2.', 'So 56 cubic feet of sand fill it.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m5-t4', title: 'Two boxes joined together', skill: 'Volume of a solid made of two boxes: find each box, then add',
    bigIdea: "When two boxes are joined, find the volume of each box, then add them.",
    screens: [
      { scene: 'g5m5-t4', title: 'A toy chest', text: 'A toy chest is a big box with a small box joined on top. How much space is inside it all?',
        pictures: [{ kind: 'solid', shape: 'prism', labels: { l: '4 ft', w: '2 ft', h: '3 ft' } }, { kind: 'solid', shape: 'prism', labels: { l: '2 ft', w: '2 ft', h: '1 ft' } }] },
      { title: "It is not one box", text: "Can you multiply one length, one width and one height here? No. The chest is two boxes of different sizes.",
        beats: [
          { say: "Can you multiply one length, one width and one height here?", pic: 0 },
          { say: "No. The chest is two boxes of different sizes." },
        ],
        pictures: [boxes(['4 ft', '2 ft', '3 ft'], ['2 ft', '2 ft', '1 ft'], ['big box', 'small box'])] },
      { title: "The big idea", text: "When two boxes are joined, find the volume of each box, then add them.",
        beats: [
          { say: "When two boxes are joined, find the volume of each box, then add them.", pic: 0 },
        ],
        pictures: [{ kind: 'solid', shape: 'prism', labels: { l: '4 ft', w: '2 ft', h: '3 ft' } }, { kind: 'solid', shape: 'prism', labels: { l: '2 ft', w: '2 ft', h: '1 ft' } }] },
      { title: "The big box first", text: "Start with the big box. It's 4 feet long, 2 feet wide and 3 feet tall. 4 × 2 × 3 = 24 cubic feet.",
        beats: [
          { say: "Start with the big box.", pic: 0 },
          { say: "It's 4 feet long, 2 feet wide and 3 feet tall." },
          { say: "4 × 2 × 3 = 24 cubic feet.", pic: 1 },
        ],
        pictures: [{ kind: 'solid', shape: 'prism', labels: { l: '4 ft', w: '2 ft', h: '3 ft' } }, { kind: 'eq', text: '4 × 2 × 3 = 24' }] },
      { title: "Then the small box", text: "Now the small box on top. It's 2 feet long, 2 feet wide and 1 foot tall. 2 × 2 × 1 = 4 cubic feet.",
        beats: [
          { say: "Now the small box on top.", pic: 0 },
          { say: "It's 2 feet long, 2 feet wide and 1 foot tall." },
          { say: "2 × 2 × 1 = 4 cubic feet.", pic: 1 },
        ],
        pictures: [{ kind: 'solid', shape: 'prism', labels: { l: '2 ft', w: '2 ft', h: '1 ft' } },
          { kind: 'table', head: ['box', 'multiply', 'cubic feet'], rows: [['big box', '4 × 2 × 3', '24'], ['small box', '2 × 2 × 1', '4']], motion: true }] },
      { title: "Add the two boxes", text: "Put them back together. 24 + 4 = 28. The chest holds 28 cubic feet.",
        beats: [
          { say: "Put them back together." },
          { say: "24 + 4 = 28. The chest holds 28 cubic feet.", pic: 0 },
        ],
        pictures: [{ kind: 'eq', text: '24 + 4 = 28', lines: ['28 cubic feet'] }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't use the TALLEST height for the whole chest. 4 × 2 × 4 = 32 counts empty space beside the small box. Find each box, then add. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't use the TALLEST height for the whole chest.", pic: 0 },
          { say: "4 × 2 × 4 = 32 counts empty space beside the small box. Find each box, then add." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '4 × 2 × 4 = 32', right: '24 + 4 = 28' }] },
    ],
    turn: {
      text: 'Two boxes are joined. Box A is 5 cm long, 3 cm wide and 2 cm tall. Box B is 2 cm long, 3 cm wide and 4 cm tall. What is the total volume in cubic centimeters?',
      picture: boxes(['5 cm', '3 cm', '2 cm'], ['2 cm', '3 cm', '4 cm']),
      answer: 54, steps: ['Box A: 5 × 3 × 2 = 30 cubic centimeters.', 'Box B: 2 × 3 × 4 = 24 cubic centimeters.', '30 + 24 = 54. So the total volume is 54 cubic centimeters.'],
      prompt: 'Find the volume of each box. Then add the two.',
      hint1: 'Find the volume of each box on its own. Then add them.',
      hint2: 'Box A is 5 × 3 × 2. Box B is 2 × 3 × 4. Add the two answers.',
      twin: { text: 'Two boxes are joined. Box A is 4 in long, 4 in wide and 2 in tall. Box B is 3 in long, 2 in wide and 2 in tall. What is the total volume in cubic inches?',
        picture: boxes(['4 in', '4 in', '2 in'], ['3 in', '2 in', '2 in']),
        answer: 44, steps: ['Box A: 4 × 4 × 2 = 32 cubic inches.', 'Box B: 3 × 2 × 2 = 12 cubic inches.', '32 + 12 = 44. So the total volume is 44 cubic inches.'],
        hint1: 'Find the volume of each box on its own. Then add them.', hint2: 'Box A is 4 × 4 × 2. Box B is 3 × 2 × 2. Add the two answers.' },
    },
    won: { text: 'You found the volume of each box, then added them.', sticker: 'A solid made of smaller boxes is a composite solid. Its volume is the boxes added together.' },
    twinWon: { text: 'You found each box and added them to get 44 cubic inches.', sticker: 'A solid made of smaller boxes is a composite solid. Its volume is the boxes added together.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Two boxes are joined. Box A is 3 ft by 2 ft by 2 ft. Box B is 2 ft by 2 ft by 1 ft. What is the total volume in cubic feet?',
        picture: boxes(['3 ft', '2 ft', '2 ft'], ['2 ft', '2 ft', '1 ft']), answer: 16,
        steps: ['Box A: 3 × 2 × 2 = 12.', 'Box B: 2 × 2 × 1 = 4.', '12 + 4 = 16. So the total is 16 cubic feet.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Two boxes are joined. Box A is 6 cm by 2 cm by 3 cm. Box B is 3 cm by 2 cm by 2 cm. What is the total volume in cubic centimeters?',
        picture: boxes(['6 cm', '2 cm', '3 cm'], ['3 cm', '2 cm', '2 cm']), answer: 48,
        steps: ['Box A: 6 × 2 × 3 = 36.', 'Box B: 3 × 2 × 2 = 12.', '36 + 12 = 48. So the total is 48 cubic centimeters.'] } },
      { why: 'Still "each box, then add"', problem: { text: 'Two boxes are joined. Box A is 5 in by 5 in by 2 in. Box B is 5 in by 2 in by 3 in. What is the total volume in cubic inches?',
        picture: boxes(['5 in', '5 in', '2 in'], ['5 in', '2 in', '3 in']), answer: 80,
        steps: ['Box A: 5 × 5 × 2 = 50.', 'Box B: 5 × 2 × 3 = 30.', '50 + 30 = 80. So the total is 80 cubic inches.'] } },
      { why: 'A little harder', problem: { text: 'Two boxes are joined. Box A is 10 cm by 4 cm by 3 cm. Box B is 6 cm by 4 cm by 2 cm. What is the total volume in cubic centimeters?',
        picture: boxes(['10 cm', '4 cm', '3 cm'], ['6 cm', '4 cm', '2 cm']), answer: 168,
        steps: ['Box A: 10 × 4 × 3 = 120.', 'Box B: 6 × 4 × 2 = 48.', '120 + 48 = 168. So the total is 168 cubic centimeters.'] } },
      { why: 'Same math in a story', problem: { text: 'A step stool is made of two wooden boxes. The bottom box is 8 inches long, 6 inches wide and 4 inches tall. The top box is 4 inches long, 6 inches wide and 4 inches tall. What is the volume of the stool in cubic inches?',
        picture: boxes(['8 in', '6 in', '4 in'], ['4 in', '6 in', '4 in'], ['bottom box', 'top box']), answer: 288,
        steps: ['Bottom box: 8 × 6 × 4 = 192.', 'Top box: 4 × 6 × 4 = 96.', '192 + 96 = 288. So the stool is 288 cubic inches.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m5-t5', title: 'Tiles with fraction sides', skill: 'Area of a rectangle with fraction side lengths, with unit fraction tiles',
    bigIdea: "Cut each foot into halves, count the small tiles, and every 4 small tiles make 1 square foot.",
    screens: [
      { scene: 'g5m5-t5', title: 'A rug with fraction sides', text: 'A rug is 2 1/2 feet long and 1 1/2 feet wide. How many square feet does it cover?',
        pictures: [{ kind: 'grid', rows: 3, cols: 5, top: '2 1/2 ft', left: '1 1/2 ft' }] },
      { title: "Big tiles leave a gap", text: "Try 1-foot square tiles. Two fit along the top. Then half a foot is left. What goes in that gap?",
        beats: [
          { say: "Try 1-foot square tiles.", pic: 0 },
          { say: "Two fit along the top. Then half a foot is left." },
          { say: "What goes in that gap?" },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 5, top: '2 1/2 ft', left: '1 1/2 ft', shade: [{ r: 0, c: 0, h: 2, w: 2, tone: 2 }, { r: 0, c: 2, h: 2, w: 2, tone: 2 }] }] },
      { title: "The big idea", text: "Cut each foot into halves, count the small tiles, and every 4 small tiles make 1 square foot.",
        beats: [
          { say: "Cut each foot into halves, count the small tiles, and every 4 small tiles make 1 square foot.", pic: 0 },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 5, shade: [{ r: 0, c: 0, h: 2, w: 2, tone: 2 }] }] },
      { title: "Cut into halves", text: "So cut every foot in half. Now the top is 5 halves, and the side is 3 halves. That's 3 rows of 5 small tiles, with no gap.",
        beats: [
          { say: "So cut every foot in half.", pic: 0 },
          { say: "Now the top is 5 halves, and the side is 3 halves." },
          { say: "That's 3 rows of 5 small tiles, with no gap." },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 5, top: '5 halves', left: '3 halves' }] },
      { title: "How big is one small tile?", text: "How big is one small tile? It's 1/2 foot on each side. 4 of them make 1 square foot, so one is 1/4 of a square foot.",
        beats: [
          { say: "How big is one small tile?", pic: 0 },
          { say: "It's 1/2 foot on each side." },
          { say: "4 of them make 1 square foot, so one is 1/4 of a square foot.", pic: 1 },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 5, motion: true,
          shade: [{ r: 0, c: 0, h: 1, w: 1 }, { r: 0, c: 1, h: 1, w: 1 }, { r: 1, c: 0, h: 1, w: 1 }, { r: 1, c: 1, h: 1, w: 1 }] },
          { kind: 'eq', text: '4 small tiles = 1 square foot' }] },
      { title: "Count, then change to feet", text: "Count them. 3 rows of 5 is 15 small tiles. Every 4 make 1 square foot, so that's 15/4, or 3 3/4 square feet. It's the same as 5/2 × 3/2.",
        beats: [
          { say: "Count them.", pic: 0 },
          { say: "3 rows of 5 is 15 small tiles." },
          { say: "Every 4 make 1 square foot, so that's 15/4, or 3 3/4 square feet.", pic: 1 },
          { say: "It's the same as 5/2 × 3/2." },
        ],
        pictures: [{ kind: 'grid', rows: 3, cols: 5, motion: true,
          shade: [{ r: 0, c: 0, h: 1, w: 5 }, { r: 1, c: 0, h: 1, w: 5 }, { r: 2, c: 0, h: 1, w: 5 }] },
          { kind: 'eq', text: '5/2 × 3/2 = 15/4', lines: ['15/4 = 3 3/4 square feet'] }] },
      { title: "One thing not to do", text: "Here's the part people mix up. 15 small tiles are NOT 15 square feet. Each tile is only 1/4 of one. So the rug is 3 3/4 square feet. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "15 small tiles are NOT 15 square feet.", pic: 0 },
          { say: "Each tile is only 1/4 of one. So the rug is 3 3/4 square feet." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '15 square feet', right: '15/4 = 3 3/4 square feet' }] },
    ],
    turn: {
      text: 'A mat is 1 1/2 feet long and 1 1/2 feet wide. Each small tile is 1/2 foot on a side. How many square feet is the mat?',
      picture: { kind: 'grid', rows: 3, cols: 3, top: '1 1/2 ft', left: '1 1/2 ft' },
      answer: { frac: [1, 4], whole: 2 },
      steps: ['1 1/2 feet is 3 halves, so the mat is 3 rows of 3 small tiles: 9 tiles.', 'Each small tile is 1/4 of a square foot, so 9 tiles are 9/4.', '9/4 = 2 1/4. So the mat is 2 1/4 square feet.'],
      prompt: 'Count the small tiles. Then change them to square feet.',
      hint1: 'How many small tiles are there? How much of a square foot is one tile?',
      hint2: 'It takes 4 small tiles to make 1 square foot. How many square feet do your tiles make?',
      twin: { text: 'A tray is 3 1/2 feet long and 1 1/2 feet wide. Each small tile is 1/2 foot on a side. How many square feet is the tray?',
        picture: { kind: 'grid', rows: 3, cols: 7, top: '3 1/2 ft', left: '1 1/2 ft' },
        answer: { frac: [1, 4], whole: 5 },
        steps: ['3 1/2 feet is 7 halves and 1 1/2 feet is 3 halves: 3 rows of 7 small tiles, 21 tiles.', 'Each small tile is 1/4 of a square foot, so 21 tiles are 21/4.', '21/4 = 5 1/4. So the tray is 5 1/4 square feet.'],
        hint1: 'Count the halves along each side. Then think about how big one small tile is.', hint2: 'Count all the small tiles. Every 4 small tiles make 1 square foot.' },
    },
    won: { text: 'You counted the small tiles and changed them into square feet.', sticker: 'To find area with fraction sides, multiply the fractions. A tile 1/2 by 1/2 is 1/4 of a square unit.' },
    twinWon: { text: 'You counted the small tiles and found 5 1/4 square feet.', sticker: 'To find area with fraction sides, multiply the fractions. A tile 1/2 by 1/2 is 1/4 of a square unit.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A shelf is 2 1/2 feet long and 1/2 foot wide. Each small tile is 1/2 foot on a side. How many square feet is the shelf?',
        picture: { kind: 'grid', rows: 1, cols: 5, top: '2 1/2 ft', left: '1/2 ft' }, answer: { frac: [1, 4], whole: 1 },
        steps: ['2 1/2 feet is 5 halves and 1/2 foot is 1 half: 1 row of 5 small tiles.', 'Each small tile is 1/4 of a square foot, so 5 tiles are 5/4.', '5/4 = 1 1/4. So the shelf is 1 1/4 square feet.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A mat is 3 feet long and 1 1/2 feet wide. Each small tile is 1/2 foot on a side. How many square feet is the mat?',
        picture: { kind: 'grid', rows: 3, cols: 6, top: '3 ft', left: '1 1/2 ft' }, answer: { frac: [1, 2], whole: 4 },
        steps: ['3 feet is 6 halves and 1 1/2 feet is 3 halves: 3 rows of 6, or 18 small tiles.', 'Each small tile is 1/4 of a square foot, so 18 tiles are 18/4.', '18/4 = 4 2/4 = 4 1/2. So the mat is 4 1/2 square feet.'] } },
      { why: 'Still "count the small tiles"', problem: { text: 'A rug is 3 1/2 feet long and 2 1/2 feet wide. Each small tile is 1/2 foot on a side. How many square feet is the rug?',
        picture: { kind: 'grid', rows: 5, cols: 7, top: '3 1/2 ft', left: '2 1/2 ft' }, answer: { frac: [3, 4], whole: 8 },
        steps: ['3 1/2 feet is 7 halves and 2 1/2 feet is 5 halves: 5 rows of 7, or 35 small tiles.', 'Each small tile is 1/4 of a square foot, so 35 tiles are 35/4.', '35/4 = 8 3/4. So the rug is 8 3/4 square feet.'] } },
      { why: 'A little harder', problem: { text: 'A floor is 4 1/2 feet long and 3 1/2 feet wide. What is its area in square feet?',
        picture: { kind: 'grid', rows: 7, cols: 9, top: '4 1/2 ft', left: '3 1/2 ft' }, answer: { frac: [3, 4], whole: 15 },
        steps: ['4 1/2 is 9/2 and 3 1/2 is 7/2.', 'Multiply: 9/2 × 7/2 = 63/4. That is 63 small tiles of 1/4 square foot.', '63/4 = 15 3/4. So the floor is 15 3/4 square feet.'] } },
      { why: 'Same math in a story', problem: { text: 'Ava paints a board that is 5 1/2 feet long and 1 1/2 feet wide. How many square feet does she paint?',
        picture: { kind: 'grid', rows: 3, cols: 11, top: '5 1/2 ft', left: '1 1/2 ft' }, answer: { frac: [1, 4], whole: 8 },
        steps: ['5 1/2 is 11/2 and 1 1/2 is 3/2.', 'Multiply: 11/2 × 3/2 = 33/4. That is 33 small tiles of 1/4 square foot.', '33/4 = 8 1/4. So Ava paints 8 1/4 square feet.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m5-t6', title: 'Sort four-sided shapes into families', skill: 'Four-sided shapes belong to families inside families (square, rectangle, rhombus, parallelogram)',
    bigIdea: "If a shape follows a family’s rule, it belongs to that family, so one shape can have more than one name.",
    screens: [
      { scene: 'g5m5-t6', title: 'The tile shop bins', text: 'A tile shop sorts four-sided tiles into bins: parallelograms, rectangles, rhombuses and squares. Which bin does a square tile go in?',
        pictures: [FAMILY] },
      { title: "Which bin?", text: "Look at the square tile. It has 4 square corners, like a rectangle. And 4 equal sides, like a rhombus. So which bin? Can it be both?",
        beats: [
          { say: "Look at the square tile.", pic: 0 },
          { say: "It has 4 square corners, like a rectangle." },
          { say: "And 4 equal sides, like a rhombus." },
          { say: "So which bin? Can it be both?" },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: sq, tone: 1, right: ALL4, ticks: ALL4 }, { pts: rect, tone: 2 }, { pts: rhom, tone: 3 }, { pts: lean, tone: 4 }] }] },
      { title: "The big idea", text: "If a shape follows a family’s rule, it belongs to that family, so one shape can have more than one name.",
        beats: [
          { say: "If a shape follows a family’s rule, it belongs to that family, so one shape can have more than one name.", pic: 0 },
        ],
        pictures: [FAMILY] },
      { title: "The biggest family", text: "Start with the biggest family. Every tile here has 2 pairs of sides that run side by side. So all 4 are parallelograms.",
        beats: [
          { say: "Start with the biggest family.", pic: 0 },
          { say: "Every tile here has 2 pairs of sides that run side by side." },
          { say: "So all 4 are parallelograms." },
        ],
        pictures: [{ ...FAMILY, motion: true }] },
      { title: "Two smaller families", text: "Add one more rule, and the family gets smaller. 4 square corners make a rectangle. 4 equal sides make a rhombus. Which tile got both?",
        beats: [
          { say: "Add one more rule, and the family gets smaller.", pic: 0 },
          { say: "4 square corners make a rectangle." },
          { say: "4 equal sides make a rhombus." },
          { say: "Which tile got both?" },
        ],
        pictures: [{ kind: 'poly', shapes: [{ pts: sq, tone: 1, right: ALL4, ticks: ALL4 }, { pts: rect, tone: 2, right: ALL4 }, { pts: rhom, tone: 3, ticks: ALL4 }, { pts: lean, tone: 4 }] }] },
      { title: "The square is in every family", text: "The square. It has square corners and equal sides, both at once. So it's a rectangle, a rhombus and a parallelogram. One tile, 4 names.",
        beats: [
          { say: "The square." },
          { say: "It has square corners and equal sides, both at once." },
          { say: "So it's a rectangle, a rhombus and a parallelogram.", pic: 0 },
          { say: "One tile, 4 names." },
        ],
        pictures: [{ kind: 'table', head: ['tile', 'parallelogram?', 'rectangle?', 'rhombus?', 'square?'], motion: true,
          rows: [['square', 'yes', 'yes', 'yes', 'yes'], ['rectangle', 'yes', 'yes', 'no', 'no'], ['rhombus', 'yes', 'no', 'yes', 'no'], ['leaning tile', 'yes', 'no', 'no', 'no']] }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't flip the families around. Every square is a rectangle, but a rectangle is NOT always a square. It needs 4 equal sides too. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't flip the families around.", pic: 0 },
          { say: "Every square is a rectangle, but a rectangle is NOT always a square." },
          { say: "It needs 4 equal sides too." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: 'Every rectangle is a square', right: 'Every square is a rectangle' }] },
    ],
    turn: {
      text: 'Is every rectangle a parallelogram?',
      picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [6, 0], [6, 3], [0, 3]], right: ALL4, sides: ['6 in', '3 in', '6 in', '3 in'], tone: 2 }] },
      answer: { choices: YES_NO, correct: 0 },
      steps: ['A rectangle has 4 square corners.', 'Its opposite sides run side by side, so it has two pairs of parallel sides.', 'So yes, every rectangle is a parallelogram.'],
      prompt: 'Think of the rule for the family. Does the shape follow it?',
      hint1: 'What rule does every parallelogram follow?',
      hint2: 'Look at the opposite sides of the rectangle. Are they parallel?',
      twin: { text: 'Is every rhombus a square?',
        picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [3, 0], [4.5, 2.6], [1.5, 2.6]], ticks: ALL4, tone: 3 }] },
        answer: { choices: YES_NO, correct: 1 },
        steps: ['A rhombus has 4 equal sides.', 'A square also needs 4 square corners, and this rhombus has none.', 'So no, not every rhombus is a square.'],
        hint1: 'What does a square need that a rhombus might not have?', hint2: 'Look at the corners of this rhombus. Are they square corners?' },
    },
    won: { text: 'You checked the family rule to see which names fit.', sticker: 'Sorting shapes into families inside families is called a hierarchy.' },
    twinWon: { text: 'You saw that a rhombus needs square corners before it is a square.', sticker: 'Sorting shapes into families inside families is called a hierarchy.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Is every square a rhombus?',
        picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [3, 0], [3, 3], [0, 3]], right: ALL4, ticks: ALL4, tone: 1 }] },
        answer: { choices: YES_NO, correct: 0 },
        steps: ['A rhombus needs 4 equal sides.', 'Every square has 4 equal sides.', 'So yes, every square is a rhombus.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Is every parallelogram a rectangle?',
        picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [4, 0], [5, 2.5], [1, 2.5]], tone: 4 }] },
        answer: { choices: YES_NO, correct: 1 },
        steps: ['A rectangle needs 4 square corners.', 'This parallelogram leans over, so its corners are not square corners.', 'So no, not every parallelogram is a rectangle.'] } },
      { why: 'Still "follow the family rules"', problem: { text: 'This shape has two pairs of parallel sides and 4 equal sides, but no square corners. What is the best name for it?',
        picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [2.6, 1.5], [2.6, 4.5], [0, 3]], ticks: ALL4, tone: 3 }] },
        answer: { choices: ['square', 'rhombus', 'rectangle'], correct: 1 },
        steps: ['Two pairs of parallel sides make it a parallelogram. 4 equal sides make it a rhombus.', 'It has no square corners, so it is not a rectangle or a square.', 'So the best name is rhombus.'] } },
      { why: 'A little harder', problem: { text: 'A shape has 4 square corners and 4 equal sides. Which list gives all of its names?',
        picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [4, 0], [4, 4], [0, 4]], right: ALL4, ticks: ALL4, tone: 1 }] },
        answer: { choices: ['square only', 'square and rectangle', 'square, rectangle, rhombus and parallelogram'], correct: 2 },
        steps: ['4 square corners make it a rectangle. 4 equal sides make it a rhombus.', 'Rectangles and rhombuses are both parallelograms, and a shape that is both is a square.', 'So its names are square, rectangle, rhombus and parallelogram.'] } },
      { why: 'Same math in a story', problem: { text: 'Sam cuts a window pane with 4 square corners. Its sides are 3 feet and 2 feet long. Sam says it is a square. Is Sam right?',
        picture: { kind: 'poly', shapes: [{ pts: [[0, 0], [3, 0], [3, 2], [0, 2]], right: ALL4, sides: ['3 ft', '2 ft', '3 ft', '2 ft'], tone: 2 }] },
        answer: { choices: YES_NO, correct: 1 },
        steps: ['4 square corners make it a rectangle.', 'A square also needs 4 equal sides, but its sides are 3 feet and 2 feet.', 'So no, Sam is not right. It is a rectangle, but not a square.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m5-t7', title: 'Cubic units', skill: 'Volume is measured in cubic units; pick a cube size that fits the thing',
    bigIdea: 'Space inside is measured with cubes, so its unit is a cube: a cubic inch, a cubic foot, a cubic meter.',
    screens: [
      { scene: 'g5m5-t7', title: 'A lunch box and a truck', text: 'A lunch box and a moving truck both have space inside. Would you measure them with the same size cube?',
        pictures: [{ kind: 'cubes', l: 3, w: 2, h: 2 }] },
      { title: "Flat squares cannot fill it", text: "You know square units. They're flat, like stickers, great for a floor. But a box goes up too. Can flat stickers fill it? No.",
        beats: [
          { say: "You know square units.", pic: 0 },
          { say: "They're flat, like stickers, great for a floor." },
          { say: "But a box goes up too." },
          { say: "Can flat stickers fill it? No." },
        ],
        pictures: [{ kind: 'cubes', l: 3, w: 2, h: 2, layers: 1 }] },
      { title: "The big idea", text: "Space inside is measured with cubes, so its unit is a cube: a cubic inch, a cubic foot, a cubic meter.",
        beats: [
          { say: "Space inside is measured with cubes, so its unit is a cube: a cubic inch, a cubic foot, a cubic meter.", pic: 0 },
        ],
        pictures: [{ kind: 'cubes', l: 1, w: 1, h: 1 }] },
      { title: "A tiny cube and a big cube", text: "Cubes come in sizes. A cubic centimeter is about as big as your fingertip. A cubic meter is so big you could sit inside it.",
        beats: [
          { say: "Cubes come in sizes.", pic: 0 },
          { say: "A cubic centimeter is about as big as your fingertip.", pic: 1 },
          { say: "A cubic meter is so big you could sit inside it." },
        ],
        pictures: [{ kind: 'cubes', l: 1, w: 1, h: 1 }, { kind: 'table', head: ['cube', 'each edge'], rows: [['cubic centimeter', '1 cm'], ['cubic meter', '1 m']] }] },
      { title: "Count in cubes", text: "Say each cube here is 1 cubic centimeter. One layer is 3 × 2 = 6. There are 2 layers, so that's 12. The box is 12 cubic centimeters, not just 12.",
        beats: [
          { say: "Say each cube here is 1 cubic centimeter.", pic: 0 },
          { say: "One layer is 3 × 2 = 6.", pic: 1 },
          { say: "There are 2 layers, so that's 12." },
          { say: "The box is 12 cubic centimeters, not just 12." },
        ],
        pictures: [{ kind: 'cubes', l: 3, w: 2, h: 2, motion: true }, { kind: 'eq', text: '3 × 2 × 2 = 12', lines: ['12 cubic centimeters'] }] },
      { title: "Pick a cube that fits", text: "Which cube should you pick? A small thing takes a small cube, so a lunch box gets cubic inches. A big truck gets cubic feet.",
        beats: [
          { say: "Which cube should you pick?" },
          { say: "A small thing takes a small cube, so a lunch box gets cubic inches.", pic: 0 },
          { say: "A big truck gets cubic feet." },
        ],
        pictures: [{ kind: 'table', head: ['thing', 'good unit'], rows: [['lunch box', 'cubic inches'], ['juice box', 'cubic centimeters'], ['moving truck', 'cubic feet'], ['swimming pool', 'cubic meters']], motion: true }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't measure space in SQUARE units. Squares only cover a floor. It takes cubes to fill a box, so it's 12 cubic centimeters. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't measure space in SQUARE units.", pic: 0 },
          { say: "Squares only cover a floor." },
          { say: "It takes cubes to fill a box, so it's 12 cubic centimeters." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '12 square centimeters', right: '12 cubic centimeters' }] },
    ],
    turn: {
      text: 'Each cube is 1 cubic inch. What is the volume of this box in cubic inches?',
      picture: { kind: 'cubes', l: 4, w: 2, h: 3 },
      answer: 24, steps: ['One layer is 4 × 2 = 8 cubes.', 'There are 3 layers: 8 × 3.', 'Each cube is 1 cubic inch, so the volume is 24 cubic inches.'],
      prompt: 'Count the cubes one layer at a time. Each cube is 1 cubic inch.',
      hint1: 'How many cubes are in one layer? How many layers are there?',
      hint2: 'One layer is 4 × 2. Count the layers going up.',
      twin: { text: 'Each cube is 1 cubic centimeter. What is the volume of this box in cubic centimeters?',
        picture: { kind: 'cubes', l: 5, w: 2, h: 2 },
        answer: 20, steps: ['One layer is 5 × 2 = 10 cubes.', 'There are 2 layers: 10 × 2.', 'Each cube is 1 cubic centimeter, so the volume is 20 cubic centimeters.'],
        hint1: 'How many cubes are in one layer? How many layers are there?', hint2: 'One layer is 5 × 2. Count the layers going up.' },
    },
    won: { text: 'You counted the cubes and named the unit as a cube.', sticker: 'A cube 1 unit on every edge is a cubic unit. 1 cubic centimeter is written 1 cm³.' },
    twinWon: { text: 'You counted the cubes and found 20 cubic centimeters.', sticker: 'A cube 1 unit on every edge is a cubic unit. 1 cubic centimeter is written 1 cm³.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Each cube is 1 cubic inch. What is the volume of this box in cubic inches?',
        picture: { kind: 'cubes', l: 3, w: 3, h: 2 }, answer: 18,
        steps: ['One layer is 3 × 3 = 9 cubes.', 'There are 2 layers: 9 × 2.', 'So the volume is 18 cubic inches.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Each cube is 1 cubic centimeter. What is the volume of this box in cubic centimeters?',
        picture: { kind: 'cubes', l: 5, w: 3, h: 2 }, answer: 30,
        steps: ['One layer is 5 × 3 = 15 cubes.', 'There are 2 layers: 15 × 2.', 'So the volume is 30 cubic centimeters.'] } },
      { why: 'Still "measure with cubes"', problem: { text: 'Which unit fits best for the space inside a swimming pool?',
        picture: { kind: 'cubes', l: 4, w: 3, h: 2 },
        answer: { choices: ['cubic centimeters', 'cubic meters', 'square meters'], correct: 1 },
        steps: ['Space inside is measured with cubes, not flat squares.', 'A pool is huge, so tiny centimeter cubes would take far too long to count.', 'So the best unit is cubic meters.'] } },
      { why: 'A little harder', problem: { text: 'Each cube is 1 cubic foot. The box is 6 cubes long, 4 cubes wide and 3 cubes tall. What is its volume in cubic feet?',
        picture: { kind: 'cubes', l: 6, w: 4, h: 3, layers: 1 }, answer: 72,
        steps: ['One layer is 6 × 4 = 24 cubes.', 'There are 3 layers: 24 × 3.', 'So the volume is 72 cubic feet.'] } },
      { why: 'Same math in a story', problem: { text: 'Mia fills a jewelry box with 1-centimeter cubes. Each layer has 4 rows of 5 cubes, and there are 2 layers. What is the volume of the box?',
        picture: { kind: 'cubes', l: 5, w: 4, h: 2, layers: 1 },
        answer: { choices: ['40 square centimeters', '40 cubic centimeters', '11 cubic centimeters'], correct: 1 },
        steps: ['4 rows of 5 is 20 cubes in a layer.', '2 layers: 20 × 2 = 40 cubes.', 'Cubes fill space, so the volume is 40 cubic centimeters.'] } },
    ],
  },
]

attachChalk(G5M5, G5M5_CHALK)
