/**
 * Grade 5 · Module 6 — Foundations to geometry in the coordinate plane.
 * Written to docs/new-flow/AUTHORING.md. Every teaching picture is the first-quadrant `coord` grid (plus `table`).
 * Question pictures label points with LETTERS or place names, never with their pairs.
 */
import type { Lesson, Picture } from '../script'
import { attachChalk } from '../chalk'
import { G5M6_CHALK } from './chalk/g5m6'

type Pt = { x: number; y: number; label?: string }
type Ln = { a: [number, number]; b: [number, number]; extend?: boolean; dashed?: boolean; label?: string; tone?: 1 | 2 }
const grid = (max: number, points: Pt[] = [], lines?: Ln[], motion = false): Picture =>
  ({ kind: 'coord', min: 0, max, points, lines, motion })
/** A two-row pattern table: `head` names the columns, each row starts with its name. */
const pat = (head: string[], a: string[], b: string[], mark?: [number, number][], motion = false): Picture =>
  ({ kind: 'table', head: ['', ...head], rows: [['A', ...a], ['B', ...b]], rowHead: true, mark, motion })
const NTH = ['1st', '2nd', '3rd', '4th', '5th', '6th']
const LETTERS3 = ['A', 'B', 'C']

export const G5M6: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m6-t1', title: 'Points on a grid', skill: 'Read where a point is on a grid: across first, then up',
    bigIdea: 'Go across first, then up, so 3 across and 5 up is the point (3, 5).',
    screens: [
      { scene: 'g5m6-t1', title: 'Find the treasure', text: 'A treasure map is a grid. The treasure is at point A. How can you tell a friend exactly where it is?',
        pictures: [grid(6, [{ x: 3, y: 5, label: 'A' }])] },
      { title: 'Pointing is not enough', text: 'Could you just point and say, up near the middle? No. That could be lots of spots. You need two numbers, read in the right order.',
        beats: [
          { say: 'Could you just point and say, up near the middle?', pic: 0 },
          { say: 'No. That could be lots of spots.' },
          { say: 'You need two numbers, read in the right order.' },
        ],
        pictures: [grid(6, [{ x: 3, y: 5, label: 'A' }])] },
      { title: 'The big idea', text: 'Go across first, then up, so 3 across and 5 up is the point (3, 5).',
        beats: [
          { say: 'Go across first, then up, so 3 across and 5 up is the point (3, 5).', pic: 0 },
        ],
        pictures: [grid(6, [{ x: 3, y: 5, label: 'A' }])] },
      { title: 'Go across first', text: "Start at 0, down in the corner. Walk along the bottom until you're right under point A. One, two, three. That's 3 across.",
        beats: [
          { say: 'Start at 0, down in the corner.', pic: 0 },
          { say: "Walk along the bottom until you're right under point A." },
          { say: "One, two, three. That's 3 across." },
        ],
        pictures: [grid(6, [{ x: 3, y: 5, label: 'A' }], [{ a: [0, 0], b: [3, 0], dashed: true, tone: 2, label: '3 across' }], true)] },
      { title: 'Then go up', text: "Now go straight up from there. Count with me. One, two, three, four, five. You land on point A. That's 5 up.",
        beats: [
          { say: 'Now go straight up from there.', pic: 0 },
          { say: 'Count with me. One, two, three, four, five.' },
          { say: "You land on point A. That's 5 up." },
        ],
        pictures: [grid(6, [{ x: 3, y: 5, label: 'A' }], [{ a: [0, 0], b: [3, 0], dashed: true, tone: 2 }, { a: [3, 0], b: [3, 5], dashed: true, label: '5 up' }], true)] },
      { title: 'Write the two numbers', text: 'Two moves, two numbers. The number across goes first. The number up goes second. So point A is at (3, 5).',
        beats: [
          { say: 'Two moves, two numbers.', pic: 0 },
          { say: 'The number across goes first. The number up goes second.' },
          { say: 'So point A is at (3, 5).', pic: 1 },
        ],
        pictures: [grid(6, [{ x: 3, y: 5, label: 'A' }], [{ a: [0, 0], b: [3, 0], dashed: true, tone: 2 }, { a: [3, 0], b: [3, 5], dashed: true }]),
          { kind: 'eq', text: '3 across, 5 up', lines: ['(3, 5)'] }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't write the number UP first. That's 5 across and 3 up, a different spot. Across goes first. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't write the number UP first.", pic: 0 },
          { say: "That's 5 across and 3 up, a different spot. Across goes first." },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: 'A is at (5, 3)', right: 'A is at (3, 5)' }] },
    ],
    turn: {
      text: 'How far across is point A?',
      picture: grid(6, [{ x: 4, y: 2, label: 'A' }]),
      answer: 4, steps: ['Start at 0 in the corner.', 'Walk along the bottom until you are right under point A.', 'Point A is 4 across.'],
      prompt: 'Go along the bottom first, until you are right under the point.',
      hint1: 'Start at 0. Which way do you go first, across or up?',
      hint2: 'Move along the bottom until you are right under point A. Read the number there.',
      twin: { text: 'What is the second number of point B?',
        picture: grid(6, [{ x: 2, y: 5, label: 'B' }]),
        answer: 5, steps: ['The first number is how far across. The second number is how far up.', 'Go across until you are under point B, then go up to it.', 'Point B is 5 up, so the second number is 5.'],
        hint1: 'Is the second number the one across, or the one up?',
        hint2: 'Go across until you are under point B. Then count how far up it is.' },
    },
    won: { text: 'You went across first, then up.', sticker: 'A pair like (3, 5) is an ordered pair. The order matters: across first, then up.' },
    twinWon: { text: 'You found that point B is 5 up.', sticker: 'A pair like (3, 5) is an ordered pair. The order matters: across first, then up.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'How far across is point C?',
        picture: grid(6, [{ x: 5, y: 1, label: 'C' }]), answer: 5,
        steps: ['Start at 0 in the corner.', 'Walk along the bottom until you are right under point C.', 'Point C is 5 across.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'How far up is point D?',
        picture: grid(6, [{ x: 1, y: 4, label: 'D' }]), answer: 4,
        steps: ['Go across until you are right under point D.', 'Now count up to the point.', 'Point D is 4 up.'] } },
      { why: 'Still "across first, then up"', problem: { text: 'Which pair tells where point E is?',
        picture: grid(6, [{ x: 6, y: 2, label: 'E' }]), answer: { choices: ['(2, 6)', '(6, 2)'], correct: 1 },
        steps: ['Go across first: point E is 6 across.', 'Then go up: point E is 2 up.', 'Across comes first, so E is at (6, 2).'] } },
      { why: 'A little harder', problem: { text: 'What is the first number of point F?',
        picture: grid(10, [{ x: 7, y: 9, label: 'F' }, { x: 9, y: 7, label: 'G' }]), answer: 7,
        steps: ['The first number is how far across.', 'Go along the bottom until you are right under point F, not G.', 'F is 7 across, so the first number is 7.'] } },
      { why: 'Same math in a story', problem: { text: 'A bee lands on a garden grid at point B. Which pair tells where the bee is?',
        picture: grid(6, [{ x: 4, y: 3, label: 'B' }]), answer: { choices: ['(3, 4)', '(4, 3)', '(4, 4)'], correct: 1 },
        steps: ['Go across first: the bee is 4 across.', 'Then go up: the bee is 3 up.', 'So the bee is at (4, 3).'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m6-t2', title: 'Plot a point', skill: 'Find the spot on a grid for a pair of numbers',
    bigIdea: 'To find (4, 2), start at 0, go 4 across, then 2 up, and put the dot there.',
    screens: [
      { scene: 'g5m6-t2', title: 'Where does the flag go?', text: 'Your friend says, "Put the flag at (4, 2)." Where on the grid does it go?',
        pictures: [grid(6)] },
      { title: 'Two numbers, two moves', text: 'Look at all the spots on this grid. Which one is (4, 2)? The two numbers tell you, but only if you make the moves in the right order.',
        beats: [
          { say: 'Look at all the spots on this grid.', pic: 0 },
          { say: 'Which one is (4, 2)?' },
          { say: 'The two numbers tell you, but only if you make the moves in the right order.' },
        ],
        pictures: [grid(6)] },
      { title: 'The big idea', text: 'To find (4, 2), start at 0, go 4 across, then 2 up, and put the dot there.',
        beats: [
          { say: 'To find (4, 2), start at 0, go 4 across, then 2 up, and put the dot there.', pic: 0 },
        ],
        pictures: [grid(6)] },
      { title: 'Go 4 across', text: 'Put your finger on 0, right in the corner. The first number is 4, so slide along the bottom. One, two, three, four. Stop.',
        beats: [
          { say: 'Put your finger on 0, right in the corner.', pic: 0 },
          { say: 'The first number is 4, so slide along the bottom.' },
          { say: 'One, two, three, four. Stop.' },
        ],
        pictures: [grid(6, [], [{ a: [0, 0], b: [4, 0], dashed: true, tone: 2, label: '4 across' }], true)] },
      { title: 'Go 2 up', text: 'The second number is 2. So go straight up from where you stopped. One, two. Stop again.',
        beats: [
          { say: 'The second number is 2. So go straight up from where you stopped.', pic: 0 },
          { say: 'One, two. Stop again.' },
        ],
        pictures: [grid(6, [], [{ a: [0, 0], b: [4, 0], dashed: true, tone: 2 }, { a: [4, 0], b: [4, 2], dashed: true, label: '2 up' }], true)] },
      { title: 'Put the dot', text: "Now put your dot right where you stopped. That spot is (4, 2), and there's only one on the whole grid. The flag goes there.",
        beats: [
          { say: 'Now put your dot right where you stopped.', pic: 0 },
          { say: "That spot is (4, 2), and there's only one on the whole grid." },
          { say: 'The flag goes there.' },
        ],
        pictures: [grid(6, [{ x: 4, y: 2, label: '(4, 2)' }], [{ a: [0, 0], b: [4, 0], dashed: true, tone: 2 }, { a: [4, 0], b: [4, 2], dashed: true }], true)] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't go UP 4 first. That lands on (2, 4), a different spot. The first number always goes across. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't go UP 4 first. That lands on (2, 4), a different spot.", pic: 0 },
          { say: 'The first number always goes across.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '(4, 2): up 4, across 2', right: '(4, 2): across 4, up 2' }] },
    ],
    turn: {
      text: 'Which point is at (3, 1)?',
      picture: grid(6, [{ x: 1, y: 3, label: 'A' }, { x: 3, y: 1, label: 'B' }, { x: 3, y: 3, label: 'C' }]),
      answer: { choices: LETTERS3, correct: 1 }, steps: ['Start at 0. Go 3 across.', 'Then go 1 up.', 'The point there is B.'],
      prompt: 'Go across first, then up. Which point is there?',
      hint1: 'Which number tells you how far across?',
      hint2: 'Slide 3 across the bottom. Now go up just 1.',
      twin: { text: 'Which point is at (2, 5)?',
        picture: grid(6, [{ x: 5, y: 2, label: 'A' }, { x: 2, y: 4, label: 'B' }, { x: 2, y: 5, label: 'C' }]),
        answer: { choices: LETTERS3, correct: 2 }, steps: ['Start at 0. Go 2 across.', 'Then go 5 up.', 'The point there is C.'],
        hint1: 'Go across first. How far across do you go?',
        hint2: 'Slide 2 across the bottom. Then count up 5.' },
    },
    won: { text: 'You went across first, then up, and found the spot.', sticker: 'Putting a point on a grid is called plotting the point.' },
    twinWon: { text: 'You went 2 across and 5 up to find point C.', sticker: 'Putting a point on a grid is called plotting the point.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which point is at (4, 3)?',
        picture: grid(6, [{ x: 4, y: 3, label: 'A' }, { x: 3, y: 4, label: 'B' }, { x: 4, y: 4, label: 'C' }]), answer: { choices: LETTERS3, correct: 0 },
        steps: ['Start at 0. Go 4 across.', 'Then go 3 up.', 'The point there is A.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Which point is at (5, 1)?',
        picture: grid(6, [{ x: 1, y: 5, label: 'A' }, { x: 5, y: 5, label: 'B' }, { x: 5, y: 1, label: 'C' }]), answer: { choices: LETTERS3, correct: 2 },
        steps: ['Start at 0. Go 5 across.', 'Then go 1 up.', 'The point there is C.'] } },
      { why: 'Still "across first, then up"', problem: { text: 'Which point is at (0, 4)?',
        picture: grid(6, [{ x: 4, y: 0, label: 'A' }, { x: 0, y: 4, label: 'B' }, { x: 4, y: 4, label: 'C' }]), answer: { choices: LETTERS3, correct: 1 },
        steps: ['The first number is 0, so you do not go across at all.', 'Go 4 up the left side.', 'The point there is B.'] } },
      { why: 'A little harder', problem: { text: 'Which point is at (7, 8)?',
        picture: grid(10, [{ x: 8, y: 7, label: 'A' }, { x: 7, y: 8, label: 'B' }, { x: 7, y: 6, label: 'C' }, { x: 6, y: 8, label: 'D' }]),
        answer: { choices: ['A', 'B', 'C', 'D'], correct: 1 },
        steps: ['Start at 0. Go 7 across.', 'Then go 8 up.', 'The point there is B.'] } },
      { why: 'Same math in a story', problem: { text: 'Sam hides a toy on a game board grid at (6, 3). Which point is the toy?',
        picture: grid(8, [{ x: 6, y: 6, label: 'A' }, { x: 3, y: 6, label: 'B' }, { x: 6, y: 3, label: 'C' }]), answer: { choices: LETTERS3, correct: 2 },
        steps: ['Start at 0. Go 6 across.', 'Then go 3 up.', 'The toy is at point C.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m6-t3', title: 'Two number patterns', skill: 'Make two number patterns from two rules and compare them',
    bigIdea: 'Follow each rule one step at a time, then line the two patterns up and compare the numbers in each column.',
    screens: [
      { scene: 'g5m6-t3', title: 'Two piggy banks', text: 'Mia and Leo both start with 0 dollars. Each week Mia puts in 2 dollars and Leo puts in 6. How do their savings compare?',
        pictures: [pat(NTH.slice(0, 5), ['0', '?', '?', '?', '?'], ['0', '?', '?', '?', '?'])] },
      { title: 'A guess can fool you', text: "Is Leo always 4 dollars ahead? It's a fair guess, but no. He pulls further ahead every week.",
        beats: [
          { say: "Is Leo always 4 dollars ahead? It's a fair guess, but no.", pic: 0 },
          { say: 'He pulls further ahead every week.' },
        ],
        pictures: [pat(NTH.slice(0, 5), ['0', '?', '?', '?', '?'], ['0', '?', '?', '?', '?'])] },
      { title: 'The big idea', text: 'Follow each rule one step at a time, then line the two patterns up and compare the numbers in each column.',
        beats: [
          { say: 'Follow each rule one step at a time, then line the two patterns up and compare the numbers in each column.', pic: 0 },
        ],
        pictures: [pat(NTH.slice(0, 5), ['0', '?', '?', '?', '?'], ['0', '?', '?', '?', '?'])] },
      { title: 'Follow the first rule', text: 'Mia first. She starts at 0 and adds 2 every week. So, 2, 4, 6, 8.',
        beats: [
          { say: 'Mia first.', pic: 0 },
          { say: 'She starts at 0 and adds 2 every week.' },
          { say: 'So, 2, 4, 6, 8.' },
        ],
        pictures: [pat(NTH.slice(0, 5), ['0', '2', '4', '6', '8'], ['0', '?', '?', '?', '?'], [[0, 2], [0, 3], [0, 4], [0, 5]], true)] },
      { title: 'Follow the second rule', text: 'Now Leo. Same start, but he adds 6 every week. So he has 6, 12, 18, then 24.',
        beats: [
          { say: 'Now Leo. Same start, but he adds 6 every week.', pic: 0 },
          { say: 'So he has 6, 12, 18, then 24.' },
        ],
        pictures: [pat(NTH.slice(0, 5), ['0', '2', '4', '6', '8'], ['0', '6', '12', '18', '24'], [[1, 2], [1, 3], [1, 4], [1, 5]], true)] },
      { title: 'Line them up', text: "Now look straight down each column. 2 and 6. 4 and 12. 6 and 18. Each of Leo's numbers is 3 times Mia's.",
        beats: [
          { say: 'Now look straight down each column.', pic: 0 },
          { say: '2 and 6. 4 and 12. 6 and 18.' },
          { say: "Each of Leo's numbers is 3 times Mia's.", pic: 1 },
        ],
        pictures: [pat(NTH.slice(0, 5), ['0', '2', '4', '6', '8'], ['0', '6', '12', '18', '24'], [[0, 3], [1, 3]]),
          { kind: 'eq', text: '2 × 3 = 6', lines: ['4 × 3 = 12', '6 × 3 = 18'] }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't say Leo always has 4 MORE. 6 − 2 is 4, but 12 − 4 is 8. What stays the same is 3 times as much. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't say Leo always has 4 MORE.", pic: 0 },
          { say: '6 − 2 is 4, but 12 − 4 is 8. What stays the same is 3 times as much.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: 'always 4 more', right: 'always 3 times as much' }] },
    ],
    turn: {
      text: 'Pattern A: start at 0, add 2. Pattern B: start at 0, add 8. What is the 5th number in pattern B?',
      picture: pat(NTH.slice(0, 5), ['0', '2', '4', '6', '8'], ['0', '?', '?', '?', '?']),
      answer: 32, steps: ['Pattern B starts at 0 and adds 8 each time.', 'Count on: 0, 8, 16, 24, then add one more 8.', 'So the 5th number is 32.'],
      prompt: 'Start at 0. Follow the rule one step at a time.',
      hint1: 'What is the first number in pattern B? What do you add each time?',
      hint2: 'Start at 0 and add 8 four times, once for each new number.',
      twin: { text: 'Pattern A: start at 0, add 2. Pattern B: start at 0, add 10. Each number in pattern B is how many times the number above it in pattern A?',
        picture: pat(NTH.slice(0, 5), ['0', '2', '4', '6', '8'], ['0', '10', '20', '30', '40']),
        answer: 5, steps: ['Line them up: 2 and 10, 4 and 20, 6 and 30.', '2 × 5 = 10, 4 × 5 = 20 and 6 × 5 = 30.', 'So each number in pattern B is 5 times the number in pattern A.'],
        hint1: 'Look down one column, like 2 and 10. What do you multiply 2 by to get 10?',
        hint2: 'Check another column too, like 4 and 20. Is it the same times?' },
    },
    won: { text: 'You followed both rules, one step at a time.', sticker: 'Each number in a pattern is called a term. The rule tells you how to get the next term.' },
    twinWon: { text: 'You lined up the two patterns and found 5 times as much.', sticker: 'Each number in a pattern is called a term. The rule tells you how to get the next term.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Pattern A: start at 0, add 2. Pattern B: start at 0, add 4. What is the 5th number in pattern B?',
        picture: pat(NTH.slice(0, 5), ['0', '2', '4', '6', '8'], ['0', '?', '?', '?', '?']), answer: 16,
        steps: ['Pattern B starts at 0 and adds 4 each time.', 'Count on: 0, 4, 8, 12, then add one more 4.', 'So the 5th number is 16.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Pattern A: start at 0, add 3. Pattern B: start at 0, add 9. What is the 4th number in pattern B?',
        picture: pat(NTH.slice(0, 4), ['0', '3', '6', '9'], ['0', '?', '?', '?']), answer: 27,
        steps: ['Pattern B starts at 0 and adds 9 each time.', 'Count on: 0, 9, 18, then add one more 9.', 'So the 4th number is 27.'] } },
      { why: 'Still "line them up"', problem: { text: 'Pattern A: start at 0, add 4. Pattern B: start at 0, add 12. Each number in pattern B is how many times the number in pattern A?',
        picture: pat(NTH.slice(0, 5), ['0', '4', '8', '12', '16'], ['0', '12', '24', '36', '48']), answer: 3,
        steps: ['Line them up: 4 and 12, 8 and 24.', '4 × 3 = 12 and 8 × 3 = 24.', 'So each number in pattern B is 3 times the number in pattern A.'] } },
      { why: 'A little harder', problem: { text: 'Pattern A: start at 0, add 5. Pattern B: start at 0, add 10. What is the 6th number in pattern B?',
        picture: pat(NTH, ['0', '5', '10', '15', '20', '25'], ['0', '?', '?', '?', '?', '?']), answer: 50,
        steps: ['Pattern B starts at 0 and adds 10 each time.', 'Count on: 0, 10, 20, 30, 40, then add one more 10.', 'So the 6th number is 50.'] } },
      { why: 'Same math in a story', problem: { text: 'Ava and Ben both start at 0 pages. Each day Ava reads 3 pages and Ben reads 6 pages. How many pages has Ben read after day 4?',
        picture: { kind: 'table', head: ['Day', '0', '1', '2', '3', '4'], rows: [['Ava', '0', '3', '6', '9', '12'], ['Ben', '0', '6', '?', '?', '?']], rowHead: true },
        answer: 24,
        steps: ['Ben starts at 0 and adds 6 pages each day.', 'Day 1, 2, 3: 6, 12, 18.', 'Add 6 more for day 4, so Ben has read 24 pages.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m6-t4', title: 'Graph the pattern pairs', skill: 'Turn two patterns into pairs and plot them as points',
    bigIdea: 'Each column gives one pair: the top number goes across, and the bottom number goes up.',
    screens: [
      { scene: 'g5m6-t4', title: 'Two patterns', text: 'Pattern A: start at 0, add 1. Pattern B: start at 0, add 2. What do the two patterns look like on a grid?',
        pictures: [pat(NTH.slice(0, 4), ['0', '1', '2', '3'], ['0', '2', '4', '6'])] },
      { title: 'Lists are not dots', text: 'Pattern A is 0, 1, 2, 3. Pattern B is 0, 2, 4, 6. But a grid does not take lists. Where would a dot go? Every dot needs two numbers, one across and one up.',
        beats: [
          { say: 'Pattern A is 0, 1, 2, 3. Pattern B is 0, 2, 4, 6.', pic: 0 },
          { say: 'But a grid does not take lists. Where would a dot go?', pic: 1 },
          { say: 'Every dot needs two numbers, one across and one up.' },
        ],
        pictures: [pat(NTH.slice(0, 4), ['0', '1', '2', '3'], ['0', '2', '4', '6']), grid(8)] },
      { title: 'The big idea', text: 'Each column gives one pair: the top number goes across, and the bottom number goes up.',
        beats: [
          { say: 'Each column gives one pair: the top number goes across, and the bottom number goes up.', pic: 0 },
        ],
        pictures: [pat(NTH.slice(0, 4), ['0', '1', '2', '3'], ['0', '2', '4', '6'])] },
      { title: 'Make the pairs', text: 'Read straight down each column. 0 and 0. 1 and 2. 2 and 4. 3 and 6. 4 columns, so 4 pairs.',
        beats: [
          { say: 'Read straight down each column.', pic: 0 },
          { say: '0 and 0. 1 and 2. 2 and 4. 3 and 6.', pic: 1 },
          { say: '4 columns, so 4 pairs.' },
        ],
        pictures: [pat(NTH.slice(0, 4), ['0', '1', '2', '3'], ['0', '2', '4', '6'], [[0, 3], [1, 3]], true),
          { kind: 'eq', text: '(0, 0)   (1, 2)   (2, 4)   (3, 6)' }] },
      { title: 'Plot each pair', text: 'Now take the pairs to the grid. Take (1, 2). Go 1 across, then 2 up, and put a dot. Do the same for (0, 0), (2, 4) and (3, 6).',
        beats: [
          { say: 'Now take the pairs to the grid.', pic: 0 },
          { say: 'Take (1, 2). Go 1 across, then 2 up, and put a dot.' },
          { say: 'Do the same for (0, 0), (2, 4) and (3, 6).' },
        ],
        pictures: [grid(8, [{ x: 0, y: 0 }, { x: 1, y: 2 }, { x: 2, y: 4 }, { x: 3, y: 6 }], [], true)] },
      { title: 'See the pattern', text: 'Look at the four dots. What do you notice? They sit on one straight line, climbing to the right. Every 1 step across, they go 2 steps up.',
        beats: [
          { say: 'Look at the four dots. What do you notice?', pic: 0 },
          { say: 'They sit on one straight line, climbing to the right.' },
          { say: 'Every 1 step across, they go 2 steps up.' },
        ],
        pictures: [grid(8, [{ x: 0, y: 0 }, { x: 1, y: 2 }, { x: 2, y: 4 }, { x: 3, y: 6 }], [{ a: [0, 0], b: [3, 6], extend: true, dashed: true }])] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't write the bottom number FIRST. 1 and 2 make (1, 2), not (2, 1). Those are two different dots. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't write the bottom number FIRST.", pic: 0 },
          { say: '1 and 2 make (1, 2), not (2, 1). Those are two different dots.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '1 and 2 make (2, 1)', right: '1 and 2 make (1, 2)' }] },
    ],
    turn: {
      text: 'Pattern A: start at 0, add 1. Pattern B: start at 0, add 3. Pattern A goes across. When the dot is 2 across, how far up is it?',
      picture: pat(NTH.slice(0, 4), ['0', '1', '2', '3'], ['0', '3', '?', '?']),
      answer: 6, steps: ['Find the column where pattern A is 2. It is the 3rd column.', 'Pattern B in that column: 0, 3, then add 3 more.', 'The pair is (2, 6), so the dot is 6 up.'],
      prompt: 'Find the column. The bottom number tells how far up.',
      hint1: 'Find the column where pattern A is 2.',
      hint2: 'Follow pattern B to that column: start at 0 and add 3 each step.',
      twin: { text: 'Pattern A: start at 0, add 2. Pattern B: start at 0, add 4. Which pair is a dot on this graph?',
        picture: pat(NTH.slice(0, 3), ['0', '2', '4'], ['0', '4', '8']),
        answer: { choices: ['(4, 2)', '(2, 4)', '(2, 6)'], correct: 1 },
        steps: ['Take one column: pattern A has 2 and pattern B has 4.', 'Pattern A goes across, and pattern B goes up.', 'So the dot is at (2, 4).'],
        hint1: 'Pick one column. Which number comes from pattern A?',
        hint2: 'The number from pattern A goes first, because it tells how far across.' },
    },
    won: { text: 'You made a pair from each column and put the dot in the right spot.', sticker: 'The line along the bottom is the x-axis. The line up the side is the y-axis.' },
    twinWon: { text: 'You made the pair (2, 4) with pattern A going across.', sticker: 'The line along the bottom is the x-axis. The line up the side is the y-axis.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Pattern A: start at 0, add 1. Pattern B: start at 0, add 4. Pattern A goes across. When the dot is 2 across, how far up is it?',
        picture: pat(NTH.slice(0, 4), ['0', '1', '2', '3'], ['0', '4', '?', '?']), answer: 8,
        steps: ['Pattern A is 2 in the 3rd column.', 'Pattern B in that column: 0, 4, then add 4 more.', 'The pair is (2, 8), so the dot is 8 up.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Pattern A: start at 0, add 2. Pattern B: start at 0, add 3. Pattern A goes across. When the dot is 6 across, how far up is it?',
        picture: pat(NTH.slice(0, 4), ['0', '2', '4', '6'], ['0', '3', '?', '?']), answer: 9,
        steps: ['Pattern A is 6 in the 4th column.', 'Pattern B in that column: 0, 3, 6, then add 3 more.', 'The pair is (6, 9), so the dot is 9 up.'] } },
      { why: 'Still "top across, bottom up"', problem: { text: 'Pattern A: start at 0, add 1. Pattern B: start at 0, add 5. Which pair is a dot on this graph?',
        picture: pat(NTH.slice(0, 3), ['0', '1', '2'], ['0', '5', '10']), answer: { choices: ['(5, 1)', '(1, 5)', '(1, 1)'], correct: 1 },
        steps: ['Take the 2nd column: pattern A has 1 and pattern B has 5.', 'Pattern A goes across, and pattern B goes up.', 'So the dot is at (1, 5).'] } },
      { why: 'A little harder', problem: { text: 'These dots come from two patterns that both start at 0. Each dot is 1 more across than the one before. The next dot is 4 across. How far up is it?',
        picture: grid(10, [{ x: 0, y: 0 }, { x: 1, y: 2 }, { x: 2, y: 4 }, { x: 3, y: 6 }]), answer: 8,
        steps: ['Read the dots: 0 up, 2 up, 4 up, 6 up. Each dot is 2 more up.', 'The last dot is 3 across and 6 up. Go 1 more across and 2 more up.', 'So the next dot is 8 up.'] } },
      { why: 'Same math in a story', problem: { text: 'Every box holds 4 crayons. Pattern A counts boxes: start at 0, add 1. Pattern B counts crayons: start at 0, add 4. On the graph, how far up is the dot for 3 boxes?',
        picture: pat(NTH.slice(0, 4), ['0', '1', '2', '3'], ['0', '4', '?', '?']), answer: 12,
        steps: ['Pattern B adds 4 crayons for each box: 0, 4, 8, then add 4 more.', 'The pair for 3 boxes is 3 across and 12 up.', 'So the dot is 12 up.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m6-t5', title: 'Distance along a grid line', skill: 'Find how far apart two points are when they share a number',
    bigIdea: 'When two points share a number, they sit on one straight line, so subtract the other two numbers.',
    screens: [
      { scene: 'g5m6-t5', title: 'A walk in the park', text: 'A path runs straight across a park grid. A bench is at point A and a tree is at point B. How many units apart are they?',
        pictures: [grid(8, [{ x: 2, y: 3, label: 'A' }, { x: 7, y: 3, label: 'B' }])] },
      { title: 'Counting is slow', text: "You could count every step from the bench to the tree. That works, but on a big grid it takes ages, and it's easy to lose count. Is there a faster way? Yes.",
        beats: [
          { say: 'You could count every step from the bench to the tree.', pic: 0 },
          { say: "That works, but on a big grid it takes ages, and it's easy to lose count." },
          { say: 'Is there a faster way? Yes.' },
        ],
        pictures: [grid(8, [{ x: 2, y: 3, label: 'A' }, { x: 7, y: 3, label: 'B' }])] },
      { title: 'The big idea', text: 'When two points share a number, they sit on one straight line, so subtract the other two numbers.',
        beats: [
          { say: 'When two points share a number, they sit on one straight line, so subtract the other two numbers.', pic: 0 },
        ],
        pictures: [grid(8, [{ x: 2, y: 3, label: 'A' }, { x: 7, y: 3, label: 'B' }])] },
      { title: 'Find the number they share', text: 'Point A is at (2, 3), and point B is at (7, 3). Look at the second numbers. Both are 3. So the two points sit on one straight line, going across.',
        beats: [
          { say: 'Point A is at (2, 3), and point B is at (7, 3).', pic: 0 },
          { say: 'Look at the second numbers. Both are 3.', pic: 1 },
          { say: 'So the two points sit on one straight line, going across.' },
        ],
        pictures: [grid(8, [{ x: 2, y: 3, label: 'A' }, { x: 7, y: 3, label: 'B' }], [{ a: [2, 3], b: [7, 3], dashed: true }], true),
          { kind: 'eq', text: 'A (2, 3)', lines: ['B (7, 3)'] }] },
      { title: 'Subtract the other numbers', text: 'Which numbers are different? The first ones, 2 and 7. Take the smaller from the bigger. 7 − 2 = 5. So they are 5 units apart.',
        beats: [
          { say: 'Which numbers are different? The first ones, 2 and 7.', pic: 0 },
          { say: 'Take the smaller from the bigger. 7 − 2 = 5.', pic: 1 },
          { say: 'So they are 5 units apart.' },
        ],
        pictures: [grid(8, [{ x: 2, y: 3, label: 'A' }, { x: 7, y: 3, label: 'B' }], [{ a: [2, 3], b: [7, 3], tone: 2, label: '5' }], true),
          { kind: 'eq', text: '7 − 2 = 5' }] },
      { title: 'Check by counting', text: "Let's check by counting, just this once. One, two, three, four, five steps along the line. Yes, 5 units apart.",
        beats: [
          { say: "Let's check by counting, just this once.", pic: 0 },
          { say: 'One, two, three, four, five steps along the line.' },
          { say: 'Yes, 5 units apart.' },
        ],
        pictures: [grid(8, [{ x: 2, y: 3, label: 'A' }, { x: 7, y: 3, label: 'B' }], [{ a: [2, 3], b: [7, 3], tone: 2, label: '5 units' }])] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't subtract the numbers that MATCH. 3 − 3 is 0, but the points are not 0 apart. Subtract the numbers that are different. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't subtract the numbers that MATCH.", pic: 0 },
          { say: '3 − 3 is 0, but the points are not 0 apart. Subtract the numbers that are different.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '3 − 3 = 0 apart', right: '7 − 2 = 5 apart' }] },
    ],
    turn: {
      text: 'Point A is at (1, 4). Point B is at (8, 4). How many units apart are they?',
      picture: grid(10, [{ x: 1, y: 4, label: 'A' }, { x: 8, y: 4, label: 'B' }]),
      answer: 7, steps: ['Both points are 4 up, so they are on the same line going across.', 'Subtract the numbers across: 8 − 1.', 'So they are 7 units apart.'],
      prompt: 'Find the number they share. Subtract the other two.',
      hint1: 'Which number is the same for both points?',
      hint2: 'Both are 4 up. Now subtract the numbers across.',
      twin: { text: 'Point C is at (3, 2). Point D is at (3, 8). How many units apart are they?',
        picture: grid(10, [{ x: 3, y: 2, label: 'C' }, { x: 3, y: 8, label: 'D' }]),
        answer: 6, steps: ['Both points are 3 across, so they are on the same line going up.', 'Subtract the numbers up: 8 − 2.', 'So they are 6 units apart.'],
        hint1: 'This time the numbers across match. Which numbers are different?',
        hint2: 'Subtract the smaller number up from the bigger one.' },
    },
    won: { text: 'You found the number they share and subtracted the other two.', sticker: 'In (3, 8), 3 is the x-coordinate and 8 is the y-coordinate.' },
    twinWon: { text: 'You subtracted 8 − 2 and found they are 6 units apart.', sticker: 'In (3, 8), 3 is the x-coordinate and 8 is the y-coordinate.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Point A is at (2, 5). Point B is at (9, 5). How many units apart are they?',
        picture: grid(10, [{ x: 2, y: 5, label: 'A' }, { x: 9, y: 5, label: 'B' }]), answer: 7,
        steps: ['Both points are 5 up.', 'Subtract the numbers across: 9 − 2.', 'So they are 7 units apart.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Point E is at (4, 1). Point F is at (4, 6). How many units apart are they?',
        picture: grid(10, [{ x: 4, y: 1, label: 'E' }, { x: 4, y: 6, label: 'F' }]), answer: 5,
        steps: ['Both points are 4 across.', 'Subtract the numbers up: 6 − 1.', 'So they are 5 units apart.'] } },
      { why: 'Still "subtract the numbers that differ"', problem: { text: 'Point G is at (6, 3). Point H is at (0, 3). How many units apart are they?',
        picture: grid(10, [{ x: 6, y: 3, label: 'G' }, { x: 0, y: 3, label: 'H' }]), answer: 6,
        steps: ['Both points are 3 up, so the 3s are not subtracted.', 'The numbers across are 6 and 0: 6 − 0.', 'So they are 6 units apart.'] } },
      { why: 'A little harder', problem: { text: 'Point P is at (2, 4). Point Q is 6 units to the right of P. What is the first number of point Q?',
        picture: grid(10, [{ x: 2, y: 4, label: 'P' }]), answer: 8,
        steps: ['Moving right changes only the number across. The 4 up stays the same.', 'Add 6 to the number across: 2 + 6.', 'So Q is at (8, 4), and its first number is 8.'] } },
      { why: 'Same math in a story', problem: { text: 'A fence post is at (3, 6) and another post is at (10, 6). Each unit is 1 meter. How many meters apart are the posts?',
        picture: grid(10, [{ x: 3, y: 6, label: 'A' }, { x: 10, y: 6, label: 'B' }]), answer: 7,
        steps: ['Both posts are 6 up, so they are on the same line going across.', 'Subtract the numbers across: 10 − 3.', 'So the posts are 7 meters apart.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g5m6-t6', title: 'Maps on a grid', skill: 'Use a grid map to find places and count blocks between them',
    bigIdea: 'Every place on the map has a pair, across then up, and along one straight street you subtract to count the blocks.',
    screens: [
      { scene: 'g5m6-t6', title: 'Your town map', text: 'This town map is a grid, and each line is a street. How many blocks is it from the school to the park?',
        pictures: [grid(10, [{ x: 2, y: 3, label: 'School' }, { x: 2, y: 8, label: 'Park' }, { x: 6, y: 1, label: 'Library' }])] },
      { title: 'Easy to lose count', text: "You could trace the street with your finger and count the blocks. But on a busy map, it's easy to skip a block, or count one twice. Is there a surer way? Yes.",
        beats: [
          { say: 'You could trace the street with your finger and count the blocks.', pic: 0 },
          { say: "But on a busy map, it's easy to skip a block, or count one twice." },
          { say: 'Is there a surer way? Yes.' },
        ],
        pictures: [grid(10, [{ x: 2, y: 3, label: 'School' }, { x: 2, y: 8, label: 'Park' }, { x: 6, y: 1, label: 'Library' }])] },
      { title: 'The big idea', text: 'Every place on the map has a pair, across then up, and along one straight street you subtract to count the blocks.',
        beats: [
          { say: 'Every place on the map has a pair, across then up, and along one straight street you subtract to count the blocks.', pic: 0 },
        ],
        pictures: [grid(10, [{ x: 2, y: 3, label: 'School' }, { x: 2, y: 8, label: 'Park' }, { x: 6, y: 1, label: 'Library' }])] },
      { title: 'Name the places', text: 'Go across first, then up, like always. The school is at (2, 3). The park is at (2, 8), straight above it.',
        beats: [
          { say: 'Go across first, then up, like always.', pic: 0 },
          { say: 'The school is at (2, 3).' },
          { say: 'The park is at (2, 8), straight above it.', pic: 1 },
        ],
        pictures: [grid(10, [{ x: 2, y: 3, label: 'School' }, { x: 2, y: 8, label: 'Park' }], [], true),
          { kind: 'eq', text: 'School (2, 3)', lines: ['Park (2, 8)'] }] },
      { title: 'Walk the street', text: 'Both are 2 across, so one straight street joins them. Subtract the numbers going up. 8 − 3 = 5. So the park is 5 blocks away.',
        beats: [
          { say: 'Both are 2 across, so one straight street joins them.', pic: 0 },
          { say: 'Subtract the numbers going up. 8 − 3 = 5.' },
          { say: 'So the park is 5 blocks away.' },
        ],
        pictures: [grid(10, [{ x: 2, y: 3, label: 'School' }, { x: 2, y: 8, label: 'Park' }], [{ a: [2, 3], b: [2, 8], tone: 2, label: '5 blocks' }], true)] },
      { title: 'Find a place', text: "Now turn it around. What is at (6, 1)? Go 6 across, then 1 up. It's the library.",
        beats: [
          { say: 'Now turn it around. What is at (6, 1)?', pic: 0 },
          { say: 'Go 6 across, then 1 up.' },
          { say: "It's the library." },
        ],
        pictures: [grid(10, [{ x: 6, y: 1, label: 'Library' }], [{ a: [0, 0], b: [6, 0], dashed: true, tone: 2 }, { a: [6, 0], b: [6, 1], dashed: true }], true)] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't count the CORNERS you pass. From 3 up to 8 up, count the blocks between them. That's 5, not 6. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't count the CORNERS you pass.", pic: 0 },
          { say: "From 3 up to 8 up, count the blocks between them. That's 5, not 6." },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '3, 4, 5, 6, 7, 8: 6 blocks', right: '8 − 3 = 5 blocks' }] },
    ],
    turn: {
      text: 'On the map, the school is at (2, 3) and the pool is at (2, 9). How many blocks apart are they?',
      picture: grid(10, [{ x: 2, y: 3, label: 'School' }, { x: 2, y: 9, label: 'Pool' }]),
      answer: 6, steps: ['Both places are 2 across, so one straight street joins them.', 'Subtract the numbers up: 9 − 3.', 'So they are 6 blocks apart.'],
      prompt: 'Find the number they share. Subtract the other two.',
      hint1: 'Which number is the same for both places?',
      hint2: 'Both are 2 across. Subtract the numbers up.',
      twin: { text: 'Which place is at (5, 4)?',
        picture: grid(10, [{ x: 4, y: 5, label: 'Shop' }, { x: 5, y: 4, label: 'Farm' }, { x: 5, y: 1, label: 'Zoo' }]),
        answer: { choices: ['Shop', 'Farm', 'Zoo'], correct: 1 },
        steps: ['Start at 0. Go 5 across.', 'Then go 4 up.', 'The place there is the Farm.'],
        hint1: 'Go across first. How far across do you go?',
        hint2: 'Go 5 across, then count up 4. Which place is there?' },
    },
    won: { text: 'You found the places by their pairs and counted the blocks.', sticker: 'The corner of the grid where you start, at 0 across and 0 up, is called the origin.' },
    twinWon: { text: 'You went 5 across and 4 up to find the Farm.', sticker: 'The corner of the grid where you start is called the origin.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'The school is at (4, 2) and the store is at (4, 7). How many blocks apart are they?',
        picture: grid(10, [{ x: 4, y: 2, label: 'School' }, { x: 4, y: 7, label: 'Store' }]), answer: 5,
        steps: ['Both places are 4 across.', 'Subtract the numbers up: 7 − 2.', 'So they are 5 blocks apart.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'The bakery is at (1, 5) and the bank is at (8, 5). How many blocks apart are they?',
        picture: grid(10, [{ x: 1, y: 5, label: 'Bakery' }, { x: 8, y: 5, label: 'Bank' }]), answer: 7,
        steps: ['Both places are 5 up.', 'Subtract the numbers across: 8 − 1.', 'So they are 7 blocks apart.'] } },
      { why: 'Still "across first, then up"', problem: { text: 'Which place is at (3, 6)?',
        picture: grid(10, [{ x: 6, y: 3, label: 'Park' }, { x: 3, y: 6, label: 'Pond' }, { x: 3, y: 3, label: 'Barn' }]),
        answer: { choices: ['Park', 'Pond', 'Barn'], correct: 1 },
        steps: ['Start at 0. Go 3 across.', 'Then go 6 up.', 'The place there is the Pond.'] } },
      { why: 'A little harder', problem: { text: 'Home is at (2, 2), the store is at (2, 6) and the park is at (7, 6). You walk from home to the store, then on to the park. How many blocks do you walk?',
        picture: grid(10, [{ x: 2, y: 2, label: 'Home' }, { x: 2, y: 6, label: 'Store' }, { x: 7, y: 6, label: 'Park' }]), answer: 9,
        steps: ['Home to the store: both are 2 across, so 6 − 2 = 4 blocks.', 'Store to the park: both are 6 up, so 7 − 2 = 5 blocks.', '4 + 5 = 9, so you walk 9 blocks.'] } },
      { why: 'Same math in a story', problem: { text: 'Jay rides his bike from the library at (3, 8) to the pool at (3, 2). Each unit is one block. How many blocks does he ride?',
        picture: grid(10, [{ x: 3, y: 8, label: 'Library' }, { x: 3, y: 2, label: 'Pool' }]), answer: 6,
        steps: ['Both places are 3 across, so one straight street joins them.', 'Subtract the numbers up: 8 − 2.', 'So Jay rides 6 blocks.'] } },
    ],
  },
]

attachChalk(G5M6, G5M6_CHALK)
