/**
 * Grade 6 · Module 1 — Ratios, rates and proportions.
 * Written to docs/new-flow/AUTHORING.md.
 */
import type { Lesson, Picture } from '../script'
import { attachChalk } from '../chalk'
import { G6M1_CHALK } from './chalk/g6m1'

type TapeRow = Extract<Picture, { kind: 'tape' }>['rows'][number]

/** A tape row of `n` equal cells. */
const row = (label: string, n: number, shade = false, text?: string, brace?: string): TapeRow =>
  ({ label, cells: Array.from({ length: n }, () => ({ w: 1, shade, text })), brace })
const tape = (rows: TapeRow[], motion = false): Picture => ({ kind: 'tape', rows, motion })
/** One unlabeled row of `n` equal cells under a brace (a total split into equal parts). */
const split = (n: number, brace: string, text?: string, motion = false): Picture =>
  ({ kind: 'tape', rows: [{ cells: Array.from({ length: n }, () => ({ w: 1, text })), brace }], motion })
/** A table whose first cell of each row is its name. */
const table = (rows: string[][], head?: string[], mark?: [number, number][], motion = false): Picture =>
  ({ kind: 'table', head, rows, rowHead: true, mark, motion })
/** A trip as a number line: `hours` equal gaps, only the ends labeled. */
const trip = (miles: number, gaps: number): Picture => ({ kind: 'numline', min: 0, max: miles, ticks: gaps, labels: 'ends' })

export const G6M1: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m1-t1', title: 'What a ratio is', skill: 'Describe a ratio part to part and part to whole',
    bigIdea: "Compare a part to a part, like 3 red to 2 blue, or a part to the whole, like 3 red out of 5 beads.",
    screens: [
      { title: 'Beads on a bracelet', text: 'A bracelet repeats the same set again and again: 3 red beads, then 2 blue beads. How can you describe the beads?',
        pictures: [tape([row('Red', 3, true), row('Blue', 2)])] },
      { title: '"3 and 2" is not enough', text: "A friend says the beads are 3 and 2. Which number is red? You can't tell. And does a number count one color, or all the beads?",
        beats: [
          { say: "A friend says the beads are 3 and 2.", pic: 0 },
          { say: "Which number is red? You can't tell." },
          { say: "And does a number count one color, or all the beads?" },
        ],
        pictures: [tape([row('Red', 3, true), row('Blue', 2)])] },
      { title: "The big idea", text: "Compare a part to a part, like 3 red to 2 blue, or a part to the whole, like 3 red out of 5 beads.",
        beats: [
          { say: "Compare a part to a part, like 3 red to 2 blue, or a part to the whole, like 3 red out of 5 beads.", pic: 0 },
        ],
        pictures: [tape([row('Red', 3, true), row('Blue', 2)])] },
      { title: "Part to part", text: "Look. Red beads on top, blue beads underneath. For every 3 red, there are 2 blue. We say 3 to 2. We write it with two dots: 3 : 2.",
        beats: [
          { say: "Look. Red beads on top, blue beads underneath.", pic: 0 },
          { say: "For every 3 red, there are 2 blue." },
          { say: "We say 3 to 2. We write it with two dots: 3 : 2.", pic: 1 },
        ],
        pictures: [tape([row('Red', 3, true), row('Blue', 2)], true), { kind: 'eq', text: 'red to blue = 3 : 2' }] },
      { title: "Part to whole", text: "Now put both colors in one line. How many beads are in one set? 3 + 2 is 5. So 3 out of every 5 beads are red.",
        beats: [
          { say: "Now put both colors in one line.", pic: 0 },
          { say: "How many beads are in one set? 3 + 2 is 5." },
          { say: "So 3 out of every 5 beads are red.", pic: 1 },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 1, shade: true }, { w: 1, shade: true }, { w: 1, shade: true }, { w: 1 }, { w: 1 }], brace: '5 beads' }], motion: true },
          { kind: 'eq', text: 'red out of all = 3 out of 5' }] },
      { title: "Order matters", text: "Wait. The order of the words sets the order of the numbers. Red to blue is 3 : 2. Blue to red is 2 : 3.",
        beats: [
          { say: "Wait. The order of the words sets the order of the numbers.", pic: 0 },
          { say: "Red to blue is 3 : 2.", pic: 1 },
          { say: "Blue to red is 2 : 3." },
        ],
        pictures: [tape([row('Red', 3, true), row('Blue', 2)]), { kind: 'eq', text: 'red to blue = 3 : 2', lines: ['blue to red = 2 : 3'] }] },
      { title: "One thing not to do", text: "Here's the part people mix up. When the question asks about ALL the beads, the answer is not 3 : 2. Count both colors. Red is 3 out of 5. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "When the question asks about ALL the beads, the answer is not 3 : 2.", pic: 0 },
          { say: "Count both colors. Red is 3 out of 5." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: 'red out of all beads: 3 : 2', right: 'red out of all beads: 3 out of 5' }] },
    ],
    turn: {
      text: 'A bracelet pattern has 4 green beads for every 3 yellow beads. Green beads are 4 out of every how many beads?',
      picture: tape([row('Green', 4, true), row('Yellow', 3)]),
      answer: 7,
      steps: ['The question compares green beads to all the beads in one set.', 'One set has 4 green and 3 yellow beads: 4 + 3.', 'So green beads are 4 out of every 7 beads.'],
      prompt: 'The whole means every bead in one set, both colors.',
      hint1: 'Does the question ask about one color, or all the beads?',
      hint2: 'Put the green beads and the yellow beads of one set together.',
      twin: { text: 'A snack mix has 5 pretzels for every 4 crackers. Crackers are 4 out of every how many pieces?',
        picture: tape([row('Pretzels', 5), row('Crackers', 4, true)]),
        answer: 9,
        steps: ['The question compares crackers to all the pieces in one set.', 'One set has 5 pretzels and 4 crackers: 5 + 4.', 'So crackers are 4 out of every 9 pieces.'],
        hint1: 'Does the question ask about one snack, or all the pieces?',
        hint2: 'Put the pretzels and the crackers of one set together.' },
    },
    won: { text: 'You compared one part to the whole set.', sticker: 'A comparison like 4 : 3 is called a ratio. It can compare part to part, or part to whole.' },
    twinWon: { text: 'You added 5 pretzels and 4 crackers: crackers are 4 out of every 9 pieces.', sticker: 'A comparison like 5 : 4 is called a ratio. It can compare part to part, or part to whole.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A bracelet pattern has 2 red beads for every 5 white beads. Red beads are 2 out of every how many beads?',
        picture: tape([row('Red', 2, true), row('White', 5)]), answer: 7,
        steps: ['The whole is every bead in one set.', 'One set has 2 red and 5 white beads: 2 + 5.', 'So red beads are 2 out of every 7 beads.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A floor pattern has 6 blue tiles for every 3 gray tiles. Gray tiles are 3 out of every how many tiles?',
        picture: tape([row('Blue', 6), row('Gray', 3, true)]), answer: 9,
        steps: ['The whole is every tile in one set.', 'One set has 6 blue and 3 gray tiles: 6 + 3.', 'So gray tiles are 3 out of every 9 tiles.'] } },
      { why: 'Still "the order matters"', problem: { text: 'A flag has 3 white stripes and 4 blue stripes. What number goes where the ? is?',
        picture: { kind: 'eq', text: 'blue to white = ? : 3' }, answer: 4,
        steps: ['Blue to white means the blue number comes first.', 'There are 4 blue stripes and 3 white stripes.', 'So blue to white is 4 : 3, and the missing number is 4.'] } },
      { why: 'A little harder', problem: { text: 'Every scoop of trail mix has 3 nuts, 2 raisins and 4 seeds. Raisins are 2 out of every how many pieces?',
        picture: tape([row('Nuts', 3), row('Raisins', 2, true), row('Seeds', 4)]), answer: 9,
        steps: ['The whole is every piece in one scoop, all three kinds.', 'Add all three parts: 3 + 2 + 4.', 'So raisins are 2 out of every 9 pieces.'] } },
      { why: 'Same math in a story', problem: { text: 'A marching band has 8 drummers for every 5 trumpet players. Drummers are 8 out of every how many players?',
        picture: tape([row('Drums', 8, true), row('Trumpets', 5)]), answer: 13,
        steps: ['The whole is every player in one set.', 'One set has 8 drummers and 5 trumpet players: 8 + 5.', 'So drummers are 8 out of every 13 players.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m1-t2', title: 'Equivalent ratios', skill: 'Make equivalent ratios by multiplying both parts by the same number',
    bigIdea: "Multiply both numbers by the same number, and the mix stays the same, just bigger.",
    screens: [
      { title: 'Pancakes for a crowd', text: 'A pancake recipe uses 3 cups of flour for every 2 eggs. You want to make a lot more pancakes. How much of each do you need?',
        pictures: [table([['Flour (cups)', '3'], ['Eggs', '2']], ['Batches', '1'])] },
      { title: "Adding 1 to each changes it", text: "What if you just add 1 to each? That's 4 cups of flour and 3 eggs. Same recipe? No. There's less flour for each egg now.",
        beats: [
          { say: "What if you just add 1 to each?", pic: 0 },
          { say: "That's 4 cups of flour and 3 eggs." },
          { say: "Same recipe? No. There's less flour for each egg now." },
        ],
        pictures: [table([['Flour (cups)', '3', '4'], ['Eggs', '2', '3']], ['', 'Recipe', 'Add 1'])] },
      { title: "The big idea", text: "Multiply both numbers by the same number, and the mix stays the same, just bigger.",
        beats: [
          { say: "Multiply both numbers by the same number, and the mix stays the same, just bigger.", pic: 0 },
        ],
        pictures: [table([['Flour (cups)', '3', '?'], ['Eggs', '2', '?']], ['Batches', '1', 'more'])] },
      { title: "Make 2 batches", text: "Two batches means everything twice. Double the flour: 3 × 2 = 6 cups. Double the eggs too: 2 × 2 = 4.",
        beats: [
          { say: "Two batches means everything twice." },
          { say: "Double the flour: 3 × 2 = 6 cups.", pic: 0 },
          { say: "Double the eggs too: 2 × 2 = 4." },
        ],
        pictures: [table([['Flour (cups)', '3', '6'], ['Eggs', '2', '4']], ['Batches', '1', '2'], [[0, 2], [1, 2]], true)] },
      { title: "Make 3 batches", text: "What about 3 batches? Multiply both by 3. Flour: 3 × 3 = 9 cups. Eggs: 2 × 3 = 6. Every column here is the same recipe.",
        beats: [
          { say: "What about 3 batches? Multiply both by 3." },
          { say: "Flour: 3 × 3 = 9 cups. Eggs: 2 × 3 = 6.", pic: 0 },
          { say: "Every column here is the same recipe." },
        ],
        pictures: [table([['Flour (cups)', '3', '6', '9'], ['Eggs', '2', '4', '6']], ['Batches', '1', '2', '3'], [[0, 3], [1, 3]], true)] },
      { title: "You can go back down", text: "It works backwards too. Divide both by the same number. 6 cups and 4 eggs, both divided by 2, are 3 cups and 2 eggs again.",
        beats: [
          { say: "It works backwards too.", pic: 0 },
          { say: "Divide both by the same number." },
          { say: "6 cups and 4 eggs, both divided by 2, are 3 cups and 2 eggs again.", pic: 1 },
        ],
        pictures: [table([['Flour (cups)', '6', '3'], ['Eggs', '4', '2']], ['Batches', '2', '1']), { kind: 'eq', text: '6 : 4 is the same mix as 3 : 2' }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't ADD the same number to both. Adding 2 gives 5 cups and 4 eggs, a different recipe. Multiply instead. Times 2 gives 6 cups and 4 eggs, the same recipe. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't ADD the same number to both. Adding 2 gives 5 cups and 4 eggs, a different recipe.", pic: 0 },
          { say: "Multiply instead. Times 2 gives 6 cups and 4 eggs, the same recipe." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '3 : 2 → 5 : 4 (add 2)', right: '3 : 2 → 6 : 4 (times 2)' }] },
    ],
    turn: {
      text: 'A lemonade recipe uses 2 lemons for every 5 cups of water. How many cups of water go with 6 lemons?',
      picture: table([['Lemons', '2', '6'], ['Water (cups)', '5', '?']], ['', 'Recipe', 'Big jug']),
      answer: 15,
      steps: ['6 lemons is 2 lemons times 3.', 'Multiply the water by the same number: 5 × 3.', 'So you need 15 cups of water.'],
      prompt: 'Find what the lemons were multiplied by. Do the same to the water.',
      hint1: 'What do you multiply 2 by to get 6?',
      hint2: 'Multiply the 5 cups of water by that same number.',
      twin: { text: 'A paint mix uses 3 cans of blue for every 4 cans of white. How many cans of blue go with 16 cans of white?',
        picture: table([['Blue (cans)', '3', '?'], ['White (cans)', '4', '16']], ['', 'Mix', 'Big mix']),
        answer: 12,
        steps: ['16 cans of white is 4 cans times 4.', 'Multiply the blue by the same number: 3 × 4.', 'So you need 12 cans of blue.'],
        hint1: 'What do you multiply 4 by to get 16?',
        hint2: 'Multiply the 3 cans of blue by that same number.' },
    },
    won: { text: 'You multiplied both parts by the same number, so the lemonade tastes the same.', sticker: 'Ratios that make the same mix, like 2 : 5 and 6 : 15, are called equivalent ratios.' },
    twinWon: { text: 'You multiplied 3 and 4 by the same number: 12 cans of blue for 16 cans of white.', sticker: 'Ratios that make the same mix, like 3 : 4 and 12 : 16, are called equivalent ratios.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A recipe uses 3 cups of flour for every 2 eggs. How many eggs go with 12 cups of flour?',
        picture: table([['Flour (cups)', '3', '12'], ['Eggs', '2', '?']]), answer: 8,
        steps: ['12 cups is 3 cups times 4.', 'Multiply the eggs by 4 too: 2 × 4.', 'So you need 8 eggs.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A trail mix uses 4 scoops of nuts for every 3 scoops of raisins. How many scoops of nuts go with 9 scoops of raisins?',
        picture: table([['Nuts', '4', '?'], ['Raisins', '3', '9']]), answer: 12,
        steps: ['9 scoops of raisins is 3 scoops times 3.', 'Multiply the nuts by 3 too: 4 × 3.', 'So you need 12 scoops of nuts.'] } },
      { why: 'Still "times both by the same number"', problem: { text: 'Every column in this table is the same paint mix. What number goes where the ? is?',
        picture: table([['Red (cups)', '5', '10', '?'], ['Yellow (cups)', '2', '4', '6']]), answer: 15,
        steps: ['6 cups of yellow is 2 cups times 3.', 'Multiply the red by 3 too: 5 × 3.', 'So the missing number is 15.'] } },
      { why: 'A little harder', problem: { text: 'A party plan uses 15 pizzas for 20 people. Keep the same plan. How many pizzas do 4 people need?',
        picture: table([['Pizzas', '15', '?'], ['People', '20', '4']]), answer: 3,
        steps: ['4 people is 20 people divided by 5.', 'Divide the pizzas by 5 too: 15 ÷ 5.', 'So 4 people need 3 pizzas.'] } },
      { why: 'Same math in a story', problem: { text: 'A fruit punch uses 2 cups of juice for every 3 cups of soda water. Leo makes punch with 14 cups of juice. How many cups of soda water does he use?',
        picture: table([['Juice (cups)', '2', '14'], ['Soda (cups)', '3', '?']]), answer: 21,
        steps: ['14 cups of juice is 2 cups times 7.', 'Multiply the soda water by 7 too: 3 × 7.', 'So Leo uses 21 cups of soda water.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m1-t3', title: 'Unit rate', skill: 'Find how much for one (a unit rate) by dividing',
    bigIdea: "To find how much for one, divide the total by how many there are.",
    screens: [
      { title: 'Notebooks for school', text: 'At the store, a pack of 4 notebooks costs $5. How much does one notebook cost?',
        pictures: [split(4, '$5')] },
      { title: "The tag is for the whole pack", text: "Look at the tag. $5 buys the whole pack. So what does one notebook cost? Not $5. That pays for all 4. We have to share the $5 out.",
        beats: [
          { say: "Look at the tag. $5 buys the whole pack.", pic: 0 },
          { say: "So what does one notebook cost? Not $5. That pays for all 4." },
          { say: "We have to share the $5 out." },
        ],
        pictures: [split(4, '$5')] },
      { title: "The big idea", text: "To find how much for one, divide the total by how many there are.",
        beats: [
          { say: "To find how much for one, divide the total by how many there are.", pic: 0 },
        ],
        pictures: [split(4, '$5')] },
      { title: "One part for each notebook", text: "Draw the $5 as one long bar. 4 notebooks share it, so cut it into 4 equal parts. One part for each notebook.",
        beats: [
          { say: "Draw the $5 as one long bar.", pic: 0 },
          { say: "4 notebooks share it, so cut it into 4 equal parts." },
          { say: "One part for each notebook." },
        ],
        pictures: [split(4, '$5', undefined, true)] },
      { title: "Share out the dollars", text: "Now divide $5 by 4. Each part gets $1, and $1 is left over. Split that last $1 into 4 quarters, 25 cents each. So each part is $1.25. That's one notebook.",
        beats: [
          { say: "Now divide $5 by 4. Each part gets $1, and $1 is left over." },
          { say: "Split that last $1 into 4 quarters, 25 cents each." },
          { say: "So each part is $1.25. That's one notebook.", pic: 0 },
        ],
        pictures: [split(4, '$5', '$1.25', true), { kind: 'eq', text: '$5 ÷ 4 = $1.25' }] },
      { title: "Check it", text: "Does that match the tag? Check it. 4 × $1.25 = $5. Yes. So one notebook costs $1.25.",
        beats: [
          { say: "Does that match the tag? Check it.", pic: 0 },
          { say: "4 × $1.25 = $5. Yes.", pic: 1 },
          { say: "So one notebook costs $1.25." },
        ],
        pictures: [split(4, '$5', '$1.25'), { kind: 'eq', text: '4 × $1.25 = $5' }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't divide the other way around. 4 ÷ 5 would make a notebook 80 cents, and that's too cheap. Put the DOLLARS first: $5 ÷ 4 = $1.25. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't divide the other way around. 4 ÷ 5 would make a notebook 80 cents, and that's too cheap.", pic: 0 },
          { say: "Put the DOLLARS first: $5 ÷ 4 = $1.25." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '4 ÷ 5 = $0.80 each', right: '$5 ÷ 4 = $1.25 each' }] },
    ],
    turn: {
      text: 'A pack of 4 pens costs $7. How much does one pen cost?',
      picture: split(4, '$7'),
      answer: 1.75,
      steps: ['The $7 pays for 4 pens, so split it into 4 equal parts.', '$7 ÷ 4.', 'So one pen costs $1.75.'],
      prompt: 'Split the total into one equal part for each pen.',
      hint1: 'How many pens share the $7?',
      hint2: 'Divide the dollars by the number of pens.',
      twin: { text: 'A car goes 150 miles on 4 gallons of gas. How many miles does it go on one gallon?',
        picture: split(4, '150 miles'),
        answer: 37.5,
        steps: ['The 150 miles are shared by 4 gallons.', 'Split 150 into 4 equal parts: 150 ÷ 4.', 'So the car goes 37.5 miles on one gallon.'],
        hint1: 'How many gallons share the 150 miles?',
        hint2: 'Divide the miles by the number of gallons.' },
    },
    won: { text: 'You split the price into equal parts and found the cost of one.', sticker: 'How much for ONE, like $1.75 per pen, is called a unit rate.' },
    twinWon: { text: 'You split 150 miles into 4 equal parts: 37.5 miles for each gallon.', sticker: 'How much for ONE, like 37.5 miles per gallon, is called a unit rate.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A pack of 4 folders costs $3. How much does one folder cost?',
        picture: split(4, '$3'), answer: 0.75,
        steps: ['The $3 pays for 4 folders.', 'Split it into 4 equal parts: $3 ÷ 4.', 'So one folder costs $0.75.'] } },
      { why: 'Same idea, new numbers', problem: { text: '4 sandwiches cost $31. How much does one sandwich cost?',
        picture: split(4, '$31'), answer: 7.75,
        steps: ['The $31 pays for 4 sandwiches.', 'Split it into 4 equal parts: $31 ÷ 4.', 'So one sandwich costs $7.75.'] } },
      { why: 'Still "how much for one"', problem: { text: 'A printer prints 135 pages in 5 minutes. How many pages does it print in one minute?',
        picture: split(5, '135 pages'), answer: 27,
        steps: ['The 135 pages are shared by 5 minutes.', 'Split 135 into 5 equal parts: 135 ÷ 5.', 'So it prints 27 pages in one minute.'] } },
      { why: 'A little harder', problem: { text: '6 muffins cost $13.50. How much does one muffin cost?',
        picture: split(6, '$13.50'), answer: 2.25,
        steps: ['The $13.50 pays for 6 muffins.', 'Split it into 6 equal parts: $13.50 ÷ 6.', 'So one muffin costs $2.25.'] } },
      { why: 'Same math in a story', problem: { text: 'Maya earns $39 for babysitting for 4 hours. How much does she earn for one hour?',
        picture: split(4, '$39'), answer: 9.75,
        steps: ['The $39 is for 4 hours of work.', 'Split it into 4 equal parts: $39 ÷ 4.', 'So Maya earns $9.75 for one hour.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m1-t4', title: 'Use a unit rate', skill: 'Use the amount for one to find another amount',
    bigIdea: "Find how much for one first, then multiply by how many you want.",
    screens: [
      { title: 'Snacks for movie night', text: '3 bags of popcorn cost $12. Your friends are coming, so you need 5 bags. How much do 5 bags cost?',
        pictures: [tape([row('3 bags', 3, false, undefined, '$12')])] },
      { title: "2 more bags is not $2 more", text: "3 bags cost $12. You want 5, just 2 more. So is it $12 plus $2? No. One bag costs a lot more than $1. First we need the price of one bag.",
        beats: [
          { say: "3 bags cost $12. You want 5, just 2 more.", pic: 0 },
          { say: "So is it $12 plus $2? No. One bag costs a lot more than $1." },
          { say: "First we need the price of one bag." },
        ],
        pictures: [tape([row('3 bags', 3, false, undefined, '$12')])] },
      { title: "The big idea", text: "Find how much for one first, then multiply by how many you want.",
        beats: [
          { say: "Find how much for one first, then multiply by how many you want.", pic: 0 },
        ],
        pictures: [tape([row('3 bags', 3, false, undefined, '$12')])] },
      { title: "Find one bag", text: "Split the $12 into 3 equal parts, one for each bag. $12 ÷ 3 = $4. So one bag costs $4.",
        beats: [
          { say: "Split the $12 into 3 equal parts, one for each bag.", pic: 0 },
          { say: "$12 ÷ 3 = $4.", pic: 1 },
          { say: "So one bag costs $4." },
        ],
        pictures: [tape([row('3 bags', 3, false, '$4', '$12')], true), { kind: 'eq', text: '$12 ÷ 3 = $4' }] },
      { title: "Line up 5 bags", text: "Now line up the 5 bags you want. What does each one cost? The same $4. The price didn't change. You just need more bags.",
        beats: [
          { say: "Now line up the 5 bags you want.", pic: 0 },
          { say: "What does each one cost? The same $4." },
          { say: "The price didn't change. You just need more bags." },
        ],
        pictures: [tape([row('3 bags', 3, false, '$4'), row('5 bags', 5, true, '$4')], true)] },
      { title: "Multiply", text: "Last step, multiply. 5 bags at $4 each is 5 × $4 = $20. So movie night costs $20.",
        beats: [
          { say: "Last step, multiply." },
          { say: "5 bags at $4 each is 5 × $4 = $20.", pic: 1 },
          { say: "So movie night costs $20.", pic: 0 },
        ],
        pictures: [tape([row('5 bags', 5, true, '$4', '$20')]), { kind: 'eq', text: '$12 ÷ 3 = $4', lines: ['5 × $4 = $20'] }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't multiply $12 by 5. That gives $60, way too much. $12 is the price of 3 bags, not ONE. Find one bag first, then 5 × $4 = $20. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't multiply $12 by 5. That gives $60, way too much.", pic: 0 },
          { say: "$12 is the price of 3 bags, not ONE. Find one bag first, then 5 × $4 = $20." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '5 × $12 = $60', right: '$12 ÷ 3 = $4, then 5 × $4 = $20' }] },
    ],
    turn: {
      text: '4 movie tickets cost $18. How much do 6 tickets cost?',
      picture: tape([row('4 tickets', 4, false, undefined, '$18')]),
      answer: 27,
      steps: ['Find one ticket: $18 ÷ 4 = $4.50.', 'Multiply by the 6 tickets you want: 6 × $4.50.', 'So 6 tickets cost $27.'],
      prompt: 'Find the price of one ticket first. Then multiply.',
      hint1: 'What does one ticket cost? Split $18 into 4 equal parts.',
      hint2: 'Now multiply the price of one ticket by 6.',
      twin: { text: 'A machine fills 120 bottles in 8 minutes. How many bottles does it fill in 5 minutes?',
        picture: tape([row('8 minutes', 8, false, undefined, '120 bottles')]),
        answer: 75,
        steps: ['Find one minute: 120 ÷ 8 = 15 bottles.', 'Multiply by the 5 minutes: 5 × 15.', 'So it fills 75 bottles in 5 minutes.'],
        hint1: 'How many bottles does it fill in one minute? Split 120 into 8 equal parts.',
        hint2: 'Now multiply the bottles for one minute by 5.' },
    },
    won: { text: 'You found the price of one ticket, then multiplied.', sticker: 'Once you know the unit rate, multiply it to find any amount.' },
    twinWon: { text: 'You found the bottles for one minute, then found 75 bottles in 5 minutes.', sticker: 'Once you know the unit rate, multiply it to find any amount.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '3 bags of chips cost $6. How much do 7 bags cost?',
        picture: tape([row('3 bags', 3, false, undefined, '$6')]), answer: 14,
        steps: ['Find one bag: $6 ÷ 3 = $2.', 'Multiply by 7 bags: 7 × $2.', 'So 7 bags cost $14.'] } },
      { why: 'Same idea, new numbers', problem: { text: '5 notebooks cost $15. How much do 8 notebooks cost?',
        picture: tape([row('5 books', 5, false, undefined, '$15')]), answer: 24,
        steps: ['Find one notebook: $15 ÷ 5 = $3.', 'Multiply by 8 notebooks: 8 × $3.', 'So 8 notebooks cost $24.'] } },
      { why: 'Still "one first, then multiply"', problem: { text: 'A printer prints 42 pages in 6 minutes. How many pages does it print in 10 minutes?',
        picture: tape([row('6 minutes', 6, false, undefined, '42 pages')]), answer: 70,
        steps: ['Find one minute: 42 ÷ 6 = 7 pages.', 'Multiply by 10 minutes: 10 × 7.', 'So it prints 70 pages in 10 minutes.'] } },
      { why: 'A little harder', problem: { text: '4 yards of fabric cost $23. How much do 9 yards cost?',
        picture: tape([row('4 yards', 4, false, undefined, '$23')]), answer: 51.75,
        steps: ['Find one yard: $23 ÷ 4 = $5.75.', 'Multiply by 9 yards: 9 × $5.75.', 'So 9 yards cost $51.75.'] } },
      { why: 'Same math in a story', problem: { text: 'Sam’s car uses 3 gallons of gas to drive 84 miles. How far can it drive on 8 gallons?',
        picture: tape([row('3 gallons', 3, false, undefined, '84 miles')]), answer: 224,
        steps: ['Find one gallon: 84 ÷ 3 = 28 miles.', 'Multiply by 8 gallons: 8 × 28.', 'So the car can drive 224 miles.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m1-t5', title: 'Ratio tables', skill: 'Solve a ratio problem with a table: scale up, scale down, add columns',
    bigIdea: "Every column is the same mix, so you can multiply, divide or add whole columns to make a new one.",
    screens: [
      { title: 'Trail mix for a camp trip', text: 'Trail mix uses 3 cups of nuts for every 5 cups of cereal. For a camp trip you have 15 cups of nuts. How much cereal do you need?',
        pictures: [table([['Nuts (cups)', '3', '15'], ['Cereal (cups)', '5', '?']])] },
      { title: "A big jump is hard to see", text: "You have 15 cups of nuts. How much cereal goes with them? Going from 3 and 5 straight to 15 is a big jump. So take small steps, in a table.",
        beats: [
          { say: "You have 15 cups of nuts. How much cereal goes with them?", pic: 0 },
          { say: "Going from 3 and 5 straight to 15 is a big jump. So take small steps, in a table." },
        ],
        pictures: [table([['Nuts (cups)', '3', '15'], ['Cereal (cups)', '5', '?']])] },
      { title: "The big idea", text: "Every column is the same mix, so you can multiply, divide or add whole columns to make a new one.",
        beats: [
          { say: "Every column is the same mix, so you can multiply, divide or add whole columns to make a new one.", pic: 0 },
        ],
        pictures: [table([['Nuts (cups)', '3', '6', '9'], ['Cereal (cups)', '5', '10', '15']])] },
      { title: "Double it", text: "Start with 3 cups of nuts and 5 cups of cereal. Double both. 3 × 2 = 6, and 5 × 2 = 10. Same mix, just twice as much.",
        beats: [
          { say: "Start with 3 cups of nuts and 5 cups of cereal.", pic: 0 },
          { say: "Double both. 3 × 2 = 6, and 5 × 2 = 10." },
          { say: "Same mix, just twice as much." },
        ],
        pictures: [table([['Nuts (cups)', '3', '6'], ['Cereal (cups)', '5', '10']], undefined, [[0, 2], [1, 2]], true)] },
      { title: "Add two columns", text: "Can you add two columns together? Yes. 3 + 6 = 9 cups of nuts, and 5 + 10 = 15 cups of cereal. Still the same mix.",
        beats: [
          { say: "Can you add two columns together? Yes.", pic: 0 },
          { say: "3 + 6 = 9 cups of nuts, and 5 + 10 = 15 cups of cereal." },
          { say: "Still the same mix." },
        ],
        pictures: [table([['Nuts (cups)', '3', '6', '9'], ['Cereal (cups)', '5', '10', '15']], undefined, [[0, 3], [1, 3]], true)] },
      { title: "Reach 15 cups of nuts", text: "Now look. 6 + 9 = 15 cups of nuts, just what you have. So add those two columns. Underneath, 10 + 15 = 25. You need 25 cups of cereal.",
        beats: [
          { say: "Now look. 6 + 9 = 15 cups of nuts, just what you have.", pic: 0 },
          { say: "So add those two columns. Underneath, 10 + 15 = 25." },
          { say: "You need 25 cups of cereal." },
        ],
        pictures: [table([['Nuts (cups)', '3', '6', '9', '15'], ['Cereal (cups)', '5', '10', '15', '25']], undefined, [[0, 4], [1, 4]], true)] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't ADD 12 to both numbers. 5 + 12 = 17 makes a different mix. 3 × 5 = 15, so multiply the cereal by 5 too. That's 25. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't ADD 12 to both numbers. 5 + 12 = 17 makes a different mix." },
          { say: "3 × 5 = 15, so multiply the cereal by 5 too. That's 25." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '3 : 5 → 15 : 17 (add 12)', right: '3 : 5 → 15 : 25 (times 5)' }] },
    ],
    turn: {
      text: 'A smoothie uses 2 cups of berries for every 3 cups of yogurt. How many cups of yogurt go with 10 cups of berries?',
      picture: table([['Berries (cups)', '2', '4', '6', '10'], ['Yogurt (cups)', '3', '6', '9', '?']]),
      answer: 15,
      steps: ['Two columns of berries add up to 10: 4 + 6 = 10.', 'Add the yogurt in those same columns: 6 + 9.', 'So you need 15 cups of yogurt.'],
      prompt: 'Use the columns you already have. Multiply one, or add two together.',
      hint1: 'Which two columns of berries add up to 10?',
      hint2: 'Add the yogurt in those same two columns.',
      twin: { text: 'A bakery uses 12 eggs for every 8 cups of flour. How many eggs go with 2 cups of flour?',
        picture: table([['Eggs', '12', '6', '?'], ['Flour (cups)', '8', '4', '2']]),
        answer: 3,
        steps: ['Halve both numbers: 6 eggs for 4 cups of flour.', 'Halve again: 6 ÷ 2 eggs for 2 cups of flour.', 'So you need 3 eggs.'],
        hint1: 'How do you get from 8 cups to 4 cups? Do the same to the eggs.',
        hint2: 'Now go from 4 cups to 2 cups. Do the same to the 6 eggs.' },
    },
    won: { text: 'You added two columns you already had to make the one you needed.', sticker: 'A table of equivalent ratios is called a ratio table.' },
    twinWon: { text: 'You halved 12 eggs and 8 cups of flour, then halved again: 3 eggs for 2 cups.', sticker: 'A table of equivalent ratios is called a ratio table.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A salad uses 3 tomatoes for every 4 cucumbers. How many cucumbers go with 12 tomatoes?',
        picture: table([['Tomatoes', '3', '6', '9', '12'], ['Cucumbers', '4', '8', '12', '?']]), answer: 16,
        steps: ['Add the 3 : 4 and 9 : 12 columns: 3 + 9 = 12 tomatoes.', 'Add the cucumbers in those columns: 4 + 12.', 'So you need 16 cucumbers.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A paint mix uses 5 cups of white for every 2 cups of red. How many cups of white go with 14 cups of red?',
        picture: table([['White (cups)', '5', '10', '?'], ['Red (cups)', '2', '4', '14']]), answer: 35,
        steps: ['14 cups of red is 2 cups times 7.', 'Multiply the white by 7 too: 5 × 7.', 'So you need 35 cups of white.'] } },
      { why: 'Still "every column is the same ratio"', problem: { text: 'A gym has 30 balls for every 18 kids. At the same ratio, how many balls go with 3 kids?',
        picture: table([['Balls', '30', '10', '?'], ['Kids', '18', '6', '3']]), answer: 5,
        steps: ['Divide both by 3: 10 balls for 6 kids.', 'Divide both by 2: 10 ÷ 2 balls for 3 kids.', 'So 3 kids get 5 balls.'] } },
      { why: 'A little harder', problem: { text: 'A recipe uses 4 cups of rice for every 6 cups of water. How many cups of water go with 10 cups of rice?',
        picture: table([['Rice (cups)', '4', '2', '10'], ['Water (cups)', '6', '3', '?']]), answer: 15,
        steps: ['Halve the first column: 2 cups of rice for 3 cups of water.', 'Add columns: 4 + 4 + 2 = 10 cups of rice, so 6 + 6 + 3 cups of water.', 'So you need 15 cups of water.'] } },
      { why: 'Same math in a story', problem: { text: 'A school trip needs 2 adults for every 9 students. 45 students are going. How many adults are needed?',
        picture: table([['Adults', '2', '?'], ['Students', '9', '45']]), answer: 10,
        steps: ['45 students is 9 students times 5.', 'Multiply the adults by 5 too: 2 × 5.', 'So 10 adults are needed.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m1-t6', title: 'Part-part-whole ratios', skill: 'Use a ratio and a total to find each part',
    bigIdea: "Add the parts to find how many equal boxes make the whole, then find what one box holds.",
    screens: [
      { title: 'A class photo', text: 'A class has 2 boys for every 3 girls. There are 30 students in all. How many girls are in the class?',
        pictures: [tape([row('Boys', 2), row('Girls', 3, true)])] },
      { title: "Not 3 girls", text: "Are there just 3 girls in the class? No. There are 30 students in all. The 2 and the 3 only say that for every 2 boys, there are 3 girls.",
        beats: [
          { say: "Are there just 3 girls in the class? No.", pic: 0 },
          { say: "There are 30 students in all." },
          { say: "The 2 and the 3 only say that for every 2 boys, there are 3 girls." },
        ],
        pictures: [tape([row('Boys', 2), row('Girls', 3, true)])] },
      { title: "The big idea", text: "Add the parts to find how many equal boxes make the whole, then find what one box holds.",
        beats: [
          { say: "Add the parts to find how many equal boxes make the whole, then find what one box holds.", pic: 0 },
        ],
        pictures: [tape([row('Boys', 2), row('Girls', 3, true)])] },
      { title: "Draw the boxes", text: "Draw it as boxes. 2 for the boys, 3 for the girls. Every box holds the same number of students.",
        beats: [
          { say: "Draw it as boxes. 2 for the boys, 3 for the girls.", pic: 0 },
          { say: "Every box holds the same number of students." },
        ],
        pictures: [tape([row('Boys', 2), row('Girls', 3, true)], true)] },
      { title: "Share the 30 students", text: "How many boxes in all? 2 + 3 = 5. Those 5 boxes hold all 30 students. So 30 ÷ 5 = 6 in each box.",
        beats: [
          { say: "How many boxes in all? 2 + 3 = 5.", pic: 0 },
          { say: "Those 5 boxes hold all 30 students." },
          { say: "So 30 ÷ 5 = 6 in each box." },
        ],
        pictures: [split(5, '30 students', '6', true), { kind: 'eq', text: '30 ÷ 5 = 6' }] },
      { title: "Count the girls", text: "The girls have 3 boxes, and each box holds 6. 3 × 6 = 18. So there are 18 girls. Check it. The boys have 2 × 6 = 12, and 12 + 18 = 30.",
        beats: [
          { say: "The girls have 3 boxes, and each box holds 6.", pic: 0 },
          { say: "3 × 6 = 18. So there are 18 girls." },
          { say: "Check it. The boys have 2 × 6 = 12, and 12 + 18 = 30." },
        ],
        pictures: [tape([row('Boys', 2, false, '6'), row('Girls', 3, true, '6')], true), { kind: 'eq', text: '3 × 6 = 18 girls' }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't divide 30 by JUST the 3. That leaves out the boys. Use all 5 boxes. 30 ÷ 5 = 6, and 3 × 6 = 18. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't divide 30 by JUST the 3. That leaves out the boys." },
          { say: "Use all 5 boxes. 30 ÷ 5 = 6, and 3 × 6 = 18." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '30 ÷ 3 = 10 girls', right: '30 ÷ 5 = 6, and 3 × 6 = 18 girls' }] },
    ],
    turn: {
      text: 'A club has 3 boys for every 4 girls. There are 28 members. How many girls are in the club?',
      picture: tape([row('Boys', 3), row('Girls', 4, true)]),
      answer: 16,
      steps: ['There are 3 + 4 = 7 boxes for the 28 members.', 'One box holds 28 ÷ 7 = 4.', 'The girls have 4 boxes: 4 × 4, so there are 16 girls.'],
      prompt: 'Count all the boxes first. Then find what one box holds.',
      hint1: 'How many boxes are there for boys and girls together?',
      hint2: 'Share 28 among all the boxes. Then count the girls’ boxes.',
      twin: { text: 'A bag has 5 red marbles for every 2 blue marbles. There are 42 marbles. How many red marbles are there?',
        picture: tape([row('Red', 5, true), row('Blue', 2)]),
        answer: 30,
        steps: ['There are 5 + 2 = 7 boxes for the 42 marbles.', 'One box holds 42 ÷ 7 = 6.', 'Red has 5 boxes: 5 × 6, so there are 30 red marbles.'],
        hint1: 'How many boxes are there for red and blue together?',
        hint2: 'Share 42 among all the boxes. Then count the red boxes.' },
    },
    won: { text: 'You counted all the boxes, found one box, then counted the girls.', sticker: 'In a ratio, the parts add up to the whole. Here 3 + 4 parts make the whole club.' },
    twinWon: { text: 'You shared 42 marbles into equal boxes and found 30 red marbles.', sticker: 'In a ratio, the parts add up to the whole. Here 5 + 2 parts make the whole bag.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A class has 2 boys for every 3 girls. There are 25 students. How many boys are in the class?',
        picture: tape([row('Boys', 2, true), row('Girls', 3)]), answer: 10,
        steps: ['There are 2 + 3 = 5 boxes for 25 students.', 'One box holds 25 ÷ 5 = 5.', 'The boys have 2 boxes: 2 × 5, so there are 10 boys.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A fruit bowl has 4 apples for every 5 oranges. There are 36 pieces of fruit. How many oranges are there?',
        picture: tape([row('Apples', 4), row('Oranges', 5, true)]), answer: 20,
        steps: ['There are 4 + 5 = 9 boxes for 36 pieces of fruit.', 'One box holds 36 ÷ 9 = 4.', 'Oranges have 5 boxes: 5 × 4, so there are 20 oranges.'] } },
      { why: 'Still "add the parts first"', problem: { text: 'A drink is 1 part juice to 3 parts water. You make 12 cups of the drink. How many cups of juice do you use?',
        picture: tape([row('Juice', 1, true), row('Water', 3)]), answer: 3,
        steps: ['There are 1 + 3 = 4 boxes for 12 cups.', 'One box holds 12 ÷ 4 cups.', 'Juice has 1 box, so you use 3 cups of juice.'] } },
      { why: 'A little harder', problem: { text: 'Paint is mixed 3 parts blue, 2 parts white and 1 part black. You mix 18 cups. How many cups of blue do you use?',
        picture: tape([row('Blue', 3, true), row('White', 2), row('Black', 1)]), answer: 9,
        steps: ['There are 3 + 2 + 1 = 6 boxes for 18 cups.', 'One box holds 18 ÷ 6 = 3 cups.', 'Blue has 3 boxes: 3 × 3, so you use 9 cups of blue.'] } },
      { why: 'Same math in a story', problem: { text: 'At a soccer game there are 5 home fans for every 3 away fans. There are 400 fans in the stands. How many are away fans?',
        picture: tape([row('Home', 5), row('Away', 3, true)]), answer: 150,
        steps: ['There are 5 + 3 = 8 boxes for 400 fans.', 'One box holds 400 ÷ 8 = 50 fans.', 'Away fans have 3 boxes: 3 × 50, so there are 150 away fans.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m1-t7', title: 'Change units with a rate', skill: 'Convert measurement units with a unit rate (inches, feet, yards, minutes, meters)',
    bigIdea: "Start from one fact, 1 foot is 12 inches, then multiply to change to the smaller unit and divide to change back.",
    screens: [
      { title: 'A shelf for your room', text: 'A shelf is 4 feet long. Your tape measure only shows inches. How many inches long is the shelf?',
        pictures: [table([['Feet', '1', '4'], ['Inches', '12', '?']])] },
      { title: "Feet and inches are different sizes", text: "Is 4 feet the same as 4 inches? No. A foot is much longer than an inch. So first you need one fact. How many inches fit in 1 foot?",
        beats: [
          { say: "Is 4 feet the same as 4 inches? No.", pic: 0 },
          { say: "A foot is much longer than an inch." },
          { say: "So first you need one fact. How many inches fit in 1 foot?" },
        ],
        pictures: [table([['Feet', '1', '4'], ['Inches', '12', '?']])] },
      { title: "The big idea", text: "Start from one fact, 1 foot is 12 inches, then multiply to change to the smaller unit and divide to change back.",
        beats: [
          { say: "Start from one fact, 1 foot is 12 inches, then multiply to change to the smaller unit and divide to change back.", pic: 0 },
        ],
        pictures: [table([['Feet', '1'], ['Inches', '12']])] },
      { title: "Build the table", text: "1 foot is 12 inches. So 2 feet is 24 inches, and 3 feet is 36 inches. Each extra foot adds 12 more.",
        beats: [
          { say: "1 foot is 12 inches.", pic: 0 },
          { say: "So 2 feet is 24 inches, and 3 feet is 36 inches." },
          { say: "Each extra foot adds 12 more." },
        ],
        pictures: [table([['Feet', '1', '2', '3'], ['Inches', '12', '24', '36']], undefined, undefined, true)] },
      { title: "Jump to 4 feet", text: "Do you have to step up one foot at a time? No. 4 feet is 4 × 12 = 48 inches. So the shelf is 48 inches long.",
        beats: [
          { say: "Do you have to step up one foot at a time? No.", pic: 0 },
          { say: "4 feet is 4 × 12 = 48 inches." },
          { say: "So the shelf is 48 inches long." },
        ],
        pictures: [table([['Feet', '1', '2', '3', '4'], ['Inches', '12', '24', '36', '48']], undefined, [[0, 4], [1, 4]], true), { kind: 'eq', text: '4 × 12 = 48 inches' }] },
      { title: "Going back", text: "What about going back, from inches to feet? Feet are bigger, so you divide by 12. 36 ÷ 12 = 3. So 36 inches is 3 feet.",
        beats: [
          { say: "What about going back, from inches to feet?", pic: 0 },
          { say: "Feet are bigger, so you divide by 12." },
          { say: "36 ÷ 12 = 3. So 36 inches is 3 feet." },
        ],
        pictures: [table([['Feet', '1', '2', '3', '4'], ['Inches', '12', '24', '36', '48']], undefined, [[0, 3], [1, 3]]), { kind: 'eq', text: '36 ÷ 12 = 3 feet' }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Going to the smaller unit, don't DIVIDE. Smaller units mean more of them, so multiply. 4 × 12 = 48 inches. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Going to the smaller unit, don't DIVIDE." },
          { say: "Smaller units mean more of them, so multiply. 4 × 12 = 48 inches." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '4 feet = 4 ÷ 12 inches', right: '4 feet = 4 × 12 = 48 inches' }] },
    ],
    turn: {
      text: 'A rug is 5 yards long. 1 yard is 3 feet. How many feet long is the rug?',
      picture: table([['Yards', '1', '5'], ['Feet', '3', '?']]),
      answer: 15,
      steps: ['1 yard is 3 feet, so each yard adds 3 feet.', 'Feet are smaller, so multiply: 5 × 3.', 'So the rug is 15 feet long.'],
      prompt: 'Start from one yard. Smaller units means more of them.',
      hint1: 'How many feet are in one yard?',
      hint2: 'Feet are smaller than yards, so you get more of them. Multiply the 5 yards by the feet in one yard.',
      twin: { text: 'A movie is 150 minutes long. 60 minutes is 1 hour. How many hours long is the movie?',
        picture: table([['Hours', '1', '?'], ['Minutes', '60', '150']]),
        answer: 2.5,
        steps: ['Hours are bigger than minutes, so divide by 60.', '120 minutes is 2 hours, and the other 30 minutes is half an hour.', 'So the movie is 2.5 hours long.'],
        hint1: 'Are hours bigger or smaller than minutes? Will you get more hours or fewer?',
        hint2: 'Divide 150 by the number of minutes in one hour.' },
    },
    won: { text: 'You started from one yard and multiplied to get feet.', sticker: 'A rate like 3 feet per 1 yard is called a conversion factor.' },
    twinWon: { text: 'You divided 150 minutes by 60 and got 2.5 hours.', sticker: 'A rate like 60 minutes per 1 hour is called a conversion factor.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A fence is 7 yards long. 1 yard is 3 feet. How many feet long is the fence?',
        picture: table([['Yards', '1', '7'], ['Feet', '3', '?']]), answer: 21,
        steps: ['Feet are smaller than yards, so multiply.', '7 yards is 7 × 3 feet.', 'So the fence is 21 feet long.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A board is 6 feet long. 1 foot is 12 inches. How many inches long is the board?',
        picture: table([['Feet', '1', '6'], ['Inches', '12', '?']]), answer: 72,
        steps: ['Inches are smaller than feet, so multiply.', '6 feet is 6 × 12 inches.', 'So the board is 72 inches long.'] } },
      { why: 'Still "start from one"', problem: { text: 'A race is 5,000 meters long. 1,000 meters is 1 kilometer. How many kilometers long is the race?',
        picture: table([['Kilometers', '1', '?'], ['Meters', '1,000', '5,000']]), answer: 5,
        steps: ['Kilometers are bigger than meters, so divide by 1,000.', '5,000 ÷ 1,000.', 'So the race is 5 kilometers long.'] } },
      { why: 'A little harder', problem: { text: 'A ribbon is 54 inches long. 12 inches is 1 foot. How many feet long is the ribbon?',
        picture: table([['Feet', '1', '?'], ['Inches', '12', '54']]), answer: 4.5,
        steps: ['Feet are bigger than inches, so divide by 12.', '48 inches is 4 feet, and the other 6 inches is half a foot.', 'So the ribbon is 4.5 feet long.'] } },
      { why: 'Same math in a story', problem: { text: 'Jada runs 2.5 kilometers every morning. 1 kilometer is 1,000 meters. How many meters does she run?',
        picture: table([['Kilometers', '1', '2.5'], ['Meters', '1,000', '?']]), answer: 2500,
        steps: ['Meters are smaller than kilometers, so multiply by 1,000.', '2.5 × 1,000.', 'So Jada runs 2,500 meters.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m1-t8', title: 'Speed', skill: 'Find speed as distance ÷ time',
    bigIdea: "How fast you go is how far you go in one hour, so divide the distance by the hours.",
    screens: [
      { title: 'A long bike ride', text: 'You ride 36 miles in 3 hours, at a steady pace the whole way. How far do you ride in one hour?',
        pictures: [trip(36, 3)] },
      { title: "The total hides how fast", text: "36 miles is how far you rode in all, over 3 hours. So how far did you ride in one hour? The total can't say. A faster rider could do the same 36 miles in 2 hours.",
        beats: [
          { say: "36 miles is how far you rode in all, over 3 hours.", pic: 0 },
          { say: "So how far did you ride in one hour? The total can't say." },
          { say: "A faster rider could do the same 36 miles in 2 hours." },
        ],
        pictures: [trip(36, 3)] },
      { title: "The big idea", text: "How fast you go is how far you go in one hour, so divide the distance by the hours.",
        beats: [
          { say: "How fast you go is how far you go in one hour, so divide the distance by the hours.", pic: 0 },
        ],
        pictures: [trip(36, 3)] },
      { title: "One jump for each hour", text: "Cut the ride up by the hours. 3 hours means 3 equal jumps, one for each hour.",
        beats: [
          { say: "Cut the ride up by the hours.", pic: 0 },
          { say: "3 hours means 3 equal jumps, one for each hour." },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 36, ticks: 3, labels: 'ends',
          jumps: [{ from: 0, to: 12, label: '1 hr' }, { from: 12, to: 24, label: '1 hr' }, { from: 24, to: 36, label: '1 hr' }], motion: true }] },
      { title: "How long is one jump?", text: "So how long is one jump? 36 ÷ 3 = 12. Each jump is 12 miles. So you ride 12 miles in one hour.",
        beats: [
          { say: "So how long is one jump? 36 ÷ 3 = 12.", pic: 0 },
          { say: "Each jump is 12 miles. So you ride 12 miles in one hour." },
        ],
        pictures: [{ kind: 'numline', min: 0, max: 36, ticks: 3, labels: ['0', '12', '24', '36'],
          jumps: [{ from: 0, to: 12, label: '1 hr' }, { from: 12, to: 24, label: '1 hr' }, { from: 24, to: 36, label: '1 hr' }], motion: true },
          { kind: 'eq', text: '36 ÷ 3 = 12' }] },
      { title: "Say it as miles per hour", text: "12 miles in each hour is 12 miles per hour. Check it. 3 × 12 = 36 miles, the whole ride.",
        beats: [
          { say: "12 miles in each hour is 12 miles per hour.", pic: 0 },
          { say: "Check it. 3 × 12 = 36 miles, the whole ride." },
        ],
        pictures: [{ kind: 'eq', text: '36 miles ÷ 3 hours = 12 miles per hour', lines: ['3 × 12 = 36'] }] },
      { title: "One thing not to do", text: "Here's the part people mix up. Don't divide the HOURS by the miles. The miles go first. 36 ÷ 3, not 3 ÷ 36. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't divide the HOURS by the miles." },
          { say: "The miles go first. 36 ÷ 3, not 3 ÷ 36." },
          { say: "Okay. Your turn." },
        ],
        pictures: [{ kind: 'cards', wrong: '3 ÷ 36 miles per hour', right: '36 ÷ 3 = 12 miles per hour' }] },
    ],
    turn: {
      text: 'A train goes 150 miles in 3 hours. How many miles does it go in one hour?',
      picture: trip(150, 3),
      answer: 50,
      steps: ['Split the 150 miles into 3 equal jumps, one for each hour.', '150 ÷ 3.', 'So the train goes 50 miles in one hour.'],
      prompt: 'Cut the trip into one equal jump for each hour.',
      hint1: 'How many hours does the trip take?',
      hint2: 'Divide the miles by the hours.',
      twin: { text: 'A car drives 220 miles in 4 hours. How many miles per hour is that?',
        picture: trip(220, 4),
        answer: 55,
        steps: ['Split the 220 miles into 4 equal jumps, one for each hour.', '220 ÷ 4.', 'So the car goes 55 miles per hour.'],
        hint1: 'How many hours does the drive take?',
        hint2: 'Divide the 220 miles by the hours.' },
    },
    won: { text: 'You split the trip into hours and found the miles in one hour.', sticker: 'Speed is a rate: distance ÷ time, like 50 miles per hour.' },
    twinWon: { text: 'You split 220 miles into 4 hours: 55 miles per hour.', sticker: 'Speed is a rate: distance ÷ time, like 55 miles per hour.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A bus goes 120 miles in 3 hours. How many miles does it go in one hour?',
        picture: trip(120, 3), answer: 40,
        steps: ['Split 120 miles into 3 equal jumps, one for each hour.', '120 ÷ 3.', 'So the bus goes 40 miles in one hour.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A boat travels 76 miles in 4 hours. What is its speed in miles per hour?',
        picture: trip(76, 4), answer: 19,
        steps: ['Split 76 miles into 4 equal jumps, one for each hour.', '76 ÷ 4.', 'So the boat goes 19 miles per hour.'] } },
      { why: 'Still "distance ÷ time"', problem: { text: 'You walk 15 kilometers in 3 hours. How many kilometers do you walk in one hour?',
        picture: trip(15, 3), answer: 5,
        steps: ['Split 15 kilometers into 3 equal jumps, one for each hour.', '15 ÷ 3.', 'So you walk 5 kilometers in one hour.'] } },
      { why: 'A little harder', problem: { text: 'A cyclist rides 27 miles in 1.5 hours. What is her speed in miles per hour?',
        picture: trip(27, 3), answer: 18,
        steps: ['1.5 hours is 3 half hours. 27 ÷ 3 = 9 miles in each half hour.', 'Two half hours make one hour: 9 × 2.', 'So her speed is 18 miles per hour.'] } },
      { why: 'Same math in a story', problem: { text: 'The Lee family drives 396 miles to the beach. The drive takes 6 hours. How many miles per hour do they drive?',
        picture: trip(396, 6), answer: 66,
        steps: ['Split 396 miles into 6 equal jumps, one for each hour.', '396 ÷ 6.', 'So they drive 66 miles per hour.'] } },
    ],
  },
]

attachChalk(G6M1, G6M1_CHALK)
