/**
 * Grade 6 · Module 2 — Operations with fractions and mixed numbers.
 * Written to docs/new-flow/AUTHORING.md. Continues Grade 5 Module 3 (dividing by a unit fraction).
 */
import type { Lesson, Picture } from '../script'

type Bar = { parts: number; shaded: number; shade2?: number; split?: number; label?: string }
const bars = (list: Bar[], motion = false): Picture => ({ kind: 'bars', bars: list, motion })
/** One fraction bar. */
const frac = (parts: number, shaded: number, label?: string, split?: number): Bar => ({ parts, shaded, label, split })
/** `n` whole bars, each optionally cut or shaded. */
const wholes = (n: number, parts = 1, shaded = 0, split?: number): Bar[] =>
  Array.from({ length: n }, () => ({ parts, shaded, split }))
/** A mixed number as bars: `whole` full bars, then one bar cut into `d` with `n` shaded. */
const mixed = (whole: number, n: number, d: number): Picture => bars([...wholes(whole, 1, 1), frac(d, n)])
const eq = (text: string, lines?: string[]): Picture => ({ kind: 'eq', text, lines })
/** An area model with the side pieces as labels; no cells filled (the question). */
const area = (cols: string[], rows: string[], widths: number[], heights: number[], cells?: (string | null)[][], motion = false): Picture =>
  ({ kind: 'area', cols, rows, widths, heights, cells, motion })
/** A tape of `n` whole units, each `text`, under a brace. */
const units = (n: number, text: string, brace: string): Picture =>
  ({ kind: 'tape', rows: [{ cells: Array.from({ length: n }, () => ({ w: 1, text })), brace }] })
/** Factor table: the question, both lists unknown. */
const factorQ = (a: number, b: number): Picture =>
  ({ kind: 'table', head: ['Number', 'Factors'], rows: [[String(a), '?'], [String(b), '?']], rowHead: true })
/** Scratch line for "count by a and by b": one jump of each from 0, ends labelled only. */
const countQ = (a: number, b: number, max: number, ticks: number): Picture =>
  ({ kind: 'numline', min: 0, max, ticks, labels: 'ends', jumps: [{ from: 0, to: a, label: `+${a}` }, { from: 0, to: b, label: `+${b}` }] })
/** Teaching line 0..24 counting by `step`, `n` jumps. */
const countBy = (step: number, n: number, motion = false, point?: number): Picture => ({
  kind: 'numline', min: 0, max: 24, ticks: 24, motion,
  labels: Array.from({ length: 25 }, (_, i) => (i % step === 0 ? String(i) : null)),
  jumps: Array.from({ length: n }, (_, k) => ({ from: step * k, to: step * (k + 1) })),
  points: point ? [{ at: point, label: String(point) }] : undefined,
})
const factorTable = (fill18: boolean, mark = false): Picture => ({
  kind: 'table', rowHead: true, motion: !mark,
  head: ['', '1', '2', '3', '4', '6', '9', '12', '18'],
  rows: [
    ['12', '✓', '✓', '✓', '✓', '✓', '', '✓', ''],
    fill18 ? ['18', '✓', '✓', '✓', '', '✓', '✓', '', '✓'] : ['18', '', '', '', '', '', '', '', ''],
  ],
  mark: mark ? [[0, 5], [1, 5]] : undefined,
})

export const G6M2: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m2-t1', title: 'How many fractions fit in a fraction?', skill: 'Divide a fraction by a unit fraction by counting how many fit',
    bigIdea: 'Dividing by a fraction asks how many of those pieces fit. Cut both into the same size pieces, then count.',
    screens: [
      { title: 'Serving the lasagna', text: 'You have 3/4 of a pan of lasagna left. Each serving is 1/8 of the pan. How many servings can you cut?',
        pictures: [bars([frac(4, 3, '3/4')])] },
      { title: 'Not a sharing problem', text: 'Nobody shares with 1/8 of a person. The question is how many 1/8-size pieces fit inside 3/4. And fourths and eighths are different sizes, so we cannot count yet.',
        pictures: [bars([frac(4, 3, '3/4'), frac(8, 1, '1/8')])] },
      { title: 'The big idea', text: 'Dividing by a fraction asks how many of those pieces fit. Cut both into the same size pieces, then count.',
        pictures: [bars([frac(4, 3, '3/4', 2), frac(8, 1, '1/8')])] },
      { title: 'Cut into eighths', text: 'Cut each fourth into 2 equal pieces. Now every piece is 1/8 of the pan, and 3/4 is the same as 6/8.',
        pictures: [bars([frac(4, 3, '3/4', 2)], true), eq('3/4 = 6/8')] },
      { title: 'Count the eighths', text: 'Count the 1/8 pieces inside the shaded part: 1, 2, 3, 4, 5, 6.',
        pictures: [bars([frac(8, 6, '6/8')], true)] },
      { title: 'Put it together', text: '6 servings of 1/8 fit in 3/4 of the pan. So 3/4 ÷ 1/8 = 6.',
        pictures: [bars([frac(8, 6, '6/8')]), eq('3/4 ÷ 1/8 = 6', ['3/4 = 6/8', '6 eighths ÷ 1 eighth = 6'])] },
      { title: 'One thing not to do', text: "Don't expect a tiny answer. You are counting small pieces inside a bigger amount, so the answer is more than 1.",
        pictures: [{ kind: 'cards', wrong: '3/4 ÷ 1/8 = 3/32', right: '3/4 ÷ 1/8 = 6' }] },
    ],
    turn: {
      text: 'You have 2/3 of a pan of cornbread. Each serving is 1/6 of the pan. How many servings can you cut? Find 2/3 ÷ 1/6.',
      picture: bars([frac(3, 2, '2/3')]),
      answer: 4,
      steps: ['Cut each third into 2 equal pieces. Every piece is now 1/6, so 2/3 is the same as 4/6.', 'Count the sixths in the shaded part.', 'So 2/3 ÷ 1/6 = 4.'],
      prompt: 'Cut the shaded part into pieces the size of one serving. Then count them.',
      hint1: 'How many sixths make one third?',
      hint2: 'Write 2/3 as sixths. How many 1/6 pieces is that?',
      twin: { text: 'You have 1/2 gallon of juice. Each glass holds 1/10 gallon. How many glasses can you fill? Find 1/2 ÷ 1/10.',
        picture: bars([frac(2, 1, '1/2')]),
        answer: 5,
        steps: ['A whole gallon is 10 tenths.', 'Half a gallon is half of those tenths, so 1/2 is the same as 5/10.', 'So 1/2 ÷ 1/10 = 5.'],
        hint1: 'How many tenths make a whole gallon?',
        hint2: 'A whole is 10/10. Half of that is how many tenths?' },
    },
    won: { text: 'You made the pieces the same size and counted how many fit.', sticker: 'In 2/3 ÷ 1/6, the number you divide by (1/6) is called the divisor.' },
    twinWon: { text: 'You counted how many 1/10-gallon glasses fit in 1/2 gallon: 5.', sticker: 'In 1/2 ÷ 1/10, the number you divide by (1/10) is called the divisor.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Find 1/2 ÷ 1/6.',
        picture: bars([frac(2, 1, '1/2')]), answer: 3,
        steps: ['Cut the half into sixths: 1/2 is the same as 3/6.', 'Count the 1/6 pieces in 3/6.', 'So 1/2 ÷ 1/6 = 3.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Find 3/5 ÷ 1/10.',
        picture: bars([frac(5, 3, '3/5')]), answer: 6,
        steps: ['Cut each fifth into 2 pieces: 3/5 is the same as 6/10.', 'Count the 1/10 pieces in 6/10.', 'So 3/5 ÷ 1/10 = 6.'] } },
      { why: 'Still "how many pieces fit"', problem: { text: 'Find 3/4 ÷ 1/12.',
        picture: bars([frac(4, 3, '3/4')]), answer: 9,
        steps: ['Cut each fourth into 3 pieces: 3/4 is the same as 9/12.', 'Count the 1/12 pieces in 9/12.', 'So 3/4 ÷ 1/12 = 9.'] } },
      { why: 'A little harder', problem: { text: 'Find 3/4 ÷ 1/2. Part of a piece can fit too.',
        picture: bars([frac(4, 3, '3/4'), frac(2, 1, '1/2')]), answer: { frac: [1, 2], whole: 1 },
        steps: ['Make the pieces match: 3/4 is 3 fourths, and 1/2 is 2 fourths.', 'One 2-fourth piece fits in 3 fourths, with 1 fourth left over.', 'That 1 fourth is half of a 2-fourth piece. So 3/4 ÷ 1/2 = 1 1/2.'] } },
      { why: 'Same math in a story', problem: { text: 'You have 5/6 yard of ribbon. Each bow uses 1/12 yard. How many bows can you make?',
        picture: bars([frac(6, 5, '5/6 yd')]), answer: 10,
        steps: ['Cut each sixth into 2 pieces: 5/6 is the same as 10/12.', 'Each bow uses one 1/12 piece.', 'So you can make 10 bows.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m2-t2', title: 'Flip and multiply', skill: 'Divide by a fraction by multiplying by the flipped fraction, and know why it works',
    bigIdea: 'Dividing by a fraction is the same as multiplying by that fraction flipped over.',
    screens: [
      { title: 'Filling bottles', text: 'You have 2 liters of juice. Each bottle holds 2/3 liter. How many bottles can you fill?',
        pictures: [bars(wholes(2))] },
      { title: 'Drawing gets slow', text: 'You could cut every liter into thirds and count, like last time. That works here. But with numbers like 5/6 ÷ 4/9, drawing and counting takes far too long.',
        pictures: [bars(wholes(2))] },
      { title: 'The big idea', text: 'Dividing by a fraction is the same as multiplying by that fraction flipped over.',
        pictures: [bars(wholes(2, 3)), eq('2 ÷ 2/3 = 2 × 3/2')] },
      { title: 'Same-size pieces first', text: 'Cut each liter into thirds. 2 liters is 6 thirds. Each bottle takes 2 thirds, so 6 thirds ÷ 2 thirds = 3 bottles.',
        pictures: [bars(wholes(2, 1, 0, 3), true), eq('6/3 ÷ 2/3 = 6 ÷ 2 = 3')] },
      { title: 'Where the flip comes from', text: 'Counting thirds in 2 liters is 2 × 3. But a bottle is 2 thirds, so only half as many fit: divide by 2. Times 3, then divide by 2, is the same as times 3/2.',
        pictures: [bars(wholes(2, 3, 3), true), eq('2 × 3 = 6 thirds', ['6 ÷ 2 = 3 bottles', '× 3, then ÷ 2 is × 3/2'])] },
      { title: 'Flip and multiply', text: 'Keep the first number. Change ÷ to ×. Flip the fraction you divide by. 2 × 3/2 = 6/2 = 3, the same answer as counting.',
        pictures: [bars(wholes(2, 3, 3)), eq('2 ÷ 2/3', ['= 2 × 3/2', '= 6/2', '= 3'])] },
      { title: 'One thing not to do', text: "Don't flip the first number. Only the fraction you divide by gets flipped.",
        pictures: [{ kind: 'cards', wrong: '2 ÷ 2/3 = 1/2 × 2/3', right: '2 ÷ 2/3 = 2 × 3/2' }] },
    ],
    turn: {
      text: 'You have 3 liters of juice. Each bottle holds 3/4 liter. How many bottles can you fill? Find 3 ÷ 3/4.',
      picture: bars(wholes(3)),
      answer: 4,
      steps: ['Keep the 3. Change ÷ to ×. Flip 3/4 to 4/3.', '3 × 4/3 = 12/3.', '12 thirds make 4 wholes. So 3 ÷ 3/4 = 4.'],
      prompt: 'Keep the first number, change ÷ to ×, and flip the fraction you divide by.',
      hint1: 'Which number gets flipped: the 3 or the 3/4?',
      hint2: 'Flip 3/4 and multiply it by 3. How many thirds is that, and how many wholes?',
      twin: { text: 'Find 1/2 ÷ 3/4.',
        picture: bars([frac(2, 1, '1/2'), frac(4, 3, '3/4')]),
        answer: { frac: [2, 3] },
        steps: ['Keep 1/2. Change ÷ to ×. Flip 3/4 to 4/3.', 'Multiply tops and bottoms: 1/2 × 4/3 = 4/6.', 'So 1/2 ÷ 3/4 = 4/6, the same as 2/3.'],
        hint1: 'Only one fraction gets flipped. Which one?',
        hint2: 'Flip 3/4, then multiply the tops together and the bottoms together.' },
    },
    won: { text: 'You flipped the fraction you divide by and multiplied.', sticker: 'A flipped fraction is called the reciprocal. 3/4 and 4/3 are reciprocals.' },
    twinWon: { text: 'You flipped 3/4 and multiplied: 1/2 ÷ 3/4 = 2/3.', sticker: 'A flipped fraction is called the reciprocal. 3/4 and 4/3 are reciprocals.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Find 4 ÷ 2/3.',
        picture: eq('4 ÷ 2/3 = ?'), answer: 6,
        steps: ['Keep 4, change ÷ to ×, flip 2/3 to 3/2.', '4 × 3/2 = 12/2.', 'So 4 ÷ 2/3 = 6.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Find 3/5 ÷ 3/10.',
        picture: eq('3/5 ÷ 3/10 = ?'), answer: 2,
        steps: ['Flip 3/10 to 10/3 and multiply.', '3/5 × 10/3 = 30/15.', '30/15 is 2 wholes. So 3/5 ÷ 3/10 = 2.'] } },
      { why: 'Still "flip, then multiply"', problem: { text: 'Find 2/3 ÷ 4/5.',
        picture: eq('2/3 ÷ 4/5 = ?'), answer: { frac: [5, 6] },
        steps: ['Flip 4/5 to 5/4 and multiply.', '2/3 × 5/4 = 10/12.', 'So 2/3 ÷ 4/5 = 10/12, the same as 5/6.'] } },
      { why: 'A little harder', problem: { text: 'Find 5/6 ÷ 2/9. Write the answer as a mixed number.',
        picture: eq('5/6 ÷ 2/9 = ?'), answer: { frac: [3, 4], whole: 3 },
        steps: ['Flip 2/9 to 9/2 and multiply: 5/6 × 9/2 = 45/12.', '45/12 is the same as 15/4. 12/4 makes 3 wholes, with 3/4 left.', 'So 5/6 ÷ 2/9 = 3 3/4.'] } },
      { why: 'Same math in a story', problem: { text: 'A jug holds 3/4 gallon of lemonade. Each glass holds 3/16 gallon. How many glasses can you fill?',
        picture: bars([frac(4, 3, '3/4 gal')]), answer: 4,
        steps: ['The story asks how many 3/16s fit in 3/4, so find 3/4 ÷ 3/16.', 'Flip and multiply: 3/4 × 16/3 = 48/12.', 'So you can fill 4 glasses.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m2-t3', title: 'Multiply mixed numbers', skill: 'Multiply mixed numbers by changing them to fractions first',
    bigIdea: 'Change each mixed number into a fraction first. Then multiply the tops and multiply the bottoms.',
    screens: [
      { title: 'A garden bed', text: 'A garden bed is 2 1/2 yards long and 1 1/2 yards wide. How many square yards does it cover?',
        pictures: [area(['2', '1/2'], ['1', '1/2'], [4, 1], [2, 1])] },
      { title: 'Two pieces go missing', text: 'It is tempting to do 2 × 1 = 2 and 1/2 × 1/2 = 1/4, and say 2 1/4. But look: that skips two whole parts of the bed.',
        pictures: [area(['2', '1/2'], ['1', '1/2'], [4, 1], [2, 1], [['2', null], [null, '1/4']])] },
      { title: 'The big idea', text: 'Change each mixed number into a fraction first. Then multiply the tops and multiply the bottoms.',
        pictures: [area(['2', '1/2'], ['1', '1/2'], [4, 1], [2, 1]), eq('2 1/2 × 1 1/2 = 5/2 × 3/2')] },
      { title: 'Every part counts', text: 'Split the bed into 4 parts and find each one: 2 × 1 = 2, 1/2 × 1 = 1/2, 2 × 1/2 = 1, and 1/2 × 1/2 = 1/4. Together that is 3 3/4.',
        pictures: [area(['2', '1/2'], ['1', '1/2'], [4, 1], [2, 1], [['2', '1/2'], ['1', '1/4']], true)] },
      { title: 'Change to fractions', text: 'There is a faster way. 2 1/2 is 5 halves, so it is 5/2. 1 1/2 is 3 halves, so it is 3/2.',
        pictures: [area(['2', '1/2'], ['1', '1/2'], [4, 1], [2, 1]), eq('2 1/2 = 5/2', ['1 1/2 = 3/2'])] },
      { title: 'Multiply, then change back', text: '5/2 × 3/2 = 15/4. 12/4 makes 3 wholes, with 3/4 left. So the bed covers 3 3/4 square yards, just like the 4 parts.',
        pictures: [area(['2', '1/2'], ['1', '1/2'], [4, 1], [2, 1], [['2', '1/2'], ['1', '1/4']]), eq('5/2 × 3/2 = 15/4', ['15/4 = 3 3/4'])] },
      { title: 'One thing not to do', text: "Don't multiply the whole numbers and the fractions on their own. You lose parts. Change to fractions first.",
        pictures: [{ kind: 'cards', wrong: '2 1/2 × 1 1/2 = 2 1/4', right: '2 1/2 × 1 1/2 = 3 3/4' }] },
    ],
    turn: {
      text: 'Find 1 1/2 × 2 1/3.',
      picture: area(['2', '1/3'], ['1', '1/2'], [6, 1], [2, 1]),
      answer: { frac: [1, 2], whole: 3 },
      steps: ['Change to fractions: 1 1/2 = 3/2 and 2 1/3 = 7/3.', 'Multiply: 3/2 × 7/3 = 21/6.', '18/6 makes 3 wholes, with 3/6 left, and 3/6 = 1/2. So the answer is 3 1/2.'],
      prompt: 'Change both mixed numbers into fractions. Then multiply.',
      hint1: 'How many halves are in 1 1/2? How many thirds are in 2 1/3?',
      hint2: 'Write both as fractions, then multiply the tops together and the bottoms together.',
      twin: { text: 'Find 2 1/2 × 1 1/3.',
        picture: area(['2', '1/2'], ['1', '1/3'], [4, 1], [3, 1]),
        answer: { frac: [1, 3], whole: 3 },
        steps: ['Change to fractions: 2 1/2 = 5/2 and 1 1/3 = 4/3.', 'Multiply: 5/2 × 4/3 = 20/6.', '18/6 makes 3 wholes, with 2/6 left, and 2/6 = 1/3. So the answer is 3 1/3.'],
        hint1: 'How many halves are in 2 1/2? How many thirds are in 1 1/3?',
        hint2: 'Write both as fractions. Multiply tops, multiply bottoms, then change back to a mixed number.' },
    },
    won: { text: 'You changed to fractions, multiplied, and changed back.', sticker: 'A fraction whose top is bigger than its bottom, like 3/2, is called an improper fraction.' },
    twinWon: { text: 'You changed 2 1/2 and 1 1/3 into fractions and got 3 1/3.', sticker: 'A fraction whose top is bigger than its bottom, like 3/2, is called an improper fraction.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Find 1 1/2 × 1 1/2.',
        picture: area(['1', '1/2'], ['1', '1/2'], [2, 1], [2, 1]), answer: { frac: [1, 4], whole: 2 },
        steps: ['Change to fractions: 1 1/2 = 3/2.', 'Multiply: 3/2 × 3/2 = 9/4.', '8/4 makes 2 wholes, with 1/4 left. So the answer is 2 1/4.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Find 3 1/3 × 1 1/2.',
        picture: area(['3', '1/3'], ['1', '1/2'], [9, 1], [2, 1]), answer: 5,
        steps: ['Change to fractions: 3 1/3 = 10/3 and 1 1/2 = 3/2.', 'Multiply: 10/3 × 3/2 = 30/6.', '30/6 is 5 wholes. So the answer is 5.'] } },
      { why: 'Still "fractions first"', problem: { text: 'Find 1 3/4 × 2 2/3.',
        picture: area(['2', '2/3'], ['1', '3/4'], [3, 2], [4, 3]), answer: { frac: [2, 3], whole: 4 },
        steps: ['Change to fractions: 1 3/4 = 7/4 and 2 2/3 = 8/3.', 'Multiply: 7/4 × 8/3 = 56/12, the same as 14/3.', '12/3 makes 4 wholes, with 2/3 left. So the answer is 4 2/3.'] } },
      { why: 'A little harder', problem: { text: 'Find 2 3/5 × 3 1/3.',
        picture: area(['3', '1/3'], ['2', '3/5'], [9, 1], [10, 3]), answer: { frac: [2, 3], whole: 8 },
        steps: ['Change to fractions: 2 3/5 = 13/5 and 3 1/3 = 10/3.', 'Multiply: 13/5 × 10/3 = 130/15, the same as 26/3.', '24/3 makes 8 wholes, with 2/3 left. So the answer is 8 2/3.'] } },
      { why: 'Same math in a story', problem: { text: 'A recipe uses 2 1/4 cups of flour. You make 1 1/3 batches. How many cups of flour do you need?',
        picture: area(['2', '1/4'], ['1', '1/3'], [8, 1], [3, 1]), answer: 3,
        steps: ['Find 2 1/4 × 1 1/3. Change to fractions: 9/4 and 4/3.', 'Multiply: 9/4 × 4/3 = 36/12.', '36/12 is 3 wholes. So you need 3 cups of flour.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m2-t4', title: 'Divide mixed numbers', skill: 'Divide with mixed numbers by changing them to fractions, then flipping and multiplying',
    bigIdea: 'Change mixed numbers into fractions first. Then flip the one you divide by and multiply.',
    screens: [
      { title: 'Burger patties', text: 'You have 2 1/4 pounds of ground beef. Each patty uses 3/4 pound. How many patties can you make?',
        pictures: [mixed(2, 1, 4)] },
      { title: 'The rule needs one fraction', text: 'Flip and multiply works on fractions. But 2 1/4 is a whole number and a fraction stuck together, so the rule cannot use it yet.',
        pictures: [mixed(2, 1, 4)] },
      { title: 'The big idea', text: 'Change mixed numbers into fractions first. Then flip the one you divide by and multiply.',
        pictures: [bars([...wholes(2, 1, 1, 4), frac(4, 1)]), eq('2 1/4 ÷ 3/4 = 9/4 ÷ 3/4')] },
      { title: 'Cut every pound into fourths', text: 'Each pound is 4 fourths. Two pounds are 8 fourths, and 1 fourth more makes 9. So 2 1/4 = 9/4.',
        pictures: [bars([...wholes(2, 1, 1, 4), frac(4, 1)], true), eq('2 1/4 = 9/4')] },
      { title: 'Now flip and multiply', text: 'Flip 3/4 to 4/3 and multiply: 9/4 × 4/3 = 36/12 = 3.',
        pictures: [bars([...wholes(2, 4, 4), frac(4, 1)], true), eq('9/4 ÷ 3/4', ['= 9/4 × 4/3', '= 36/12', '= 3'])] },
      { title: 'Check with the picture', text: 'Count the fourths: 9. Each patty takes 3 of them. 9 ÷ 3 = 3. So you can make 3 patties.',
        pictures: [bars([...wholes(2, 4, 4), frac(4, 1)]), eq('2 1/4 ÷ 3/4 = 3')] },
      { title: 'One thing not to do', text: "Don't divide the whole number and the fraction on their own. 2 1/4 is one amount. Change it to 9/4 first.",
        pictures: [{ kind: 'cards', wrong: '2 1/4 ÷ 3/4 = 2 1/3', right: '9/4 ÷ 3/4 = 3' }] },
    ],
    turn: {
      text: 'You have 3 3/4 pounds of ground beef. Each patty uses 3/4 pound. How many patties can you make?',
      picture: mixed(3, 3, 4),
      answer: 5,
      steps: ['Change 3 3/4 to a fraction: 3 wholes are 12 fourths, plus 3 fourths makes 15/4.', 'Flip 3/4 and multiply: 15/4 × 4/3 = 60/12.', 'So you can make 5 patties.'],
      prompt: 'Change the mixed number into a fraction. Then flip and multiply.',
      hint1: 'How many fourths are in 3 3/4 pounds?',
      hint2: 'Write 3 3/4 as fourths. Then flip 3/4 and multiply.',
      twin: { text: 'Find 1 2/3 ÷ 2 1/2.',
        picture: eq('1 2/3 ÷ 2 1/2 = ?'),
        answer: { frac: [2, 3] },
        steps: ['Change both: 1 2/3 = 5/3 and 2 1/2 = 5/2.', 'Flip 5/2 and multiply: 5/3 × 2/5 = 10/15.', 'So 1 2/3 ÷ 2 1/2 = 10/15, the same as 2/3.'],
        hint1: 'Change both mixed numbers into fractions before anything else.',
        hint2: 'Flip only the fraction you divide by, then multiply tops and bottoms.' },
    },
    won: { text: 'You changed to a fraction first, then flipped and multiplied.', sticker: 'The answer to a division is called the quotient.' },
    twinWon: { text: 'You changed both mixed numbers first, then flipped and multiplied to get 2/3.', sticker: 'The answer to a division is called the quotient.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Find 2 2/3 ÷ 2/3.',
        picture: mixed(2, 2, 3), answer: 4,
        steps: ['Change 2 2/3 to a fraction: 8/3.', 'Flip 2/3 and multiply: 8/3 × 3/2 = 24/6.', 'So 2 2/3 ÷ 2/3 = 4.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Find 4 1/2 ÷ 1 1/2.',
        picture: mixed(4, 1, 2), answer: 3,
        steps: ['Change both: 4 1/2 = 9/2 and 1 1/2 = 3/2.', 'Flip 3/2 and multiply: 9/2 × 2/3 = 18/6.', 'So 4 1/2 ÷ 1 1/2 = 3.'] } },
      { why: 'Still "change first, then flip"', problem: { text: 'Find 2 1/4 ÷ 1 1/2.',
        picture: mixed(2, 1, 4), answer: { frac: [1, 2], whole: 1 },
        steps: ['Change both: 2 1/4 = 9/4 and 1 1/2 = 3/2.', 'Flip 3/2 and multiply: 9/4 × 2/3 = 18/12, the same as 3/2.', '2/2 makes 1 whole, with 1/2 left. So the answer is 1 1/2.'] } },
      { why: 'A little harder', problem: { text: 'Find 5 1/4 ÷ 2 1/3.',
        picture: mixed(5, 1, 4), answer: { frac: [1, 4], whole: 2 },
        steps: ['Change both: 5 1/4 = 21/4 and 2 1/3 = 7/3.', 'Flip 7/3 and multiply: 21/4 × 3/7 = 63/28, the same as 9/4.', '8/4 makes 2 wholes, with 1/4 left. So the answer is 2 1/4.'] } },
      { why: 'Same math in a story', problem: { text: 'A trail is 7 1/2 miles long. It is split into equal sections of 1 1/4 miles. How many sections are there?',
        picture: mixed(7, 1, 2), answer: 6,
        steps: ['Find 7 1/2 ÷ 1 1/4. Change both: 15/2 and 5/4.', 'Flip 5/4 and multiply: 15/2 × 4/5 = 60/10.', 'So there are 6 sections.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m2-t5', title: 'Fraction division stories', skill: 'Solve "how many fit" stories by dividing fractions',
    bigIdea: 'Ask what the story counts. "How many of this size fit in that amount?" is a division, and the amount you start with comes first.',
    screens: [
      { title: 'Packing trail mix', text: 'You have 3 cups of trail mix. Each serving is 3/4 cup. How many servings can you pack?',
        pictures: [units(3, '1 cup', '3 cups')] },
      { title: 'Which way round?', text: 'The story gives two amounts. Divide them the wrong way round and you get an answer that makes no sense, like less than one serving from 3 cups.',
        pictures: [units(3, '1 cup', '3 cups')] },
      { title: 'The big idea', text: 'Ask what the story counts. "How many of this size fit in that amount?" is a division, and the amount you start with comes first.',
        pictures: [{ kind: 'tape', rows: [
          { label: 'Mix', cells: Array.from({ length: 3 }, () => ({ w: 4, text: '1 cup' })), brace: '3 cups' },
          { label: 'Servings', cells: [{ w: 3, text: '3/4', shade: true }, { w: 9 }] },
        ] }] },
      { title: 'Draw the whole amount', text: 'Draw the 3 cups as one long tape. Cut each cup into 4 fourths. The tape is now 12 fourths long.',
        pictures: [{ kind: 'tape', rows: [{ label: 'Mix', cells: Array.from({ length: 12 }, () => ({ w: 1 })), brace: '3 cups' }], motion: true }] },
      { title: 'Mark off the servings', text: 'One serving is 3 of those fourths. Mark them off: 3, 6, 9, 12. That is 4 servings with nothing left.',
        pictures: [{ kind: 'tape', rows: [
          { label: 'Mix', cells: Array.from({ length: 12 }, () => ({ w: 1 })), brace: '3 cups' },
          { label: 'Servings', cells: Array.from({ length: 4 }, (_, i) => ({ w: 3, text: '3/4', shade: i % 2 === 0 })) },
        ], motion: true }] },
      { title: 'Write the division', text: 'The story asks how many 3/4s fit in 3. That is 3 ÷ 3/4. Flip and multiply: 3 × 4/3 = 12/3 = 4 servings.',
        pictures: [{ kind: 'tape', rows: [
          { label: 'Mix', cells: Array.from({ length: 12 }, () => ({ w: 1 })), brace: '3 cups' },
          { label: 'Servings', cells: Array.from({ length: 4 }, (_, i) => ({ w: 3, text: '3/4', shade: i % 2 === 0 })) },
        ] }, eq('3 ÷ 3/4 = 4', ['3 × 4/3 = 12/3 = 4'])] },
      { title: 'One thing not to do', text: "Don't put the fraction first just because it is smaller. Start with the amount you have, then divide by the size of each piece.",
        pictures: [{ kind: 'cards', wrong: '3/4 ÷ 3 = 1/4 serving', right: '3 ÷ 3/4 = 4 servings' }] },
    ],
    turn: {
      text: 'You have 4 yards of ribbon. Each bow uses 2/3 yard. How many bows can you make?',
      picture: units(4, '1 yd', '4 yards'),
      answer: 6,
      steps: ['The story asks how many 2/3-yard pieces fit in 4 yards, so find 4 ÷ 2/3.', 'Flip and multiply: 4 × 3/2 = 12/2.', 'So you can make 6 bows.'],
      prompt: 'Start with the amount you have. Divide by the size of one bow.',
      hint1: 'What amount do you start with? What size is each bow?',
      hint2: 'Find how many 2/3s fit in 4: that is 4 ÷ 2/3. Flip 2/3 and multiply.',
      twin: { text: 'You have 5 cups of rice. Each serving is 2/3 cup. How many servings is that?',
        picture: units(5, '1 cup', '5 cups'),
        answer: { frac: [1, 2], whole: 7 },
        steps: ['The story asks how many 2/3-cup servings fit in 5 cups, so find 5 ÷ 2/3.', 'Flip and multiply: 5 × 3/2 = 15/2.', '14/2 makes 7 wholes, with 1/2 left. So there are 7 1/2 servings.'],
        hint1: 'Which amount do you start with, and what size is each serving?',
        hint2: 'Start with 5 and divide by 2/3. Flip 2/3, multiply, then change back to a mixed number.' },
    },
    won: { text: 'You saw the story was counting how many fit, and divided the right way round.', sticker: 'In a division, the amount you start with is the dividend. The size of each piece is the divisor.' },
    twinWon: { text: 'You found how many 2/3-cup servings fit in 5 cups: 7 1/2.', sticker: 'In a division, the amount you start with is the dividend. The size of each piece is the divisor.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'You have 6 cups of trail mix. Each serving is 3/4 cup. How many servings can you pack?',
        picture: units(6, '1 cup', '6 cups'), answer: 8,
        steps: ['Find how many 3/4s fit in 6: 6 ÷ 3/4.', 'Flip and multiply: 6 × 4/3 = 24/3.', 'So you can pack 8 servings.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A board is 5 feet long. You cut it into pieces that are each 5/6 foot long. How many pieces do you get?',
        picture: units(5, '1 ft', '5 feet'), answer: 6,
        steps: ['Find how many 5/6s fit in 5: 5 ÷ 5/6.', 'Flip and multiply: 5 × 6/5 = 30/5.', 'So you get 6 pieces.'] } },
      { why: 'Still "how many of this size fit"', problem: { text: 'You have 7/8 pound of cheese. Each sandwich uses 1/8 pound. How many sandwiches can you make?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 7, text: '7/8 lb', shade: true }, { w: 1 }], brace: '1 pound' }] }, answer: 7,
        steps: ['Find how many 1/8s fit in 7/8: 7/8 ÷ 1/8.', 'Flip and multiply: 7/8 × 8/1 = 56/8.', 'So you can make 7 sandwiches.'] } },
      { why: 'A little harder', problem: { text: 'A path is 7 1/2 feet long. Each paving stone is 3/4 foot long. How many stones fit along the path?',
        picture: { kind: 'tape', rows: [{ cells: [...Array.from({ length: 7 }, () => ({ w: 1, text: '1 ft' })), { w: 0.5 }], brace: '7 1/2 feet' }] }, answer: 10,
        steps: ['Find 7 1/2 ÷ 3/4. Change 7 1/2 to 15/2.', 'Flip and multiply: 15/2 × 4/3 = 60/6.', 'So 10 stones fit along the path.'] } },
      { why: 'Same math in a story', problem: { text: 'You have 3 1/3 cups of sugar. Each batch of cookies uses 2/3 cup. How many batches can you bake?',
        picture: { kind: 'tape', rows: [{ cells: [...Array.from({ length: 3 }, () => ({ w: 3, text: '1 cup' })), { w: 1 }], brace: '3 1/3 cups' }] }, answer: 5,
        steps: ['Find 3 1/3 ÷ 2/3. Change 3 1/3 to 10/3.', 'Flip and multiply: 10/3 × 3/2 = 30/6.', 'So you can bake 5 batches.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m2-t6', title: 'Greatest common factor', skill: 'Find the greatest common factor of two numbers by listing factors',
    bigIdea: 'List the factors of both numbers. The biggest number on both lists is the biggest factor they share.',
    screens: [
      { title: 'Gift bags', text: 'You have 12 pencils and 18 erasers. You want identical gift bags that use them all, with nothing left over. What is the largest number of bags you can make?',
        pictures: [{ kind: 'table', head: ['Item', 'How many'], rows: [['Pencils', '12'], ['Erasers', '18']], rowHead: true }] },
      { title: 'Guessing can miss it', text: '2 bags works: 6 pencils and 9 erasers each. 3 bags works too. But is there a bigger number? Trying numbers one at a time is slow, and you might stop too soon.',
        pictures: [{ kind: 'table', head: ['Bags', 'Pencils each', 'Erasers each'], rows: [['2', '6', '9'], ['3', '4', '6']] }] },
      { title: 'The big idea', text: 'List the factors of both numbers. The biggest number on both lists is the biggest factor they share.',
        pictures: [factorTable(true)] },
      { title: 'Factors of 12', text: 'Find every number that divides 12 with nothing left over: 1, 2, 3, 4, 6 and 12.',
        pictures: [factorTable(false)] },
      { title: 'Factors of 18', text: 'Now do the same for 18: 1, 2, 3, 6, 9 and 18.',
        pictures: [factorTable(true)] },
      { title: 'The biggest on both lists', text: '1, 2, 3 and 6 are on both lists. The biggest is 6. So you can make 6 bags, each with 2 pencils and 3 erasers.',
        pictures: [factorTable(true, true), eq('12 ÷ 6 = 2 pencils', ['18 ÷ 6 = 3 erasers'])] },
      { title: 'One thing not to do', text: "Don't stop at the first number that works. Finish both lists and take the biggest number they share.",
        pictures: [{ kind: 'cards', wrong: '12 and 18: 3 bags', right: '12 and 18: 6 bags' }] },
    ],
    turn: {
      text: 'What is the biggest number that is a factor of both 16 and 24?',
      picture: factorQ(16, 24),
      answer: 8,
      steps: ['Factors of 16: 1, 2, 4, 8, 16.', 'Factors of 24: 1, 2, 3, 4, 6, 8, 12, 24.', 'The biggest number on both lists is 8.'],
      prompt: 'List the factors of each number. Find the biggest one on both lists.',
      hint1: 'List every number that divides 16 with nothing left over.',
      hint2: 'Now list the factors of 24. Which numbers are on both lists? Take the biggest.',
      twin: { text: 'What is the biggest number that is a factor of both 15 and 25?',
        picture: factorQ(15, 25),
        answer: 5,
        steps: ['Factors of 15: 1, 3, 5, 15.', 'Factors of 25: 1, 5, 25.', 'The biggest number on both lists is 5.'],
        hint1: 'List every number that divides 15 with nothing left over.',
        hint2: 'Now list the factors of 25. Which is the biggest number on both lists?' },
    },
    won: { text: 'You listed both sets of factors and took the biggest one they share.', sticker: 'The biggest factor two numbers share is their greatest common factor (GCF).' },
    twinWon: { text: 'You listed the factors of 15 and 25 and found 5 on both.', sticker: 'The biggest factor two numbers share is their greatest common factor (GCF).' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What is the biggest number that is a factor of both 8 and 12?',
        picture: factorQ(8, 12), answer: 4,
        steps: ['Factors of 8: 1, 2, 4, 8.', 'Factors of 12: 1, 2, 3, 4, 6, 12.', 'The biggest number on both lists is 4.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is the biggest number that is a factor of both 18 and 27?',
        picture: factorQ(18, 27), answer: 9,
        steps: ['Factors of 18: 1, 2, 3, 6, 9, 18.', 'Factors of 27: 1, 3, 9, 27.', 'The biggest number on both lists is 9.'] } },
      { why: 'Still "biggest on both lists"', problem: { text: 'What is the biggest number that is a factor of both 20 and 30?',
        picture: factorQ(20, 30), answer: 10,
        steps: ['Factors of 20: 1, 2, 4, 5, 10, 20.', 'Factors of 30: 1, 2, 3, 5, 6, 10, 15, 30.', 'The biggest number on both lists is 10.'] } },
      { why: 'A little harder', problem: { text: 'What is the biggest number that is a factor of both 36 and 48?',
        picture: factorQ(36, 48), answer: 12,
        steps: ['Factors of 36: 1, 2, 3, 4, 6, 9, 12, 18, 36.', 'Factors of 48: 1, 2, 3, 4, 6, 8, 12, 16, 24, 48.', 'The biggest number on both lists is 12.'] } },
      { why: 'Same math in a story', problem: { text: 'A florist has 24 roses and 36 tulips. She makes identical bunches that use every flower. What is the largest number of bunches she can make?',
        picture: factorQ(24, 36), answer: 12,
        steps: ['Factors of 24: 1, 2, 3, 4, 6, 8, 12, 24.', 'Factors of 36: 1, 2, 3, 4, 6, 9, 12, 18, 36.', 'The biggest number on both lists is 12, so she can make 12 bunches.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m2-t7', title: 'Least common multiple', skill: 'Find the least common multiple of two numbers by counting by each',
    bigIdea: 'Count by each number. The first number both counts land on is the smallest multiple they share.',
    screens: [
      { title: 'Hot dogs and buns', text: 'Hot dogs come in packs of 6. Buns come in packs of 4. You want the same number of hot dogs and buns. What is the smallest number of each you can buy?',
        pictures: [countBy(6, 0), countBy(4, 0)] },
      { title: 'The packs do not match', text: 'You cannot buy 4 hot dogs, because they come in 6s. You cannot buy 6 buns, because they come in 4s. You need a number both pack sizes can make.',
        pictures: [countBy(6, 1), countBy(4, 1)] },
      { title: 'The big idea', text: 'Count by each number. The first number both counts land on is the smallest multiple they share.',
        pictures: [countBy(6, 4), countBy(4, 6)] },
      { title: 'Count by 6s', text: 'Hot dogs: 6, 12, 18, 24.',
        pictures: [countBy(6, 4, true)] },
      { title: 'Count by 4s', text: 'Buns: 4, 8, 12, 16, 20, 24.',
        pictures: [countBy(6, 4), countBy(4, 6, true)] },
      { title: 'The first place both land', text: 'Both counts land on 12 first. So buy 12 of each: 2 packs of hot dogs and 3 packs of buns.',
        pictures: [countBy(6, 2, false, 12), countBy(4, 3, false, 12)] },
      { title: 'One thing not to do', text: "Don't just multiply the two numbers. 6 × 4 = 24 works, but it is not the smallest. Find the first place both counts meet.",
        pictures: [{ kind: 'cards', wrong: '6 × 4 = 24, so buy 24', right: 'both counts meet at 12 first, so buy 12' }] },
    ],
    turn: {
      text: 'What is the smallest number that is a multiple of both 6 and 8?',
      picture: countQ(6, 8, 32, 16),
      answer: 24,
      steps: ['Count by 6s: 6, 12, 18, 24.', 'Count by 8s: 8, 16, 24.', 'The first number on both counts is 24.'],
      prompt: 'Count by each number. Stop at the first number both counts reach.',
      hint1: 'Count by 6s. Then count by 8s.',
      hint2: 'Write the two counts one under the other. Which number shows up in both first?',
      twin: { text: 'What is the smallest number that is a multiple of both 3 and 5?',
        picture: countQ(3, 5, 20, 20),
        answer: 15,
        steps: ['Count by 3s: 3, 6, 9, 12, 15.', 'Count by 5s: 5, 10, 15.', 'The first number on both counts is 15.'],
        hint1: 'Count by 3s. Then count by 5s.',
        hint2: 'Keep both counts going until they reach the same number.' },
    },
    won: { text: 'You counted by both numbers and found where they first meet.', sticker: 'The smallest multiple two numbers share is their least common multiple (LCM).' },
    twinWon: { text: 'You counted by 3s and 5s until both landed on 15.', sticker: 'The smallest multiple two numbers share is their least common multiple (LCM).' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What is the smallest number that is a multiple of both 4 and 10?',
        picture: countQ(4, 10, 24, 24), answer: 20,
        steps: ['Count by 4s: 4, 8, 12, 16, 20.', 'Count by 10s: 10, 20.', 'The first number on both counts is 20.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is the smallest number that is a multiple of both 6 and 9?',
        picture: countQ(6, 9, 24, 24), answer: 18,
        steps: ['Count by 6s: 6, 12, 18.', 'Count by 9s: 9, 18.', 'The first number on both counts is 18.'] } },
      { why: 'Still "first place both counts land"', problem: { text: 'What is the smallest number that is a multiple of both 5 and 8?',
        picture: countQ(5, 8, 48, 24), answer: 40,
        steps: ['Count by 8s: 8, 16, 24, 32, 40.', 'Check each against 5s: only 40 ends in 0 or 5.', 'The first number on both counts is 40.'] } },
      { why: 'A little harder', problem: { text: 'What is the smallest number that is a multiple of both 12 and 18?',
        picture: countQ(12, 18, 48, 24), answer: 36,
        steps: ['Count by 12s: 12, 24, 36.', 'Count by 18s: 18, 36.', 'The first number on both counts is 36.'] } },
      { why: 'Same math in a story', problem: { text: 'One bus leaves the station every 12 minutes. Another leaves every 15 minutes. They just left together. In how many minutes will they next leave together?',
        picture: countQ(12, 15, 72, 24), answer: 60,
        steps: ['Count by 12s: 12, 24, 36, 48, 60.', 'Count by 15s: 15, 30, 45, 60.', 'They next leave together in 60 minutes.'] } },
    ],
  },
]
