/**
 * Grade 6 · Module 3 — Operations with decimals.
 * Written to docs/new-flow/AUTHORING.md. Continues Grade 5 · Module 4 (decimal operations) and Module 1 (long division).
 * Teaching pictures: `columns` (t1, t2), `longdiv` (t3, t4, t5), `table` (t6).
 */
import type { Lesson, Picture } from '../script'
import { attachChalk } from '../chalk'
import { G6M3_CHALK } from './chalk/g6m3'

const add = (rows: string[]): Picture => ({ kind: 'columns', rows, op: '+', answer: null })
const sub = (rows: string[]): Picture => ({ kind: 'columns', rows, op: '−', answer: null })
const mul = (a: string, b: string): Picture => ({ kind: 'columns', rows: [a, b], op: '×', answer: null })
const ld = (divisor: string, dividend: string): Picture => ({ kind: 'longdiv', divisor, dividend })

/** t1 teaching sum: 12.5 − 3.875, padded so the points line up. */
const trail = (answer?: string, motion = false): Picture => ({ kind: 'columns', rows: ['12.500', ' 3.875'], op: '−', answer, motion })

/** t3 teaching division: 8.52 ÷ 4. The point is one column of the dividend. */
const rope = (quotient?: string, work?: string[]): Picture => ({ kind: 'longdiv', divisor: '4', dividend: '8.52', quotient, work })

/** t5 teaching division: 5,184 ÷ 24. */
const eggs = (quotient?: string, work?: string[]): Picture => ({ kind: 'longdiv', divisor: '24', dividend: '5184', quotient, work })

/** t6: the price-for-one table. */
const PACK = ['Pack', 'Price', 'Price for one']
const packs = (rows: string[][], mark?: [number, number][], motion = false): Picture => ({ kind: 'table', head: PACK, rows, mark, motion })

export const G6M3: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m3-t1', title: 'Add and take away decimals', skill: 'Add and subtract multi-digit decimals to thousandths by lining up the points',
    bigIdea: 'Line up the points, fill each empty place with a 0, then add or take away like whole numbers.',
    screens: [
      { title: 'A long bike ride', text: 'A bike trail is 12.5 kilometers long. You have ridden 3.875 kilometers. How far is left?',
        pictures: [{ kind: 'eq', text: '12.5 − 3.875' }] },
      { title: "The ends don't match", text: 'Can you just line up the last digits? No. The 5 tenths would sit on top of the 5 thousandths. Those are different places.',
        beats: [
          { say: 'Can you just line up the last digits? No.', pic: 0 },
          { say: 'The 5 tenths would sit on top of the 5 thousandths.' },
          { say: 'Those are different places.' },
        ],
        pictures: [{ kind: 'columns', rows: ['12.5', '3.875'], op: '−' }] },
      { title: 'The big idea', text: 'Line up the points, fill each empty place with a 0, then add or take away like whole numbers.',
        beats: [
          { say: 'Line up the points, fill each empty place with a 0, then add or take away like whole numbers.', pic: 0 },
        ],
        pictures: [trail()] },
      { title: 'Fill the empty places', text: "Give 12.5 three places, like 3.875. Write it 12.500. The zeros don't change how much it is.",
        beats: [
          { say: 'Give 12.5 three places, like 3.875. Write it 12.500.', pic: 0 },
          { say: "The zeros don't change how much it is." },
        ],
        pictures: [trail(undefined, true)] },
      { title: 'Take away from the right', text: "Start at the right. 0 − 5 won't go. So trade 1 tenth. It makes 9 hundredths and 10 thousandths. 10 − 5 = 5. 9 − 7 = 2. Tenths. 4 − 8 won't go, so trade 1 one. 14 − 8 = 6.",
        beats: [
          { say: "Start at the right. 0 − 5 won't go.", pic: 0 },
          { say: 'So trade 1 tenth. It makes 9 hundredths and 10 thousandths.' },
          { say: '10 − 5 = 5. 9 − 7 = 2.' },
          { say: "Tenths. 4 − 8 won't go, so trade 1 one. 14 − 8 = 6." },
        ],
        pictures: [trail('8.625', true)] },
      { title: 'Bring the point down', text: "Ones. 1 − 3 won't go, so trade the ten. 11 − 3 = 8. The point comes straight down. So 8.625 kilometers are left.",
        beats: [
          { say: "Ones. 1 − 3 won't go, so trade the ten. 11 − 3 = 8.", pic: 0 },
          { say: 'The point comes straight down. So 8.625 kilometers are left.', pic: 1 },
        ],
        pictures: [trail('8.625'), { kind: 'eq', text: '12.5 − 3.875 = 8.625' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't bring the 7 and 5 DOWN with nothing above them. That gives 8.775. Fill in zeros and trade. It's 8.625. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't bring the 7 and 5 DOWN with nothing above them.", pic: 0 },
          { say: "That gives 8.775. Fill in zeros and trade. It's 8.625." },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '12.5 − 3.875 = 8.775', right: '12.5 − 3.875 = 8.625' }] },
    ],
    turn: {
      text: 'Take away. 15.4 − 6.237 = ?',
      picture: sub(['15.4  ', ' 6.237']),
      answer: 9.163, steps: ['Write 15.4 as 15.400 so both have three places after the point.', 'Thousandths: trade, 10 − 7 = 3. Hundredths: 9 − 3 = 6. Tenths: 3 − 2 = 1. Ones: trade, 15 − 6 = 9.', 'So 15.4 − 6.237 = 9.163.'],
      prompt: 'Line up the points. Fill the empty places with 0s. Take away from the right.',
      hint1: 'How many places after the point does 15.4 need so it matches 6.237?',
      hint2: 'Write 15.400. The thousandths are 0 − 7, so trade from the places to the left.',
      twin: { text: 'Take away. 20.3 − 7.456 = ?',
        picture: sub(['20.3  ', ' 7.456']),
        answer: 12.844, steps: ['Write 20.3 as 20.300 so the points line up.', 'Thousandths: trade, 10 − 6 = 4. Hundredths: 9 − 5 = 4. Tenths: 2 − 4 needs a trade, so 12 − 4 = 8. Ones: 9 − 7 = 2. Tens: 1.', 'So 20.3 − 7.456 = 12.844.'],
        hint1: 'Write 20.3 with three places after the point first.',
        hint2: 'Start with the thousandths: 0 − 6 needs a trade from the places to its left.' },
    },
    won: { text: 'You lined up the points, filled the empty places with 0s, and took away.', sticker: 'Each place after the point is a decimal place. Give both numbers the same decimal places before you start.' },
    twinWon: { text: 'You filled in zeros and found 20.3 − 7.456 = 12.844.', sticker: 'Each place after the point is a decimal place. Give both numbers the same decimal places before you start.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Take away. 14.2 − 5.318 = ?',
        picture: sub(['14.2  ', ' 5.318']), answer: 8.882,
        steps: ['Write 14.2 as 14.200.', 'Thousandths: 10 − 8 = 2. Hundredths: 9 − 1 = 8. Tenths: 11 − 3 = 8. Ones: 13 − 5 = 8.', 'So 14.2 − 5.318 = 8.882.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Add. 36.75 + 8.468 = ?',
        picture: add(['36.75 ', ' 8.468']), answer: 45.218,
        steps: ['Write 36.75 as 36.750.', 'Thousandths: 0 + 8 = 8. Hundredths: 5 + 6 = 11, carry 1. Tenths: 7 + 4 + 1 = 12, carry 1. Ones: 6 + 8 + 1 = 15, carry 1. Tens: 3 + 1 = 4.', 'So 36.75 + 8.468 = 45.218.'] } },
      { why: 'Still "fill the empty places with 0s"', problem: { text: 'Take away. 9 − 2.64 = ?',
        picture: sub(['9   ', '2.64']), answer: 6.36,
        steps: ['9 is the same as 9.00.', 'Hundredths: 10 − 4 = 6. Tenths: 9 − 6 = 3. Ones: 8 − 2 = 6.', 'So 9 − 2.64 = 6.36.'] } },
      { why: 'A little harder', problem: { text: 'Take away. 125.6 − 48.375 = ?',
        picture: sub(['125.6  ', ' 48.375']), answer: 77.225,
        steps: ['Write 125.6 as 125.600.', 'Thousandths: 10 − 5 = 5. Hundredths: 9 − 7 = 2. Tenths: 5 − 3 = 2. Ones: 15 − 8 = 7. Tens: 11 − 4 = 7.', 'So 125.6 − 48.375 = 77.225.'] } },
      { why: 'Same math in a story', problem: { text: 'A hiking trail is 10.2 kilometers long. Ana has walked 3.875 kilometers. How far does she have left?',
        picture: sub(['10.2  ', ' 3.875']), answer: 6.325,
        steps: ['Write 10.2 as 10.200.', 'Thousandths: 10 − 5 = 5. Hundredths: 9 − 7 = 2. Tenths: 11 − 8 = 3. Ones: 9 − 3 = 6.', 'So Ana has 6.325 kilometers left.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m3-t2', title: 'Multiply decimals', skill: 'Multiply two decimals by multiplying whole numbers and counting the places after the point',
    bigIdea: 'Multiply as if there were no points, then give the answer as many places after the point as both numbers have together.',
    screens: [
      { title: 'A garden bed', text: 'A garden bed is 2.4 meters long and 1.3 meters wide. What is its area?',
        pictures: [{ kind: 'columns', rows: ['2.4', '1.3'], op: '×' }] },
      { title: 'Where does the point go?', text: "When you add, you line up the points. But when you multiply, lining them up doesn't help. So where does the point go in the answer?",
        beats: [
          { say: 'When you add, you line up the points.' },
          { say: "But when you multiply, lining them up doesn't help." },
          { say: 'So where does the point go in the answer?', pic: 0 },
        ],
        pictures: [{ kind: 'eq', text: '2.4 × 1.3 = ?' }] },
      { title: 'The big idea', text: 'Multiply as if there were no points, then give the answer as many places after the point as both numbers have together.',
        beats: [
          { say: 'Multiply as if there were no points, then give the answer as many places after the point as both numbers have together.', pic: 0 },
        ],
        pictures: [{ kind: 'columns', rows: ['2.4', '1.3'], op: '×' }] },
      { title: 'Forget the points', text: 'Cover the points. That leaves 24 × 13. 24 × 3 = 72, and 24 × 10 = 240. Add the rows. 72 + 240 = 312.',
        beats: [
          { say: 'Cover the points. That leaves 24 × 13.', pic: 0 },
          { say: '24 × 3 = 72, and 24 × 10 = 240.' },
          { say: 'Add the rows. 72 + 240 = 312.' },
        ],
        pictures: [{ kind: 'columns', rows: ['24', '13'], op: '×', answer: '312', motion: true }] },
      { title: 'Count the places', text: 'Now the point. 2.4 has 1 place after the point. 1.3 has 1 place too. 1 + 1 = 2, so the answer needs 2 places.',
        beats: [
          { say: 'Now the point. 2.4 has 1 place after the point.', pic: 0 },
          { say: '1.3 has 1 place too.' },
          { say: '1 + 1 = 2, so the answer needs 2 places.' },
        ],
        pictures: [{ kind: 'eq', text: '2.4 → 1 place', lines: ['1.3 → 1 place', '1 + 1 = 2 places'] }] },
      { title: 'Put the point in', text: "Start at the right of 312 and count 2 places left. That's 3.12. Is that about right? 2 × 1 = 2 and 3 × 2 = 6, and 3.12 is in between. Yes. So the bed is 3.12 square meters.",
        beats: [
          { say: "Start at the right of 312 and count 2 places left. That's 3.12.", pic: 0 },
          { say: 'Is that about right? 2 × 1 = 2 and 3 × 2 = 6, and 3.12 is in between. Yes.' },
          { say: 'So the bed is 3.12 square meters.', pic: 1 },
        ],
        pictures: [{ kind: 'columns', rows: ['2.4', '1.3'], op: '×', answer: '3.12' }, { kind: 'eq', text: '2.4 × 1.3 = 3.12' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't COPY the point from the numbers above. That gives 31.2. Count the places. 1 + 1 = 2, so it's 3.12. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't COPY the point from the numbers above. That gives 31.2.", pic: 0 },
          { say: "Count the places. 1 + 1 = 2, so it's 3.12." },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '2.4 × 1.3 = 31.2', right: '2.4 × 1.3 = 3.12' }] },
    ],
    turn: {
      text: 'Multiply. 3.2 × 1.4 = ?',
      picture: mul('3.2', '1.4'),
      answer: 4.48, steps: ['Take the points away: 32 × 14 = 448.', '3.2 has 1 place and 1.4 has 1 place, so the answer has 2 places.', 'So 3.2 × 1.4 = 4.48.'],
      prompt: 'Multiply without the points. Count the places. Put the point back.',
      hint1: 'Take the points away. What is 32 × 14?',
      hint2: 'Count the places after the point in 3.2 and in 1.4. Add them up.',
      twin: { text: 'Multiply. 4.3 × 2.1 = ?',
        picture: mul('4.3', '2.1'),
        answer: 9.03, steps: ['Take the points away: 43 × 21 = 903.', '4.3 has 1 place and 2.1 has 1 place, so the answer has 2 places.', 'So 4.3 × 2.1 = 9.03.'],
        hint1: 'Multiply 43 × 21 as if there were no points.',
        hint2: 'How many places after the point are in 4.3 and 2.1 together?' },
    },
    won: { text: 'You multiplied without the points, then counted the places.', sticker: 'The places after the point are decimal places. The answer has as many as both numbers together.' },
    twinWon: { text: 'You counted the places and found 4.3 × 2.1 = 9.03.', sticker: 'The places after the point are decimal places. The answer has as many as both numbers together.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Multiply. 1.6 × 2.3 = ?',
        picture: mul('1.6', '2.3'), answer: 3.68,
        steps: ['16 × 23 = 368.', '1.6 has 1 place and 2.3 has 1 place, so 2 places.', 'So 1.6 × 2.3 = 3.68.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Multiply. 5.4 × 0.6 = ?',
        picture: mul('5.4', '0.6'), answer: 3.24,
        steps: ['54 × 6 = 324.', '5.4 has 1 place and 0.6 has 1 place, so 2 places.', 'So 5.4 × 0.6 = 3.24.'] } },
      { why: 'Still "count the places"', problem: { text: 'Multiply. 0.3 × 0.02 = ?',
        picture: mul('0.3', '0.02'), answer: 0.006,
        steps: ['3 × 2 = 6.', '0.3 has 1 place and 0.02 has 2, so the answer needs 3 places. Put zeros in front of the 6 to fill them.', 'So 0.3 × 0.02 = 0.006.'] } },
      { why: 'A little harder', problem: { text: 'Multiply. 2.46 × 1.3 = ?',
        picture: mul('2.46', '1.3'), answer: 3.198,
        steps: ['246 × 13 = 3,198.', '2.46 has 2 places and 1.3 has 1, so the answer has 3 places.', 'So 2.46 × 1.3 = 3.198.'] } },
      { why: 'Same math in a story', problem: { text: 'One meter of chain weighs 0.35 kilograms. How much do 2.7 meters of chain weigh?',
        picture: mul('0.35', '2.7'), answer: 0.945,
        steps: ['35 × 27 = 945.', '0.35 has 2 places and 2.7 has 1, so the answer has 3 places.', 'So 2.7 meters weigh 0.945 kilograms.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m3-t3', title: 'Divide a decimal by a whole number', skill: 'Divide a decimal by a one-digit whole number with long division',
    bigIdea: 'Put the point in the answer straight above the point inside, then divide like whole numbers.',
    screens: [
      { title: 'Cut the rope', text: 'A rope is 8.52 meters long. You cut it into 4 equal pieces. How long is each piece?',
        pictures: [rope()] },
      { title: 'A point inside', text: 'You know how to divide whole numbers this way. But 8.52 has a point inside it. So where does the point go in the answer?',
        beats: [
          { say: 'You know how to divide whole numbers this way.', pic: 0 },
          { say: 'But 8.52 has a point inside it.' },
          { say: 'So where does the point go in the answer?' },
        ],
        pictures: [rope()] },
      { title: 'The big idea', text: 'Put the point in the answer straight above the point inside, then divide like whole numbers.',
        beats: [
          { say: 'Put the point in the answer straight above the point inside, then divide like whole numbers.', pic: 0 },
        ],
        pictures: [rope(' .')] },
      { title: 'The point goes up first', text: "Before you divide anything, write the point on top. Put it straight above the point in 8.52. Do it first, and it can't get lost.",
        beats: [
          { say: 'Before you divide anything, write the point on top.' },
          { say: 'Put it straight above the point in 8.52.', pic: 0 },
          { say: "Do it first, and it can't get lost." },
        ],
        pictures: [rope(' .')] },
      { title: 'Divide the 8', text: 'Start on the left. How many 4s fit into 8? 2. Write the 2 on top. 2 × 4 = 8, and 8 − 8 = 0. Bring down the 5.',
        beats: [
          { say: 'Start on the left. How many 4s fit into 8? 2.', pic: 0 },
          { say: 'Write the 2 on top. 2 × 4 = 8, and 8 − 8 = 0.' },
          { say: 'Bring down the 5.', pic: 1 },
        ],
        pictures: [rope('2.', ['−8', '  5']),
          { kind: 'table', head: ['Divide', 'Multiply', 'Take away', 'Bring down'], rows: [['8 ÷ 4 = 2', '2 × 4 = 8', '8 − 8 = 0', '5']], motion: true }] },
      { title: 'Keep going', text: '4 fits into 5 one time. 5 − 4 = 1. Bring down the 2 to make 12. 4 fits into 12 three times, with nothing left. So each piece is 2.13 meters long.',
        beats: [
          { say: '4 fits into 5 one time. 5 − 4 = 1.', pic: 0 },
          { say: 'Bring down the 2 to make 12. 4 fits into 12 three times, with nothing left.' },
          { say: 'So each piece is 2.13 meters long.', pic: 1 },
        ],
        pictures: [rope('2.13', ['−8', '  5', '  −4', '  12', '  −12', '   0']), { kind: 'eq', text: '8.52 ÷ 4 = 2.13' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't DROP the point and write 213. That's longer than the whole rope. The point sits straight above, so it's 2.13. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't DROP the point and write 213.", pic: 0 },
          { say: "That's longer than the whole rope. The point sits straight above, so it's 2.13." },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '8.52 ÷ 4 = 213', right: '8.52 ÷ 4 = 2.13' }] },
    ],
    turn: {
      text: 'Divide. 9.45 ÷ 3 = ?',
      picture: ld('3', '9.45'),
      answer: 3.15, steps: ['Put the point on top, right above the point in 9.45.', '3 fits into 9 three times. Bring down the 4: one time, 1 left. Bring down the 5 to make 15: five times.', 'So 9.45 ÷ 3 = 3.15.'],
      prompt: 'Put the point on top first. Then divide like whole numbers.',
      hint1: 'Where does the point go in the answer?',
      hint2: 'Start with 9 ÷ 3. Then bring down the 4 and keep going.',
      twin: { text: 'Divide. 6.72 ÷ 4 = ?',
        picture: ld('4', '6.72'),
        answer: 1.68, steps: ['Put the point on top, right above the point in 6.72.', '4 fits into 6 one time, 2 left. Bring down the 7 to make 27: six times, 3 left. Bring down the 2 to make 32: eight times.', 'So 6.72 ÷ 4 = 1.68.'],
        hint1: 'Write the point on top before you divide.',
        hint2: '4 fits into 6 one time. Take away, bring down the 7, and keep going.' },
    },
    won: { text: 'You put the point on top first, then divided like whole numbers.', sticker: 'The number you divide up is the dividend. The answer is the quotient, and its point sits right above.' },
    twinWon: { text: 'You put the point on top and found 6.72 ÷ 4 = 1.68.', sticker: 'The number you divide up is the dividend. The answer is the quotient, and its point sits right above.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Divide. 8.46 ÷ 2 = ?',
        picture: ld('2', '8.46'), answer: 4.23,
        steps: ['Put the point on top.', '2 fits into 8 four times, into 4 two times, and into 6 three times.', 'So 8.46 ÷ 2 = 4.23.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Divide. 13.5 ÷ 5 = ?',
        picture: ld('5', '13.5'), answer: 2.7,
        steps: ['Put the point on top. 5 fits into 13 two times: 13 − 10 = 3.', 'Bring down the 5 to make 35. 5 fits into 35 seven times.', 'So 13.5 ÷ 5 = 2.7.'] } },
      { why: 'Still "the point goes straight up"', problem: { text: 'Divide. 0.84 ÷ 7 = ?',
        picture: ld('7', '0.84'), answer: 0.12,
        steps: ['Put the point on top. 7 does not fit into 0, so write 0 there.', '7 fits into 8 one time, 1 left. Bring down the 4 to make 14: two times.', 'So 0.84 ÷ 7 = 0.12.'] } },
      { why: 'A little harder', problem: { text: 'Divide. 45.36 ÷ 8 = ?',
        picture: ld('8', '45.36'), answer: 5.67,
        steps: ['Put the point on top. 8 fits into 45 five times: 45 − 40 = 5.', 'Bring down the 3 to make 53: six times, 5 left. Bring down the 6 to make 56: seven times.', 'So 45.36 ÷ 8 = 5.67.'] } },
      { why: 'Same math in a story', problem: { text: 'A rope 22.75 meters long is cut into 7 equal pieces. How long is each piece?',
        picture: ld('7', '22.75'), answer: 3.25,
        steps: ['Put the point on top. 7 fits into 22 three times, 1 left.', 'Bring down the 7 to make 17: two times, 3 left. Bring down the 5 to make 35: five times.', 'So each piece is 3.25 meters long.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m3-t4', title: 'Divide by a decimal', skill: 'Divide by a decimal by multiplying both numbers by 10 or 100 to make the number you divide by whole',
    bigIdea: 'Multiply both numbers by 10 or 100 until the number you divide by is whole, and the answer stays the same.',
    screens: [
      { title: 'Ribbon pieces', text: 'A ribbon is 9.6 meters long. You cut it into pieces that are 0.4 meters long. How many pieces do you get?',
        pictures: [ld('0.4', '9.6')] },
      { title: 'The 0.4 is not whole', text: "You can divide by a whole number. But 0.4 is not whole. How many 0.4s fit in 9.6? That's hard to see.",
        beats: [
          { say: 'You can divide by a whole number.' },
          { say: 'But 0.4 is not whole.', pic: 0 },
          { say: "How many 0.4s fit in 9.6? That's hard to see." },
        ],
        pictures: [ld('0.4', '9.6')] },
      { title: 'The big idea', text: 'Multiply both numbers by 10 or 100 until the number you divide by is whole, and the answer stays the same.',
        beats: [
          { say: 'Multiply both numbers by 10 or 100 until the number you divide by is whole, and the answer stays the same.', pic: 0 },
        ],
        pictures: [{ kind: 'eq', text: '9.6 ÷ 0.4 = 96 ÷ 4' }] },
      { title: 'Grow both, same answer', text: "Why does that work? Look at 6 ÷ 2 = 3. Make both 10 times bigger. 60 ÷ 20 is still 3. Both grew the same, so the answer didn't move.",
        beats: [
          { say: 'Why does that work? Look at 6 ÷ 2 = 3.', pic: 0 },
          { say: 'Make both 10 times bigger. 60 ÷ 20 is still 3.' },
          { say: "Both grew the same, so the answer didn't move." },
        ],
        pictures: [{ kind: 'table', head: ['Divide', 'Answer'], rows: [['6 ÷ 2', '3'], ['60 ÷ 20', '3'], ['600 ÷ 200', '3']], motion: true }] },
      { title: 'Make it whole', text: '0.4 has 1 place after the point, so times 10 makes it 4. Do the same to 9.6. It becomes 96.',
        beats: [
          { say: '0.4 has 1 place after the point, so times 10 makes it 4.', pic: 0 },
          { say: 'Do the same to 9.6. It becomes 96.' },
        ],
        pictures: [{ kind: 'eq', text: '9.6 ÷ 0.4', lines: ['9.6 × 10 = 96', '0.4 × 10 = 4', '96 ÷ 4'] }] },
      { title: 'Now divide', text: 'So 9.6 ÷ 0.4 turns into 96 ÷ 4, one you can do. 4 fits into 9 two times, 1 left. Bring down the 6 to make 16. 4 fits four times, with nothing left. So 9.6 ÷ 0.4 = 24. You get 24 pieces of ribbon.',
        beats: [
          { say: 'So 9.6 ÷ 0.4 turns into 96 ÷ 4, one you can do.', pic: 0 },
          { say: '4 fits into 9 two times, 1 left.' },
          { say: 'Bring down the 6 to make 16. 4 fits four times, with nothing left.' },
          { say: 'So 9.6 ÷ 0.4 = 24. You get 24 pieces of ribbon.', pic: 1 },
        ],
        pictures: [{ kind: 'longdiv', divisor: '4', dividend: '96', quotient: '24', work: ['−8 ', '16', '−16', ' 0'] }, { kind: 'eq', text: '9.6 ÷ 0.4 = 24' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't grow ONLY the 0.4. That gives 2.4, far too few. Grow both numbers. 96 ÷ 4 = 24. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't grow ONLY the 0.4. That gives 2.4, far too few.", pic: 0 },
          { say: 'Grow both numbers. 96 ÷ 4 = 24.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '9.6 ÷ 0.4 → 9.6 ÷ 4', right: '9.6 ÷ 0.4 → 96 ÷ 4' }] },
    ],
    turn: {
      text: 'Divide. 7.2 ÷ 0.3 = ?',
      picture: ld('0.3', '7.2'),
      answer: 24, steps: ['0.3 has 1 place after the point, so multiply both by 10: 72 ÷ 3.', '3 fits into 7 two times, 1 left. Bring down the 2 to make 12: four times.', 'So 7.2 ÷ 0.3 = 24.'],
      prompt: 'Multiply both numbers by 10 or 100 until the outside number is whole. Then divide.',
      hint1: 'What do you multiply 0.3 by to make it whole?',
      hint2: 'Multiply both by 10. Then divide 72 by 3.',
      twin: { text: 'Divide. 1.56 ÷ 0.12 = ?',
        picture: ld('0.12', '1.56'),
        answer: 13, steps: ['0.12 has 2 places after the point, so multiply both by 100: 156 ÷ 12.', '12 fits into 15 one time, 3 left. Bring down the 6 to make 36: three times.', 'So 1.56 ÷ 0.12 = 13.'],
        hint1: 'How many places after the point does 0.12 have? Is 10 enough to make it whole?',
        hint2: 'Multiply both by 100. Then divide 156 by 12.' },
    },
    won: { text: 'You made the outside number whole, then divided.', sticker: 'The number you divide by is the divisor. Make it whole, and move the dividend the same way.' },
    twinWon: { text: 'You multiplied both by 100 and found 1.56 ÷ 0.12 = 13.', sticker: 'The number you divide by is the divisor. Make it whole, and move the dividend the same way.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Divide. 6.3 ÷ 0.7 = ?',
        picture: ld('0.7', '6.3'), answer: 9,
        steps: ['Multiply both by 10: 63 ÷ 7.', '7 × 9 = 63.', 'So 6.3 ÷ 0.7 = 9.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Divide. 2.75 ÷ 0.25 = ?',
        picture: ld('0.25', '2.75'), answer: 11,
        steps: ['0.25 has 2 places, so multiply both by 100: 275 ÷ 25.', '25 fits into 27 one time, 2 left. Bring down the 5 to make 25: one time.', 'So 2.75 ÷ 0.25 = 11.'] } },
      { why: 'Still "make it whole"', problem: { text: 'Divide. 12 ÷ 0.5 = ?',
        picture: ld('0.5', '12'), answer: 24,
        steps: ['Multiply both by 10: 12 becomes 120 and 0.5 becomes 5.', '5 fits into 12 two times, 2 left. Bring down the 0 to make 20: four times.', 'So 12 ÷ 0.5 = 24.'] } },
      { why: 'A little harder', problem: { text: 'Divide. 3.64 ÷ 0.7 = ?',
        picture: ld('0.7', '3.64'), answer: 5.2,
        steps: ['Multiply both by 10: 36.4 ÷ 7.', 'Put the point on top. 7 fits into 36 five times, 1 left. Bring down the 4 to make 14: two times.', 'So 3.64 ÷ 0.7 = 5.2.'] } },
      { why: 'Same math in a story', problem: { text: 'A water bottle holds 0.75 liters. How many bottles can you fill from 9 liters of water?',
        picture: ld('0.75', '9'), answer: 12,
        steps: ['0.75 has 2 places, so multiply both by 100: 900 ÷ 75.', '75 fits into 90 one time, 15 left. Bring down the 0 to make 150: two times.', 'So you can fill 12 bottles.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m3-t5', title: 'Long division with big numbers', skill: 'Divide multi-digit whole numbers by a two-digit number with long division',
    bigIdea: 'Go one digit at a time: guess with a round number, then multiply, take away and bring down.',
    screens: [
      { title: 'Packing eggs', text: 'A farm has 5,184 eggs. Each box holds 24 eggs. How many boxes can the farm fill?',
        pictures: [eggs()] },
      { title: 'Too big to do at once', text: "Nobody knows 5,184 ÷ 24 by heart. And 24 isn't in the times tables. So how do we start? One small piece at a time.",
        beats: [
          { say: 'Nobody knows 5,184 ÷ 24 by heart.', pic: 0 },
          { say: "And 24 isn't in the times tables." },
          { say: 'So how do we start? One small piece at a time.' },
        ],
        pictures: [eggs()] },
      { title: 'The big idea', text: 'Go one digit at a time: guess with a round number, then multiply, take away and bring down.',
        beats: [
          { say: 'Go one digit at a time: guess with a round number, then multiply, take away and bring down.', pic: 0 },
        ],
        pictures: [eggs()] },
      { title: 'The first digit', text: "24 won't fit into 5, so start with 51. Here's the trick: 24 is about 20, and 51 holds two 20s. So try 2. 2 × 24 = 48, which fits. Take it away. 51 − 48 = 3.",
        beats: [
          { say: "24 won't fit into 5, so start with 51.", pic: 0 },
          { say: "Here's the trick: 24 is about 20, and 51 holds two 20s. So try 2." },
          { say: '2 × 24 = 48, which fits.', pic: 1 },
          { say: 'Take it away. 51 − 48 = 3.' },
        ],
        pictures: [eggs(' 2', ['−48', ' 3']),
          { kind: 'table', head: ['Try', '× 24', 'Fits into 51?'], rows: [['2', '48', 'yes'], ['3', '72', 'no']], motion: true }] },
      { title: 'Bring down, again', text: 'Now bring down the 8. That makes 38. 24 fits into 38 one time, so 1 goes on top. And 38 − 24 = 14.',
        beats: [
          { say: 'Now bring down the 8. That makes 38.', pic: 0 },
          { say: '24 fits into 38 one time, so 1 goes on top.' },
          { say: 'And 38 − 24 = 14.' },
        ],
        pictures: [eggs(' 21', ['−48', ' 38', ' −24', ' 14'])] },
      { title: 'The last digit', text: 'Bring down the 4 to make 144. Guess 7. But 7 × 24 = 168, too big. So try 6. 6 × 24 = 144, exactly. Nothing is left, so the farm fills 216 boxes.',
        beats: [
          { say: 'Bring down the 4 to make 144.', pic: 0 },
          { say: 'Guess 7. But 7 × 24 = 168, too big.', pic: 1 },
          { say: 'So try 6. 6 × 24 = 144, exactly.' },
          { say: 'Nothing is left, so the farm fills 216 boxes.' },
        ],
        pictures: [eggs(' 216', ['−48', ' 38', ' −24', ' 144', ' −144', '   0']),
          { kind: 'table', head: ['Try', '× 24', 'Fits into 144?'], rows: [['7', '168', 'no'], ['6', '144', 'yes']], motion: true }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. In 4,920 ÷ 24, 24 won't fit into 12. Don't SKIP that place. Write a 0 on top and bring down the next digit. That makes 205, not 25. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "In 4,920 ÷ 24, 24 won't fit into 12. Don't SKIP that place.", pic: 0 },
          { say: 'Write a 0 on top and bring down the next digit. That makes 205, not 25.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '4,920 ÷ 24 = 25', right: '4,920 ÷ 24 = 205' }] },
    ],
    turn: {
      text: 'Find 4,368 ÷ 24.',
      picture: ld('24', '4368'),
      answer: 182, steps: ['24 fits into 43 one time: 43 − 24 = 19.', 'Bring down the 6 to make 196. 8 × 24 = 192, so 4 left. Bring down the 8 to make 48. 2 × 24 = 48.', 'So 4,368 ÷ 24 = 182.'],
      prompt: 'Guess each digit with a round number. Multiply, take away, bring down.',
      hint1: 'How many times does 24 fit into 43?',
      hint2: '43 − 24 = 19. Bring down the 6, then see how many 24s fit into the new number.',
      twin: { text: 'Find 6,048 ÷ 32.',
        picture: ld('32', '6048'),
        answer: 189, steps: ['32 fits into 60 one time: 60 − 32 = 28.', 'Bring down the 4 to make 284. 8 × 32 = 256, so 28 left. Bring down the 8 to make 288. 9 × 32 = 288.', 'So 6,048 ÷ 32 = 189.'],
        hint1: 'How many times does 32 fit into 60? Think of 32 as about 30.',
        hint2: 'Take away, bring down the 4, then guess how many 32s fit into the new number.' },
    },
    won: { text: 'You divided one digit at a time: divide, multiply, take away, bring down.', sticker: 'In a division, the dividend is shared, the divisor is the size of each group, and the answer is the quotient.' },
    twinWon: { text: 'You divided 6,048 by 32 one digit at a time and got 189.', sticker: 'In a division, the dividend is shared, the divisor is the size of each group, and the answer is the quotient.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Find 3,672 ÷ 24.',
        picture: ld('24', '3672'), answer: 153,
        steps: ['24 fits into 36 one time: 36 − 24 = 12.', 'Bring down the 7 to make 127. 5 × 24 = 120, so 7 left. Bring down the 2 to make 72. 3 × 24 = 72.', 'So 3,672 ÷ 24 = 153.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Find 5,712 ÷ 42.',
        picture: ld('42', '5712'), answer: 136,
        steps: ['42 fits into 57 one time: 57 − 42 = 15.', 'Bring down the 1 to make 151. 3 × 42 = 126, so 25 left. Bring down the 2 to make 252. 6 × 42 = 252.', 'So 5,712 ÷ 42 = 136.'] } },
      { why: 'Still "one digit at a time"', problem: { text: 'Find 7,245 ÷ 35.',
        picture: ld('35', '7245'), answer: 207,
        steps: ['35 fits into 72 two times: 72 − 70 = 2.', 'Bring down the 4 to make 24. 35 does not fit, so write 0 on top. Bring down the 5 to make 245. 7 × 35 = 245.', 'So 7,245 ÷ 35 = 207.'] } },
      { why: 'A little harder', problem: { text: 'Find 38,556 ÷ 51.',
        picture: ld('51', '38556'), answer: 756,
        steps: ['51 does not fit into 38, so start with 385. 7 × 51 = 357, so 28 left.', 'Bring down the 5 to make 285. 5 × 51 = 255, so 30 left. Bring down the 6 to make 306. 6 × 51 = 306.', 'So 38,556 ÷ 51 = 756.'] } },
      { why: 'Same math in a story', problem: { text: 'A truck carries 9,108 cans. They are packed in boxes of 36. How many boxes are on the truck?',
        picture: ld('36', '9108'), answer: 253,
        steps: ['36 fits into 91 two times: 91 − 72 = 19.', 'Bring down the 0 to make 190. 5 × 36 = 180, so 10 left. Bring down the 8 to make 108. 3 × 36 = 108.', 'So the truck carries 253 boxes.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m3-t6', title: 'Money stories', skill: 'Solve money problems with decimals: price for one, the better buy, change and splitting a bill',
    bigIdea: 'Find the price of one in each pack, and the lower price for one is the better buy.',
    screens: [
      { title: 'Juice boxes', text: 'A 4-pack of juice boxes costs $3.00. A 6-pack costs $4.20. Which pack is the better buy?',
        pictures: [packs([['4 boxes', '$3.00', '?'], ['6 boxes', '$4.20', '?']])] },
      { title: 'The price tag tricks you', text: "The 4-pack has the lower price tag. But it also has fewer boxes in it. So is it really the better buy? The tag alone can't tell you.",
        beats: [
          { say: 'The 4-pack has the lower price tag.', pic: 0 },
          { say: 'But it also has fewer boxes in it.' },
          { say: "So is it really the better buy? The tag alone can't tell you." },
        ],
        pictures: [packs([['4 boxes', '$3.00', '?'], ['6 boxes', '$4.20', '?']])] },
      { title: 'The big idea', text: 'Find the price of one in each pack, and the lower price for one is the better buy.',
        beats: [
          { say: 'Find the price of one in each pack, and the lower price for one is the better buy.', pic: 0 },
        ],
        pictures: [packs([['4 boxes', '$3.00', '?'], ['6 boxes', '$4.20', '?']])] },
      { title: 'One box in the 4-pack', text: 'Start with the 4-pack. $3.00 is shared by 4 boxes. How much is one? 3.00 ÷ 4 = 0.75. So one box costs $0.75.',
        beats: [
          { say: 'Start with the 4-pack.' },
          { say: '$3.00 is shared by 4 boxes. How much is one?' },
          { say: '3.00 ÷ 4 = 0.75.' },
          { say: 'So one box costs $0.75.', pic: 0 },
        ],
        pictures: [packs([['4 boxes', '$3.00', '$0.75'], ['6 boxes', '$4.20', '?']], [[0, 2]], true)] },
      { title: 'One box in the 6-pack', text: 'Now the 6-pack, the same way. $4.20 is shared by 6 boxes. 4.20 ÷ 6 = 0.70. So one box costs $0.70.',
        beats: [
          { say: 'Now the 6-pack, the same way.' },
          { say: '$4.20 is shared by 6 boxes.' },
          { say: '4.20 ÷ 6 = 0.70.' },
          { say: 'So one box costs $0.70.', pic: 0 },
        ],
        pictures: [packs([['4 boxes', '$3.00', '$0.75'], ['6 boxes', '$4.20', '$0.70']], [[1, 2]], true)] },
      { title: 'Compare', text: 'Now put the two side by side. $0.70 is less than $0.75. So the 6-pack is the better buy, even with the higher price tag.',
        beats: [
          { say: 'Now put the two side by side.', pic: 0 },
          { say: '$0.70 is less than $0.75.', pic: 1 },
          { say: 'So the 6-pack is the better buy, even with the higher price tag.' },
        ],
        pictures: [packs([['4 boxes', '$3.00', '$0.75'], ['6 boxes', '$4.20', '$0.70']], [[0, 2], [1, 2]]), { kind: 'eq', text: '$0.70 < $0.75' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't just grab the LOWER price tag. $3.00 buys fewer boxes. Compare the price for one. 70 cents beats 75 cents. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't just grab the LOWER price tag. $3.00 buys fewer boxes.", pic: 0 },
          { say: 'Compare the price for one. 70 cents beats 75 cents.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '$3.00 < $4.20, so buy the 4-pack', right: '$0.70 < $0.75, so buy the 6-pack' }] },
    ],
    turn: {
      text: 'Pens come 3 for $2.85 or 5 for $4.60. Which is the better buy?',
      picture: packs([['3 pens', '$2.85', '?'], ['5 pens', '$4.60', '?']]),
      answer: { choices: ['3 for $2.85', '5 for $4.60'], correct: 1 },
      steps: ['One pen in the 3-pack: 2.85 ÷ 3 = 0.95, so $0.95.', 'One pen in the 5-pack: 4.60 ÷ 5 = 0.92, so $0.92. That is less.', 'So 5 for $4.60 is the better buy.'],
      prompt: 'Find the price of one pen in each pack. Pick the lower one.',
      hint1: 'What does one pen cost in each pack?',
      hint2: 'Find $2.85 ÷ 3 and $4.60 ÷ 5. Which is less?',
      twin: { text: 'Yogurt comes 6 cups for $5.10 or 4 cups for $3.56. Which is the better buy?',
        picture: packs([['6 cups', '$5.10', '?'], ['4 cups', '$3.56', '?']]),
        answer: { choices: ['6 for $5.10', '4 for $3.56'], correct: 0 },
        steps: ['One cup in the 6-pack: 5.10 ÷ 6 = 0.85, so $0.85.', 'One cup in the 4-pack: 3.56 ÷ 4 = 0.89, so $0.89.', '$0.85 is less, so 6 for $5.10 is the better buy.'],
        hint1: 'What does one cup cost in each pack?',
        hint2: 'Divide each price by the number of cups. Then compare the two prices for one.' },
    },
    won: { text: 'You found the price of one pen in each pack and picked the lower one.', sticker: 'The price for one is the unit price. The lowest unit price is the better buy.' },
    twinWon: { text: 'You found the price of one cup and picked 6 for $5.10.', sticker: 'The price for one is the unit price. The lowest unit price is the better buy.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Granola bars come 5 for $4.35 or 8 for $6.80. Which is the better buy?',
        picture: packs([['5 bars', '$4.35', '?'], ['8 bars', '$6.80', '?']]),
        answer: { choices: ['5 for $4.35', '8 for $6.80'], correct: 1 },
        steps: ['One bar in the 5-pack: 4.35 ÷ 5 = 0.87.', 'One bar in the 8-pack: 6.80 ÷ 8 = 0.85. That is less.', 'So 8 for $6.80 is the better buy.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A 3-pound bag of apples costs $5.37. What is the price for one pound?',
        picture: { kind: 'table', head: ['Bag', 'Price', 'Price for one pound'], rows: [['3 pounds', '$5.37', '?']] }, answer: 1.79,
        steps: ['Share $5.37 by 3 pounds: 5.37 ÷ 3.', '3 fits into 5 one time, 2 left. 23 ÷ 3 is 7, 2 left. 27 ÷ 3 is 9.', 'So one pound costs $1.79.'] } },
      { why: 'Still "find the price of one"', problem: { text: 'Four friends split a bill of $38.60 equally. How much does each friend pay?',
        picture: { kind: 'table', head: ['Friends', 'Bill', 'Each pays'], rows: [['4', '$38.60', '?']] }, answer: 9.65,
        steps: ['Each friend pays the price for one: 38.60 ÷ 4.', '4 fits into 38 nine times, 2 left. 26 ÷ 4 is 6, 2 left. 20 ÷ 4 is 5.', 'So each friend pays $9.65.'] } },
      { why: 'A little harder', problem: { text: 'You buy 3 notebooks at $2.49 each and pay with a $20 bill. How much change do you get?',
        picture: { kind: 'table', head: ['', 'Amount'], rows: [['3 notebooks at $2.49 each', '?'], ['You pay', '$20.00'], ['Change', '?']] }, answer: 12.53,
        steps: ['3 notebooks cost 3 × 2.49 = 7.47, so $7.47.', 'Take it away from $20.00: 20.00 − 7.47 = 12.53.', 'So your change is $12.53.'] } },
      { why: 'Same math in a story', problem: { text: 'A 1.2-pound bag of cherries costs $4.38. What is the price for one pound?',
        picture: { kind: 'table', head: ['Bag', 'Price', 'Price for one pound'], rows: [['1.2 pounds', '$4.38', '?']] }, answer: 3.65,
        steps: ['Multiply both by 10 so you divide by a whole number: 43.8 ÷ 12.', '12 fits into 43 three times, 7 left. 78 ÷ 12 is 6, 6 left. 60 ÷ 12 is 5.', 'So one pound costs $3.65.'] } },
    ],
  },
]

attachChalk(G6M3, G6M3_CHALK)
