/**
 * Grade 6 · Module 4 — Percentages.
 * Written to docs/new-flow/AUTHORING.md.
 */
import type { Lesson, Picture } from '../script'

/** A 10 × 10 grid with `n` squares shaded: full columns first (tone 1), then the rest of the next column (tone 2). */
const hund = (n: number, motion = false): Picture => {
  const cols = Math.floor(n / 10), extra = n % 10
  const shade: { r: number; c: number; h: number; w: number; tone?: 1 | 2 }[] = []
  if (cols) shade.push({ r: 0, c: 0, h: 10, w: cols, tone: 1 })
  if (extra) shade.push({ r: 0, c: cols, h: extra, w: 1, tone: 2 })
  return { kind: 'grid', rows: 10, cols: 10, shade, motion }
}
const blank: Picture = { kind: 'grid', rows: 10, cols: 10 }

/** A whole as `n` equal percent pieces (top row) over the amounts (bottom row); the first `shade` pieces shaded. */
const pct = (n: number, brace: string, shade = 0, each?: string | (string | undefined)[], motion = false): Picture => ({
  kind: 'tape', motion, rows: [
    { label: 'Percent', cells: Array.from({ length: n }, (_, i) => ({ w: 1, shade: i < shade, text: `${100 / n}%` })), brace: '100%' },
    { label: 'Amount', cells: Array.from({ length: n }, (_, i) => ({ w: 1, shade: i < shade, text: Array.isArray(each) ? each[i] : each })), brace },
  ],
})

/** A price with the tax piece added on the end. */
const taxTape = (price: string, tax: string, brace = 'Total: ?', motion = false): Picture =>
  ({ kind: 'tape', motion, rows: [{ cells: [{ w: 10, text: price }, { w: 1, text: tax, shade: true }], brace }] })

/** What the bank pays, year by year. */
const years = (n: number, pays: string, total?: string[], mark?: [number, number][], motion = false): Picture => ({
  kind: 'table', head: ['Year', ...Array.from({ length: n }, (_, i) => String(i + 1))], rowHead: true, mark, motion,
  rows: [['Bank pays', ...Array(n).fill(pays)], ...(total ? [['In all', ...total]] : [])],
})

export const G6M4: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m4-t1', title: 'Percent means out of 100', skill: 'Read a shaded 100-square grid as a percent',
    bigIdea: 'The sign % means out of 100. So 35 squares out of 100 is 35%.',
    screens: [
      { title: 'Painting a mural', text: 'A school wall has 100 equal tiles. Your class has painted 35 of them. How much of the wall is done?',
        pictures: [hund(35)] },
      { title: '35 tiles of what?', text: 'So we painted 35 tiles. But 35 tiles is a lot on a small wall, and hardly anything on a huge wall. The count on its own does not tell you how much is done. You have to say out of how many.',
        beats: [
          { say: 'So we painted 35 tiles.', pic: 0 },
          { say: 'But 35 tiles is a lot on a small wall, and hardly anything on a huge wall.' },
          { say: 'The count on its own does not tell you how much is done. You have to say out of how many.', write: 'out of how many?' },
        ],
        pictures: [hund(35)] },
      { title: 'The big idea', text: 'The sign % means out of 100. So 35 squares out of 100 is 35%.',
        beats: [
          { say: 'The sign % means out of 100.', pic: 0 },
          { say: 'So 35 squares out of 100 is 35%.' },
        ],
        pictures: [hund(35)] },
      { title: 'One tile out of 100', text: 'Look at the whole wall. It has 100 equal tiles. Now look at just one tile. That is 1 out of 100. And we write that 1%.',
        beats: [
          { say: 'Look at the whole wall. It has 100 equal tiles.', pic: 0 },
          { say: 'Now look at just one tile. That is 1 out of 100.' },
          { say: 'And we write that 1%.', pic: 1 },
        ],
        pictures: [{ kind: 'grid', rows: 10, cols: 10, shade: [{ r: 0, c: 0, h: 1, w: 1, tone: 2 }], motion: true }, { kind: 'eq', text: '1 out of 100 = 1%' }] },
      { title: 'Count the painted tiles', text: "Now let's count what we painted. Count the full columns by 10s: 10, 20, 30. Then 5 more tiles: 35. So that is 35 out of 100.",
        beats: [
          { say: "Now let's count what we painted.", pic: 0 },
          { say: 'Count the full columns by 10s: 10, 20, 30.' },
          { say: 'Then 5 more tiles: 35. So that is 35 out of 100.', pic: 1 },
        ],
        pictures: [hund(35, true), { kind: 'eq', text: '35 out of 100' }] },
      { title: 'Write it with the sign', text: 'So 35 out of 100 is written 35%. The wall is 35% done, and the 65 tiles still bare are 65%. Add those two and you get the whole wall, every time.',
        beats: [
          { say: 'So 35 out of 100 is written 35%.', pic: 0 },
          { say: 'The wall is 35% done, and the 65 tiles still bare are 65%.', pic: 1 },
          { say: 'Add those two and you get the whole wall, every time.', write: 'done % + left % = 100%' },
        ],
        pictures: [hund(35), { kind: 'eq', text: '35% done', lines: ['65% to go'] }] },
      { title: 'One thing not to do', text: 'Here is the slip to watch for. Do not count the empty tiles. Count the painted ones. Those are the tiles that say how much is done.',
        beats: [
          { say: 'Here is the slip to watch for.' },
          { say: 'Do not count the empty tiles.', pic: 0 },
          { say: 'Count the painted ones. Those are the tiles that say how much is done.' },
        ],
        pictures: [{ kind: 'cards', wrong: 'The wall is 65% done', right: 'The wall is 35% done' }] },
    ],
    turn: {
      text: 'This grid has 100 equal squares. What percent of the grid is shaded?',
      picture: hund(42),
      answer: 42, steps: ['The grid has 100 equal squares, so each square is 1%.', 'Count full columns by 10s: 10, 20, 30, 40. Then 2 more makes 42.', '42 out of 100 is 42%, so 42% is shaded.'],
      prompt: 'Count the shaded squares. Out of 100, that count is the percent.',
      hint1: 'Count the full shaded columns by 10s first.',
      hint2: 'After the full columns, add the squares in the column that is not full.',
      twin: { text: 'This grid has 100 equal squares. What percent of the grid is shaded?',
        picture: hund(76),
        answer: 76, steps: ['Each square is 1 out of 100, or 1%.', 'Count full columns: 10, 20, 30, 40, 50, 60, 70. Then 6 more makes 76.', '76 out of 100 is 76%, so 76% is shaded.'],
        hint1: 'Count the full columns by 10s first.',
        hint2: 'After the full columns, count the squares in the column that is only part full.' },
    },
    won: { text: 'You counted the shaded squares out of 100.', sticker: 'Percent means "out of 100". Its sign is %.' },
    twinWon: { text: 'You counted 76 squares out of 100 and wrote 76%.', sticker: 'Percent means "out of 100". Its sign is %.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'This grid has 100 equal squares. What percent is shaded?',
        picture: hund(58), answer: 58,
        steps: ['Each square is 1%.', '5 full columns is 50. Then 8 more makes 58.', 'So 58% is shaded.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'This grid has 100 equal squares. What percent is shaded?',
        picture: hund(9), answer: 9,
        steps: ['No full column is shaded.', 'Count the squares: 9 out of 100.', 'So 9% is shaded.'] } },
      { why: 'Still "out of 100"', problem: { text: '81 squares out of 100 are shaded. What percent is that?',
        picture: blank, answer: 81,
        steps: ['Percent means out of 100.', '81 out of 100 is 81 hundredths of the grid.', 'So it is 81%.'] } },
      { why: 'A little harder', problem: { text: 'This grid has 100 equal squares. What percent is NOT shaded?',
        picture: hund(37), answer: 63,
        steps: ['37 squares are shaded.', 'The rest are not: 100 − 37 = 63 squares.', 'So 63% is not shaded.'] } },
      { why: 'Same math in a story', problem: { text: 'You have one dollar. You spend 65 cents on a snack. What percent of your dollar did you spend?',
        picture: blank, answer: 65,
        steps: ['A dollar is 100 cents.', '65 cents is 65 out of 100.', 'So you spent 65% of your dollar.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m4-t2', title: 'Fraction, decimal, percent', skill: 'Change between a fraction, a decimal and a percent',
    bigIdea: 'A fraction, a decimal and a percent can name the same amount. Make it out of 100 and read all three.',
    screens: [
      { title: 'Three screens, one download', text: 'A game is downloading. One screen says 3/4 done. Another says 0.75. A third says 75%. Do they agree?',
        pictures: [hund(75)] },
      { title: 'They look nothing alike', text: "Look at them side by side. 3/4, 0.75 and 75. Different digits, different shapes. It is hard to believe they could be the same amount. So let's put all three on the same 100 squares and find out.",
        beats: [
          { say: 'Look at them side by side.', pic: 0 },
          { say: '3/4, 0.75 and 75. Different digits, different shapes.' },
          { say: "It is hard to believe they could be the same amount. So let's put all three on the same 100 squares and find out." },
        ],
        pictures: [{ kind: 'eq', text: '3/4   0.75   75%' }] },
      { title: 'The big idea', text: 'A fraction, a decimal and a percent can name the same amount. Make it out of 100 and read all three.',
        beats: [
          { say: 'A fraction, a decimal and a percent can name the same amount.', pic: 0 },
          { say: 'Make it out of 100 and read all three.' },
        ],
        pictures: [hund(75)] },
      { title: 'Make it out of 100', text: 'Start with the fraction. Cut the 100 squares into 4 equal parts. 100 ÷ 4 = 25, so each part is 25 squares. Take 3 of those parts and you have 75 squares. So 3/4 is 75/100.',
        beats: [
          { say: 'Start with the fraction. Cut the 100 squares into 4 equal parts.', pic: 0 },
          { say: '100 ÷ 4 = 25, so each part is 25 squares.', write: '1 part = 25 squares' },
          { say: 'Take 3 of those parts and you have 75 squares. So 3/4 is 75/100.', pic: 1 },
        ],
        pictures: [{ kind: 'grid', rows: 10, cols: 10, split: { col: 5, row: 5 }, motion: true,
          shade: [{ r: 0, c: 0, h: 10, w: 5, tone: 1 }, { r: 0, c: 5, h: 5, w: 5, tone: 1 }] }, { kind: 'eq', text: '3/4 = 75/100' }] },
      { title: 'Read it as a decimal', text: 'Same 75 squares, slid over into columns. 7 full columns and 5 more. 75 out of 100 is 75 hundredths, and 75 hundredths is 0.75.',
        beats: [
          { say: 'Same 75 squares, slid over into columns.', pic: 0 },
          { say: '7 full columns and 5 more.' },
          { say: '75 out of 100 is 75 hundredths, and 75 hundredths is 0.75.', pic: 1 },
        ],
        pictures: [hund(75, true), { kind: 'eq', text: '75/100 = 0.75' }] },
      { title: 'Read it as a percent', text: 'Now the easy one. 75 out of 100 is 75%. So 3/4, 0.75 and 75% are one amount with three names. All three screens were right.',
        beats: [
          { say: 'Now the easy one. 75 out of 100 is 75%.', pic: 0 },
          { say: 'So 3/4, 0.75 and 75% are one amount with three names.', pic: 1 },
          { say: 'All three screens were right.' },
        ],
        pictures: [hund(75), { kind: 'eq', text: '3/4 = 0.75 = 75%' }] },
      { title: 'One thing not to do', text: 'Here is the trap. Do not push the top and bottom numbers together. 3/4 is not 34%. Make it out of 100 first, every time.',
        beats: [
          { say: 'Here is the trap. Do not push the top and bottom numbers together.' },
          { say: '3/4 is not 34%.', pic: 0 },
          { say: 'Make it out of 100 first, every time.', write: 'out of 100 first' },
        ],
        pictures: [{ kind: 'cards', wrong: '3/4 = 34%', right: '3/4 = 75/100 = 75%' }] },
    ],
    turn: {
      text: 'What percent is 1/4?',
      picture: { kind: 'grid', rows: 10, cols: 10, split: { col: 5, row: 5 } },
      answer: 25, steps: ['Cut 100 squares into 4 equal parts: 100 ÷ 4 = 25.', '1/4 is 1 of those parts, so 1/4 = 25/100.', 'So 1/4 is 25%.'],
      prompt: 'Make the fraction out of 100. Then read the percent.',
      hint1: 'How many squares are in each of the 4 equal parts?',
      hint2: 'Split 100 into 4 equal parts. One part, out of 100, is the percent.',
      twin: { text: 'What percent is 2/5?',
        picture: blank,
        answer: 40, steps: ['Cut 100 squares into 5 equal parts: 100 ÷ 5 = 20.', '2/5 is 2 of those parts: 2 × 20 squares, so 2/5 = 40/100.', 'So 2/5 is 40%.'],
        hint1: 'How many squares out of 100 make one fifth?',
        hint2: 'Find one fifth of 100 first. Then take 2 of those parts.' },
    },
    won: { text: 'You made the fraction out of 100 and read the percent.', sticker: 'A fraction, a decimal and a percent that name the same amount are equivalent.' },
    twinWon: { text: 'You made 2/5 out of 100 and found 40%.', sticker: 'A fraction, a decimal and a percent that name the same amount are equivalent.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What percent is 3/10?',
        picture: blank, answer: 30,
        steps: ['100 ÷ 10 = 10, so each tenth is 10 squares.', '3 tenths is 3 × 10 squares, so 3/10 = 30/100.', 'So 3/10 is 30%.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Write 0.64 as a percent.',
        picture: { kind: 'eq', text: '0.64 = ?%' }, answer: 64,
        steps: ['0.64 is 64 hundredths.', '64 hundredths is 64 out of 100.', 'So 0.64 is 64%.'] } },
      { why: 'Still "make it out of 100"', problem: { text: 'Write 45% as a decimal.',
        picture: { kind: 'eq', text: '45% = ?' }, answer: 0.45,
        steps: ['45% is 45 out of 100, or 45 hundredths.', 'Hundredths take two places after the point.', 'So 45% is 0.45.'] } },
      { why: 'A little harder', problem: { text: 'What percent is 7/20?',
        picture: blank, answer: 35,
        steps: ['To make 20 into 100, multiply by 5.', 'Multiply the top by 5 too: 7 × 5 = 35, so 7/20 = 35/100.', 'So 7/20 is 35%.'] } },
      { why: 'Same math in a story', problem: { text: 'A basketball player makes 18 of her 25 free throws. What percent of her free throws does she make?',
        picture: blank, answer: 72,
        steps: ['She makes 18/25 of her shots. To make 25 into 100, multiply by 4.', 'Multiply the top by 4 too: 18 × 4 = 72, so 18/25 = 72/100.', 'So she makes 72% of her free throws.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m4-t3', title: 'Percent of a number', skill: 'Find a percent of a number with a tape diagram',
    bigIdea: 'Cut the whole into 10 equal parts. Each part is 10%. Then take as many parts as you need.',
    screens: [
      { title: 'Money for the shelter', text: 'Your class raised $80 at a bake sale. 30% of it goes to an animal shelter. How much money is that?',
        pictures: [pct(10, '$80')] },
      { title: 'Not $30', text: 'Careful here. 30% does not mean $30. It means 30 out of every 100. But you raised $80, not $100, so the answer has to come out smaller than $30.',
        beats: [
          { say: 'Careful here. 30% does not mean $30.', pic: 0 },
          { say: 'It means 30 out of every 100.', write: '30% = 30 out of 100' },
          { say: 'But you raised $80, not $100, so the answer has to come out smaller than $30.' },
        ],
        pictures: [pct(10, '$80')] },
      { title: 'The big idea', text: 'Cut the whole into 10 equal parts. Each part is 10%. Then take as many parts as you need.',
        beats: [
          { say: 'Cut the whole into 10 equal parts.', pic: 0 },
          { say: 'Each part is 10%.' },
          { say: 'Then take as many parts as you need.' },
        ],
        pictures: [pct(10, '$80')] },
      { title: 'Cut into 10 parts', text: 'Cut the $80 into 10 equal parts. 80 ÷ 10 = 8, so every part is $8. And one part out of ten is 10% of the money.',
        beats: [
          { say: 'Cut the $80 into 10 equal parts.', pic: 0 },
          { say: '80 ÷ 10 = 8, so every part is $8.', pic: 1 },
          { say: 'And one part out of ten is 10% of the money.', write: '10% = whole ÷ 10' },
        ],
        pictures: [pct(10, '$80', 0, '$8', true), { kind: 'eq', text: '10% of 80 = 8' }] },
      { title: 'Take 3 parts', text: 'Now, how many parts do we need? 30% is 3 parts of 10%. Count the money in those 3 parts: 8, 16, 24.',
        beats: [
          { say: 'Now, how many parts do we need? 30% is 3 parts of 10%.', pic: 0 },
          { say: 'Count the money in those 3 parts: 8, 16, 24.', pic: 1 },
        ],
        pictures: [pct(10, '$80', 3, '$8', true), { kind: 'eq', text: '3 × 8 = 24' }] },
      { title: 'Put it together', text: 'So 30% of $80 is $24. That is the money that goes to the shelter. Find one part, then take the parts you need. That works for any percent.',
        beats: [
          { say: 'So 30% of $80 is $24.', pic: 0 },
          { say: 'That is the money that goes to the shelter.', pic: 1 },
          { say: 'Find one part, then take the parts you need. That works for any percent.', write: 'one part first, then count parts' },
        ],
        pictures: [pct(10, '$80', 3, '$8'), { kind: 'eq', text: '30% of 80 = 24', lines: ['80 ÷ 10 = 8', '3 × 8 = 24'] }] },
      { title: 'One thing not to do', text: 'Here is the mistake to dodge. Do not read the 30 as dollars. $80 is less than $100, so 30% of it has to be less than $30.',
        beats: [
          { say: 'Here is the mistake to dodge. Do not read the 30 as dollars.' },
          { say: '$80 is less than $100, so 30% of it has to be less than $30.', pic: 0 },
        ],
        pictures: [{ kind: 'cards', wrong: '30% of $80 = $30', right: '30% of $80 = $24' }] },
    ],
    turn: {
      text: 'What is 40% of 70?',
      picture: pct(10, '70'),
      answer: 28, steps: ['Cut 70 into 10 equal parts: 70 ÷ 10 = 7. Each part is 10%.', '40% is 4 parts: 4 × 7.', 'So 40% of 70 is 28.'],
      prompt: 'Find 10% first. Then take the parts you need.',
      hint1: 'How much is one 10% part of 70?',
      hint2: 'Find 10% first: 70 ÷ 10. Then take 4 of those parts.',
      twin: { text: 'What is 60% of 90?',
        picture: pct(10, '90'),
        answer: 54, steps: ['Cut 90 into 10 equal parts: 90 ÷ 10 = 9. Each part is 10%.', '60% is 6 parts: 6 × 9.', 'So 60% of 90 is 54.'],
        hint1: 'How much is 10% of 90?',
        hint2: 'Find one 10% part first. Then take 6 of those parts.' },
    },
    won: { text: 'You found 10% first, then took 4 parts.', sticker: 'In math, "of" means times. A percent of a number is a part of that number.' },
    twinWon: { text: 'You found 10% of 90 first, then built up 60% to get 54.', sticker: 'In math, "of" means times. A percent of a number is a part of that number.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What is 20% of 60?',
        picture: pct(10, '60'), answer: 12,
        steps: ['60 ÷ 10 = 6, so each 10% part is 6.', '20% is 2 parts: 2 × 6.', 'So 20% of 60 is 12.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is 70% of 30?',
        picture: pct(10, '30'), answer: 21,
        steps: ['30 ÷ 10 = 3, so each 10% part is 3.', '70% is 7 parts: 7 × 3.', 'So 70% of 30 is 21.'] } },
      { why: 'Still "find one part first"', problem: { text: 'What is 25% of 36? Here each part is 25%.',
        picture: pct(4, '36'), answer: 9,
        steps: ['4 parts of 25% make 100%, so cut 36 into 4 equal parts.', 'One part is 36 ÷ 4.', 'So 25% of 36 is 9.'] } },
      { why: 'A little harder', problem: { text: 'What is 75% of 120? Here each part is 25%.',
        picture: pct(4, '120'), answer: 90,
        steps: ['Cut 120 into 4 equal parts: 120 ÷ 4 = 30. Each part is 25%.', '75% is 3 parts: 3 × 30.', 'So 75% of 120 is 90.'] } },
      { why: 'Same math in a story', problem: { text: 'A school has 250 students. 30% of them take the bus. How many students take the bus?',
        picture: pct(10, '250 students'), answer: 75,
        steps: ['250 ÷ 10 = 25, so 10% is 25 students.', '30% is 3 parts: 3 × 25.', 'So 75 students take the bus.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m4-t4', title: 'Find the whole from a part', skill: 'Find the whole when a percent of it is known',
    bigIdea: 'The part you know is some equal pieces of the whole. Find one piece, then count up to 100%.',
    screens: [
      { title: 'Saving for a helmet', text: 'You have saved $15. That is 25% of the price of a bike helmet. How much does the helmet cost?',
        pictures: [pct(4, 'Price: ?', 1, ['$15'])] },
      { title: 'The $15 is only a part', text: 'It is tempting to go and find 25% of $15. Do not. The $15 is the part you already have, not the price. The price is the whole thing, so it has to be bigger than $15.',
        beats: [
          { say: 'It is tempting to go and find 25% of $15. Do not.', pic: 0 },
          { say: 'The $15 is the part you already have, not the price.', write: 'the $15 is a part, not the whole' },
          { say: 'The price is the whole thing, so it has to be bigger than $15.' },
        ],
        pictures: [pct(4, 'Price: ?', 1, ['$15'])] },
      { title: 'The big idea', text: 'The part you know is some equal pieces of the whole. Find one piece, then count up to 100%.',
        beats: [
          { say: 'The part you know is some equal pieces of the whole.', pic: 0 },
          { say: 'Find one piece, then count up to 100%.' },
        ],
        pictures: [pct(4, 'Price: ?', 1, ['$15'])] },
      { title: 'How many pieces make 100%?', text: 'So how many 25% pieces make a whole? 25, 50, 75, 100. That is 4 of them. So the price is 4 equal pieces, and your $15 is one of them.',
        beats: [
          { say: 'So how many 25% pieces make a whole?', pic: 0 },
          { say: '25, 50, 75, 100. That is 4 of them.', pic: 1 },
          { say: 'So the price is 4 equal pieces, and your $15 is one of them.' },
        ],
        pictures: [pct(4, 'Price: ?', 1, ['$15'], true), { kind: 'eq', text: '4 × 25% = 100%' }] },
      { title: 'Every piece is the same', text: 'Here is the move that unlocks it. The pieces are equal. Your piece is $15, so every single piece is $15.',
        beats: [
          { say: 'Here is the move that unlocks it. The pieces are equal.' },
          { say: 'Your piece is $15, so every single piece is $15.', pic: 0 },
        ],
        pictures: [pct(4, 'Price: ?', 4, '$15', true)] },
      { title: 'Count up to 100%', text: 'Now count all 4 pieces. 15, 30, 45, 60. So the helmet costs $60.',
        beats: [
          { say: 'Now count all 4 pieces.', pic: 0 },
          { say: '15, 30, 45, 60.', pic: 1 },
          { say: 'So the helmet costs $60.' },
        ],
        pictures: [pct(4, '$60', 4, '$15'), { kind: 'eq', text: '4 × 15 = 60' }] },
      { title: 'One thing not to do', text: 'Here is the one that catches people. Do not find 25% of the 15. The 15 is the part you were given, so the whole has to come out bigger.',
        beats: [
          { say: 'Here is the one that catches people.' },
          { say: 'Do not find 25% of the 15.', pic: 0 },
          { say: 'The 15 is the part you were given, so the whole has to come out bigger.' },
        ],
        pictures: [{ kind: 'cards', wrong: '15 is 25% of 3.75', right: '15 is 25% of 60' }] },
    ],
    turn: {
      text: '12 is 25% of what number?',
      picture: pct(4, '?', 1, ['12']),
      answer: 48, steps: ['25% is 1 of the 4 equal pieces that make 100%.', 'That piece is 12, so every piece is 12. All 4 pieces: 4 × 12.', 'So 12 is 25% of 48.'],
      prompt: 'Find how many equal pieces make 100%. Then count them all.',
      hint1: 'How many 25% pieces make 100%?',
      hint2: 'Every piece is 12. How much are all the pieces together?',
      twin: { text: '7 is 10% of what number?',
        picture: pct(10, '?', 1, ['7']),
        answer: 70, steps: ['10% is 1 of the 10 equal pieces that make 100%.', 'That piece is 7, so all 10 pieces: 10 × 7.', 'So 7 is 10% of 70.'],
        hint1: 'How many 10% pieces make 100%?',
        hint2: 'Each piece is 7. Count all the pieces that make 100%.' },
    },
    won: { text: 'You found one piece, then counted up to 100%.', sticker: 'The whole is always 100%. A percent of it is a part.' },
    twinWon: { text: 'You saw that 7 is one 10% piece, so the whole is 70.', sticker: 'The whole is always 100%. A percent of it is a part.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '9 is 25% of what number?',
        picture: pct(4, '?', 1, ['9']), answer: 36,
        steps: ['25% is 1 of 4 equal pieces.', 'Every piece is 9, so 4 × 9.', 'So 9 is 25% of 36.'] } },
      { why: 'Same idea, new numbers', problem: { text: '8 is 10% of what number?',
        picture: pct(10, '?', 1, ['8']), answer: 80,
        steps: ['10% is 1 of 10 equal pieces.', 'Every piece is 8, so 10 × 8.', 'So 8 is 10% of 80.'] } },
      { why: 'Still "one piece, then up to 100%"', problem: { text: '35 is 50% of what number?',
        picture: pct(2, '?', 1, ['35']), answer: 70,
        steps: ['50% is 1 of 2 equal pieces.', 'Every piece is 35, so 2 × 35.', 'So 35 is 50% of 70.'] } },
      { why: 'A little harder', problem: { text: '24 is 30% of what number?',
        picture: { kind: 'tape', rows: [
          { label: 'Percent', cells: Array.from({ length: 10 }, (_, i) => ({ w: 1, shade: i < 3, text: '10%' })), brace: '100%' },
          { label: 'Amount', cells: [{ w: 3, text: '24', shade: true }, ...Array.from({ length: 7 }, () => ({ w: 1 }))], brace: '?' },
        ] },
        answer: 80,
        steps: ['30% is 3 of the 10 equal pieces, and those 3 pieces are 24.', 'One piece is 24 ÷ 3 = 8. All 10 pieces: 10 × 8.', 'So 24 is 30% of 80.'] } },
      { why: 'Same math in a story', problem: { text: 'Leo has read 54 pages of a book. That is 75% of the book. How many pages does the book have?',
        picture: { kind: 'tape', rows: [
          { label: 'Percent', cells: Array.from({ length: 4 }, (_, i) => ({ w: 1, shade: i < 3, text: '25%' })), brace: '100%' },
          { label: 'Pages', cells: [{ w: 3, text: '54', shade: true }, { w: 1 }], brace: '?' },
        ] },
        answer: 72,
        steps: ['75% is 3 of the 4 equal pieces, and those 3 pieces are 54 pages.', 'One piece is 54 ÷ 3 = 18 pages. All 4 pieces: 4 × 18.', 'So the book has 72 pages.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m4-t5', title: 'Discounts', skill: 'Find the sale price after a percent off',
    bigIdea: 'Find the money you save first. Then take it away from the price.',
    screens: [
      { title: 'A jacket on sale', text: 'A jacket costs $40. The sign says 25% off. How much do you pay?',
        pictures: [pct(4, '$40')] },
      { title: 'Not $15', text: 'Watch out for this one. 25% off does not mean $25 off, so the price is not $40 − $25. The 25 is out of 100, not dollars.',
        beats: [
          { say: 'Watch out for this one.', pic: 0 },
          { say: '25% off does not mean $25 off, so the price is not $40 − $25.' },
          { say: 'The 25 is out of 100, not dollars.', write: 'the % is out of 100, not dollars' },
        ],
        pictures: [pct(4, '$40')] },
      { title: 'The big idea', text: 'Find the money you save first. Then take it away from the price.',
        beats: [
          { say: 'Find the money you save first.', pic: 0 },
          { say: 'Then take it away from the price.' },
        ],
        pictures: [pct(4, '$40')] },
      { title: 'Find what you save', text: 'Saving first. Cut the $40 into 4 equal pieces of 25%. 40 ÷ 4 = 10, so 25% off saves you $10.',
        beats: [
          { say: 'Saving first. Cut the $40 into 4 equal pieces of 25%.', pic: 0 },
          { say: '40 ÷ 4 = 10, so 25% off saves you $10.', pic: 1 },
        ],
        pictures: [pct(4, '$40', 1, '$10', true), { kind: 'eq', text: '25% of 40 = 10' }] },
      { title: 'Take it away', text: 'Now take that saving off. The shaded piece leaves the price. $40 − $10 = $30.',
        beats: [
          { say: 'Now take that saving off. The shaded piece leaves the price.', pic: 0 },
          { say: '$40 − $10 = $30.', pic: 1 },
        ],
        pictures: [pct(4, '$40', 1, ['$10 off', '$10', '$10', '$10'], true), { kind: 'eq', text: '40 − 10 = 30' }] },
      { title: 'What you pay', text: 'So you pay for the 3 pieces that are left. That is $30, and it is 75% of the price. Save, then subtract. That is the whole job.',
        beats: [
          { say: 'So you pay for the 3 pieces that are left.', pic: 0 },
          { say: 'That is $30, and it is 75% of the price.', pic: 1 },
          { say: 'Save, then subtract. That is the whole job.', write: 'save first, then subtract' },
        ],
        pictures: [pct(4, '$40', 1, ['$10 off', '$10', '$10', '$10']), { kind: 'eq', text: 'You pay $30', lines: ['40 − 10 = 30'] }] },
      { title: 'One thing not to do', text: 'Here is where people stop too early. Do not stop at the money you save. $10 is what comes off. $30 is what you hand over.',
        beats: [
          { say: 'Here is where people stop too early.' },
          { say: 'Do not stop at the money you save.', pic: 0 },
          { say: '$10 is what comes off. $30 is what you hand over.' },
        ],
        pictures: [{ kind: 'cards', wrong: 'You pay $10', right: 'You save $10, so you pay $30' }] },
    ],
    turn: {
      text: 'Shoes cost $60. They are 20% off. What is the sale price, in dollars?',
      picture: pct(10, '$60'),
      answer: 48, steps: ['10% of $60 is 60 ÷ 10 = 6, so 20% is 2 × 6 = $12 off.', 'Take it away from the price: 60 − 12.', 'So the sale price is $48.'],
      prompt: 'Find the money you save. Then take it away from the price.',
      hint1: 'How much money do you save? Find 10% of $60 first.',
      hint2: '20% off is $12 off. Take that away from the price.',
      twin: { text: 'A game costs $80. It is 25% off. What is the sale price, in dollars?',
        picture: pct(4, '$80'),
        answer: 60, steps: ['25% is 1 of 4 equal pieces: 80 ÷ 4 = 20, so you save $20.', 'Take it away from the price: 80 − 20.', 'So the sale price is $60.'],
        hint1: 'How much is one 25% piece of $80?',
        hint2: 'Find the money you save, then take it away from $80.' },
    },
    won: { text: 'You found the money you save, then took it away.', sticker: 'Money taken off a price is called a discount. The price you pay is the sale price.' },
    twinWon: { text: 'You took 25% off $80 and found the sale price, $60.', sticker: 'Money taken off a price is called a discount. The price you pay is the sale price.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A hat costs $20. It is 25% off. What is the sale price, in dollars?',
        picture: pct(4, '$20'), answer: 15,
        steps: ['25% of $20 is 20 ÷ 4 = $5 off.', 'Take it away: 20 − 5.', 'So the sale price is $15.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A backpack costs $50. It is 30% off. What is the sale price, in dollars?',
        picture: pct(10, '$50'), answer: 35,
        steps: ['10% of $50 is $5, so 30% is 3 × 5 = $15 off.', 'Take it away: 50 − 15.', 'So the sale price is $35.'] } },
      { why: 'Still "save first, then take away"', problem: { text: 'A bike lock costs $90. It is 10% off. What is the sale price, in dollars?',
        picture: pct(10, '$90'), answer: 81,
        steps: ['10% of $90 is 90 ÷ 10 = $9 off.', 'Take it away: 90 − 9.', 'So the sale price is $81.'] } },
      { why: 'A little harder', problem: { text: 'A book costs $45. It is 15% off. What is the sale price, in dollars?',
        picture: pct(10, '$45'), answer: 38.25,
        steps: ['10% of $45 is $4.50, and 5% is half of that: $2.25.', 'So 15% off is $4.50 + $2.25 = $6.75 off.', 'Take it away: $45 − $6.75. So the sale price is $38.25.'] } },
      { why: 'Same math in a story', problem: { text: 'Maya wants a skateboard that costs $120. The store takes 35% off. How many dollars does Maya pay?',
        picture: pct(10, '$120'), answer: 78,
        steps: ['10% of $120 is $12, so 30% is $36. 5% is half of $12, which is $6.', '35% off is $36 + $6 = $42 off. Take it away: 120 − 42.', 'So Maya pays $78.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m4-t6', title: 'Sales tax', skill: 'Find the total cost after a percent of tax is added',
    bigIdea: 'Find the tax first. Then add it to the price, so the total is more than the price.',
    screens: [
      { title: 'At the register', text: 'A soccer ball has a price tag of $25. The store adds 8% sales tax at the register. How much do you pay in all?',
        pictures: [taxTape('$25', '8%')] },
      { title: 'The tag is not the total', text: 'The tag says $25, but that is not what you hand over. A little more gets added at the register. And careful: 8% does not mean $8. It means 8 out of every 100.',
        beats: [
          { say: 'The tag says $25, but that is not what you hand over.', pic: 0 },
          { say: 'A little more gets added at the register.' },
          { say: 'And careful: 8% does not mean $8. It means 8 out of every 100.', write: '8% = 8 out of 100' },
        ],
        pictures: [taxTape('$25', '8%')] },
      { title: 'The big idea', text: 'Find the tax first. Then add it to the price, so the total is more than the price.',
        beats: [
          { say: 'Find the tax first.', pic: 0 },
          { say: 'Then add it to the price, so the total is more than the price.' },
        ],
        pictures: [taxTape('$25', '8%')] },
      { title: 'Find 1% first', text: 'The price on the tag is the whole thing, 100%. So 1% of it is 25 ÷ 100, which is $0.25. That is one quarter.',
        beats: [
          { say: 'The price on the tag is the whole thing, 100%.', pic: 0 },
          { say: 'So 1% of it is 25 ÷ 100, which is $0.25. That is one quarter.', pic: 1 },
        ],
        pictures: [taxTape('$25', '8%', 'Total: ?', true), { kind: 'eq', text: '1% of 25 = 0.25' }] },
      { title: 'Find the tax', text: 'Now, 8% is 8 of those quarters. 8 × $0.25 = $2. So the tax is $2.',
        beats: [
          { say: 'Now, 8% is 8 of those quarters.', pic: 0 },
          { say: '8 × $0.25 = $2. So the tax is $2.', pic: 1 },
        ],
        pictures: [taxTape('$25', '$2', 'Total: ?', true), { kind: 'eq', text: '8 × 0.25 = 2' }] },
      { title: 'Add it on', text: 'Last step, and it is the one to remember. Add the tax onto the price: $25 + $2 = $27. That is what you pay at the register.',
        beats: [
          { say: 'Last step, and it is the one to remember.', write: 'tax goes on top of the price' },
          { say: 'Add the tax onto the price: $25 + $2 = $27.', pic: 0 },
          { say: 'That is what you pay at the register.', pic: 1 },
        ],
        pictures: [taxTape('$25', '$2', '$27'), { kind: 'eq', text: '25 + 2 = 27' }] },
      { title: 'One thing not to do', text: 'Here is the slip. Do not add the 8 as dollars. 8% of $25 is $2, not $8.',
        beats: [
          { say: 'Here is the slip. Do not add the 8 as dollars.' },
          { say: '8% of $25 is $2, not $8.', pic: 0 },
        ],
        pictures: [{ kind: 'cards', wrong: '$25 + $8 = $33', right: '$25 + $2 = $27' }] },
    ],
    turn: {
      text: 'A jacket costs $50. The sales tax is 6%. What is the total, in dollars?',
      picture: taxTape('$50', '6%'),
      answer: 53, steps: ['1% of $50 is 50 ÷ 100 = $0.50, so 6% is 6 × $0.50 = $3 of tax.', 'Add the tax to the price: 50 + 3.', 'So the total is $53.'],
      prompt: 'Find the tax. Then add it to the price.',
      hint1: 'Find 1% of $50 first.',
      hint2: 'The tax is 6 of those 1% pieces. Add it to the price.',
      twin: { text: 'A lamp costs $40. The sales tax is 5%. What is the total, in dollars?',
        picture: taxTape('$40', '5%'),
        answer: 42, steps: ['10% of $40 is $4, and 5% is half of that: $2 of tax.', 'Add the tax to the price: 40 + 2.', 'So the total is $42.'],
        hint1: 'Find 10% of $40 first. 5% is half of that.',
        hint2: 'Work out the tax, then add it to $40.' },
    },
    won: { text: 'You found the tax, then added it to the price.', sticker: 'Sales tax is extra money added to a price. It is a percent of the price.' },
    twinWon: { text: 'You found the 5% tax on $40 and a total of $42.', sticker: 'Sales tax is extra money added to a price. It is a percent of the price.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Shoes cost $75. The sales tax is 8%. What is the total, in dollars?',
        picture: taxTape('$75', '8%'), answer: 81,
        steps: ['1% of $75 is $0.75, so 8% is 8 × $0.75 = $6 of tax.', 'Add it: 75 + 6.', 'So the total is $81.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A board game costs $60. The sales tax is 5%. What is the total, in dollars?',
        picture: taxTape('$60', '5%'), answer: 63,
        steps: ['10% of $60 is $6, so 5% is $3 of tax.', 'Add it: 60 + 3.', 'So the total is $63.'] } },
      { why: 'Still "find the tax, then add"', problem: { text: 'A bike costs $200. The sales tax is 7%. What is the total, in dollars?',
        picture: taxTape('$200', '7%'), answer: 214,
        steps: ['1% of $200 is $2, so 7% is 7 × 2 = $14 of tax.', 'Add it: 200 + 14.', 'So the total is $214.'] } },
      { why: 'A little harder', problem: { text: 'A sweater costs $45. The sales tax is 7%. What is the total, in dollars?',
        picture: taxTape('$45', '7%'), answer: 48.15,
        steps: ['1% of $45 is $0.45.', '7% is 7 × $0.45 = $3.15 of tax.', 'Add it: $45 + $3.15. So the total is $48.15.'] } },
      { why: 'Same math in a story', problem: { text: 'Nia buys headphones for $20 and a case for $15. The sales tax is 9%. How many dollars does she pay in all?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 6, text: '$20' }, { w: 4, text: '$15' }, { w: 1, text: '9%', shade: true }], brace: 'Total: ?' }] },
        answer: 38.15,
        steps: ['The price is $20 + $15 = $35.', '1% of $35 is $0.35, so 9% is 9 × $0.35 = $3.15 of tax.', 'Add it: $35 + $3.15. So Nia pays $38.15.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m4-t7', title: 'Simple interest', skill: 'Find simple interest and the total with I = P × r × t',
    bigIdea: 'Find what the bank pays for one year. Every year pays the same, so multiply by the number of years.',
    screens: [
      { title: 'Money in the bank', text: 'You put $500 in a bank. Each year the bank pays you 4% of the $500. How much does the bank pay you in 3 years?',
        pictures: [years(3, '?')] },
      { title: 'Not $4, and not $12', text: 'Two things to be careful about here. 4% does not mean $4 a year. It means 4 out of every 100 dollars. And there are 3 years to count, not one.',
        beats: [
          { say: 'Two things to be careful about here.', pic: 0 },
          { say: '4% does not mean $4 a year. It means 4 out of every 100 dollars.', write: '4% = 4 out of 100' },
          { say: 'And there are 3 years to count, not one.' },
        ],
        pictures: [years(3, '?')] },
      { title: 'The big idea', text: 'Find what the bank pays for one year. Every year pays the same, so multiply by the number of years.',
        beats: [
          { say: 'Find what the bank pays for one year.', pic: 0 },
          { say: 'Every year pays the same, so multiply by the number of years.' },
        ],
        pictures: [years(3, '?')] },
      { title: 'One year', text: 'Start with just one year. 1% of $500 is 500 ÷ 100, which is $5. So 4% is 4 × $5, and that is $20 for the year.',
        beats: [
          { say: 'Start with just one year.', pic: 0 },
          { say: '1% of $500 is 500 ÷ 100, which is $5.', write: '1% of $500 = $5' },
          { say: 'So 4% is 4 × $5, and that is $20 for the year.', pic: 1 },
        ],
        pictures: [{ kind: 'table', head: ['Year', '1', '2', '3'], rowHead: true, rows: [['Bank pays', '$20', '?', '?']], mark: [[0, 1]], motion: true },
          { kind: 'eq', text: '4 × 5 = 20' }] },
      { title: 'Every year the same', text: 'Now here is what makes this one simple. The bank pays 4% of the same $500 every year. So year 2 is $20, and year 3 is $20 too.',
        beats: [
          { say: 'Now here is what makes this one simple.' },
          { say: 'The bank pays 4% of the same $500 every year.', write: 'same $500 every year' },
          { say: 'So year 2 is $20, and year 3 is $20 too.', pic: 0 },
        ],
        pictures: [years(3, '$20', undefined, [[0, 2], [0, 3]], true)] },
      { title: 'Add up the years', text: 'So count up 3 years of $20: 20, 40, 60. The bank pays you $60. Add that to the money you put in and you have $560.',
        beats: [
          { say: 'So count up 3 years of $20: 20, 40, 60.', pic: 0 },
          { say: 'The bank pays you $60.', pic: 1 },
          { say: 'Add that to the money you put in and you have $560.' },
        ],
        pictures: [years(3, '$20', ['$20', '$40', '$60'], [[1, 3]]), { kind: 'eq', text: '3 × 20 = 60', lines: ['500 + 60 = 560'] }] },
      { title: 'One thing not to do', text: 'Here is where it goes wrong. Do not stop at one year. $20 is one year of pay, so 3 years is 3 times as much.',
        beats: [
          { say: 'Here is where it goes wrong. Do not stop at one year.' },
          { say: '$20 is one year of pay, so 3 years is 3 times as much.', pic: 0 },
        ],
        pictures: [{ kind: 'cards', wrong: '3 years: $20', right: '3 years: 3 × $20 = $60' }] },
    ],
    turn: {
      text: 'You put $600 in a bank that pays 3% a year. How many dollars does the bank pay you in 2 years? (Just what the bank pays, not the $600.)',
      picture: years(2, '?'),
      answer: 36, steps: ['1% of $600 is $6, so 3% is 3 × $6 = $18 each year.', 'Every year pays the same $18, so 2 years is 2 × 18.', 'So the bank pays $36.'],
      prompt: 'Find one year first. Then multiply by the years.',
      hint1: 'How much is 1% of $600?',
      hint2: 'Find the pay for one year. Every year pays the same.',
      twin: { text: 'You put $200 in a bank that pays 6% a year. How many dollars does the bank pay you in 4 years? (Just what the bank pays.)',
        picture: years(4, '?'),
        answer: 48, steps: ['1% of $200 is $2, so 6% is 6 × $2 = $12 each year.', 'Every year pays the same $12, so 4 years is 4 × 12.', 'So the bank pays $48.'],
        hint1: 'How much is 1% of $200?',
        hint2: 'Find the pay for one year. Then do it for all 4 years.' },
    },
    won: { text: 'You found one year, then multiplied by the years.', sticker: 'Money a bank pays you is interest. Simple interest = principal (the money you put in) × rate (the percent) × time (the years).' },
    twinWon: { text: 'You found one year of pay on $200, then all 4 years: $48.', sticker: 'Money a bank pays you is interest. Simple interest = principal (the money you put in) × rate (the percent) × time (the years).' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'You put $400 in a bank that pays 5% a year. How much interest do you get in 2 years, in dollars?',
        picture: years(2, '?'), answer: 40,
        steps: ['1% of $400 is $4, so 5% is 5 × $4 = $20 each year.', '2 years is 2 × 20.', 'So the interest is $40.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'You put $800 in a bank that pays 2% a year. How much interest do you get in 3 years, in dollars?',
        picture: years(3, '?'), answer: 48,
        steps: ['1% of $800 is $8, so 2% is 2 × $8 = $16 each year.', '3 years is 3 × 16.', 'So the interest is $48.'] } },
      { why: 'Still "one year, then times the years"', problem: { text: 'You put $100 in a bank that pays 7% a year. How much money do you have IN ALL after 5 years (the $100 and the interest), in dollars?',
        picture: years(5, '?'), answer: 135,
        steps: ['7% of $100 is $7 each year.', '5 years of interest is 5 × 7 = $35. Add it to the $100.', 'So you have $135 in all.'] } },
      { why: 'A little harder', problem: { text: 'You put $1,200 in a bank that pays 3% a year. How much money do you have IN ALL after 4 years, in dollars?',
        picture: years(4, '?'), answer: 1344,
        steps: ['1% of $1,200 is $12, so 3% is 3 × $12 = $36 each year.', '4 years of interest is 4 × 36 = $144.', 'Add it to $1,200. So you have $1,344 in all.'] } },
      { why: 'Same math in a story', problem: { text: 'Omar puts $250 in a savings account that pays 4% a year. How much interest does he earn in 2 years, in dollars?',
        picture: years(2, '?'), answer: 20,
        steps: ['1% of $250 is $2.50, so 4% is 4 × $2.50 = $10 each year.', 'Every year pays the same $10, so 2 years is 2 × 10.', 'So Omar earns $20 in interest.'] } },
    ],
  },
]
