/**
 * Grade 6 · Module 5 — Algebraic expressions and one-step equations.
 * Written to docs/new-flow/AUTHORING.md.
 * Teaching pictures: `tape` (t1–t3, t8), `eq` + `table` (t4, t5), `area` (t6), `balance` + `table` (t7), `numline` (t9).
 * Expressions are always answered as choices; nothing asks the child to type a letter.
 */
import type { Lesson, Picture } from '../script'

const eq = (text: string, lines?: string[]): Picture => ({ kind: 'eq', text, lines })
/** One tape row of labelled cells, each 1 wide unless given as [text, width]. */
const tape = (cells: (string | [string, number])[], brace?: string, motion = false, shadeFirst = false): Picture =>
  ({ kind: 'tape', rows: [{ cells: cells.map((c, i) => typeof c === 'string' ? { w: 1, text: c, shade: shadeFirst && i === 0 } : { w: c[1], text: c[0] }), brace }], motion })
const bal = (left: string, right: string): Picture => ({ kind: 'balance', left, right })
const line = (min: number, max: number, extra: Partial<Extract<Picture, { kind: 'numline' }>> = {}): Picture =>
  ({ kind: 'numline', min, max, ticks: max - min, ...extra })
const sides = (rows: string[][], motion = false): Picture => ({ kind: 'table', head: ['Left side', 'Right side'], rows, motion })
const ORDER = (mark?: [number, number][], motion = false): Picture =>
  ({ kind: 'table', head: ['1st', '2nd', '3rd', '4th'], rows: [['( )', 'exponents', '× ÷', '+ −']], mark, motion })
const bags = (a: string, b: string, cells?: (string | null)[][], motion = false): Picture =>
  ({ kind: 'area', cols: ['x', b], rows: [a], cells, widths: [3, 1], motion })

export const G6M5: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m5-t1', title: 'A letter stands for a number', skill: 'Use a letter for a number you do not know yet, and find the total once you know it',
    bigIdea: 'A letter can stand for a number you do not know yet. When you find out the number, put it where the letter is.',
    screens: [
      { title: 'How many marbles?', text: 'You have a closed bag of marbles and 3 loose marbles. You cannot see inside the bag. How can you write how many marbles you have?',
        pictures: [tape([['?', 3], '3'])] },
      { title: 'No number to write yet', text: 'You do not know how many marbles are in the bag. So you cannot write the total as one number, not yet.',
        pictures: [tape([['?', 3], '3'])] },
      { title: 'The big idea', text: 'A letter can stand for a number you do not know yet. When you find out the number, put it where the letter is.',
        pictures: [tape([['n', 3], '3'], 'n + 3')] },
      { title: 'Call the bag n', text: 'Say the bag holds n marbles. n stands in for the number in the bag. You have n and 3 more, so you have n + 3.',
        pictures: [tape([['n', 3], '3'], 'n + 3', true)] },
      { title: 'Open the bag', text: 'You open the bag and count 5 marbles. So this time n = 5. Put 5 where the n is.',
        pictures: [tape([['5', 3], '3'], '5 + 3', true), eq('n = 5')] },
      { title: 'Work it out', text: 'n + 3 becomes 5 + 3, and that is 8. You have 8 marbles.',
        pictures: [eq('n + 3', ['5 + 3', '8'])] },
      { title: 'One thing not to do', text: "Don't think n means marbles. n is a NUMBER: how many marbles are in the bag.",
        pictures: [{ kind: 'cards', wrong: 'n = marbles', right: 'n = how many marbles' }] },
    ],
    turn: {
      text: 'A box holds n pencils. You also have 4 more pencils, so you have n + 4 pencils. How many pencils is that when n = 6?',
      picture: tape([['n', 3], '4'], 'n + 4'),
      answer: 10, steps: ['n stands for the pencils in the box, and n = 6.', 'Put 6 where the n is: 6 + 4.', 'So you have 10 pencils.'],
      prompt: 'Find what n stands for. Put that number where the n is.',
      hint1: 'What number does n stand for this time?',
      hint2: 'Put 6 in place of n. Then add the 4.',
      twin: { text: 'A jar holds n cookies. You eat 2 of them, so n − 2 cookies are left. How many are left when n = 9?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 4, text: 'n' }] }, { cells: [{ w: 3, text: '?', shade: true }, { w: 1, text: '2' }] }] },
        answer: 7, steps: ['n stands for the cookies in the jar, and n = 9.', 'Put 9 where the n is: 9 − 2.', 'So 7 cookies are left.'],
        hint1: 'What number does n stand for this time?',
        hint2: 'Put 9 in place of n. Then take 2 away.' },
    },
    won: { text: 'You put the number in place of the letter.', sticker: 'A letter that stands for a number is called a variable.' },
    twinWon: { text: 'You put 9 in place of n and found 7 cookies left.', sticker: 'A letter that stands for a number is called a variable.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A bag holds n marbles, and you have 5 more. You have n + 5 marbles. How many is that when n = 7?',
        picture: tape([['n', 3], '5'], 'n + 5'), answer: 12,
        steps: ['n stands for the marbles in the bag, and n = 7.', 'Put 7 where the n is: 7 + 5.', 'So you have 12 marbles.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is n + 8 when n = 11?',
        picture: tape([['n', 3], '8'], 'n + 8'), answer: 19,
        steps: ['This time n = 11.', 'Put 11 in place of n: 11 + 8.', 'So n + 8 is 19.'] } },
      { why: 'Still "put the number in"', problem: { text: 'What is n − 6 when n = 15?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 5, text: 'n' }] }, { cells: [{ w: 3, text: '?', shade: true }, { w: 2, text: '6' }] }] }, answer: 9,
        steps: ['This time n = 15.', 'Put 15 in place of n: 15 − 6.', 'So n − 6 is 9.'] } },
      { why: 'A little harder', problem: { text: 'You have two bags with n marbles in each, and 3 loose marbles. That is n + n + 3. How many marbles is that when n = 8?',
        picture: tape([['n', 3], ['n', 3], '3'], 'n + n + 3'), answer: 19,
        steps: ['Both bags hold n marbles, and n = 8.', 'Put 8 in place of each n: 8 + 8 + 3.', 'So you have 19 marbles.'] } },
      { why: 'Same math in a story', problem: { text: 'A bus has n people on it. At a stop, 4 more get on, so n + 4 people are on the bus. How many is that when n = 23?',
        picture: tape([['n', 4], '4'], 'n + 4'), answer: 27,
        steps: ['n stands for the people already on the bus, and n = 23.', 'Put 23 in place of n: 23 + 4.', 'So there are 27 people on the bus.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m5-t2', title: 'Write an expression from words', skill: 'Turn words like "5 more than n" into letters, numbers and signs',
    bigIdea: 'Each phrase hides an action. "More than" adds, "less than" takes away, and "times" multiplies.',
    screens: [
      { title: 'Say it with a letter', text: 'Mia has n stickers. Jon has 5 more than Mia. How can you write how many stickers Jon has?',
        pictures: [{ kind: 'tape', rows: [{ label: 'Mia', cells: [{ w: 3, text: 'n' }] }, { label: 'Jon', cells: [{ w: 3, text: 'n' }, { w: 1, text: '5' }], brace: '?' }] }] },
      { title: 'The words come in a funny order', text: 'You read "5 more than n" with the 5 first. But Jon starts with the same n as Mia, and then 5 more go on the end.',
        pictures: [{ kind: 'tape', rows: [{ label: 'Mia', cells: [{ w: 3, text: 'n' }] }, { label: 'Jon', cells: [{ w: 3, text: 'n' }, { w: 1, text: '5' }], brace: '?' }] }] },
      { title: 'The big idea', text: 'Each phrase hides an action. "More than" adds, "less than" takes away, and "times" multiplies.',
        pictures: [{ kind: 'tape', rows: [{ label: 'Mia', cells: [{ w: 3, text: 'n' }] }, { label: 'Jon', cells: [{ w: 3, text: 'n' }, { w: 1, text: '5' }], brace: '?' }] }] },
      { title: '"More than" means add', text: 'Jon has Mia\'s n, and then 5 more. Write it as n + 5.',
        pictures: [{ kind: 'tape', rows: [{ label: 'Mia', cells: [{ w: 3, text: 'n' }] }, { label: 'Jon', cells: [{ w: 3, text: 'n' }, { w: 1, text: '5', shade: true }], brace: 'n + 5' }], motion: true }, eq('5 more than n', ['n + 5'])] },
      { title: '"Times" means multiply', text: 'Ali has 3 times as many as Mia. That is three strips of n. Write 3 × n, or just 3n.',
        pictures: [{ kind: 'tape', rows: [{ label: 'Mia', cells: [{ w: 3, text: 'n' }] }, { label: 'Ali', cells: [{ w: 3, text: 'n' }, { w: 3, text: 'n' }, { w: 3, text: 'n' }], brace: '3n' }], motion: true }, eq('3 times n', ['3 × n = 3n'])] },
      { title: '"Less than" means take away', text: 'Zoe has 2 less than Mia. Start with n, then take 2 away. Write n − 2.',
        pictures: [{ kind: 'tape', rows: [{ label: 'Mia', cells: [{ w: 3, text: 'n' }] }, { label: 'Zoe', cells: [{ w: 2, text: 'n − 2', shade: true }] }], motion: true }, eq('2 less than n', ['n − 2'])] },
      { title: 'One thing not to do', text: '"2 less than n" is not 2 − n. Start with n, and then take the 2 away.',
        pictures: [{ kind: 'cards', wrong: '2 less than n → 2 − n', right: '2 less than n → n − 2' }] },
    ],
    turn: {
      text: 'Which shows "7 more than n"?',
      picture: eq('7 more than n'),
      answer: { choices: ['n + 7', '7n', 'n − 7', '7 − n'], correct: 0 },
      steps: ['"More than" means add.', 'Start with n, and add 7 to it.', 'So it is n + 7.'],
      prompt: 'Find the action word. Then write it with n.',
      hint1: 'Which action does "more than" mean?',
      hint2: '"More than" means you add. Start with n.',
      twin: { text: 'Which shows "4 times a number n"?',
        picture: eq('4 times n'),
        answer: { choices: ['n + 4', '4n', 'n − 4', '4 − n'], correct: 1 },
        steps: ['"Times" means multiply.', 'Multiply the number n by 4.', 'So it is 4n.'],
        hint1: 'Which action does "times" mean?',
        hint2: 'You multiply n by 4. How do you write a number times a letter?' },
    },
    won: { text: 'You found the action word and wrote it with n.', sticker: 'Letters and numbers joined by +, −, × or ÷, like 4n, make an expression.' },
    twinWon: { text: 'You saw "times" and wrote 4n.', sticker: 'Letters and numbers joined by +, −, × or ÷, like 4n, make an expression.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which shows "9 more than n"?',
        picture: eq('9 more than n'), answer: { choices: ['n + 9', '9n', 'n − 9', '9 − n'], correct: 0 },
        steps: ['"More than" means add.', 'Start with n, and add 9 to it.', 'So it is n + 9.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Which shows "6 times a number n"?',
        picture: eq('6 times n'), answer: { choices: ['n + 6', '6n', 'n − 6', 'n ÷ 6'], correct: 1 },
        steps: ['"Times" means multiply.', 'Multiply the number n by 6.', 'So it is 6n.'] } },
      { why: 'Still "find the action word"', problem: { text: 'Which shows "3 less than n"?',
        picture: eq('3 less than n'), answer: { choices: ['3 − n', 'n − 3', '3n', 'n + 3'], correct: 1 },
        steps: ['"Less than" means take away.', 'Start with n, then take 3 away. The n comes first.', 'So it is n − 3.'] } },
      { why: 'A little harder', problem: { text: 'Which shows "5 more than 2 times n"?',
        picture: eq('5 more than 2 times n'), answer: { choices: ['2n + 5', '2(n + 5)', '5n + 2', '2 + 5n'], correct: 0 },
        steps: ['First, 2 times n is 2n.', '"5 more than" that means add 5 to 2n.', 'So it is 2n + 5.'] } },
      { why: 'Same math in a story', problem: { text: 'Tickets cost 8 dollars each. Which shows the cost, in dollars, of t tickets?',
        picture: eq('t tickets at 8 dollars each'), answer: { choices: ['t + 8', '8t', 't − 8', '8 − t'], correct: 1 },
        steps: ['Each ticket costs 8 dollars, so t tickets cost t times 8.', '"Times" means multiply, and we write the number first.', 'So it is 8t.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m5-t3', title: 'Work out an expression', skill: 'Find the value of an expression when you know what each letter stands for',
    bigIdea: 'Put each number in place of its letter. Then do the math.',
    screens: [
      { title: 'Party shopping', text: 'Cupcakes cost 3 dollars each, and a card costs 2 dollars. For n cupcakes and a card you pay 3n + 2 dollars. What do you pay for 4 cupcakes?',
        pictures: [tape(['n', 'n', 'n', '2'], '3n + 2')] },
      { title: 'The letter is in the way', text: 'You cannot add 3n and 2 while n is still a letter. You need to know the number first.',
        pictures: [tape(['n', 'n', 'n', '2'], '3n + 2')] },
      { title: 'The big idea', text: 'Put each number in place of its letter. Then do the math.',
        pictures: [tape(['n', 'n', 'n', '2'], '3n + 2')] },
      { title: 'Put the number in', text: 'You buy 4 cupcakes, so n = 4. Every n becomes 4. 3n means 3 × n, so it becomes 3 × 4.',
        pictures: [tape(['4', '4', '4', '2'], '3 × 4 + 2', true), eq('3n + 2', ['3 × 4 + 2'])] },
      { title: 'Do the math', text: 'Multiply first: 3 × 4 = 12. Then add the 2: 12 + 2 = 14. You pay 14 dollars.',
        pictures: [tape(['4', '4', '4', '2'], '14', true), eq('3 × 4 + 2', ['12 + 2', '14'])] },
      { title: 'Two letters work the same way', text: 'For a + b with a = 6 and b = 5, put 6 where a is and 5 where b is: 6 + 5 = 11.',
        pictures: [tape(['6', '5'], '11', true), eq('a + b', ['6 + 5', '11'])] },
      { title: 'One thing not to do', text: "Don't stick the number onto the 3. When n = 4, 3n is 3 × 4 = 12, not 34.",
        pictures: [{ kind: 'cards', wrong: '3n = 34', right: '3n = 3 × 4 = 12' }] },
    ],
    turn: {
      text: 'What is 2n + 5 when n = 6?',
      picture: tape(['n', 'n', '5'], '2n + 5'),
      answer: 17, steps: ['2n means 2 × n, and n = 6.', 'Put 6 in: 2 × 6 + 5.', 'Multiply first: 12 + 5 = 17.'],
      prompt: 'Put the number where the letter is. Then do the math.',
      hint1: 'What does 2n mean?',
      hint2: 'Put 6 in place of n. Multiply before you add.',
      twin: { text: 'What is 4n − 3 when n = 7?',
        picture: eq('4n − 3'),
        answer: 25, steps: ['4n means 4 × n, and n = 7.', 'Put 7 in: 4 × 7 − 3.', 'Multiply first: 28 − 3 = 25.'],
        hint1: 'What does 4n mean?',
        hint2: 'Put 7 in place of n. Multiply before you take away.' },
    },
    won: { text: 'You put the number in place of the letter, then did the math.', sticker: 'Working out an expression for a given number is called evaluating it.' },
    twinWon: { text: 'You put 7 in for n and worked out 4n − 3.', sticker: 'Working out an expression for a given number is called evaluating it.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What is 3n + 4 when n = 5?',
        picture: tape(['n', 'n', 'n', '4'], '3n + 4'), answer: 19,
        steps: ['3n means 3 × n, and n = 5.', 'Put 5 in: 3 × 5 + 4.', 'Multiply first: 15 + 4 = 19.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is 5n − 2 when n = 3?',
        picture: eq('5n − 2'), answer: 13,
        steps: ['5n means 5 × n, and n = 3.', 'Put 3 in: 5 × 3 − 2.', 'Multiply first: 15 − 2 = 13.'] } },
      { why: 'Still "put it in, then do the math"', problem: { text: 'What is a + b when a = 14 and b = 9?',
        picture: tape(['a', 'b'], 'a + b'), answer: 23,
        steps: ['Put 14 where a is and 9 where b is.', 'That makes 14 + 9.', 'So a + b = 23.'] } },
      { why: 'A little harder', problem: { text: 'What is 2a + b when a = 8 and b = 6?',
        picture: eq('2a + b'), answer: 22,
        steps: ['2a means 2 × a. Put 8 for a and 6 for b.', 'That makes 2 × 8 + 6.', 'Multiply first: 16 + 6 = 22.'] } },
      { why: 'Same math in a story', problem: { text: 'A taxi ride costs 3 dollars to start, plus 2 dollars for each mile. For m miles it costs 2m + 3 dollars. How many dollars does a 9-mile ride cost?',
        picture: eq('2m + 3'), answer: 21,
        steps: ['The ride is 9 miles, so m = 9.', 'Put 9 in: 2 × 9 + 3.', 'Multiply first: 18 + 3 = 21, so it costs 21 dollars.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m5-t4', title: 'Exponents', skill: 'Read a small raised number as how many times to multiply a number by itself',
    bigIdea: 'The small raised number says how many times to multiply the big number by itself. 4³ = 4 × 4 × 4.',
    screens: [
      { title: 'A shop full of toys', text: 'A toy shop has 4 shelves. Each shelf has 4 boxes. Each box holds 4 toys. How many toys are there?',
        pictures: [{ kind: 'table', head: ['Shelves', 'Boxes on each shelf', 'Toys in each box'], rows: [['4', '4', '4']] }] },
      { title: 'Long to write', text: 'You could write 4 × 4 × 4. But a longer one, like 4 × 4 × 4 × 4 × 4 × 4, is slow to write and easy to miscount.',
        pictures: [eq('4 × 4 × 4 × 4 × 4 × 4')] },
      { title: 'The big idea', text: 'The small raised number says how many times to multiply the big number by itself. 4³ = 4 × 4 × 4.',
        pictures: [eq('4³ = 4 × 4 × 4')] },
      { title: 'Read the small number', text: 'In 4³ the small 3 says: write the 4 three times, with × between them.',
        pictures: [{ kind: 'table', head: ['4¹', '4²', '4³'], rows: [['4', '4 × 4', '4 × 4 × 4']], mark: [[0, 2]], motion: true }] },
      { title: 'Multiply step by step', text: '4 × 4 = 16. Then 16 × 4 = 64. So 4³ = 64, and the shop has 64 toys.',
        pictures: [eq('4 × 4 × 4', ['16 × 4', '64'])] },
      { title: 'Squared and cubed', text: '5² is 5 × 5 = 25. We say "5 squared". 2³ is 2 × 2 × 2 = 8. We say "2 cubed".',
        pictures: [{ kind: 'table', head: ['', 'means', 'is'], rows: [['5²', '5 × 5', '25'], ['2³', '2 × 2 × 2', '8']], rowHead: true, motion: true }] },
      { title: 'One thing not to do', text: "Don't multiply the two numbers together. 4³ is not 4 × 3 = 12. It is 4 × 4 × 4 = 64.",
        pictures: [{ kind: 'cards', wrong: '4³ = 4 × 3 = 12', right: '4³ = 4 × 4 × 4 = 64' }] },
    ],
    turn: {
      text: 'What is 3³?',
      picture: eq('3³'),
      answer: 27, steps: ['3³ means three 3s multiplied: 3 × 3 × 3.', '3 × 3 = 9, then 9 × 3.', 'So 3³ = 27.'],
      prompt: 'Write the big number as many times as the small number says. Then multiply.',
      hint1: 'How many 3s does the small number say to multiply?',
      hint2: 'Write 3 × 3 × 3. Multiply the first two, then multiply by 3 again.',
      twin: { text: 'What is 2⁵?',
        picture: eq('2⁵'),
        answer: 32, steps: ['2⁵ means five 2s multiplied: 2 × 2 × 2 × 2 × 2.', 'Keep doubling: 2, 4, 8, 16, then double once more.', 'So 2⁵ = 32.'],
        hint1: 'How many 2s does the small number say to multiply?',
        hint2: 'Write five 2s with × between them. Keep doubling.' },
    },
    won: { text: 'You multiplied the number by itself as many times as the small number said.', sticker: 'In 4³, 4 is the base and 3 is the exponent.' },
    twinWon: { text: 'You multiplied five 2s and got 32.', sticker: 'In 2⁵, 2 is the base and the small raised number is the exponent.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What is 5³?',
        picture: eq('5³'), answer: 125,
        steps: ['5³ means 5 × 5 × 5.', '5 × 5 = 25, then 25 × 5.', 'So 5³ = 125.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is 6²?',
        picture: eq('6²'), answer: 36,
        steps: ['6² means two 6s multiplied.', 'That is 6 × 6.', 'So 6² = 36.'] } },
      { why: 'Still "multiply it by itself"', problem: { text: 'What is 10⁴?',
        picture: eq('10⁴'), answer: 10000,
        steps: ['10⁴ means four 10s: 10 × 10 × 10 × 10.', 'Each 10 adds a zero: 100, 1,000, then one more zero.', 'So 10⁴ = 10,000.'] } },
      { why: 'A little harder', problem: { text: 'What is 3⁴?',
        picture: eq('3⁴'), answer: 81,
        steps: ['3⁴ means 3 × 3 × 3 × 3.', '3 × 3 = 9, 9 × 3 = 27, then 27 × 3.', 'So 3⁴ = 81.'] } },
      { why: 'Same math in a story', problem: { text: 'A square garden is 7 feet long on each side. Its area in square feet is 7². What is the area, in square feet?',
        picture: eq('7 feet by 7 feet'), answer: 49,
        steps: ['7² means 7 × 7.', 'A square has the same length on both sides, so multiply 7 by 7.', 'So the area is 49 square feet.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m5-t5', title: 'Order of operations', skill: 'Work out a problem with parentheses, exponents, × ÷ and + − in the agreed order',
    bigIdea: 'Parentheses first, then exponents. Then × and ÷, then + and −, each from left to right.',
    screens: [
      { title: 'Two different answers', text: 'Two friends work out 2 + 3 × 4². One gets 80. The other gets 50. They cannot both be right. Who is?',
        pictures: [eq('2 + 3 × 4²')] },
      { title: 'Left to right is not enough', text: 'Going left to right, 2 + 3 = 5, then 5 × 16 = 80. But everyone agreed on a different order, so the whole world gets the same answer.',
        pictures: [eq('2 + 3 × 4²')] },
      { title: 'The big idea', text: 'Parentheses first, then exponents. Then × and ÷, then + and −, each from left to right.',
        pictures: [ORDER()] },
      { title: 'Exponents first here', text: 'There are no parentheses. So do the exponent first: 4² = 4 × 4 = 16.',
        pictures: [ORDER([[0, 1]], true), eq('2 + 3 × 4²', ['2 + 3 × 16'])] },
      { title: 'Then ×, then +', text: 'Multiply next: 3 × 16 = 48. Add last: 2 + 48 = 50. The friend who got 50 is right.',
        pictures: [ORDER([[0, 2], [0, 3]], true), eq('2 + 3 × 16', ['2 + 48', '50'])] },
      { title: 'Parentheses come first', text: 'With parentheses, (2 + 3) × 4², you work out 2 + 3 = 5 first. Then 4² = 16. Then 5 × 16 = 80.',
        pictures: [ORDER([[0, 0]], true), eq('(2 + 3) × 4²', ['5 × 4²', '5 × 16', '80'])] },
      { title: 'One thing not to do', text: "Don't just go left to right. Multiply before you add: 2 + 3 × 16 is 50, not 80.",
        pictures: [{ kind: 'cards', wrong: '2 + 3 × 16 = 5 × 16 = 80', right: '2 + 3 × 16 = 2 + 48 = 50' }] },
    ],
    turn: {
      text: 'What is 5 + 2 × 3²?',
      picture: eq('5 + 2 × 3²'),
      answer: 23, steps: ['Exponent first: 3² = 9, so 5 + 2 × 9.', 'Multiply next: 2 × 9 = 18.', 'Add last: 5 + 18 = 23.'],
      prompt: 'Parentheses, then exponents, then × and ÷, then + and −.',
      hint1: 'There are no parentheses. Which part do you work out first?',
      hint2: 'Work out 3² first. Then multiply before you add.',
      twin: { text: 'What is (1 + 3)² − 2 × 5?',
        picture: eq('(1 + 3)² − 2 × 5'),
        answer: 6, steps: ['Parentheses first: 1 + 3 = 4.', 'Exponent next: 4² = 16. Then multiply: 2 × 5 = 10.', 'Subtract last: 16 − 10 = 6.'],
        hint1: 'Which part do you work out first?',
        hint2: 'Start inside the parentheses. Then square what you get.' },
    },
    won: { text: 'You followed the order, one step at a time.', sticker: 'This agreed order is called the order of operations.' },
    twinWon: { text: 'You did the parentheses first and got 6.', sticker: 'This agreed order is called the order of operations.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'What is 4 + 3 × 2²?',
        picture: eq('4 + 3 × 2²'), answer: 16,
        steps: ['Exponent first: 2² = 4, so 4 + 3 × 4.', 'Multiply next: 3 × 4 = 12.', 'Add last: 4 + 12 = 16.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is 20 − 2 × 3²?',
        picture: eq('20 − 2 × 3²'), answer: 2,
        steps: ['Exponent first: 3² = 9.', 'Multiply next: 2 × 9 = 18.', 'Subtract last: 20 − 18 = 2.'] } },
      { why: 'Still "follow the order"', problem: { text: 'What is (3 + 2)² − 5?',
        picture: eq('(3 + 2)² − 5'), answer: 20,
        steps: ['Parentheses first: 3 + 2 = 5.', 'Exponent next: 5² = 25.', 'Subtract last: 25 − 5 = 20.'] } },
      { why: 'A little harder', problem: { text: 'What is 2³ + 12 ÷ (5 − 2)?',
        picture: eq('2³ + 12 ÷ (5 − 2)'), answer: 12,
        steps: ['Parentheses first: 5 − 2 = 3.', 'Exponent: 2³ = 8. Then divide: 12 ÷ 3 = 4.', 'Add last: 8 + 4 = 12.'] } },
      { why: 'Same math in a story', problem: { text: 'Leo has 10 stickers. He buys 3 sheets with 4 stickers on each. He has 10 + 3 × 4 stickers now. How many is that?',
        picture: eq('10 + 3 × 4'), answer: 22,
        steps: ['Multiply first: 3 sheets of 4 is 3 × 4 = 12.', 'Add last: 10 + 12.', 'So Leo has 22 stickers.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m5-t6', title: 'Equivalent expressions', skill: 'Rewrite an expression so it looks different but always means the same amount',
    bigIdea: 'Two ways of writing can mean the same amount. 3(x + 2) is 3 groups of x + 2, which is 3x + 6.',
    screens: [
      { title: 'Three gift bags', text: 'Each gift bag holds x pens and 2 erasers. You pack 3 bags. How can you write how many things you packed?',
        pictures: [bags('3', '2')] },
      { title: 'x and 2 do not join', text: 'You do not know x, so x + 2 cannot become one number. You need another way to write 3 bags of it.',
        pictures: [bags('3', '2')] },
      { title: 'The big idea', text: 'Two ways of writing can mean the same amount. 3(x + 2) is 3 groups of x + 2, which is 3x + 6.',
        pictures: [bags('3', '2', [['3x', '6']])] },
      { title: 'Keep the bag together', text: '3 bags of x + 2 is written 3(x + 2). The parentheses keep x + 2 together as one bag.',
        pictures: [bags('3', '2', undefined, true), eq('3 bags of x + 2', ['3(x + 2)'])] },
      { title: 'Multiply each part', text: 'The 3 multiplies each part of the bag. 3 times x is 3x. 3 times 2 is 6.',
        pictures: [bags('3', '2', [['3x', '6']], true)] },
      { title: 'Put the parts together', text: 'So 3(x + 2) = 3x + 6. Check with x = 4: 3 × 6 = 18, and 12 + 6 = 18. They match.',
        pictures: [bags('3', '2', [['3x', '6']]), eq('3(x + 2) = 3x + 6', ['3 × 6 = 18', '12 + 6 = 18'])] },
      { title: 'One thing not to do', text: "Don't multiply only the first part. 3(x + 2) is not 3x + 2. The 3 multiplies the 2 as well.",
        pictures: [{ kind: 'cards', wrong: '3(x + 2) = 3x + 2', right: '3(x + 2) = 3x + 6' }] },
    ],
    turn: {
      text: 'Which is the same as 4(x + 3)?',
      picture: bags('4', '3'),
      answer: { choices: ['4x + 3', '4x + 12', 'x + 12', '7x'], correct: 1 },
      steps: ['Multiply the 4 by each part inside the parentheses.', '4 × x = 4x and 4 × 3 = 12.', 'So it is 4x + 12.'],
      prompt: 'Multiply the number outside by every part inside.',
      hint1: 'Does the 4 multiply only the x, or both parts?',
      hint2: 'Multiply 4 by x. Then multiply 4 by 3.',
      twin: { text: 'Which is the same as 5(x + 1)?',
        picture: bags('5', '1'),
        answer: { choices: ['5x + 1', '5x + 5', 'x + 5', '6x'], correct: 1 },
        steps: ['Multiply the 5 by each part inside the parentheses.', '5 × x = 5x and 5 × 1 = 5.', 'So it is 5x + 5.'],
        hint1: 'Which parts does the 5 multiply?',
        hint2: 'Multiply 5 by x. Then multiply 5 by 1.' },
    },
    won: { text: 'You multiplied the number outside by every part inside.', sticker: '3(x + 2) and 3x + 6 are equivalent expressions. Multiplying every part is the distributive property.' },
    twinWon: { text: 'You multiplied the 5 by both parts to get 5x + 5.', sticker: '3(x + 2) and 3x + 6 are equivalent expressions. Multiplying every part is the distributive property.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which is the same as 2(x + 5)?',
        picture: bags('2', '5'), answer: { choices: ['2x + 5', '2x + 10', 'x + 10', '7x'], correct: 1 },
        steps: ['Multiply the 2 by each part.', '2 × x = 2x and 2 × 5 = 10.', 'So it is 2x + 10.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Which is the same as 6(x + 2)?',
        picture: bags('6', '2'), answer: { choices: ['6x + 12', '6x + 2', '8x', 'x + 12'], correct: 0 },
        steps: ['Multiply the 6 by each part.', '6 × x = 6x and 6 × 2 = 12.', 'So it is 6x + 12.'] } },
      { why: 'Still "multiply every part"', problem: { text: 'Which is the same as 3(x − 4)?',
        picture: eq('3(x − 4)'), answer: { choices: ['3x − 4', '3x − 12', '3x + 12', 'x − 12'], correct: 1 },
        steps: ['Multiply the 3 by each part, and keep the take away.', '3 × x = 3x and 3 × 4 = 12.', 'So it is 3x − 12.'] } },
      { why: 'A little harder', problem: { text: 'Which is the same as 2x + 3x?',
        picture: { kind: 'area', cols: ['2', '3'], rows: ['x'], widths: [2, 3] }, answer: { choices: ['5x', '6x', '5 + x', '5x²'], correct: 0 },
        steps: ['2x is 2 groups of x, and 3x is 3 more groups of x.', 'Together that is 2 + 3 groups of x.', 'So it is 5x.'] } },
      { why: 'Same math in a story', problem: { text: 'Each of 4 teams has x players and 1 coach. Which shows how many people are on the 4 teams?',
        picture: bags('4', '1'), answer: { choices: ['4x + 1', '4x + 4', 'x + 4', '5x'], correct: 1 },
        steps: ['One team is x + 1 people, so 4 teams is 4(x + 1).', 'Multiply the 4 by each part: 4x and 4.', 'So it is 4x + 4.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m5-t7', title: 'Solve x + a = b', skill: 'Find the unknown number by taking the same amount off both sides',
    bigIdea: 'Keep it balanced. Take the same amount off both sides until x is alone.',
    screens: [
      { title: 'A level scale', text: 'A bag of x marbles and 4 loose marbles balance 9 marbles on the other side. How many marbles are in the bag?',
        pictures: [bal('x + 4', '9')] },
      { title: 'Guessing is slow', text: 'You could try 1, then 2, then 3, until it balances. With big numbers that takes a long time.',
        pictures: [bal('x + 4', '9')] },
      { title: 'The big idea', text: 'Keep it balanced. Take the same amount off both sides until x is alone.',
        pictures: [bal('x + 4', '9')] },
      { title: 'Take 4 off both sides', text: 'The 4 is in the way of x. Take 4 off the left. Take 4 off the right too, so the scale stays level.',
        pictures: [bal('x + 4 − 4', '9 − 4'), sides([['x + 4', '9'], ['x + 4 − 4', '9 − 4']], true)] },
      { title: 'See what is left', text: 'On the left, only x is left. On the right, 9 − 4 = 5. So x = 5.',
        pictures: [bal('x', '5'), sides([['x + 4', '9'], ['x + 4 − 4', '9 − 4'], ['x', '5']], true)] },
      { title: 'Check it', text: 'Put 5 back in for x: 5 + 4 = 9. Both sides match, so the bag holds 5 marbles.',
        pictures: [bal('5 + 4', '9'), eq('x + 4 = 9', ['5 + 4 = 9', '9 = 9'])] },
      { title: 'One thing not to do', text: "Don't add the 4 to the other side. x + 4 = 9 does not make x = 13. Take 4 away from both sides.",
        pictures: [{ kind: 'cards', wrong: 'x = 9 + 4 = 13', right: 'x = 9 − 4 = 5' }] },
    ],
    turn: {
      text: 'Solve x + 6 = 15. What is x?',
      picture: bal('x + 6', '15'),
      answer: 9, steps: ['Take 6 off both sides to keep it balanced.', 'Left: x. Right: 15 − 6.', 'So x = 9.'],
      prompt: 'Take the same amount off both sides until x is alone.',
      hint1: 'What is added to x on the left side?',
      hint2: 'Take 6 off both sides. What is left on the right?',
      twin: { text: 'Solve x + 8 = 20. What is x?',
        picture: bal('x + 8', '20'),
        answer: 12, steps: ['Take 8 off both sides to keep it balanced.', 'Left: x. Right: 20 − 8.', 'So x = 12.'],
        hint1: 'What number is added to x?',
        hint2: 'Take 8 away from both sides to get x alone.' },
    },
    won: { text: 'You took the same amount off both sides until x was alone.', sticker: 'The number that makes both sides balance is called the solution.' },
    twinWon: { text: 'You took 8 off both sides and found x = 12.', sticker: 'The number that makes both sides balance is called the solution.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Solve x + 5 = 12. What is x?',
        picture: bal('x + 5', '12'), answer: 7,
        steps: ['Take 5 off both sides.', 'Left: x. Right: 12 − 5.', 'So x = 7.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Solve x + 9 = 23. What is x?',
        picture: bal('x + 9', '23'), answer: 14,
        steps: ['Take 9 off both sides.', 'Left: x. Right: 23 − 9.', 'So x = 14.'] } },
      { why: 'Still "same off both sides"', problem: { text: 'Solve 11 + x = 30. What is x?',
        picture: bal('11 + x', '30'), answer: 19,
        steps: ['The 11 is with x on the left. Take 11 off both sides.', 'Left: x. Right: 30 − 11.', 'So x = 19.'] } },
      { why: 'A little harder', problem: { text: 'Solve x + 38 = 75. What is x?',
        picture: bal('x + 38', '75'), answer: 37,
        steps: ['Take 38 off both sides.', 'Left: x. Right: 75 − 38.', 'So x = 37.'] } },
      { why: 'Same math in a story', problem: { text: 'Sam had x dollars. He earned 15 dollars and now has 42 dollars, so x + 15 = 42. How many dollars did Sam have at first?',
        picture: bal('x + 15', '42'), answer: 27,
        steps: ['Take 15 off both sides.', 'Left: x. Right: 42 − 15.', 'So Sam had 27 dollars.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m5-t8', title: 'Solve ax = b', skill: 'Find the unknown number by dividing both sides by the number it is multiplied by',
    bigIdea: '3x means 3 equal parts of x. To find one x, divide both sides by 3.',
    screens: [
      { title: 'Movie tickets', text: '3 movie tickets cost 24 dollars in all. Every ticket costs the same, x dollars. How much is one ticket?',
        pictures: [tape(['x', 'x', 'x'], '24 dollars')] },
      { title: 'Taking away will not work', text: 'Here nothing is added to x, so taking away will not get it alone. There are 3 lots of x.',
        pictures: [tape(['x', 'x', 'x'], '24 dollars')] },
      { title: 'The big idea', text: '3x means 3 equal parts of x. To find one x, divide both sides by 3.',
        pictures: [tape(['x', 'x', 'x'], '24')] },
      { title: 'Three equal parts', text: '3x = 24 means 3 equal parts make 24 in all.',
        pictures: [tape(['x', 'x', 'x'], '24', true), eq('3x = 24')] },
      { title: 'Divide both sides by 3', text: 'Split 24 into 3 equal parts: 24 ÷ 3 = 8. Each part is 8, so x = 8.',
        pictures: [tape(['8', '8', '8'], '24', true), eq('3x ÷ 3 = 24 ÷ 3', ['x = 8'])] },
      { title: 'Check it', text: '3 × 8 = 24. It matches, so one ticket costs 8 dollars.',
        pictures: [tape(['8', '8', '8'], '24'), eq('3 × 8 = 24')] },
      { title: 'One thing not to do', text: "Don't take the 3 away. 3x = 24 does not make x = 21. 3x means 3 times x, so divide.",
        pictures: [{ kind: 'cards', wrong: 'x = 24 − 3 = 21', right: 'x = 24 ÷ 3 = 8' }] },
    ],
    turn: {
      text: 'Solve 4x = 28. What is x?',
      picture: tape(['x', 'x', 'x', 'x'], '28'),
      answer: 7, steps: ['4x means 4 equal parts make 28.', 'Divide both sides by 4: 28 ÷ 4.', 'So x = 7.'],
      prompt: 'Divide both sides by the number in front of x.',
      hint1: 'Is x added to 4, or multiplied by 4?',
      hint2: 'Split 28 into 4 equal parts. How big is one part?',
      twin: { text: 'Solve 6x = 54. What is x?',
        picture: tape(['x', 'x', 'x', 'x', 'x', 'x'], '54'),
        answer: 9, steps: ['6x means 6 equal parts make 54.', 'Divide both sides by 6: 54 ÷ 6.', 'So x = 9.'],
        hint1: 'How many equal parts of x are there?',
        hint2: 'Divide 54 by 6 to find one part.' },
    },
    won: { text: 'You divided both sides to find one x.', sticker: 'In 3x, the 3 is called the coefficient. Divide by it to get x alone.' },
    twinWon: { text: 'You divided 54 by 6 and found x = 9.', sticker: 'In 3x, the 3 is called the coefficient. Divide by it to get x alone.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Solve 5x = 35. What is x?',
        picture: tape(['x', 'x', 'x', 'x', 'x'], '35'), answer: 7,
        steps: ['5x means 5 equal parts make 35.', 'Divide both sides by 5: 35 ÷ 5.', 'So x = 7.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Solve 8x = 72. What is x?',
        picture: tape(['x', 'x', 'x', 'x', 'x', 'x', 'x', 'x'], '72'), answer: 9,
        steps: ['8x means 8 equal parts make 72.', 'Divide both sides by 8: 72 ÷ 8.', 'So x = 9.'] } },
      { why: 'Still "divide both sides"', problem: { text: 'Solve 2x = 30. What is x?',
        picture: tape(['x', 'x'], '30'), answer: 15,
        steps: ['2x means 2 equal parts make 30.', 'Divide both sides by 2: 30 ÷ 2.', 'So x = 15.'] } },
      { why: 'A little harder', problem: { text: 'Solve 7x = 84. What is x?',
        picture: tape(['x', 'x', 'x', 'x', 'x', 'x', 'x'], '84'), answer: 12,
        steps: ['7x means 7 equal parts make 84.', 'Divide both sides by 7: 84 ÷ 7.', 'So x = 12.'] } },
      { why: 'Same math in a story', problem: { text: '5 packs hold 60 cards in all, with the same number in each pack. Solve 5x = 60. How many cards are in one pack?',
        picture: tape(['x', 'x', 'x', 'x', 'x'], '60 cards'), answer: 12,
        steps: ['5 equal packs make 60 cards, so 5x = 60.', 'Divide both sides by 5: 60 ÷ 5.', 'So each pack has 12 cards.'] } },
    ],
  },

  // ── Topic 9 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g6m5-t9', title: 'Inequalities on a number line', skill: 'Show every number that makes x > 3 or x ≤ 5 true on a number line',
    bigIdea: 'x > 3 means any number bigger than 3 works. Draw an open dot at 3 and an arrow to the right.',
    screens: [
      { title: 'Old enough to join', text: 'To join a club, you must be more than 3 years old. 4 works. 7 works. Even 3 and a half works. How can you show every age that works?',
        pictures: [line(0, 10)] },
      { title: 'Too many to list', text: 'You cannot write down every number bigger than 3. There are too many, and they never stop.',
        pictures: [line(0, 10)] },
      { title: 'The big idea', text: 'x > 3 means any number bigger than 3 works. Draw an open dot at 3 and an arrow to the right.',
        pictures: [line(0, 10, { ray: { from: 3, dir: 'right', open: true } })] },
      { title: 'An open dot at 3', text: '3 itself does not work, because 3 is not more than 3. So the dot at 3 stays open and empty.',
        pictures: [line(0, 10, { points: [{ at: 3, open: true }], motion: true })] },
      { title: 'An arrow to the right', text: 'Bigger numbers are to the right. Color the line from 3 to the right, with an arrow, because it keeps going.',
        pictures: [line(0, 10, { ray: { from: 3, dir: 'right', open: true }, motion: true })] },
      { title: 'When the number works too', text: 'x ≤ 5 means 5 or less. 5 works, so fill in the dot at 5. Less is to the left, so the arrow goes left.',
        pictures: [line(0, 10, { ray: { from: 5, dir: 'left', open: false }, motion: true }), eq('x ≤ 5', ['5 or less'])] },
      { title: 'One thing not to do', text: "Don't fill in the dot for > or <. In x > 3, the 3 does not work, so its dot stays open.",
        pictures: [{ kind: 'cards', wrong: 'x > 3: filled dot at 3', right: 'x > 3: open dot at 3' }] },
    ],
    turn: {
      text: 'Which number line shows x < 6?',
      picture: line(0, 10),
      answer: { choices: ['open dot at 6, arrow left', 'filled dot at 6, arrow left', 'open dot at 6, arrow right'], correct: 0 },
      steps: ['"<" means less than, so the arrow goes left, toward smaller numbers.', '6 is not less than 6, so its dot is open.', 'So it is open dot at 6, arrow left.'],
      prompt: 'Decide the dot first: does the number itself work? Then decide which way the arrow goes.',
      hint1: 'Are the numbers that work bigger or smaller than 6?',
      hint2: 'Does 6 itself make x < 6 true? If not, the dot is open.',
      twin: { text: 'What is the greatest whole number that makes x < 9 true?',
        picture: line(0, 12),
        answer: 8, steps: ['x < 9 means numbers less than 9.', '9 itself does not work, because 9 is not less than 9.', 'The next whole number down is 8.'],
        hint1: 'Does 9 itself make x < 9 true?',
        hint2: 'Count down one whole number from 9.' },
    },
    won: { text: 'You chose the right dot and the right arrow.', sticker: 'x > 3 is called an inequality. Every number that makes it true is a solution.' },
    twinWon: { text: 'You saw that 9 does not work, so the greatest whole number is 8.', sticker: 'x > 3 is called an inequality. Every number that makes it true is a solution.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which number line shows x > 4?',
        picture: line(0, 10), answer: { choices: ['open dot at 4, arrow right', 'filled dot at 4, arrow right', 'open dot at 4, arrow left'], correct: 0 },
        steps: ['">" means greater than, so the arrow goes right.', '4 is not greater than 4, so its dot is open.', 'So it is open dot at 4, arrow right.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Is 7 a solution of x < 5?',
        picture: line(0, 10), answer: { choices: ['yes', 'no'], correct: 1 },
        steps: ['x < 5 means numbers less than 5.', '7 is bigger than 5, so it does not make x < 5 true.', 'So the answer is no.'] } },
      { why: 'Still "dot, then arrow"', problem: { text: 'Which number line shows x ≥ 2?',
        picture: line(0, 10), answer: { choices: ['open dot at 2, arrow right', 'filled dot at 2, arrow right', 'filled dot at 2, arrow left'], correct: 1 },
        steps: ['"≥" means greater than or equal to, so the arrow goes right.', '2 works too, so its dot is filled in.', 'So it is filled dot at 2, arrow right.'] } },
      { why: 'A little harder', problem: { text: 'What is the least whole number that makes x > 12 true?',
        picture: line(8, 18), answer: 13,
        steps: ['x > 12 means numbers greater than 12.', '12 itself does not work, because 12 is not greater than 12.', 'The next whole number up is 13.'] } },
      { why: 'Same math in a story', problem: { text: 'A bag may weigh at most 8 pounds. Which number line shows the weights w that are allowed?',
        picture: line(0, 10), answer: { choices: ['filled dot at 8, arrow left', 'open dot at 8, arrow left', 'filled dot at 8, arrow right'], correct: 0 },
        steps: ['"At most 8" means 8 or less, so w ≤ 8.', '8 pounds is allowed, so the dot is filled in, and less goes to the left.', 'So it is filled dot at 8, arrow left.'] } },
    ],
  },
]
