/**
 * Grade 7 · Module 1 — Proportional relationships and percent applications.
 * Written to docs/new-flow/AUTHORING.md.
 */
import type { Lesson, Picture } from '../script'

type TapeRow = Extract<Picture, { kind: 'tape' }>['rows'][number]
const tape = (rows: TapeRow[], motion = false): Picture => ({ kind: 'tape', rows, motion })
/** A table whose first cell of each row is its name. */
const table = (rows: string[][], head?: string[], mark?: [number, number][], motion = false): Picture =>
  ({ kind: 'table', head, rows, rowHead: true, mark, motion })
/** A straight line from (0, 0) through one labeled point. */
const graph = (x: number, y: number, motion = false): Picture =>
  ({ kind: 'coord', min: 0, max: 10, points: [{ x, y, label: `(${x}, ${y})` }], lines: [{ a: [0, 0], b: [x, y], extend: true }], motion })
/** `n` equal pieces of time on top; the amount done in the first piece below. `all` fills every piece. */
const perOne = (n: number, piece: string, first: string, amount: string, whole = '1 hour', timeLabel = 'Time', all?: string, brace = '?', motion = false): Picture =>
  tape([
    { label: timeLabel, cells: Array.from({ length: n }, (_, i) => ({ w: 1, text: piece, shade: i === 0 || !!all })), brace: whole },
    { label: amount, cells: Array.from({ length: n }, (_, i) => ({ w: 1, text: i === 0 ? first : all, shade: i === 0 || !!all })), brace },
  ], motion)
/** Before and after, drawn to scale; the change is the shaded piece. */
const change = (before: string, b: number, after: string, a: number, motion = false): Picture => a > b
  ? tape([{ label: 'Before', cells: [{ w: b, text: before }] }, { label: 'After', cells: [{ w: b, text: before }, { w: a - b, shade: true }], brace: after }], motion)
  : tape([{ label: 'Before', cells: [{ w: a }, { w: b - a, shade: true }], brace: before }, { label: 'After', cells: [{ w: a, text: after }] }], motion)
/** A price with percent pieces added on the end. */
const addOn = (price: string, extras: string[], brace = 'Total: ?', motion = false): Picture =>
  tape([{ cells: [{ w: 10, text: price }, ...extras.map(text => ({ w: 3, text, shade: true }))], brace }], motion)
/** A guess and the real amount, drawn to scale. */
const guess = (g: string, gw: number, r: string, rw: number): Picture =>
  tape([{ label: 'Guess', cells: [{ w: gw, text: g }] }, { label: 'Real', cells: [{ w: rw, text: r }] }])

const PN = ['proportional', 'not proportional']

export const G7M1: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m1-t1', title: 'Proportional or not?', skill: 'Decide if a table is proportional by checking every y ÷ x',
    bigIdea: 'Divide each bottom number by the top number above it. If every answer is the same, the table grows at one steady rate.',
    screens: [
      { title: 'Two summer jobs', text: 'You can take one of two summer jobs. The tables show what each one pays. Which job pays the same amount for every hour you work?',
        pictures: [table([['Job A ($)', '12', '24', '36']], ['Hours', '1', '2', '3']), table([['Job B ($)', '15', '25', '35']], ['Hours', '1', '2', '3'])] },
      { title: 'Both go up', text: 'Take a look at Job A. The pay climbs as the hours climb. Now Job B. That one climbs too. So going up does not tell these two jobs apart. We need something sharper.',
        beats: [
          { say: 'Take a look at Job A. The pay climbs as the hours climb.', pic: 0 },
          { say: 'Now Job B. That one climbs too.', pic: 1 },
          { say: 'So going up does not tell these two jobs apart. We need something sharper.', write: 'both go up → no help' },
        ],
        pictures: [table([['Job A ($)', '12', '24', '36']], ['Hours', '1', '2', '3']), table([['Job B ($)', '15', '25', '35']], ['Hours', '1', '2', '3'])] },
      { title: 'The big idea', text: 'Divide each bottom number by the top number above it. If every answer is the same, the table grows at one steady rate.',
        beats: [
          { say: 'Divide each bottom number by the top number above it.', pic: 0 },
          { say: 'If every answer is the same, the table grows at one steady rate.' },
        ],
        pictures: [table([['Job A ($)', '12', '24', '36']], ['Hours', '1', '2', '3'])] },
      { title: 'Check Job A', text: "Let's try it on Job A. Take each pay and divide it by the hours above it. 12 ÷ 1 = 12. 24 ÷ 2 = 12. And 36 ÷ 3 = 12. Every single one comes out 12. That is one steady rate.",
        beats: [
          { say: "Let's try it on Job A. Take each pay and divide it by the hours above it.", pic: 0 },
          { say: '12 ÷ 1 = 12. 24 ÷ 2 = 12. And 36 ÷ 3 = 12.', pic: 1 },
          { say: 'Every single one comes out 12. That is one steady rate.' },
        ],
        pictures: [table([['Job A ($)', '12', '24', '36']], ['Hours', '1', '2', '3'], [[0, 1], [0, 2], [0, 3]], true), { kind: 'eq', text: '12 ÷ 1 = 12', lines: ['24 ÷ 2 = 12', '36 ÷ 3 = 12'] }] },
      { title: 'Check Job B', text: 'Now the same test on Job B. 15 ÷ 1 = 15. But 25 ÷ 2 = 12.5. Those two are already different, so you can stop right there. Job B has no steady rate.',
        beats: [
          { say: 'Now the same test on Job B.', pic: 0 },
          { say: '15 ÷ 1 = 15. But 25 ÷ 2 = 12.5.', pic: 1 },
          { say: 'Those two are already different, so you can stop right there.', write: 'two different → stop' },
          { say: 'Job B has no steady rate.' },
        ],
        pictures: [table([['Job B ($)', '15', '25', '35']], ['Hours', '1', '2', '3'], [[0, 1], [0, 2]], true), { kind: 'eq', text: '15 ÷ 1 = 15', lines: ['25 ÷ 2 = 12.5'] }] },
      { title: 'One steady rate', text: 'Here is Job A with the divisions written underneath. $12 an hour, every hour, no matter how long you work. Job B never does that, because it hands you an extra $5 at the start. That extra keeps shifting the pay for each hour.',
        beats: [
          { say: 'Here is Job A with the divisions written underneath.', pic: 0 },
          { say: '$12 an hour, every hour, no matter how long you work.' },
          { say: 'Job B never does that, because it hands you an extra $5 at the start.', write: 'extra at the start → not steady' },
          { say: 'That extra keeps shifting the pay for each hour.' },
        ],
        pictures: [table([['Job A ($)', '12', '24', '36'], ['Pay ÷ hours', '12', '12', '12']], ['Hours', '1', '2', '3'])] },
      { title: 'One thing not to do', text: "Here is the trap. Don't just check that the numbers go up by the same amount each time. Job B does go up $10 every hour. But its pay divided by hours still changes, so it is not one steady rate.",
        beats: [
          { say: 'Here is the trap.' },
          { say: "Don't just check that the numbers go up by the same amount each time.", pic: 0 },
          { say: 'Job B does go up $10 every hour.' },
          { say: 'But its pay divided by hours still changes, so it is not one steady rate.' },
        ],
        pictures: [{ kind: 'cards', wrong: 'Up $10 each time, so one steady rate', right: '15 ÷ 1 = 15, 25 ÷ 2 = 12.5: not steady' }] },
    ],
    turn: {
      text: 'Tables with one steady rate are called proportional. The table shows the cost of movie tickets. Is it proportional?',
      picture: table([['Cost ($)', '18', '36', '54']], ['Tickets', '2', '4', '6']),
      answer: { choices: PN, correct: 0 },
      steps: ['Divide each cost by its tickets: 18 ÷ 2 = 9, 36 ÷ 4 = 9, 54 ÷ 6 = 9.', 'Every answer is 9, so the rate is steady.', 'So the table is proportional.'],
      prompt: 'Divide each cost by its number of tickets. Are the answers all the same?',
      hint1: 'Divide each cost by the tickets above it.',
      hint2: 'Is 18 ÷ 2 the same as 36 ÷ 4 and 54 ÷ 6?',
      twin: { text: 'A pizza shop charges $11 for 1 pizza, $19 for 2 pizzas and $27 for 3 pizzas. Is the cost proportional to the number of pizzas?',
        picture: table([['Cost ($)', '11', '19', '27']], ['Pizzas', '1', '2', '3']),
        answer: { choices: PN, correct: 1 },
        steps: ['Divide each cost by its pizzas: 11 ÷ 1 = 11, but 19 ÷ 2 = 9.5.', 'The answers are different, so the rate is not steady.', 'So the table is not proportional.'],
        hint1: 'Divide each cost by the number of pizzas.',
        hint2: 'Compare 11 ÷ 1 with 19 ÷ 2. Are they the same?' },
    },
    won: { text: 'Every cost ÷ tickets came out the same, so the table keeps one steady rate.', sticker: 'When every y ÷ x is the same number, the relationship is called proportional.' },
    twinWon: { text: 'You checked 11 ÷ 1 and 19 ÷ 2. They are different, so the cost is not proportional.', sticker: 'When every y ÷ x is the same number, the relationship is called proportional.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'The table shows how far a hiker walks. Is it proportional?',
        picture: table([['Miles', '8', '12', '20']], ['Hours', '2', '3', '5']), answer: { choices: PN, correct: 0 },
        steps: ['Divide each distance by its hours: 8 ÷ 2 = 4, 12 ÷ 3 = 4, 20 ÷ 5 = 4.', 'Every answer is the same.', 'So the table is proportional.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'The table shows what a gym charges in all. Is it proportional?',
        picture: table([['Cost ($)', '40', '65', '90']], ['Months', '1', '2', '3']), answer: { choices: PN, correct: 1 },
        steps: ['40 ÷ 1 = 40, but 65 ÷ 2 = 32.5.', 'The answers are different, so the rate is not steady.', 'So the table is not proportional.'] } },
      { why: 'Still "divide each y by its x"', problem: { text: 'Is this table proportional?',
        picture: table([['y', '6', '9', '15']], ['x', '4', '6', '10']), answer: { choices: PN, correct: 0 },
        steps: ['6 ÷ 4 = 1.5, 9 ÷ 6 = 1.5, 15 ÷ 10 = 1.5.', 'Every answer is 1.5.', 'So the table is proportional.'] } },
      { why: 'A little harder', problem: { text: 'Is this table proportional? Check every column.',
        picture: table([['y', '12', '20', '30']], ['x', '3', '5', '8']), answer: { choices: PN, correct: 1 },
        steps: ['12 ÷ 3 = 4 and 20 ÷ 5 = 4.', 'But 30 ÷ 8 = 3.75, which is different.', 'So the table is not proportional.'] } },
      { why: 'Same math in a story', problem: { text: 'At a farm stand, 3 pounds of apples cost $4.50, 5 pounds cost $7.50 and 8 pounds cost $12. Is the cost proportional to the pounds?',
        picture: table([['Cost ($)', '4.50', '7.50', '12']], ['Pounds', '3', '5', '8']), answer: { choices: PN, correct: 0 },
        steps: ['4.50 ÷ 3 = 1.5, 7.50 ÷ 5 = 1.5, 12 ÷ 8 = 1.5.', 'Every pound costs the same $1.50.', 'So the cost is proportional.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m1-t2', title: 'The constant of proportionality', skill: 'Find k in y = kx from a proportional table',
    bigIdea: 'In a proportional table, y ÷ x is the same number every time. Multiply x by that number to get y.',
    screens: [
      { title: 'Filling a pool', text: 'A hose fills a pool at a steady rate. The table shows the gallons after a few minutes. How could you find the gallons for any number of minutes?',
        pictures: [table([['Gallons (y)', '5', '10', '15']], ['Minutes (x)', '2', '4', '6'])] },
      { title: 'The table stops', text: 'Here is the trouble. The table stops at 6 minutes. But what if I ask you about 20 minutes? Or 100? You do not want to keep stretching the table forever. You want one rule that handles any number of minutes.',
        beats: [
          { say: 'Here is the trouble. The table stops at 6 minutes.', pic: 0 },
          { say: 'But what if I ask you about 20 minutes? Or 100?' },
          { say: 'You do not want to keep stretching the table forever.' },
          { say: 'You want one rule that handles any number of minutes.', write: 'one rule for any x' },
        ],
        pictures: [table([['Gallons (y)', '5', '10', '15', '?']], ['Minutes (x)', '2', '4', '6', '20'])] },
      { title: 'The big idea', text: 'In a proportional table, y ÷ x is the same number every time. Multiply x by that number to get y.',
        beats: [
          { say: 'In a proportional table, y ÷ x is the same number every time.', pic: 0 },
          { say: 'Multiply x by that number to get y.' },
        ],
        pictures: [table([['Gallons (y)', '5', '10', '15']], ['Minutes (x)', '2', '4', '6'])] },
      { title: 'Divide y by x', text: "Let's do the dividing. 5 ÷ 2 = 2.5. Then 10 ÷ 4 = 2.5, and 15 ÷ 6 = 2.5. Same number every time. So the hose adds 2.5 gallons every single minute.",
        beats: [
          { say: "Let's do the dividing.", pic: 0 },
          { say: '5 ÷ 2 = 2.5. Then 10 ÷ 4 = 2.5, and 15 ÷ 6 = 2.5.', pic: 1 },
          { say: 'Same number every time. So the hose adds 2.5 gallons every single minute.', write: '2.5 gallons each minute' },
        ],
        pictures: [table([['Gallons (y)', '5', '10', '15']], ['Minutes (x)', '2', '4', '6'], [[0, 1], [0, 2], [0, 3]], true), { kind: 'eq', text: '5 ÷ 2 = 2.5', lines: ['10 ÷ 4 = 2.5', '15 ÷ 6 = 2.5'] }] },
      { title: 'Go the other way', text: 'Now watch it run backwards. Multiply the minutes by 2.5 and the gallons come right back. 2 × 2.5 = 5. And 4 × 2.5 = 10. It works both ways.',
        beats: [
          { say: 'Now watch it run backwards.' },
          { say: 'Multiply the minutes by 2.5 and the gallons come right back.', pic: 0 },
          { say: '2 × 2.5 = 5. And 4 × 2.5 = 10.' },
          { say: 'It works both ways.', write: 'y ÷ x gives the rate, x × rate gives y' },
        ],
        pictures: [table([['Gallons (y)', '5', '10', '15'], ['Minutes × 2.5', '5', '10', '15']], ['Minutes (x)', '2', '4', '6'], [[1, 1], [1, 2], [1, 3]], true)] },
      { title: 'Write the rule', text: 'So here is your rule. Gallons equals 2.5 times minutes. In short: y = 2.5x. Now try 20 minutes. 2.5 × 20 = 50 gallons, and you never needed a longer table.',
        beats: [
          { say: 'So here is your rule.' },
          { say: 'Gallons equals 2.5 times minutes. In short: y = 2.5x.', pic: 0 },
          { say: 'Now try 20 minutes. 2.5 × 20 = 50 gallons, and you never needed a longer table.' },
        ],
        pictures: [{ kind: 'eq', text: 'y = 2.5x', lines: ['2.5 × 20 = 50 gallons'] }] },
      { title: 'One thing not to do', text: "One more thing before you try it. Don't divide x by y. 2 ÷ 5 = 0.4, and that tells you minutes for each gallon. You want gallons for each minute, so keep y on top.",
        beats: [
          { say: 'One more thing before you try it.' },
          { say: "Don't divide x by y.", pic: 0 },
          { say: '2 ÷ 5 = 0.4, and that tells you minutes for each gallon.' },
          { say: 'You want gallons for each minute, so keep y on top.', write: 'y ÷ x, not x ÷ y' },
        ],
        pictures: [{ kind: 'cards', wrong: '2 ÷ 5 = 0.4 gallons each minute', right: '5 ÷ 2 = 2.5 gallons each minute' }] },
    ],
    turn: {
      text: 'A hose fills a tank at a steady rate. What number do you multiply the minutes by to get the gallons?',
      picture: table([['Gallons (y)', '14', '28', '42']], ['Minutes (x)', '4', '8', '12']),
      answer: 3.5,
      steps: ['Divide y by x: 14 ÷ 4.', 'Check another column: 28 ÷ 8 gives the same.', 'So y = 3.5x, and the number is 3.5.'],
      prompt: 'Divide the gallons by the minutes. Check it with a second column.',
      hint1: 'Divide a gallons number by the minutes above it.',
      hint2: 'Try 14 ÷ 4. Does 28 ÷ 8 give the same?',
      twin: { text: 'A printer prints 18 pages in 4 minutes, 36 pages in 8 minutes and 54 pages in 12 minutes. What number do you multiply the minutes by to get the pages?',
        picture: table([['Pages (y)', '18', '36', '54']], ['Minutes (x)', '4', '8', '12']),
        answer: 4.5,
        steps: ['Divide y by x: 18 ÷ 4.', 'Check: 36 ÷ 8 gives the same.', 'So y = 4.5x, and the number is 4.5.'],
        hint1: 'Divide the pages by the minutes.',
        hint2: 'Try 18 ÷ 4. Does 36 ÷ 8 match?' },
    },
    won: { text: 'You divided y by x and found the number that turns minutes into gallons.', sticker: 'In y = kx, the number k is called the constant of proportionality.' },
    twinWon: { text: 'You divided 18 by 4 and found the rule y = 4.5x.', sticker: 'In y = kx, the number k is called the constant of proportionality.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'This table is proportional. What is k in y = kx?',
        picture: table([['y', '11', '22', '33']], ['x', '2', '4', '6']), answer: 5.5,
        steps: ['Divide y by x: 11 ÷ 2.', 'Check: 22 ÷ 4 gives the same.', 'So k is 5.5.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'This table is proportional. What is k in y = kx?',
        picture: table([['y', '8', '16', '24']], ['x', '5', '10', '15']), answer: 1.6,
        steps: ['Divide y by x: 8 ÷ 5.', 'Check: 16 ÷ 10 gives the same.', 'So k is 1.6.'] } },
      { why: 'Still "y ÷ x"', problem: { text: 'This table is proportional. What is k in y = kx?',
        picture: table([['y', '21', '35', '56']], ['x', '3', '5', '8']), answer: 7,
        steps: ['Divide y by x: 21 ÷ 3.', 'Check: 35 ÷ 5 and 56 ÷ 8 give the same.', 'So k is 7.'] } },
      { why: 'A little harder', problem: { text: 'This table is proportional. What is k in y = kx?',
        picture: table([['y', '3', '12', '18']], ['x', '0.5', '2', '3']), answer: 6,
        steps: ['Use a whole-number column: 12 ÷ 2.', 'Check: 3 ÷ 0.5 gives the same, because 0.5 fits into 3 that many times.', 'So k is 6.'] } },
      { why: 'Same math in a story', problem: { text: 'Sam earns $52.50 for 5 hours, $105 for 10 hours and $136.50 for 13 hours. What is k, his pay for each hour, in y = kx?',
        picture: table([['Pay ($)', '52.50', '105', '136.50']], ['Hours', '5', '10', '13']), answer: 10.5,
        steps: ['Divide pay by hours: 105 ÷ 10.', 'Check: 52.50 ÷ 5 gives the same.', 'So k is 10.5 dollars an hour.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m1-t3', title: 'Proportional graphs', skill: 'Recognise a proportional graph and read k at x = 1',
    bigIdea: 'A proportional graph is a straight line through (0, 0). The y-value at x = 1 is the rate.',
    screens: [
      { title: 'Saving every week', text: 'Jo saves $2 every week. Each dot shows a number of weeks and her savings so far. What does this picture tell you?',
        pictures: [{ kind: 'coord', min: 0, max: 10, points: [{ x: 1, y: 2 }, { x: 2, y: 4 }, { x: 3, y: 6 }, { x: 4, y: 8 }] }] },
      { title: 'Dots can fool you', text: 'Look at the dots. They march up to the right, and that looks steady. But dots can climb without keeping one steady rate. So what do you look for? You need something you can spot on a graph in a second.',
        beats: [
          { say: 'Look at the dots. They march up to the right, and that looks steady.', pic: 0, effect: 'draw' },
          { say: 'But dots can climb without keeping one steady rate.' },
          { say: 'So what do you look for?' },
          { say: 'You need something you can spot on a graph in a second.' },
        ],
        pictures: [{ kind: 'coord', min: 0, max: 10, points: [{ x: 1, y: 2 }, { x: 2, y: 4 }, { x: 3, y: 6 }, { x: 4, y: 8 }] }] },
      { title: 'The big idea', text: 'A proportional graph is a straight line through (0, 0). The y-value at x = 1 is the rate.',
        beats: [
          { say: 'A proportional graph is a straight line through (0, 0).', pic: 0, effect: 'draw' },
          { say: 'The y-value at x = 1 is the rate.' },
        ],
        pictures: [{ kind: 'coord', min: 0, max: 10, points: [{ x: 1, y: 2 }, { x: 2, y: 4 }, { x: 3, y: 6 }, { x: 4, y: 8 }], lines: [{ a: [0, 0], b: [4, 8], extend: true }] }] },
      { title: 'Join the dots', text: 'Lay a ruler across those dots. Every one of them sits on a single straight line. Not a curve, not a bend. Straight.',
        beats: [
          { say: 'Lay a ruler across those dots.', pic: 0, effect: 'draw' },
          { say: 'Every one of them sits on a single straight line.' },
          { say: 'Not a curve, not a bend. Straight.', write: 'test 1: straight' },
        ],
        pictures: [{ kind: 'coord', min: 0, max: 10, points: [{ x: 1, y: 2 }, { x: 2, y: 4 }, { x: 3, y: 6 }, { x: 4, y: 8 }], lines: [{ a: [1, 2], b: [4, 8], extend: true }], motion: true }] },
      { title: 'Start at zero', text: 'Now the second thing to check. Before Jo saved anything, she had $0. Zero weeks, zero dollars. So the line runs right through the corner of the graph.',
        beats: [
          { say: 'Now the second thing to check.' },
          { say: 'Before Jo saved anything, she had $0. Zero weeks, zero dollars.', pic: 0, effect: 'draw' },
          { say: 'So the line runs right through the corner of the graph.', write: 'test 2: starts at the corner' },
        ],
        pictures: [{ kind: 'coord', min: 0, max: 10, points: [{ x: 0, y: 0, label: '(0, 0)' }, { x: 2, y: 4 }, { x: 4, y: 8 }], lines: [{ a: [0, 0], b: [4, 8], extend: true }], motion: true }] },
      { title: 'Read the rate at x = 1', text: 'Here is the useful part. Find x = 1 along the bottom, then go straight up to the line. y is 2 there. So Jo saves $2 a week, and the rule is y = 2x.',
        beats: [
          { say: 'Here is the useful part.' },
          { say: 'Find x = 1 along the bottom, then go straight up to the line.', pic: 0, effect: 'draw' },
          { say: 'y is 2 there.' },
          { say: 'So Jo saves $2 a week, and the rule is y = 2x.', pic: 1 },
        ],
        pictures: [{ kind: 'coord', min: 0, max: 10, points: [{ x: 1, y: 2, label: '(1, 2)' }], lines: [{ a: [0, 0], b: [4, 8], extend: true }, { a: [1, 0], b: [1, 2], dashed: true, tone: 2 }] },
          { kind: 'eq', text: 'y = 2x' }] },
      { title: 'One thing not to do', text: "Careful with this one. Don't call every straight line proportional. A line that starts at (0, 3) already has 3 saved before week one. That head start keeps y ÷ x changing.",
        beats: [
          { say: 'Careful with this one.' },
          { say: "Don't call every straight line proportional.", pic: 0 },
          { say: 'A line that starts at (0, 3) already has 3 saved before week one.' },
          { say: 'That head start keeps y ÷ x changing.' },
        ],
        pictures: [{ kind: 'cards', wrong: 'Straight line from (0, 3): proportional', right: 'Straight line through (0, 0): proportional' }] },
    ],
    turn: {
      text: 'This graph is proportional. It goes through (0, 0) and (2, 6). What is y when x = 1?',
      picture: graph(2, 6),
      answer: 3,
      steps: ['The line goes through (0, 0) and (2, 6).', 'x = 1 is half of 2, so y is half of 6.', 'So y = 3 when x = 1, and the rule is y = 3x.'],
      prompt: 'Find x = 1 on the bottom. Go up to the line and read y.',
      hint1: 'Find x = 1 on the bottom. Go straight up to the line.',
      hint2: 'x = 1 is half of 2. What is half of 6?',
      twin: { text: 'This graph is proportional. It goes through (0, 0) and (4, 10). What is y when x = 1?',
        picture: graph(4, 10),
        answer: 2.5,
        steps: ['The line goes through (0, 0) and (4, 10).', 'x = 1 is one quarter of 4, so y is one quarter of 10: 10 ÷ 4.', 'So y = 2.5 when x = 1.'],
        hint1: 'How much does y grow for each 1 that x grows?',
        hint2: 'x grows by 4 while y grows by 10. Share the 10 equally among the 4.' },
    },
    won: { text: 'You read y at x = 1 on a line through (0, 0).', sticker: 'On a proportional graph, the y-value at x = 1 is the constant of proportionality, k.' },
    twinWon: { text: 'You shared 10 among 4 and read y = 2.5 at x = 1.', sticker: 'On a proportional graph, the y-value at x = 1 is the constant of proportionality, k.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'This graph is proportional. It goes through (2, 8). What is y when x = 1?',
        picture: graph(2, 8), answer: 4,
        steps: ['The line goes through (0, 0) and (2, 8).', 'x = 1 is half of 2, so y is half of 8.', 'So y = 4 when x = 1.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'This graph is proportional. It goes through (4, 2). What is k?',
        picture: graph(4, 2), answer: 0.5,
        steps: ['k is the y-value at x = 1.', 'x = 1 is one quarter of 4, so y is 2 ÷ 4.', 'So k is 0.5.'] } },
      { why: 'Still "straight and through (0, 0)"', problem: { text: 'This straight line crosses the side at (0, 2). Is the graph proportional?',
        picture: { kind: 'coord', min: 0, max: 10, points: [{ x: 0, y: 2, label: '(0, 2)' }, { x: 4, y: 10 }], lines: [{ a: [0, 2], b: [4, 10], extend: true }] },
        answer: { choices: PN, correct: 1 },
        steps: ['The line is straight, but at x = 0 it is at y = 2, not 0.', 'A proportional graph must go through (0, 0).', 'So the graph is not proportional.'] } },
      { why: 'A little harder', problem: { text: 'This graph is proportional. It goes through (3, 5). What is y when x = 1? A fraction is fine.',
        picture: graph(3, 5), answer: { frac: [5, 3] },
        steps: ['x = 1 is one third of 3.', 'So y is one third of 5: 5 ÷ 3.', 'So y = 5/3 when x = 1.'] } },
      { why: 'Same math in a story', problem: { text: 'A graph shows the cost of apples: x pounds and y dollars. It is a straight line through (0, 0) and (6, 9). How many dollars does one pound cost?',
        picture: graph(6, 9), answer: 1.5,
        steps: ['One pound is the point where x = 1.', 'x = 1 is one sixth of 6, so y is 9 ÷ 6.', 'So one pound costs 1.5 dollars.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m1-t4', title: 'Unit rates with fractions', skill: 'Find a unit rate when both amounts are fractions',
    bigIdea: 'Divide the amount by the time, even when both are fractions. Ask how much fits in one whole.',
    screens: [
      { title: 'A walk in the park', text: 'You walk 1/2 mile in 1/4 of an hour. At that pace, how far do you walk in one whole hour?',
        pictures: [perOne(4, '1/4 h', '1/2', 'Miles')] },
      { title: 'Fractions make it look hard', text: "Normally you would just divide. So that is 1/2 ÷ 1/4. And that looks strange, doesn't it? You cannot even tell whether the answer should be bigger or smaller than 1/2.",
        beats: [
          { say: 'Normally you would just divide. So that is 1/2 ÷ 1/4.', pic: 0, effect: 'draw' },
          { say: "And that looks strange, doesn't it?" },
          { say: 'You cannot even tell whether the answer should be bigger or smaller than 1/2.', write: 'bigger or smaller?' },
        ],
        pictures: [perOne(4, '1/4 h', '1/2', 'Miles')] },
      { title: 'The big idea', text: 'Divide the amount by the time, even when both are fractions. Ask how much fits in one whole.',
        beats: [
          { say: 'Divide the amount by the time, even when both are fractions.', pic: 0, effect: 'draw' },
          { say: 'Ask how much fits in one whole.' },
        ],
        pictures: [perOne(4, '1/4 h', '1/2', 'Miles')] },
      { title: 'Fill the hour', text: "Let's picture the whole hour instead. One hour splits into 4 quarter hours. Your walk so far fills just one of those four.",
        beats: [
          { say: "Let's picture the whole hour instead.", pic: 0, effect: 'draw' },
          { say: 'One hour splits into 4 quarter hours.' },
          { say: 'Your walk so far fills just one of those four.' },
        ],
        pictures: [perOne(4, '1/4 h', '1/2', 'Miles', '1 hour', 'Time', undefined, '?', true)] },
      { title: 'Each quarter adds 1/2 mile', text: 'Now keep that same pace going. Every quarter hour you add another 1/2 mile. Four quarters, so 1/2 + 1/2 + 1/2 + 1/2. That is 2 miles in the hour.',
        beats: [
          { say: 'Now keep that same pace going.' },
          { say: 'Every quarter hour you add another 1/2 mile.', pic: 0, effect: 'draw' },
          { say: 'Four quarters, so 1/2 + 1/2 + 1/2 + 1/2.' },
          { say: 'That is 2 miles in the hour.' },
        ],
        pictures: [perOne(4, '1/4 h', '1/2', 'Miles', '1 hour', 'Time', '1/2', '2 miles', true)] },
      { title: 'It is the same as dividing', text: 'Now here is the shortcut that matches the picture. Dividing by 1/4 is the same as multiplying by 4. So 1/2 ÷ 1/4 = 2, and your pace is 2 miles per hour.',
        beats: [
          { say: 'Now here is the shortcut that matches the picture.' },
          { say: 'Dividing by 1/4 is the same as multiplying by 4.', write: '÷ 1/4 is the same as × 4' },
          { say: 'So 1/2 ÷ 1/4 = 2, and your pace is 2 miles per hour.', pic: 0 },
        ],
        pictures: [{ kind: 'eq', text: '1/2 ÷ 1/4', lines: ['= 1/2 × 4', '= 2 miles per hour'] }] },
      { title: 'One thing not to do', text: "Watch the order here. Don't divide the time by the distance. 1/4 ÷ 1/2 = 1/2, and that tells you hours for each mile. You were asked for miles in one hour, so the miles go on top.",
        beats: [
          { say: 'Watch the order here.' },
          { say: "Don't divide the time by the distance.", pic: 0 },
          { say: '1/4 ÷ 1/2 = 1/2, and that tells you hours for each mile.' },
          { say: 'You were asked for miles in one hour, so the miles go on top.' },
        ],
        pictures: [{ kind: 'cards', wrong: '1/4 ÷ 1/2 = 1/2 mile per hour', right: '1/2 ÷ 1/4 = 2 miles per hour' }] },
    ],
    turn: {
      text: 'You walk 3/4 mile in 1/4 hour. How many miles do you walk in one hour?',
      picture: perOne(4, '1/4 h', '3/4', 'Miles'),
      answer: 3,
      steps: ['One hour is 4 quarter hours.', 'Each quarter hour adds another 3/4 mile: 4 × 3/4.', 'So you walk 3 miles in one hour.'],
      prompt: 'Count how many of those time pieces make one whole hour.',
      hint1: 'How many quarter hours make one hour?',
      hint2: 'Add 3/4 mile for every quarter hour in the hour.',
      twin: { text: 'You jog 2/3 mile in 1/6 hour. How many miles do you jog in one hour?',
        picture: perOne(6, '1/6 h', '2/3', 'Miles'),
        answer: 4,
        steps: ['One hour is 6 sixths of an hour.', 'Each sixth adds another 2/3 mile: 6 × 2/3.', 'So you jog 4 miles in one hour.'],
        hint1: 'How many sixths of an hour make one hour?',
        hint2: 'Take 2/3 mile once for every sixth in the hour.' },
    },
    won: { text: 'You filled the whole hour with quarter hours and added up the miles.', sticker: 'A rate like 3/4 mile per 1/4 hour, a fraction over a fraction, is called a complex fraction.' },
    twinWon: { text: 'You found 6 sixths in an hour, and 6 × 2/3 = 4 miles per hour.', sticker: 'A rate like 2/3 mile per 1/6 hour, a fraction over a fraction, is called a complex fraction.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'You walk 1/2 mile in 1/3 hour. How many miles do you walk in one hour?',
        picture: perOne(3, '1/3 h', '1/2', 'Miles'), answer: 1.5,
        steps: ['One hour is 3 thirds of an hour.', 'Each third adds 1/2 mile: 3 × 1/2 = 3/2.', 'So you walk 1.5 miles in one hour.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A recipe uses 2/3 cup of sugar for 1/2 of a batch. How many cups of sugar are in one whole batch?',
        picture: perOne(2, '1/2', '2/3', 'Cups', '1 batch', 'Batch'), answer: { frac: [4, 3] },
        steps: ['One batch is 2 halves.', 'Each half uses 2/3 cup: 2 × 2/3.', 'So one batch uses 4/3 cups.'] } },
      { why: 'Still "how much in one whole"', problem: { text: 'A snail crawls 1/10 meter in 1/5 minute. How many meters does it crawl in one minute?',
        picture: perOne(5, '1/5 min', '1/10', 'Meters', '1 minute'), answer: { frac: [1, 2] },
        steps: ['One minute is 5 fifths of a minute.', 'Each fifth adds 1/10 meter: 5 × 1/10 = 5/10.', 'So it crawls 1/2 meter in one minute.'] } },
      { why: 'A little harder', problem: { text: 'A runner goes 1 1/2 miles in 3/4 hour. What is her speed in miles per hour?',
        picture: tape([
          { label: 'Time', cells: Array.from({ length: 4 }, (_, i) => ({ w: 1, text: '1/4 h', shade: i < 3 })), brace: '1 hour' },
          { label: 'Miles', cells: [{ w: 3, text: '1 1/2', shade: true }, { w: 1 }], brace: '?' },
        ]), answer: 2,
        steps: ['3/4 hour is 3 quarter hours, so one quarter hour is 1 1/2 ÷ 3 = 1/2 mile.', 'One hour is 4 quarter hours: 4 × 1/2.', 'So her speed is 2 miles per hour.'] } },
      { why: 'Same math in a story', problem: { text: 'Lena mows 2/5 of a lawn in 1/2 hour. At that pace, how much of the lawn does she mow in one hour?',
        picture: perOne(2, '1/2 h', '2/5', 'Lawn'), answer: { frac: [4, 5] },
        steps: ['One hour is 2 half hours.', 'Each half hour mows 2/5 of the lawn: 2 × 2/5.', 'So she mows 4/5 of the lawn in one hour.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m1-t5', title: 'Solve a proportion', skill: 'Find the missing number in two equal ratios',
    bigIdea: 'Two equal ratios grow by the same factor. Find what one number was multiplied by, and do the same to the other.',
    screens: [
      { title: 'Reading a map', text: 'On a map, 2 inches stands for 15 miles. Two towns are 6 inches apart on the map. How far apart are they really?',
        pictures: [table([['Inches', '2', '6'], ['Miles', '15', '?']], ['', 'Scale', 'Towns'])] },
      { title: 'Adding does not work', text: 'Your first thought might be to add. 6 inches is 4 more inches than 2, so add 4 miles to the 15? No. That would give a different number of miles for every inch, and the map would stop matching the real world.',
        beats: [
          { say: 'Your first thought might be to add.', pic: 0 },
          { say: '6 inches is 4 more inches than 2, so add 4 miles to the 15?' },
          { say: 'No. That would give a different number of miles for every inch, and the map would stop matching the real world.', write: 'adding breaks the scale' },
        ],
        pictures: [table([['Inches', '2', '6'], ['Miles', '15', '?']], ['', 'Scale', 'Towns'])] },
      { title: 'The big idea', text: 'Two equal ratios grow by the same factor. Find what one number was multiplied by, and do the same to the other.',
        beats: [
          { say: 'Two equal ratios grow by the same factor.', pic: 0 },
          { say: 'Find what one number was multiplied by, and do the same to the other.' },
        ],
        pictures: [table([['Inches', '2', '6'], ['Miles', '15', '?']], ['', 'Scale', 'Towns'])] },
      { title: 'Find the factor', text: 'Look along the inches row instead. 2 inches turned into 6 inches. So ask yourself: 2 times what makes 6? 2 × 3 = 6. Everything here was multiplied by 3.',
        beats: [
          { say: 'Look along the inches row instead.', pic: 0 },
          { say: '2 inches turned into 6 inches.' },
          { say: 'So ask yourself: 2 times what makes 6?' },
          { say: '2 × 3 = 6. Everything here was multiplied by 3.', pic: 1 },
        ],
        pictures: [table([['Inches', '2', '6'], ['Miles', '15', '?']], ['', 'Scale', 'Towns'], [[0, 1], [0, 2]], true), { kind: 'eq', text: '2 × 3 = 6' }] },
      { title: 'Do the same to the miles', text: 'Now do the exact same thing to the miles. 15 × 3 = 45. So those two towns are really 45 miles apart.',
        beats: [
          { say: 'Now do the exact same thing to the miles.' },
          { say: '15 × 3 = 45.', pic: 1 },
          { say: 'So those two towns are really 45 miles apart.', pic: 0 },
        ],
        pictures: [table([['Inches', '2', '6'], ['Miles', '15', '45']], ['', 'Scale', 'Towns'], [[1, 1], [1, 2]], true), { kind: 'eq', text: '15 × 3 = 45' }] },
      { title: 'Check by crossing', text: 'Want to be sure? Write both ratios as fractions: 2/15 and 6/45. Now multiply across the middle. 2 × 45 = 90, and 15 × 6 = 90. Same answer both ways, so the two ratios really are equal.',
        beats: [
          { say: 'Want to be sure?' },
          { say: 'Write both ratios as fractions: 2/15 and 6/45.', pic: 0 },
          { say: 'Now multiply across the middle.', write: 'cross and compare' },
          { say: '2 × 45 = 90, and 15 × 6 = 90. Same answer both ways, so the two ratios really are equal.' },
        ],
        pictures: [{ kind: 'eq', text: '2/15 = 6/45', lines: ['2 × 45 = 90', '15 × 6 = 90'] }] },
      { title: 'One thing not to do', text: "Here is the mix-up to avoid. Don't add the difference to the other number. The inches were multiplied, so the miles get multiplied by that same factor.",
        beats: [
          { say: 'Here is the mix-up to avoid.' },
          { say: "Don't add the difference to the other number.", pic: 0 },
          { say: 'The inches were multiplied, so the miles get multiplied by that same factor.' },
        ],
        pictures: [{ kind: 'cards', wrong: '2 → 6 is + 4, so 15 + 4 = 19 miles', right: '2 → 6 is × 3, so 15 × 3 = 45 miles' }] },
    ],
    turn: {
      text: 'On a map, 3 inches stands for 20 miles. Two towns are 12 inches apart. How many miles apart are they?',
      picture: table([['Inches', '3', '12'], ['Miles', '20', '?']], ['', 'Scale', 'Towns']),
      answer: 80,
      steps: ['12 inches is 3 inches times 4.', 'Multiply the miles by 4 too: 20 × 4.', 'So the towns are 80 miles apart.'],
      prompt: 'Find what the inches were multiplied by. Do the same to the miles.',
      hint1: 'What do you multiply 3 by to get 12?',
      hint2: 'Multiply the 20 miles by that same number.',
      twin: { text: '4 cups of juice make 10 servings. How many servings do 6 cups make?',
        picture: table([['Cups', '4', '6'], ['Servings', '10', '?']]),
        answer: 15,
        steps: ['6 ÷ 4 = 1.5, so the factor is 1.5.', 'Multiply the servings by 1.5 too: 10 × 1.5.', 'So 6 cups make 15 servings.'],
        hint1: 'What do you multiply 4 by to get 6? It is not a whole number.',
        hint2: 'Find the servings for 1 cup first: 10 ÷ 4. Then take 6 cups.' },
    },
    won: { text: 'You found the factor and used it on the miles too.', sticker: 'An equation like 3/20 = 12/80, saying two ratios are equal, is called a proportion.' },
    twinWon: { text: 'You multiplied 4 and 10 by the same factor: 6 cups make 15 servings.', sticker: 'An equation like 4/10 = 6/15, saying two ratios are equal, is called a proportion.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'On a map, 2 inches stands for 25 miles. Two lakes are 8 inches apart. How many miles apart are they?',
        picture: table([['Inches', '2', '8'], ['Miles', '25', '?']]), answer: 100,
        steps: ['8 inches is 2 inches times 4.', 'Multiply the miles by 4 too: 25 × 4.', 'So the lakes are 100 miles apart.'] } },
      { why: 'Same idea, new numbers', problem: { text: '5 notebooks cost $8. How many dollars do 15 notebooks cost?',
        picture: table([['Notebooks', '5', '15'], ['Cost ($)', '8', '?']]), answer: 24,
        steps: ['15 notebooks is 5 notebooks times 3.', 'Multiply the cost by 3 too: 8 × 3.', 'So 15 notebooks cost $24.'] } },
      { why: 'Still "the same factor for both"', problem: { text: 'Solve the proportion 6/9 = ?/12.',
        picture: table([['Top', '6', '?'], ['Bottom', '9', '12']]), answer: 8,
        steps: ['Multiply across: 6 × 12 = 72.', 'The missing number times 9 must also make 72: 72 ÷ 9.', 'So the missing number is 8.'] } },
      { why: 'A little harder', problem: { text: 'A car goes 150 miles on 6 gallons of gas. How many miles does it go on 10 gallons?',
        picture: table([['Gallons', '6', '10'], ['Miles', '150', '?']]), answer: 250,
        steps: ['Multiply across: 150 × 10 = 1,500.', 'The missing miles times 6 must also make 1,500: 1,500 ÷ 6.', 'So the car goes 250 miles.'] } },
      { why: 'Same math in a story', problem: { text: 'For a party, 4 pizzas feed 14 people. How many pizzas feed 35 people?',
        picture: table([['Pizzas', '4', '?'], ['People', '14', '35']]), answer: 10,
        steps: ['35 ÷ 14 = 2.5, so the factor is 2.5.', 'Multiply the pizzas by 2.5 too: 4 × 2.5.', 'So 35 people need 10 pizzas.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m1-t6', title: 'Percent increase and decrease', skill: 'Find a percent change: change ÷ original × 100',
    bigIdea: 'Find the change, then compare it to the original amount: change ÷ original × 100.',
    screens: [
      { title: 'A ticket costs more', text: 'A concert ticket cost $20 last year. This year it costs $25. By what percent did the price go up?',
        pictures: [change('$20', 20, '$25', 25)] },
      { title: '$5 out of what?', text: 'The price went up $5. That part is easy. But a percent always compares one amount to another amount. So $5 out of what? Out of the old $20, or out of the new $25? Those two give different answers.',
        beats: [
          { say: 'The price went up $5. That part is easy.', pic: 0, effect: 'draw' },
          { say: 'But a percent always compares one amount to another amount.' },
          { say: 'So $5 out of what? Out of the old $20, or out of the new $25?' },
          { say: 'Those two give different answers.', write: '$5 out of what?' },
        ],
        pictures: [change('$20', 20, '$25', 25)] },
      { title: 'The big idea', text: 'Find the change, then compare it to the original amount: change ÷ original × 100.',
        beats: [
          { say: 'Find the change, then compare it to the original amount: change ÷ original × 100.', pic: 0, effect: 'draw' },
        ],
        pictures: [change('$20', 20, '$25', 25)] },
      { title: 'Find the change', text: 'Start with the change. Take the new price and subtract the old one. $25 − $20 = $5. That $5 is the piece that got added on.',
        beats: [
          { say: 'Start with the change.', pic: 0, effect: 'draw' },
          { say: 'Take the new price and subtract the old one.' },
          { say: '$25 − $20 = $5.', pic: 1 },
          { say: 'That $5 is the piece that got added on.' },
        ],
        pictures: [tape([{ label: 'Before', cells: [{ w: 20, text: '$20' }] }, { label: 'After', cells: [{ w: 20, text: '$20' }, { w: 5, text: '$5', shade: true }], brace: '$25' }], true), { kind: 'eq', text: '25 − 20 = 5' }] },
      { title: 'Compare to the original', text: "Now hold that change against last year's price. Cut the $20 into equal $5 pieces. Four of them. And the change is exactly one of those four pieces: 5 ÷ 20 = 0.25.",
        beats: [
          { say: "Now hold that change against last year's price.", pic: 0, effect: 'draw' },
          { say: 'Cut the $20 into equal $5 pieces. Four of them.' },
          { say: 'And the change is exactly one of those four pieces: 5 ÷ 20 = 0.25.', pic: 1 },
        ],
        pictures: [tape([
          { label: 'Before', cells: Array.from({ length: 4 }, () => ({ w: 5, text: '$5' })) },
          { label: 'After', cells: [...Array.from({ length: 4 }, () => ({ w: 5, text: '$5' })), { w: 5, text: '$5', shade: true }] },
        ], true), { kind: 'eq', text: '5 ÷ 20 = 0.25' }] },
      { title: 'Make it a percent', text: 'One last move. A decimal turns into a percent when you multiply by 100. 0.25 × 100 = 25, so the ticket went up 25%.',
        beats: [
          { say: 'One last move.' },
          { say: 'A decimal turns into a percent when you multiply by 100.', write: '× 100 → percent' },
          { say: '0.25 × 100 = 25, so the ticket went up 25%.', pic: 0 },
        ],
        pictures: [{ kind: 'eq', text: '5 ÷ 20 × 100 = 25%' }] },
      { title: 'One thing not to do', text: "Here is where people slip. Don't divide by the new amount. The change always gets compared to the amount you started with.",
        beats: [
          { say: 'Here is where people slip.' },
          { say: "Don't divide by the new amount.", pic: 0 },
          { say: 'The change always gets compared to the amount you started with.' },
        ],
        pictures: [{ kind: 'cards', wrong: '5 ÷ 25 × 100 = 20% up', right: '5 ÷ 20 × 100 = 25% up' }] },
    ],
    turn: {
      text: 'A game cost $40. Now it costs $46. By what percent did the price go up?',
      picture: change('$40', 40, '$46', 46),
      answer: 15,
      steps: ['The change is $46 − $40 = $6.', 'Compare it to the original: 6 ÷ 40 = 0.15.', 'Times 100: the price went up 15%.'],
      prompt: 'Find the change. Divide it by the original price, then multiply by 100.',
      hint1: 'How many dollars did the price go up?',
      hint2: 'Divide that change by the original $40, then multiply by 100.',
      twin: { text: 'A bike cost $80. On sale it costs $60. By what percent did the price go down?',
        picture: change('$80', 80, '$60', 60),
        answer: 25,
        steps: ['The change is $80 − $60 = $20.', 'Compare it to the original: 20 ÷ 80 = 0.25.', 'Times 100: the price went down 25%.'],
        hint1: 'How many dollars did the price drop?',
        hint2: 'Divide the drop by the original $80, not the sale price. Then multiply by 100.' },
    },
    won: { text: 'You found the change and compared it to the original price.', sticker: 'Change ÷ original × 100 is the percent change. When the amount grows, it is a percent increase.' },
    twinWon: { text: 'You compared the drop to the original $80: the price went down 25%.', sticker: 'Change ÷ original × 100 is the percent change. When the amount shrinks, it is a percent decrease.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A shirt cost $50. Now it costs $60. By what percent did the price go up?',
        picture: change('$50', 50, '$60', 60), answer: 20,
        steps: ['The change is $60 − $50 = $10.', 'Compare it to the original: 10 ÷ 50 = 0.2.', 'Times 100: the price went up 20%.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A jacket cost $80. On sale it costs $68. By what percent did the price go down?',
        picture: change('$80', 80, '$68', 68), answer: 15,
        steps: ['The change is $80 − $68 = $12.', 'Compare it to the original: 12 ÷ 80 = 0.15.', 'Times 100: the price went down 15%.'] } },
      { why: 'Still "divide by the original"', problem: { text: 'A plant was 16 inches tall. Now it is 20 inches tall. By what percent did it grow?',
        picture: change('16 in', 16, '20 in', 20), answer: 25,
        steps: ['The change is 20 − 16 = 4 inches.', 'Compare it to the original 16, not the new 20: 4 ÷ 16 = 0.25.', 'Times 100: the plant grew 25%.'] } },
      { why: 'A little harder', problem: { text: 'A town had 1,250 people. Now it has 1,400 people. By what percent did the town grow?',
        picture: change('1,250', 1250, '1,400', 1400), answer: 12,
        steps: ['The change is 1,400 − 1,250 = 150 people.', 'Compare it to the original: 150 ÷ 1,250 = 0.12.', 'Times 100: the town grew 12%.'] } },
      { why: 'Same math in a story', problem: { text: 'Last season the soccer team scored 40 goals. This season they scored 30 goals. By what percent did their goals go down?',
        picture: change('40 goals', 40, '30 goals', 30), answer: 25,
        steps: ['The change is 40 − 30 = 10 goals.', 'Compare it to last season: 10 ÷ 40 = 0.25.', 'Times 100: their goals went down 25%.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m1-t7', title: 'Markup, tax and tip', skill: 'Find a final price after a markup, sales tax or tip',
    bigIdea: 'Find the percent of the price and add it on. That is the same as taking 100% plus that percent of the price.',
    screens: [
      { title: 'A shop sets a price', text: 'A shop pays $20 for a T-shirt. It adds 40% on top to set the price you pay. What does the tag say?',
        pictures: [addOn('$20', ['40%'], 'Price: ?')] },
      { title: 'Not $60', text: 'Careful with that 40. It does not mean $40, so the tag is not $20 plus $40. A percent is a share out of 100. So 40% means 40 dollars for every 100 dollars.',
        beats: [
          { say: 'Careful with that 40.', pic: 0, effect: 'draw' },
          { say: 'It does not mean $40, so the tag is not $20 plus $40.' },
          { say: 'A percent is a share out of 100.' },
          { say: 'So 40% means 40 dollars for every 100 dollars.', write: '40% = 40 out of every 100' },
        ],
        pictures: [addOn('$20', ['40%'], 'Price: ?')] },
      { title: 'The big idea', text: 'Find the percent of the price and add it on. That is the same as taking 100% plus that percent of the price.',
        beats: [
          { say: 'Find the percent of the price and add it on.', pic: 0, effect: 'draw' },
          { say: 'That is the same as taking 100% plus that percent of the price.' },
        ],
        pictures: [addOn('$20', ['40%'], 'Price: ?')] },
      { title: 'Find the extra', text: 'So find the extra first. 10% of $20 is $2. And 40% is four of those tens. 4 × $2 = $8.',
        beats: [
          { say: 'So find the extra first.' },
          { say: '10% of $20 is $2.', write: '10% of $20 = $2' },
          { say: 'And 40% is four of those tens.', pic: 0, effect: 'draw' },
          { say: '4 × $2 = $8.', pic: 1 },
        ],
        pictures: [addOn('$20', ['$8'], 'Price: ?', true), { kind: 'eq', text: '40% of 20 = 8' }] },
      { title: 'Add it on', text: 'Now add the extra to what the shop paid. $20 + $8 = $28. That is the number on the tag.',
        beats: [
          { say: 'Now add the extra to what the shop paid.' },
          { say: '$20 + $8 = $28.', pic: 1 },
          { say: 'That is the number on the tag.', pic: 0, effect: 'draw' },
        ],
        pictures: [addOn('$20', ['$8'], '$28', true), { kind: 'eq', text: '20 + 8 = 28' }] },
      { title: 'One step instead of two', text: 'There is a faster way, once you see it. The tag is all of the $20, which is 100%, plus 40% more. Together that is 140% of the $20. And 140% is just 1.4, so 1.4 × $20 = $28. Same answer, one step.',
        beats: [
          { say: 'There is a faster way, once you see it.' },
          { say: 'The tag is all of the $20, which is 100%, plus 40% more.', pic: 0 },
          { say: 'Together that is 140% of the $20.', write: '100% + 40% = 140%' },
          { say: 'And 140% is just 1.4, so 1.4 × $20 = $28. Same answer, one step.', pic: 1 },
        ],
        pictures: [addOn('$20', ['$8'], '140% = $28'), { kind: 'eq', text: '140% of 20 = 1.4 × 20 = 28' }] },
      { title: 'One thing not to do', text: "One thing to watch for. Don't stop once you have the extra. The $8 is what gets added on. The tag is the $20 and the $8 together.",
        beats: [
          { say: 'One thing to watch for.' },
          { say: "Don't stop once you have the extra.", pic: 0 },
          { say: 'The $8 is what gets added on.' },
          { say: 'The tag is the $20 and the $8 together.' },
        ],
        pictures: [{ kind: 'cards', wrong: 'Price: $8', right: 'Price: $20 + $8 = $28' }] },
    ],
    turn: {
      text: 'A shop pays $30 for a hat and adds 40% on top. What is the price, in dollars?',
      picture: addOn('$30', ['40%'], 'Price: ?'),
      answer: 42,
      steps: ['10% of $30 is $3, so 40% is 4 × $3 = $12.', 'Add it on: $30 + $12.', 'So the price is $42.'],
      prompt: 'Find 40% of what the shop paid. Then add it on.',
      hint1: 'Find 10% of $30 first.',
      hint2: 'The extra is 4 of those 10% pieces. Add it to $30.',
      twin: { text: 'A meal costs $36. You leave an 18% tip. What is the total, in dollars?',
        picture: addOn('$36', ['18%']),
        answer: 42.48,
        steps: ['1% of $36 is $0.36, so 18% is 18 × $0.36 = $6.48.', 'Add the tip to the meal: $36 + $6.48.', 'So the total is $42.48.'],
        hint1: 'Find 1% of $36 first.',
        hint2: 'The tip is 18 of those 1% pieces. Add it to $36.' },
    },
    won: { text: 'You found the extra, then added it to what the shop paid.', sticker: 'The amount a store adds to what it paid is called a markup. Tax and tips are added on the same way.' },
    twinWon: { text: 'You found an 18% tip on $36 and a total of $42.48.', sticker: 'Money you add for good service is a tip. It is added on the same way as a markup.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A shop pays $15 for a cap and adds 60% on top. What is the price, in dollars?',
        picture: addOn('$15', ['60%'], 'Price: ?'), answer: 24,
        steps: ['10% of $15 is $1.50, so 60% is 6 × $1.50 = $9.', 'Add it on: $15 + $9.', 'So the price is $24.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Headphones cost $55. The sales tax is 7%. What is the total, in dollars?',
        picture: addOn('$55', ['7%']), answer: 58.85,
        steps: ['1% of $55 is $0.55, so 7% is 7 × $0.55 = $3.85.', 'Add the tax: $55 + $3.85.', 'So the total is $58.85.'] } },
      { why: 'Still "find the percent, then add it on"', problem: { text: 'A haircut costs $25. You leave a 15% tip. What is the total, in dollars?',
        picture: addOn('$25', ['15%']), answer: 28.75,
        steps: ['10% of $25 is $2.50 and 5% is $1.25, so 15% is $3.75.', 'Add the tip: $25 + $3.75.', 'So the total is $28.75.'] } },
      { why: 'A little harder', problem: { text: 'A store pays $40 for shoes and adds 50% on top. Then 5% sales tax is added to that price. What is the total, in dollars?',
        picture: addOn('$40', ['50%', '5%']), answer: 63,
        steps: ['50% of $40 is $20, so the price is $40 + $20 = $60.', 'The tax is 5% of $60, which is $3.', 'Add it: $60 + $3. So the total is $63.'] } },
      { why: 'Same math in a story', problem: { text: 'The Kim family’s dinner costs $64. They pay 8% tax and leave a 15% tip, both on the $64. What do they pay in all, in dollars?',
        picture: addOn('$64', ['8%', '15%']), answer: 78.72,
        steps: ['Tax: 1% of $64 is $0.64, so 8% is $5.12.', 'Tip: 10% is $6.40 and 5% is $3.20, so 15% is $9.60.', 'Add: $64 + $5.12 + $9.60. So they pay $78.72.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m1-t8', title: 'Percent error', skill: 'Find percent error: |estimate − actual| ÷ actual × 100',
    bigIdea: 'Find how far the guess is from the real amount. Divide by the real amount, then multiply by 100.',
    screens: [
      { title: 'Guess the jar', text: 'You guess a jar holds 45 jelly beans. The real count is 50. How close was your guess?',
        pictures: [guess('45', 45, '50', 50)] },
      { title: '5 off is not always close', text: 'Your guess is 5 beans off. Now, is 5 off good? For a jar of 50, that is pretty close. For a jar of 10, it is way off. So the gap on its own does not tell you how good the guess was.',
        beats: [
          { say: 'Your guess is 5 beans off.', pic: 0, effect: 'draw' },
          { say: 'Now, is 5 off good?' },
          { say: 'For a jar of 50, that is pretty close. For a jar of 10, it is way off.' },
          { say: 'So the gap on its own does not tell you how good the guess was.', write: 'the gap alone is not enough' },
        ],
        pictures: [guess('45', 45, '50', 50)] },
      { title: 'The big idea', text: 'Find how far the guess is from the real amount. Divide by the real amount, then multiply by 100.',
        beats: [
          { say: 'Find how far the guess is from the real amount.', pic: 0, effect: 'draw' },
          { say: 'Divide by the real amount, then multiply by 100.' },
        ],
        pictures: [guess('45', 45, '50', 50)] },
      { title: 'How far off?', text: 'Start with the gap. 50 − 45 = 5, so the guess was 5 beans away. And if you had guessed too high, you would still write the gap as a positive number. We only care how far off it was, not which side.',
        beats: [
          { say: 'Start with the gap.', pic: 0, effect: 'draw' },
          { say: '50 − 45 = 5, so the guess was 5 beans away.', pic: 1 },
          { say: 'And if you had guessed too high, you would still write the gap as a positive number.', write: 'the gap is always positive' },
          { say: 'We only care how far off it was, not which side.' },
        ],
        pictures: [tape([{ label: 'Guess', cells: [{ w: 45, text: '45' }, { w: 5, text: '5', shade: true }] }, { label: 'Real', cells: [{ w: 50, text: '50' }] }], true),
          { kind: 'eq', text: '50 − 45 = 5' }] },
      { title: 'Compare to the real amount', text: 'Now hold that gap against the real count. Cut the 50 into equal pieces of 5. Ten of them. The gap is one piece out of ten: 5 ÷ 50 = 0.1.',
        beats: [
          { say: 'Now hold that gap against the real count.', pic: 0, effect: 'draw' },
          { say: 'Cut the 50 into equal pieces of 5. Ten of them.' },
          { say: 'The gap is one piece out of ten: 5 ÷ 50 = 0.1.', pic: 1 },
        ],
        pictures: [tape([
          { label: 'Guess', cells: [...Array.from({ length: 9 }, () => ({ w: 1, text: '5' })), { w: 1, text: '5', shade: true }] },
          { label: 'Real', cells: Array.from({ length: 10 }, () => ({ w: 1, text: '5' })) },
        ], true), { kind: 'eq', text: '5 ÷ 50 = 0.1' }] },
      { title: 'Make it a percent', text: 'Last step, same as always. Multiply by 100 to turn it into a percent. 0.1 × 100 = 10, so your guess was 10% off.',
        beats: [
          { say: 'Last step, same as always.' },
          { say: 'Multiply by 100 to turn it into a percent.', write: '× 100 → percent' },
          { say: '0.1 × 100 = 10, so your guess was 10% off.', pic: 0 },
        ],
        pictures: [{ kind: 'eq', text: '5 ÷ 50 × 100 = 10%' }] },
      { title: 'One thing not to do', text: "Here is the slip to avoid. Don't divide by your own guess. Your guess is the thing being tested, so the gap gets compared to the real amount.",
        beats: [
          { say: 'Here is the slip to avoid.' },
          { say: "Don't divide by your own guess.", pic: 0 },
          { say: 'Your guess is the thing being tested, so the gap gets compared to the real amount.' },
        ],
        pictures: [{ kind: 'cards', wrong: '5 ÷ 45 × 100', right: '5 ÷ 50 × 100 = 10%' }] },
    ],
    turn: {
      text: 'You guess a jar holds 68 marbles. The real count is 80. By what percent was your guess off?',
      picture: guess('68', 68, '80', 80),
      answer: 15,
      steps: ['The gap is 80 − 68 = 12 marbles.', 'Compare it to the real count: 12 ÷ 80 = 0.15.', 'Times 100: your guess was 15% off.'],
      prompt: 'Find the gap. Divide it by the real count, then multiply by 100.',
      hint1: 'How many marbles away was your guess?',
      hint2: 'Divide that gap by the real 80, then multiply by 100.',
      twin: { text: 'You guess a trip takes 60 minutes. It really takes 48 minutes. By what percent was your guess off?',
        picture: guess('60 min', 60, '48 min', 48),
        answer: 25,
        steps: ['The gap is 60 − 48 = 12 minutes.', 'Compare it to the real time: 12 ÷ 48 = 0.25.', 'Times 100: your guess was 25% off.'],
        hint1: 'How many minutes apart are the guess and the real time?',
        hint2: 'Divide the gap by the real 48 minutes, not by your guess. Then multiply by 100.' },
    },
    won: { text: 'You found the gap and compared it to the real count.', sticker: 'How far off a guess is, as a percent of the real amount, is called percent error.' },
    twinWon: { text: 'You divided the gap by the real 48 minutes: your guess was 25% off.', sticker: 'How far off a guess is, as a percent of the real amount, is called percent error.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'You guess a jar holds 36 buttons. The real count is 40. What is the percent error?',
        picture: guess('36', 36, '40', 40), answer: 10,
        steps: ['The gap is 40 − 36 = 4.', 'Compare it to the real count: 4 ÷ 40 = 0.1.', 'Times 100: the percent error is 10%.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'You guess 90 people are in a line. There are really 75. What is the percent error?',
        picture: guess('90', 90, '75', 75), answer: 20,
        steps: ['The gap is 90 − 75 = 15.', 'Compare it to the real 75: 15 ÷ 75 = 0.2.', 'Times 100: the percent error is 20%.'] } },
      { why: 'Still "divide by the real amount"', problem: { text: 'A pencil is really 25 cm long. You measure it as 24 cm. What is the percent error?',
        picture: guess('24 cm', 24, '25 cm', 25), answer: 4,
        steps: ['The gap is 25 − 24 = 1 cm.', 'Compare it to the real length: 1 ÷ 25 = 0.04.', 'Times 100: the percent error is 4%.'] } },
      { why: 'A little harder', problem: { text: 'You estimate a room is 12.6 meters long. It is really 12 meters. What is the percent error?',
        picture: guess('12.6 m', 12.6, '12 m', 12), answer: 5,
        steps: ['The gap is 12.6 − 12 = 0.6 meters.', 'Compare it to the real length: 0.6 ÷ 12 = 0.05.', 'Times 100: the percent error is 5%.'] } },
      { why: 'Same math in a story', problem: { text: 'Ava guesses 350 people will come to the school play. 400 people come. What is her percent error?',
        picture: guess('350', 350, '400', 400), answer: 12.5,
        steps: ['The gap is 400 − 350 = 50 people.', 'Compare it to the real 400: 50 ÷ 400 = 0.125.', 'Times 100: her percent error is 12.5%.'] } },
    ],
  },
]
