/**
 * Grade 7 · Module 3 — Equivalent expressions, equations and inequalities.
 * Written to docs/new-flow/AUTHORING.md. Continues Grade 6 · Module 5 (g6m5.ts).
 * Teaching pictures: `tape` (t1, t5, t8), `area` (t2, t3), `balance` + `table` (t4), `numline` (t6, t7).
 * Expressions and inequalities are answered as choices; nothing asks the child to type a letter.
 */
import type { Lesson, Picture } from '../script'

const eq = (text: string, lines?: string[]): Picture => ({ kind: 'eq', text, lines })
const cards = (wrong: string, right: string): Picture => ({ kind: 'cards', wrong, right })
/** Algebra tiles on one tape: a part with a letter is 2 wide, a plain number 1 wide. `shade` shades the letter parts. */
const tiles = (parts: string[], brace?: string, motion = false, shade = false): Picture =>
  ({ kind: 'tape', rows: [{ cells: parts.map(t => /[a-z]/.test(t) ? { w: 2, text: t, shade } : { w: 1, text: t }), brace }], motion })
/** Area model: the number outside on the left, the parts inside across the top. */
const box = (outside: string, inside: string[], cells?: (string | null)[][], motion = false): Picture =>
  ({ kind: 'area', rows: [outside], cols: inside, cells, widths: inside.map(t => /[a-z]/.test(t) ? 3 : 1), motion })
const bal = (left: string, right: string): Picture => ({ kind: 'balance', left, right })
const sides = (rows: string[][], motion = false): Picture => ({ kind: 'table', head: ['Left side', '', 'Right side'], rows, motion })
const line = (min: number, max: number, extra: Partial<Extract<Picture, { kind: 'numline' }>> = {}): Picture =>
  ({ kind: 'numline', min, max, ticks: max - min, ...extra })
/** `groups` equal boxes of x and a plain number, all on one tape. */
const groups = (n: number, q: string, brace?: string, motion = false): Picture =>
  ({ kind: 'tape', rows: [{ cells: Array.from({ length: n }, () => [{ w: 3, text: 'x' }, { w: 1, text: q, shade: true }]).flat(), brace }], motion })

export const G7M3: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m3-t1', title: 'Combine like terms', skill: 'Make an expression shorter by putting the letter parts together and the plain numbers together',
    bigIdea: 'Put the x parts together and the plain numbers together. An x part and a plain number never join.',
    screens: [
      { title: 'Boxes of pens', text: 'You have 3 boxes with x pens in each, and 5 loose pens. Then you get 2 more boxes and give 1 loose pen away. That is 3x + 5 + 2x − 1. Can you write it shorter?',
        pictures: [tiles(['x', 'x', 'x', '5', 'x', 'x', '−1'])] },
      { title: 'It is long and mixed up', text: "Look at that line. The boxes and the loose pens are all jumbled up together. And here's the thing: you can't add 3x and 5 to make one number. You don't know how many pens are in a box yet.",
        beats: [
          { say: 'Look at that line.', pic: 0, effect: 'draw' },
          { say: 'The boxes and the loose pens are all jumbled up together.' },
          { say: "And here's the thing: you can't add 3x and 5 to make one number.", write: '3x + 5 is not one number' },
          { say: "You don't know how many pens are in a box yet." },
        ],
        pictures: [tiles(['x', 'x', 'x', '5', 'x', 'x', '−1'])] },
      { title: 'The big idea', text: 'Put the x parts together and the plain numbers together. An x part and a plain number never join.',
        beats: [
          { say: 'Put the x parts together and the plain numbers together.', pic: 0, effect: 'draw' },
          { say: 'An x part and a plain number never join.' },
        ],
        pictures: [tiles(['x', 'x', 'x', 'x', 'x', '5', '−1'], undefined, false, true)] },
      { title: 'Group the x parts', text: "Let's slide all the boxes next to each other. 3 boxes and 2 more boxes. That's 5 boxes. So 3x + 2x = 5x.",
        beats: [
          { say: "Let's slide all the boxes next to each other.", pic: 0, effect: 'draw' },
          { say: "3 boxes and 2 more boxes. That's 5 boxes." },
          { say: 'So 3x + 2x = 5x.', pic: 1 },
        ],
        pictures: [tiles(['x', 'x', 'x', 'x', 'x', '5', '−1'], undefined, true, true), eq('3x + 2x', ['5x'])] },
      { title: 'Group the plain numbers', text: 'Now the loose pens. You had 5, and you gave 1 away. 5 − 1 = 4 loose pens left.',
        beats: [
          { say: 'Now the loose pens.', pic: 0, effect: 'draw' },
          { say: 'You had 5, and you gave 1 away.' },
          { say: '5 − 1 = 4 loose pens left.', pic: 1 },
        ],
        pictures: [tiles(['x', 'x', 'x', 'x', 'x', '4'], '5x + 4', true, true), eq('5 − 1', ['4'])] },
      { title: 'Put it together', text: "So that whole long line, 3x + 5 + 2x − 1, is just 5x + 4. Let's check it with x = 2. The long way gives 6 + 5 + 4 − 1 = 14, and the short way gives 10 + 4 = 14. They match.",
        beats: [
          { say: 'So that whole long line, 3x + 5 + 2x − 1, is just 5x + 4.', pic: 0 },
          { say: "Let's check it with x = 2." },
          { say: 'The long way gives 6 + 5 + 4 − 1 = 14, and the short way gives 10 + 4 = 14. They match.' },
        ],
        pictures: [eq('3x + 5 + 2x − 1 = 5x + 4', ['6 + 5 + 4 − 1 = 14', '10 + 4 = 14'])] },
      { title: 'One thing not to do', text: "Here's the slip almost everybody makes. Don't join an x part with a plain number. 3x + 5 is not 8x. It stays 3x + 5.",
        beats: [
          { say: "Here's the slip almost everybody makes." },
          { say: "Don't join an x part with a plain number.", pic: 0 },
          { say: '3x + 5 is not 8x. It stays 3x + 5.' },
        ],
        pictures: [cards('3x + 5 = 8x', '3x + 5 stays 3x + 5')] },
    ],
    turn: {
      text: 'Which is the same as 4x + 2 + 3x + 6?',
      picture: tiles(['x', 'x', 'x', 'x', '2', 'x', 'x', 'x', '6']),
      answer: { choices: ['7x + 8', '15x', '12x + 3', '7x + 6'], correct: 0 },
      steps: ['Put the x parts together: 4x + 3x = 7x.', 'Put the plain numbers together: 2 + 6 = 8.', 'So it is 7x + 8.'],
      prompt: 'Put the x parts together. Then put the plain numbers together.',
      hint1: 'Which parts have an x, and which are plain numbers?',
      hint2: 'Add 4x and 3x. Then add 2 and 6. Do not join the two answers.',
      twin: { text: 'Which is the same as 5x + 9 − 2x − 4?',
        picture: eq('5x + 9 − 2x − 4'),
        answer: { choices: ['3x + 5', '7x + 13', '8x', '3x + 13'], correct: 0 },
        steps: ['The x parts: 5x − 2x = 3x.', 'The plain numbers: 9 − 4 = 5.', 'So it is 3x + 5.'],
        hint1: 'Find the x parts. The minus sign belongs to the part right after it.',
        hint2: 'Take 2x away from 5x. Take 4 away from 9.' },
    },
    won: { text: 'You put the x parts together and the plain numbers together.', sticker: 'Parts with the same letter, like 3x and 2x, are called like terms. Putting them together is combining like terms.' },
    twinWon: { text: 'You took 2x from 5x and 4 from 9 to get 3x + 5.', sticker: 'Parts with the same letter, like 3x and 2x, are called like terms. Putting them together is combining like terms.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which is the same as 2x + 3 + 4x + 1?',
        picture: tiles(['x', 'x', '3', 'x', 'x', 'x', 'x', '1']), answer: { choices: ['6x + 4', '10x', '6x + 3', '8x + 2'], correct: 0 },
        steps: ['The x parts: 2x + 4x = 6x.', 'The plain numbers: 3 + 1 = 4.', 'So it is 6x + 4.'] } },
      { why: 'Same idea, new numbers', problem: { text: '8x + 3 + 2x + 9 becomes ?x + 12. What number goes in front of the x?',
        picture: eq('8x + 3 + 2x + 9 = ?x + 12'), answer: 10,
        steps: ['8x and 2x are the x parts.', 'Put them together: 8 + 2 groups of x.', 'So the number is 10.'] } },
      { why: 'Still "x parts with x parts"', problem: { text: 'Which is the same as 9x − 4 − 3x + 10?',
        picture: eq('9x − 4 − 3x + 10'), answer: { choices: ['6x + 6', '12x + 6', '6x − 14', '12x'], correct: 0 },
        steps: ['The x parts: 9x − 3x = 6x.', 'The plain numbers: −4 + 10 = 6.', 'So it is 6x + 6.'] } },
      { why: 'A little harder', problem: { text: 'Make 5x + 8 − x − 11 shorter. The x part is 4x. What is the plain number part?',
        picture: eq('5x + 8 − x − 11'), answer: -3,
        steps: ['A lone x means 1x, so 5x − x = 4x.', 'The plain numbers: 8 − 11.', 'So the plain number part is −3.'] } },
      { why: 'Same math in a story', problem: { text: 'T-shirts cost x dollars each. Ana buys 3 and pays a 2-dollar fee. Ben buys 4 and gets 5 dollars off. Together they pay 3x + 2 + 4x − 5 dollars. Which is the same?',
        picture: eq('3x + 2 + 4x − 5'), answer: { choices: ['7x − 3', '7x + 7', '10x', '7x + 3'], correct: 0 },
        steps: ['The x parts: 3x + 4x = 7x.', 'The plain numbers: 2 − 5 = −3.', 'So it is 7x − 3.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m3-t2', title: 'Expand brackets', skill: 'Multiply the number outside the brackets by every part inside, keeping track of negative signs',
    bigIdea: 'The number outside multiplies every part inside. Bring its sign along too.',
    screens: [
      { title: 'Tickets with a coupon', text: 'A ticket costs x dollars, and a coupon takes 4 dollars off each one. You buy 3 tickets, so you pay 3(x − 4). How can you write that without the brackets?',
        pictures: [box('3', ['x', '−4'])] },
      { title: 'You cannot work inside first', text: "Normally you'd work out the brackets first. But look inside: x − 4 can't become one number, because you don't know x. So we have to open the brackets another way.",
        beats: [
          { say: "Normally you'd work out the brackets first.", pic: 0, effect: 'draw' },
          { say: "But look inside: x − 4 can't become one number, because you don't know x." },
          { say: 'So we have to open the brackets another way.' },
        ],
        pictures: [box('3', ['x', '−4'])] },
      { title: 'The big idea', text: 'The number outside multiplies every part inside. Bring its sign along too.',
        beats: [
          { say: 'The number outside multiplies every part inside.', pic: 0, effect: 'draw' },
          { say: 'Bring its sign along too.' },
        ],
        pictures: [box('3', ['x', '−4'], [['3x', '−12']])] },
      { title: 'Multiply every part', text: 'So the 3 has to reach both parts inside. 3 × x = 3x. And 3 × (−4) = −12, because each of the 3 tickets gets 4 dollars off. So 3(x − 4) = 3x − 12.',
        beats: [
          { say: 'So the 3 has to reach both parts inside.', pic: 0, effect: 'draw' },
          { say: '3 × x = 3x.' },
          { say: 'And 3 × (−4) = −12, because each of the 3 tickets gets 4 dollars off.' },
          { say: 'So 3(x − 4) = 3x − 12.', pic: 1 },
        ],
        pictures: [box('3', ['x', '−4'], [['3x', '−12']], true), eq('3(x − 4)', ['3x − 12'])] },
      { title: 'Now a negative outside', text: 'Now watch what a negative outside does. Try −2(x − 4). The −2 reaches the x first, and −2 × x = −2x.',
        beats: [
          { say: 'Now watch what a negative outside does.', pic: 0, effect: 'draw' },
          { say: 'Try −2(x − 4). The −2 reaches the x first, and −2 × x = −2x.', write: 'the sign comes along' },
        ],
        pictures: [box('−2', ['x', '−4'], [['−2x', null]], true)] },
      { title: 'Negative times negative', text: 'Next part: −2 × (−4). A negative times a negative comes out positive, so it is +8. So −2(x − 4) = −2x + 8.',
        beats: [
          { say: 'Next part: −2 × (−4).', pic: 0, effect: 'draw' },
          { say: 'A negative times a negative comes out positive, so it is +8.', write: 'negative × negative → positive' },
          { say: 'So −2(x − 4) = −2x + 8.', pic: 1 },
        ],
        pictures: [box('−2', ['x', '−4'], [['−2x', '+8']], true), eq('−2(x − 4)', ['−2x + 8'])] },
      { title: 'One thing not to do', text: "Here's the one that catches people. Don't lose the sign on the second part. −2 × (−4) is +8, not −8.",
        beats: [
          { say: "Here's the one that catches people." },
          { say: "Don't lose the sign on the second part.", pic: 0 },
          { say: '−2 × (−4) is +8, not −8.' },
        ],
        pictures: [cards('−2(x − 4) = −2x − 8', '−2(x − 4) = −2x + 8')] },
    ],
    turn: {
      text: 'Which is the same as −3(x − 5)?',
      picture: box('−3', ['x', '−5']),
      answer: { choices: ['−3x + 15', '−3x − 15', '−3x − 5', '3x + 15'], correct: 0 },
      steps: ['Multiply −3 by each part inside.', '−3 × x = −3x, and −3 × (−5) = +15, because a negative times a negative is positive.', 'So it is −3x + 15.'],
      prompt: 'Multiply the number outside by every part inside. Watch the signs.',
      hint1: 'Which parts does the −3 multiply?',
      hint2: 'Work out −3 × x, then −3 × (−5). What sign does a negative times a negative give?',
      twin: { text: 'Which is the same as −4(x + 2)?',
        picture: box('−4', ['x', '2']),
        answer: { choices: ['−4x − 8', '−4x + 8', '−4x + 2', '4x − 8'], correct: 0 },
        steps: ['Multiply −4 by each part inside.', '−4 × x = −4x, and −4 × 2 = −8, because a negative times a positive is negative.', 'So it is −4x − 8.'],
        hint1: 'Does the −4 multiply only the x, or the 2 as well?',
        hint2: 'Work out −4 × 2. What sign does a negative times a positive give?' },
    },
    won: { text: 'You multiplied every part inside and kept track of the signs.', sticker: 'Multiplying every part inside is the distributive property. Writing it without brackets is called expanding.' },
    twinWon: { text: 'You multiplied −4 by x and by 2 to get −4x − 8.', sticker: 'Multiplying every part inside is the distributive property. Writing it without brackets is called expanding.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which is the same as −2(x − 6)?',
        picture: box('−2', ['x', '−6']), answer: { choices: ['−2x + 12', '−2x − 12', '−2x − 6', '2x + 12'], correct: 0 },
        steps: ['Multiply −2 by each part.', '−2 × x = −2x, and −2 × (−6) = +12.', 'So it is −2x + 12.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Write 5(x − 3) without brackets. What is the plain number part?',
        picture: box('5', ['x', '−3']), answer: -15,
        steps: ['5 multiplies each part.', '5 × x = 5x, and 5 × (−3) is a positive times a negative.', 'So the plain number part is −15.'] } },
      { why: 'Still "every part, with its sign"', problem: { text: 'Which is the same as −5(2x − 1)?',
        picture: box('−5', ['2x', '−1']), answer: { choices: ['−10x + 5', '−10x − 5', '−10x − 1', '10x + 5'], correct: 0 },
        steps: ['Multiply −5 by each part.', '−5 × 2x = −10x, and −5 × (−1) = +5.', 'So it is −10x + 5.'] } },
      { why: 'A little harder', problem: { text: 'Write −6(3 − 2x) without brackets. What number goes in front of the x?',
        picture: box('−6', ['3', '−2x']), answer: 12,
        steps: ['Multiply −6 by each part.', '−6 × 3 = −18, and −6 × (−2x) is a negative times a negative, so it is positive.', 'So the number in front of x is 12.'] } },
      { why: 'Same math in a story', problem: { text: 'A gym costs x dollars a month, and a deal takes 3 dollars off every month. Which shows the cost of 4 months?',
        picture: box('4', ['x', '−3']), answer: { choices: ['4x − 12', '4x − 3', 'x − 12', '4x + 12'], correct: 0 },
        steps: ['One month costs x − 3, so 4 months cost 4(x − 3).', '4 × x = 4x, and 4 × (−3) = −12.', 'So it is 4x − 12.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m3-t3', title: 'Factor out a common number', skill: 'Rewrite an expression like 6x + 9 as a number times brackets, 3(2x + 3)',
    bigIdea: 'Find the biggest number that divides every part. Put it outside, and write what is left inside the brackets.',
    screens: [
      { title: 'Equal gift bags', text: 'A class has 6 packs with x pencils in each, and 9 erasers. That is 6x + 9 things. They want equal gift bags with nothing left over. How many bags, and what goes in each?',
        pictures: [box('?', ['?', '?'], [['6x', '9']])] },
      { title: 'Going backwards', text: "Last time you had the brackets and multiplied your way out of them. This time you're going backwards. All you have is 6x + 9, and you have to find the brackets it came from.",
        beats: [
          { say: 'Last time you had the brackets and multiplied your way out of them.', pic: 0, effect: 'draw' },
          { say: "This time you're going backwards." },
          { say: 'All you have is 6x + 9, and you have to find the brackets it came from.', write: 'go backwards' },
        ],
        pictures: [box('?', ['?', '?'], [['6x', '9']])] },
      { title: 'The big idea', text: 'Find the biggest number that divides every part. Put it outside, and write what is left inside the brackets.',
        beats: [
          { say: 'Find the biggest number that divides every part.', pic: 0, effect: 'draw' },
          { say: 'Put it outside, and write what is left inside the brackets.' },
        ],
        pictures: [box('?', ['?', '?'], [['6x', '9']])] },
      { title: 'A number that divides both', text: 'So look for a number that goes into both 6 and 9 with nothing left over. 3 does, and nothing bigger than 3 works for both. 6 ÷ 3 = 2, and 9 ÷ 3 = 3, no leftovers either way. So the 3 goes outside: 3 bags.',
        beats: [
          { say: 'So look for a number that goes into both 6 and 9 with nothing left over.' },
          { say: '3 does, and nothing bigger than 3 works for both.', write: 'biggest that divides every part' },
          { say: '6 ÷ 3 = 2, and 9 ÷ 3 = 3, no leftovers either way.', pic: 1 },
          { say: 'So the 3 goes outside: 3 bags.', pic: 0, effect: 'draw' },
        ],
        pictures: [box('3', ['?', '?'], [['6x', '9']], true), eq('6 ÷ 3 = 2', ['9 ÷ 3 = 3'])] },
      { title: 'What is left inside', text: "Now what's left for each bag? 6x ÷ 3 = 2x, and 9 ÷ 3 = 3. So one bag holds 2 packs and 3 erasers, and that is the 2x + 3 inside the brackets.",
        beats: [
          { say: "Now what's left for each bag?" },
          { say: '6x ÷ 3 = 2x, and 9 ÷ 3 = 3.', pic: 0, effect: 'draw' },
          { say: 'So one bag holds 2 packs and 3 erasers, and that is the 2x + 3 inside the brackets.' },
        ],
        pictures: [box('3', ['2x', '3'], [['6x', '9']], true)] },
      { title: 'Check by multiplying', text: "Let's check it by multiplying back out. 3 × 2x = 6x, and 3 × 3 = 9. That is 6x + 9, exactly what we started with.",
        beats: [
          { say: "Let's check it by multiplying back out.", pic: 0, effect: 'draw' },
          { say: '3 × 2x = 6x, and 3 × 3 = 9.' },
          { say: 'That is 6x + 9, exactly what we started with.', pic: 1 },
        ],
        pictures: [box('3', ['2x', '3'], [['6x', '9']]), eq('3(2x + 3)', ['6x + 9'])] },
      { title: 'One thing not to do', text: "Here's the slip to watch for. Don't divide only the first part. The 9 has to be divided by 3 as well.",
        beats: [
          { say: "Here's the slip to watch for." },
          { say: "Don't divide only the first part.", pic: 0 },
          { say: 'The 9 has to be divided by 3 as well.' },
        ],
        pictures: [cards('6x + 9 = 3(2x + 9)', '6x + 9 = 3(2x + 3)')] },
    ],
    turn: {
      text: 'Which is the same as 8x + 12?',
      picture: box('?', ['?', '?'], [['8x', '12']]),
      answer: { choices: ['4(2x + 3)', '4(2x + 12)', '2(4x + 3)', '4(4x + 8)'], correct: 0 },
      steps: ['The biggest number that divides both 8 and 12 is 4.', 'Divide each part by 4: 8x ÷ 4 = 2x, and 12 ÷ 4 = 3.', 'So it is 4(2x + 3).'],
      prompt: 'Find the biggest number that divides every part. Put it outside.',
      hint1: 'What is the biggest number that divides both 8 and 12?',
      hint2: 'Divide BOTH parts by that number, and write what is left inside the brackets.',
      twin: { text: 'What is the biggest number you can put outside the brackets in 10x + 15?',
        picture: box('?', ['?', '?'], [['10x', '15']]),
        answer: 5, steps: ['10 and 15 can both be divided by 5 with nothing left over. Nothing bigger works.', '10x + 15 = 5(2x + 3).', 'So the number is 5.'],
        hint1: 'Which numbers divide both 10 and 15 with nothing left over?',
        hint2: 'List what divides 15. Which of those also divides 10?' },
    },
    won: { text: 'You found the biggest number that divides every part and put it outside.', sticker: 'A number that divides every part is a common factor. Putting it outside the brackets is called factoring.' },
    twinWon: { text: 'You found that 5 divides both 10 and 15.', sticker: 'A number that divides every part is a common factor. Putting it outside the brackets is called factoring.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which is the same as 6x + 15?',
        picture: box('?', ['?', '?'], [['6x', '15']]), answer: { choices: ['3(2x + 5)', '3(2x + 15)', '6(x + 15)', '2(3x + 5)'], correct: 0 },
        steps: ['The biggest number that divides 6 and 15 is 3.', '6x ÷ 3 = 2x, and 15 ÷ 3 = 5.', 'So it is 3(2x + 5).'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is the biggest number you can put outside the brackets in 12x + 18?',
        picture: box('?', ['?', '?'], [['12x', '18']]), answer: 6,
        steps: ['12 and 18 can both be divided by 2, by 3 and by 6.', 'Nothing bigger divides both: 12x + 18 = 6(2x + 3).', 'So the number is 6.'] } },
      { why: 'Still "divide every part"', problem: { text: 'Which is the same as 14x − 21?',
        picture: box('?', ['?', '?'], [['14x', '−21']]), answer: { choices: ['7(2x − 3)', '7(2x − 21)', '7(7x − 3)', '2(7x − 3)'], correct: 0 },
        steps: ['The biggest number that divides 14 and 21 is 7.', '14x ÷ 7 = 2x, and 21 ÷ 7 = 3. Keep the minus sign.', 'So it is 7(2x − 3).'] } },
      { why: 'A little harder', problem: { text: '24x − 16 = 8(3x − ?). What number goes in the ?',
        picture: eq('24x − 16 = 8(3x − ?)'), answer: 2,
        steps: ['8 divides both 24 and 16.', '24x ÷ 8 = 3x, and 16 ÷ 8 is the number that is left.', 'So the number is 2.'] } },
      { why: 'Same math in a story', problem: { text: 'A school has 9 boxes with x crayons in each, and 12 rulers. It shares them equally into 3 bags, so 9x + 12 = 3(?x + 4). How many boxes of crayons go in each bag?',
        picture: box('3', ['?', '?'], [['9x', '12']]), answer: 3,
        steps: ['Divide each part by 3.', '9x ÷ 3 = 3x, and 12 ÷ 3 = 4, so each bag gets 3x + 4.', 'So each bag gets 3 boxes of crayons.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m3-t4', title: 'Two-step equations', skill: 'Solve px + q = r by undoing the adding first, then the multiplying',
    bigIdea: 'Undo the adding first, then undo the multiplying. Do the same thing to both sides each time.',
    screens: [
      { title: 'A level scale', text: '2 bags with x marbles in each, and 3 loose marbles, balance 11 marbles. How many marbles are in each bag?',
        pictures: [bal('2x + 3', '11')] },
      { title: 'Two things are stuck to x', text: "Look what's happened to x here. It got multiplied by 2, and then 3 got added on top. One step won't get x on its own. You need two.",
        beats: [
          { say: "Look what's happened to x here.", pic: 0, effect: 'draw' },
          { say: 'It got multiplied by 2, and then 3 got added on top.' },
          { say: "One step won't get x on its own. You need two.", write: 'two things on x → two steps' },
        ],
        pictures: [bal('2x + 3', '11')] },
      { title: 'The big idea', text: 'Undo the adding first, then undo the multiplying. Do the same thing to both sides each time.',
        beats: [
          { say: 'Undo the adding first, then undo the multiplying.', pic: 0, effect: 'draw' },
          { say: 'Do the same thing to both sides each time.' },
        ],
        pictures: [bal('2x + 3', '11')] },
      { title: 'Take 3 off both sides', text: 'The 3 was added last, so it comes off first. Take 3 off both sides, and keep the scale level. 11 − 3 = 8, so now 2x = 8.',
        beats: [
          { say: 'The 3 was added last, so it comes off first.', write: 'undo the last thing first' },
          { say: 'Take 3 off both sides, and keep the scale level.', pic: 0, effect: 'draw' },
          { say: '11 − 3 = 8, so now 2x = 8.', pic: 1 },
        ],
        pictures: [bal('2x', '8'), sides([['2x + 3', '=', '11'], ['2x', '=', '8']], true)] },
      { title: 'Divide both sides by 2', text: 'Now the 2. Two bags together make 8, so one bag is 8 ÷ 2 = 4. Divide both sides by 2, and x = 4.',
        beats: [
          { say: 'Now the 2.' },
          { say: 'Two bags together make 8, so one bag is 8 ÷ 2 = 4.', pic: 0, effect: 'draw' },
          { say: 'Divide both sides by 2, and x = 4.', pic: 1 },
        ],
        pictures: [bal('x', '4'), sides([['2x + 3', '=', '11'], ['2x', '=', '8'], ['x', '=', '4']], true)] },
      { title: 'Check it', text: 'Always check. Put 4 back in for x: 2 × 4 + 3 = 8 + 3 = 11. Both sides match, so each bag holds 4 marbles.',
        beats: [
          { say: 'Always check.' },
          { say: 'Put 4 back in for x: 2 × 4 + 3 = 8 + 3 = 11.', pic: 0, effect: 'draw' },
          { say: 'Both sides match, so each bag holds 4 marbles.', pic: 1 },
        ],
        pictures: [bal('2 × 4 + 3', '11'), eq('2x + 3 = 11', ['2 × 4 + 3 = 11', '11 = 11'])] },
      { title: 'One thing not to do', text: "Here's the tangle people get into. Don't divide just the 2x. If you divide first, the 3 has to be divided too. Take the 3 away first.",
        beats: [
          { say: "Here's the tangle people get into." },
          { say: "Don't divide just the 2x.", pic: 0 },
          { say: 'If you divide first, the 3 has to be divided too. Take the 3 away first.' },
        ],
        pictures: [cards('2x + 3 = 11 → x + 3 = 11 ÷ 2', '2x + 3 = 11 → 2x = 8 → x = 4')] },
    ],
    turn: {
      text: 'Solve 3x + 5 = 20. What is x?',
      picture: bal('3x + 5', '20'),
      answer: 5, steps: ['Take 5 off both sides: 3x = 15.', 'Divide both sides by 3: x = 15 ÷ 3.', 'So x = 5.'],
      prompt: 'Undo the adding first. Then undo the multiplying.',
      hint1: 'What is added to 3x? Take it off both sides first.',
      hint2: 'After that, 3x = 15. Divide both sides by 3.',
      twin: { text: 'Solve 2x + 9 = 3. What is x?',
        picture: bal('2x + 9', '3'),
        answer: -3, steps: ['Take 9 off both sides: 2x = 3 − 9 = −6.', 'Divide both sides by 2: x = −6 ÷ 2.', 'So x = −3.'],
        hint1: 'What is added to 2x? Take it off both sides first.',
        hint2: 'The right side becomes a negative number. Then divide both sides by 2.' },
    },
    won: { text: 'You undid the adding, then the multiplying, on both sides.', sticker: 'An equation that takes two steps to solve is called a two-step equation.' },
    twinWon: { text: 'You took 9 off both sides, then divided by 2, and found x = −3.', sticker: 'An equation that takes two steps to solve is called a two-step equation.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Solve 2x + 7 = 15. What is x?',
        picture: bal('2x + 7', '15'), answer: 4,
        steps: ['Take 7 off both sides: 2x = 8.', 'Divide both sides by 2: x = 8 ÷ 2.', 'So x = 4.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Solve 5x − 3 = 32. What is x?',
        picture: bal('5x − 3', '32'), answer: 7,
        steps: ['3 is taken away, so add 3 to both sides: 5x = 35.', 'Divide both sides by 5: x = 35 ÷ 5.', 'So x = 7.'] } },
      { why: 'Still "undo adding, then multiplying"', problem: { text: 'Solve 3x + 14 = 2. What is x?',
        picture: bal('3x + 14', '2'), answer: -4,
        steps: ['Take 14 off both sides: 3x = 2 − 14 = −12.', 'Divide both sides by 3: x = −12 ÷ 3.', 'So x = −4.'] } },
      { why: 'A little harder', problem: { text: 'Solve −4x + 6 = 34. What is x?',
        picture: bal('−4x + 6', '34'), answer: -7,
        steps: ['Take 6 off both sides: −4x = 28.', 'Divide both sides by −4: x = 28 ÷ (−4).', 'So x = −7.'] } },
      { why: 'Same math in a story', problem: { text: 'Maya had 6 dollars. She saved the same amount each week for 5 weeks, and now she has 41 dollars, so 5x + 6 = 41. How many dollars did she save each week?',
        picture: bal('5x + 6', '41'), answer: 7,
        steps: ['Take 6 off both sides: 5x = 35.', 'Divide both sides by 5: x = 35 ÷ 5.', 'So she saved 7 dollars each week.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m3-t5', title: 'Equations with brackets', skill: 'Solve p(x + q) = r by dividing by the number outside first, or by multiplying out first',
    bigIdea: 'The brackets are one group. Divide both sides by the number outside, then solve what is left.',
    screens: [
      { title: 'Three gift boxes', text: 'Each gift box holds x chocolates and 2 mints. 3 boxes hold 21 sweets in all, so 3(x + 2) = 21. How many chocolates are in each box?',
        pictures: [groups(3, '2', '21')] },
      { title: 'The 2 is in every box', text: "Careful here. You can't just take 2 away from 21. Every box has a 2 in it, so there are three 2s hiding inside that 21.",
        beats: [
          { say: 'Careful here.', pic: 0, effect: 'draw' },
          { say: "You can't just take 2 away from 21." },
          { say: 'Every box has a 2 in it, so there are three 2s hiding inside that 21.' },
        ],
        pictures: [groups(3, '2', '21')] },
      { title: 'The big idea', text: 'The brackets are one group. Divide both sides by the number outside, then solve what is left.',
        beats: [
          { say: 'The brackets are one group.', pic: 0, effect: 'draw' },
          { say: 'Divide both sides by the number outside, then solve what is left.' },
        ],
        pictures: [groups(3, '2', '21')] },
      { title: 'Divide by 3', text: 'So treat one whole box as one thing. 3 equal boxes make 21, so one box is 21 ÷ 3 = 7. That means x + 2 = 7.',
        beats: [
          { say: 'So treat one whole box as one thing.', write: 'one bracket = one box' },
          { say: '3 equal boxes make 21, so one box is 21 ÷ 3 = 7.', pic: 0, effect: 'draw' },
          { say: 'That means x + 2 = 7.', pic: 1 },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 3, text: 'x' }, { w: 1, text: '2', shade: true }, { w: 3, text: 'x' }, { w: 1, text: '2', shade: true }, { w: 3, text: 'x' }, { w: 1, text: '2', shade: true }], brace: '21' },
          { cells: [{ w: 4, text: '7' }, { w: 4, text: '7' }, { w: 4, text: '7' }] }], motion: true }, eq('3(x + 2) = 21', ['x + 2 = 7'])] },
      { title: 'Take the 2 away', text: 'One box is x and 2 mints, and it comes to 7. So take the 2 off both sides: x = 7 − 2 = 5. Each box holds 5 chocolates.',
        beats: [
          { say: 'One box is x and 2 mints, and it comes to 7.', pic: 0, effect: 'draw' },
          { say: 'So take the 2 off both sides: x = 7 − 2 = 5.', pic: 1 },
          { say: 'Each box holds 5 chocolates.' },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 3, text: 'x' }, { w: 1, text: '2', shade: true }], brace: '7' }, { cells: [{ w: 3, text: '5' }, { w: 1, text: '2', shade: true }] }], motion: true }, eq('x + 2 = 7', ['x = 5'])] },
      { title: 'Or multiply out first', text: "There's a second way, and it works just as well. Multiply out first: 3(x + 2) = 3x + 6. Then 3x + 6 = 21, so 3x = 15 and x = 5. Same answer, so take whichever way you like.",
        beats: [
          { say: "There's a second way, and it works just as well." },
          { say: 'Multiply out first: 3(x + 2) = 3x + 6.', pic: 0, effect: 'draw' },
          { say: 'Then 3x + 6 = 21, so 3x = 15 and x = 5.', pic: 1 },
          { say: 'Same answer, so take whichever way you like.' },
        ],
        pictures: [groups(3, '2', '3x + 6 = 21'), eq('3(x + 2) = 21', ['3x + 6 = 21', '3x = 15', 'x = 5'])] },
      { title: 'One thing not to do', text: "Here's the trap. Don't multiply only the x. The 3 multiplies the 2 as well, because there's a 2 in every box.",
        beats: [
          { say: "Here's the trap." },
          { say: "Don't multiply only the x.", pic: 0 },
          { say: "The 3 multiplies the 2 as well, because there's a 2 in every box." },
        ],
        pictures: [cards('3(x + 2) = 21 → 3x + 2 = 21', '3(x + 2) = 21 → 3x + 6 = 21')] },
    ],
    turn: {
      text: 'Solve 4(x + 3) = 32. What is x?',
      picture: groups(4, '3', '32'),
      answer: 5, steps: ['Divide both sides by 4: x + 3 = 8.', 'Take 3 off both sides: x = 8 − 3.', 'So x = 5.'],
      prompt: 'Divide both sides by the number outside. Then solve what is left.',
      hint1: 'Divide both sides by 4 first. What is one box, x + 3, equal to?',
      hint2: 'After dividing, take 3 off both sides.',
      twin: { text: 'Solve 2(x − 5) = 8. What is x?',
        picture: eq('2(x − 5) = 8'),
        answer: 9, steps: ['Divide both sides by 2: x − 5 = 4.', 'Add 5 to both sides: x = 4 + 5.', 'So x = 9.'],
        hint1: 'Divide both sides by the number outside the brackets.',
        hint2: 'After dividing, 5 is still taken away from x. Add 5 to both sides.' },
    },
    won: { text: 'You divided by the number outside, then solved what was left.', sticker: 'Both ways work: divide first, or use the distributive property to multiply out first.' },
    twinWon: { text: 'You divided 8 by 2, then added 5, and found x = 9.', sticker: 'Both ways work: divide first, or use the distributive property to multiply out first.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Solve 3(x + 5) = 24. What is x?',
        picture: groups(3, '5', '24'), answer: 3,
        steps: ['Divide both sides by 3: x + 5 = 8.', 'Take 5 off both sides: x = 8 − 5.', 'So x = 3.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Solve 7(x − 4) = 21. What is x?',
        picture: eq('7(x − 4) = 21'), answer: 7,
        steps: ['Divide both sides by 7: x − 4 = 3.', 'Add 4 to both sides: x = 3 + 4.', 'So x = 7.'] } },
      { why: 'Still "divide by the number outside"', problem: { text: 'Solve 2(x + 9) = 10. What is x?',
        picture: eq('2(x + 9) = 10'), answer: -4,
        steps: ['Divide both sides by 2: x + 9 = 5.', 'Take 9 off both sides: x = 5 − 9.', 'So x = −4.'] } },
      { why: 'A little harder', problem: { text: 'Solve −3(x − 6) = 12. What is x?',
        picture: eq('−3(x − 6) = 12'), answer: 2,
        steps: ['Divide both sides by −3: x − 6 = −4.', 'Add 6 to both sides: x = −4 + 6.', 'So x = 2.'] } },
      { why: 'Same math in a story', problem: { text: '4 friends each buy a ticket for x dollars and a 2-dollar snack. They pay 44 dollars in all, so 4(x + 2) = 44. How many dollars is one ticket?',
        picture: groups(4, '2', '44 dollars'), answer: 9,
        steps: ['Divide both sides by 4: x + 2 = 11.', 'Take 2 off both sides: x = 11 − 2.', 'So one ticket is 9 dollars.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m3-t6', title: 'Two-step inequalities', skill: 'Solve px + q > r the way you solve an equation, and show every number that works',
    bigIdea: 'Solve it just like an equation, and keep the sign. The answer is every number on one side of where you end up.',
    screens: [
      { title: 'Saving for a game', text: 'You have 3 dollars and save 2 dollars a week. You want MORE than 11 dollars. After x weeks you have 2x + 3, so you need 2x + 3 > 11. Which numbers of weeks work?',
        pictures: [line(0, 10)] },
      { title: 'Lots of answers', text: 'Try a few and see. 5 weeks works. 6 weeks works. So does 10. An equation has one answer, but this has more answers than you could ever list.',
        beats: [
          { say: 'Try a few and see.' },
          { say: '5 weeks works. 6 weeks works. So does 10.', pic: 0, effect: 'draw' },
          { say: 'An equation has one answer, but this has more answers than you could ever list.' },
        ],
        pictures: [line(0, 10, { points: [{ at: 5 }, { at: 6 }, { at: 10 }] })] },
      { title: 'The big idea', text: 'Solve it just like an equation, and keep the sign. The answer is every number on one side of where you end up.',
        beats: [
          { say: 'Solve it just like an equation, and keep the sign.', pic: 0, effect: 'draw' },
          { say: 'The answer is every number on one side of where you end up.' },
        ],
        pictures: [line(0, 10, { ray: { from: 4, dir: 'right', open: true } })] },
      { title: 'Take 3 off both sides', text: "Start exactly like an equation, and take 3 off both sides. 11 − 3 = 8, so 2x + 3 > 11 turns into 2x > 8. And notice the > hasn't moved.",
        beats: [
          { say: 'Start exactly like an equation, and take 3 off both sides.', pic: 0, effect: 'draw' },
          { say: '11 − 3 = 8, so 2x + 3 > 11 turns into 2x > 8.', pic: 1 },
          { say: "And notice the > hasn't moved.", write: 'take away → sign stays' },
        ],
        pictures: [line(0, 10), { kind: 'table', head: ['Left side', '', 'Right side'], rows: [['2x + 3', '>', '11'], ['2x', '>', '8']], motion: true }] },
      { title: 'Divide both sides by 2', text: 'Now divide both sides by 2. 8 ÷ 2 = 4, so x > 4. Mark 4 on the line, and leave the dot open.',
        beats: [
          { say: 'Now divide both sides by 2.', pic: 1 },
          { say: '8 ÷ 2 = 4, so x > 4.' },
          { say: 'Mark 4 on the line, and leave the dot open.', pic: 0, effect: 'draw' },
        ],
        pictures: [line(0, 10, { points: [{ at: 4, open: true }], motion: true }), { kind: 'table', head: ['Left side', '', 'Right side'], rows: [['2x + 3', '>', '11'], ['2x', '>', '8'], ['x', '>', '4']], motion: true }] },
      { title: 'Draw every answer', text: 'Why open, and not filled in? At exactly 4 weeks you have 2 × 4 + 3 = 11, and 11 is not MORE than 11. So 4 itself is out, and the arrow runs right from there. Every number past 4 works, and that is what x > 4 means.',
        beats: [
          { say: 'Why open, and not filled in?' },
          { say: 'At exactly 4 weeks you have 2 × 4 + 3 = 11, and 11 is not MORE than 11.' },
          { say: 'So 4 itself is out, and the arrow runs right from there.', pic: 0, write: 'open dot = not included', effect: 'draw' },
          { say: 'Every number past 4 works, and that is what x > 4 means.', pic: 1 },
        ],
        pictures: [line(0, 10, { ray: { from: 4, dir: 'right', open: true }, motion: true }), eq('x > 4')] },
      { title: 'One thing not to do', text: "Here's the one to avoid. Don't stop at one number. x > 4 is not just 5. It is every number more than 4.",
        beats: [
          { say: "Here's the one to avoid." },
          { say: "Don't stop at one number.", pic: 0 },
          { say: 'x > 4 is not just 5. It is every number more than 4.' },
        ],
        pictures: [cards('x > 4 means x = 5', 'x > 4 means every number more than 4')] },
    ],
    turn: {
      text: 'Solve 3x + 2 > 14. Which is the answer?',
      picture: eq('3x + 2 > 14'),
      answer: { choices: ['x > 4', 'x < 4', 'x > 12', 'x ≥ 4'], correct: 0 },
      steps: ['Take 2 off both sides: 3x > 12.', 'Divide both sides by 3: 12 ÷ 3 = 4, and the > stays.', 'So it is x > 4.'],
      prompt: 'Solve it like an equation. Keep the sign.',
      hint1: 'Take 2 off both sides, just like an equation.',
      hint2: 'Now divide both sides by 3. Keep the > sign as it is.',
      twin: { text: 'What is the greatest whole number that makes 2x + 5 < 17 true?',
        picture: eq('2x + 5 < 17'),
        answer: 5, steps: ['Take 5 off both sides: 2x < 12.', 'Divide both sides by 2: x < 6. The 6 itself does not work.', 'So the greatest whole number is 5.'],
        hint1: 'Take the plain number off both sides. Then divide by the number in front of x.',
        hint2: 'You get x < a number. Does that number itself make it true?' },
    },
    won: { text: 'You solved it like an equation and kept the sign.', sticker: 'An inequality has a whole set of answers. Together they are called the solution set.' },
    twinWon: { text: 'You solved 2x + 5 < 17 and found the greatest whole number, 5.', sticker: 'An inequality has a whole set of answers. Together they are called the solution set.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Solve 2x + 1 > 11. Which is the answer?',
        picture: eq('2x + 1 > 11'), answer: { choices: ['x > 5', 'x < 5', 'x > 6', 'x ≥ 5'], correct: 0 },
        steps: ['Take 1 off both sides: 2x > 10.', 'Divide both sides by 2, and the > stays.', 'So it is x > 5.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Solve 4x − 3 ≤ 25. Which is the answer?',
        picture: eq('4x − 3 ≤ 25'), answer: { choices: ['x ≤ 7', 'x ≥ 7', 'x < 7', 'x ≤ 28'], correct: 0 },
        steps: ['Add 3 to both sides: 4x ≤ 28.', 'Divide both sides by 4, and the ≤ stays.', 'So it is x ≤ 7.'] } },
      { why: 'Still "solve it like an equation"', problem: { text: 'Solve 6x + 5 < 53. You get x < ?. What number goes in the ?',
        picture: eq('6x + 5 < 53'), answer: 8,
        steps: ['Take 5 off both sides: 6x < 48.', 'Divide both sides by 6: 48 ÷ 6.', 'So x < 8, and the number is 8.'] } },
      { why: 'A little harder', problem: { text: 'What is the greatest whole number that makes 3x − 4 ≤ 29 true?',
        picture: eq('3x − 4 ≤ 29'), answer: 11,
        steps: ['Add 4 to both sides: 3x ≤ 33.', 'Divide both sides by 3: x ≤ 33 ÷ 3. The ≤ means that number itself works too.', 'So the greatest whole number is 11.'] } },
      { why: 'Same math in a story', problem: { text: 'A gym charges a 10-dollar fee plus 4 dollars for each class. Jo can spend at most 38 dollars, so 4x + 10 ≤ 38. What is the greatest number of classes she can take?',
        picture: eq('4x + 10 ≤ 38'), answer: 7,
        steps: ['Take 10 off both sides: 4x ≤ 28.', 'Divide both sides by 4: x ≤ 28 ÷ 4, and that number itself is allowed.', 'So she can take 7 classes.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m3-t7', title: 'Flip the sign', skill: 'Turn the inequality sign around when you multiply or divide both sides by a negative number',
    bigIdea: 'When you multiply or divide both sides by a negative number, flip the sign around.',
    screens: [
      { title: 'A true fact', text: '2 < 5 is true. Now multiply both sides by −1. You get −2 and −5. Is −2 < −5 still true?',
        pictures: [line(-6, 6, { points: [{ at: 2 }, { at: 5 }] })] },
      { title: 'The order turned around', text: 'Find them on the number line. −2 sits to the RIGHT of −5, so −2 is the bigger one. That means −2 < −5 is not true any more. The sign has to turn around: −2 > −5.',
        beats: [
          { say: 'Find them on the number line.', pic: 0, effect: 'draw' },
          { say: '−2 sits to the RIGHT of −5, so −2 is the bigger one.' },
          { say: 'That means −2 < −5 is not true any more.' },
          { say: 'The sign has to turn around: −2 > −5.', write: 'times a negative → turn the sign' },
        ],
        pictures: [line(-6, 6, { points: [{ at: 2 }, { at: 5 }, { at: -2 }, { at: -5 }] })] },
      { title: 'The big idea', text: 'When you multiply or divide both sides by a negative number, flip the sign around.',
        beats: [
          { say: 'When you multiply or divide both sides by a negative number, flip the sign around.', pic: 1 },
        ],
        pictures: [line(-6, 6, { points: [{ at: 2 }, { at: 5 }, { at: -2 }, { at: -5 }] }), eq('2 < 5', ['−2 > −5'])] },
      { title: 'Divide by −3', text: 'Now a real one: solve −3x < 12. To get x by itself, divide both sides by −3. And 12 ÷ (−3) = −4, so mark −4 on the line.',
        beats: [
          { say: 'Now a real one: solve −3x < 12.', pic: 1 },
          { say: 'To get x by itself, divide both sides by −3.' },
          { say: 'And 12 ÷ (−3) = −4, so mark −4 on the line.', pic: 0, effect: 'draw' },
        ],
        pictures: [line(-6, 6, { points: [{ at: -4, open: true }], motion: true }), eq('−3x < 12', ['x ? −4'])] },
      { title: 'Flip the sign', text: 'But you just divided by a negative, so the < flips to >. That gives x > −4, and the arrow runs right from −4.',
        beats: [
          { say: 'But you just divided by a negative, so the < flips to >.', pic: 1 },
          { say: 'That gives x > −4, and the arrow runs right from −4.', pic: 0, effect: 'draw' },
        ],
        pictures: [line(-6, 6, { ray: { from: -4, dir: 'right', open: true }, motion: true }), eq('−3x < 12', ['−3x ÷ (−3) > 12 ÷ (−3)', 'x > −4'])] },
      { title: 'Check two numbers', text: "Let's test it. Try 0, which is more than −4: −3 × 0 = 0, and 0 < 12. True. Now try −5, which is less: −3 × (−5) = 15, and 15 is not less than 12. So the numbers past −4 are the ones that work.",
        beats: [
          { say: "Let's test it.", pic: 0, effect: 'draw' },
          { say: 'Try 0, which is more than −4: −3 × 0 = 0, and 0 < 12. True.', pic: 1 },
          { say: 'Now try −5, which is less: −3 × (−5) = 15, and 15 is not less than 12.' },
          { say: 'So the numbers past −4 are the ones that work.' },
        ],
        pictures: [line(-6, 6, { ray: { from: -4, dir: 'right', open: true } }), { kind: 'table', head: ['x', '−3x', 'less than 12?'], rows: [['0', '0', 'yes'], ['−5', '15', 'no']], motion: true }] },
      { title: 'One thing not to do', text: "Here's the one to watch. Don't keep the same sign when you divide by a negative. −3x < 12 gives x > −4, not x < −4.",
        beats: [
          { say: "Here's the one to watch." },
          { say: "Don't keep the same sign when you divide by a negative.", pic: 0 },
          { say: '−3x < 12 gives x > −4, not x < −4.' },
        ],
        pictures: [cards('−3x < 12 → x < −4', '−3x < 12 → x > −4')] },
    ],
    turn: {
      text: 'Solve −2x < 10. Which is the answer?',
      picture: eq('−2x < 10'),
      answer: { choices: ['x > −5', 'x < −5', 'x > 5', 'x < 5'], correct: 0 },
      steps: ['Divide both sides by −2: 10 ÷ (−2) = −5.', 'You divided by a negative, so < flips to >.', 'So it is x > −5.'],
      prompt: 'Divide both sides. If you divide by a negative, flip the sign.',
      hint1: 'What do you divide both sides by to get x alone?',
      hint2: 'You divide by a negative number. What happens to the < sign?',
      twin: { text: 'Solve −4x ≥ 24. Which is the answer?',
        picture: eq('−4x ≥ 24'),
        answer: { choices: ['x ≤ −6', 'x ≥ −6', 'x ≤ 6', 'x ≥ 6'], correct: 0 },
        steps: ['Divide both sides by −4: 24 ÷ (−4) = −6.', 'You divided by a negative, so ≥ flips to ≤.', 'So it is x ≤ −6.'],
        hint1: 'Divide both sides by the number in front of x. Is that number negative?',
        hint2: 'When you divide by a negative, the ≥ sign turns around.' },
    },
    won: { text: 'You flipped the sign because you divided by a negative.', sticker: 'Flipping the sign keeps an inequality true. It is called reversing the inequality.' },
    twinWon: { text: 'You divided 24 by −4 and flipped the sign to get x ≤ −6.', sticker: 'Flipping the sign keeps an inequality true. It is called reversing the inequality.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Solve −5x < 15. Which is the answer?',
        picture: eq('−5x < 15'), answer: { choices: ['x > −3', 'x < −3', 'x > 3', 'x < 3'], correct: 0 },
        steps: ['Divide both sides by −5: 15 ÷ (−5) = −3.', 'You divided by a negative, so < flips to >.', 'So it is x > −3.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Solve −6x > 42. Which is the answer?',
        picture: eq('−6x > 42'), answer: { choices: ['x < −7', 'x > −7', 'x < 7', 'x > 7'], correct: 0 },
        steps: ['Divide both sides by −6: 42 ÷ (−6) = −7.', 'You divided by a negative, so > flips to <.', 'So it is x < −7.'] } },
      { why: 'Still "negative means flip"', problem: { text: 'Solve −3x ≤ −18. Which is the answer?',
        picture: eq('−3x ≤ −18'), answer: { choices: ['x ≥ 6', 'x ≤ 6', 'x ≥ −6', 'x ≤ −6'], correct: 0 },
        steps: ['Divide both sides by −3: −18 ÷ (−3) = 6.', 'You divided by a negative, so ≤ flips to ≥.', 'So it is x ≥ 6.'] } },
      { why: 'A little harder', problem: { text: 'Solve 5 − 2x > 11. Which is the answer?',
        picture: eq('5 − 2x > 11'), answer: { choices: ['x < −3', 'x > −3', 'x < 3', 'x > 8'], correct: 0 },
        steps: ['Take 5 off both sides: −2x > 6. The sign stays, because you only took away.', 'Divide both sides by −2: 6 ÷ (−2) = −3, and > flips to <.', 'So it is x < −3.'] } },
      { why: 'Same math in a story', problem: { text: 'The temperature starts at 0 degrees and drops 2 degrees each hour, so after h hours it is −2h degrees. It is colder than −10 degrees when −2h < −10. Which is the answer?',
        picture: eq('−2h < −10'), answer: { choices: ['h > 5', 'h < 5', 'h > −5', 'h < −5'], correct: 0 },
        steps: ['Divide both sides by −2: −10 ÷ (−2) = 5.', 'You divided by a negative, so < flips to >.', 'So it is h > 5.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g7m3-t8', title: 'Equation stories', skill: 'Write an equation from a story, solve it, and answer the question the story asks',
    bigIdea: 'Use a letter for the number you do not know. Write the story as an equation, then solve it.',
    screens: [
      { title: 'The phone bill', text: 'A phone plan costs 20 dollars a month, plus 5 dollars for each GB of data. This month the bill is 45 dollars. How many GB were used?',
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 4, text: '20 plan' }, { w: 5, text: '5 for each GB' }], brace: '45 dollars' }] }] },
      { title: 'Guessing takes a while', text: "You could guess your way there. Try 1 GB and add it up. Try 2 GB and add it up. Try 3. It works, but with a bigger bill you'd be guessing all day.",
        beats: [
          { say: 'You could guess your way there.', pic: 0, effect: 'draw' },
          { say: 'Try 1 GB and add it up. Try 2 GB and add it up. Try 3.' },
          { say: "It works, but with a bigger bill you'd be guessing all day." },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 4, text: '20 plan' }, { w: 5, text: '5 for each GB' }], brace: '45 dollars' }] }] },
      { title: 'The big idea', text: 'Use a letter for the number you do not know. Write the story as an equation, then solve it.',
        beats: [
          { say: 'Use a letter for the number you do not know.', pic: 0, effect: 'draw' },
          { say: 'Write the story as an equation, then solve it.' },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 4, text: '20' }, { w: 5, text: '5g', shade: true }], brace: '45' }] }] },
      { title: 'Write the equation', text: 'So give the unknown a letter. Let g be the number of GB. Each GB costs 5 dollars, so the data part is 5g. Add the 20 for the plan, and the whole bill is 20 + 5g = 45.',
        beats: [
          { say: 'So give the unknown a letter. Let g be the number of GB.', write: 'g = the GB we want' },
          { say: 'Each GB costs 5 dollars, so the data part is 5g.', pic: 0, effect: 'draw' },
          { say: 'Add the 20 for the plan, and the whole bill is 20 + 5g = 45.', pic: 1 },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 4, text: '20' }, { w: 5, text: '5g', shade: true }], brace: '45' }], motion: true }, eq('20 + 5g = 45')] },
      { title: 'Solve it', text: 'Now solve it the way you already know. Take 20 off both sides: 5g = 25. Then divide both sides by 5, and g = 5.',
        beats: [
          { say: 'Now solve it the way you already know.', pic: 0, effect: 'draw' },
          { say: 'Take 20 off both sides: 5g = 25.' },
          { say: 'Then divide both sides by 5, and g = 5.', pic: 1 },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 4, text: '20' }, { w: 5, text: '5g', shade: true }], brace: '45' }, { cells: [{ w: 4, text: '' }, { w: 5, text: '25', shade: true }] }], motion: true }, eq('20 + 5g = 45', ['5g = 25', 'g = 5'])] },
      { title: 'Check it in the story', text: 'One more step, and it is the one people skip: go back to the story. 5 GB cost 5 × 5 = 25 dollars. Add the 20 for the plan and you get 45 dollars, which is the bill. So 5 GB were used.',
        beats: [
          { say: 'One more step, and it is the one people skip: go back to the story.' },
          { say: '5 GB cost 5 × 5 = 25 dollars.', pic: 0, effect: 'draw' },
          { say: 'Add the 20 for the plan and you get 45 dollars, which is the bill.', pic: 1 },
          { say: 'So 5 GB were used.' },
        ],
        pictures: [{ kind: 'tape', rows: [{ cells: [{ w: 4, text: '20' }, { w: 5, text: '25', shade: true }], brace: '45' }] }, eq('20 + 5 × 5 = 45')] },
      { title: 'One thing not to do', text: "Here's the mix-up to watch for. Don't put the letter with the wrong number. The 5 is paid for EACH GB, so the letter goes with the 5, not the 20.",
        beats: [
          { say: "Here's the mix-up to watch for." },
          { say: "Don't put the letter with the wrong number.", pic: 0 },
          { say: 'The 5 is paid for EACH GB, so the letter goes with the 5, not the 20.' },
        ],
        pictures: [cards('5 + 20g = 45', '20 + 5g = 45')] },
    ],
    turn: {
      text: 'A gym costs 15 dollars to join, plus 8 dollars for each class. Leo paid 63 dollars. How many classes did he take?',
      picture: { kind: 'tape', rows: [{ cells: [{ w: 3, text: '15 to join' }, { w: 6, text: '8 for each class' }], brace: '63 dollars' }] },
      answer: 6, steps: ['Let c be the number of classes: 15 + 8c = 63.', 'Take 15 off both sides: 8c = 48. Then divide both sides by 8.', 'So Leo took 6 classes.'],
      prompt: 'Use a letter for what you do not know. Write the equation, then solve it.',
      hint1: 'Which number is paid once, and which is paid for each class?',
      hint2: 'Write 15 + 8c = 63. Take 15 off both sides first.',
      twin: { text: 'A taxi charges 4 dollars to start, plus 3 dollars for each mile. A ride costs 25 dollars. How many miles long was the ride?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 2, text: '4 to start' }, { w: 6, text: '3 for each mile' }], brace: '25 dollars' }] },
        answer: 7, steps: ['Let m be the number of miles: 4 + 3m = 25.', 'Take 4 off both sides: 3m = 21. Then divide both sides by 3.', 'So the ride was 7 miles long.'],
        hint1: 'Which number is paid once, and which is paid for each mile?',
        hint2: 'Write 4 + 3m = 25. Take 4 off both sides, then divide.' },
    },
    won: { text: 'You used a letter, wrote the equation, and solved it.', sticker: 'Turning a story into an equation is called modeling. The letter you choose is the variable.' },
    twinWon: { text: 'You wrote 4 + 3m = 25 and found the ride was 7 miles long.', sticker: 'Turning a story into an equation is called modeling. The letter you choose is the variable.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A phone plan costs 10 dollars a month, plus 4 dollars for each GB. The bill is 42 dollars. How many GB were used?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 3, text: '10 plan' }, { w: 6, text: '4 for each GB' }], brace: '42 dollars' }] }, answer: 8,
        steps: ['Let g be the GB: 10 + 4g = 42.', 'Take 10 off both sides: 4g = 32. Divide both sides by 4.', 'So 8 GB were used.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A water park costs 6 dollars to get in, plus 2 dollars for each slide ride. Ana paid 20 dollars. How many slide rides did she take?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 3, text: '6 to get in' }, { w: 6, text: '2 for each ride' }], brace: '20 dollars' }] }, answer: 7,
        steps: ['Let r be the rides: 6 + 2r = 20.', 'Take 6 off both sides: 2r = 14. Divide both sides by 2.', 'So Ana took 7 slide rides.'] } },
      { why: 'Still "letter, equation, solve"', problem: { text: 'Tom has 70 dollars and spends 6 dollars each week. Now he has 16 dollars left. How many weeks has it been?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 6, text: '6 each week' }, { w: 3, text: '16 left' }], brace: '70 dollars' }] }, answer: 9,
        steps: ['Let w be the weeks: 70 − 6w = 16.', 'Take 70 off both sides: −6w = −54. Divide both sides by −6.', 'So it has been 9 weeks.'] } },
      { why: 'A little harder', problem: { text: '3 friends each buy a ticket and a 2-dollar drink. Together they pay 39 dollars. How many dollars is one ticket?',
        picture: { kind: 'tape', rows: [{ cells: [{ w: 3, text: 'ticket' }, { w: 1, text: '2' }, { w: 3, text: 'ticket' }, { w: 1, text: '2' }, { w: 3, text: 'ticket' }, { w: 1, text: '2' }], brace: '39 dollars' }] }, answer: 11,
        steps: ['Let t be one ticket. Each friend pays t + 2, so 3(t + 2) = 39.', 'Divide both sides by 3: t + 2 = 13. Take 2 off both sides.', 'So one ticket is 11 dollars.'] } },
      { why: 'Same math in a story', problem: { text: 'At sunset the temperature was 5 degrees. It fell 3 degrees each hour, and now it is −10 degrees. How many hours have passed?',
        picture: eq('5 − 3h = −10'), answer: 5,
        steps: ['Let h be the hours: 5 − 3h = −10.', 'Take 5 off both sides: −3h = −15. Divide both sides by −3.', 'So 5 hours have passed.'] } },
    ],
  },
]
