/**
 * Grade 8 · Module 2 — Linear relationships, slope and systems.
 * Written to docs/new-flow/AUTHORING.md.
 * Teaching pictures: `coord` (t1, t3, t4, t7), `table` (t2, t9), `balance` + `table` (t5, t6), `eq` + `table` (t8).
 * Nothing asks the child to type an equation: answers are one number, or a pick.
 */
import type { Lesson, Picture } from '../script'

type Line = NonNullable<Extract<Picture, { kind: 'coord' }>['lines']>[number]
type Pt = { x: number; y: number; label?: string }

const eq = (text: string, lines?: string[]): Picture => ({ kind: 'eq', text, lines })
const cards = (wrong: string, right: string): Picture => ({ kind: 'cards', wrong, right })
const bal = (left: string, right: string): Picture => ({ kind: 'balance', left, right })
const sides = (rows: string[][], motion = false): Picture => ({ kind: 'table', head: ['Left side', '', 'Right side'], rows, motion })
const plane = (max: number, points: Pt[] = [], lines: Line[] = [], motion = false, min = 0): Picture =>
  ({ kind: 'coord', min, max, points, lines, motion })
const P = (x: number, y: number, label = true): Pt => ({ x, y, label: label ? `(${x}, ${y})`.replace(/-/g, '−') : undefined })
/** A line through two labelled lattice points: the question picture for t1 and t3. */
const twoPts = (x1: number, y1: number, x2: number, y2: number): Picture =>
  plane(10, [P(x1, y1), P(x2, y2)], [{ a: [x1, y1], b: [x2, y2], extend: true }])
/** Two points as a table: Point 1 and Point 2. */
const pts = (x1: string, y1: string, x2: string, y2: string, mark?: [number, number][], motion = false): Picture =>
  ({ kind: 'table', head: ['', 'Point 1', 'Point 2'], rows: [['x', x1, x2], ['y', y1, y2]], rowHead: true, mark, motion })
/** Two extended lines, crossing point never labelled. */
const cross = (max: number, a: Line['a'], b: Line['b'], c: Line['a'], d: Line['b'], min = 0): Picture =>
  plane(max, [], [{ a, b, extend: true }, { a: c, b: d, extend: true, tone: 2 }], false, min)

const run = (a: [number, number], b: [number, number], label?: string): Line => ({ a, b, dashed: true, label })
const rise = (a: [number, number], b: [number, number], label?: string): Line => ({ a, b, dashed: true, tone: 2, label })

const SOL = ['one solution', 'no solution', 'infinitely many solutions']

// t1 teaching line: through (1, 1) and (3, 4)
const T1: Line = { a: [1, 1], b: [3, 4], extend: true }
// t7 teaching lines: y = x + 2 and y = −x + 6, crossing at (2, 4)
const T7A: Line = { a: [0, 2], b: [6, 8], extend: true }
const T7B: Line = { a: [0, 6], b: [6, 0], extend: true, tone: 2 }

export const G8M2: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m2-t1', title: 'Slope: rise over run', skill: 'Measure how steep a line is: count the rise and the run between two points, then divide',
    bigIdea: 'Go across from one point, then up to the next. Divide how far up (the rise) by how far across (the run).',
    screens: [
      { title: 'A skate ramp', text: 'A skate ramp climbs in a straight line. You want ONE number that says how steep it is. How could you find it?',
        pictures: [plane(10, [], [T1])] },
      { title: '"Quite steep" is not a number', text: 'So how steep is it? You could say "quite steep" — but that does not help anyone actually build a ramp. And look, the line keeps going forever, so you cannot just measure how tall it is.',
        beats: [
          { say: 'So how steep is it?', pic: 0, effect: 'draw' },
          { say: 'You could say "quite steep" — but that does not help anyone actually build a ramp.', write: 'steep needs a number' },
          { say: 'And look, the line keeps going forever, so you cannot just measure how tall it is.' },
        ],
        pictures: [plane(10, [], [T1])] },
      { title: 'The big idea', text: 'Go across from one point, then up to the next. Divide how far up (the rise) by how far across (the run).',
        beats: [
          { say: 'Go across from one point, then up to the next.', pic: 0, effect: 'draw' },
          { say: 'Divide how far up (the rise) by how far across (the run).' },
        ],
        pictures: [plane(10, [P(1, 1), P(3, 4)], [T1])] },
      { title: 'Go across first', text: 'Start at the point (1, 1). Now walk right along the bottom until you are straight under (3, 4). You went 2 across. That is the run.',
        beats: [
          { say: 'Start at the point (1, 1).', pic: 0, effect: 'draw' },
          { say: 'Now walk right along the bottom until you are straight under (3, 4).' },
          { say: 'You went 2 across. That is the run.', write: 'across → run' },
        ],
        pictures: [plane(10, [P(1, 1), P(3, 4)], [T1, run([1, 1], [3, 1], 'run 2')], true)] },
      { title: 'Then go up', text: 'Now climb straight up to (3, 4). You went 3 up. That is the rise.',
        beats: [
          { say: 'Now climb straight up to (3, 4).', pic: 0, effect: 'draw' },
          { say: 'You went 3 up. That is the rise.', write: 'up → rise' },
        ],
        pictures: [plane(10, [P(1, 1), P(3, 4)], [T1, run([1, 1], [3, 1], 'run 2'), rise([3, 1], [3, 4], 'rise 3')], true)] },
      { title: 'Divide, and every stair agrees', text: 'Keep stepping along the line. Every stair is the same: 2 across and 3 up. Now divide, with the rise on top. That gives 3/2, so the line is 3/2 steep everywhere. Every single stair agrees.',
        beats: [
          { say: 'Keep stepping along the line. Every stair is the same: 2 across and 3 up.', pic: 0, effect: 'draw' },
          { say: 'Now divide, with the rise on top.', pic: 1 },
          { say: 'That gives 3/2, so the line is 3/2 steep everywhere. Every single stair agrees.' },
        ],
        pictures: [plane(10, [P(1, 1), P(3, 4), P(5, 7, false)], [T1, run([1, 1], [3, 1], 'run 2'), rise([3, 1], [3, 4], 'rise 3'), run([3, 4], [5, 4]), rise([5, 4], [5, 7])], true),
          eq('rise ÷ run', ['3 ÷ 2 = 3/2'])] },
      { title: 'One thing not to do', text: "Here is the one that catches people. Don't turn it upside down. The rise goes on top: up ÷ across, never across ÷ up.",
        beats: [
          { say: 'Here is the one that catches people.' },
          { say: "Don't turn it upside down.", pic: 0 },
          { say: 'The rise goes on top: up ÷ across, never across ÷ up.', write: 'up on top' },
        ],
        pictures: [cards('2 ÷ 3 = 2/3', '3 ÷ 2 = 3/2')] },
    ],
    turn: {
      text: 'The line goes through (2, 1) and (4, 7). How steep is it? Find rise ÷ run.',
      picture: twoPts(2, 1, 4, 7),
      answer: 3,
      steps: ['Go across from (2, 1) to under (4, 7): 4 − 2 = 2. That is the run.', 'Go up to (4, 7): 7 − 1 = 6. That is the rise.', 'Rise ÷ run = 6 ÷ 2 = 3.'],
      prompt: 'Count across, then up. Divide the up by the across.',
      hint1: 'From (2, 1), how far across do you go to be straight under (4, 7)?',
      hint2: 'Now how far up is it to (4, 7)? Put that number on top.',
      twin: { text: 'The line goes through (1, 3) and (5, 6). How steep is it? Find rise ÷ run.',
        picture: twoPts(1, 3, 5, 6),
        answer: { frac: [3, 4] },
        steps: ['The run is 5 − 1 = 4.', 'The rise is 6 − 3 = 3.', 'Rise ÷ run = 3 ÷ 4 = 3/4.'],
        hint1: 'How far across is it from (1, 3) to (5, 6)? How far up?',
        hint2: 'Put the up number on top and the across number on the bottom.' },
    },
    won: { text: 'You counted the run and the rise, then divided the rise by the run.', sticker: 'How steep a line is, rise ÷ run, is called its slope.' },
    twinWon: { text: 'You went 4 across and 3 up, so the line climbs 3/4 for each step across.', sticker: 'How steep a line is, rise ÷ run, is called its slope.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'The line goes through (1, 1) and (2, 5). What is rise ÷ run?',
        picture: twoPts(1, 1, 2, 5), answer: 4,
        steps: ['The run is 2 − 1 = 1.', 'The rise is 5 − 1 = 4.', 'Rise ÷ run = 4 ÷ 1 = 4.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'The line goes through (0, 2) and (6, 6). What is rise ÷ run?',
        picture: twoPts(0, 2, 6, 6), answer: { frac: [2, 3] },
        steps: ['The run is 6 − 0 = 6.', 'The rise is 6 − 2 = 4.', 'Rise ÷ run = 4 ÷ 6 = 2/3.'] } },
      { why: 'Still "rise over run"', problem: { text: 'The line goes through (3, 2) and (5, 9). What is rise ÷ run? A decimal is fine.',
        picture: twoPts(3, 2, 5, 9), answer: 3.5,
        steps: ['The run is 5 − 3 = 2.', 'The rise is 9 − 2 = 7.', 'Rise ÷ run = 7 ÷ 2 = 3.5.'] } },
      { why: 'A little harder', problem: { text: 'The line goes through (0, 3) and (5, 5). What is rise ÷ run?',
        picture: twoPts(0, 3, 5, 5), answer: { frac: [2, 5] },
        steps: ['The run is 5 − 0 = 5.', 'The rise is 5 − 3 = 2. The line climbs slowly.', 'Rise ÷ run = 2 ÷ 5 = 2/5.'] } },
      { why: 'Same math in a story', problem: { text: 'A ramp is drawn on a grid. It starts on the ground at (0, 1) and reaches the stage at (5, 9). How steep is the ramp, as rise ÷ run?',
        picture: twoPts(0, 1, 5, 9), answer: { frac: [8, 5] },
        steps: ['From (0, 1) to (5, 9), the run is 5 − 0 = 5.', 'The rise is 9 − 1 = 8.', 'Rise ÷ run = 8 ÷ 5 = 8/5.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m2-t2', title: 'Slope from two points', skill: 'Find the slope from two points with (y₂ − y₁) ÷ (x₂ − x₁), subtracting in the same order',
    bigIdea: 'Subtract the y-values, then the x-values in the same order, and divide: (y₂ − y₁) ÷ (x₂ − x₁).',
    screens: [
      { title: 'Two points, no grid', text: 'A map app gives you just two points on a straight path: (2, 3) and (6, 11). There is no graph. What is the slope of the path?',
        pictures: [pts('2', '3', '6', '11')] },
      { title: 'No squares to count', text: 'Last time you counted squares, across and then up. But here there is no grid at all. With no grid — or with really big numbers — there is nothing left to count.',
        beats: [
          { say: 'Last time you counted squares, across and then up.', pic: 0 },
          { say: 'But here there is no grid at all.' },
          { say: 'With no grid — or with really big numbers — there is nothing left to count.' },
        ],
        pictures: [pts('2', '3', '6', '11')] },
      { title: 'The big idea', text: 'Subtract the y-values, then the x-values in the same order, and divide: (y₂ − y₁) ÷ (x₂ − x₁).',
        beats: [
          { say: 'Subtract the y-values, then the x-values in the same order, and divide: (y₂ − y₁) ÷ (x₂ − x₁).', pic: 0 },
        ],
        pictures: [pts('2', '3', '6', '11')] },
      { title: 'The rise is a subtraction', text: 'The two y-values are 3 and 11. Going up from 3 to 11 is 8. Notice I started with Point 2. That is your rise.',
        beats: [
          { say: 'The two y-values are 3 and 11.', pic: 0 },
          { say: 'Going up from 3 to 11 is 8.', pic: 1 },
          { say: 'Notice I started with Point 2. That is your rise.', write: 'Point 2 first' },
        ],
        pictures: [pts('2', '3', '6', '11', [[1, 1], [1, 2]], true), eq('11 − 3 = 8')] },
      { title: 'The run is a subtraction too', text: 'Now the x-values: 2 and 6. Going across from 2 to 6 is 4. Point 2 comes first again — the same order, top and bottom. That is your run.',
        beats: [
          { say: 'Now the x-values: 2 and 6.', pic: 0 },
          { say: 'Going across from 2 to 6 is 4.', pic: 1 },
          { say: 'Point 2 comes first again — the same order, top and bottom. That is your run.', write: 'same order, top and bottom' },
        ],
        pictures: [pts('2', '3', '6', '11', [[0, 1], [0, 2]], true), eq('6 − 2 = 4')] },
      { title: 'Divide', text: 'Now put the rise over the run and divide. You get 2. That means up 2 for every 1 across. And if the y-values get smaller instead, the top comes out negative. The slope is negative, and the line goes down.',
        beats: [
          { say: 'Now put the rise over the run and divide.', pic: 0 },
          { say: 'You get 2. That means up 2 for every 1 across.', pic: 1 },
          { say: 'And if the y-values get smaller instead, the top comes out negative. The slope is negative, and the line goes down.', write: 'y going down → negative slope' },
        ],
        pictures: [pts('2', '3', '6', '11'), eq('(11 − 3) ÷ (6 − 2)', ['= 8 ÷ 4', '= 2'])] },
      { title: 'One thing not to do', text: "Here is the mix-up to watch for. Don't flip the order halfway through. If the top starts with Point 2, the bottom has to start with Point 2 too.",
        beats: [
          { say: 'Here is the mix-up to watch for.' },
          { say: "Don't flip the order halfway through.", pic: 0 },
          { say: 'If the top starts with Point 2, the bottom has to start with Point 2 too.', write: 'same point first, both times' },
        ],
        pictures: [cards('(11 − 3) ÷ (2 − 6) = −2', '(11 − 3) ÷ (6 − 2) = 2')] },
    ],
    turn: {
      text: 'A line goes through (1, 4) and (5, 16). What is its slope?',
      picture: pts('1', '4', '5', '16'),
      answer: 3,
      steps: ['Subtract the y-values: 16 − 4 = 12.', 'Subtract the x-values in the same order: 5 − 1 = 4.', 'Divide: 12 ÷ 4 = 3. The slope is 3.'],
      prompt: 'Subtract the y-values, then the x-values in the same order. Divide.',
      hint1: 'Start with Point 2 on top: what is 16 − 4?',
      hint2: 'Start with Point 2 on the bottom too: 5 − 1. Divide the top by the bottom.',
      twin: { text: 'A line goes through (1, 9) and (4, 3). What is its slope?',
        picture: pts('1', '9', '4', '3'),
        answer: -2,
        steps: ['Subtract the y-values: 3 − 9 = −6.', 'Subtract the x-values in the same order: 4 − 1 = 3.', 'Divide: −6 ÷ 3 = −2. The slope is −2.'],
        hint1: 'Subtract the y-values, Point 2 first. Is the answer positive or negative?',
        hint2: 'Subtract the x-values in the same order. Then divide.' },
    },
    won: { text: 'You subtracted the y-values and the x-values in the same order, then divided.', sticker: 'The rule (y₂ − y₁) ÷ (x₂ − x₁) is called the slope formula. It works for any two points on a line.' },
    twinWon: { text: 'You subtracted in the same order and found a slope of −2. The line goes down.', sticker: 'The rule (y₂ − y₁) ÷ (x₂ − x₁) is called the slope formula. It works for any two points on a line.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A line goes through (3, 5) and (7, 13). What is its slope?',
        picture: pts('3', '5', '7', '13'), answer: 2,
        steps: ['y-values: 13 − 5 = 8.', 'x-values in the same order: 7 − 3 = 4.', 'Divide: 8 ÷ 4 = 2.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A line goes through (0, 1) and (4, 7). What is its slope?',
        picture: pts('0', '1', '4', '7'), answer: { frac: [3, 2] },
        steps: ['y-values: 7 − 1 = 6.', 'x-values in the same order: 4 − 0 = 4.', 'Divide: 6 ÷ 4 = 3/2.'] } },
      { why: 'Still "same order, top and bottom"', problem: { text: 'A line goes through (1, 10) and (4, 1). What is its slope?',
        picture: pts('1', '10', '4', '1'), answer: -3,
        steps: ['y-values: 1 − 10 = −9.', 'x-values in the same order: 4 − 1 = 3.', 'Divide: −9 ÷ 3 = −3.'] } },
      { why: 'A little harder', problem: { text: 'A line goes through (−3, 4) and (5, −2). What is its slope?',
        picture: pts('−3', '4', '5', '−2'), answer: { frac: [-3, 4] },
        steps: ['y-values: −2 − 4 = −6.', 'x-values in the same order: 5 − (−3) = 8.', 'Divide: −6 ÷ 8 = −3/4.'] } },
      { why: 'Same math in a story', problem: { text: 'A hot-air balloon rises at a steady rate. After 2 minutes it is 350 feet up. After 6 minutes it is 950 feet up. How many feet does it rise each minute?',
        picture: { kind: 'table', head: ['', 'Point 1', 'Point 2'], rows: [['Minutes', '2', '6'], ['Feet up', '350', '950']], rowHead: true }, answer: 150,
        steps: ['Subtract the heights: 950 − 350 = 600.', 'Subtract the minutes in the same order: 6 − 2 = 4.', 'Divide: 600 ÷ 4 = 150 feet each minute.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m2-t3', title: 'y = mx + b', skill: 'Read the slope m and the crossing point b from y = mx + b',
    bigIdea: 'In y = mx + b, the number in front of x is the slope. The plain number b is where the line crosses the y-axis.',
    screens: [
      { title: 'A taxi ride', text: 'A taxi charges $1 to get in, plus $2 for each mile. The cost is y = 2x + 1. Where can you see the 2 and the 1 on its graph?',
        pictures: [plane(10, [], [{ a: [0, 1], b: [4, 9], extend: true }])] },
      { title: 'Two numbers, two jobs', text: 'In the equation, the 2 and the 1 sit right next to each other. But on this graph they do completely different jobs. So you need to know which one is which.',
        beats: [
          { say: 'In the equation, the 2 and the 1 sit right next to each other.', pic: 0, effect: 'draw' },
          { say: 'But on this graph they do completely different jobs.' },
          { say: 'So you need to know which one is which.', write: 'two numbers, two jobs' },
        ],
        pictures: [plane(10, [], [{ a: [0, 1], b: [4, 9], extend: true }])] },
      { title: 'The big idea', text: 'In y = mx + b, the number in front of x is the slope. The plain number b is where the line crosses the y-axis.',
        beats: [
          { say: 'In y = mx + b, the number in front of x is the slope.', pic: 1 },
          { say: 'The plain number b is where the line crosses the y-axis.', pic: 0, effect: 'draw' },
        ],
        pictures: [plane(10, [P(0, 1)], [{ a: [0, 1], b: [4, 9], extend: true }]), eq('y = mx + b')] },
      { title: 'Start at x = 0', text: 'Try x = 0 — that is the moment you get in, before any miles. The x part disappears, and you are left with 1. So the line crosses the y-axis at (0, 1). That is the $1 to get in.',
        beats: [
          { say: 'Try x = 0 — that is the moment you get in, before any miles.', pic: 1 },
          { say: 'The x part disappears, and you are left with 1.' },
          { say: 'So the line crosses the y-axis at (0, 1). That is the $1 to get in.', pic: 0, effect: 'draw' },
        ],
        pictures: [plane(10, [P(0, 1)], [{ a: [0, 1], b: [4, 9], extend: true }], true), eq('y = 2 × 0 + 1', ['y = 1'])] },
      { title: 'The number in front of x', text: 'Now step along the line. Each 1 across adds 2 more. So the slope is 2, and that is the $2 for each mile you ride.',
        beats: [
          { say: 'Now step along the line. Each 1 across adds 2 more.', pic: 0, effect: 'draw' },
          { say: 'So the slope is 2, and that is the $2 for each mile you ride.', write: 'in front of x → slope' },
        ],
        pictures: [plane(10, [P(0, 1), P(1, 3)], [{ a: [0, 1], b: [4, 9], extend: true }, run([0, 1], [1, 1], 'run 1'), rise([1, 1], [1, 3], 'rise 2')], true)] },
      { title: 'Read any equation', text: 'Now you can read any equation this way. y = 3x + 4 climbs 3 each step, and it crosses at (0, 4). And y = x + 5 has a slope of 1, because an x on its own means 1x.',
        beats: [
          { say: 'Now you can read any equation this way.', pic: 1 },
          { say: 'y = 3x + 4 climbs 3 each step, and it crosses at (0, 4).', pic: 0, effect: 'draw' },
          { say: 'And y = x + 5 has a slope of 1, because an x on its own means 1x.', write: 'x means 1x' },
        ],
        pictures: [plane(10, [P(0, 4), P(0, 5)], [{ a: [0, 4], b: [2, 10], extend: true }, { a: [0, 5], b: [5, 10], extend: true, tone: 2 }]),
          eq('y = 3x + 4: slope 3, crosses at 4', ['y = x + 5: slope 1, crosses at 5'])] },
      { title: 'One thing not to do', text: "Here is the mix-up. Don't swap the two jobs over. In y = 2x + 1 the slope is 2, and the line crosses at 1 — not at 2.",
        beats: [
          { say: 'Here is the mix-up.' },
          { say: "Don't swap the two jobs over.", pic: 0 },
          { say: 'In y = 2x + 1 the slope is 2, and the line crosses at 1 — not at 2.', write: 'the slope is stuck to the x' },
        ],
        pictures: [cards('y = 2x + 1: slope 1, crosses at 2', 'y = 2x + 1: slope 2, crosses at 1')] },
    ],
    turn: {
      text: 'A line has the equation y = 3x + 5. What is its slope?',
      picture: eq('y = 3x + 5'),
      answer: 3,
      steps: ['The slope is the number in front of x.', 'The plain number 5 is where the line crosses the y-axis, so it is not the slope.', 'So the slope is 3.'],
      prompt: 'Find the number in front of x.',
      hint1: 'Which number is stuck to the x?',
      hint2: 'The plain number tells where the line crosses. The slope is the other one.',
      twin: { text: 'A line has the equation y = −2x + 7. Where does it cross the y-axis? Give the y-value.',
        picture: eq('y = −2x + 7'),
        answer: 7,
        steps: ['The line crosses the y-axis where x is 0.', 'Put in x = 0: the x part becomes 0, so only the plain number is left.', 'So it crosses at y = 7.'],
        hint1: 'On the y-axis, what is x?',
        hint2: 'Put 0 in for x. What is left?' },
    },
    won: { text: 'You picked out the number in front of x: that is the slope.', sticker: 'b, where the line crosses the y-axis, is the y-intercept. y = mx + b is called slope-intercept form.' },
    twinWon: { text: 'You found the plain number in y = −2x + 7: the line crosses at 7.', sticker: 'b, where the line crosses the y-axis, is the y-intercept. y = mx + b is called slope-intercept form.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A line has the equation y = 5x + 2. What is its slope?',
        picture: eq('y = 5x + 2'), answer: 5,
        steps: ['The slope is the number in front of x.', 'The 2 is where the line crosses the y-axis.', 'So the slope is 5.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A line has the equation y = 3x − 4. Where does it cross the y-axis? Give the y-value.',
        picture: eq('y = 3x − 4'), answer: -4,
        steps: ['y = 3x − 4 is the same as y = 3x + (−4).', 'Put in x = 0: the x part is 0, and the plain number is left.', 'So it crosses at y = −4.'] } },
      { why: 'Still "m is the slope, b is the crossing"', problem: { text: 'This line crosses the y-axis at (0, 1) and goes through (3, 7). Its equation is y = mx + 1. What is m?',
        picture: twoPts(0, 1, 3, 7), answer: 2,
        steps: ['From (0, 1) to (3, 7): the rise is 7 − 1 = 6 and the run is 3 − 0 = 3.', 'The slope is 6 ÷ 3.', 'So m is 2.'] } },
      { why: 'A little harder', problem: { text: 'Which equation matches this line?',
        picture: twoPts(0, 8, 2, 4), answer: { choices: ['y = −2x + 8', 'y = 8x − 2', 'y = 2x + 8', 'y = −2x + 4'], correct: 0 },
        steps: ['It crosses the y-axis at (0, 8), so b is 8.', 'From (0, 8) to (2, 4): (4 − 8) ÷ (2 − 0) = −4 ÷ 2, so the slope is −2.', 'So it is y = −2x + 8.'] } },
      { why: 'Same math in a story', problem: { text: 'Mia’s phone plan costs y = 4x + 15 dollars, where x is the GB of data she uses. How many dollars does she pay if she uses no data at all?',
        picture: eq('y = 4x + 15'), answer: 15,
        steps: ['No data means x = 0.', 'y = 4 × 0 + 15, so only the plain number is left.', 'So she pays 15 dollars.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m2-t4', title: 'Graph a line from its equation', skill: 'Graph y = mx + b by starting at b and stepping by the slope, and check a point is on the line',
    bigIdea: 'Put the first dot at b on the y-axis. Then step by the slope: across the bottom number, up the top number, again and again.',
    screens: [
      { title: 'A growing plant', text: 'A plant is 3 cm tall and grows 2 cm each week: y = 2x + 3. You want to draw its line. Where do you start?',
        pictures: [plane(10)] },
      { title: 'A table is slow', text: 'You could work out y for x = 0, then 1, then 2, then 3, and keep going. That works, but it is slow. And the equation already tells you where to start and how to step.',
        beats: [
          { say: 'You could work out y for x = 0, then 1, then 2, then 3, and keep going.', pic: 0, effect: 'draw' },
          { say: 'That works, but it is slow.' },
          { say: 'And the equation already tells you where to start and how to step.' },
        ],
        pictures: [plane(10)] },
      { title: 'The big idea', text: 'Put the first dot at b on the y-axis. Then step by the slope: across the bottom number, up the top number, again and again.',
        beats: [
          { say: 'Put the first dot at b on the y-axis.', pic: 0, effect: 'draw' },
          { say: 'Then step by the slope: across the bottom number, up the top number, again and again.', pic: 1 },
        ],
        pictures: [plane(10, [P(0, 3)]), eq('y = 2x + 3')] },
      { title: 'Start at b', text: 'In y = 2x + 3, the plain number is 3. That is our b. So put a dot at (0, 3), right on the y-axis. That is the plant before any weeks have passed.',
        beats: [
          { say: 'In y = 2x + 3, the plain number is 3. That is our b.', write: 'b = the plain number' },
          { say: 'So put a dot at (0, 3), right on the y-axis.', pic: 0, effect: 'draw' },
          { say: 'That is the plant before any weeks have passed.' },
        ],
        pictures: [plane(10, [P(0, 3)], [], true)] },
      { title: 'Step by the slope', text: 'The slope is 2, and 2 is the same as 2/1. So go 1 across and 2 up. That lands you on (1, 5). Step again the same way, and you are at (2, 7).',
        beats: [
          { say: 'The slope is 2, and 2 is the same as 2/1.', write: 'a whole-number slope sits over 1' },
          { say: 'So go 1 across and 2 up. That lands you on (1, 5).', pic: 0, effect: 'draw' },
          { say: 'Step again the same way, and you are at (2, 7).' },
        ],
        pictures: [plane(10, [P(0, 3), P(1, 5), P(2, 7)], [run([0, 3], [1, 3]), rise([1, 3], [1, 5], 'rise 2'), run([1, 5], [2, 5]), rise([2, 5], [2, 7])], true)] },
      { title: 'Join the dots', text: 'Now draw a straight line right through the dots. Then check one of them. Put x = 2 into the equation. It gives 7, and sure enough the point (2, 7) sits on the line.',
        beats: [
          { say: 'Now draw a straight line right through the dots.', pic: 0, effect: 'draw' },
          { say: 'Then check one of them. Put x = 2 into the equation.', pic: 1 },
          { say: 'It gives 7, and sure enough the point (2, 7) sits on the line.' },
        ],
        pictures: [plane(10, [P(0, 3), P(1, 5), P(2, 7)], [{ a: [0, 3], b: [3, 9], extend: true }], true), eq('2 × 2 + 3 = 7')] },
      { title: 'One thing not to do', text: "One mix-up to avoid. Don't start your first dot at the slope. The first dot goes at b, the plain number — never the number in front of x.",
        beats: [
          { say: 'One mix-up to avoid.' },
          { say: "Don't start your first dot at the slope.", pic: 0 },
          { say: 'The first dot goes at b, the plain number — never the number in front of x.', write: 'first dot → the plain number' },
        ],
        pictures: [cards('y = 2x + 3: first dot at (0, 2)', 'y = 2x + 3: first dot at (0, 3)')] },
    ],
    turn: {
      text: 'Which point is on the line y = 2x − 1?',
      picture: eq('y = 2x − 1'),
      answer: { choices: ['(3, 5)', '(3, 7)', '(5, 3)', '(0, 1)'], correct: 0 },
      steps: ['Put in x = 3: y = 2 × 3 − 1 = 5.', 'That matches (3, 5), not (3, 7). (5, 3) and (0, 1) do not work either.', 'So (3, 5) is on the line.'],
      prompt: 'Put each point’s x into the equation. Does it give that point’s y?',
      hint1: 'Try the x of each point in y = 2x − 1.',
      hint2: 'For x = 3, work out 2 × 3 − 1. Which point has that y?',
      twin: { text: 'What is y on the line y = 3x + 2 when x = 4?',
        picture: eq('y = 3x + 2'),
        answer: 14,
        steps: ['Put 4 in for x: y = 3 × 4 + 2.', '3 × 4 = 12, then add 2.', 'So y = 14.'],
        hint1: 'Put 4 in place of x.',
        hint2: 'Multiply 3 by 4 first, then add 2.' },
    },
    won: { text: 'You put the x into the equation and checked that it gave the y.', sticker: 'The graph of an equation is every point whose x and y make the equation true.' },
    twinWon: { text: 'You put x = 4 into y = 3x + 2 and found y = 14.', sticker: 'The graph of an equation is every point whose x and y make the equation true.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Which point is on the line y = 2x + 1?',
        picture: eq('y = 2x + 1'), answer: { choices: ['(2, 5)', '(2, 4)', '(5, 2)', '(1, 2)'], correct: 0 },
        steps: ['Put in x = 2: y = 2 × 2 + 1 = 5.', 'That matches (2, 5).', 'So (2, 5) is on the line.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'What is y on the line y = 4x − 3 when x = 2?',
        picture: eq('y = 4x − 3'), answer: 5,
        steps: ['Put 2 in for x: y = 4 × 2 − 3.', '4 × 2 = 8, then take away 3.', 'So y = 5.'] } },
      { why: 'Still "start at b, step by the slope"', problem: { text: 'You graph y = 3x + 1. You start at (0, 1) and step 1 across and 3 up, two times. What is the y of the dot you land on?',
        picture: plane(10, [P(0, 1)]), answer: 7,
        steps: ['Start at (0, 1).', 'One step lands on (1, 4). A second step lands on (2, 7).', 'So the dot is at y = 7.'] } },
      { why: 'A little harder', problem: { text: 'Which point is on the line y = (1/2)x + 3?',
        picture: eq('y = (1/2)x + 3'), answer: { choices: ['(4, 5)', '(4, 7)', '(5, 4)', '(2, 3)'], correct: 0 },
        steps: ['Put in x = 4: half of 4 is 2, and 2 + 3 = 5.', 'That matches (4, 5).', 'So (4, 5) is on the line.'] } },
      { why: 'Same math in a story', problem: { text: 'A candle is 10 inches tall and burns down 2 inches each hour, so its height is y = −2x + 10. How many inches tall is it after 3 hours?',
        picture: eq('y = −2x + 10'), answer: 4,
        steps: ['Put 3 in for x: y = −2 × 3 + 10.', '−2 × 3 = −6, and −6 + 10 = 4.', 'So the candle is 4 inches tall.'] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m2-t5', title: 'Variables on both sides', skill: 'Solve an equation with x on both sides by taking the smaller x part off both sides first',
    bigIdea: 'Take the smaller x part off both sides, so x is on one side only. Then solve what is left.',
    screens: [
      { title: 'Bags on both sides', text: 'A scale is level. On the left: 5 bags with x marbles in each, and 2 loose marbles. On the right: 3 bags and 10 loose marbles. How many marbles are in one bag?',
        pictures: [bal('5x + 2', '3x + 10')] },
      { title: 'x on both sides', text: 'Before, x was only ever on one side. Now there are bags on both sides. So just undoing the adding and the dividing will not get x on its own yet.',
        beats: [
          { say: 'Before, x was only ever on one side.', pic: 0, effect: 'draw' },
          { say: 'Now there are bags on both sides.' },
          { say: 'So just undoing the adding and the dividing will not get x on its own yet.' },
        ],
        pictures: [bal('5x + 2', '3x + 10')] },
      { title: 'The big idea', text: 'Take the smaller x part off both sides, so x is on one side only. Then solve what is left.',
        beats: [
          { say: 'Take the smaller x part off both sides, so x is on one side only.', pic: 0, effect: 'draw' },
          { say: 'Then solve what is left.' },
        ],
        pictures: [bal('5x + 2', '3x + 10')] },
      { title: 'Take 3 bags off both sides', text: 'The right side has fewer bags, so take 3x off both sides. Take the same off each side and the scale stays level. On the left, 5 bags take away 3 bags leaves 2. So now there are no bags at all on the right.',
        beats: [
          { say: 'The right side has fewer bags, so take 3x off both sides.', pic: 1 },
          { say: 'Take the same off each side and the scale stays level.', pic: 0, effect: 'draw', write: 'same off both sides → still level' },
          { say: 'On the left, 5 bags take away 3 bags leaves 2. So now there are no bags at all on the right.' },
        ],
        pictures: [bal('2x + 2', '10'), sides([['5x + 2', '=', '3x + 10'], ['2x + 2', '=', '10']], true)] },
      { title: 'Solve what is left', text: 'Now it looks like the ones you already know. Take the 2 loose marbles off both sides, then split what is left between the 2 bags. And there it is: one bag holds 4 marbles.',
        beats: [
          { say: 'Now it looks like the ones you already know.', pic: 1 },
          { say: 'Take the 2 loose marbles off both sides, then split what is left between the 2 bags.' },
          { say: 'And there it is: one bag holds 4 marbles.', pic: 0, effect: 'draw' },
        ],
        pictures: [bal('x', '4'), sides([['5x + 2', '=', '3x + 10'], ['2x + 2', '=', '10'], ['2x', '=', '8'], ['x', '=', '4']], true)] },
      { title: 'Check both sides', text: 'Always check. Put 4 in for x on both sides. The left comes to 22, and the right comes to 22 as well. They match, so 4 marbles in each bag is right.',
        beats: [
          { say: 'Always check. Put 4 in for x on both sides.', pic: 0, effect: 'draw' },
          { say: 'The left comes to 22, and the right comes to 22 as well.', pic: 1 },
          { say: 'They match, so 4 marbles in each bag is right.' },
        ],
        pictures: [bal('5 × 4 + 2', '3 × 4 + 10'), eq('22 = 22')] },
      { title: 'One thing not to do', text: "Here is the one to watch. Don't add the x parts across the equals sign. You take 3x off both sides. You never push 5x and 3x together.",
        beats: [
          { say: 'Here is the one to watch.' },
          { say: "Don't add the x parts across the equals sign.", pic: 0 },
          { say: 'You take 3x off both sides. You never push 5x and 3x together.', write: 'off both sides, not added together' },
        ],
        pictures: [cards('5x + 2 = 3x + 10 → 8x + 2 = 10', '5x + 2 = 3x + 10 → 2x + 2 = 10')] },
    ],
    turn: {
      text: 'Solve 6x + 5 = 3x + 20. What is x?',
      picture: bal('6x + 5', '3x + 20'),
      answer: 5,
      steps: ['Take 3x off both sides: 3x + 5 = 20.', 'Take 5 off both sides: 3x = 15. Divide both sides by 3.', 'So x = 5.'],
      prompt: 'Take the smaller x part off both sides. Then solve what is left.',
      hint1: 'Which side has fewer x? Take that many x off both sides.',
      hint2: 'After taking 3x off, you have 3x + 5 = 20. Undo the adding, then the multiplying.',
      twin: { text: 'Solve 2x + 12 = 5x + 3. What is x?',
        picture: bal('2x + 12', '5x + 3'),
        answer: 3,
        steps: ['Take 2x off both sides: 12 = 3x + 3.', 'Take 3 off both sides: 9 = 3x. Divide both sides by 3.', 'So x = 3.'],
        hint1: 'This time the smaller x part is on the left. Take it off both sides.',
        hint2: 'You get 12 = 3x + 3. Take 3 off both sides, then divide.' },
    },
    won: { text: 'You took the smaller x part off both sides, then solved what was left.', sticker: 'Moving every x to one side is called collecting like terms. It works whenever the variable is on both sides.' },
    twinWon: { text: 'You took 2x off both sides of 2x + 12 = 5x + 3 and found x = 3.', sticker: 'Moving every x to one side is called collecting like terms. It works whenever the variable is on both sides.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Solve 4x + 3 = 2x + 11. What is x?',
        picture: bal('4x + 3', '2x + 11'), answer: 4,
        steps: ['Take 2x off both sides: 2x + 3 = 11.', 'Take 3 off both sides: 2x = 8. Divide both sides by 2.', 'So x = 4.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Solve 7x − 4 = 3x + 16. What is x?',
        picture: bal('7x − 4', '3x + 16'), answer: 5,
        steps: ['Take 3x off both sides: 4x − 4 = 16.', 'Add 4 to both sides: 4x = 20. Divide both sides by 4.', 'So x = 5.'] } },
      { why: 'Still "x on one side only"', problem: { text: 'Solve x + 21 = 4x + 3. What is x?',
        picture: bal('x + 21', '4x + 3'), answer: 6,
        steps: ['Take x off both sides: 21 = 3x + 3.', 'Take 3 off both sides: 18 = 3x. Divide both sides by 3.', 'So x = 6.'] } },
      { why: 'A little harder', problem: { text: 'Solve 3x + 8 = 5x + 14. What is x?',
        picture: bal('3x + 8', '5x + 14'), answer: -3,
        steps: ['Take 3x off both sides: 8 = 2x + 14.', 'Take 14 off both sides: −6 = 2x. Divide both sides by 2.', 'So x = −3.'] } },
      { why: 'Same math in a story', problem: { text: 'Gym A costs 20 dollars to join plus 5 dollars a class. Gym B costs 8 dollars to join plus 8 dollars a class. So 5x + 20 = 8x + 8. After how many classes do they cost the same?',
        picture: bal('5x + 20', '8x + 8'), answer: 4,
        steps: ['Take 5x off both sides: 20 = 3x + 8.', 'Take 8 off both sides: 12 = 3x. Divide both sides by 3.', 'So they cost the same after 4 classes.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m2-t6', title: 'One, none or many solutions', skill: 'Tell whether a linear equation has one solution, no solution or infinitely many',
    bigIdea: 'Take the x parts off both sides. If x is still there, there is one answer. If what is left is never true, there is none. If it is always true, every number works.',
    screens: [
      { title: 'Two bike rentals', text: 'Shop A charges $3 plus $2 an hour. Shop B charges $5 plus $2 an hour. When do they cost the same? 2x + 3 = 2x + 5.',
        pictures: [bal('2x + 3', '2x + 5')] },
      { title: 'Something strange', text: "Let's just try some numbers. At 1 hour it is $5 and $7. At 10 hours it is $23 and $25. Shop B is always $2 more, every single time. No number of hours seems to work at all.",
        beats: [
          { say: "Let's just try some numbers. At 1 hour it is $5 and $7.", pic: 0 },
          { say: 'At 10 hours it is $23 and $25.' },
          { say: 'Shop B is always $2 more, every single time. No number of hours seems to work at all.', write: 'always $2 apart' },
        ],
        pictures: [{ kind: 'table', head: ['Hours', 'Shop A', 'Shop B'], rows: [['1', '5', '7'], ['10', '23', '25']] }] },
      { title: 'The big idea', text: 'Take the x parts off both sides. If x is still there, there is one answer. If what is left is never true, there is none. If it is always true, every number works.',
        beats: [
          { say: 'Take the x parts off both sides.', pic: 0, effect: 'draw' },
          { say: 'If x is still there, there is one answer.' },
          { say: 'If what is left is never true, there is none.' },
          { say: 'If it is always true, every number works.' },
        ],
        pictures: [bal('2x + 3', '2x + 5')] },
      { title: 'Nothing works', text: 'Take 2x off both sides and watch what happens. Every x has gone, and what is left is not true. It never will be, whatever x you pick. On a graph these are two lines with the same slope, running side by side, never meeting.',
        beats: [
          { say: 'Take 2x off both sides and watch what happens.', pic: 1 },
          { say: 'Every x has gone, and what is left is not true.', pic: 0, effect: 'draw' },
          { say: 'It never will be, whatever x you pick.', write: 'never true → no solution' },
          { say: 'On a graph these are two lines with the same slope, running side by side, never meeting.' },
        ],
        pictures: [bal('3', '5'), sides([['2x + 3', '=', '2x + 5'], ['3', '=', '5']], true)] },
      { title: 'Everything works', text: 'Now try a different one. Multiply out the brackets, and both sides turn out to be exactly the same. Take the x parts off and what is left is always true. So every number you can think of works.',
        beats: [
          { say: 'Now try a different one.', pic: 0, effect: 'draw' },
          { say: 'Multiply out the brackets, and both sides turn out to be exactly the same.', pic: 1 },
          { say: 'Take the x parts off and what is left is always true.', write: 'always true → every number works' },
          { say: 'So every number you can think of works.' },
        ],
        pictures: [bal('2(x + 3)', '2x + 6'), sides([['2(x + 3)', '=', '2x + 6'], ['2x + 6', '=', '2x + 6'], ['6', '=', '6']], true)] },
      { title: 'Exactly one works', text: 'And here is the ordinary kind. Take 2x off both sides, and this time an x is still standing there. So you can solve it, and only one number fits. The x did not vanish, so there is exactly one answer.',
        beats: [
          { say: 'And here is the ordinary kind.', pic: 0, effect: 'draw' },
          { say: 'Take 2x off both sides, and this time an x is still standing there.', pic: 1 },
          { say: 'So you can solve it, and only one number fits.', write: 'x still there → one answer' },
          { say: 'The x did not vanish, so there is exactly one answer.' },
        ],
        pictures: [bal('3x + 1', '2x + 5'), sides([['3x + 1', '=', '2x + 5'], ['x + 1', '=', '5'], ['x', '=', '4']], true)] },
      { title: 'One thing not to do', text: "Here is the mix-up. Don't say x = 0 when the x parts vanish. Something like 6 = 6 means every number works — it does not mean x is 0.",
        beats: [
          { say: 'Here is the mix-up.' },
          { say: "Don't say x = 0 when the x parts vanish.", pic: 0 },
          { say: 'Something like 6 = 6 means every number works — it does not mean x is 0.', write: 'x vanished → not x = 0' },
        ],
        pictures: [cards('6 = 6, so x = 0', '6 = 6, so every number works')] },
    ],
    turn: {
      text: 'How many solutions does 4x + 1 = 4x + 7 have?',
      picture: bal('4x + 1', '4x + 7'),
      answer: { choices: SOL, correct: 1 },
      steps: ['Take 4x off both sides: 1 = 7.', '1 = 7 is never true, whatever x is.', 'So there is no solution.'],
      prompt: 'Take the x parts off both sides. Look at what is left.',
      hint1: 'Take 4x off both sides. What is left?',
      hint2: 'Is what is left ever true, always true, or does x remain?',
      twin: { text: 'How many solutions does 3(x + 2) = 3x + 6 have?',
        picture: bal('3(x + 2)', '3x + 6'),
        answer: { choices: SOL, correct: 2 },
        steps: ['Multiply out: 3x + 6 = 3x + 6.', 'Take 3x off both sides: 6 = 6, which is always true.', 'So there are infinitely many solutions.'],
        hint1: 'Multiply out the brackets first.',
        hint2: 'Take the x parts off both sides. Is what is left always true, or never?' },
    },
    won: { text: 'The x parts vanished and left 1 = 7, which is never true.', sticker: 'When the x parts vanish and leave something never true, there is no solution. When it is always true, there are infinitely many solutions.' },
    twinWon: { text: 'Both sides of 3(x + 2) = 3x + 6 are the same, so every number works.', sticker: 'When the x parts vanish and leave something never true, there is no solution. When it is always true, there are infinitely many solutions.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'How many solutions does 5x + 2 = 5x + 9 have?',
        picture: bal('5x + 2', '5x + 9'), answer: { choices: SOL, correct: 1 },
        steps: ['Take 5x off both sides: 2 = 9.', 'That is never true.', 'So there is no solution.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'How many solutions does 2(x + 4) = 2x + 8 have?',
        picture: bal('2(x + 4)', '2x + 8'), answer: { choices: SOL, correct: 2 },
        steps: ['Multiply out: 2x + 8 = 2x + 8.', 'Take 2x off both sides: 8 = 8, which is always true.', 'So there are infinitely many solutions.'] } },
      { why: 'Still "see what is left"', problem: { text: 'How many solutions does 6x + 1 = 4x + 9 have?',
        picture: bal('6x + 1', '4x + 9'), answer: { choices: SOL, correct: 0 },
        steps: ['Take 4x off both sides: 2x + 1 = 9.', 'The x is still there, so only x = 4 works.', 'So there is one solution.'] } },
      { why: 'A little harder', problem: { text: 'How many solutions does 3(2x − 1) = 6x + 3 have?',
        picture: bal('3(2x − 1)', '6x + 3'), answer: { choices: SOL, correct: 1 },
        steps: ['Multiply out: 6x − 3 = 6x + 3.', 'Take 6x off both sides: −3 = 3, which is never true.', 'So there is no solution.'] } },
      { why: 'Same math in a story', problem: { text: 'Tank A has 20 gallons and gains 5 gallons a minute: 5x + 20. Tank B gains 5 gallons a minute too, but started 4 minutes early: 5(x + 4). How many solutions does 5x + 20 = 5(x + 4) have?',
        picture: bal('5x + 20', '5(x + 4)'), answer: { choices: SOL, correct: 2 },
        steps: ['Multiply out: 5(x + 4) = 5x + 20.', 'Both sides are the same, so taking 5x off leaves 20 = 20.', 'So there are infinitely many solutions.'] } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m2-t7', title: 'Where two lines cross', skill: 'Read the crossing point of two lines and check it makes both equations true',
    bigIdea: 'The point where two lines cross is on both lines. Its x and y make both equations true at the same time.',
    screens: [
      { title: 'Two walkers', text: 'Ana starts 2 blocks from home and walks away 1 block each minute: y = x + 2. Ben starts 6 blocks away and walks toward home 1 block each minute: y = −x + 6. When are they at the same place?',
        pictures: [plane(8, [], [T7A, T7B])] },
      { title: 'Two rules at once', text: 'You could work out each walker on their own, minute by minute. But that is two separate lists, and you would have to keep comparing them. What you really need is one x and one y that fit both rules at the same time.',
        beats: [
          { say: 'You could work out each walker on their own, minute by minute.', pic: 0, effect: 'draw' },
          { say: 'But that is two separate lists, and you would have to keep comparing them.' },
          { say: 'What you really need is one x and one y that fit both rules at the same time.', write: 'one point, both rules' },
        ],
        pictures: [plane(8, [], [T7A, T7B])] },
      { title: 'The big idea', text: 'The point where two lines cross is on both lines. Its x and y make both equations true at the same time.',
        beats: [
          { say: 'The point where two lines cross is on both lines.', pic: 0, effect: 'draw' },
          { say: 'Its x and y make both equations true at the same time.' },
        ],
        pictures: [plane(8, [], [T7A, T7B])] },
      { title: 'Find the crossing', text: 'Follow the two lines with your finger until they meet. Then look straight down from that meeting point. They cross right above x = 2.',
        beats: [
          { say: 'Follow the two lines with your finger until they meet.', pic: 0, effect: 'draw' },
          { say: 'Then look straight down from that meeting point.', write: 'straight down for x' },
          { say: 'They cross right above x = 2.' },
        ],
        pictures: [plane(8, [], [T7A, T7B, { a: [2, 0], b: [2, 4], dashed: true }], true)] },
      { title: 'Read the point', text: 'Now look across from the crossing to the y-axis. That gives y = 4. So the crossing is the point (2, 4). After 2 minutes, both walkers are 4 blocks from home.',
        beats: [
          { say: 'Now look across from the crossing to the y-axis.', write: 'straight across for y' },
          { say: 'That gives y = 4. So the crossing is the point (2, 4).', pic: 0, effect: 'draw' },
          { say: 'After 2 minutes, both walkers are 4 blocks from home.' },
        ],
        pictures: [plane(8, [P(2, 4)], [T7A, T7B, { a: [0, 4], b: [2, 4], dashed: true }], true)] },
      { title: 'Check both rules', text: "Always check it in both rules. Ana's rule gives 4, and Ben's rule gives 4 too. So the point (2, 4) makes both equations true, and that is what we were after.",
        beats: [
          { say: 'Always check it in both rules.', pic: 0, effect: 'draw' },
          { say: "Ana's rule gives 4, and Ben's rule gives 4 too.", pic: 1 },
          { say: 'So the point (2, 4) makes both equations true, and that is what we were after.' },
        ],
        pictures: [plane(8, [P(2, 4)], [T7A, T7B]), eq('y = x + 2 → 2 + 2 = 4', ['y = −x + 6 → −2 + 6 = 4'])] },
      { title: 'One thing not to do', text: "Here is the one to watch for. Don't grab a point that sits on only one of the lines. The point (1, 3) is on Ana's line, but Ben's rule gives 5 there, not 3.",
        beats: [
          { say: 'Here is the one to watch for.' },
          { say: "Don't grab a point that sits on only one of the lines.", pic: 0 },
          { say: "The point (1, 3) is on Ana's line, but Ben's rule gives 5 there, not 3.", write: 'it has to fit both' },
        ],
        pictures: [cards('(1, 3): true for one rule', '(2, 4): true for both rules')] },
    ],
    turn: {
      text: 'The lines y = x + 1 and y = −x + 7 cross at one point. What is the x-value of that point?',
      picture: cross(8, [0, 1], [7, 8], [0, 7], [7, 0]),
      answer: 3,
      steps: ['Follow both lines to the place they meet.', 'Check x = 3: y = 3 + 1 = 4 and y = −3 + 7 = 4. Both rules give the same y.', 'So the lines cross at x = 3.'],
      prompt: 'Find where the lines meet. Check the point in both equations.',
      hint1: 'Follow both lines to the one place they meet. Look straight down.',
      hint2: 'At the crossing, both equations give the same y. Which x does that?',
      twin: { text: 'The lines y = 2x and y = x + 3 cross at one point. What is the y-value of that point?',
        picture: cross(10, [0, 0], [5, 10], [0, 3], [7, 10]),
        answer: 6,
        steps: ['At the crossing, both rules give the same y.', 'At x = 3: y = 2 × 3 = 6 and y = 3 + 3 = 6.', 'So the lines cross at y = 6.'],
        hint1: 'Find where the two lines meet, then look across to the y-axis.',
        hint2: 'Try some x-values in both equations until they give the same y.' },
    },
    won: { text: 'You found the one point that is on both lines.', sticker: 'Two equations about the same x and y are a system of equations. The crossing point is its solution.' },
    twinWon: { text: 'You found the point where y = 2x and y = x + 3 both give 6.', sticker: 'Two equations about the same x and y are a system of equations. The crossing point is its solution.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'The lines y = x + 3 and y = −x + 7 cross at one point. What is its x-value?',
        picture: cross(8, [0, 3], [5, 8], [0, 7], [7, 0]), answer: 2,
        steps: ['Try x = 2: y = 2 + 3 = 5 and y = −2 + 7 = 5.', 'Both rules give the same y.', 'So they cross at x = 2.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'The lines y = 3x and y = x + 4 cross at one point. What is its y-value?',
        picture: cross(10, [0, 0], [3, 9], [0, 4], [6, 10]), answer: 6,
        steps: ['Try x = 2: y = 3 × 2 = 6 and y = 2 + 4 = 6.', 'Both rules give the same y, so the crossing is at x = 2.', 'So they cross at y = 6.'] } },
      { why: 'Still "on both lines"', problem: { text: 'Which point is on both y = 2x + 1 and y = x + 4?',
        picture: cross(10, [0, 1], [4, 9], [0, 4], [6, 10]), answer: { choices: ['(3, 7)', '(1, 3)', '(0, 4)', '(2, 5)'], correct: 0 },
        steps: ['(3, 7): 2 × 3 + 1 = 7 and 3 + 4 = 7. Both are true.', '(1, 3) and (2, 5) fit only the first rule, and (0, 4) only the second.', 'So (3, 7) is on both lines.'] } },
      { why: 'A little harder', problem: { text: 'The lines y = x + 1 and y = −x − 3 cross at one point. What is its x-value?',
        picture: cross(6, [0, 1], [1, 2], [0, -3], [-3, 0], -6), answer: -2,
        steps: ['Try x = −2: y = −2 + 1 = −1 and y = 2 − 3 = −1.', 'Both rules give the same y.', 'So they cross at x = −2.'] } },
      { why: 'Same math in a story', problem: { text: 'Plan A costs 4 dollars plus 1 dollar for each GB: y = x + 4. Plan B costs 2 dollars for each GB: y = 2x. At how many GB do the plans cost the same?',
        picture: cross(10, [0, 4], [6, 10], [0, 0], [5, 10]), answer: 4,
        steps: ['The plans cost the same where the lines cross.', 'Try x = 4: 4 + 4 = 8 and 2 × 4 = 8.', 'So they cost the same at 4 GB.'] } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m2-t8', title: 'Solve a system by substitution', skill: 'Solve two equations together by putting one letter’s expression in place of it in the other',
    bigIdea: 'When one equation says what y equals, put that in place of y in the other equation. Then only x is left to solve.',
    screens: [
      { title: 'Two clues', text: 'A number puzzle has two clues. Clue 1: y is 2 times x. Clue 2: x and y add up to 12. What are x and y?',
        pictures: [eq('y = 2x', ['x + y = 12'])] },
      { title: 'One clue is not enough', text: 'Look at clue 2 on its own. It has two letters in it. And loads of pairs fit: 1 and 11, or 5 and 7, or 6 and 6. On its own, it can never tell you which pair is the right one.',
        beats: [
          { say: 'Look at clue 2 on its own. It has two letters in it.', pic: 0 },
          { say: 'And loads of pairs fit: 1 and 11, or 5 and 7, or 6 and 6.' },
          { say: 'On its own, it can never tell you which pair is the right one.', write: 'two letters → you need two clues' },
        ],
        pictures: [eq('x + y = 12')] },
      { title: 'The big idea', text: 'When one equation says what y equals, put that in place of y in the other equation. Then only x is left to solve.',
        beats: [
          { say: 'When one equation says what y equals, put that in place of y in the other equation.', pic: 0 },
          { say: 'Then only x is left to solve.' },
        ],
        pictures: [eq('y = 2x', ['x + y = 12'])] },
      { title: 'Swap y for 2x', text: 'Clue 1 tells you y is exactly the same thing as 2x. So anywhere you see a y, you are allowed to write 2x instead. Do that in clue 2 and the y disappears.',
        beats: [
          { say: 'Clue 1 tells you y is exactly the same thing as 2x.' },
          { say: 'So anywhere you see a y, you are allowed to write 2x instead.', write: 'same thing → swap it in' },
          { say: 'Do that in clue 2 and the y disappears.', pic: 0 },
        ],
        pictures: [sides([['x + y', '=', '12'], ['x + 2x', '=', '12']], true)] },
      { title: 'Solve for x', text: 'Now there is only one letter left, so this is one you can already do. An x plus 2 more x makes 3 of them. Split 12 between those 3, and x is 4.',
        beats: [
          { say: 'Now there is only one letter left, so this is one you can already do.', pic: 0 },
          { say: 'An x plus 2 more x makes 3 of them.' },
          { say: 'Split 12 between those 3, and x is 4.' },
        ],
        pictures: [sides([['x + y', '=', '12'], ['x + 2x', '=', '12'], ['3x', '=', '12'], ['x', '=', '4']], true)] },
      { title: 'Find y, then check', text: 'You are not finished — you still need y. Put x = 4 back into clue 1, and y comes out as 8. Then check clue 2: 4 and 8 do add up to 12. Both clues work, so you are done.',
        beats: [
          { say: 'You are not finished — you still need y.', write: 'find x, then go back for y' },
          { say: 'Put x = 4 back into clue 1, and y comes out as 8.', pic: 0 },
          { say: 'Then check clue 2: 4 and 8 do add up to 12. Both clues work, so you are done.' },
        ],
        pictures: [eq('y = 2 × 4 = 8', ['4 + 8 = 12'])] },
      { title: 'One thing not to do', text: "Here is the slip to watch for. Don't drop the 2x in the wrong spot. 2x is what y equals, so it goes where the y was — never where the x was.",
        beats: [
          { say: 'Here is the slip to watch for.' },
          { say: "Don't drop the 2x in the wrong spot.", pic: 0 },
          { say: '2x is what y equals, so it goes where the y was — never where the x was.', write: 'it replaces y' },
        ],
        pictures: [cards('x + y = 12 → 2x + y = 12', 'x + y = 12 → x + 2x = 12')] },
    ],
    turn: {
      text: 'y = 3x and x + y = 16. What is x?',
      picture: eq('y = 3x', ['x + y = 16']),
      answer: 4,
      steps: ['Put 3x in place of y: x + 3x = 16.', 'x + 3x = 4x, so 4x = 16. Divide both sides by 4.', 'So x = 4.'],
      prompt: 'Put what y equals in place of y. Then solve for x.',
      hint1: 'y is the same as 3x. Write 3x where y is in x + y = 16.',
      hint2: 'x + 3x is how many x? Then divide.',
      twin: { text: 'y = x + 2 and x + y = 10. What is y?',
        picture: eq('y = x + 2', ['x + y = 10']),
        answer: 6,
        steps: ['Put x + 2 in place of y: x + x + 2 = 10.', '2x + 2 = 10, so 2x = 8 and x = 4.', 'Then y = 4 + 2, so y = 6.'],
        hint1: 'Write x + 2 where y is in x + y = 10.',
        hint2: 'Solve for x first. Then put it back into y = x + 2.' },
    },
    won: { text: 'You swapped y for 3x, so only x was left to solve.', sticker: 'Putting what a letter equals in its place is called substitution.' },
    twinWon: { text: 'You put x + 2 in place of y, found x, then found y = 6.', sticker: 'Putting what a letter equals in its place is called substitution.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'y = 2x and x + y = 15. What is x?',
        picture: eq('y = 2x', ['x + y = 15']), answer: 5,
        steps: ['Put 2x in place of y: x + 2x = 15.', '3x = 15. Divide both sides by 3.', 'So x = 5.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'y = 4x and x + y = 20. What is y?',
        picture: eq('y = 4x', ['x + y = 20']), answer: 16,
        steps: ['Put 4x in place of y: x + 4x = 20, so 5x = 20.', 'Divide both sides by 5: x = 4.', 'Then y = 4 × 4, so y = 16.'] } },
      { why: 'Still "put it in place of y"', problem: { text: 'y = x + 3 and x + y = 13. What is x?',
        picture: eq('y = x + 3', ['x + y = 13']), answer: 5,
        steps: ['Put x + 3 in place of y: x + x + 3 = 13.', '2x + 3 = 13, so 2x = 10. Divide both sides by 2.', 'So x = 5.'] } },
      { why: 'A little harder', problem: { text: 'y = x − 6 and x + y = 2. What is y?',
        picture: eq('y = x − 6', ['x + y = 2']), answer: -2,
        steps: ['Put x − 6 in place of y: x + x − 6 = 2.', '2x − 6 = 2, so 2x = 8 and x = 4.', 'Then y = 4 − 6, so y = −2.'] } },
      { why: 'Same math in a story', problem: { text: 'Mia is 3 times as old as her brother, so y = 3x. Their ages add up to 24, so x + y = 24. How old is Mia?',
        picture: eq('y = 3x', ['x + y = 24']), answer: 18,
        steps: ['Put 3x in place of y: x + 3x = 24, so 4x = 24.', 'Divide both sides by 4: her brother is x = 6.', 'Mia is y = 3 × 6 = 18 years old.'] } },
    ],
  },

  // ── Topic 9 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m2-t9', title: 'System stories', skill: 'Write two equations from a story with two unknowns and solve them together',
    bigIdea: 'Give each unknown its own letter. Write one equation for each fact in the story, then solve them together.',
    screens: [
      { title: 'Tickets for the play', text: 'A family buys 10 tickets for a play. Adult tickets cost $5 and kid tickets cost $2. They pay $32. How many adult tickets did they buy?',
        pictures: [{ kind: 'table', head: ['', 'Adult', 'Kid', 'Total'], rows: [['Tickets', '?', '?', '10'], ['Cost ($)', '5 each', '2 each', '32']], rowHead: true }] },
      { title: 'Two things you do not know', text: 'The trouble is you do not know the adult tickets, and you do not know the kid tickets either. You could guess pairs that add up to 10 and check the cost of each one. That does work, but it takes a long, long time.',
        beats: [
          { say: 'The trouble is you do not know the adult tickets, and you do not know the kid tickets either.', pic: 0 },
          { say: 'You could guess pairs that add up to 10 and check the cost of each one.' },
          { say: 'That does work, but it takes a long, long time.' },
        ],
        pictures: [{ kind: 'table', head: ['', 'Adult', 'Kid', 'Total'], rows: [['Tickets', '?', '?', '10'], ['Cost ($)', '5 each', '2 each', '32']], rowHead: true }] },
      { title: 'The big idea', text: 'Give each unknown its own letter. Write one equation for each fact in the story, then solve them together.',
        beats: [
          { say: 'Give each unknown its own letter.', pic: 0 },
          { say: 'Write one equation for each fact in the story, then solve them together.' },
        ],
        pictures: [{ kind: 'table', head: ['', 'Adult', 'Kid', 'Total'], rows: [['Tickets', 'a', 'k', '10'], ['Cost ($)', '5a', '2k', '32']], rowHead: true }] },
      { title: 'One equation for each fact', text: 'Let a be the adult tickets and k be the kid tickets. Now, fact one: there are 10 tickets in all. And fact two: they paid $32 in all. That is one equation for each fact.',
        beats: [
          { say: 'Let a be the adult tickets and k be the kid tickets.', pic: 0 },
          { say: 'Now, fact one: there are 10 tickets in all.', pic: 1 },
          { say: 'And fact two: they paid $32 in all.' },
          { say: 'That is one equation for each fact.', write: 'one fact → one equation' },
        ],
        pictures: [{ kind: 'table', head: ['', 'Adult', 'Kid', 'Total'], rows: [['Tickets', 'a', 'k', '10'], ['Cost ($)', '5a', '2k', '32']], rowHead: true, mark: [[0, 3], [1, 3]], motion: true },
          eq('a + k = 10', ['5a + 2k = 32'])] },
      { title: 'Get one letter alone', text: 'Start with the easier equation. If the tickets add up to 10, then the kid tickets are just 10 take away the adult ones. Now that tells you what k equals, so you can put it in place of k in the cost equation.',
        beats: [
          { say: 'Start with the easier equation.' },
          { say: 'If the tickets add up to 10, then the kid tickets are just 10 take away the adult ones.', pic: 0 },
          { say: 'Now that tells you what k equals, so you can put it in place of k in the cost equation.', write: 'get one letter alone first' },
        ],
        pictures: [eq('k = 10 − a', ['5a + 2(10 − a) = 32', '5a + 20 − 2a = 32'])] },
      { title: 'Solve and check', text: 'Tidy it up and only the letter a is left. Take the 20 off both sides, divide by 3, and a is 4. So there were 4 adult tickets and 6 kid ones. Check the money: $20 of adult tickets and $12 of kid tickets makes $32. It fits.',
        beats: [
          { say: 'Tidy it up and only the letter a is left.', pic: 0 },
          { say: 'Take the 20 off both sides, divide by 3, and a is 4. So there were 4 adult tickets and 6 kid ones.' },
          { say: 'Check the money: $20 of adult tickets and $12 of kid tickets makes $32. It fits.', write: 'check it against the story' },
        ],
        pictures: [eq('3a + 20 = 32', ['3a = 12', 'a = 4, k = 6', '5 × 4 + 2 × 6 = 32'])] },
      { title: 'One thing not to do', text: "Here is the mix-up. Don't put tickets and dollars into the same equation. One equation counts tickets. The other counts dollars. Keep them apart.",
        beats: [
          { say: 'Here is the mix-up.' },
          { say: "Don't put tickets and dollars into the same equation.", pic: 0 },
          { say: 'One equation counts tickets. The other counts dollars. Keep them apart.', write: 'tickets and dollars, separate equations' },
        ],
        pictures: [cards('a + k = 32', 'a + k = 10 and 5a + 2k = 32')] },
    ],
    turn: {
      text: 'A family buys 9 tickets. Adult tickets cost $6 and kid tickets cost $3. They pay $39. How many adult tickets did they buy?',
      picture: { kind: 'table', head: ['', 'Adult', 'Kid', 'Total'], rows: [['Tickets', '?', '?', '9'], ['Cost ($)', '6 each', '3 each', '39']], rowHead: true },
      answer: 4,
      steps: ['a + k = 9 and 6a + 3k = 39.', 'Put k = 9 − a into the cost: 6a + 27 − 3a = 39, so 3a + 27 = 39 and 3a = 12.', 'Divide by 3: they bought 4 adult tickets.'],
      prompt: 'Write one equation for the tickets and one for the dollars. Then solve them together.',
      hint1: 'Write one equation for the number of tickets and one for the dollars.',
      hint2: 'From a + k = 9, k = 9 − a. Put that into 6a + 3k = 39.',
      twin: { text: 'Phone Plan A costs $20 to start plus $5 a month. Plan B costs $8 to start plus $7 a month. After how many months do they cost the same?',
        picture: { kind: 'table', head: ['', 'Start ($)', 'Each month ($)'], rows: [['Plan A', '20', '5'], ['Plan B', '8', '7']], rowHead: true },
        answer: 6,
        steps: ['Plan A: y = 5x + 20. Plan B: y = 7x + 8.', 'Both are y, so 5x + 20 = 7x + 8. Take 5x and 8 off both sides: 12 = 2x.', 'So they cost the same after 6 months.'],
        hint1: 'Write one equation for each plan: y = the monthly cost × x + the start cost.',
        hint2: 'Both equations give y, so set them equal. Then solve for x.' },
    },
    won: { text: 'You wrote one equation for each fact and solved them together.', sticker: 'A story with two unknowns and two facts becomes a system of equations. You can solve it by substitution.' },
    twinWon: { text: 'You set 5x + 20 equal to 7x + 8 and found 6 months.', sticker: 'A story with two unknowns and two facts becomes a system of equations. You can solve it by substitution.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A family buys 7 tickets. Adult tickets cost $4 and kid tickets cost $2. They pay $20. How many adult tickets did they buy?',
        picture: { kind: 'table', head: ['', 'Adult', 'Kid', 'Total'], rows: [['Tickets', '?', '?', '7'], ['Cost ($)', '4 each', '2 each', '20']], rowHead: true }, answer: 3,
        steps: ['a + k = 7 and 4a + 2k = 20.', 'Put k = 7 − a in: 4a + 14 − 2a = 20, so 2a = 6.', 'So they bought 3 adult tickets.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Gym A costs $30 to join plus $4 a visit. Gym B costs $10 to join plus $6 a visit. After how many visits do they cost the same?',
        picture: { kind: 'table', head: ['', 'Join ($)', 'Each visit ($)'], rows: [['Gym A', '30', '4'], ['Gym B', '10', '6']], rowHead: true }, answer: 10,
        steps: ['Gym A: y = 4x + 30. Gym B: y = 6x + 10.', 'Set them equal: 4x + 30 = 6x + 10, so 20 = 2x.', 'So they cost the same after 10 visits.'] } },
      { why: 'Still "one equation for each fact"', problem: { text: 'A farm has hens and cows: 10 animals and 28 legs. A hen has 2 legs and a cow has 4. How many cows are there?',
        picture: { kind: 'table', head: ['', 'Hens', 'Cows', 'Total'], rows: [['Animals', '?', '?', '10'], ['Legs', '2 each', '4 each', '28']], rowHead: true }, answer: 4,
        steps: ['h + c = 10 and 2h + 4c = 28.', 'Put h = 10 − c in: 20 − 2c + 4c = 28, so 2c = 8.', 'So there are 4 cows.'] } },
      { why: 'A little harder', problem: { text: 'Pens cost $3 and notebooks cost $5. Leo buys 12 items and pays $46. How many notebooks does he buy?',
        picture: { kind: 'table', head: ['', 'Pens', 'Notebooks', 'Total'], rows: [['Items', '?', '?', '12'], ['Cost ($)', '3 each', '5 each', '46']], rowHead: true }, answer: 5,
        steps: ['p + n = 12 and 3p + 5n = 46.', 'Put p = 12 − n in: 36 − 3n + 5n = 46, so 2n = 10.', 'So he buys 5 notebooks.'] } },
      { why: 'Same math in a story', problem: { text: 'A school sells 50 tickets for a concert. Adult tickets cost $8 and student tickets cost $4. It takes in $280. How many student tickets did it sell?',
        picture: { kind: 'table', head: ['', 'Adult', 'Student', 'Total'], rows: [['Tickets', '?', '?', '50'], ['Cost ($)', '8 each', '4 each', '280']], rowHead: true }, answer: 30,
        steps: ['a + s = 50 and 8a + 4s = 280.', 'Put a = 50 − s in: 400 − 8s + 4s = 280, so 4s = 120.', 'So the school sold 30 student tickets.'] } },
    ],
  },
]
