/**
 * Grade 8 · Module 3 — Functions.
 * Written to docs/new-flow/AUTHORING.md.
 * Teaching pictures: `table` (t1, t2, t4, t5), `coord` points + `table` (t3), `coord` path (t6).
 * Rules are always answered as choices; nothing asks the child to type an equation.
 */
import type { Lesson, Picture } from '../script'

const eq = (text: string, lines?: string[]): Picture => ({ kind: 'eq', text, lines })
/** An input row on top, one output row below. */
const io = (xs: string[], ys: string[], x = 'Input (x)', y = 'Output (y)', mark?: [number, number][], motion = false): Picture =>
  ({ kind: 'table', head: [x, ...xs], rows: [[y, ...ys]], rowHead: true, mark, motion })
const dots = (pts: [number, number][], lines: Extract<Picture, { kind: 'coord' }>['lines'] = [], motion = false, max = 10): Picture =>
  ({ kind: 'coord', min: 0, max, points: pts.map(([x, y]) => ({ x, y })), lines, motion })
/** A graph made of connected pieces; piece `hi` is drawn in the second colour. */
const path = (pts: [number, number][], hi = -1, motion = false): Picture =>
  ({ kind: 'coord', min: 0, max: 10, lines: pts.slice(1).map((b, i) => ({ a: pts[i], b, tone: i === hi ? 2 as const : undefined })), motion })

const FN = ['yes, a function', 'no, not a function']
const LIN = ['linear', 'not linear']
const AB = ['function A', 'function B']
const CH = ['increasing', 'decreasing', 'not changing']

const RIDE: [number, number][] = [[0, 0], [2, 6], [4, 6], [6, 8], [10, 0]]

export const G8M3: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m3-t1', title: 'One input, one output', skill: 'Decide if a table is a function by checking that no input has two different outputs',
    bigIdea: 'A function gives exactly one output for each input. If one input ever gets two different outputs, it is not a function.',
    screens: [
      { title: 'The snack machine', text: 'Press button A and you get chips. Would you trust a machine where button A gave chips today and a cookie tomorrow?',
        pictures: [io(['A', 'B', 'C'], ['chips', 'pretzels', 'crackers'], 'Button (input)', 'Snack (output)')] },
      { title: 'A pattern is not the test', text: 'You might start hunting for a pattern. Outputs that go up, maybe. But this table has no pattern at all. That is fine, because the real question is simpler than a pattern.',
        beats: [
          { say: 'You might start hunting for a pattern. Outputs that go up, maybe.', pic: 0 },
          { say: 'But this table has no pattern at all.' },
          { say: 'That is fine, because the real question is simpler than a pattern.', write: 'a pattern is not the test' },
        ],
        pictures: [io(['1', '2', '3', '4'], ['5', '2', '9', '2'])] },
      { title: 'The big idea', text: 'A function gives exactly one output for each input. If one input ever gets two different outputs, it is not a function.',
        beats: [
          { say: 'A function gives exactly one output for each input.', pic: 0 },
          { say: 'If one input ever gets two different outputs, it is not a function.' },
        ],
        pictures: [io(['A', 'B', 'C'], ['chips', 'pretzels', 'crackers'], 'Button (input)', 'Snack (output)')] },
      { title: 'Follow each input', text: "Let's walk the inputs one at a time. Input 1 gives 3. Input 2 gives 5. Keep going and every input shows up exactly once, with one output each. So this table is a function.",
        beats: [
          { say: "Let's walk the inputs one at a time.", pic: 0 },
          { say: 'Input 1 gives 3. Input 2 gives 5.' },
          { say: 'Keep going and every input shows up exactly once, with one output each.', write: 'each input once \u2192 one output' },
          { say: 'So this table is a function.' },
        ],
        pictures: [io(['1', '2', '3', '4'], ['3', '5', '7', '9'], undefined, undefined, [[0, 1], [0, 2], [0, 3], [0, 4]], true)] },
      { title: 'Look for a repeated input', text: 'Now watch this one. Input 2 shows up twice. Once it gives 6, and once it gives 8. That is button A handing you chips one day and a cookie the next. Not a function.',
        beats: [
          { say: 'Now watch this one.', pic: 0 },
          { say: 'Input 2 shows up twice. Once it gives 6, and once it gives 8.', write: 'same input, two outputs' },
          { say: 'That is button A handing you chips one day and a cookie the next. Not a function.' },
        ],
        pictures: [io(['1', '2', '2', '3'], ['4', '6', '8', '10'], undefined, undefined, [[0, 2], [0, 3]], true)] },
      { title: 'The same output is fine', text: 'Here is one that looks suspicious. Every single input gives 5. But two buttons are allowed to give you the same snack. Each input still has just one output, so this is a function.',
        beats: [
          { say: 'Here is one that looks suspicious. Every single input gives 5.', pic: 0 },
          { say: 'But two buttons are allowed to give you the same snack.', write: 'a repeated output is fine' },
          { say: 'Each input still has just one output, so this is a function.' },
        ],
        pictures: [io(['1', '2', '3', '4'], ['5', '5', '5', '5'], undefined, undefined, [[0, 1], [0, 2], [0, 3], [0, 4]], true)] },
      { title: 'One thing not to do', text: "Here is the one that catches people. Don't say \"not a function\" just because an output repeats. Only a repeated input with two different outputs breaks the rule.",
        beats: [
          { say: 'Here is the one that catches people.' },
          { say: "Don't say \"not a function\" just because an output repeats.", pic: 0 },
          { say: 'Only a repeated input with two different outputs breaks the rule.', write: 'a repeated INPUT is what breaks it' },
        ],
        pictures: [{ kind: 'cards', wrong: 'Outputs 5, 5, 5 repeat, so not a function', right: 'Each input has one output, so a function' }] },
    ],
    turn: {
      text: 'Is this table a function?',
      picture: io(['1', '2', '3', '1'], ['4', '5', '6', '8']),
      answer: { choices: FN, correct: 1 },
      steps: ['Look at the inputs: 1, 2, 3, 1.', 'Input 1 shows up twice, once with output 4 and once with output 8.', 'One input has two outputs, so no, not a function.'],
      prompt: 'Look along the input row. Does any input show up twice with a different output?',
      hint1: 'Is any input in the top row written twice?',
      hint2: 'Find both places input 1 shows up. Are its outputs the same?',
      twin: { text: 'Is this table a function?',
        picture: io(['2', '4', '6', '8'], ['3', '3', '5', '5']),
        answer: { choices: FN, correct: 0 },
        steps: ['The inputs are 2, 4, 6 and 8. None of them repeats.', 'The outputs 3 and 5 repeat, but that is fine: each input still has one output.', 'So yes, a function.'],
        hint1: 'Is any input in the top row written twice?',
        hint2: 'Some outputs repeat. Does that matter, or only repeated inputs?' },
    },
    won: { text: 'You spotted input 1 with two different outputs, so it cannot be a function.', sticker: 'All the inputs of a function are called its domain. All the outputs are called its range.' },
    twinWon: { text: 'No input repeated, so each input had one output. That is a function.', sticker: 'All the inputs of a function are called its domain. All the outputs are called its range.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Is this table a function?',
        picture: io(['1', '2', '3', '4'], ['6', '7', '8', '9']), answer: { choices: FN, correct: 0 },
        steps: ['The inputs are 1, 2, 3 and 4.', 'No input repeats, so each one has one output.', 'So yes, a function.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Is this table a function?',
        picture: io(['5', '6', '5', '7'], ['1', '2', '3', '4']), answer: { choices: FN, correct: 1 },
        steps: ['Input 5 shows up twice.', 'Once it gives 1 and once it gives 3.', 'One input has two outputs, so no, not a function.'] } },
      { why: 'Still "one input, one output"', problem: { text: 'Is this table a function?',
        picture: io(['0', '1', '2', '3'], ['4', '4', '4', '4']), answer: { choices: FN, correct: 0 },
        steps: ['The inputs 0, 1, 2 and 3 are all different.', 'Every output is 4, but each input still has just one output.', 'So yes, a function.'] } },
      { why: 'A little harder', problem: { text: 'Is this table a function? Check every input.',
        picture: io(['−3', '−1', '0', '2', '−1'], ['5', '2', '7', '2', '0']), answer: { choices: FN, correct: 1 },
        steps: ['Look for an input written twice: −1 shows up in two places.', 'Once −1 gives 2 and once it gives 0.', 'One input has two outputs, so no, not a function.'] } },
      { why: 'Same math in a story', problem: { text: 'A school lists each student ID with that student\'s homeroom. Is the homeroom a function of the student ID?',
        picture: io(['104', '105', '106', '107'], ['12', '12', '14', '15'], 'Student ID', 'Room'), answer: { choices: FN, correct: 0 },
        steps: ['Each student ID shows up once.', 'Two students share room 12, but no ID has two rooms.', 'So yes, a function.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m3-t2', title: 'Evaluate a function', skill: 'Find the output of a rule like f(x) = 3x − 2 for a given input',
    bigIdea: 'Put the input into the rule in place of x. Then work it out, multiplying first, to get the output.',
    screens: [
      { title: 'A number machine', text: 'This machine follows one rule: output = 3 × input − 2. You drop in 4. What comes out?',
        pictures: [eq('output = 3 × input − 2'), io(['4'], ['?'])] },
      { title: 'You cannot just look', text: 'Seeing 4 go in does not tell you what comes out. There is no guessing here. You have to follow the rule, and follow it in the right order.',
        beats: [
          { say: 'Seeing 4 go in does not tell you what comes out. There is no guessing here.', pic: 1 },
          { say: 'You have to follow the rule, and follow it in the right order.', pic: 0 },
        ],
        pictures: [eq('output = 3 × input − 2'), io(['4'], ['?'])] },
      { title: 'The big idea', text: 'Put the input into the rule in place of x. Then work it out, multiplying first, to get the output.',
        beats: [
          { say: 'Put the input into the rule in place of x.', pic: 0 },
          { say: 'Then work it out, multiplying first, to get the output.', pic: 1 },
        ],
        pictures: [eq('output = 3 × input − 2'), io(['4'], ['?'])] },
      { title: 'Put the input in', text: 'Our input is 4. So everywhere the rule says input, we write a 4 instead. That gives us 3 \u00d7 4 \u2212 2.',
        beats: [
          { say: 'Our input is 4.' },
          { say: 'So everywhere the rule says input, we write a 4 instead.', pic: 0 },
          { say: 'That gives us 3 \u00d7 4 \u2212 2.', pic: 1 },
        ],
        pictures: [eq('output = 3 × input − 2', ['output = 3 × 4 − 2']), io(['4'], ['3 × 4 − 2'], undefined, undefined, [[0, 1]], true)] },
      { title: 'Multiply first, then subtract', text: 'Multiply before you subtract. 3 \u00d7 4 = 12, and then 12 \u2212 2 = 10. So an input of 4 gives an output of 10. Do that same work for other inputs and you can fill a whole table.',
        beats: [
          { say: 'Multiply before you subtract.', write: 'multiply first, then subtract' },
          { say: '3 \u00d7 4 = 12, and then 12 \u2212 2 = 10.', pic: 0 },
          { say: 'So an input of 4 gives an output of 10.' },
          { say: 'Do that same work for other inputs and you can fill a whole table.', pic: 1 },
        ],
        pictures: [eq('3 × 4 − 2', ['12 − 2', '10']), io(['1', '2', '3', '4'], ['1', '4', '7', '10'], undefined, undefined, [[0, 4]], true)] },
      { title: 'A shorter way to write it', text: 'Mathematicians write this same rule a shorter way. It looks like f(x) = 3x \u2212 2, and the x is just the input. So f(4) means the output when the input is 4, which we already found: 10.',
        beats: [
          { say: 'Mathematicians write this same rule a shorter way.' },
          { say: 'It looks like f(x) = 3x \u2212 2, and the x is just the input.', pic: 0 },
          { say: 'So f(4) means the output when the input is 4, which we already found: 10.', write: 'x is the input' },
        ],
        pictures: [eq('f(x) = 3x − 2', ['f(4) = 3 × 4 − 2', 'f(4) = 10'])] },
      { title: 'One thing not to do', text: "Here is the mistake to watch for. Don't subtract before you multiply. In 3 \u00d7 4 \u2212 2 you multiply 3 \u00d7 4 first, and then take the 2 away.",
        beats: [
          { say: 'Here is the mistake to watch for.' },
          { say: "Don't subtract before you multiply.", pic: 0 },
          { say: 'In 3 \u00d7 4 \u2212 2 you multiply 3 \u00d7 4 first, and then take the 2 away.' },
        ],
        pictures: [{ kind: 'cards', wrong: '3 × 4 − 2 = 3 × 2 = 6', right: '3 × 4 − 2 = 12 − 2 = 10' }] },
    ],
    turn: {
      text: 'The rule is output = 3 × input − 2. What is the output when the input is 6?',
      picture: io(['6'], ['?']),
      answer: 16,
      steps: ['Put 6 in place of the input: 3 × 6 − 2.', 'Multiply first: 3 × 6 = 18.', 'Then subtract 2, so the output is 16.'],
      prompt: 'Put the input into the rule. Multiply first, then subtract.',
      hint1: 'Put 6 where the rule says input.',
      hint2: 'Work out 3 × 6 first. Then take away 2.',
      twin: { text: 'f(x) = 2x + 5. What is f(7)?',
        picture: io(['7'], ['?'], 'x', 'f(x)'),
        answer: 19,
        steps: ['f(7) means put 7 in place of x: 2 × 7 + 5.', 'Multiply first: 2 × 7 = 14.', 'Then add 5, so f(7) = 19.'],
        hint1: 'f(7) means the input is 7. Where does the 7 go?',
        hint2: 'Work out 2 × 7 first. Then add 5.' },
    },
    won: { text: 'You put 6 into the rule, multiplied, then subtracted.', sticker: 'Writing a rule as f(x) is called function notation. Say it "f of x".' },
    twinWon: { text: 'You put 7 in place of x in 2x + 5 and found f(7) = 19.', sticker: 'Writing a rule as f(x) is called function notation. Say it "f of x".' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'The rule is output = 3 × input − 2. What is the output when the input is 9?',
        picture: io(['9'], ['?']), answer: 25,
        steps: ['Put 9 in place of the input: 3 × 9 − 2.', 'Multiply first: 3 × 9 = 27.', 'Then 27 − 2, so the output is 25.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'f(x) = 4x + 1. What is f(5)?',
        picture: io(['5'], ['?'], 'x', 'f(x)'), answer: 21,
        steps: ['Put 5 in place of x: 4 × 5 + 1.', 'Multiply first: 4 × 5 = 20.', 'Then 20 + 1, so f(5) = 21.'] } },
      { why: 'Still "put the input in"', problem: { text: 'f(x) = 5x − 3. What is the missing output in the table?',
        picture: io(['0', '1', '2'], ['−3', '2', '?'], 'x', 'f(x)'), answer: 7,
        steps: ['The missing output is f(2): 5 × 2 − 3.', 'Multiply first: 5 × 2 = 10.', 'Then 10 − 3, so f(2) = 7.'] } },
      { why: 'A little harder', problem: { text: 'f(x) = 2x − 7. What is f(−3)?',
        picture: io(['−3'], ['?'], 'x', 'f(x)'), answer: -13,
        steps: ['Put −3 in place of x: 2 × (−3) − 7.', 'Multiply first: 2 × (−3) = −6.', 'Then −6 − 7, so f(−3) = −13.'] } },
      { why: 'Same math in a story', problem: { text: 'A taxi charges $3 plus $2 for each mile, so a ride of x miles costs C(x) = 2x + 3 dollars. How many dollars does a 12-mile ride cost?',
        picture: io(['12'], ['?'], 'Miles (x)', 'Cost ($)'), answer: 27,
        steps: ['Put 12 in place of x: 2 × 12 + 3.', 'Multiply first: 2 × 12 = 24.', 'Then 24 + 3, so the ride costs $27.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m3-t3', title: 'Linear or not?', skill: 'Decide if a table or a set of points is linear by checking that equal steps in x give equal changes in y',
    bigIdea: 'When x goes up in equal steps, check how much y changes each step. The same change every time makes a straight line.',
    screens: [
      { title: 'Two plants', text: 'Two plants grow for 3 weeks. The tables show their heights in inches. Which one grows the same amount every week?',
        pictures: [io(['0', '1', '2', '3'], ['1', '3', '5', '7'], 'Week', 'Plant A'), io(['0', '1', '2', '3'], ['0', '1', '4', '9'], 'Week', 'Plant B')] },
      { title: 'Both keep growing', text: 'Look at both tables. Plant A gets taller every week, and so does Plant B. So \"it goes up\" does not tell them apart at all. What you have to look at is how much it goes up each week.',
        beats: [
          { say: 'Look at both tables.', pic: 0 },
          { say: 'Plant A gets taller every week, and so does Plant B.', pic: 1 },
          { say: 'So \"it goes up\" does not tell them apart at all.' },
          { say: 'What you have to look at is how much it goes up each week.', write: 'how much, not just up' },
        ],
        pictures: [io(['0', '1', '2', '3'], ['1', '3', '5', '7'], 'Week', 'Plant A'), io(['0', '1', '2', '3'], ['0', '1', '4', '9'], 'Week', 'Plant B')] },
      { title: 'The big idea', text: 'When x goes up in equal steps, check how much y changes each step. The same change every time makes a straight line.',
        beats: [
          { say: 'When x goes up in equal steps, check how much y changes each step.', pic: 0 },
          { say: 'The same change every time makes a straight line.' },
        ],
        pictures: [dots([[0, 1], [1, 3], [2, 5], [3, 7]])] },
      { title: 'Plant A: the same step', text: 'Start with Plant A. Each week x goes up 1. The height goes 1, 3, 5, 7, so that is up 2, up 2, up 2, the same step every single time. Plot those points and they sit on one straight line.',
        beats: [
          { say: 'Start with Plant A. Each week x goes up 1.' },
          { say: 'The height goes 1, 3, 5, 7, so that is up 2, up 2, up 2, the same step every single time.', pic: 1 },
          { say: 'Plot those points and they sit on one straight line.', pic: 0 },
        ],
        pictures: [dots([[0, 1], [1, 3], [2, 5], [3, 7]], [{ a: [0, 1], b: [3, 7] }], true), eq('3 − 1 = 2', ['5 − 3 = 2', '7 − 5 = 2'])] },
      { title: 'Plant B: the steps change', text: 'Now Plant B. It goes 0, 1, 4, 9. That is up 1, then up 3, then up 5. The steps keep getting bigger, so the points bend upward instead of staying in line.',
        beats: [
          { say: 'Now Plant B. It goes 0, 1, 4, 9.' },
          { say: 'That is up 1, then up 3, then up 5.', pic: 1 },
          { say: 'The steps keep getting bigger, so the points bend upward instead of staying in line.', pic: 0 },
        ],
        pictures: [dots([[0, 0], [1, 1], [2, 4], [3, 9]], [{ a: [0, 0], b: [1, 1], dashed: true }, { a: [1, 1], b: [2, 4], dashed: true }, { a: [2, 4], b: [3, 9], dashed: true }], true), eq('1 − 0 = 1', ['4 − 1 = 3', '9 − 4 = 5'])] },
      { title: 'Give it a name', text: 'Plant A changed by the same amount every step, so its points make a straight line. We have a name for a table like that. We call it linear, and Plant B is not linear.',
        beats: [
          { say: 'Plant A changed by the same amount every step, so its points make a straight line.', pic: 0 },
          { say: 'We have a name for a table like that.' },
          { say: 'We call it linear, and Plant B is not linear.', write: 'same change each step = linear' },
        ],
        pictures: [dots([[0, 1], [1, 3], [2, 5], [3, 7]], [{ a: [0, 1], b: [3, 7], extend: true }])] },
      { title: 'One thing not to do', text: "Careful with this one. Don't compare the y changes before you check the x steps. If x jumps 1 and then jumps 2, y should jump twice as far the second time, and it is still linear.",
        beats: [
          { say: 'Careful with this one.' },
          { say: "Don't compare the y changes before you check the x steps.", pic: 0 },
          { say: 'If x jumps 1 and then jumps 2, y should jump twice as far the second time, and it is still linear.', write: 'check the x steps first' },
        ],
        pictures: [{ kind: 'cards', wrong: 'x: 0, 1, 3 · y: 0, 2, 6 · up 2, up 4, so not linear', right: 'x went up 2, so up 4 is still 2 for each 1: linear' }] },
    ],
    turn: {
      text: 'Is this table linear?',
      picture: io(['0', '1', '2', '3'], ['2', '5', '8', '11'], 'x', 'y'),
      answer: { choices: LIN, correct: 0 },
      steps: ['x goes up 1 each time.', 'y goes 2, 5, 8, 11: up 3 every time.', 'The change is the same each step, so it is linear.'],
      prompt: 'Check that x goes up in equal steps. Then find how much y changes each step.',
      hint1: 'Does x go up by the same step each time?',
      hint2: 'Find 5 − 2, 8 − 5 and 11 − 8. Are they the same?',
      twin: { text: 'In this table x goes 1, 2, 3, 4 and y goes 1, 4, 9, 16. Is it linear?',
        picture: io(['1', '2', '3', '4'], ['1', '4', '9', '16'], 'x', 'y'),
        answer: { choices: LIN, correct: 1 },
        steps: ['x goes up 1 each time.', 'y goes up 3, then up 5, then up 7.', 'The changes are different, so it is not linear.'],
        hint1: 'How much does y change from one column to the next?',
        hint2: 'Find 4 − 1 and 9 − 4. Do they match?' },
    },
    won: { text: 'y went up 3 every step, so the points make a straight line.', sticker: 'A function whose graph is a straight line is a linear function. Any other function is nonlinear.' },
    twinWon: { text: 'y went 1, 4, 9, 16, and the changes kept growing, so it is not linear.', sticker: 'A function whose graph is a straight line is a linear function. Any other function is nonlinear.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Is this table linear?',
        picture: io(['0', '1', '2', '3'], ['4', '6', '8', '10'], 'x', 'y'), answer: { choices: LIN, correct: 0 },
        steps: ['x goes up 1 each time.', 'y goes 4, 6, 8, 10: up 2 every time.', 'The change is the same each step, so it is linear.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Is this table linear?',
        picture: io(['0', '1', '2', '3'], ['10', '7', '4', '1'], 'x', 'y'), answer: { choices: LIN, correct: 0 },
        steps: ['x goes up 1 each time.', 'y goes 10, 7, 4, 1: down 3 every time.', 'Going down by the same amount still counts, so it is linear.'] } },
      { why: 'Still "same change each step"', problem: { text: 'Are these points linear?',
        picture: dots([[0, 1], [1, 2], [2, 4], [3, 8]]), answer: { choices: LIN, correct: 1 },
        steps: ['x goes up 1 each time.', 'y goes 1, 2, 4, 8: up 1, then up 2, then up 4.', 'The changes are different, so it is not linear.'] } },
      { why: 'A little harder', problem: { text: 'Is this table linear? Watch the x steps.',
        picture: io(['0', '1', '3', '4'], ['5', '7', '11', '13'], 'x', 'y'), answer: { choices: LIN, correct: 0 },
        steps: ['x goes up 1, then 2, then 1.', 'y goes up 2, then 4, then 2. That is 2 for each 1 in x, every time.', 'So it is linear.'] } },
      { why: 'Same math in a story', problem: { text: 'A candle is 12 inches tall. After 1, 2 and 3 hours it is 10, 7 and 3 inches tall. Is its height linear?',
        picture: io(['0', '1', '2', '3'], ['12', '10', '7', '3'], 'Hours', 'Inches'), answer: { choices: LIN, correct: 1 },
        steps: ['The hours go up 1 each time.', 'The height goes down 2, then 3, then 4.', 'The changes are different, so it is not linear.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m3-t4', title: 'Compare two functions', skill: 'Compare how fast two functions grow when one is a table and one is a rule',
    bigIdea: 'Find how much each one goes up for every 1 step in x. The bigger number grows faster.',
    screens: [
      { title: 'Two savings jars', text: 'Ava shows her savings in a table. Ben tells you his rule: y = 8x + 2, where x is the number of weeks. Whose savings grow faster?',
        pictures: [io(['0', '1', '2', '3'], ['10', '16', '22', '28'], 'Weeks (x)', 'Ava ($)'), eq('Ben: y = 8x + 2')] },
      { title: 'Not the same kind of picture', text: 'These two do not even look alike. One is a table and one is a rule. And Ava starts out with more money than Ben does. But where you start is not the same thing as how fast you grow.',
        beats: [
          { say: 'These two do not even look alike. One is a table and one is a rule.', pic: 0 },
          { say: 'And Ava starts out with more money than Ben does.', pic: 1 },
          { say: 'But where you start is not the same thing as how fast you grow.', write: 'where you start is not how fast' },
        ],
        pictures: [io(['0', '1', '2', '3'], ['10', '16', '22', '28'], 'Weeks (x)', 'Ava ($)'), eq('Ben: y = 8x + 2')] },
      { title: 'The big idea', text: 'Find how much each one goes up for every 1 step in x. The bigger number grows faster.',
        beats: [
          { say: 'Find how much each one goes up for every 1 step in x.', pic: 0 },
          { say: 'The bigger number grows faster.', pic: 1 },
        ],
        pictures: [io(['0', '1', '2', '3'], ['10', '16', '22', '28'], 'Weeks (x)', 'Ava ($)'), eq('Ben: y = 8x + 2')] },
      { title: "Ava's table", text: 'Take Ava first. Week by week her savings go 10, 16, 22, 28. Subtract to find each step and you get 6 every time. So Ava is up $6 a week.',
        beats: [
          { say: 'Take Ava first. Week by week her savings go 10, 16, 22, 28.', pic: 0 },
          { say: 'Subtract to find each step and you get 6 every time.', pic: 1 },
          { say: 'So Ava is up $6 a week.', write: 'Ava: $6 a week' },
        ],
        pictures: [io(['0', '1', '2', '3'], ['10', '16', '22', '28'], 'Weeks (x)', 'Ava ($)', [[0, 1], [0, 2], [0, 3], [0, 4]], true), eq('16 − 10 = 6', ['22 − 16 = 6', '28 − 22 = 6'])] },
      { title: "Ben's rule", text: "Now Ben. His rule is y = 8x + 2, and every extra week adds another 8. Let's check that. Week 0 is $2, week 1 is $10, week 2 is $18. That is up $8 a week.",
        beats: [
          { say: 'Now Ben. His rule is y = 8x + 2, and every extra week adds another 8.', pic: 1 },
          { say: "Let's check that. Week 0 is $2, week 1 is $10, week 2 is $18.", pic: 0 },
          { say: 'That is up $8 a week.', write: 'Ben: $8 a week' },
        ],
        pictures: [io(['0', '1', '2'], ['2', '10', '18'], 'Weeks (x)', 'Ben ($)', [[0, 1], [0, 2], [0, 3]], true), eq('y = 8x + 2', ['8 more each week'])] },
      { title: 'Compare the two numbers', text: "Now put the two numbers side by side. 8 is more than 6. So Ben's savings grow faster, even though Ava started with more in her jar.",
        beats: [
          { say: 'Now put the two numbers side by side.', pic: 0 },
          { say: '8 is more than 6.' },
          { say: "So Ben's savings grow faster, even though Ava started with more in her jar." },
        ],
        pictures: [eq('Ben: 8 a week   Ava: 6 a week', ['8 > 6', 'Ben grows faster'])] },
      { title: 'One thing not to do', text: "Here is the trap. Don't pick the one that starts higher. That + 2 in Ben's rule is where he starts, not how fast he grows.",
        beats: [
          { say: 'Here is the trap.' },
          { say: "Don't pick the one that starts higher.", pic: 0 },
          { say: "That + 2 in Ben's rule is where he starts, not how fast he grows.", write: 'the number in front of x is the speed' },
        ],
        pictures: [{ kind: 'cards', wrong: 'Ava starts at $10, so Ava grows faster', right: 'Ben adds $8 a week, Ava $6, so Ben grows faster' }] },
    ],
    turn: {
      text: 'Function A is the table. Function B is y = 3x + 10. Which grows faster?',
      picture: io(['0', '1', '2', '3'], ['5', '9', '13', '17'], 'x', 'A: y'),
      answer: { choices: AB, correct: 0 },
      steps: ['Function A goes 5, 9, 13, 17: up 4 for each 1 in x.', 'In y = 3x + 10, function B goes up 3 for each 1 in x.', '4 is more than 3, so function A grows faster.'],
      prompt: 'Find how much each one goes up for each 1 in x. Compare the two numbers.',
      hint1: 'How much does the table go up each time x goes up 1?',
      hint2: 'Compare the table\'s step with the number in front of x in the rule.',
      twin: { text: 'Function A is y = 2x + 9. Function B is the table. Which grows faster?',
        picture: io(['0', '1', '2', '3'], ['1', '4', '7', '10'], 'x', 'B: y'),
        answer: { choices: AB, correct: 1 },
        steps: ['Function A adds 2 for each 1 in x.', 'Function B goes 1, 4, 7, 10: up 3 for each 1 in x.', '3 is more than 2, so function B grows faster.'],
        hint1: 'What number is in front of x in function A?',
        hint2: 'How much does the table go up each time x goes up 1?' },
    },
    won: { text: 'The table went up 4 each step and the rule only 3, so function A grows faster.', sticker: 'How much y changes for each 1 in x is called the rate of change.' },
    twinWon: { text: 'The table went up by more than the 2 in 2x + 9, so function B grows faster.', sticker: 'How much y changes for each 1 in x is called the rate of change.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'Function A is the table. Function B is y = 5x + 12. Which grows faster?',
        picture: io(['0', '1', '2', '3'], ['2', '8', '14', '20'], 'x', 'A: y'), answer: { choices: AB, correct: 0 },
        steps: ['Function A goes 2, 8, 14, 20: up 6 for each 1 in x.', 'Function B goes up 5 for each 1 in x.', '6 is more than 5, so function A grows faster.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'Function A is the table. Function B is y = 7x. Which grows faster?',
        picture: io(['0', '1', '2', '3'], ['7', '12', '17', '22'], 'x', 'A: y'), answer: { choices: AB, correct: 1 },
        steps: ['Function A goes 7, 12, 17, 22: up 5 for each 1 in x.', 'Function B goes up 7 for each 1 in x.', '7 is more than 5, so function B grows faster.'] } },
      { why: 'Still "find each step"', problem: { text: 'Function A is y = 6x + 3. Function B is the table. How much does function B go up for each 1 in x?',
        picture: io(['0', '1', '2', '3'], ['3', '11', '19', '27'], 'x', 'B: y'), answer: 8,
        steps: ['Function B goes 3, 11, 19, 27.', 'Each step is 11 − 3, the same every time.', 'So function B goes up 8 for each 1 in x.'] } },
      { why: 'A little harder', problem: { text: 'Function A is y = 4x + 20. Function B is the table. Which grows faster? Watch the x steps.',
        picture: io(['0', '2', '4', '6'], ['1', '11', '21', '31'], 'x', 'B: y'), answer: { choices: AB, correct: 1 },
        steps: ['In the table, x goes up 2 each time and y goes up 10.', 'So function B goes up 10 ÷ 2 = 5 for each 1 in x. Function A goes up 4.', '5 is more than 4, so function B grows faster.'] } },
      { why: 'Same math in a story', problem: { text: "Maya's plant is h = 1.5w + 4 inches tall after w weeks. Leo's plant is in the table. How many more inches each week does Leo's plant grow than Maya's?",
        picture: io(['0', '1', '2', '3'], ['2', '4', '6', '8'], 'Weeks', 'Leo (in.)'), answer: 0.5,
        steps: ["Maya's plant grows 1.5 inches each week.", "Leo's goes 2, 4, 6, 8: 2 inches each week.", "2 − 1.5 = 0.5, so Leo's grows 0.5 inch more each week."] } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m3-t5', title: 'Build a model from a story', skill: 'Turn a story with a one-time amount and a repeated amount into y = mx + b',
    bigIdea: 'The amount that repeats each time goes in front of x. The amount paid once is added on.',
    screens: [
      { title: 'Joining a gym', text: 'A gym costs $25 to join, plus $10 for every month. How can you write one rule for the cost after any number of months?',
        pictures: [io(['0', '1', '2', '3'], ['?', '?', '?', '?'], 'Months (x)', 'Cost (y)')] },
      { title: 'Too many months to list', text: 'You could just keep adding $10 down a list. 35, 45, 55, and on it goes. But for 24 months that is a very long list to write out. A rule does the whole thing in one line.',
        beats: [
          { say: 'You could just keep adding $10 down a list. 35, 45, 55, and on it goes.', pic: 0 },
          { say: 'But for 24 months that is a very long list to write out.' },
          { say: 'A rule does the whole thing in one line.', write: 'one rule, any number of months' },
        ],
        pictures: [io(['1', '2', '3', '24'], ['35', '45', '55', '?'], 'Months (x)', 'Cost (y)')] },
      { title: 'The big idea', text: 'The amount that repeats each time goes in front of x. The amount paid once is added on.',
        beats: [
          { say: 'The amount that repeats each time goes in front of x.', pic: 0 },
          { say: 'The amount paid once is added on.' },
        ],
        pictures: [io(['0', '1', '2', '3'], ['25', '35', '45', '55'], 'Months (x)', 'Cost (y)')] },
      { title: 'What you pay once', text: 'Start with the $25. You pay that one time, right at the start. So at 0 months, before a single month has gone by, you have already paid $25.',
        beats: [
          { say: 'Start with the $25. You pay that one time, right at the start.', pic: 0 },
          { say: 'So at 0 months, before a single month has gone by, you have already paid $25.', write: 'paid once \u2192 add it on' },
        ],
        pictures: [io(['0', '1', '2', '3'], ['25', '?', '?', '?'], 'Months (x)', 'Cost (y)', [[0, 1]], true)] },
      { title: 'What repeats', text: 'Now the part that repeats. Each month adds another $10, so x months add 10 \u00d7 x. We write that as 10x. Check it at 3 months: 25 + 10 \u00d7 3 = 55.',
        beats: [
          { say: 'Now the part that repeats. Each month adds another $10, so x months add 10 \u00d7 x.', pic: 0 },
          { say: 'We write that as 10x.', write: '10x is 10 for every month' },
          { say: 'Check it at 3 months: 25 + 10 \u00d7 3 = 55.', pic: 1 },
        ],
        pictures: [io(['0', '1', '2', '3'], ['25', '35', '45', '55'], 'Months (x)', 'Cost (y)', [[0, 2], [0, 3], [0, 4]], true), eq('25 + 10 × 3 = 55')] },
      { title: 'Put it together', text: 'Put the two pieces together. The cost is 10 times the months, plus 25. Use y for the cost and x for the months and you get y = 10x + 25. Now those 24 months take one line.',
        beats: [
          { say: 'Put the two pieces together. The cost is 10 times the months, plus 25.' },
          { say: 'Use y for the cost and x for the months and you get y = 10x + 25.', pic: 0 },
          { say: 'Now those 24 months take one line.' },
        ],
        pictures: [eq('y = 10x + 25', ['x = 24: 10 × 24 + 25', 'y = 265'])] },
      { title: 'One thing not to do', text: "Here is the swap to watch for. Don't put the one-time amount in front of x. The $25 is paid once, so it gets added on. It never gets multiplied by the months.",
        beats: [
          { say: 'Here is the swap to watch for.' },
          { say: "Don't put the one-time amount in front of x.", pic: 0 },
          { say: 'The $25 is paid once, so it gets added on. It never gets multiplied by the months.', write: 'paid once \u2192 add, not multiply' },
        ],
        pictures: [{ kind: 'cards', wrong: 'y = 25x + 10', right: 'y = 10x + 25' }] },
    ],
    turn: {
      text: 'A skating rink costs $15 to join, plus $8 for each visit. Which rule gives the cost y for x visits?',
      picture: io(['0', '1', '2'], ['15', '23', '?'], 'Visits (x)', 'Cost (y)'),
      answer: { choices: ['y = 8x + 15', 'y = 15x + 8', 'y = 23x', 'y = 8x − 15'], correct: 0 },
      steps: ['The $8 repeats every visit, so it goes in front of x: 8x.', 'The $15 is paid once, so it is added on.', 'So the rule is y = 8x + 15.'],
      prompt: 'Find the amount that repeats and the amount paid once.',
      hint1: 'Which amount is paid every visit? Which is paid only once?',
      hint2: 'The amount paid each visit goes in front of x.',
      twin: { text: 'A tree is 4 feet tall and grows 2 feet each year. Which rule gives its height y after x years?',
        picture: io(['0', '1', '2'], ['4', '?', '?'], 'Years (x)', 'Feet (y)'),
        answer: { choices: ['y = 4x + 2', 'y = 2x + 4', 'y = 6x', 'y = 2x − 4'], correct: 1 },
        steps: ['The 2 feet repeat every year, so they go in front of x: 2x.', 'The 4 feet are where the tree starts, so they are added on.', 'So the rule is y = 2x + 4.'],
        hint1: 'Which amount happens every year? Which is there from the start?',
        hint2: 'The amount that repeats goes in front of x.' },
    },
    won: { text: 'You put the $8 that repeats in front of x and added the $15 paid once.', sticker: 'In y = mx + b, the starting amount b is called the initial value.' },
    twinWon: { text: 'The 2 feet repeat each year and the 4 feet are the start, so y = 2x + 4.', sticker: 'In y = mx + b, the starting amount b is called the initial value.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A bowling alley charges $4 for shoes, plus $6 for each game. Which rule gives the cost y for x games?',
        picture: io(['0', '1', '2'], ['4', '10', '?'], 'Games (x)', 'Cost (y)'), answer: { choices: ['y = 6x + 4', 'y = 4x + 6', 'y = 10x', 'y = 6x − 4'], correct: 0 },
        steps: ['The $6 repeats every game, so it goes in front of x: 6x.', 'The $4 for shoes is paid once, so it is added on.', 'So the rule is y = 6x + 4.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A streaming plan costs $9 to sign up, plus $14 each month. Write the cost as y = mx + b. What is m?',
        picture: eq('y = mx + b'), answer: 14,
        steps: ['m is the amount that repeats, in front of x.', '$14 is paid every month; $9 is paid only once.', 'So m is 14.'] } },
      { why: 'Still "once is added, each time multiplies"', problem: { text: 'A taxi ride costs $3.50 to start, plus $2 for each mile. Write the cost as y = mx + b. What is b?',
        picture: eq('y = mx + b'), answer: 3.5,
        steps: ['b is the amount paid once, added on.', 'The $2 repeats every mile, so that is m. The $3.50 is paid once.', 'So b is 3.5.'] } },
      { why: 'A little harder', problem: { text: 'A gym costs $35 to join, plus $18 a month. What is the total cost, in dollars, after 7 months?',
        picture: io(['0', '7'], ['35', '?'], 'Months (x)', 'Cost (y)'), answer: 161,
        steps: ['The rule is y = 18x + 35.', 'Put in 7 months: 18 × 7 = 126.', 'Then 126 + 35, so the cost is $161.'] } },
      { why: 'Same math in a story', problem: { text: 'A water tank holds 200 gallons. It drains 15 gallons every hour. How many gallons are left after 6 hours?',
        picture: io(['0', '6'], ['200', '?'], 'Hours (x)', 'Gallons (y)'), answer: 110,
        steps: ['It starts at 200 and loses 15 each hour: y = −15x + 200.', 'After 6 hours: 15 × 6 = 90 gallons are gone.', '200 − 90, so 110 gallons are left.'] } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m3-t6', title: "Read a graph's story", skill: 'Describe each piece of a graph as going up, going down or flat, and find where it changes fastest',
    bigIdea: 'Read the graph from left to right. Up means the amount is growing, down means it is shrinking, and flat means it is not changing.',
    screens: [
      { title: 'A bike ride', text: 'This graph shows how far Sam is from home on a bike ride. Along the bottom is hours. Up the side is miles from home. What story does it tell?',
        pictures: [path(RIDE)] },
      { title: 'No rule to use', text: 'There is no rule here to put numbers into. Nothing to multiply, nothing to add. You read this one by looking at the shape of the graph, one piece at a time.',
        beats: [
          { say: 'There is no rule here to put numbers into. Nothing to multiply, nothing to add.', pic: 0 },
          { say: 'You read this one by looking at the shape of the graph, one piece at a time.', write: 'read it piece by piece' },
        ],
        pictures: [path(RIDE)] },
      { title: 'The big idea', text: 'Read the graph from left to right. Up means the amount is growing, down means it is shrinking, and flat means it is not changing.',
        beats: [
          { say: 'Read the graph from left to right.', pic: 0 },
          { say: 'Up means the amount is growing, down means it is shrinking, and flat means it is not changing.' },
        ],
        pictures: [path(RIDE)] },
      { title: 'Going up', text: 'Start at the left. From hour 0 to hour 2 the graph climbs. The distance from home is growing, so Sam is riding away from home.',
        beats: [
          { say: 'Start at the left. From hour 0 to hour 2 the graph climbs.', pic: 0 },
          { say: 'The distance from home is growing, so Sam is riding away from home.', write: 'up = riding away' },
        ],
        pictures: [path(RIDE, 0, true)] },
      { title: 'Flat', text: 'Now the next piece. From hour 2 to hour 4 the graph runs flat at 6 miles. The distance is not changing at all. Sam has stopped for a rest.',
        beats: [
          { say: 'Now the next piece. From hour 2 to hour 4 the graph runs flat at 6 miles.', pic: 0 },
          { say: 'The distance is not changing at all.' },
          { say: 'Sam has stopped for a rest.', write: 'flat = stopped' },
        ],
        pictures: [path(RIDE, 1, true)] },
      { title: 'Steep or gentle, up or down', text: 'Two of these pieces go up, but not in the same way. From hour 4 to hour 6 the graph climbs only 2 miles, and from hour 0 to hour 2 it climbed 6. Steeper means faster. And from hour 6 to hour 10 it heads back down, because Sam is riding home.',
        beats: [
          { say: 'Two of these pieces go up, but not in the same way.', pic: 0 },
          { say: 'From hour 4 to hour 6 the graph climbs only 2 miles, and from hour 0 to hour 2 it climbed 6.' },
          { say: 'Steeper means faster.', write: 'steeper = faster' },
          { say: 'And from hour 6 to hour 10 it heads back down, because Sam is riding home.' },
        ],
        pictures: [path(RIDE, 3, true)] },
      { title: 'One thing not to do', text: "Here is the big one. Don't read the graph as a picture of a hill. Going down does not mean Sam is riding downhill. It means he is getting closer to home.",
        beats: [
          { say: 'Here is the big one.' },
          { say: "Don't read the graph as a picture of a hill.", pic: 0 },
          { say: 'Going down does not mean Sam is riding downhill. It means he is getting closer to home.', write: 'the graph shows distance, not a hill' },
        ],
        pictures: [{ kind: 'cards', wrong: 'The graph goes down, so Sam rides down a hill', right: 'The graph goes down, so Sam gets closer to home' }] },
    ],
    turn: {
      text: 'The graph shows how many miles Mia is from home. Along the bottom is hours. What is her distance doing between hour 3 and hour 5?',
      picture: path([[0, 0], [3, 6], [5, 6], [8, 0]]),
      answer: { choices: CH, correct: 2 },
      steps: ['Find hour 3 and hour 5 along the bottom.', 'Between them the graph is flat, staying at 6 miles.', 'So the distance is not changing.'],
      prompt: 'Find the two hours along the bottom. Is that piece going up, going down or flat?',
      hint1: 'Find hour 3 and hour 5 on the bottom. What does the graph do between them?',
      hint2: 'Is that piece going up, going down or flat?',
      twin: { text: 'The graph shows how many miles Jon is from home. What is his distance doing between hour 6 and hour 9?',
        picture: path([[0, 2], [2, 8], [6, 8], [9, 2]]),
        answer: { choices: CH, correct: 1 },
        steps: ['Find hour 6 and hour 9 along the bottom.', 'Between them the graph goes down, from 8 miles to 2 miles.', 'So the distance is decreasing.'],
        hint1: 'Find hour 6 and hour 9 on the bottom.',
        hint2: 'Read from left to right. Does that piece go up, go down or stay flat?' },
    },
    won: { text: 'The graph was flat between hour 3 and hour 5, so Mia stayed put.', sticker: 'Where a graph goes up, the function is increasing. Down is decreasing. Flat is constant.' },
    twinWon: { text: 'Between hour 6 and hour 9 the graph went down, so the distance was decreasing.', sticker: 'Where a graph goes up, the function is increasing. Down is decreasing. Flat is constant.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'The graph shows miles from home. What is the distance doing between hour 2 and hour 5?',
        picture: path([[0, 0], [2, 4], [5, 4], [7, 10]]), answer: { choices: CH, correct: 2 },
        steps: ['Find hour 2 and hour 5 along the bottom.', 'Between them the graph is flat at 4 miles.', 'So the distance is not changing.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'The graph shows miles from home. What is the distance doing between hour 0 and hour 4?',
        picture: path([[0, 9], [4, 1], [6, 1], [8, 5]]), answer: { choices: CH, correct: 1 },
        steps: ['Find hour 0 and hour 4 along the bottom.', 'Between them the graph goes down, from 9 miles to 1 mile.', 'So the distance is decreasing.'] } },
      { why: 'Still "read it left to right"', problem: { text: 'The graph shows miles from home. During which hour did the distance not change?',
        picture: path([[0, 0], [1, 3], [2, 3], [4, 9]]), answer: { choices: ['hour 0 to 1', 'hour 1 to 2', 'hour 2 to 3'], correct: 1 },
        steps: ['From hour 0 to 1 the graph goes up.', 'From hour 1 to 2 it is flat, and after hour 2 it goes up again.', 'So the distance did not change from hour 1 to 2.'] } },
      { why: 'A little harder', problem: { text: 'The graph shows miles from home. During which part is the distance growing fastest?',
        picture: path([[0, 0], [2, 2], [3, 7], [6, 9]]), answer: { choices: ['hour 0 to 2', 'hour 2 to 3', 'hour 3 to 6'], correct: 1 },
        steps: ['From hour 0 to 2 it climbs 2 miles, just 1 mile each hour.', 'From hour 2 to 3 it climbs 5 miles in one hour. From hour 3 to 6 it climbs only 2 miles in 3 hours.', 'The steepest piece is hour 2 to 3.'] } },
      { why: 'Same math in a story', problem: { text: 'The graph shows the gallons of water in a sink over minutes. What is the water doing between minute 7 and minute 10?',
        picture: path([[0, 0], [3, 6], [7, 6], [10, 0]]), answer: { choices: CH, correct: 1 },
        steps: ['Find minute 7 and minute 10 along the bottom.', 'Between them the graph goes down to 0: the sink is draining.', 'So the water is decreasing.'] } },
    ],
  },
]
