/**
 * Grade 8 · Module 5 — Volume of cylinders, cones and spheres.
 * Written to docs/new-flow/AUTHORING.md. Not yet reviewed by the founder.
 * Every topic teaches with `solid` (it cannot animate, so the moving picture is a `table`). π ≈ 3.14 throughout.
 * ⚠️ `solid` draws its r label on a radius line, so a problem that gives a DIAMETER leaves r unlabelled
 * rather than write "across" on a radius.
 */
import type { Lesson, Picture } from '../script'

const cyl = (r?: string, h?: string): Picture => ({ kind: 'solid', shape: 'cylinder', labels: { r, h } })
const cone = (r?: string, h?: string): Picture => ({ kind: 'solid', shape: 'cone', labels: { r, h } })
const ball = (r?: string): Picture => ({ kind: 'solid', shape: 'sphere', labels: { r } })

const WHICH = (a: string, b: string, correct: 0 | 1 | 2) => ({ choices: [a, b, 'they hold the same'], correct })

export const G8M5: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m5-t1', title: 'Volume of a cylinder', skill: 'Volume of a cylinder = area of the circle base × height, using π ≈ 3.14',
    bigIdea: 'A cylinder is a stack of circles. Find the area of the circle, 3.14 × radius × radius, then multiply by the height.',
    screens: [
      { title: 'A can of soup', text: 'A soup can is 2 in from its center to its edge and 5 in tall. How much soup fits inside?',
        pictures: [cyl('2 in', '5 in')] },
      { title: 'Cubes leave gaps', text: 'In a box you can stack cubes and count them. A can is round, so cubes leave gaps all along the curved side.',
        pictures: [cyl('2 in', '5 in')] },
      { title: 'The big idea', text: 'A cylinder is a stack of circles. Find the area of the circle, 3.14 × radius × radius, then multiply by the height.',
        pictures: [cyl('2 in', '5 in')] },
      { title: 'The bottom circle', text: 'The circle on the bottom has a radius of 2 in. Its area is 3.14 × 2 × 2 = 12.56 square inches.',
        pictures: [cyl('2 in'), { kind: 'eq', text: '3.14 × 2 × 2 = 12.56', lines: ['12.56 square inches in one layer'] }] },
      { title: 'Stack the layers', text: 'Each inch of height is one more layer of 12.56. The can is 5 in tall, so there are 5 layers.',
        pictures: [cyl('2 in', '5 in'),
          { kind: 'table', head: ['layers', '1', '2', '3', '4', '5'], rows: [['cubic inches', '12.56', '25.12', '37.68', '50.24', '62.8']], rowHead: true, motion: true }] },
      { title: 'Put it together', text: '12.56 × 5 = 62.8. That is the same as 3.14 × 2 × 2 × 5. The can holds 62.8 cubic inches.',
        pictures: [cyl('2 in', '5 in'), { kind: 'eq', text: '3.14 × 2 × 2 × 5 = 62.8', lines: ['62.8 cubic inches'] }] },
      { title: 'One thing not to do', text: "Don't use the distance across. The can is 4 in across, but the rule needs the radius, 2 in.",
        pictures: [{ kind: 'cards', wrong: '3.14 × 4 × 4 × 5 = 251.2', right: '3.14 × 2 × 2 × 5 = 62.8' }] },
    ],
    turn: {
      text: 'A can has a radius of 2 in and a height of 7 in. What is its volume in cubic inches? Use π ≈ 3.14.',
      picture: cyl('2 in', '7 in'),
      answer: 87.92, steps: ['The circle on the bottom: 3.14 × 2 × 2 = 12.56 square inches.', 'There are 7 layers of 12.56: 12.56 × 7.', 'So the volume is 87.92 cubic inches.'],
      prompt: 'Find the area of the circle. Then multiply by the height.',
      hint1: 'What is the area of the circle on the bottom?',
      hint2: 'Find 3.14 × 2 × 2. Then multiply by the height, 7.',
      twin: { text: 'A glass is 6 cm across and 10 cm tall. What is its volume in cubic centimeters? Use π ≈ 3.14.',
        picture: cyl(undefined, '10 cm'),
        answer: 282.6, steps: ['Halve the distance across: the radius is 3 cm.', 'The circle: 3.14 × 3 × 3 = 28.26. There are 10 layers: 28.26 × 10.', 'So the volume is 282.6 cubic centimeters.'],
        hint1: 'The rule needs the radius. Is 6 cm the radius?', hint2: 'Take half of 6 first. Find the area of the circle, then multiply by 10.' },
    },
    won: { text: 'You found the area of the circle, then stacked it up the height.', sticker: 'The volume of a cylinder is V = π × r × r × h, and π is about 3.14.' },
    twinWon: { text: 'You halved the 6 cm across before finding the circle, then stacked 10 layers.', sticker: 'The volume of a cylinder is V = π × r × r × h, and π is about 3.14.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A can has a radius of 2 in and a height of 3 in. What is its volume in cubic inches? Use π ≈ 3.14.',
        picture: cyl('2 in', '3 in'), answer: 37.68,
        steps: ['The circle: 3.14 × 2 × 2 = 12.56.', 'Multiply by the height: 12.56 × 3.', 'So the volume is 37.68 cubic inches.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A cylinder has a radius of 4 cm and a height of 2 cm. What is its volume in cubic centimeters? Use π ≈ 3.14.',
        picture: cyl('4 cm', '2 cm'), answer: 100.48,
        steps: ['The circle: 3.14 × 4 × 4 = 50.24.', 'Multiply by the height: 50.24 × 2.', 'So the volume is 100.48 cubic centimeters.'] } },
      { why: 'Still "circle × height"', problem: { text: 'A cylinder has a radius of 5 m and a height of 3 m. What is its volume in cubic meters? Use π ≈ 3.14.',
        picture: cyl('5 m', '3 m'), answer: 235.5,
        steps: ['The circle: 3.14 × 5 × 5 = 78.5.', 'Multiply by the height: 78.5 × 3.', 'So the volume is 235.5 cubic meters.'] } },
      { why: 'A little harder', problem: { text: 'A round pool is 12 ft across and 5 ft deep. How many cubic feet of water fill it? Use π ≈ 3.14.',
        picture: cyl(undefined, '5 ft'), answer: 565.2,
        steps: ['Halve the distance across: the radius is 6 ft.', 'The circle: 3.14 × 6 × 6 = 113.04. Multiply by the depth: 113.04 × 5.', 'So 565.2 cubic feet of water fill it.'] } },
      { why: 'Same math in a story', problem: { text: 'Leo has a rain barrel shaped like a cylinder. It has a radius of 3 ft and a height of 6 ft. How many cubic feet of rain can it hold? Use π ≈ 3.14.',
        picture: cyl('3 ft', '6 ft'), answer: 169.56,
        steps: ['The circle: 3.14 × 3 × 3 = 28.26.', 'Multiply by the height: 28.26 × 6.', 'So it can hold 169.56 cubic feet of rain.'] } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m5-t2', title: 'Volume of a cone', skill: 'Volume of a cone = 1/3 of the cylinder with the same base and height, using π ≈ 3.14',
    bigIdea: 'A cone holds 1/3 of the cylinder with the same bottom and height. Find the cylinder, then divide by 3.',
    screens: [
      { title: 'A paper cup', text: 'A cone-shaped paper cup is 3 cm from the center to the edge at the top, and 4 cm tall. How much water does it hold?',
        pictures: [cone('3 cm', '4 cm')] },
      { title: 'It gets narrow', text: 'A cone is not the same all the way up. Its circles shrink to a point, so you cannot stack one circle again and again.',
        pictures: [cone('3 cm', '4 cm')] },
      { title: 'The big idea', text: 'A cone holds 1/3 of the cylinder with the same bottom and height. Find the cylinder, then divide by 3.',
        pictures: [cone('3 cm', '4 cm'), cyl('3 cm', '4 cm')] },
      { title: 'Pour it in', text: 'Fill the cone with water. Pour it into a cylinder with the same bottom and the same height. It takes 3 full cones to fill the cylinder.',
        pictures: [cyl('3 cm', '4 cm'),
          { kind: 'table', head: ['cones poured', '1', '2', '3'], rows: [['cylinder', '1/3 full', '2/3 full', 'full']], rowHead: true, motion: true }] },
      { title: 'Find the cylinder first', text: 'The cylinder with the same bottom and height: 3.14 × 3 × 3 × 4 = 113.04 cubic centimeters.',
        pictures: [cyl('3 cm', '4 cm'), { kind: 'eq', text: '3.14 × 3 × 3 × 4 = 113.04' }] },
      { title: 'Take one third', text: 'The cone holds 1/3 of that. 113.04 ÷ 3 = 37.68. The cup holds 37.68 cubic centimeters.',
        pictures: [cone('3 cm', '4 cm'), { kind: 'eq', text: '113.04 ÷ 3 = 37.68', lines: ['37.68 cubic centimeters'] }] },
      { title: 'One thing not to do', text: "Don't stop at the cylinder. A cone holds only one third of it, so divide by 3.",
        pictures: [{ kind: 'cards', wrong: '3.14 × 3 × 3 × 4 = 113.04', right: '1/3 × 3.14 × 3 × 3 × 4 = 37.68' }] },
    ],
    turn: {
      text: 'A cone has a radius of 3 cm and a height of 5 cm. What is its volume in cubic centimeters? Use π ≈ 3.14.',
      picture: cone('3 cm', '5 cm'),
      answer: 47.1, steps: ['The cylinder with the same bottom and height: 3.14 × 3 × 3 × 5 = 141.3.', 'The cone is 1/3 of it: 141.3 ÷ 3.', 'So the volume is 47.1 cubic centimeters.'],
      prompt: 'Find the cylinder with the same bottom and height. Then divide by 3.',
      hint1: 'What would a cylinder with the same bottom and height hold?',
      hint2: 'Find 3.14 × 3 × 3 × 5. Then divide by 3.',
      twin: { text: 'A cone has a radius of 6 in and a height of 2 in. What is its volume in cubic inches? Use π ≈ 3.14.',
        picture: cone('6 in', '2 in'),
        answer: 75.36, steps: ['The cylinder with the same bottom and height: 3.14 × 6 × 6 × 2 = 226.08.', 'The cone is 1/3 of it: 226.08 ÷ 3.', 'So the volume is 75.36 cubic inches.'],
        hint1: 'Start with the cylinder that has the same bottom and height.', hint2: 'Find 3.14 × 6 × 6 × 2. Then take one third of it.' },
    },
    won: { text: 'You found the cylinder, then took one third of it.', sticker: 'The volume of a cone is V = 1/3 × π × r × r × h, and π is about 3.14.' },
    twinWon: { text: 'You found the cylinder for the 6 in radius and 2 in height, then took one third.', sticker: 'The volume of a cone is V = 1/3 × π × r × r × h, and π is about 3.14.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A cone has a radius of 3 cm and a height of 2 cm. What is its volume in cubic centimeters? Use π ≈ 3.14.',
        picture: cone('3 cm', '2 cm'), answer: 18.84,
        steps: ['The cylinder: 3.14 × 3 × 3 × 2 = 56.52.', 'The cone is 1/3 of it: 56.52 ÷ 3.', 'So the volume is 18.84 cubic centimeters.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A cone has a radius of 2 in and a height of 6 in. What is its volume in cubic inches? Use π ≈ 3.14.',
        picture: cone('2 in', '6 in'), answer: 25.12,
        steps: ['The cylinder: 3.14 × 2 × 2 × 6 = 75.36.', 'The cone is 1/3 of it: 75.36 ÷ 3.', 'So the volume is 25.12 cubic inches.'] } },
      { why: 'Still "one third of the cylinder"', problem: { text: 'A cone has a radius of 4 m and a height of 3 m. What is its volume in cubic meters? Use π ≈ 3.14.',
        picture: cone('4 m', '3 m'), answer: 50.24,
        steps: ['The cylinder: 3.14 × 4 × 4 × 3 = 150.72.', 'The cone is 1/3 of it: 150.72 ÷ 3.', 'So the volume is 50.24 cubic meters.'] } },
      { why: 'A little harder', problem: { text: 'A cone is 12 cm across its bottom and 10 cm tall. What is its volume in cubic centimeters? Use π ≈ 3.14.',
        picture: cone(undefined, '10 cm'), answer: 376.8,
        steps: ['Halve the distance across: the radius is 6 cm.', 'The cylinder: 3.14 × 6 × 6 × 10 = 1,130.4. The cone is 1/3 of it: 1,130.4 ÷ 3.', 'So the volume is 376.8 cubic centimeters.'] } },
      { why: 'Same math in a story', problem: { text: 'Nina fills a cone-shaped funnel with sand. The funnel has a radius of 5 cm and a height of 12 cm. How many cubic centimeters of sand does it hold? Use π ≈ 3.14.',
        picture: cone('5 cm', '12 cm'), answer: 314,
        steps: ['The cylinder: 3.14 × 5 × 5 × 12 = 942.', 'The funnel is a cone, so 1/3 of it: 942 ÷ 3.', 'So it holds 314 cubic centimeters of sand.'] } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m5-t3', title: 'Volume of a sphere', skill: 'Volume of a sphere = 4/3 × π × r × r × r, using π ≈ 3.14',
    bigIdea: 'A ball fills 2/3 of the can that fits around it. Its volume is 4/3 × 3.14 × radius × radius × radius.',
    screens: [
      { title: 'A round ball', text: 'A ball is 3 in from its center to its outside. How much air is inside it?',
        pictures: [ball('3 in')] },
      { title: 'No bottom, no height', text: 'A ball has no flat bottom to stack layers on. The cylinder rule has nothing to hold on to.',
        pictures: [ball('3 in')] },
      { title: 'The big idea', text: 'A ball fills 2/3 of the can that fits around it. Its volume is 4/3 × 3.14 × radius × radius × radius.',
        pictures: [ball('3 in'), cyl('3 in', '6 in')] },
      { title: 'A can that fits around it', text: 'The can that fits the ball exactly has the same radius, 3 in. Its height is the whole way across the ball: 3 × 2 = 6 in.',
        pictures: [cyl('3 in', '6 in'), { kind: 'eq', text: '3 × 2 = 6', lines: ['the can is 6 in tall'] }] },
      { title: 'The ball fills 2/3', text: 'Fill the can with water and push the ball in. The water that spills out is the size of the ball. 2/3 of the can spills, 1/3 stays.',
        pictures: [cyl('3 in', '6 in'),
          { kind: 'table', head: ['the can', 'spills out', 'stays in'], rows: [['full', '2/3', '1/3']], motion: true }] },
      { title: 'Work it out', text: 'The can: 3.14 × 3 × 3 × 6 = 169.56. Two thirds of it: 169.56 ÷ 3 × 2 = 113.04. The ball holds 113.04 cubic inches.',
        pictures: [ball('3 in'), { kind: 'eq', text: '4/3 × 3.14 × 3 × 3 × 3 = 113.04', lines: ['113.04 cubic inches'] }] },
      { title: 'One thing not to do', text: "Don't use the radius only twice. A ball is round in every direction, so the radius goes in three times.",
        pictures: [{ kind: 'cards', wrong: '4/3 × 3.14 × 3 × 3 = 37.68', right: '4/3 × 3.14 × 3 × 3 × 3 = 113.04' }] },
    ],
    turn: {
      text: 'A ball has a radius of 6 cm. What is its volume in cubic centimeters? Use π ≈ 3.14.',
      picture: ball('6 cm'),
      answer: 904.32, steps: ['Radius × radius × radius: 6 × 6 × 6 = 216.', 'Take 4/3 of it: 216 ÷ 3 × 4 = 288. Then 288 × 3.14.', 'So the volume is 904.32 cubic centimeters.'],
      prompt: 'Multiply the radius by itself three times. Take 4/3 of that, then multiply by 3.14.',
      hint1: 'How many times does the radius go into the rule?',
      hint2: 'Find 6 × 6 × 6. Then take 4/3 of it and multiply by 3.14.',
      twin: { text: 'A ball is 9 in across. What is its volume in cubic inches? Use π ≈ 3.14.',
        picture: ball(),
        answer: 381.51, steps: ['Halve the distance across: the radius is 4.5 in.', '4.5 × 4.5 × 4.5 = 91.125, and 4/3 of it is 121.5.', 'Multiply by 3.14: 121.5 × 3.14. So the volume is 381.51 cubic inches.'],
        hint1: 'Is 9 in the radius, or the whole way across?', hint2: 'Take half of 9 first. Use that radius three times, then take 4/3 and multiply by 3.14.' },
    },
    won: { text: 'You used the radius three times, took 4/3, and multiplied by 3.14.', sticker: 'The volume of a sphere is V = 4/3 × π × r × r × r, and π is about 3.14.' },
    twinWon: { text: 'You halved the 9 in across, then used the radius three times.', sticker: 'The volume of a sphere is V = 4/3 × π × r × r × r, and π is about 3.14.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A ball has a radius of 9 cm. What is its volume in cubic centimeters? Use π ≈ 3.14.',
        picture: ball('9 cm'), answer: 3052.08,
        steps: ['9 × 9 × 9 = 729.', 'Take 4/3 of it: 729 ÷ 3 × 4 = 972. Then 972 × 3.14.', 'So the volume is 3,052.08 cubic centimeters.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A marble has a radius of 1.5 cm. What is its volume in cubic centimeters? Use π ≈ 3.14.',
        picture: ball('1.5 cm'), answer: 14.13,
        steps: ['1.5 × 1.5 × 1.5 = 3.375.', 'Take 4/3 of it: 3.375 ÷ 3 × 4 = 4.5. Then 4.5 × 3.14.', 'So the volume is 14.13 cubic centimeters.'] } },
      { why: 'Still "the radius three times"', problem: { text: 'A ball has a radius of 3 m. Leave the answer as a number times π. How many π cubic meters is its volume?',
        picture: ball('3 m'), answer: 36,
        steps: ['3 × 3 × 3 = 27.', 'Take 4/3 of it: 27 ÷ 3 × 4 = 36.', 'So the volume is 36π cubic meters. The answer is 36.'] } },
      { why: 'A little harder', problem: { text: 'A ball is 15 cm across. What is its volume in cubic centimeters? Use π ≈ 3.14.',
        picture: ball(), answer: 1766.25,
        steps: ['Halve the distance across: the radius is 7.5 cm. 7.5 × 7.5 × 7.5 = 421.875.', 'Take 4/3 of it: 421.875 ÷ 3 × 4 = 562.5. Then 562.5 × 3.14.', 'So the volume is 1,766.25 cubic centimeters.'] } },
      { why: 'Same math in a story', problem: { text: 'A town stores water in a round tank shaped like a ball. The tank has a radius of 12 ft. How many cubic feet of water can it hold? Use π ≈ 3.14.',
        picture: ball('12 ft'), answer: 7234.56,
        steps: ['12 × 12 × 12 = 1,728.', 'Take 4/3 of it: 1,728 ÷ 3 × 4 = 2,304. Then 2,304 × 3.14.', 'So it can hold 7,234.56 cubic feet of water.'] } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g8m5-t4', title: 'Volume stories', skill: 'Choose the right volume rule for a real object, add the pieces, and compare, using π ≈ 3.14',
    bigIdea: 'First name each shape: can, cone or ball. Use its rule, and add the pieces when one object is made of two shapes.',
    screens: [
      { title: 'An ice-cream cone', text: 'A cone has a radius of 3 cm and a height of 4 cm. On top sits half a ball of ice cream with the same radius. How much ice cream is there in all?',
        pictures: [cone('3 cm', '4 cm'), ball('3 cm')] },
      { title: 'Two shapes in one', text: 'No one rule fits the whole thing. The bottom is a cone, and the top is half of a ball.',
        pictures: [cone('3 cm', '4 cm'), ball('3 cm')] },
      { title: 'The big idea', text: 'First name each shape: can, cone or ball. Use its rule, and add the pieces when one object is made of two shapes.',
        pictures: [cyl(), cone(), ball()] },
      { title: 'The cone part', text: 'The cone is 1/3 of its cylinder: 1/3 × 3.14 × 3 × 3 × 4 = 37.68 cubic centimeters.',
        pictures: [cone('3 cm', '4 cm'), { kind: 'eq', text: '1/3 × 3.14 × 3 × 3 × 4 = 37.68' }] },
      { title: 'The half ball', text: 'A whole ball: 4/3 × 3.14 × 3 × 3 × 3 = 113.04. The top is only half a ball, so 113.04 ÷ 2 = 56.52.',
        pictures: [ball('3 cm'), { kind: 'eq', text: '4/3 × 3.14 × 3 × 3 × 3 = 113.04', lines: ['113.04 ÷ 2 = 56.52'] }] },
      { title: 'Add the pieces', text: '37.68 + 56.52 = 94.2. There are 94.2 cubic centimeters of ice cream.',
        pictures: [cone('3 cm', '4 cm'),
          { kind: 'table', head: ['piece', 'cubic cm'], rows: [['cone', '37.68'], ['half ball', '56.52'], ['in all', '94.2']], rowHead: true, motion: true }] },
      { title: 'One thing not to do', text: "Don't add a whole ball when the top is only half a ball. Halve it first.",
        pictures: [{ kind: 'cards', wrong: '37.68 + 113.04 = 150.72', right: '37.68 + 56.52 = 94.2' }] },
    ],
    turn: {
      text: 'An ice-cream cone has a radius of 3 cm and a height of 8 cm. Half a ball of ice cream with a radius of 3 cm sits on top. How many cubic centimeters is that in all? Use π ≈ 3.14.',
      picture: cone('3 cm', '8 cm'),
      answer: 131.88, steps: ['The cone: 1/3 × 3.14 × 3 × 3 × 8 = 75.36.', 'The half ball: 4/3 × 3.14 × 3 × 3 × 3 = 113.04, and half of that is 56.52.', 'Add them: 75.36 + 56.52. So 131.88 cubic centimeters in all.'],
      prompt: 'Name the two shapes. Find each one, then add.',
      hint1: 'Which two shapes make up this ice-cream cone?',
      hint2: 'Find the cone. Then find a whole ball with radius 3 cm and take half. Add the two.',
      twin: { text: 'A can has a radius of 2 in and a height of 6 in. A ball has a radius of 3 in. Which holds more? Use π ≈ 3.14.',
        picture: { kind: 'table', head: ['', 'radius', 'height'], rows: [['can', '2 in', '6 in'], ['ball', '3 in', '']], rowHead: true },
        answer: WHICH('the can', 'the ball', 1),
        steps: ['The can: 3.14 × 2 × 2 × 6 = 75.36 cubic inches.', 'The ball: 4/3 × 3.14 × 3 × 3 × 3 = 113.04 cubic inches.', '113.04 is more than 75.36, so the answer is the ball.'],
        hint1: 'Use the can rule for the can and the ball rule for the ball.', hint2: 'Find both volumes. Then compare them.' },
    },
    won: { text: 'You named both shapes, found each one, and added them.', sticker: 'Half of a ball is called a hemisphere. Volume is always measured in cubic units.' },
    twinWon: { text: 'You found the can and the ball with their own rules, and saw the ball holds more.', sticker: 'Half of a ball is called a hemisphere. Volume is always measured in cubic units.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'An ice-cream cone has a radius of 3 cm and a height of 2 cm. Half a ball of ice cream with a radius of 3 cm sits on top. How many cubic centimeters is that in all? Use π ≈ 3.14.',
        picture: cone('3 cm', '2 cm'), answer: 75.36,
        steps: ['The cone: 1/3 × 3.14 × 3 × 3 × 2 = 18.84.', 'The half ball: 113.04 ÷ 2 = 56.52.', 'Add them: 18.84 + 56.52. So 75.36 cubic centimeters in all.'] } },
      { why: 'Same idea, new numbers', problem: { text: 'A juice can has a radius of 4 cm and a height of 10 cm. How many cubic centimeters of juice fit inside? Use π ≈ 3.14.',
        picture: cyl('4 cm', '10 cm'), answer: 502.4,
        steps: ['A can is a cylinder, so use circle × height.', 'The circle: 3.14 × 4 × 4 = 50.24. Then 50.24 × 10.', 'So 502.4 cubic centimeters of juice fit inside.'] } },
      { why: 'Still "name the shape first"', problem: { text: 'A funnel is a cone with a radius of 3 in and a height of 9 in. A can has a radius of 3 in and a height of 3 in. Which holds more? Use π ≈ 3.14.',
        picture: { kind: 'table', head: ['', 'radius', 'height'], rows: [['funnel (cone)', '3 in', '9 in'], ['can', '3 in', '3 in']], rowHead: true },
        answer: WHICH('the funnel', 'the can', 2),
        steps: ['The funnel: 1/3 × 3.14 × 3 × 3 × 9 = 84.78 cubic inches.', 'The can: 3.14 × 3 × 3 × 3 = 84.78 cubic inches.', 'Both are 84.78, so they hold the same.'] } },
      { why: 'A little harder', problem: { text: 'A ball with a radius of 3 in fits exactly inside a box that is 6 in long, 6 in wide and 6 in tall. How many cubic inches of the box are empty space? Use π ≈ 3.14.',
        picture: { kind: 'solid', shape: 'prism', labels: { l: '6 in', w: '6 in', h: '6 in' } }, answer: 102.96,
        steps: ['The box: 6 × 6 × 6 = 216 cubic inches.', 'The ball: 4/3 × 3.14 × 3 × 3 × 3 = 113.04 cubic inches.', 'Take the ball away from the box: 216 − 113.04. So 102.96 cubic inches are empty.'] } },
      { why: 'Same math in a story', problem: { text: 'A farm silo is a cylinder with a radius of 3 m and a height of 10 m, with half a ball of radius 3 m on top. How many cubic meters of grain can it hold? Use π ≈ 3.14.',
        picture: cyl('3 m', '10 m'), answer: 339.12,
        steps: ['The cylinder: 3.14 × 3 × 3 × 10 = 282.6.', 'The half ball: 4/3 × 3.14 × 3 × 3 × 3 = 113.04, and half of that is 56.52.', 'Add them: 282.6 + 56.52. So it can hold 339.12 cubic meters of grain.'] } },
    ],
  },
]
