// GENERATED by scripts/audio/build-manifest.mjs — do not edit (its --check fails if this drifts).
// One chapter's clips: clip key → [object name (16 hex), clipCheck]. One import() each, so each is its own chunk.
export type ClipIndex = Record<string, [string, string]>
export const VOICE_INDEX: Record<string, () => Promise<ClipIndex>> = {
  addition: () => import('./addition.json').then(x => x.default as unknown as ClipIndex),
  additionTo100: () => import('./additionTo100.json').then(x => x.default as unknown as ClipIndex),
  colors: () => import('./colors.json').then(x => x.default as unknown as ClipIndex),
  compareNumbers: () => import('./compareNumbers.json').then(x => x.default as unknown as ClipIndex),
  counting: () => import('./counting.json').then(x => x.default as unknown as ClipIndex),
  fractions: () => import('./fractions.json').then(x => x.default as unknown as ClipIndex),
  matchingQuantities: () => import('./matchingQuantities.json').then(x => x.default as unknown as ClipIndex),
  measurement: () => import('./measurement.json').then(x => x.default as unknown as ClipIndex),
  money: () => import('./money.json').then(x => x.default as unknown as ClipIndex),
  multiplication: () => import('./multiplication.json').then(x => x.default as unknown as ClipIndex),
  numberComparison: () => import('./numberComparison.json').then(x => x.default as unknown as ClipIndex),
  numberOrdering: () => import('./numberOrdering.json').then(x => x.default as unknown as ClipIndex),
  numberRecognition: () => import('./numberRecognition.json').then(x => x.default as unknown as ClipIndex),
  numbersTo100: () => import('./numbersTo100.json').then(x => x.default as unknown as ClipIndex),
  patterns: () => import('./patterns.json').then(x => x.default as unknown as ClipIndex),
  placeValue: () => import('./placeValue.json').then(x => x.default as unknown as ClipIndex),
  shapes: () => import('./shapes.json').then(x => x.default as unknown as ClipIndex),
  shapes2d3d: () => import('./shapes2d3d.json').then(x => x.default as unknown as ClipIndex),
  skipCounting: () => import('./skipCounting.json').then(x => x.default as unknown as ClipIndex),
  storyProblems: () => import('./storyProblems.json').then(x => x.default as unknown as ClipIndex),
  subtraction: () => import('./subtraction.json').then(x => x.default as unknown as ClipIndex),
  subtractionTo100: () => import('./subtractionTo100.json').then(x => x.default as unknown as ClipIndex),
  time: () => import('./time.json').then(x => x.default as unknown as ClipIndex),
}
