-- READ-ONLY. Compares production's schema NAMES (tables, views, columns+types, functions+args,
-- triggers incl. app triggers on auth tables, policies, enums) with what the repo's baseline +
-- 98 pre-2026-09-23 migrations produce. No data is read. 364 expected names.
-- Positive control: the COUNTS row — 'matched' must be large before an empty difference means anything.
with expected(kind, name) as (values
('column','admin_scope_accounts.created_at:timestamp with time zone'),
('column','admin_scope_accounts.id:uuid'),
('column','admin_scope_learners.age_group:text'),
('column','admin_scope_learners.created_at:timestamp with time zone'),
('column','admin_scope_learners.created_by:uuid'),
('column','admin_scope_learners.id:uuid'),
('column','admin_users.granted_at:timestamp with time zone'),
('column','admin_users.note:text'),
('column','admin_users.user_id:uuid'),
('column','auth_events.client_id:uuid'),
('column','auth_events.created_at:timestamp with time zone'),
('column','auth_events.event:text'),
('column','auth_events.id:uuid'),
('column','auth_events.user_id:uuid'),
('column','billing_config.enforced:boolean'),
('column','billing_config.id:boolean'),
('column','billing_config.updated_at:timestamp with time zone'),
('column','billing_events.account_id:uuid'),
('column','billing_events.at:timestamp with time zone'),
('column','billing_events.id:uuid'),
('column','billing_events.payload:jsonb'),
('column','billing_events.processed_at:timestamp with time zone'),
('column','billing_events.stripe_event_id:text'),
('column','billing_events.type:text'),
('column','chapters.age_groups:text[]'),
('column','chapters.emoji:text'),
('column','chapters.id:text'),
('column','chapters.is_free:boolean'),
('column','chapters.name:text'),
('column','chapters.sort_order:integer'),
('column','diagnostic_items.correct:boolean'),
('column','diagnostic_items.created_at:timestamp with time zone'),
('column','diagnostic_items.id:uuid'),
('column','diagnostic_items.ordinal:integer'),
('column','diagnostic_items.session_id:uuid'),
('column','diagnostic_items.skill_id:text'),
('column','diagnostic_leads.band:text'),
('column','diagnostic_leads.created_at:timestamp with time zone'),
('column','diagnostic_leads.email:text'),
('column','diagnostic_leads.id:uuid'),
('column','diagnostic_plan_progress.chapter_id:text'),
('column','diagnostic_plan_progress.id:uuid'),
('column','diagnostic_plan_progress.plan_id:uuid'),
('column','diagnostic_plan_progress.skill_id:text'),
('column','diagnostic_plan_progress.status:text'),
('column','diagnostic_plan_progress.updated_at:timestamp with time zone'),
('column','diagnostic_plans.active:boolean'),
('column','diagnostic_plans.chapter_sequence:text[]'),
('column','diagnostic_plans.created_at:timestamp with time zone'),
('column','diagnostic_plans.free_chapters:text[]'),
('column','diagnostic_plans.id:uuid'),
('column','diagnostic_plans.learner_id:uuid'),
('column','diagnostic_plans.revised_chapter:text'),
('column','diagnostic_plans.session_id:uuid'),
('column','diagnostic_plans.skill_sequence:text[]'),
('column','diagnostic_rechecks.client_id:uuid'),
('column','diagnostic_rechecks.created_at:timestamp with time zone'),
('column','diagnostic_rechecks.gap_closed:boolean'),
('column','diagnostic_rechecks.id:uuid'),
('column','diagnostic_rechecks.learner_id:uuid'),
('column','diagnostic_rechecks.session_id:uuid'),
('column','diagnostic_rechecks.skill_id:text'),
('column','diagnostic_rechecks.week:integer'),
('column','diagnostic_sessions.band:text'),
('column','diagnostic_sessions.blocked_skills:text[]'),
('column','diagnostic_sessions.client_id:uuid'),
('column','diagnostic_sessions.completed_at:timestamp with time zone'),
('column','diagnostic_sessions.id:uuid'),
('column','diagnostic_sessions.learner_id:uuid'),
('column','diagnostic_sessions.root_gap_skill:text'),
('column','diagnostic_sessions.second_gap_skill:text'),
('column','diagnostic_sessions.started_at:timestamp with time zone'),
('column','diagnostic_sessions.status:text'),
('column','diagnostic_sessions.strengths:text[]'),
('column','diagnostic_sessions.working_level:text'),
('column','error_events.at:timestamp with time zone'),
('column','error_events.component_stack:text'),
('column','error_events.digest:text'),
('column','error_events.id:uuid'),
('column','error_events.learner_id:uuid'),
('column','error_events.message:text'),
('column','error_events.method:text'),
('column','error_events.route_path:text'),
('column','error_events.source:text'),
('column','error_events.stack:text'),
('column','error_events.ua:text'),
('column','error_events.url:text'),
('column','exercise_results.class_id:uuid'),
('column','exercise_results.created_at:timestamp with time zone'),
('column','exercise_results.exercise_id:text'),
('column','exercise_results.id:uuid'),
('column','exercise_results.learner_id:uuid'),
('column','exercise_results.outcomes:text[]'),
('column','game_settings.enabled:boolean'),
('column','game_settings.learner_id:uuid'),
('column','game_settings.minutes_per_day:integer'),
('column','game_settings.time_zone:text'),
('column','game_settings.updated_at:timestamp with time zone'),
('column','grade_chapters.chapter_id:text'),
('column','grade_chapters.grade_id:uuid'),
('column','grade_chapters.sort_order:integer'),
('column','grades.age_group:text'),
('column','grades.created_at:timestamp with time zone'),
('column','grades.created_by:uuid'),
('column','grades.exercises:jsonb'),
('column','grades.grade:smallint'),
('column','grades.id:uuid'),
('column','grades.lesson_ids:text[]'),
('column','grades.name:text'),
('column','grades.updated_at:timestamp with time zone'),
('column','learner_access.access_role:text'),
('column','learner_access.granted_at:timestamp with time zone'),
('column','learner_access.id:uuid'),
('column','learner_access.learner_id:uuid'),
('column','learner_access.parent_id:uuid'),
('column','learner_events.client_id:text'),
('column','learner_events.client_ts:timestamp with time zone'),
('column','learner_events.created_at:timestamp with time zone'),
('column','learner_events.event:text'),
('column','learner_events.id:uuid'),
('column','learner_events.learner_id:uuid'),
('column','learner_events.props:jsonb'),
('column','learner_invites.created_at:timestamp with time zone'),
('column','learner_invites.expires_at:timestamp with time zone'),
('column','learner_invites.id:uuid'),
('column','learner_invites.invited_by:uuid'),
('column','learner_invites.invited_email:text'),
('column','learner_invites.learner_id:uuid'),
('column','learner_invites.status:invite_status'),
('column','learner_progress.best_stars:smallint'),
('column','learner_progress.chapter:text'),
('column','learner_progress.current_level:smallint'),
('column','learner_progress.id:uuid'),
('column','learner_progress.last_played_at:timestamp with time zone'),
('column','learner_progress.learner_id:uuid'),
('column','learner_progress.total_sessions:integer'),
('column','learner_progress.total_xp:integer'),
('column','learner_progress.updated_at:timestamp with time zone'),
('column','learner_state.coins_spent:integer'),
('column','learner_state.equipped_items:jsonb'),
('column','learner_state.learner_id:uuid'),
('column','learner_state.owned_items:text[]'),
('column','learner_state.updated_at:timestamp with time zone'),
('column','learner_stats.current_level:smallint'),
('column','learner_stats.last_played_at:timestamp with time zone'),
('column','learner_stats.learner_id:uuid'),
('column','learner_stats.total_coins:integer'),
('column','learner_stats.total_xp:integer'),
('column','learner_stats.updated_at:timestamp with time zone'),
('column','learners.age_group:text'),
('column','learners.avatar_index:smallint'),
('column','learners.created_at:timestamp with time zone'),
('column','learners.created_by:uuid'),
('column','learners.display_name:text'),
('column','learners.grade_id:uuid'),
('column','learners.id:uuid'),
('column','learners.lesson_due:jsonb'),
('column','learners.lesson_ids:text[]'),
('column','learners.updated_at:timestamp with time zone'),
('column','lesson_feedback.created_at:timestamp with time zone'),
('column','lesson_feedback.id:uuid'),
('column','lesson_feedback.learner_id:uuid'),
('column','lesson_feedback.lesson_id:text'),
('column','lesson_feedback.reasons:text[]'),
('column','lesson_feedback.screen:text'),
('column','lesson_progress.done:boolean'),
('column','lesson_progress.learner_id:uuid'),
('column','lesson_progress.lesson_id:text'),
('column','lesson_progress.level:integer'),
('column','lesson_progress.mastered:boolean'),
('column','lesson_progress.streak:integer'),
('column','lesson_progress.updated_at:timestamp with time zone'),
('column','parent_pins.account_id:uuid'),
('column','parent_pins.failed_count:integer'),
('column','parent_pins.locked_until:timestamp with time zone'),
('column','parent_pins.lockouts:integer'),
('column','parent_pins.pin_hash:text'),
('column','parent_pins.reset_requested_at:timestamp with time zone'),
('column','parent_pins.salt:text'),
('column','parent_pins.updated_at:timestamp with time zone'),
('column','point_events.client_id:uuid'),
('column','point_events.created_at:timestamp with time zone'),
('column','point_events.ends_at:timestamp with time zone'),
('column','point_events.id:uuid'),
('column','point_events.learner_id:uuid'),
('column','point_events.lesson_id:text'),
('column','point_events.minutes:integer'),
('column','point_events.points:integer'),
('column','point_events.reason:text'),
('column','profiles.avatar_index:smallint'),
('column','profiles.created_at:timestamp with time zone'),
('column','profiles.display_name:text'),
('column','profiles.id:uuid'),
('column','profiles.is_internal:boolean'),
('column','profiles.role:user_role'),
('column','profiles.updated_at:timestamp with time zone'),
('column','sessions.chapter:text'),
('column','sessions.client_id:text'),
('column','sessions.coins_earned:integer'),
('column','sessions.completed_at:timestamp with time zone'),
('column','sessions.correct_count:smallint'),
('column','sessions.id:uuid'),
('column','sessions.learner_id:uuid'),
('column','sessions.phase:text'),
('column','sessions.stars_earned:smallint'),
('column','sessions.started_at:timestamp with time zone'),
('column','sessions.wrong_count:smallint'),
('column','sessions.xp_earned:integer'),
('column','subscription_seats.assigned_at:timestamp with time zone'),
('column','subscription_seats.id:uuid'),
('column','subscription_seats.last_reassigned_at:timestamp with time zone'),
('column','subscription_seats.learner_id:uuid'),
('column','subscription_seats.seat_index:integer'),
('column','subscription_seats.subscription_id:uuid'),
('column','subscriptions.account_id:uuid'),
('column','subscriptions.cancel_at_period_end:boolean'),
('column','subscriptions.created_at:timestamp with time zone'),
('column','subscriptions.current_period_end:timestamp with time zone'),
('column','subscriptions.current_period_start:timestamp with time zone'),
('column','subscriptions.grace_until:timestamp with time zone'),
('column','subscriptions.id:uuid'),
('column','subscriptions.seats_paid:integer'),
('column','subscriptions.status:text'),
('column','subscriptions.stripe_customer_id:text'),
('column','subscriptions.stripe_subscription_id:text'),
('column','subscriptions.updated_at:timestamp with time zone'),
('column','teacher_plans.paid:boolean'),
('column','teacher_plans.teacher_id:uuid'),
('column','teacher_plans.updated_at:timestamp with time zone'),
('enum','invite_status'),
('enum','user_role'),
('function','admin_assert()'),
('function','admin_funnel(p_min_cohort integer)'),
('function','admin_learning(p_min_cohort integer)'),
('function','admin_overview(p_min_cohort integer)'),
('function','can_self_grant_access(p_learner_id uuid, p_role text)'),
('function','delete_lead_by_email(p_email text)'),
('function','delete_my_account(p_confirm_email text)'),
('function','enforce_grade_cap()'),
('function','enforce_grade_ownership()'),
('function','enforce_learner_cap()'),
('function','entitle_revised_step(p_learner_id uuid, p_chapter text)'),
('function','entitled_chapters(p_learner_id uuid, p_chapters text[])'),
('function','game_wallet(p_learner uuid)'),
('function','get_insights_rollup(p_since timestamp with time zone)'),
('function','get_learner_bootstrap(p_learner_id uuid)'),
('function','get_parent_dashboard()'),
('function','grant_owner_access()'),
('function','handle_new_user()'),
('function','init_learner_stats()'),
('function','is_chapter_entitled(p_learner_id uuid, p_chapter text)'),
('function','materialize_seats(p_subscription_id uuid, p_seats integer)'),
('function','parent_pin_hash(p_salt text, p_pin text)'),
('function','parent_pin_status()'),
('function','prune_diagnostic_items()'),
('function','prune_diagnostic_leads()'),
('function','prune_error_events()'),
('function','prune_unconfirmed_users()'),
('function','reassign_learner_seat(p_seat_id uuid, p_learner_id uuid)'),
('function','record_lesson_progress(p_learner uuid, p_lesson text, p_done boolean, p_level integer, p_streak integer, p_mastered boolean, p_outcome text, p_event uuid)'),
('function','record_module_practice(p_learner uuid, p_module text, p_event uuid)'),
('function','request_parent_pin_reset()'),
('function','rls_auto_enable()'),
('function','set_game_settings(p_learner uuid, p_enabled boolean, p_minutes_per_day integer, p_time_zone text)'),
('function','set_parent_pin(p_pin text, p_current text)'),
('function','set_updated_at()'),
('function','start_diagnostic(p_learner_id uuid, p_band text, p_client_id uuid)'),
('function','start_game_time(p_learner uuid, p_minutes integer)'),
('function','sync_diagnostic(p_learner_id uuid, p_band text, p_root_gap text, p_second_gap text, p_blocked text[], p_strengths text[], p_working_level text, p_plan_skills text[], p_plan_chapters text[], p_items jsonb, p_client_id uuid)'),
('function','sync_recheck(p_learner_id uuid, p_week integer, p_skill text, p_gap_closed boolean, p_client_id uuid)'),
('function','sync_session(p_learner_id uuid, p_chapter text, p_phase text, p_correct integer, p_wrong integer, p_stars integer, p_xp integer, p_coins integer, p_client_id text, p_completed_at timestamp with time zone)'),
('function','sync_session(p_learner_id uuid, p_chapter text, p_phase text, p_correct integer, p_wrong integer, p_stars integer, p_xp integer, p_coins integer, p_client_id text, p_completed_at timestamp with time zone, p_difficulty integer)'),
('function','sync_session(p_learner_id uuid, p_chapter text, p_phase text, p_correct integer, p_wrong integer, p_stars integer, p_xp integer, p_coins integer, p_client_id text, p_completed_at timestamp with time zone, p_difficulty integer, p_started_at timestamp with time zone)'),
('function','touch_grades_updated_at()'),
('function','verify_parent_pin(p_pin text)'),
('policy','auth_events.own inserts only'),
('policy','chapters.chapters: select'),
('policy','diagnostic_items.diag_items_read'),
('policy','diagnostic_leads.diagnostic_leads: insert'),
('policy','diagnostic_plan_progress.diag_progress_read'),
('policy','diagnostic_plans.diag_plans_read'),
('policy','diagnostic_rechecks.diag_rechecks_read'),
('policy','diagnostic_sessions.diag_sessions_read'),
('policy','exercise_results.exercise_results: teacher or the child reads'),
('policy','exercise_results.exercise_results: the child posts an open exercise'),
('policy','game_settings.game_settings: read'),
('policy','grade_chapters.grade_chapters: delete'),
('policy','grade_chapters.grade_chapters: insert'),
('policy','grade_chapters.grade_chapters: select'),
('policy','grades.grades: delete'),
('policy','grades.grades: insert'),
('policy','grades.grades: select'),
('policy','grades.grades: update'),
('policy','learner_access.learner_access: delete'),
('policy','learner_access.learner_access: insert'),
('policy','learner_access.learner_access: select'),
('policy','learner_events.learner_events_insert'),
('policy','learner_events.learner_events_select'),
('policy','learner_invites.learner_invites: recipient can accept'),
('policy','learner_invites.learner_invites: recipient can view'),
('policy','learner_invites.learner_invites: sender'),
('policy','learner_progress.learner_progress: parent access'),
('policy','learner_state.learner_state: parent access'),
('policy','learner_stats.learner_stats: parent access'),
('policy','learners.learners: delete'),
('policy','learners.learners: insert'),
('policy','learners.learners: select'),
('policy','learners.learners: update'),
('policy','lesson_feedback.lesson_feedback: sent for a learner you can reach'),
('policy','lesson_feedback.lesson_feedback: the child''s adults and the child read'),
('policy','lesson_progress.lesson_progress: read'),
('policy','point_events.point_events: read'),
('policy','profiles.profiles: own row'),
('policy','sessions.sessions: parent can insert'),
('policy','sessions.sessions: parent can read'),
('policy','subscription_seats.subscription_seats: owner can read'),
('policy','subscriptions.subscriptions: owner can read'),
('policy','teacher_plans.teacher_plans: read own or my creator''s'),
('table','admin_users'),
('table','auth_events'),
('table','billing_config'),
('table','billing_events'),
('table','chapters'),
('table','diagnostic_items'),
('table','diagnostic_leads'),
('table','diagnostic_plan_progress'),
('table','diagnostic_plans'),
('table','diagnostic_rechecks'),
('table','diagnostic_sessions'),
('table','error_events'),
('table','exercise_results'),
('table','game_settings'),
('table','grade_chapters'),
('table','grades'),
('table','learner_access'),
('table','learner_events'),
('table','learner_invites'),
('table','learner_progress'),
('table','learner_state'),
('table','learner_stats'),
('table','learners'),
('table','lesson_feedback'),
('table','lesson_progress'),
('table','parent_pins'),
('table','point_events'),
('table','profiles'),
('table','sessions'),
('table','subscription_seats'),
('table','subscriptions'),
('table','teacher_plans'),
('trigger','auth.users.on_auth_user_created'),
('trigger','public.grades.trg_enforce_grade_cap'),
('trigger','public.grades.trg_touch_grades'),
('trigger','public.learner_progress.learner_progress_updated_at'),
('trigger','public.learner_stats.learner_stats_updated_at'),
('trigger','public.learners.learners_updated_at'),
('trigger','public.learners.on_learner_created'),
('trigger','public.learners.on_learner_created_stats'),
('trigger','public.learners.trg_enforce_grade_ownership'),
('trigger','public.learners.trg_enforce_learner_cap'),
('trigger','public.profiles.profiles_updated_at'),
('trigger','public.subscriptions.subscriptions_updated_at'),
('view','admin_scope_accounts'),
('view','admin_scope_learners')
),
actual as (
select kind, name from (
  select 'table' kind, c.relname::text name from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p')
  union all select 'view', c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('v','m')
  union all select 'column', c.relname||'.'||a.attname||':'||format_type(a.atttypid,a.atttypmod) from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p','v','m') and a.attnum>0 and not a.attisdropped
  union all select 'function', p.proname||'('||pg_get_function_identity_arguments(p.oid)||')' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prokind in ('f','p') and not exists (select 1 from pg_depend d where d.objid=p.oid and d.deptype='e')
  union all select 'trigger', n.nspname||'.'||c.relname||'.'||t.tgname from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where not t.tgisinternal and (n.nspname='public' or (n.nspname='auth' and exists (select 1 from pg_proc p join pg_namespace pn on pn.oid=p.pronamespace where p.oid=t.tgfoid and pn.nspname='public')))
  union all select 'policy', tablename||'.'||policyname from pg_policies where schemaname='public'
  union all select 'enum', t.typname from pg_type t join pg_namespace n on n.oid=t.typnamespace where n.nspname='public' and t.typtype='e'
) x order by 1,2
),
missing as (select kind, name from expected except select kind, name from actual),
extra   as (select kind, name from actual   except select kind, name from expected)
select 'COUNTS' as status, null::text as kind,
       format('expected=%s production=%s matched=%s missing=%s extra=%s',
              (select count(*) from expected), (select count(*) from actual),
              (select count(*) from (select kind,name from expected intersect select kind,name from actual) m),
              (select count(*) from missing), (select count(*) from extra))
       || format(' | db: public_tables=%s has_learners=%s', (select count(*) from pg_tables where schemaname = 'public'), to_regclass('public.learners') is not null) as name
union all select 'missing_in_production', kind, name from missing
union all select 'extra_in_production',   kind, name from extra
order by 1, 2, 3;
