/**
 * Grade 3 · Module 1 — Multiplication and Division with Units of 2, 3, 4, 5 and 10.
 * Source of truth for the wording: docs/new-flow/grade3-module1-scripts.md (approved 2026-09-13).
 * Change a sentence there first, then here.
 */
import type { Lesson } from './script'
import { attachChalk } from './chalk'
import { G3M1_CHALK } from './content/chalk/g3m1'

export const MODULE_1_TITLE = 'Multiplication and Division with 2, 3, 4, 5 and 10'

export const GRADE3_MODULE1: Lesson[] = [
  // ── Topic 1 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m1-t1', title: 'Plates of cookies', skill: 'Multiplication means equal groups',
    bigIdea: 'When every group has the same number, you can count a whole group at a time.',
    screens: [
      { title: 'Cookies on plates', text: 'There are 4 plates. Each plate has 3 cookies. How many cookies are there?',
        pictures: [{ kind: 'groups', groups: 4, each: 3, obj: 'cookie' }], scene: 'table' },
      { title: 'Counting one by one is slow', text: "You could count every cookie. That works. But it's slow, and it's easy to lose your place. Is there a faster way? Yes. Look at the plates.",
        beats: [
          { say: 'You could count every cookie.', pic: 0 },
          { say: "That works. But it's slow, and it's easy to lose your place." },
          { say: 'Is there a faster way? Yes. Look at the plates.' },
        ],
        pictures: [{ kind: 'groups', groups: 4, each: 3, obj: 'cookie', show: 'count' }] },
      { title: 'The big idea', text: 'When every group has the same number, you can count a whole group at a time.',
        beats: [
          { say: 'When every group has the same number, you can count a whole group at a time.', pic: 0 },
        ],
        pictures: [{ kind: 'groups', groups: 4, each: 3, obj: 'cookie' }] },
      { title: 'How many groups? How many in each?', text: "Look. Each plate is a group. There are 4 plates, so there are 4 groups. And each plate has 3 cookies. That's 3 in each group.",
        beats: [
          { say: 'Look. Each plate is a group.', pic: 0 },
          { say: 'There are 4 plates, so there are 4 groups.' },
          { say: "And each plate has 3 cookies. That's 3 in each group.", pic: 1 },
        ],
        pictures: [{ kind: 'groups', groups: 4, each: 3, obj: 'cookie', show: 'rings', motion: true }, { kind: 'eq', text: '4 groups · 3 in each' }] },
      { title: 'Count by 3s', text: 'Now count one whole plate at a time. 3, 6, 9, 12. So there are 12 cookies.',
        beats: [
          { say: 'Now count one whole plate at a time.', pic: 0 },
          { say: '3, 6, 9, 12.' },
          { say: 'So there are 12 cookies.' },
        ],
        pictures: [{ kind: 'groups', groups: 4, each: 3, obj: 'cookie', show: 'running', motion: true }] },
      { title: '4 groups of 3', text: '4 groups of 3 make 12. We write that as 4 × 3 = 12. The first number is the groups. The second is how many in each.',
        beats: [
          { say: '4 groups of 3 make 12.', pic: 0 },
          { say: 'We write that as 4 × 3 = 12.', pic: 1 },
          { say: 'The first number is the groups. The second is how many in each.' },
        ],
        pictures: [{ kind: 'groups', groups: 4, each: 3, obj: 'cookie' }, { kind: 'eq', text: '4 × 3 = 12' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. 4 × 3 does not mean ADD 4 and 3. That gives 7, just one plate and 4 more cookies. 4 × 3 is 4 whole plates of 3. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: '4 × 3 does not mean ADD 4 and 3.', pic: 0 },
          { say: 'That gives 7, just one plate and 4 more cookies. 4 × 3 is 4 whole plates of 3.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '4 × 3 = 7', right: '4 × 3 = 12' }] },
    ],
    turn: {
      text: '3 plates. 5 cookies on each plate. How many cookies?', op: { t: 'mul', a: 3, b: 5 },
      picture: { kind: 'groups', groups: 3, each: 5, obj: 'cookie' },
      prompt: 'Find how many groups and how many in each. Then count by groups.',
      hint1: 'How many plates are there? How many cookies are on each plate?',
      hint2: 'There are 3 groups of 5. Count by 5s, one plate at a time: 5, 10 …',
      twin: { text: '5 plates. 2 cookies on each plate. How many cookies?', op: { t: 'mul', a: 5, b: 2 },
        picture: { kind: 'groups', groups: 5, each: 2, obj: 'cookie' } },
    },
    won: { text: 'You counted by groups instead of one by one. That is multiplication.', sticker: 'Equal groups = multiplication. 3 × 5 means 3 groups of 5.' },
    twinWon: { text: 'You counted by groups instead of one by one. That is multiplication.', sticker: 'Equal groups = multiplication. 5 × 2 means 5 groups of 2.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '2 plates, 3 cookies on each. How many cookies?', op: { t: 'mul', a: 2, b: 3 }, picture: { kind: 'groups', groups: 2, each: 3, obj: 'cookie' } } },
      { why: 'Same idea, new numbers', problem: { text: '5 plates, 2 cookies on each. How many cookies?', op: { t: 'mul', a: 5, b: 2 }, picture: { kind: 'groups', groups: 5, each: 2, obj: 'cookie' } } },
      { why: 'Still "equal groups", new objects', problem: { text: '4 bags, 5 marbles in each. How many marbles?', op: { t: 'mul', a: 4, b: 5 }, picture: { kind: 'groups', groups: 4, each: 5, obj: 'dot' } } },
      { why: 'A little harder', problem: { text: '10 plates, 2 cookies on each. How many cookies?', op: { t: 'mul', a: 10, b: 2 }, picture: { kind: 'groups', groups: 10, each: 2, obj: 'cookie' } } },
      { why: 'Same math in a story', problem: { text: 'Sam has 3 packs of stickers. Each pack has 4 stickers. How many stickers?', op: { t: 'mul', a: 3, b: 4 }, picture: { kind: 'groups', groups: 3, each: 4, obj: 'sticker' } } },
    ],
  },

  // ── Topic 2 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m1-t2', title: 'Rows of chairs', skill: 'Equal rows (arrays)',
    bigIdea: 'When every row has the same number, count the rows, count one row, then multiply.',
    screens: [
      { title: 'Chairs in a hall', text: 'The chairs are set out in 3 rows. Each row has 5 chairs. How many chairs are there?',
        pictures: [{ kind: 'array', rows: 3, cols: 5, obj: 'chair' }] },
      { title: 'A jumble is hard to count', text: "When chairs are jumbled, you have to count every one. And it's easy to miss some. What if they stand in neat rows? Then it's much faster.",
        beats: [
          { say: 'When chairs are jumbled, you have to count every one.', pic: 0 },
          { say: "And it's easy to miss some." },
          { say: "What if they stand in neat rows? Then it's much faster.", pic: 1 },
        ],
        pictures: [{ kind: 'scatter', n: 15, obj: 'chair' }, { kind: 'array', rows: 3, cols: 5, obj: 'chair' }] },
      { title: 'The big idea', text: 'When every row has the same number, count the rows, count one row, then multiply.',
        beats: [
          { say: 'When every row has the same number, count the rows, count one row, then multiply.', pic: 0 },
        ],
        pictures: [{ kind: 'array', rows: 3, cols: 5, obj: 'chair' }] },
      { title: 'How many rows?', text: 'Look. Rows go across, from left to right. Count them. 1, 2, 3. There are 3 rows.',
        beats: [
          { say: 'Look. Rows go across, from left to right.', pic: 0 },
          { say: 'Count them. 1, 2, 3.' },
          { say: 'There are 3 rows.' },
        ],
        pictures: [{ kind: 'array', rows: 3, cols: 5, obj: 'chair', show: 'rows', motion: true }] },
      { title: 'How many in a row?', text: 'Every row is the same, so you only need to count one. 1, 2, 3, 4, 5. Each row has 5 chairs.',
        beats: [
          { say: 'Every row is the same, so you only need to count one.', pic: 0 },
          { say: '1, 2, 3, 4, 5.' },
          { say: 'Each row has 5 chairs.' },
        ],
        pictures: [{ kind: 'array', rows: 3, cols: 5, obj: 'chair', show: 'oneRow' }] },
      { title: '3 rows of 5', text: 'Now count one whole row at a time. 5, 10, 15. 3 rows of 5 is 15. We write it as 3 × 5 = 15.',
        beats: [
          { say: 'Now count one whole row at a time. 5, 10, 15.', pic: 0 },
          { say: '3 rows of 5 is 15.' },
          { say: 'We write it as 3 × 5 = 15.', pic: 1 },
        ],
        pictures: [{ kind: 'array', rows: 3, cols: 5, obj: 'chair', show: 'running', motion: true }, { kind: 'eq', text: '3 × 5 = 15' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. If one row is missing a chair, it is NOT 3 × 5 any more. Every row must have the same number. Count each row to check. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: 'If one row is missing a chair, it is NOT 3 × 5 any more.', pic: 0 },
          { say: 'Every row must have the same number. Count each row to check.', pic: 1 },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'array', rows: 3, cols: 5, obj: 'chair', missing: true }, { kind: 'cards', wrong: 'rows of 5, 5, 4', right: '3 full rows of 5' }] },
    ],
    turn: {
      text: 'A garden has 4 rows. Each row has 3 tomato plants. How many plants?', op: { t: 'mul', a: 4, b: 3 },
      picture: { kind: 'array', rows: 4, cols: 3, obj: 'plant' },
      prompt: 'Count the rows. Count one row. Then multiply.',
      hint1: 'How many rows are there? How many plants are in one row?',
      hint2: 'There are 4 rows of 3. Count by 3s, one row at a time: 3, 6 …',
      twin: { text: 'A garden has 2 rows. Each row has 5 plants. How many plants?', op: { t: 'mul', a: 2, b: 5 },
        picture: { kind: 'array', rows: 2, cols: 5, obj: 'plant' } },
    },
    won: { text: 'You counted the rows and one row, then multiplied. That is the whole trick.', sticker: 'Equal rows = an array.' },
    twinWon: { text: 'You counted the rows and one row, then multiplied. That is the whole trick.', sticker: 'Equal rows = an array.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: 'A muffin tray has 3 rows, 4 muffins in each row. How many muffins?', op: { t: 'mul', a: 3, b: 4 }, picture: { kind: 'array', rows: 3, cols: 4, obj: 'muffin' } } },
      { why: 'Same idea, new numbers', problem: { text: 'A building has 5 rows of windows, 2 windows in each row. How many windows?', op: { t: 'mul', a: 5, b: 2 }, picture: { kind: 'array', rows: 5, cols: 2, obj: 'dot' } } },
      { why: 'Still "equal rows"', problem: { text: 'A sheet of stamps has 4 rows, 5 stamps in each row. How many stamps?', op: { t: 'mul', a: 4, b: 5 }, picture: { kind: 'array', rows: 4, cols: 5, obj: 'sticker' } } },
      { why: 'A little harder', problem: { text: 'A box of chocolates has 5 rows, 5 in each row. How many chocolates?', op: { t: 'mul', a: 5, b: 5 }, picture: { kind: 'array', rows: 5, cols: 5, obj: 'cookie' } } },
      { why: 'Same math in a story', problem: { text: 'The class sits in 4 rows. There are 4 desks in each row. How many desks?', op: { t: 'mul', a: 4, b: 4 }, picture: { kind: 'array', rows: 4, cols: 4, obj: 'chair' } } },
    ],
  },

  // ── Topic 3 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m1-t3', title: 'Turn the tray', skill: 'The order does not change the total',
    bigIdea: 'Turning the rows around does not change how many there are, so 2 × 5 and 5 × 2 make the same total.',
    screens: [
      { title: 'A tray of muffins', text: 'This tray has 2 rows of 5 muffins. What happens if we turn the tray around?',
        pictures: [{ kind: 'array', rows: 2, cols: 5, obj: 'muffin' }] },
      { title: 'It looks like a new problem', text: 'Turn the tray, and now there are 5 rows of 2. It looks different. So did the number of muffins change?',
        beats: [
          { say: 'Turn the tray, and now there are 5 rows of 2.', pic: 0 },
          { say: 'It looks different. So did the number of muffins change?' },
        ],
        pictures: [{ kind: 'array', rows: 5, cols: 2, obj: 'muffin' }] },
      { title: 'The big idea', text: 'Turning the rows around does not change how many there are, so 2 × 5 and 5 × 2 make the same total.',
        beats: [
          { say: 'Turning the rows around does not change how many there are, so 2 × 5 and 5 × 2 make the same total.', pic: 0 },
        ],
        pictures: [{ kind: 'array', rows: 2, cols: 5, obj: 'muffin' }, { kind: 'array', rows: 5, cols: 2, obj: 'muffin' }] },
      { title: '2 rows of 5', text: 'First, the tray as it started. 2 rows of 5. Count by rows. 5, 10. So 2 × 5 = 10.',
        beats: [
          { say: 'First, the tray as it started. 2 rows of 5.', pic: 0 },
          { say: 'Count by rows. 5, 10.' },
          { say: 'So 2 × 5 = 10.', pic: 1 },
        ],
        pictures: [{ kind: 'array', rows: 2, cols: 5, obj: 'muffin', show: 'running', motion: true }, { kind: 'eq', text: '2 × 5 = 10' }] },
      { title: 'Turn the tray', text: 'Now watch the tray turn. Does any muffin fall off? No. Is any muffin added? No. Every muffin just moves to a new spot.',
        beats: [
          { say: 'Now watch the tray turn.', pic: 0 },
          { say: 'Does any muffin fall off? No. Is any muffin added? No.' },
          { say: 'Every muffin just moves to a new spot.' },
        ],
        pictures: [{ kind: 'array', rows: 2, cols: 5, obj: 'muffin', turn: true, motion: true }] },
      { title: '5 rows of 2', text: 'Now count the turned tray by rows. 2, 4, 6, 8, 10. So 5 × 2 = 10. Same muffins, same total.',
        beats: [
          { say: 'Now count the turned tray by rows. 2, 4, 6, 8, 10.', pic: 0 },
          { say: 'So 5 × 2 = 10.', pic: 1 },
          { say: 'Same muffins, same total.' },
        ],
        pictures: [{ kind: 'array', rows: 5, cols: 2, obj: 'muffin', show: 'running', motion: true }, { kind: 'eq', text: '5 × 2 = 10' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. This turn-around trick works for times. It does NOT work for take away. 5 − 2 leaves 3. But 2 − 5 does not leave 3, so they are not the same. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: 'This turn-around trick works for times. It does NOT work for take away.', pic: 0 },
          { say: "5 − 2 leaves 3. But 2 − 5 does not leave 3, so they are not the same." },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '5 − 2 = 2 − 5', right: '5 × 2 = 2 × 5' }] },
    ],
    turn: {
      text: '4 × 10 = 40. What is 10 × 4?', op: { t: 'turn', a: 4, b: 10 },
      picture: { kind: 'array', rows: 4, cols: 10, obj: 'dot', turn: true },
      prompt: 'Turn the rows around. Does the total change?',
      hint1: 'Tap turn. Were any dots added or taken away?',
      hint2: '10 × 4 is the same dots turned around, so it has the same total as 4 × 10.',
      twin: { text: '3 × 5 = 15. What is 5 × 3?', op: { t: 'turn', a: 3, b: 5 },
        picture: { kind: 'array', rows: 3, cols: 5, obj: 'dot', turn: true } },
    },
    won: { text: 'You turned the rows around and the total stayed the same. That is the whole trick.', sticker: 'Turn-around facts = the commutative property.' },
    twinWon: { text: 'You turned the rows around and the total stayed the same. That is the whole trick.', sticker: 'Turn-around facts = the commutative property.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '2 × 4 = 8. What is 4 × 2?', op: { t: 'turn', a: 2, b: 4 }, picture: { kind: 'array', rows: 2, cols: 4, obj: 'dot', turn: true } } },
      { why: 'Same idea, new numbers', problem: { text: '3 × 10 = 30. What is 10 × 3?', op: { t: 'turn', a: 3, b: 10 }, picture: { kind: 'array', rows: 3, cols: 10, obj: 'dot', turn: true } } },
      { why: 'Still "turn it around"', problem: { text: '5 × 4 = 20. What is 4 × 5?', op: { t: 'turn', a: 5, b: 4 }, picture: { kind: 'array', rows: 5, cols: 4, obj: 'dot', turn: true } } },
      { why: 'A little harder', problem: { text: '5 × __ = 2 × 5. What number goes in the blank?', op: { t: 'missing', a: 5, total: 10 }, picture: { kind: 'array', rows: 2, cols: 5, obj: 'dot', turn: true } } },
      { why: 'Same math in a story', problem: { text: 'Ana puts 3 stickers on each of 4 pages. She has 12 stickers. Ben puts 4 stickers on each of 3 pages. How many stickers does Ben have?', op: { t: 'turn', a: 4, b: 3 }, picture: { kind: 'array', rows: 3, cols: 4, obj: 'sticker', turn: true } } },
    ],
  },

  // ── Topic 4 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m1-t4', title: 'Counting by 2s, 5s and 10s', skill: 'Skip counting is multiplying',
    bigIdea: 'When the groups are the same size, jump by that size, and each jump counts a whole group.',
    screens: [
      { title: 'Socks on the line', text: 'There are 6 pairs of socks on the line. Each pair has 2 socks. How many socks are there?',
        pictures: [{ kind: 'groups', groups: 6, each: 2, obj: 'sock' }] },
      { title: 'One by one is slow', text: 'You could count every sock, one at a time. But socks come in pairs. Is there a faster way? Yes.',
        beats: [
          { say: 'You could count every sock, one at a time.', pic: 0 },
          { say: 'But socks come in pairs. Is there a faster way? Yes.' },
        ],
        pictures: [{ kind: 'groups', groups: 6, each: 2, obj: 'sock', show: 'count' }] },
      { title: 'The big idea', text: 'When the groups are the same size, jump by that size, and each jump counts a whole group.',
        beats: [
          { say: 'When the groups are the same size, jump by that size, and each jump counts a whole group.', pic: 0 },
        ],
        pictures: [{ kind: 'groups', groups: 6, each: 2, obj: 'sock' }] },
      { title: 'Jump by 2s', text: 'Look at the number line. Each pair is one jump of 2. 2, 4, 6, 8, 10, 12.',
        beats: [
          { say: 'Look at the number line. Each pair is one jump of 2.', pic: 0 },
          { say: '2, 4, 6, 8, 10, 12.', pic: 1 },
        ],
        pictures: [{ kind: 'groups', groups: 6, each: 2, obj: 'sock' }, { kind: 'line', max: 12, step: 2, jumps: 6, motion: true }] },
      { title: 'How many jumps?', text: 'How many jumps did we make? Count them. 6 jumps of 2. And we landed on 12. So 6 × 2 = 12.',
        beats: [
          { say: 'How many jumps did we make? Count them. 6 jumps of 2.', pic: 0 },
          { say: 'And we landed on 12.' },
          { say: 'So 6 × 2 = 12.', pic: 1 },
        ],
        pictures: [{ kind: 'line', max: 12, step: 2, jumps: 6, show: 'count' }, { kind: 'eq', text: '6 × 2 = 12' }] },
      { title: 'Hands and bundles', text: '5s work the same way. Each hand is a jump of 5. 5, 10, 15. And bundles of ten jump by 10s. 10, 20, 30, 40.',
        beats: [
          { say: '5s work the same way. Each hand is a jump of 5. 5, 10, 15.', pic: 0 },
          { say: 'And bundles of ten jump by 10s. 10, 20, 30, 40.', pic: 1 },
        ],
        pictures: [{ kind: 'groups', groups: 3, each: 5, obj: 'finger', show: 'running' }, { kind: 'groups', groups: 4, each: 10, obj: 'straw', show: 'running' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. 4 hands means 4 jumps. Don't STOP at 15. Hold up a finger for each jump. 5, 10, 15, 20. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "4 hands means 4 jumps. Don't STOP at 15.", pic: 0 },
          { say: 'Hold up a finger for each jump. 5, 10, 15, 20.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '4 hands → 5, 10, 15', right: '4 hands → 5, 10, 15, 20' }] },
    ],
    turn: {
      text: '7 hands. How many fingers?', op: { t: 'mul', a: 7, b: 5 },
      picture: { kind: 'line', step: 5, jumps: 0 },
      prompt: 'Jump by 5s. Count one jump for each hand.',
      hint1: 'Count by 5s. Hold up one finger for each hand you count.',
      hint2: '5, 10, 15, 20, 25, 30 is 6 hands. Make one more jump.',
      twin: { text: '6 bundles of 10 straws. How many straws?', op: { t: 'mul', a: 6, b: 10 },
        picture: { kind: 'line', step: 10, jumps: 0 } },
    },
    won: { text: 'You jumped a whole group at a time. Counting by jumps is multiplying.', sticker: 'Skip counting by 5 = the 5 times table.' },
    twinWon: { text: 'You jumped a whole group at a time. Counting by jumps is multiplying.', sticker: 'Skip counting by 10 = the 10 times table.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '4 pairs of shoes. How many shoes?', op: { t: 'mul', a: 4, b: 2 }, picture: { kind: 'line', step: 2, jumps: 0 } } },
      { why: 'Same idea, new numbers', problem: { text: '5 bundles of 10 straws. How many straws?', op: { t: 'mul', a: 5, b: 10 }, picture: { kind: 'line', step: 10, jumps: 0 } } },
      { why: 'Still "jump by groups"', problem: { text: '8 hands. How many fingers?', op: { t: 'mul', a: 8, b: 5 }, picture: { kind: 'line', step: 5, jumps: 0 } } },
      { why: 'A little harder', problem: { text: '9 pairs of socks. How many socks?', op: { t: 'mul', a: 9, b: 2 }, picture: { kind: 'line', step: 2, jumps: 0 } } },
      { why: 'Same math in a story', problem: { text: 'A nickel is worth 5 cents. Mia has 6 nickels. How many cents does she have?', op: { t: 'mul', a: 6, b: 5 }, picture: { kind: 'line', step: 5, jumps: 0 } } },
    ],
  },

  // ── Topic 5 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m1-t5', title: 'Counting by 3s and 4s', skill: 'Skip counting with 3s and 4s',
    bigIdea: '3s and 4s work just like 2s and 5s, so add the same number every time you jump.',
    screens: [
      { title: 'Tricycles in the park', text: 'There are 4 tricycles. Each tricycle has 3 wheels. How many wheels are there?',
        pictures: [{ kind: 'groups', groups: 4, each: 3, obj: 'wheel' }] },
      { title: '3s are new', text: "You already count by 2s, 5s and 10s. Counting by 3s is new, so it doesn't come as easily yet. Can you do it the same way? Yes.",
        beats: [
          { say: 'You already count by 2s, 5s and 10s.', pic: 0 },
          { say: "Counting by 3s is new, so it doesn't come as easily yet." },
          { say: 'Can you do it the same way? Yes.' },
        ],
        pictures: [{ kind: 'groups', groups: 4, each: 3, obj: 'wheel' }] },
      { title: 'The big idea', text: '3s and 4s work just like 2s and 5s, so add the same number every time you jump.',
        beats: [
          { say: '3s and 4s work just like 2s and 5s, so add the same number every time you jump.', pic: 0 },
        ],
        pictures: [{ kind: 'groups', groups: 4, each: 3, obj: 'wheel' }] },
      { title: 'Jump by 3s', text: 'Each tricycle has 3 wheels, so each is a jump of 3. Three, six, nine, twelve. 4 jumps of 3 make 12.',
        beats: [
          { say: 'Each tricycle has 3 wheels, so each is a jump of 3.', pic: 0 },
          { say: 'Three, six, nine, twelve.', pic: 1 },
          { say: '4 jumps of 3 make 12.' },
        ],
        pictures: [{ kind: 'groups', groups: 4, each: 3, obj: 'wheel' }, { kind: 'line', max: 12, step: 3, jumps: 4, motion: true }] },
      { title: 'Now cars', text: 'A car has 4 wheels. Jump by 4s. Four, eight, twelve. 3 jumps of 4 make 12.',
        beats: [
          { say: 'A car has 4 wheels. Jump by 4s.', pic: 0 },
          { say: 'Four, eight, twelve.', pic: 1 },
          { say: '3 jumps of 4 make 12.' },
        ],
        pictures: [{ kind: 'groups', groups: 3, each: 4, obj: 'wheel' }, { kind: 'line', max: 12, step: 4, jumps: 3, motion: true }] },
      { title: 'Two facts', text: 'Now write them down. 4 tricycles have 12 wheels, so 4 × 3 = 12. 3 cars have 12 wheels, so 3 × 4 = 12.',
        beats: [
          { say: 'Now write them down.' },
          { say: '4 tricycles have 12 wheels, so 4 × 3 = 12.', pic: 0 },
          { say: '3 cars have 12 wheels, so 3 × 4 = 12.', pic: 1 },
        ],
        pictures: [{ kind: 'eq', text: '4 × 3 = 12' }, { kind: 'eq', text: '3 × 4 = 12' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Counting by 3s does not mean ADD 1 each time. That gives 3, 4, 5, 6. Every jump adds a whole group of 3, so it goes 3, 6, 9, 12. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: 'Counting by 3s does not mean ADD 1 each time.', pic: 0 },
          { say: 'That gives 3, 4, 5, 6. Every jump adds a whole group of 3, so it goes 3, 6, 9, 12.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '3, 4, 5, 6', right: '3, 6, 9, 12' }] },
    ],
    turn: {
      text: '5 cars. Each car has 4 wheels. How many wheels?', op: { t: 'mul', a: 5, b: 4 },
      picture: { kind: 'line', step: 4, jumps: 0 },
      prompt: 'Jump by 4s. Count one jump for each car.',
      hint1: 'Each car has 4 wheels. Jump by 4s, one jump for each car.',
      hint2: '4, 8, 12, 16 is 4 cars. Make one more jump.',
      twin: { text: '6 tricycles. Each tricycle has 3 wheels. How many wheels?', op: { t: 'mul', a: 6, b: 3 },
        picture: { kind: 'line', step: 3, jumps: 0 } },
    },
    won: { text: 'You added the same group every jump. That is the whole trick.', sticker: 'Counting by 3s and 4s = the 3 and 4 times tables.' },
    twinWon: { text: 'You added the same group every jump. That is the whole trick.', sticker: 'Counting by 3s = the 3 times table.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '3 tricycles. How many wheels?', op: { t: 'mul', a: 3, b: 3 }, picture: { kind: 'line', step: 3, jumps: 0 } } },
      { why: 'Same idea, new numbers', problem: { text: '4 cars. How many wheels?', op: { t: 'mul', a: 4, b: 4 }, picture: { kind: 'line', step: 4, jumps: 0 } } },
      { why: 'Still "jump by 3s or 4s"', problem: { text: '6 boxes, 4 crayons in each. How many crayons?', op: { t: 'mul', a: 6, b: 4 }, picture: { kind: 'line', step: 4, jumps: 0 } } },
      { why: 'A little harder', problem: { text: '7 × 3 = ?', op: { t: 'mul', a: 7, b: 3 }, picture: { kind: 'line', step: 3, jumps: 0 } } },
      { why: 'Same math in a story', problem: { text: 'A table has 4 legs. How many legs do 5 tables have?', op: { t: 'mul', a: 5, b: 4 }, picture: { kind: 'line', step: 4, jumps: 0 } } },
    ],
  },

  // ── Topic 6 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m1-t6', title: 'Share the apples fairly', skill: 'Division: how many in each group',
    bigIdea: 'Division shares a total into equal groups, and here we know how many groups, so we find how many in each.',
    screens: [
      { title: 'Sharing apples', text: '12 apples are shared fairly by 3 friends. How many apples does each friend get?',
        pictures: [{ kind: 'share', total: 12, groups: 3, state: 'start', obj: 'apple' }] },
      { title: 'Fair means the same', text: "What does fair mean here? If one friend gets 6 and another gets 2, that isn't fair. Every friend must get the same number.",
        beats: [
          { say: 'What does fair mean here?' },
          { say: "If one friend gets 6 and another gets 2, that isn't fair.", pic: 0 },
          { say: 'Every friend must get the same number.' },
        ],
        pictures: [{ kind: 'share', total: 12, groups: 3, state: 'uneven', obj: 'apple' }] },
      { title: 'The big idea', text: 'Division shares a total into equal groups, and here we know how many groups, so we find how many in each.',
        beats: [
          { say: 'Division shares a total into equal groups, and here we know how many groups, so we find how many in each.', pic: 0 },
        ],
        pictures: [{ kind: 'share', total: 12, groups: 3, state: 'start', obj: 'apple' }] },
      { title: 'One for you, one for you …', text: 'Give one apple to each friend. That is one round. Then go round again. Now each friend has 2.',
        beats: [
          { say: 'Give one apple to each friend. That is one round.', pic: 0 },
          { say: 'Then go round again. Now each friend has 2.' },
        ],
        pictures: [{ kind: 'share', total: 12, groups: 3, state: 'deal', obj: 'apple', motion: true }] },
      { title: 'Keep going', text: "Keep going, round and round, until the basket is empty. Now count the first friend's apples. One, two, three, four. Each friend has 4 apples, and it is fair.",
        beats: [
          { say: 'Keep going, round and round, until the basket is empty.', pic: 0 },
          { say: "Now count the first friend's apples. One, two, three, four." },
          { say: 'Each friend has 4 apples, and it is fair.' },
        ],
        pictures: [{ kind: 'share', total: 12, groups: 3, state: 'done', obj: 'apple' }] },
      { title: '12 shared by 3', text: '12 shared by 3 friends is 4 each. We write 12 ÷ 3 = 4. The first number is the total, then the friends, then how many each.',
        beats: [
          { say: '12 shared by 3 friends is 4 each.', pic: 0 },
          { say: 'We write 12 ÷ 3 = 4.', pic: 1 },
          { say: 'The first number is the total, then the friends, then how many each.' },
        ],
        pictures: [{ kind: 'share', total: 12, groups: 3, state: 'done', obj: 'apple' }, { kind: 'eq', text: '12 ÷ 3 = 4' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. Don't FLIP it to 3 ÷ 12. You are sharing 12 apples, not 3, so the total goes first. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "Don't FLIP it to 3 ÷ 12.", pic: 0 },
          { say: 'You are sharing 12 apples, not 3, so the total goes first.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '3 ÷ 12', right: '12 ÷ 3 = 4' }] },
    ],
    turn: {
      text: '10 cookies are shared fairly by 2 friends. How many does each friend get?', op: { t: 'div', total: 10, by: 2, mode: 'share' },
      picture: { kind: 'share', total: 10, groups: 2, state: 'start', obj: 'cookie' },
      prompt: 'Share them out one at a time until none are left.',
      hint1: 'Give one cookie to each friend. Then go round again until none are left.',
      hint2: 'After 4 rounds, each plate has 4 cookies and 2 are left. Give one more to each friend.',
      twin: { text: '15 stickers are shared fairly by 5 friends. How many does each friend get?', op: { t: 'div', total: 15, by: 5, mode: 'share' },
        picture: { kind: 'share', total: 15, groups: 5, state: 'start', obj: 'sticker' } },
    },
    won: { text: 'You shared the total fairly. That is division.', sticker: '÷ means share into equal groups.' },
    twinWon: { text: 'You shared the total fairly. That is division.', sticker: '÷ means share into equal groups.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '8 apples shared by 2 friends. How many each?', op: { t: 'div', total: 8, by: 2, mode: 'share' }, picture: { kind: 'share', total: 8, groups: 2, state: 'start', obj: 'apple' } } },
      { why: 'Same idea, new numbers', problem: { text: '20 pencils shared by 4 kids. How many each?', op: { t: 'div', total: 20, by: 4, mode: 'share' }, picture: { kind: 'share', total: 20, groups: 4, state: 'start', obj: 'crayon' } } },
      { why: 'Still "share fairly"', problem: { text: '30 crayons shared into 10 boxes. How many in each box?', op: { t: 'div', total: 30, by: 10, mode: 'share' }, picture: { kind: 'share', total: 30, groups: 10, state: 'start', obj: 'crayon' } } },
      { why: 'A little harder', problem: { text: '18 grapes shared by 3 friends. How many each?', op: { t: 'div', total: 18, by: 3, mode: 'share' }, picture: { kind: 'share', total: 18, groups: 3, state: 'start', obj: 'dot' } } },
      { why: 'Same math in a story', problem: { text: 'Lea has 20 beads. She puts the same number on 5 bracelets. How many beads are on each bracelet?', op: { t: 'div', total: 20, by: 5, mode: 'share' }, picture: { kind: 'share', total: 20, groups: 5, state: 'start', obj: 'dot' } } },
    ],
  },

  // ── Topic 7 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m1-t7', title: 'How many bags can we fill?', skill: 'Division: how many groups',
    bigIdea: 'Division can also mean: how many groups of this size can we make?',
    screens: [
      { title: 'Filling bags', text: 'There are 12 apples. We put 3 apples in each bag. How many bags can we fill?',
        pictures: [{ kind: 'rings', total: 12, size: 3, obj: 'apple', state: 'start' }] },
      { title: "This time it's different", text: 'When we shared apples, we knew how many friends. This time we know how many go in each bag. So what is missing? The number of bags.',
        beats: [
          { say: 'When we shared apples, we knew how many friends.' },
          { say: 'This time we know how many go in each bag.', pic: 0 },
          { say: 'So what is missing? The number of bags.' },
        ],
        pictures: [{ kind: 'rings', total: 12, size: 3, obj: 'apple', state: 'one' }] },
      { title: 'The big idea', text: 'Division can also mean: how many groups of this size can we make?',
        beats: [
          { say: 'Division can also mean: how many groups of this size can we make?', pic: 0 },
        ],
        pictures: [{ kind: 'rings', total: 12, size: 3, obj: 'apple', state: 'start' }] },
      { title: 'Fill one bag', text: 'Take 3 apples and put them in a bag. That is one bag. 9 apples are left.',
        beats: [
          { say: 'Take 3 apples and put them in a bag.', pic: 0 },
          { say: 'That is one bag. 9 apples are left.' },
        ],
        pictures: [{ kind: 'rings', total: 12, size: 3, obj: 'apple', state: 'one', motion: true }] },
      { title: 'Keep filling', text: 'Keep making bags of 3. Two bags, three bags, four bags. Now no apples are left.',
        beats: [
          { say: 'Keep making bags of 3.', pic: 0 },
          { say: 'Two bags, three bags, four bags.' },
          { say: 'Now no apples are left.' },
        ],
        pictures: [{ kind: 'rings', total: 12, size: 3, obj: 'apple', state: 'all', motion: true }] },
      { title: 'How many bags?', text: 'Count the bags. We filled 4 bags. We write 12 ÷ 3 = 4. It works, because 4 bags of 3 make 12.',
        beats: [
          { say: 'Count the bags. We filled 4 bags.', pic: 0 },
          { say: 'We write 12 ÷ 3 = 4.', pic: 1 },
          { say: 'It works, because 4 bags of 3 make 12.' },
        ],
        pictures: [{ kind: 'rings', total: 12, size: 3, obj: 'apple', state: 'all' }, { kind: 'eq', text: '12 ÷ 3 = 4' }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. The answer is NOT the number in each bag. We already know that is 3. The question is how many bags, and that is 4. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: 'The answer is NOT the number in each bag.', pic: 0 },
          { say: 'We already know that is 3. The question is how many bags, and that is 4.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '3 bags', right: '4 bags' }] },
    ],
    turn: {
      text: '15 stickers. 5 stickers go in each pack. How many packs?', op: { t: 'div', total: 15, by: 5, mode: 'group' },
      picture: { kind: 'rings', total: 15, size: 5, obj: 'sticker', state: 'start' },
      prompt: 'Make packs of 5 until none are left. Then count the packs.',
      hint1: 'Ring 5 stickers to make one pack. Keep going until none are left.',
      hint2: '2 packs of 5 use 10 stickers. 5 are left. That makes one more pack.',
      twin: { text: '20 wheels. 4 wheels go on each car. How many cars?', op: { t: 'div', total: 20, by: 4, mode: 'group' },
        picture: { kind: 'rings', total: 20, size: 4, obj: 'wheel', state: 'start' } },
    },
    won: { text: 'You made groups of the same size and counted them. Check it: 3 packs of 5 is 15.', sticker: 'Division also means: how many groups?' },
    twinWon: { text: 'You made groups of the same size and counted them. Check it: 5 cars with 4 wheels each is 20.', sticker: 'Division also means: how many groups?' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '10 apples, 2 in each bag. How many bags?', op: { t: 'div', total: 10, by: 2, mode: 'group' }, picture: { kind: 'rings', total: 10, size: 2, obj: 'apple', state: 'start' } } },
      { why: 'Same idea, new numbers', problem: { text: '20 pencils, 10 in each box. How many boxes?', op: { t: 'div', total: 20, by: 10, mode: 'group' }, picture: { kind: 'rings', total: 20, size: 10, obj: 'crayon', state: 'start' } } },
      { why: 'Still "how many groups"', problem: { text: '12 wheels, 4 on each car. How many cars?', op: { t: 'div', total: 12, by: 4, mode: 'group' }, picture: { kind: 'rings', total: 12, size: 4, obj: 'wheel', state: 'start' } } },
      { why: 'A little harder', problem: { text: '18 flowers, 3 in each vase. How many vases?', op: { t: 'div', total: 18, by: 3, mode: 'group' }, picture: { kind: 'rings', total: 18, size: 3, obj: 'plant', state: 'start' } } },
      { why: 'Same math in a story', problem: { text: '25 children are at a party. 5 children sit at each table. How many tables are needed?', op: { t: 'div', total: 25, by: 5, mode: 'group' }, picture: { kind: 'rings', total: 25, size: 5, obj: 'dot', state: 'start' } } },
    ],
  },

  // ── Topic 8 ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'g3m1-t8', title: 'The missing number', skill: 'Multiplication and division are partners',
    bigIdea: 'Multiplication and division are partners, so a times fact you know can find a missing number.',
    screens: [
      { title: 'Setting out chairs', text: '20 chairs are set out in 4 equal rows. How many chairs go in each row?',
        pictures: [{ kind: 'scatter', n: 20, obj: 'chair' }] },
      { title: 'A number is missing', text: 'We know there are 4 rows. We know there are 20 chairs. So which number is missing? The number in each row.',
        beats: [
          { say: 'We know there are 4 rows. We know there are 20 chairs.' },
          { say: 'So which number is missing? The number in each row.', pic: 0 },
        ],
        pictures: [{ kind: 'eq', text: '4 × ? = 20' }] },
      { title: 'The big idea', text: 'Multiplication and division are partners, so a times fact you know can find a missing number.',
        beats: [
          { say: 'Multiplication and division are partners, so a times fact you know can find a missing number.', pic: 0 },
        ],
        pictures: [{ kind: 'scatter', n: 20, obj: 'chair' }] },
      { title: 'Count by 4s', text: 'Count by 4s until you reach 20. Four, eight, twelve, sixteen, twenty. That is 5 jumps.',
        beats: [
          { say: 'Count by 4s until you reach 20.', pic: 0 },
          { say: 'Four, eight, twelve, sixteen, twenty.' },
          { say: 'That is 5 jumps.' },
        ],
        pictures: [{ kind: 'line', max: 20, step: 4, jumps: 5, show: 'count', motion: true }] },
      { title: 'The missing number is 5', text: 'Put the chairs in 4 rows, 5 in each row. 4 rows of 5 make 20. So 4 × 5 = 20, and the missing number is 5.',
        beats: [
          { say: 'Put the chairs in 4 rows, 5 in each row.', pic: 0 },
          { say: '4 rows of 5 make 20. So 4 × 5 = 20, and the missing number is 5.', pic: 1 },
        ],
        pictures: [{ kind: 'array', rows: 4, cols: 5, obj: 'chair' }, { kind: 'eq', text: '4 × 5 = 20' }] },
      { title: 'One picture, four facts', text: 'The same three numbers, 4, 5 and 20, make four facts. 4 × 5 = 20, and 5 × 4 = 20. 20 ÷ 4 = 5, and 20 ÷ 5 = 4.',
        beats: [
          { say: 'The same three numbers, 4, 5 and 20, make four facts.', pic: 0 },
          { say: '4 × 5 = 20, and 5 × 4 = 20.' },
          { say: '20 ÷ 4 = 5, and 20 ÷ 5 = 4.' },
        ],
        pictures: [{ kind: 'triangle', total: 20, a: 4, b: 5, facts: true }] },
      { title: 'One thing not to do', text: "Here's the part people mix up. When you divide, don't put the 20 LAST. The biggest number is the total, and it comes first, like 20 ÷ 5 = 4. Okay. Your turn.",
        beats: [
          { say: "Here's the part people mix up." },
          { say: "When you divide, don't put the 20 LAST.", pic: 0 },
          { say: 'The biggest number is the total, and it comes first, like 20 ÷ 5 = 4.' },
          { say: 'Okay. Your turn.' },
        ],
        pictures: [{ kind: 'cards', wrong: '5 ÷ 20 = 4', right: '20 ÷ 5 = 4' }] },
    ],
    turn: {
      text: '3 × ? = 30', op: { t: 'missing', a: 3, total: 30 },
      picture: { kind: 'triangle', total: 30, a: 3, b: null },
      prompt: 'Use a times fact you know to find the missing number.',
      hint1: '3 groups of what number make 30?',
      hint2: 'Count by 10s three times: 10, 20, 30. What did you count by?',
      twin: { text: '5 × ? = 15', op: { t: 'missing', a: 5, total: 15 },
        picture: { kind: 'triangle', total: 15, a: 5, b: null } },
    },
    won: { text: 'You used a times fact to find the missing number. That is the whole trick.', sticker: '3 numbers, 4 facts = a fact family.' },
    twinWon: { text: 'You used a times fact to find the missing number. That is the whole trick.', sticker: 'Numbers that go together, like 5, 3 and 15 = a fact family.' },
    practice: [
      { why: 'Almost a copy of the lesson', problem: { text: '2 × ? = 10', op: { t: 'missing', a: 2, total: 10 }, picture: { kind: 'triangle', total: 10, a: 2, b: null } } },
      { why: 'Same idea, new numbers', problem: { text: '4 × ? = 12', op: { t: 'missing', a: 4, total: 12 }, picture: { kind: 'triangle', total: 12, a: 4, b: null } } },
      { why: 'Still "use the partner fact"', problem: { text: '40 ÷ 10 = ?  (think: 10 × ? = 40)', op: { t: 'missing', a: 10, total: 40 }, picture: { kind: 'triangle', total: 40, a: 10, b: null } } },
      { why: 'A little harder', problem: { text: '? × 5 = 35', op: { t: 'missing', a: 5, total: 35 }, picture: { kind: 'triangle', total: 35, a: 5, b: null } } },
      { why: 'Same math in a story', problem: { text: 'Tom has 18 cookies. He puts 3 cookies in each bag. How many bags? Think: 3 × ? = 18.', op: { t: 'missing', a: 3, total: 18 }, picture: { kind: 'triangle', total: 18, a: 3, b: null } } },
    ],
  },
]

attachChalk(GRADE3_MODULE1, G3M1_CHALK)
