/**
 * The founder-approved wording of Grade 3 · Module 1 (approved 2026-09-13), held word for word against the app by
 * lessonsGrade3Module1.test.ts. Written out here BY HAND ON PURPOSE: it is the intent, independent of the lesson data.
 * Do not derive it from src/features/lessons/grade3Module1.ts — a fixture read from the code under test passes on any
 * change. Changing a line of a lesson means changing it here too; the red test in between is the reminder that the
 * wording is an approved decision. Extracted 2026-09-28 from the approved scripts document, which is in history:
 * `git show fbf193280:docs/new-flow/grade3-module1-scripts.md`.
 */
export const G3M1_APPROVED: [field: string, text: string][][] = [
  // Topic 1
  [
    ["Title", "Cookies on plates"],
    ["Text", "There are 4 plates. Each plate has 3 cookies. How many cookies are there?"],
    ["Title", "Counting one by one is slow"],
    ["Text", "You could count every cookie. That works. But it's slow, and it's easy to lose your place. Is there a faster way? Yes. Look at the plates."],
    ["Title", "The big idea"],
    ["Text", "When every group has the same number, you can count a whole group at a time."],
    ["Title", "How many groups? How many in each?"],
    ["Text", "Look. Each plate is a group. There are 4 plates, so there are 4 groups. And each plate has 3 cookies. That's 3 in each group."],
    ["Title", "Count by 3s"],
    ["Text", "Now count one whole plate at a time. 3, 6, 9, 12. So there are 12 cookies."],
    ["Title", "4 groups of 3"],
    ["Text", "4 groups of 3 make 12. We write that as 4 × 3 = 12. The first number is the groups. The second is how many in each."],
    ["Title", "One thing not to do"],
    ["Text", "Here's the part people mix up. 4 × 3 does not mean ADD 4 and 3. That gives 7, just one plate and 4 more cookies. 4 × 3 is 4 whole plates of 3. Okay. Your turn."],
    ["Title", "Now you try"],
    ["Prompt", "Find how many groups and how many in each. Then count by groups."],
    ["Hint after 1 miss", "How many plates are there? How many cookies are on each plate?"],
    ["Hint after 2 misses", "There are 3 groups of 5. Count by 5s, one plate at a time: 5, 10 …"],
    ["Title", "You got it"],
    ["Text", "You counted by groups instead of one by one. That is multiplication."],
    ["Math word sticker", "Equal groups = multiplication. 3 × 5 means 3 groups of 5."],
    ["Text after the twin", "You counted by groups instead of one by one. That is multiplication."],
    ["Math word sticker after the twin", "Equal groups = multiplication. 5 × 2 means 5 groups of 2."],
  ],
  // Topic 2
  [
    ["Title", "Chairs in a hall"],
    ["Text", "The chairs are set out in 3 rows. Each row has 5 chairs. How many chairs are there?"],
    ["Title", "A jumble is hard to count"],
    ["Text", "When chairs are jumbled, you have to count every one. And it's easy to miss some. What if they stand in neat rows? Then it's much faster."],
    ["Title", "The big idea"],
    ["Text", "When every row has the same number, count the rows, count one row, then multiply."],
    ["Title", "How many rows?"],
    ["Text", "Look. Rows go across, from left to right. Count them. 1, 2, 3. There are 3 rows."],
    ["Title", "How many in a row?"],
    ["Text", "Every row is the same, so you only need to count one. 1, 2, 3, 4, 5. Each row has 5 chairs."],
    ["Title", "3 rows of 5"],
    ["Text", "Now count one whole row at a time. 5, 10, 15. 3 rows of 5 is 15. We write it as 3 × 5 = 15."],
    ["Title", "One thing not to do"],
    ["Text", "Here's the part people mix up. If one row is missing a chair, it is NOT 3 × 5 any more. Every row must have the same number. Count each row to check. Okay. Your turn."],
    ["Title", "Now you try"],
    ["Prompt", "Count the rows. Count one row. Then multiply."],
    ["Hint after 1 miss", "How many rows are there? How many plants are in one row?"],
    ["Hint after 2 misses", "There are 4 rows of 3. Count by 3s, one row at a time: 3, 6 …"],
    ["Title", "You got it"],
    ["Text", "You counted the rows and one row, then multiplied. That is the whole trick."],
    ["Math word sticker", "Equal rows = an array."],
    ["Text after the twin", "You counted the rows and one row, then multiplied. That is the whole trick."],
    ["Math word sticker after the twin", "Equal rows = an array."],
  ],
  // Topic 3
  [
    ["Title", "A tray of muffins"],
    ["Text", "This tray has 2 rows of 5 muffins. What happens if we turn the tray around?"],
    ["Title", "It looks like a new problem"],
    ["Text", "Turn the tray, and now there are 5 rows of 2. It looks different. So did the number of muffins change?"],
    ["Title", "The big idea"],
    ["Text", "Turning the rows around does not change how many there are, so 2 × 5 and 5 × 2 make the same total."],
    ["Title", "2 rows of 5"],
    ["Text", "First, the tray as it started. 2 rows of 5. Count by rows. 5, 10. So 2 × 5 = 10."],
    ["Title", "Turn the tray"],
    ["Text", "Now watch the tray turn. Does any muffin fall off? No. Is any muffin added? No. Every muffin just moves to a new spot."],
    ["Title", "5 rows of 2"],
    ["Text", "Now count the turned tray by rows. 2, 4, 6, 8, 10. So 5 × 2 = 10. Same muffins, same total."],
    ["Title", "One thing not to do"],
    ["Text", "Here's the part people mix up. This turn-around trick works for times. It does NOT work for take away. 5 − 2 leaves 3. But 2 − 5 does not leave 3, so they are not the same. Okay. Your turn."],
    ["Title", "Now you try"],
    ["Prompt", "Turn the rows around. Does the total change?"],
    ["Hint after 1 miss", "Tap turn. Were any dots added or taken away?"],
    ["Hint after 2 misses", "10 × 4 is the same dots turned around, so it has the same total as 4 × 10."],
    ["Title", "You got it"],
    ["Text", "You turned the rows around and the total stayed the same. That is the whole trick."],
    ["Math word sticker", "Turn-around facts = the commutative property."],
    ["Text after the twin", "You turned the rows around and the total stayed the same. That is the whole trick."],
    ["Math word sticker after the twin", "Turn-around facts = the commutative property."],
  ],
  // Topic 4
  [
    ["Title", "Socks on the line"],
    ["Text", "There are 6 pairs of socks on the line. Each pair has 2 socks. How many socks are there?"],
    ["Title", "One by one is slow"],
    ["Text", "You could count every sock, one at a time. But socks come in pairs. Is there a faster way? Yes."],
    ["Title", "The big idea"],
    ["Text", "When the groups are the same size, jump by that size, and each jump counts a whole group."],
    ["Title", "Jump by 2s"],
    ["Text", "Look at the number line. Each pair is one jump of 2. 2, 4, 6, 8, 10, 12."],
    ["Title", "How many jumps?"],
    ["Text", "How many jumps did we make? Count them. 6 jumps of 2. And we landed on 12. So 6 × 2 = 12."],
    ["Title", "Hands and bundles"],
    ["Text", "5s work the same way. Each hand is a jump of 5. 5, 10, 15. And bundles of ten jump by 10s. 10, 20, 30, 40."],
    ["Title", "One thing not to do"],
    ["Text", "Here's the part people mix up. 4 hands means 4 jumps. Don't STOP at 15. Hold up a finger for each jump. 5, 10, 15, 20. Okay. Your turn."],
    ["Title", "Now you try"],
    ["Prompt", "Jump by 5s. Count one jump for each hand."],
    ["Hint after 1 miss", "Count by 5s. Hold up one finger for each hand you count."],
    ["Hint after 2 misses", "5, 10, 15, 20, 25, 30 is 6 hands. Make one more jump."],
    ["Title", "You got it"],
    ["Text", "You jumped a whole group at a time. Counting by jumps is multiplying."],
    ["Math word sticker", "Skip counting by 5 = the 5 times table."],
    ["Text after the twin", "You jumped a whole group at a time. Counting by jumps is multiplying."],
    ["Math word sticker after the twin", "Skip counting by 10 = the 10 times table."],
  ],
  // Topic 5
  [
    ["Title", "Tricycles in the park"],
    ["Text", "There are 4 tricycles. Each tricycle has 3 wheels. How many wheels are there?"],
    ["Title", "3s are new"],
    ["Text", "You already count by 2s, 5s and 10s. Counting by 3s is new, so it doesn't come as easily yet. Can you do it the same way? Yes."],
    ["Title", "The big idea"],
    ["Text", "3s and 4s work just like 2s and 5s, so add the same number every time you jump."],
    ["Title", "Jump by 3s"],
    ["Text", "Each tricycle has 3 wheels, so each is a jump of 3. Three, six, nine, twelve. 4 jumps of 3 make 12."],
    ["Title", "Now cars"],
    ["Text", "A car has 4 wheels. Jump by 4s. Four, eight, twelve. 3 jumps of 4 make 12."],
    ["Title", "Two facts"],
    ["Text", "Now write them down. 4 tricycles have 12 wheels, so 4 × 3 = 12. 3 cars have 12 wheels, so 3 × 4 = 12."],
    ["Title", "One thing not to do"],
    ["Text", "Here's the part people mix up. Counting by 3s does not mean ADD 1 each time. That gives 3, 4, 5, 6. Every jump adds a whole group of 3, so it goes 3, 6, 9, 12. Okay. Your turn."],
    ["Title", "Now you try"],
    ["Prompt", "Jump by 4s. Count one jump for each car."],
    ["Hint after 1 miss", "Each car has 4 wheels. Jump by 4s, one jump for each car."],
    ["Hint after 2 misses", "4, 8, 12, 16 is 4 cars. Make one more jump."],
    ["Title", "You got it"],
    ["Text", "You added the same group every jump. That is the whole trick."],
    ["Math word sticker", "Counting by 3s and 4s = the 3 and 4 times tables."],
    ["Text after the twin", "You added the same group every jump. That is the whole trick."],
    ["Math word sticker after the twin", "Counting by 3s = the 3 times table."],
  ],
  // Topic 6
  [
    ["Title", "Sharing apples"],
    ["Text", "12 apples are shared fairly by 3 friends. How many apples does each friend get?"],
    ["Title", "Fair means the same"],
    ["Text", "What does fair mean here? If one friend gets 6 and another gets 2, that isn't fair. Every friend must get the same number."],
    ["Title", "The big idea"],
    ["Text", "Division shares a total into equal groups, and here we know how many groups, so we find how many in each."],
    ["Title", "One for you, one for you …"],
    ["Text", "Give one apple to each friend. That is one round. Then go round again. Now each friend has 2."],
    ["Title", "Keep going"],
    ["Text", "Keep going, round and round, until the basket is empty. Now count the first friend's apples. One, two, three, four. Each friend has 4 apples, and it is fair."],
    ["Title", "12 shared by 3"],
    ["Text", "12 shared by 3 friends is 4 each. We write 12 ÷ 3 = 4. The first number is the total, then the friends, then how many each."],
    ["Title", "One thing not to do"],
    ["Text", "Here's the part people mix up. Don't FLIP it to 3 ÷ 12. You are sharing 12 apples, not 3, so the total goes first. Okay. Your turn."],
    ["Title", "Now you try"],
    ["Prompt", "Share them out one at a time until none are left."],
    ["Hint after 1 miss", "Give one cookie to each friend. Then go round again until none are left."],
    ["Hint after 2 misses", "After 4 rounds, each plate has 4 cookies and 2 are left. Give one more to each friend."],
    ["Title", "You got it"],
    ["Text", "You shared the total fairly. That is division."],
    ["Math word sticker", "÷ means share into equal groups."],
    ["Text after the twin", "You shared the total fairly. That is division."],
    ["Math word sticker after the twin", "÷ means share into equal groups."],
  ],
  // Topic 7
  [
    ["Title", "Filling bags"],
    ["Text", "There are 12 apples. We put 3 apples in each bag. How many bags can we fill?"],
    ["Title", "This time it's different"],
    ["Text", "When we shared apples, we knew how many friends. This time we know how many go in each bag. So what is missing? The number of bags."],
    ["Title", "The big idea"],
    ["Text", "Division can also mean: how many groups of this size can we make?"],
    ["Title", "Fill one bag"],
    ["Text", "Take 3 apples and put them in a bag. That is one bag. 9 apples are left."],
    ["Title", "Keep filling"],
    ["Text", "Keep making bags of 3. Two bags, three bags, four bags. Now no apples are left."],
    ["Title", "How many bags?"],
    ["Text", "Count the bags. We filled 4 bags. We write 12 ÷ 3 = 4. It works, because 4 bags of 3 make 12."],
    ["Title", "One thing not to do"],
    ["Text", "Here's the part people mix up. The answer is NOT the number in each bag. We already know that is 3. The question is how many bags, and that is 4. Okay. Your turn."],
    ["Title", "Now you try"],
    ["Prompt", "Make packs of 5 until none are left. Then count the packs."],
    ["Hint after 1 miss", "Ring 5 stickers to make one pack. Keep going until none are left."],
    ["Hint after 2 misses", "2 packs of 5 use 10 stickers. 5 are left. That makes one more pack."],
    ["Title", "You got it"],
    ["Text", "You made groups of the same size and counted them. Check it: 3 packs of 5 is 15."],
    ["Math word sticker", "Division also means: how many groups?"],
    ["Text after the twin", "You made groups of the same size and counted them. Check it: 5 cars with 4 wheels each is 20."],
    ["Math word sticker after the twin", "Division also means: how many groups?"],
  ],
  // Topic 8
  [
    ["Title", "Setting out chairs"],
    ["Text", "20 chairs are set out in 4 equal rows. How many chairs go in each row?"],
    ["Title", "A number is missing"],
    ["Text", "We know there are 4 rows. We know there are 20 chairs. So which number is missing? The number in each row."],
    ["Title", "The big idea"],
    ["Text", "Multiplication and division are partners, so a times fact you know can find a missing number."],
    ["Title", "Count by 4s"],
    ["Text", "Count by 4s until you reach 20. Four, eight, twelve, sixteen, twenty. That is 5 jumps."],
    ["Title", "The missing number is 5"],
    ["Text", "Put the chairs in 4 rows, 5 in each row. 4 rows of 5 make 20. So 4 × 5 = 20, and the missing number is 5."],
    ["Title", "One picture, four facts"],
    ["Text", "The same three numbers, 4, 5 and 20, make four facts. 4 × 5 = 20, and 5 × 4 = 20. 20 ÷ 4 = 5, and 20 ÷ 5 = 4."],
    ["Title", "One thing not to do"],
    ["Text", "Here's the part people mix up. When you divide, don't put the 20 LAST. The biggest number is the total, and it comes first, like 20 ÷ 5 = 4. Okay. Your turn."],
    ["Title", "Now you try"],
    ["Prompt", "Use a times fact you know to find the missing number."],
    ["Hint after 1 miss", "3 groups of what number make 30?"],
    ["Hint after 2 misses", "Count by 10s three times: 10, 20, 30. What did you count by?"],
    ["Title", "You got it"],
    ["Text", "You used a times fact to find the missing number. That is the whole trick."],
    ["Math word sticker", "3 numbers, 4 facts = a fact family."],
    ["Text after the twin", "You used a times fact to find the missing number. That is the whole trick."],
    ["Math word sticker after the twin", "Numbers that go together, like 5, 3 and 15 = a fact family."],
  ],
]
