-- ============================================================================
-- PUBLIC SCHEMA — SECURITY SURFACE BASELINE  (generated snapshot; do NOT re-apply)
--
-- WHY THIS FILE EXISTS: the base tables + their RLS were created in the Supabase
-- dashboard, not in supabase/migrations/, so they were invisible to code review.
-- That blind spot is exactly where V1 (the forged-invite escalation) hid. This is a
-- committed, diffable snapshot of the security-relevant surface — RLS, policies,
-- function security posture, grants, triggers — so drift is caught in review.
--
-- REGENERATE + DIFF: run the query in docs/security.md against prod and overwrite
-- this file; a non-empty `git diff` means the live security posture changed.
-- Last FULLY generated: 2026-08-17 (post V13–V19 audit). ⚠️ PARTIALLY HAND-UPDATED 2026-08-24 for
-- the leads lockdown and the four new retention/data-rights functions below — a full regeneration is
-- owed and the diff should be reviewed when it happens. Covers auth_events, diagnostic_leads,
-- error_events + the V12 column-grant and the V19 EXECUTE revokes, none of which existed at the
-- 2026-07-03 snapshot — so the drift check had been comparing against a 6-week-stale baseline.
-- ============================================================================

-- ==== TABLES: RLS status — every data table has rls=t AND >=1 policy ====
--   auth_events                rls=t  policies=1   (V-audit 2026-07-21: INSERT-only, own rows; no read)
--   chapters                   rls=t  policies=1   (public catalog: SELECT using(true) — intentional)
--   diagnostic_items           rls=t  policies=1
--   diagnostic_leads           rls=t  policies=1   ✅ CLOSED 2026-08-24. anon no longer holds the
--                                                  INSERT grant and is gone from the ACL entirely
--                                                  (verified: anon → POST /rest/v1/diagnostic_leads
--                                                  returns 401 / 42501; was 201). The policy is
--                                                  `authenticated` only and checks email SHAPE.
--                                                  ⚠️ The shape check was briefly LOST: the
--                                                  now-applied leads_server_only was written
--                                                  2026-08-16, before V13 added it, so applying it
--                                                  recreated the length-only policy. rls_regression
--                                                  A9b caught it; restored by
--                                                  20260823222545_leads_insert_restore_shape_check.
--                                                  Still no SELECT — not readable through the API.
--   diagnostic_plan_progress   rls=t  policies=1
--   diagnostic_plans           rls=t  policies=1
--   diagnostic_rechecks        rls=t  policies=1
--   diagnostic_sessions        rls=t  policies=1
--   error_events               rls=t  policies=0   INTENTIONAL: RLS on with ZERO policies = deny-all,
--                                                  service-role only. Advisor reports this as INFO
--                                                  rls_enabled_no_policy — that is the design.
--   grade_chapters             rls=t  policies=3
--   grades                     rls=t  policies=4
--   learner_access             rls=t  policies=3   (SELECT/INSERT/DELETE — DELETE added V11)
--   learner_events             rls=t  policies=2
--   learner_invites            rls=t  policies=3   (sender INSERT now requires learner ownership — V1)
--   learner_progress           rls=t  policies=1
--   learner_state              rls=t  policies=1
--   learner_stats              rls=t  policies=1
--   learners                   rls=t  policies=4
--   profiles                   rls=t  policies=1
--   sessions                   rls=t  policies=2

-- ==== RLS POLICIES (every access predicate is scoped by auth.uid()/jwt email) ====
--   chapters: select        SELECT  using(true)                          [public catalog]
--   diagnostic_*            SELECT  using(learner_access join, parent_id = auth.uid())   [owner-scoped, read-only; writes via SECURITY DEFINER RPC]
--   grades / grade_chapters SELECT/INSERT/UPDATE/DELETE scoped to grades.created_by = auth.uid() (+ learner_access for read)
--   learner_access: select  SELECT  using(parent_id = auth.uid())
--   learner_access: insert  INSERT  check(parent_id = auth.uid() AND can_self_grant_access(learner_id, access_role))
--   learner_access: delete  DELETE  using(learner_id in owned learners)   [V11: owner can revoke]
--   learner_events          INSERT/SELECT scoped by learner_access.parent_id = auth.uid()
--   learner_invites: sender      ALL     using(invited_by = auth.uid())
--                                        check(invited_by = auth.uid() AND EXISTS owned-learner)   [V1 FIX]
--   learner_invites: recipient   SELECT/UPDATE  where invited_email = lower(jwt email)
--                                ⚠️ V12 FIX IS A COLUMN-LEVEL GRANT, NOT A POLICY — `authenticated`
--                                holds UPDATE on `status` ONLY. RLS WITH CHECK cannot see OLD values,
--                                so the grant is the only thing stopping a recipient from repointing
--                                learner_id/invited_by and self-granting on a stranger's child.
--                                Verified live 2026-08-17. Do not "simplify" it back to a table grant.
--   auth_events: own inserts     INSERT  check(user_id = auth.uid())      [write-only; no SELECT policy]
--   diagnostic_leads: insert     INSERT  check(length 3..254 AND email ~ shape)   [anon+authenticated]
--   error_events                 (no policies — deny-all by design; service-role writes only)
--   learner_progress/state/stats ALL     using+check EXISTS(learner_access where parent_id = auth.uid())
--   learners: select        SELECT  using(created_by = auth.uid() OR id in learner_access)
--   learners: insert        INSERT  check(created_by = auth.uid())
--   learners: update        UPDATE  using+check(created_by = auth.uid())
--   learners: delete        DELETE  using(created_by = auth.uid())        [owner-only]
--   profiles: own row       ALL     using+check(auth.uid() = id)
--   sessions: parent insert INSERT  check EXISTS(learner_access where parent_id = auth.uid())
--   sessions: parent read   SELECT  using EXISTS(learner_access where parent_id = auth.uid())

-- ==== FUNCTIONS (security posture — DEFINER functions must pin search_path + guard auth.uid()) ====
--   DEFINER, authenticated-callable (each self-guards on learner ownership / auth.uid()):
--     can_self_grant_access(uuid,text)        stable   search_path=public   [computes the grant check; V1-hardened]
--     sync_session(...)                        volatile search_path=public   [learner_access guard; xp/coins server-derived — V2]
--     sync_diagnostic(...)                     volatile search_path=public   [learner_access guard; payload bounds — V5]
--     sync_recheck(...)                        volatile search_path=public   [learner_access guard]
--   INVOKER, authenticated-callable (RLS is the gate):
--     get_parent_dashboard()                   stable   search_path=public
--     get_insights_rollup(timestamptz)         stable   search_path=public
--     get_learner_bootstrap(uuid)              stable   search_path=public
--   DEFINER, trigger-only (NOT granted to anon/authenticated — correct):
--     grant_owner_access(), init_learner_stats(), handle_new_user(),
--     enforce_learner_cap(), enforce_grade_cap(), enforce_grade_ownership(),
--     rls_auto_enable()  [event trigger — auto-enables RLS on any new public table]
--     prune_error_events()  [V16 retention, pg_cron 'prune-error-events' daily 03:27 since 2026-08-24]
--     prune_diagnostic_leads()  [24-month lead retention, pg_cron 'prune-diagnostic-leads' 03:32]
--     prune_diagnostic_items()  [90-day RAW placement answers, pg_cron 'prune-diagnostic-items' 03:22]
--     delete_lead_by_email(text) [honours a lead's deletion request; docs/runbooks/data-requests.md]
--        ⚠️ All four are SECURITY DEFINER with an explicit REVOKE from public/anon/authenticated —
--        the V19 rule. delete_lead_by_email is an address-enumeration oracle without it.
--        ⚠️ V19: created SECURITY DEFINER, which Postgres gives PUBLIC EXECUTE by DEFAULT, and
--        Supabase exposes every public-schema function at /rest/v1/rpc/<name> — i.e. for a few
--        minutes ANY anonymous caller could wipe the crash log. Revoked. THE GENERAL RULE: always
--        pair `create function ... security definer` with an explicit REVOKE, and verify `proacl`
--        afterwards — a successful migration tells you nothing about who can call the result.
--   INVOKER trigger helpers: set_updated_at() (revoked),
--     touch_grades_updated_at()  [FIXED 2026-08-17 — PUBLIC/anon EXECUTE revoked; was the last
--        function in the schema still callable from the API. Same class as V19.]
--
--   As of 2026-08-17: ALL 12 DEFINER functions pin search_path, NONE is anon-callable, and no
--   function in `public` retains default PUBLIC EXECUTE. Verified against pg_proc.proacl.

-- ==== TRIGGERS (public tables) ====
--   learners.on_learner_created           -> grant_owner_access      (owner gets learner_access on create)
--   learners.on_learner_created_stats     -> init_learner_stats
--   learners.trg_enforce_learner_cap      -> enforce_learner_cap      (<=25 per account)
--   learners.trg_enforce_grade_ownership  -> enforce_grade_ownership
--   learners.learners_updated_at          -> set_updated_at
--   grades.trg_enforce_grade_cap          -> enforce_grade_cap
--   grades.trg_touch_grades               -> touch_grades_updated_at
--   learner_progress/learner_stats/profiles.*_updated_at -> set_updated_at
