/**
 * How g3m1's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G3M1_VOICE: Record<string, VoiceLine> = {
  // ── g3m1-t5 ── ("Here's the part people mix up." and "Okay. Your turn." share g5m1's rows)
  "You already count by 2s, 5s and 10s.": { style: 'B' },
  "Counting by 3s is new, so it doesn't come as easily yet.": { style: 'B' },
  "Can you do it the same way? Yes.": { style: 'B' },
  "3s and 4s work just like 2s and 5s, so add the same number every time you jump.": { style: 'B' },
  "Each tricycle has 3 wheels, so each is a jump of 3.": { style: 'B' },
  "Three, six, nine, twelve.": { style: 'B' },
  "4 jumps of 3 make 12.": { style: 'B' },
  "A car has 4 wheels. Jump by 4s.": { style: 'B' },
  "Four, eight, twelve.": { style: 'B' },
  "3 jumps of 4 make 12.": { style: 'B' },
  "Now write them down.": { style: 'B' },
  "4 tricycles have 12 wheels, so 4 × 3 = 12.": { style: 'B' },
  "3 cars have 12 wheels, so 3 × 4 = 12.": { style: 'B' },
  "Counting by 3s does not mean ADD 1 each time.": { style: 'B+' },
  "That gives 3, 4, 5, 6. Every jump adds a whole group of 3, so it goes 3, 6, 9, 12.": { style: 'B+' },
  "There are 6 groups of 3. Count by 3s: 3, 6 …": { style: 'A', say: "There are 6 groups of 3. Count by 3s, 3, 6, and so on." },
  // ── g3m1-t6 ──
  "What does fair mean here?": { style: 'B' },
  "If one friend gets 6 and another gets 2, that isn't fair.": { style: 'B' },
  "Every friend must get the same number.": { style: 'B' },
  "Division shares a total into equal groups, and here we know how many groups, so we find how many in each.": { style: 'B' },
  "Give one apple to each friend. That is one round.": { style: 'B' },
  "Then go round again. Now each friend has 2.": { style: 'B' },
  "Keep going, round and round, until the basket is empty.": { style: 'B' },
  "Now count the first friend's apples. One, two, three, four.": { style: 'B' },
  "Each friend has 4 apples, and it is fair.": { style: 'B' },
  "12 shared by 3 friends is 4 each.": { style: 'B' },
  "We write 12 ÷ 3 = 4.": { style: 'B' },
  "The first number is the total, then the friends, then how many each.": { style: 'B' },
  "Don't FLIP it to 3 ÷ 12.": { style: 'B+' },
  "You are sharing 12 apples, not 3, so the total goes first.": { style: 'B+' },
  // ── g3m1-t7 ── ("We write 12 ÷ 3 = 4." shares g3m1-t6's row)
  "When we shared apples, we knew how many friends.": { style: 'B' },
  "This time we know how many go in each bag.": { style: 'B' },
  "So what is missing? The number of bags.": { style: 'B' },
  "Division can also mean: how many groups of this size can we make?": { style: 'B' },
  "Take 3 apples and put them in a bag.": { style: 'B' },
  "That is one bag. 9 apples are left.": { style: 'B' },
  "Keep making bags of 3.": { style: 'B' },
  "Two bags, three bags, four bags.": { style: 'B' },
  "Now no apples are left.": { style: 'B' },
  "Count the bags. We filled 4 bags.": { style: 'B' },
  "It works, because 4 bags of 3 make 12.": { style: 'B' },
  "The answer is NOT the number in each bag.": { style: 'B+' },
  "We already know that is 3. The question is how many bags, and that is 4.": { style: 'B+' },
  "Count by 4s until you reach 20: 4, 8 … How many groups?": { style: 'A', say: "Count by 4s until you reach 20, 4, 8, and so on. How many groups?" },
  // ── g3m1-t8 ──
  "We know there are 4 rows. We know there are 20 chairs.": { style: 'B' },
  "So which number is missing? The number in each row.": { style: 'B' },
  "Multiplication and division are partners, so a times fact you know can find a missing number.": { style: 'B' },
  "Count by 4s until you reach 20.": { style: 'B' },
  "Four, eight, twelve, sixteen, twenty.": { style: 'B' },
  "That is 5 jumps.": { style: 'B' },
  "Put the chairs in 4 rows, 5 in each row.": { style: 'B' },
  "4 rows of 5 make 20. So 4 × 5 = 20, and the missing number is 5.": { style: 'B' },
  "The same three numbers, 4, 5 and 20, make four facts.": { style: 'B' },
  "4 × 5 = 20, and 5 × 4 = 20.": { style: 'B' },
  "20 ÷ 4 = 5, and 20 ÷ 5 = 4.": { style: 'B' },
  "When you divide, don't put the 20 LAST.": { style: 'B+' },
  "The biggest number is the total, and it comes first, like 20 ÷ 5 = 4.": { style: 'B+' },
}
