/**
 * How g3m1's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G3M1_VOICE: Record<string, VoiceLine> = {
  // Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts.
  // ── g3m1-t1 ──
  "You could count every cookie.": { style: 'B' },
  "That works. But it's slow, and it's easy to lose your place.": { style: 'B' },
  "Is there a faster way? Yes. Look at the plates.": { style: 'B' },
  "When every group has the same number, you can count a whole group at a time.": { style: 'B' },
  "Look. Each plate is a group.": { style: 'B' },
  "There are 4 plates, so there are 4 groups.": { style: 'B' },
  "And each plate has 3 cookies. That's 3 in each group.": { style: 'B' },
  "Now count one whole plate at a time.": { style: 'B' },
  "3, 6, 9, 12.": { style: 'B' },
  "So there are 12 cookies.": { style: 'B' },
  "4 groups of 3 make 12.": { style: 'B' },
  "We write that as 4 × 3 = 12.": { style: 'B' },
  "The first number is the groups. The second is how many in each.": { style: 'B' },
  "4 × 3 does not mean ADD 4 and 3.": { style: 'B+' },
  "That gives 7, just one plate and 4 more cookies. 4 × 3 is 4 whole plates of 3.": { style: 'B+' },
  "There are 3 groups of 5. Count by 5s, one plate at a time: 5, 10 …": { style: 'A', say: "There are 3 groups of 5. Count by 5s, one plate at a time. 5, 10, and keep going." },
  "There are 5 groups of 2. Count by 2s: 2, 4 …": { style: 'A', say: "There are 5 groups of 2. Count by 2s. 2, 4, and keep going." },
  // ── g3m1-t2 ──
  "When chairs are jumbled, you have to count every one.": { style: 'B' },
  "And it's easy to miss some.": { style: 'B' },
  "What if they stand in neat rows? Then it's much faster.": { style: 'B' },
  "When every row has the same number, count the rows, count one row, then multiply.": { style: 'B' },
  "Look. Rows go across, from left to right.": { style: 'B' },
  "Count them. 1, 2, 3.": { style: 'B' },
  "There are 3 rows.": { style: 'B' },
  "Every row is the same, so you only need to count one.": { style: 'B' },
  "1, 2, 3, 4, 5.": { style: 'B' },
  "Each row has 5 chairs.": { style: 'B' },
  "Now count one whole row at a time. 5, 10, 15.": { style: 'B' },
  "3 rows of 5 is 15.": { style: 'B' },
  "We write it as 3 × 5 = 15.": { style: 'B' },
  "If one row is missing a chair, it is NOT 3 × 5 any more.": { style: 'B+' },
  "Every row must have the same number. Count each row to check.": { style: 'B+' },
  "There are 4 rows of 3. Count by 3s, one row at a time: 3, 6 …": { style: 'A', say: "There are 4 rows of 3. Count by 3s, one row at a time. 3, 6, and keep going." },
  "There are 2 groups of 5. Count by 5s: 5 …": { style: 'A', say: "There are 2 groups of 5. Count by 5s. 5, and keep going." },
  // ── g3m1-t3 ──
  "Turn the tray, and now there are 5 rows of 2.": { style: 'B' },
  "It looks different. So did the number of muffins change?": { style: 'B' },
  "Turning the rows around does not change how many there are, so 2 × 5 and 5 × 2 make the same total.": { style: 'B' },
  "First, the tray as it started. 2 rows of 5.": { style: 'B' },
  "Count by rows. 5, 10.": { style: 'B' },
  "So 2 × 5 = 10.": { style: 'B' },
  "Now watch the tray turn.": { style: 'B' },
  "Does any muffin fall off? No. Is any muffin added? No.": { style: 'B' },
  "Every muffin just moves to a new spot.": { style: 'B' },
  "Now count the turned tray by rows. 2, 4, 6, 8, 10.": { style: 'B' },
  "So 5 × 2 = 10.": { style: 'B' },
  "Same muffins, same total.": { style: 'B' },
  "This turn-around trick works for times. It does NOT work for take away.": { style: 'B+' },
  "5 − 2 leaves 3. But 2 − 5 does not leave 3, so they are not the same.": { style: 'B+' },
  // ── g3m1-t4 ──
  "You could count every sock, one at a time.": { style: 'B' },
  "But socks come in pairs. Is there a faster way? Yes.": { style: 'B' },
  "When the groups are the same size, jump by that size, and each jump counts a whole group.": { style: 'B' },
  "Look at the number line. Each pair is one jump of 2.": { style: 'B' },
  "2, 4, 6, 8, 10, 12.": { style: 'B' },
  "How many jumps did we make? Count them. 6 jumps of 2.": { style: 'B' },
  "And we landed on 12.": { style: 'B' },
  "So 6 × 2 = 12.": { style: 'B' },
  "5s work the same way. Each hand is a jump of 5. 5, 10, 15.": { style: 'B' },
  "And bundles of ten jump by 10s. 10, 20, 30, 40.": { style: 'B' },
  "4 hands means 4 jumps. Don't STOP at 15.": { style: 'B+' },
  "Hold up a finger for each jump. 5, 10, 15, 20.": { style: 'B+' },
  "There are 6 groups of 10. Count by 10s: 10, 20 …": { style: 'A', say: "There are 6 groups of 10. Count by 10s. 10, 20, and keep going." },
  // ── g3m1-t5 ── ("Here's the part people mix up." and "Okay. Your turn." share g5m1's rows)
  "You already count by 2s, 5s and 10s.": { style: 'B' },
  "Counting by 3s is new, so it doesn't come as easily yet.": { style: 'B' },
  "Can you do it the same way? Yes.": { style: 'B' },
  "3s and 4s work just like 2s and 5s, so add the same number every time you jump.": { style: 'B' },
  "Each tricycle has 3 wheels, so each is a jump of 3.": { style: 'B' },
  "Three, six, nine, twelve.": { style: 'B' },
  "4 jumps of 3 make 12.": { style: 'B' },
  "A car has 4 wheels. Jump by 4s.": { style: 'B' },
  "Four, eight, twelve.": { style: 'B' },
  "3 jumps of 4 make 12.": { style: 'B' },
  "Now write them down.": { style: 'B' },
  "4 tricycles have 12 wheels, so 4 × 3 = 12.": { style: 'B' },
  "3 cars have 12 wheels, so 3 × 4 = 12.": { style: 'B' },
  "Counting by 3s does not mean ADD 1 each time.": { style: 'B+' },
  "That gives 3, 4, 5, 6. Every jump adds a whole group of 3, so it goes 3, 6, 9, 12.": { style: 'B+' },
  "There are 6 groups of 3. Count by 3s: 3, 6 …": { style: 'A', say: "There are 6 groups of 3. Count by 3s, 3, 6, and so on." },
  // ── g3m1-t6 ──
  "What does fair mean here?": { style: 'B' },
  "If one friend gets 6 and another gets 2, that isn't fair.": { style: 'B' },
  "Every friend must get the same number.": { style: 'B' },
  "Division shares a total into equal groups, and here we know how many groups, so we find how many in each.": { style: 'B' },
  "Give one apple to each friend. That is one round.": { style: 'B' },
  "Then go round again. Now each friend has 2.": { style: 'B' },
  "Keep going, round and round, until the basket is empty.": { style: 'B' },
  "Now count the first friend's apples. One, two, three, four.": { style: 'B' },
  "Each friend has 4 apples, and it is fair.": { style: 'B' },
  "12 shared by 3 friends is 4 each.": { style: 'B' },
  "We write 12 ÷ 3 = 4.": { style: 'B' },
  "The first number is the total, then the friends, then how many each.": { style: 'B' },
  "Don't FLIP it to 3 ÷ 12.": { style: 'B+' },
  "You are sharing 12 apples, not 3, so the total goes first.": { style: 'B+' },
  // ── g3m1-t7 ── ("We write 12 ÷ 3 = 4." shares g3m1-t6's row)
  "When we shared apples, we knew how many friends.": { style: 'B' },
  "This time we know how many go in each bag.": { style: 'B' },
  "So what is missing? The number of bags.": { style: 'B' },
  "Division can also mean: how many groups of this size can we make?": { style: 'B' },
  "Take 3 apples and put them in a bag.": { style: 'B' },
  "That is one bag. 9 apples are left.": { style: 'B' },
  "Keep making bags of 3.": { style: 'B' },
  "Two bags, three bags, four bags.": { style: 'B' },
  "Now no apples are left.": { style: 'B' },
  "Count the bags. We filled 4 bags.": { style: 'B' },
  "It works, because 4 bags of 3 make 12.": { style: 'B' },
  "The answer is NOT the number in each bag.": { style: 'B+' },
  "We already know that is 3. The question is how many bags, and that is 4.": { style: 'B+' },
  "Count by 4s until you reach 20: 4, 8 … How many groups?": { style: 'A', say: "Count by 4s until you reach 20, 4, 8, and so on. How many groups?" },
  // ── g3m1-t8 ──
  "We know there are 4 rows. We know there are 20 chairs.": { style: 'B' },
  "So which number is missing? The number in each row.": { style: 'B' },
  "Multiplication and division are partners, so a times fact you know can find a missing number.": { style: 'B' },
  "Count by 4s until you reach 20.": { style: 'B' },
  "Four, eight, twelve, sixteen, twenty.": { style: 'B' },
  "That is 5 jumps.": { style: 'B' },
  "Put the chairs in 4 rows, 5 in each row.": { style: 'B' },
  "4 rows of 5 make 20. So 4 × 5 = 20, and the missing number is 5.": { style: 'B' },
  "The same three numbers, 4, 5 and 20, make four facts.": { style: 'B' },
  "4 × 5 = 20, and 5 × 4 = 20.": { style: 'B' },
  "20 ÷ 4 = 5, and 20 ÷ 5 = 4.": { style: 'B' },
  "When you divide, don't put the 20 LAST.": { style: 'B+' },
  "The biggest number is the total, and it comes first, like 20 ÷ 5 = 4.": { style: 'B+' },
}
