/**
 * How g3m2's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G3M2_VOICE: Record<string, VoiceLine> = {
  // ── g3m2-t1 ── ("Here's the part people mix up." and "Okay. Your turn." share g5m1's rows)
  "Look at the long hand. It points right at the 3.": { style: 'B' },
  "So is it 3 minutes? No.": { style: 'B' },
  "The big numbers are for the hours, not the minutes.": { style: 'B' },
  "The long hand counts by 5s, so each number on the clock is 5 more minutes.": { style: 'B' },
  "Start with the short hand.": { style: 'B' },
  "It is just past the 4, but not at the 5 yet.": { style: 'B' },
  "So the hour is 4.": { style: 'B' },
  "Now the long hand. Start at the 12 and count by 5s.": { style: 'B' },
  "Five, ten, fifteen.": { style: 'B' },
  "We stop at the 3, so that's 15 minutes.": { style: 'B' },
  "So it's hour 4 and 15 minutes.": { style: 'B' },
  "We write the hour, then two dots, then the minutes.": { style: 'B' },
  "So your show starts at 4:15.": { style: 'B' },
  "The long hand on the 3 does NOT mean 3 minutes.": { style: 'B+' },
  "That would be 4:03. Count by 5s instead, and it's 4:15.": { style: 'B+' },
  // ── g3m2-t2 ──
  "Look at the long hand. It's between the 5 and the 6, not on a number.": { style: 'B' },
  "Can counting by 5s get us there? Not on its own.": { style: 'B' },
  "Count by 5s to the last number the long hand passed, then count on by 1s for the little marks.": { style: 'B', say: "Count by 5s to the last number the long hand passed, then count on by ones for the little marks." },
  "First the short hand. It's just past the 3, so the hour is 3.": { style: 'B' },
  "The long hand has passed the 5, so count by 5s to the 5.": { style: 'B' },
  "Five, ten, fifteen, twenty, twenty-five.": { style: 'B' },
  "Each little mark is 1 more minute.": { style: 'B' },
  "From 25, keep going. Twenty-six, twenty-seven.": { style: 'B' },
  "That's 27 minutes.": { style: 'B' },
  "So it's hour 3 and 27 minutes.": { style: 'B' },
  "Write the hour, two dots, then the minutes.": { style: 'B' },
  "The bus comes at 3:27.": { style: 'B' },
  "Don't STOP at the number the long hand passed.": { style: 'B+' },
  "That gives 3:25, and it drops 2 little marks. The time is 3:27.": { style: 'B+' },
  // ── g3m2-t3 ──
  "A clock tells you what time it is right now.": { style: 'B' },
  "It doesn't tell you how long something took.": { style: 'B' },
  "So how do we find out? We count the minutes in between.": { style: 'B' },
  "Start at the start time, then jump to the end time and add up the jumps.": { style: 'B' },
  "We start at 3:10 and jump by 10s.": { style: 'B' },
  "3:20, 3:30, 3:40.": { style: 'B' },
  "That's 3 jumps of 10, so 30 minutes so far.": { style: 'B' },
  "Now we're at 3:40, and the game ends at 3:45.": { style: 'B' },
  "How big is that last jump? Just 5 minutes.": { style: 'B' },
  "Now add up the jumps.": { style: 'B' },
  "10, 10 and 10 make 30, and 5 more makes 35.": { style: 'B' },
  "So the game is 35 minutes long.": { style: 'B' },
  "The answer is NOT the end time, 3:45.": { style: 'B+' },
  "The question asks how long, so the answer is 35 minutes.": { style: 'B+' },
  // ── g3m2-t4 ──
  "Look where the needle stopped, between 600 and 800.": { style: 'B' },
  "There's no number right there. So what does it say?": { style: 'B' },
  "First we need to know what each mark is worth.": { style: 'B' },
  "Find what each little mark is worth, then count the marks to the needle.": { style: 'B' },
  "Look from 0 to 200.": { style: 'B' },
  "That's 2 jumps, mark to mark.": { style: 'B' },
  "2 equal jumps make 200, so each mark is worth 100 grams.": { style: 'B' },
  "Find the last number before the needle. That's 600.": { style: 'B' },
  "One more mark is 100 more. That makes 700.": { style: 'B' },
  "So the apples weigh 700 grams.": { style: 'B' },
  "Light things, like apples, are weighed in grams.": { style: 'B' },
  "What about a dog? A dog is heavy, so we use kilograms.": { style: 'B' },
  "And 1 kilogram is 1,000 grams.": { style: 'B' },
  "Each mark is NOT 1 gram. That would make 601.": { style: 'B+' },
  "On this scale, each mark is 100 grams. So it's 700.": { style: 'B+' },
  // ── g3m2-t5 ──
  "Look at the top of the juice, between 400 and 600.": { style: 'B' },
  "There's no number at that line. So how much is it?": { style: 'B' },
  "First we find what each mark is worth.": { style: 'B' },
  "Find what each little mark is worth, then count the marks up to the top.": { style: 'B' },
  "Start at 0 and go up to 200.": { style: 'B' },
  "2 equal jumps make 200, so each mark is worth 100 milliliters.": { style: 'B' },
  "Find the last number below the juice. That's 400.": { style: 'B' },
  "Count up one more mark. That's 500.": { style: 'B' },
  "So there are 500 milliliters of juice.": { style: 'B' },
  "A cup of water is small. We use milliliters.": { style: 'B' },
  "A bucket holds a lot. We use liters.": { style: 'B' },
  "And 1 liter is 1,000 milliliters.": { style: 'B' },
  "Don't STOP at the number below the juice. That's only 400.": { style: 'B+' },
  "Count up to the top, and it's 500.": { style: 'B+' },
  // Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts.
  // ── g3m2-t6 ──
  "37 starts with a 3. So is it 30?": { style: 'B' },
  "Not so fast. The 3 does not tell you which ten is closer.": { style: 'B' },
  "How can we tell? Use a number line.": { style: 'B' },
  "A number rounds to the closer ten, and right in the middle, it rounds up.": { style: 'B' },
  "Look. 37 is more than 30, and less than 40.": { style: 'B' },
  "So it sits between 30 and 40.": { style: 'B' },
  "Count the hops. From 37 up to 40 is 3 hops.": { style: 'B' },
  "From 37 back to 30 is 7 hops.": { style: 'B' },
  "3 hops is fewer. So the jar has about 40 marbles.": { style: 'B' },
  "What about 35?": { style: 'B' },
  "It is 5 hops from 30, and 5 hops from 40.": { style: 'B' },
  "Right in the middle, it goes up. So 35 rounds to 40.": { style: 'B' },
  "Don't just KEEP the 3 and write 30.": { style: 'B+' },
  "Count the hops. 37 is closer to 40.": { style: 'B+' },
  // ── g3m2-t7 ──
  "200 to 300 is a long way. Hopping by 1s takes all day.": { style: 'B' },
  "Is there a faster way? Yes. Hop by 10s instead.": { style: 'B' },
  "A number rounds to the closer hundred, and right in the middle, it rounds up.": { style: 'B' },
  "Look. 270 is more than 200, and less than 300.": { style: 'B' },
  "So it sits between 200 and 300.": { style: 'B' },
  "Count hops of 10. From 270 up to 300 is 3 hops.": { style: 'B' },
  "From 270 back to 200 is 7 hops.": { style: 'B' },
  "3 hops is fewer. So about 300 people came.": { style: 'B' },
  "What about 250?": { style: 'B' },
  "It is 5 hops from 200, and 5 hops from 300.": { style: 'B' },
  "Right in the middle, it goes up. So 250 rounds to 300.": { style: 'B' },
  "329 ends in 9. Don't let that LAST digit push it to 400.": { style: 'B+' },
  "Count the hops. 329 is just past 300, so it rounds to 300.": { style: 'B+' },
  // ── g3m2-t8 ──
  "Start with the ones. 6 and 8 make 14 ones.": { style: 'B' },
  "Can 14 fit in the ones place? No. A place holds one digit, 0 to 9.": { style: 'B' },
  "Add the ones first, and if there are 10 or more, trade 10 ones for 1 ten.": { style: 'B' },
  "Look. Stack 146 on 128, ones under ones.": { style: 'B' },
  "6 + 8 = 14. That's 1 ten and 4 ones.": { style: 'B' },
  "Write the 4. The 1 ten goes up, on top of the tens.": { style: 'B' },
  "Now the tens. The 1 we traded, plus 4, plus 2.": { style: 'B' },
  "1 + 4 + 2 = 7 tens.": { style: 'B' },
  "Last, the hundreds. 1 + 1 = 2.": { style: 'B' },
  "So 146 + 128 = 274. That's 274 books.": { style: 'B' },
  "Don't FORGET the ten you traded.": { style: 'B+' },
  "Without it, the tens make 6, and you get 264. Add the little 1, and it's 274.": { style: 'B+' },
  // ── g3m2-t9 ──
  "Start with the ones. We need to take away 7.": { style: 'B' },
  "But there are only 2 ones. Can you take 7 from 2? No.": { style: 'B' },
  "Take away the ones first, and if there are not enough, break 1 ten into 10 ones.": { style: 'B' },
  "Look. Stack 352 on 127, ones under ones.": { style: 'B' },
  "Take 1 ten from the 5 tens. Now there are 4 tens.": { style: 'B' },
  "Break it into 10 ones. 10 and 2 make 12 ones.": { style: 'B' },
  "Now 12 − 7 = 5. Write 5 in the ones place.": { style: 'B' },
  "Tens next. 4 − 2 = 2.": { style: 'B' },
  "Last, the hundreds. 3 − 1 = 2.": { style: 'B' },
  "So 352 − 127 = 225. Nia has 225 stickers left.": { style: 'B' },
  "Don't FLIP it to 7 − 2. The 7 is what you take away.": { style: 'B+' },
  "Break a ten instead. Then it's 12 − 7, and you get 225.": { style: 'B+' },
}
