/**
 * How g3m3's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G3M3_VOICE: Record<string, VoiceLine> = {
  // Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts.
  // ── g3m3-t1 ──
  "There are 4 plates.": { style: 'B' },
  "So there must be some cookies, right?": { style: 'B' },
  "Look closely. Every plate is empty.": { style: 'B' },
  "Empty groups add up to nothing, so any number times 0 is 0.": { style: 'B' },
  "Now count one plate at a time.": { style: 'B' },
  "This plate adds 0. So does the next, and the next, and the last.": { style: 'B' },
  "0, 0, 0, 0.": { style: 'B' },
  "Where did we get to? Still 0.": { style: 'B' },
  "So 4 groups of 0 make 0.": { style: 'B' },
  "Not one cookie.": { style: 'B' },
  "We write it as 4 × 0 = 0.": { style: 'B' },
  "Now flip it. 0 plates, with 4 cookies on each.": { style: 'B' },
  "How many cookies? There are no plates to put them on.": { style: 'B' },
  "So 0 × 4 = 0 too.": { style: 'B' },
  "4 × 0 is NOT 4.": { style: 'B+' },
  "Empty plates hold 0 cookies, however many plates there are.": { style: 'B+' },
  // ── g3m3-t2 ──
  "You could count the cookies, one by one.": { style: 'B' },
  "That works. But is there a way to know without counting?": { style: 'B' },
  "Yes. Look at the plates.": { style: 'B' },
  "When each group has 1, the total is the number of groups, so any number times 1 is that same number.": { style: 'B' },
  "Count one plate at a time.": { style: 'B' },
  "1, 2, 3, 4, 5, 6.": { style: 'B' },
  "See what happened? We counted the plates.": { style: 'B' },
  "That's 6 cookies.": { style: 'B' },
  "So 6 plates of 1 make 6.": { style: 'B' },
  "We write it as 6 × 1 = 6.": { style: 'B' },
  "The 6 stays 6.": { style: 'B' },
  "Now turn it around. 1 plate, with 6 cookies on it.": { style: 'B' },
  "How many is that? Still 6.": { style: 'B' },
  "So 1 × 6 = 6 too.": { style: 'B' },
  "Times 1 does not mean ADD 1.": { style: 'B+' },
  "That gives 7, one extra cookie. 6 plates with 1 on each is 6.": { style: 'B+' },
  // ── g3m3-t3 ──
  "You know your 5s by heart.": { style: 'B' },
  "But what is 6 × 3? Your 6s are new.": { style: 'B' },
  "Good news. Your 5s can do most of the work.": { style: 'B' },
  "To find 6 groups, find 5 groups first, then add one more group.": { style: 'B' },
  "Look at the top 5 rows.": { style: 'B' },
  "5 rows of 3. You know that one.": { style: 'B' },
  "5 × 3 = 15.": { style: 'B' },
  "Now the row left over. Just one row.": { style: 'B' },
  "How many muffins in it? 3.": { style: 'B' },
  "So 1 × 3 = 3.": { style: 'B' },
  "So 6 rows is 5 rows and 1 more row.": { style: 'B' },
  "15 and 3 more make 18.": { style: 'B' },
  "So 6 × 3 = 18.": { style: 'B' },
  "Don't add just ONE at the end.": { style: 'B+' },
  "One more row is a whole group of 3, so add 3.": { style: 'B+' },
  // ── g3m3-t4 ──
  "Can you count by 7s? 7, 14, then it gets tricky.": { style: 'B' },
  "Your 5s and your 2s are much faster.": { style: 'B' },
  "Could they help? Yes.": { style: 'B' },
  "Break 7 groups into 5 groups and 2 groups, find each part, then add them.": { style: 'B' },
  "Look at the first 5 days.": { style: 'B' },
  "5 days of 3 stickers. That's a fact you know.": { style: 'B' },
  "Now the 2 days left over.": { style: 'B' },
  "2 days of 3 stickers. What's that?": { style: 'B' },
  "2 × 3 = 6.": { style: 'B' },
  "Put the two parts back together.": { style: 'B' },
  "15 and 6 make 21.": { style: 'B' },
  "So 7 × 3 = 21. Mia gets 21 stickers.": { style: 'B' },
  "Don't add just ONE row at the end.": { style: 'B+' },
  "7 days is 5 days and 2 days, so add both rows, 6 more.": { style: 'B+' },
  // ── g3m3-t5 ──
  "Counting 8 groups one at a time takes a long time.": { style: 'B' },
  "And a long count is where slips creep in.": { style: 'B' },
  "Is there a shortcut? Yes. It's hiding in your 4s.": { style: 'B' },
  "8 groups is 4 groups and 4 more groups, so find 4 groups, then double it.": { style: 'B' },
  "Look at the top 4 rows.": { style: 'B' },
  "That's 4 packs of 3. What's 4 × 3?": { style: 'B' },
  "It's 12.": { style: 'B' },
  "Now the bottom 4 rows.": { style: 'B' },
  "Same packs, same 3 in each.": { style: 'B' },
  "So they make 12 too.": { style: 'B' },
  "Two halves, 12 each.": { style: 'B' },
  "So we double. 12 and 12 make 24.": { style: 'B' },
  "So 8 × 3 = 24.": { style: 'B' },
  "Don't double the 3.": { style: 'B+' },
  "Double the ANSWER for 4 packs, which is 12. So it's 12 + 12.": { style: 'B+' },
}
