/**
 * How g3m3's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G3M3_VOICE: Record<string, VoiceLine> = {
  // Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts.
  // ── g3m3-t1 ──
  "There are 4 plates.": { style: 'B' },
  "So there must be some cookies, right?": { style: 'B' },
  "Look closely. Every plate is empty.": { style: 'B' },
  "Empty groups add up to nothing, so any number times 0 is 0.": { style: 'B' },
  "Now count one plate at a time.": { style: 'B' },
  "This plate adds 0. So does the next, and the next, and the last.": { style: 'B' },
  "0, 0, 0, 0.": { style: 'B' },
  "Where did we get to? Still 0.": { style: 'B' },
  "So 4 groups of 0 make 0.": { style: 'B' },
  "Not one cookie.": { style: 'B' },
  "We write it as 4 × 0 = 0.": { style: 'B' },
  "Now flip it. 0 plates, with 4 cookies on each.": { style: 'B' },
  "How many cookies? There are no plates to put them on.": { style: 'B' },
  "So 0 × 4 = 0 too.": { style: 'B' },
  "4 × 0 is NOT 4.": { style: 'B+' },
  "Empty plates hold 0 cookies, however many plates there are.": { style: 'B+' },
  // ── g3m3-t2 ──
  "You could count the cookies, one by one.": { style: 'B' },
  "That works. But is there a way to know without counting?": { style: 'B' },
  "Yes. Look at the plates.": { style: 'B' },
  "When each group has 1, the total is the number of groups, so any number times 1 is that same number.": { style: 'B' },
  "Count one plate at a time.": { style: 'B' },
  "1, 2, 3, 4, 5, 6.": { style: 'B' },
  "See what happened? We counted the plates.": { style: 'B' },
  "That's 6 cookies.": { style: 'B' },
  "So 6 plates of 1 make 6.": { style: 'B' },
  "We write it as 6 × 1 = 6.": { style: 'B' },
  "The 6 stays 6.": { style: 'B' },
  "Now turn it around. 1 plate, with 6 cookies on it.": { style: 'B' },
  "How many is that? Still 6.": { style: 'B' },
  "So 1 × 6 = 6 too.": { style: 'B' },
  "Times 1 does not mean ADD 1.": { style: 'B+' },
  "That gives 7, one extra cookie. 6 plates with 1 on each is 6.": { style: 'B+' },
  // ── g3m3-t3 ──
  "You know your 5s by heart.": { style: 'B' },
  "But what is 6 × 3? Your 6s are new.": { style: 'B' },
  "Good news. Your 5s can do most of the work.": { style: 'B' },
  "To find 6 groups, find 5 groups first, then add one more group.": { style: 'B' },
  "Look at the top 5 rows.": { style: 'B' },
  "5 rows of 3. You know that one.": { style: 'B' },
  "5 × 3 = 15.": { style: 'B' },
  "Now the row left over. Just one row.": { style: 'B' },
  "How many muffins in it? 3.": { style: 'B' },
  "So 1 × 3 = 3.": { style: 'B' },
  "So 6 rows is 5 rows and 1 more row.": { style: 'B' },
  "15 and 3 more make 18.": { style: 'B' },
  "So 6 × 3 = 18.": { style: 'B' },
  "Don't add just ONE at the end.": { style: 'B+' },
  "One more row is a whole group of 3, so add 3.": { style: 'B+' },
  // ── g3m3-t4 ──
  "Can you count by 7s? 7, 14, then it gets tricky.": { style: 'B' },
  "Your 5s and your 2s are much faster.": { style: 'B' },
  "Could they help? Yes.": { style: 'B' },
  "Break 7 groups into 5 groups and 2 groups, find each part, then add them.": { style: 'B' },
  "Look at the first 5 days.": { style: 'B' },
  "5 days of 3 stickers. That's a fact you know.": { style: 'B' },
  "Now the 2 days left over.": { style: 'B' },
  "2 days of 3 stickers. What's that?": { style: 'B' },
  "2 × 3 = 6.": { style: 'B' },
  "Put the two parts back together.": { style: 'B' },
  "15 and 6 make 21.": { style: 'B' },
  "So 7 × 3 = 21. Mia gets 21 stickers.": { style: 'B' },
  "Don't add just ONE row at the end.": { style: 'B+' },
  "7 days is 5 days and 2 days, so add both rows, 6 more.": { style: 'B+' },
  // ── g3m3-t5 ──
  "Counting 8 groups one at a time takes a long time.": { style: 'B' },
  "And a long count is where slips creep in.": { style: 'B' },
  "Is there a shortcut? Yes. It's hiding in your 4s.": { style: 'B' },
  "8 groups is 4 groups and 4 more groups, so find 4 groups, then double it.": { style: 'B' },
  "Look at the top 4 rows.": { style: 'B' },
  "That's 4 packs of 3. What's 4 × 3?": { style: 'B' },
  "It's 12.": { style: 'B' },
  "Now the bottom 4 rows.": { style: 'B' },
  "Same packs, same 3 in each.": { style: 'B' },
  "So they make 12 too.": { style: 'B' },
  "Two halves, 12 each.": { style: 'B' },
  "So we double. 12 and 12 make 24.": { style: 'B' },
  "So 8 × 3 = 24.": { style: 'B' },
  "Don't double the 3.": { style: 'B+' },
  "Double the ANSWER for 4 packs, which is 12. So it's 12 + 12.": { style: 'B+' },
  // ── g3m3-t6 ──
  "You could count by 3s, one box at a time.": { style: 'B' },
  "That works, but 9 boxes is a lot to keep track of.": { style: 'B' },
  "Is there a faster way? Yes. Use 10 boxes instead.": { style: 'B' },
  "To find 9 groups, find 10 groups, then take away one group.": { style: 'B' },
  "Look. Add one pretend box, so there are 10 boxes.": { style: 'B' },
  "10 boxes of 3 make 30.": { style: 'B' },
  "But we only have 9 boxes.": { style: 'B' },
  "So the pretend box has to go, and its 3 crayons go with it.": { style: 'B' },
  "So start at 30, and take away 3.": { style: 'B' },
  "That leaves 27.": { style: 'B' },
  "So 9 boxes of 3 make 27 crayons.": { style: 'B' },
  "Don't take away just 1. That gives 29.": { style: 'B+' },
  "The pretend box held 3 crayons, so take away the whole BOX. 30 − 3 = 27.": { style: 'B+' },
  // ── g3m3-t7 ──
  "7 rows of 8 is a big fact to just know.": { style: 'B' },
  "Counting by 8s, row by row, is slow, and it's easy to slip.": { style: 'B' },
  "Can we make it smaller? Yes. Cut the rows apart.": { style: 'B' },
  "Break a big fact into two smaller facts you know, solve each one, then add them.": { style: 'B' },
  "Look. Cut the 7 rows into 5 rows and 2 rows.": { style: 'B' },
  "5 rows of 8 is a fact you know. So is 2 rows of 8.": { style: 'B' },
  "5 rows of 8 make 40.": { style: 'B' },
  "2 rows of 8 make 16.": { style: 'B' },
  "Now put the parts back together.": { style: 'B' },
  "40 and 16 make 56.": { style: 'B' },
  "So 7 rows of 8 make 56 carrots.": { style: 'B' },
  "The 2 rows are NOT just 2 carrots.": { style: 'B+' },
  "40 and 2 make 42, and that's too few. Each of those 2 rows holds 8 carrots, so add 16.": { style: 'B+' },
  // ── g3m3-t8 ──
  "Each cup holds 4 bundles of 10. That's 40 straws in one cup.": { style: 'B' },
  "Jumping by 40s in your head is hard.": { style: 'B' },
  "Is there a faster way? Yes. Count the bundles, not the straws.": { style: 'B' },
  "To multiply by tens, count how many tens, then turn the tens into a number.": { style: 'B' },
  "Look. Each cup has 4 bundles.": { style: 'B' },
  "Count one cup at a time. 4, 8, 12.": { style: 'B' },
  "So there are 12 bundles.": { style: 'B' },
  "3 × 4 = 12. That's a fact you know.": { style: 'B' },
  "And every bundle is a ten, so that's 12 tens.": { style: 'B' },
  "Now, how much is 12 tens?": { style: 'B' },
  "10 tens make 100. 2 more tens make 20.": { style: 'B' },
  "100 and 20 make 120. So there are 120 straws.": { style: 'B' },
  "Don't STOP at 12. Those are 12 bundles, not 12 straws.": { style: 'B+' },
  "Each bundle is 10 straws, so 12 tens is 120.": { style: 'B+' },
  // ── g3m3-t9 ──
  "Can we take 5 away right now? Not yet.": { style: 'B' },
  "First we need to know how many pencils Sam has.": { style: 'B' },
  "The story doesn't tell us. It hides that question.": { style: 'B' },
  "A two-step story hides a first question, so answer it first, then use that to answer the real one.": { style: 'B' },
  "Step 1. How many pencils did Sam buy?": { style: 'B' },
  "3 packs with 4 in each. 3 × 4 = 12.": { style: 'B' },
  "So Sam has 12 pencils.": { style: 'B' },
  "Step 2. Now the real question.": { style: 'B' },
  "He gives 5 away, so take 5 from 12.": { style: 'B' },
  "12 take away 5 leaves 7.": { style: 'B' },
  "So Sam has 7 pencils left.": { style: 'B' },
  "Don't ADD 3 and 4, then take away 5. That leaves just 2.": { style: 'B+' },
  "3 packs of 4 is 12, so take 5 from 12.": { style: 'B+' },
}
