/**
 * How g3m4's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G3M4_VOICE: Record<string, VoiceLine> = {
  // Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts; "1, 2, 3, 4, 5." has its row in g3m1.ts.
  // ── g3m4-t1 ──
  "A ruler tells you how long one side is.": { style: 'B' },
  "But the floor is the whole inside.": { style: 'B' },
  "So how do we measure the inside? We cover it with tiles.": { style: 'B' },
  "To find how much floor there is, count the square tiles that cover it, with no gaps and no overlaps.": { style: 'B' },
  "Look at one tile.": { style: 'B' },
  "It is a square, 1 foot on every side.": { style: 'B' },
  "Every tile is the same, and they fit side by side.": { style: 'B' },
  "Now count every tile, just once.": { style: 'B' },
  "Go one row at a time. 4, 8, 12.": { style: 'B' },
  "That's 12 tiles.": { style: 'B' },
  "So how do we say how big that is?": { style: 'B' },
  "Each tile is 1 foot on every side, so we call it 1 square foot.": { style: 'B' },
  "12 tiles cover 12 square feet.": { style: 'B' },
  "Don't leave a GAP, and don't let tiles overlap.": { style: 'B+' },
  "A gap misses floor, and an overlap counts it twice. Cover it all, just once.": { style: 'B+' },
  // ── g3m4-t2 ──
  "You could count every tile, one at a time.": { style: 'B' },
  "That works. But in a big garden, it takes a long time.": { style: 'B' },
  "Is there a faster way? Yes. Look at the rows.": { style: 'B' },
  "For a rectangle, the area is the number of rows times the tiles in one row.": { style: 'B' },
  "Look. Rows go across, like lines of writing.": { style: 'B' },
  "How many rows are there? Count with me. 1, 2, 3.": { style: 'B' },
  "That's 3 rows.": { style: 'B' },
  "Every row is the same, so count just one.": { style: 'B' },
  "One row has 5 tiles.": { style: 'B' },
  "Now count by whole rows. 5, 10, 15.": { style: 'B' },
  "3 rows of 5 is 15, so 3 × 5 = 15.": { style: 'B' },
  "The area is 15 square units.": { style: 'B' },
  "Don't ADD 5 and 3.": { style: 'B+' },
  "That gives 8, but the tiles are 3 rows of 5. So multiply, 3 × 5 = 15.": { style: 'B+' },
  "There are 4 rows of 6. Count by 6s, one row at a time: 6, 12 …": { style: 'A', say: "There are 4 rows of 6. Count by 6s, one row at a time. 6, 12, and keep going." },
  // ── g3m4-t3 ──
  "The area is 3 × 7.": { style: 'B' },
  "Do you know that fact yet? That's okay if not.": { style: 'B' },
  "But you know 3 × 5, and 3 × 2.": { style: 'B' },
  "Cut a big rectangle into two smaller ones, find each area, then add them.": { style: 'B' },
  "So let's cut it, right after 5 tiles.": { style: 'B' },
  "Now there are two smaller rugs.": { style: 'B' },
  "One is 3 by 5, and one is 3 by 2.": { style: 'B' },
  "Now find each one.": { style: 'B' },
  "The first is 3 rows of 5. That's 15.": { style: 'B' },
  "The second is 3 rows of 2. That's 6.": { style: 'B' },
  "Now put the pieces back together.": { style: 'B' },
  "15 + 6 = 21. So 3 × 7 = 21.": { style: 'B' },
  "The rug covers 21 square units.": { style: 'B' },
  "Don't STOP after one piece.": { style: 'B+' },
  "3 × 5 = 15 is only part of the rug. Add the other piece, and 15 + 6 = 21.": { style: 'B+' },
  // ── g3m4-t4 ──
  "Can you just multiply the rows by one row? Not here.": { style: 'B' },
  "Look at the rows.": { style: 'B' },
  "The top 2 rows have 3 tiles. The bottom 3 have 6.": { style: 'B' },
  "Cut the L into two rectangles, find the area of each, then add.": { style: 'B' },
  "So draw a line down, after 3 tiles.": { style: 'B' },
  "Now there are two rectangles.": { style: 'B' },
  "A tall one on the left, and a short one.": { style: 'B' },
  "Now take them one at a time.": { style: 'B' },
  "The tall one is 5 rows of 3. That's 15.": { style: 'B' },
  "The short one is 3 rows of 3. That's 9.": { style: 'B' },
  "Now put the two parts together.": { style: 'B' },
  "15 + 9 = 24.": { style: 'B' },
  "So the room needs 24 square feet of carpet.": { style: 'B' },
  "Don't multiply the two LONGEST sides. 5 × 6 = 30 counts the missing corner too, where there is no floor.": { style: 'B+' },
  "Find each part and add them. 15 + 9 = 24.": { style: 'B+' },
}
