/**
 * How g3m5's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G3M5_VOICE: Record<string, VoiceLine> = {
  // Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts.
  // ── g3m5-t1 ──
  "2 pieces, one for each of you. That sounds fair.": { style: 'B' },
  "But look. This sandwich has 2 pieces too, one big and one small.": { style: 'B' },
  "So is counting the pieces enough? No.": { style: 'B' },
  "A cut is fair only when every piece is the same size.": { style: 'B' },
  "Look. I'll cut the sandwich right down the middle.": { style: 'B' },
  "Now check. Are both pieces the same size? Yes, they match.": { style: 'B' },
  "That's 2 fair pieces, one for you and one for your friend.": { style: 'B' },
  "What if 4 friends share the sandwich?": { style: 'B' },
  "Then we cut 4 pieces, and every piece is the same size.": { style: 'B' },
  "Each friend gets 1 of the 4 equal pieces.": { style: 'B' },
  "How can you check a cut? Just look at the pieces.": { style: 'B' },
  "If every piece matches, the cut is fair.": { style: 'B' },
  "If even one piece is bigger, it is not fair.": { style: 'B' },
  "Don't just COUNT the pieces and call it fair.": { style: 'B+' },
  "4 pieces are not fair if one is bigger. Every piece has to be the same size.": { style: 'B+' },
  // ── g3m5-t2 ──
  "You ate 1 piece.": { style: 'B' },
  "But that is not 1 whole sandwich.": { style: 'B' },
  "So how do we write 1 piece out of 4?": { style: 'B' },
  "1 of 4 equal pieces is 1/4, and the bottom number counts all the equal pieces.": { style: 'B' },
  "Start with the whole sandwich.": { style: 'B' },
  "It is cut into equal pieces. Count them. 1, 2, 3, 4.": { style: 'B' },
  "4 pieces make the whole. So the 4 goes on the bottom.": { style: 'B' },
  "The 4 is on the bottom.": { style: 'B' },
  "Now the piece you ate. Just 1 piece, the shaded one.": { style: 'B' },
  "So the 1 goes on top.": { style: 'B' },
  "Put the two numbers together. That's 1/4.": { style: 'B' },
  "We say it out loud as one fourth.": { style: 'B' },
  "It means 1 of 4 equal pieces, the part you ate.": { style: 'B' },
  "Don't put the LEFTOVER pieces on the bottom.": { style: 'B+' },
  "3 pieces are left, but the sandwich was cut into 4. So it is 1/4, not 1/3.": { style: 'B+' },
  // ── g3m5-t3 ──
  "You know this part. 1 piece out of 4 is 1/4.": { style: 'B' },
  "But this time you ate 3 pieces.": { style: 'B' },
  "So how do we write 3 of them?": { style: 'B' },
  "The bottom number counts all the equal pieces, and the top number counts the pieces you have.": { style: 'B' },
  "Look at the whole sandwich.": { style: 'B' },
  "It is still cut into 4 equal pieces. Did eating change that? No.": { style: 'B' },
  "So the bottom number is still 4.": { style: 'B' },
  "The 4 is on the bottom. Now count the shaded pieces with me.": { style: 'B' },
  "1, 2, 3.": { style: 'B' },
  "You have 3 pieces, so the top number is 3.": { style: 'B' },
  "Put the two numbers together. That's 3/4.": { style: 'B' },
  "We say it out loud as three fourths.": { style: 'B' },
  "It means 3 of 4 equal pieces, the part you ate.": { style: 'B' },
  "Don't put the piece that is LEFT on the bottom.": { style: 'B+' },
  "1 piece is left, but the sandwich was cut into 4. The bottom counts all the pieces, so it is 3/4.": { style: 'B+' },
  // ── g3m5-t4 ──
  "This one is different. There's no sandwich, just a path from home to the park.": { style: 'B' },
  "There are no pieces to pick up and count.": { style: 'B' },
  "So how do we find 3 of the 4 parts?": { style: 'B' },
  "The space from 0 to 1 is one whole, so cut it into equal jumps and count the jumps from 0.": { style: 'B' },
  "The path from 0 all the way to 1 is one whole.": { style: 'B' },
  "Cut it into 4 equal jumps.": { style: 'B' },
  "Every jump is the same size, so each one is 1/4.": { style: 'B' },
  "Put your finger on 0.": { style: 'B' },
  "Now jump with me. 1/4, 2/4, 3/4.": { style: 'B' },
  "That's 3 jumps. You land on 3/4.": { style: 'B' },
  "Every mark on this line has a name.": { style: 'B' },
  "The mark after 3 jumps is 3/4.": { style: 'B' },
  "Is 3/4 a real number? Yes, just like 0 and 1 are.": { style: 'B' },
  "Jumps of DIFFERENT sizes are not fourths.": { style: 'B+' },
  "Every jump from 0 to 1 must be the same size. Only then do 3 jumps land on 3/4.": { style: 'B+' },
  // ── g3m5-t5 ── ("Here's the part people mix up." and "Okay. Your turn." share g5m1's rows)
  "One bar shows 1/2, the other 2/4.": { style: 'B' },
  "Every number is different. So does one bar have more chocolate?": { style: 'B' },
  "Look at the bars, not the numbers.": { style: 'B' },
  "You can cut the same amount into smaller pieces, and the amount stays the same.": { style: 'B' },
  "Start with one bar, cut into 2 equal pieces.": { style: 'B' },
  "Shade 1 of the 2. That's 1/2.": { style: 'B' },
  "Now cut each piece in 2.": { style: 'B' },
  "There are 4 pieces now, and 2 are shaded. That's 2/4.": { style: 'B' },
  "Did we add chocolate? No, and none was eaten.": { style: 'B' },
  "Put the two bars one above the other.": { style: 'B' },
  "Look where the shading stops. Both stop at the same place.": { style: 'B' },
  "So 1/2 and 2/4 are the same amount. Nobody has more.": { style: 'B' },
  "Don't change just ONE number. 1/2 is not 1/4.": { style: 'B+' },
  "Smaller pieces means you need more of them. So 1/2 = 2/4.": { style: 'B+' },
  // ── g3m5-t6 ── ("Here's the part people mix up." and "Okay. Your turn." share g5m1's rows)
  "4 slices were eaten.": { style: 'B' },
  "So is that 4 pizzas? No.": { style: 'B' },
  "It was one pizza the whole time, cut into 4 slices.": { style: 'B' },
  "When the top and bottom numbers are the same, you have all the pieces, and that is 1 whole.": { style: 'B' },
  "Count the slices with me.": { style: 'B' },
  "1/4, 2/4, 3/4, 4/4.": { style: 'B' },
  "That's all 4 of the 4 slices.": { style: 'B' },
  "Look at the pizza now.": { style: 'B' },
  "Every slice is gone, and nothing is left over.": { style: 'B' },
  "So 4/4 is 1 whole pizza.": { style: 'B' },
  "It works however you cut it.": { style: 'B' },
  "Cut a bar into 6 equal pieces, and all 6 make 6/6.": { style: 'B' },
  "Cut one into 2, and both pieces make 2/2.": { style: 'B' },
  "Each one is 1 whole.": { style: 'B' },
  "Bigger numbers do not mean MORE here. 8/8 is not more than 4/4.": { style: 'B+' },
  "Both are all the pieces, so both are 1 whole.": { style: 'B+' },
  // ── g3m5-t7 ── ("Here's the part people mix up." and "Okay. Your turn." share g5m1's rows)
  "Ana ate 3/8. Ben ate 5/8.": { style: 'B' },
  "Both bottom numbers are 8. So how can we tell who ate more?": { style: 'B' },
  "When the pieces are the same size, more pieces is more, so just compare the top numbers.": { style: 'B' },
  "Look at the two pizzas.": { style: 'B' },
  "Both are cut into 8 equal slices.": { style: 'B' },
  "So every slice is the same size, on both pizzas.": { style: 'B' },
  "Now just count.": { style: 'B' },
  "Ana has 3 slices. Ben has 5 slices.": { style: 'B' },
  "5 same-size slices are more than 3. So Ben ate more.": { style: 'B' },
  "Now write it with a sign. 5/8 > 3/8.": { style: 'B' },
  "The open side of the sign faces the bigger number.": { style: 'B' },
  "Don't count the slices LEFT on the plate.": { style: 'B+' },
  "Ana left 5 slices, but she ate only 3. Count the slices each one ate.": { style: 'B+' },
  // ── g3m5-t8 ── ("Here's the part people mix up." and "Okay. Your turn." share g5m1's rows)
  "8 is a bigger number than 3.": { style: 'B' },
  "So is 1/8 bigger than 1/3? No.": { style: 'B' },
  "This time, the bigger number gives the smaller piece.": { style: 'B' },
  "When you take the same number of pieces, the one cut into fewer pieces is more, because its pieces are bigger.": { style: 'B' },
  "Take a bar and cut it into 3 equal pieces.": { style: 'B' },
  "Only 3 pieces, so each one is big.": { style: 'B' },
  "Now cut a bar the same size into 8 equal pieces.": { style: 'B' },
  "Each piece is much smaller.": { style: 'B' },
  "More cuts, smaller pieces.": { style: 'B' },
  "Take 2 pieces from each. That's 2/3 and 2/8.": { style: 'B' },
  "Same number of pieces, but the pieces of 3 are bigger.": { style: 'B' },
  "So 2/3 > 2/8.": { style: 'B' },
  "Don't pick the BIGGER bottom number.": { style: 'B+' },
  "A bigger bottom number means more cuts, so smaller pieces. So 1/3 > 1/8.": { style: 'B+' },
}
