/**
 * How g3m6's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G3M6_VOICE: Record<string, VoiceLine> = {
  // ── g3m6-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Count Mia's stars. There are 3.": { style: 'B' },
  "So did she read 3 books? No.": { style: 'B' },
  "Look under the graph. It says each star is 2 books.": { style: 'B' },
  "Each star stands for 2 books, so count the stars by 2s, and a half star is 1.": { style: 'B' },
  "Look at Mia's row.": { style: 'B' },
  "Count her stars by 2s, one star at a time.": { style: 'B' },
  "2, 4, 6. So Mia read 6 books.": { style: 'B' },
  "Now Ava. She has 2 stars and a half star.": { style: 'B' },
  "Count the whole stars. 2, 4.": { style: 'B' },
  "Half a star is half of 2, so it is 1 more. Ava read 5 books.": { style: 'B' },
  "How many more books did Mia read than Leo?": { style: 'B' },
  "Mia read 6. Leo has 2 stars. 2, 4. So Leo read 4.": { style: 'B' },
  "How many more means we subtract. 6 − 4 = 2. Mia read 2 more books.": { style: 'B' },
  "Don't count each star as ONE book.": { style: 'B+' },
  "Mia's 3 stars are 6 books, not 3. Every star is 2.": { style: 'B+' },
  // ── g3m6-t2 ── (its "Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Count the lines up the grapes bar. It is 7 lines tall.": { style: 'B' },
  "So did 7 kids choose grapes? No.": { style: 'B' },
  "Look at the numbers up the side. They go 0, 5, 10, 15. Every line is 5 kids.": { style: 'B' },
  "Go from the top of the bar straight across to the numbers on the side, and check what they count by.": { style: 'B' },
  "Put your finger on the top of the grapes bar.": { style: 'B' },
  "Slide it straight across to the side. It lands on 35.": { style: 'B' },
  "So 35 kids chose grapes.": { style: 'B' },
  "Now the pears.": { style: 'B' },
  "Top of the bar, straight across.": { style: 'B' },
  "It lands on 15. So 15 kids chose pears.": { style: 'B' },
  "So, how many more kids chose grapes than pears?": { style: 'B' },
  "Grapes is 35. Pears is 15.": { style: 'B' },
  "How many more means we subtract. 35 − 15 = 20. So 20 more kids chose grapes.": { style: 'B' },
  "Don't count the lines by ONES.": { style: 'B+' },
  "Each line here is 5 kids, so grapes is 35, not 7.": { style: 'B+' },
  // ── g3m6-t3 ── (its "Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Look at the end of the crayon. Does it stop on a number? No.": { style: 'B' },
  "It stops between 2 and 3.": { style: 'B' },
  "So we need a way to say exactly where it stops.": { style: 'B' },
  "Count the whole inches from 0, then add the part of an inch past the last one.": { style: 'B' },
  "Start at 0, at the end of the crayon.": { style: 'B' },
  "Go along. Past 1, past 2, but not to 3.": { style: 'B' },
  "That's 2 whole inches, and a bit more.": { style: 'B' },
  "Now look at the inch from 2 to 3.": { style: 'B' },
  "A middle mark cuts it into 2 equal parts.": { style: 'B' },
  "The crayon stops right on that mark. That's half an inch more.": { style: 'B' },
  "So the crayon is 2 1/2 inches long.": { style: 'B' },
  "Some rulers cut each inch into 4 equal parts. Each part is 1/4 of an inch.": { style: 'B' },
  "This pencil goes past 1, then 3 parts more.": { style: 'B' },
  "So it is 1 3/4 inches long.": { style: 'B' },
  "Don't count every mark as a WHOLE inch.": { style: 'B+' },
  "From 0 to the end are 5 half inches. That's 2 1/2 inches, not 5.": { style: 'B+' },
  // ── g3m6-t4 ── (its "Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Look at the list. The lengths are all jumbled up.": { style: 'B' },
  "Which ones are the same? Which are longer? It's hard to see.": { style: 'B' },
  "So let's build a better picture.": { style: 'B' },
  "Each ✕ is one thing we measured, sitting above its length, so count the ✕s to answer.": { style: 'B' },
  "First draw a line.": { style: 'B' },
  "Write the lengths along it in order, a half inch apart.": { style: 'B' },
  "4, 4 1/2, 5, 5 1/2, 6.": { style: 'B' },
  "Now take the pencils one at a time.": { style: 'B' },
  "Each pencil gets one ✕, above its own length.": { style: 'B' },
  "7 pencils, so 7 ✕s in all.": { style: 'B' },
  "Which pencils are longer than 5 inches? Look to the right of 5.": { style: 'B' },
  "There's no ✕ above 5 1/2, and 1 ✕ above 6.": { style: 'B' },
  "So 1 pencil is longer than 5 inches.": { style: 'B' },
  "Don't count the NUMBERS under the line.": { style: 'B+' },
  "They are lengths, not pencils. Count the ✕s to find how many.": { style: 'B+' },
  // Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts.
  // ── g3m6-t5 ──
  "Every tile has 4 sides.": { style: 'B' },
  "But they don't look the same at all.": { style: 'B' },
  "So is 4 sides enough to tell them apart? No. We have to look closer.": { style: 'B' },
  "Check two things: are all 4 sides the same length, and are all 4 corners square corners?": { style: 'B' },
  "Start with the corners.": { style: 'B' },
  "A square corner is like the corner of a book. We mark it with a small square.": { style: 'B' },
  "The first two tiles have that mark in all 4 corners.": { style: 'B' },
  "Now the sides.": { style: 'B' },
  "A tick on a side means it matches the other sides with a tick.": { style: 'B' },
  "Which tiles have 4 ticks? The first one, and the leaning one.": { style: 'B' },
  "So what is each tile?": { style: 'B' },
  "A square has both, 4 equal sides and 4 square corners.": { style: 'B' },
  "The rectangle has the square corners, but not the equal sides.": { style: 'B' },
  "The leaning tile has the equal sides, but not the square corners.": { style: 'B' },
  "Don't say a square is NOT a rectangle.": { style: 'B+' },
  "It has 4 square corners, so it is a rectangle too.": { style: 'B+' },
  // ── g3m6-t6 ──
  "Where does the fence go? Not across the middle.": { style: 'B' },
  "It goes all the way around the edge.": { style: 'B' },
  "So we need to know how long the whole edge is.": { style: 'B' },
  "The distance around a shape is all of its sides added together.": { style: 'B' },
  "Let's walk it. Start at this corner.": { style: 'B' },
  "5 feet across the top, then 3 feet down.": { style: 'B' },
  "5 feet back, then 3 feet up.": { style: 'B' },
  "We're back where we started.": { style: 'B' },
  "Now add every side you walked.": { style: 'B' },
  "How many is that, 2 or 4? It's 4.": { style: 'B' },
  "5 + 3 + 5 + 3 = 16.": { style: 'B' },
  "So Sam needs 16 feet of fence.": { style: 'B' },
  "Sometimes a side has no number. What is it?": { style: 'B' },
  "In a rectangle, the sides across from each other are the same length.": { style: 'B' },
  "The top is 5 feet, so the bottom is 5 feet too.": { style: 'B' },
  "Don't add just TWO sides.": { style: 'B+' },
  "5 + 3 = 8 only takes you halfway around. Add all 4, and you get 16.": { style: 'B+' },
  // ── g3m6-t7 ──
  "Same fence, so the same room inside? It sounds right.": { style: 'B' },
  "But let's not guess. Let's count and check.": { style: 'B' },
  "Two gardens can have the same fence around them but hold a different number of squares inside.": { style: 'B' },
  "First, are the fences really the same?": { style: 'B' },
  "Walk the long thin garden. 5 + 1 + 5 + 1 = 12.": { style: 'B' },
  "Now the wider one. 4 + 2 + 4 + 2 = 12.": { style: 'B' },
  "Yes. Both fences are 12 feet.": { style: 'B' },
  "Now count the squares inside.": { style: 'B' },
  "The long thin garden is one row of 5. That's 5 squares.": { style: 'B' },
  "The wider garden is 2 rows of 4. That's 8 squares.": { style: 'B' },
  "Same fence, but not the same room inside.": { style: 'B' },
  "One more. A garden 3 feet by 3 feet uses 12 feet of fence too.": { style: 'B' },
  "Inside, it's 3 rows of 3. That's 9 squares.": { style: 'B' },
  "That's the most room of all three.": { style: 'B' },
  "The same fence does NOT mean the same room inside.": { style: 'B+' },
  "12 feet of fence held 5, 8 and 9 squares. So count the squares to check.": { style: 'B+' },
}
