/**
 * How g4m1's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G4M1_VOICE: Record<string, VoiceLine> = {
  // ── g4m1-t1 ── (Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts)
  "Six digits in a row.": { style: 'B' },
  "You could read them one by one. Three, zero, five, four, two, zero.": { style: 'B' },
  "But how many people is that? It doesn't say.": { style: 'B' },
  "Look at the comma.": { style: 'B' },
  'Read the part before the comma, say "thousand" at the comma, then read the last three digits.': { style: 'B' },
  "Cover up everything after the comma. What's left is 305.": { style: 'B' },
  "Read it like a normal number. Three hundred five.": { style: 'B' },
  "Then say thousand. Three hundred five thousand.": { style: 'B' },
  "Now the part after the comma. 420.": { style: 'B' },
  "Read it just as it is. Four hundred twenty.": { style: 'B' },
  "No extra word goes after it.": { style: 'B' },
  "Put the two parts together.": { style: 'B' },
  "Three hundred five thousand, four hundred twenty.": { style: 'B' },
  "That's how many people live in the city.": { style: 'B' },
  "Don't DROP the zero in three hundred five.": { style: 'B+' },
  "35 is not 305. The zero holds the tens place open.": { style: 'B+' },
  // ── g4m1-t2 ──
  "Look at 440. Both first digits are 4.": { style: 'B' },
  "Are they worth the same? No.": { style: 'B' },
  "But how much more is one?": { style: 'B' },
  "Ten of one place make one of the next place to the left, so each place is worth 10 times the place to its right.": { style: 'B' },
  "Take 10 little cubes and snap them together.": { style: 'B' },
  "They make 1 ten. So 1 ten is worth 10 ones.": { style: 'B' },
  "Now snap 10 tens together.": { style: 'B' },
  "They make 1 hundred.": { style: 'B' },
  "See? 10 of one place make 1 of the next.": { style: 'B' },
  "Back to 440. The second 4 is worth 40.": { style: 'B' },
  "The first 4 is one place to the left, so it's worth 400.": { style: 'B' },
  "That's 10 times as much.": { style: 'B' },
  "Don't TAKE AWAY to find how many times.": { style: 'B+' },
  "That gives 360. Count the 40s. 400 is 10 groups of 40.": { style: 'B+', say: "That gives 360. Count the forties. 400 is 10 groups of 40." },
  // ── g4m1-t3 ──
  "City B has a 9 and an 8. Big digits.": { style: 'B' },
  "So does City B have more? Not so fast.": { style: 'B' },
  "Big digits in small places can trick you.": { style: 'B' },
  "Line the numbers up by place, and the first place from the left where the digits differ decides which is bigger.": { style: 'B' },
  "So put both numbers in a chart.": { style: 'B' },
  "Every digit goes under its own place.": { style: 'B' },
  "Now we can compare straight down.": { style: 'B' },
  "Start at the left, the biggest place.": { style: 'B' },
  "Ten thousands: 4 and 4. The same, so keep going.": { style: 'B' },
  "Thousands: 8 and 6. They're different. This place decides.": { style: 'B' },
  "8 thousands is more than 6 thousands.": { style: 'B' },
  "So City A has more. 48,250 is greater than 46,980.": { style: 'B' },
  "The digits after that don't matter at all.": { style: 'B' },
  "Don't just compare the FIRST digits.": { style: 'B+' },
  "9,870 starts with 9, but it has no ten thousands.": { style: 'B+' },
  "10,200 does, so it's bigger.": { style: 'B+' },
  // Screen 8: the blank between the two numbers is read as "blank".
  "Now you try. Pick the sign that makes it true: 57,340 __ 57,290 Line up the places. Find the first place where the digits are different.": { style: 'A', say: "Now you try. Pick the sign that makes it true. 57,340, blank, 57,290. Line up the places. Find the first place where the digits are different." },
  "Try a new one. Pick the sign that makes it true: 63,105 __ 63,150": { style: 'A', say: "Try a new one. Pick the sign that makes it true. 63,105, blank, 63,150." },
  // ── g4m1-t4 ──
  "You could cross out the last three digits.": { style: 'B' },
  "36,420 becomes 36,000.": { style: 'B' },
  "But try 36,720. It becomes 36,000 too.": { style: 'B' },
  "Is that right? No. It's closer to 37,000.": { style: 'B' },
  "A number rounds to the closer of the two round numbers it sits between, and the exact middle rounds up.": { style: 'B' },
  "Look at 36,420.": { style: 'B' },
  "It's more than 36,000 and less than 37,000.": { style: 'B' },
  "So those are the two ends of the line.": { style: 'B' },
  "Now find the middle. Halfway from 36,000 to 37,000 is 36,500.": { style: 'B' },
  "Has 36,420 reached it? Not yet.": { style: 'B' },
  "It's still closer to 36,000.": { style: 'B' },
  "So 36,420 rounds to 36,000. The news says about 36,000 fans.": { style: 'B' },
  "Quick check. The digit after the thousands is 4, and less than 5 rounds down.": { style: 'B' },
  "Exactly in the middle, don't round DOWN.": { style: 'B+' },
  "36,500 is halfway, and halfway goes up, to 37,000.": { style: 'B+' },
}
