/**
 * How g4m2's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G4M2_VOICE: Record<string, VoiceLine> = {
  // Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts.
  // ── g4m2-t1 ──
  "Can we just add them? 3 + 4 is 7.": { style: 'B' },
  "Wait. The 4 doesn't mean 4 more stickers.": { style: 'B' },
  "It means Sam has what Ann has, 4 times over.": { style: 'B' },
  "Times as many means copies, so 4 times as many as 3 is 4 × 3.": { style: 'B' },
  "Look. Here is Ann's bar, with her 3 stickers.": { style: 'B' },
  "This one bar is the size we will copy.": { style: 'B' },
  "Now Sam. How many of Ann's bars does he get? 4.": { style: 'B' },
  "One copy, two, three, four.": { style: 'B' },
  "That's 4 copies of 3, side by side.": { style: 'B' },
  "4 copies of 3 is what 4 × 3 means.": { style: 'B' },
  "Count by 3s. 3, 6, 9, 12.": { style: 'B' },
  "So 4 × 3 = 12. Sam has 12 stickers.": { style: 'B' },
  "Don't ADD 3 and 4.": { style: 'B+' },
  "That gives 7, but Sam gets 4 copies of 3. So multiply, 4 × 3 = 12.": { style: 'B+' },
  // ── g4m2-t2 ──
  "Here is one way. 3 rows of 4 uses every tile.": { style: 'B' },
  "Is that the only way? No. 12 tiles make other rectangles too.": { style: 'B' },
  "Guess, and it's easy to miss one.": { style: 'B' },
  "Each rectangle that uses every tile shows a pair of numbers that multiply to make the total.": { style: 'B' },
  "So go in order. 1 row of 12 is 1 × 12.": { style: 'B' },
  "2 rows of 6 is 2 × 6.": { style: 'B' },
  "Both use all 12 tiles, so both are pairs.": { style: 'B' },
  "3 rows of 4 works too. That's 3 × 4 = 12.": { style: 'B' },
  "What about 4 rows of 3? It's the same one, turned.": { style: 'B' },
  "So we don't count it twice.": { style: 'B' },
  "Try 5 in a row. 5, 10, then only 2.": { style: 'B' },
  "The last row is short, so 5 is not in a pair.": { style: 'B' },
  "That leaves 3 pairs for 12. 1 and 12, 2 and 6, 3 and 4.": { style: 'B' },
  "Don't FORGET the one long row.": { style: 'B+' },
  "1 row of 12 is a pair too. Every number has that pair.": { style: 'B+' },
  // ── g4m2-t3 ──
  "She tries 2 rows. Is there a gap? Yes, one spot is empty.": { style: 'B' },
  "So 2 rows doesn't work for 7.": { style: 'B' },
  "Some numbers just won't make a second rectangle.": { style: 'B' },
  "Some numbers make only one rectangle, one long row, and others make more than one.": { style: 'B' },
  "Let's test 7. 2 rows leaves a short row.": { style: 'B' },
  "3 rows leaves a short row too, and so do 4, 5 and 6.": { style: 'B' },
  "So 7 makes just one rectangle, the long row.": { style: 'B' },
  "Now try 6. 1 long row of 6 works.": { style: 'B' },
  "2 rows of 3 works too.": { style: 'B' },
  "So 6 makes more than one rectangle.": { style: 'B' },
  "So 7 makes one rectangle, and 6 makes more than one.": { style: 'B' },
  "Is there a number in between? No.": { style: 'B' },
  "Every number bigger than 1 is one kind or the other.": { style: 'B' },
  "Being odd does NOT mean only one rectangle.": { style: 'B+' },
  "9 is odd, but 3 rows of 3 uses all 9. So test the rows, every time.": { style: 'B+' },
  // ── g4m2-t4 ──
  "Could you count every space? 1, 2, 3, 4, then start again.": { style: 'B' },
  "That works, but it's slow, and easy to lose your place.": { style: 'B' },
  "The frog skips the numbers in between, and so can we.": { style: 'B' },
  "Each landing is the jump times the number of jumps so far.": { style: 'B' },
  "Look. The frog starts at 0 and jumps 4.": { style: 'B' },
  "It jumps 4 again, and again.": { style: 'B' },
  "It lands on 4, then 8, then 12.": { style: 'B' },
  "Now count the jumps. 1 jump lands on 1 × 4.": { style: 'B' },
  "2 jumps land on 2 × 4, and 3 jumps land on 3 × 4.": { style: 'B' },
  "See the pattern? The number of jumps, times 4, is the landing.": { style: 'B' },
  "So where is the 6th landing? You don't have to count every jump.": { style: 'B' },
  "6 jumps of 4 is 6 × 4.": { style: 'B' },
  "6 × 4 = 24, so the frog lands on 24.": { style: 'B' },
  "0 is NOT a landing.": { style: 'B+' },
  "The frog starts there, before it jumps. So the 1st landing is 4.": { style: 'B+' },
  // ── g4m2-t1..t4: hints the voice cannot read as written (the " …" trail) ──
  "Count by 3s: 3, 6, 9 … Do you land exactly on 15?": { style: 'A', say: "Count by 3s. 3, 6, 9, and keep going. Do you land exactly on 15?" },
  "The 5th landing is 5 × 3. Count by 3s: 3, 6, 9 …": { style: 'A', say: "The 5th landing is 5 times 3. Count by 3s. 3, 6, 9, and keep going." },
  "The 4th landing is 4 × 6. Count by 6s: 6, 12 …": { style: 'A', say: "The 4th landing is 4 times 6. Count by 6s. 6, 12, and keep going." },
  // ── g4m2-t5 ── ("Here's the part people mix up." and "Okay. Your turn." share g5m1's rows)
  "You could count by 10s, 34 times over.": { style: 'B' },
  "That's a lot of counting.": { style: 'B' },
  "Is there a faster way? Yes. Watch the digits.": { style: 'B' },
  "Each zero in 10, 100 or 1,000 slides every digit one place to the left.": { style: 'B' },
  "Start with 10. One zero, so every digit slides one place left.": { style: 'B' },
  "The 3 tens become 3 hundreds. The 4 ones become 4 tens.": { style: 'B' },
  "The ones place is empty, so a 0 fills it. That's 340 pencils.": { style: 'B', say: "The ones place is empty, so a zero fills it. That's 340 pencils." },
  "Now 100. Two zeros, so every digit slides two places.": { style: 'B' },
  "The 3 lands in the thousands, the 4 in the hundreds, and two 0s fill the rest. That's 3,400.": { style: 'B', say: "The 3 lands in the thousands, the 4 in the hundreds, and two zeros fill the rest. That's 3,400." },
  "And 1,000? Three zeros, so three places.": { style: 'B' },
  "That's 34,000. See the pattern? One more zero, one more place.": { style: 'B' },
  "34 × 100 is not 340. Don't slide just ONE place.": { style: 'B+' },
  "Two zeros means two places. That's 3,400.": { style: 'B+' },
  // ── g4m2-t6 ── ("Here's the part people mix up." and "Okay. Your turn." share g5m1's rows)
  "You know 4 × 3 = 12.": { style: 'B' },
  "But each pack has 30 cards, not 3.": { style: 'B' },
  "So is the answer 12? No, it has to be much bigger.": { style: 'B' },
  "Think of 30 as 3 tens, multiply 4 × 3 tens, then turn the tens into a number.": { style: 'B' },
  "Look at one pack. 30 cards is 3 tens.": { style: 'B' },
  "4 packs is 4 groups of 3 tens.": { style: 'B' },
  "Now multiply the tens. 4 × 3 = 12, so that's 12 tens.": { style: 'B' },
  "It's the fact you already know. We're just counting tens, not ones.": { style: 'B' },
  "How much is 12 tens? 10 tens make 1 hundred.": { style: 'B' },
  "The 2 tens left make 20. 100 and 20 make 120. So there are 120 cards.": { style: 'B' },
  "Don't DROP the tens. 4 × 30 is not 12.": { style: 'B+' },
  "12 tens is 120, so 4 × 30 = 120.": { style: 'B+' },
  // ── g4m2-t7 ── ("Here's the part people mix up." and "Okay. Your turn." share g5m1's rows)
  "You could hand them out one sticker at a time. That would take a long while.": { style: 'B' },
  "Is there a faster way? Yes. The stickers already come in tens.": { style: 'B' },
  "Share the tens, then turn the tens back into a number.": { style: 'B' },
  "Look. 80 stickers is 8 sheets of 10.": { style: 'B' },
  "That's 8 tens. So we share sheets, not single stickers.": { style: 'B' },
  "Give each of the 4 friends one sheet. Then go around again.": { style: 'B' },
  "8 sheets shared by 4 is 2 sheets each. So 8 tens ÷ 4 = 2 tens.": { style: 'B' },
  "Now turn the tens back into a number. 2 tens is 20.": { style: 'B' },
  "So 80 ÷ 4 = 20. Each friend gets 20 stickers.": { style: 'B' },
  "Don't DROP the tens at the end. 80 ÷ 4 is not 2.": { style: 'B+' },
  "Each friend gets 2 tens, and 2 tens is 20.": { style: 'B+' },
  // ── g4m2-t8 ── ("Here's the part people mix up." and "Okay. Your turn." share g5m1's rows)
  "Let's count by 4s. 4, 8, 12, 16.": { style: 'B' },
  "Did you catch that? 16 is past 14.": { style: 'B' },
  "So the pages won't come out even. What do we do?": { style: 'B' },
  "Make as many full groups as you can, and what is left is too few for another group.": { style: 'B' },
  "Look. Put 4 stickers on the first page. That page is full.": { style: 'B' },
  "Keep going. 4, then 8, then 12. That's 3 full pages.": { style: 'B' },
  "3 pages used 12 stickers, so 2 are still in your hand.": { style: 'B' },
  "Can 2 fill another page? No, a page needs 4. So they're left over.": { style: 'B' },
  "So 14 ÷ 4 gives 3 full pages, with 2 left over.": { style: 'B' },
  "You can fill 3 pages all the way.": { style: 'B' },
  "Don't STOP with 6 left. 6 can fill another page.": { style: 'B+' },
  "That's 3 pages, with 2 left.": { style: 'B+' },
}
