/**
 * How g4m3's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G4M3_VOICE: Record<string, VoiceLine> = {
  // Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts.
  // ── g4m3-t1 ──
  "The floor is 16 by 3, so we need 16 × 3.": { style: 'B' },
  "Do you know that one by heart? Most people don't.": { style: 'B' },
  "But you do know 10 × 3. And you know 6 × 3.": { style: 'B' },
  "Break the big number into tens and ones, multiply each part, then add the parts.": { style: 'B' },
  "16 is 10 and 6.": { style: 'B' },
  "So I cut the floor right after 10 feet.": { style: 'B' },
  "Now there are two smaller pieces, 10 by 3 and 6 by 3.": { style: 'B' },
  "Now find each piece.": { style: 'B' },
  "The first piece is 10 × 3. That's 30.": { style: 'B' },
  "The second piece is 6 × 3. That's 18.": { style: 'B' },
  "Now put the two pieces back together.": { style: 'B' },
  "30 + 18 = 48. So 16 × 3 = 48.": { style: 'B' },
  "The floor is 48 square feet.": { style: 'B' },
  "Don't STOP at 30.": { style: 'B+' },
  "10 × 3 is only part of the floor. Add the other piece, and 30 + 18 = 48.": { style: 'B+' },
  // ── g4m3-t2 ──
  "342 × 6 is not in your times tables.": { style: 'B' },
  "You could add 342, six times. But that's slow.": { style: 'B' },
  "Is there a faster way? Yes. Break it up by place.": { style: 'B' },
  "Break the number into hundreds, tens and ones, multiply each part, then add all the parts.": { style: 'B' },
  "Look at 342. The 3 is 3 hundreds, so it's 300.": { style: 'B' },
  "The 4 is 4 tens, so it's 40. And the 2 is just 2.": { style: 'B' },
  "So 342 is 300 and 40 and 2.": { style: 'B' },
  "Start with the biggest part. 300 × 6 is 18 hundreds, so that's 1,800.": { style: 'B' },
  "Next, 40 × 6. That's 24 tens, or 240.": { style: 'B' },
  "Last, 2 × 6 = 12.": { style: 'B' },
  "Now add every part. 1,800 + 240 + 12 = 2,052.": { style: 'B' },
  "So 342 × 6 = 2,052.": { style: 'B' },
  "There are 2,052 seats on the train.": { style: 'B' },
  "Don't FORGET the 2 ones.": { style: 'B+' },
  "Without the 12, you get 2,040. Add every part, and it's 2,052.": { style: 'B+' },
  // ── g4m3-t3 ──
  "You could break 164 into 100, 60 and 4.": { style: 'B' },
  "That works, but it's a lot of writing.": { style: 'B' },
  "Is there a shorter way? Yes. Stack it in columns.": { style: 'B' },
  "Start at the ones and move left, and when a place makes 10 or more, write the ones and carry the tens to the next place.": { style: 'B' },
  "Ones first. 4 × 3 = 12.": { style: 'B' },
  "That's 1 ten and 2 ones. Write the 2 under the ones.": { style: 'B' },
  "Carry the 1 ten up to the top of the tens.": { style: 'B' },
  "Now the tens. 6 × 3 = 18, plus the 1 you carried is 19.": { style: 'B' },
  "Write the 9, and carry the 1 to the hundreds.": { style: 'B' },
  "Last, the hundreds. 1 × 3 = 3, plus the 1 you carried is 4.": { style: 'B' },
  "So 164 × 3 = 492 crayons.": { style: 'B' },
  "Don't FORGET the number you carried.": { style: 'B+' },
  "Without the carries, you get 382. Multiply first, then add the carry.": { style: 'B+' },
  // ── g4m3-t4 ──
  "Last time, one number was big. Now both are.": { style: 'B' },
  "Break only the 23, and you still need 20 × 14.": { style: 'B' },
  "Is that any easier? Not really. So break both.": { style: 'B' },
  "Break both numbers into tens and ones, multiply every part by every part, then add all four pieces.": { style: 'B' },
  "23 is 20 and 3. 14 is 10 and 4.": { style: 'B' },
  "So I cut the garden both ways, across and down.": { style: 'B' },
  "Look. Four smaller pieces.": { style: 'B' },
  "One at a time. 20 × 10 = 200, and 3 × 10 = 30.": { style: 'B' },
  "20 × 4 = 80. And the little corner, 3 × 4 = 12.": { style: 'B' },
  "Every piece is part of the garden, so add all four.": { style: 'B' },
  "200 + 30 + 80 + 12 = 322.": { style: 'B' },
  "So 23 × 14 = 322. The garden is 322 square feet.": { style: 'B' },
  "Don't multiply ONLY tens by tens and ones by ones.": { style: 'B+' },
  "That leaves two pieces out, and you get 212. Add all four, and it's 322.": { style: 'B+' },
}
