/**
 * How g4m3's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G4M3_VOICE: Record<string, VoiceLine> = {
  // ── g4m3-t5 ── ("Here's the part people mix up." and "Okay. Your turn." share g5m1's rows in t5–t8, t8's big idea shares an existing row)
  "The rug is 4 feet wide, so its length is 84 ÷ 4.": { style: 'B' },
  "Do you know 84 ÷ 4 by heart? Most people don't.": { style: 'B' },
  "It's too big to share out all in one go.": { style: 'B' },
  "Break the number into parts that are easy to share, divide each part, then add the answers.": { style: 'B' },
  "84 is 80 and 4.": { style: 'B' },
  "Why those two? Because 80 and 4 both share by 4 easily.": { style: 'B' },
  "So cut the rug into an 80 piece and a 4 piece.": { style: 'B' },
  "Share each piece on its own.": { style: 'B' },
  "80 ÷ 4 = 20, because 4 × 20 = 80.": { style: 'B' },
  "And 4 ÷ 4 = 1.": { style: 'B' },
  "So one piece is 20 feet long, and the other is 1 foot.": { style: 'B' },
  "Now push the pieces back together.": { style: 'B' },
  "20 + 1 = 21.": { style: 'B' },
  "So 84 ÷ 4 = 21. The rug is 21 feet long.": { style: 'B' },
  "Don't share the 80 and FORGET the 4.": { style: 'B+' },
  "20 + 4 = 24 is too long. The 4 gets shared too, so it's 20 + 1 = 21.": { style: 'B+' },
  // ── g4m3-t6 ──
  "Could you break 372 into easy parts? You could.": { style: 'B' },
  "But with a number this big, good parts are hard to find.": { style: 'B' },
  "So here's a way for any number, one digit at a time.": { style: 'B' },
  "Share one place at a time, starting with the biggest: divide, multiply, take away, then bring down the next digit.": { style: 'B' },
  "Start with the hundreds.": { style: 'B' },
  "3 hundreds shared by 3 is 1 hundred each, so write 1 on top.": { style: 'B' },
  "1 × 3 = 3, and 3 − 3 = 0.": { style: 'B' },
  "Nothing is left, so bring the 7 down.": { style: 'B' },
  "Now the tens. How many 3s fit in 7?": { style: 'B' },
  "2, because 2 × 3 = 6. Write 2 on top.": { style: 'B' },
  "7 − 6 = 1. Bring the 2 down beside that 1, and now you have 12.": { style: 'B' },
  "Last, the ones. 12 ÷ 3 = 4, so write 4 on top.": { style: 'B' },
  "4 × 3 = 12, and 12 − 12 = 0.": { style: 'B' },
  "So 372 ÷ 3 = 124. Each friend gets 124 stickers.": { style: 'B' },
  "Don't SKIP the hundreds.": { style: 'B+' },
  "Every place gets a digit on top, so the answer is 124, not 24.": { style: 'B+' },
  // ── g4m3-t7 ──
  "26 ÷ 4 is 6, with 2 left over.": { style: 'B' },
  "But can you order 6 vans and 2 left over? Not really.": { style: 'B' },
  "You have to decide what that 2 means.": { style: 'B' },
  "Divide, then let the question tell you what to do with the leftover: add one more group, leave it out, or give it as the answer.": { style: 'B' },
  "Let's fill the vans, 4 children at a time.": { style: 'B' },
  "6 full vans carry 24 children.": { style: 'B' },
  "And 2 children are still waiting.": { style: 'B' },
  "Now read the question again. How many vans do they need?": { style: 'B' },
  "Those 2 children still need a ride, so add one more van.": { style: 'B' },
  "That's 7 vans.": { style: 'B' },
  "So is the answer always 7? No.": { style: 'B' },
  "How many vans are full? 6. How many children are left over? 2.": { style: 'B' },
  "Same 26 ÷ 4, three answers. The question decides.": { style: 'B' },
  "Don't just COPY down the 6.": { style: 'B+' },
  "6 vans leave 2 children behind. Read the question, then decide.": { style: 'B+' },
  // ── g4m3-t8 ──
  "Can you take 38 away yet? Not yet.": { style: 'B' },
  "Take it away from what? The story never says how many pencils the shop had.": { style: 'B' },
  "That number is hiding.": { style: 'B' },
  "Step one. The shop has 4 boxes, and each box holds 25 pencils.": { style: 'B' },
  "How many pencils is that? 4 × 25 = 100.": { style: 'B' },
  "There it is. The shop started with 100 pencils.": { style: 'B' },
  "Step two. Now we know the shop had 100.": { style: 'B' },
  "Take away the 38 that sold. 100 − 38 = 62.": { style: 'B' },
  "So 62 pencils are left.": { style: 'B' },
  "Does 62 make sense? Let's check.": { style: 'B' },
  "62 left and 38 sold, put back together, make 100.": { style: 'B' },
  "That's all 4 boxes. It fits.": { style: 'B' },
  "Don't STOP after step one.": { style: 'B+' },
  "100 is how many pencils there were, not how many are left. Finish with 100 − 38 = 62.": { style: 'B+' },
}
