/**
 * How g4m4's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G4M4_VOICE: Record<string, VoiceLine> = {
  // Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts.
  // ── g4m4-t1 ──
  // Spoken outside the teach (the turn, read aloud): "?/6" has no spoken form, so she asks it in words.
  "Now you try. Cut every piece of 1/2 into smaller pieces so there are 6 in all. 1/2 = ?/6. What is the missing top number? Find what the bottom was multiplied by. Multiply the top by the same number.": { style: 'A', say: "Now you try. Cut every piece of 1/2 into smaller pieces so there are 6 in all. 1/2 equals how many sixths? What is the missing top number? Find what the bottom was multiplied by. Multiply the top by the same number." },
  "Try a new one. Cut every piece of 1/3 into smaller pieces so there are 6 in all. 1/3 = ?/6. What is the missing top number?": { style: 'A', say: "Try a new one. Cut every piece of 1/3 into smaller pieces so there are 6 in all. 1/3 equals how many sixths? What is the missing top number?" },
  "1/2 and 2/4. Every number is different.": { style: 'B' },
  "So did your friend eat more? Let's cut a bar and watch.": { style: 'B' },
  "Cut every piece into the same number of smaller pieces, and multiply the top and the bottom by that number.": { style: 'B' },
  "Start with 1/2. 1 of 2 pieces is shaded.": { style: 'B' },
  "Now cut each piece down the middle.": { style: 'B' },
  "Now there are 4 pieces, and 2 are shaded. That's 2/4.": { style: 'B' },
  "Did the shading grow or shrink? No. It's the same amount as before.": { style: 'B' },
  "So what happened to the numbers?": { style: 'B' },
  "Every piece became 2, so the bottom is 2 × 2 = 4.": { style: 'B' },
  "The shaded piece became 2 too, so the top is 1 × 2 = 2.": { style: 'B' },
  "So 1/2 = 2/4. You both ate the same amount.": { style: 'B' },
  "Don't change ONLY the bottom number. 1/2 is not 1/4.": { style: 'B+' },
  "1/4 is smaller. Multiply the top by the same number.": { style: 'B+' },
  // ── g4m4-t2 ──
  "Is 4/6 bigger, because 4 is more than 3?": { style: 'B' },
  "Wait. Eighths and sixths are different sizes.": { style: 'B' },
  "So check each one against one half.": { style: 'B' },
  "If one fraction is less than half and the other is more than half, the one more than half is bigger.": { style: 'B' },
  "Start with 3/8. Half of 8 pieces is 4 pieces.": { style: 'B' },
  "You have 3, and 3 is less than 4.": { style: 'B' },
  "So 3/8 is less than half.": { style: 'B' },
  "Now 4/6. Half of 6 pieces is 3 pieces.": { style: 'B' },
  "Your friend has 4, and 4 is more than 3.": { style: 'B' },
  "So 4/6 is more than half.": { style: 'B' },
  "Side by side, 3/8 is less than half, and 4/6 is more.": { style: 'B' },
  "So which one is bigger? The one past half.": { style: 'B' },
  "3/8 < 4/6. Your friend ate more.": { style: 'B' },
  "Don't pick 3/8 just because 8 is BIGGER than 6.": { style: 'B+' },
  "More pieces means smaller pieces. Check each one against half.": { style: 'B+' },
  // ── g4m4-t3 ──
  "3/4 and 5/8. The 5 is bigger than the 3. So does Leo have more?": { style: 'B' },
  "Look. A fourth is a big piece, and an eighth is half of one.": { style: 'B' },
  "So we can't count them against each other yet.": { style: 'B' },
  "Cut the pieces until both fractions use the same size pieces, then compare the top numbers.": { style: 'B' },
  "The eighths are already small, so leave them alone.": { style: 'B' },
  "Cut each fourth into 2 eighths.": { style: 'B' },
  "Now both ribbons are in eighths.": { style: 'B' },
  "How many eighths are shaded now? One, two, three, four, five, six.": { style: 'B' },
  "That's 6/8, the same ribbon as 3/4, just cut smaller.": { style: 'B' },
  "Now the pieces match, so counting is fair.": { style: 'B' },
  "6 eighths is more than 5 eighths.": { style: 'B' },
  "So 3/4 > 5/8. Mia has more ribbon.": { style: 'B' },
  "Don't compare the top numbers BEFORE the pieces match.": { style: 'B+' },
  "5/8 has the bigger top number, but smaller pieces. Cut first, then compare.": { style: 'B+' },
  // ── g4m4-t4 ──
  "5/8 looks like one number. How can it go on two plates?": { style: 'B' },
  "Look again. It's really 5 pieces, and pieces can be moved.": { style: 'B' },
  "A fraction is a group of same-size pieces, so you can split it into groups that add back to it.": { style: 'B' },
  "Count them with me. One, two, three, four, five.": { style: 'B' },
  "Each piece is 1/8 of the pan.": { style: 'B' },
  "So 5/8 is 1/8 + 1/8 + 1/8 + 1/8 + 1/8.": { style: 'B' },
  "Put 2 pieces on the first plate.": { style: 'B' },
  "The other 3 go on the second plate.": { style: 'B' },
  "Did any get lost? No. The pieces only moved.": { style: 'B' },
  "The first plate holds 2/8. The second holds 3/8.": { style: 'B' },
  "Together, that's 5 pieces again.": { style: 'B' },
  "So 5/8 = 2/8 + 3/8.": { style: 'B' },
  "Don't split the BOTTOM number. 5/8 is not 2/4 + 3/4.": { style: 'B+' },
  "Every piece is still an eighth. Split the top number, and keep the 8.": { style: 'B+' },
  // ── g4m4-t5 ──
  "2/8 + 3/8. Should you add every number you see?": { style: 'B' },
  "Look at the 8. It doesn't count the brownies you ate.": { style: 'B' },
  "It tells you the size of each piece.": { style: 'B' },
  "When the pieces are the same size, add the top numbers and keep the bottom number.": { style: 'B' },
  "Here's the pan, cut into 8 equal pieces.": { style: 'B' },
  "You eat 2 of them. That's 2/8.": { style: 'B' },
  "Then you eat 3 more. That's 3/8.": { style: 'B' },
  "Did the pieces change size? No. The pan still has 8 pieces.": { style: 'B' },
  "Now count what you ate. 2 and 3 make 5.": { style: 'B' },
  "Each one is still an eighth of the pan.": { style: 'B' },
  "So 2/8 + 3/8 = 5/8.": { style: 'B' },
  "Don't ADD the bottom numbers. 2/8 + 3/8 is not 5/16.": { style: 'B+' },
  "Sixteenths are smaller pieces, and the pan was never cut that small. Keep the 8.": { style: 'B+' },
}
