/**
 * How g4m5's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G4M5_VOICE: Record<string, VoiceLine> = {
  // ── g4m5-t1 ──
  "Both paths are straight.": { style: 'B' },
  "Cover the ends, and the middles look the same.": { style: 'B' },
  "How do we tell them apart?": { style: 'B' },
  "Look at the ends: a dot means the path stops there, and an arrow means it goes on forever.": { style: 'B' },
  "The string stops at both ends, so each end gets a dot.": { style: 'B' },
  "Two dots make a line segment.": { style: 'B' },
  "The beam starts at the flashlight, so that end gets a dot.": { style: 'B' },
  "It never stops, so the other end gets an arrow.": { style: 'B' },
  "One dot, one arrow. That's a ray.": { style: 'B' },
  "What if both ends get an arrow?": { style: 'B' },
  "Then it goes on forever both ways. That's a line.": { style: 'B' },
  // "Here's the part people mix up." and "Okay. Your turn." share g5m1's rows
  "Don't name a path by how LONG it looks.": { style: 'B+' },
  "A short path with two arrows is still a line. Look at the ends.": { style: 'B+' },
  // ── g4m5-t2 ──
  "Do long rays make a big angle? No.": { style: 'B' },
  "Two long rays can barely open.": { style: 'B' },
  "What counts is how wide they open.": { style: 'B' },
  "Hold the angle up to a square corner: narrower is acute, the same is right, and wider is obtuse.": { style: 'B' },
  "Start with the corner of a book.": { style: 'B' },
  "That square corner is a right angle, and a little square marks it.": { style: 'B' },
  "Now hold a square corner up to this one.": { style: 'B' },
  "It opens less, so it's narrower. That's acute.": { style: 'B' },
  "This one opens more.": { style: 'B' },
  "Look. A whole square corner fits inside, with some extra.": { style: 'B' },
  "Wider than a square corner is obtuse.": { style: 'B' },
  "Long rays do NOT make an angle obtuse.": { style: 'B+' },
  "Only the opening counts. Hold it up to a square corner.": { style: 'B+' },
  // ── g4m5-t3 ──
  "Narrow isn't exact.": { style: 'B' },
  "These two are both narrow, and they're not the same.": { style: 'B' },
  "So how do we say it? With a number.": { style: 'B' },
  "Put the middle of the protractor on the corner and 0 on one ray, then count up to the other ray.": { style: 'B' },
  "This is a protractor. Its edge is marked in degrees.": { style: 'B' },
  "Put its middle on the corner.": { style: 'B' },
  "Turn it so one ray sits on 0.": { style: 'B' },
  "Each small mark is 10 more.": { style: 'B' },
  "Ten, twenty, thirty, forty.": { style: 'B' },
  "The other ray is right on 40.": { style: 'B' },
  "So how far does the ramp open? 40 degrees.": { style: 'B' },
  "The small circle up high means degrees.": { style: 'B' },
  "Don't count from the FAR end.": { style: 'B+' },
  "It has two rows of numbers. Start at the 0 on your ray. That gives 40, not 140.": { style: 'B+' },
  // ── g4m5-t4 ──
  "You could measure each part.": { style: 'B' },
  "But if you know the whole and one part, do you need to? No. You can work it out.": { style: 'B' },
  "When an angle is split into parts, the parts add up to the whole angle.": { style: 'B' },
  "Here's a 40 degree part, and next to it, a 50 degree part.": { style: 'B' },
  "Together they fill the square corner.": { style: 'B' },
  "So how big is the whole? Add the parts.": { style: 'B' },
  "40 + 50 = 90.": { style: 'B' },
  "That's 90 degrees, a right angle.": { style: 'B' },
  "Now turn it around. The whole is 90 degrees, and one part is 40.": { style: 'B' },
  "Take the part away.": { style: 'B' },
  "90 − 40 = 50. The missing part is 50 degrees.": { style: 'B' },
  "When a part is missing, don't ADD it on.": { style: 'B+' },
  "That makes it bigger than the whole. Take the part away.": { style: 'B+' },
  // ── g4m5-t5 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "The rails never cross. The plus sign does.": { style: 'B' },
  "So how do we name each pair?": { style: 'B' },
  "We check the gap, and the corner.": { style: 'B' },
  "Lines with the same gap all the way are parallel, and lines that cross at a square corner are perpendicular.": { style: 'B' },
  "Start with the rails.": { style: 'B' },
  "The gap here, here and here is the same.": { style: 'B' },
  "So they never meet.": { style: 'B' },
  "They are parallel.": { style: 'B' },
  "Now the plus sign.": { style: 'B' },
  "The lines cross, and all 4 corners are square corners.": { style: 'B' },
  "We mark one with a small square.": { style: 'B' },
  "They are perpendicular.": { style: 'B' },
  "What about open scissors?": { style: 'B' },
  "They cross, so they are not parallel.": { style: 'B' },
  "The corners are not square, so they are not perpendicular.": { style: 'B' },
  "They are neither.": { style: 'B' },
  "Not touching does NOT mean parallel.": { style: 'B+' },
  "This gap gets smaller, so they meet farther on.": { style: 'B+' },
  "You checked if the lines meet, and how they meet.": { style: 'B' },
  "You saw the gap between the lines stays the same.": { style: 'B' },
  // ── g4m5-t6 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Count the sides. Every one has 3.": { style: 'B' },
  "Count the corners. 3 again.": { style: 'B' },
  "So what makes them different? The size of their angles.": { style: 'B' },
  "Find the biggest angle: a square corner makes a right triangle, wider makes an obtuse triangle, and narrower makes an acute triangle.": { style: 'B' },
  "Find the biggest angle first.": { style: 'B' },
  "Here it's this corner, with a small square.": { style: 'B' },
  "That's a right angle, 90°.": { style: 'B' },
  "So this is a right triangle.": { style: 'B' },
  "Next one. Its angles are 25°, 35° and 120°.": { style: 'B' },
  "The biggest is 120°.": { style: 'B' },
  "Is that wider than 90°? Yes.": { style: 'B' },
  "So this is an obtuse triangle.": { style: 'B' },
  "Last one. Its angles are 70°, 70° and 40°.": { style: 'B' },
  "Even the biggest, 70°, is narrower than 90°.": { style: 'B' },
  "So this is an acute triangle.": { style: 'B' },
  "Don't name a triangle by a SMALL angle. Every triangle has small ones.": { style: 'B+' },
  "Only the biggest angle names it.": { style: 'B+' },
  "You sorted the triangle by its biggest angle.": { style: 'B' },
  "You found the biggest angle and saw it was narrower than a right angle.": { style: 'B' },
  // ── g4m5-t7 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "All 3 have 4 sides.": { style: 'B' },
  "So is 4 sides a name? No.": { style: 'B' },
  "Look at which sides are parallel.": { style: 'B' },
  "Count the pairs of parallel sides first, then check the sides and corners to find the best name.": { style: 'B' },
  "Take the leaning shelf.": { style: 'B' },
  "Top and bottom are parallel. That's 1 pair.": { style: 'B' },
  "Left and right are parallel too. 2 pairs.": { style: 'B' },
  "So it's a parallelogram.": { style: 'B' },
  "Now the lampshade side.": { style: 'B' },
  "Top and bottom are parallel again.": { style: 'B' },
  "But the other 2 sides lean in, so they would meet.": { style: 'B' },
  "Just 1 pair. It's a trapezoid.": { style: 'B' },
  "What about the table top?": { style: 'B' },
  "2 pairs, and 4 square corners.": { style: 'B' },
  "So it's a rectangle.": { style: 'B' },
  "With 4 equal sides too, it would be a square.": { style: 'B' },
  "Not every leaning shape is a rhombus.": { style: 'B+' },
  "It needs 4 EQUAL sides. The shelf leans, but its sides don't match.": { style: 'B+' },
  "You counted the pairs of parallel sides, then checked the rest.": { style: 'B' },
  "You found only one pair of parallel sides.": { style: 'B' },
  // ── g4m5-t8 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "How can you tell if a fold works?": { style: 'B' },
  "Picture the fold, and check where every part lands.": { style: 'B' },
  "A fold line counts only if the two halves land exactly on top of each other.": { style: 'B' },
  "Fold the house down the dashed line.": { style: 'B' },
  "Wall lands on wall, roof on roof.": { style: 'B' },
  "Nothing sticks out, so this line works.": { style: 'B' },
  "Now try a line across the middle.": { style: 'B' },
  "Fold the top down.": { style: 'B' },
  "The top has a point, and the bottom has square corners.": { style: 'B' },
  "They don't match, so this line does not work.": { style: 'B' },
  "Can a shape have more than one?": { style: 'B' },
  "This rectangle can.": { style: 'B' },
  "Down the middle works, and across the middle works.": { style: 'B' },
  "So it has 2 fold lines.": { style: 'B' },
  "On a long rectangle, corner to corner does NOT work.": { style: 'B+' },
  "Fold it, and the corners stick out.": { style: 'B+' },
  "You folded the shape in your head and checked that the halves match.": { style: 'B' },
  "You saw that the halves would not match on that fold.": { style: 'B' },
}
