/**
 * How g4m6's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G4M6_VOICE: Record<string, VoiceLine> = {
  // ── g4m6-t5 ── ("Here's the part people mix up." and "Okay. Your turn." share g5m1's rows)
  "Look at Kim's 0.5 and Raj's 0.45.": { style: 'B', say: "Look at Kim's zero point five and Raj's zero point four five." },
  "0.45 is longer, and 45 is more than 5. So does Raj drink more?": { style: 'B', say: "Zero point four five is longer, and 45 is more than 5. So does Raj drink more?" },
  "Wait. After the point, digits are pieces of one bottle.": { style: 'B' },
  "Line up the points and compare from the left, so the tenths decide before the hundredths do.": { style: 'B' },
  "A tenth is one full column.": { style: 'B' },
  "Kim's 0.5 has 5 tenths, 5 columns.": { style: 'B', say: "Kim's zero point five has 5 tenths, 5 columns." },
  "Raj's 0.45 has 4 tenths, and 5 loose squares.": { style: 'B', say: "Raj's zero point four five has 4 tenths, and 5 loose squares." },
  "Can 5 loose squares catch up? No.": { style: 'B' },
  "Kim has 50 squares. Raj has 45.": { style: 'B' },
  "So 0.5 is 0.50, and 50 hundredths beats 45.": { style: 'B', say: "So zero point five is zero point five zero, and 50 hundredths beats 45." },
  "Now write it with a sign. 0.5 > 0.45.": { style: 'B', say: "Now write it with a sign. Zero point five is greater than zero point four five." },
  "The open side faces the bigger number. Kim drinks more.": { style: 'B' },
  "Don't pick the number with MORE digits.": { style: 'B+' },
  "Line up the points. 4 tenths is less than 5 tenths.": { style: 'B+' },
  "Who drank more?. Two bottles of juice are the same size. Kim drinks 0.5 of hers. Raj drinks 0.45 of his. Who drinks more?": { style: 'A', say: "Who drank more? Two bottles of juice are the same size. Kim drinks zero point five of hers. Raj drinks zero point four five of his. Who drinks more?" },
  "Now you try. Which sign goes between them? 0.6 ? 0.58 Look at the tenths first.": { style: 'A', say: "Now you try. Which sign goes between zero point six and zero point five eight? Look at the tenths first." },
  "Try a new one. Which sign goes between them? 0.3 ? 0.35": { style: 'A', say: "Try a new one. Which sign goes between zero point three and zero point three five?" },
  "Write 0.6 as 0.60. Now compare 60 hundredths and 58 hundredths.": { style: 'A', say: "Write zero point six as zero point six zero. Now compare 60 hundredths and 58 hundredths." },
  "Put a 0 at the end of 0.3 so both have two places. Then compare.": { style: 'A', say: "Put a zero at the end of zero point three so both have two places. Then compare." },
  "You saw that 0.3 < 0.35 by looking at the hundredths.": { style: 'A', say: "You saw that zero point three is less than zero point three five by looking at the hundredths." },
  // ── g4m6-t6 ──
  "Can we just add 3 and 4 to get 7?": { style: 'B' },
  "A tenth is a whole column. A hundredth is one tiny square.": { style: 'B' },
  "No. The pieces are not the same size.": { style: 'B' },
  "Change the tenths into hundredths, so every piece is the same size, then add.": { style: 'B' },
  "One column holds 10 little squares.": { style: 'B' },
  "So 1 tenth is 10 hundredths.": { style: 'B' },
  "Dad painted 3 columns, that's 30 squares. So 3/10 is 30/100.": { style: 'B' },
  "Now everything is little squares.": { style: 'B' },
  "Dad's 30, and your 4 more. How many is that?": { style: 'B' },
  "34 squares out of 100. That's 34/100.": { style: 'B' },
  "And 34/100 with a point is 0.34.": { style: 'B', say: "And 34 hundredths with a point is zero point three four." },
  "The 3 is Dad's 3 columns. The 4 is your 4 squares.": { style: 'B' },
  "Don't ADD the bottom numbers.": { style: 'B+' },
  "10 and 100 are sizes, not amounts. Change the tenths into hundredths first.": { style: 'B+' },
  // ── g4m6-t7 ──
  "Here is your money. 2 dollars, 3 dimes, 5 pennies.": { style: 'B' },
  "The tag just says $2.35.": { style: 'B', say: "The tag just says two point three five, with a dollar sign." },
  "So which digit counts the dimes, and which the pennies?": { style: 'B' },
  "Dimes are tenths of a dollar and pennies are hundredths, so dimes go first after the point and pennies second.": { style: 'B' },
  "10 dimes make 1 dollar.": { style: 'B' },
  "So one dime is 1/10 of a dollar.": { style: 'B' },
  "Tenths go first after the point. Your 3 dimes make the 3.": { style: 'B' },
  "100 pennies make 1 dollar.": { style: 'B' },
  "So one penny is 1/100 of a dollar.": { style: 'B' },
  "Hundredths go second. Your 5 pennies make the 5.": { style: 'B' },
  "Now put it together.": { style: 'B' },
  "Dollars, then the point, then dimes, then pennies.": { style: 'B' },
  "That's $2.35, like the tag. You have just enough.": { style: 'B' },
  "Don't put 5 cents RIGHT after the point.": { style: 'B+' },
  "That place is for dimes, so $0.5 is 50 cents. 5 cents is $0.05.": { style: 'B+', say: "That place is for dimes, so zero point five dollars is 50 cents. 5 cents is zero point zero five dollars." },
}
