/**
 * How Grade 5 · Module 1's re-voiced lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson
 * says it — that is what the clip is looked up by. `say` is what the voice model reads: the same words with
 * symbols spelt out (no tags, no ellipses — docs/new-flow/voice.md). A line with no row here renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G5M1_VOICE: Record<string, VoiceLine> = {
  // ── g5m1-t1 ──
  "You could add 40, ten times.": { style: 'B' },
  "That works. But it takes a while, and it's easy to lose count.": { style: 'B' },
  "Is there a faster way? Yes. It's in this chart of places.": { style: 'B' },
  "Slide a digit left and it's worth 10 times as much, slide it right and it's worth 1/10 as much.": { style: 'B' },
  "Look at the places, from the right.": { style: 'B' },
  "10 ones make 1 ten. 10 tens make 1 hundred. 10 hundreds make 1 thousand.": { style: 'B' },
  "See the pattern? Each step to the left is 10 times as much.": { style: 'B' },
  "Look at 40. The 4 is in the tens place.": { style: 'B' },
  "Slide it one place to the left, into the hundreds. That's 400.": { style: 'B' },
  "That's 10 times as much. So a carton holds 400 pencils.": { style: 'B' },
  "Now go back the other way. One box is 1/10 of a carton.": { style: 'B' },
  "Slide the 4 in 400 one place to the right, back to the tens. That's 40.": { style: 'B' },
  "So 1/10 of 400 is 40 pencils.": { style: 'B' },
  "Here's the part people mix up.": { style: 'B+' },
  "Ten times as much does not mean ADD 10.": { style: 'B+' },
  "That gives 50. Every digit slides one place to the left.": { style: 'B+' },
  "Okay. Your turn.": { style: 'B' },
  "You did it! You slid the 7 one place to the left, and now it's worth 10 times as much.": { style: 'B' },
  "Yes! You slid the 3 one place to the left, from 300 all the way to 3,000.": { style: 'B' },
  // ── g5m1-t2 ── (its "Here's the part people mix up." and "Okay. Your turn." share t1's rows)
  "Add 37 one thousand times? That would take all day.": { style: 'B' },
  "There's a faster way. And it works for dividing too.": { style: 'B' },
  "Each zero in 10, 100 or 1,000 slides every digit one place, left to multiply and right to divide.": { style: 'B' },
  "Start with 10. It has one zero.": { style: 'B' },
  "So 37 × 10 slides the 3 and the 7 one place to the left.": { style: 'B' },
  "The ones place is empty now, so a 0 fills it. That's 370.": { style: 'B', say: "The ones place is empty now, so a zero fills it. That's 370." },
  "Now 100. It has two zeros, so the digits slide two places. That's 3,700.": { style: 'B' },
  "1,000 has three zeros, so they slide three places. That's 37,000.": { style: 'B' },
  "So the shop has 37,000 beads.": { style: 'B' },
  "Now go backwards. The shop shares 37,000 beads into 1,000 bags.": { style: 'B' },
  "1,000 still has three zeros. So every digit slides three places — this time to the right.": { style: 'B' },
  "The zeros slide off the end. That's 37 beads in each bag.": { style: 'B' },
  "When you divide, don't slide LEFT.": { style: 'B+' },
  "Dividing makes the number smaller, so every digit slides right.": { style: 'B+' },
  "You did it! You counted three zeros and slid every digit three places to the left.": { style: 'B' },
  "Yes! You counted two zeros and slid 29 two places to the left, all the way to 2,900.": { style: 'B' },
  // ── g5m1-t9 ──
  "You could break 23 into 20 and 3, and work out 124 × 20 and 124 × 3.": { style: 'B' },
  "That works, but it's a lot to write.": { style: 'B' },
  "Is there a shorter way? Yes. Stack the numbers in columns.": { style: 'B' },
  "Make a row for the ones, then a row for the tens that starts with a 0, and add the two rows.": { style: 'B', say: "Make a row for the ones, then a row for the tens that starts with a zero, and add the two rows." },
  "Start with the 3 ones. 4 × 3 = 12, so write the 2 and carry the 1.": { style: 'B' },
  "2 × 3 = 6, and the carried 1 makes 7.": { style: 'B' },
  "1 × 3 = 3. So the ones row is 372.": { style: 'B' },
  "Now the 2 in 23. Is it just 2? No, it's 2 tens.": { style: 'B' },
  "So write a 0 in the ones place first.": { style: 'B', say: "So write a zero in the ones place first." },
  "Then 124 × 2 = 248, and the tens row is 2,480.": { style: 'B' },
  "Now add the two rows. 372 + 2,480 = 2,852.": { style: 'B' },
  "Look. Those rows are 124 × 3 and 124 × 20, the two parts from before.": { style: 'B' },
  "So there are 2,852 chairs in the hall.": { style: 'B' },
  "In the tens row, don't FORGET the 0.": { style: 'B+', say: "In the tens row, don't FORGET the zero." },
  "Without it, the row is 248, not 2,480.": { style: 'B+' },
  // ── g5m1-t10 ──
  "With 23, you made two rows, one for the ones and one for the tens.": { style: 'B' },
  "But 123 has three digits. What about the 1 hundred?": { style: 'B' },
  "It gets a row of its own.": { style: 'B' },
  "Make a row for each digit of the bottom number, give each new row one more 0, then add all the rows.": { style: 'B', say: "Make a row for each digit of the bottom number, give each new row one more zero, then add all the rows." },
  "Start with the 3 ones. 231 × 3.": { style: 'B' },
  "1 × 3 = 3, 3 × 3 = 9 and 2 × 3 = 6. So the ones row is 693.": { style: 'B' },
  "Next, the 2 in 123. That 2 means 2 tens, so write one 0 first.": { style: 'B', say: "Next, the 2 in 123. That 2 means 2 tens, so write one zero first." },
  "Then 231 × 2 = 462. The tens row is 4,620.": { style: 'B' },
  "Last, the 1 in 123. It means 1 hundred, so this row starts with two 0s.": { style: 'B', say: "Last, the 1 in 123. It means 1 hundred, so this row starts with two zeros." },
  "Then 231 × 1 = 231. The hundreds row is 23,100.": { style: 'B' },
  "Add all three rows. 693 + 4,620 + 23,100 = 28,413 bottles.": { style: 'B' },
  "The hundreds row starts with TWO 0s.": { style: 'B+', say: "The hundreds row starts with TWO zeros." },
  "The 1 in 123 is 1 hundred, so the row is 23,100, not 231.": { style: 'B+' },
  "Make one row for each digit of 123: the 3 ones, the 2 tens and the 1 hundred.": { style: 'A', say: "Make one row for each digit of 123, the 3 ones, the 2 tens and the 1 hundred." },
  "Make one row for each digit of 213: the 3 ones, the 1 ten and the 2 hundreds.": { style: 'A', say: "Make one row for each digit of 213, the 3 ones, the 1 ten and the 2 hundreds." },
  // ── g5m1-t11 ──
  "You already know how to work out 406 × 35.": { style: 'B' },
  "But with big numbers, one small slip, like a lost 0, throws the answer far off.": { style: 'B', say: "But with big numbers, one small slip, like a lost zero, throws the answer far off." },
  "So how do you catch it? Estimate first.": { style: 'B' },
  "Estimate with round numbers first, then multiply the standard way and check that your answer is close.": { style: 'B' },
  "406 is close to 400, and 35 rounds up to 40.": { style: 'B' },
  "400 × 40 = 16,000.": { style: 'B' },
  "So the answer should be somewhere near 16,000.": { style: 'B' },
  "Now multiply for real. The ones row is 406 × 5 = 2,030.": { style: 'B' },
  "The tens row starts with a 0. Then 406 × 3 = 1,218, so the row is 12,180.": { style: 'B', say: "The tens row starts with a zero. Then 406 × 3 = 1,218, so the row is 12,180." },
  "Add the rows. 2,030 + 12,180 = 14,210.": { style: 'B' },
  "Now check. Is 14,210 close to 16,000? Yes, so it makes sense.": { style: 'B' },
  "The warehouse ships 14,210 toys.": { style: 'B' },
  "If your answer is far from the estimate, don't KEEP it.": { style: 'B+' },
  "3,248 is nowhere near 16,000, so a row lost its 0. Go back and fix that row.": { style: 'B+', say: "3,248 is nowhere near 16,000, so a row lost its zero. Go back and fix that row." },
  // ── g5m1-t12 ──
  "240 ÷ 60 isn't a fact you know by heart.": { style: 'B' },
  "You could count up by 60s, but that's slow, and one slip changes the answer.": { style: 'B' },
  "Is there a fact hiding inside it? Yes.": { style: 'B' },
  "Think of both numbers in tens, and 240 ÷ 60 becomes 24 tens ÷ 6 tens, the same as 24 ÷ 6.": { style: 'B' },
  "Look at this line. Each small step is 10.": { style: 'B' },
  "Jump 10 tens to 100, 10 more to 200, then 4 more to 240.": { style: 'B' },
  "That's 24 tens in all.": { style: 'B' },
  "Now one bus. It seats 60 students.": { style: 'B' },
  "How many small steps is 60? 6, so 60 is 6 tens.": { style: 'B' },
  "One busload is one jump of 6 tens.": { style: 'B' },
  "So jump 6 tens at a time, from 0 all the way to 240.": { style: 'B', say: "So jump 6 tens at a time, from zero all the way to 240." },
  "That's 4 jumps, because 24 ÷ 6 = 4.": { style: 'B' },
  "So 240 ÷ 60 = 4. The students fill 4 buses.": { style: 'B' },
  "Take the 0 off BOTH numbers, never just one.": { style: 'B+', say: "Take the zero off BOTH numbers, never just one." },
  "Take it off only the 60 and you get 240 ÷ 6, a different problem.": { style: 'B+' },
  // ── g5m1-t13 ──
  "You know your facts up to 10 × 10. But nobody learns the 17s.": { style: 'B' },
  "You could count 17, 34, 51 and on, but it's slow and hard to keep track.": { style: 'B' },
  "Is there a quicker way? Yes, a smart guess.": { style: 'B' },
  "Guess with the nearest ten, then multiply to check, and if a whole group still fits in what is left, add one more.": { style: 'B' },
  "17 is close to 20, so guess with 20s.": { style: 'B' },
  "How many 20s fit into 68? 3 × 20 = 60, and 4 × 20 = 80 is too many.": { style: 'B' },
  "So the guess is 3 teams.": { style: 'B' },
  "Now check with the real team size. 3 × 17 = 51.": { style: 'B' },
  "Take that away. 68 − 51 = 17, so 17 kids are left.": { style: 'B' },
  "Wait. 17 kids left is a whole team, so the guess was too small.": { style: 'B' },
  "Add one more team. 4 × 17 = 68, and no one is left out.": { style: 'B' },
  "So 68 ÷ 17 = 4. The coach makes 4 teams.": { style: 'B' },
  "Don't STOP while a whole group still fits in what's left.": { style: 'B+' },
  "17 left makes one more team, so the answer is 4, not 3.": { style: 'B+' },
  // ── g5m1-t14 ──
  "You usually start with the first digit, or the first two.": { style: 'B' },
  "But 23 doesn't fit into 1, and it doesn't fit into 18 either.": { style: 'B' },
  "If the number you divide by doesn't fit into the first two digits, the answer has one digit, so guess with round numbers and try one less if it's too big.": { style: 'B' },
  "23 doesn't fit into 18 tens, so the answer has no tens.": { style: 'B' },
  "Where does its one digit go? Up over the 4.": { style: 'B' },
  "23 is close to 20. How many 20s fit into 184? 9 × 20 = 180, so guess 9.": { style: 'B' },
  "Now check with the real number. 9 × 23 = 207.": { style: 'B' },
  "That's more than 184, so 9 is too big.": { style: 'B' },
  "So try one less. 8 × 23 = 184.": { style: 'B' },
  "It fits exactly, with 0 left, so write the 8 over the 4.": { style: 'B', say: "It fits exactly, with zero left, so write the 8 over the 4." },
  "184 ÷ 23 = 8. The shop makes 8 bunches.": { style: 'B' },
  "Never KEEP a guess that is too big.": { style: 'B+' },
  "9 × 23 = 207, and that's more than the 184 roses, so try one less.": { style: 'B+' },
}
