/**
 * How Grade 5 · Module 1's re-voiced lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson
 * says it — that is what the clip is looked up by. `say` is what the voice model reads: the same words with
 * symbols spelt out (no tags, no ellipses — docs/new-flow/voice.md). A line with no row here renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G5M1_VOICE: Record<string, VoiceLine> = {
  // ── g5m1-t1 ──
  "You could add 40, ten times.": { style: 'B' },
  "That works. But it takes a while, and it's easy to lose count.": { style: 'B' },
  "Is there a faster way? Yes. It's in this chart of places.": { style: 'B' },
  "Slide a digit left and it's worth 10 times as much, slide it right and it's worth 1/10 as much.": { style: 'B' },
  "Look at the places, from the right.": { style: 'B' },
  "10 ones make 1 ten. 10 tens make 1 hundred. 10 hundreds make 1 thousand.": { style: 'B' },
  "See the pattern? Each step to the left is 10 times as much.": { style: 'B' },
  "Look at 40. The 4 is in the tens place.": { style: 'B' },
  "Slide it one place to the left, into the hundreds. That's 400.": { style: 'B' },
  "That's 10 times as much. So a carton holds 400 pencils.": { style: 'B' },
  "Now go back the other way. One box is 1/10 of a carton.": { style: 'B' },
  "Slide the 4 in 400 one place to the right, back to the tens. That's 40.": { style: 'B' },
  "So 1/10 of 400 is 40 pencils.": { style: 'B' },
  "Here's the part people mix up.": { style: 'B+' },
  "Ten times as much does not mean ADD 10.": { style: 'B+' },
  "That gives 50. Every digit slides one place to the left.": { style: 'B+' },
  "Okay. Your turn.": { style: 'B' },
  "You did it! You slid the 7 one place to the left, and now it's worth 10 times as much.": { style: 'B' },
  "Yes! You slid the 3 one place to the left, from 300 all the way to 3,000.": { style: 'B' },
  // ── g5m1-t2 ── (its "Here's the part people mix up." and "Okay. Your turn." share t1's rows)
  "Add 37 one thousand times? That would take all day.": { style: 'B' },
  "There's a faster way. And it works for dividing too.": { style: 'B' },
  "Each zero in 10, 100 or 1,000 slides every digit one place, left to multiply and right to divide.": { style: 'B' },
  "Start with 10. It has one zero.": { style: 'B' },
  "So 37 × 10 slides the 3 and the 7 one place to the left.": { style: 'B' },
  "The ones place is empty now, so a 0 fills it. That's 370.": { style: 'B', say: "The ones place is empty now, so a zero fills it. That's 370." },
  "Now 100. It has two zeros, so the digits slide two places. That's 3,700.": { style: 'B' },
  "1,000 has three zeros, so they slide three places. That's 37,000.": { style: 'B' },
  "So the shop has 37,000 beads.": { style: 'B' },
  "Now go backwards. The shop shares 37,000 beads into 1,000 bags.": { style: 'B' },
  "1,000 still has three zeros. So every digit slides three places — this time to the right.": { style: 'B' },
  "The zeros slide off the end. That's 37 beads in each bag.": { style: 'B' },
  "When you divide, don't slide LEFT.": { style: 'B+' },
  "Dividing makes the number smaller, so every digit slides right.": { style: 'B+' },
  "You did it! You counted three zeros and slid every digit three places to the left.": { style: 'B' },
  "Yes! You counted two zeros and slid 29 two places to the left, all the way to 2,900.": { style: 'B' },
  // ── g5m1-t15 ──
  "Can you find 312 ÷ 13 with one guess? Not really.": { style: 'B' },
  "13 fits into 31, the first two digits. So the answer has a tens digit and a ones digit.": { style: 'B' },
  "We find them one at a time.": { style: 'B' },
  "Divide the tens first, then bring down the ones and divide again.": { style: 'B' },
  "Start with the 31 tens. How many 13s fit?": { style: 'B', say: "Start with the 31 tens. How many thirteens fit?" },
  "2 × 13 = 26 fits. 3 × 13 = 39 is too many.": { style: 'B' },
  "So write the 2 over the 1, and take away. 31 − 26 = 5.": { style: 'B' },
  "5 tens are left over.": { style: 'B' },
  "Bring down the 2 ones and write it beside the 5. Now there are 52 to divide.": { style: 'B' },
  "Round two. 4 × 13 = 52, so write the 4 over the 2.": { style: 'B' },
  "Take away. 52 − 52 = 0.": { style: 'B' },
  "So 312 ÷ 13 = 24. The store fills 24 cartons.": { style: 'B' },
  "Don't STOP after the tens.": { style: 'B+' },
  "The 2 ones still have to come down. You're done only when every digit has come down.": { style: 'B+' },
  // ── g5m1-t16 ──
  "Where does the answer start?": { style: 'B' },
  "24 doesn't fit into 11, the first two digits of 1,176.": { style: 'B' },
  "Start one place too far left, and every digit lands one place off.": { style: 'B' },
  "Start where the number you divide by first fits, then bring down one digit at a time.": { style: 'B' },
  "Does 24 fit into 1? No. Into 11? No.": { style: 'B' },
  "Into 117, the first three digits? Yes.": { style: 'B' },
  "So the first digit of the answer goes over the 7.": { style: 'B' },
  "How many 24s fit into 117? 4 × 24 = 96 fits, and 5 × 24 = 120 is too many.": { style: 'B', say: "How many twenty-fours fit into 117? 4 times 24 equals 96 fits, and 5 times 24 equals 120 is too many." },
  "Write the 4 over the 7, and take away. 117 − 96 = 21.": { style: 'B' },
  "Then bring down the 6. That makes 216.": { style: 'B' },
  "One more round. 9 × 24 = 216, so write the 9 over the 6.": { style: 'B' },
  "216 − 216 = 0, and there are no digits left to bring down.": { style: 'B' },
  "So 1,176 ÷ 24 = 49. Each kid gets 49 stickers.": { style: 'B' },
  "Don't put the first digit over the second 1. It goes over the 7, the LAST digit of 117.": { style: 'B+' },
  "Over the 1, the answer comes out 490. That's 10 times too many.": { style: 'B+' },
  // ── g5m1-t17 ──
  "You could add every piece: 4 + 2 + 4 + 2 + 4 + 2.": { style: 'B' },
  "That's long. And it hides the best part.": { style: 'B' },
  "What's the same every time? Each bag. They're all 4 + 2.": { style: 'B' },
  "The ( ) keep one bag together, so 3 × (4 + 2) means 3 times as much as 4 + 2.": { style: 'B', say: "The brackets keep one bag together, so 3 times 4 plus 2, all together, means 3 times as much as 4 plus 2." },
  "Start with one bag. 4 apples and 2 pears, so 4 + 2.": { style: 'B' },
  "Put ( ) around it. Now the whole bag stays together.": { style: 'B', say: "Put brackets around it. Now the whole bag stays together." },
  "There are 3 bags, all the same. So write 3 × (4 + 2).": { style: 'B', say: "There are 3 bags, all the same. So write 3 times 4 plus 2, all together." },
  "It means 3 times as much as 4 + 2.": { style: 'B' },
  "One bag is 6, so 3 bags are 18.": { style: 'B' },
  "Now look at 3 × 4 + 2. Is it the same?": { style: 'B' },
  "No. It's 3 bags of 4 apples, and just 2 pears in all.": { style: 'B' },
  "3 × (4 + 2) has 2 pears in every bag, so it's more.": { style: 'B', say: "3 times 4 plus 2, all together, has 2 pears in every bag, so it's more." },
  "Don't DROP the ( ).": { style: 'B+', say: "Don't DROP the brackets." },
  "Without them, there are just 2 pears in all, not 2 in every bag.": { style: 'B+' },
  "Now you try. A fruit stand packs 3 bags. Each bag has 4 apples and 5 pears. Which number sentence shows all the fruit? Keep one bag together inside the ( ). Then show how many bags.": { style: 'A', say: "Now you try. A fruit stand packs 3 bags. Each bag has 4 apples and 5 pears. Which number sentence shows all the fruit? Keep one bag together inside the brackets. Then show how many bags." },
  "What is in one bag? That part goes inside the ( ).": { style: 'A', say: "What is in one bag? That part goes inside the brackets." },
  "What is in one bag? Keep it together inside the ( ).": { style: 'A', say: "What is in one bag? Keep it together inside the brackets." },
  "You kept each bag together with ( ), then showed how many bags.": { style: 'A', say: "You kept each bag together with brackets, then showed how many bags." },
  "You kept 5 apples and 3 pears together in the ( ), then showed 4 bags of them.": { style: 'A', say: "You kept 5 apples and 3 pears together in the brackets, then showed 4 bags of them." },
  // ── g5m1-t18 ──
  "What do the 4, the 6 and the 3 count? What do the × and the + do?": { style: 'B', say: "What do the 4, the 6 and the 3 count? What do the times sign and the plus sign do?" },
  "The board doesn't say.": { style: 'B' },
  "So a story has to give every part a job.": { style: 'B' },
  "Give every number and sign a job in the story, and let the part in ( ) happen first.": { style: 'B', say: "Give every number and sign a job in the story, and let the part in brackets happen first." },
  "The part in ( ) happens first, so it's one thing.": { style: 'B', say: "The part in brackets happens first, so it's one thing." },
  "Make 6 + 3 one bag: 6 red marbles and 3 green.": { style: 'B' },
  "Now the 4 ×. That means 4 of that whole bag.": { style: 'B', say: "Now the 4 times. That means 4 of that whole bag." },
  "So the story is 4 bags, each with 6 red and 3 green.": { style: 'B' },
  "Does the story match the board? Let's solve it.": { style: 'B' },
  "One bag has 6 + 3 = 9 marbles. 4 bags have 4 × 9 = 36.": { style: 'B' },
  "The board gives 36 too. They match.": { style: 'B' },
  "Don't let the story do the × FIRST.": { style: 'B+', say: "Don't let the story multiply FIRST." },
  "4 bags of 6 red, plus 3 green, is 4 × 6 + 3. The ( ) put 3 green in every bag.": { style: 'B+', say: "4 bags of 6 red, plus 3 green, is 4 times 6, plus 3. The brackets put 3 green in every bag." },
  "A number sentence on the board. The board in class shows 4 × (6 + 3). What story could these numbers and signs tell?": { style: 'A', say: "A number sentence on the board. The board in class shows 4 times 6 plus 3, all together. What story could these numbers and signs tell?" },
  "Now you try. The board shows 4 × (6 + 5). A class makes this story: 4 bags, each with 6 red marbles and 5 green marbles. How many marbles are in the story? Do the part in the ( ) first. Then do the rest of the story.": { style: 'A', say: "Now you try. The board shows 4 times 6 plus 5, all together. A class makes this story, 4 bags, each with 6 red marbles and 5 green marbles. How many marbles are in the story? Do the part in the brackets first. Then do the rest of the story." },
  "Try a new one. The board shows 5 × (4 + 3). A class makes this story: 5 boxes, each with 4 red crayons and 3 green crayons. How many crayons are in the story?": { style: 'A', say: "Try a new one. The board shows 5 times 4 plus 3, all together. A class makes this story, 5 boxes, each with 4 red crayons and 3 green crayons. How many crayons are in the story?" },
  "Start with the ( ). How many marbles are in one bag?": { style: 'A', say: "Start with the brackets. How many marbles are in one bag?" },
  "Start with the ( ). How many crayons are in one box?": { style: 'A', say: "Start with the brackets. How many crayons are in one box?" },
  "You did the part in the ( ) first, then the rest of the story.": { style: 'A', say: "You did the part in the brackets first, then the rest of the story." },
  // ── g5m1-t19 ──
  "Can we share the markers among 18 classes yet? Not yet.": { style: 'B' },
  "How many markers are there in all? The story never says.": { style: 'B' },
  "That number is hidden. We have to find it first.": { style: 'B' },
  "Find the hidden number first, then use it to answer the question.": { style: 'B' },
  "24 boxes, with 36 markers in each.": { style: 'B' },
  "24 × 36 = 864. So there are 864 markers in all.": { style: 'B' },
  "Now answer the real question.": { style: 'B' },
  "Share the 864 markers among 18 classes. 864 ÷ 18 = 48.": { style: 'B' },
  "Each class gets 48 markers.": { style: 'B' },
  "Does 48 make sense? Check it.": { style: 'B' },
  "18 classes with 48 each is 18 × 48 = 864.": { style: 'B' },
  "That's every marker in the 24 boxes. It checks out.": { style: 'B' },
  "Don't STOP at the hidden number.": { style: 'B+' },
  "864 is all the markers, not one class's share. Finish with the question.": { style: 'B+' },
  // ── g5m1-t20 ──
  "The story gives 32, 25 and 186. Which one is the empty seats?": { style: 'B' },
  "None of them. And pick a sign too soon, and you may answer a different question.": { style: 'B' },
  "Draw the story as a tape, solve one part at a time, and check what the question asks.": { style: 'B' },
  "32 rows of 25 seats make one long tape.": { style: 'B' },
  "32 × 25 = 800. So the theater has 800 seats.": { style: 'B' },
  "186 seats are sold. That's one part of the 800.": { style: 'B' },
  "The empty seats are the other part. So take away. 800 − 186 = 614.": { style: 'B' },
  "Now read the question again. Does it ask for sold seats? No, empty ones.": { style: 'B' },
  "Check it. 614 empty and 186 sold make 800.": { style: 'B' },
  "So 614 seats are still empty.": { style: 'B' },
  "Don't ADD the sold seats.": { style: 'B+' },
  "They're part of the 800, so take them away.": { style: 'B+' },
}
