/**
 * How g5m3's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G5M3_VOICE: Record<string, VoiceLine> = {
  // Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts.
  // ── g5m3-t1 ──
  "3 pizzas, and 4 friends.": { style: 'B' },
  "Can each friend get a whole pizza? No. There are more friends than pizzas.": { style: 'B' },
  "So each share is less than 1 pizza.": { style: 'B' },
  "A fraction is a division, so 3 ÷ 4 is the same as 3/4.": { style: 'B' },
  "Look. Cut each pizza into 4 equal slices.": { style: 'B' },
  "Why 4? There is one slice for each friend.": { style: 'B' },
  "Every slice is 1/4 of a pizza.": { style: 'B' },
  "Now follow one friend.": { style: 'B' },
  "That friend takes 1 slice from each pizza.": { style: 'B' },
  "That's 3 slices, and each one is 1/4 of a pizza.": { style: 'B' },
  "Push the 3 slices together.": { style: 'B' },
  "3 slices of 1/4 make 3/4 of a pizza.": { style: 'B' },
  "So each friend gets 3/4, and 3 ÷ 4 = 3/4.": { style: 'B' },
  "Don't FLIP the numbers to 4/3.": { style: 'B+' },
  "4/3 is more than a whole pizza each. The number you share goes on top.": { style: 'B+' },
  // ── g5m3-t2 ──
  "2/3 of 12. Do you give 2 stickers? Or 3?": { style: 'B' },
  "No. 2/3 is a part of all 12, not a number of stickers.": { style: 'B' },
  "So first, we need to know how big one part is.": { style: 'B' },
  "To find 2/3 of 12, cut 12 into 3 equal parts and take 2 of them.": { style: 'B' },
  "Look at the bottom number, 3. It says how many equal parts.": { style: 'B' },
  "So cut the 12 stickers into 3 parts.": { style: 'B' },
  "How many in each part? 12 ÷ 3 = 4.": { style: 'B' },
  "Now the top number, 2. It says how many parts to give.": { style: 'B' },
  "Give 2 parts. 4 and 4 is 8.": { style: 'B' },
  "So 2/3 of 12 is 8 stickers.": { style: 'B' },
  "Two steps, every time.": { style: 'B' },
  "Divide by the bottom number. 12 ÷ 3 = 4.": { style: 'B' },
  "Then multiply by the top number. 2 × 4 = 8.": { style: 'B' },
  "Don't STOP at one part.": { style: 'B+' },
  "4 is only 1/3 of 12. You give 2 parts, so it's 8.": { style: 'B+' },
  // ── g5m3-t3 ──
  "You eat 1/3. But 1/3 of what?": { style: 'B' },
  "Not of the whole pan. It's 1/3 of the half you have.": { style: 'B' },
  "So how much of the whole pan is that?": { style: 'B' },
  "Cut the half into 3 equal pieces, then count how many of those pieces fill the whole pan.": { style: 'B' },
  "Here is the whole pan.": { style: 'B' },
  "Cut it into 2 equal rows. The top row is your half.": { style: 'B' },
  "Now cut your half into 3 equal pieces.": { style: 'B' },
  "Carry the cuts down the pan.": { style: 'B' },
  "You eat 1 of the 3 pieces in your half.": { style: 'B' },
  "Now look at the whole pan. How many pieces like yours fill it?": { style: 'B' },
  "2 rows of 3. That's 6 pieces, and you ate 1.": { style: 'B' },
  "So 1/3 of 1/2 is 1/6. 1/3 × 1/2 = 1/6.": { style: 'B' },
  "Multiplying does not always make a number BIGGER.": { style: 'B+' },
  "A piece of a piece is smaller. 1/6 is less than the 1/2 you had.": { style: 'B+' },
  // ── g5m3-t4 ──
  "With whole-number sides, you count square meters.": { style: 'B' },
  "But this rug is smaller than 1 square meter.": { style: 'B' },
  "So what can you count? Not even one whole square.": { style: 'B' },
  "Cut 1 square meter to match the sides, then count the pieces the rug covers out of all the pieces.": { style: 'B' },
  "Start with a square, 1 meter on each side.": { style: 'B' },
  "The rug is 1/2 meter wide, so cut 2 equal rows.": { style: 'B' },
  "It's 3/4 meter long, so cut 4 equal columns. How many pieces now? 8.": { style: 'B' },
  "Now lay the rug on the square.": { style: 'B' },
  "1/2 meter wide covers 1 row. 3/4 meter long covers 3 columns.": { style: 'B' },
  "So the rug covers 3 pieces.": { style: 'B' },
  "Count them. 3 pieces out of 8.": { style: 'B' },
  "So the rug covers 3/8 of a square meter.": { style: 'B' },
  "Look. 1/2 × 3/4 = 3/8, side times side.": { style: 'B' },
  "Don't ADD the sides. That only measures the edges.": { style: 'B+' },
  "The floor it covers is 1/2 × 3/4, and that is 3/8.": { style: 'B+' },
  // ── g5m3-t5 ──
  "Up to now, times made numbers bigger.": { style: 'B' },
  "3 × 8 = 24. But look at the 3. It's more than 1.": { style: 'B' },
  "3/4 is less than 1. So what happens?": { style: 'B' },
  "Multiply by less than 1 and you get part of the amount, multiply by more than 1 and you get more than all of it.": { style: 'B' },
  "Start with 1 × 8. That's one whole recipe.": { style: 'B' },
  "It uses the same 8 cups. Nothing changes.": { style: 'B' },
  "Now 3/4 × 8. Is 3/4 more than 1? No, less.": { style: 'B' },
  "So cut the 8 cups into 4 equal parts, and take 3.": { style: 'B' },
  "That's 6 cups, less than 8.": { style: 'B' },
  "Now 1 1/2 × 8. That's more than 1 whole.": { style: 'B' },
  "So you get all 8 cups, and half of 8 again.": { style: 'B' },
  "8 + 4 = 12 cups, more than you started with.": { style: 'B' },
  "Don't think times ALWAYS makes it bigger.": { style: 'B+' },
  "Look at what you multiply by first. 3/4 is less than 1, so 3/4 × 8 comes out smaller.": { style: 'B+' },
  // ── g5m3-t6 ──
  "Usually, dividing means sharing.": { style: 'B' },
  "But can you share 2 yards among 1/4 of a friend? No.": { style: 'B' },
  "So dividing by 1/4 must ask something else.": { style: 'B' },
  "Dividing by a small piece asks how many of those pieces fit.": { style: 'B' },
  "Each bow takes 1/4 of a yard.": { style: 'B' },
  "So cut every yard into 4 equal pieces, one piece for each bow.": { style: 'B' },
  "Now count the pieces with me.": { style: 'B' },
  "The first yard gives 4. The second yard gives 4 more.": { style: 'B' },
  "Four, eight. That's 8 pieces, so 8 bows.": { style: 'B' },
  "So 8 fourths fit in 2 yards.": { style: 'B' },
  "That's what 2 ÷ 1/4 asks. 2 ÷ 1/4 = 8.": { style: 'B' },
  "Each yard holds 4, so 2 yards hold 2 × 4 = 8.": { style: 'B' },
  "Don't answer 1/2. That's 2 ÷ 4, NOT 2 ÷ 1/4.": { style: 'B+' },
  "Small pieces fit many times, so the answer is bigger than 2.": { style: 'B+' },
  // ── g5m3-t7 ──
  "Each friend gets 1 of 3 pieces of the half.": { style: 'B' },
  "But is that 1/3 of the pie? No.": { style: 'B' },
  "The question asks about the whole pie, not the half.": { style: 'B' },
  "To share a piece, cut it up, then see how big one share is in the whole.": { style: 'B' },
  "Draw the whole pie first.": { style: 'B' },
  "It's 2 halves. The shaded half is what's left.": { style: 'B' },
  "Now cut that half into 3 equal pieces, one for each friend.": { style: 'B' },
  "Here's the move that matters. Give the other half the same cuts.": { style: 'B' },
  "Now the whole pie has 6 equal pieces.": { style: 'B' },
  "Each friend gets 1 of those 6 pieces.": { style: 'B' },
  "That's 1/6 of the whole pie.": { style: 'B' },
  "So 1/2 ÷ 3 = 1/6.": { style: 'B' },
  "Sharing does not make a piece BIGGER. 1/2 ÷ 3 is not 3/2.": { style: 'B+' },
  "Each share is smaller than the half. It's 1/6.": { style: 'B+' },
  // ── g5m3-t8 ──
  "Two stories can use the same 4 miles.": { style: 'B' },
  "One takes part of it. One counts pieces along it.": { style: 'B' },
  "So times or divide? The words tell you.": { style: 'B' },
  "Draw the story, then ask: are you taking part of an amount, or counting how many pieces fit?": { style: 'B' },
  "Our story says 3/4 of the trail. That's part of it, so multiply.": { style: 'B' },
  "Cut 4 miles into 4 equal parts, and take 3.": { style: 'B' },
  "3/4 × 4 = 3 miles.": { style: 'B' },
  "Now a new story: a water stop every 1/2 mile.": { style: 'B' },
  "How many halves fit in 4 miles? Each mile holds 2, so 8.": { style: 'B' },
  "That's 4 ÷ 1/2 = 8 water stops.": { style: 'B' },
  "Check the size.": { style: 'B' },
  "Part of 4 miles must be less than 4, and 3 is.": { style: 'B' },
  "Counting half miles gives more than 4, and 8 is.": { style: 'B' },
  "Don't pick times or divide from the NUMBERS.": { style: 'B+' },
  "A stop every 1/2 mile is not 1/2 × 4. It's 4 ÷ 1/2 = 8.": { style: 'B+' },
}
