/**
 * How g5m3's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G5M3_VOICE: Record<string, VoiceLine> = {
  // Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts.
  // ── g5m3-t5 ──
  "Up to now, times made numbers bigger.": { style: 'B' },
  "3 × 8 = 24. But look at the 3. It's more than 1.": { style: 'B' },
  "3/4 is less than 1. So what happens?": { style: 'B' },
  "Multiply by less than 1 and you get part of the amount, multiply by more than 1 and you get more than all of it.": { style: 'B' },
  "Start with 1 × 8. That's one whole recipe.": { style: 'B' },
  "It uses the same 8 cups. Nothing changes.": { style: 'B' },
  "Now 3/4 × 8. Is 3/4 more than 1? No, less.": { style: 'B' },
  "So cut the 8 cups into 4 equal parts, and take 3.": { style: 'B' },
  "That's 6 cups, less than 8.": { style: 'B' },
  "Now 1 1/2 × 8. That's more than 1 whole.": { style: 'B' },
  "So you get all 8 cups, and half of 8 again.": { style: 'B' },
  "8 + 4 = 12 cups, more than you started with.": { style: 'B' },
  "Don't think times ALWAYS makes it bigger.": { style: 'B+' },
  "Look at what you multiply by first. 3/4 is less than 1, so 3/4 × 8 comes out smaller.": { style: 'B+' },
  // ── g5m3-t6 ──
  "Usually, dividing means sharing.": { style: 'B' },
  "But can you share 2 yards among 1/4 of a friend? No.": { style: 'B' },
  "So dividing by 1/4 must ask something else.": { style: 'B' },
  "Dividing by a small piece asks how many of those pieces fit.": { style: 'B' },
  "Each bow takes 1/4 of a yard.": { style: 'B' },
  "So cut every yard into 4 equal pieces, one piece for each bow.": { style: 'B' },
  "Now count the pieces with me.": { style: 'B' },
  "The first yard gives 4. The second yard gives 4 more.": { style: 'B' },
  "Four, eight. That's 8 pieces, so 8 bows.": { style: 'B' },
  "So 8 fourths fit in 2 yards.": { style: 'B' },
  "That's what 2 ÷ 1/4 asks. 2 ÷ 1/4 = 8.": { style: 'B' },
  "Each yard holds 4, so 2 yards hold 2 × 4 = 8.": { style: 'B' },
  "Don't answer 1/2. That's 2 ÷ 4, NOT 2 ÷ 1/4.": { style: 'B+' },
  "Small pieces fit many times, so the answer is bigger than 2.": { style: 'B+' },
  // ── g5m3-t7 ──
  "Each friend gets 1 of 3 pieces of the half.": { style: 'B' },
  "But is that 1/3 of the pie? No.": { style: 'B' },
  "The question asks about the whole pie, not the half.": { style: 'B' },
  "To share a piece, cut it up, then see how big one share is in the whole.": { style: 'B' },
  "Draw the whole pie first.": { style: 'B' },
  "It's 2 halves. The shaded half is what's left.": { style: 'B' },
  "Now cut that half into 3 equal pieces, one for each friend.": { style: 'B' },
  "Here's the move that matters. Give the other half the same cuts.": { style: 'B' },
  "Now the whole pie has 6 equal pieces.": { style: 'B' },
  "Each friend gets 1 of those 6 pieces.": { style: 'B' },
  "That's 1/6 of the whole pie.": { style: 'B' },
  "So 1/2 ÷ 3 = 1/6.": { style: 'B' },
  "Sharing does not make a piece BIGGER. 1/2 ÷ 3 is not 3/2.": { style: 'B+' },
  "Each share is smaller than the half. It's 1/6.": { style: 'B+' },
  // ── g5m3-t8 ──
  "Two stories can use the same 4 miles.": { style: 'B' },
  "One takes part of it. One counts pieces along it.": { style: 'B' },
  "So times or divide? The words tell you.": { style: 'B' },
  "Draw the story, then ask: are you taking part of an amount, or counting how many pieces fit?": { style: 'B' },
  "Our story says 3/4 of the trail. That's part of it, so multiply.": { style: 'B' },
  "Cut 4 miles into 4 equal parts, and take 3.": { style: 'B' },
  "3/4 × 4 = 3 miles.": { style: 'B' },
  "Now a new story: a water stop every 1/2 mile.": { style: 'B' },
  "How many halves fit in 4 miles? Each mile holds 2, so 8.": { style: 'B' },
  "That's 4 ÷ 1/2 = 8 water stops.": { style: 'B' },
  "Check the size.": { style: 'B' },
  "Part of 4 miles must be less than 4, and 3 is.": { style: 'B' },
  "Counting half miles gives more than 4, and 8 is.": { style: 'B' },
  "Don't pick times or divide from the NUMBERS.": { style: 'B+' },
  "A stop every 1/2 mile is not 1/2 × 4. It's 4 ÷ 1/2 = 8.": { style: 'B+' },
}
