/**
 * How g5m4's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 * Decimals: t1–t5 are about writing the digits and lining them up, so a decimal is read digit by digit ("0.047" →
 * "zero point zero four seven"). "Here's the part people mix up." and "Okay. Your turn." share g5m1's rows.
 */
import type { VoiceLine } from './styles'

export const G5M4_VOICE: Record<string, VoiceLine> = {
  // ── g5m4-t1 ──
  "You know tenths and hundredths.": { style: 'B' },
  "But one hundredth of a gram is too heavy for this seed.": { style: 'B' },
  "So where do 47 thousandths go? We need a smaller place.": { style: 'B' },
  "The third place after the point is thousandths, so 47 thousandths is 0.047.": { style: 'B', say: "The third place after the point is thousandths, so 47 thousandths is zero point zero four seven." },
  "Look. Cut one hundredth into 10 equal pieces.": { style: 'B' },
  "Each piece is one thousandth, and we write it 0.001.": { style: 'B', say: "Each piece is one thousandth, and we write it zero point zero zero one." },
  "It takes 1,000 of them to make 1 whole.": { style: 'B' },
  "Now build 47 thousandths.": { style: 'B' },
  "What is it made of? 4 hundredths and 7 thousandths.": { style: 'B' },
  "So the 4 goes in the hundredths, and the 7 in the thousandths.": { style: 'B' },
  "There are no ones or tenths, so each gets a 0.": { style: 'B', say: "There are no ones or tenths, so each gets a zero." },
  "Now read it across. The seed weighs 0.047 grams.": { style: 'B', say: "Now read it across. The seed weighs zero point zero four seven grams." },
  "Don't write 0.47. That's 47 HUNDREDTHS, ten times as heavy.": { style: 'B+', say: "Don't write zero point four seven. That's 47 hundredths, ten times as heavy." },
  "Thousandths need three places after the point.": { style: 'B+' },
  "Thousandths take three places after the point. Put a 0 in any empty place.": { style: 'A', say: "Thousandths take three places after the point. Put a zero in any empty place." },
  "Use three places after the point. Fill the tenths place with a 0.": { style: 'A', say: "Use three places after the point. Fill the tenths place with a zero." },
  "You wrote 52 thousandths as 0.052.": { style: 'A', say: "You wrote 52 thousandths as zero point zero five two." },
  // ── g5m4-t2 ──
  "Look at 0.389. It has more digits, and 389 is more than 4.": { style: 'B', say: "Look at zero point three eight nine. It has more digits, and 389 is more than 4." },
  "So is 0.389 bigger? Not so fast.": { style: 'B', say: "So is zero point three eight nine bigger? Not so fast." },
  "The digits after the point are not whole numbers.": { style: 'B' },
  "Line up the places, compare from the left, and the first place that is different decides.": { style: 'B' },
  "Put both numbers in the chart, one place under the other.": { style: 'B' },
  "0.4 has no hundredths or thousandths, so fill those with zeros.": { style: 'B', say: "Zero point four has no hundredths or thousandths, so fill those with zeros." },
  "Now 0.4 reads 0.400, the same amount.": { style: 'B', say: "Now zero point four reads zero point four zero zero, the same amount." },
  "Start at the left. The ones match, 0 and 0.": { style: 'B' },
  "Next, the tenths. 4 and 3. Are they the same? No.": { style: 'B' },
  "So the tenths decide.": { style: 'B' },
  "4 tenths is more than 3 tenths.": { style: 'B' },
  "So 0.4 is bigger. We write 0.4 > 0.389.": { style: 'B', say: "So zero point four is bigger. We write zero point four > zero point three eight nine." },
  "The first snail wins.": { style: 'B' },
  "Don't pick a number because it has MORE digits.": { style: 'B+', say: "Don't pick a number because it has more digits." },
  "Line up the places and compare from the left.": { style: 'B+' },
  "A snail race. Two snails race. One crawls 0.4 meters. The other crawls 0.389 meters. Which one crawls farther?": { style: 'A', say: "A snail race. Two snails race. One crawls zero point four meters. The other crawls zero point three eight nine meters. Which one crawls farther?" },
  "Now you try. Which sign goes between them? 0.7 ? 0.698 Line up the places. Find the first place that is different.": { style: 'A', say: "Now you try. Which sign goes between them? Zero point seven, and zero point six nine eight. Line up the places. Find the first place that is different." },
  "Try a new one. Which sign goes between them? 0.352 ? 0.36": { style: 'A', say: "Try a new one. Which sign goes between them? Zero point three five two, and zero point three six." },
  "Write 0.7 with three places after the point.": { style: 'A', say: "Write zero point seven with three places after the point." },
  "Put a 0 at the end of 0.36 so both have three places.": { style: 'A', say: "Put a zero at the end of zero point three six so both have three places." },
  "You saw that 0.352 < 0.36 by checking the hundredths.": { style: 'A', say: "You saw that zero point three five two < zero point three six by checking the hundredths." },
  // ── g5m4-t3 ──
  "The tag has room for one place after the point.": { style: 'B' },
  "But 3.27 has two places.": { style: 'B', say: "But three point two seven has two places." },
  "So which should it say, 3.2 or 3.3?": { style: 'B', say: "So which should it say, three point two or three point three?" },
  "Find the two numbers it sits between and pick the closer one, and if it is halfway or past, round up.": { style: 'B' },
  "Look. 3.27 sits between 3.2 and 3.3.": { style: 'B', say: "Look. Three point two seven sits between three point two and three point three." },
  "Halfway between them is 3.25.": { style: 'B', say: "Halfway between them is three point two five." },
  "So where did 3.27 land? Past halfway.": { style: 'B', say: "So where did three point two seven land? Past halfway." },
  "Up to 3.3 is only 3 hundredths.": { style: 'B', say: "Up to three point three is only 3 hundredths." },
  "Back down to 3.2 is 7 hundredths.": { style: 'B', say: "Back down to three point two is 7 hundredths." },
  "3.3 is closer, so 3.27 rounds up to 3.3.": { style: 'B', say: "Three point three is closer, so three point two seven rounds up to three point three." },
  "The tag says 3.3 meters.": { style: 'B', say: "The tag says three point three meters." },
  "Don't just CHOP off the last digit. That gives 3.2.": { style: 'B+', say: "Don't just chop off the last digit. That gives three point two." },
  "But 3.27 is closer to 3.3.": { style: 'B+', say: "But three point two seven is closer to three point three." },
  "How long is the ribbon?. A ribbon is 3.27 meters long. The shop only writes tenths of a meter on the tag. What should the tag say?": { style: 'A', say: "How long is the ribbon? A ribbon is three point two seven meters long. The shop only writes tenths of a meter on the tag. What should the tag say?" },
  "Now you try. Round 5.64 to the nearest tenth. Find the two tenths it sits between. Pick the closer one.": { style: 'A', say: "Now you try. Round five point six four to the nearest tenth. Find the two tenths it sits between. Pick the closer one." },
  "Try a new one. Round 2.386 to the nearest hundredth.": { style: 'A', say: "Try a new one. Round two point three eight six to the nearest hundredth." },
  "Which two tenths does 5.64 sit between?": { style: 'A', say: "Which two tenths does five point six four sit between?" },
  "Halfway between them is 5.65. Is 5.64 before or past halfway?": { style: 'A', say: "Halfway between them is five point six five. Is five point six four before or past halfway?" },
  "Find halfway between the two hundredths. Is 2.386 before or past it?": { style: 'A', say: "Find halfway between the two hundredths. Is two point three eight six before or past it?" },
  "You rounded 2.386 up to 2.39.": { style: 'A', say: "You rounded two point three eight six up to two point three nine." },
  // ── g5m4-t4 ──
  "What if you line up the last digits?": { style: 'B' },
  "Then the 7 tenths sits under the 5 hundredths.": { style: 'B' },
  "Two different places get added, and the answer is way off.": { style: 'B' },
  "Line up the points, add like whole numbers, and bring the point straight down.": { style: 'B' },
  "Put the points one right under the other.": { style: 'B' },
  "3.7 has no hundredths, so write it as 3.70.": { style: 'B', say: "Three point seven has no hundredths, so write it as three point seven zero." },
  "Now both numbers have the same places.": { style: 'B' },
  "Add from the right. Hundredths, 5 + 0 = 5.": { style: 'B' },
  "Tenths, 4 + 7 = 11. Write 1, carry 1 to the ones.": { style: 'B' },
  "Ones, 1 + 2 + 3 = 6. Tens, just the 1.": { style: 'B' },
  "Last, the point. It drops straight down.": { style: 'B' },
  "So the two bags weigh 16.15 pounds.": { style: 'B', say: "So the two bags weigh sixteen point one five pounds." },
  "Don't line up the LAST digits. That gives 12.82.": { style: 'B+', say: "Don't line up the last digits. That gives twelve point eight two." },
  "Line up the points, and it's 16.15.": { style: 'B+', say: "Line up the points, and it's sixteen point one five." },
  "Two bags of apples. One bag of apples weighs 12.45 pounds. Another bag weighs 3.7 pounds. How much do they weigh together?": { style: 'A', say: "Two bags of apples. One bag of apples weighs twelve point four five pounds. Another bag weighs three point seven pounds. How much do they weigh together?" },
  "Now you try. Add. 23.56 + 4.8 = ? Line up the points. Add from the right. Bring the point down.": { style: 'A', say: "Now you try. Add. Twenty-three point five six + four point eight = ? Line up the points. Add from the right. Bring the point down." },
  "Try a new one. Add. 15.3 + 2.64 = ?": { style: 'A', say: "Try a new one. Add. Fifteen point three + two point six four = ?" },
  "Is the point of 4.8 right under the other point?": { style: 'A', say: "Is the point of four point eight right under the other point?" },
  "Write 4.8 as 4.80. Start with the hundredths: 6 + 0.": { style: 'A', say: "Write four point eight as four point eight zero. Start with the hundredths: 6 + 0." },
  "Which number needs a 0 at the end so both have two places after the point?": { style: 'A', say: "Which number needs a zero at the end so both have two places after the point?" },
  "You lined up the points and found 17.94.": { style: 'A', say: "You lined up the points and found seventeen point nine four." },
  // ── g5m4-t5 ──
  "Line them up. Look at the hundredths.": { style: 'B' },
  "1.35 has 5 hundredths. But 5.2 has nothing there.": { style: 'B', say: "One point three five has 5 hundredths. But five point two has nothing there." },
  "What do you take the 5 away from?": { style: 'B' },
  "Line up the points, fill any empty place with a 0, and take away like whole numbers.": { style: 'B', say: "Line up the points, fill any empty place with a zero, and take away like whole numbers." },
  "Look. 5.2 is the same as 5.20.": { style: 'B', say: "Look. Five point two is the same as five point two zero." },
  "So write a 0 in the empty place.": { style: 'B', say: "So write a zero in the empty place." },
  "Now every place has a digit.": { style: 'B' },
  "Hundredths first. 0 − 5 won't go, so trade 1 tenth.": { style: 'B' },
  "10 − 5 = 5.": { style: 'B' },
  "Tenths. 1 − 3 won't go, so trade 1 one.": { style: 'B' },
  "11 − 3 = 8.": { style: 'B' },
  "Then the ones. 4 − 1 = 3.": { style: 'B' },
  "The point comes straight down. So 3.85 liters are left.": { style: 'B', say: "The point comes straight down. So three point eight five liters are left." },
  "Don't just bring the 5 DOWN when the top is empty.": { style: 'B+', say: "Don't just bring the 5 down when the top is empty." },
  "That gives 3.95. Write a 0 up top and trade. It's 3.85.": { style: 'B+', say: "That gives three point nine five. Write a zero up top and trade. It's three point eight five." },
  "Juice left over. A jug holds 5.2 liters of juice. You pour out 1.35 liters. How much juice is left?": { style: 'A', say: "Juice left over. A jug holds five point two liters of juice. You pour out one point three five liters. How much juice is left?" },
  "Now you try. Take away. 6.4 − 2.75 = ? Put a 0 in the empty place. Then take away from the right.": { style: 'A', say: "Now you try. Take away. Six point four − two point seven five = ? Put a zero in the empty place. Then take away from the right." },
  "Try a new one. Take away. 9.3 − 4.68 = ?": { style: 'A', say: "Try a new one. Take away. Nine point three − four point six eight = ?" },
  "What goes in the empty hundredths place of 6.4?": { style: 'A', say: "What goes in the empty hundredths place of six point four?" },
  "Write 6.40. Now 0 − 5 needs a trade from the tenths.": { style: 'A', say: "Write six point four zero. Now 0 − 5 needs a trade from the tenths." },
  "Fill the empty place in 9.3 with a 0 first.": { style: 'A', say: "Fill the empty place in nine point three with a zero first." },
  "You filled the empty place with a 0, traded, and took away.": { style: 'A', say: "You filled the empty place with a zero, traded, and took away." },
  "You filled in a 0 and found 4.62.": { style: 'A', say: "You filled in a zero and found four point six two." },
}
