/**
 * How g5m4's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G5M4_VOICE: Record<string, VoiceLine> = {
  // ── g5m4-t6 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "You could add 1.25 three times.": { style: 'B', say: "You could add one and twenty-five hundredths three times." },
  "That works for 3 smoothies. But what about 9 of them?": { style: 'B' },
  "Is there a faster way? Yes.": { style: 'B' },
  "Break the number into wholes, tenths and hundredths, multiply each part, then add the parts.": { style: 'B' },
  "Look at 1.25.": { style: 'B', say: "Look at one and twenty-five hundredths." },
  "It is 1 whole, 2 tenths and 5 hundredths.": { style: 'B' },
  "So 1.25 = 1 + 0.2 + 0.05.": { style: 'B', say: "So one and twenty-five hundredths equals 1, plus two tenths, plus five hundredths." },
  "Now multiply each part by 3.": { style: 'B' },
  "3 × 1 = 3. 3 × 2 tenths is 6 tenths, which is 0.6.": { style: 'B', say: "3 times 1 equals 3. 3 times 2 tenths is 6 tenths, which is zero point six." },
  "And 3 × 5 hundredths is 15 hundredths, which is 0.15.": { style: 'B', say: "And 3 times 5 hundredths is 15 hundredths, which is zero point one five." },
  // "Now put the parts back together." already has a row in another module
  "Line up the points and add. 3 + 0.6 + 0.15 = 3.75.": { style: 'B', say: "Line up the points and add. 3, plus six tenths, plus fifteen hundredths, equals three and seventy-five hundredths." },
  "So 3 smoothies cost $3.75.": { style: 'B', say: "So 3 smoothies cost 3 dollars and 75 cents." },
  "Don't DROP the point. 3 × 1.25 is not 375.": { style: 'B+', say: "Don't drop the point. 3 times one and twenty-five hundredths is not 375." },
  "One smoothie is about $1, so 3 cost about $3. The answer is $3.75.": { style: 'B+', say: "One smoothie is about 1 dollar, so 3 cost about 3 dollars. The answer is 3 dollars and 75 cents." },
  "Three smoothies. One smoothie costs $1.25. You buy 3 smoothies. How much do you pay?": { style: 'A', say: "Three smoothies. One smoothie costs 1 dollar and 25 cents. You buy 3 smoothies. How much do you pay?" },
  "Now you try. Multiply. 4 × 1.32 = ? Break the decimal into parts. Multiply each part. Then add.": { style: 'A', say: "Now you try. Multiply. 4 times one and thirty-two hundredths equals what? Break the decimal into parts. Multiply each part. Then add." },
  "Try a new one. Multiply. 3 × 2.14 = ?": { style: 'A', say: "Try a new one. Multiply. 3 times two and fourteen hundredths equals what?" },
  "Break 1.32 into wholes, tenths and hundredths.": { style: 'A', say: "Break one and thirty-two hundredths into wholes, tenths and hundredths." },
  "Find 4 × 1, 4 × 0.3 and 4 × 0.02. Then add them.": { style: 'A', say: "Find 4 times 1, 4 times three tenths and 4 times two hundredths. Then add them." },
  "Break 2.14 into wholes, tenths and hundredths.": { style: 'A', say: "Break two and fourteen hundredths into wholes, tenths and hundredths." },
  "You multiplied each part of 2.14 by 3 and got 6.42.": { style: 'A', say: "You multiplied each part of two and fourteen hundredths by 3 and got six and forty-two hundredths." },
  // ── g5m4-t7 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "With whole numbers, times 100 adds two zeros.": { style: 'B' },
  "Does that work here? 2.36 becomes 2.3600.": { style: 'B', say: "Does that work here? Two point three six becomes two point three six zero zero." },
  "But 2.3600 is still 2.36. Nothing changed.": { style: 'B', say: "But two point three six zero zero is still two point three six. Nothing changed." },
  "The point stays put while each zero in 10, 100 or 1,000 slides every digit one place, left to multiply and right to divide.": { style: 'B' },
  "Each place is worth 10 times the place to its right.": { style: 'B' },
  "So 2.36 × 10 slides every digit one place left.": { style: 'B', say: "So two point three six times 10 slides every digit one place left." },
  "The 2 is in the tens now. That's 23.6.": { style: 'B', say: "The 2 is in the tens now. That's twenty-three point six." },
  "What about × 100? That's × 10 twice.": { style: 'B' },
  "So every digit slides two places left.": { style: 'B' },
  "Now the 2 is in the hundreds. That's 236.": { style: 'B' },
  "So the store has 236 kilograms.": { style: 'B' },
  "Now go back. 236 ÷ 100 slides every digit two places right.": { style: 'B' },
  "The 2 lands back in the ones.": { style: 'B' },
  "That's 2.36 again, one bag.": { style: 'B', say: "That's two point three six again, one bag." },
  "Don't just ADD zeros. 2.3600 is still 2.36.": { style: 'B+', say: "Don't just add zeros. Two point three six zero zero is still two point three six." },
  "Slide every digit. 2.36 × 100 = 236.": { style: 'B+', say: "Slide every digit. Two point three six times 100 equals 236." },
  "A store full of rice. One bag of rice weighs 2.36 kilograms. A store has 100 bags. How many kilograms is that?": { style: 'A', say: "A store full of rice. One bag of rice weighs two point three six kilograms. A store has 100 bags. How many kilograms is that?" },
  "Now you try. Multiply. 4.57 × 100 = ? Count the zeros in 100. Move every digit that many places.": { style: 'A', say: "Now you try. Multiply. Four point five seven times 100 equals what? Count the zeros in 100. Move every digit that many places." },
  "Try a new one. Divide. 38.2 ÷ 10 = ?": { style: 'A', say: "Try a new one. Divide. Thirty-eight point two divided by 10 equals what?" },
  "You moved every digit of 38.2 one place right, to 3.82.": { style: 'A', say: "You moved every digit of thirty-eight point two one place right, to three point eight two." },
  // ── g5m4-t8 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Try the 7 whole meters first. 3 pieces of 2 meters is 6, with 1 meter left over.": { style: 'B' },
  "And the 0.2 is still there. What do we do with the rest?": { style: 'B', say: "And the two tenths is still there. What do we do with the rest?" },
  "Count the whole amount in tenths, share the tenths equally, then put the point back.": { style: 'B' },
  "Every meter is 10 tenths. So 7 meters is 70 tenths.": { style: 'B' },
  "Add the 2 tenths, and the ribbon is 72 tenths.": { style: 'B' },
  "Now 72 shares into 3 just fine. 72 ÷ 3 = 24.": { style: 'B' },
  "So each piece gets 24 tenths.": { style: 'B' },
  "Is 24 the answer? Not yet. 24 tenths is 2 wholes and 4 tenths.": { style: 'B' },
  "That's 2.4. So each piece is 2.4 meters long.": { style: 'B', say: "That's two and four tenths. So each piece is two and four tenths meters long." },
  "Don't STOP at 24. That's how many tenths, not meters.": { style: 'B+' },
  "Put the point back in. 7.2 ÷ 3 = 2.4.": { style: 'B+', say: "Put the point back in. Seven and two tenths divided by 3 equals two and four tenths." },
  "Share a ribbon. A ribbon is 7.2 meters long. You cut it into 3 equal pieces. How long is each piece?": { style: 'A', say: "Share a ribbon. A ribbon is seven and two tenths meters long. You cut it into 3 equal pieces. How long is each piece?" },
  "Now you try. Divide. 7.5 ÷ 3 = ? Count the decimal in tenths. Share them. Then write it with a point.": { style: 'A', say: "Now you try. Divide. Seven and five tenths divided by 3 equals what? Count the decimal in tenths. Share them. Then write it with a point." },
  "Try a new one. Divide. 9.2 ÷ 4 = ?": { style: 'A', say: "Try a new one. Divide. Nine and two tenths divided by 4 equals what?" },
  "How many tenths is 7.5?": { style: 'A', say: "How many tenths is seven and five tenths?" },
  "Count 9.2 in tenths first.": { style: 'A', say: "Count nine and two tenths in tenths first." },
  "You shared 9.2 into 4 equal parts and got 2.3.": { style: 'A', say: "You shared nine and two tenths into 4 equal parts and got two and three tenths." },
  // ── g5m4-t9 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "A kilometer is much longer than a meter. It's 1,000 meters.": { style: 'B' },
  "So is the trail more meters, or fewer? More.": { style: 'B' },
  "To a smaller unit multiply, because it takes more of them, and to a bigger unit divide.": { style: 'B' },
  "Kilometers to meters. Meters are the smaller unit.": { style: 'B' },
  // "Smaller unit, more of them. So we multiply." already has a row in another module
  "1 kilometer is 1,000 meters, so multiply by 1,000.": { style: 'B' },
  "Times 1,000 slides every digit three places left.": { style: 'B' },
  "The 2 lands in the thousands, the 5 in the hundreds. Zeros fill the rest.": { style: 'B' },
  "So 2.5 × 1,000 = 2,500. The trail is 2,500 meters long.": { style: 'B', say: "So two point five times 1,000 equals 2,500. The trail is 2,500 meters long." },
  "Does 2,500 make sense? Yes. Meters are small, so we need lots.": { style: 'B' },
  "And back to kilometers? Divide. 2,500 ÷ 1,000 = 2.5.": { style: 'B', say: "And back to kilometers? Divide. 2,500 divided by 1,000 equals two point five." },
  "Don't DIVIDE here. That gives 0.0025 meters, a tiny speck.": { style: 'B+', say: "Don't divide here. That gives zero point zero zero two five meters, a tiny speck." },
  "Smaller unit, more of them. So multiply.": { style: 'B+' },
  "A long trail. A trail is 2.5 kilometers long. The sign at the start counts in meters. How many meters long is the trail?": { style: 'A', say: "A long trail. A trail is two point five kilometers long. The sign at the start counts in meters. How many meters long is the trail?" },
  "Now you try. How many meters is 4.2 kilometers? Smaller unit: multiply. Bigger unit: divide.": { style: 'A', say: "Now you try. How many meters is four point two kilometers? Smaller unit, multiply. Bigger unit, divide." },
  "1 kilometer is 1,000 meters. Multiply 4.2 by 1,000.": { style: 'A', say: "1 kilometer is 1,000 meters. Multiply four point two by 1,000." },
  "You changed 3,400 grams into 3.4 kilograms.": { style: 'A', say: "You changed 3,400 grams into three point four kilograms." },
}
