/**
 * How g5m5's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G5M5_VOICE: Record<string, VoiceLine> = {
  // ── g5m5-t1 ── (Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts)
  "Tiles cover a flat floor.": { style: 'B' },
  "But this box goes up, too. Can flat tiles fill it?": { style: 'B' },
  "No. The space above them stays empty.": { style: 'B' },
  "To find how much space is inside a box, count the small cubes that fill it, with no gaps.": { style: 'B' },
  "Look at one little cube.": { style: 'B' },
  "It's 1 unit long, 1 unit wide and 1 unit tall.": { style: 'B' },
  "They're all the same, so they fit with no gaps.": { style: 'B' },
  "Let's count. The bottom layer is 2 rows of 3. That's 6.": { style: 'B' },
  "The top layer is the same, 6 more.": { style: 'B' },
  "6 + 6 = 12.": { style: 'B' },
  "So 12 cubes fill the box.": { style: 'B' },
  "That number is how much space is inside.": { style: 'B' },
  "Don't count only the cubes you SEE.": { style: 'B+' },
  "You see 10. 2 more hide in back, under the top layer. That makes 12.": { style: 'B+' },
  // ── g5m5-t2 ── (Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts)
  "Could you count them one by one?": { style: 'B' },
  "You could. But some hide at the back, and a whole layer hides underneath.": { style: 'B' },
  "You'd lose your place. Is there a faster way? Yes.": { style: 'B' },
  "Count the cubes in one layer, then multiply by how many layers.": { style: 'B' },
  "Start with the bottom layer.": { style: 'B' },
  "It's 4 cubes long and 3 cubes wide.": { style: 'B' },
  "So 4 × 3 = 12 cubes.": { style: 'B' },
  "Now put the next layer on top.": { style: 'B' },
  "It's just like the bottom one. Another 12 cubes.": { style: 'B' },
  "So that's 2 layers of 12.": { style: 'B' },
  "12 × 2 = 24. The box holds 24 cubes.": { style: 'B' },
  "Don't STOP after one layer.": { style: 'B+' },
  "12 is only the bottom of the box. Multiply by the 2 layers to get 24.": { style: 'B+' },
  // ── g5m5-t3 ── (Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts)
  "This time there are no cubes to count.": { style: 'B' },
  "But you know every edge: 5 feet, 2 feet and 3 feet.": { style: 'B' },
  "Can the edges tell you how much fits? Yes.": { style: 'B' },
  "Multiply the length, the width and the height to find the volume of a box.": { style: 'B' },
  "Start with the bottom. It's 5 feet by 2 feet.": { style: 'B' },
  "Cubes 1 foot on each side cover it: 5 × 2 = 10.": { style: 'B' },
  "That's one layer.": { style: 'B' },
  "The tank is 3 feet tall, so 3 layers stack up.": { style: 'B' },
  "Ten, twenty, thirty.": { style: 'B' },
  "So multiply all three.": { style: 'B' },
  "5 × 2 × 3 = 30. The tank holds 30 cubic feet of water.": { style: 'B' },
  "Don't ADD the edges.": { style: 'B+' },
  "5 + 2 + 3 = 10 only walks along three edges. Multiply to fill the inside.": { style: 'B+' },
  // ── g5m5-t4 ── (Screen 7's "Here's the part people mix up." and "Okay. Your turn." have their rows in g5m1.ts)
  "Can you multiply one length, one width and one height here?": { style: 'B' },
  "No. The chest is two boxes of different sizes.": { style: 'B' },
  "When two boxes are joined, find the volume of each box, then add them.": { style: 'B' },
  "Start with the big box.": { style: 'B' },
  "It's 4 feet long, 2 feet wide and 3 feet tall.": { style: 'B' },
  "4 × 2 × 3 = 24 cubic feet.": { style: 'B' },
  "Now the small box on top.": { style: 'B' },
  "It's 2 feet long, 2 feet wide and 1 foot tall.": { style: 'B' },
  "2 × 2 × 1 = 4 cubic feet.": { style: 'B' },
  "Put them back together.": { style: 'B' },
  "24 + 4 = 28. The chest holds 28 cubic feet.": { style: 'B' },
  "Don't use the TALLEST height for the whole chest.": { style: 'B+' },
  "4 × 2 × 4 = 32 counts empty space beside the small box. Find each box, then add.": { style: 'B+' },
  // ── g5m5-t5 ──
  "Try 1-foot square tiles.": { style: 'B' },
  "Two fit along the top. Then half a foot is left.": { style: 'B' },
  "What goes in that gap?": { style: 'B' },
  "Cut each foot into halves, count the small tiles, and every 4 small tiles make 1 square foot.": { style: 'B' },
  "So cut every foot in half.": { style: 'B' },
  "Now the top is 5 halves, and the side is 3 halves.": { style: 'B' },
  "That's 3 rows of 5 small tiles, with no gap.": { style: 'B' },
  "How big is one small tile?": { style: 'B' },
  "It's 1/2 foot on each side.": { style: 'B' },
  "4 of them make 1 square foot, so one is 1/4 of a square foot.": { style: 'B' },
  "Count them.": { style: 'B' },
  "3 rows of 5 is 15 small tiles.": { style: 'B' },
  "Every 4 make 1 square foot, so that's 15/4, or 3 3/4 square feet.": { style: 'B' },
  "It's the same as 5/2 × 3/2.": { style: 'B' },
  "15 small tiles are NOT 15 square feet.": { style: 'B+' },
  "Each tile is only 1/4 of one. So the rug is 3 3/4 square feet.": { style: 'B+' },
  // ── g5m5-t6 ──
  "Look at the square tile.": { style: 'B' },
  "It has 4 square corners, like a rectangle.": { style: 'B' },
  "And 4 equal sides, like a rhombus.": { style: 'B' },
  "So which bin? Can it be both?": { style: 'B' },
  "If a shape follows a family’s rule, it belongs to that family, so one shape can have more than one name.": { style: 'B' },
  "Start with the biggest family.": { style: 'B' },
  "Every tile here has 2 pairs of sides that run side by side.": { style: 'B' },
  "So all 4 are parallelograms.": { style: 'B' },
  "Add one more rule, and the family gets smaller.": { style: 'B' },
  "4 square corners make a rectangle.": { style: 'B' },
  "4 equal sides make a rhombus.": { style: 'B' },
  "Which tile got both?": { style: 'B' },
  "The square.": { style: 'B' },
  "It has square corners and equal sides, both at once.": { style: 'B' },
  "So it's a rectangle, a rhombus and a parallelogram.": { style: 'B' },
  "One tile, 4 names.": { style: 'B' },
  "Don't flip the families around.": { style: 'B+' },
  "Every square is a rectangle, but a rectangle is NOT always a square.": { style: 'B+' },
  "It needs 4 equal sides too.": { style: 'B+' },
  // ── g5m5-t7 ──
  "You know square units.": { style: 'B' },
  "They're flat, like stickers, great for a floor.": { style: 'B' },
  "But a box goes up too.": { style: 'B' },
  "Can flat stickers fill it? No.": { style: 'B' },
  "Space inside is measured with cubes, so its unit is a cube: a cubic inch, a cubic foot, a cubic meter.": { style: 'B' },
  "Cubes come in sizes.": { style: 'B' },
  "A cubic centimeter is about as big as your fingertip.": { style: 'B' },
  "A cubic meter is so big you could sit inside it.": { style: 'B' },
  "Say each cube here is 1 cubic centimeter.": { style: 'B' },
  "One layer is 3 × 2 = 6.": { style: 'B' },
  "There are 2 layers, so that's 12.": { style: 'B' },
  "The box is 12 cubic centimeters, not just 12.": { style: 'B' },
  "Which cube should you pick?": { style: 'B' },
  "A small thing takes a small cube, so a lunch box gets cubic inches.": { style: 'B' },
  "A big truck gets cubic feet.": { style: 'B' },
  "Don't measure space in SQUARE units.": { style: 'B+' },
  "Squares only cover a floor.": { style: 'B+' },
  "It takes cubes to fill a box, so it's 12 cubic centimeters.": { style: 'B+' },
}
