/**
 * How g6m1's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G6M1_VOICE: Record<string, VoiceLine> = {
  // ── g6m1-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "A friend says the beads are 3 and 2.": { style: 'B' },
  "Which number is red? You can't tell.": { style: 'B' },
  "And does a number count one color, or all the beads?": { style: 'B' },
  "Compare a part to a part, like 3 red to 2 blue, or a part to the whole, like 3 red out of 5 beads.": { style: 'B' },
  "Look. Red beads on top, blue beads underneath.": { style: 'B' },
  "For every 3 red, there are 2 blue.": { style: 'B' },
  "We say 3 to 2. We write it with two dots: 3 : 2.": { style: 'B', say: "We say 3 to 2. We write it with two dots, 3 to 2." },
  "Now put both colors in one line.": { style: 'B' },
  "How many beads are in one set? 3 + 2 is 5.": { style: 'B' },
  "So 3 out of every 5 beads are red.": { style: 'B' },
  "Wait. The order of the words sets the order of the numbers.": { style: 'B' },
  "Red to blue is 3 : 2.": { style: 'B', say: "Red to blue is 3 to 2." },
  "Blue to red is 2 : 3.": { style: 'B', say: "Blue to red is 2 to 3." },
  "When the question asks about ALL the beads, the answer is not 3 : 2.": { style: 'B+', say: "When the question asks about all the beads, the answer is not 3 to 2." },
  "Count both colors. Red is 3 out of 5.": { style: 'B+' },
  // ── g6m1-t2 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "What if you just add 1 to each?": { style: 'B' },
  "That's 4 cups of flour and 3 eggs.": { style: 'B' },
  "Same recipe? No. There's less flour for each egg now.": { style: 'B' },
  "Multiply both numbers by the same number, and the mix stays the same, just bigger.": { style: 'B' },
  "Two batches means everything twice.": { style: 'B' },
  "Double the flour: 3 × 2 = 6 cups.": { style: 'B' },
  "Double the eggs too: 2 × 2 = 4.": { style: 'B' },
  "What about 3 batches? Multiply both by 3.": { style: 'B' },
  "Flour: 3 × 3 = 9 cups. Eggs: 2 × 3 = 6.": { style: 'B' },
  "Every column here is the same recipe.": { style: 'B' },
  "It works backwards too.": { style: 'B' },
  "Divide both by the same number.": { style: 'B' },
  "6 cups and 4 eggs, both divided by 2, are 3 cups and 2 eggs again.": { style: 'B' },
  "Don't ADD the same number to both. Adding 2 gives 5 cups and 4 eggs, a different recipe.": { style: 'B+' },
  "Multiply instead. Times 2 gives 6 cups and 4 eggs, the same recipe.": { style: 'B+' },
  // ── g6m1-t3 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Look at the tag. $5 buys the whole pack.": { style: 'B' },
  "So what does one notebook cost? Not $5. That pays for all 4.": { style: 'B' },
  "We have to share the $5 out.": { style: 'B' },
  "To find how much for one, divide the total by how many there are.": { style: 'B' },
  "Draw the $5 as one long bar.": { style: 'B' },
  "4 notebooks share it, so cut it into 4 equal parts.": { style: 'B' },
  "One part for each notebook.": { style: 'B' },
  "Now divide $5 by 4. Each part gets $1, and $1 is left over.": { style: 'B', say: "Now divide 5 dollars by 4. Each part gets 1 dollar, and 1 dollar is left over." },
  "Split that last $1 into 4 quarters, 25 cents each.": { style: 'B', say: "Split that last dollar into 4 quarters, 25 cents each." },
  "So each part is $1.25. That's one notebook.": { style: 'B', say: "So each part is 1 dollar and 25 cents. That's one notebook." },
  "Does that match the tag? Check it.": { style: 'B' },
  "4 × $1.25 = $5. Yes.": { style: 'B', say: "4 times 1 dollar and 25 cents equals 5 dollars. Yes." },
  "So one notebook costs $1.25.": { style: 'B', say: "So one notebook costs 1 dollar and 25 cents." },
  "Don't divide the other way around. 4 ÷ 5 would make a notebook 80 cents, and that's too cheap.": { style: 'B+' },
  "Put the DOLLARS first: $5 ÷ 4 = $1.25.": { style: 'B+', say: "Put the dollars first. 5 dollars divided by 4 equals 1 dollar and 25 cents." },
  // ── g6m1-t4 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "3 bags cost $12. You want 5, just 2 more.": { style: 'B' },
  "So is it $12 plus $2? No. One bag costs a lot more than $1.": { style: 'B', say: "So is it 12 dollars plus 2 dollars? No. One bag costs a lot more than 1 dollar." },
  "First we need the price of one bag.": { style: 'B' },
  "Find how much for one first, then multiply by how many you want.": { style: 'B' },
  "Split the $12 into 3 equal parts, one for each bag.": { style: 'B' },
  "$12 ÷ 3 = $4.": { style: 'B' },
  "So one bag costs $4.": { style: 'B' },
  "Now line up the 5 bags you want.": { style: 'B' },
  "What does each one cost? The same $4.": { style: 'B' },
  "The price didn't change. You just need more bags.": { style: 'B' },
  "Last step, multiply.": { style: 'B' },
  "5 bags at $4 each is 5 × $4 = $20.": { style: 'B' },
  "So movie night costs $20.": { style: 'B' },
  "Don't multiply $12 by 5. That gives $60, way too much.": { style: 'B+' },
  "$12 is the price of 3 bags, not ONE. Find one bag first, then 5 × $4 = $20.": { style: 'B+' },
  // outside the teach: a line the voice cannot read as written
  "You split 150 miles into 4 equal parts: 37.5 miles for each gallon.": { style: 'A', say: "You split 150 miles into 4 equal parts, 37 and a half miles for each gallon." },
}
