/**
 * How g6m1's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G6M1_VOICE: Record<string, VoiceLine> = {
  // ── g6m1-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "A friend says the beads are 3 and 2.": { style: 'B' },
  "Which number is red? You can't tell.": { style: 'B' },
  "And does a number count one color, or all the beads?": { style: 'B' },
  "Compare a part to a part, like 3 red to 2 blue, or a part to the whole, like 3 red out of 5 beads.": { style: 'B' },
  "Look. Red beads on top, blue beads underneath.": { style: 'B' },
  "For every 3 red, there are 2 blue.": { style: 'B' },
  "We say 3 to 2. We write it with two dots: 3 : 2.": { style: 'B', say: "We say 3 to 2. We write it with two dots, 3 to 2." },
  "Now put both colors in one line.": { style: 'B' },
  "How many beads are in one set? 3 + 2 is 5.": { style: 'B' },
  "So 3 out of every 5 beads are red.": { style: 'B' },
  "Wait. The order of the words sets the order of the numbers.": { style: 'B' },
  "Red to blue is 3 : 2.": { style: 'B', say: "Red to blue is 3 to 2." },
  "Blue to red is 2 : 3.": { style: 'B', say: "Blue to red is 2 to 3." },
  "When the question asks about ALL the beads, the answer is not 3 : 2.": { style: 'B+', say: "When the question asks about all the beads, the answer is not 3 to 2." },
  "Count both colors. Red is 3 out of 5.": { style: 'B+' },
  // ── g6m1-t2 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "What if you just add 1 to each?": { style: 'B' },
  "That's 4 cups of flour and 3 eggs.": { style: 'B' },
  "Same recipe? No. There's less flour for each egg now.": { style: 'B' },
  "Multiply both numbers by the same number, and the mix stays the same, just bigger.": { style: 'B' },
  "Two batches means everything twice.": { style: 'B' },
  "Double the flour: 3 × 2 = 6 cups.": { style: 'B' },
  "Double the eggs too: 2 × 2 = 4.": { style: 'B' },
  "What about 3 batches? Multiply both by 3.": { style: 'B' },
  "Flour: 3 × 3 = 9 cups. Eggs: 2 × 3 = 6.": { style: 'B' },
  "Every column here is the same recipe.": { style: 'B' },
  "It works backwards too.": { style: 'B' },
  "Divide both by the same number.": { style: 'B' },
  "6 cups and 4 eggs, both divided by 2, are 3 cups and 2 eggs again.": { style: 'B' },
  "Don't ADD the same number to both. Adding 2 gives 5 cups and 4 eggs, a different recipe.": { style: 'B+' },
  "Multiply instead. Times 2 gives 6 cups and 4 eggs, the same recipe.": { style: 'B+' },
  // ── g6m1-t3 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Look at the tag. $5 buys the whole pack.": { style: 'B' },
  "So what does one notebook cost? Not $5. That pays for all 4.": { style: 'B' },
  "We have to share the $5 out.": { style: 'B' },
  "To find how much for one, divide the total by how many there are.": { style: 'B' },
  "Draw the $5 as one long bar.": { style: 'B' },
  "4 notebooks share it, so cut it into 4 equal parts.": { style: 'B' },
  "One part for each notebook.": { style: 'B' },
  "Now divide $5 by 4. Each part gets $1, and $1 is left over.": { style: 'B', say: "Now divide 5 dollars by 4. Each part gets 1 dollar, and 1 dollar is left over." },
  "Split that last $1 into 4 quarters, 25 cents each.": { style: 'B', say: "Split that last dollar into 4 quarters, 25 cents each." },
  "So each part is $1.25. That's one notebook.": { style: 'B', say: "So each part is 1 dollar and 25 cents. That's one notebook." },
  "Does that match the tag? Check it.": { style: 'B' },
  "4 × $1.25 = $5. Yes.": { style: 'B', say: "4 times 1 dollar and 25 cents equals 5 dollars. Yes." },
  "So one notebook costs $1.25.": { style: 'B', say: "So one notebook costs 1 dollar and 25 cents." },
  "Don't divide the other way around. 4 ÷ 5 would make a notebook 80 cents, and that's too cheap.": { style: 'B+' },
  "Put the DOLLARS first: $5 ÷ 4 = $1.25.": { style: 'B+', say: "Put the dollars first. 5 dollars divided by 4 equals 1 dollar and 25 cents." },
  // ── g6m1-t4 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "3 bags cost $12. You want 5, just 2 more.": { style: 'B' },
  "So is it $12 plus $2? No. One bag costs a lot more than $1.": { style: 'B', say: "So is it 12 dollars plus 2 dollars? No. One bag costs a lot more than 1 dollar." },
  "First we need the price of one bag.": { style: 'B' },
  "Find how much for one first, then multiply by how many you want.": { style: 'B' },
  "Split the $12 into 3 equal parts, one for each bag.": { style: 'B' },
  "$12 ÷ 3 = $4.": { style: 'B' },
  "So one bag costs $4.": { style: 'B' },
  "Now line up the 5 bags you want.": { style: 'B' },
  "What does each one cost? The same $4.": { style: 'B' },
  "The price didn't change. You just need more bags.": { style: 'B' },
  "Last step, multiply.": { style: 'B' },
  "5 bags at $4 each is 5 × $4 = $20.": { style: 'B' },
  "So movie night costs $20.": { style: 'B' },
  "Don't multiply $12 by 5. That gives $60, way too much.": { style: 'B+' },
  "$12 is the price of 3 bags, not ONE. Find one bag first, then 5 × $4 = $20.": { style: 'B+' },
  // outside the teach: a line the voice cannot read as written
  "You split 150 miles into 4 equal parts: 37.5 miles for each gallon.": { style: 'A', say: "You split 150 miles into 4 equal parts, 37 and a half miles for each gallon." },
  // ── g6m1-t5 ──
  "You have 15 cups of nuts. How much cereal goes with them?": { style: 'B' },
  "Going from 3 and 5 straight to 15 is a big jump. So take small steps, in a table.": { style: 'B' },
  "Every column is the same mix, so you can multiply, divide or add whole columns to make a new one.": { style: 'B' },
  "Start with 3 cups of nuts and 5 cups of cereal.": { style: 'B' },
  "Double both. 3 × 2 = 6, and 5 × 2 = 10.": { style: 'B' },
  "Same mix, just twice as much.": { style: 'B' },
  "Can you add two columns together? Yes.": { style: 'B' },
  "3 + 6 = 9 cups of nuts, and 5 + 10 = 15 cups of cereal.": { style: 'B' },
  "Still the same mix.": { style: 'B' },
  "Now look. 6 + 9 = 15 cups of nuts, just what you have.": { style: 'B' },
  "So add those two columns. Underneath, 10 + 15 = 25.": { style: 'B' },
  "You need 25 cups of cereal.": { style: 'B' },
  "Don't ADD 12 to both numbers. 5 + 12 = 17 makes a different mix.": { style: 'B+' },
  "3 × 5 = 15, so multiply the cereal by 5 too. That's 25.": { style: 'B+' },
  // ── g6m1-t6 ──
  "Are there just 3 girls in the class? No.": { style: 'B' },
  "There are 30 students in all.": { style: 'B' },
  "The 2 and the 3 only say that for every 2 boys, there are 3 girls.": { style: 'B' },
  "Add the parts to find how many equal boxes make the whole, then find what one box holds.": { style: 'B' },
  "Draw it as boxes. 2 for the boys, 3 for the girls.": { style: 'B' },
  "Every box holds the same number of students.": { style: 'B' },
  "How many boxes in all? 2 + 3 = 5.": { style: 'B' },
  "Those 5 boxes hold all 30 students.": { style: 'B' },
  "So 30 ÷ 5 = 6 in each box.": { style: 'B' },
  "The girls have 3 boxes, and each box holds 6.": { style: 'B' },
  "3 × 6 = 18. So there are 18 girls.": { style: 'B' },
  "Check it. The boys have 2 × 6 = 12, and 12 + 18 = 30.": { style: 'B' },
  "Don't divide 30 by JUST the 3. That leaves out the boys.": { style: 'B+' },
  "Use all 5 boxes. 30 ÷ 5 = 6, and 3 × 6 = 18.": { style: 'B+' },
  // ── g6m1-t7 ──
  "Is 4 feet the same as 4 inches? No.": { style: 'B' },
  "A foot is much longer than an inch.": { style: 'B' },
  "So first you need one fact. How many inches fit in 1 foot?": { style: 'B' },
  "Start from one fact, 1 foot is 12 inches, then multiply to change to the smaller unit and divide to change back.": { style: 'B' },
  "1 foot is 12 inches.": { style: 'B' },
  "So 2 feet is 24 inches, and 3 feet is 36 inches.": { style: 'B' },
  "Each extra foot adds 12 more.": { style: 'B' },
  "Do you have to step up one foot at a time? No.": { style: 'B' },
  "4 feet is 4 × 12 = 48 inches.": { style: 'B' },
  "So the shelf is 48 inches long.": { style: 'B' },
  "What about going back, from inches to feet?": { style: 'B' },
  "Feet are bigger, so you divide by 12.": { style: 'B' },
  "36 ÷ 12 = 3. So 36 inches is 3 feet.": { style: 'B' },
  "Going to the smaller unit, don't DIVIDE.": { style: 'B+' },
  "Smaller units mean more of them, so multiply. 4 × 12 = 48 inches.": { style: 'B+' },
  // ── g6m1-t8 ──
  "36 miles is how far you rode in all, over 3 hours.": { style: 'B' },
  "So how far did you ride in one hour? The total can't say.": { style: 'B' },
  "A faster rider could do the same 36 miles in 2 hours.": { style: 'B' },
  "How fast you go is how far you go in one hour, so divide the distance by the hours.": { style: 'B' },
  "Cut the ride up by the hours.": { style: 'B' },
  "3 hours means 3 equal jumps, one for each hour.": { style: 'B' },
  "So how long is one jump? 36 ÷ 3 = 12.": { style: 'B' },
  "Each jump is 12 miles. So you ride 12 miles in one hour.": { style: 'B' },
  "12 miles in each hour is 12 miles per hour.": { style: 'B' },
  "Check it. 3 × 12 = 36 miles, the whole ride.": { style: 'B' },
  "Don't divide the HOURS by the miles.": { style: 'B+' },
  "The miles go first. 36 ÷ 3, not 3 ÷ 36.": { style: 'B+' },
  // lines outside the teach
  "You divided 150 minutes by 60 and got 2.5 hours.": { style: 'A', say: "You divided 150 minutes by 60 and got two and a half hours." },
}
