/**
 * How g6m3's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 * Decimals: t1–t3 are about where the point goes — lining points up, counting places after it, putting it above — so a
 * decimal is read digit by digit ("8.52" → "eight point five two"). "Here's the part people mix up." and
 * "Okay. Your turn." share g5m1's rows.
 */
import type { VoiceLine } from './styles'

export const G6M3_VOICE: Record<string, VoiceLine> = {
  // ── g6m3-t1 ──
  "Can you just line up the last digits? No.": { style: 'B' },
  "The 5 tenths would sit on top of the 5 thousandths.": { style: 'B' },
  "Those are different places.": { style: 'B' },
  "Line up the points, fill each empty place with a 0, then add or take away like whole numbers.": { style: 'B', say: "Line up the points, fill each empty place with a zero, then add or take away like whole numbers." },
  "Give 12.5 three places, like 3.875. Write it 12.500.": { style: 'B', say: "Give twelve point five three places, like three point eight seven five. Write it twelve point five zero zero." },
  "The zeros don't change how much it is.": { style: 'B' },
  "Start at the right. 0 − 5 won't go.": { style: 'B', say: "Start at the right. Zero minus 5 won't go." },
  "So trade 1 tenth. It makes 9 hundredths and 10 thousandths.": { style: 'B' },
  "10 − 5 = 5. 9 − 7 = 2.": { style: 'B' },
  "Tenths. 4 − 8 won't go, so trade 1 one. 14 − 8 = 6.": { style: 'B' },
  "Ones. 1 − 3 won't go, so trade the ten. 11 − 3 = 8.": { style: 'B' },
  "The point comes straight down. So 8.625 kilometers are left.": { style: 'B', say: "The point comes straight down. So eight point six two five kilometers are left." },
  "Don't bring the 7 and 5 DOWN with nothing above them.": { style: 'B+', say: "Don't bring the 7 and 5 down with nothing above them." },
  "That gives 8.775. Fill in zeros and trade. It's 8.625.": { style: 'B+', say: "That gives eight point seven seven five. Fill in zeros and trade. It's eight point six two five." },
  "A long bike ride. A bike trail is 12.5 kilometers long. You have ridden 3.875 kilometers. How far is left?": { style: 'A', say: "A long bike ride. A bike trail is twelve point five kilometers long. You have ridden three point eight seven five kilometers. How far is left?" },
  "Now you try. Take away. 15.4 − 6.237 = ? Line up the points. Fill the empty places with 0s. Take away from the right.": { style: 'A', say: "Now you try. Take away. Fifteen point four minus six point two three seven equals what? Line up the points. Fill the empty places with zeros. Take away from the right." },
  "Try a new one. Take away. 20.3 − 7.456 = ?": { style: 'A', say: "Try a new one. Take away. Twenty point three minus seven point four five six equals what?" },
  "How many places after the point does 15.4 need so it matches 6.237?": { style: 'A', say: "How many places after the point does fifteen point four need so it matches six point two three seven?" },
  "Write 15.400. The thousandths are 0 − 7, so trade from the places to the left.": { style: 'A', say: "Write fifteen point four zero zero. The thousandths are zero minus 7, so trade from the places to the left." },
  "Write 20.3 with three places after the point first.": { style: 'A', say: "Write twenty point three with three places after the point first." },
  "You filled in zeros and found 20.3 − 7.456 = 12.844.": { style: 'A', say: "You filled in zeros and found twenty point three minus seven point four five six equals twelve point eight four four." },
  // ── g6m3-t2 ── ("So where does the point go in the answer?" is also t3's line: one row)
  "When you add, you line up the points.": { style: 'B' },
  "But when you multiply, lining them up doesn't help.": { style: 'B' },
  "So where does the point go in the answer?": { style: 'B' },
  "Multiply as if there were no points, then give the answer as many places after the point as both numbers have together.": { style: 'B' },
  "Cover the points. That leaves 24 × 13.": { style: 'B' },
  "24 × 3 = 72, and 24 × 10 = 240.": { style: 'B' },
  "Add the rows. 72 + 240 = 312.": { style: 'B' },
  "Now the point. 2.4 has 1 place after the point.": { style: 'B', say: "Now the point. Two point four has 1 place after the point." },
  "1.3 has 1 place too.": { style: 'B', say: "One point three has 1 place too." },
  "1 + 1 = 2, so the answer needs 2 places.": { style: 'B' },
  "Start at the right of 312 and count 2 places left. That's 3.12.": { style: 'B', say: "Start at the right of 312 and count 2 places left. That's three point one two." },
  "Is that about right? 2 × 1 = 2 and 3 × 2 = 6, and 3.12 is in between. Yes.": { style: 'B', say: "Is that about right? 2 times 1 equals 2 and 3 times 2 equals 6, and three point one two is in between. Yes." },
  "So the bed is 3.12 square meters.": { style: 'B', say: "So the bed is three point one two square meters." },
  "Don't COPY the point from the numbers above. That gives 31.2.": { style: 'B+', say: "Don't copy the point from the numbers above. That gives thirty-one point two." },
  "Count the places. 1 + 1 = 2, so it's 3.12.": { style: 'B+', say: "Count the places. 1 plus 1 equals 2, so it's three point one two." },
  "A garden bed. A garden bed is 2.4 meters long and 1.3 meters wide. What is its area?": { style: 'A', say: "A garden bed. A garden bed is two point four meters long and one point three meters wide. What is its area?" },
  "Now you try. Multiply. 3.2 × 1.4 = ? Multiply without the points. Count the places. Put the point back.": { style: 'A', say: "Now you try. Multiply. Three point two times one point four equals what? Multiply without the points. Count the places. Put the point back." },
  "Try a new one. Multiply. 4.3 × 2.1 = ?": { style: 'A', say: "Try a new one. Multiply. Four point three times two point one equals what?" },
  "Count the places after the point in 3.2 and in 1.4. Add them up.": { style: 'A', say: "Count the places after the point in three point two and in one point four. Add them up." },
  "How many places after the point are in 4.3 and 2.1 together?": { style: 'A', say: "How many places after the point are in four point three and two point one together?" },
  "You counted the places and found 4.3 × 2.1 = 9.03.": { style: 'A', say: "You counted the places and found four point three times two point one equals nine point zero three." },
  // ── g6m3-t3 ──
  "You know how to divide whole numbers this way.": { style: 'B' },
  "But 8.52 has a point inside it.": { style: 'B', say: "But eight point five two has a point inside it." },
  "Put the point in the answer straight above the point inside, then divide like whole numbers.": { style: 'B' },
  "Before you divide anything, write the point on top.": { style: 'B' },
  "Put it straight above the point in 8.52.": { style: 'B', say: "Put it straight above the point in eight point five two." },
  "Do it first, and it can't get lost.": { style: 'B' },
  "Start on the left. How many 4s fit into 8? 2.": { style: 'B', say: "Start on the left. How many fours fit into 8? 2." },
  "Write the 2 on top. 2 × 4 = 8, and 8 − 8 = 0.": { style: 'B' },
  "Bring down the 5.": { style: 'B' },
  "4 fits into 5 one time. 5 − 4 = 1.": { style: 'B' },
  "Bring down the 2 to make 12. 4 fits into 12 three times, with nothing left.": { style: 'B' },
  "So each piece is 2.13 meters long.": { style: 'B', say: "So each piece is two point one three meters long." },
  "Don't DROP the point and write 213.": { style: 'B+', say: "Don't drop the point and write 213." },
  "That's longer than the whole rope. The point sits straight above, so it's 2.13.": { style: 'B+', say: "That's longer than the whole rope. The point sits straight above, so it's two point one three." },
  "Cut the rope. A rope is 8.52 meters long. You cut it into 4 equal pieces. How long is each piece?": { style: 'A', say: "Cut the rope. A rope is eight point five two meters long. You cut it into 4 equal pieces. How long is each piece?" },
  "Now you try. Divide. 9.45 ÷ 3 = ? Put the point on top first. Then divide like whole numbers.": { style: 'A', say: "Now you try. Divide. Nine point four five divided by 3 equals what? Put the point on top first. Then divide like whole numbers." },
  "Try a new one. Divide. 6.72 ÷ 4 = ?": { style: 'A', say: "Try a new one. Divide. Six point seven two divided by 4 equals what?" },
  "You put the point on top and found 6.72 ÷ 4 = 1.68.": { style: 'A', say: "You put the point on top and found six point seven two divided by 4 equals one point six eight." },
  // ── g6m3-t4 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows). The point is the topic: decimals as digits.
  "You can divide by a whole number.": { style: 'B' },
  "But 0.4 is not whole.": { style: 'B', say: "But zero point four is not whole." },
  "How many 0.4s fit in 9.6? That's hard to see.": { style: 'B', say: "How many zero point fours fit in nine point six? That's hard to see." },
  "Multiply both numbers by 10 or 100 until the number you divide by is whole, and the answer stays the same.": { style: 'B' },
  "Why does that work? Look at 6 ÷ 2 = 3.": { style: 'B' },
  "Make both 10 times bigger. 60 ÷ 20 is still 3.": { style: 'B' },
  "Both grew the same, so the answer didn't move.": { style: 'B' },
  "0.4 has 1 place after the point, so times 10 makes it 4.": { style: 'B', say: "Zero point four has 1 place after the point, so times 10 makes it 4." },
  "Do the same to 9.6. It becomes 96.": { style: 'B', say: "Do the same to nine point six. It becomes 96." },
  "So 9.6 ÷ 0.4 turns into 96 ÷ 4, one you can do.": { style: 'B', say: "So nine point six divided by zero point four turns into 96 divided by 4, one you can do." },
  "4 fits into 9 two times, 1 left.": { style: 'B' },
  "Bring down the 6 to make 16. 4 fits four times, with nothing left.": { style: 'B' },
  "So 9.6 ÷ 0.4 = 24. You get 24 pieces of ribbon.": { style: 'B', say: "So nine point six divided by zero point four equals 24. You get 24 pieces of ribbon." },
  "Don't grow ONLY the 0.4. That gives 2.4, far too few.": { style: 'B+', say: "Don't grow only the zero point four. That gives two point four, far too few." },
  "Grow both numbers. 96 ÷ 4 = 24.": { style: 'B+' },
  "Ribbon pieces. A ribbon is 9.6 meters long. You cut it into pieces that are 0.4 meters long. How many pieces do you get?": { style: 'A', say: "Ribbon pieces. A ribbon is nine point six meters long. You cut it into pieces that are zero point four meters long. How many pieces do you get?" },
  "Now you try. Divide. 7.2 ÷ 0.3 = ? Multiply both numbers by 10 or 100 until the outside number is whole. Then divide.": { style: 'A', say: "Now you try. Divide. Seven point two divided by zero point three equals what? Multiply both numbers by 10 or 100 until the outside number is whole. Then divide." },
  "Try a new one. Divide. 1.56 ÷ 0.12 = ?": { style: 'A', say: "Try a new one. Divide. One point five six divided by zero point one two equals what?" },
  "What do you multiply 0.3 by to make it whole?": { style: 'A', say: "What do you multiply zero point three by to make it whole?" },
  "How many places after the point does 0.12 have? Is 10 enough to make it whole?": { style: 'A', say: "How many places after the point does zero point one two have? Is 10 enough to make it whole?" },
  "You multiplied both by 100 and found 1.56 ÷ 0.12 = 13.": { style: 'A', say: "You multiplied both by 100 and found one point five six divided by zero point one two equals 13." },
  // ── g6m3-t5 ── (its "Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Nobody knows 5,184 ÷ 24 by heart.": { style: 'B' },
  "And 24 isn't in the times tables.": { style: 'B' },
  "So how do we start? One small piece at a time.": { style: 'B' },
  "Go one digit at a time: guess with a round number, then multiply, take away and bring down.": { style: 'B' },
  "24 won't fit into 5, so start with 51.": { style: 'B' },
  "Here's the trick: 24 is about 20, and 51 holds two 20s. So try 2.": { style: 'B', say: "Here's the trick, 24 is about 20, and 51 holds two twenties. So try 2." },
  "2 × 24 = 48, which fits.": { style: 'B' },
  "Take it away. 51 − 48 = 3.": { style: 'B' },
  "Now bring down the 8. That makes 38.": { style: 'B' },
  "24 fits into 38 one time, so 1 goes on top.": { style: 'B' },
  "And 38 − 24 = 14.": { style: 'B' },
  "Bring down the 4 to make 144.": { style: 'B' },
  "Guess 7. But 7 × 24 = 168, too big.": { style: 'B' },
  "So try 6. 6 × 24 = 144, exactly.": { style: 'B' },
  "Nothing is left, so the farm fills 216 boxes.": { style: 'B' },
  "In 4,920 ÷ 24, 24 won't fit into 12. Don't SKIP that place.": { style: 'B+' },
  "Write a 0 on top and bring down the next digit. That makes 205, not 25.": { style: 'B+', say: "Write a zero on top and bring down the next digit. That makes 205, not 25." },
  // ── g6m3-t6 ── (its "Here's the part people mix up." and "Okay. Your turn." are g5m1's rows). Money is how much: said as dollars and cents.
  "The 4-pack has the lower price tag.": { style: 'B' },
  "But it also has fewer boxes in it.": { style: 'B' },
  "So is it really the better buy? The tag alone can't tell you.": { style: 'B' },
  "Find the price of one in each pack, and the lower price for one is the better buy.": { style: 'B' },
  "Start with the 4-pack.": { style: 'B' },
  "$3.00 is shared by 4 boxes. How much is one?": { style: 'B', say: "3 dollars is shared by 4 boxes. How much is one?" },
  "3.00 ÷ 4 = 0.75.": { style: 'B', say: "3 dollars divided by 4 equals 75 cents." },
  "So one box costs $0.75.": { style: 'B', say: "So one box costs 75 cents." },
  "Now the 6-pack, the same way.": { style: 'B' },
  "$4.20 is shared by 6 boxes.": { style: 'B', say: "4 dollars and 20 cents is shared by 6 boxes." },
  "4.20 ÷ 6 = 0.70.": { style: 'B', say: "4 dollars and 20 cents divided by 6 equals 70 cents." },
  "So one box costs $0.70.": { style: 'B', say: "So one box costs 70 cents." },
  "Now put the two side by side.": { style: 'B' },
  "$0.70 is less than $0.75.": { style: 'B', say: "70 cents is less than 75 cents." },
  "So the 6-pack is the better buy, even with the higher price tag.": { style: 'B' },
  "Don't just grab the LOWER price tag. $3.00 buys fewer boxes.": { style: 'B+', say: "Don't just grab the lower price tag. 3 dollars buys fewer boxes." },
  "Compare the price for one. 70 cents beats 75 cents.": { style: 'B+' },
  "Juice boxes. A 4-pack of juice boxes costs $3.00. A 6-pack costs $4.20. Which pack is the better buy?": { style: 'A', say: "Juice boxes. A 4-pack of juice boxes costs 3 dollars. A 6-pack costs 4 dollars and 20 cents. Which pack is the better buy?" },
}
