/**
 * How g6m5's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 * "Here's the part people mix up." and "Okay. Your turn." already have rows in g5m1.ts.
 * A number next to a letter (3n) is said "3 n"; a small raised number past ³ is said "to the fifth".
 * Algebra: a number next to a letter ("3x") is said "3 x"; "3(x + 2)" is said "3 times x plus 2, all together".
 */
import type { VoiceLine } from './styles'

export const G6M5_VOICE: Record<string, VoiceLine> = {
  // ── g6m5-t1 ──
  "You can count the loose ones: 3.": { style: 'B' },
  "But how many are in the closed bag?": { style: 'B' },
  "You can't tell, so the total isn't one number yet.": { style: 'B' },
  "A letter can stand for a number you don't know yet, and once you know it, you put it where the letter is.": { style: 'B' },
  "So give the bag a name: n.": { style: 'B' },
  "It stands for how many marbles are inside.": { style: 'B' },
  "You have n, and 3 more. That's n + 3.": { style: 'B' },
  "Now open the bag and count. There are 5.": { style: 'B' },
  "So this time, n is 5.": { style: 'B' },
  "Wherever you see n, put a 5.": { style: 'B' },
  "So n + 3 becomes 5 + 3.": { style: 'B' },
  "And 5 + 3 is 8. You have 8 marbles.": { style: 'B' },
  "n does NOT mean marbles.": { style: 'B+' },
  "n is a number: how many are in the bag.": { style: 'B+' },
  // ── g6m5-t2 ──
  "You say the 5 first. But do you write it first?": { style: 'B' },
  "Look at the strips.": { style: 'B' },
  "Jon starts with Mia's n, then 5 more go on the end.": { style: 'B' },
  "Each phrase hides an action: \"more than\" adds, \"less than\" takes away, and \"times\" multiplies.": { style: 'B' },
  "So Jon has n, then 5 more.": { style: 'B' },
  "More than means add: n + 5.": { style: 'B' },
  "Ali has 3 times as many as Mia: three strips of n.": { style: 'B' },
  "So you write 3 × n, or just 3n.": { style: 'B', say: "So you write 3 times n, or just 3 n." },
  "Zoe has 2 less than Mia. Start with n, then take 2 away.": { style: 'B' },
  "So it's n − 2.": { style: 'B' },
  "The n goes first, even though you said 2 first.": { style: 'B' },
  "\"2 less than n\" is NOT 2 − n.": { style: 'B+' },
  "Start with n, then take 2 away.": { style: 'B+' },
  "You saw \"times\" and wrote 4n.": { style: 'A', say: "You saw times and wrote 4 n." },
  // ── g6m5-t3 ──
  "Look at 3n + 2. Can you work it out yet?": { style: 'B', say: "Look at 3 n plus 2. Can you work it out yet?" },
  "No. While n is a letter, 3n is not a number you know.": { style: 'B', say: "No. While n is a letter, 3 n is not a number you know." },
  "So first, find n.": { style: 'B' },
  "Put each number in place of its letter, then do the math.": { style: 'B' },
  "You're buying 4 cupcakes, so n is 4.": { style: 'B' },
  "3n means 3 × n.": { style: 'B', say: "3 n means 3 times n." },
  "So put 4 in: 3 × 4 + 2.": { style: 'B' },
  "Multiply first. 3 × 4 is 12.": { style: 'B' },
  "Then add 2. 12 + 2 is 14.": { style: 'B' },
  "You pay 14 dollars.": { style: 'B' },
  "Two letters work the same way.": { style: 'B' },
  "For a + b, with a = 6 and b = 5, it's 6 + 5, which is 11.": { style: 'B' },
  "When n = 4, 3n is NOT 34.": { style: 'B+', say: "When n equals 4, 3 n is not 34." },
  "It's 3 × 4, which is 12.": { style: 'B+' },
  "Party shopping. Cupcakes cost 3 dollars each, and a card costs 2 dollars. For n cupcakes and a card you pay 3n + 2 dollars. What do you pay for 4 cupcakes?": { style: 'A', say: "Party shopping. Cupcakes cost 3 dollars each, and a card costs 2 dollars. For n cupcakes and a card you pay 3 n plus 2 dollars. What do you pay for 4 cupcakes?" },
  "Now you try. What is 2n + 5 when n = 6? Put the number where the letter is. Then do the math.": { style: 'A', say: "Now you try. What is 2 n plus 5 when n equals 6? Put the number where the letter is. Then do the math." },
  "Try a new one. What is 4n − 3 when n = 7?": { style: 'A', say: "Try a new one. What is 4 n minus 3 when n equals 7?" },
  "What does 2n mean?": { style: 'A', say: "What does 2 n mean?" },
  "What does 4n mean?": { style: 'A', say: "What does 4 n mean?" },
  "You put 7 in for n and worked out 4n − 3.": { style: 'A', say: "You put 7 in for n and worked out 4 n minus 3." },
  // ── g6m5-t4 ──
  "You could write 4 × 4 × 4.": { style: 'B' },
  "But what about six 4s? Would you write them all?": { style: 'B', say: "But what about six fours? Would you write them all?" },
  "That's slow, and easy to lose count.": { style: 'B' },
  "The small raised number says how many of the big number to multiply, so 4³ is 4 × 4 × 4.": { style: 'B', say: "The small raised number says how many of the big number to multiply, so 4 with a small 3 is 4 times 4 times 4." },
  "So write 4 with a small 3 up high.": { style: 'B' },
  "The 4 is what you multiply.": { style: 'B' },
  "The 3 says how many: 4 × 4 × 4.": { style: 'B' },
  "Multiply two at a time. 4 × 4 is 16.": { style: 'B' },
  "Then 16 × 4 is 64. So the shop has 64 toys.": { style: 'B' },
  "Two have names.": { style: 'B' },
  "5² is 5 × 5, or 25. We say five squared.": { style: 'B', say: "5 with a small 2 is 5 times 5, or 25. We say five squared." },
  "2³ is 2 × 2 × 2, or 8. We say two cubed.": { style: 'B', say: "2 with a small 3 is 2 times 2 times 2, or 8. We say two cubed." },
  "4³ does NOT mean 4 × 3.": { style: 'B+' },
  "It means 4 × 4 × 4, which is 64.": { style: 'B+' },
  "Try a new one. What is 2⁵?": { style: 'A', say: "Try a new one. What is 2 to the fifth?" },
  "How many 3s does the small number say to multiply?": { style: 'A', say: "How many threes does the small number say to multiply?" },
  "How many 2s does the small number say to multiply?": { style: 'A', say: "How many twos does the small number say to multiply?" },
  "Write five 2s with × between them. Keep doubling.": { style: 'A', say: "Write five twos with times signs between them. Keep doubling." },
  "You multiplied five 2s and got 32.": { style: 'A', say: "You multiplied five twos and got 32." },
  // ── g6m5-t5 ──
  "One friend adds first: 2 + 3 is 5, 4² is 16, and 5 × 16 is 80.": { style: 'B' },
  "But is that right?": { style: 'B' },
  "We all need one order.": { style: 'B' },
  "Parentheses first, then exponents, then × and ÷, then + and −, each pair from left to right.": { style: 'B', say: "Parentheses first, then exponents, then times and divide, then plus and minus, each pair from left to right." },
  "Any parentheses? No.": { style: 'B' },
  "So 4² goes first. 4 × 4 is 16.": { style: 'B' },
  "Now it's 2 + 3 × 16.": { style: 'B' },
  "Multiply next. 3 × 16 is 48.": { style: 'B' },
  "Add last. 2 + 48 is 50.": { style: 'B' },
  "The friend with 50 is right.": { style: 'B' },
  "Now put parentheses around 2 + 3. They go first: 5.": { style: 'B' },
  "Then 4² is 16, and 5 × 16 is 80.": { style: 'B' },
  "Same numbers, new answer.": { style: 'B' },
  "Don't ADD first just because + comes first.": { style: 'B+' },
  "Multiply first: 2 + 3 × 16 is 50, not 80.": { style: 'B+' },
  "Now you try. What is 5 + 2 × 3²? Parentheses, then exponents, then × and ÷, then + and −.": { style: 'A', say: "Now you try. What is 5 plus 2 times 3 squared? Parentheses, then exponents, then times and divide, then plus and minus." },
  "Try a new one. What is (1 + 3)² − 2 × 5?": { style: 'A', say: "Try a new one. What is 1 plus 3, all in parentheses, squared, minus 2 times 5?" },
  // ── g6m5-t6 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "One bag holds x pens and 2 erasers. That's x + 2.": { style: 'B' },
  "You don't know x, so x and 2 can't join into one number.": { style: 'B' },
  'So how do you write three bags?': { style: 'B' },
  'The number outside the parentheses multiplies every part inside, so 3(x + 2) is the same amount as 3x + 6.': { style: 'B', say: 'The number outside the parentheses multiplies every part inside, so 3 times x plus 2, all together, is the same amount as 3 x plus 6.' },
  'Put parentheses around x + 2.': { style: 'B' },
  'Now x and 2 stay together, one whole bag.': { style: 'B' },
  "Three bags? Write a 3 in front. That's 3(x + 2).": { style: 'B', say: "Three bags? Write a 3 in front. That's 3 times x plus 2, all together." },
  'Now open the bags and count.': { style: 'B' },
  "Every bag has an x, so that's 3 x's, which we write 3x.": { style: 'B', say: "Every bag has an x, so that's 3 x's, which we write 3 x." },
  'Every bag has 2 erasers, so 3 × 2 = 6 erasers.': { style: 'B' },
  'So 3(x + 2) = 3x + 6.': { style: 'B', say: 'So 3 times x plus 2, all together, equals 3 x plus 6.' },
  'Does it really match? Try x = 4.': { style: 'B' },
  'One bag is 4 + 2 = 6, and 3 bags is 3 × 6 = 18.': { style: 'B' },
  'The other way, 3x is 3 × 4 = 12, and 12 + 6 = 18.': { style: 'B', say: 'The other way, 3 x is 3 times 4 equals 12, and 12 plus 6 equals 18.' },
  'Same amount.': { style: 'B' },
  "Don't multiply ONLY the x.": { style: 'B+' },
  "3(x + 2) is not 3x + 2. The 3 multiplies the 2 too, so it's 3x + 6.": { style: 'B+', say: "3 times x plus 2, all together, is not 3 x plus 2. The 3 multiplies the 2 too, so it's 3 x plus 6." },
  // ── g6m5-t7 ──
  'You could guess. Try 3. 3 + 4 is 7, too light.': { style: 'B' },
  'Try 6. 6 + 4 is 10, too heavy.': { style: 'B' },
  'Is there a way with no guessing? Yes.': { style: 'B' },
  'To get x alone, take the same amount off both sides, so the scale stays level.': { style: 'B' },
  'The 4 is in the way of x. So take 4 off the left.': { style: 'B' },
  "But if that's all you do, the scale tips.": { style: 'B' },
  'So take 4 off the right too, and it stays level.': { style: 'B' },
  'Now look at each side.': { style: 'B' },
  'On the left, 4 − 4 leaves nothing, so x is alone.': { style: 'B' },
  'On the right, 9 − 4 = 5.': { style: 'B' },
  'So x = 5.': { style: 'B' },
  'Does 5 really work? Put 5 back where x was.': { style: 'B' },
  '5 + 4 = 9, and the other side is 9.': { style: 'B' },
  'Both sides match, so the bag holds 5 marbles.': { style: 'B' },
  "Don't ADD the 4 to the other side.": { style: 'B+' },
  'x + 4 = 9 does not make x = 13.': { style: 'B+' },
  'Take 4 off both sides, so x = 5.': { style: 'B+' },
  // ── g6m5-t8 ──
  'Three tickets, each x dollars, cost 24 dollars.': { style: 'B' },
  "Nothing is added to x this time, so taking something away won't help.": { style: 'B' },
  'So how do you find one x?': { style: 'B' },
  '3x is 3 equal parts, so divide both sides by 3 to find one x.': { style: 'B', say: '3 x is 3 equal parts, so divide both sides by 3 to find one x.' },
  'Draw it. Three equal parts of x make 24.': { style: 'B' },
  'Three groups of x is written 3x.': { style: 'B', say: 'Three groups of x is written 3 x.' },
  'So 3x = 24.': { style: 'B', say: 'So 3 x equals 24.' },
  'Split both sides into 3 equal parts.': { style: 'B' },
  '3x ÷ 3 is one x.': { style: 'B', say: '3 x divided by 3 is one x.' },
  '24 ÷ 3 = 8.': { style: 'B' },
  'So x = 8.': { style: 'B' },
  'Does 8 really work? Put 8 back where x was.': { style: 'B' },
  '3 × 8 = 24, and that matches.': { style: 'B' },
  'So one ticket costs 8 dollars.': { style: 'B' },
  "Don't SUBTRACT the 3.": { style: 'B+' },
  '3x = 24 does not make x = 21.': { style: 'B+', say: '3 x equals 24 does not make x equals 21.' },
  'The 3 multiplies x, so divide by 3 instead. That gives 8.': { style: 'B+' },
  // ── g6m5-t9 ──
  'Try listing them. 4, 5, 6, and 3 and a half.': { style: 'B' },
  'They never stop, even past 100.': { style: 'B' },
  'So how can you show every one at once? On a number line.': { style: 'B' },
  'x > 3 means every number bigger than 3, so draw an open dot at 3 and an arrow to the right.': { style: 'B' },
  'Start at 3. Does 3 itself work?': { style: 'B' },
  'No, 3 is not more than 3.': { style: 'B' },
  'So the dot at 3 stays open, an empty circle.': { style: 'B' },
  'Bigger numbers are to the right.': { style: 'B' },
  'So color the line from 3 all the way right.': { style: 'B' },
  'Then add an arrow, because it never stops.': { style: 'B' },
  'Now a new one. x ≤ 5 means 5 or less.': { style: 'B' },
  '5 works this time, so fill the dot in.': { style: 'B' },
  'Less means smaller, so color the line to the left.': { style: 'B' },
  "Don't FILL the dot for x > 3.": { style: 'B+', say: "Don't fill the dot for x greater than 3." },
  'The 3 does not work, so its dot stays open.': { style: 'B+' },
  // Lines outside the teach that the voice could not read as written (text unchanged; `say` spells the math).
  'Now you try. Which is the same as 4(x + 3)? Multiply the number outside by every part inside.': { style: 'A', say: 'Now you try. Which is the same as 4 times x plus 3, all together? Multiply the number outside by every part inside.' },
  'Try a new one. Which is the same as 5(x + 1)?': { style: 'A', say: 'Try a new one. Which is the same as 5 times x plus 1, all together?' },
  'You multiplied the 5 by both parts to get 5x + 5.': { style: 'A', say: 'You multiplied the 5 by both parts to get 5 x plus 5.' },
  'Now you try. Solve 4x = 28. What is x? Divide both sides by the number in front of x.': { style: 'A', say: 'Now you try. Solve 4 x equals 28. What is x? Divide both sides by the number in front of x.' },
  'Try a new one. Solve 6x = 54. What is x?': { style: 'A', say: 'Try a new one. Solve 6 x equals 54. What is x?' },
}
