/**
 * How g6m5's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 * "Here's the part people mix up." and "Okay. Your turn." already have rows in g5m1.ts.
 * A number next to a letter (3n) is said "3 n"; a small raised number past ³ is said "to the fifth".
 */
import type { VoiceLine } from './styles'

export const G6M5_VOICE: Record<string, VoiceLine> = {
  // ── g6m5-t1 ──
  "You can count the loose ones: 3.": { style: 'B' },
  "But how many are in the closed bag?": { style: 'B' },
  "You can't tell, so the total isn't one number yet.": { style: 'B' },
  "A letter can stand for a number you don't know yet, and once you know it, you put it where the letter is.": { style: 'B' },
  "So give the bag a name: n.": { style: 'B' },
  "It stands for how many marbles are inside.": { style: 'B' },
  "You have n, and 3 more. That's n + 3.": { style: 'B' },
  "Now open the bag and count. There are 5.": { style: 'B' },
  "So this time, n is 5.": { style: 'B' },
  "Wherever you see n, put a 5.": { style: 'B' },
  "So n + 3 becomes 5 + 3.": { style: 'B' },
  "And 5 + 3 is 8. You have 8 marbles.": { style: 'B' },
  "n does NOT mean marbles.": { style: 'B+' },
  "n is a number: how many are in the bag.": { style: 'B+' },
  // ── g6m5-t2 ──
  "You say the 5 first. But do you write it first?": { style: 'B' },
  "Look at the strips.": { style: 'B' },
  "Jon starts with Mia's n, then 5 more go on the end.": { style: 'B' },
  "Each phrase hides an action: \"more than\" adds, \"less than\" takes away, and \"times\" multiplies.": { style: 'B' },
  "So Jon has n, then 5 more.": { style: 'B' },
  "More than means add: n + 5.": { style: 'B' },
  "Ali has 3 times as many as Mia: three strips of n.": { style: 'B' },
  "So you write 3 × n, or just 3n.": { style: 'B', say: "So you write 3 times n, or just 3 n." },
  "Zoe has 2 less than Mia. Start with n, then take 2 away.": { style: 'B' },
  "So it's n − 2.": { style: 'B' },
  "The n goes first, even though you said 2 first.": { style: 'B' },
  "\"2 less than n\" is NOT 2 − n.": { style: 'B+' },
  "Start with n, then take 2 away.": { style: 'B+' },
  "You saw \"times\" and wrote 4n.": { style: 'A', say: "You saw times and wrote 4 n." },
  // ── g6m5-t3 ──
  "Look at 3n + 2. Can you work it out yet?": { style: 'B', say: "Look at 3 n plus 2. Can you work it out yet?" },
  "No. While n is a letter, 3n is not a number you know.": { style: 'B', say: "No. While n is a letter, 3 n is not a number you know." },
  "So first, find n.": { style: 'B' },
  "Put each number in place of its letter, then do the math.": { style: 'B' },
  "You're buying 4 cupcakes, so n is 4.": { style: 'B' },
  "3n means 3 × n.": { style: 'B', say: "3 n means 3 times n." },
  "So put 4 in: 3 × 4 + 2.": { style: 'B' },
  "Multiply first. 3 × 4 is 12.": { style: 'B' },
  "Then add 2. 12 + 2 is 14.": { style: 'B' },
  "You pay 14 dollars.": { style: 'B' },
  "Two letters work the same way.": { style: 'B' },
  "For a + b, with a = 6 and b = 5, it's 6 + 5, which is 11.": { style: 'B' },
  "When n = 4, 3n is NOT 34.": { style: 'B+', say: "When n equals 4, 3 n is not 34." },
  "It's 3 × 4, which is 12.": { style: 'B+' },
  "Party shopping. Cupcakes cost 3 dollars each, and a card costs 2 dollars. For n cupcakes and a card you pay 3n + 2 dollars. What do you pay for 4 cupcakes?": { style: 'A', say: "Party shopping. Cupcakes cost 3 dollars each, and a card costs 2 dollars. For n cupcakes and a card you pay 3 n plus 2 dollars. What do you pay for 4 cupcakes?" },
  "Now you try. What is 2n + 5 when n = 6? Put the number where the letter is. Then do the math.": { style: 'A', say: "Now you try. What is 2 n plus 5 when n equals 6? Put the number where the letter is. Then do the math." },
  "Try a new one. What is 4n − 3 when n = 7?": { style: 'A', say: "Try a new one. What is 4 n minus 3 when n equals 7?" },
  "What does 2n mean?": { style: 'A', say: "What does 2 n mean?" },
  "What does 4n mean?": { style: 'A', say: "What does 4 n mean?" },
  "You put 7 in for n and worked out 4n − 3.": { style: 'A', say: "You put 7 in for n and worked out 4 n minus 3." },
  // ── g6m5-t4 ──
  "You could write 4 × 4 × 4.": { style: 'B' },
  "But what about six 4s? Would you write them all?": { style: 'B', say: "But what about six fours? Would you write them all?" },
  "That's slow, and easy to lose count.": { style: 'B' },
  "The small raised number says how many of the big number to multiply, so 4³ is 4 × 4 × 4.": { style: 'B', say: "The small raised number says how many of the big number to multiply, so 4 with a small 3 is 4 times 4 times 4." },
  "So write 4 with a small 3 up high.": { style: 'B' },
  "The 4 is what you multiply.": { style: 'B' },
  "The 3 says how many: 4 × 4 × 4.": { style: 'B' },
  "Multiply two at a time. 4 × 4 is 16.": { style: 'B' },
  "Then 16 × 4 is 64. So the shop has 64 toys.": { style: 'B' },
  "Two have names.": { style: 'B' },
  "5² is 5 × 5, or 25. We say five squared.": { style: 'B', say: "5 with a small 2 is 5 times 5, or 25. We say five squared." },
  "2³ is 2 × 2 × 2, or 8. We say two cubed.": { style: 'B', say: "2 with a small 3 is 2 times 2 times 2, or 8. We say two cubed." },
  "4³ does NOT mean 4 × 3.": { style: 'B+' },
  "It means 4 × 4 × 4, which is 64.": { style: 'B+' },
  "Try a new one. What is 2⁵?": { style: 'A', say: "Try a new one. What is 2 to the fifth?" },
  "How many 3s does the small number say to multiply?": { style: 'A', say: "How many threes does the small number say to multiply?" },
  "How many 2s does the small number say to multiply?": { style: 'A', say: "How many twos does the small number say to multiply?" },
  "Write five 2s with × between them. Keep doubling.": { style: 'A', say: "Write five twos with times signs between them. Keep doubling." },
  "You multiplied five 2s and got 32.": { style: 'A', say: "You multiplied five twos and got 32." },
  // ── g6m5-t5 ──
  "One friend adds first: 2 + 3 is 5, 4² is 16, and 5 × 16 is 80.": { style: 'B' },
  "But is that right?": { style: 'B' },
  "We all need one order.": { style: 'B' },
  "Parentheses first, then exponents, then × and ÷, then + and −, each pair from left to right.": { style: 'B', say: "Parentheses first, then exponents, then times and divide, then plus and minus, each pair from left to right." },
  "Any parentheses? No.": { style: 'B' },
  "So 4² goes first. 4 × 4 is 16.": { style: 'B' },
  "Now it's 2 + 3 × 16.": { style: 'B' },
  "Multiply next. 3 × 16 is 48.": { style: 'B' },
  "Add last. 2 + 48 is 50.": { style: 'B' },
  "The friend with 50 is right.": { style: 'B' },
  "Now put parentheses around 2 + 3. They go first: 5.": { style: 'B' },
  "Then 4² is 16, and 5 × 16 is 80.": { style: 'B' },
  "Same numbers, new answer.": { style: 'B' },
  "Don't ADD first just because + comes first.": { style: 'B+' },
  "Multiply first: 2 + 3 × 16 is 50, not 80.": { style: 'B+' },
  "Now you try. What is 5 + 2 × 3²? Parentheses, then exponents, then × and ÷, then + and −.": { style: 'A', say: "Now you try. What is 5 plus 2 times 3 squared? Parentheses, then exponents, then times and divide, then plus and minus." },
  "Try a new one. What is (1 + 3)² − 2 × 5?": { style: 'A', say: "Try a new one. What is 1 plus 3, all in parentheses, squared, minus 2 times 5?" },
}
