/**
 * How g6m5's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 * Algebra: a number next to a letter ("3x") is said "3 x"; "3(x + 2)" is said "3 times x plus 2, all together".
 */
import type { VoiceLine } from './styles'

export const G6M5_VOICE: Record<string, VoiceLine> = {
  // ── g6m5-t6 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "One bag holds x pens and 2 erasers. That's x + 2.": { style: 'B' },
  "You don't know x, so x and 2 can't join into one number.": { style: 'B' },
  'So how do you write three bags?': { style: 'B' },
  'The number outside the parentheses multiplies every part inside, so 3(x + 2) is the same amount as 3x + 6.': { style: 'B', say: 'The number outside the parentheses multiplies every part inside, so 3 times x plus 2, all together, is the same amount as 3 x plus 6.' },
  'Put parentheses around x + 2.': { style: 'B' },
  'Now x and 2 stay together, one whole bag.': { style: 'B' },
  "Three bags? Write a 3 in front. That's 3(x + 2).": { style: 'B', say: "Three bags? Write a 3 in front. That's 3 times x plus 2, all together." },
  'Now open the bags and count.': { style: 'B' },
  "Every bag has an x, so that's 3 x's, which we write 3x.": { style: 'B', say: "Every bag has an x, so that's 3 x's, which we write 3 x." },
  'Every bag has 2 erasers, so 3 × 2 = 6 erasers.': { style: 'B' },
  'So 3(x + 2) = 3x + 6.': { style: 'B', say: 'So 3 times x plus 2, all together, equals 3 x plus 6.' },
  'Does it really match? Try x = 4.': { style: 'B' },
  'One bag is 4 + 2 = 6, and 3 bags is 3 × 6 = 18.': { style: 'B' },
  'The other way, 3x is 3 × 4 = 12, and 12 + 6 = 18.': { style: 'B', say: 'The other way, 3 x is 3 times 4 equals 12, and 12 plus 6 equals 18.' },
  'Same amount.': { style: 'B' },
  "Don't multiply ONLY the x.": { style: 'B+' },
  "3(x + 2) is not 3x + 2. The 3 multiplies the 2 too, so it's 3x + 6.": { style: 'B+', say: "3 times x plus 2, all together, is not 3 x plus 2. The 3 multiplies the 2 too, so it's 3 x plus 6." },
  // ── g6m5-t7 ──
  'You could guess. Try 3. 3 + 4 is 7, too light.': { style: 'B' },
  'Try 6. 6 + 4 is 10, too heavy.': { style: 'B' },
  'Is there a way with no guessing? Yes.': { style: 'B' },
  'To get x alone, take the same amount off both sides, so the scale stays level.': { style: 'B' },
  'The 4 is in the way of x. So take 4 off the left.': { style: 'B' },
  "But if that's all you do, the scale tips.": { style: 'B' },
  'So take 4 off the right too, and it stays level.': { style: 'B' },
  'Now look at each side.': { style: 'B' },
  'On the left, 4 − 4 leaves nothing, so x is alone.': { style: 'B' },
  'On the right, 9 − 4 = 5.': { style: 'B' },
  'So x = 5.': { style: 'B' },
  'Does 5 really work? Put 5 back where x was.': { style: 'B' },
  '5 + 4 = 9, and the other side is 9.': { style: 'B' },
  'Both sides match, so the bag holds 5 marbles.': { style: 'B' },
  "Don't ADD the 4 to the other side.": { style: 'B+' },
  'x + 4 = 9 does not make x = 13.': { style: 'B+' },
  'Take 4 off both sides, so x = 5.': { style: 'B+' },
  // ── g6m5-t8 ──
  'Three tickets, each x dollars, cost 24 dollars.': { style: 'B' },
  "Nothing is added to x this time, so taking something away won't help.": { style: 'B' },
  'So how do you find one x?': { style: 'B' },
  '3x is 3 equal parts, so divide both sides by 3 to find one x.': { style: 'B', say: '3 x is 3 equal parts, so divide both sides by 3 to find one x.' },
  'Draw it. Three equal parts of x make 24.': { style: 'B' },
  'Three groups of x is written 3x.': { style: 'B', say: 'Three groups of x is written 3 x.' },
  'So 3x = 24.': { style: 'B', say: 'So 3 x equals 24.' },
  'Split both sides into 3 equal parts.': { style: 'B' },
  '3x ÷ 3 is one x.': { style: 'B', say: '3 x divided by 3 is one x.' },
  '24 ÷ 3 = 8.': { style: 'B' },
  'So x = 8.': { style: 'B' },
  'Does 8 really work? Put 8 back where x was.': { style: 'B' },
  '3 × 8 = 24, and that matches.': { style: 'B' },
  'So one ticket costs 8 dollars.': { style: 'B' },
  "Don't SUBTRACT the 3.": { style: 'B+' },
  '3x = 24 does not make x = 21.': { style: 'B+', say: '3 x equals 24 does not make x equals 21.' },
  'The 3 multiplies x, so divide by 3 instead. That gives 8.': { style: 'B+' },
  // ── g6m5-t9 ──
  'Try listing them. 4, 5, 6, and 3 and a half.': { style: 'B' },
  'They never stop, even past 100.': { style: 'B' },
  'So how can you show every one at once? On a number line.': { style: 'B' },
  'x > 3 means every number bigger than 3, so draw an open dot at 3 and an arrow to the right.': { style: 'B' },
  'Start at 3. Does 3 itself work?': { style: 'B' },
  'No, 3 is not more than 3.': { style: 'B' },
  'So the dot at 3 stays open, an empty circle.': { style: 'B' },
  'Bigger numbers are to the right.': { style: 'B' },
  'So color the line from 3 all the way right.': { style: 'B' },
  'Then add an arrow, because it never stops.': { style: 'B' },
  'Now a new one. x ≤ 5 means 5 or less.': { style: 'B' },
  '5 works this time, so fill the dot in.': { style: 'B' },
  'Less means smaller, so color the line to the left.': { style: 'B' },
  "Don't FILL the dot for x > 3.": { style: 'B+', say: "Don't fill the dot for x greater than 3." },
  'The 3 does not work, so its dot stays open.': { style: 'B+' },
  // Lines outside the teach that the voice could not read as written (text unchanged; `say` spells the math).
  'Now you try. Which is the same as 4(x + 3)? Multiply the number outside by every part inside.': { style: 'A', say: 'Now you try. Which is the same as 4 times x plus 3, all together? Multiply the number outside by every part inside.' },
  'Try a new one. Which is the same as 5(x + 1)?': { style: 'A', say: 'Try a new one. Which is the same as 5 times x plus 1, all together?' },
  'You multiplied the 5 by both parts to get 5x + 5.': { style: 'A', say: 'You multiplied the 5 by both parts to get 5 x plus 5.' },
  'Now you try. Solve 4x = 28. What is x? Divide both sides by the number in front of x.': { style: 'A', say: 'Now you try. Solve 4 x equals 28. What is x? Divide both sides by the number in front of x.' },
  'Try a new one. Solve 6x = 54. What is x?': { style: 'A', say: 'Try a new one. Solve 6 x equals 54. What is x?' },
}
