/**
 * How g6m6's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G6M6_VOICE: Record<string, VoiceLine> = {
  // Each topic's "Here's the part people mix up." and "Okay. Your turn." share g5m1's rows.
  // ── g6m6-t1 ──
  "Could you count square tiles?": { style: 'B' },
  "The ends lean, so the tiles there break into bits.": { style: 'B' },
  "Is there a better way? Yes.": { style: 'B' },
  "Cut a triangle off one end, slide it to the other end, and you get a rectangle, so the area is base × height.": { style: 'B' },
  "The base is the bottom edge, 6 cm.": { style: 'B' },
  "The height is how tall it stands, straight up. That's 4 cm.": { style: 'B' },
  "Cut along the dashed line.": { style: 'B' },
  "Slide that triangle to the other end.": { style: 'B' },
  "Nothing is lost or added.": { style: 'B' },
  "Now it's a rectangle, 6 cm by 4 cm.": { style: 'B' },
  "So 6 × 4 = 24 square centimeters.": { style: 'B' },
  "Don't use the SLANTED side, 5 cm. That gives 30, too much.": { style: 'B+' },
  "Use the straight-up height: 6 × 4 = 24.": { style: 'B+' },
  // ── g6m6-t2 ──
  "What about 6 × 4?": { style: 'B' },
  "That's cloth for a whole rectangle, and the flag fills only part of it.": { style: 'B' },
  "So how much of it is flag? Exactly half. Here's why.": { style: 'B' },
  "Two copies of a triangle make a leaning four-sided shape, so one triangle is half of it: 1/2 × base × height.": { style: 'B' },
  "The base is the bottom edge, 6 inches.": { style: 'B' },
  "The height goes straight up to the top point. That's 4 inches.": { style: 'B' },
  "Turn a copy of the flag upside down.": { style: 'B' },
  "Fit it onto the slanted side.": { style: 'B' },
  "Two flags make one leaning shape, 6 inches by 4.": { style: 'B' },
  "That shape is 6 × 4 = 24 square inches.": { style: 'B' },
  "It's two flags, so take half: 24 ÷ 2 = 12 square inches.": { style: 'B' },
  "Don't STOP at 6 × 4 = 24.": { style: 'B+' },
  "That's two flags. Take half: 1/2 × 6 × 4 = 12.": { style: 'B+' },
  // ── g6m6-t3 ── ("Now put the pieces back together." shares g3m4's row)
  "Is this wall a rectangle? No.": { style: 'B' },
  "Is it a triangle? No again.": { style: 'B' },
  "So no one rule fits the whole wall.": { style: 'B' },
  "Cut the shape into pieces you know, find each piece's area, and add them.": { style: 'B' },
  "Cut straight across, right where the roof starts.": { style: 'B' },
  "Now there's a rectangle at the bottom and a triangle on top.": { style: 'B' },
  "The rectangle is 6 × 4 = 24 square meters.": { style: 'B' },
  "The triangle is half of 6 × 3. That's 9 square meters.": { style: 'B' },
  "24 + 9 = 33. So there are 33 square meters to paint.": { style: 'B' },
  "Don't draw ONE big box around the wall. 6 × 7 = 42 counts the empty corners too.": { style: 'B+' },
  "Find each piece, then add: 24 + 9 = 33.": { style: 'B+' },
  // ── g6m6-t4 ──
  "Length × width × height counts the cubes inside.": { style: 'B' },
  "But paper doesn't go inside. It wraps the outside.": { style: 'B' },
  "So what do we add up? Every flat side.": { style: 'B' },
  "Unfold the box flat, then add up the areas of all 6 of its flat sides.": { style: 'B' },
  "Cut some edges and fold the box open, flat.": { style: 'B' },
  "A bottom, a front, a top, a back, and an end on each side.": { style: 'B' },
  "That's 6 flat sides.": { style: 'B' },
  "The top and the bottom are both 4 × 3 = 12.": { style: 'B' },
  "The front and the back are both 4 × 2 = 8.": { style: 'B' },
  "The two ends are both 3 × 2 = 6.": { style: 'B' },
  "Now add all six. 12 + 12 + 8 + 8 + 6 + 6 = 52.": { style: 'B' },
  "So the paper is 52 square centimeters.": { style: 'B' },
  "Don't add only the 3 sides you SEE.": { style: 'B+' },
  "12 + 8 + 6 is just 26, half the paper.": { style: 'B+' },
  "Each has a partner at the back or underneath. Count each one twice, and you get 52.": { style: 'B+' },
  // ── g6m6-t5 ──
  "Let's try filling it with 1-foot cubes.": { style: 'B' },
  "Along the length, 2 fit, and then half a foot is left.": { style: 'B' },
  "Does a whole cube fit in that gap? No.": { style: 'B' },
  "So counting whole cubes would miss space.": { style: 'B' },
  "Multiply length × width × height, even when the edges are fractions.": { style: 'B' },
  "Mixed numbers are hard to multiply, so first I rewrite them.": { style: 'B' },
  "2 1/2 feet is 5 half feet. We write 5/2.": { style: 'B' },
  "1 1/2 feet is 3 half feet, so 3/2.": { style: 'B' },
  "Same chest, same edges, just easier to multiply.": { style: 'B' },
  "Now multiply, two edges at a time.": { style: 'B' },
  "Length times width first. 5/2 × 2 = 10/2, and that's 5.": { style: 'B' },
  "Then times the height. 5 × 3/2 = 15/2.": { style: 'B' },
  "15/2 means 15 halves. How many wholes is that?": { style: 'B' },
  "2 halves make 1 whole, so 14 halves make 7, and 1 half is left.": { style: 'B' },
  "So the chest holds 7 1/2 cubic feet.": { style: 'B' },
  "Don't DROP the halves.": { style: 'B+' },
  "2 × 2 × 1 is only 4. That leaves out a big chunk of the chest.": { style: 'B+' },
  "Keep them: 5/2 × 2 × 3/2 = 7 1/2.": { style: 'B+' },
  // ── g6m6-t6 ──
  "You could get a protractor and measure the other angle.": { style: 'B' },
  "But do you need one? No.": { style: 'B' },
  "The floor is a straight line, and that line already tells you.": { style: 'B' },
  "Angles that sit side by side on a straight line add up to 180°.": { style: 'B' },
  "Here's why. Face one way, then turn until you face the other way.": { style: 'B' },
  "That's a half turn, and a half turn is 180°.": { style: 'B' },
  "A straight line opens exactly that much.": { style: 'B' },
  "Now the board splits the line into two angles, 55° and the one we want.": { style: 'B' },
  "They fill the whole line, with no gap and no overlap.": { style: 'B' },
  "So together, the two make 180°.": { style: 'B' },
  "One part is 55°, so the other is what's left of 180.": { style: 'B' },
  "Take it away. 180 − 55 = 125.": { style: 'B' },
  "The angle on the other side of the board is 125°.": { style: 'B' },
  "Don't take it away from 90. That gives 35.": { style: 'B+' },
  "A straight line is NOT a square corner. It's two of them, 180°.": { style: 'B+' },
  // Screen 7's "Here's the part people mix up." and "Okay. Your turn." are g5m1's rows.
}
