/**
 * How g6m7's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G6M7_VOICE: Record<string, VoiceLine> = {
  // ── g6m7-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Look at these four towers.": { style: 'B' },
  "Pick the tallest, 6? Or the shortest, 2?": { style: 'B' },
  "Neither one is fair to every tower. We need one number that treats all four the same.": { style: 'B' },
  "Put it all together, then share it out equally: the total ÷ how many is the fair share.": { style: 'B' },
  "So push every tower into one pile.": { style: 'B' },
  "2 + 6 + 3 + 5 = 16 cubes in all.": { style: 'B' },
  "There are 4 towers, so share the 16 cubes into 4 equal towers.": { style: 'B' },
  "16 ÷ 4 = 4.": { style: 'B' },
  "Every tower is 4 tall.": { style: 'B' },
  "Let's check it.": { style: 'B' },
  "Take 2 cubes off the 6 and give them to the 2.": { style: 'B' },
  "Take 1 off the 5 and give it to the 3.": { style: 'B' },
  "Now every tower is 4, and no cube was added.": { style: 'B' },
  "Don't stop at the total. 16 is the whole pile, NOT one tower.": { style: 'B+' },
  "Divide it by 4 towers. 16 ÷ 4 = 4.": { style: 'B+' },
  // ── g6m7-t2 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "The middle spot of this list holds 9.": { style: 'B' },
  "But 9 is the tallest seedling. Can the tallest be the middle? No.": { style: 'B' },
  "This list is jumbled.": { style: 'B' },
  "Put the numbers in order, and the one in the very middle splits them in half.": { style: 'B' },
  "So the first job, every time, is to sort them.": { style: 'B' },
  "Smallest to biggest, that's 3, 4, 6, 7, 9.": { style: 'B' },
  "Now cross off one from each end.": { style: 'B' },
  "3 and 9 go. Then 4 and 7 go.": { style: 'B' },
  "The one left is 6, so the middle height is 6 inches.": { style: 'B' },
  "What if there's no single middle?": { style: 'B' },
  "Add a seedling that's 10 inches tall.": { style: 'B' },
  "Now two numbers share the middle, 6 and 7.": { style: 'B' },
  "Halfway between them is 6.5.": { style: 'B', say: "Halfway between them is six and a half." },
  "Don't grab the middle spot BEFORE you sort. That gives 9.": { style: 'B+' },
  "Sort first, and the middle is 6.": { style: 'B+' },
  // ── g6m7-t3 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "You could add up all the pets.": { style: 'B' },
  "Would that show which answer came up most? No.": { style: 'B' },
  "It only tells how many pets there are in all.": { style: 'B' },
  "The most common value is the one that shows up most often, so find the tallest stack and read the number under it.": { style: 'B' },
  "Here's how this picture is made.": { style: 'B' },
  "Each kid puts one ✕ above their number of pets.": { style: 'B' },
  "Watch the stacks grow.": { style: 'B' },
  "Which stack is the tallest?": { style: 'B' },
  "Count each one: 3, 5, 2, 1, 1.": { style: 'B' },
  "The tallest has 5 ✕s, more than any other.": { style: 'B' },
  "Now look under that stack.": { style: 'B' },
  "It sits above 1.": { style: 'B' },
  "So the most common number of pets is 1.": { style: 'B' },
  "The answer is NOT how tall the stack is.": { style: 'B+' },
  "It holds 5 kids, but the most common answer is 1 pet.": { style: 'B+' },
  // ── g6m7-t4 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Sam's best game was 15 points.": { style: 'B' },
  "But does one number show how far apart his games are? No.": { style: 'B' },
  "A player who scores 15 every game is very different.": { style: 'B' },
  "To see how spread out numbers are, take the biggest number minus the smallest number.": { style: 'B' },
  "Start at the two ends.": { style: 'B' },
  "His smallest score is 4. His biggest is 15.": { style: 'B' },
  "Every other game sits in between.": { style: 'B' },
  "How far is it from 4 up to 15?": { style: 'B' },
  "15 − 4 = 11.": { style: 'B' },
  "So his scores are spread over 11 points.": { style: 'B' },
  "Now Kim. She scored 9, 10, 8, 11 and 10.": { style: 'B' },
  "Her gap is 11 − 8 = 3.": { style: 'B' },
  "See how her scores huddle close together?": { style: 'B' },
  "Don't subtract the FIRST number from the LAST one. That gives 9 − 4 = 5.": { style: 'B+' },
  "Find the smallest and the biggest instead. 15 − 4 = 11.": { style: 'B+' },
  // lines outside the teach
  "Try a new one. The low temperatures one week were 41, 36, 45, 50, 38, 43 and 47 °F. What is the biggest minus the smallest?": { style: 'A', say: "Try a new one. The low temperatures one week were 41, 36, 45, 50, 38, 43 and 47 degrees Fahrenheit. What is the biggest minus the smallest?" },
  // ── g6m7-t5 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Try the mean first. Add all five ages, and you get 80.": { style: 'B' },
  "Share it by 5. 80 ÷ 5 = 16.": { style: 'B' },
  "But who at this party is 16? Nobody.": { style: 'B' },
  "One number far from the rest pulls the mean toward it, so the median fits the group better.": { style: 'B' },
  "Look at the four kids on their own. 9, 10, 10 and 11 make 40.": { style: 'B' },
  "40 ÷ 4 = 10. So their mean is 10.": { style: 'B' },
  "Now put the grown-up back in. The mean jumps to 16, pulled up by one person.": { style: 'B' },
  "Now try the median. Put the ages in order: 9, 10, 10, 11, 40.": { style: 'B' },
  "The one in the middle is 10.": { style: 'B' },
  "The 40 is still in the list, and the median is still 10.": { style: 'B' },
  "So which number fits this party? Almost everyone is about 10.": { style: 'B' },
  "The median says 10. The mean says 16, and that fits nobody.": { style: 'B' },
  "When one number sits far from the rest, pick the median.": { style: 'B' },
  "Don't reach for the mean EVERY time.": { style: 'B+' },
  "One far number pulls it away from the group. Then the median fits better.": { style: 'B+' },
  // ── g6m7-t6 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "You could read a long list of names and times, one kid at a time.": { style: 'B' },
  "That works. But it's slow, and it's easy to lose count.": { style: 'B' },
  "Is there a faster way? Yes. A picture sorts the kids for us.": { style: 'B' },
  "Each ✕ stands for one thing, and each bar counts everything in its group.": { style: 'B' },
  "Look. Every ✕ here is one kid.": { style: 'B' },
  "Above 30 I count 5. Above 40, 3. Above 50, just 1.": { style: 'B' },
  "The question says 30 minutes or more. Does 30 itself count? Yes.": { style: 'B' },
  "So add the stacks over 30, 40 and 50.": { style: 'B' },
  "5 + 3 + 1 = 9. So 9 kids practiced that long.": { style: 'B' },
  "Sometimes every time is different, so every stack is just 1 tall.": { style: 'B' },
  "So we put the times in groups, and draw one bar for each group.": { style: 'B' },
  "This bar is over 20–29. It reaches 8, so 8 kids practiced 20 to 29 minutes.": { style: 'B', say: "This bar is over 20 to 29. It reaches 8, so 8 kids practiced 20 to 29 minutes." },
  "Don't count the NUMBERS along the bottom.": { style: 'B+' },
  "30, 40 and 50 give you 3. Count the ✕s instead, and you get 9.": { style: 'B+', say: "30, 40 and 50 give you 3. Count the X's instead, and you get 9." },
  // ── g6m7-t7 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Only two things can happen. You win, or you lose.": { style: 'B' },
  "So is your chance 1/2? No.": { style: 'B' },
  "Look at the spinner. Red covers only some of the parts.": { style: 'B' },
  "The chance of something is the number of ways it can happen over the number of all the ways.": { style: 'B' },
  "First, count the ways to win. Count the red parts with me.": { style: 'B' },
  "1, 2, 3. So there are 3 ways to win.": { style: 'B' },
  "Next, count every part. The arrow could stop on any one of them.": { style: 'B' },
  "3 red, 3 blue, 1 green and 1 yellow. That's 8 parts in all.": { style: 'B' },
  "Now make a fraction. The ways to win go on top.": { style: 'B' },
  "All the ways go on the bottom.": { style: 'B' },
  "So the chance of red is 3/8.": { style: 'B' },
  "Don't put red over the parts that are NOT red.": { style: 'B+' },
  "That gives 3/5. Red goes over every part, all 8, so it's 3/8.": { style: 'B+' },
  // ── g6m7-t8 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "You might say maybe. A friend might say probably.": { style: 'B' },
  "Which one is right? Words mean different things to different people.": { style: 'B' },
  "So we put every chance on one line, from 0 to 1.": { style: 'B' },
  "Every chance is a number from 0 to 1, where 0 is impossible, 1 is certain and 1/2 is right in the middle.": { style: 'B' },
  "Start with the two ends. Can you pull out a green marble? No.": { style: 'B' },
  "That's 0 ways out of 4. Its chance is 0.": { style: 'B' },
  "Any marble at all is 4 ways out of 4. Its chance is 1.": { style: 'B' },
  "Now the middle. Flip a coin. Heads is 1 way out of 2, so 1/2.": { style: 'B' },
  "Heads and tails have the same chance, so 1/2 sits exactly halfway.": { style: 'B' },
  "Back to the bag. Red is 3 ways out of 4, so 3/4.": { style: 'B' },
  "Is 3/4 past the middle? Yes, so red is likely.": { style: 'B' },
  "Blue is 1 way out of 4, so 1/4. That's below the middle, so blue is unlikely.": { style: 'B' },
  "Don't call blue likely just because it CAN happen.": { style: 'B+' },
  "1/4 is below 1/2, so blue is unlikely.": { style: 'B+', say: "One fourth is below one half, so blue is unlikely." },
}
