/**
 * How g6m7's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G6M7_VOICE: Record<string, VoiceLine> = {
  // ── g6m7-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Look at these four towers.": { style: 'B' },
  "Pick the tallest, 6? Or the shortest, 2?": { style: 'B' },
  "Neither one is fair to every tower. We need one number that treats all four the same.": { style: 'B' },
  "Put it all together, then share it out equally: the total ÷ how many is the fair share.": { style: 'B' },
  "So push every tower into one pile.": { style: 'B' },
  "2 + 6 + 3 + 5 = 16 cubes in all.": { style: 'B' },
  "There are 4 towers, so share the 16 cubes into 4 equal towers.": { style: 'B' },
  "16 ÷ 4 = 4.": { style: 'B' },
  "Every tower is 4 tall.": { style: 'B' },
  "Let's check it.": { style: 'B' },
  "Take 2 cubes off the 6 and give them to the 2.": { style: 'B' },
  "Take 1 off the 5 and give it to the 3.": { style: 'B' },
  "Now every tower is 4, and no cube was added.": { style: 'B' },
  "Don't stop at the total. 16 is the whole pile, NOT one tower.": { style: 'B+' },
  "Divide it by 4 towers. 16 ÷ 4 = 4.": { style: 'B+' },
  // ── g6m7-t2 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "The middle spot of this list holds 9.": { style: 'B' },
  "But 9 is the tallest seedling. Can the tallest be the middle? No.": { style: 'B' },
  "This list is jumbled.": { style: 'B' },
  "Put the numbers in order, and the one in the very middle splits them in half.": { style: 'B' },
  "So the first job, every time, is to sort them.": { style: 'B' },
  "Smallest to biggest, that's 3, 4, 6, 7, 9.": { style: 'B' },
  "Now cross off one from each end.": { style: 'B' },
  "3 and 9 go. Then 4 and 7 go.": { style: 'B' },
  "The one left is 6, so the middle height is 6 inches.": { style: 'B' },
  "What if there's no single middle?": { style: 'B' },
  "Add a seedling that's 10 inches tall.": { style: 'B' },
  "Now two numbers share the middle, 6 and 7.": { style: 'B' },
  "Halfway between them is 6.5.": { style: 'B', say: "Halfway between them is six and a half." },
  "Don't grab the middle spot BEFORE you sort. That gives 9.": { style: 'B+' },
  "Sort first, and the middle is 6.": { style: 'B+' },
  // ── g6m7-t3 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "You could add up all the pets.": { style: 'B' },
  "Would that show which answer came up most? No.": { style: 'B' },
  "It only tells how many pets there are in all.": { style: 'B' },
  "The most common value is the one that shows up most often, so find the tallest stack and read the number under it.": { style: 'B' },
  "Here's how this picture is made.": { style: 'B' },
  "Each kid puts one ✕ above their number of pets.": { style: 'B' },
  "Watch the stacks grow.": { style: 'B' },
  "Which stack is the tallest?": { style: 'B' },
  "Count each one: 3, 5, 2, 1, 1.": { style: 'B' },
  "The tallest has 5 ✕s, more than any other.": { style: 'B' },
  "Now look under that stack.": { style: 'B' },
  "It sits above 1.": { style: 'B' },
  "So the most common number of pets is 1.": { style: 'B' },
  "The answer is NOT how tall the stack is.": { style: 'B+' },
  "It holds 5 kids, but the most common answer is 1 pet.": { style: 'B+' },
  // ── g6m7-t4 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Sam's best game was 15 points.": { style: 'B' },
  "But does one number show how far apart his games are? No.": { style: 'B' },
  "A player who scores 15 every game is very different.": { style: 'B' },
  "To see how spread out numbers are, take the biggest number minus the smallest number.": { style: 'B' },
  "Start at the two ends.": { style: 'B' },
  "His smallest score is 4. His biggest is 15.": { style: 'B' },
  "Every other game sits in between.": { style: 'B' },
  "How far is it from 4 up to 15?": { style: 'B' },
  "15 − 4 = 11.": { style: 'B' },
  "So his scores are spread over 11 points.": { style: 'B' },
  "Now Kim. She scored 9, 10, 8, 11 and 10.": { style: 'B' },
  "Her gap is 11 − 8 = 3.": { style: 'B' },
  "See how her scores huddle close together?": { style: 'B' },
  "Don't subtract the FIRST number from the LAST one. That gives 9 − 4 = 5.": { style: 'B+' },
  "Find the smallest and the biggest instead. 15 − 4 = 11.": { style: 'B+' },
  // lines outside the teach
  "Try a new one. The low temperatures one week were 41, 36, 45, 50, 38, 43 and 47 °F. What is the biggest minus the smallest?": { style: 'A', say: "Try a new one. The low temperatures one week were 41, 36, 45, 50, 38, 43 and 47 degrees Fahrenheit. What is the biggest minus the smallest?" },
}
