/**
 * How g7m1's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G7M1_VOICE: Record<string, VoiceLine> = {
  // ── g7m1-t5 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Your first thought might be to add.": { style: 'B' },
  "6 inches is 4 more than 2, so add 4 miles to the 15?": { style: 'B' },
  "No. 2 inches is already 15 miles, so 6 inches can't be only 19.": { style: 'B' },
  "The map would stop matching the real world.": { style: 'B' },
  "Two equal ratios grow the same way, so find what one number was multiplied by and do the same to the other.": { style: 'B' },
  "Look along the inches row.": { style: 'B' },
  "2 inches turned into 6 inches.": { style: 'B' },
  "So, 2 times what makes 6? 2 × 3 = 6.": { style: 'B' },
  "The map distance was multiplied by 3.": { style: 'B' },
  "Now do the exact same thing to the miles.": { style: 'B' },
  "15 × 3 = 45.": { style: 'B' },
  "So the towns are really 45 miles apart.": { style: 'B' },
  "Want to be sure?": { style: 'B' },
  "Write both ratios as fractions: 2/15 and 6/45.": { style: 'B', say: "Write both ratios as fractions, two fifteenths and six forty-fifths." },
  "Now multiply across the middle.": { style: 'B' },
  "2 × 45 = 90.": { style: 'B' },
  "And 15 × 6 = 90.": { style: 'B' },
  "Both make 90, so the two ratios are equal.": { style: 'B' },
  "Don't ADD the 4 extra inches to the miles. 15 + 4 = 19 miles is far too short.": { style: 'B+' },
  "The inches were multiplied by 3, so multiply the miles by 3. That makes 45 miles.": { style: 'B+' },
  // ── g7m1-t6 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "The price went up $5.": { style: 'B' },
  "But a percent compares one amount to another.": { style: 'B' },
  "So, $5 out of what? The old $20, or the new $25?": { style: 'B' },
  "Those give different answers.": { style: 'B' },
  "Find the change, then compare it to the original amount: change ÷ original × 100.": { style: 'B' },
  "Start with the change.": { style: 'B' },
  "New price minus old price. $25 − $20 = $5.": { style: 'B' },
  "That $5 is the piece that got added on.": { style: 'B' },
  "Now hold that $5 against last year's $20.": { style: 'B' },
  "How many $5 pieces fit in $20? Four.": { style: 'B' },
  "So the change is one piece out of four: 5 ÷ 20 = 0.25.": { style: 'B', say: "So the change is one piece out of four. 5 divided by 20 equals zero point two five." },
  "One last move.": { style: 'B' },
  "Multiply by 100 to turn it into a percent.": { style: 'B' },
  "0.25 × 100 = 25, so the ticket went up 25%.": { style: 'B', say: "Zero point two five times 100 equals 25, so the ticket went up 25 percent." },
  "Don't divide by the NEW price. 5 ÷ 25 × 100 gives 20%, and that's too small.": { style: 'B+' },
  "Divide by the price you started with. 5 ÷ 20 × 100 gives 25%.": { style: 'B+' },
  // ── g7m1-t7 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Careful with that 40.": { style: 'B' },
  "Does it mean $40 more? No. The tag is not $20 plus $40.": { style: 'B' },
  "A percent is a share out of 100.": { style: 'B' },
  "So 40% means $40 for every $100 the shop paid.": { style: 'B' },
  "Find that percent of the price, then add it on.": { style: 'B' },
  "So find the extra first.": { style: 'B' },
  "10% of $20 is $2.": { style: 'B' },
  "40% is four of those 10% pieces. 4 × $2 = $8.": { style: 'B' },
  "Now add the extra to what the shop paid.": { style: 'B' },
  "$20 + $8 = $28.": { style: 'B' },
  "That is the number on the tag.": { style: 'B' },
  "The tag is all of the $20, which is 100%, plus 40% more.": { style: 'B' },
  "Together that is 140% of $20.": { style: 'B' },
  "And 140% is 1.4, so 1.4 × $20 = $28.": { style: 'B', say: "And 140 percent is one point four, so one point four times 20 dollars equals 28 dollars." },
  "Don't STOP at the $8. That is only the extra.": { style: 'B+' },
  "The tag is the $20 and the $8 together: $28.": { style: 'B+' },
  // ── g7m1-t8 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Your guess is 5 beans off.": { style: 'B' },
  "Is 5 off good?": { style: 'B' },
  "In a jar of 50, that's close. In a jar of 10, it's way off.": { style: 'B' },
  "So the gap alone can't tell you how good the guess was.": { style: 'B' },
  "Find how far the guess is from the real amount, then divide by the real amount and multiply by 100.": { style: 'B' },
  "Start with the gap.": { style: 'B' },
  "50 − 45 = 5, so the guess was 5 beans away.": { style: 'B' },
  "What if you had guessed too high, like 55? The gap is still 5.": { style: 'B' },
  "Only how far matters, not which side.": { style: 'B' },
  "Now hold that gap against the real count.": { style: 'B' },
  "Cut the 50 into pieces of 5. Ten of them.": { style: 'B' },
  "The gap is one piece out of ten: 5 ÷ 50 = 0.1.": { style: 'B', say: "The gap is one piece out of ten. 5 divided by 50 equals zero point one." },
  "Last step, same as before.": { style: 'B' },
  "Times 100 turns it into a percent.": { style: 'B' },
  "0.1 × 100 = 10, so your guess was 10% off.": { style: 'B', say: "Zero point one times 100 equals 10, so your guess was 10 percent off." },
  "Don't divide by your GUESS. It's the thing being checked, so it can't be the measuring stick.": { style: 'B+' },
  "Divide by the real count: 5 ÷ 50 × 100 = 10%.": { style: 'B+' },
}
