/**
 * How g7m1's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G7M1_VOICE: Record<string, VoiceLine> = {
  // ── g7m1-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Look at Job A. More hours, more pay.": { style: 'B' },
  "Job B goes up too. So which one pays the same for every hour?": { style: 'B' },
  "Going up can't tell us. We need a sharper test.": { style: 'B' },
  "Divide each pay by its hours, and if every answer is the same, the job pays one steady rate.": { style: 'B' },
  "Take Job A. Divide each pay by its hours.": { style: 'B' },
  "12 ÷ 1 = 12. 24 ÷ 2 = 12. 36 ÷ 3 = 12.": { style: 'B' },
  "Every answer is 12. Job A pays $12 for every hour.": { style: 'B' },
  "Now the same test on Job B.": { style: 'B' },
  "15 ÷ 1 = 15. But 25 ÷ 2 = 12.5.": { style: 'B', say: "15 divided by 1 equals 15. But 25 divided by 2 equals twelve and a half." },
  "Already different. So Job B does not pay the same for every hour.": { style: 'B' },
  "Why is Job B different? It pays an extra $5 at the start, then $10 an hour.": { style: 'B' },
  "That $5 is shared by more hours as you go, so each hour's pay keeps changing.": { style: 'B' },
  "Job A has no extra. It stays at $12 an hour.": { style: 'B' },
  "Job B goes up $10 every hour. That does NOT make it steady.": { style: 'B+' },
  "Going up by the same amount is not the test. Divide pay by hours, and every answer must match.": { style: 'B+' },
  // ── g7m1-t2 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "The table stops at 6 minutes.": { style: 'B' },
  "What about 20 minutes? Or 100? You don't want to keep making the table longer.": { style: 'B' },
  "You want one rule that works for any number of minutes.": { style: 'B' },
  "Find the one number that y ÷ x always makes, then multiply any x by it to get y.": { style: 'B' },
  "Take each number of gallons and divide it by its minutes.": { style: 'B' },
  "5 ÷ 2 = 2.5. 10 ÷ 4 = 2.5. 15 ÷ 6 = 2.5.": { style: 'B', say: "5 divided by 2 equals two and a half. 10 divided by 4 equals two and a half. 15 divided by 6 equals two and a half." },
  "The same every time. The hose adds 2.5 gallons each minute.": { style: 'B', say: "The same every time. The hose adds two and a half gallons each minute." },
  "Does it work backwards? Multiply the minutes by 2.5.": { style: 'B', say: "Does it work backwards? Multiply the minutes by two and a half." },
  "2 × 2.5 = 5. 4 × 2.5 = 10. 6 × 2.5 = 15.": { style: 'B', say: "2 times two and a half equals 5. 4 times two and a half equals 10. 6 times two and a half equals 15." },
  "Every number of gallons comes back. So it works.": { style: 'B' },
  "So the gallons are 2.5 times the minutes. We write y = 2.5x.": { style: 'B', say: "So the gallons are two and a half times the minutes. We write y equals two point five x." },
  "Now 20 minutes is quick. 2.5 × 20 = 50 gallons.": { style: 'B', say: "Now 20 minutes is quick. Two and a half times 20 equals 50 gallons." },
  "No longer table needed.": { style: 'B' },
  "Don't flip it. 2 ÷ 5 = 0.4 gives MINUTES for each gallon.": { style: 'B+', say: "Don't flip it. 2 divided by 5 equals four tenths, and that gives minutes for each gallon." },
  "You want gallons for each minute, so y goes on top: 5 ÷ 2.": { style: 'B+' },
  // ── g7m1-t3 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Look at the dots. They climb up to the right.": { style: 'B' },
  "But dots can climb without growing at one steady rate.": { style: 'B' },
  "So what should you look for on a graph?": { style: 'B' },
  "A steady-rate graph is a straight line through (0, 0), and its height at x = 1 is the rate.": { style: 'B', say: "A steady-rate graph is a straight line through the point zero, zero, and its height at x equals 1 is the rate." },
  "Lay a ruler along the dots.": { style: 'B' },
  "Do they all sit on one straight line? Yes. No bend, no curve.": { style: 'B' },
  "Now go back to week 0.": { style: 'B' },
  "Jo had saved nothing yet. 0 weeks, $0.": { style: 'B' },
  "So the line starts right at the corner, at (0, 0).": { style: 'B', say: "So the line starts right at the corner, at the point zero, zero." },
  "Here's the useful part. Find 1 week on the bottom, and go straight up to the line.": { style: 'B' },
  "The line is at 2. That's $2 a week.": { style: 'B' },
  "So the rule is y = 2x.": { style: 'B', say: "So the rule is y equals 2 x." },
  "A straight line is NOT enough. A line that starts at (0, 3) had $3 saved before week one.": { style: 'B+', say: "A straight line is not enough. A line that starts at the point zero, three had 3 dollars saved before week one." },
  "That head start keeps y ÷ x changing. The line has to start at (0, 0).": { style: 'B+', say: "That head start keeps y divided by x changing. The line has to start at the point zero, zero." },
  // ── g7m1-t4 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Normally you divide the miles by the hours.": { style: 'B' },
  "That's 1/2 ÷ 1/4. Strange, isn't it?": { style: 'B' },
  "Will the answer be more than 1/2, or less?": { style: 'B' },
  "Divide the distance by the time, and it tells you how far you go in one whole hour, even when both are fractions.": { style: 'B' },
  "Draw one hour as a bar. Cut it into quarters. That's 4 pieces.": { style: 'B' },
  "Your walk fills one piece, 1/4 of an hour, and covers 1/2 mile.": { style: 'B' },
  "So will a whole hour go farther? Yes. It's 4 pieces long.": { style: 'B' },
  "Keep the same pace. Each quarter adds 1/2 mile.": { style: 'B' },
  "1/2 + 1/2 + 1/2 + 1/2 = 2.": { style: 'B' },
  "So you walk 2 miles in one hour.": { style: 'B' },
  "Now check it with division. Dividing by 1/4 is the same as multiplying by 4.": { style: 'B' },
  "So 1/2 ÷ 1/4 = 1/2 × 4 = 2.": { style: 'B' },
  "2 miles per hour. It matches the bar.": { style: 'B' },
  "Don't put the TIME on top. 1/4 ÷ 1/2 = 1/2 is hours for each mile.": { style: 'B+' },
  "You want miles for each hour, so the miles go on top: 1/2 ÷ 1/4 = 2.": { style: 'B+' },
  // Lines outside the teach (Screen 8's question, Screen 9) that speakable() cannot say on its own
  "You divided 18 by 4 and found the rule y = 4.5x.": { style: 'A', say: "You divided 18 by 4 and found the rule y equals four point five x." },
  "Now you try. This graph is proportional. It goes through (0, 0) and (2, 6). What is y when x = 1? Find x = 1 on the bottom. Go up to the line and read y.": { style: 'A', say: "Now you try. This graph is proportional. It goes through the points zero, zero and two, six. What is y when x equals 1? Find x equals 1 on the bottom. Go up to the line and read y." },
  "Try a new one. This graph is proportional. It goes through (0, 0) and (4, 10). What is y when x = 1?": { style: 'A', say: "Try a new one. This graph is proportional. It goes through the points zero, zero and four, ten. What is y when x equals 1?" },
  "You read y at x = 1 on a line through (0, 0).": { style: 'A', say: "You read y at x equals 1 on a line through the point zero, zero." },
  "You shared 10 among 4 and read y = 2.5 at x = 1.": { style: 'A', say: "You shared 10 among 4 and read y equals two and a half at x equals 1." },
  // ── g7m1-t5 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Your first thought might be to add.": { style: 'B' },
  "6 inches is 4 more than 2, so add 4 miles to the 15?": { style: 'B' },
  "No. 2 inches is already 15 miles, so 6 inches can't be only 19.": { style: 'B' },
  "The map would stop matching the real world.": { style: 'B' },
  "Two equal ratios grow the same way, so find what one number was multiplied by and do the same to the other.": { style: 'B' },
  "Look along the inches row.": { style: 'B' },
  "2 inches turned into 6 inches.": { style: 'B' },
  "So, 2 times what makes 6? 2 × 3 = 6.": { style: 'B' },
  "The map distance was multiplied by 3.": { style: 'B' },
  "Now do the exact same thing to the miles.": { style: 'B' },
  "15 × 3 = 45.": { style: 'B' },
  "So the towns are really 45 miles apart.": { style: 'B' },
  "Want to be sure?": { style: 'B' },
  "Write both ratios as fractions: 2/15 and 6/45.": { style: 'B', say: "Write both ratios as fractions, two fifteenths and six forty-fifths." },
  "Now multiply across the middle.": { style: 'B' },
  "2 × 45 = 90.": { style: 'B' },
  "And 15 × 6 = 90.": { style: 'B' },
  "Both make 90, so the two ratios are equal.": { style: 'B' },
  "Don't ADD the 4 extra inches to the miles. 15 + 4 = 19 miles is far too short.": { style: 'B+' },
  "The inches were multiplied by 3, so multiply the miles by 3. That makes 45 miles.": { style: 'B+' },
  // ── g7m1-t6 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "The price went up $5.": { style: 'B' },
  "But a percent compares one amount to another.": { style: 'B' },
  "So, $5 out of what? The old $20, or the new $25?": { style: 'B' },
  "Those give different answers.": { style: 'B' },
  "Find the change, then compare it to the original amount: change ÷ original × 100.": { style: 'B' },
  "Start with the change.": { style: 'B' },
  "New price minus old price. $25 − $20 = $5.": { style: 'B' },
  "That $5 is the piece that got added on.": { style: 'B' },
  "Now hold that $5 against last year's $20.": { style: 'B' },
  "How many $5 pieces fit in $20? Four.": { style: 'B' },
  "So the change is one piece out of four: 5 ÷ 20 = 0.25.": { style: 'B', say: "So the change is one piece out of four. 5 divided by 20 equals zero point two five." },
  "One last move.": { style: 'B' },
  "Multiply by 100 to turn it into a percent.": { style: 'B' },
  "0.25 × 100 = 25, so the ticket went up 25%.": { style: 'B', say: "Zero point two five times 100 equals 25, so the ticket went up 25 percent." },
  "Don't divide by the NEW price. 5 ÷ 25 × 100 gives 20%, and that's too small.": { style: 'B+' },
  "Divide by the price you started with. 5 ÷ 20 × 100 gives 25%.": { style: 'B+' },
  // ── g7m1-t7 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Careful with that 40.": { style: 'B' },
  "Does it mean $40 more? No. The tag is not $20 plus $40.": { style: 'B' },
  "A percent is a share out of 100.": { style: 'B' },
  "So 40% means $40 for every $100 the shop paid.": { style: 'B' },
  "Find that percent of the price, then add it on.": { style: 'B' },
  "So find the extra first.": { style: 'B' },
  "10% of $20 is $2.": { style: 'B' },
  "40% is four of those 10% pieces. 4 × $2 = $8.": { style: 'B' },
  "Now add the extra to what the shop paid.": { style: 'B' },
  "$20 + $8 = $28.": { style: 'B' },
  "That is the number on the tag.": { style: 'B' },
  "The tag is all of the $20, which is 100%, plus 40% more.": { style: 'B' },
  "Together that is 140% of $20.": { style: 'B' },
  "And 140% is 1.4, so 1.4 × $20 = $28.": { style: 'B', say: "And 140 percent is one point four, so one point four times 20 dollars equals 28 dollars." },
  "Don't STOP at the $8. That is only the extra.": { style: 'B+' },
  "The tag is the $20 and the $8 together: $28.": { style: 'B+' },
  // ── g7m1-t8 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Your guess is 5 beans off.": { style: 'B' },
  "Is 5 off good?": { style: 'B' },
  "In a jar of 50, that's close. In a jar of 10, it's way off.": { style: 'B' },
  "So the gap alone can't tell you how good the guess was.": { style: 'B' },
  "Find how far the guess is from the real amount, then divide by the real amount and multiply by 100.": { style: 'B' },
  "Start with the gap.": { style: 'B' },
  "50 − 45 = 5, so the guess was 5 beans away.": { style: 'B' },
  "What if you had guessed too high, like 55? The gap is still 5.": { style: 'B' },
  "Only how far matters, not which side.": { style: 'B' },
  "Now hold that gap against the real count.": { style: 'B' },
  "Cut the 50 into pieces of 5. Ten of them.": { style: 'B' },
  "The gap is one piece out of ten: 5 ÷ 50 = 0.1.": { style: 'B', say: "The gap is one piece out of ten. 5 divided by 50 equals zero point one." },
  "Last step, same as before.": { style: 'B' },
  "Times 100 turns it into a percent.": { style: 'B' },
  "0.1 × 100 = 10, so your guess was 10% off.": { style: 'B', say: "Zero point one times 100 equals 10, so your guess was 10 percent off." },
  "Don't divide by your GUESS. It's the thing being checked, so it can't be the measuring stick.": { style: 'B+' },
  "Divide by the real count: 5 ÷ 50 × 100 = 10%.": { style: 'B+' },
}
