/**
 * How g7m2's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G7M2_VOICE: Record<string, VoiceLine> = {
  // ── g7m2-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Both of them are 4 feet from the water.": { style: 'B' },
  "So do we just write 4 for the bird, and 4 for the fish?": { style: 'B' },
  "Then which one is up in the air, and which one is under the water? You can't tell.": { style: 'B' },
  "A number and its opposite are the same distance from 0, on different sides of it.": { style: 'B' },
  "The water is 0 on this number line.": { style: 'B' },
  "Count with me from 0 out to the bird. 1, 2, 3, 4.": { style: 'B' },
  "That's 4 steps to the right, so the bird is at 4.": { style: 'B' },
  "Now the fish. Which way does it go?": { style: 'B' },
  "It's 4 steps from 0 too, but the other way, to the left.": { style: 'B' },
  "Left of 0 gets a minus sign, so the fish is at −4.": { style: 'B' },
  "So 4 and −4 are opposites.": { style: 'B' },
  "Try 7. Go 7 steps the other way, and you land on −7.": { style: 'B' },
  "And the opposite of −7? Change the sign again, and it's 7.": { style: 'B' },
  "To find the opposite of −5, don't KEEP the minus sign.": { style: 'B+' },
  "−5 is left of 0, so its opposite is right of 0, at 5.": { style: 'B+' },
  // ── g7m2-t2 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Ben ended up at −5.": { style: 'B' },
  "So did he walk −5 blocks? No. Nobody walks a negative number of blocks.": { style: 'B' },
  "The minus sign tells you which way he went, not how far.": { style: 'B' },
  "How far a number is from 0 is never negative, so count the steps to 0 and drop the sign.": { style: 'B' },
  "Put your finger on −5 and walk it to 0.": { style: 'B' },
  "1, 2, 3, 4, 5.": { style: 'B' },
  "So −5 is 5 steps from 0. Ben walked 5 blocks.": { style: 'B' },
  "Now Ana. How far is 5 from 0?": { style: 'B' },
  "Count back to 0. That's 5 steps too.": { style: 'B' },
  "So they both walked the same distance, 5 blocks each.": { style: 'B' },
  "Math has a short way to ask how far from 0.": { style: 'B' },
  "Two bars around a number ask that question.": { style: 'B' },
  "So the bars turn −5 into 5, and 5 stays 5.": { style: 'B' },
  "Bars around −4 do NOT give −4.": { style: 'B+' },
  "A distance is never negative, so it's 4.": { style: 'B+' },
  // ── g7m2-t3 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "We write it as 3 + (−5).": { style: 'B', say: "We write it as 3 plus negative 5." },
  "Is it 3 + 5, which is 8?": { style: 'B' },
  "No. You lost 5 points, so your score can't go up.": { style: 'B' },
  "A plus and a minus cancel to 0, so pair them up, take the pairs away, and count what is left.": { style: 'B' },
  "Put out 3 plus counters for the win, and 5 minus counters for the loss.": { style: 'B' },
  "Win a point, lose a point, and you're back to 0.": { style: 'B' },
  "How many pairs can we make? 3.": { style: 'B' },
  "Each pair is worth 0, so taking it away changes nothing.": { style: 'B' },
  "What's left behind? 2 minus counters.": { style: 'B' },
  "2 minus counters means −2.": { style: 'B' },
  "So 3 + (−5) = −2.": { style: 'B', say: "So 3 plus negative 5 equals negative 2." },
  "Your score went down by 2, just like the story said.": { style: 'B' },
  "Don't just ADD the 5 on and get 8.": { style: 'B+' },
  "A minus counter cancels a plus counter. It doesn't join it.": { style: 'B+' },
  // ── g7m2-t4 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "We write it as −3 − 5.": { style: 'B' },
  "Look at the two minus signs. Do they mean the same thing?": { style: 'B' },
  "No. The first is part of the number. The second means take away.": { style: 'B' },
  "So let's turn the taking away into adding.": { style: 'B' },
  "Taking away a number is the same as adding its opposite.": { style: 'B' },
  "First, change the take-away sign to a plus.": { style: 'B' },
  "Then change 5 to its opposite, −5.": { style: 'B' },
  "Nothing else changes. The −3 stays just as it is.": { style: 'B' },
  "Now it's adding, and we know how to add.": { style: 'B' },
  "Start at −3 on the number line.": { style: 'B' },
  "Which way does adding −5 go? Left, 5 steps.": { style: 'B' },
  "Count them off, and you land on −8.": { style: 'B' },
  "So −3 − 5 = −8.": { style: 'B' },
  "The elevator is on floor −8, way below the ground floor.": { style: 'B' },
  "Don't just TAKE the small number from the big one.": { style: 'B+' },
  "Change it to adding the opposite first, then move along the line.": { style: 'B+' },
  // ── outside the teach (Screen 8, hints, won lines): the bars and parentheses said in words ──
  "Now you try. What is |−8|? Count the steps from the number to 0. Drop the sign.": { style: 'A', say: "Now you try. How far is negative 8 from 0? Count the steps from the number to 0. Drop the sign." },
  "Try a new one. What is |−3|?": { style: 'A', say: "Try a new one. How far is negative 3 from 0?" },
  "Now you try. Add. 4 + (−7) = ? Pair each plus with a minus. Take the pairs away. Count what is left.": { style: 'A', say: "Now you try. Add. 4 plus negative 7 equals what? Pair each plus with a minus. Take the pairs away. Count what is left." },
  "Try a new one. Take away. 4 − (−3) = ?": { style: 'A', say: "Try a new one. Take away. 4 minus negative 3 equals what?" },
  "Write −1 + (−6). Start at −1. Which way does adding a negative move you?": { style: 'A', say: "Write negative 1 plus negative 6. Start at negative 1. Which way does adding a negative move you?" },
  "You added the opposite and found 4 − (−3) = 7.": { style: 'A', say: "You added the opposite and found 4 minus negative 3 equals 7." },
}
