/**
 * How g7m3's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G7M3_VOICE: Record<string, VoiceLine> = {
  // ── g7m3-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  'Look at that line.': { style: 'B' },
  'Boxes and loose pens, all jumbled together.': { style: 'B' },
  'Can you add 3x and 5 to get one number? No.': { style: 'B', say: 'Can you add 3 x and 5 to get one number? No.' },
  "You don't know how many pens are in a box yet.": { style: 'B' },
  'Put the x parts together and the plain numbers together, but never join an x part to a plain number.': { style: 'B' },
  'Slide all the boxes next to each other.': { style: 'B' },
  "3 boxes, and 2 more boxes. That's 5 boxes.": { style: 'B' },
  'So 3x + 2x = 5x.': { style: 'B', say: 'So 3 x plus 2 x equals 5 x.' },
  'Now the loose pens.': { style: 'B' },
  'You had 5, and you gave 1 away.': { style: 'B' },
  '5 − 1 = 4 loose pens left.': { style: 'B' },
  'So that whole long line is just 5x + 4.': { style: 'B', say: 'So that whole long line is just 5 x plus 4.' },
  "Does it really match? Let's check with x = 2.": { style: 'B' },
  'The long way gives 6 + 5 + 4 − 1 = 14.': { style: 'B' },
  'The short way gives 10 + 4 = 14. They match.': { style: 'B' },
  "Don't JOIN an x part and a plain number.": { style: 'B+' },
  '3x + 5 is not 8x. It stays 3x + 5.': { style: 'B+', say: '3 x plus 5 is not 8 x. It stays 3 x plus 5.' },
  // ── g7m3-t2 ──
  'Normally you work out the parentheses first.': { style: 'B' },
  "But can x − 4 become one number? No. You don't know x yet.": { style: 'B' },
  'So we need another way to open them.': { style: 'B' },
  'The number outside multiplies every part inside, and its sign comes along.': { style: 'B' },
  'The 3 has to reach both parts inside.': { style: 'B' },
  '3 × x = 3x.': { style: 'B', say: '3 times x equals 3 x.' },
  'And 3 × (−4) = −12, because each of the 3 tickets gets 4 dollars off.': { style: 'B', say: 'And 3 times negative 4 equals negative 12, because each of the 3 tickets gets 4 dollars off.' },
  'So 3(x − 4) = 3x − 12.': { style: 'B', say: 'So 3 times x minus 4, all together, equals 3 x minus 12.' },
  'Now watch what a negative outside does.': { style: 'B' },
  'Try −2(x − 4).': { style: 'B', say: 'Try negative 2 times x minus 4, all together.' },
  'The −2 reaches the x first. −2 × x = −2x.': { style: 'B', say: 'The negative 2 reaches the x first. Negative 2 times x equals negative 2 x.' },
  'Next, the −2 reaches the −4.': { style: 'B' },
  'A negative times a negative is positive, so −2 × (−4) = 8.': { style: 'B', say: 'A negative times a negative is positive, so negative 2 times negative 4 equals 8.' },
  'So −2(x − 4) = −2x + 8.': { style: 'B', say: 'So negative 2 times x minus 4, all together, equals negative 2 x plus 8.' },
  "Don't DROP the sign on the second part.": { style: 'B+' },
  "−2 × (−4) is 8, not −8. So it's −2x + 8.": { style: 'B+', say: "Negative 2 times negative 4 is 8, not negative 8. So it's negative 2 x plus 8." },
  // outside the teach (Screen 1, Screen 8, hints): only the lines speakable() cannot say
  'Tickets with a coupon. A ticket costs x dollars, and a coupon takes 4 dollars off each one. You buy 3 tickets, so you pay 3(x − 4). How can you write that without the parentheses?': { style: 'A', say: 'Tickets with a coupon. A ticket costs x dollars, and a coupon takes 4 dollars off each one. You buy 3 tickets, so you pay 3 times x minus 4, all together. How can you write that without the parentheses?' },
  'Now you try. Which is the same as −3(x − 5)? Multiply the number outside by every part inside. Watch the signs.': { style: 'A', say: 'Now you try. Which is the same as negative 3 times x minus 5, all together? Multiply the number outside by every part inside. Watch the signs.' },
  'Try a new one. Which is the same as −4(x + 2)?': { style: 'A', say: 'Try a new one. Which is the same as negative 4 times x plus 2, all together?' },
  'Work out −3 × x, then −3 × (−5). What sign does a negative times a negative give?': { style: 'A', say: 'Work out negative 3 times x, then negative 3 times negative 5. What sign does a negative times a negative give?' },
  // ── g7m3-t3 ──
  'Last time you had the parentheses, and you multiplied your way out.': { style: 'B' },
  'This time, go backwards.': { style: 'B' },
  'All you have is 6x + 9. What did it look like with parentheses?': { style: 'B', say: 'All you have is 6 x plus 9. What did it look like with parentheses?' },
  'Find the biggest number that divides every part, put it outside, and write what is left inside the parentheses.': { style: 'B' },
  'What number goes into both 6 and 9 with nothing left over?': { style: 'B' },
  '2 goes into 6, but not into 9. 3 goes into both.': { style: 'B' },
  "Nothing bigger works for both, so the 3 goes outside. That's 3 bags.": { style: 'B' },
  'Now, what goes in each bag?': { style: 'B' },
  '6x ÷ 3 = 2x, and 9 ÷ 3 = 3.': { style: 'B', say: '6 x divided by 3 equals 2 x, and 9 divided by 3 equals 3.' },
  "So each bag gets 2 packs and 3 erasers. That's 3(2x + 3).": { style: 'B', say: "So each bag gets 2 packs and 3 erasers. That's 3 times 2 x plus 3, all together." },
  "Let's check by multiplying back out.": { style: 'B' },
  '3 × 2x = 6x, and 3 × 3 = 9.': { style: 'B', say: '3 times 2 x equals 6 x, and 3 times 3 equals 9.' },
  "That's 6x + 9, exactly where we started.": { style: 'B', say: "That's 6 x plus 9, exactly where we started." },
  "Don't divide ONLY the first part.": { style: 'B+' },
  "The 9 gets divided by 3 as well. It's 3(2x + 3), not 3(2x + 9).": { style: 'B+', say: "The 9 gets divided by 3 as well. It's 3 times 2 x plus 3, all together, not 3 times 2 x plus 9." },
  // ── g7m3-t4 ──
  'Look at what happened to x.': { style: 'B' },
  'It got multiplied by 2, and then 3 got added on.': { style: 'B' },
  'Can one step get x on its own? No. It takes two.': { style: 'B' },
  'Undo the adding first, then undo the multiplying, and do the same to both sides each time.': { style: 'B' },
  'The 3 went on last, so it comes off first.': { style: 'B' },
  'Take 3 off both sides, and the scale stays level.': { style: 'B' },
  '11 − 3 = 8, so now 2x = 8.': { style: 'B', say: '11 minus 3 equals 8, so now 2 x equals 8.' },
  'Now the 2.': { style: 'B' },
  'Two bags make 8, so one bag is 8 ÷ 2 = 4.': { style: 'B' },
  'Divide both sides by 2, and x = 4.': { style: 'B' },
  'Always check.': { style: 'B' },
  'Put 4 back in for x. 2 × 4 + 3 = 8 + 3 = 11.': { style: 'B' },
  'Both sides match, so each bag holds 4 marbles.': { style: 'B' },
  "Don't divide JUST the 2x.": { style: 'B+', say: "Don't divide just the 2 x." },
  'The 3 would need dividing too. Take the 3 away first, then divide.': { style: 'B+' },
}
