/**
 * How g7m3's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 * Algebra: a number next to a letter ("3x") is said "3 x"; "3(x + 2)" is said "3 times x plus 2, all together".
 */
import type { VoiceLine } from './styles'

export const G7M3_VOICE: Record<string, VoiceLine> = {
  // ── g7m3-t5 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  'Three gift boxes. Each gift box holds x chocolates and 2 mints. 3 boxes hold 21 sweets in all, so 3(x + 2) = 21. How many chocolates are in each box?': { style: 'A', say: 'Three gift boxes. Each gift box holds x chocolates and 2 mints. 3 boxes hold 21 sweets in all, so 3 times x plus 2, all together, equals 21. How many chocolates are in each box?' },
  'Can you just take 2 away from 21?': { style: 'B' },
  "Not quite. There isn't just one 2 here.": { style: 'B' },
  'Every box has 2 mints, so three 2s are hiding inside that 21.': { style: 'B', say: "Every box has 2 mints, so three 2's are hiding inside that 21." },
  'The parentheses are one group, so divide both sides by the number outside first, then solve what is left.': { style: 'B' },
  'Look. Treat one whole box as one thing.': { style: 'B' },
  '3 equal boxes make 21, so one box is 21 ÷ 3 = 7.': { style: 'B' },
  'That means x + 2 = 7.': { style: 'B' },
  'One box is x chocolates and 2 mints, and it comes to 7.': { style: 'B' },
  'Take 2 off both sides. 7 − 2 = 5, so x = 5.': { style: 'B' },
  'Each box holds 5 chocolates.': { style: 'B' },
  'Is there another way? Yes, and it works just as well.': { style: 'B' },
  'Multiply out first. 3 times x is 3x, and 3 times 2 is 6.': { style: 'B', say: 'Multiply out first. 3 times x is 3 x, and 3 times 2 is 6.' },
  'So 3x + 6 = 21. Take 6 off both sides, and 3x = 15.': { style: 'B', say: 'So 3 x plus 6 equals 21. Take 6 off both sides, and 3 x equals 15.' },
  'Then 15 ÷ 3 = 5. Same answer, x = 5.': { style: 'B' },
  "Don't multiply ONLY the x.": { style: 'B+' },
  "The 3 multiplies the 2 as well, so it's 3x + 6, not 3x + 2.": { style: 'B+', say: "The 3 multiplies the 2 as well, so it's 3 x plus 6, not 3 x plus 2." },
  'Now you try. Solve 4(x + 3) = 32. What is x? Divide both sides by the number outside. Then solve what is left.': { style: 'A', say: 'Now you try. Solve 4 times x plus 3, all together, equals 32. What is x? Divide both sides by the number outside. Then solve what is left.' },
  'Try a new one. Solve 2(x − 5) = 8. What is x?': { style: 'A', say: 'Try a new one. Solve 2 times x minus 5, all together, equals 8. What is x?' },
  // ── g7m3-t6 ──
  'Saving for a game. You have 3 dollars and save 2 dollars a week. You want MORE than 11 dollars. After x weeks you have 2x + 3, so you need 2x + 3 > 11. Which numbers of weeks work?': { style: 'A', say: 'Saving for a game. You have 3 dollars and save 2 dollars a week. You want more than 11 dollars. After x weeks you have 2 x plus 3, so you need 2 x plus 3 to be greater than 11. Which numbers of weeks work?' },
  'How many weeks is enough? Try 5.': { style: 'B' },
  '2 × 5 + 3 = 13, more than 11, so 5 works.': { style: 'B' },
  'So do 6, and 10, and 100.': { style: 'B' },
  'An equation has one answer, but this has too many to list.': { style: 'B' },
  'Solve it just like an equation and keep the sign, and the answer is every number on one side of where you end up.': { style: 'B' },
  'Start the way you would with an equation.': { style: 'B' },
  'Take 3 off both sides. 11 − 3 = 8, so 2x + 3 > 11 becomes 2x > 8.': { style: 'B', say: 'Take 3 off both sides. 11 minus 3 equals 8, so 2 x plus 3 is greater than 11 becomes 2 x is greater than 8.' },
  "Look, the sign didn't change.": { style: 'B' },
  'Now divide both sides by 2.': { style: 'B' },
  '8 ÷ 2 = 4, so x > 4.': { style: 'B' },
  'Mark 4 on the number line with an open dot.': { style: 'B' },
  'Why open, and not filled in?': { style: 'B' },
  'At 4 weeks you have 2 × 4 + 3 = 11, and 11 is not more than 11.': { style: 'B' },
  'So 4 is out, and the arrow runs right from there.': { style: 'B' },
  'Every number past 4 works. That is x > 4.': { style: 'B' },
  'x > 4 does not mean JUST 5.': { style: 'B+' },
  '5 works, but so does 6, and 50, and every number past 4.': { style: 'B+' },
  'Now you try. Solve 3x + 2 > 14. Which is the answer? Solve it like an equation. Keep the sign.': { style: 'A', say: 'Now you try. Solve 3 x plus 2 is greater than 14. Which is the answer? Solve it like an equation. Keep the sign.' },
  'Try a new one. What is the greatest whole number that makes 2x + 5 < 17 true?': { style: 'A', say: 'Try a new one. What is the greatest whole number that makes 2 x plus 5 is less than 17 true?' },
  // ── g7m3-t7 ──
  'Find them on the number line.': { style: 'B' },
  '−2 sits to the right of −5, so −2 is the bigger one.': { style: 'B' },
  'So is −2 < −5 true? No.': { style: 'B' },
  'The sign has to turn around. −2 > −5.': { style: 'B' },
  'When you multiply or divide both sides by a negative number, flip the sign around.': { style: 'B' },
  'Now a real one. Solve −3x < 12.': { style: 'B', say: 'Now a real one. Solve negative 3 x is less than 12.' },
  'To get x by itself, divide both sides by −3.': { style: 'B' },
  '12 ÷ (−3) = −4.': { style: 'B', say: '12 divided by negative 3 equals negative 4.' },
  'But which way does the sign point?': { style: 'B' },
  'You divided by a negative, so the < flips to >.': { style: 'B', say: 'You divided by a negative, so less than flips to greater than.' },
  'That gives x > −4. Mark −4 with an open dot, and the arrow runs right.': { style: 'B' },
  'Does it really work? Test two numbers.': { style: 'B' },
  'Try 0, which is past −4. −3 × 0 = 0, and 0 < 12. True.': { style: 'B' },
  'Now try −5, on the other side. −3 × (−5) = 15, and 15 is not less than 12.': { style: 'B', say: 'Now try negative 5, on the other side. Negative 3 times negative 5 equals 15, and 15 is not less than 12.' },
  'So the numbers past −4 are the ones that work.': { style: 'B' },
  "Don't KEEP the sign when you divide by a negative.": { style: 'B+' },
  '−3x < 12 gives x > −4, not x < −4.': { style: 'B+', say: 'Negative 3 x is less than 12 gives x is greater than negative 4, not x is less than negative 4.' },
  'Now you try. Solve −2x < 10. Which is the answer? Divide both sides. If you divide by a negative, flip the sign.': { style: 'A', say: 'Now you try. Solve negative 2 x is less than 10. Which is the answer? Divide both sides. If you divide by a negative, flip the sign.' },
  'Try a new one. Solve −4x ≥ 24. Which is the answer?': { style: 'A', say: 'Try a new one. Solve negative 4 x is greater than or equal to 24. Which is the answer?' },
  // ── g7m3-t8 ──
  'The phone bill. A phone plan costs 20 dollars a month, plus 5 dollars for each GB of data. This month the bill is 45 dollars. How many GB were used?': { style: 'A', say: 'The phone bill. A phone plan costs 20 dollars a month, plus 5 dollars for each gigabyte of data. This month the bill is 45 dollars. How many gigabytes were used?' },
  'You could guess. Try 3 gigabytes.': { style: 'B' },
  "20 + 3 × 5 = 35. Too low. Try 4, and that's 40. Still too low.": { style: 'B' },
  "Guessing works, but it's slow. Is there a way with no guessing? Yes.": { style: 'B' },
  "Use a letter for the number you don't know, write the story as an equation, then solve it.": { style: 'B' },
  'Let g be the number of gigabytes.': { style: 'B' },
  'Each one costs 5 dollars, so the data part is 5g.': { style: 'B', say: 'Each one costs 5 dollars, so the data part is 5 g.' },
  'Add the 20 for the plan. The whole bill is 20 + 5g = 45.': { style: 'B', say: 'Add the 20 for the plan. The whole bill is 20 plus 5 g equals 45.' },
  'Now solve it the way you already know.': { style: 'B' },
  'Take 20 off both sides. 45 − 20 = 25, so 5g = 25.': { style: 'B', say: 'Take 20 off both sides. 45 minus 20 equals 25, so 5 g equals 25.' },
  'Divide both sides by 5, and g = 5.': { style: 'B' },
  'Does 5 really fit the story? Check it.': { style: 'B' },
  '5 gigabytes cost 5 × 5 = 25 dollars.': { style: 'B' },
  "Add the 20 for the plan, and that's 45 dollars, the bill.": { style: 'B' },
  'So 5 gigabytes were used.': { style: 'B' },
  'The letter goes with the number paid for EACH gigabyte.': { style: 'B+' },
  "That's the 5, not the 20. So it's 20 + 5g, not 5 + 20g.": { style: 'B+', say: "That's the 5, not the 20. So it's 20 plus 5 g, not 5 plus 20 g." },
}
