/**
 * How g7m5's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G7M5_VOICE: Record<string, VoiceLine> = {
  // ── g7m5-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "The basketball team has 20 kids, and they're easy to find.": { style: 'B' },
  "Look. 16 of the 20 pick basketball.": { style: 'B' },
  "Does that sound like the whole school? No. We only asked one kind of kid.": { style: 'B' },
  "A fair sample gives everyone in the group the same chance to be picked.": { style: 'B' },
  "Here is a better way. Put all 400 names in a hat.": { style: 'B' },
  "Pull out 20 without looking.": { style: 'B' },
  "Now every student has the same chance. Nobody is left out.": { style: 'B' },
  "So how did the hat do? 7 of the 20 names picked soccer.": { style: 'B' },
  "That's 35 out of every 100.": { style: 'B' },
  "In the whole school, 140 of 400 picked soccer. Also 35 out of every 100.": { style: 'B' },
  "The small group is a little copy of the big one.": { style: 'B' },
  "So ask this every time. Could anyone never be picked?": { style: 'B' },
  "Ask the team, and every kid who is not on the team is left out. That's 380 kids.": { style: 'B' },
  "Draw from the hat, and nobody is left out.": { style: 'B' },
  "Don't call a sample fair just because it's BIG.": { style: 'B+' },
  "100 fans at a basketball game is a lot, but they still pick basketball.": { style: 'B+' },
  "Ask who is left out, not how many you asked.": { style: 'B+' },
  // ── g7m5-t2 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "12 of the kids you asked like pizza best.": { style: 'B' },
  "So do just 12 kids in the whole school like pizza? No.": { style: 'B' },
  "You asked only 40 of the 600. Lots of pizza fans never got asked.": { style: 'B' },
  "A fair sample is a small copy of the whole group, so the same fraction works for both.": { style: 'B' },
  "Start with the kids you asked. 12 out of 40 like pizza.": { style: 'B' },
  "Divide both by 4. 12 out of 40 is the same as 3 out of 10.": { style: 'B' },
  "So about 3 out of every 10 kids pick pizza.": { style: 'B' },
  "Now the whole school. Does it need a new fraction? No. Same tape, just bigger.": { style: 'B' },
  "Split the 600 students into those same 10 equal parts.": { style: 'B' },
  "600 ÷ 10 = 60, so each part is 60 kids.": { style: 'B' },
  "3 of those 10 parts are the pizza parts.": { style: 'B' },
  "So count them up. 3 × 60 = 180.": { style: 'B' },
  "Predict that about 180 of the 600 students pick pizza.": { style: 'B' },
  "Don't STOP at the 12 from the sample.": { style: 'B+' },
  "12 is out of the 40 you asked. Scale it up to 600, and you get 180.": { style: 'B+' },
  // ── g7m5-t3 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Careful. Class A has a plant that is only 5 inches.": { style: 'B' },
  "Class B has one that is 7.": { style: 'B' },
  "So is Class B taller? No. Pick two other plants, and A wins.": { style: 'B' },
  "We need one number for a whole class.": { style: 'B' },
  "To compare two groups, find the gap between their means, then check it against the spread.": { style: 'B' },
  "Add up Class A. 5 + 6 + 6 + 7 + 7 + 7 + 8 + 8 + 9 = 63.": { style: 'B' },
  "Class B adds up to 45.": { style: 'B' },
  "Each class has 9 plants, so divide each total by 9.": { style: 'B' },
  "63 ÷ 9 = 7, and 45 ÷ 9 = 5.": { style: 'B' },
  "So Class A's plants are 7 inches on average. Class B's are 5.": { style: 'B' },
  "How far apart is that? 7 − 5 = 2.": { style: 'B' },
  "On average, Class A's plants are 2 inches taller.": { style: 'B' },
  "Is a gap of 2 a lot? That depends on the spread.": { style: 'B' },
  "Class A runs from 5 to 9. Class B runs from 3 to 7.": { style: 'B' },
  "That's a spread of 4 in each class.": { style: 'B' },
  "The gap is only half of that, so the plots overlap a lot.": { style: 'B' },
  "Class A is a bit taller, not a lot.": { style: 'B' },
  "Don't compare just the TALLEST plants.": { style: 'B+' },
  "9 beats 7, but one plant is not the class.": { style: 'B+' },
  "Find the means first, then check the spread.": { style: 'B+' },
}
