/**
 * How g7m5's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G7M5_VOICE: Record<string, VoiceLine> = {
  // ── g7m5-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "The basketball team has 20 kids, and they're easy to find.": { style: 'B' },
  "Look. 16 of the 20 pick basketball.": { style: 'B' },
  "Does that sound like the whole school? No. We only asked one kind of kid.": { style: 'B' },
  "A fair sample gives everyone in the group the same chance to be picked.": { style: 'B' },
  "Here is a better way. Put all 400 names in a hat.": { style: 'B' },
  "Pull out 20 without looking.": { style: 'B' },
  "Now every student has the same chance. Nobody is left out.": { style: 'B' },
  "So how did the hat do? 7 of the 20 names picked soccer.": { style: 'B' },
  "That's 35 out of every 100.": { style: 'B' },
  "In the whole school, 140 of 400 picked soccer. Also 35 out of every 100.": { style: 'B' },
  "The small group is a little copy of the big one.": { style: 'B' },
  "So ask this every time. Could anyone never be picked?": { style: 'B' },
  "Ask the team, and every kid who is not on the team is left out. That's 380 kids.": { style: 'B' },
  "Draw from the hat, and nobody is left out.": { style: 'B' },
  "Don't call a sample fair just because it's BIG.": { style: 'B+' },
  "100 fans at a basketball game is a lot, but they still pick basketball.": { style: 'B+' },
  "Ask who is left out, not how many you asked.": { style: 'B+' },
  // ── g7m5-t2 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "12 of the kids you asked like pizza best.": { style: 'B' },
  "So do just 12 kids in the whole school like pizza? No.": { style: 'B' },
  "You asked only 40 of the 600. Lots of pizza fans never got asked.": { style: 'B' },
  "A fair sample is a small copy of the whole group, so the same fraction works for both.": { style: 'B' },
  "Start with the kids you asked. 12 out of 40 like pizza.": { style: 'B' },
  "Divide both by 4. 12 out of 40 is the same as 3 out of 10.": { style: 'B' },
  "So about 3 out of every 10 kids pick pizza.": { style: 'B' },
  "Now the whole school. Does it need a new fraction? No. Same tape, just bigger.": { style: 'B' },
  "Split the 600 students into those same 10 equal parts.": { style: 'B' },
  "600 ÷ 10 = 60, so each part is 60 kids.": { style: 'B' },
  "3 of those 10 parts are the pizza parts.": { style: 'B' },
  "So count them up. 3 × 60 = 180.": { style: 'B' },
  "Predict that about 180 of the 600 students pick pizza.": { style: 'B' },
  "Don't STOP at the 12 from the sample.": { style: 'B+' },
  "12 is out of the 40 you asked. Scale it up to 600, and you get 180.": { style: 'B+' },
  // ── g7m5-t3 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Careful. Class A has a plant that is only 5 inches.": { style: 'B' },
  "Class B has one that is 7.": { style: 'B' },
  "So is Class B taller? No. Pick two other plants, and A wins.": { style: 'B' },
  "We need one number for a whole class.": { style: 'B' },
  "To compare two groups, find the gap between their means, then check it against the spread.": { style: 'B' },
  "Add up Class A. 5 + 6 + 6 + 7 + 7 + 7 + 8 + 8 + 9 = 63.": { style: 'B' },
  "Class B adds up to 45.": { style: 'B' },
  "Each class has 9 plants, so divide each total by 9.": { style: 'B' },
  "63 ÷ 9 = 7, and 45 ÷ 9 = 5.": { style: 'B' },
  "So Class A's plants are 7 inches on average. Class B's are 5.": { style: 'B' },
  "How far apart is that? 7 − 5 = 2.": { style: 'B' },
  "On average, Class A's plants are 2 inches taller.": { style: 'B' },
  "Is a gap of 2 a lot? That depends on the spread.": { style: 'B' },
  "Class A runs from 5 to 9. Class B runs from 3 to 7.": { style: 'B' },
  "That's a spread of 4 in each class.": { style: 'B' },
  "The gap is only half of that, so the plots overlap a lot.": { style: 'B' },
  "Class A is a bit taller, not a lot.": { style: 'B' },
  "Don't compare just the TALLEST plants.": { style: 'B+' },
  "9 beats 7, but one plant is not the class.": { style: 'B+' },
  "Find the means first, then check the spread.": { style: 'B+' },
  // ── g7m5-t4 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "There are four colors here. So is the chance of blue 1 out of 4?": { style: 'B' },
  "Blue covers 4 parts. Yellow covers only 1.": { style: 'B' },
  "The colors are not the same size, so count the parts, not the colors.": { style: 'B' },
  "The chance of something is the ways it can happen over all the equal ways, a number from 0 to 1.": { style: 'B' },
  "Count the blue parts with me. 1, 2, 3, 4.": { style: 'B' },
  "Now count every part. There are 10, all the same size.": { style: 'B' },
  "So blue is 4 ways out of 10 equal ways. That's 4/10.": { style: 'B' },
  "4/10 is four tenths.": { style: 'B' },
  "How do we write four tenths as a decimal? A 4 in the tenths place, 0.4.": { style: 'B', say: "How do we write four tenths as a decimal? A 4 in the tenths place, zero point four." },
  "4/10 and 0.4 are the same chance, just written two ways.": { style: 'B', say: "Four tenths and zero point four are the same chance, just written two ways." },
  "What about not blue? That's the other 6 parts.": { style: 'B' },
  "6 out of 10 is 6/10, or 0.6.": { style: 'B', say: "6 out of 10 is six tenths, or zero point six." },
  "Add them, and 0.4 + 0.6 = 1, because the spinner always lands somewhere.": { style: 'B', say: "Add them, and zero point four plus zero point six equals 1, because the spinner always lands somewhere." },
  "And purple? There is no purple, so its chance is 0.": { style: 'B' },
  "Don't put the blue parts over the parts that are NOT blue. That gives 4/6.": { style: 'B+' },
  "Blue goes over all 10 parts, so it's 4/10, or 0.4.": { style: 'B+', say: "Blue goes over all 10 parts, so it's four tenths, or zero point four." },
  // ── g7m5-t5 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "One kid guessed 40 heads. Another guessed 10.": { style: 'B' },
  "Which guess is right? A guess could be anything at all.": { style: 'B' },
  "What we want is a number that comes from the coin itself.": { style: 'B' },
  "The number you expect is the chance times the number of tries, and real results land near it, not always on it.": { style: 'B' },
  "On each flip, heads has a chance of 1/2.": { style: 'B' },
  "Multiply that chance by the 50 tries. 1/2 × 50 = 25.": { style: 'B' },
  "So we expect 25 heads, and 25 tails.": { style: 'B' },
  "Here is what the class really got. 27 heads, and 23 tails.": { style: 'B' },
  "Is 27 close to 25? Yes, just 2 more.": { style: 'B' },
  "Every flip starts fresh, so real results wander a little.": { style: 'B' },
  "Another class flipped 500 times and got 246 heads.": { style: 'B' },
  "27 out of 50 is 0.54. 246 out of 500 is 0.492.": { style: 'B', say: "27 out of 50 is zero point five four. 246 out of 500 is zero point four nine two." },
  "Which one is closer to one half, 0.5? The 500 flips.": { style: 'B', say: "Which one is closer to one half, zero point five? The 500 flips." },
  "The more tries you take, the closer you get to the chance.": { style: 'B' },
  "The real count does NOT have to equal the expected count.": { style: 'B+' },
  "27 heads is not a mistake, and the coin is not broken. Close to 25 is just what real results do.": { style: 'B+' },
  // ── g7m5-t6 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Heads is 1/2. A 5 is 1/6. So do we just add them?": { style: 'B' },
  "1/2 + 1/6 = 4/6. That's bigger than either chance on its own.": { style: 'B' },
  "But getting both at once should be harder than getting one, not easier.": { style: 'B' },
  "To find the chance of two things together, list every pair in a table and count the pairs you want over all the pairs.": { style: 'B' },
  "Let's build the table. The rows are the coin, heads or tails.": { style: 'B' },
  "The columns are the cube, 1 through 6.": { style: 'B' },
  "Every box is one way the two can land together. H1, H2, all the way to T6.": { style: 'B', say: "Every box is one way the two can land together. Heads 1, heads 2, all the way to tails 6." },
  "How many boxes are there?": { style: 'B' },
  "2 rows × 6 columns = 12.": { style: 'B' },
  "So there are 12 pairs, each one just as likely.": { style: 'B' },
  "Now find the one we wanted, heads and a 5.": { style: 'B' },
  "It's a single box, H5, in the heads row.": { style: 'B', say: "It's a single box, heads 5, in the heads row." },
  "One box out of 12, so the chance is 1/12.": { style: 'B' },
  "That's smaller than 1/2, and smaller than 1/6, just as it should be.": { style: 'B' },
  "Don't ADD the two chances together.": { style: 'B+' },
  "Make the table, then count the pairs you want over all the pairs.": { style: 'B+' },
  // ── g7m5-t6, outside the teach (the twin): the parentheses said as words ──
  "Try a new one. You spin a spinner with 3 equal parts (red, blue and green) and flip a coin. What is the probability of blue and heads?": { style: 'A', say: "Try a new one. You spin a spinner with 3 equal parts, red, blue and green, and flip a coin. What is the probability of blue and heads?" },
}
