/**
 * How g8m1's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G8M1_VOICE: Record<string, VoiceLine> = {
  // ── g8m1-t6 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  // The topic is the WRITTEN form, so a decimal is said digit by digit: "zero point zero zero zero five two".
  "Last time, big numbers got a positive exponent.": { style: 'B' },
  "So could this be 5.2 × 10⁴?": { style: 'B', say: "So could this be five point two times 10 to the fourth?" },
  "No. That is 52,000, and this grain is smaller than 1.": { style: 'B', say: "No. That is 52 thousand, and this grain is smaller than 1." },
  "The exponent has to do something new.": { style: 'B' },
  "For a number smaller than 1, the point moves right to make a number from 1 up to 10, and the exponent is the number of jumps, made negative.": { style: 'B' },
  "Start at 0.00052 and move the point to the right.": { style: 'B', say: "Start at zero point zero zero zero five two, and move the point to the right." },
  "Stop just after the 5, the first digit that is not a zero. Now it reads 5.2.": { style: 'B', say: "Stop just after the 5, the first digit that is not a zero. Now it reads five point two." },
  "How many jumps was that? Count them: 1, 2, 3, 4.": { style: 'B', say: "How many jumps was that? Count them. 1, 2, 3, 4." },
  "Now go back the other way.": { style: 'B' },
  "From 5.2, divide by 10 four times and you are back at 0.00052.": { style: 'B', say: "From five point two, divide by 10 four times, and you are back at zero point zero zero zero five two." },
  "Each ÷ 10 is the same as × 10⁻¹, so four of them make × 10⁻⁴.": { style: 'B', say: "Each divide by 10 is the same as times 10 to the negative 1, so four of them make times 10 to the negative 4." },
  "So 0.00052 = 5.2 × 10⁻⁴.": { style: 'B', say: "So zero point zero zero zero five two equals five point two times 10 to the negative 4." },
  "Here is a shorter one: 0.03.": { style: 'B', say: "Here is a shorter one. Zero point zero three." },
  "The point jumps 2 places right to make 3.": { style: 'B' },
  "So 0.03 = 3 × 10⁻².": { style: 'B', say: "So zero point zero three equals 3 times 10 to the negative 2." },
  "Don't count ONLY the zeros after the point.": { style: 'B+' },
  "0.00052 has 3 of them, but the point jumps 4 places to land past the 5.": { style: 'B+', say: "Zero point zero zero zero five two has 3 of them, but the point jumps 4 places to land past the 5." },
  "A grain of pollen. A grain of pollen is about 0.00052 meters wide. That is a lot of zeros on the other side of the point. Can you write it the short way, like 1.5 × 10⁸?": { style: 'A', say: "A grain of pollen. A grain of pollen is about zero point zero zero zero five two meters wide. That is a lot of zeros on the other side of the point. Can you write it the short way, like one point five times 10 to the eighth?" },
  "Now you try. 0.0007 = 7 × 10^?. What is the exponent? Move the point right to make a number from 1 up to 10. Count the jumps, and make it negative.": { style: 'A', say: "Now you try. Zero point zero zero zero seven equals 7 times 10 to the what? What is the exponent? Move the point right to make a number from 1 up to 10. Count the jumps, and make it negative." },
  "Try a new one. 0.000061 = 6.1 × 10^?. What is the exponent?": { style: 'A', say: "Try a new one. Zero point zero zero zero zero six one equals six point one times 10 to the what? What is the exponent?" },
  "Move the point right. Where must it stop to make 6.1?": { style: 'A', say: "Move the point right. Where must it stop to make six point one?" },
  "You moved the point 5 places to make 6.1, so the exponent is −5.": { style: 'A', say: "You moved the point 5 places to make six point one, so the exponent is negative 5." },
  // ── g8m1-t7 ──
  "You could write these out the long way, 30,000 × 2,000, and count the zeros.": { style: 'B', say: "You could write these out the long way, 30 thousand times 2 thousand, and count the zeros." },
  "That works for small ones.": { style: 'B' },
  "But what about 3 × 10²¹? That is 21 zeros to write before you even start.": { style: 'B', say: "But what about 3 times 10 to the twenty-first? That is 21 zeros to write before you even start." },
  "Multiply the front numbers and add the exponents of 10, and if the front number comes out 10 or more, move its point one place and add 1 to the exponent.": { style: 'B' },
  "When you multiply, the order does not matter.": { style: 'B' },
  "So put the front numbers together, and the powers of 10 together.": { style: 'B' },
  "Then 3 × 2 = 6.": { style: 'B' },
  "Now the powers of 10.": { style: 'B' },
  "They have the same base, so add the exponents: 4 + 3 = 7.": { style: 'B' },
  "That makes 10⁷. So the warehouse holds 6 × 10⁷ screws.": { style: 'B', say: "That makes 10 to the seventh. So the warehouse holds 6 times 10 to the seventh screws." },
  "Now try (4 × 10⁵) × (5 × 10²).": { style: 'B', say: "Now try 4 times 10 to the fifth, times 5 times 10 squared." },
  "4 × 5 = 20, and 10⁵ × 10² = 10⁷.": { style: 'B', say: "4 times 5 equals 20, and 10 to the fifth times 10 squared equals 10 to the seventh." },
  "But is 20 under 10? No, so we are not done.": { style: 'B' },
  "20 is 2 × 10¹, so that extra 10 joins the others, and the answer is 2 × 10⁸.": { style: 'B', say: "20 is 2 times 10 to the first, so that extra 10 joins the others, and the answer is 2 times 10 to the eighth." },
  "Don't STOP at 20 × 10⁷.": { style: 'B+', say: "Don't stop at 20 times 10 to the seventh." },
  "It has the right value, but the front number has to be under 10. Write it as 2 × 10⁸.": { style: 'B+', say: "It has the right value, but the front number has to be under 10. Write it as 2 times 10 to the eighth." },
  "Boxes of screws. A warehouse has 3 × 10⁴ boxes. Each box holds 2 × 10³ screws. How many screws are there in all?": { style: 'A', say: "Boxes of screws. A warehouse has 3 times 10 to the fourth boxes. Each box holds 2 times 10 cubed screws. How many screws are there in all?" },
  "Now you try. (3 × 10⁵) × (3 × 10²) = 9 × 10^?. What is the exponent? Multiply the front numbers. Add the exponents of 10.": { style: 'A', say: "Now you try. 3 times 10 to the fifth, times 3 times 10 squared, equals 9 times 10 to the what? What is the exponent? Multiply the front numbers. Add the exponents of 10." },
  "Try a new one. (2 × 10⁶) × (4 × 10³) = 8 × 10^?. What is the exponent?": { style: 'A', say: "Try a new one. 2 times 10 to the sixth, times 4 times 10 cubed, equals 8 times 10 to the what? What is the exponent?" },
  "The front numbers make 9. What do you do with 10⁵ and 10²?": { style: 'A', say: "The front numbers make 9. What do you do with 10 to the fifth and 10 squared?" },
  "You added the exponents of 10 and got 8 × 10⁹.": { style: 'A', say: "You added the exponents of 10 and got 8 times 10 to the ninth." },
  // ── g8m1-t8 ── (12.5 is how much, so it is said as a value: "twelve and a half")
  "Dividing feels like the obvious move. Half of 25 is 12.5.": { style: 'B', say: "Dividing feels like the obvious move. Half of 25 is twelve and a half." },
  "But could the patio be 12.5 tiles long?": { style: 'B', say: "But could the patio be twelve and a half tiles long?" },
  "No. 12.5 rows of 12.5 tiles is far more than 25.": { style: 'B', say: "No. Twelve and a half rows of twelve and a half tiles is far more than 25." },
  "What we need is a number that multiplies with itself.": { style: 'B' },
  "To undo squaring, find the number that times itself makes it, and to undo cubing, find the number that, used three times, makes it.": { style: 'B' },
  "Start with the patio. It is a square, so side times side makes 25.": { style: 'B' },
  "5 × 5 = 25, so the side is 5 tiles.": { style: 'B' },
  "We write that as √25 = 5.": { style: 'B' },
  "Now the box. It is a cube, so side times side times side makes 27.": { style: 'B' },
  "3 × 3 × 3 = 27, so the side is 3 cubes.": { style: 'B' },
  "This one gets a small 3 on the sign: ∛27 = 3.": { style: 'B', say: "This one gets a small 3 on the sign. The cube root of 27 equals 3." },
  "Is there a faster way? Yes. Know your squares and cubes by heart.": { style: 'B' },
  "16 is 4 × 4, so √16 = 4.": { style: 'B' },
  "And 64 is 4 × 4 × 4, so ∛64 = 4.": { style: 'B', say: "And 64 is 4 times 4 times 4, so the cube root of 64 equals 4." },
  "Don't DIVIDE by 2 to find √36.": { style: 'B+' },
  "36 ÷ 2 is 18, and 18 × 18 is far more than 36. 6 × 6 = 36, so √36 = 6.": { style: 'B+' },
  // ── g8m1-t9 ── (4.5 is how much: "four and a half")
  "Try whole numbers first. 4 × 4 = 16, and that is too small.": { style: 'B' },
  "5 × 5 = 25, and that is too big.": { style: 'B' },
  "So which whole number times itself makes 20? None of them. We have to close in on it.": { style: 'B' },
  "Find the perfect squares just below and just above the number, and the square root sits between their roots, nearer the closer square.": { style: 'B' },
  "Which perfect squares sit on each side of 20? They are 16 and 25.": { style: 'B' },
  "So √20 is between √16 = 4 and √25 = 5.": { style: 'B', say: "So the square root of 20 is between the square root of 16, which is 4, and the square root of 25, which is 5." },
  "Now measure the two gaps. 20 is 4 away from 16, but 5 away from 25.": { style: 'B' },
  "It is closer to 16, so √20 is closer to 4.": { style: 'B' },
  "Let's check. Halfway between 4 and 5 is 4.5.": { style: 'B', say: "Let's check. Halfway between 4 and 5 is four and a half." },
  "4.5 × 4.5 = 20.25, a little more than 20.": { style: 'B', say: "Four and a half times four and a half is twenty and a quarter, a little more than 20." },
  "So √20 is just under 4.5, nearer to 4.": { style: 'B', say: "So the square root of 20 is just under four and a half, nearer to 4." },
  "Don't HALVE the number.": { style: 'B+' },
  "√20 is not 10, because 10 × 10 = 100. Look for the perfect squares around 20 instead.": { style: 'B+' },
}
