/**
 * How g8m1's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G8M1_VOICE: Record<string, VoiceLine> = {
  // ── g8m1-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "You could work it all out. 2³ is 8, 2² is 4, and 8 × 4 = 32.": { style: 'B', say: "You could work it all out. 2 cubed is 8, 2 squared is 4, and 8 × 4 = 32." },
  "Then you hunt for the exponent that makes 32.": { style: 'B' },
  "But what about 2¹⁰ × 2¹⁵? You would be counting all day.": { style: 'B', say: "But what about 2 to the tenth × 2 to the fifteenth? You would be counting all day." },
  "When you multiply two numbers with the same base, keep the base and add the exponents.": { style: 'B' },
  "What does 2³ really mean? Three twos, multiplied together.": { style: 'B', say: "What does 2 cubed really mean? Three twos, multiplied together." },
  "And 2² is two more twos.": { style: 'B', say: "And 2 squared is two more twos." },
  "Line them all up in one long row.": { style: 'B' },
  "Now count them. 3 twos, then 2 more.": { style: 'B' },
  "That makes 5 twos in one row.": { style: 'B' },
  "So 2³ × 2² = 2⁵. The 3 and the 2 added up to 5.": { style: 'B', say: "So 2 cubed × 2 squared = 2 to the fifth. The 3 and the 2 added up to 5." },
  "Does it check out? 2⁵ is 32, the same 32 as before.": { style: 'B', say: "Does it check out? 2 to the fifth is 32, the same 32 as before." },
  "And any base works. 5⁴ × 5³ = 5⁷, because 4 + 3 = 7.": { style: 'B', say: "And any base works. 5 to the fourth × 5 cubed = 5 to the seventh, because 4 + 3 = 7." },
  "Don't MULTIPLY the exponents. 2³ × 2² is not 2⁶.": { style: 'B+', say: "Don't multiply the exponents. 2 cubed × 2 squared is not 2 to the sixth." },
  "Count the twos instead: 3 and 2 more make 5, so it's 2⁵.": { style: 'B+', say: "Count the twos instead: 3 and 2 more make 5, so it's 2 to the fifth." },
  "Now you try. Write 3⁴ × 3² as 3 with one exponent. What is the exponent? Keep the base. Add the exponents.": { style: 'A', say: "Now you try. Write 3 to the fourth × 3 squared as 3 with one exponent. What is the exponent? Keep the base. Add the exponents." },
  "Try a new one. Write 7⁵ × 7³ as 7 with one exponent. What is the exponent?": { style: 'A', say: "Try a new one. Write 7 to the fifth × 7 cubed as 7 with one exponent. What is the exponent?" },
  "You kept the base 7 and added the exponents to get 7⁸.": { style: 'A', say: "You kept the base 7 and added the exponents to get 7 to the eighth." },
  // ── g8m1-t2 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Could you just divide the exponents, 5 ÷ 3?": { style: 'B' },
  "No. 5 ÷ 3 is not even a whole number, so that can't be it.": { style: 'B' },
  "You could work out 32 ÷ 8. But that's no help for 2²⁰ ÷ 2¹⁷.": { style: 'B', say: "You could work out 32 ÷ 8. But that's no help for 2 to the twentieth ÷ 2 to the seventeenth." },
  "When you divide powers with the same base, keep the base and subtract the exponents: top minus bottom.": { style: 'B' },
  "Let's write the division as a fraction.": { style: 'B' },
  "What's on top? Five twos, multiplied.": { style: 'B' },
  "And on the bottom, three twos.": { style: 'B' },
  "Now pair them off. A 2 on top and a 2 on the bottom make 2 ÷ 2, which is 1.": { style: 'B' },
  "Three pairs cancel, and two twos are left on top.": { style: 'B' },
  "That's 5 − 3 = 2, so 2⁵ ÷ 2³ = 2².": { style: 'B', say: "That's 5 − 3 = 2, so 2 to the fifth ÷ 2 cubed = 2 squared." },
  "Check it. 2² is 4, and 32 ÷ 8 is 4 too. So there are 4 teams.": { style: 'B', say: "Check it. 2 squared is 4, and 32 ÷ 8 is 4 too. So there are 4 teams." },
  "Any base works the same way. 7⁶ ÷ 7² = 7⁴, because 6 − 2 = 4.": { style: 'B', say: "Any base works the same way. 7 to the sixth ÷ 7 squared = 7 to the fourth, because 6 − 2 = 4." },
  "Don't DIVIDE the exponents. 2⁶ ÷ 2³ is not 2².": { style: 'B+', say: "Don't divide the exponents. 2 to the sixth ÷ 2 cubed is not 2 squared." },
  "Subtract them instead. 6 − 3 = 3, so it's 2³.": { style: 'B+', say: "Subtract them instead. 6 − 3 = 3, so it's 2 cubed." },
  "Teams for a tournament. A game tournament starts with 2⁵ players. They split into teams of 2³ players each. The number of teams is 2⁵ ÷ 2³. Can you write it as 2 with one exponent?": { style: 'A', say: "Teams for a tournament. A game tournament starts with 2 to the fifth players. They split into teams of 2 cubed players each. The number of teams is 2 to the fifth ÷ 2 cubed. Can you write it as 2 with one exponent?" },
  "Now you try. Write 3⁷ ÷ 3² as 3 with one exponent. What is the exponent? Keep the base. Subtract the bottom exponent from the top one.": { style: 'A', say: "Now you try. Write 3 to the seventh ÷ 3 squared as 3 with one exponent. What is the exponent? Keep the base. Subtract the bottom exponent from the top one." },
  "Try a new one. Write 5⁹ ÷ 5³ as 5 with one exponent. What is the exponent?": { style: 'A', say: "Try a new one. Write 5 to the ninth ÷ 5 cubed as 5 with one exponent. What is the exponent?" },
  "You cancelled the 5s in pairs and had 5⁶ left.": { style: 'A', say: "You cancelled the fives in pairs and had 5 to the sixth left." },
  // ── g8m1-t3 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "You see a 3 and a 2. Should you add them and get 2⁵?": { style: 'B', say: "You see a 3 and a 2. Should you add them and get 2 to the fifth?" },
  "Look at what the outside 2 asks for. Two copies of 2³, multiplied: 2³ × 2³.": { style: 'B', say: "Look at what the outside 2 asks for. Two copies of 2 cubed, multiplied: 2 cubed × 2 cubed." },
  "Count those twos, and there are more than five.": { style: 'B' },
  "When you raise a power to another exponent, keep the base and multiply the exponents.": { style: 'B' },
  "What is the outside 2 counting? Copies.": { style: 'B' },
  "It says write 2³ down two times, and multiply them.": { style: 'B', say: "It says write 2 cubed down two times, and multiply them." },
  "So (2³)² = 2³ × 2³.": { style: 'B', say: "So 2 cubed, all squared, = 2 cubed × 2 cubed." },
  "Now count every 2. Each copy has 3 twos, and there are 2 copies.": { style: 'B' },
  "3 twos, 2 times over, is 3 × 2 = 6 twos.": { style: 'B' },
  "So (2³)² = 2⁶.": { style: 'B', say: "So 2 cubed, all squared, = 2 to the sixth." },
  "Try a bigger one. (5⁴)³ is three copies of 5⁴.": { style: 'B', say: "Try a bigger one. 5 to the fourth, all cubed, is three copies of 5 to the fourth." },
  "That's 4 + 4 + 4 fives, which is 4 × 3 = 12.": { style: 'B' },
  "So (5⁴)³ = 5¹².": { style: 'B', say: "So 5 to the fourth, all cubed, = 5 to the twelfth." },
  "Don't ADD the exponents here. (2³)² is not 2⁵.": { style: 'B+', say: "Don't add the exponents here. 2 cubed, all squared, is not 2 to the fifth." },
  "The outside 2 counts copies, so multiply. 3 × 2 = 6, and it's 2⁶.": { style: 'B+', say: "The outside 2 counts copies, so multiply. 3 × 2 = 6, and it's 2 to the sixth." },
  "A square poster. A square poster is 2³ inches wide and 2³ inches tall. Its area is (2³)² square inches. Can you write that as 2 with one exponent?": { style: 'A', say: "A square poster. A square poster is 2 cubed inches wide and 2 cubed inches tall. Its area is 2 cubed, all squared, square inches. Can you write that as 2 with one exponent?" },
  "Now you try. Write (3²)⁴ as 3 with one exponent. What is the exponent? Keep the base. Multiply the exponents.": { style: 'A', say: "Now you try. Write 3 squared, all to the fourth, as 3 with one exponent. What is the exponent? Keep the base. Multiply the exponents." },
  "Try a new one. Write (7⁵)² as 7 with one exponent. What is the exponent?": { style: 'A', say: "Try a new one. Write 7 to the fifth, all squared, as 7 with one exponent. What is the exponent?" },
  "Two copies of 7⁵: count the 7s in both copies together.": { style: 'A', say: "Two copies of 7 to the fifth: count the sevens in both copies together." },
  "You multiplied the exponents and wrote it as 7¹⁰.": { style: 'A', say: "You multiplied the exponents and wrote it as 7 to the tenth." },
  // ── g8m1-t4 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "What would 2⁰ mean? Zero twos, multiplied together?": { style: 'B', say: "What would 2 to the zero mean? Zero twos, multiplied together?" },
  "And 2⁻¹ would be a negative number of twos. You can't count that.": { style: 'B', say: "And 2 to the negative 1 would be a negative number of twos. You can't count that." },
  "So counting won't help here. We need another way to look at it.": { style: 'B' },
  "Each time the exponent goes down by 1, divide by the base, even past zero.": { style: 'B' },
  "Read the row with me, left to right.": { style: 'B' },
  "Each time the exponent drops by 1, what happens? The value is divided by 2.": { style: 'B' },
  "8 ÷ 2 = 4, and 4 ÷ 2 = 2.": { style: 'B' },
  "Now keep the pattern going, one more step down from 2¹.": { style: 'B', say: "Now keep the pattern going, one more step down from 2 to the first." },
  "2 ÷ 2 = 1, so 2⁰ = 1.": { style: 'B', say: "2 ÷ 2 = 1, so 2 to the zero = 1." },
  "Any other base does the same. 5⁰ is 1 too.": { style: 'B', say: "Any other base does the same. 5 to the zero is 1 too." },
  "One more step down. 1 ÷ 2 = 1/2, so 2⁻¹ = 1/2.": { style: 'B', say: "One more step down. 1 ÷ 2 = 1/2, so 2 to the negative 1 = 1/2." },
  "One more again, and 2⁻² = 1/4.": { style: 'B', say: "One more again, and 2 to the negative 2 = 1/4." },
  "So 2⁻² is 1 divided by 2², which is 1/4.": { style: 'B', say: "So 2 to the negative 2 is 1 divided by 2 squared, which is 1/4." },
  "A negative exponent does NOT make a negative answer.": { style: 'B+' },
  "2⁻² is 1/4, a small number above 0. It is not −4.": { style: 'B+', say: "2 to the negative 2 is 1/4, a small number above 0. It is not −4." },
  "Half a pizza each day. You have 8 pizzas. Each day, half of what is left gets eaten: 8, then 4, then 2. In 2s those are 2³, 2², 2¹. What comes next, and what could 2⁰ and 2⁻¹ mean?": { style: 'A', say: "Half a pizza each day. You have 8 pizzas. Each day, half of what is left gets eaten: 8, then 4, then 2. In twos those are 2 cubed, 2 squared, 2 to the first. What comes next, and what could 2 to the zero and 2 to the negative 1 mean?" },
  "Now you try. What is 3⁻²? Write it as a fraction. Start from a value you know. Divide by the base for each step down.": { style: 'A', say: "Now you try. What is 3 to the negative 2? Write it as a fraction. Start from a value you know. Divide by the base for each step down." },
  "Try a new one. What is 4⁻²? Write it as a fraction.": { style: 'A', say: "Try a new one. What is 4 to the negative 2? Write it as a fraction." },
  "What is 3⁰? Start there.": { style: 'A', say: "What is 3 to the zero? Start there." },
  "3⁻¹ = 1/3. Divide by 3 one more time.": { style: 'A', say: "3 to the negative 1 = 1/3. Divide by 3 one more time." },
  "Start at 4⁰. What is it?": { style: 'A', say: "Start at 4 to the zero. What is it?" },
  "You divided by 4 two times and found 4⁻² = 1/16.": { style: 'A', say: "You divided by 4 two times and found 4 to the negative 2 = 1/16." },
  // ── g8m1-t5 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Quick, which is bigger: 150,000,000 or 15,000,000?": { style: 'B' },
  "You had to count the zeros, didn't you?": { style: 'B' },
  "Drop just one zero, and the number is 10 times too small.": { style: 'B' },
  "Write a big number as a number from 1 up to 10 times a power of 10, where the exponent counts the places the point moved.": { style: 'B' },
  "First, make a number from 1 up to 10.": { style: 'B' },
  "Where does the point go? Right after the first digit.": { style: 'B' },
  "So 150,000,000 becomes 1.5.": { style: 'B', say: "So 150,000,000 becomes 1 point 5." },
  "Now count the jumps from the new point to the end.": { style: 'B' },
  "1, 2, 3, 4, 5, 6, 7, 8. That's 8 places, and each jump is × 10.": { style: 'B' },
  "So 150,000,000 = 1.5 × 10⁸.": { style: 'B', say: "So 150,000,000 = 1 point 5 × 10 to the eighth." },
  "Try a smaller one, 4,200.": { style: 'B' },
  "The point goes after the 4, to make 4.2.": { style: 'B', say: "The point goes after the 4, to make 4 point 2." },
  "Then it jumps 3 places to the end, so 4,200 = 4.2 × 10³.": { style: 'B', say: "Then it jumps 3 places to the end, so 4,200 = 4 point 2 × 10 cubed." },
  "Don't count ALL the digits. 150,000,000 has 9 digits, but it is not 1.5 × 10⁹.": { style: 'B+', say: "Don't count all the digits. 150,000,000 has 9 digits, but it is not 1 point 5 × 10 to the ninth." },
  "Count only the digits after the first one. That's 8, so it's 1.5 × 10⁸.": { style: 'B+', say: "Count only the digits after the first one. That's 8, so it's 1 point 5 × 10 to the eighth." },
  "Now you try. 4,500,000 = 4.5 × 10^?. What is the exponent? Make a number from 1 up to 10. Count how many places the point jumps.": { style: 'A', say: "Now you try. 4,500,000 = 4 point 5 × 10 to some power. What is the exponent? Make a number from 1 up to 10. Count how many places the point jumps." },
  "Try a new one. 72,000,000 = 7.2 × 10^?. What is the exponent?": { style: 'A', say: "Try a new one. 72,000,000 = 7 point 2 × 10 to some power. What is the exponent?" },
  "Where does the point go to make 4.5?": { style: 'A', say: "Where does the point go to make 4 point 5?" },
  "You moved the point 7 places: 72,000,000 = 7.2 × 10⁷.": { style: 'A', say: "You moved the point 7 places: 72,000,000 = 7 point 2 × 10 to the seventh." },

}
