/**
 * How g8m1's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G8M1_VOICE: Record<string, VoiceLine> = {
  // ── g8m1-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "You could work it all out. 2³ is 8, 2² is 4, and 8 × 4 = 32.": { style: 'B', say: "You could work it all out. 2 cubed is 8, 2 squared is 4, and 8 × 4 = 32." },
  "Then you hunt for the exponent that makes 32.": { style: 'B' },
  "But what about 2¹⁰ × 2¹⁵? You would be counting all day.": { style: 'B', say: "But what about 2 to the tenth × 2 to the fifteenth? You would be counting all day." },
  "When you multiply two numbers with the same base, keep the base and add the exponents.": { style: 'B' },
  "What does 2³ really mean? Three twos, multiplied together.": { style: 'B', say: "What does 2 cubed really mean? Three twos, multiplied together." },
  "And 2² is two more twos.": { style: 'B', say: "And 2 squared is two more twos." },
  "Line them all up in one long row.": { style: 'B' },
  "Now count them. 3 twos, then 2 more.": { style: 'B' },
  "That makes 5 twos in one row.": { style: 'B' },
  "So 2³ × 2² = 2⁵. The 3 and the 2 added up to 5.": { style: 'B', say: "So 2 cubed × 2 squared = 2 to the fifth. The 3 and the 2 added up to 5." },
  "Does it check out? 2⁵ is 32, the same 32 as before.": { style: 'B', say: "Does it check out? 2 to the fifth is 32, the same 32 as before." },
  "And any base works. 5⁴ × 5³ = 5⁷, because 4 + 3 = 7.": { style: 'B', say: "And any base works. 5 to the fourth × 5 cubed = 5 to the seventh, because 4 + 3 = 7." },
  "Don't MULTIPLY the exponents. 2³ × 2² is not 2⁶.": { style: 'B+', say: "Don't multiply the exponents. 2 cubed × 2 squared is not 2 to the sixth." },
  "Count the twos instead: 3 and 2 more make 5, so it's 2⁵.": { style: 'B+', say: "Count the twos instead: 3 and 2 more make 5, so it's 2 to the fifth." },
  "Now you try. Write 3⁴ × 3² as 3 with one exponent. What is the exponent? Keep the base. Add the exponents.": { style: 'A', say: "Now you try. Write 3 to the fourth × 3 squared as 3 with one exponent. What is the exponent? Keep the base. Add the exponents." },
  "Try a new one. Write 7⁵ × 7³ as 7 with one exponent. What is the exponent?": { style: 'A', say: "Try a new one. Write 7 to the fifth × 7 cubed as 7 with one exponent. What is the exponent?" },
  "You kept the base 7 and added the exponents to get 7⁸.": { style: 'A', say: "You kept the base 7 and added the exponents to get 7 to the eighth." },
  // ── g8m1-t2 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Could you just divide the exponents, 5 ÷ 3?": { style: 'B' },
  "No. 5 ÷ 3 is not even a whole number, so that can't be it.": { style: 'B' },
  "You could work out 32 ÷ 8. But that's no help for 2²⁰ ÷ 2¹⁷.": { style: 'B', say: "You could work out 32 ÷ 8. But that's no help for 2 to the twentieth ÷ 2 to the seventeenth." },
  "When you divide powers with the same base, keep the base and subtract the exponents: top minus bottom.": { style: 'B' },
  "Let's write the division as a fraction.": { style: 'B' },
  "What's on top? Five twos, multiplied.": { style: 'B' },
  "And on the bottom, three twos.": { style: 'B' },
  "Now pair them off. A 2 on top and a 2 on the bottom make 2 ÷ 2, which is 1.": { style: 'B' },
  "Three pairs cancel, and two twos are left on top.": { style: 'B' },
  "That's 5 − 3 = 2, so 2⁵ ÷ 2³ = 2².": { style: 'B', say: "That's 5 − 3 = 2, so 2 to the fifth ÷ 2 cubed = 2 squared." },
  "Check it. 2² is 4, and 32 ÷ 8 is 4 too. So there are 4 teams.": { style: 'B', say: "Check it. 2 squared is 4, and 32 ÷ 8 is 4 too. So there are 4 teams." },
  "Any base works the same way. 7⁶ ÷ 7² = 7⁴, because 6 − 2 = 4.": { style: 'B', say: "Any base works the same way. 7 to the sixth ÷ 7 squared = 7 to the fourth, because 6 − 2 = 4." },
  "Don't DIVIDE the exponents. 2⁶ ÷ 2³ is not 2².": { style: 'B+', say: "Don't divide the exponents. 2 to the sixth ÷ 2 cubed is not 2 squared." },
  "Subtract them instead. 6 − 3 = 3, so it's 2³.": { style: 'B+', say: "Subtract them instead. 6 − 3 = 3, so it's 2 cubed." },
  "Teams for a tournament. A game tournament starts with 2⁵ players. They split into teams of 2³ players each. The number of teams is 2⁵ ÷ 2³. Can you write it as 2 with one exponent?": { style: 'A', say: "Teams for a tournament. A game tournament starts with 2 to the fifth players. They split into teams of 2 cubed players each. The number of teams is 2 to the fifth ÷ 2 cubed. Can you write it as 2 with one exponent?" },
  "Now you try. Write 3⁷ ÷ 3² as 3 with one exponent. What is the exponent? Keep the base. Subtract the bottom exponent from the top one.": { style: 'A', say: "Now you try. Write 3 to the seventh ÷ 3 squared as 3 with one exponent. What is the exponent? Keep the base. Subtract the bottom exponent from the top one." },
  "Try a new one. Write 5⁹ ÷ 5³ as 5 with one exponent. What is the exponent?": { style: 'A', say: "Try a new one. Write 5 to the ninth ÷ 5 cubed as 5 with one exponent. What is the exponent?" },
  "You cancelled the 5s in pairs and had 5⁶ left.": { style: 'A', say: "You cancelled the fives in pairs and had 5 to the sixth left." },
  // ── g8m1-t3 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "You see a 3 and a 2. Should you add them and get 2⁵?": { style: 'B', say: "You see a 3 and a 2. Should you add them and get 2 to the fifth?" },
  "Look at what the outside 2 asks for. Two copies of 2³, multiplied: 2³ × 2³.": { style: 'B', say: "Look at what the outside 2 asks for. Two copies of 2 cubed, multiplied: 2 cubed × 2 cubed." },
  "Count those twos, and there are more than five.": { style: 'B' },
  "When you raise a power to another exponent, keep the base and multiply the exponents.": { style: 'B' },
  "What is the outside 2 counting? Copies.": { style: 'B' },
  "It says write 2³ down two times, and multiply them.": { style: 'B', say: "It says write 2 cubed down two times, and multiply them." },
  "So (2³)² = 2³ × 2³.": { style: 'B', say: "So 2 cubed, all squared, = 2 cubed × 2 cubed." },
  "Now count every 2. Each copy has 3 twos, and there are 2 copies.": { style: 'B' },
  "3 twos, 2 times over, is 3 × 2 = 6 twos.": { style: 'B' },
  "So (2³)² = 2⁶.": { style: 'B', say: "So 2 cubed, all squared, = 2 to the sixth." },
  "Try a bigger one. (5⁴)³ is three copies of 5⁴.": { style: 'B', say: "Try a bigger one. 5 to the fourth, all cubed, is three copies of 5 to the fourth." },
  "That's 4 + 4 + 4 fives, which is 4 × 3 = 12.": { style: 'B' },
  "So (5⁴)³ = 5¹².": { style: 'B', say: "So 5 to the fourth, all cubed, = 5 to the twelfth." },
  "Don't ADD the exponents here. (2³)² is not 2⁵.": { style: 'B+', say: "Don't add the exponents here. 2 cubed, all squared, is not 2 to the fifth." },
  "The outside 2 counts copies, so multiply. 3 × 2 = 6, and it's 2⁶.": { style: 'B+', say: "The outside 2 counts copies, so multiply. 3 × 2 = 6, and it's 2 to the sixth." },
  "A square poster. A square poster is 2³ inches wide and 2³ inches tall. Its area is (2³)² square inches. Can you write that as 2 with one exponent?": { style: 'A', say: "A square poster. A square poster is 2 cubed inches wide and 2 cubed inches tall. Its area is 2 cubed, all squared, square inches. Can you write that as 2 with one exponent?" },
  "Now you try. Write (3²)⁴ as 3 with one exponent. What is the exponent? Keep the base. Multiply the exponents.": { style: 'A', say: "Now you try. Write 3 squared, all to the fourth, as 3 with one exponent. What is the exponent? Keep the base. Multiply the exponents." },
  "Try a new one. Write (7⁵)² as 7 with one exponent. What is the exponent?": { style: 'A', say: "Try a new one. Write 7 to the fifth, all squared, as 7 with one exponent. What is the exponent?" },
  "Two copies of 7⁵: count the 7s in both copies together.": { style: 'A', say: "Two copies of 7 to the fifth: count the sevens in both copies together." },
  "You multiplied the exponents and wrote it as 7¹⁰.": { style: 'A', say: "You multiplied the exponents and wrote it as 7 to the tenth." },
  // ── g8m1-t4 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "What would 2⁰ mean? Zero twos, multiplied together?": { style: 'B', say: "What would 2 to the zero mean? Zero twos, multiplied together?" },
  "And 2⁻¹ would be a negative number of twos. You can't count that.": { style: 'B', say: "And 2 to the negative 1 would be a negative number of twos. You can't count that." },
  "So counting won't help here. We need another way to look at it.": { style: 'B' },
  "Each time the exponent goes down by 1, divide by the base, even past zero.": { style: 'B' },
  "Read the row with me, left to right.": { style: 'B' },
  "Each time the exponent drops by 1, what happens? The value is divided by 2.": { style: 'B' },
  "8 ÷ 2 = 4, and 4 ÷ 2 = 2.": { style: 'B' },
  "Now keep the pattern going, one more step down from 2¹.": { style: 'B', say: "Now keep the pattern going, one more step down from 2 to the first." },
  "2 ÷ 2 = 1, so 2⁰ = 1.": { style: 'B', say: "2 ÷ 2 = 1, so 2 to the zero = 1." },
  "Any other base does the same. 5⁰ is 1 too.": { style: 'B', say: "Any other base does the same. 5 to the zero is 1 too." },
  "One more step down. 1 ÷ 2 = 1/2, so 2⁻¹ = 1/2.": { style: 'B', say: "One more step down. 1 ÷ 2 = 1/2, so 2 to the negative 1 = 1/2." },
  "One more again, and 2⁻² = 1/4.": { style: 'B', say: "One more again, and 2 to the negative 2 = 1/4." },
  "So 2⁻² is 1 divided by 2², which is 1/4.": { style: 'B', say: "So 2 to the negative 2 is 1 divided by 2 squared, which is 1/4." },
  "A negative exponent does NOT make a negative answer.": { style: 'B+' },
  "2⁻² is 1/4, a small number above 0. It is not −4.": { style: 'B+', say: "2 to the negative 2 is 1/4, a small number above 0. It is not −4." },
  "Half a pizza each day. You have 8 pizzas. Each day, half of what is left gets eaten: 8, then 4, then 2. In 2s those are 2³, 2², 2¹. What comes next, and what could 2⁰ and 2⁻¹ mean?": { style: 'A', say: "Half a pizza each day. You have 8 pizzas. Each day, half of what is left gets eaten: 8, then 4, then 2. In twos those are 2 cubed, 2 squared, 2 to the first. What comes next, and what could 2 to the zero and 2 to the negative 1 mean?" },
  "Now you try. What is 3⁻²? Write it as a fraction. Start from a value you know. Divide by the base for each step down.": { style: 'A', say: "Now you try. What is 3 to the negative 2? Write it as a fraction. Start from a value you know. Divide by the base for each step down." },
  "Try a new one. What is 4⁻²? Write it as a fraction.": { style: 'A', say: "Try a new one. What is 4 to the negative 2? Write it as a fraction." },
  "What is 3⁰? Start there.": { style: 'A', say: "What is 3 to the zero? Start there." },
  "3⁻¹ = 1/3. Divide by 3 one more time.": { style: 'A', say: "3 to the negative 1 = 1/3. Divide by 3 one more time." },
  "Start at 4⁰. What is it?": { style: 'A', say: "Start at 4 to the zero. What is it?" },
  "You divided by 4 two times and found 4⁻² = 1/16.": { style: 'A', say: "You divided by 4 two times and found 4 to the negative 2 = 1/16." },
  // ── g8m1-t5 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Quick, which is bigger: 150,000,000 or 15,000,000?": { style: 'B' },
  "You had to count the zeros, didn't you?": { style: 'B' },
  "Drop just one zero, and the number is 10 times too small.": { style: 'B' },
  "Write a big number as a number from 1 up to 10 times a power of 10, where the exponent counts the places the point moved.": { style: 'B' },
  "First, make a number from 1 up to 10.": { style: 'B' },
  "Where does the point go? Right after the first digit.": { style: 'B' },
  "So 150,000,000 becomes 1.5.": { style: 'B', say: "So 150,000,000 becomes 1 point 5." },
  "Now count the jumps from the new point to the end.": { style: 'B' },
  "1, 2, 3, 4, 5, 6, 7, 8. That's 8 places, and each jump is × 10.": { style: 'B' },
  "So 150,000,000 = 1.5 × 10⁸.": { style: 'B', say: "So 150,000,000 = 1 point 5 × 10 to the eighth." },
  "Try a smaller one, 4,200.": { style: 'B' },
  "The point goes after the 4, to make 4.2.": { style: 'B', say: "The point goes after the 4, to make 4 point 2." },
  "Then it jumps 3 places to the end, so 4,200 = 4.2 × 10³.": { style: 'B', say: "Then it jumps 3 places to the end, so 4,200 = 4 point 2 × 10 cubed." },
  "Don't count ALL the digits. 150,000,000 has 9 digits, but it is not 1.5 × 10⁹.": { style: 'B+', say: "Don't count all the digits. 150,000,000 has 9 digits, but it is not 1 point 5 × 10 to the ninth." },
  "Count only the digits after the first one. That's 8, so it's 1.5 × 10⁸.": { style: 'B+', say: "Count only the digits after the first one. That's 8, so it's 1 point 5 × 10 to the eighth." },
  "Now you try. 4,500,000 = 4.5 × 10^?. What is the exponent? Make a number from 1 up to 10. Count how many places the point jumps.": { style: 'A', say: "Now you try. 4,500,000 = 4 point 5 × 10 to some power. What is the exponent? Make a number from 1 up to 10. Count how many places the point jumps." },
  "Try a new one. 72,000,000 = 7.2 × 10^?. What is the exponent?": { style: 'A', say: "Try a new one. 72,000,000 = 7 point 2 × 10 to some power. What is the exponent?" },
  "Where does the point go to make 4.5?": { style: 'A', say: "Where does the point go to make 4 point 5?" },
  "You moved the point 7 places: 72,000,000 = 7.2 × 10⁷.": { style: 'A', say: "You moved the point 7 places: 72,000,000 = 7 point 2 × 10 to the seventh." },

  // ── g8m1-t6 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  // The topic is the WRITTEN form, so a decimal is said digit by digit: "zero point zero zero zero five two".
  "Last time, big numbers got a positive exponent.": { style: 'B' },
  "So could this be 5.2 × 10⁴?": { style: 'B', say: "So could this be five point two times 10 to the fourth?" },
  "No. That is 52,000, and this grain is smaller than 1.": { style: 'B', say: "No. That is 52 thousand, and this grain is smaller than 1." },
  "The exponent has to do something new.": { style: 'B' },
  "For a number smaller than 1, the point moves right to make a number from 1 up to 10, and the exponent is the number of jumps, made negative.": { style: 'B' },
  "Start at 0.00052 and move the point to the right.": { style: 'B', say: "Start at zero point zero zero zero five two, and move the point to the right." },
  "Stop just after the 5, the first digit that is not a zero. Now it reads 5.2.": { style: 'B', say: "Stop just after the 5, the first digit that is not a zero. Now it reads five point two." },
  "How many jumps was that? Count them: 1, 2, 3, 4.": { style: 'B', say: "How many jumps was that? Count them. 1, 2, 3, 4." },
  "Now go back the other way.": { style: 'B' },
  "From 5.2, divide by 10 four times and you are back at 0.00052.": { style: 'B', say: "From five point two, divide by 10 four times, and you are back at zero point zero zero zero five two." },
  "Each ÷ 10 is the same as × 10⁻¹, so four of them make × 10⁻⁴.": { style: 'B', say: "Each divide by 10 is the same as times 10 to the negative 1, so four of them make times 10 to the negative 4." },
  "So 0.00052 = 5.2 × 10⁻⁴.": { style: 'B', say: "So zero point zero zero zero five two equals five point two times 10 to the negative 4." },
  "Here is a shorter one: 0.03.": { style: 'B', say: "Here is a shorter one. Zero point zero three." },
  "The point jumps 2 places right to make 3.": { style: 'B' },
  "So 0.03 = 3 × 10⁻².": { style: 'B', say: "So zero point zero three equals 3 times 10 to the negative 2." },
  "Don't count ONLY the zeros after the point.": { style: 'B+' },
  "0.00052 has 3 of them, but the point jumps 4 places to land past the 5.": { style: 'B+', say: "Zero point zero zero zero five two has 3 of them, but the point jumps 4 places to land past the 5." },
  "A grain of pollen. A grain of pollen is about 0.00052 meters wide. That is a lot of zeros on the other side of the point. Can you write it the short way, like 1.5 × 10⁸?": { style: 'A', say: "A grain of pollen. A grain of pollen is about zero point zero zero zero five two meters wide. That is a lot of zeros on the other side of the point. Can you write it the short way, like one point five times 10 to the eighth?" },
  "Now you try. 0.0007 = 7 × 10^?. What is the exponent? Move the point right to make a number from 1 up to 10. Count the jumps, and make it negative.": { style: 'A', say: "Now you try. Zero point zero zero zero seven equals 7 times 10 to the what? What is the exponent? Move the point right to make a number from 1 up to 10. Count the jumps, and make it negative." },
  "Try a new one. 0.000061 = 6.1 × 10^?. What is the exponent?": { style: 'A', say: "Try a new one. Zero point zero zero zero zero six one equals six point one times 10 to the what? What is the exponent?" },
  "Move the point right. Where must it stop to make 6.1?": { style: 'A', say: "Move the point right. Where must it stop to make six point one?" },
  "You moved the point 5 places to make 6.1, so the exponent is −5.": { style: 'A', say: "You moved the point 5 places to make six point one, so the exponent is negative 5." },
  // ── g8m1-t7 ──
  "You could write these out the long way, 30,000 × 2,000, and count the zeros.": { style: 'B', say: "You could write these out the long way, 30 thousand times 2 thousand, and count the zeros." },
  "That works for small ones.": { style: 'B' },
  "But what about 3 × 10²¹? That is 21 zeros to write before you even start.": { style: 'B', say: "But what about 3 times 10 to the twenty-first? That is 21 zeros to write before you even start." },
  "Multiply the front numbers and add the exponents of 10, and if the front number comes out 10 or more, move its point one place and add 1 to the exponent.": { style: 'B' },
  "When you multiply, the order does not matter.": { style: 'B' },
  "So put the front numbers together, and the powers of 10 together.": { style: 'B' },
  "Then 3 × 2 = 6.": { style: 'B' },
  "Now the powers of 10.": { style: 'B' },
  "They have the same base, so add the exponents: 4 + 3 = 7.": { style: 'B' },
  "That makes 10⁷. So the warehouse holds 6 × 10⁷ screws.": { style: 'B', say: "That makes 10 to the seventh. So the warehouse holds 6 times 10 to the seventh screws." },
  "Now try (4 × 10⁵) × (5 × 10²).": { style: 'B', say: "Now try 4 times 10 to the fifth, times 5 times 10 squared." },
  "4 × 5 = 20, and 10⁵ × 10² = 10⁷.": { style: 'B', say: "4 times 5 equals 20, and 10 to the fifth times 10 squared equals 10 to the seventh." },
  "But is 20 under 10? No, so we are not done.": { style: 'B' },
  "20 is 2 × 10¹, so that extra 10 joins the others, and the answer is 2 × 10⁸.": { style: 'B', say: "20 is 2 times 10 to the first, so that extra 10 joins the others, and the answer is 2 times 10 to the eighth." },
  "Don't STOP at 20 × 10⁷.": { style: 'B+', say: "Don't stop at 20 times 10 to the seventh." },
  "It has the right value, but the front number has to be under 10. Write it as 2 × 10⁸.": { style: 'B+', say: "It has the right value, but the front number has to be under 10. Write it as 2 times 10 to the eighth." },
  "Boxes of screws. A warehouse has 3 × 10⁴ boxes. Each box holds 2 × 10³ screws. How many screws are there in all?": { style: 'A', say: "Boxes of screws. A warehouse has 3 times 10 to the fourth boxes. Each box holds 2 times 10 cubed screws. How many screws are there in all?" },
  "Now you try. (3 × 10⁵) × (3 × 10²) = 9 × 10^?. What is the exponent? Multiply the front numbers. Add the exponents of 10.": { style: 'A', say: "Now you try. 3 times 10 to the fifth, times 3 times 10 squared, equals 9 times 10 to the what? What is the exponent? Multiply the front numbers. Add the exponents of 10." },
  "Try a new one. (2 × 10⁶) × (4 × 10³) = 8 × 10^?. What is the exponent?": { style: 'A', say: "Try a new one. 2 times 10 to the sixth, times 4 times 10 cubed, equals 8 times 10 to the what? What is the exponent?" },
  "The front numbers make 9. What do you do with 10⁵ and 10²?": { style: 'A', say: "The front numbers make 9. What do you do with 10 to the fifth and 10 squared?" },
  "You added the exponents of 10 and got 8 × 10⁹.": { style: 'A', say: "You added the exponents of 10 and got 8 times 10 to the ninth." },
  // ── g8m1-t8 ── (12.5 is how much, so it is said as a value: "twelve and a half")
  "Dividing feels like the obvious move. Half of 25 is 12.5.": { style: 'B', say: "Dividing feels like the obvious move. Half of 25 is twelve and a half." },
  "But could the patio be 12.5 tiles long?": { style: 'B', say: "But could the patio be twelve and a half tiles long?" },
  "No. 12.5 rows of 12.5 tiles is far more than 25.": { style: 'B', say: "No. Twelve and a half rows of twelve and a half tiles is far more than 25." },
  "What we need is a number that multiplies with itself.": { style: 'B' },
  "To undo squaring, find the number that times itself makes it, and to undo cubing, find the number that, used three times, makes it.": { style: 'B' },
  "Start with the patio. It is a square, so side times side makes 25.": { style: 'B' },
  "5 × 5 = 25, so the side is 5 tiles.": { style: 'B' },
  "We write that as √25 = 5.": { style: 'B' },
  "Now the box. It is a cube, so side times side times side makes 27.": { style: 'B' },
  "3 × 3 × 3 = 27, so the side is 3 cubes.": { style: 'B' },
  "This one gets a small 3 on the sign: ∛27 = 3.": { style: 'B', say: "This one gets a small 3 on the sign. The cube root of 27 equals 3." },
  "Is there a faster way? Yes. Know your squares and cubes by heart.": { style: 'B' },
  "16 is 4 × 4, so √16 = 4.": { style: 'B' },
  "And 64 is 4 × 4 × 4, so ∛64 = 4.": { style: 'B', say: "And 64 is 4 times 4 times 4, so the cube root of 64 equals 4." },
  "Don't DIVIDE by 2 to find √36.": { style: 'B+' },
  "36 ÷ 2 is 18, and 18 × 18 is far more than 36. 6 × 6 = 36, so √36 = 6.": { style: 'B+' },
  // ── g8m1-t9 ── (4.5 is how much: "four and a half")
  "Try whole numbers first. 4 × 4 = 16, and that is too small.": { style: 'B' },
  "5 × 5 = 25, and that is too big.": { style: 'B' },
  "So which whole number times itself makes 20? None of them. We have to close in on it.": { style: 'B' },
  "Find the perfect squares just below and just above the number, and the square root sits between their roots, nearer the closer square.": { style: 'B' },
  "Which perfect squares sit on each side of 20? They are 16 and 25.": { style: 'B' },
  "So √20 is between √16 = 4 and √25 = 5.": { style: 'B', say: "So the square root of 20 is between the square root of 16, which is 4, and the square root of 25, which is 5." },
  "Now measure the two gaps. 20 is 4 away from 16, but 5 away from 25.": { style: 'B' },
  "It is closer to 16, so √20 is closer to 4.": { style: 'B' },
  "Let's check. Halfway between 4 and 5 is 4.5.": { style: 'B', say: "Let's check. Halfway between 4 and 5 is four and a half." },
  "4.5 × 4.5 = 20.25, a little more than 20.": { style: 'B', say: "Four and a half times four and a half is twenty and a quarter, a little more than 20." },
  "So √20 is just under 4.5, nearer to 4.": { style: 'B', say: "So the square root of 20 is just under four and a half, nearer to 4." },
  "Don't HALVE the number.": { style: 'B+' },
  "√20 is not 10, because 10 × 10 = 100. Look for the perfect squares around 20 instead.": { style: 'B+' },
}
