/**
 * How g8m2's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G8M2_VOICE: Record<string, VoiceLine> = {
  // ── g8m2-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "So how steep is it? You could say quite steep.": { style: 'B' },
  "But nobody can build a ramp from quite steep. We need a number.": { style: 'B' },
  "And the line goes on forever, so its height can't tell us.": { style: 'B' },
  "Go across from one point and up to the next, then divide how far up you went, the rise, by how far across, the run.": { style: 'B' },
  "Start at the point (1, 1).": { style: 'B', say: "Start at the point 1, 1." },
  "Walk right until you are straight under (3, 4).": { style: 'B', say: "Walk right until you are straight under the point 3, 4." },
  "How far did you walk? 2 across. That is the run.": { style: 'B' },
  "Now climb straight up to (3, 4).": { style: 'B', say: "Now climb straight up to the point 3, 4." },
  "You went 3 up. That is the rise.": { style: 'B' },
  "Now divide, with the rise on top. 3 ÷ 2 is 3/2.": { style: 'B' },
  "Does every stair agree? Take the next one, 2 across and 3 up again.": { style: 'B' },
  "So the line is 3/2 steep everywhere. For every 2 across, it climbs 3.": { style: 'B' },
  "Don't turn it UPSIDE DOWN. 2 ÷ 3 is 2/3, a gentler ramp than this one.": { style: 'B+' },
  "Up goes on top. Rise ÷ run, so 3 ÷ 2.": { style: 'B+' },
  "Now you try. The line goes through (2, 1) and (4, 7). How steep is it? Find rise ÷ run. Count across, then up. Divide the up by the across.": { style: 'A', say: "Now you try. The line goes through the points 2, 1 and 4, 7. How steep is it? Find rise divided by run. Count across, then up. Divide the up by the across." },
  "Try a new one. The line goes through (1, 3) and (5, 6). How steep is it? Find rise ÷ run.": { style: 'A', say: "Try a new one. The line goes through the points 1, 3 and 5, 6. How steep is it? Find rise divided by run." },
  "From (2, 1), how far across do you go to be straight under (4, 7)?": { style: 'A', say: "From the point 2, 1, how far across do you go to be straight under the point 4, 7?" },
  "Now how far up is it to (4, 7)? Put that number on top.": { style: 'A', say: "Now how far up is it to the point 4, 7? Put that number on top." },
  "How far across is it from (1, 3) to (5, 6)? How far up?": { style: 'A', say: "How far across is it from the point 1, 3 to the point 5, 6? How far up?" },
  // ── g8m2-t2 ──
  "Last time you counted squares, across and then up.": { style: 'B' },
  "Here there is no grid at all. So what do you count?": { style: 'B' },
  "Nothing. But the numbers already say how far apart the points are.": { style: 'B' },
  "Subtract the two y-values, then the two x-values in the same order, and divide the first answer by the second.": { style: 'B' },
  "The two y-values are 3 and 11.": { style: 'B' },
  "Start with Point 2. 11 − 3 = 8.": { style: 'B' },
  "The points are 8 apart going up. That is the rise.": { style: 'B' },
  "Now the x-values, 2 and 6.": { style: 'B' },
  "Point 2 first again. 6 − 2 = 4.": { style: 'B' },
  "Same order, top and bottom. That 4 is the run.": { style: 'B' },
  "Now divide the rise by the run. 8 ÷ 4 = 2.": { style: 'B' },
  "So the path climbs 2 for every 1 across.": { style: 'B' },
  "If the y-values went down instead, the top would come out negative, and so would the answer. That line goes downhill.": { style: 'B' },
  "Don't FLIP the order halfway. 11 − 3 on top, then 2 − 6 on the bottom, gives −2.": { style: 'B+' },
  "That says downhill, but this path climbs. Point 2 first on top means Point 2 first on the bottom.": { style: 'B+' },
  "Two points, no grid. A map app gives you just two points on a straight path: (2, 3) and (6, 11). There is no graph. What is the slope of the path?": { style: 'A', say: "Two points, no grid. A map app gives you just two points on a straight path, the point 2, 3 and the point 6, 11. There is no graph. What is the slope of the path?" },
  "Now you try. A line goes through (1, 4) and (5, 16). What is its slope? Subtract the y-values, then the x-values in the same order. Divide.": { style: 'A', say: "Now you try. A line goes through the points 1, 4 and 5, 16. What is its slope? Subtract the y-values, then the x-values in the same order. Divide." },
  "Try a new one. A line goes through (1, 9) and (4, 3). What is its slope?": { style: 'A', say: "Try a new one. A line goes through the points 1, 9 and 4, 3. What is its slope?" },
  // ── g8m2-t3 ──
  "The equation has two numbers, 2 and 1, side by side.": { style: 'B' },
  "On the graph they do two different jobs. Which is which?": { style: 'B' },
  "Let's find each one on the line.": { style: 'B' },
  "In y = mx + b, the number in front of x is the slope, and the plain number b is where the line crosses the y-axis.": { style: 'B', say: "In y equals m x plus b, the number in front of x is the slope, and the plain number b is where the line crosses the y-axis." },
  "Try x = 0. That is the moment you get in, before any miles.": { style: 'B' },
  "2 × 0 is 0, so you are left with 1.": { style: 'B' },
  "So the line crosses the y-axis at (0, 1). That is the $1 to get in.": { style: 'B', say: "So the line crosses the y-axis at the point 0, 1. That is the 1 dollar to get in." },
  "Now step along the line. What happens for each 1 across?": { style: 'B' },
  "It climbs 2. From (0, 1) to (1, 3), then to (2, 5).": { style: 'B', say: "It climbs 2. From the point 0, 1 to the point 1, 3, then to the point 2, 5." },
  "So the slope is 2, the $2 for each mile.": { style: 'B' },
  "Now you can read any equation this way.": { style: 'B' },
  "y = 3x + 4 climbs 3 each step and crosses at 4.": { style: 'B', say: "y equals 3 x plus 4 climbs 3 each step and crosses at 4." },
  "And y = x + 5? A lone x means 1x, so it climbs 1 and crosses at 5.": { style: 'B', say: "And y equals x plus 5? A lone x means 1 x, so it climbs 1 and crosses at 5." },
  "Don't SWAP the two jobs. In y = 2x + 1 the line does not cross at 2.": { style: 'B+', say: "Don't swap the two jobs. In y equals 2 x plus 1 the line does not cross at 2." },
  "The number stuck to x is the slope, 2. The plain number is the crossing, 1.": { style: 'B+' },
  "You found the plain number in y = −2x + 7: the line crosses at 7.": { style: 'A', say: "You found the plain number in y equals negative 2 x plus 7. The line crosses at 7." },
  // ── g8m2-t4 ──
  "You could work out y for x = 0, then 1, then 2, and keep going.": { style: 'B' },
  "That works, but it's slow. Is there a faster way? Yes.": { style: 'B' },
  "The equation already tells you where to start, and how to step.": { style: 'B' },
  "Put the first dot at b on the y-axis, then step by the slope again and again, across the bottom number and up the top number.": { style: 'B' },
  "In y = 2x + 3, the plain number is 3.": { style: 'B', say: "In y equals 2 x plus 3, the plain number is 3." },
  "So the first dot goes at (0, 3), right on the y-axis.": { style: 'B', say: "So the first dot goes at the point 0, 3, right on the y-axis." },
  "That is the plant before any weeks have passed, 3 cm tall.": { style: 'B' },
  "The slope is 2. That means 2 up for every 1 across.": { style: 'B' },
  "So from (0, 3), go 1 across and 2 up. You land on (1, 5).": { style: 'B', say: "So from the point 0, 3, go 1 across and 2 up. You land on the point 1, 5." },
  "Step again the same way. Now you are at (2, 7).": { style: 'B', say: "Step again the same way. Now you are at the point 2, 7." },
  "Now draw one straight line through the dots.": { style: 'B' },
  "Is (2, 7) really on it? Put x = 2 into the equation.": { style: 'B', say: "Is the point 2, 7 really on it? Put x equals 2 into the equation." },
  "2 × 2 + 3 = 7. Yes, it matches.": { style: 'B' },
  "Don't start at the SLOPE. (0, 2) is not where y = 2x + 3 begins.": { style: 'B+', say: "Don't start at the slope. The point 0, 2 is not where y equals 2 x plus 3 begins." },
  "The first dot goes at the plain number, (0, 3). The 2 is only for stepping.": { style: 'B+', say: "The first dot goes at the plain number, the point 0, 3. The 2 is only for stepping." },
  // ── g8m2-t5 ──
  "Before, x was only ever on one side.": { style: 'B' },
  "Now there are bags on both sides. Which bags do you undo first?": { style: 'B' },
  "Taking off loose marbles won't help yet. The bags are still on both sides.": { style: 'B' },
  "Take the smaller x part off both sides, so x is on one side only, and then solve what is left.": { style: 'B' },
  "The right side has fewer bags, 3. So take 3x off both sides.": { style: 'B', say: "The right side has fewer bags, 3. So take 3 x off both sides." },
  "Same off each side, so the scale stays level.": { style: 'B' },
  "5 bags take away 3 bags leaves 2 bags. Now it reads 2x + 2 = 10.": { style: 'B', say: "5 bags take away 3 bags leaves 2 bags. Now it reads 2 x plus 2 equals 10." },
  "Now it looks like the ones you know.": { style: 'B' },
  "Take the 2 loose marbles off both sides. 2x = 8.": { style: 'B', say: "Take the 2 loose marbles off both sides. 2 x equals 8." },
  "Split 8 between the 2 bags. One bag holds 4 marbles, so x = 4.": { style: 'B' },
  "Does 4 really work? Put 4 in for x on both sides.": { style: 'B' },
  "Left, 5 × 4 + 2 = 22. Right, 3 × 4 + 10 = 22.": { style: 'B' },
  "Both 22. The scale balances, so x = 4 is right.": { style: 'B' },
  "Don't ADD 5x and 3x across the equals sign. That makes 8x, and the scale tips.": { style: 'B+', say: "Don't add 5 x and 3 x across the equals sign. That makes 8 x, and the scale tips." },
  "Take 3x off BOTH sides instead. 5x + 2 = 3x + 10 becomes 2x + 2 = 10.": { style: 'B+', say: "Take 3 x off both sides instead. 5 x plus 2 equals 3 x plus 10 becomes 2 x plus 2 equals 10." },
}
