/**
 * How g8m2's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G8M2_VOICE: Record<string, VoiceLine> = {
  // ── g8m2-t6 ── ("Here's the part people mix up.", "Okay. Your turn." and "Is there a faster way? Yes." have rows elsewhere)
  "Try some hours. At 1 hour it is $5 and $7.": { style: 'B' },
  "At 10 hours it is $23 and $25.": { style: 'B' },
  "Shop B is always $2 more. So will they ever cost the same?": { style: 'B' },
  "Take the x parts off both sides, then read what is left: an x means one answer, something never true means none, and something always true means every number works.": { style: 'B' },
  "Take 2x off both sides and watch.": { style: 'B', say: "Take 2 x off both sides and watch." },
  "Every x is gone, and what is left is 3 = 5.": { style: 'B' },
  "Is 3 ever equal to 5? Never, for any number of hours.": { style: 'B' },
  "So there is no answer. The two prices never meet.": { style: 'B' },
  "Now try 2(x + 3) = 2x + 6.": { style: 'B', say: "Now try 2 times x plus 3, all together, equals 2 x plus 6." },
  "Multiply out the parentheses. The left side becomes 2x + 6 too.": { style: 'B', say: "Multiply out the parentheses. The left side becomes 2 x + 6 too." },
  "Take 2x off both sides, and you get 6 = 6.": { style: 'B', say: "Take 2 x off both sides, and you get 6 = 6." },
  "Is that ever false? No. So every number works.": { style: 'B' },
  "Now the usual kind: 3x + 1 = 2x + 5.": { style: 'B', say: "Now the usual kind: 3 x + 1 = 2 x + 5." },
  "Take 2x off both sides. This time an x is still there: x + 1 = 5.": { style: 'B', say: "Take 2 x off both sides. This time an x is still there: x + 1 = 5." },
  "Take 1 off both sides, and x = 4.": { style: 'B' },
  "The x stayed, so exactly one number fits.": { style: 'B' },
  "When the x parts vanish and leave 6 = 6, that does NOT mean x = 0.": { style: 'B+' },
  "It is always true, so every number works.": { style: 'B+' },
  // ── g8m2-t7 ── ("Here's the part people mix up.", "Okay. Your turn." and "Is there a faster way? Yes." have rows elsewhere)
  "You could list each walker, minute by minute, and keep comparing.": { style: 'B' },
  "But what you really want is one x and one y that fit both rules. Where do you find that?": { style: 'B' },
  "The point where two lines cross sits on both lines, so its x and y make both equations true at once.": { style: 'B' },
  "Follow the two lines with your finger until they meet.": { style: 'B' },
  "Then look straight down from that point.": { style: 'B' },
  "It sits right above x = 2.": { style: 'B' },
  "Now look straight across to the side.": { style: 'B' },
  "The crossing is at y = 4. So the point is (2, 4).": { style: 'B', say: "The crossing is at y equals 4. So the point is 2, 4." },
  "After 2 minutes, both walkers are 4 blocks from home.": { style: 'B' },
  "Does (2, 4) really fit both rules? Check each one.": { style: 'B', say: "Does the point 2, 4 really fit both rules? Check each one." },
  "Ana: 2 + 2 = 4. Ben: −2 + 6 = 4.": { style: 'B', say: "For Ana, 2 plus 2 equals 4. For Ben, negative 2 plus 6 equals 4." },
  "Both give 4, so the point fits both at once.": { style: 'B' },
  "A point on just ONE line is not enough. (1, 3) is on Ana's line.": { style: 'B+', say: "A point on just one line is not enough. The point 1, 3 is on Ana's line." },
  "But Ben's rule gives 5 there, not 3. Only the crossing fits both.": { style: 'B+' },
  // ── g8m2-t8 ── ("Here's the part people mix up.", "Okay. Your turn." and "Is there a faster way? Yes." have rows elsewhere)
  "Look at clue 2 on its own: x + y = 12.": { style: 'B' },
  "Lots of pairs fit it: 1 and 11, 5 and 7, 6 and 6.": { style: 'B' },
  "So which pair is it? One clue alone can't tell you.": { style: 'B' },
  "When one equation tells you what y equals, write that in place of y in the other one, so only x is left to solve.": { style: 'B' },
  "Clue 1 says y is the same as 2x.": { style: 'B', say: "Clue 1 says y is the same as 2 x." },
  "So wherever you see y, you can write 2x instead.": { style: 'B', say: "So wherever you see y, you can write 2 x instead." },
  "Clue 2 becomes x + 2x = 12, with only one letter left.": { style: 'B', say: "Clue 2 becomes x + 2 x = 12, with only one letter left." },
  "An x plus 2 more x makes 3x.": { style: 'B', say: "An x plus 2 more x makes 3 x." },
  "So 3x = 12. What times 3 gives 12?": { style: 'B', say: "So 3 x = 12. What times 3 gives 12?" },
  "It is 4. So x = 4.": { style: 'B' },
  "You are not done yet. You still need y.": { style: 'B' },
  "Clue 1 says y = 2x, so y = 2 × 4 = 8.": { style: 'B', say: "Clue 1 says y equals 2 x, so y equals 2 times 4, which is 8." },
  "Check it in clue 2. 4 + 8 = 12, so both clues work.": { style: 'B' },
  "The 2x goes where the y was. Do NOT put it where the x was.": { style: 'B+', say: "The 2 x goes where the y was. Do NOT put it where the x was." },
  "So x + y = 12 becomes x + 2x = 12, never 2x + y = 12.": { style: 'B+', say: "So x + y = 12 becomes x + 2 x = 12, never 2 x + y = 12." },
  // ── g8m2-t9 ── ("Here's the part people mix up.", "Okay. Your turn." and "Is there a faster way? Yes." have rows elsewhere)
  "You don't know the adult tickets, and you don't know the kid tickets.": { style: 'B' },
  "You could guess pairs that make 10 and check each cost. That works, but it is slow.": { style: 'B' },
  "Give each unknown its own letter, write one equation for each fact in the story, and solve them together.": { style: 'B' },
  "Let a be the adult tickets, and k the kid tickets.": { style: 'B' },
  "Fact one, 10 tickets in all: a + k = 10.": { style: 'B', say: "Fact one, 10 tickets in all. a plus k equals 10." },
  "Fact two, $32 in all: 5a + 2k = 32.": { style: 'B', say: "Fact two, 32 dollars in all. 5 a plus 2 k equals 32." },
  "Start with the easier one. If a + k = 10, then k = 10 − a.": { style: 'B' },
  "Put 10 − a in place of k in the money equation.": { style: 'B' },
  "That gives 5a + 2(10 − a) = 32, or 5a + 20 − 2a = 32.": { style: 'B', say: "That gives 5 a plus 2 times 10 minus a, all together, equals 32. That is 5 a plus 20 minus 2 a equals 32." },
  "Tidy it up: 3a + 20 = 32. Take 20 off both sides, and 3a = 12.": { style: 'B', say: "Tidy it up: 3 a + 20 = 32. Take 20 off both sides, and 3 a = 12." },
  "So a = 4. That is 4 adult tickets and 6 kid tickets.": { style: 'B' },
  "Check the money: $20 + $12 = $32. It fits.": { style: 'B' },
  "Don't mix tickets and dollars in ONE equation.": { style: 'B+' },
  "a + k counts tickets, so it equals 10, not 32. The dollars get their own equation.": { style: 'B+' },
  // ── outside the teach (Screen 1, the question, the win) — style A, math said in words ──
  "Try a new one. How many solutions does 3(x + 2) = 3x + 6 have?": { style: 'A', say: "Try a new one. How many solutions does 3 times x plus 2, all together, equal 3 x plus 6 have?" },
  "Both sides of 3(x + 2) = 3x + 6 are the same, so every number works.": { style: 'A', say: "Both sides of 3 times x plus 2, all together, and 3 x plus 6 are the same, so every number works." },
  "Two walkers. Ana starts 2 blocks from home and walks away 1 block each minute: y = x + 2. Ben starts 6 blocks away and walks toward home 1 block each minute: y = −x + 6. When are they at the same place?": { style: 'A', say: "Two walkers. Ana starts 2 blocks from home and walks away 1 block each minute, so y equals x plus 2. Ben starts 6 blocks away and walks toward home 1 block each minute, so y equals negative x plus 6. When are they at the same place?" },
  "Now you try. The lines y = x + 1 and y = −x + 7 cross at one point. What is the x-value of that point? Find where the lines meet. Check the point in both equations.": { style: 'A', say: "Now you try. The lines y equals x plus 1 and y equals negative x plus 7 cross at one point. What is the x-value of that point? Find where the lines meet. Check the point in both equations." },
  "Two clues. A number puzzle has two clues. Clue 1: y is 2 times x. Clue 2: x and y add up to 12. What are x and y?": { style: 'A', say: "Two clues. A number puzzle has two clues. Clue 1 says y is 2 times x. Clue 2 says x and y add up to 12. What are x and y?" },
}
