/**
 * How g8m3's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 * Algebra: a number next to a letter ("8x") is said "8 x".
 */
import type { VoiceLine } from './styles'

export const G8M3_VOICE: Record<string, VoiceLine> = {
  // ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  // ── g8m3-t1 ──
  "Look at this table.": { style: 'B' },
  "You might hunt for a pattern, like outputs that go up.": { style: 'B' },
  "There isn't one. 5, 2, 9, 2.": { style: 'B' },
  "So is this table broken? No. The real question is much simpler than a pattern.": { style: 'B' },
  "A function gives each input exactly one output, so one input with two different outputs breaks it.": { style: 'B' },
  "Walk the inputs one at a time.": { style: 'B' },
  "Input 1 gives 3. Input 2 gives 5.": { style: 'B' },
  "Input 3 gives 7, and input 4 gives 9.": { style: 'B' },
  "Every input shows up once, with one output. So this table is a function.": { style: 'B' },
  "Now watch this one.": { style: 'B' },
  "Input 2 shows up twice.": { style: 'B' },
  "Once it gives 6, and once it gives 8.": { style: 'B' },
  "That is button A giving chips today and a cookie tomorrow. Not a function.": { style: 'B' },
  "Here is one that looks strange. Every input gives 5.": { style: 'B' },
  "Is that allowed? Yes. Two buttons can give you the same snack.": { style: 'B' },
  "Each input still has just one output, so this is a function.": { style: 'B' },
  "Don't call it \"not a function\" just because an OUTPUT repeats.": { style: 'B+' },
  "Only one INPUT with two different outputs breaks the rule.": { style: 'B+' },
  // ── g8m3-t2 ──
  "You drop in 4. Can you just look and know what comes out?": { style: 'B' },
  "No. The machine does not guess, and neither can you.": { style: 'B' },
  "You have to follow its rule, step by step, in the right order.": { style: 'B' },
  "Put the input into the rule, then multiply before you add or subtract, and that gives the output.": { style: 'B' },
  "Our input is 4.": { style: 'B' },
  "So wherever the rule says input, we write a 4 instead.": { style: 'B' },
  "That gives us 3 × 4 − 2.": { style: 'B' },
  "Which comes first, the times or the minus?": { style: 'B' },
  "Multiply first. 3 × 4 = 12.": { style: 'B' },
  "Then take away the 2. 12 − 2 = 10.": { style: 'B' },
  "So when 4 goes in, 10 comes out.": { style: 'B' },
  "People write this same rule a shorter way.": { style: 'B' },
  "It looks like f(x) = 3x − 2.": { style: 'B', say: "It looks like f of x equals 3 x minus 2." },
  "The x is the input, and 3x means 3 × x.": { style: 'B', say: "The x is the input, and 3 x means 3 times x." },
  "So f(4) asks for the output when 4 goes in, and we already found it: 10.": { style: 'B', say: "So f of 4 asks for the output when 4 goes in, and we already found it, 10." },
  "Don't SUBTRACT before you multiply.": { style: 'B+' },
  "3 × 4 − 2 is not 3 × 2. Multiply 3 × 4 first, then take away the 2.": { style: 'B+' },
  // outside the teach (Screen 8, hints, Screen 9): only the lines speakable() cannot say
  "Try a new one. f(x) = 2x + 5. What is f(7)?": { style: 'A', say: "Try a new one. f of x equals 2 x plus 5. What is f of 7?" },
  "f(7) means the input is 7. Where does the 7 go?": { style: 'A', say: "f of 7 means the input is 7. Where does the 7 go?" },
  "You put 7 in place of x in 2x + 5 and found f(7) = 19.": { style: 'A', say: "You put 7 in place of x in 2 x plus 5 and found f of 7 equals 19." },
  // ── g8m3-t3 ──
  "Look at both tables.": { style: 'B' },
  "Plant A gets taller every week. So does Plant B.": { style: 'B' },
  "So does going up tell them apart? No.": { style: 'B' },
  "What matters is how much each one grows every week.": { style: 'B' },
  "When x goes up in equal steps and y changes by the same amount every step, the points make a straight line.": { style: 'B' },
  "Start with Plant A. Each week, x goes up 1.": { style: 'B' },
  "The height goes 1, 3, 5, 7.": { style: 'B' },
  "That is up 2, up 2, up 2, the same step every time.": { style: 'B' },
  "Plot those points, and they sit on one straight line.": { style: 'B' },
  "Now Plant B. It goes 0, 1, 4, 9.": { style: 'B' },
  "Is that the same step each week? No.": { style: 'B' },
  "It goes up 1, then up 3, then up 5, so the points bend upward.": { style: 'B' },
  "Plant A grew by the same amount every week, so its points make a straight line.": { style: 'B' },
  "A table like that has a name.": { style: 'B' },
  "We call it linear. Plant B is not linear.": { style: 'B' },
  "Don't compare the y changes before you CHECK the x steps.": { style: 'B+' },
  "If x goes up 1 and then up 2, y should go up twice as far the second time. That is still a straight line.": { style: 'B+' },
  // ── g8m3-t4 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  'Look. One is a table, and one is a rule.': { style: 'B' },
  'Ava starts with $10, and Ben starts with only $2.': { style: 'B' },
  'Does that mean Ava grows faster? Not yet. Where you start is not how fast you grow.': { style: 'B' },
  'For each one, find how much it goes up for every 1 step in x, and the bigger number grows faster.': { style: 'B' },
  'Take Ava first. Her savings go 10, 16, 22, 28, one week at a time.': { style: 'B' },
  'How much is each step? 16 − 10 = 6, and every step is 6.': { style: 'B' },
  'So Ava goes up $6 a week.': { style: 'B' },
  'Now Ben. His rule is y = 8x + 2.': { style: 'B', say: 'Now Ben. His rule is y equals 8 x plus 2.' },
  'Try weeks 0, 1 and 2. He has $2, then $10, then $18.': { style: 'B' },
  'Each week adds 8 more, the same 8 that sits in front of x.': { style: 'B' },
  'So Ben goes up $8 a week.': { style: 'B' },
  'Now put the two side by side. Ava goes up 6 a week, and Ben goes up 8.': { style: 'B' },
  'Which is bigger? 8 is more than 6.': { style: 'B' },
  'So Ben grows faster, even though Ava started with more.': { style: 'B' },
  "Don't pick the one that STARTS higher.": { style: 'B+' },
  "The + 2 in Ben's rule is where he starts. The 8 in front of x is how fast he grows.": { style: 'B+' },
  'Two savings jars. Ava shows her savings in a table. Ben tells you his rule: y = 8x + 2, where x is the number of weeks. Whose savings grow faster?': { style: 'A', say: 'Two savings jars. Ava shows her savings in a table. Ben tells you his rule, y equals 8 x plus 2, where x is the number of weeks. Whose savings grow faster?' },
  'Now you try. Function A is the table. Function B is y = 3x + 10. Which grows faster? Find how much each one goes up for each 1 in x. Compare the two numbers.': { style: 'A', say: 'Now you try. Function A is the table. Function B is y equals 3 x plus 10. Which grows faster? Find how much each one goes up for each 1 in x. Compare the two numbers.' },
  'Try a new one. Function A is y = 2x + 9. Function B is the table. Which grows faster?': { style: 'A', say: 'Try a new one. Function A is y equals 2 x plus 9. Function B is the table. Which grows faster?' },
  'The table went up by more than the 2 in 2x + 9, so function B grows faster.': { style: 'A', say: 'The table went up by more than the 2 in 2 x plus 9, so function B grows faster.' },
  // ── g8m3-t5 ──
  'You could add $10 again and again. 35, 45, 55, and on it goes.': { style: 'B' },
  'But what about 24 months? That is a very long list.': { style: 'B' },
  'Is there a faster way? Yes. One rule can do it in one line.': { style: 'B' },
  'The amount that repeats goes in front of x, and the amount paid once is added on.': { style: 'B' },
  'Start with the $25. You pay it one time, when you join.': { style: 'B' },
  'So at 0 months, before any month has gone by, you have already paid $25.': { style: 'B' },
  'Now the part that repeats. Every month adds another $10.': { style: 'B' },
  'So x months add 10 times x, and we write that as 10x.': { style: 'B', say: 'So x months add 10 times x, and we write that as 10 x.' },
  'Does it work? Try 3 months. 10 × 3 = 30, and 30 + 25 = 55.': { style: 'B' },
  'Now put the two pieces together. The cost is 10 times the months, plus 25.': { style: 'B' },
  'With y for the cost and x for the months, that is y = 10x + 25.': { style: 'B', say: 'With y for the cost and x for the months, that is y equals 10 x plus 25.' },
  'And 24 months? 10 × 24 + 25 = 265. One line, and it is done.': { style: 'B' },
  "Don't MULTIPLY the $25 by the months.": { style: 'B+' },
  'You pay the $25 once, so it is added on. The $10 is what repeats, so 10 goes in front of x.': { style: 'B+' },
  'You put the $8 that repeats in front of x and added the $15 paid once.': { style: 'A', say: 'You put the 8 dollars that repeat in front of x and added the 15 dollars paid once.' },
  'The 2 feet repeat each year and the 4 feet are the start, so y = 2x + 4.': { style: 'A', say: 'The 2 feet repeat each year and the 4 feet are the start, so y equals 2 x plus 4.' },
  // ── g8m3-t6 ──
  'There is no rule here to put numbers into.': { style: 'B' },
  'So how can a graph tell a story?': { style: 'B' },
  'You read its shape, one piece at a time.': { style: 'B' },
  'Read the graph from left to right, where up means growing, down means shrinking, and flat means staying the same.': { style: 'B' },
  'Start at the left. From hour 0 to hour 2, the graph climbs to 6 miles.': { style: 'B' },
  'What does that mean for Sam?': { style: 'B' },
  'His distance from home is growing, so he is riding away.': { style: 'B' },
  'Next piece. From hour 2 to hour 4, the graph stays flat at 6 miles.': { style: 'B' },
  'Is Sam getting any farther from home? No.': { style: 'B' },
  'His distance is not changing, so he has stopped for a rest.': { style: 'B' },
  'From hour 4 to hour 6 it climbs again, but only 2 miles.': { style: 'B' },
  'From hour 0 to hour 2 it climbed 6. Steeper means faster.': { style: 'B' },
  'Then from hour 6 to hour 10 it goes down to 0, because Sam is riding home.': { style: 'B' },
  'The graph is NOT a picture of a hill.': { style: 'B+' },
  'Going down does not mean Sam rides downhill. It means he is getting closer to home.': { style: 'B+' },
}
