/**
 * How g8m4's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G8M4_VOICE: Record<string, VoiceLine> = {
  // ── g8m4-t6 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Can you climb up and measure that top corner?": { style: 'B' },
  "Not really. It is way up on the roof, and nobody is holding a protractor up there.": { style: 'B' },
  "So we need a rule that finds the angle without measuring it at all.": { style: 'B' },
  "The three angles inside a triangle always add to 180°, so the angle outside a corner equals the two far inside angles added.": { style: 'B' },
  "Here is something you can try with paper.": { style: 'B' },
  "Tear the three corners off a paper triangle, then push their points together.": { style: 'B' },
  "They line up. Every time, they make one straight line, and a straight line is 180°.": { style: 'B' },
  "So back to the roof. Add the two angles you know, 50 + 60 = 110.": { style: 'B' },
  "How much is left over out of 180? 180 − 110 = 70.": { style: 'B' },
  "The top angle is 70°.": { style: 'B' },
  "Now stretch the bottom side out past the 60° corner.": { style: 'B', say: "Now stretch the bottom side out past the 60 degree corner." },
  "The angle that opens up outside is 180 − 60 = 120°.": { style: 'B' },
  "Look. That is exactly the two far angles added together, 50 + 70 = 120.": { style: 'B' },
  "Don't STOP at 50 + 60 = 110.": { style: 'B+' },
  "That is two angles together, not the third one. Take it away from 180°, and you get 70°.": { style: 'B+' },
  // ── g8m4-t7 ──
  "Can you just add them? 4 + 3 = 7.": { style: 'B' },
  "But 7 is the walk along two edges, the long way around the corner.": { style: 'B' },
  "The path straight across cuts the corner off, so it has to be shorter than 7.": { style: 'B' },
  "In a right triangle, square the two short sides and add them, and you get the square of the long side.": { style: 'B' },
  "Watch this. Draw a square out from each side of the triangle.": { style: 'B' },
  "The square on the 3 side holds 3 × 3 = 9 little squares.": { style: 'B' },
  "The one on the 4 side holds 4 × 4 = 16.": { style: 'B' },
  "Now tip those two squares into the big one on the long side.": { style: 'B' },
  "9 + 16 = 25.": { style: 'B' },
  "The big square holds exactly 25 little squares. Not one over, not one short.": { style: 'B' },
  "So the long side, squared, is 25. Which number times itself makes 25?": { style: 'B' },
  "5 × 5 = 25.": { style: 'B' },
  "So the path straight across the park is 5 blocks.": { style: 'B' },
  "Don't add the SIDES.": { style: 'B+' },
  "3 + 4 = 7 is the walk around the corner. Add their squares instead, then undo the square, and you get 5.": { style: 'B+' },
  // ── g8m4-t8 ──
  "Careful. Something has changed.": { style: 'B' },
  "Last time you knew the two short sides. This time the ladder is the long side, and you already know it.": { style: 'B' },
  "So do you add the squares again? No. That would make the wall taller than the ladder itself.": { style: 'B' },
  "When you already know the long side, take the short side's square away from the long side's square, then undo the square.": { style: 'B' },
  "Build the squares again, the same way as before.": { style: 'B' },
  "The square on the 5 meter ladder holds 5 × 5 = 25. The square on the 3 meter ground holds 3 × 3 = 9.": { style: 'B' },
  "The square on the wall is the one we are hunting for.": { style: 'B' },
  "The two small squares fill the big one exactly.": { style: 'B' },
  "So the missing square is whatever is left when you take 9 out of 25.": { style: 'B' },
  "25 − 9 = 16.": { style: 'B' },
  "Now undo the square. Which number times itself makes 16?": { style: 'B' },
  "4 × 4 = 16.": { style: 'B' },
  "So the ladder reaches 4 meters up the wall.": { style: 'B' },
  "Don't ADD when you already know the long side.": { style: 'B+' },
  "25 + 9 = 34 makes the wall taller than the ladder. Take away instead.": { style: 'B+' },
  // ── g8m4-t9 ──
  "Draw the straight path in, and look at it closely.": { style: 'B' },
  "It runs on a slant, cutting across the squares right through their middles.": { style: 'B' },
  "So can you count squares along it to get its length? No. A slant does not match the grid.": { style: 'B' },
  "Draw a right triangle between the two points, count its two short sides on the grid, then find the long side.": { style: 'B' },
  "Start at (1, 1) and go straight across, then turn and go straight up to (4, 5).": { style: 'B', say: "Start at 1, 1 and go straight across, then turn and go straight up to 4, 5." },
  "Now look at the corner where the two paths meet.": { style: 'B' },
  "It is a square corner, so what you have drawn is a right triangle.": { style: 'B' },
  "Now measure the two short sides. You can take away instead of counting.": { style: 'B' },
  "Across, 4 − 1 = 3. Up, 5 − 1 = 4.": { style: 'B' },
  "So the short sides are 3 miles and 4 miles.": { style: 'B' },
  "Now it is the same job as last time.": { style: 'B' },
  "Square them and add, 9 + 16 = 25. Which number times itself makes 25?": { style: 'B' },
  "5 × 5 = 25, so the two towns are 5 miles apart.": { style: 'B' },
  "Don't ADD the two sides.": { style: 'B+' },
  "3 + 4 = 7 is the walk along the grid lines, around the corner. The straight line is 5 miles.": { style: 'B+' },
  "Two towns on a map. Two towns are at (1, 1) and (4, 5) on a map grid. Each square is 1 mile. How far apart are they in a straight line?": { style: 'A', say: 'Two towns on a map. Two towns are at 1, 1 and 4, 5 on a map grid. Each square is 1 mile. How far apart are they in a straight line?' },
  "Now you try. How far apart are the points (2, 1) and (8, 9), in units? Find how far across and how far up. Those are the legs.": { style: 'A', say: 'Now you try. How far apart are the points 2, 1 and 8, 9, in units? Find how far across and how far up. Those are the legs.' },
  "Try a new one. How far apart are the points (1, 2) and (6, 14), in units?": { style: 'A', say: 'Try a new one. How far apart are the points 1, 2 and 6, 14, in units?' },
  "You made a right triangle from (1, 2) to (6, 14) and found its hypotenuse, 13.": { style: 'A', say: 'You made a right triangle from 1, 2 to 6, 14 and found its hypotenuse, 13.' },
}
