/**
 * How g8m4's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G8M4_VOICE: Record<string, VoiceLine> = {
  // ── g8m4-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "You could just drag it across and hope it lands right.": { style: 'B' },
  "But where exactly does it land? Hoping can't tell you.": { style: 'B' },
  "You need the new spot of every single corner.": { style: 'B' },
  "In a slide, every point moves the same distance in the same direction.": { style: 'B' },
  "Take corner A. It starts at (1, 1).": { style: 'B', say: "Take corner A. It starts at 1, 1." },
  "Move it 4 to the right, and x goes from 1 up to 5.": { style: 'B' },
  "Move it 2 up, and y goes from 1 up to 3.": { style: 'B' },
  "So A lands on (5, 3). We call that new point A prime.": { style: 'B', say: "So A lands on 5, 3. We call that new point A prime." },
  "The other two corners do the same thing.": { style: 'B' },
  "B at (3, 1) goes to (7, 3). C at (1, 3) goes to (5, 5).": { style: 'B', say: "B at 3, 1 goes to 7, 3. C at 1, 3 goes to 5, 5." },
  "Every corner went 4 right and 2 up.": { style: 'B' },
  "Nothing stretched and nothing turned, so it is the same triangle, just moved.": { style: 'B' },
  "Is there a rule that works for every point? Yes.": { style: 'B' },
  "Right adds to x, and left takes away from x.": { style: 'B' },
  "Up adds to y, and down takes away from y.": { style: 'B' },
  "So for 4 right and 2 up, every point (x, y) becomes (x + 4, y + 2).": { style: 'B', say: "So for 4 right and 2 up, every point x, y becomes x + 4, y + 2." },
  "Don't add the right move to y. Right and left change x, the FIRST number.": { style: 'B+' },
  "Up and down change y, the second one.": { style: 'B+' },
  "So 4 right and 2 up takes (1, 1) to (5, 3). Not to (3, 5).": { style: 'B+', say: "So 4 right and 2 up takes 1, 1 to 5, 3. Not to 3, 5." },
  "Now you try. Point A is at (2, 1). The triangle slides 5 right and 3 up. What is the x-coordinate of A′? Right and left change x. Up and down change y.": { style: 'A', say: "Now you try. Point A is at 2, 1. The triangle slides 5 right and 3 up. What is the x-coordinate of A prime? Right and left change x. Up and down change y." },
  "Try a new one. Point B is at (6, 5). The triangle slides 4 left and 2 down. What is the y-coordinate of B′?": { style: 'A', say: "Try a new one. Point B is at 6, 5. The triangle slides 4 left and 2 down. What is the y-coordinate of B prime?" },
  // ── g8m4-t2 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Could we just slide the triangle straight down?": { style: 'B' },
  "Look. It comes out the same way up.": { style: 'B' },
  "But the picture in the water is upside down, so a slide can't make it.": { style: 'B' },
  "Flip over the x-axis and the y changes sign, flip over the y-axis and the x changes sign.": { style: 'B' },
  "Look at corner A, at (2, 1). It sits 1 square above the x-axis.": { style: 'B', say: "Look at corner A, at 2, 1. It sits 1 square above the x-axis." },
  "Its picture sits 1 square below, straight down. Same distance, other side.": { style: 'B' },
  "So A at (2, 1) becomes A′ at (2, −1).": { style: 'B', say: "So A at 2, 1 becomes A prime at 2, −1." },
  "The other corners do the same.": { style: 'B' },
  "B at (4, 1) drops to (4, −1). C at (2, 3) drops to (2, −3).": { style: 'B', say: "B at 4, 1 drops to 4, −1. C at 2, 3 drops to 2, −3." },
  "Look down the list. Every x stayed the same, and every y flipped its sign.": { style: 'B' },
  "Now flip the same triangle the other way, over the y-axis.": { style: 'B' },
  "It swings across to the left. A at (2, 1) lands on (−2, 1).": { style: 'B', say: "It swings across to the left. A at 2, 1 lands on −2, 1." },
  "This time y stays put, and it is x that changes sign.": { style: 'B' },
  "A flip over the x-axis does NOT change x.": { style: 'B+' },
  "The point moves straight down, so only the y changes.": { style: 'B+' },
  "So (2, 1) becomes (2, −1), not (−2, 1).": { style: 'B+', say: "So 2, 1 becomes 2, −1, not −2, 1." },
  "Now you try. Point A is at (3, 2). The triangle flips over the x-axis. What is the y-coordinate of A′? Over the x-axis, the y changes sign. Over the y-axis, the x changes sign.": { style: 'A', say: "Now you try. Point A is at 3, 2. The triangle flips over the x-axis. What is the y-coordinate of A prime? Over the x-axis, the y changes sign. Over the y-axis, the x changes sign." },
  "Try a new one. Point B is at (4, −3). The triangle flips over the y-axis. What is the x-coordinate of B′?": { style: 'A', say: "Try a new one. Point B is at 4, −3. The triangle flips over the y-axis. What is the x-coordinate of B prime?" },
  // ── g8m4-t3 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Can we just count squares, like a slide?": { style: 'B' },
  "No. Each corner swings around (0, 0) on its own circle.": { style: 'B', say: "No. Each corner swings around the point 0, 0 on its own circle." },
  "A corner far from the center travels farther than a close one, so no single count works.": { style: 'B' },
  "A quarter turn counterclockwise around (0, 0) sends (x, y) to (−y, x).": { style: 'B', say: "A quarter turn counterclockwise around the point 0, 0 sends x, y to negative y, x." },
  "Follow corner A, at (3, 1). That is 3 right and 1 up from the center.": { style: 'B', say: "Follow corner A, at 3, 1. That is 3 right and 1 up from the center." },
  "Turn that arm a quarter turn, the way a clock hand goes backward.": { style: 'B' },
  "Now it points 1 left and 3 up. So A′ is at (−1, 3).": { style: 'B', say: "Now it points 1 left and 3 up. So A prime is at −1, 3." },
  "Look at what happened to the numbers.": { style: 'B' },
  "They swapped places, and then the new first number changed sign.": { style: 'B' },
  "Check B. (4, 1) swaps to (1, 4), and the sign change gives (−1, 4).": { style: 'B', say: "Check B. 4, 1 swaps to 1, 4, and the sign change gives −1, 4." },
  "C at (3, 3) goes to (−3, 3). Same rule.": { style: 'B', say: "C at 3, 3 goes to −3, 3. Same rule." },
  "Now turn twice as far, until the board faces the other way.": { style: 'B' },
  "That is a half turn, 180°.": { style: 'B' },
  "Nothing swaps this time. Both signs change.": { style: 'B' },
  "So A at (3, 1) goes to (−3, −1).": { style: 'B', say: "So A at 3, 1 goes to −3, −1." },
  "Don't just swap the numbers and STOP.": { style: 'B+' },
  "A swap is only half the job.": { style: 'B+' },
  "Change the sign of the new first number, so (3, 1) goes to (−1, 3).": { style: 'B+', say: "Change the sign of the new first number, so 3, 1 goes to −1, 3." },
  "Spin the board. A triangle is drawn on a board pinned at (0, 0). The board turns a quarter turn counterclockwise. Where does the triangle land?": { style: 'A', say: "Spin the board. A triangle is drawn on a board pinned at the point 0, 0. The board turns a quarter turn counterclockwise. Where does the triangle land?" },
  "Now you try. Point A is at (4, 2). The triangle turns a quarter turn counterclockwise around (0, 0). What is the x-coordinate of A′? Swap the two numbers. Then change the sign of the new first number.": { style: 'A', say: "Now you try. Point A is at 4, 2. The triangle turns a quarter turn counterclockwise around the point 0, 0. What is the x-coordinate of A prime? Swap the two numbers. Then change the sign of the new first number." },
  "Try a new one. Point B is at (3, −5). The triangle makes a half turn around (0, 0). What is the y-coordinate of B′?": { style: 'A', say: "Try a new one. Point B is at 3, −5. The triangle makes a half turn around the point 0, 0. What is the y-coordinate of B prime?" },
  "After a quarter turn, which number of (4, 2) moves into the first place?": { style: 'A', say: "After a quarter turn, which number of 4, 2 moves into the first place?" },
  // ── g8m4-t4 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "What if we just add 2 to every number?": { style: 'B' },
  "Look. The triangle only slides over. It is the same size as before.": { style: 'B' },
  "But we want every side twice as long.": { style: 'B' },
  "To stretch a shape from (0, 0), multiply both coordinates of every point by the same number.": { style: 'B', say: "To stretch a shape from the point 0, 0, multiply both coordinates of every point by the same number." },
  "Start with corner A, at (2, 1).": { style: 'B', say: "Start with corner A, at 2, 1." },
  "Multiply both numbers by 2, and you get (4, 2).": { style: 'B', say: "Multiply both numbers by 2, and you get 4, 2." },
  "A′ lands on the same straight line out from (0, 0), just twice as far along it.": { style: 'B', say: "A prime lands on the same straight line out from the point 0, 0, just twice as far along it." },
  "Do the same to the other two.": { style: 'B' },
  "B at (4, 1) doubles to (8, 2). C at (2, 3) doubles to (4, 6).": { style: 'B', say: "B at 4, 1 doubles to 8, 2. C at 2, 3 doubles to 4, 6." },
  "Now measure a side. The bottom was 2 squares long, and now it is 4.": { style: 'B' },
  "Every side is twice as long.": { style: 'B' },
  "Can the same move shrink a shape? Yes.": { style: 'B' },
  "Multiply by 1/2, and (8, 2) goes right back to (4, 1).": { style: 'B', say: "Multiply by 1/2, and 8, 2 goes right back to 4, 1." },
  "A number bigger than 1 grows the shape. A number smaller than 1 shrinks it.": { style: 'B' },
  "Twice as big does NOT mean add 2.": { style: 'B+' },
  "Adding 2 to (2, 1) gives (4, 3), and that only slides it.": { style: 'B+', say: "Adding 2 to 2, 1 gives 4, 3, and that only slides it." },
  "Multiply both numbers, so (2, 1) becomes (4, 2).": { style: 'B+', say: "Multiply both numbers, so 2, 1 becomes 4, 2." },
  "Make the photo bigger. You make a triangle picture twice as big, and the corner (0, 0) stays put. Where do the triangle's corners go?": { style: 'A', say: "Make the photo bigger. You make a triangle picture twice as big, and the corner at 0, 0 stays put. Where do the triangle's corners go?" },
  "Now you try. Point A is at (3, 1). The triangle is stretched from (0, 0), multiplying by 2. What is the x-coordinate of A′? Multiply both coordinates by the stretch number.": { style: 'A', say: "Now you try. Point A is at 3, 1. The triangle is stretched from the point 0, 0, multiplying by 2. What is the x-coordinate of A prime? Multiply both coordinates by the stretch number." },
  "Try a new one. Point B is at (2, 4). The triangle is stretched from (0, 0), multiplying by 3. What is the y-coordinate of B′?": { style: 'A', say: "Try a new one. Point B is at 2, 4. The triangle is stretched from the point 0, 0, multiplying by 3. What is the y-coordinate of B prime?" },
  "Which number of (2, 4) is the y-coordinate?": { style: 'A', say: "Which number of 2, 4 is the y-coordinate?" },
  // ── g8m4-t5 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Did every side just grow by the same amount? Let's test it.": { style: 'B' },
  "The bottom went from 4 to 8. That is 4 more.": { style: 'B' },
  "But the 3 foot side went to 6, and that is only 3 more.": { style: 'B' },
  "Different amounts, so adding is not what happened.": { style: 'B' },
  "Triangles with the same angles have every side multiplied by the same number.": { style: 'B' },
  "Look at the corners first, not the sides.": { style: 'B' },
  "Each corner of the big sign has the same angle as a corner of the small one.": { style: 'B' },
  "So each big side matches the small side in the same place.": { style: 'B' },
  "Pick a pair where you know both sides, the bottoms, 4 and 8.": { style: 'B' },
  "8 ÷ 4 = 2, so the big side is 2 times as long.": { style: 'B' },
  "Check a second pair. 3 × 2 = 6, and the big sign says 6.": { style: 'B' },
  "Now the side we came for.": { style: 'B' },
  "It matches the 2 foot side on the small sign.": { style: 'B' },
  "So 2 × 2 = 4. The missing side is 4 feet.": { style: 'B' },
  "Don't ADD the difference you saw.": { style: 'B+' },
  "2 + 4 = 6 feet gives a sign with a different shape.": { style: 'B+' },
  "Multiply by 2 every time, so 2 × 2 = 4 feet.": { style: 'B+' },
  // ── g8m4-t6 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Can you climb up and measure that top corner?": { style: 'B' },
  "Not really. It is way up on the roof, and nobody is holding a protractor up there.": { style: 'B' },
  "So we need a rule that finds the angle without measuring it at all.": { style: 'B' },
  "The three angles inside a triangle always add to 180°, so the angle outside a corner equals the two far inside angles added.": { style: 'B' },
  "Here is something you can try with paper.": { style: 'B' },
  "Tear the three corners off a paper triangle, then push their points together.": { style: 'B' },
  "They line up. Every time, they make one straight line, and a straight line is 180°.": { style: 'B' },
  "So back to the roof. Add the two angles you know, 50 + 60 = 110.": { style: 'B' },
  "How much is left over out of 180? 180 − 110 = 70.": { style: 'B' },
  "The top angle is 70°.": { style: 'B' },
  "Now stretch the bottom side out past the 60° corner.": { style: 'B', say: "Now stretch the bottom side out past the 60 degree corner." },
  "The angle that opens up outside is 180 − 60 = 120°.": { style: 'B' },
  "Look. That is exactly the two far angles added together, 50 + 70 = 120.": { style: 'B' },
  "Don't STOP at 50 + 60 = 110.": { style: 'B+' },
  "That is two angles together, not the third one. Take it away from 180°, and you get 70°.": { style: 'B+' },
  // ── g8m4-t7 ──
  "Can you just add them? 4 + 3 = 7.": { style: 'B' },
  "But 7 is the walk along two edges, the long way around the corner.": { style: 'B' },
  "The path straight across cuts the corner off, so it has to be shorter than 7.": { style: 'B' },
  "In a right triangle, square the two short sides and add them, and you get the square of the long side.": { style: 'B' },
  "Watch this. Draw a square out from each side of the triangle.": { style: 'B' },
  "The square on the 3 side holds 3 × 3 = 9 little squares.": { style: 'B' },
  "The one on the 4 side holds 4 × 4 = 16.": { style: 'B' },
  "Now tip those two squares into the big one on the long side.": { style: 'B' },
  "9 + 16 = 25.": { style: 'B' },
  "The big square holds exactly 25 little squares. Not one over, not one short.": { style: 'B' },
  "So the long side, squared, is 25. Which number times itself makes 25?": { style: 'B' },
  "5 × 5 = 25.": { style: 'B' },
  "So the path straight across the park is 5 blocks.": { style: 'B' },
  "Don't add the SIDES.": { style: 'B+' },
  "3 + 4 = 7 is the walk around the corner. Add their squares instead, then undo the square, and you get 5.": { style: 'B+' },
  // ── g8m4-t8 ──
  "Careful. Something has changed.": { style: 'B' },
  "Last time you knew the two short sides. This time the ladder is the long side, and you already know it.": { style: 'B' },
  "So do you add the squares again? No. That would make the wall taller than the ladder itself.": { style: 'B' },
  "When you already know the long side, take the short side's square away from the long side's square, then undo the square.": { style: 'B' },
  "Build the squares again, the same way as before.": { style: 'B' },
  "The square on the 5 meter ladder holds 5 × 5 = 25. The square on the 3 meter ground holds 3 × 3 = 9.": { style: 'B' },
  "The square on the wall is the one we are hunting for.": { style: 'B' },
  "The two small squares fill the big one exactly.": { style: 'B' },
  "So the missing square is whatever is left when you take 9 out of 25.": { style: 'B' },
  "25 − 9 = 16.": { style: 'B' },
  "Now undo the square. Which number times itself makes 16?": { style: 'B' },
  "4 × 4 = 16.": { style: 'B' },
  "So the ladder reaches 4 meters up the wall.": { style: 'B' },
  "Don't ADD when you already know the long side.": { style: 'B+' },
  "25 + 9 = 34 makes the wall taller than the ladder. Take away instead.": { style: 'B+' },
  // ── g8m4-t9 ──
  "Draw the straight path in, and look at it closely.": { style: 'B' },
  "It runs on a slant, cutting across the squares right through their middles.": { style: 'B' },
  "So can you count squares along it to get its length? No. A slant does not match the grid.": { style: 'B' },
  "Draw a right triangle between the two points, count its two short sides on the grid, then find the long side.": { style: 'B' },
  "Start at (1, 1) and go straight across, then turn and go straight up to (4, 5).": { style: 'B', say: "Start at 1, 1 and go straight across, then turn and go straight up to 4, 5." },
  "Now look at the corner where the two paths meet.": { style: 'B' },
  "It is a square corner, so what you have drawn is a right triangle.": { style: 'B' },
  "Now measure the two short sides. You can take away instead of counting.": { style: 'B' },
  "Across, 4 − 1 = 3. Up, 5 − 1 = 4.": { style: 'B' },
  "So the short sides are 3 miles and 4 miles.": { style: 'B' },
  "Now it is the same job as last time.": { style: 'B' },
  "Square them and add, 9 + 16 = 25. Which number times itself makes 25?": { style: 'B' },
  "5 × 5 = 25, so the two towns are 5 miles apart.": { style: 'B' },
  "Don't ADD the two sides.": { style: 'B+' },
  "3 + 4 = 7 is the walk along the grid lines, around the corner. The straight line is 5 miles.": { style: 'B+' },
  "Two towns on a map. Two towns are at (1, 1) and (4, 5) on a map grid. Each square is 1 mile. How far apart are they in a straight line?": { style: 'A', say: 'Two towns on a map. Two towns are at 1, 1 and 4, 5 on a map grid. Each square is 1 mile. How far apart are they in a straight line?' },
  "Now you try. How far apart are the points (2, 1) and (8, 9), in units? Find how far across and how far up. Those are the legs.": { style: 'A', say: 'Now you try. How far apart are the points 2, 1 and 8, 9, in units? Find how far across and how far up. Those are the legs.' },
  "Try a new one. How far apart are the points (1, 2) and (6, 14), in units?": { style: 'A', say: 'Try a new one. How far apart are the points 1, 2 and 6, 14, in units?' },
  "You made a right triangle from (1, 2) to (6, 14) and found its hypotenuse, 13.": { style: 'A', say: 'You made a right triangle from 1, 2 to 6, 14 and found its hypotenuse, 13.' },
}
