/**
 * How g8m6's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G8M6_VOICE: Record<string, VoiceLine> = {
  // ── g8m6-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Can two students settle it? Look at these two.": { style: 'B' },
  "This one studied 2 hours and got 70. This one studied an hour more and got 68.": { style: 'B' },
  "So two dots can show almost anything.": { style: 'B' },
  "Read the whole cloud from left to right, and if it rises the pattern is positive, but if it falls it is negative.": { style: 'B' },
  "Now read this cloud left to right.": { style: 'B' },
  "At 1 hour the scores are 55 and 60. At 6 hours, 92.": { style: 'B' },
  "Do the scores climb as the hours go up? Yes, so this pattern is positive.": { style: 'B' },
  "Not every cloud rises. More screen time goes with less sleep.": { style: 'B' },
  "These dots fall, so the pattern is negative.": { style: 'B' },
  "And shoe size against test score? The dots are scattered everywhere.": { style: 'B' },
  "No rise and no fall means no pattern at all.": { style: 'B' },
  "Look at this one, way up here. 1 hour of study, and a score of 95.": { style: 'B' },
  "It sits far from the others. Does it change the pattern?": { style: 'B' },
  "No. Notice it, but read the whole cloud, and this cloud still rises.": { style: 'B' },
  "When the dots fall, don't call it NO pattern.": { style: 'B+' },
  "Falling dots are a pattern, a negative one. No pattern means no rise and no fall.": { style: 'B+' },
  // ── g8m6-t2 ──
  "Here is a line that rises, just like the dots. Is it a good fit?": { style: 'B' },
  "Look underneath it. All 10 dots sit below it.": { style: 'B' },
  "It rises the right way, but it misses where the students really are.": { style: 'B' },
  "A line that fits runs through the middle of the cloud, with about as many dots above it as below it.": { style: 'B' },
  "Let's build a better one. First, tilt the line the way the dots go.": { style: 'B' },
  "Then slide it down until it runs right through the middle of the cloud.": { style: 'B' },
  "Now count with me. How many dots sit above the line? 5.": { style: 'B' },
  "And below it? 5 again.": { style: 'B' },
  "5 and 5 is balanced, so this line sits right in the middle.": { style: 'B' },
  "Our line goes through (0, 50) and (6, 92). How steep is it?": { style: 'B', say: "Our line goes through the point 0, 50 and the point 6, 92. How steep is it?" },
  "The rise is 92 − 50, which is 42. The run is 6 − 0, which is 6.": { style: 'B' },
  "42 ÷ 6 is 7. So the slope is 7, about 7 more points for every extra hour.": { style: 'B' },
  "Don't pick a line JUST because it rises like the dots.": { style: 'B+' },
  "Count the dots above it and below it, and move it until they balance.": { style: 'B+' },
  "Now you try. A line fits these dots well. It passes through (0, 40) and (5, 70). What is its slope? Find the rise and the run between the two points. Then divide.": { style: 'A', say: "Now you try. A line fits these dots well. It passes through the point 0, 40 and the point 5, 70. What is its slope? Find the rise and the run between the two points. Then divide." },
  "Try a new one. A line fits the dots for weeks and plant height in cm. It passes through (2, 10) and (6, 30). What is its slope?": { style: 'A', say: "Try a new one. A line fits the dots for weeks and plant height in centimeters. It passes through the point 2, 10 and the point 6, 30. What is its slope?" },
  "How much does the line go up from (0, 40) to (5, 70)?": { style: 'A', say: "How much does the line go up from the point 0, 40 to the point 5, 70?" },
  "How much does the height go up from (2, 10) to (6, 30)?": { style: 'A', say: "How much does the height go up from the point 2, 10 to the point 6, 30?" },
  // ── g8m6-t3 ──
  "Find 6 hours along the bottom. Is there a dot to read?": { style: 'B' },
  "No. Nobody in this class studied that long.": { style: 'B' },
  "And a guess is not a plan, so we need the line itself.": { style: 'B' },
  "The line is a rule, so put the x value into its equation and the y value you get is your prediction.": { style: 'B' },
  "Where does the line start, at 0 hours? At 50.": { style: 'B' },
  "From there it climbs 5 points for every hour.": { style: 'B' },
  "So its equation is y = 5x + 50.": { style: 'B' },
  "Maya studies 6 hours, so 6 goes in for x.": { style: 'B' },
  "5 × 6 is 30. Then 30 + 50 is 80.": { style: 'B' },
  "So we predict a score of 80 for her.": { style: 'B' },
  "What do the two numbers mean?": { style: 'B' },
  "The 5 means about 5 more points for every extra hour.": { style: 'B' },
  "The 50 is where the line starts, the score at 0 hours.": { style: 'B' },
  "Don't STOP at 5 × 6. That 30 is only the extra points from studying.": { style: 'B+' },
  "Add the 50 the line starts at, and you get 80.": { style: 'B+' },
}
