/**
 * How g8m6's lines are RENDERED (docs/new-flow/voice.md). Keyed by the line EXACTLY as the lesson says it; `say` is what
 * the voice model reads (symbols spelt out, no tags, no ellipses). A line with no row renders as style A from its own text.
 */
import type { VoiceLine } from './styles'

export const G8M6_VOICE: Record<string, VoiceLine> = {
  // ── g8m6-t1 ── ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  "Can two students settle it? Look at these two.": { style: 'B' },
  "This one studied 2 hours and got 70. This one studied an hour more and got 68.": { style: 'B' },
  "So two dots can show almost anything.": { style: 'B' },
  "Read the whole cloud from left to right, and if it rises the pattern is positive, but if it falls it is negative.": { style: 'B' },
  "Now read this cloud left to right.": { style: 'B' },
  "At 1 hour the scores are 55 and 60. At 6 hours, 92.": { style: 'B' },
  "Do the scores climb as the hours go up? Yes, so this pattern is positive.": { style: 'B' },
  "Not every cloud rises. More screen time goes with less sleep.": { style: 'B' },
  "These dots fall, so the pattern is negative.": { style: 'B' },
  "And shoe size against test score? The dots are scattered everywhere.": { style: 'B' },
  "No rise and no fall means no pattern at all.": { style: 'B' },
  "Look at this one, way up here. 1 hour of study, and a score of 95.": { style: 'B' },
  "It sits far from the others. Does it change the pattern?": { style: 'B' },
  "No. Notice it, but read the whole cloud, and this cloud still rises.": { style: 'B' },
  "When the dots fall, don't call it NO pattern.": { style: 'B+' },
  "Falling dots are a pattern, a negative one. No pattern means no rise and no fall.": { style: 'B+' },
  // ── g8m6-t2 ──
  "Here is a line that rises, just like the dots. Is it a good fit?": { style: 'B' },
  "Look underneath it. All 10 dots sit below it.": { style: 'B' },
  "It rises the right way, but it misses where the students really are.": { style: 'B' },
  "A line that fits runs through the middle of the cloud, with about as many dots above it as below it.": { style: 'B' },
  "Let's build a better one. First, tilt the line the way the dots go.": { style: 'B' },
  "Then slide it down until it runs right through the middle of the cloud.": { style: 'B' },
  "Now count with me. How many dots sit above the line? 5.": { style: 'B' },
  "And below it? 5 again.": { style: 'B' },
  "5 and 5 is balanced, so this line sits right in the middle.": { style: 'B' },
  "Our line goes through (0, 50) and (6, 92). How steep is it?": { style: 'B', say: "Our line goes through the point 0, 50 and the point 6, 92. How steep is it?" },
  "The rise is 92 − 50, which is 42. The run is 6 − 0, which is 6.": { style: 'B' },
  "42 ÷ 6 is 7. So the slope is 7, about 7 more points for every extra hour.": { style: 'B' },
  "Don't pick a line JUST because it rises like the dots.": { style: 'B+' },
  "Count the dots above it and below it, and move it until they balance.": { style: 'B+' },
  "Now you try. A line fits these dots well. It passes through (0, 40) and (5, 70). What is its slope? Find the rise and the run between the two points. Then divide.": { style: 'A', say: "Now you try. A line fits these dots well. It passes through the point 0, 40 and the point 5, 70. What is its slope? Find the rise and the run between the two points. Then divide." },
  "Try a new one. A line fits the dots for weeks and plant height in cm. It passes through (2, 10) and (6, 30). What is its slope?": { style: 'A', say: "Try a new one. A line fits the dots for weeks and plant height in centimeters. It passes through the point 2, 10 and the point 6, 30. What is its slope?" },
  "How much does the line go up from (0, 40) to (5, 70)?": { style: 'A', say: "How much does the line go up from the point 0, 40 to the point 5, 70?" },
  "How much does the height go up from (2, 10) to (6, 30)?": { style: 'A', say: "How much does the height go up from the point 2, 10 to the point 6, 30?" },
  // ── g8m6-t3 ──
  "Find 6 hours along the bottom. Is there a dot to read?": { style: 'B' },
  "No. Nobody in this class studied that long.": { style: 'B' },
  "And a guess is not a plan, so we need the line itself.": { style: 'B' },
  "The line is a rule, so put the x value into its equation and the y value you get is your prediction.": { style: 'B' },
  "Where does the line start, at 0 hours? At 50.": { style: 'B' },
  "From there it climbs 5 points for every hour.": { style: 'B' },
  "So its equation is y = 5x + 50.": { style: 'B' },
  "Maya studies 6 hours, so 6 goes in for x.": { style: 'B' },
  "5 × 6 is 30. Then 30 + 50 is 80.": { style: 'B' },
  "So we predict a score of 80 for her.": { style: 'B' },
  "What do the two numbers mean?": { style: 'B' },
  "The 5 means about 5 more points for every extra hour.": { style: 'B' },
  "The 50 is where the line starts, the score at 0 hours.": { style: 'B' },
  "Don't STOP at 5 × 6. That 30 is only the extra points from studying.": { style: 'B+' },
  "Add the 50 the line starts at, and you get 80.": { style: 'B+' },
  // ("Here's the part people mix up." and "Okay. Your turn." are g5m1's rows)
  // ── g8m6-t4 ──
  "Here is what we know so far.": { style: 'B' },
  "27 students like pizza, and 20 students are in grade 7.": { style: 'B' },
  "So how many grade 7 students like pizza? Those two counts cannot tell you.": { style: 'B' },
  "Put one question in the rows and one in the columns, so each box counts the people who fit both.": { style: 'B' },
  "Let's fill one box together.": { style: 'B' },
  "12 students are in grade 7 and they like pizza.": { style: 'B' },
  "Where does that 12 go? Right where the Grade 7 row meets the Likes pizza column.": { style: 'B' },
  "Now check each row. It has to add up to its own total.": { style: 'B' },
  "In grade 7, 12 and 8 make 20.": { style: 'B' },
  "In grade 8, 15 and 5 make 20 as well.": { style: 'B' },
  "Does it work going down, too? Yes.": { style: 'B' },
  "Down the Likes pizza column, 12 and 15 make 27.": { style: 'B' },
  "Down the Does not column, 8 and 5 make 13.": { style: 'B' },
  "And 27 and 13 make 40, the same 40 you get from 20 and 20.": { style: 'B' },
  "Don't ADD a row total to a column total.": { style: 'B+' },
  "The 12 grade 7 pizza fans are in both, so they get counted twice.": { style: 'B+' },
  "Add the two row totals instead. 20 and 20 make all 40.": { style: 'B+' },
  // ── g8m6-t5 ──
  "15 is more than 12, sure. But look at the row totals.": { style: 'B' },
  "Grade 8 has 30 students, and grade 7 has only 20.": { style: 'B' },
  "So is 15 out of 30 really more than 12 out of 20? The counts alone cannot tell us.": { style: 'B' },
  "Divide each count by the total of its own group, and then groups of different sizes compare fairly.": { style: 'B' },
  "Start with grade 7. 12 of their 20 students like pizza.": { style: 'B' },
  "Divide 12 by 20 and you get 0.6.": { style: 'B', say: "Divide 12 by 20 and you get zero point six." },
  "That is 60 out of every 100, so 60%.": { style: 'B' },
  "Now grade 8. 15 of their 30 students like pizza.": { style: 'B' },
  "Divide 15 by 30 and you get 0.5, or 50%.": { style: 'B', say: "Divide 15 by 30 and you get zero point five, or 50 percent." },
  "So which grade likes pizza more? Grade 7, even though its count was smaller.": { style: 'B' },
  "Here is a different question. Of the students who like pizza, what part are in grade 7?": { style: 'B' },
  "Now we divide by the Likes pizza column total, 27.": { style: 'B' },
  "So it is 12 out of 27, which simplifies to 4/9.": { style: 'B', say: "So it is 12 out of 27, which simplifies to four ninths." },
  "When the question asks about grade 7 students, don't divide by ALL 50 students.": { style: 'B+' },
  "Divide by the Grade 7 row total, 20, and you get 60%.": { style: 'B+' },
}
